### ISSUE TITLE
.log file name is always the same 

### ISSUE THREAD

**Issue by iammelea** [solana-labs/solana#10004]
the logs file name is always the same and rewrite the previous one after restarting the node

In previous versions every time I restart the node, I get a different file name for the logs in order with dates, in this way I can reload my node without losing my logs.

for example

before

solana-validator-BSF2yD9mqzaixDaLEraF1en82EWaXx7wbaCqSuKppqG5-20200424-044627.log

stop , start

solana-validator-BSF2yD9mqzaixDaLEraF1en82EWaXx7wbaCqSuKppqG5-20200424-044627.log
solana-validator-BSF2yD9mqzaixDaLEraF1en82EWaXx7wbaCqSuKppqG5-20200511-045960.log 

The result is that I get another .logs file without losing the previous one, and this is the best.

now this last versions every time restart the node, there is no creation of a new log file name 

solana-validator-BSF2yD9mqzaixDaLEraF1en82EWaXx7wbaCqSuKppqG5.log

and can cause the loss of logs if I do not take this into account.

**Comment by mvines** [comment]
@iammelea - The log file is appended to, not truncated, if it already exists so I don't think there should be any information loss on restart.    

I don't have a super strong opinion about re-introducing the timestamp in the log filename by default.   For our nodes here I'm now using a single log file with logrotate:
```
$ cat /etc/logrotate.d/sol 
/home/sol/solana-validator.log {
  rotate 7
  daily
  missingok
  postrotate
    systemctl kill -s USR1 sol.service
  endscript
}
```
