### ISSUE TITLE
Default --limit-ledger-size doesn't seem to actually limit to ~400GB

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#10005]
https://github.com/solana-labs/solana/blob/fa20963b93c6aa0af9ef6ff117205f905b81d84b/core/src/ledger_cleanup_service.rs#L16-L24 advertises that the default ` --limit-ledger-size` will keep the ledger under 400GB.  

Based on mainnet-beta feedback, this does not seem to be the case.

**Comment by sakridge** [comment]
possible fix: https://github.com/solana-labs/solana/pull/10036

**Comment by mvines** [comment]
With the default `--limit-ledger-size`, I'm seeing the ledger disk usage on the solana validator nodes hover between 1TG-1.2TG

**Comment by sakridge** [comment]
From one of our machines:

```
[2020-05-19T15:28:15.312659324Z INFO  solana_core::ledger_cleanup_service] 
checking for ledger purge: max_shreds: 200000000
slots: 6643473 total_shreds: 577596682 iterate_time took 53.6s

[2020-05-19T09:17:56.861409346Z INFO  solana_core::ledger_cleanup_service] 
purge: new root: 11819765 last_purge: 0 purge_interval: 512 disk: Ok(810773235806)
```

810773235806 bytes / (577 million) = 1.4kb/shred

Actually seems like the bytes/shred assumption is fine, in this case the ledger purging thread is not keeping up with ledger growth.

The validator started with 577m shreds, and it is not purging fast enough.

**Comment by sakridge** [comment]
@mvines can we test ssd on one node to see if that helps the issue?

**Comment by mvines** [comment]
Yeah I could do that for one of the mainnet-beta API nodes soon.   Devnet's API node (`da`) is running the ledger on an SSD right now though and the Devnet validator node (`dv`) is not
