### ISSUE TITLE
Failed to open ledger database: RocksDb(Error { message: "Corruption: SST file is ahead of WALs"

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#10015]
There have been a couple reports now of this error occurring on validator restart:
> thread 'main' panicked at 'Failed to open ledger database: RocksDb(Error { message: "Corruption: SST file is ahead of WALs" })', core/src/validator.rs:599:9

One full backtrace at https://pastebin.com/raw/dnapUSmB

**Comment by mvines** [comment]
This might occur as a side-effect of running out of disk space

**Comment by kwunyeung** [comment]
Just got the same error. The node died but failed to restart. It's `v1.1.18` on mainnet beta. Here is the log https://pastebin.com/txLH6D4L

**Comment by t-nelson** [comment]
We caught this issue on `ba3` Saturday morning.  Ledger and log were copied to `ledger-sst_ahead_of_wal-20200628T10:35:00*` before restarting.

Original failure _is_ a `No space left on device` however, the volume in question was ~30% free by the time I got to it.

**Comment by brianlong** [comment]
Ditto. I saw the same errors when it appeared like I had free space on the device.

**Comment by t-nelson** [comment]
Inode usage, reserved space and fragmentation all look fine :confused:

**Comment by sakridge** [comment]
Thinking we should just plumb through the wal recovery modes to the validator:

https://docs.rs/rocksdb/0.14.0/rocksdb/struct.Options.html#method.set_wal_recovery_mode

Likely TolerateCorruptedTailRecords would allow the validator to open the ledger and then it can fetch the missing shreds from the network again.

**Comment by sakridge** [comment]
Wonder if our WAL size changes have something to do with this.

**Comment by mvines** [comment]
I think this issue first manifested before we started tuning the WAL size

**Comment by ryoqun** [comment]
for your information, we're revisiting this at https://github.com/solana-labs/solana/issues/17000#issuecomment-834597070
