### ISSUE TITLE
RPC: getConfirmedBlock doesn't include collected rent

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#10085]
#### Problem
Rent collection happens when accounts are newly created as well as at epoch boundaries (through eager rent collection). Currently, the rent dues are not included in `getConfirmedBlock` and so clients have no idea that they were collected (unless they calculate them).

#### Proposed Solution
Either add (account, rent) to the `rewards` object (treat as negative rewards) OR add a new object for `rent`.

**Comment by CriesofCarrots** [comment]
Hey hey, It does now! #17504 and (txs) #17528
