### ISSUE TITLE
RPC: Not possible to query for account reward/rent history

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#10087]
#### Problem
The RPC API doesn't provide a way to query for the rewards received to / rent collected from accounts. This is a problem because the explorer should show the full history of account changes and rewards / rent take place at block granularity (rather than transaction granularity).

#### Proposed Solution
Create a new RPC method that returns a list of objects `{blockhash, rewards}` for an account, where each blockhash represents a block in which the account received rewards or paid rent dues.

**Comment by CriesofCarrots** [comment]
RPC does now return rewards history via the `getInflationReward` endpoint. All accounts are now rent-exempt, so the rent aspect of this issue is no longer relevant.
