### ISSUE TITLE
Rent should only be collected per block (not per transaction)

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#10088]
#### Problem
Rent is a protocol thing that happens to accounts outside of transactions but currently is closely tied to account creation transactions. This is an issue for a few reasons:
1. Accounts could be charged rent more than once per block (if created / destroyed / created again)
2. Rent affects the `postBalance` field in stored transaction status metadata and this effect is not currently transparent to clients (see: https://github.com/solana-labs/explorer/issues/118)
3. Tying rent collection to transactions is inconsistent with how eager rent collection works (per block) 

#### Proposed Solution
Instead of collecting rent during each transaction which creates accounts, wait to collect rent from newly created accounts until the end of a block.

**Comment by sakridge** [comment]
The end-of-block rent only collects for a subset of account keys, so you could rotate your key in a way to avoid the rent. Thus both mechanisms are needed.

**Comment by jstarry** [comment]
@sakridge I just updated the description to say "Collect rent from *newly created* accounts". Does that address your comment?

**Comment by jstarry** [comment]
It's a separate mechanism from eager rent collection
