### ISSUE TITLE
RPC: getBlockTime returns null for slot that hasn't been purged

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#10089]
#### Problem
Developers expect that `getBlockTime` will return a non-null response when the requested block is still available via `getConfimedBlock`. The reason it can return null is because we only keep the last 5 epochs of stake info and stake info is needed for calculating stake-weighted timestamp for a block.

#### Proposed Solution
Only prune epochs from `epoch_stakes` when the last slot in an epoch is purged from the blockstore.

**Comment by mvines** [comment]
This problem is quite visible on mainnet-beta too:
```
$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":1, "method":"minimumLedgerSlot"}' http://api.mainnet-beta.solana.com
{"jsonrpc":"2.0","result":5481065,"id":1}
$ solana block-time 5481065
Error: Block Not Found: slot=5481065
```

**Comment by mvines** [comment]
Alternatively/additionally consider adding the block-time estimate to the results from:
* https://docs.solana.com/apps/jsonrpc-api#getconfirmedtransaction
* https://docs.solana.com/apps/jsonrpc-api#getconfirmedblock
which would probably be more compatible with a SQL-connector for longer transaction history, when we build that

**Comment by mvines** [comment]
At the same time, consider adding a block-time column in blockstore to reduce the compute performed by the `getBlockTime` RPC endpoint

**Comment by mvines** [comment]
Once https://github.com/solana-labs/solana/issues/10093 is fixed, there only needs to be a single estimated block production time as well

**Comment by mvines** [comment]
Once `blockTime` is fully added to `getConfirmedBlock`, the `getBlockTime` endpoint could be deprecated and de-documented.

**Comment by mvines** [comment]
This needs #10630 to land (cc: https://github.com/solana-labs/solana/pull/10984#pullrequestreview-446177790)

**Comment by CriesofCarrots** [comment]
Unless we add `block_time` to the `ConfirmedTransaction` struct, I'm thinking we'll want to keep the `getBlockTime` endpoint, since the explorer uses it on all `/tx` pages. Seems like unnecessary overhead to pull the whole block for this purpose. Does this sound right, @jstarry ?

**Comment by jstarry** [comment]
Yeah the current form of the confirmed block endpoint is pretty expensive. I wouldn't mind deprecating getBlockTime if we made sure to have a lighter weight confirmed block endpoint. It could exclude tx details and paginate transaction signatures via options

**Comment by zfedoran** [comment]
> Once `blockTime` is fully added to `getConfirmedBlock`, the `getBlockTime` endpoint could be deprecated and de-documented.

@mvines I apologize, I might not be up to date with all of the other issues you guys are solving for and this is an older issue so the conversation here might be outdated. 

However, my team has a need for getting just the `blockTime` without any other details. We could migrate to `getBlock`, but it seems wasteful if all we're after is the time. Is there a recommendation to migrate to `getBlock` or are we okay to keep using the `getBlockTime` endpoint?
