### ISSUE TITLE
Use assert_eq, not assert_matches, where possible

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#1010]
Following the Rule of Least Power (https://en.wikipedia.org/wiki/Rule_of_least_power), look for code such as:

```rust
assert_matches!(rv, Err(Error::CrdtError(CrdtError::NoPeers)));
```

and drop the dependency on the `matches` crate. Change them to:

```rust
assert_eq!(rv, Err(Error::CrdtError(CrdtError::NoPeers)));
```

If you see something with an underscore in it, such as:

```rust
assert_matches!(addr_parse_error(), Err(Error::AddrParse(_)));
```

That's a correct use of the `matches` crate. No update needed there.

**Comment by Atul9** [comment]
@garious I have opened up a PR for this #1031

**Comment by garious** [comment]
Depends on https://github.com/solana-labs/solana/issues/1033

**Comment by garious** [comment]
`assert_matches` is pretty handy. It works when `Eq` isn't implemented.
