### ISSUE TITLE
Airdrop failure on testnet-sanity

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#1012]
wallet sanity fails semi-regularly on the perf testnet sanity.   More timeout needed, the network is actually down, or ??

eg: https://buildkite.com/solana-labs/testnet-sanity/builds/958#c05fcf27-884b-4dea-bd51-bf35eeba4963

**Comment by mvines** [comment]
This is now probably our top testnet-sanity issue

**Comment by garious** [comment]
@mvines, @pgarg66, @CriesofCarrots, is this fixed now with Pankaj's recent timeout changes?

**Comment by mvines** [comment]
Same as #964, need to get back to a stable master dashboard before we can assess

**Comment by mvines** [comment]
Observed today in CI at https://buildkite.com/solana-labs/solana/builds/2926#07b4918d-63e9-48d9-9fc4-15ff08797779/502-558

**Comment by mvines** [comment]
https://buildkite.com/solana-labs/solana/builds/2966#1d68acba-1581-4756-835a-0c0e838831cb/552-634

**Comment by mvines** [comment]
https://buildkite.com/solana-labs/testnet-sanity/builds/1856#842ab232-6bc6-4d29-ab8e-b4938c83236b/121-260

**Comment by rob-solana** [comment]
apparently fixed by #1160
