### ISSUE TITLE
Transaction history collection from CLI

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#10149]
#### Problem
We don't have a way for accounting purposes to regularly query a list of addresses of interest and produce a digestible output format containing all transaction details those addresses were involved in.

For a single address and a single transaction, this is straightforward with
    solana transaction-history [address]
        Output: txn_sig
    solana confirm -v [txn_sig]
        Output: Full transaction details.

For accounting/finances, we need to be able to follow the tokens more easily over many accounts and transactions without parsing CLI text output or copy-pasting lots of signatures into the explorer.

#### Proposal
A CLI subcommand (or an added flag to transaction-history) that takes inputs:
slot range [default: latest root to minimum ledger slot on RPC node]

- One or more addresses
- Output file (appendable)

And outputs a .csv file with each row representing a single instruction from a transaction which impacted one or more input addresses, and columns:

- Txn signature
- Slot
- Wallclock time/date of slot
- Input address
- Type of instruction
- sender/recipient addresses
- sender/recipient balance before & after txn
- old/new signing authority

Some txn formats have more fields than others and .csv is not the most flexible format to handle this, but the easiest to work with for spreadsheet accounting.  Even if a transaction only changes the balance of an account in the amount of a transaction fee, but an account is signed over to the authority of an address of interest, this need to be captured as well.

**Comment by danpaul000** [comment]
Limiting the scope of the tooling to account types and instructions of particular interest for accounting is fine, rather than trying to capture every thing.

Account types:
 - system
 - stake

Instructions:
 - system transfer
 - stake authority changes
 - stake account create/withdraw
 - split stake

I don't think delegation/deactivation or stake rewards are needed at this time.

**Comment by mvines** [comment]
@danpaul000 - do we have enough tooling now to satisfy this issue?

**Comment by danpaul000** [comment]
Yeah, the bigtable features are fine for now.  I might work on adding direct to csv support from the bigtable output, but that should be minor at this point.  Thanks.
