### ISSUE TITLE
RPC uses base58 for large binary leading to slow response

### ISSUE THREAD

**Issue by ryoqun** [solana-labs/solana#10140]
#### Problem

RPC responses encodes `account.data` with base58:

https://github.com/solana-labs/solana/blob/ad7b113944a62e670a2277503f251ef53b0267a5/client/src/rpc_response.rs#L78

base58 isn't suited for large arbitrary-sized binary blobs. it's only for hash: https://github.com/solana-labs/solana/pull/9490#discussion_r416430038

And it's very easy to attack dos. Also, viewing program account data (which tends to be large by definition) takes long time to retrieve via RPC.

```
$ time curl -s -X POST -H 'Content-Type: application/json' -d '{"id":1,"jsonrpc":"2.0","method":"getAccountInfo","params":["SysvarS1otHistory11111111111111111111111111",{"commitment":"max"}]}' http://tds.solana.com -o - | wc -c
179217

real    0m24.143s
user    0m0.005s
sys     0m0.007s

$ time curl -s -X POST -H 'Content-Type: application/json' -d '{"id":1,"jsonrpc":"2.0","method":"getAccountInfo","params":["SysvarRecentB1ockHashes11111111111111111111",{"commitment":"max"}]}' http://tds.solana.com -o - | wc -c
8389

real    0m0.377s
user    0m0.005s
sys     0m0.005s

$ time curl -s -X POST -H 'Content-Type: application/json' -d '{"id":1,"jsonrpc":"2.0","method":"getAccountInfo","params":["SysvarC1ock11111111111111111111111111111111",{"commitment":"max"}]}' http://tds.solana.com -o - | wc -c
239

real    0m0.304s
user    0m0.002s
sys     0m0.010s

```

As predicted theoretically, this is quadratic time increase to the size of account.data:

```
$ pry
[9] pry(main)> 179217.0 / 8389
=> 21.363332935987604
[11] pry(main)> (377 - 304) * 21.363332935987604 ** 2
=> 33316.615571771246    # =~ 24.143s
```

#### Proposed Solution

Use base64? But compat... ;)

FYI: @CriesofCarrots 

Discovered via #9490.

**Comment by mvines** [comment]
This would likely reduce the load on our RPC servers significantly.

**Comment by garious** [comment]
If a new API endpoint because we want a new encoding, why base64 and not unicode via `String::from_utf8`?

**Comment by garious** [comment]
For this endpoint, how about we return an error for large accounts, and perhaps that error includes a hash of the account data?

**Comment by mvines** [comment]
I was thinking of allowing the caller to supply their preferred encoding as an option to some of the existing RPC methods

**Comment by garious** [comment]
Umm, so caller has the option to DOS?

**Comment by mvines** [comment]
Imposing a max response length for base58 at the same time would solve that and allow for a smooth migration.  Large base58 response already take forever or time out already.  Run `solana account TokenSVp5gheXUvJ6jGWGeCsgPKgnE3YgdGKRVCMY9o`, ~10 seconds to respond in base58

**Comment by garious** [comment]
Got it, yeah, perfect

**Comment by mvines** [comment]
Priority here should be on adding an optional user-provided encoding to `getAccountInfo` to improve response time.  Streamlining the other RPC methods that return base58 can be secondary
