### ISSUE TITLE
Update tokio from 0.1.x to 1.x with async fn

### ISSUE THREAD

**Issue by ryoqun** [solana-labs/solana#10187]
#### Problem

Our tokio version 0.1.22 is [old (July 4, 2019)](https://crates.io/crates/tokio/versions). And the tokio 0.2 was released half a year ago. Also, some time also passed since the stable release of rust's `async fn`.

Maybe time has matured?

We'll be behind the rest of rust ecosystem in near future. It looks like the 0.1 tokio branch is still maintained https://github.com/tokio-rs/tokio/commits/v0.1.x but when they finally stops that, we won't promptly be able to react to security vulnerabilities.

Well, I've just noticed we neglecting dependabot regarding this: https://github.com/solana-labs/solana/pulls?q=is%3Apr+is%3Aclosed+label%3Adependencies+%22bump+tokio+from+0.1.22%22+

#### Proposed Solution

Update it. At quick look, the migration is tough....

Also, tokio blocks update of bytes from 0.4.12 to 0.5.4 as well: https://github.com/solana-labs/solana/pulls?q=is%3Apr+is%3Aclosed+label%3Adependencies+%22bump+bytes+from+0.4.12%22+

**Comment by mvines** [comment]
We're stuck on tokio 0.1 in some parts of the tree because the json-rpc crates embed tokio 0.1 structs in their public interface :-/

**Comment by mvines** [comment]
I've have net-utils now ported to tokio v0.3, will PR it later today

**Comment by mvines** [comment]
This is blocked on tarpc upgrading to tokio 1.0.   Looks close, https://github.com/google/tarpc/pull/337 just needs to ship to crates.io

**Comment by CriesofCarrots** [comment]
Re jsonrpc, bump to tokio v0.2 in progress: https://github.com/paritytech/jsonrpc/pull/603

**Comment by mvines** [comment]
Once tonic upgrades to a newer tokio than 2.5 (see https://github.com/solana-labs/solana/pull/14367), revert https://github.com/solana-labs/solana/pull/14367

**Comment by mvines** [comment]
We made some good progress towards this in the 1.5 timeframe but some dependencies are still dragging us down.  Worth having another go at this in the late Jan timeframe once other projects update

**Comment by CriesofCarrots** [comment]
Looks like Tonic 0.4 is out with tokio 1.0: https://github.com/hyperium/tonic/pull/538/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed

Paritytech/jsonrpc 17.0 crates are out with tokio 0.2: eg https://crates.io/crates/jsonrpc-http-server

**Comment by mvines** [comment]
> Paritytech/jsonrpc 17.0 crates are out with tokio 0.2: eg https://crates.io/crates/jsonrpc-http-server

Sweet, I can drop my local `[patch]` then!  I'm picking on failing unit tests with the new jsonrpc but it all builds at least :)

**Comment by CriesofCarrots** [comment]
I was curious whether dependabot would catch these, but looks like no. I'm going to take a crack at updating jsonrpc and tonic today

**Comment by CriesofCarrots** [comment]
@mvines , if you would share your branch, that would be great! I'll pull it in to mind; I have the tonic update pretty close.
Incidentally, what were the failures you saw leading to #14367? Want to make sure those are squashed.

**Comment by mvines** [comment]
My branch is at https://github.com/mvines/solana/tree/jsonrpc-16.0.0
* Top commit is rando hacks as I was trying to debug the RPC failure
* Second commit is pretty clean
* Third commit is Cargo.toml patches that probably can be reverted now that 17.0.0 has shipped

**Comment by mvines** [comment]
> Incidentally, what were the failures you saw leading to #14367? Want to make sure those are squashed on revert.

The RPC invocation of BigTable methods was totally broken
