### ISSUE TITLE
Block time on devnet often longer than 400ms

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#10196]
#### Problem

Blocktime on devnet often 600ms

#### Proposed Solution

Debug and fix.

**Comment by ryoqun** [comment]
My guess is it's related to the number of alive appendvecs...

**Comment by ryoqun** [comment]
Hmm, not definitely convinced; but it seems some correlation between the two:

![Screenshot from 2020-05-23 20-25-26](https://user-images.githubusercontent.com/117807/82729605-d1626180-9d33-11ea-9462-38eacd23b12b.png)
