### ISSUE TITLE
Bpf program execution slower than it could be

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#10195]
#### Problem

Seems there is some extra work done in the execution of a bpf program. The break program runs in 500us, @jackcmay said "We can cut out the verify and relocate and save 32us and 137us respectively"

#### Proposed Solution

Reduce code in the critical execution path.

**Comment by mvines** [comment]
@jackcmay - wdyt, do we call this one done with the cached executor work?

**Comment by mvines** [comment]
Calling this done.   We can create new issues for future optimizations
