### ISSUE TITLE
Add a comprehensive unit test for compute_broadcast_table()

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#1020]
Looks like there's no I/O, lots of branches, and if it contained a bug, it'd be an expensive one to debug!

**Comment by garious** [comment]
@pgarg66, can you update or close this one. Looks like this function has had some name changes (in cluster_info.rs, called `tvu_peers()` and/or `tpu_peers()`). Looks to still lack unit tests but at least much more concise and has few branches.
