### ISSUE TITLE
Dump the debug_id in favor of the formatter

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#1021]
We should dump the debug_id in favor of the formatter we have now.
Reference: @aeyakovenko comment on https://github.com/solana-labs/solana/pull/999

**Comment by garious** [comment]
@pgarg66, instead of referencing the PR and reviewer, can you paraphrase? This description doesn't provide enough information for a new developer (or even me!) to take action.

**Comment by garious** [comment]
To clarify, instead of using `debug_id()` to "compress" the Pubkey to a u64, just go ahead and use the whole base58-encoded string, which is the default output format for Pubkey.
