### ISSUE TITLE
v1.3: Enable switch vote on mainnet beta

### ISSUE THREAD

**Issue by carllin** [solana-labs/solana#10312]
After mainnet-beta upgrades to the v1.2 release line, 
#10218, `UNLOCK_SWITCH_VOTE_SLOT` needs to be updated for mainnet beta
https://github.com/solana-labs/solana/blob/d9366776b25262ac6b8a8f65cebaf8d279400d68/core/src/replay_stage.rs#L1807-L1813

**Comment by mvines** [comment]
cc: https://github.com/solana-labs/solana/pull/10615

**Comment by mvines** [comment]
Done
