### ISSUE TITLE
v1.2: Enable switch vote on testnet

### ISSUE THREAD

**Issue by carllin** [solana-labs/solana#10311]
After testnet upgrades to the v1.2 release line,
https://github.com/solana-labs/solana/pull/10218, `UNLOCK_SWITCH_VOTE_SLOT` needs to be updated for testnet
https://github.com/solana-labs/solana/blob/d9366776b25262ac6b8a8f65cebaf8d279400d68/core/src/replay_stage.rs#L1807-L1813

**Comment by mvines** [comment]
Fixed by https://github.com/solana-labs/solana/pull/10615
