### ISSUE TITLE
TW Transactions to self seem to timeout without an error

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#10336]
#### Problem

Users tend to transfer to self as test.

#### Proposed Solution

I don't see why transfer to self would fail.

```
        SystemInstruction::Transfer { lamports } => {
            let from = next_keyed_account(keyed_accounts_iter)?;
            let mut to_account = next_keyed_account(keyed_accounts_iter)?.try_account_ref_mut()?;
            transfer(from, &mut to_account, lamports)
        }
```

My guess the TW integration includes the same account twice in the TX.  explorer should show the AccountInUse error code, the timeout is super annoying.

tag: @jstarry @CriesofCarrots @mvines

**Comment by mvines** [comment]
I think this issue is adequately addresesd by the two referenced PRs.
