### ISSUE TITLE
Reduce unnecessary uses of `result::Error`

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#1033]
result.rs is overused. If a module-defined `Error` object is sufficient, use that. crdt.rs is probably the best example of this.

**Comment by garious** [comment]
This gem prevents nearly everything in the `core` crate from escaping.

**Comment by lazaridiscom** [comment]
Just 6 hits:

https://github.com/search?utf8=%E2%9C%93&q=%22crate%3A%3Aresult%3A%3AError%22+repo%3Asolana-labs%2Fsolana&type=Code&ref=advsearch&l=&l=

9 for
