### ISSUE TITLE
Writing to Log Blocks Other Operations

### ISSUE THREAD

**Issue by brianlong** [solana-labs/solana#10368]
#### Problem
Writing to the log blocks other validator operations.

In Discord, I asked "Q: Does writing to the log file block any other threads/procedures within the validator?" and Leo replied "Logging does block. interesting. it's a synchronous write to a fd."

When the log level is low (info or debug), the amount of data written to the logs might interfere with block production on a busy validator.

#### Proposed Solution
Move the logger to an asynchronous thread.

If that is not possible, review the amount of data written to the logs and the log level for each. A busy validator should be able to run a log level of 'error' or 'warn' without a performance hit.

**Comment by mvines** [comment]
There's a convenient central location where the dispatch to another dedicated logging thread could be plugged in:
https://github.com/solana-labs/solana/blob/69d90b591f0a2d644b736c5d6edb4118e8d0cc37/logger/src/lib.rs#L18-L20

This would incur another memory allocation for each log message, and might skew the logging timestamp (nbd).  

Seems like we could enable "async logging" initially as a `solana-validator` command-line argument, to allow people to experiment with it

**Comment by mvines** [comment]
It would be worthwhile to invest some time measuring where the time goes while logging.  We burrow through at least 4 software layers within the validator itself from the `info!()` macro to when the contents finally hit the log file.
