### ISSUE TITLE
Enable a rolling update of "Permit paying oneself"

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#10374]
https://github.com/solana-labs/solana/pull/10337 will cause a hard fork if anybody sends a transfer to themselves with a collection of mixed validator nodes with/without this PR.

This affects both 1.2 and 1.1 and blocks an update of testnet and mainnet-beta

Options:
1. Back out #10337 entirely
2. Duplicate the system program, old and new version, and at a well-defined epoch swap in the new version

**Comment by garious** [comment]
What about rejecting payment to self below a particular epoch?

**Comment by mvines** [comment]
It's a plumbing problem, system program doesn't have epoch info

**Comment by garious** [comment]
Coincidentally, builtins have a different `process_instruction` signature than the ones loaders call. You can pass in whatever you'd like, so long as you pass it to all builtins. https://github.com/solana-labs/solana/blob/master/runtime/src/message_processor.rs#L295

**Comment by garious** [comment]
Also, keep in mind you can register the same `process_instruction` with multiple program IDs. The program ID is passed to `process_instruction`, which you can use to toggle operational semantics as-needed.  This isn't a hack - it's actually what that `program_id` parameter was intended for.

**Comment by mvines** [comment]
Making everybody jump to `System211111...` doesn't sound nice though

**Comment by garious** [comment]
You don't need to.  The trick is that you use `System2` to represent the old behavior, not the new. Then, just add a special case such that *before* a certain epoch, `System1` is swapped with `System2`.

**Comment by mvines** [comment]
The paths through bank to do this are very sneaky, unless you're seeing something I'm not.

**Comment by garious** [comment]
Thinking either here:
https://github.com/solana-labs/solana/blob/master/runtime/src/bank.rs#L1372

Or pass the epoch into `process_message` and do the swap in its for loop.

**Comment by mvines** [comment]
Here's the direction I'm thinking of, wdyt? https://github.com/solana-labs/solana/pull/10375

**Comment by mvines** [comment]
Done.
