### ISSUE TITLE
Reenable running benchmarks in CI

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#1038]
When we moved back from Criterion to libtest, we raised the sample count from 2 iterations per benchmark to some libtest automagic per-benchmark number. While it runs very fast locally (5-10 seconds), it's painfully slow in CI (~20 minutes). Why?

Troubleshoot Buildkite performance. Reenable running the benchmarks in CI if we can bring that total runtime back below 5 minutes.

**Comment by garious** [comment]
It's the release mode build that's so slow. Remaining possibilities:

1. BuildKite server with too little RAM for compiler optimizations
2. Bug in nightly Rust that's consuming too much RAM
3. Gremlins

@mvines, thoughts on quick ways to figure out which?

**Comment by mvines** [comment]
We're running benchmarks in CI now
