### ISSUE TITLE
1.2.x CLI Ledger error with 1.1.x cluster

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#10412]
#### Problem

We see an error running a stake-split command from the 1.2.0 CLI targeting a 1.1.15 cluster (Mainnet Beta) and using a Ledger Nano S with the latest Solana app 0.2.2.

```
Error: ClientError { request: None, kind: SigningError(Protocol("Ledger operation not supported")) }
```

#### Proposed Solution

Fix it. In the docs, we say clients don't need to move in lockstep with the cluster; that newer clients should work with older clusters.

@t-nelson?  cc: @ericlwilliams

**Comment by garious** [comment]
@t-nelson Split to a derived address via `solana-stake-accounts rebase`, which creates a message with `stake_instruction::split_with_seed`.

**Comment by t-nelson** [comment]
We'll need support for the new TX formats added in https://github.com/solana-labs/solana/commit/36a36d1c8375af3ab76693751cf57b34a34603cc#

**Comment by garious** [comment]
I see, thanks. I'll create an issue over there

**Comment by garious** [comment]
@t-nelson, I created https://github.com/solana-labs/ledger-app-solana/issues/129

Need for a fix is fairly urgent since it takes so long to get our PRs upstreamed. We'll need the Ledger team to release an update before we upgrade Mainnet Beta to 1.2 at the end of the month. Do you think you could squeeze this in within the next week?  @mvines, fyi.

**Comment by t-nelson** [comment]
Yeah shouldn't take much.  Should just be a couple new transaction briefs and a printer or two.  I'll knock it out after I get 1.1 -> 1.2 rolling upgrade test automation going

**Comment by mvines** [comment]
@t-nelson - do we need to do anything here?

**Comment by t-nelson** [comment]
Closed by https://github.com/solana-labs/ledger-app-solana/pull/131
