### ISSUE TITLE
Add discord user IDs to stake-o-matic lists

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#10457]
#### Problem
Automatic stake updates refer to a validator's identity pubkey, as this is the only information the stake-o-matic program has for an account.  This makes tracking changes for a user on Discord looking at #mainnet-beta-stake or #tourdesol-stake a little tedious.

#### Proposed Solution
Add a second field to the lists in https://github.com/solana-labs/solana/blob/master/stake-o-matic/src/whitelist.rs optionally specifying a discord username.  If present, stake-o-matic should include the user ID when posting to the stake channels, so the user gets a ping whenever their stake status changes.

**Comment by mvines** [comment]
@danpaul000 - https://github.com/solana-labs/solana/pull/10679 enables this.  If you can help produce a spreadsheet or something that contains a discord to pubkey mapping for all mainnet-beta and testnet validators, then I can easily get the rest hooked up

**Comment by danpaul000** [comment]
Great thanks @mvines .  I'm working on consolidating such data atm.  Merging your PR isn't blocked on me providing this sheet, right?

**Comment by mvines** [comment]
Nope, not at all.   I demonstrated the address label format in the description of https://github.com/solana-labs/solana/pull/10679#issue-436254626 so it would just need to be filled out more, then we can figure out a good home for that file.  Maybe just in the repo alongside the allow list
