### ISSUE TITLE
Withdrawing from vote account can delete it while still validating

### ISSUE THREAD

**Issue by svenski123** [solana-labs/solana#10461]
#### Problem
Withdrawing all funds from a validator voting account causes it to be deleted while the validator is still validating.

#### Proposed Solution
- Whenever a voting account has active stake against it, reject any withdrawals that would take the balance below the rent-free minimum or to zero; it should not be possible for actively staked voting accounts to "disappear"
- UI/UX add a flag to `solana withdraw-from-vote-account` to sweep all available funds down to the minimum necessary to cover rent; in practice this is what one wants usually wants to do as excess funds in a voting account can't be staked, spent, etc.
- UI/UX add a flag to close out the voting account; this transfer out all funds, causing the vote account to be deleted and would only work when all stake has been removed

**Comment by aeyakovenko** [comment]
we can block withdrawals of the final balance while the account is in the schedule

**Comment by mvines** [comment]
This is going to be tough because the leader schedule is not in a sysvar yet, and even if it was it would be quite expensive to search it from a program.   

For now prohibiting the withdrawal of the rent-free minimum seems acceptable.  This would require adding the rent sysvar to the withdraw instruction

**Comment by aeyakovenko** [comment]
@svenski123 @mvines why is it a problem for them to disappear?  loss of rewards?

**Comment by mvines** [comment]
@carllin went through a ton of effort to enforce that the authorized voter can't be changed more than once an Epoch:
https://github.com/solana-labs/solana/blob/f19faa2e13198cf3074da45876329baa6ae50c38/programs/vote/src/vote_state/mod.rs#L172
Being able to delete and recreate the vote account at will completely bypasses those checks

**Comment by aeyakovenko** [comment]
@mvines ah, we need a "shutdown instruction" that kills the vote account, then next epoch it can be deleted.

**Comment by carllin** [comment]
hmm yeah can we enforce that the vote account can only be deleted at the epoch `leader_schedule_offset` after the vote account has been completely unstaked?

**Comment by mvines** [comment]
> * Whenever a voting account has active stake against it, reject any withdrawals that would take the balance below the rent-free minimum or to zero; it should not be possible for actively staked voting accounts to "disappear"
> * UI/UX add a flag to `solana withdraw-from-vote-account` to sweep all available funds down to the minimum necessary to cover rent; in practice this is what one wants usually wants to do as excess funds in a voting account can't be staked, spent, etc.

https://github.com/solana-labs/solana/pull/10602 fixes these two items

> * UI/UX add a flag to close out the voting account; this transfer out all funds, causing the vote account to be deleted and would only work when all stake has been removed

This is still unresolved, pending https://github.com/solana-labs/solana/issues/10461#issuecomment-642084513

**Comment by mvines** [comment]
Some preliminary work at https://github.com/solana-labs/solana/pull/10494/files

**Comment by ryoqun** [comment]
(this problem is encountered again recently, bumping this issue; seems zero-ing staked vote account is still easy?; cc: @t-nelson, @mvines )

**Comment by mvines** [comment]
How was it encountered @ryoqun?  The cli won't allow you do withdraw the rent reserve from a vote account, so either somebody modified the cli or perhaps they used web3.js?

**Comment by ryoqun** [comment]
> How was it encountered @ryoqun? The cli won't allow you do withdraw the rent reserve from a vote account, so either somebody modified the cli or perhaps they used web3.js?

well, it turned out, web3.js is used... so, false alarm...

**Comment by CriesofCarrots** [comment]
cc https://github.com/solana-labs/solana/issues/21815

**Comment by t-nelson** [comment]
An alternative mechanism would be to block withdrawing the rent exempt reserve until the account has received no credits for an entire epoch.  This can be implemented without modifying the instruction and additionally protects delegators from losing rewards

**Comment by CriesofCarrots** [comment]
My thinking is yes, we need to retain that logic, given that it's still initialized as a vote account and could potentially resume receiving votes.

**Comment by t-nelson** [comment]
Agreed, any account that needs to be rent-exempt must be either rent-exempt or zero-balance/deleted
