### ISSUE TITLE
Enhance RPC getAccountInfo to support decoding account info for SPL Token

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#10475]
We need an easy way for users to figure the current account balance/state of any SPL Fungible Token account, without having to resort to client-side language-specific decoding libraries.

This can be done by enhance [getAccountInfo](https://docs.solana.com/apps/jsonrpc-api#getaccountinfo) to support decoding of account info for SPL Token accounts when an optional parameter is supplied.  

At the same time add account decoding support for one or more of nonce, stake, and config accounts to setup a general precedent.   Also probably file a longer-term issue to add decoding support for various sysvars/etc

**Comment by CriesofCarrots** [comment]
@mvines , are you thinking that we want this decoded account info to look similar to the program `State` struct? Or parsed even further to something like we're returning from Cli?
Eg. should a decoded Vote account be:
[VoteState](https://github.com/solana-labs/solana/blob/583cec922b6107e0f85c7e14cb5e642bc7dfb340/programs/vote/src/vote_state/mod.rs#L157) or [CliVoteAccount](https://github.com/solana-labs/solana/blob/583cec922b6107e0f85c7e14cb5e642bc7dfb340/cli/src/cli_output.rs#L868)

**Comment by mvines** [comment]
The latter is just a beautified version fo the former right?  Reformatting the program `State` struct to be more JSON friendly sounds great (ie, Pubkey byte array vs string).

**Comment by CriesofCarrots** [comment]
> The latter is just a beautified version fo the former right? Reformatting the program `State` struct to be more JSON friendly sounds great (ie, Pubkey byte array vs string).

That sounds more like what I meant by the former.

We're a little more heavy-handed than that in the Cli structs. Some fields are stripped out, eg. `prior_voters` from VoteState. CliStakeState might be a better example; in addition to the stake account, we pull stake_history to process and return activating/deactivating information, and the clock sysvar to process lockup, etc.

Either way, I would plan on making everything JSON friendly.

**Comment by mvines** [comment]
I think I'd favour a more naive approach of just exposing the `State` without additional computed meta data until we have an end-user asking for more with a good reason behind them.  Less work for the RPC server to do
