### ISSUE TITLE
random repair start counter and have the leader use finality when servicing repair requests

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#1055]
So all the validators are not on the same repair counter, they should start with a random value so that huge repair spikes are not seen in the network when everyone repairs at the same time.

Also, when servicing repair requests the leader could use the finality it has seen to decide to retransmit a blob or not. If most of the network has already seen that blob, then it could let another validator take care of that.

**Comment by mvines** [comment]
Obsolete
