### ISSUE TITLE
watchtower: support for error.sh/success.sh triggers

### ISSUE THREAD

**Issue by huglester** [solana-labs/solana#10562]
#### Problem
Currently you can basically only can integrate with current implementations. Not some custom one. For example I want to integrate with grafana.

#### Proposed Solution
We add support like:
```
--on-success /root/solana-success-notice.sh \
--on-error /root/solana-error-notice.sh
```
that way we could easily make it integrate into grafana/prometheus to further integrate into monitoring system with some more combined graphs and so on

There should be also some params passed
Probably entire message could be passed to script as a 1st param; 
later it could be just extract with bash,python,php,nodejs whatever user uses.

thanks

**Comment by mvines** [comment]
This looks quite easy to add.  Here is main code block that would require changes to execute the success/error scripts: 

https://github.com/solana-labs/solana/blob/f6546d00c2b9041b3033cb67f8e9a60be9ef468b/watchtower/src/main.rs#L427-L456
