### ISSUE TITLE
RPC only works when removing  the line --no-untrusted-rpc from the service file v1.2.2

### ISSUE THREAD

**Issue by JB273** [solana-labs/solana#10579]
#### Problem
RPC calls are not working for any of the solana commands since upgrade to version 1.2.2

#### Proposed Solution
To get it working correctly again one need to remove the line
`--no-untrusted-rpc`
from the solana service config file, after that all works as expected.

Since this line protects us from malicious RPC calls this might need to be checked out!

**Comment by mvines** [comment]
Hey @JB273, I wonder if this was a temporary issue today? 
I'm able to connect to testnet with the 1.2.2 release and the validator arguments at https://docs.solana.com/clusters#example-solana-validator-command-line-1, which include `--no-untrusted-rpc`. 

Could I see your validator log when you put `--no-untrusted-rpc` back?  That might help us identity what's going on

**Comment by JB273** [comment]
Tried to add the `--no-untrusted-rpc` back, but then RPC doesn't work.
Command I try is: `solana-gossip spy --entrypoint testnet.solana.com:8001`

To add to this, the command: `solana catchup ~/validator-keypair.json` doesn't work in neither setups for me now!

When removing the line again it works, also when adding the line again in the service file, my Validator goes directly into delinquent status in Solana Beach

**Comment by JB273** [comment]
Hi Michael,

I reverted back to version 1.2.1 and deleted install of version 1.2.2.
Then did the upgrade again and now all seems to work well again.
Maybe just a glitch in downloading..

Sidenote: when I downloaded the release yesterday it was really slow, like 10 minutes, so maybe that had something to do with it!

If you want you can close this one.
