### ISSUE TITLE
RPC Restricted Mode

### ISSUE THREAD

**Issue by brianlong** [solana-labs/solana#10603]
#### Feature Request
Currently, when running a validator, I can use `--private-rpc` to query RPC from my localhost, OR I can open RPC to the world. I would like to access RPC on my nodes from other machines that I control, but not allow global access to my RPC service.

I tried to remove the `--private-rpc` option and then restrict access with my firewall, but I saw errors when booting. The errors were related to the closed firewall ports 8899:8900 and the validator did not start.

#### Proposed Solution
Create an option for `--restricted-rpc` that allows me to access RPC from other machines, but not advertise RPC to the cluster. I will then manage access through my firewall settings.

**Comment by mvines** [comment]
@brianlong - I think `--private-rpc` does exactly what you're hoping for.  It doesn't advertise RPC to the cluster but still allows anybody to use it.   You could further restrict RPC to a specific interface with something like `--rpc-bind-address 127.0.0.1`

**Comment by mvines** [comment]
I don't think there's any action here.  If you disagree please re-open with comments
