### ISSUE TITLE
RPC single gossip commitment subscriptions notify on incomplete slot

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#10619]
#### Problem
It's possible for a block to reach single confirmation in gossip before the node processes the bank. This causes the RPC subscriptions service to notify for a slot that hasn't been fully processed yet.

#### Proposed Solution
1. If bank is not frozen yet, queue single gossip notification
1. Notify RPC subscription service when banks are frozen
1. Check frozen bank notifications against single gossip notification queue and process when match is found

**Comment by aeyakovenko** [comment]
@jstarry can we query the working bank instead of waiting for the frozen bank?

**Comment by aeyakovenko** [comment]
https://github.com/solana-labs/solana/issues/10625

**Comment by jstarry** [comment]
@aeyakovenko that won't help break. It needs the state from the confirmed block to determine a transaction was processed.

**Comment by aeyakovenko** [comment]
@jstarry why?  A state from a working bank is just as good.

**Comment by jstarry** [comment]
@aeyakovenko seems like I'm missing something here. What I observed was that on "single gossip" confirmation, a notification was sent with account data that didn't include the account state changes from all of the transactions that landed in a particular slot.

On devnet, I imagined this happened because cluster majority processed and voted on a bank that hadn't been processed yet on the RPC node. Isn't the working bank the same as the not-yet frozen bank?

**Comment by aeyakovenko** [comment]
@jstarry if the custer approved slot 10, and RPC is working on slot 10, i guess it needs to wait for slot 10 to finalize before reading it's state.  But we can probably wake up the client and have it poll.

**Comment by jstarry** [comment]
@aeyakovenko the API that this affects directly right now is the account subscription API which streams updates to the client in realtime without the need for polling. I'd like to keep that dev experience simple for now. 

As for confirmation times, it would be nice to know ASAP that a block was single gossip confirmed for use in the confirmation time stat (without waiting for the RPC node to process the block). We could do that with a separate subscription to the stream of single gossip confirmed slots.
