### ISSUE TITLE
validators should start asynchronously

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#1063]
#1058 has validators blocking for a balance check.  None of the nodes in the network should need to wait for anything before they join.  The client thats airdropping validator tokens should do the balance checks for the validators identities before starting the bench.  The dashboard should reflect the number of valid voters out of the total network.  We might also need a counter for dropped votes (account not found votes)

@garious @sakridge @mvines @pgarg66

**Comment by sakridge** [comment]
Well, how does the validator know the airdrop has been successful?

**Comment by sakridge** [comment]
Or it's TCP so maybe it's a bit more robust in that way.

**Comment by aeyakovenko** [comment]
@sakridge it sees its vote in the ledger.  it doesn't need to wait to start.  it can just start voting regardless if its stake is 0 or not.

**Comment by sakridge** [comment]
Sure ok. I was thinking more that if the airdrop packet is dropped or unsuccessful for some reason. But that checking can be done asynchronously while the validator is booted.

**Comment by mvines** [comment]
Obsolete
