### ISSUE TITLE
fix docker/wallet/drone network env

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#1069]
Gossiping for the network from the wallet/drone to the testnet wont work if they are unable to punch through the NAT.

I think it might be possible to use the gossip listen socket as the send socket, and create a route that way.  So only the leader would have an open NAT.  But, clients would need to bind to 0, connect to the leader's gossip port, ask it to echo back the clients IP, and advertise that one.

**Comment by garious** [comment]
Was this already fixed? @pgarg66, @aeyakovenko, @mvines?

**Comment by aeyakovenko** [comment]
@garious, @rob-solana did a bunch of network refactoring.  i think it can be closed

**Comment by rob-solana** [comment]
it's not perfect, but we're getting there.  I don't have a clear way forward for us, though, so until we have to support NAT'd fullnodes, we can leave this closed.
