### ISSUE TITLE
Ledger app returns wallet ID when presented with negative key path

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#10722]
#### Problem
Passing a negative value to the solana ledger app will return the Ledger's wallet ID.
```
~$ solana --version
solana-cli 1.3.0 296ac10b
~$ solana-keygen pubkey usb://ledger
2JT2Xvy6T8hSmT8g6WdeDbHUgoeGdj6bE2VueCZUJmyN
~$ solana-keygen pubkey usb://ledger?key=-1
2JT2Xvy6T8hSmT8g6WdeDbHUgoeGdj6bE2VueCZUJmyN
```
To my knowledge, a negative value here is an invalid derivation path.

#### Proposed Solution
Return an error message when invalid key paths are passed.

**Comment by t-nelson** [comment]
@CriesofCarrots looks like we're discarding parse errors here in remote-wallet.  Intended?

https://github.com/solana-labs/solana/blob/0550b893b004d4e1c25678d0bb002422def60744/remote-wallet/src/remote_wallet.rs#L284-L289

**Comment by t-nelson** [comment]
We should probably be setting the harden bit instead of casting off the `'` too

**Comment by CriesofCarrots** [comment]
> looks like we're discarding parse errors here in remote-wallet. Intended?

No, we should probably be bubbling those up.

> We should probably be setting the harden bit instead of casting off the `'` too

We do set the hardened bit, we just don't require users type it in as part of the query string: https://github.com/solana-labs/solana/blob/0550b893b004d4e1c25678d0bb002422def60744/remote-wallet/src/ledger.rs#L468
We could add it when missing instead of stripping it when present, but that will make DerivationPath a more-complex type, unnecessarily, imo.

**Comment by t-nelson** [comment]
> No, we should probably be bubbling those up.
> 
:+1: 
 
> We do set the hardened bit, we just don't require users type it in as part of the query string:
> 
> https://github.com/solana-labs/solana/blob/0550b893b004d4e1c25678d0bb002422def60744/remote-wallet/src/ledger.rs#L468
> 
> We could add it when missing instead of stripping it when present, but that will make DerivationPath a more-complex type, unnecessarily, imo.

Ah! I guess I expected the harden bit to be set here(-ish) since it's a BIP32 feature, not Ledger specific.

I have an idea, stand by :slightly_smiling_face:
