### ISSUE TITLE
converge module

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#1072]
the hotfix in #1071 demonstrates the need for a converge/discover module.  the `converge` function is sprinkled around the code, `bench-tps.rs` and `drone.rs` and a few other places have a copy of it. 

We need 1 copy, that discovers the network to the minimum set (current node count, eventually some set of validators or stake size), and returns the set and the current leader.

**Comment by mvines** [comment]
`core/src/gossip_service.rs ` has these now
