### ISSUE TITLE
solana-tokens does not support funding a pre-existing stake account

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#10743]
#### Problem
`solana-tokens` creates new stake accounts whenever `distribute-stake` subcommand is called.  We have a need to be able to accept the address of an existing stake account.

#### Proposed Solution
Add an optional `stake_account_address` field to `Allocations` struct and, if present, use this address rather than creating a new account in `distribute_tokens`

**Comment by danpaul000** [comment]
cc: @garious

**Comment by garious** [comment]
@danpaul000, if the account already exists, you'd also need to change the instruction from `split` to `withdraw-stake`.

**Comment by danpaul000** [comment]
Right, thanks.  We can't `withdraw-stake` into a stake account though, right?  So to move from a funding stake account to a pre-existing stake account, we need to `withdraw-stake`, `create-stake-account` with some random address, then `merge-stake` from the locally created account to the target pre-exsiting account, is that right?

This feels rather messy, is there a cleaner workflow?

**Comment by garious** [comment]
The recipient of withdraw-stake can be a stake account

**Comment by mvines** [comment]
@danpaul000 - do we need this issue still?

**Comment by danpaul000** [comment]
Nope
