### ISSUE TITLE
Validator can be stalled for >1hr

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#10753]
#### Problem

Mainnet-beta node 7Np was stalled for about 1.5 hours on 6/20/2020 starting around 4:30am PST. Seems that shred insertion was stalled for a long time. A purge was happening around the same time, but it's not clear if that is the direct and only cause of the stall.

![ledger-pruning-mainnet-stall](https://user-images.githubusercontent.com/1024962/85464277-4ce64700-b55c-11ea-8cfa-c28bc55e760f.png)

![ledger-insert-stall-mainnet-stall](https://user-images.githubusercontent.com/1024962/85464351-61c2da80-b55c-11ea-9050-775c2ceef294.png)

#### Proposed Solution

Debug and fix... maybe only insert 1 slot at a time so that insert cannot be stalled for such a long time. Also, maybe some tweaking of the duty cycle of purge so that the disk is not blocked completely.

**Comment by sakridge** [comment]
cc @carllin

**Comment by mvines** [comment]
Obsolete
