### ISSUE TITLE
Improve leader seed generation

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#1081]
The proposed plan for updating the random seed can be manipulated by the leader. 

https://github.com/solana-labs/solana/blob/master/rfcs/rfc-002-consensus.md#leader-seed-generation

That node can postpone acceptance of voting signatures and then reorder them to get a seed that will select itself as the next leader. How can we do better?

**Comment by garious** [comment]
@carllin, I'm bumping this back a release. This one is lower priority than the other tickets assigned to you. If you get to it this release, go ahead and reassign it to 0.8.

**Comment by aeyakovenko** [comment]
Another simple approach.

* leader rotation occurs every X poh counts
* seed is generated every Y poh counts
* seed is simply the sha(Y)

The only thing that a malicious network can modify is the set of active nodes, which is censorship resistant if X <<< Y and there is enough leaders rotating to allow everyone to submit a vote.

**Comment by garious** [comment]
@aeyakovenko, do you mean the sha of the poh hash at each of the Y poh counts?

**Comment by aeyakovenko** [comment]
@garious no, the actual counter.  so the seed is basically known in advance.  the only thing the leader can change is the active set of nodes and their stake weight, which is computed over a longer period.  seed is basically Y

**Comment by garious** [comment]
So if Y is constant, then sha(Y) will always be the same.  Seems like you can remove that rule, and use every Yth poh hash as the seed.

**Comment by garious** [comment]
Also, does <<< mean "much less than"?

**Comment by aeyakovenko** [comment]
Y, changes, 100, 200, 300, 400...  It's just known ahead of time.  The difference with using sha(poh) is that poh can be manipulated at the moment of computation, so the bad leader can order or exclude nodes from rotation

**Comment by garious** [comment]
I see, Y as an absolute poh count. You said "Y poh counts".  You need another variable. Something like SUM(Yn).

**Comment by garious** [comment]
I'm on board with this technique.

**Comment by aeyakovenko** [comment]
yea, i like how simple it is.  we should try to optimize for fast leader rotation anyways, under 10s!

**Comment by garious** [comment]
I think your strategy breaks because the absolute poh count will change once a validator becomes a leader by mistake.  It'll never calculate the right leader again.  Instead, how about:

Hash the genesis seed once per entry and sample that chain every X entries. So:

```
h0 = entries[0].id
h1 = hash(h0)
h2 = hash(h1)
```

And then say that h1 is the seed after X, h2 is the seed after 2*X, etc.  In this way, you could generate the leader schedule using only the entry height and the genesis block. No need for poh.

**Comment by aeyakovenko** [comment]
@garious always rotate the seed at the expected height, no matter how many network timeout based leader switches occurred

**Comment by garious** [comment]
I see, expected height. Clever.

**Comment by garious** [comment]
This is now implemented as a function of entry height, not its hash.
