### ISSUE TITLE
 v1.3: Enable eager rent collect across gapped epochs on mainnet-beta

### ISSUE THREAD

**Issue by ryoqun** [solana-labs/solana#10810]
#### Problem

this needs to be updated for mainnet-beta:

https://github.com/solana-labs/solana/blob/50f7ed80c824cc844bcacff0bbbd299d193cc620/runtime/src/bank.rs#L1871-L1873

#### Context

#10206

**Comment by ryoqun** [comment]
Enable this after #10809  is applied on the testnet and some time passed.

**Comment by mvines** [comment]
@ryoqun - can you please port this feature activation to `FeatureSet` then roll it out to mainnet-beta over the next v1.3 release or two

**Comment by ryoqun** [comment]
> @ryoqun - can you please port this feature activation to `FeatureSet` then roll it out to mainnet-beta over the next v1.3 release or two

@mvines roger! finally this is getting some care: #12842
