### ISSUE TITLE
TdS died 1.2.6

### ISSUE THREAD

**Issue by leoluk** [solana-labs/solana#10821]
#### Problem

:skull: 

Last root slot is 21042857 at ~07:51:45 UTC. Things started going downhill at ~07:09 UTC.

![image](https://user-images.githubusercontent.com/859697/85836446-e39e4800-b796-11ea-8e82-560d465cb6b6.png)

Please upload your logs:

    ADDRESS=<your node ID>
    TZ=UTC journalctl -u solana.service -o cat --utc --since '2020-06-26 06:30' --until '2020-06-26 10:30' | xz | curl --data-binary @- "http://logbin.certus.one:8080/solana-github-10821/$ADDRESS.log.xz"

For plain logfiles:

    ADDRESS=<your node ID>
    xz | curl --data-binary @- "http://logbin.certus.one:8080/solana-github-10821/$ADDRESS.log.xz" < your_logfile.log

Upload destination: http://logbin.certus.one:8080/Qui9iehu/solana-github-10821

#### Proposed Solution

Resurrection?

**Comment by Bambarello** [comment]
Logs uploaded. /solana-github-10821/3ANJb42D3pkVtntgT6VtW2cD3icGVyoHi2NGwtXYHQAs.log.xz

**Comment by czarly** [comment]
Logs uploaded. /solana-github-10821/ChLMXZ4KXsMpa8W1VymMxim1vdPSK5a1jDwfMbm7cycT.log.xz

**Comment by MBGBuzzer** [comment]
Logs uploaded. /solana-github-10821/2bvUqyatpaDLn9ch9BxNYRwg5SFpq3rDfWJKfohC9iD4.log.xz

**Comment by JB273** [comment]
Uploaded 4997616 bytes to /solana-github-10821/hQBS6cu8RHkXcCzE6N8mQxhgrtbNy4kivoRjTMzF2cA.log.xz

**Comment by rk-p2p** [comment]
Uploaded 3256936 bytes to /solana-github-10821/D52Q6Ap8RVMw1EvJYTdEABP6M5SPg98aToMcqw7KVLD9.log.xz

**Comment by andreisid** [comment]
Uploaded 4437172 bytes to /solana-github-10821/2JT1SRSm61vvHKErY2PCnHUtMsumoh69jrC7bojd9f1x.log.xz

**Comment by novy4** [comment]
Uploaded 8224308 bytes to /solana-github-10821/BLfpk2WoF8RnerCqjxHe7qFJjpEE427riMkf2fS6vUB6.log.xz

**Comment by chinezupwnz** [comment]
Uploaded.

**Comment by pkrasam** [comment]
doing it now

**Comment by Pete-LunaNova** [comment]
Uploaded 2748336 bytes to /solana-github-10821/D71JRzjPpHipt8NAWnWb3yZoXezbkGXqSf7TVCir6wvT.log.xz

**Comment by kwunyeung** [comment]
Uploaded 3499596 bytes to /solana-github-10821/AkVMbJq8pqKEe87uFaxjmt35tX2cNhUJTJwv13iioHu7.log.xz

**Comment by k0kk0k** [comment]
Uploaded 4081892 bytes to /solana-github-10821/B8T2dbvYaM4gJfpLLbuBScuWKFhnG6KspRK72v5D5uoK.log.xz

**Comment by sakridge** [comment]
[tds-fail-6-26-2020-2.pdf](https://github.com/solana-labs/solana/files/4838985/tds-fail-6-26-2020-2.pdf)

**Comment by carllin** [comment]
Closer to time of death:
[graph.pdf](https://github.com/solana-labs/solana/files/4839278/graph.pdf)

**Comment by ryoqun** [comment]
After straggling to find some clue from the logs, I've finally managed to doodle something interesting: 
[frozen-full.pdf](https://github.com/solana-labs/solana/files/4846184/frozen-full.pdf)

Basically, this is the directed (= chronologically-ordered) graph of slots of frozen banks for each color-keyed validators. I guess this effectively indicates the order each validator's replay stage tried forks and roll-backed while searching the aggreable common one.

Before around 21042964, the world was calm. But after it, the world is chaos. :)

Also, apparently, most slots are timely available to each validators, so I guess the repair subsystem is fine and this cluster death is related to the inabibility of convergence of heaviest fork among validators, possibly due to FailedThreshold log floods? I guess after some trigger, validators started to panic, desperately finding all visible forks after one and one in dark with brute force fashion as they became available.

I'm still new to the consensus code (debut with #10718 ), maybe is this phenomenon is like heavy OS threshing?

I'll post how to create these pdfs (ugly one-liners!) shortly after.

**Comment by sakridge** [comment]
> 
> Also, apparently, most slots are timely available to most validators, so I guess the repair subsystem is fine and this cluster 
> death is related to the inabibility of convergence of heaviest fork among validators, possibly due to FailedThreshold log 
> floods? I guess after some trigger, validators started to panic, desperately finding all visible forks after one and one in dark 
> with brute force fashion as they became available.

From the stake graphs, seems that most validators are on the main fork, some are just quite a bit behind. We only have 2 logs for the validators stuck behind, one is `A5hM`, the other `8t6UU` which both started to struggle with performance problems. They started freezing banks much later than the testnet.solana.com node. In both, the ledger purge seems to be happening during this time, although maybe slightly after for `A5hM`. Ledger purging affecting the shred insert and causing the delay is one theory. There were quite a few nodes behind though and hard to say that all of them were affected by the purging.

**Comment by ryoqun** [comment]
> From the stake graphs, seems that most validators are on the main fork, some are just quite a bit behind.

Yeah, I was aware of it. Importantly, the _most_ comprised supermajority (+2/3%) So, I thought the cluster can progress although bunch of others are far behind including `A5hM` and `8t6UU`:

```
$ pry
[1] pry(main)> 2.5 + 1.7 + 44.1 + 19.8
=> 68.10000000000001
```

So, I focused on the reason of stagnation of the lively group of validators.

**Comment by ryoqun** [comment]
And here is how to create the pdf (with further-extended version with lagging validators excluded):
[frozen-slots-reduced.pdf](https://github.com/solana-labs/solana/files/4846856/frozen-slots-reduced.pdf)


```bash
# extract slots from logs (can print slots with any criteria)
for f in ../tmp/tds-june-logs/*.log.xz; do echo $f; cat $f | zgrep -E '^.2020-06-26T07:(4[89]|5[0123])' | grep -o 'replay.*bank frozen.**$' | grep -o '[0-9]*' >| $f-frozen-slots; done

# post-process
$ rm ../tmp/tds-june-logs/8t6UUXRkQTBpanRoMjxNxio1baXXkEdeLniCVJGMdzLJ.log.xz-frozen-slots
...

# convert to edges and create a combined DOT file
(echo 'digraph D {' && for f in ../tmp/tds-june-logs/*-frozen-slots; do color="#$(basename $f | grep -o '^[^.]*'| base58 -d| xxd -ps -l3)"; cat $f | (while read s; do if [[ -n $l ]]; then echo $l '->' $s '[color="'$color'"]'; fi; l=$s; done); done && echo '}') >| ../tmp/tds-june-logs/frozen-slots-reduced.dot

# generate pdf
dot -x -Tpdf < ../tmp/tds-june-logs/frozen-slots-reduced.dot >| /tmp/frozen-slots-reduced.pdf
```

TODO: color the nodes using leader schedule...

**Comment by carllin** [comment]
@ryoqun so you're right that around slot `21042999`, `68.1%`  of the stake was near the tip, but I think it quickly degenerated from there, check my second graph here: https://github.com/solana-labs/solana/issues/10821#issuecomment-650405549, `<60%` was near the tip. 


We believe the problem right now is that inserts into blockstore are really slow, and this is stalling `ReplayStage`'s ability to make progress. The suspicion for this is two fold:

1) We're seeing `bank frozen` logs at very slow intervals, often times `1-5` seconds apart. However, the slot `is full` logs were already present many seconds ago (slot full is marked when all the shreds are detected, but the `WriteBatch` containing those shreds has not necessarily committed to the blockstore). This makes us believe the *commit* step in blockstore write batch is taking a while

Here' such an example:

```
[2020-06-26T07:22:11.040574552Z INFO  solana_core::replay_stage] new fork:21038583 parent:21038582 root:21038525
[2020-06-26T07:22:11.425660622Z INFO  solana_ledger::blockstore] slot 21038583 is full, last: 146
[2020-06-26T07:22:15.501489282Z INFO  solana_core::replay_stage] voting: 21038583 107980705602567435581605752
```

2) We're seeing repair logs for slots, even after the slot was marked as full:

For that same slot above:
```
[2020-06-26T07:22:12.309841612Z INFO  solana_core::repair_service]
        21038583: SlotRepairs {
                    highest_shred_index: 79,
                    pubkey_repairs: {
                        ChorusM5BVgnAKbg9PF15285LkqeCoZWK2p9s35T7J2A: 1,
                        77uXenX1Y9T2D1pcnHnYsYiwTTHbnzkyrKX5fQFMGVCR: 1,
                        4WufhXsUhPc7cdHXYxxDrYZVVLKa9jCDGC4ccfmuBvu2: 1,
                        8diJdQj3y4QbkjfnXr95SXoktiJ1ad965ZkeFsmutfyz: 1,
                        GuKn8nEJwUPjBfxpwyq2MXU2JNrSpj7gqnKptCZeEk7j: 1,
                        BWiftESMUsve87rkjU7HsaA7fkiJRAbv3xZLQrmKZtnz: 1,
                        Ft5fbkqNa76vnsjYNwjDZUXoTWpP7VYm3mtsaQckQADN: 1,
                        B6ZramCQhQWcq4Vxo3H5y1MYvo37wRZiAwKk88qaYNiF: 1,
                    },
                },

[2020-06-26T07:22:14.520088904Z INFO  solana_core::repair_service] repair_stats: RepairStats {
                21038583: SlotRepairs {
                    highest_shred_index: 79,
                    pubkey_repairs: {
                        BWiftESMUsve87rkjU7HsaA7fkiJRAbv3xZLQrmKZtnz: 1,
                        8onJp7KyshoMcxVm5CemhPgGvA1hdSnHbcjLCvJidV8o: 1,
                        3ANJb42D3pkVtntgT6VtW2cD3icGVyoHi2NGwtXYHQAs: 1,
                        4dWYFeMhh2Q6bqXdV7CCd4mJC81im2k6CXCBKVPShXjT: 1,
                        GuKn8nEJwUPjBfxpwyq2MXU2JNrSpj7gqnKptCZeEk7j: 1,
                        B6ZramCQhQWcq4Vxo3H5y1MYvo37wRZiAwKk88qaYNiF: 1,
                    },
                },
```

This implies repair has not seen the committed shreds to blockstore, even though the `is full` logs were from many seconds ago.

**Comment by ryoqun** [comment]
@carllin Thanks for explaining! I learnt a lot. So, my graph was just capturing the post-incident phenomenon... I hope #10830 can improve the situation. :)

**Comment by ryoqun** [comment]
I guess this can be closed now.
