### ISSUE TITLE
Some apps may want to optimistically move forward as soon as a tx is in a block

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#10827]
#### Problem
Games may want to take the chance of state rollback as soon as a tx is in a block.

#### Proposed Solution

Api to help pick the leader
Api to synchronously submit the tx and get a signal that it’s in the block.

Tag: @jstarry @carllin

**Comment by jstarry** [comment]
@aeyakovenko we fan out entries/shreds while creating a block right? Could we do this in a more decentralized way? Chasing the next leader sounds challenging and requiring each leader to hold on to short lived connections doesn't sound great.

**Comment by aeyakovenko** [comment]
Yep, I would imagine these are premium apis.  I think 0 confirmations gets you a notification right after the block is produced.
