### ISSUE TITLE
explorer/: Add memo support to explorer.solana.com

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#10832]
The explorer should decode and display memo instructions in any transaction it shows to to user

Depends-on: https://github.com/solana-labs/solana/issues/10476
cc: https://github.com/solana-labs/solana/issues/10831

**Comment by jstarry** [comment]
@oJshua this is done right?

**Comment by oJshua** [comment]
@jstarry correct. We can close.

**Comment by oJshua** [comment]
@jstarry I'll add Memo to the search as well.
