### ISSUE TITLE
`scripts/cargo-for-all-lock-files.sh tree` gives an error.

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#10855]
#### Problem

`scripts/cargo-for-all-lock-files.sh tree` gives an error:
```
sakridge@wiggins:~/solana$ ./scripts/cargo-for-all-lock-files.sh tree
++ dirname Cargo.lock
+ cd .
+ cargo tree
Error: this command requires running against an actual package in this workspace
```

#### Proposed Solution

Skip virtual manifests?

**Comment by t-nelson** [comment]
Was this on master or a release branch?

**Comment by sakridge** [comment]
> 
> 
> Was this on master or a release branch?

v1.2

**Comment by sakridge** [comment]
But I just tried master and seems the same behavior is there too.

**Comment by t-nelson** [comment]
Hmm, worked for me from master.  Linux / cargo v1.44.1 :thinking:

**Comment by CriesofCarrots** [comment]
`./scripts/cargo-for-all-lock-files.sh tree` works for me on MacOS, master and branch

**Comment by sakridge** [comment]
Ah, the cargo version was the problem.
