### ISSUE TITLE
Snapshot creation fails sometimes

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#10860]
#### Problem

```
[2020-06-26T00:00:15.866622778Z WARN  solana_ledger::snapshot_utils] tar command failed with exit code: signal: 10
[2020-06-26T00:00:15.866649939Z INFO  solana_ledger::snapshot_utils] tar stdout:
[2020-06-26T00:00:15.866653937Z INFO  solana_ledger::snapshot_utils] tar stderr:
```

#### Proposed Solution

Debug and fix.. is it from the log rotation signal propagating to `tar`?

**Comment by t-nelson** [comment]
Judging by that timestamp, logrotate seems like the culprit...  Time to stop shelling out?

**Comment by mvines** [comment]
yeah that's totally logrotate.  I'm surprised SIGUSR1 is getting propagated into the validator child processes though, maybe we can eat that signal better or configure logrotate to not do that.

I'd love to ditch our silly tar subprocess, we don't have a crate that supports tarring sparse files.  Although that's based on some months ago, maybe the crates.io situation has improved recently

**Comment by t-nelson** [comment]
```
       --kill-who=
           When used with kill, choose which processes to send a signal to.
           Must be one of main, control or all to select whether to kill only
           the main process, the control process or all processes of the unit.
           The main process of the unit is the one that defines the life-time
           of it. A control process of a unit is one that is invoked by the
           manager to induce state changes of it. For example, all processes
           started due to the ExecStartPre=, ExecStop= or ExecReload= settings
           of service units are control processes. Note that there is only one
           control process per unit at a time, as only one state change is
           executed at a time. For services of type Type=forking, the initial
           process started by the manager for ExecStart= is a control process,
           while the process ultimately forked off by that one is then
           considered the main process of the unit (if it can be determined).
           This is different for service units of other types, where the
           process forked off by the manager for ExecStart= is always the main
           process itself. A service unit consists of zero or one main
           process, zero or one control process plus any number of additional
           processes. Not all unit types manage processes of these types
           however. For example, for mount units, control processes are
           defined (which are the invocations of /bin/mount and /bin/umount),
           but no main process is defined. If omitted, defaults to all.
```

`--kill-who=main` sounds like a nice start

**Comment by t-nelson** [comment]
> I'd love to ditch our silly tar subprocess, we don't have a crate that supports tarring sparse files. Although that's based on some months ago, maybe the crates.io situation has improved recently

https://github.com/alexcrichton/tar-rs/pull/62 !

**Comment by nyetwurk** [comment]
Since this did not make 1.7, more and more validators are seeing disks getting filled up with old tmp files. Having a cron to clean it out makes no sense, as that could disrupt a tar in process. Old tmp-* files should be cleared on startup, or there should be documentation for validator operators that instructs them to add such a rm to any startup scripts.

**Comment by mvines** [comment]
> Old tmp-* files should be cleared on startup

This is exactly what happens on startup!

**Comment by nyetwurk** [comment]
Ah. I wasn't aware it did that; I have it in our own startup scripts

**Comment by t-nelson** [comment]
The backport will be in the next v1.8 release, then the v1.7 release after we're happy with it there
