### ISSUE TITLE
point values look too high in rewards on testnet

### ISSUE THREAD

**Issue by rwalker-com** [solana-labs/solana#10880]
#### Problem
```
[rwalker@anodyne solana]$ val=0; for i in $(solana account SysvarRewards111111111111111111111111111111  --url http://testnet.solana.com | awk '/0000: / {print "0x" $9 " 0x" $8 " 0x" $7 " 0x" $6 " 0x" $5 " 0x" $4 " 0x" $3 " 0x" $2}' ); do ((val*=256)); ((val+= $i)); done; echo $((val)) $((val/1000000000))
4564589405481740449 4564589405
```
4,564,589,405 SOL for each point?

this value is set in bank::update_rewards() and can go sideways if:
* inflation is really large
* period calculation comes out bad because bank and poh may not be configured the same (ticks/slot, etc.)
* `bank.capitalization()` is incorrectly calculated (i.e. way too big)
* `validator_points` is incorrect, way too small

capitalization looks wrong:
```
[rwalker@anodyne solana]$ solana total-supply --url http://testnet.solana.com
10061492361.588398 SOL
```
but 10B SOL doesn't get us to point values that high

inflation is zero?
`{"jsonrpc":"2.0","result":{"epoch":61,"foundation":0.0,"total":0.0,"validator":0.0},"id":1}`

#### Proposed Solution
more investigation

**Comment by rwalker-com** [comment]
calculation for point value above is incorrect...

**Comment by mvines** [comment]
Nice, getInflationRate is broken. https://github.com/solana-labs/solana/pull/10882
