### ISSUE TITLE
web3.js: Conflicting code / test logic for Transaction serialization

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#10897]
#### Problem

While fixing a bug in transaction message serialization, I happened upon the following paradox...

We have a test:
https://github.com/solana-labs/solana/blob/3884323cb6333d3f085624a008b5fac14dc5fe4c/web3.js/test/transaction.test.js#L198-L200
Which is named and has a golden value to imply it is testing serialization of a transaction that has not yet been signed.

However!  `Transaction.serialize()` starts like this:
https://github.com/solana-labs/solana/blob/3884323cb6333d3f085624a008b5fac14dc5fe4c/web3.js/src/transaction.js#L395-L406
Implying that attempting to serialize an unsigned transaction should throw.

#### Proposed solution

I can't think of a compelling reason to serialize an unsigned transaction, where just the message wouldn't do the same job.  So I'm thinking the RightThing(TM) to do here is replace the test with one that ensures `Transaction.serialize()` throws on an unsigned transaction and another that tests `Transaction.serializeMessage()`

**Comment by mvines** [comment]
(302 into the main repo, since that's where the web3.js source now lives)
