### ISSUE TITLE
TdS died 1.2.9

### ISSUE THREAD

**Issue by leoluk** [solana-labs/solana#10908]
#### Problem

The front fell off:

![image](https://user-images.githubusercontent.com/859697/86463048-0c8d8280-bd2d-11ea-98da-1fda94e9b4c3.png)

This happened precisely when we updated our node (Ft5...) to 1.2.9, at 2020-07-03 09:37:15 UTC.

Please upload your logs:

    ADDRESS=<your node ID>
    TZ=UTC journalctl -u solana.service -o cat --utc --since '2020-07-03 05:00' --until '2020-07-03 13:00' | xz | curl --data-binary @- "http://logbin.certus.one:8080/solana-github-10908/$ADDRESS.log.xz"

For plain logfiles:

    ADDRESS=<your node ID>
    xz | curl --data-binary @- "http://logbin.certus.one:8080/solana-github-10908/$ADDRESS.log.xz" < your_logfile.log

Upload destination: http://logbin.certus.one:8080/Qui9iehu/solana-github-10908

(no "uploaded log" comments here on GitHub, please - it spams the team's inbox)

#### Proposed Solution

:shrug:

**Comment by leoluk** [comment]
In case it's relevant, these were the start parameters for our node:

```
/opt/solana/solana/target/release/solana-validator \
    --identity /opt/solana/keys/validator-keypair.json \
    --vote-account /opt/solana/keys/validator-vote-keypair.json \
    --authorized-voter /opt/solana/keys/validator-vote-keypair.json \
    --expected-bank-hash 6q2oTgs8FiJxra2Zo1N8tzWqo5b6uGbjmFgoWDsXxchY \
    --ledger /opt/solana/data \
    --rpc-port 8899 \
    --entrypoint 35.203.170.30:8001 \
    --limit-ledger-size \
    --expected-genesis-hash 4uhcVJyU9pJkvQyS88uRDiswHXSCkY3zQawwpjk2NsNY \
    --wait-for-supermajority 21042873 \
    --no-untrusted-rpc \
    --trusted-validator 5D1fNXzvv5NjV1ysLjirC4WY92RNsVH18vjmcszZd8on \
    --trusted-validator 8diJdQj3y4QbkjfnXr95SXoktiJ1ad965ZkeFsmutfyz \
    --trusted-validator ChorusM5BVgnAKbg9PF15285LkqeCoZWK2p9s35T7J2A \
    --dynamic-port-range 8000-8100 \
    --expected-shred-version  55441 \
    --rpc-faucet-address 127.0.0.1:9900 \
    --log -
```

(notably, no `--hard-fork`)

**Comment by mvines** [comment]
🤔 closing as seems unlikely we're going to follow up on this one
