### ISSUE TITLE
bank.capitalization() can overflow

### ISSUE THREAD

**Issue by rwalker-com** [solana-labs/solana#10916]
#### Problem
bank.capitalization is a u64, which could overflow at some point

#### Proposed Solution
promote to a u128 and deal with bank deserialization versioning

**Comment by ryoqun** [comment]
Hehe, I and @svenski123 are working on this, this will be quite easy thing once all foundation (#10581) is merged like this: https://github.com/ryoqun/solana/commit/cd83759b04f835f589de889f1a1e4b420ce5a1b2

**Comment by ryoqun** [comment]
I think this issue can be closed by #11927 because we're checking `bank.capitalization` are under `u64::MAX` periodically now.

Let's revisit this in distant future. :)
