### ISSUE TITLE
v1.1: panicked at ‘FeeCalculator must exist’, core/src/transaction_status_service.rs:65:38

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#10958]
This `.expect()` is reachable by a mainnet-beta validator:
https://github.com/solana-labs/solana/blob/6429042b6e8621e340365752050ae1934bc5aa7e/core/src/transaction_status_service.rs#L65-L71

**Comment by mvines** [comment]
It appears that the bank contained in a `TransactionStatusBatch` message is unfrozen, so bank contents could differ between the time the actual transaction executed and the attempt to fetch the fee_calculator here

**Comment by mvines** [comment]
Sample log: [log.csv.zip](https://github.com/solana-labs/solana/files/4892200/log.csv.zip)

**Comment by CriesofCarrots** [comment]
It seems like we actually need to return the fee collector from transaction commitment to guarantee we have it in TransactionStatusService... maybe as part of the TransactionResults struct `fee_collection_results`?
I'll work up a draft @mvines

**Comment by CriesofCarrots** [comment]
Our api node also experienced this panic, but on a different slot: 
[ba1.log](https://github.com/solana-labs/solana/files/4901567/ba1.log)
