### ISSUE TITLE
InfluxDB: offload client-side dashboard queries with server-side continuous queries 

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#1096]
Our testnet dashboard currently executes a significant number of queries against the metrics server on behalf of the user (and only that user).  We should be able to use  use 
https://docs.influxdata.com/influxdb/v1.6/query_language/continuous_queries/ to perform some of that work for all clients instead, helping to lower the server load.

**Comment by t-nelson** [comment]
We might actually want to look into this soon.  Metrics queries are getting painful
