### ISSUE TITLE
find gossip on leader IP

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#1100]
instead of hardcoding a port on the leader and distributing that, take an IP and sniff around  (in FULLNODE_PORT_RANGE)

- [ ] change --network in bench-tps, drone, and fullnode to accept an IP without a port specifier
- [ ] enhance poll_gossip_for_leader() to iterate through FULLNODE_PORT_RANGE until a valid gossip response comes back
- [ ] don't break other protocols, either:
      - move gossip into its own port range
      - robustify other protocol ports against gossip pings
      - accept gossip pings on all ports
- [ ] simplify multinode scripts, take away the ":8001" assumption

**Comment by mvines** [comment]
I don't think we need to do this anymore, if you disagree please reopen and comment
