### ISSUE TITLE
help devs with abi checks

### ISSUE THREAD

**Issue by rwalker-com** [solana-labs/solana#11047]
#### Problem
 Once one has reproduced an abi  test failure, there's this suggestion in the log output (just an example):
`Confirm the diff by rerunning before and after this test failed with SOLANA_ABI_DUMP_DIR!', runtime/src/serde_snapshot/tests.rs:285:5`

#### Proposed Solution
Three suggestions:
1. have the tests make the DUMP_DIR directory if the env var is set.  When the variable is set and the directory doesn't exist, nothing happens.  Maybe even **_always_** dump for ABI (there's always farf)
2. remove the exclamation point from the log message
3. clarify the steps necessary to compare ABIs (with examples)

**Comment by ryoqun** [comment]
Thanks for suggestions! I'll address these once we land #10914. :)
