### ISSUE TITLE
v1.3: Enable RecentBlockhashes one tick delay fix on mainnet-beta

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#11053]
We need to pick a slot for enabling the `RecentBlockhashes` sysvar one tick update delay for mainnet-beta

https://github.com/solana-labs/solana/blob/5741002a3201d33e01f74f1fe1f7d52726cc41e5/runtime/src/bank.rs#L2925

Context: #11036

**Comment by mvines** [comment]
@t-nelson - time to enable for mainnet-beta?   @jstarry was going to ship a new 1.2 release in a day or two.

**Comment by t-nelson** [comment]
Yep!  Do we have a target epoch for other stuff?  82 sg if not?

**Comment by t-nelson** [comment]
Ah wait... no I forgot this was the one I messed up the enable on testnet for.  Should probably turn it on there for awhile first?

**Comment by mvines** [comment]
Oh, yeah for sure.  Testnet first!  Let's just do this in the v1.3 mainnet-beta timeframe then

**Comment by mvines** [comment]
Nothing much to track here. Once mainnet-beta upgrades to v1.3 we'll flip on the feature
