### ISSUE TITLE
Update rust-bpf-builder to be based on Rust 1.40 or above

### ISSUE THREAD

**Issue by Aaron1011** [solana-labs/solana#11055]
Currently, rust-bpf-builder uses a custom version of Rust based on Rust 1.39: https://github.com/solana-labs/rust-bpf-builder/blob/2ae3f921f65789067963b7d7a41219d0a1997edb/linux/Dockerfile#L66-L69

In Rust 1.40, procedural macros can expand to `macro_rules!` declaration without using `#![feature(proc_macro_hygiene)]`. By basing rust-bpf-builder on a newer version of Rust, we can avoid the need to conditionally apply the `#![feature(proc_macro_hygiene)]` feature gate in https://github.com/solana-labs/solana/pull/10905

**Comment by garious** [comment]
@jackcmay ^^^

**Comment by jackcmay** [comment]
@garious Yup

**Comment by Lichtso** [comment]
I rebased the BPF patches onto Rust 1.46
https://github.com/Lichtso/rust/tree/solana-1.46

It still compiles on macOS, but I haven't done any further testing yet.

**Comment by jackcmay** [comment]
Rust v1.46 is planned for Solana v1.6 and support for v1.50 and incremental upgrades after is in the works
