### ISSUE TITLE
Enable RecentBlockhashes one tick delay fix on testnet

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#11054]
We need to pick a slot for enabling the `RecentBlockhashes` sysvar one tick update delay for testnet

https://github.com/solana-labs/solana/blob/5741002a3201d33e01f74f1fe1f7d52726cc41e5/runtime/src/bank.rs#L2926

Context: #11036

**Comment by t-nelson** [comment]
Closed by #11159

**Comment by t-nelson** [comment]
I botched the enable in https://github.com/solana-labs/solana/pull/11215 :pensive:

**Comment by mvines** [comment]
Already enabled on testnet? https://github.com/solana-labs/solana/blob/838aaee1442b242271d5f48ac13c52860c547065/runtime/src/bank.rs#L3542

**Comment by t-nelson** [comment]
This was enabled in #11258
