### ISSUE TITLE
taper of inflation is based on epoch 0, not the inflation activation epoch

### ISSUE THREAD

**Issue by ryoqun** [solana-labs/solana#11130]
#### Problem

taper of inflation is calculated as if the inflation was enabled since the very start of our cluster (genesis, epoch 0/slot 0). But it isn't true.

So, although initial interest rate is expected to be 15% at the start of inflation, it actually will be about ~14.28% without proper offsetting implementation: https://github.com/solana-labs/solana/blob/0a7cbdf495cea82360f570f0b9317e0024efa340/sdk/src/inflation.rs#L25-L27

As far as I understand the token economy correctly, I think the planned initial inflation rate should be aligned with the _time_ when the inflation is enabled, not the time of birth of our cluster.

#### Proposed Solution

Make it possible to take consider of inflation activation epoch?

CC: @ericlwilliams @mvines @rwalker-com

**Comment by ryoqun** [comment]
slightly related to this (w.r.t. inflation parameters): #5786 #10093

**Comment by rwalker-com** [comment]
assuming the network enables inflation soon, I think the fudge would probably be fine

another approach could be to increase `inflation.initial` so that it's actually 0.15 at inflation X

**Comment by ryoqun** [comment]
@rwalker-com @ericlwilliams I see. Thanks for checking this! Then this issue will be just simple constant changing PR. :)

**Comment by mvines** [comment]
I think there's no expect action needed here.  As we finalize on the inflation rate we'll just adjust the initial values to match the desired % when inflation is activated
