### ISSUE TITLE
`invoke_signed` could unintentionally mark a key as a signer if the instruction contains duplicate keys

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#11169]
#### Problem

`invoke_signed` takes a list of signer seeds and internally calculates the program address based on the invoking program and then marks any matching keys in the instruction as being a signer.  There could be cases where the same generated key is passed multiple times in the same instruction but only one of them should be marked as a signer.  In this case `invoke_signed` will mark them all as signed.

#### Proposed Solution

Pass key indices along with their seeds to explicitly tell `invoke_signed` which key is supposed to be marked as signed.

**Comment by jackcmay** [comment]
@aeyakovenko not convinced if this is an issue we need to fix, thoughts?

**Comment by aeyakovenko** [comment]
@jackcmay the index was necessary only if we want to skip the `create_program_address` calls in the program

**Comment by jackcmay** [comment]
@aeyakovenko so this will suffice: https://github.com/solana-labs/solana/issues/11168
