### ISSUE TITLE
mainnet-beta transaction history: Status and balance-delta metadata potentially store with wrong transaction

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#11191]
#### Problem

As a followup to #10958 we need to triage which transactions may have been stored alongside the wrong status and balance-delta metadata.  This may have occurred in any entries storing a transaction batch with size greater than one.  The effected code was in place through the following commit ranges.

Statuses: 97ca685 - 6c38369
Balance-deltas: 6aaf742 - ca6480a

#### Proposed Solution

Investigate and correct

**Comment by mvines** [comment]
@t-nelson - can you find the lower/upper bound for mainnet-beta slots that might be affected.   With that info we can either:
1) Go in an remove the status metadata for the range
2) Reprocess the range with the fix in place to compute the correct status metadata
I'd default to 1 unless anybody really wants that status metadata (nobody is asking for it so seems unlikely)

**Comment by t-nelson** [comment]
This code was introduce in November 2019, before we lit up MB, so it's pretty much all of it.

The latest first slot that the fixes started on was a bit before 24150000. :grimacing:

**Comment by mvines** [comment]
Oh dang. I was under the impression this was a recent regression.

**Comment by mvines** [comment]
Closing this for now as it's not really actionable.   We'd only re-process the ledger if somebody external raises this issue and has a very good reason
