### ISSUE TITLE
RPC: websocket dependency can cause panic in pubsub service

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#11248]
#### Problem
`ws-rs` logs to stdout when error logging for `ws` is not enabled [[source]](https://github.com/housleyjk/ws-rs/blob/4a981affa5281ea742fbaf4f4f4120876cd2b5b2/src/handler.rs#L64). This [can panic](https://doc.rust-lang.org/std/macro.println.html#panics) if writing to stdout fails.

#### Proposed Solution
- Patch `ws` dependency

**Comment by mvines** [comment]
I'm trying to think of a valid reason why writing to stdout would fail if the host system is configured and running properly

**Comment by t-nelson** [comment]
> I'm failing to think of a valid reason why writing to stdout would fail if the host system is configured and running properly

One way would be if stdout is being piped, and an up-pipe program fails

**Comment by mvines** [comment]
I'd file that under "the host system is not configured and running properly" though ;)

**Comment by mvines** [comment]
Closing as won't fix.  Please log correctly
