### ISSUE TITLE
explorer/: Show owned token transfer history

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#11244]
#### Problem
- Want to see list of token transfers for tokens owned by a particular account

Flow using current (and planned) APIs isn't great:
1. Call `getTokenAccountsByOwner` 
2. Call `getConfirmedSignaturesForAddress` for each token account
3. Call `getConfirmedTransaction` for each confirmed signature

#### Proposed Solution
- Add "Token transfers" tab to account history card
- Display list of detailed transfers (token name, from, to, etc)

Blockers
- Long term ledger history: https://github.com/solana-labs/solana/pull/11222
- New account history RPC API: https://github.com/solana-labs/solana/pull/10928

RPC nice to haves:
- Not possible to query for closed token accounts
- `getConfirmedTransaction` is not batchable
- Many tokens per owner, requires separate request for each token

**Comment by jstarry** [comment]
@mvines I don't think the blockers I listed will affect the MVP. But your account history changes will be really important for this

**Comment by CriesofCarrots** [comment]
Regarding transfer details from `getConfirmedTransaction`: token instruction decoding is in master and v1.2 https://github.com/solana-labs/solana/pull/11281

**Comment by jstarry** [comment]
Token instructions are now viewable on the transaction details page: https://github.com/solana-labs/solana/pull/11443

**Comment by jstarry** [comment]
This can be considered finished because I'm tracking the work to surface CPI transfers here: https://github.com/solana-labs/solana/issues/11754
