### ISSUE TITLE
No RPC API to easily figure rewards for a specific stake or vote account

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#11251]
[getConfirmedBlock](https://docs.solana.com/apps/jsonrpc-api#getconfirmedblock) contains a `rewards` object that can be used to track vote/stake account rewards at a block level, useful for exchange integration.

However this API is very inconvenient to use from a wallet integration perspective, where the wallet is just tracking a handful of stake accounts and wants to be able to present the user with their staking rewards over the last N epochs.

Consider adding a new method that allows the user to query the rewards only for a given stake or vote account

**Comment by CriesofCarrots** [comment]
We have the `getInflationReward` rpc now: #16278
