### ISSUE TITLE
RPC: Cannot setup local integration tests for token RPC endpoints

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#11265]
#### Problem
Want to setup integration tests for token endpoints in the web3 SDK but the hard-coded token program is not present on new nodes. If the SPL token v1.0 is not loaded, the token endpoints return an error when querying for supply and account balance.

#### Proposed Solutions
- Loosen token program check restriction
- Allow specifying a token program id in the RPC endpoint request to ensure the correct token program is being queried
- Publish a snapshot with v1 pre-loaded that can be used in tests

tag @CriesofCarrots

**Comment by mvines** [comment]
How about:
1.  Publish the BPF .so at https://github.com/solana-labs/solana-program-library/releases/tag/token-v1.0.0
2. Augment `solana-genesis` to support including programs 
3. Utilize 1 and 2 in`sdk/docker-solana/build.sh` and `run.sh`

**Comment by CriesofCarrots** [comment]
Memo too, please: https://github.com/solana-labs/solana-program-library/releases/download/memo-v1.0.0/spl_memo.so

**Comment by mvines** [comment]
edge and beta docker images now contain SPL token and memo v1.0.0
