### ISSUE TITLE
RPC: Parsed responses are not very client friendly

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#11357]
##### Account Keys
```json
{
  "accountKeys": {
    "abcd": ["writable", "signer"],
    "efgh": ["signer"]
  }
}
```

##### Parsed accounts
```json
{
  "data": {
    "spl-token": {
      "mint": {}
    }
  },
  "executable": false,
  "lamports": 1169280,
  "owner": "TokenSVp5gheXUvJ6jGWGeCsgPKgnE3YgdGKRVCMY9o",
  "rentEpoch": 5
}
```

##### Parsed instructions
```json
{
  "spl-token": {}
}
```

---

##### Account Keys
```json
{
  "accountKeys": [{
    "pubkey": "abcd",
    "writable": true,
    "signer": true,
  },{
    "pubkey": "efgh",
    "signer": true,
  }]
}
```
I wouldn't expect account keys to be specifically ordered or duplicated here.

##### Parsed accounts
```json
{
  "data": {
    "program": "spl-token",
    "parsed": {
      "type": "mint",
      "info": {
        "decimals": 2,
        "isInitialized": true,
        "owner": "5PBZvfvZ76JMrSjAgimgdSb2C1oL2WhT7xooJVduhCUX"
      }
    }
  },
  "executable": false,
  "lamports": 1169280,
  "owner": "TokenSVp5gheXUvJ6jGWGeCsgPKgnE3YgdGKRVCMY9o",
  "rentEpoch": 5
}
```
All parsed accounts should follow a common structure with "program" and "parsed" as top level keys. Anything inside "parsed" is program specific but should generally aim to provide a common top-level structure for all account types/states

##### Parsed instructions
```json
{
  "program": "spl-token",
  "programId": "TokenSVp5gheXUvJ6jGWGeCsgPKgnE3YgdGKRVCMY9o",
  "parsed": {
    "type": "transfer",
    "info": {
      "amount": 1,
      "destination": "6G1hpMMGnGWAD5B7GaSMQEZZNuj1uma57ayVYxXWbkJJ",
      "authority": "Drz9WPMnJumHR3s1ecSBkLUybVwnpMHDbTWsUb4hSKQH",
      "source": "9DrMHtmBSE1JPAN78ZUt3XQ4dPaUsnAmnwwf4ABbne4o",
    }
  }
}
```
All parsed instructions should follow a common structure with "program" and "parsed" as top level keys. Anything inside "parsed" is program specific but should generally aim to provide a common top-level structure for all instruction types

```json
{
  "programId": "TokenSVp5gheXUvJ6jGWGeCsgPKgnE3YgdGKRVCMY9o",
  "accounts": [
    "6G1hpMMGnGWAD5B7GaSMQEZZNuj1uma57ayVYxXWbkJJ",
    "Drz9WPMnJumHR3s1ecSBkLUybVwnpMHDbTWsUb4hSKQH",
    "9DrMHtmBSE1JPAN78ZUt3XQ4dPaUsnAmnwwf4ABbne4o"
  ],
  "data": "abasdaf3f23f",
}
```
Since accountKeys is not ordered / duplicated, unparsed instructions should hydrate accounts / programId with address strings

**Comment by garious** [comment]
Are you thinking of implementing this client-side or in solana_core?

**Comment by CriesofCarrots** [comment]
In solana. We already optionally return this decoded data; this is a formatting update.

**Comment by garious** [comment]
Why do parsing on the backend? Can we deploy this functionality via a wasm library?

**Comment by jstarry** [comment]
I imagine it's because we expect to have non-JS clients which need to easily decode token accounts and instructions. Wasm library works fine for the explorer.
