### ISSUE TITLE
Add beta and stable versions of solanalabs/rust-nightly docker image

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#1136]
We need beta and stable channel versions of the solanalabs/rust-nightly docker image, and all other docker images used in CI (see `ci/buildkite.yml` for the list).   Currently we reuse the same image across all release channels and that leads to inevitable bustage (eg, v0.7 nightly is broken now because we just updated the docker image)

cc: #701

**Comment by garious** [comment]
@mvines, got time to take this ticket yourself before 0.8?
