### ISSUE TITLE
RPC: Query account history newer than specific signature

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#11446]
#### Problem
The `getConfirmedSignaturesForAccount2` allows searching `before` a certain signature but doesn't support searching recent history up `until` a signature that you already have. Using `until` is useful when refreshing the explorer UI to check if any new signatures have been confirmed since the last fetch (common operation). Clients need to refresh with no params and dedupe but there could be gaps in fetched history.

#### Proposed Solution
Add `until` option which works with together with `before` / `limit`

tag @mvines

**Comment by jstarry** [comment]
Not blocked, the explorer can just replace the last fetched results with new results for now

**Comment by mvines** [comment]
BigTable doesn't support reverse scanning of rows, https://cloud.google.com/bigtable/docs/reads#reverse-scan, so that makes adding a generic `after` hard.

What I think we can do easily though is add `until: Signature`.   This would work in conjunction to the existing `before` and `limit` options:   Search stops when `limit` signatures are found or the `until` is reached.

**Comment by mvines** [comment]
This would be a good issue for somebody not me to work on, to get another pair of eyes through the `storage-bigtable/` crate.    We'll need to make some small changes in how we do the gRPC queries to add the end qualifier (`until` value)

**Comment by CriesofCarrots** [comment]
> This would be a good issue for somebody not me to work on, to get another pair of eyes through the `storage-bigtable/` crate. We'll need to make some small changes in how we do the gRPC queries to add the end qualifier (`until` value)

✋ I'd like to dig into bigtable.

**Comment by mvines** [comment]
Sold!  It looks pretty easy to implement.
