### ISSUE TITLE
Snapshot/Account operations in set_root() are taking more time as number of accounts grows

### ISSUE THREAD

**Issue by carllin** [solana-labs/solana#11456]
#### Problem
Not a major issue yet, but things to keep an eye on:

1) @t-nelson noticed Devnet is dead at 3 million accounts due to accounts hash generation taking 500 seconds: https://metrics.solana.com:8888/sources/3/chronograf/data-explorer?query=SELECT%20mean%28%22hash_accumulate%22%29%20AS%20%22mean_hash_accumulate%22%2C%20mean%28%22accounts_scan%22%29%20AS%20%22mean_accounts_scan%22%20FROM%20%22devnet%22.%22autogen%22.%22update_accounts_hash%22%20WHERE%20time%20%3E%20now%28%29%20-%206h%20GROUP%20BY%20time%28%3Ainterval%3A%29%20FILL%28null%29

2) On Tds, with 150k accounts set_root() currently takes about 600-800 ms due to 
     a) accounts hash generation
     b) `add_snapshots()` takes roughly `400ms` https://metrics.solana.com:3000/d/monitor-edge/cluster-telemetry-edge?refresh=60s&orgId=2&var-datasource=Solana%20Metrics%20(read-only)&var-testnet=tds&var-hostid=5D1fNXzvv5NjV1ysLjirC4WY92RNsVH18vjmcszZd8on&from=now-1h&to=now&panelId=43&fullscreen&edit. I suspect the time mostly in here: https://github.com/solana-labs/solana/blob/master/runtime/src/serde_snapshot/future.rs#L234-L244. The remainder of the work here: https://github.com/solana-labs/solana/blob/master/runtime/src/serde_snapshot/future.rs#L255-L262 seems to only take 30-40ms. @ryoqun 

#### Proposed Solution
1) Accounts hash calculation can be moved into background
2) Throw more threads at the serialize? Not sure if the serialization of `AccountStorageEntry`'s can be safely offloaded from the main pipeline as well.

**Comment by ryoqun** [comment]
@carllin maybe is this partly solved by #12787 ?

**Comment by carllin** [comment]
@ryoqun yeah! the accounts hash calculation is backgrounded by https://github.com/solana-labs/solana/pull/12852
and the serialize of `AccountStorageEntry` is backgrounded by https://github.com/solana-labs/solana/pull/12194
