### ISSUE TITLE
web3.js:  PublicKey.createProgramAddress() does not create valid program addresses

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#11465]
PublicKey.createProgramAddress() needs to be updated to match #11323

**Comment by jackcmay** [comment]
@mvines, https://github.com/solana-labs/solana/pull/11355 fixes this issue afaik, was there anything else?

**Comment by mvines** [comment]
Oh nice.  I think just re-enabling this then:
https://github.com/solana-labs/solana-program-library/blob/b619da32aea7b2898d1fe2faf4cdc7dba99df164/ci/script.sh#L96-L102

There's also this problem:
https://github.com/solana-labs/solana-program-library/blob/b619da32aea7b2898d1fe2faf4cdc7dba99df164/ci/script.sh#L59-L60

**Comment by jackcmay** [comment]
On the latter, yeah, looking into that to provide a clearer picture to developers

**Comment by mvines** [comment]
Nothing more to do here
