### ISSUE TITLE
RPC: Token account decoding issues

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#11471]
#### Problem
1. When encoding token accounts to JSON in RPC, `tokenAmount` is a `UiAmount` but `delegatedAmount` is a number. They should be treated the same.

2. The `delegate` property is returning `null` when unset. I would expect it to be omitted.

**Comment by CriesofCarrots** [comment]
Would you expect `delegatedAmount` to also be omitted when zero?

**Comment by jstarry** [comment]
Hmm sounds reasonable to me. Seems like delegatedAmount should always be present when delegated is present. Not sure if it can be 0 when delegated is set

**Comment by CriesofCarrots** [comment]
👍 

> Not sure if it can be 0 when delegated is set

Shouldn't ever be. Delegated and delegatedAmount get set/unset in tandem (approve, revoke), and delegated gets set to None when delegatedAmount reaches zero via Transfers
