### ISSUE TITLE
Migrate beta testnet buildkite setup to net/ after v0.8 branches from master

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#1151]

**Comment by garious** [comment]
You mentioned last week you're on DevOps strike this week. Is there someone else that would know how to move this ticket forward before Friday's release?

**Comment by mvines** [comment]
I’ve be more than happy to help somebody who wants to play with the buildkite/gcp setup to do this.  It’s maybe a 5min job once we branch (assuming nothing goes wrong)

**Comment by garious** [comment]
Let's try to get both me and @rob-solana comfy with this process.

**Comment by mvines** [comment]
So I did this.  Sry
