### ISSUE TITLE
v1.3: Enable retirement of rent collect in Bank::deposit() on mainnet-beta

### ISSUE THREAD

**Issue by ryoqun** [solana-labs/solana#11545]
#### Problem

this needs to be updated for mainnet-beta:

for v1.2 branch
https://github.com/solana-labs/solana/blob/e477501687d764bee98ed8fb1b14a6a91faae8a7/runtime/src/bank.rs#L2299

for v1.3 branch
https://github.com/solana-labs/solana/blob/53e917b54f6ba7c74cb7a1b3f1f072cb7226b3b0/runtime/src/bank.rs#L2549

#### Context

#10468 

#### Cousin

#11543

**Comment by ryoqun** [comment]
Enable this after #11543 is applied on the testnet and some time passed.

**Comment by mvines** [comment]
@ryoqun - since rent is 100% burned on mainnet-beta this seems quite low risk to enable, and @jstarry was going to ship a new 1.2 release in a day or two.   Should we get this out of the way?

**Comment by ryoqun** [comment]
How about early next week? (I can do by myself now that I'm release ninja!) Or is it too frequent for stable release channel? As you said, it's pretty very low risk. But I want to confirm my belief backed by some evidence. Humans (including me) tend to think in an optimistic way, which oftentimes is betrayed by terse reality. And I think there is no pressure to hurry up this.

We would look bad if we killed the mainnet-beta bending the rule of gated release (testnet then mainnet-beta).

**Comment by mvines** [comment]
> How about early next week? 

Sure.  We just want to give the mainnet-beta validators at least 2-3 days to upgrade.

> We would look bad if we killed the mainnet-beta bending the rule of gated release (testnet then mainnet-beta).

I was thinking this was already enabled on testnet.  But is that not the case?

**Comment by ryoqun** [comment]
> Sure. We just want to give the mainnet-beta validators at least 2-3 days to upgrade.

Noted. :)

> I was thinking this was already enabled on testnet. But is that not the case?

it's not. It will be enabled at epoch 97 (released in v1.3.10) along with other gated changes (totalling to 3): https://github.com/solana-labs/solana/milestone/132?closed=1, https://github.com/solana-labs/solana/projects/58.

**Comment by mvines** [comment]
Ah, got it.  Let's do this later then for mainnet-beta, in the v1.3 timeframe

**Comment by mvines** [comment]
@ryoqun - I think you have the feature keypair for this right?  Please feel free to activate it when mainnet-beta ready

**Comment by ryoqun** [comment]
> @ryoqun - I think you have the feature keypair for this right? Please feel free to activate it when mainnet-beta ready

@mvines roger! finally this is getting some care: https://github.com/solana-labs/solana/pull/12842 (well, we must first port this to runtime feature...)
