### ISSUE TITLE
v1.3: Upgrade loader on mainnet-beta

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#11568]
#### Problem

Needs to be updated for mainnet:

https://github.com/solana-labs/solana/blob/9290e561e1babdfb0f48abf43fb88dd397788ea0/genesis-programs/src/lib.rs#L68

And a collection of PRs must be backported

- [x] #10528
- [ ]  #11384
- [x]  #11460
- [ ]  #11516
- [ ]  #11571
- [ ]  #11649
- [x]  #11651
- [ ]  #11652
- [ ]  #11656
- [ ]  #11657
- [x]  #11658 
- [ ] #11675
- [ ]  #11695
- [ ]  #11717
- [x] #11745
- [ ] #11750
- [ ] #11808
- [ ] #11864

**Comment by ryoqun** [comment]
@jackcmay FYI, I'm stacking https://github.com/solana-labs/solana/pull/12068 to this list. (After all of the above prs are backported into v1.2, I can backport #12068 by myself).

**Comment by jackcmay** [comment]
@ryoqun We are probably going to forgo this port into 1.2 and just wait for 1.3 on mainnet

**Comment by ryoqun** [comment]
> @ryoqun We are probably going to forgo this port into 1.2 and just wait for 1.3 on mainnet

Oh, i see!

**Comment by mvines** [comment]
Nothing much to track here.  Once mainnet-beta upgrades to v1.3 we'll flip on the new bpfloader2 feature
