### ISSUE TITLE
RPC: getConfirmedSignaturesForAddress2 is returning unconfirmed signatures

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#11611]
#### Problem
`getConfirmedSignaturesForAddress2` is returning unconfirmed signatures

https://explorer.solana.com/address/BcXxdfGjVQY3aYYGASigp5oSPcuh19hgJNeW3Bt1xkYx
![Screen Shot 2020-08-13 at 5 09 31 PM](https://user-images.githubusercontent.com/1076145/90116318-e5908a80-dd87-11ea-9584-0f6f05440401.png)

In the above example, slot 28248977 is not confirmed. It was obvious something was up when a duplicate signature was returned for a different block 😬 

#### Proposed Solution
- Filter out unconfirmed signatures

cc @CriesofCarrots @mvines

**Comment by CriesofCarrots** [comment]
<img width="1180" alt="image" src="https://user-images.githubusercontent.com/3030561/90187552-321f9a00-dd77-11ea-8f59-a6ba9647aad7.png">
