### ISSUE TITLE
Panic when opening the ledger

### ISSUE THREAD

**Issue by vkomenda** [solana-labs/solana#11629]
#### Problem

```
[2020-08-14T11:47:23.158650638Z INFO  solana_ledger::blockstore] Opening database at "~/validator-ledger/rocksdb"
thread 'main' panicked at 'Failed to open ledger database: RocksDb(Error { message: "Corruption: SST file is ahead of WALs" })', core/src/validator.rs:610:14
```

#### Proposed Solution

Handle the error?

**Comment by sakridge** [comment]
`--wal_recovery_mode skip_any_corrupted_record` should get around this. Potentially that could be the default or fallback to that after asking the user.

**Comment by mvines** [comment]
@sakridge - why reason to not make this the default?

**Comment by sakridge** [comment]
> @sakridge - any reason to not make this the default?

Just that we don't understand any side-affects that well. @carllin do you think it's safe?

**Comment by carllin** [comment]
Hmmm, if it's dropping the record, that's much better than persisting a corrupted one. 

So essentially the question is can anything terrible happen if I randomly remove data from columns in Rocks (roots, shreds, transaction statuses, etc)?

There could be some very subtle cases, but I think most of the time it would at worst prevent progress on your local node, so I think it's ok.
