### ISSUE TITLE
Leader node OOMing after ~15min on master testnet

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#1164]
STR:
1. Goto https://metrics.solana.com:3000/d/testnet/testnet-hud?panelId=38&orgId=2&var-testnet=testnet-master
2. Observe the OOM on the leader node ~15min after the master testnet redeploys every hour

The testnet then goes dark until the next redeploy.

**Comment by sakridge** [comment]
Log from heaptrack:

[heaptrack.log.zip](https://github.com/solana-labs/solana/files/2368538/heaptrack.log.zip)

**Comment by sakridge** [comment]
[heaptrack.log.zip](https://github.com/solana-labs/solana/files/2368540/heaptrack.log.zip)

**Comment by rob-solana** [comment]
looks like the blob recycler fixes got us to 35 minutes, and once crashed, we have an unrecoverable ledger on leader

**Comment by sakridge** [comment]
Seems that heaptrack points to a banking_stage::process_packets allocation which is growing very large.

**Comment by rob-solana** [comment]
per the Discord discussion:
```
@sakridge
write_stage seems to get just further and further behind:
 INFO 2018-09-17T22:37:34.028362894Z: solana::write_stage: write_stage entries: 7608
 INFO 2018-09-17T22:37:46.351789725Z: solana::write_stage: write_stage entries: 14456
 INFO 2018-09-17T22:38:11.270759336Z: solana::write_stage: write_stage entries: 28443
INFO 2018-09-17T22:38:54.305099111Z: solana::write_stage: write_stage entries: 50351
INFO 2018-09-17T22:40:09.392122359Z: solana::write_stage: write_stage entries: 90871
```

write_stage is the system's bottleneck, which causes the channel between it and record_stage to grow without bound

to fix (ameliorate): move everything but ledger_writer stuff out of write_stage

1. move register_last_id() back to as early as possible that has "entry"
2. move to_blobs() to broadcast stage
3. have record_stage send entries to both broadcast and write_stage (which will address #1238) 

After this, we may still be disk-limited, necessitating a multi-threaded ledger (woo-hoo!)

**Comment by rob-solana** [comment]
I think we should also move "having an entry" back to banking_stage

**Comment by garious** [comment]
@sakridge, @pgarg66, @rob-solana, can you update this ticket?

**Comment by pgarg66** [comment]
We are still depleting memory on the leader. The leader runs out of memory in ~1hr time (with our default testnet configuration)

We fixed some bugs (in PRs tagged with this issue).

My current analysis points at PacketRecycler causing the depletion of memory. I have added some statistics to the recycler to see when it's allocation more memory from heap, instead of reusing it from landfill. The jumps in RAM usage correspond to the jump in these statistics.

I am analyzing the code (from fetch stage -> sigverify -> banking stage) to see if I can spot any leaks.

**Comment by pgarg66** [comment]
I am seeing some weird behavior with PacketRecycler. It seems to allocate more recyclables from heap every 10 minutes. See this graph:

Purple line is the allocation from heap. Blue line is size of recycler at the time an entry is dropped.

<img width="1394" alt="screen shot 2018-09-25 at 5 53 33 pm" src="https://user-images.githubusercontent.com/40076733/46051218-fcbf2400-c0ec-11e8-93b8-da1101319f96.png">

**Comment by pgarg66** [comment]
I disabled recycler (by not adding recyclables back to landfill). The memory usage on leader is below 5% for last 20 minutes. Also TPS seems to be better (160K). It does not suggest that recycler have a memory leak. But, maybe the size of recycler is just growing due to some condition.

**Comment by mvines** [comment]
re-opening, self-assigning to validate on 0.9 branch

**Comment by mvines** [comment]
Looks good on 0.9
