### ISSUE TITLE
Setup nightly testnet performance automation

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#1168]
On the master branch let's run a nightly performance test where we spin up hundreds of nodes and dozens of client benchers to stress the network as hard as possible for a while.  

1. Duration of the test should be ~10min or so (bounded by instance pricing and cloud provider DoS detectors that are not properly tuned for our network usage patterns)
2. Number of nodes should be highly tunable.  We start at a stable number, and over time crank up the numbers
3. Reporting goes to InfluxDB so that we have a standard metrics dashboard for the result
4. Use Kapacitor to setup alerts for when key metrics are different than the expectations
5. Nice to have: at the end of each run, collect key metrics from InfluxDB and submit a report message to Discord so people can effortlessly observe the nightly result.

**Comment by garious** [comment]
@pgarg66, fyi

**Comment by pgarg66** [comment]
Moving it to Tabletop, given instability we are fighting with the current testnet.

**Comment by mvines** [comment]
Done, see this morning's run at https://metrics.solana.com:3000/d/testnet/testnet-hud?orgId=2&var-testnet=testnet-edge-perf&from=1542031477893&to=1542034960126

TPS in this run is terrible, which is being tracked at #1741
