### ISSUE TITLE
BpfLoader211111... programs can't CPI into BpfLoader111111.. programs

### ISSUE THREAD

**Issue by hendrikhofstadt** [solana-labs/solana#11686]
#### Problem

fetch-spl.sh uses the deprecated BpfLoader11111 which breaks the default SPL programs when launched via the runscript.

#### Proposed Solution

SPL in the runscript should compiled for and use the new BpfLoader211111.

**Comment by mvines** [comment]
Hmm, that's strange.  `fetch-spl.sh` downloads the 1.0.0 version of the SPL programs, which require the old loader and will not work with the new loader.  Maybe something else is going on in your environment @hendrikhofstadt?

**Comment by hendrikhofstadt** [comment]
@mvines Technially it's "working" but I can't CPI into the old token program. I misworded the issue I think.

Are there plans to support CPI between incompatible BPFLoader versions?

**Comment by mvines** [comment]
Ah, that makes sense.  Yes we need to support that, since we can't force spl-token 1.0.0s to upgrade.  I fixed the title of the issue to reflect this.
