### ISSUE TITLE
v1.3: Enable stricter check on rent-exempt accounts on mainnet-beta

### ISSUE THREAD

**Issue by ryoqun** [solana-labs/solana#11682]
#### Problem

this needs to be updated for testnet:
https://github.com/solana-labs/solana/blob/e2626dad83e597cbb769e0033fdc3ee597a910ec/runtime/src/rent_collector.rs#L68

#### Context

#11342 

#### Cousin

#11681

**Comment by mvines** [comment]
@ryoqun - same here?  Time to enable this feature too?

**Comment by ryoqun** [comment]
@mvines same here: https://github.com/solana-labs/solana/issues/11545#issuecomment-692925600

**Comment by mvines** [comment]
Let's rewrite this feature activation in `FeatureSet` before activating it.
