### ISSUE TITLE
Transaction simulation failure drops the logs the user needs to debug

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#11699]
#### Problem

Simulate transaction drops the logs the user needs to debug:

https://github.com/solana-labs/solana/blob/46830124f8b98c72ff58e6e1c723fb1cbdb75e4e/core/src/rpc.rs#L2137

#### Proposed Solution

Return those logs to the user

**Comment by mvines** [comment]
I think you're looking at the wrong spot.   The simulate transaction in `sendTransaction` is intended to be a sanity check before transmitting actually the transaction, it's not for debugging purposes.

However the `simulateTransaction` endpoint is exactly intended for debugging purposes, and the transaction logs are returned to the caller:
https://github.com/solana-labs/solana/blob/46830124f8b98c72ff58e6e1c723fb1cbdb75e4e/core/src/rpc.rs#L2182
