### ISSUE TITLE
RPC: singleSlot signature notification has incorrect slot

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#11739]
#### Problem
When confirming the same tx on 3 different commitment levels, I noticed that `singleGossip` returned a different slot than the other levels
```
1597939048079 "[recent] confirmed tx (landed in slot: 31669131)"
1597939048137 "start processing slot" 31669132
1597939048384 "[single] confirmed tx (landed in slot: 31669131)"
1597939048385 "start processing slot" 31669133
1597939048572 "[singleGossip] confirmed tx (landed in slot: 31669132)"
```

This was the confirmed transaction:
https://explorer.solana.com/tx/2QuKxp2dqvKuL3QNCzb1VcHqoogcpadiv15WwyderCoN7A5cqiirCh34bj9FjvNBbj64KfNT2rrQR2oXu13P6E8y?cluster=testnet

`31669132` is incorrect. It is a confirmed block but it doesn't contain the tx that I was confirming.

#### Proposed Solution
Return the correct slot that a transaction landed in with `singleGossip` commitment

**Comment by jstarry** [comment]
Actually `single` is sometimes different too. I believe `recent` is the only reliable one but not positive.

**Comment by jstarry** [comment]
Never mind this context slot is not saying when the tx was processed, it's saying what the current slot is when the notification is sent

**Comment by CriesofCarrots** [comment]
Lol, just typing that 👆

**Comment by jstarry** [comment]
🤦
