### ISSUE TITLE
explorer: Users can't tell if their transaction has expired

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#11755]
# Problem

User's can't tell if their transaction has expired.

# Solution

Explorer should show root block (not slot) height.  After 120 roots the TX is invalid.

**Comment by jstarry** [comment]
We now have an API for checking if a recent blockhash has expired here: https://docs.solana.com/developing/clients/jsonrpc-api#getfeecalculatorforblockhash

Tricky part is that we probably won't have a transaction status at all for an unconfirmed transaction signature so `/tx/<SIGNATURE>` wouldn't be enough. Might need to pass more transaction details from the client to show a proper "Transaction Status" page which transitions from "Pending" to "Expired" based on the recent blockhash
