### ISSUE TITLE
explorer: Add support for all parsed accounts

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#11768]
#### Problem
The RPC API decodes many account types and returns them as JSON but the explorer doesn't support displaying them nicely yet

#### Proposed Solution
Add support for
- [ ] Vote accounts
- [ ] Nonce accounts
- [ ] Sysvar accounts
- [ ] Config accounts

**Comment by oJshua** [comment]
![index-tsx-explorer-Code-OSS](https://user-images.githubusercontent.com/188792/91225171-fe7a3380-e6d7-11ea-9320-f43069674a5b.png)

Rounding out the types / validators of each kind of account. I imagine these are destined for the web3 sdk, but we can at least get them mapped out here first.
