### ISSUE TITLE
explorer: Cannot easily determine epoch of a transaction's slot

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#11763]
#### Problem
It's useful to know the epoch of the slot of a transaction to know which feature switches were active during transaction processing

#### Proposed Solution
- Change `Block` label to `Slot`
- Calculate epoch from transaction slot
- Display epoch on transaction details page

**Comment by jstarry** [comment]
@jackcmay why would it be useful to know the epoch for a transaction? Something related to epoch feature switches?

**Comment by jackcmay** [comment]
Yup

**Comment by mvines** [comment]
`solana feature status` neatly solves the problem here in a different way, so closing the issue
