### ISSUE TITLE
explorer: Remove dependency on solana beach API

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#11771]
#### Problem
We currently use the solana beach api for:
- real time transaction count
- average tps and blocktime
- tps history

But it's not ideal to have an external dependency that we can't fix quickly if something gets broken

#### Proposed Solution
Build Solana equivalents of these APIs and migrate explorer to use those instead

**Comment by oJshua** [comment]
@jstarry This might be a good one for me to tackle next. Did you envision using the same socket.io-style api (drop in replacement for solana beach) or is there an existing service we might attach this to?

**Comment by jstarry** [comment]
@oJshua we have an [existing jsonrpc pubsub service](https://github.com/solana-labs/solana/blob/master/core/src/rpc_pubsub.rs) which we could add to. Some of these APIs may need some sort of backing time series db for historical calculations, which we don't have a precedent for

**Comment by oJshua** [comment]
Just spoke with @mvines about writing tps averages per minute to RocksDB. Should do the trick.

**Comment by aditya-manit** [comment]
Hey, is there any doc on all the apis provided by solana beach?

**Comment by mvines** [comment]
👋🏼  Solana Beach is provided by Staking Facilities, so separate organization.  As far as I know they haven't published a public API
