### ISSUE TITLE
wallet: add a raw command-line interface to issue transactions 

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#1184]
Let’s add a wallet subcommand that makes it possible to issue a raw Transaction from the shell.

signature and last_id are generated at runtime, but the rest of Transaction,
https://github.com/solana-labs/solana/blob/9e6d3bf532dd16c3a93962bfbcb8c05fbcbeee45/src/transaction.rs#L81, can be reflected out to the cli.

Wallet is perhaps not the best home for this but it seems most convenient at the moment.

**Comment by mvines** [comment]
Quick note since I'm thinking about it: `key[0]` should be implicit as it's always the wallet's key (and who signed the Transaction)

**Comment by garious** [comment]
@mvines, does anything depend on this?

**Comment by mvines** [comment]
No, not at the moment.  We can boot this from 0.10 for now.

**Comment by garious** [comment]
Cool, I also unassigned @CriesofCarrots. No need for individual backlogs.

**Comment by mvines** [comment]
I don't think this is too useful anymore
