### ISSUE TITLE
TdS incident 2020-08-28

### ISSUE THREAD

**Issue by leoluk** [solana-labs/solana#11882]
TdS halted after a sufficient quantity of validators went down due to RPC flooding (?)

Our logs are at http://logbin.certus.one:8080/Qui9iehu/solana-github-11882/Ft5fbkqNa76vnsjYNwjDZUXoTWpP7VYm3mtsaQckQADN.log.xz

![image](https://user-images.githubusercontent.com/859697/91511178-66e73180-e8df-11ea-9755-4f6602d5f7a1.png)

![image](https://user-images.githubusercontent.com/859697/91511339-bded0680-e8df-11ea-9aae-f693b7aca882.png)

![image](https://user-images.githubusercontent.com/859697/91512952-749eb600-e8e3-11ea-985b-d1118ddf7369.png)

**Comment by c29r3** [comment]
![image](https://user-images.githubusercontent.com/52304443/91509445-e9252500-e8e2-11ea-9213-49a6cf74f00f.png)

**Comment by leoluk** [comment]
Some context for anyone stumbling upon this issue: RPC isn't currently built to be safe to expose to the outside world. On mainnet, nobody exposes their validator's RPC ports. The public mainnet RPC nodes are behind load balancers that expose a subset of endpoints with rate limits which prevent such simple DoS attacks.

On TdS, RPC is open for debugging purposes with an informal agreement to all be nice and not abuse it. This needs to be documented somewhere so we won't get woken up by this again :-)

Relevant prior discussions:

https://github.com/solana-labs/solana/issues/5778

https://github.com/solana-labs/solana/issues/6291

https://github.com/solana-labs/solana/issues/8862
