### ISSUE TITLE
explorer: Improve display of Serum dex program instructions

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#11937]
#### Problem
Serum instructions show up as "Unknown" in the explorer. It would be nice to do a little bit of parsing to at least show what type of instruction they are.

Example: https://explorer.solana.com/tx/5uAPWj9WNWKrKxTx6YXCoWJCSuuaUZWi43h9zv6WurFjaaX3SxNqKaEc6nZCZbXffKEMgNYrEhjrVHfCLtaCK4dR

#### Proposed Solution
Parse few bytes of instruction data to determine instruction type:

```
0:  Initialize Market
1:  New Order
..  Match Orders
    Consume Events
    Cancel Order
    Settle Funds
    Cancel Order By Client Id
    Disable Market
    Sweep Fees
```

**Comment by oJshua** [comment]
https://github.com/solana-labs/solana/pull/11985
