### ISSUE TITLE
explorer: Token history table doesn't show inner token instructions

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#11935]
#### Problem
Some instruction types never load correctly on this page:

https://explorer.solana.com/address/BpU4BSqq8FVcZYrtparzH2gqx2CPx1TbXpTG3UAoKb2M/tokens

![Screen Shot 2020-08-31 at 5 46 17 PM](https://user-images.githubusercontent.com/1076145/91707070-e2800180-ebb1-11ea-9b1e-01800492f390.png)

#### Proposed Solution
- Investigate cause and fix

**Comment by oJshua** [comment]
@jstarry This happens when none of the parsed instructions match the SPL token program. My initial solution was to provide an "Unknown" instruction type. Do you know if there are any other types of instruction types (associated with other program IDs) I might need to watch for? 

![failed-instruction-parse](https://user-images.githubusercontent.com/188792/92142627-fcdff800-edc8-11ea-94b1-ef57563981aa.png)

**Comment by jstarry** [comment]
@oJshua you can check out what RPC is using for the enum and corroborate. What is the RPC call returning for these unknown instructions?

**Comment by jstarry** [comment]
Hey @oJshua I realized I didn't follow exactly what you were saying before..

> This happens when none of the parsed instructions match the SPL token program. My initial solution was to provide an "Unknown" instruction type.

Yeah, this is fine for now. The reason is because the these non-parsed instructions are invoking inner SPL Token instructions which are not yet surfaced in the API. Soon!

> Do you know if there are any other types of instruction types (associated with other program IDs) I might need to watch for?

Nope, just a CPI thing

**Comment by jstarry** [comment]
I was tracking down a separate bug in token history where fetching more results caused strange behaviour and while in the area I made your change to display these instructions as "Unknown (inner)". I think we can leave this issue open though because we need a better fix once inner instruction details are available

**Comment by jstarry** [comment]
To close this issue, I think we need to be able to expand instructions in the UI which have inner token instructions
