### ISSUE TITLE
explorer: Do not report errors when block time is pending

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#11964]
#### Problem
The web3 `getBlockTime` method throws an error when a new block is fetched because the block time is not yet available. This is very common for recently sent transactions and so should not be considered to be an issue.

Related to: https://github.com/solana-labs/solana/issues/11963

#### Proposed Solution
- Detect when block time is just not available yet in order to not report an error
- Display "Pending" text instead of "Unavailable" in UI

**Comment by CriesofCarrots** [comment]
Explorer is no longer in this repo.
