### ISSUE TITLE
web3: Differentiate between getBlockTime errors

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#11963]
#### Problem
The `getBlockTime` endpoint returns two different errors when block time is unavailable

This error should be treated as an issue and fixed upstream. Issue: https://github.com/solana-labs/solana/issues/10089
```
code: -32001
message: "Block 14265592 cleaned up, does not exist on node. First available block: 28031964"
```

This error is usually temporary. The most common case is that the slot is too new to have a block time.
```
code: -32004
message: "Block not available for slot 33522758"
```

#### Proposed Solution
- Bubble up error so that clients can distinguish between the two errors and handle them separately. In the explorer, it would be nice to say that block time is either "Unavailable" or "Pending"
- Fix struct validation so that errors can bubble properly (`value` is expected but not set for errors as seen below)

```
{
  "jsonrpc": "2.0",
  "error": {
    "code": -32001,
    "message": "Block 14265592 cleaned up, does not exist on node. First available block: 28031964"
  },
  "id": "996d99da-f4fe-4c77-9fbb-5c0619c7d13c"
}

**Comment by roccomuso** [comment]
Why some slots are unavailable? doesn't solana validator keep and index all the blocks?

**Comment by jstarry** [comment]
> doesn't solana validator keep and index all the blocks?

Nope, the storage needed grows pretty quickly so validators only keep blocks for at most a week or two.

> Why some slots are unavailable?

1. New slots take some number of seconds to get timestamped
2. Until [recently](https://github.com/solana-labs/solana/pull/11955), block timestamps were computed on demand based on stake weight and the stake weight info wasn't readily accessible for computing older timestamps.

**Comment by roccomuso** [comment]
@jstarry I got it.
When will #11955 land in `https://api.mainnet-beta.solana.com` ?

**Comment by jstarry** [comment]
@roccomuso probably in a week or so. Need to upgrade mainnet from the v1.2 release line to v1.3

**Comment by CriesofCarrots** [comment]
@steveluscher , is this issue still relevant? If so, I will transfer it to the right repo.

**Comment by CriesofCarrots** [comment]
I'm closing this issue as no longer needed. It can be re-opened in https://github.com/solana-labs/solana-web3.js if the bothersome behavior still exists.
