### ISSUE TITLE
RPC: Unable to fetch details for some transactions

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#11962]
#### Problem
All transactions should be queryable via RPC / BigTable but some transactions only have status available, the details are unavailable.

Example: 
https://explorer.solana.com/tx/2tznUL45CJa9nZrx6BZVX87rK1xSJ2u6YaKBbnh59Eg37nw4dT6VvvpBHUYJmn6B82VGeibMpuBuSyhyjLVXP2ZD

#### Proposed Solution
Investigate if there is a hole in BigTable ledger history for transaction details

**Comment by jstarry** [comment]
@mvines @CriesofCarrots this is unexpected right?

**Comment by mvines** [comment]
It's expected.  Parts of the the history is missing status information.

**Comment by jstarry** [comment]
> It's expected. Parts of the the history is missing status information.

Did you mean "details" information?

**Comment by jstarry** [comment]
So nothing to do here? I'll close if that's the case

**Comment by mvines** [comment]
Yeah nothing to do here IMO. To fix we'd literally need to reprocess the ledger from 0.  Not worth it :)
