### ISSUE TITLE
RPC: getTokenLargestAccounts should return owner of accounts

### ISSUE THREAD

**Issue by oJshua** [solana-labs/solana#11970]
#### Problem
Explorer currently displays the largest accounts associated with an SPL token. One of the columns displayed, alongside the address and balance, is the owner. Currently, this requires an additional RPC call (getParsedAccountInfo) for each row returned by getTokenLargestAccounts, in order to fetch the owner pubkey. 

![largest-distribution](https://user-images.githubusercontent.com/188792/92018719-5cc39980-ed0a-11ea-8e20-2078d77b6a00.png)

#### Proposed Solution
Provide the owner for each of the largest accounts.

**Comment by CriesofCarrots** [comment]
@oJshua , can you please expand "Problem" to describe the actual (product-level) problem that would be solved by including that data in the RPC response?

**Comment by oJshua** [comment]
> @oJshua , can you please expand "Problem" to describe the actual (product-level) problem that would be solved by including that data in the RPC response?

Sure thing!

**Comment by leonardgee** [comment]
Any update on this? Could use this improvement!

**Comment by leonardgee** [comment]
Additionally, will it be possible to make the number of tokens account configurable? I saw in the rpc implementation that it's a hard coded value, but the sorting is done either way. So might as well make it configuration instead of always 20?

**Comment by CriesofCarrots** [comment]
No longer needed, given the move to geyser plugins and external indexing.
