### ISSUE TITLE
Upgrade to rust 1.46.0

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#11976]
Codebase doesn't compile with Rust 1.46.0 :-/

Workaround for now: please use 1.45.1

**Comment by CriesofCarrots** [comment]
The issue seems to be in this area: https://github.com/solana-labs/solana/pull/11326/files

**Comment by marshall** [comment]
yup, confirmed locally that if I revert this change, I can compile locally using 1.48.0.

oddly enough, it looks like the `declare_builtin_name` macro in `sdk/src/builtins.rs` is still using the original code

https://github.com/solana-labs/solana/blob/12eb0af3d1f5bc2d900d968c5ad7898b4620e0c5/sdk/src/builtins.rs#L40

I'd vote for a revert commit, but it's not clear what hack the original commit was supposed to fix

**Comment by mvines** [comment]
Sweet, I reverted it as a part of #11978
