### ISSUE TITLE
RPC: Parsed token instructions return amounts as u64 causing precision loss

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#11986]
#### Problem
The parsed token instruction data returned from RPC returns u64 amounts directly in JSON which means that, in JS, precision is lost when parsing those numbers.

#### Proposed Solution
Unfortunately we don't have decimals on hand to return `UiTokenAmount`. Seems like the best way forward is returning amount as a string. Breaking change is fine with me since only the explorer consumes those parsed instructions afaik

tag @CriesofCarrots

**Comment by CriesofCarrots** [comment]
We do have decimals for Transfer2, so I'll update that one to return a `UiTokenAmount` and Transfer to return a string
