### ISSUE TITLE
PoH hash can't be mapped to Bank state in leader

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#1200]
Problem:

Currently, after processing transactions in the TPU, those transactions are shipped to the RecordStage to be tagged with the PoH counter. Meanwhile, the BankStage will read the next batch of transactions and start processing them. By the time the bank learns the PoH hash of the first set of transactions, its accounts will be in an unknown state. And because we can't map a PoH hash to a Bank state, we can't calculate stake consistently from everywhere in the network. And because we can't do that, the leader isn't able to generate the same leader schedule as the validators, and therefore doesn't know when to stop leading.

Proposed solution:

* Move RecordStage into BankStage. After sending it transactions, wait for it to reply with an Entry.
* Rename RecordStage to RecordService, since it is no longer a one-way street.
* Bonus points: Instead of sending `Vec<Transaction>` and waiting for an `Entry`, send a `Hash` of the transactions and wait for a `Hash` to use as the entry ID. If you do this, be sure to update `Block::verify()` to hash the transactions separately as well.

**Comment by garious** [comment]
Note: the proposed solution, should we go that route, should likely fix https://github.com/solana-labs/solana/issues/1171. That is, assuming we move `register_entry_id()` from the WriteStage to the BankingStage.

**Comment by rob-solana** [comment]
fixed in #1300
