### ISSUE TITLE
solana-ledger-tool: add batch mode for request for transaction data (confirm -v)

### ISSUE THREAD

**Issue by ericlwilliams** [solana-labs/solana#12037]
#### Problem
Requesting transaction details (e.g. `solana-ledger-tool -l . bigtable confirm -v <TXID>`) for many transactions is time inefficient and is a blocker for historical ledger analysis

#### Proposed Solution
Enable batch requests of transaction data

**Comment by mvines** [comment]
Hopefully fixed by https://github.com/solana-labs/solana/pull/12071, if not LMK.  This'll ship in the v1.3.9 release
