### ISSUE TITLE
bank.accounts length should be propagated to influx

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#1206]
bank.accounts length is being logged now, but could be useful information in influx to see how fast/large the accounts table is growing.

https://github.com/solana-labs/solana/blob/ee74b367ce07f56e515ec7e14597e54f24be9c0d/src/bank.rs#L499

**Comment by garious** [comment]
@sakridge, was this ever done? Still needed?

**Comment by sakridge** [comment]
@garious no, not done. It could be useful, but maybe not a priority unless we are focusing on memory-use issues.

**Comment by mvines** [comment]
Closing.  If anybody ever wants this then just do it
