### ISSUE TITLE
RPC: simulateTransaction and sendTransaction options are not dev friendly

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#12096]
#### Problem

```rust
pub struct RpcSendTransactionConfig {
    pub skip_preflight: bool,
    pub preflight_commitment: Option<CommitmentConfig>,
}
```
- `skip_preflight` is required, not optional
- `preflight_commitment` is not flattened and looks like this in json: `{preflightCommitment: {commitment: 'single'}}`

```rust
pub struct RpcSimulateTransactionConfig {
    pub sig_verify: bool,
    pub commitment: Option<CommitmentConfig>,
}
```
- `sig_verify` is required, not optional
- `commitment` is not flattened and looks like this in json: `{commitment: {commitment: 'single'}}`

#### Proposed Solution
- make all config fields optional
- flatten commitment fields

**Comment by jstarry** [comment]
@mvines I'd like to do these changes (commitment flattening is a breaking change) before adding support in the web3 sdk. Sound good?

**Comment by mvines** [comment]
Yep, wfm.  Backport all the way to 1.2 of course!
