### ISSUE TITLE
Prototype Pollution for node-forge package

### ISSUE THREAD

**Issue by MKokeshi** [solana-labs/solana#12149]
#### Problem
**Introduced through:**` solana-docs@0.0.0 › @docusaurus/core@2.0.0-alpha.58 › webpack-dev-server@3.11.0 › selfsigned@1.10.7 › node-forge@0.9.0

**node-forge** is a JavaScript implementations of network transports, cryptography, ciphers, PKI, message digests, and various utilities.
Affected versions of this package are vulnerable to Prototype Pollution via the `util.setPath` function.

Note: version 0.10.0 is a breaking change removing the vulnerable functions.

#### Proposed Solution

Upgrade node-forge to version 0.10.0 or higher.

**Comment by CriesofCarrots** [comment]
Done
