### ISSUE TITLE
solana-install-init: Unable to figure latest release

### ISSUE THREAD

**Issue by ShayanJa** [solana-labs/solana#12164]
#### Problem
I keep getting this err 
`solana-install-init: Unable to figure latest release
`
when running 
`curl -sSf https://raw.githubusercontent.com/solana-labs/solana/v1.3.9/install/solana-install-init.sh | sh -s - v1.3.9`
I'm on mac OS Catalina 10.15.6

**Comment by CriesofCarrots** [comment]
I think this is long resolved, but please reopen if problems persist.
