### ISSUE TITLE
explorer: Human readable timestamps not available on account transaction history

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#12236]
#### Problem
The explorer shows the slot in which a transaction was processed but it's not human friendly. Timestamp would really help make it easier to clearly see how recent transactions were processed.

![image](https://user-images.githubusercontent.com/54819888/92636235-eeb14080-f2ce-11ea-833d-95863e6eac9f.png)

#### Proposed Solution
TBD - Probably requires RPC changes

---
Copied from https://github.com/solana-labs/explorer/issues/167

**Comment by mvines** [comment]
I think we should extend [getConfirmedSignaturesForAddress2 ](https://docs.solana.com/developing/clients/jsonrpc-api#getconfirmedsignaturesforaddress2) to include the timestamp, everything else here then falls out naturally
