### ISSUE TITLE
explorer: Token transfer instructions don't display which token is transfered

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#12273]
#### Problem
When viewing a transaction involving a token transfer, it's difficult to know which token is being transferred because SPL Token "Transfer" instructions don't include the mint address ("Transfer2" does). 

Example:

The following transaction displays an instruction which transfers wrapped ETH:
https://explorer.solana.com/tx/afPaFtbXfK8iE5D6P3F2KiPC917EfCq8yA6awT9q73iCo3MU8kn6UNd8sy3K77wZda7S9twvbMrPL5BUL2ARNNV
We know that because we can inspect the source account:
https://explorer.solana.com/address/EgrroRsUDmwDLeWFd1zZ4Yej7Jhu6yYqUEwT2RLgTdQW

#### Proposed Solution
Display which token is being transferred and include the token unit.

**Comment by jstarry** [comment]
This shouldn't be too bad because we already fetch the mint account to determine the decimals to use in the transfer amount. @oJshua are you interested in taking this on?

**Comment by oJshua** [comment]
@jstarry yep, no problem.
