### ISSUE TITLE
Data plane only scaling to 100 nodes - incomplete implementation of Avalanche

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#1230]
Currently all validators get a subset of the blobs from the leader node. Validators, then, forward/retransmit the blobs to the peer validator nodes. This is 1st level of Avalanche network.

This approach may not work very efficiently when the validator node count grows beyond a certain number. The network bandwidth of the leader may prevent it from achieving maximum TPS if it was broadcasting to all the nodes.

Solution: Add 2nd level of validators, that receive broadcast from 1st level of validators. The 2nd level validators could be the nodes that do not have high stake in the network.

This ticket is a placeholder for now. Further comments and design notes will be added here.

**Comment by garious** [comment]
@sagar-solana, I reassigned this old ticket. If this is a duplicate, can you cross-link it here and close this one?

**Comment by sagar-solana** [comment]
Fixed in #2058
