### ISSUE TITLE
Add a `distribute-spl-tokens` subcommand to `solana-tokens` tool

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#12315]
#### Problem

No convenient way to distribute SPL tokens to multiple parties

#### Proposed Solution

Add a `distribute-spl-tokens` subcommand to `solana-tokens` tool

**Comment by CriesofCarrots** [comment]
I'm pausing my work on this while https://github.com/solana-labs/solana-program-library/pull/612 is addressed, as the Default Token Account program may change the payment model we want to use.
