### ISSUE TITLE
CPU Utilization On v1.3.N Stair-Steps Upwards

### ISSUE THREAD

**Issue by brianlong** [solana-labs/solana#12317]
#### Problem

CPU Utilization on 1.3 increases in a stair-step fashion until the CPUs are maxed-out. Other validators are seeing the same problem, so I created this issue to hold screenshots & log fragments for debugging.

**Comment by brianlong** [comment]
<img width="910" alt="Screen Shot 2020-09-16 at 6 16 31 PM" src="https://user-images.githubusercontent.com/79186/93515155-5f66e700-f8e5-11ea-9447-e5190bd68026.png">

**Comment by brianlong** [comment]
![Screenshot from 2020-09-17 14-29-30](https://user-images.githubusercontent.com/79186/93524859-60524580-f8f2-11ea-832a-577735ca58f7.png)
This is a look at htop while running about 50%CPU. I post another screenshot when CPU % steps up again.

**Comment by sakridge** [comment]
@mvines can you see what send-tx-svc is doing? Or see who should look at that?

**Comment by mvines** [comment]
Interesting!

@brianlong - are you setup to easily apply patches and rebuild from source?  I have a patch at https://github.com/solana-labs/solana/pull/12320 that would be useful to apply to help narrow this down a little more.   Happy to wait until we step up more though and need to kill the process.   Based on that there might more a little more logging we can add to help debug this more.    

My guess right now:  you'll see another `send-tx-svc` thread each time the CPU steps up.  I bet some code is panicking and re-creating a new `send-tx-svc`

**Comment by brianlong** [comment]
@mvines I might need a little coaching, but I'll give it a try this evening.

**Comment by mvines** [comment]
Pretty sure the bug is in the BankServer's version of the SendTransactionService: https://github.com/solana-labs/solana/blob/9b866d79fb1173d837ad18273a7034ae7fb4fd18/banks-server/src/banks_server.rs#L230
I don't think will clean shut down the SendTransactionService in some cases, which could cause that `send-tx-svc` thread to spin loop and eat up a CPU.

**Comment by brianlong** [comment]
@mvines I've done `sudo apt install libudev-dev` and I still see this error when trying to compile from your fork & dup branch. ```
error: failed to run custom build command for `hidapi v1.2.3`

Caused by:
  process didn't exit successfully: `/home/brianlong/solana/target/release/build/hidapi-1e613a883643668a/build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Unable to find libudev: Command { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"libudev\"", cause: Os { code: 2, kind: NotFound, message: "No such file or directory" } }', /home/brianlong/.cargo/registry/src/github.com-1ecc6299db9ec823/hidapi-1.2.3/build.rs:53:54
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Any suggestions?

**Comment by brianlong** [comment]
@mvines Yes, I now see five threads for `send-tx-svc`. I think you're on the right track.

**Comment by t-nelson** [comment]
@brianlong try installing the full set of system dependencies listed [here](https://github.com/solana-labs/solana/blob/master/README.md#1-install-rustc-cargo-and-rustfmt)

**Comment by brianlong** [comment]
@t-nelson Thanks. I am now up & running on the @mvines version of 1.4.0 devbuild. I think I also just sent all of my testnet SOL to Michael ;-)

**Comment by brianlong** [comment]
I'll let this run for a while and report back when I see the CPU step-up.

**Comment by brianlong** [comment]
@mvines It just occurred to me that you might have patched a different branch, not 1.4.0. Do you want me running 1.4.0?

**Comment by mvines** [comment]
v1.3 would have been better than v1.4 but I think it's ok.   Actually it's possible that on both the tip of v1.3 and v1.4/master the issue will no longer reproduce due to another bank_server bug we recently fixed.  

But no matter, I'll look at fixing up what looks to be the root cause shortly

**Comment by brianlong** [comment]
I saw your change in the tip of the dup branch, so I ran with it. ;-)

**Comment by brianlong** [comment]
@mvines Here is a look at the threads this morning.

<img width="1004" alt="Screen Shot 2020-09-18 at 8 42 17 AM" src="https://user-images.githubusercontent.com/79186/93611020-ff2a8080-f98a-11ea-8293-85e1a2c8a1ad.png">

**Comment by mvines** [comment]
Ok great, two `send-tx-svc` threads at ~99% cpu.  That fits my theory, thanks Brian!
