### ISSUE TITLE
explorer: Display SPL Token mint freeze authority if set

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#12316]
#### Problem

Explorer does not display the optional freeze authority pubkey for SPL Token mint accounts

#### Proposed Solution

Display it!

**Comment by CriesofCarrots** [comment]
Done, eg: https://explorer.solana.com/address/EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
