### ISSUE TITLE
blockstore: Extend transaction pre/post balance metadata to support SPL Token deltas

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#12318]
#### Problem

No convenient way to query what SPL Token balance changes occurred in a given transaction

#### Proposed Solution

Extend transaction status metadata to support SPL Token balance deltas

**Comment by mvines** [comment]
We also need to extend the meta field of the `getConfirmedTransaction` (and implicitly `getConfirmedBlock`) RPC method to surface token account balance changes to the user, and then plumb this through explorer.solanaa.com
