### ISSUE TITLE
[question] solana validator system requirements

### ISSUE THREAD

**Issue by roccomuso** [solana-labs/solana#12331]
#### Question

I've read the system requirements to run a Solana validator: https://docs.solana.com/running-validator/validator-reqs

Can Solana validator run on CPU-only systems? instead of the recommended GPUs, That part is not clear.

Thanks

**Comment by danger89** [comment]
> GPUs:
> Not strictly necessary at this time

**Comment by t-nelson** [comment]
https://docs.solana.com/running-validator/validator-reqs#hardware-recommendations
![Screenshot from 2021-09-15 23-20-20](https://user-images.githubusercontent.com/490004/133554035-80bf5185-b15f-4b60-b6f5-30465a1eace5.png)
