### ISSUE TITLE
[question] min balance to have rent-exemption

### ISSUE THREAD

**Issue by roccomuso** [solana-labs/solana#12332]
Assuming a wallet cannot make external RPC api calls.
What's a safe value (like a minimum balance) to be sure a wallet has rent-exemption?

Would like `1 SOL` be enough?

**Comment by mvines** [comment]
1 SOL would be more than enough, even 0.01 SOL.

**Comment by steveluscher** [comment]
If there's any further discussion needed here, feel free to post a follow up question to the Solana Stack Exchange using this link: https://solana.stackexchange.com/questions/ask
