### ISSUE TITLE
solana_token_audit#13: Derived Program Address collisions

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#12343]
#### Problem

A program address is derived by using the SHA256 hash function taking an arbitrary amount
of seeds (each seed can have an arbitrary length in the range [0,MAX_SEED_LEN=32)], a
public key called program id and the string "ProgramDerivedAddress". All these parameters
are fed into the hasher by simple concatenation. The construction of this derivation allows
ambiguity in the specification of the seeding material, allowing possible collisions (e.g. same
value of the derived program address) with different sets of seeds. For example, the seed sets
{"abcdef"}, {"abc", "def"} and {"ab", "cd", "ef"} would all allow derivation of the same program
address for the same program ID.

Proof of Issue
solana/sdk/src/pubkey.rs: line 104 (create_program_address)
Filename: solana/sdk/src/pubkey.rs
Beginning Line Number: 104

Severity and Impact Summary
The fact of being able to produce collisions in program addresses by using different strings
could be considered a violation of a design principle for derived addresses, i.e. that no easy
collisions should be producible with an effort much less than the effort needed to find
collisions in the underlying hash function (i.e. this would imply a 128-bit effort for SHA256).

#### Proposed Solution

We would suggest moving to a slightly different construction, i.e. hash all the provided seeds
independently and then derive the program address by hashing: all the hashes of the seeds,
the program id and the string "ProgramDerivedAddress". This simple modification should
suffice as fix, while albeit it is not backward compatible with the current implementation.

**Comment by t-nelson** [comment]
I wonder if we could get away with prefixing each seed by its length?

**Comment by mvines** [comment]
Why do we allow sets of seeds anyway?

**Comment by jackcmay** [comment]
I think the original motivation was to allow the seeds to be something like `(pubkey, some_identifier_string)`

**Comment by jackcmay** [comment]
Seeds are often either pubkey bytes or identifying strings.  Collisions occur then seed-x == seed-x + seed-y.  This seems like a rare event in practical application.  

I see two options to help developers avoid collisions:
- Document the behavior of the current API and guide developers to avoid collisions
- Create a new `create_derived_address` API that takes the developer's keys and adds a prescribed delimiter between them, then add a new `invoke_signed` function that developers call in their programs that also adds the prescribed delineator.

**Comment by jackcmay** [comment]
@mvines, I'm leaning toward option one because adding two new apis for this seems like overkill

**Comment by mvines** [comment]
I'm ok with that
