### ISSUE TITLE
Finality is blocked by write stage

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#1238]
Write stage is in front of transmitting and broadcast stage.  This causes the network to effectively fall behind the leaders disk.  Since we are an A system, the leader can be optimistic about the network's ability to maintain copies of the packets even if its local disks fails

* write stage should eat the window
* vote stage should store the votes in redundant storage somewhere before votes are transmitted

This optimizes the pipeline for state transmission at the cost of a potential local node stall if the local disk fails but network succeeds.  the stall is just the local node waiting until their votes expire if the network cannot provide the ledger that is missing due to disk failure.

@rob-solana @pgarg66

**Comment by rob-solana** [comment]
this will be part of addressing the OOM issue
