### ISSUE TITLE
RPC API method request:  solana inflation

### ISSUE THREAD

**Issue by ericlwilliams** [solana-labs/solana#12394]
#### Problem
No ability to retrieve current or historical network inflation issuances and rates.

#### Proposed Solution
RPC method `inflation` which returns the current network wide inflation rate per year, the inflation rate to be applied to the current epoch, the number of tokens to be issued via inflation in the current epoch and the taper rate (<- constant).

e.g.
```
> solana inflation
Current Epoch: N
Epoch Inflation per Annum [APY]: 6%
Epoch Inflation: 0.0328%
Epoch Issuance: 180,821.9 SOL
Inflation Taper per Annum: 10%
```

A `--block` and/or `--epoch` flag would also be useful to pull historical inflation data.

**Comment by mvines** [comment]
ref: https://docs.solana.com/apps/jsonrpc-api#getinflationrate

**Comment by mvines** [comment]
Going down the metrics route for now: https://github.com/solana-labs/solana/pull/12505

**Comment by mvines** [comment]
`solana inflation` now exists.  `solana block` outputs rewards info, `solana vote-account`/`solana stake-account` also displays rewards history for the account
