### ISSUE TITLE
rpc call to get transactions given an address

### ISSUE THREAD

**Issue by roccomuso** [solana-labs/solana#12411]
#### Problem

what's the RPC to get the list of transactions given an address?

I saw `getConfirmedSignaturesForAddress2` but I don't want only the list of signature, instead I'd like to get some basic info like amount received/sent and addresses involved. Something more verbose.

I assumed having the signatures and call `getConfirmedTransaction` would give me the txs details, but what if I want the timestamp of the tx instead of the `slot`?
Nesting rpc calls seems a wrong approach to me.

**Comment by CriesofCarrots** [comment]
Oops, duplicate issues. https://github.com/solana-labs/solana-web3.js/issues/992 I'll close the other

Right now chaining those calls (`getConfirmedSignaturesForAddress2` and `getConfirmedTransaction`) is the way to go. `getBlockTime` will return the timestamp from the `slot`

**Comment by roccomuso** [comment]
I saw that `getBlockTime` could have issues depending on the validator: https://github.com/solana-labs/solana/issues/12413

**Comment by roccomuso** [comment]
Do you know if there are planned improvements to allow pagination on `getConfirmedSignaturesForAddress2` ?
For pagination I mean keeping a "cursor" that allow to filter out old transactions (the opposite of "before" parameter).
Instead of the `before` parameter an `after` parameter would do the job.

**Comment by CriesofCarrots** [comment]
Yes! There is actually already an `until` parameter enabled on the RPC side. I just filed an issue about getting that exposed in the web3.js sdk: https://github.com/solana-labs/solana/issues/12417

**Comment by roccomuso** [comment]
Oh thanks, that's a lot useful! I guess also the documentation must be updated.

**Comment by CriesofCarrots** [comment]
> Oh thanks, that's a lot useful! I guess also the documentation must be updated.

💯 on my list for today

**Comment by roccomuso** [comment]
Wouldn't be also useful to get rid of the upper limit of 1000 txs ?

**Comment by CriesofCarrots** [comment]
I think we'll keep that limit for now. RPC isn't optimized for huge data dumps.

**Comment by roccomuso** [comment]
Any plan to aggregate those nested calls?
Like using one single REST call to get all the tx detail
