### ISSUE TITLE
Need a wallet integration guide in the docs

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#12416]
#### Problem
With each new wallet integrations comes another opportunity for fragmentation if there is no clear standard for how to integrate with Solana. This includes BIP 44 key derivation paths, BIP 32 word lists, RPC API usage, etc.

#### Proposed Solution
- Add a "Wallet" page to the "Integrations" section on docs site

**Comment by jstarry** [comment]
This could be expanded to include SPL Token support as well:
- How to fetch and display token holdings
- How to transfer SPL tokens to an owner address
- Registry for token details

**Comment by CriesofCarrots** [comment]
Such docs are now supported in the foundation repository: https://github.com/solana-foundation/developer-content
