### ISSUE TITLE
block cleaned up, it does not exist on node

### ISSUE THREAD

**Issue by roccomuso** [solana-labs/solana#12413]
#### Problem

I had an error like `Block 30596283 cleaned up, does not exist on node. First available block: 34365268` when using rpc `getBlockTime`.

Why some blocks are unavailable? doesn't solana validator keep and index all the blocks?

**Comment by CriesofCarrots** [comment]
The validator does keep and index all the blocks, but the block time is provided via a [validator timestamp oracle](https://docs.solana.com/implemented-proposals/validator-timestamp-oracle), which currently has a more-limited history: https://github.com/solana-labs/solana/issues/10089
A fix to this limitation is in progress, but not yet released to the mainnet-beta cluster: https://github.com/solana-labs/solana/pull/11955

**Comment by CriesofCarrots** [comment]
This is fixed. Block times are now in sync with validator storage.
