### ISSUE TITLE
Logrotate kills validator when logging to stdout

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#12432]
#### Problem

When a validator is configured to log to stdout, we don't setup the SIGUSR1 handler.  If logrotate is setup as recommended, it will kill the validator process when run.  This is typically a misconfiguration, but could also occur when temporarily logging to stdout for debugging purposes

#### Proposed Solution

Setup ignore handler for SIGUSR1 when configured to log to stdout

**Comment by sakridge** [comment]
Not an issue now per @t-nelson
