### ISSUE TITLE
Better channel counter architecture

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#1243]
Performance counters are a bit ad-hoc and have to be manually added when adding/modifying a stage.

Couple ideas to improve that are to either have a channel wrapper which can then log how full the channel is at any given point or empty the channel at each stage similar to how we do in sigverify/banking_stage.

**Comment by aeyakovenko** [comment]
draining channel?
send(Vec<A>)
recv() -> Vec<A>

**Comment by mvines** [comment]
Closing, this doesn't seem like something worth tracking
