### ISSUE TITLE
Cross program instructions may need size restrictions

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#12441]
#### Problem
Currently, cross program instruction data and account_metas are not limited by size like they are for normal transaction instructions (MTU limited). This could have undesirable side effects. For example, a malicious program could create many large cpi instructions which would cause large allocations in the [new CPI instruction recorder](https://github.com/solana-labs/solana/pull/12311) on API nodes

#### Proposed Solution
- Pick a reasonably high limit for instruction size
- Pick a reasonably high number of allowed invoked instructions

OR

- Adjust CPI instruction recorder to drop large number of large invoked instructions

**Comment by jackcmay** [comment]
Fixed in v1.4.19 b88c56cd3
