### ISSUE TITLE
cargo audit advisory: RUSTSEC-2020-0043

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#12484]
#### Problem

Link from the report: maybe be broken
 https://rustsec.org/advisories/RUSTSEC-2020-0043

Commit:
https://github.com/RustSec/advisory-db/commit/687f99934379b0421259c511bca2ecc3b63cf623

#### Proposed Solution

Need to evaluate and either ignore or update `jsonrpc-ws-server`

**Comment by garious** [comment]
broken link

**Comment by jackcmay** [comment]
@garious heh, that's the link from the `cargo audit` report, maybe too new!
