### ISSUE TITLE
Proposal: CPIs that return values

### ISSUE THREAD

**Issue by sconybeare** [solana-labs/solana#12601]
#### Problem
There's no good way to return data to the caller of a cross-program invocation.

#### Proposed Solution
Currently the suggested solution is to have programs write data to accounts they own, and then for callers to read these buffers. I think this is inadequate for 2 reasons:
- It's a pretty big security footgun. The problem is that it's easy to write vulnerable code where a program fails to distinguish trusted state from return values of function calls. The solution is simple -- accounts must be tagged, but I think in practice people will screw this up all the time.
- It doesn't allow the return buffer to be reused across calls to different programs.

The following thing should work without changes from the Solana runtime, and is much harder to misuse:
- Write a program P, which does only one thing. It takes a writable P-owned account and some instruction data, and memcpys the instruction data into the account.
- Write a program L, which takes a single account A, and logs the contents of A. This is necessary to allow clients to find out the result of a simulated call.

This solves the problem above, but still has problems. For one thing, it means you can't mutate the data returned from a CPI without making another copy. It also generally just does a bunch of unnecessary work. Here's an idea for an improvement to the current situation that probably wouldn't be very difficult to implement: allow accounts that any program can write to. Obviously these accounts can't store any program state, but within a transaction that doesn't matter. Here's an example of how this could be done:

- Create a new built-in program, and call it SharedMemory1111111111111111111111111111111 (I'll abbreviate as SHM) or something. Accounts owned by SHM have the same read-write locking behavior as regular accounts, except that when they're writable, any program can write to them.
    - The naive implementation of this has a problem: it breaks the guarantee that if a write to account data succeeds, that account must be owned by the program (since otherwise the transaction fails).
    - Solution: add a syscall, called supports_shared_memory or something, that SHM users must call in order to not have their transaction reverted if they write to shared memory.
- The problem with the above is that it would mean that all programs written prior to the change would require significant restructuring to use it, which could create a significant amount of cruft or create two competing standards. So instead, I propose that we designate accounts right now that will be the ones that arbitrary programs can write to so that developers can already begin to code for it, and then when Solana rolls out the update that code will still be fully functional, just less efficient. Those accounts can be owned by the program P described above.

**Comment by jackcmay** [comment]
Shared memory accounts is a cool idea

Not quite following the difference between writing to a shared memory account
and writing to one owned by the called program.  Do you have a use case where
multiple programs need to write to the same account?  Is the purpose to reduce
the number of accounts that need to be supplied to the parent transaction?

If we had shared memory accounts we would probably make an exception in the
policy enforcement to allow any program write to them.  Seems like the shared
memory account data could only be considered valid within the parent transaction

What’s the purpose of program L?  Can’t anyone log the data from a supplied
account

**Comment by sconybeare** [comment]
> Not quite following the difference between writing to a shared memory account
and writing to one owned by the called program. Do you have a use case where
multiple programs need to write to the same account? Is the purpose to reduce
the number of accounts that need to be supplied to the parent transaction?

Reducing the number of accounts is one reason. Note that scratch buffer accounts
will often need to be created in the same transaction that they're used in, so this can
eat into transaction size limits substantially. The other big reason is that it's easy to
write bugs where a program can be tricked into writing attacker-controlled data
into an account that the program will later treat as a piece of trusted state.

> What’s the purpose of program L? Can’t anyone log the data from a supplied
account

Yeah L doesn't need any special treatment from the runtime, and program code
doesn't have to care about its existence. It's only purpose is to allow RPC users
to learn the result of a simulated CPI call, by inserting a call to L into the simulated
transaction. There's also no need to standardize a particular choice of L. I only mentioned
it for completeness' sake.

**Comment by aeyakovenko** [comment]
What about a *Stack* program that has a `push/pop` syscall that allows programs to push and pop data up to their level?

```
ProgramA 
    invoke_ProgramB (push b)
   b <- pop
   pop (fails)
```

**Comment by aeyakovenko** [comment]
After talking to @sconybeare, I think we came to the conclusion that the best approach is a CPI based "sharedmem" program that we can standardize on in SPL.

**Comment by CriesofCarrots** [comment]
A reference implementation for a shared-memory program was added to the SPL repository, as linked above.
But also, syscall support for getting and setting return data was added: https://github.com/solana-labs/solana/pull/19548
