### ISSUE TITLE
Periodic invalid snapshots generated by some nodes

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#12614]
Periodically I see invalid snapshots getting created by our warehouse nodes.  The latest occurrence was at slot 38434744 on bw3:

STR:
```
sol@warehouse-asia-northeast3-a:~$ RUST_LOG=solana=debug solana-ledger-tool -l bad-snapshot-38434744 verify
.
.
.
[2020-10-01T17:58:30.437575483Z WARN  solana_runtime::bank] verify failed: slot: 38434744, BPypNAAtTjrQ7zD7EG28RDUFqvq7LZEmrDciFKDGu4U (calculated) != 93NVN78UttnAW7y8AB2QzTPrXgM7CLDujUU9sEEEdL9i (expected)
thread 'main' panicked at 'Snapshot bank for slot 38434744 failed to verify', ledger/src/snapshot_utils.rs:593:9
```

**Comment by carllin** [comment]
Potentially the same zero-lamport purging issue fixed here: https://github.com/solana-labs/solana/pull/12194/commits/a214c29de9fbd591bfce8ae6dcf51736373a836f

**Comment by mvines** [comment]
Thanks Carl.  I think we don't need to do anything here.  The invalid snapshots on mainnet-beta aren't happening frequently enough for this to be an issue, so I don't mind waiting to see if v1.4 improves the situation
