### ISSUE TITLE
web3: JSON validation is very slow for large responses

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#12664]
#### Problem
JSON validation in the web3 sdk is very slow for large responses

For example:
- `getProgramAccounts` is slow when many accounts are returned
- Had to disable full validation for `getLeaderSchedule` due to slowness: https://github.com/solana-labs/solana/pull/12049

#### Proposed Solution
Seems like `superstruct.array(..)` is the culprit so I think it's worth investigating its implementation. However, this could just be an overall issue with `superstruct` and so it might be worth investigating different libraries since superstruct development hasn't been very active

**Comment by jstarry** [comment]
Another thing to explore is switching to this fork of superstruct that's currently used by the explorer: https://github.com/solana-labs/superstruct. If we do so, we'd want to publish a forked version to npm

**Comment by bartosz-lipinski** [comment]
I will profile different libraries and see which one is faster and support our use cases.

**Comment by bartosz-lipinski** [comment]
After initial testing of different libraries, I think switching to [ajv](https://ajv.js.org/) will be the best option. I am estimating that we will see **20x improvement** in validation code performance. Additionally load time of web3.js will be reduced by removing runtime construction of superstruct objects. 

**Proposed Solution**
* Move schema definition from javascript code to json schema format in json file (that could be extracted from web3.js project and posted online as part of https://api.mainnet-beta.solana.com/ e.g. _https://api.mainnet-beta.solana.com/schema.json_
* As a part of rollup build script compile json schema into a module using ajv-cli and aji-pack
* Use compiled schema to validate jsonRPC responses
* remove any references to superstruct

**Comment by mvines** [comment]
Sounds excellent!

**Comment by jstarry** [comment]
The latest superstruct fixes these this slowness
