### ISSUE TITLE
macOs BPF toolchain may not work without homebrew

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#12660]
It seems that the macOs BPF dev environment has a homebrew dependency (for libssl).  This is a problem for people who choose not to use homebrew, and is turning devs away

Confirm that https://github.com/solana-labs/example-helloworld works on a fresh macOs machine without homebrew or other package managers, or fix what breaks.

**Comment by jackcmay** [comment]
This is probably due to the fact that our toolchain binaries are mostly built on my machine.  @mvines @t-nelson Any suggestions on how we should be building these binaries besides getting a new clean macOS machine?  Is there a VM you would recommend we build these in?

**Comment by mvines** [comment]
We do pay Travis CI for the honour of using their macOS build infrastructure.   Possible pitfall, the build is too slow for Travis -- I forget what the Travis macOS build timeout is, maybe 90min?

**Comment by jackcmay** [comment]
fixed via #13176
