### ISSUE TITLE
web3: Sent transactions are base58 encoded when sent to RPC

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#12685]
#### Problem
web3 sdk encodes transactions in base58 before sending to RPC and base58 decoding is slower than base64 decoding

#### Proposed Solution
Once #12683 is live on all clusters, switch transaction encoding to base64

**Comment by t-nelson** [comment]
Rust `RpcClient` now defaults to `base64`, https://github.com/solana-labs/solana/pull/12813
