### ISSUE TITLE
Malformed transactions crash the leader

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#1274]
Need to at least audit all calls to `deserialize()` and ensure its error is being handled and not `unwrap()`ed.

**Comment by mvines** [comment]
http://lcamtuf.coredump.cx/afl/

**Comment by mvines** [comment]
Also all Vec<> deserialization needs to be audited as well (ie, Gossip).  Here's one example of  malformed data that was nodes to OOM: #4586

**Comment by jackcmay** [comment]
The use of short_vec to prevent OOM attacks is not required if we limit the deserialization with `bincode::config()::limit().`

**Comment by jackcmay** [comment]
@mvines I see two remaining action items in this issue if my comment above is correct:
- Handle errors from deserialize instead of using `unwrap()`
- Fuzzying the transaction api surface (Unsure specifically what you had in mind, maybe good for a separate issue?)

**Comment by mvines** [comment]
sg, we do have #5414 as a general starting point for fuzzing so we don't need to address that here IMO

**Comment by jackcmay** [comment]
Preventing OOM attacks is being tracked by this issue: https://github.com/solana-labs/solana/issues/5779

**Comment by jackcmay** [comment]
@garious  @mvines  Should we close this issue with the following PR? https://github.com/solana-labs/solana/pull/6769

If not, please describe the criteria for closing this issue

**Comment by garious** [comment]
Yes, you can close with that PR. Thanks!
