### ISSUE TITLE
explorer: Decode BPF Loader 2 instructions

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#12812]
The BPF Loader instructions show up as Raw in the explorer:
* Example [Write](https://github.com/solana-labs/solana/blob/2f5bb7e507279d7eff94e8a25bc931c3d2711c39/sdk/src/loader_instruction.rs#L13) instruction: https://explorer.solana.com/tx/5fFkQ71GhhrGnfXXoJ9H4E7bybN6mgM5397CT83Ukc3WnD23i9KbnhkL8ARVrr6K3WbjCXssVUe5Td4JM9jUp3Lq
* Example [Finalize](https://github.com/solana-labs/solana/blob/2f5bb7e507279d7eff94e8a25bc931c3d2711c39/sdk/src/loader_instruction.rs#L30) instruction: https://explorer.solana.com/tx/3ET4ogNzoBEKYubBM1vo3T5PeGBKyXKmDRVUpoTBMzpQxbWKYQqcCDGmUSxPRUedTVqXnNLaojMWsiVj7r8oKUqD

**Comment by oJshua** [comment]
@mvines I don't seem to be getting any raw instruction data back from the API with those transactions you referenced. Do you have other examples?

**Comment by mvines** [comment]
Strange, they worked before.  @CriesofCarrots - can you please check the explorer links above?  I think this is just due to the protobuf/rewards-related bugs we've been working through right? 

@oJshua - just select testnet, then search for "BPF Loader 2".  First transaction for the loader, at the moment, is a Finalize: https://explorer.solana.com/tx/5CV4tRvdrhoiUQKgD6stjW9VGQCszEZFBQUDf4gefZUWQA3XgFgs9hEduJQwdxZFtMPBqQKYZdpMX8r2Rj4yodNb?cluster=testnet

**Comment by CriesofCarrots** [comment]
@mvines it's the issue fixed here: https://github.com/solana-labs/solana/pull/12923
It'd be nice to get that deployed onto our api nodes. v1.3.18?

@oJshua , I'm going to start working on rpc support for more parsed instructions this week, which should help: https://github.com/solana-labs/solana/issues/11316

**Comment by mvines** [comment]
> @mvines it's the issue fixed here: #12923
> It'd be nice to get that deployed onto our api nodes. v1.3.18?

Thanks, yeah a v1.3.18 only for API node update sounds great.

**Comment by CriesofCarrots** [comment]
> Thanks, yeah a v1.3.18 only for API node update sounds great.

Cool, I'll spearhead that tomorrow

**Comment by CriesofCarrots** [comment]
@oJshua links in the original issue description are rejuvenated!

**Comment by oJshua** [comment]
@CriesofCarrots excellent! Thanks much.
