### ISSUE TITLE
Accounts accessible by all instances of a program, not one

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#1289]
Right now `program_id` is pointing to code without state.  The same `program_id` is used for calling any permutation of state.  Which forces the program to create its own namespace system for state (like a process id map) and defend against malicious users who can call the program with any object in the system.

We need an interface that takes a program_id, and creates a process_id which is what transactions use when calling the program.  This process_id should be able to attach a set of states that are always passed in along with the transaction.  This would allow the process_id to have a fixed state that can be used to maintain the progress of that specific computation.  In the future, the process_id specific states can be used to implement writable segments for the loaded elfs.

@garious @mvines would love some feedback if this captures what we discussed.

**Comment by garious** [comment]
One workaround is for the program to demand the account's signature.

@aeyakovenko, I don't think this is blocking any testnet MVP functionality. Can I bump it to a later release?

**Comment by aeyakovenko** [comment]
@garious yea, this could be designed in the future.  not blocking anything.

**Comment by jackcmay** [comment]
@aeyakovenko 
Are the  "states" you refer to stored in accounts?

How would the progress of computation be interrupted in a way that would require the state to be maintained?  Isn't that state already captured by the accounts passed in?

What specific issue are you referring to by "malicious users who can call the program with any object in the system"

**Comment by aeyakovenko** [comment]
@jackcmay I think we could deprecate this.  Or maybe a more generalized solution is to create a loader "bind" interface that automatically sets specific accounts to be loaded for instructions.  

LoaderInstruction::Bind { program_id: Pubkey, accounts: Vec<Pubkey>, process_id: Pubkey};

whenever `process_id` is used as a `program_id` in a transaction, `accounts` appear as the first N arguments.
