### ISSUE TITLE
Unable to get confirmed transaction details: invalid type: null, expected struct EncodedConfirmedTransaction

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#12908]
### STR 1
```
$ solana confirm -v 3sDdXn46grcvMwZPCG9npzcfpoG1B41TLaufQr9vxiAz6sQNagHWtkSu73WVVn1nhdEqdH8evyaYakeNPZETGEQ
RPC URL: http://api.mainnet-beta.solana.com
Unable to get confirmed transaction details: invalid type: null, expected struct EncodedConfirmedTransaction

Confirmed
```

### STR 2
https://explorer.solana.com/tx/3sDdXn46grcvMwZPCG9npzcfpoG1B41TLaufQr9vxiAz6sQNagHWtkSu73WVVn1nhdEqdH8evyaYakeNPZETGEQ reports "Details are not available"

**Comment by CriesofCarrots** [comment]
This is the issue: https://github.com/solana-labs/solana/blob/master/storage-bigtable/src/lib.rs#L345-L347
Fix coming shortly
