### ISSUE TITLE
SDK users using single confirmation for transactions should also use single confirmation blockhashes?

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#12965]
Transactions at single confirmation could still be rolled back.  If a user issues a follow-up transaction based on single confirmation, they need to ensure that their follow-up transaction doesn't reach max confirmations in the event of a rollback of the original transaction.

Suggestions:
1.  Add SDK documentation that describes this potential footgun and how to avoid it
2. Consider adding a `blockhash` field to [RpcResponseContext](https://docs.solana.com/apps/jsonrpc-api#rpcresponse-structure) so that the follow-up transaction can be sent with the exact blockhash that confirmation was obtained from by [getSignatureStatuses](https://docs.solana.com/apps/jsonrpc-api#getsignaturestatuses)
3. Rework some SDK methods to make (1) and (2) easy to use

**Comment by aeyakovenko** [comment]
It can't really be rolled back, since it means that 5% should be slashed.

**Comment by carllin** [comment]
Hmmm by single do we mean SingleGossip? If that's the case then the original transaction won't be rolled back unless as @aeyakovenko 5% equivocated. 

But just entertaining the idea of what would happen worst case if an optimistically confirmed block `B` *did* get rolled back and we wanted to ensure that all transactions based on this transaction also got rolled back, then I think @mvines suggestion is necessary. We should return `B`'s blockhash to be used by the dependent transactions, such that if `B` gets rolled back, then the entire chain of dependent transactions will be rolled back.

**Comment by aeyakovenko** [comment]
@carllin @mvines I don't want to confuse users as one "finality" is better than another.  It's the same finality, just X is different.
