### ISSUE TITLE
CLI deploy command is error prone due to positional args

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#12978]
#### Problem
The `solana deploy` subcommand is easy to misuse in a way that could result in loss of funds. If a dev is not careful about which keypair they specify for `[SIGNER_KEYPAIR]`, they may assign a system account with a lot of funds to the BPF Loader program which doesn't allow withdraws.

```
solana deploy --help
solana-deploy 
Deploy a program

USAGE:
    solana deploy [FLAGS] [OPTIONS] <PROGRAM_FILEPATH> [SIGNER_KEYPAIR]
```

#### Proposed Solution
- Add a balance check for `[SIGNER_KEYPAIR]` and abort if that address is a system account with a balance excess (+ flag to force the deploy anyway).
- Rename `[SIGNER_KEYPAIR]` arg name

**Comment by ryoqun** [comment]
lightly talked this with @aeyakovenko, we have to careful not to break cli compatibility for existing customers who has been relaying on the exact current ordering of command arguments. (@jstarry I've tagged you on the slack thread).

**Comment by mvines** [comment]
How about we add a balance check for `[SIGNER_KEYPAIR]` and abort if that address is a system account with a balance excess (+ flag to force the deploy anyway).

**Comment by jstarry** [comment]
Balance check sounds like a better proposed solution, I'll update

**Comment by CriesofCarrots** [comment]
>  I think the generic arg name "SIGNER_KEYPAIR" should be updated as well to be more specific

To be fair, that was renamed as part of this: https://github.com/solana-labs/solana/pull/12939
But will need to be fixed up again after the revert I am doing.

**Comment by CriesofCarrots** [comment]
@mvines what kind of balance excess were you envisioning? Anything over the rent-exempt minimum for the program?

**Comment by mvines** [comment]
> Anything over the rent-exempt minimum for the program?

Yep.  I always want to pay the minimum.  🐉

**Comment by t-nelson** [comment]
> > I think the generic arg name "SIGNER_KEYPAIR" should be updated as well to be more specific
> 
> To be fair, that was renamed as part of this: #12939
> But will need to be fixed up again after the revert I am doing.

This went back in as part of #13046
