### ISSUE TITLE
Clients don't get feedback about bad transactions

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#1298]
If a transaction makes it past signature verification, binary format verification, and even Budget's verify_plan(), it still might fail in the contracts engine. At that point, its `signature` will still be in the `last_ids` queue, and the client will be able to confirm its signature was accepted (and fee collected), but not know that the transaction was rejected by the contracts engine.

Note that this feature would be a usability feature for the client and is not a requirement. It's generally up to the client to submit a valid transaction and anything else could be considered part of a DDoS attack on the network. Bonus points for making any solution here optional.

Proposed solution:
In bank.rs, don't just the transaction's signature (in `HashSet<Signature>`). Instead, map that signature to its  current state. Something like `HashMap<Signature, Result<()>>`. What `Result` is exactly needs some experimentation. And perhaps we want that `Ok(())` to be `Ok(ProgramState)` where `ProgramState` might be something like `Verifying`, `Pending`, `Done`.

**Comment by garious** [comment]
@mvines, fyi

**Comment by aeyakovenko** [comment]
@garious i am stealing this.  the work to make bank mt safe is touching this shared data structure.

**Comment by aeyakovenko** [comment]
t

**Comment by garious** [comment]
@aeyakovenko, Why did you close this?

**Comment by garious** [comment]
I'll use this ticket to track the missing unit-tests on #1301, as well as running that error up to jsonrpc. I'll merge #1301 sooner than later since it duplicates some work in @aeyakovenko's PR.

**Comment by garious** [comment]
@aeyakovenko, I stole this back. Most of the work was done in #1301 and I plan to do the rest tomorrow.
