### ISSUE TITLE
RPC Banks service cannot be load balanced on GCP

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#13003]
#### Problem
RPC Banks service cannot be load balanced on GCP because GCP only load balances over HTTP/HTTPS, not arbitrary TCP ports. This is a blocker for rolling out support on mainnet.

#### Proposed Solution
Use websocket protocol instead of raw TCP / bincode encoding

tag @garious

**Comment by jstarry** [comment]
Then, requests could be proxied by path (https://api.mainnet-beta.solana.com/banks) on API nodes to a private port (8902)

cc @mvines

**Comment by mvines** [comment]
Banks service is not longer included in the validator
