### ISSUE TITLE
Failing test, possible race condition: test replicator::tests::test_replicator_startup

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#1315]
Occasional CI test failure seen in multiple PR CI results, usually in perf-stable: 
- https://buildkite.com/solana-labs/solana/builds/3461#400bee3a-a645-4143-a242-d439ec6e305f
- https://solana-ci-gate.herokuapp.com/buildkite_public_log?https://buildkite.com/solana-labs/solana/builds/3461#stable-perf

```
test replicator::tests::test_replicator_startup ... FAILED
--
  | ERROR 2018-09-24T05:00:23.078945231Z: solana::window_service: window error: SendError
```

**Comment by sakridge** [comment]
I think it may be fixed now.
