### ISSUE TITLE
Improve solana-program docs.rs information on the differences between Account, KeyedAcount, and AccountInfo

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#13154]
KeyedAcount in particular is only needed by native programs, normal BPF users don't need to care about it.  The relationship between Account and AccountInfo is also a little confusing for new users.

**Comment by jackcmay** [comment]
@mvines Do we still need to track this now that we've broken out the program stuff in the SDK and the program portion only includes definitions for `AccountInfo`?

**Comment by mvines** [comment]
Na, I think we arrived at a decent place already
