### ISSUE TITLE
explorer: Update instruction details cards to handle v1.4 parsed-instructions changes 

### ISSUE THREAD

**Issue by oJshua** [solana-labs/solana#13173]
#### Problem
The new parsed instructions functionality added in v1.4 (https://github.com/solana-labs/solana/pull/12998) breaks some of the existing instruction detail cards. 

Example: https://explorer.solana.com/tx/L2pwSQbf1GxMcrYEuVbtBPzo2YxjsUFTFDqkK3RskEGX85MUbgYHtYDEwfymcDg7YdQAsiNF1CzeW92mRpuoh3h?cluster=testnet

#### Proposed Solution
Fix instruction cards by accounting for new parsed instruction format outlined in https://github.com/solana-labs/solana/pull/12998

**Comment by jstarry** [comment]
System instruction cards broke due to this https://github.com/solana-labs/solana/pull/13202

**Comment by jstarry** [comment]
We have no way to opt into parsed accounts for different programs
