### ISSUE TITLE
Identify ideal GPU configuration for cloud nodes

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#1325]
The GCE scripts are configuring testnet with 4 K80 GPUs. The testnet performance for leader node is sub-optimal with these GPU cores. I tried using 2 V100 GPUs, and there was big jump in TPS performance.

4x K80 =>  ~130K TPS
2x V100 => ~250K TPS

This performance was not sustainable across network, as validators started lagging, and finality numbers were bad.

This ticket is to track performance wrt GPU.

**Comment by pgarg66** [comment]
We should consider switching testnet-master to 2 V100 GPUs.
Performance with 4 K80 GPUs
<img width="923" alt="screen shot 2018-09-27 at 9 36 25 am" src="https://user-images.githubusercontent.com/40076733/46168167-8e917300-c24c-11e8-85fc-f91a5bbd4424.png">

Performance with 2 V100 GPUs
<img width="928" alt="screen shot 2018-09-27 at 11 58 19 am" src="https://user-images.githubusercontent.com/40076733/46168219-acf76e80-c24c-11e8-85a9-5ccda529454a.png">

The GPUs can be configure from command line (https://github.com/solana-labs/solana/pull/1376)

**Comment by pgarg66** [comment]
@mvines , thoughts?

**Comment by mvines** [comment]
Sure, we can switch `testnet-perf` to 2 V100s as well for symmetry, once 0.9 branches.

**Comment by pgarg66** [comment]
Would you change the setup? If so, you can take over this ticket.

**Comment by mvines** [comment]
Done
