### ISSUE TITLE
Upgrade ci system images to Ubuntu 18.04

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#1326]
We're driving 16.04 right now

Depends-on: https://github.com/solana-labs/solana/issues/1702

**Comment by garious** [comment]
@mvines, can we get this into Pillbox? OS upgrades are such a hassle. Would love to bite the bullet sooner than later.

**Comment by mvines** [comment]
Sure, it's just some background work

**Comment by mvines** [comment]
Still looking for my 🍀.  No progress to report, not forgotten of course, just no time thus far

**Comment by mvines** [comment]
sry 👢

**Comment by mvines** [comment]
net/ has now switched over the 18.04.  The CI machines are still 16.04-based, but I don't see much hurry to upgrade them at this time.  This'll happen organically the next time we need to rebuild the CI images.  Punting this work to a future date since it's lowpri

**Comment by mvines** [comment]
Fixed when I moved CI to Azure last month
