### ISSUE TITLE
keypair_from_seed

### ISSUE THREAD

**Issue by yenkhoon** [solana-labs/solana#13297]
#### Problem
Hi, I want to use this function keypair_from_seed, what is the seed parameter here? Can I pass in bip39 mnemonic?

**Comment by t-nelson** [comment]
`solana_sdk::signature::keypair_from_seed()` is just a wrapper around `ed25519_dalek::Keypair::from_bytes()`.  It takes an array of random bytes from your favorite CSPRNG.

If you want to use a BIP39 seed phrase, check out `solana_clap_utils::keypair::keypair_from_seed_phase()` instead
