### ISSUE TITLE
explorer: Use anchor links for subsections

### ISSUE THREAD

**Issue by oJshua** [solana-labs/solana#13295]
#### Problem
Explorer doesn't provide anchor links for the various sections displayed. For example, on the transaction page, it would be nice if you could link someone directly to the "Account Inputs" section.

#### Proposed Solution
- Add anchor links to all major sections
- Update current url w/ anchor hash as user scrolls

**Comment by oJshua** [comment]
There is a library to update the anchor as a user scrolls, but it seems too invasive (https://pvoznyuk.github.io/react-update-url-on-scroll). I think just adding anchors to sections should be fine.

**Comment by oJshua** [comment]
@KitanGarcia thanks for offering to take this on! I think we want anchors Explorer-wide on the major headings. An anchor for each instruction would be helpful.

**Comment by KitanGarcia** [comment]
@oJshua Awesome, sounds good! I've been looking [here]( https://github.com/solana-labs/solana/blob/master/CONTRIBUTING.md) for guidelines. But didn't find a description of branch naming conventions. For the future, is there a convention I should follow when naming this branch?

**Comment by KitanGarcia** [comment]
@oJshua Got another question for you. I cloned the solana repo and have been trying to get set up by following the ReadMe. Is there any way to just work with Explorer? After running ```cargo build``` and ```cargo test``` on the repo, this project is taking over 90 GB and my computer ran out of storage.

**Comment by oJshua** [comment]
@KitanGarcia thanks for your patience on this. I'm working with ops to find a solution. Stay tuned.

**Comment by oJshua** [comment]
@KitanGarcia Give this another try and it should work fine!

**Comment by KitanGarcia** [comment]
@oJshua Thanks for looking into this! I'll give it another go as soon as I can. I was able to get things working for testing by using the custom URL option along with https://api.metaplex.solana.com/ for the API calls. I'm not sure if it's been seen yet, but I've made a PR [here](https://github.com/solana-labs/solana/pull/23151). Would love any feedback!

**Comment by oJshua** [comment]
Perfect, thanks for the heads up @KitanGarcia !

**Comment by KitanGarcia** [comment]
@oJshua Just saw that the run failed because I didn't run prettier! Apologies for that amateur mistake, somehow I didn't see that. I ran prettier on the two problematic files, did ```npm run build``` and ```npm run test``` and everything looks to be passing and in order. Just updated the PR. Please let me know if there are any other issues. Thanks for your patience!

**Comment by CriesofCarrots** [comment]
Explorer code is here now: https://github.com/solana-labs/explorer
