### ISSUE TITLE
solana crate blocked by jsonrpc 

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#1333]
published crates' dependencies must be published crates

update these to published crates or fork/pull them into Solana:
```
jsonrpc-core = { git = "https://github.com/paritytech/jsonrpc", rev = "4b6060b" }
jsonrpc-http-server = { git = "https://github.com/paritytech/jsonrpc", rev = "4b6060b" }
jsonrpc-macros = { git = "https://github.com/paritytech/jsonrpc", rev = "4b6060b" }
```

**Comment by garious** [comment]
@CriesofCarrots, we need you to push paritytech to make a release or find a way off the those dependencies.
