### ISSUE TITLE
Add RPC mechanism to subscribe to transaction notifications

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#1339]
To avoid front-end polling we need a streaming API that enables:
* [ ] Notification when a given transaction signature is confirmed
* [ ] Notification when userdata for a given account public key changes

**Comment by borromeotlhs** [comment]
Interesting.  where is this streaming API supposed to land, and what components will it talk to?  Is it to act as a read only mechanism, a la "On Optimistic Methods for Concurrency Control"?

**Comment by mvines** [comment]
It’ll likely be first exposed in documentation form in doc/json-rpc.md and then rolled up into
https://github.com/solana-labs/solana-web3.js for convenience.

Definitely real-only, it’s just a way to interrogate the current state of the ledger (up to the latest finalized transactions, pending or in-flight transactions would not be visible).  To mutate a transaction must be submitted.

**Comment by borromeotlhs** [comment]
I saw that.  I think that I was looking for: https://github.com/solana-labs/solana/blob/9c47e022dcbff00488fcc7582859eba95a8db490/src/rpc.rs

I found it, so am now just snooping around solana-web3.js, the tictactoe example, the above file.

I just like these little snippets to occupy my 'compile time', and am thinking that either:
https://github.com/claudijo/json-rpc-server-stream 
OR
https://github.com/joyent/node-fast

should suffice for your all's needs.  I'll have to see whether you all care about MIT licensing on software that implements the [JSON-RPC 2.0 Specification](https://www.jsonrpc.org/specification). . .

If you all do, then I'd just as soon look for a few more minutes for an Apache licensed version, though I think the use of Apache is smart for the base project, I don't think it'll be necessary for json streaming. 

In the interim, there is an ISC licensed version [here](https://github.com/JsCommunity/json-rpc-peer).
