### ISSUE TITLE
Document/implement pattern for upgrading a program

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#1340]
Use case:
1. Program A is deployed
2. Users make use of it, and discover a bug
3. Bug is fixed, program A` now needs to be deployed.

How do we migrate all the Users and account data over to the program A`.

**Comment by mvines** [comment]
The Solidity way is to create a parent contract that delegates all calls to the upgradable/swappable child.  We can probably do the same once Signals are available. 
Depends-on: #1348

**Comment by garious** [comment]
So program A' would be published under a new program_id. The original program would need to support registration of an upgraded program_id. That program_id would need to come from a signed pubkey that the program author trusts. When the next tx targeting one of the program's processes, the program can reassign ownership to the new program_id and then reschedule the same tx for processing (using a signals).

What's concerning about this mechanism is that a client wouldn't know a program implements this feature (unless they can read BPF bytecode) and when it does, is subject to having all tokens spent immediately when a program owner maliciously changes the program.

We should consider disallowing a program to delegate its operational semantics to a program that wasn't on the ledger before a process it created. I'm not sure how we could add that restriction.

**Comment by mvines** [comment]
Another approach would be a have a "name server" contract that maps a name into a pubkey.  Clients need to always perform a name look-up for the desired program.  This way the client is always aware of when an upgrade occurs.

The "name server" contract is updated by whatever scheme it wants (central authority, m/n votes).  Program data migration could be gnarly, and would need to be managed during the upgrade process by the entity performing the upgrade

**Comment by mvines** [comment]
(bump to 0.11, doesn't need to block 0.10 anymore)

**Comment by jackcmay** [comment]
@mvines @garious Resurrecting this issue, we don't have a process yet for upgrading programs (for example when a bug is found in our token program).

Something like migrating all the accounts associated with a particular program id to the new patched program id sounds painful.

**Comment by jackcmay** [comment]
This issue has been addressed by the upgradeable loader: https://docs.solana.com/cli/deploy-a-program

**Comment by z3r086** [comment]
> (bump to 0.11, doesn't need to block 0.10 anymore)

**Comment by z3r086** [comment]
> Another approach would be a have a "name server" contract that maps a name into a pubkey.  Clients need to always perform a name look-up for the desired program.  This way the client is always aware of when an upgrade occurs.
> 
> The "name server" contract is updated by whatever scheme it wants (central authority, m/n votes).  Program data migration could be gnarly, and would need to be managed during the upgrade process by the entity performing the upgrade
> 
>

**Comment by z3r086** [comment]
> So program A' would be published under a new program_id. The original program would need to support registration of an upgraded program_id. That program_id would need to come from a signed pubkey that the program author trusts. When the next tx targeting one of the program's processes, the program can reassign ownership to the new program_id and then reschedule the same tx for processing (using a signals).
> 
> What's concerning about this mechanism is that a client wouldn't know a program implements this feature (unless they can read BPF bytecode) and when it does, is subject to having all tokens spent immediately when a program owner maliciously changes the program.
> 
> We should consider disallowing a program to delegate its operational semantics to a program that wasn't on the ledger before a process it created. I'm not sure how we could add that restriction.
