### ISSUE TITLE
RPC: getConfirmedBlock to retrieve multiple blocks

### ISSUE THREAD

**Issue by TheLoneRonin** [solana-labs/solana#13421]
### Problem

Currently, the RPC only supports retrieving one block at a time via the `getConfirmedBlock` command. It would be great to be able to retrieve multiple blocks via the same command. The changes shouldn't be intrusive and should have full compatibility with the existing

### Proposed Solution

It's important that the RPC command preserves fallback compatibility with the current functionality.

```json
{
  "jsonrpc": "2.0",
  "id":1,
  "method":"getConfirmedBlock",
  "params":[430, "json"]
}
```

And can instead now accept more params in the RPC request like the following:

```json
{
  "jsonrpc": "2.0",
  "id":1,
  "method":"getConfirmedBlock",
  "params":[430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, "json"]
}
```

Returning an array of block objects in the result.

**Comment by jstarry** [comment]
JSONRPC actually already has batching built in, try this:

```json
[
  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getConfirmedBlock",
    "params": [
      1
    ]
  },
  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getConfirmedBlock",
    "params": [
      2
    ]
  }
]
```

**Comment by TheLoneRonin** [comment]
@jstarry, oh my goodness, my bad.
Closing now. Thanks for informing me about the batched requests.
