### ISSUE TITLE
docs: Improve exchange integration page

### ISSUE THREAD

**Issue by ryoqun** [solana-labs/solana#13443]
#### Problem

There is some desired improvments by supporting exchanges:

The exchange integration page(https://docs.solana.com/integrations/exchange)...:

-  dones't mention solana-systuner (causes innocent validator's crash)
- needs to explicitly mention about unrecommended status for docker not by indirectly via validator req page link, but rather directly on the page.
- doesn't explain stable/edge/stable release channel; exchanges are continuously mislead to using/trying v1.4

**Comment by mvines** [comment]
Also we should mention that exchanges should monitor the #mb-announcements channel in our Discord (https://solana.com/discord) for important notifications and software updates to mainnet-beta.  This is the sole location where we publish this information

**Comment by ryoqun** [comment]
> Also we should mention that exchanges should monitor the #mb-announcements channel in our Discord (https://solana.com/discord) for important notifications and software updates to mainnet-beta. This is the sole location where we publish this information

This is done at #12953 : https://docs.solana.com/integrations/exchange#new-software-release-announcements

**Comment by ryoqun** [comment]
also, mention about `solana catchup`.

**Comment by ryoqun** [comment]
also, consider `solana-validator --no-snapshot-fetch-unless-empty-ledger`, and when the option is specified leave some stable message in log or marker file in the ledger dir for the downloaded snapshot's slot number.

**Comment by ryoqun** [comment]
Also, add `--limit-ledger-size` explanation.

**Comment by ryoqun** [comment]
- Also discourage of `--no-wait` and write simple cli retry steps.
- also recommend metrics submission.

(yeah, quite much is buffered here. I'll flush to write them at once soon.)

**Comment by ryoqun** [comment]
maybe backref --accounts-index from rpc-page.

**Comment by ryoqun** [comment]
Also mention `solana rent` (kudos to @t-nelson) and system account =~ normal retail user's account

**Comment by ryoqun** [comment]
also, some misecclaneous check-lists for the integration:

- `--no-snapshot-fetch`
- paired `cli` update 
- log rotation
- metrics
- `--limit-ledger-size`
- `--secondary-index`

**Comment by ryoqun** [comment]
add iops to the hardware recommendation mainly targeted to clould computing?

**Comment by CriesofCarrots** [comment]
These docs are now supported in the foundation repository: https://github.com/solana-foundation/developer-content
