### ISSUE TITLE
Kick offline nodes from leader schedule

### ISSUE THREAD

**Issue by leoluk** [solana-labs/solana#13458]
#### Problem

Offline nodes adversely affect network performance. Unbonding is slow and delegators may be unresponsive. Offline nodes may remain in the leader schedule for many epochs while being obviously offline.

#### Proposed Solution

Offline nodes should be removed from the next epoch's validator set until the operator sends a transaction to indicate that they resolved the issue (similar to the "jail/unjail" mechanism in cosmos-sdk).

**Comment by pkrasam** [comment]
100% supportive of a mechanism to avoid offline nodes adversely affecting the network performance.

Curious, how does offline nodes being on the leader schedule affect the network currently?

Is there a way to filter out the offline nodes from the leader schedule prior to starting a new epoch?

And/Or send the offline nodes to an **alcatraz island** queue until such time they are able to resolve their pending issue and signal that they are back online by submitting a signal transaction on-chain!

**Comment by leoluk** [comment]
> And/Or send the offline nodes to an alcatraz island queue until such time they are able to resolve their pending issue and signal that they are back online by submitting a signal transaction on-chain!

This is basically how it works in cosmos-sdk - a validator that misses a specific number of blocks in a window will be marked as jailed, at which point they're no longer considered bonded. They can rejoin at any time by sending an unjail tx.

**Comment by brianlong** [comment]
+1 Good idea.

Just short of slashing, perhaps we could also reverse the related staking transactions. The delegator gets their SOL back and the validator needs to start over with a new stake. No need for the un-jail mechanism if the stake is reverted.

Link to the related discussion on Discord: https://discord.com/channels/428295358100013066/689412830075551748/809488139042160701

**Comment by mvines** [comment]
Fixed by #23932, whereby stake delegated to vote accounts that are delinquent for 5 epochs may be deactivated by anybody as a common good for the network
