### ISSUE TITLE
Try using capnproto for Transaction data serialization

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#1346]
https://github.com/solana-labs/example-tictactoe/ uses CBOR to serialize/deserialize data across the front-end <=> program boundary.   

CBOR is nice as it's schema-less and smaller than JSON (but just as expressive).  But the wire format is larger than something like protobuf that assumes all parties share the schema, and if you're paying by the bit then you want your userdata to be as small as feasible. Note that Rust bincode is not a good option as there is very limited support in other languages.

Both npmjs.com and crates.io have multiple package for dealing with protobuf

**Comment by mvines** [comment]
https://capnproto.org/ looks like possible alternative to protobuf

**Comment by mvines** [comment]
(moving out, we can hand-serialize for now...)

**Comment by mvines** [comment]
capnproto is looking quite promising.  There is:
1. A C backend at https://github.com/mikegarts/c-capnproto-1 which produces quite reasonable looking serde code
2. A JS backend at https://github.com/capnp-js that looks nice

Upon trying to use the C backend in a BPF project I was immediately blocked by the following LLVM+BPF issues: #1396, #1802 and #1803 🤕

Once these are resolved, it should be doable to `#include` the C backend generated source file and library file within a BPF .o

**Comment by mvines** [comment]
Here's the capnproto interface definition I was using to uncover the blocking issues:
```
@0xaf6c078575cf03cb;
struct Date {
  year @0 :Int16;
  month @1 :UInt8;
  day @2 :UInt8;
}
````

**Comment by rob-solana** [comment]
is this still blocked?

**Comment by mvines** [comment]
Unsure, @jackcmay ?

**Comment by jackcmay** [comment]
Should no longer be blocked in C
