### ISSUE TITLE
Expose PoH height to programs

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#1359]
Similarly to the `block.number` in Solidity, we can expose the current PoH height as input to a program.  This can be used as a rough approximation of time, and alleviates the need for an Oracle (#1341) in some use cases

**Comment by garious** [comment]
@jackcmay, can you keep this ticket in mind as we standardize the interface to programs and integrate with the bank? There might be a small handful of data that we want to expose to programs, such as PoH height. We need to be care to ensure that any data passed in is done so consistently between the leader and validator nodes.  And @aeyakovenko, this is another argument for stalling PoH Ticks once transaction processing has begun.

**Comment by mvines** [comment]
(bump to 0.11, doesn't need to block 0.10 anymore)

**Comment by aeyakovenko** [comment]
@garious when votes are gossiped around they need a height as well, although that could just be in the vote's userdata.

**Comment by mvines** [comment]
To achieve this, looks like we'll need to augment `native_loader::process_instruction()`, as well as the native program entrypoints with another argument containing "extra info" for instructions, such as `bank. tick_height()`, to avoid a backwards dependency from the loaders into the bank
