### ISSUE TITLE
Improve Signer trait, documentation

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#13670]
#### Problem
The dyn Signer trait is too difficult to figure out how to use in new cli applications, preventing integration of remote-wallet support potentially useful places.

#### Proposed Solution
Examine the api to see if it could be simplified/improved
Add better documentation such that dyn Signer (as well as the relevant clap validators and parsers) can be used out of the box

**Comment by billythedummy** [comment]
Related: https://github.com/solana-labs/solana/issues/34983
