### ISSUE TITLE
Compromising all validators of the Solana network

### ISSUE THREAD

**Issue by c29r3** [solana-labs/solana#13757]
#### Problem
Solana-gossip standard tools allow you to compromise validators and carry out DDoS \ DoS attacks by spoofing the source IP.  Multiple `solana-gossip` instances running with different validator-keys for 1 ip will cause a huge traffic flow. The owner of the IP will receive a lot of UDP traffic, which can be regarded as a DDoS attack. The victim can send abuse to the attackers (validators) IP, as a result of which the hosting provider will block the rented servers. 
Impact to TdS and MB

`solana-gossip spy --gossip-host {victim_ip} --entrypoint testnet.solana.com:8001 -i random-validator-key.json -E 999`

![image](https://user-images.githubusercontent.com/52304443/99929381-17899380-2d5e-11eb-83d9-2f28c5223250.png)
![image](https://user-images.githubusercontent.com/52304443/99929386-1f493800-2d5e-11eb-8710-aa0fe6d0c24c.png)  
also using this you can overload any of Solana's validators  
Found in TdS Stage #10

#### Proposed Solution
Source ip pre-check by establishing TCP connection

**Comment by aeyakovenko** [comment]
Seems like a dup of https://github.com/solana-labs/solana/pull/12794

**Comment by leoluk** [comment]
Related: #8334, #9491, #9492, #12410, #12409

#12794 definitely solves this particular attack.
