### ISSUE TITLE
scripts/wallet-sanity.sh needs to reset its id between runs

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#1387]
Testnet-sanity is failing on master/0.9 because we don’t clear the wallet id anymore, which causes this assertion to fail: 
https://github.com/solana-labs/solana/blob/v0.9/scripts/wallet-sanity.sh#L37

Example failure: 
https://buildkite.com/solana-labs/testnet-sanity/builds/2810#a41ee78f-a809-4eb2-ae69-7d9de8818776

**Comment by CriesofCarrots** [comment]
Ah yes. Options here include: deleting `.config/solana/id.json` before the first `solana-wallet` command; running `solana-keygen` at the top of wallet-sanity; or checking wallet balance first thing and spending any tokens >0
@mvines do you have a preference?

**Comment by mvines** [comment]
Running keygen to just explicitly create a new wallet seems nice.   Can you take this issue?

**Comment by CriesofCarrots** [comment]
Yep!

**Comment by mvines** [comment]
Hmm, this still reproduces with #1388

**Comment by mvines** [comment]
Ah, the network just needs to be redeployed first I think

**Comment by mvines** [comment]
Yep redeploy got things unstuck
