### ISSUE TITLE
Executable changes are not persisted in instruction execution context

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#13907]
#### Problem
If a program marks an account as executable, then any instructions that it calls should fail if they attempt to modify the account. Since the runtime doesn't track changes to whether an account is executable, it allows those instructions to succeed but will not return those state changes to the caller program due to this check:

https://github.com/solana-labs/solana/blob/10c81a2448c1db49e010afbbed94ac48209cba48/programs/bpf_loader/src/syscalls.rs#L1422

#### Proposed Solution
Set `is_executable` flag in `PreAccount.update`

https://github.com/solana-labs/solana/blob/10c81a2448c1db49e010afbbed94ac48209cba48/runtime/src/message_processor.rs#L156-L166

**Comment by jackcmay** [comment]
Marking an account executable by a BPF program is not currently supported.  But, a BPF program could call the BPF loader to finalize and that execution marker would be lost.
