### ISSUE TITLE
BPF ComputeBudget should be transaction wide

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#13912]
There's currently a (bpf) compute budget within each instruction, but no compute budget across the entire transaction.   This allows me to create transactions that are _probably_ too expensive.  

Suggest that we:
1. Monitor the median, 95th, 99th percentile of the compute budget used by mainnet-beta transactions.  We can do so by running a custom node.
2. Add a feature to cap the transaction-wide compute budget to somewhere between 5-10x the compute budget of a single BPF instruction while considering how many transactions that would start to fail based on the data collected from 1.

**Comment by jackcmay** [comment]
Resolved via: https://github.com/solana-labs/solana/pull/18631
