### ISSUE TITLE
Incompatible intrinsics between rustc and llc

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#1392]
Compiling rust code with rustc and passing it to llc to be converted to bpf assembly can result in what looks like a conflicting definition of llvm intrinsics

```
Intrinsic has incorrect argument type!
void (i8*, i8, i64, i1)* @llvm.memset.p0i8.i64
```

Issue seen when running rustc 1.29.0 but also after aligning the llvm versions pretty closely:

```
rustc --version --verbose
rustc 1.26.0 (a77568041 2018-05-07)
binary: rustc
commit-hash: a7756804103447ea4e68a71ccf071e7ad8f7a03e
commit-date: 2018-05-07
host: x86_64-apple-darwin
release: 1.26.0
LLVM version: 6.0
```

```
llc --version
LLVM (http://llvm.org/):
  LLVM version 6.0.1
  Optimized build.
  Default target: x86_64-apple-darwin17.7.0
  Host CPU: skylake
```

**Comment by garious** [comment]
LLVM has been notoriously bad about bitcode compatibility across versions.  In this case, it looks like they've respected semantic versioning and bumped the major number between rustc 1.26 and 1.29. Seems fair to not expect compatibility here. What happens when you use the llc from llvm-7?

**Comment by jackcmay** [comment]
Yup, that was the next step, tried it now and the intrinsic incompatibilities go away :-)
