### ISSUE TITLE
C to BPF compilation fails when including stdint.h

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#1395]
Building a BPF program from C  using both clang and llc fails when pulling in std headers such as stdint.h

Looking at the linux BPF examples its clear that this is not expected since they include headers such as stdint.h.  This could be a case of referring to wrong headers or mayer a MacOS specific issue

```
/usr/local/opt/llvm/bin/clang -target bpf -O2 -emit-llvm -fno-builtin -o out.bc -c src.c
/usr/local/opt/llvm/bin/llc -march=bpf -filetype=obj -function-sections -o out.o out.bc
```

```
In file included from src/move_funds.c:2:
In file included from /usr/local/Cellar/llvm/6.0.1/lib/clang/6.0.1/include/stdint.h:63:
In file included from /usr/include/stdint.h:52:
In file included from /usr/include/sys/_types.h:32:
/usr/include/sys/cdefs.h:763:2: error: Unsupported architecture
#error Unsupported architecture
 ^
```

One workaround is to self define the needed types (like uint64_t)

**Comment by garious** [comment]
Looks like a sysroot problem to me.  We should probably be cross-compiling to an old version of Linux.  Are you familiar with LLVM's "triple" and sysroot options?

**Comment by mvines** [comment]
@jackcmay - Is this issue obsolete?

**Comment by jackcmay** [comment]
Not obsolete, but very low priority
