### ISSUE TITLE
blockhash unintuitively expires quickly on cluster short stall

### ISSUE THREAD

**Issue by ryoqun** [solana-labs/solana#13987]
#### Problem

When the cluster stops to make slots rooted/maxed, lastly-available rooted/maxed blockhash could be regarded to expire too quickly. This causes transaction using the blockhashes as their `recent_blockhash` expires too quickly, partly causing false positive in transaction simulation.

For example, we had small cluster pause around 2020-12-06T03:35:08 - 2020-12-06T03:35:35 (UTC):

![image](https://user-images.githubusercontent.com/117807/101357938-7feb7f80-38dd-11eb-9967-1bb96b63bef8.png)

![image](https://user-images.githubusercontent.com/117807/101357966-8ed23200-38dd-11eb-97ac-a94810439670.png)

```
$ cat solana-validator.log.2 | grep "block_height=" | grep -n -C3 -E '53468880|53468954'
168674-[2020-12-06T03:35:07.858041700Z INFO  solana_metrics::metrics] datapoint: bank-new_from_parent-heights slot_height=53468878i block_height=50502184i
168675-[2020-12-06T03:35:08.174823970Z INFO  solana_metrics::metrics] datapoint: bank-new_from_parent-heights slot_height=53468879i block_height=50502185i
168676-[2020-12-06T03:35:08.701002735Z INFO  solana_metrics::metrics] datapoint: bank-new_from_parent-heights slot_height=53468881i block_height=50502185i
168677:[2020-12-06T03:35:08.819697095Z INFO  solana_metrics::metrics] datapoint: bank-new_from_parent-heights slot_height=53468880i block_height=50502186i
168678-[2020-12-06T03:35:10.215684060Z INFO  solana_metrics::metrics] datapoint: bank-new_from_parent-heights slot_height=53468888i block_height=50502187i
168679-[2020-12-06T03:35:10.217844282Z INFO  solana_metrics::metrics] datapoint: bank-new_from_parent-heights slot_height=53468885i block_height=50502187i
168680-[2020-12-06T03:35:10.838833763Z INFO  solana_metrics::metrics] datapoint: bank-new_from_parent-heights slot_height=53468889i block_height=50502188i
--
168741-[2020-12-06T03:35:34.228834438Z INFO  solana_metrics::metrics] datapoint: bank-new_from_parent-heights slot_height=53468952i block_height=50502237i
168742-[2020-12-06T03:35:34.793366893Z INFO  solana_metrics::metrics] datapoint: bank-new_from_parent-heights slot_height=53468956i block_height=50502237i
168743-[2020-12-06T03:35:34.796602173Z INFO  solana_metrics::metrics] datapoint: bank-new_from_parent-heights slot_height=53468953i block_height=50502238i
168744:[2020-12-06T03:35:35.171448240Z INFO  solana_metrics::metrics] datapoint: bank-new_from_parent-heights slot_height=53468954i block_height=50502239i
168745-[2020-12-06T03:35:35.610877503Z INFO  solana_metrics::metrics] datapoint: bank-new_from_parent-heights slot_height=53468955i block_height=50502240i
168746-[2020-12-06T03:35:36.523589569Z INFO  solana_metrics::metrics] datapoint: bank-new_from_parent-heights slot_height=53468957i block_height=50502241i
168747-[2020-12-06T03:35:36.991714902Z INFO  solana_metrics::metrics] datapoint: bank-new_from_parent-heights slot_height=53468958i block_height=50502242i

```

Here, the cluster stalled to optimistically-confirm slots around 25 secs between slot 53468880 and slot 53468954. This implies that validators returned the same blockhash for around that amount of duration with commitment=root/max.

After the pause, the cluster jumped to slot 53468954/height 50502239 from slot 53468880/height 50502186, meaning it expired 53 older part of blockhashes (`50502239 - 50502186`) within very short period of time, this is roughly 33% of `MAX_PROCESSING_AGE` (= 150 slots/1 min; a duration when any given blockhash could be used for txes).

Finally, this means if client did simulatetransaction with commitment=root/max (this is recommended thing, I guess) at the time of later part inside the pause window with somewhat older recent_blockhash (= the older 33% of the all usable recent blockhashes), the simulation could succeed as a false positive (=success tx). But in reality, the suceeded tx could have been expired at the time it got chance of being included into newly-created blocks on top of tip of major fork.

#### Proposed Solution

Maybe consider real time passage within simulate transaction for possible short cluster stall?

**Comment by ryoqun** [comment]
(I think because we're now confirmed/singleGossip everywhere by default, we can lower this issue's importance)

**Comment by ryoqun** [comment]
CC: @jstarry @CriesofCarrots after some debugging as part of https://github.com/solana-labs/solana-program-library/pull/1528, this problem manifests as a very odd `blockhash not found` errors from `sendTransaction` with completely correct usage, which rather shouldn't happen. I have this dirty patch, but dunno how this is common to prioritize. Do you recall similar reports from the dev community? 
Hmm, quick discord search tells numerous reports. so, should we fix this with higher priority, I guess.

This is another pretty naughty reliability bug although this is somewhat rare.

```patch
@@ -1353,7 +1353,8 @@
 const PublicKeyFromString = superstruct.coerce(superstruct.instance(PublicKey), superstruct.string(), value => new PublicKey(value));
 const RawAccountDataResult = superstruct.tuple([superstruct.string(), superstruct.literal('base64')]);
 const BufferFromRawAccountData = superstruct.coerce(superstruct.instance(buffer.Buffer), RawAccountDataResult, value => buffer.Buffer.from(value[0], 'base64'));
-const BLOCKHASH_CACHE_TIMEOUT_MS = 30 * 1000;
+const BLOCKHASH_CACHE_TIMEOUT_MS = 30 * 1000;   //  <=== Reducing this (like x10) didn't completely solved.. so,,...
+const BLOCKHASH_NOT_FOUND_ERROR_MESSAGE_REGEXP = /Blockhash not found$/;
 /**
  * Extra contextual information for RPC responses
  *
@@ -3474,11 +3479,14 @@
   async sendTransaction(transaction, signers, options) {
     if (transaction.nonceInfo) {
       transaction.sign(...signers);
+      const wireTransaction = transaction.serialize();
+      return await this.sendRawTransaction(wireTransaction, options);
     } else {
       let disableCache = this._disableBlockhashCaching;
 
       for (;;) {
         transaction.recentBlockhash = await this._recentBlockhash(disableCache);
         transaction.sign(...signers);
 
         if (!transaction.signature) {
@@ -3492,15 +3500,21 @@
         if (!this._blockhashInfo.transactionSignatures.includes(signature)) {
           this._blockhashInfo.transactionSignatures.push(signature);
 
-          break;
+          const wireTransaction = transaction.serialize();
+          try {
+            return await this.sendRawTransaction(wireTransaction, options);
+          } catch (err) {
+            // maybe we should take consider of the skipPreflight flag.
+            if (!BLOCKHASH_NOT_FOUND_ERROR_MESSAGE_REGEXP.test(err.message)) {
+              throw err;
+            }
+            // we gave decently-fresh blockhash from our internal cache, but detected this failure!
+            // cluster must have had a short stall: https://github.com/solana-labs/solana/issues/13987
+            // so just continue to the next iteraton of this loop, triggering disableCache = true!
+            //console.log({retrying: err});
+          }
+          // also do similar for simulateTransaction?
         } else {
-           disableCache = true;
+           disableCache = true; // maybe put this else clause out of this if
         }
       }
     }
-
-    const wireTransaction = transaction.serialize();
-    return await this.sendRawTransaction(wireTransaction, options);
   }
   /**
    * @private

```

**Comment by ryoqun** [comment]
@jstarry @CriesofCarrots (allow me to tag again...) I saw this very odd `blockhash` error in the wild at Orca production env, iirc

**Comment by ryoqun** [comment]
the reason this bug occurs is that 30 sec ttl isn't always good enough. the fetched blockhash could already be as old as finalized (~12 secs) and somewhat minor cluster stall can trigger the blockhash not found error.

**Comment by jstarry** [comment]
@ryoqun are you suggesting decreasing the length of time we keep around cached recent blockhasyhes in web3?

**Comment by CriesofCarrots** [comment]
I think checking the error type and refreshing the cache on BlockhashNotFound, like in Ryo's quick patch, seems like a decent approach.

**Comment by CriesofCarrots** [comment]
This looks like a web3.js issue, ultimately, which is no longer in this repository; https://github.com/solana-labs/solana-web3.js
