### ISSUE TITLE
Wrap RPC return values in futures

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#141]
The accountant_stub functions all block. That's fine for the moment, but we'll want to make those all async calls very soon. A stepping stone to getting there is to wrap each return value in a future, and then update the callers (mostly in client-demo.rs) to use them.

See: https://crates.io/crates/futures

Note that the tokio framework reexports the same future library, so if we use that as our async runtime, it'll be a painless transition.

**Comment by garious** [comment]
We'll go with the latest. Thanks for asking! I see tokio hasn't made a release that uses it, but their latest code shows they're migrating.

**Comment by rlkelly** [comment]
ya it's definitely an improvement but a little tricky since it's a whole new framework
