### ISSUE TITLE
Persist gossip state to disk

### ISSUE THREAD

**Issue by mieubrisse** [solana-labs/solana#14117]
[Galen](https://github.com/galenmarchetti) and I are looking at whether https://github.com/kurtosis-tech/solana-testing could help with https://github.com/solana-labs/solana/issues/6396 and https://github.com/solana-labs/solana/issues/6393 , but our understanding from @aeyakovenko was that the setup time for large networks is a limiting factor due to gossip. If gossip state could be persisted to disk, we could have tests that bootstrap the same network quickly so setup time is short.

**Comment by mvines** [comment]
Some work in this direction at https://github.com/solana-labs/solana/pull/14289
