### ISSUE TITLE
move Last IDs HashMap out of the bank

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#1412]
The data structure used for duplicate detection should be moved out of the bank.
```
    last_ids: RwLock<VecDeque<Hash>>,
```

**Comment by garious** [comment]
This change is meant to be purely organizational. Both the `last_ids` VecDeque and the `last_ids_sig` HashMap should be moved along with their respective RwLocks. It's not clear to me if the RwLocks can stay in the bank. I *think* they could, but we'd have to review potential thread contention issues that might arise.

**Comment by garious** [comment]
This was removed out of the bank in the last release cycle and is now called `StatusDeque`.
