### ISSUE TITLE
Pre-Exit Snapshot

### ISSUE THREAD

**Issue by brianlong** [solana-labs/solana#14216]
#### Problem
The `solana-validator` runtime does not take a final snapshot before a normal exit (stop/restart).

#### Benefits
- We can restart much quicker after an update.
- We can improve validator performance by using larger values for `--snapshot-interval-slots` & `--maximum-local-snapshot-age`. The interval snapshots will be there for crash recovery only.

#### Proposed Solution
- Take a final snapshot pre-exit.
- Increase the default `--snapshot-interval-slots` to 500.

**Comment by ryoqun** [comment]
> Take a final snapshot pre-exit.

I think the quickest and easiest implementation for this is like this:
1. when node operator wants to restart their validator, they don't kill their validator.
1. they just start another validator process with `--graceful-restart` and just wait. (could timeout and start normally if old version validator is running or old validator is dead).
1.  (internally) new validator creates an empty marker file by `touch <LEDGER_DIR>/.graceful-restart` and stops the startup process at very early stage.
1.  (internally) old validator notices the marker file at the next root squash interval (like 100 slots) and schedules snapshot creation out of normal schedule from `--snapshot-interval-slots`. also record its pid in the marker file.
1. (internally) old validator succeeds in creating snapshots. (what if this failed or takes too long?)
1.  (internally) old validator exits with 0 and remove the marker file
1.  (internally) new validator sees old validator's pid is gone and missing marker file and finally new validator resumes the normal validator process.
1. after graceful restart, `--graceful-restart` doesn't affect validator operation at all.

Then, I think `--snapshot-interval-slots` can even be like 3000 or more (?) without `--no-snapshot-fetch` or 1000 or 2000 with `--no-snapshot-fetch`. So, when `--graceful-restart` is present in process args, we dynamically change the default value of `--snapshot-interval-slots` if it's not explicitly specified.

@mvines do you like the `--grace-restart` and default tuning of `--snapshot-interval-slots` approach from ops perspective?
@carllin @sakridge I think this could be another bandaid quickfix aiming for v1.4 backport. do you have any concerns for the implementation?

**Comment by mvines** [comment]
Defaulting `--snapshot-interval-slots` to 500 sgtm, we'll want to then restore this to 100 for the boot nodes but that's easy.

I love the idea of generating a final snapshot archive.  I've been secretly wanting this for a while as well.  I think the logic can be a little simpler though:
1. Install a SIGTERM handler
2. On SIGTERM, force that snapshot generation and once complete exit.   

Systemd gives a 90 second grace period by default for a process to exit after a SIGTERM.  This 90 second delay can be adjusted in the systemd unit file if the node needs more time (ideally it's still receiving new shreds as it's generating the final snapshot).

A SIGTERM handler allows us to cleanly shutdown other parts of a validator too
1. Report RPC as unhealthy for ~10 seconds to cause the RPC node to be removed from the global load balancer for clean RPC client shutdown.  Currently we just drop all active connections when an RPC node restarts. 
2.  Block until the SendTransactionService queue is empty.  Currently we just drop all pending transactions on the floor when an RPC node restarts.

**Comment by mvines** [comment]
> Defaulting --snapshot-interval-slots to 500 sgtm

I take it back.  Longer time between local snapshots means longer catchup time on restart, so I think this would be harmful.  Instead we can optimize snapshot creation.   But even with today's load, a well-tuned node should be able to manage to cough up a snapshot every ~100 slots

**Comment by sakridge** [comment]
Interesting, I didn't know about the 90 second limit. I did think it might be iffy to ctrl-c the process and then be doing a significant amount of work before shutting down.

Yea, we have replay problems playing significant amount of local ledger.

**Comment by mvines** [comment]
I'm actually thinking about stealing this from you @ryoqun, I think there's another way by making `solana-validator` a multi-command binary:
* `solana-validator start` -- what `solana-validator` does today, (and `solana-validator` with no command would continue to work as it does today)
* `solana-validator status` -- renders a status dashboard like what `solana-test-validator` provides
* `solana-validator wait-for-restart-window` -- monitors the validator, and exits with a 0 exit code once the validator is caught up, has produced a fresh snapshot, and potentially when there's a gap in the leader schedule that would allow the validator to restart without missing any slots (only works for lesser staked nodes of course)

The `status`/`wait-for-restart-window` commands would obtain information through a combination of monitoring the ledger/ directory and local RPC

**Comment by ryoqun** [comment]
@mvines Nice idea! I have 2 cents:

- `solana-validator init` or `solana-validator prepare-ledger` or `solana-ledger-tool create-ledger`: download snapshot and genesis archive and just create the ledger dir. So that we don't need juggling validator restarts for the case of `--no-snapshot-fetch`. :)

**Comment by mvines** [comment]
I feel the new `solana-validator` subcommands in v1.6.x, `init`, `wait-for-restart-window` and `exit` address this issue pretty well, as well as the snapshot perf improvements in v1.6.x

I don't want to encourage a larger `--snapshot-interval-slots` by default because that will cause a slower recovery time during an unexpected event like a large power loss when we really need all affected nodes to restart as fast as possible, and having to process hundreds or thousands of slots because the node had a very lengthy snapshot interval could turn into a real issue for the network.

But when 1.6.x ships, please play with the new toys and lets go from there
