### ISSUE TITLE
library to verify ownership of a eth and other account keys

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#1425]
underwriter does the following
```
1. Here is proof of me owning the eth `address`
2. I guarantee that there is X eth in `address` destroy Y sol if I sign a transaction from `address`
3. I charge Z sol for settlement.
```

Sol can be in a staked account, and its up to the external clients to check if the eth address actually has X eth in it.  once thats validated the client has a guarantee that X eth wont be spent without destroying Y sol.

tag: @mvines @jackcmay @sakridge 

```
1. unlock the Y sol from the contract in T if there is an Eth tx from `address` to `new owner` for X eth
2. either party can present the transaction to solana in T and the underlying sol is free, contract is destroyed
```

The underwriter makes money when the sell the contract, and on settlement.  For settlement the payout could be a function of T because the `new owner` takes the risk of the transaction not being accepted by ethereum in T.

**Comment by mvines** [comment]
Note that you (the eth account holder) doesn't need to actually spend the eth.  An external client just needs to present a valid signed eth transaction to the sol program in order to get slashed.

**Comment by mvines** [comment]
@aeyakovenko - has this issue effectively been now rolled into the DEX demo work?
