### ISSUE TITLE
new feature: forking bank

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#1426]
To track trees of forks in the TPU and perform rollback, the Bank needs to be fork-able.  The bottom bank represents the last rollback point.

new functions needed?  new type needed?
BankFork::new(bank: Arc<Bank>, tick: Entry)
BankFork::process_entries() -> Result<()>
BankFork::collapse() -> (Bank, Vec<Entry>)

Internally Bank needs to understand how to chain account state.

Internally Bank needs a concept of zero balance.

**Comment by garious** [comment]
I think you can incrementally get there from the current Bank. It could be extended with a `last_bank: &Bank` and `id: Hash`.  The concept of a zero balance is currently deleting its entry in the HashMap. Instead, it could be `0` tokens until a `collapse()` on the bottom bank.

One approach to consider the use `Cow` to lazily clone each account. That might allow us to change less code. It'll be a bit annoying to refactor every bank function to walk this linked list of banks to find any values.

**Comment by aeyakovenko** [comment]
@rob-solana i think the validator bank should fork, not the leaders.  process_entries are synchronous, you have a small amount of state to fork.
