### ISSUE TITLE
erasure doesn't tolerate forks

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#1431]
data blobs have PoH information that allows us to figure out who the parent blob is, in the case of a fork (i.e. 2 different blobs at the same blob_idx/ledger height).

possible fixes:
* move FEC into the blobs themselves, so that PoH can (maybe?) be used to put the blobs in order before calling recover()
* use blob_id (i.e. leader that issued the blob) to group blobs by fork instead of PoH
* try erasure blobs with multiple PoH tracks

It's possible that erasure is generally incompatible with forks

**Comment by aeyakovenko** [comment]
@rob-solana, won’t all forks be virtual?

**Comment by rob-solana** [comment]
these cases are of concern, I think
1. leader schedule partition, where 2 leaders think they're next
2. slashable leader (i.e. 2 different data blobs for the current period)

**Comment by aeyakovenko** [comment]
@rob-solana how will two leaders be next?  L1 and l2 have different start points

**Comment by rob-solana** [comment]
in a partition that lasts long enough for a new leader schedule?

**Comment by rob-solana** [comment]
depends on #1433 being fixes

**Comment by rob-solana** [comment]
this rolls into #1717, is essentially a duplicate, so closing here
