### ISSUE TITLE
ledger doesn't carry blob_id/leader_id or leader signature

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#1432]
nodes being recovered from the ledger over repair (i.e. outside the RAM window) still need to see the blob_id of the original issuer/leader, and to verify the signature of the blob

to support bringing those nodes up, blob_id needs to be saved in the ledger for playback during repair from the ledger

**Comment by aeyakovenko** [comment]
Why do they care?

**Comment by rob-solana** [comment]
what is "split the enum"?

this issue is more focused on repair outside the window, i.e. from the ledger, wherein the id of the sender isn't known because it's not saved in the ledger.

perhaps this is a non-issue.  many of these issues were filed before the new fork strategy was devised

**Comment by rob-solana** [comment]
this should be covered by db_ledger
