### ISSUE TITLE
Wrong v1.4.10 tag

### ISSUE THREAD

**Issue by dimananet** [solana-labs/solana#14399]
#### Problem

Two tags (1.4.10 and 1.4.20) are on the one commit bbafd9783b86646a14b968f7c4ebd4ebd82fdce1

![image](https://user-images.githubusercontent.com/71597545/103473862-2415f880-4dae-11eb-9dca-fe86ab4c0877.png)

**Comment by mvines** [comment]
Fixed, thanks
```
$ git push origin :v1.4.10
To github.com:solana-labs/solana.git
 - [deleted]             v1.4.10
````
