### ISSUE TITLE
v1.5.1 validator can't keep up with mainnet

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#14410]
There's a regression on v1.5.1 that is preventing a validator running this release from keeping up with mainnet.  The general pattern is:
1. The validator catches up normally
2. Leave the validator running and after an hour or less it'll start falling behind.   Leave it overnight and it's even further behind
The same machine setup works fine with a v1.4.20 validator install.

**Comment by mvines** [comment]
Other initial triage info:
* This occurs with/without the `--bpf-jit` flag enabled. 
* A quick scan of `iotop` seems to imply there's more blockstore-related IOPS going on with v1.5 than v1.4 but this is just an eyeball measurement and might be off.  
* This is not a recent (days/hours) regression, I've observed this behavior for over a week now

**Comment by sakridge** [comment]
![de1-replay](https://user-images.githubusercontent.com/1024962/103572133-f483f080-4e80-11eb-9b53-8e2847ab7b84.png)
![beta-replay](https://user-images.githubusercontent.com/1024962/103572139-f6e64a80-4e80-11eb-881b-e0b0cd569e28.png)

Comparison of replay and store_accounts times with DE1 validator...

**Comment by sakridge** [comment]
Seems the 1.5 validator is using >128gb of ram and about 60gb into swap where 1.4 is only at about 60gb total.

**Comment by behzadnouri** [comment]
For reference, also adding what I posted in the chat.

`accounts_db_store_timings.append_accounts` is taking more time, but `find_storage` is taking less time (right chunk is what it used to be):
![append_accounts_find_storage](https://user-images.githubusercontent.com/1288998/103596397-c391d300-4ef5-11eb-8e84-7869c375a05f.png)

Rolling back https://github.com/solana-labs/solana/pull/12885 does seem to revert above change. Though the regression that causes validator to fall behind could be something independent of changes in these two metrics.
https://github.com/behzadnouri/solana/commit/72af4b721630a06ed20277465a237f6d4591c88f is the rollback commit.
