### ISSUE TITLE
Upgradeable program is executed using incorrect program_id

### ISSUE THREAD

**Issue by hendrikhofstadt** [solana-labs/solana#14412]
#### Problem

When an upgradeable program is invoked the keyed accounts seem to contain
[0]: Real "program" account
[1]: Account containing the bytecode

https://github.com/solana-labs/solana/blob/5424f54cf57031c7ef72a2ad50a2d07d61a09e1b/programs/bpf_loader/src/lib.rs#L247

This slices off the "real" program_id and leaves the programdata at index 0 of the array reference which will be consumed as "program_id" by the executor in 

https://github.com/solana-labs/solana/blob/5424f54cf57031c7ef72a2ad50a2d07d61a09e1b/programs/bpf_loader/src/lib.rs#L676

This prevents using derived accounts in upgradeable programs as they are arrived from the dynamic data account rather than the static program account.

CC: @jackcmay

**Comment by jackcmay** [comment]
@hendrikhofstadt Try this out: https://github.com/solana-labs/solana/pull/14417
