### ISSUE TITLE
RFC for validators signing their votes using an enclave

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#1447]
RFC documenting use case and sequence diagram for signing of votes on validator nodes, that are using an enclave to host their private key.

**Comment by pgarg66** [comment]
https://github.com/solana-labs/solana/issues/1429

**Comment by pgarg66** [comment]
1. Node boots up and loads the enclave
2. Untrusted code in the node performs remote attestation for the enclave
- Generate a quote from enclave
- Submit the quote to Intel's IAS
- Verify the report from IAS
3. Untrusted code asks enclave to generate a private/public keypair. The public key is exported to the untrusted code.
4. Balance is added to the public key
5. Untrusted code calls enclave's API to sign votes (and other data blocks, as needed)

**Comment by aeyakovenko** [comment]
> 3. Untrusted code asks enclave to generate a private/public keypair. The public key is exported to the untrusted code.
it can just generate without waiting for 2.
> 4. Balance is added to the public key
a transaction authorizing a stake to be voted with that key
> 5. Untrusted code calls enclave's API to sign votes (and other data blocks, as needed)
it can start signing without waiting for 4.

2 and 4 can be done asynchronously.   A step thats missing is that the enclave image needs to have some metadata that is the "genesis" or bootstap block which contains a PoH entry and a list of known validators.  The attestation that the image is booted with the right block also needs to be done.
