### ISSUE TITLE
Upgradeable programs log the incorrect program id

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#14484]
#### Problem
The programdata address is logged instead of the program id when running an upgradeable program. I expected `TokenLend1ng1111111111111111111111111111111` to be logged instead of `2YnNsPgwZEPRPumQhc8GbK9FxDzjErLrRx6RaV8taWCw`

![Screen Shot 2021-01-08 at 11 49 32 PM](https://user-images.githubusercontent.com/1076145/104034680-2b089500-520c-11eb-8d70-d89ee617b492.png)

```
Program 2YnNsPgwZEPRPumQhc8GbK9FxDzjErLrRx6RaV8taWCw invoke [1]
Instruction: Borrow
Error: InvalidAccountData
Program 2YnNsPgwZEPRPumQhc8GbK9FxDzjErLrRx6RaV8taWCw consumed 105620 of 2000000 compute units
Program 2YnNsPgwZEPRPumQhc8GbK9FxDzjErLrRx6RaV8taWCw failed: invalid account data for instruction
```

#### Proposed Solution
Fix logged program id

tag @jackcmay

**Comment by jackcmay** [comment]
@jstarry Are you seeing this on devnet or locally and if locally what branch are you on?

**Comment by jstarry** [comment]
Custom node running the tip of v1.4. Thanks for the quick fix!
