### ISSUE TITLE
Placeholder or minimum getEpochInfo rpc when starting?

### ISSUE THREAD

**Issue by ryoqun** [solana-labs/solana#14524]
#### Problem

When starting validator is stuck at long-running blockstore processor before starting full-fuleded rpc service, it's unclear what's happening to operator.

#### Proposed Solution

Launch, minimum rpc service which returns 5XX Try again later or minimum one for `solana catchup` or `solana-watchtower`.

**Comment by mvines** [comment]
I've wanted to do this for a while.  Moving `core/src/validator.rs` into `validator/src/` would make adding this feature much easier.  Otherwise we're looking at uncomfortable hacks/dependencies between the two crates

**Comment by mvines** [comment]
Some less invasive options:
* use files in the ledger/ directory to signal status
* use validator stdout to signal status (logging goes to stderr or a file already)
