### ISSUE TITLE
Difficult to debug CPI privilege escalation errors

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#14522]
#### Problem
The CPI privilege escalation error is overloaded which makes it more difficult to debug what's happening. If you get stuck thinking that the problematic account is not being signed correctly, you may not realize that the error is due to a read-only account being passed as writable.

```
    /// Cross-program invocation with unauthorized signer or writable account
    #[error("Cross-program invocation with unauthorized signer or writable account")]
    PrivilegeEscalation,
```

#### Proposed Solution
Split privilege escalation error into a "signer" escalation and a "writable" escalation

**Comment by jackcmay** [comment]
What you describe is what you should see now.  What cluster are you seeing the issue on?

you should be hitting these error cases:
https://github.com/solana-labs/solana/blob/ad0a88f1f2102bab8bc2cb61a3e0aa5e6a70ed8a/program-runtime/src/instruction_processor.rs#L446
https://github.com/solana-labs/solana/blob/ad0a88f1f2102bab8bc2cb61a3e0aa5e6a70ed8a/program-runtime/src/instruction_processor.rs#L459

Is that now what you want?

**Comment by SushantChandla** [comment]
oh, it is in the program logs (console). I thought the error message was changed.

**Comment by SushantChandla** [comment]
```js
 new TransactionInstruction({
                keys: [
                    { pubkey: new PublicKey(cardDetails.id), isSigner: true, isWritable: true },
                    { pubkey: wallet.publicKey, isSigner: true, isWritable: false }
                ],
                programId: programAccount,
                data: [2],
            });
```
How can i sign this instruction?
I am passing isSigner true for 2 different account because one of them is a program account which will invoke other program.

if i set the isSigner false, i get "{}'s signer privilege escalated",
