### ISSUE TITLE
Need mechanism to load an account with data

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#1454]
There is a limit to the amount of data that can be sent over a transaction.  For sending larger amounts of data we need a mechanism to break the data into smaller chunks over multiple transactions and a way to assemble them back together on the other side.

This mechanism will be used for loading program bits, calling program inputs, and possible other uses such as storage.

**Comment by aeyakovenko** [comment]
@jackmay, the contract for loading should take a (start,Vec<data>) as the userdata

**Comment by jackcmay** [comment]
Fixed by #1556
