### ISSUE TITLE
Measure benchmark differences for a given code change

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#1456]
We need a way to detect performance impact of code changes (submitted as PR). Solana codebase has benchmark tests for various performance critical portions of the code. We need a mechanism to automatically run these benchmark tests for a given PR, and compare them to the tip of master branch.

**Comment by pgarg66** [comment]
The benchmark results will get uploaded as build artifacts to CI pipeline.
<img width="494" alt="screen shot 2018-10-12 at 12 36 01 pm" src="https://user-images.githubusercontent.com/40076733/46890383-896f1f00-ce1b-11e8-89f1-cb1ea3ec6515.png">

The results will be compared with the results from tip of the branch. The artifacts will have details on each benchmark
<img width="1035" alt="screen shot 2018-10-12 at 12 36 15 pm" src="https://user-images.githubusercontent.com/40076733/46890427-ab68a180-ce1b-11e8-84f2-df57a602e142.png">

For a new branch, the previous results may not be available. In that case, only the current results will get uploaded.

**Comment by pgarg66** [comment]
@garious , just FYI

**Comment by garious** [comment]
Cool. No benchcmp though?

**Comment by pgarg66** [comment]
The data uploaded to influxDB is not in bench format. We can add code to reconstruct the bench like data from the database, but it might be ugly. If this change doesn't give enough information, I'll look into adding benchcmp.
