### ISSUE TITLE
BPF find_program_address syscall has variable compute cost

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#14580]
#### Problem
The addition of the `find_program_address` syscall is a big win for program development because it alleviates the need to track a bump seed in state or pass it in instruction data. Unfortunately, its cost varies quite a lot depending on the number of iterations needed to find an address off-curve. This makes it an unattractive syscall for programs which are trying to keep compute unit cost low and consistent.

#### Proposed Solution
Use a constant compute cost for `find_program_address` as long as the number of iterations is under `CAP`, where `CAP` is probably around 10. It would be nice if the cost was comparable to the cost of the `create_program_address` syscall so that devs don't have to weigh the design tradeoff between the two approaches. After `CAP`, charge compute units for each iteration to avoid DOS attacks.

cc @jackcmay

**Comment by jstarry** [comment]
This is probably easier solved by documentation recommending choosing accounts with a certain bump seed. Clients can grind out optimal accounts to keep compute costs minimal since they're paying for the transaction anyways

**Comment by aeyakovenko** [comment]
The implementation would need to bail at 10 as well. That means that 1:1024 fail

**Comment by jstarry** [comment]
> This makes it an unattractive syscall for programs which are trying to keep compute unit cost low and consistent.

While this is true, I think that `find_program_address` is still quite convenient for things like the `associated-token-account` program. Contracts that need to be composable and performant can find work arounds to avoid using this syscall. I propose we just document syscalls on their compute cost (fixed / variable) to help devs make their own tradeoff decisions.

**Comment by jackcmay** [comment]
`find_program_address` docs will be updated to make it clear that the compute cost is variable and the syscall will be enabled at the next testnet and mainnet epoch unless there are further objections.
