### ISSUE TITLE
Stake program: require lockup custodian’s signature to change the withdraw authority on a locked stake account

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#14587]
One primary intent of a stake lockup is to restrict the movement of stake between wallets until it unlocks.  To accomplish this, the stake program should additionally require the custodian’s signature when the withdraw authority is changed.

This can come in the form of a 3rd signed key to 
https://github.com/solana-labs/solana/blob/404be810bfa82fb62b78fbd595d4b8817f37d3c3/programs/stake/src/stake_instruction.rs#L71
for a locked stake account for `StakeAuthorize::Withdrawer`

`solana` cli should support this.   There may be a Ledger impact as well (cc: @t-nelson)

**Comment by t-nelson** [comment]
ACK.  Ledger app _will_ need a parser update to support this

**Comment by jstarry** [comment]
Another thing users could do is use a program derived address as the withdraw authority and then transfer authority of the controlling program to someone else to avoid needing the custodian signature. A follow up could require that the withdraw authority is not program derived.
