### ISSUE TITLE
Bank hash mismatch on epoch boundary between 1.4.23 and the tip of 1.5

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#14629]
The `bvb` forked off from mainnet-beta at slot 60912000 (first slot of epoch 141).
`bvb` was running 47b8d518 from the v1.5 branch. 

Logs/ledger are at `~/ledger.bank-mismatch-at-60912000` on `bvb`.

Compare the bank hash of 60912000 on `bvb`:
```
$ ag "bank frozen: 60912" ~/ledger.bank-mismatch-at-60912000/solana-validator.log | head -n2
2539651:[2021-01-16T13:38:31.391766871Z INFO  solana_core::replay_stage] bank frozen: 60912000
2539655:[2021-01-16T13:38:31.397633395Z INFO  solana_runtime::bank] bank frozen: 60912000 hash: DQFtgMiNoBHECFUxfKZnrkfGGM6rbAkjGUxjaopZFo1q accounts_delta: 4GnLVCVbyFBFZfHf7KPfqc4R8Kr4edxRahAFv6xVYmv7 signature_count: 1190 last_blockhash: GC9mauSeCHQT2trPNcBSMsm7oGhgfqt9e3Bx2ZWnLgSj capitalization: 488588432752692629
```
to the bank hash of 60912000 on `bv1`:
```
$ ag "bank frozen: 60912" ~/bank-mismatch-at-60912000/solana-validator.log | head -n2
2652785:[2021-01-16T13:38:31.561340695Z INFO  solana_core::replay_stage] bank frozen: 60912000
2652790:[2021-01-16T13:38:31.568487544Z INFO  solana_runtime::bank] bank frozen: 60912000 hash: ETA3qX8gMX3ntrj6JFZFb8iNBAdCid2auzjcC3yWabuF accounts_delta: 5EjzrL69BziAeLqHDscHo7UvGyEiraiyuoETdNkFCXuS signature_count: 1190 last_blockhash: GC9mauSeCHQT2trPNcBSMsm7oGhgfqt9e3Bx2ZWnLgSj capitalization: 488588432752692629
```

Unclear if this is just a one-time even due to the feature activations or reoccurring issue for all epochs.

**Comment by mvines** [comment]
`bvb` survived the transition from mainnet-beta epoch 141 to 142, so this issue looks to be related to the new feature activations that occurred from epoch 140 to 141:
```
xGbcW7EEC7zMRJ6LaJCob65EJxKryWjwM4rv8f57SRM  Loader not authorized via CPI            active since slot 60912004
5WLtuUJA5VVA1Cc28qULPfGs8anhoBev8uNqaaXeasnf Max cross-program invocation size 1280   active since slot 60912004
Bfqm7fGk5MBptqa2WHXWFLH7uJvq8hkJcAQPipy2bAMk warp timestamp to current, adjust bounding to 50% #14210 & #14531 active since slot 60912004
ED5D5a2hQaECHaMmKpnU48GdsfafdCjkb3pgAw5RKbb2 Abort on all CPI failures                active since slot 60912004
Ego6nTu7WsBcZBvVqJQKp6Yku2N3mrfG8oYCfaLZkAeK solana_stake_program v3                  active since slot 60912004
FLjgLeg1PJkZimQCVa5sVFtaq6VmSDPw3NvH8iQ3nyHn Use loaded program accounts              active since slot 60912004
FbhK8HN9qvNHvJcoFVHAEUCNkagHvu7DTWzdnLuVQ5u4 upgradeable bpf loader                   active since slot 60912004
```

It would be good to root cause to help avoid the same issue occurring in future feature activations but this no longer seems to be a critical issue

**Comment by t-nelson** [comment]
I'm planning to take a crack at diffing ledgers/accounts this morning

**Comment by t-nelson** [comment]
@jackcmay should the executable check here have been feature-gated?

**Comment by jackcmay** [comment]
The executable check moved from syscalls.rs to message_processor.rs and should be equivalent.  This was a large change that involved a feature gate, maybe that executable check was significant or maybe there is some other behavior that changed that I didn't realize

**Comment by t-nelson** [comment]
The same behavior was observed at epoch 149 on testnet from 1.5.3 to tip of 1.5 (also https://github.com/solana-labs/solana/commit/47b8d518c5194acbeaea71139bb7be7fd19afaa7). Which should narrow the feature list to the four activated there,
```
Feature FLjgLeg1PJkZimQCVa5sVFtaq6VmSDPw3NvH8iQ3nyHn activated at slot 58412256 ("Use loaded program accounts")
Feature FbhK8HN9qvNHvJcoFVHAEUCNkagHvu7DTWzdnLuVQ5u4 activated at slot 58412256 ("upgradeable bpf loader")
Feature Bfqm7fGk5MBptqa2WHXWFLH7uJvq8hkJcAQPipy2bAMk activated at slot 58412256 ("warp testnet timestamp to current #14210")
Feature ED5D5a2hQaECHaMmKpnU48GdsfafdCjkb3pgAw5RKbb2 activated at slot 58412256 ("Abort on all CPI failures")
```

**Comment by jackcmay** [comment]
@t-nelson Know of a good way to recreate this issue?

**Comment by mvines** [comment]
I have a plan to repro, stay tuned..

**Comment by mvines** [comment]
hmm, my attempts to repo failed.  I tried to ran `solana-ledger-tool verify ..` from 47b8d518 on the mainnet-beta ledger slice.  Worked fine.  

`~/ledger.bank-mismatch-at-60912000` on `bvb` also contains a snapshot of the failed ledger, I ran  `solana-ledger-tool verify` over it as well and the bank hash produced was again the correct one.

I think we might just need to let this one go...

**Comment by mvines** [comment]
Obsolete
