### ISSUE TITLE
CI unstable test: banking_stage::tests::test_banking_stage_entryfication

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#1463]
---- banking_stage::tests::test_banking_stage_entryfication stdout ----
thread 'banking_stage::tests::test_banking_stage_entryfication' panicked at 'assertion failed: `(left == right)`
  left: `2`,
 right: `1`', src/banking_stage.rs:393:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:221
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:475
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:390
   6: std::panicking::begin_panic_fmt
             at libstd/panicking.rs:345
   7: solana::banking_stage::tests::test_banking_stage_entryfication
             at src/banking_stage.rs:393
   8: solana::__test::TESTS::{{closure}}
             at src/banking_stage.rs:351
   9: core::ops::function::FnOnce::call_once
             at /checkout/src/libcore/ops/function.rs:223
  10: <F as alloc::boxed::FnBox<A>>::call_box
             at libtest/lib.rs:1451
             at /checkout/src/libcore/ops/function.rs:223
             at /checkout/src/liballoc/boxed.rs:642
  11: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:105
 

failures:
    banking_stage::tests::test_banking_stage_entryfication

**Comment by garious** [comment]
@aeyakovenko ^^^

**Comment by aeyakovenko** [comment]
@rob-solana ^ i am not sure i grok why this test is sensitive to ticks
