### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by LeeChunHao2000** [solana-labs/solana#14705]
#### Problem
![Error log](https://user-images.githubusercontent.com/64617939/105241498-ba1c9200-5ba8-11eb-9367-bee9040f3380.jpg)

**Comment by mvines** [comment]
Windows.   Try performing these steps to get git to properly create symlinks, checkout the repository again and retry: 
https://github.com/solana-labs/solana/blob/c64d4f76939415374f83a2001f4dc0e1067409d3/ci/publish-tarball.sh#L49-L57

**Comment by LeeChunHao2000** [comment]
![Errors](https://user-images.githubusercontent.com/64617939/105633172-14ac3b80-5e92-11eb-834b-e5372c5dad8e.jpg)
![errorss](https://user-images.githubusercontent.com/64617939/105633173-1675ff00-5e92-11eb-9409-99d01bfb3161.jpg)

https://github.com/Stebalien/gag-rs
The repo seems not support windows :(
