### ISSUE TITLE
Validators not filtering entries by the expected leader

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#1475]
to be able to synthesize a forked ledger in the case of a designated leader timeout, validators need to be running a PoH service, generating PoH ticks

a PoH service instance should always be running, as an object that's part of the most recent vote's state in order to kickstart the process of becoming a leader off that vote

**Comment by rob-solana** [comment]
a PoH service instance should always be running, as an object that's part of the most recent vote's state

**Comment by garious** [comment]
@rob-solana, can this one be closed?

**Comment by rob-solana** [comment]
yep
