### ISSUE TITLE
Poor error message for `solana fees` when a connection to the RPC URL can't be established 

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#14766]
This error is confusing, and it also occurs when a successful connection cannot be made to a valid URL
```
$ solana --url http://invalid.url fees
Error: parse error: expected RpcBlockhashFeeCalculator or RpcFees
```

Contrasts with this error, which is immediately obvious:
```
$ solana --url http://invalid.url epoch-info
Error: error sending request for url (http://invalid.url/): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
```

**Comment by mvines** [comment]
This appears to originate in `RpcClient::get_recent_blockhash_with_commitment()` where all error codes are eaten

**Comment by CriesofCarrots** [comment]
This seems fixed?
```
$ solana --url http://invalid.url fees
Error: RPC request error: cluster version query failed: error sending request for url (http://invalid.url/): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known
```
Not sure what PR, though...

**Comment by tunna-7** [comment]
Still facing the same error on running    
$ solana program deplay <path>

> Error: RPC request error: cluster version query failed: error sending request for url (http://localhost:8899/): error trying to connect: tcp connect error: Connection refused (os error 111)
