### ISSUE TITLE
solana program deploy prints different json schema

### ISSUE THREAD

**Issue by dafyddd** [solana-labs/solana#14830]
#### Problem
When you use cli command `solana program deploy` you will get a print out like `{"ProgramId":"EKf8..."}`if it's a new deployment and  `{"programId":"EKf8..."}` otherwise. This is annoying for those of us parsing it directly using jq in the command line. 

#### Proposed Solution
They should both have key 'programId'

**Comment by CriesofCarrots** [comment]
Fixed #14909
