### ISSUE TITLE
API nodes running the v1.5 branch are generating snapshots with MismatchedTotalLamports errors

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#14834]
On ba1, see the `~/ledger.bad-snapshot-for-62313975` directory:
* Search for `MismatchedTotalLamports` in solana-validator.log 
* STR: `solana-ledger-tool -l ~/ledger.bad-snapshot-for-62313975 verify`

On ba2, same as `ba1` but use the `~/ledger.bad-snapshot-for-62248998` directory

ba1/ba2 was running https://github.com/solana-labs/solana/commit/b48dd58fda74729bd50e5f4d16f7c1ff987b7a3b at the time

Interestingly bv4 and bvb are running the same code and may not be seeing mismatches

**Comment by sakridge** [comment]
Accounts caching enabled cc @carllin

**Comment by mvines** [comment]
I've upgraded `bw3` to the tip of v1.5.  The warehouse nodes have automatic snapshot sanity checks every hour, so I'm hoping we'll see an error appear from `bw3` if this is a non-API node problem.

**Comment by sakridge** [comment]
Snapshot at 62313975 created from starting at 62313875 and playing forward to ..975 which seems to verify:

`sakridge@lemond:~/solana/mainnet-beta-snapshot-issue-1-25-2021`

**Comment by sakridge** [comment]
small ledger from 62313875 to 62313975:
```
sol@ba1:~/ledger.bad-snapshot-for-62313975/rocksdb2.tar.zst
```

**Comment by sakridge** [comment]
cc @ryoqun

**Comment by ryoqun** [comment]
this is the truth:

```
[2021-01-25T11:01:10.744412746Z INFO  solana_runtime::bank] bank frozen: 62313975 hash: 4CLpzFHdGw63SnWWv6aEqqPuwK19Kq4FRPfymdteKBP9 accounts_delta: 4YvcemZvpzWxB3AzAhUxGPS46fvXcShTnqibPZvCEtcV signature_count: 553 last_blockhash: 5BszKHkYhyKRgt77DLYrwgEgH6u5fAnqKtd61PnHkBXb capitalization: 488587430684744678
```

this is difference:

```
[2021-01-25T12:26:23.286289635Z WARN  solana_runtime::accounts] verify_bank_hash failed: MismatchedTotalLamports(488587317027074222, 488587430684744678)
thread 'main' panicked at 'Snapshot bank for slot 62313975 failed to verify', /var/lib/buildkite-agent/builds/froome-1/solana-labs/solana-secondary/runtime/src/snapshot_utils.rs:625:9

```

**Comment by carllin** [comment]
It seems like the mismatch is caused by ~120 accounts mismatched in the bad snapshot, and about 150 or so missing accounts:

[output.txt](https://github.com/solana-labs/solana/files/5871478/output.txt)


I checked the first 10 or so mismatched account hashes from the bad snapshot and they were all from slot `62313974` instead of `62313975`. Now checking if the bank hash of the bad snapshot aligns with the hash of `62313974`, which would maybe suggest `62313975` was cleaned prematurely.

**Comment by carllin** [comment]
I think I my error, and maybe why it's only happening on API nodes.

If we are taking a snapshot of slot `S`, then in the event of an ongoing scan, https://github.com/solana-labs/solana/blob/master/runtime/src/accounts_db.rs#L3100 may set `max_flush_root == S` to a slot `R < S`, which means some slots `T` where `R < T < S` are not flushed to storage, and the snapshot won't have them.

**Comment by mvines** [comment]
Fixed
