### ISSUE TITLE
Explorer: Add stats about active stake and (de)activating stake

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#14853]
#### Problem
With increased interest in staking and associated user workflow and timing, it would be good for us to provide some network level numbers regarding total stake and state transitions on the explorer.

#### Proposed Solution

On the explorer homepage, add a new block (or a new tab at the top of the page a la "Cluster Stats" and "Supply"), which includes the following:

 - Active Stake: [N] SOL (tooltip: Amount of delegated stake across the network that is earning staking rewards in the current epoch)

 - Activating Stake: [M] SOL (tooltip: Amount of stake that has recently been delegated and is currently activating or "warming up".  This stake will become active and eligible for rewards in subsequent epochs)

 - Deactivating Stake: [P] SOL (tooltip: Amount of delegated stake that has recently been un-delegated and is currently deactivating or "cooling down".  This stake will become inactive and no longer eligible for rewards in subsequent epochs. Stake can be withdrawn from a stake account only after it has been undelegated and has finished deactivating.)

 - Maximum Stake Transition limit in the current epoch: [Q = 0.25*N] SOL (tooltip: Solana network protocol limits the amount of stake that can activate or deactivate in a single epoch to 25% of the current total active stake.  Any remaining activating or deactivating stake above this limit will roll over to continue transitioning in the following epoch.)

 - Current Stake Transitioning: [M+P or Q, whichever is smaller] SOL (tooltip: The amount of total activating and deactivating stake that will finish transitioning at the end of the current epoch)

 - Stake transition overflow: [Q - M+P, or 0] SOL (tooltip: The amount of total activating and deactivating stake that will require at least one more epoch to finish transitioning after the end of the current epoch)

**Comment by mvines** [comment]
For explorer, we're lacking nice RPC APIs for the global state of activating/deactivating state.  At present the explorer would need to pull all stake accounts to build this data.

**Comment by danpaul000** [comment]
@mvines what is a reasonable estimate for the amount of time before we could get an MVP of this on the explorer?  What with the community vote coming down the line real soon, we might get hammered with questions about this very shortly.

**Comment by mvines** [comment]
@oJshua has a pretty big backlog but chat with him to see what's doable with the current RPC APIs.  

For example, `solana stake-history` shows historical stake activation so that could be exposed, but we have no way to easily figure the stake delegations/deactivations that have occurred in the current epoch

**Comment by mvines** [comment]
But also if the new Solana Beach contains some of this information, which it seems to do, then I'm happy to avoid new explorer features for now

**Comment by danpaul000** [comment]
Yeah, I'm certainly not trying to make needless work here, but the new SB is a couple weeks out, and I'm trying to figure what we're going to needed if/when the masses decend on us.
