### ISSUE TITLE
programs using KeyedAccount should receive the full Transaction details

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#1495]
Currently programs only receive their particular instruction in the Transaction, which prevents it from observing the instructions that will execute atomically in its Transaction

cc: https://github.com/solana-labs/solana/pull/1482#issuecomment-429519625

**Comment by garious** [comment]
This title is a proposed solution, and the description describes a problem that may not be a problem. Ideally, instructions would be processed in isolation.  Another proposed solution might be a new mutex instruction, as described in the comment that the description references.

**Comment by jackcmay** [comment]
Sending the full transaction structure to programs is cumbersome especially
with #1482 where we want to add additional accounts for chained loaders.
We may have to rethink the transaction structure and/or send something
different to programs that still contain all the information they need.

**Comment by garious** [comment]
@mvines, can we close this one? rejected?

**Comment by mvines** [comment]
I think we want this still, perhaps not for v0.10 but I'll know that in a couple days once I'm further along with my current work

**Comment by garious** [comment]
But we don't want the program interface (`process()`) to depend on `Transaction`. Is there a reasonable subset of those fields the runtime could pass in instead?

**Comment by mvines** [comment]
Yeah it likely can be carved up.  Perhaps some flavour of:
```rust
struct KeyedInstruction {
    info: &Vec<KeyedAccount>,
    input: &[u8],
}
#[no_mangle]
pub extern "C" fn process(
    info: &mut Vec<KeyedAccount>,
    input: &[u8],
    before: &[KeyedInstruction], // <-- instructions before this one in the transaction
    after: &[KeyedInstruction],  // <--  instructions after this one in the transaction
) -> bool;
```

**Comment by mvines** [comment]
NB: the list of keys that signed the Transaction should also be surfaced

**Comment by garious** [comment]
Why?

**Comment by mvines** [comment]
Oh because a program instruction would like to know what keys signed it, as well as who signed the instructions that came before and after it in the single atomic Transaction.

**Comment by mvines** [comment]
#2005 may be an alternative to this issue

**Comment by sagar-solana** [comment]
+1, I would like this for storage program as well. Currently there's no way to make sure "fresh" proofs are coming in.
