### ISSUE TITLE
Occasional assertion failure in generate_index

### ISSUE THREAD

**Issue by carllin** [solana-labs/solana#14960]
#### Problem
Occasionally there seems to be issues where the same slot + account have the same write version. Validator on mainnet posted: https://discord.com/channels/428295358100013066/689412830075551748/805735779300409354

```
[2021-02-01T09:45:31.013167159Z INFO  solana_runtime::accounts_db] generating index: 352608/396634 slots...
thread 'main' panicked at 'assertion failed: entry.insert(stored_account.meta.write_version,
             (storage.append_vec_id(), stored_account)).is_none()', runtime/src/accounts_db.rs:4501:21
stack backtrace:
   0: std::panicking::begin_panic
   1: solana_runtime::accounts_db::AccountsDB::generate_index
   2: solana_runtime::serde_snapshot::bank_from_stream
   3: solana_runtime::snapshot_utils::bank_from_archive
   4: solana_ledger::bank_forks_utils::load
   5: solana_core::validator::Validator::new
   6: solana_validator::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2021-02-01T09:45:32.737207683Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at 'assertion failed: entry.insert(stored_account.meta.write_version,
                 (storage.append_vec_id(), stored_account)).is_none()', runtime/src/accounts_db.rs:4501:21" location="runtime/src/accounts_db.rs:4501:21"
```

Maybe some old corrupted storage entries?

#### Proposed Solution
Debug and fix

**Comment by ryoqun** [comment]
@carllin well, I saw this error when I was debugging #14834.


https://github.com/solana-labs/solana/pull/15022/files#r569329203:

> Snapshot at 62313975 created from starting at 62313875 and playing forward to ..975 which seems to verify:
> 
> `sakridge@lemond:~/solana/mainnet-beta-snapshot-issue-1-25-2021/snapshot-62313975-3QyJnvNL5Vu2nD1wggAtDiBayr8u1wivZqDkt9tVURZb.tar.zst`

I just snatched this one locally.

CC: @sakridge (do know you more context as to how this file created and did this work for you?)

```
[2021-02-03T12:21:48.409624022Z INFO  solana_runtime::accounts_db] generating index: 380153/387618 slots...
thread 'solana-accounts-db-2' panicked at 'assertion failed: entry.lock().unwrap().insert(stored_account.meta.write_version,
                             (storage.append_vec_id(),
                              stored_account)).is_none()', runtime/src/accounts_db.rs:2706:25

```

not bothered enough because I thought this another bug due to the unknown bug of #14834 at the time.

here's the snapshot


https://drive.google.com/file/d/1afBYu34psHQC3F6cDFJVQjYLlpT9hVeR/view?usp=sharing

```
$ sha256sum /tmp/snapshot-62313975-3QyJnvNL5Vu2nD1wggAtDiBayr8u1wivZqDkt9tVURZb.tar.zst
07295a658cb24a6d7f788e812a6c8e1a19b8dad9910f15a9734dbf99bba86b7b  /tmp/snapshot-62313975-3QyJnvNL5Vu2nD1wggAtDiBayr8u1wivZqDkt9tVURZb.tar.zst
```

**Comment by carllin** [comment]
@ryoqun awesome, thanks for the update, will take a look soon!

**Comment by carllin** [comment]
@ryoqun  my suspicion is because we re-use the write version in shrink here: https://github.com/solana-labs/solana/blob/master/runtime/src/accounts_db.rs#L1723, then if somehow one of the storages is not removed here: https://github.com/solana-labs/solana/blob/master/runtime/src/accounts_db.rs#L1769-L1776, we may see this duplicate slot and pubkey. I don't think it's dead garbage in the recycled storages, because those would be under a different slot.

**Comment by carllin** [comment]
added an assert here on one of the test validators: https://github.com/carllin/solana/commit/3d6c0878f956cc65404aed20b62293f27b5b0909, let's see what happens

**Comment by ryoqun** [comment]
@carllin thanks for thinking about this. :)

**Comment by ryoqun** [comment]
Seems like this is much more frequently happening on mainnet-beta because it has migrated to v1.5...

```
SELECT * FROM "mainnet-beta"."autogen"."panic" WHERE message !~ /[Rr]ocks[Dd]b|No such file|No space left|for bank 0 must |UnpackError|UnableToSetOpenFileDesc|permission denied|cudaHostRegister|other os error/ AND thread !~ /rpc/ AND time > now() - 60d
```

**Comment by brooksprumo** [comment]
Has this bug been seen recently?
