### ISSUE TITLE
CLI interface for deploying upgradeable programs with --final requires larger accounts then necessary 

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#15002]
#### Problem

Deploy defaults to a programdata/buffer account size of twice the size of the ELF but if the caller passes `--final` then they don't intend to upgrade ever.

#### Proposed Solution

If `--final` set max size to the size of the ELF

**Comment by jackcmay** [comment]
@fyi @CriesofCarrots

**Comment by CriesofCarrots** [comment]
Dupe of #14971
