### ISSUE TITLE
solana v0.9.0 not on crates.io

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#1503]
We did the work to ensure we weren't referencing any source repos in Cargo.toml. Why didn't the crate get published when we tagged v0.9.0?

**Comment by garious** [comment]
@mvines, can you ensure the crates.io publishing automation is ready for v0.10.0?  Perhaps my making an attempt to publish v0.9.0?

**Comment by mvines** [comment]
We might need to fix https://github.com/solana-labs/solana/issues/1542 first

**Comment by mvines** [comment]
cargo workspaces are something of a footgun.  Once we started using them for common/ and then in programs/ we ended up in a place where to publish to crates.io we now need to publish the common/ and programs/* creates to crates.io.

Publishing common/ to crates.io seems ok and we want to anyway (#1542), but publishing `programs/*` crates seems excessive.    To avoid this we need to remove all the top-level Cargo program dependencies, ok for all but `bpf_loader`.  bpf_loader needs to either be published, or folded back into `src/`

**Comment by garious** [comment]
Can you move programs to a separate repo?

**Comment by garious** [comment]
And bpf_loader back to src/

**Comment by garious** [comment]
Nm about moving the other programs. Sounds like that's not required

**Comment by mvines** [comment]
#1612

**Comment by mvines** [comment]
Next step is to wait until v0.10 branches off master tonight, try to publish a `0.10.0-pre.1` release and see what happens.  On success we'll see five crates on crates.io all with the same semver:
```
solana
solana-sdk
solana-noop
solana-bpfloader
solana-lualoader
```

**Comment by mvines** [comment]
New publishing infra works: https://crates.io/search?q=solana
