### ISSUE TITLE
Actually make lastValidSlot usable for tx expiration

### ISSUE THREAD

**Issue by ryoqun** [solana-labs/solana#15123]
#### Problem

As documented at #15081, it turned out lastValidSlot can be inaccurate under the existence of skipped slots.

The advised lastValidSlot usage for tx expiration check isn't correct, possibly leading to false-positives for tx's expired status.

However, there is more solid and more used way by `getFeeCalculatorForBlockhash`.

#### Proposed Solution

Ideally, we could provide lastValidBlockHeight or fix so that lastValidSlot can work even under the existence of skipped slots. 
Or, completely deprecate lastValitSlot?

**Comment by ryoqun** [comment]
cc: @t-nelson

**Comment by CriesofCarrots** [comment]
We fixed this! https://github.com/solana-labs/solana/blob/75658e2a96846c6afea95bc0e41dbabceef2c700/client/src/rpc_response.rs#L58
