### ISSUE TITLE
Inner instructions, program log no longer accessible through Explorer or RPC

### ISSUE THREAD

**Issue by RichardWarfield** [solana-labs/solana#15166]
It seems as if, within the last 24 hours or so, inner instructions and the program log have stopped showing up in Explorer, at least for certain Serum trading/swap transactions.  The corresponding fields in the response to `getConfirmedTransaction` are also null/empty.  For example, please compare:

[Recent token swap transaction](https://explorer.solana.com/tx/NRprnULxtu4FLZV5zGd4944DJjJ3qEUGVY9q2R8pa6s7iXPGcMWVfB7L3XjDwnmKRSXQ9v9Frn8ExorcfDFbPn7)
vs
[Token swap transaction a few days ago](https://explorer.solana.com/tx/2wK1KmP9nLEq6KSUgZTn3NruqGoNmAcxZNcL251jyyxJJjw2KhhBq4KsWpHVZGZG3K3mKCW7Yf8aQBfWcpAUWPbi)

[Recent Serum "settle funds" transaction](https://explorer.solana.com/tx/2fWbxVHfKySA1E3bnaRmBmrwboDEq7eVumfRA3Hecqkrp8q4KusggL22fsVW6nU7MVEBCFD7cex4YvSx8pDpUgCZ)
vs
[Serum "settle funds" transaction a while back](https://explorer.solana.com/tx/2VfJ2Gnrzo4Eygou6ZTcgyrEX4bBNqRW7vDWysRS5KGvNr9tezbjJXrQZVEX8fGLKU43Sru37EW992kAyiwHWjCQ)

**Comment by CriesofCarrots** [comment]
As noted in the SPL repo issue, we're missing some of that metadata on our api nodes at the moment, although we do have that data in our long-term storage. We're working on getting that backfilled as we speak.

**Comment by RichardWarfield** [comment]
Thanks; this doesn't seem like a data backfilling issue, however, as it's affecting just-executed transactions (and was not an issue a day ago).  Or perhaps I've misunderstood how this data gets populated to the API nodes?

**Comment by CriesofCarrots** [comment]
Update: bw1 warehouse node missing inner-instruction and log transaction metadata from blocks 63987673 - 64137582
Api node ranges may vary.

**Comment by CriesofCarrots** [comment]
This was resolved.
