### ISSUE TITLE
Can't revert authorized voter to my identity

### ISSUE THREAD

**Issue by meyerbro** [solana-labs/solana#15181]
#### Problem
Hello,

by a mistake I changed my authorized voter to a different one.

But later I discovered that I will pay double voting fees because of that.

I tried reverting it by simply running this command:
solana vote-authorize-voter ~/vote-account-keypair.json ~/new-vote-authority.json ~/validator-keypair.json

That gave me this error:
Error: RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: missing required signature for instruction [2 log messages]

#### Proposed Solution
I believe it should be possible to revert that change with this simple command right? I think it's a bug.

**Comment by CriesofCarrots** [comment]
I wasn't able to repro this issue. I'm guessing there were mistaken assumptions about the keypairs. But please open a new issue if this is still a problem and better repro steps are available.
