### ISSUE TITLE
Explorer: upgradeable-loader accounts should show details

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#15198]
#### Problem
The various accounts involved with a deployed upgradeable program are mysterious on the explorer.
Example (buffer account): https://explorer.solana.com/address/B8Qe8miJufJQcZMqSGoRGNGscrzcgrKjQFoU7fWjbP1q?cluster=devnet

#### Proposed Solution
Use https://github.com/solana-labs/solana/pull/15195 when landed to show data about these accounts

For program accounts, query the programdata_address to determine the last-deployed slot and program len. Example from the cli:

```
$ solana program show CYRJWqiSjLitBAcRxPvWpgX3s5TvmN2SuRY3eEYypFvT

Program Id: CYRJWqiSjLitBAcRxPvWpgX3s5TvmN2SuRY3eEYypFvT
ProgramData Address: Gkd3uoZF2LTkGz4FsQAyFA15BXhXeGn91uS7furzytJi
Authority: Bbqg1M4YVVfbhEzwA9SpC9FhsaG83YMTYoR4a8oTDLX
Last Deployed In Slot: 184
Data Length: 149600 (0x24860) bytes
```

**Comment by jstarry** [comment]
Just added support for program accounts here: https://github.com/solana-labs/solana/pull/15348

This issue can continue tracking support for buffer / program data

**Comment by jstarry** [comment]
Closed by https://github.com/solana-labs/solana/pull/15836
