### ISSUE TITLE
CI: test_no_optimistic_confirmation_violation_with_tower hangs sometimes

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#15226]
#### Problem
Sometimes `test_no_optimistic_confirmation_violation_with_tower` hangs in CI, causing the local-cluster tests to time out. Not sure if it's completely stalled in these cases, or just really slow.
eg: https://buildkite.com/solana-labs/solana/builds/39961#e758c07a-0ec6-4316-b935-77055ec6b72d

#### Proposed Solution
Debug and de-flake

**Comment by CriesofCarrots** [comment]
Seems like this is timing out a lot more frequently today, eg:
https://buildkite.com/solana-labs/solana/builds/41243
https://buildkite.com/solana-labs/solana/builds/41244
https://buildkite.com/solana-labs/solana/builds/41209
https://buildkite.com/solana-labs/solana/builds/41230

**Comment by CriesofCarrots** [comment]
When I run this test locally, it doesn't progress from this loop: https://github.com/solana-labs/solana/blob/a2c47db9209e0f0a4e4404019fbbbc152b04f377/local-cluster/tests/local_cluster.rs#L1812
last_slot values are always 2 or 3

**Comment by CriesofCarrots** [comment]
@ryoqun sorry for all the noise on this issue! The ubiquitous hang today should be fixed here: https://github.com/solana-labs/solana/pull/15647
However, I'm guessing the previous intermittent failures were also getting caught in this loop. Perhaps we should put in a timeout in the loop to catch if the validators don't start properly, or exit unexpectedly, so we can fail faster than the 45min CI job limit?

**Comment by ryoqun** [comment]
@CriesofCarrots sorry too for not responding well and not handling this timely. I've been overwhelmed with support efforts.

For the time being, the timeout sounds nice until we solve the root cause. :) I'll band-aid it.

**Comment by CriesofCarrots** [comment]
> @CriesofCarrots sorry too for not responding well and not handling this timely. I've been overwhelmed with support efforts.
> 
> For the time being, the timeout sounds nice until we solve the root cause. :) I'll band-aid it.

No worries! Looks like support was again heavy for you today 😅 
I'll put together a band-aid for your review

**Comment by CriesofCarrots** [comment]
Hanging was resolved. Flakiness is separate issue
