### ISSUE TITLE
solflare staking: broken for second staking account

### ISSUE THREAD

**Issue by zhiqiangxu** [solana-labs/solana#15255]
Maybe this is not the right project to fire an issue for solflare staking, but it appears solflare doesn't have a dedicated github project, so here goes:

Several days ago I created my first stake account and staked on a validator; Today I created a second stake account(deposited several sol at the same time), but `solflare` doesn't show it, and I can't select that account when trying to delegate it.

**Comment by t-nelson** [comment]
Hi!

Solflare is a third party wallet, so we unfortunately can't help you out directly.  They have support on Telegram at https://t.me/SolFlare_Wallet

In this case I _do_ know that they're aware of this issue and working to resolve it.

Thanks for reporting!

**Comment by zhiqiangxu** [comment]
I reported this bug there, and the feedback is that:

Someone said they checked after a few days and their staking account showed up eventually.

They suspect that there could be some bug with solana.

**Comment by t-nelson** [comment]
All of the other reports I've seen have stated that the new account is visible at https://explorer.solana.com and those willing to try our CLI tools were able to delegate the account with `solana delegate-stake ...`.

My last contact with the Solflare team suggested that their RPC nodes are lagging behind the cluster, so changes take longer than usual to show up in the UI

**Comment by zhiqiangxu** [comment]
Thanks for the feedback! I'll report this to the solflare group.

Do you know why their node lags so much?

**Comment by t-nelson** [comment]
> Thanks for the feedback! I'll report this to the solflare group.
> 
> Do you know why their node lags so much(**days**)?

Sorry I don't have any more details

> (btw, the `solana` tool is just built from `cargo build` on this project, right? )

Yes, that will build it.  You may want to use the  `cargo` wrapper script in the root of the source tree.  It will automatically install the correct version of Rust for you.  You can also install prebuild binaries with the instructions at https://docs.solana.com/cli/install-solana-cli-tools
