### ISSUE TITLE
Mining rewards aren't dispersed to active set

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#1527]
Problem:
No incentive to run a fullnode as a validator

Proposed solution:
Add a `MiningPool` program that validators can submit vote accounts to and be rewarded for their votes.

**Comment by garious** [comment]
Depends on #160

**Comment by aeyakovenko** [comment]
@garious @ericlwilliams this is the approximation we are experimenting with.  
1. Each Voter maintains an array of size N of the N most recent votes
2. A new vote X is added
   1. pop_front any votes with a lockout < X.height
   2. double the lockout of any remaining votes
   3. push_front the new vote
   4. if the array size > N, pop_back the oldest vote

The rewards of the voting program are organized as vested shares.  So when the program is created with N tokens, the vesting is for N * (1 + % reward).   For every `pop_back` vote, a fraction of the shares is "vested" and is unlockable.

**Comment by garious** [comment]
Just a quick update on the scope of this ticket. The `vote_program` maintains the last N votes, where N is currently 32. After N votes, each vote earns the validator a *credit*. Those credits can then be submitted to a new `rewards_program` for a payout. The current payout algorithm is extremely simplistic and attempts to give the staker a targeted APR on its stake.
