### ISSUE TITLE
panic cleanup

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#153]
We're too cavalier with calls to `expect()` and `unwrap()`. We're using them safely for the RwLocks, but most others should be acknowledged or added to the return values.

**Comment by jackson-sandland** [comment]
For the unsafe calls to expect, is a panic still acceptable on` err` as long as there are good error messages?

**Comment by garious** [comment]
I think replacing every call to `unwrap()` with `expect("something unique")` would be a first good step.

**Comment by jackson-sandland** [comment]
Sounds good. I'll start there, except for the calls to `unwrap()` in tests since it's alright for those to panic without error handling. Is that accurate?

**Comment by garious** [comment]
Thanks @jackson-sandland!
