### ISSUE TITLE
Publish solana_program_interface to crates.io

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#1542]
Do we want to change its name? solana-pdk?  Program Development Kit?  Maybe somehow bacronym it to pdx? :)

**Comment by mvines** [comment]
`solana-sdk` seems nice enough, `common/` moves to `sdk/common/` too?   This makes room for `sdk/examples/`, etc

**Comment by garious** [comment]
That sounds good to me, thanks!

**Comment by garious** [comment]
@jackcmay, if you agree, can you do the renaming?

**Comment by mvines** [comment]
This'll be fixed as a part of #1503
