### ISSUE TITLE
Adding basic coin functionality to RPC?

### ISSUE THREAD

**Issue by Crypto2** [solana-labs/solana#15452]
Are you planning on adding basic coin functionality to the RPC like generating addresses and sending coins? Currently it looks like you require an SDK to interface with the coin which limits you to just people using those 2 languages or shelling a program (which is def not something you'd want to do in a production environment.)

**Comment by mvines** [comment]
Not planning to add this, no.  RPC cannot be trusted to generate private keys or sign transactions

**Comment by Crypto2** [comment]
It is when you are running it on your own systems (like nearly all coins), even if you have to add an extra flag to the command line to enable them similar to geth.

**Comment by Crypto2** [comment]
@mvines Any updates on this? If it's good enough for nearly every coin I would think it would be good enough for Solana as well?

**Comment by mvines** [comment]
No updates, but please feel free to submit a PR if you feel strongly about building this feature.  Thanks!

**Comment by Crypto2** [comment]
I don't know your coin internals or I would, I know these features are being added to Velas which is descended from Solana so you may want to add them to control the interface versus them adding them and having to backport in whatever they do later.

**Comment by mvines** [comment]
Oh nice, is there anywhere I can find out more?

**Comment by Crypto2** [comment]
I know they are in some kind of partnership with Solana, it may not have trickled down from corporate to the devs yet though :(
