### ISSUE TITLE
Bank does not enforce immutable executable account userdata

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#1545]
Once finalized executable account userdata must be enforced as read-only.

**Comment by mvines** [comment]
@CriesofCarrots I feel this issue might be pretty close to what you need to do for CO accounts, would it makes sense to take it on at the same time (or shortly afterwards)?

**Comment by CriesofCarrots** [comment]
@mvines , yes, definitely part of the CO account work.

**Comment by jackcmay** [comment]
@CriesofCarrots Looks like we need to add a check to `verify_instruction` that ensures that executable account's data is not changed.  Agreed?

**Comment by CriesofCarrots** [comment]
> @CriesofCarrots Looks like we need to add a check to `verify_instruction` that ensures that executable account's data is not changed. Agreed?

Executable accounts should be marked as readonly in this step here: https://github.com/solana-labs/solana/blob/1c5d2a85cf3f451a7f30e3cce2b48f857717ab22/runtime/src/message_processor.rs#L242
And so should hit this case here: https://github.com/solana-labs/solana/blob/1c5d2a85cf3f451a7f30e3cce2b48f857717ab22/runtime/src/message_processor.rs#L139

But maybe I'm missing something?

**Comment by jackcmay** [comment]
@CriesofCarrots Agreed, I think we can close this issue
