### ISSUE TITLE
RPC getBlockCommitment Returns Null for Valid Blocks

### ISSUE THREAD

**Issue by brianlong** [solana-labs/solana#15460]
#### Problem
I expect to receive non-null commitment results from getBlockCommitment when I provide a valid block number 66343639.

`$ curl -s https://api.mainnet-beta.solana.com -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":1, "method":"getBlockCommitment","params":[66343639]}'` => `{"jsonrpc":"2.0","result":{"commitment":null,"totalStake":206350902448882539},"id":1}`

The Explorer shows good results for this block at https://explorer.solana.com/block/66343639

#### Proposed Solution
Please double-check the curl command. Did I miss something obvious?

Are we dealing with an overflow error on the slot number? (I saw a similar problem in solana-watchtower this week).

**Comment by mvines** [comment]
I believe [getBlockCommitment](https://docs.solana.com/developing/clients/jsonrpc-api#getblockcommitment) will currently return `null` for both an unknown block and a finalized block.  Does that sound right @CriesofCarrots?   

We probably should differentiate between these two cases, perhaps generate an error if a slot earlier than the highest finalized slot is provided as input to this method?

**Comment by CriesofCarrots** [comment]
Yes, that's just about right: the BlockCommitmentCache actually retains information for as many slots as the bank StatusCache (300), but blocks older than that will indeed return `null`.

This endpoint could definitely use some ❤️ . Consistent handling for finalized blocks makes a lot of sense, as well as an error for old slots. I'll take a look!

**Comment by brianlong** [comment]
Thanks for digging into this! I think I may be able to work with/around this. Not a high-priority. Cheers

**Comment by brianlong** [comment]
@mvines @CriesofCarrots For the `getBlockCommitment` RPC method, Is it feasible to also return the root & parent that the given block is building on? I am working on a daemon that will continuously loop through the most recent 300 slots to fetch slot updates until finalized. If I have the root, with the commitment levels, then I think I can start to show fork activity. (I'll be pinging my own RPC server of course).

FWIW, Different status codes, like 'finalized' will be very helpful too.

**Comment by CriesofCarrots** [comment]
@brianlong , we could certainly add the parent Slot of the queried Slot, as well as confirmation status (Processed, Confirmed, or Finalized). However, I don't think that we have that kind of transient Root data, ie. what was the Root at the time a particular slot was being processed.

**Comment by t-nelson** [comment]
You might keep any eye on this initiative.  The goals seem to at least partially overlap. https://github.com/solana-labs/solana/issues/15480, https://github.com/solana-labs/solana/pull/15488

**Comment by brianlong** [comment]
@CriesofCarrots The parent & confirmation status will be helpful.

@t-nelson Those pub/sub stories look great too.

I think you all know what I am trying to accomplish -- expose the leader schedule, block production, skipped slots, & commitment levels to let validators dig into their performance, find forks, etc.

I think we are all driving towards a goal of #ZeroForks

**Comment by CriesofCarrots** [comment]
Hi @brianlong ! I started working toward this today, but there are some complications with adding the parent slot and confirmation status to this rpc response (in short, a block's inclusion in the BlockCommitmentCache does not guarantee the node still has this data).
Have you had a chance to look at #15488? It seems like that might target your needs well.
Also or instead, I could plumb a `getBlockStatus` rpc that would return the confirmation status and parent slot of any block in BankForks or Blockstore, but wouldn't require any synchronicity with the BlockCommitmentCache. Wdyt?

**Comment by brianlong** [comment]
Hi @CriesofCarrots, The `getBlockStatus` RPC method sounds great!

The SlotUpdate pub/sub notifications will help to monitor current slot status, but `getBlockStatus` might be better when looking back in time.
