### ISSUE TITLE
Tip of master is incompatible with mainnet-beta

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#15469]
STR:
1. Run a validator with the tip of master against mainnet-beta

The log will be full of "failed to match hash" vote errors and the validator will not make new roots.   Regression range is probably a week or less.

**Comment by ryoqun** [comment]
@jackcmay it looks like https://github.com/solana-labs/solana/pull/15391 started to cause the vote mismatches. I tested running validators  before and after the commit.

**Comment by jackcmay** [comment]
Ok, I'll take a look, thanks @ryoqun !

**Comment by jackcmay** [comment]
Fixed by: https://github.com/solana-labs/solana/pull/15493
