### ISSUE TITLE
TicTacToe still using built-in programs.  Switch over to C based BPF

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#1548]
Most of the fundamental support for BPF based TicTacToe written in BPF are in place.  But there are some remaining action items that need to be completed.  This issue focuses on getting TicTacToe running end-to-end with BPF.  Not to be confused with #1255 which covers a final BPF solution.

The following is the list of remaining steps to connect the dots:

- [x] Add support for loading BPF program bytes from the account rather than loading via filename
- [x] Update TicTacToe client
- - [x]  Load the default BPF loader when the network is started
- - [x] Add BPF loader support to the SDK
- - [x] Need a client or service to load the TicTacToeDashboard and TicTacToe programs
- - [x] Switch example-TicTacToe over to using new dynamic program ids
 - - [x] No CBOR Serialization library in BPF at the moment so modify the client to interact directly with the game state in the account data

Once this is done the built-in TicTacToe and TicTacToe programs can be removed from the Bank.  They can be converted to and retained as dynamic native modules with the intent of building them into rust based BPF modules.

**Comment by jackcmay** [comment]
@mvines Please add anything I may have missed (especially related to the client side)

**Comment by mvines** [comment]
> No CBOR Serialization library in BPF ...

ouch, could we bring in tinyCBOR? https://github.com/intel/tinycbor

**Comment by jackcmay** [comment]
That's the CBOR library I was planning to try, not sure what kind of effect its going to have on the BPF.

**Comment by mvines** [comment]
Seems like we'd want to build on-chain shared objects for that kind of thing, which yeah may mean bpf linking of some fashion.  The VM proper shouldn't have an opinion on serialization formats or even libc IMO.

**Comment by jackcmay** [comment]
A run-time lookup of APIs via a VM trap that returns an interface is one way (IQI hehe).  Another way would be for the loader to be passed accounts with any dependent libs and to the resolutions

**Comment by mvines** [comment]
Fixed
