### ISSUE TITLE
Review code for ignored errors

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#155]
Rust will warn us if we ignore a `Result<T>`, but not a `Vec<Result<T>>`.

@sakridge spotted an instance of that in `process_verified_events()`. Are there others?

**Comment by jackson-sandland** [comment]
@garious how do you find these warnings?

**Comment by garious** [comment]
The compiler won't raise a warning unless the return value is `Result`. So `git grep 'Vec<Result'` is probably your best bet.

**Comment by garious** [comment]
We're in good shape here. Closing this ticket.

**Comment by garious** [comment]
FYI, as of 1.27.0, one can add `#[must_use]` to ensure a return value, such as `Vec<Result<T>>` is used.
