### ISSUE TITLE
testnet: verify_bank_hash failed: MismatchedTotalLamports

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#15504]
testnet.solana.com (`tv`) started generating invalid snapshots sometime recently.  Meanwhile `tw` is still generating valid snapshots.  Both are running
```
$ solana --version
solana-cli 1.5.8 (src:460c643f; feat:4077612551)
```

On both `tw` and `tv`, there's an `issue-15504/` directory with the a snapshot for the same slot generated on both machines.  The `tw` version is ok, `tv` version is not.   Logs are also in that directory.
To reproduce the error, run: `solana-ledger-tool -l issue-15504/ verify` on both machines.

This may be related to https://github.com/solana-labs/solana/issues/15180

**Comment by mvines** [comment]
```
[2021-02-24T02:30:13.038873100Z WARN  solana_runtime::accounts_db] Mismatched total lamports: 1324673051825686182 calculated: 1324673051827725462
[2021-02-24T02:30:13.038881045Z INFO  solana_metrics::metrics] datapoint: update_accounts_hash accounts_scan=372847i hash=5950i hash_total=654639i
[2021-02-24T02:30:13.038907625Z WARN  solana_runtime::accounts] verify_bank_hash failed: MismatchedTotalLamports(1324673051827725462, 1324673051825686182)
thread 'main' panicked at 'Snapshot bank for slot 65029588 failed to verify', /var/lib/buildkite-agent/builds/valverde-1/solana-labs/solana-secondary/runtime/src/snapshot_utils.rs:627:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[2021-02-24T02:30:13.039211259Z INFO  solana_metrics::metrics] datapoint: external_purge_slots_stats safety_checks_elapsed=2i remove_storages_elapsed=0i drop_storage_entries_elapsed=0i num_cached_slots_removed=0i num_stored_slots_removed=0i total_removed_storage_entries=0i total_removed_cached_bytes=0i total_removed_stored_bytes=0i recycle_stores_write_elapsed=0i
```

**Comment by sakridge** [comment]
calculated is 2,039,296 lamports higher.

**Comment by sakridge** [comment]
This is the difference:
```
TyGedS1k1ZKUrR42avUR36k9geFBzRo1QZndJ24o85K F9Fm5eFGgy8brwqai21nSdnJpjSkbVgJeSBaBCDHfkv1 2039280 64820103
```

**Comment by sakridge** [comment]
In the good snapshot:
```
key: 7u9aVBJZsZ9bkMG5eqT47n6yhUCuSy5azAuptwdsndpE ref_count: 1
    slots: [(64820103, AccountInfo { store_id: 769345036, offset: 0, stored_size: 224, lamports: 1461600 })]
key: FMQtW89zV25sucwHwh6e22kEzuhobHfZCY6bDAqZMyaT ref_count: 1
   slots: [(64820103, AccountInfo { store_id: 769345036, offset: 224, stored_size: 136, lamports: 121154440 })]

stores:
slot: 64820103 id: 769345036 count_and_status: (2, Available) approx_store_count: 2 len: 360 capacity: 4096 
```
`TyGedS1..` key does not seem to be present

**Comment by sakridge** [comment]
On the explorer: TyGedS1k1ZKUrR42avUR36k9geFBzRo1QZndJ24o85K has 0 balance and two transactions:

https://explorer.solana.com/tx/4gVupYvmSnb5XigggVfwVGZ3kTsCJu33CtbSMDNE87E3wrReZrRLdaJEdDAwZz2hDQ59yY3TKQdLQN14ThD6e3rH?cluster=testnet
Transferred the balance to 0 at slot 64,820,824

**Comment by sakridge** [comment]
From the bad one:
```
key: TyGedS1k1ZKUrR42avUR36k9geFBzRo1QZndJ24o85K ref_count: 1
    slots: [(64820103, AccountInfo { store_id: 778419973, offset: 136, stored_size: 304, lamports: 2039280 })]
key: FMQtW89zV25sucwHwh6e22kEzuhobHfZCY6bDAqZMyaT ref_count: 1
    slots: [(64820103, AccountInfo { store_id: 778419973, offset: 0, stored_size: 136, lamports: 121154440 })]
key: 7u9aVBJZsZ9bkMG5eqT47n6yhUCuSy5azAuptwdsndpE ref_count: 1
    slots: [(64820103, AccountInfo { store_id: 778419973, offset: 440, stored_size: 224, lamports: 1461600 })]

slot: 64820103 id: 778419973 count_and_status: (3, Available) approx_store_count: 3 len: 658 capacity: 4096
```

**Comment by sakridge** [comment]
This was the last new root before the slot was flushed:
```
[2021-02-22T18:20:11.234906489Z INFO  solana_core::replay_stage] new root 64820839
[2021-02-22T18:20:11.250659016Z INFO  solana_runtime::accounts_db] flush_slot_cache slot: 64820839
[2021-02-22T18:20:11.639581110Z INFO  solana_runtime::accounts_db] flush_slot_cache slot: 64820739
[2021-02-22T18:20:11.640541096Z INFO  solana_core::replay_stage] new fork:64820880 parent:64820879 root:64820839
```

@carllin maybe we can replay this scenario and flush the cache in the same place and see what the live account set is for slot?

**Comment by carllin** [comment]
@sakridge hmmm, so here:

> This is the difference:
> 
> key	hash	lamports	slot
> TyGedS1k1ZKUrR42avUR36k9geFBzRo1QZndJ24o85K	F9Fm5eFGgy8brwqai21nSdnJpjSkbVgJeSBaBCDHfkv1	2039280	64820103
> Only present in the bad snapshot.

Does this mean the accounts index generation somehow found an extra key that wasn't present in the other snapshot? I.e. the bad snapshot  was *missing* the update that this account went to 0 at a later slot, an update that is present in one of the good snapshot's later storage entries. Maybe that zero lamport update was cleaned up erroneously in the bad snapshot?

**Comment by sakridge** [comment]
> @sakridge hmmm, so here:
> 
> > This is the difference:
> > key	hash	lamports	slot
> > TyGedS1k1ZKUrR42avUR36k9geFBzRo1QZndJ24o85K	F9Fm5eFGgy8brwqai21nSdnJpjSkbVgJeSBaBCDHfkv1	2039280	64820103
> > Only present in the bad snapshot.
> 
> Does this mean the accounts index generation somehow found an extra key that wasn't present in the other snapshot? I.e. the bad snapshot was _missing_ the update that this account went to 0 at a later slot, an update that is present in one of the good snapshot's later storage entries. Maybe that zero lamport update was cleaned up erroneously in the bad snapshot?

Yes, the bad snapshot was missing the 0-lamport update at slot 64820824 to mask the older update.

**Comment by JB273** [comment]
I'm also having this problem on TdS, if needed I can test or provide moer info! Let me know...

**Comment by mvines** [comment]
Occurred again on `tv` today

**Comment by mvines** [comment]
and `ta`

**Comment by mvines** [comment]
and `tw`.  Ok it's affecting all our testnet nodes at once right now.  This is pretty scary

**Comment by mvines** [comment]
Might be fixed by https://github.com/solana-labs/solana/pull/15534

**Comment by mvines** [comment]
@carllin - you're basically working on this so I'll assign the issue to you

**Comment by mvines** [comment]
Stale issue
