### ISSUE TITLE
tip of master cannot catchup to mainnet-beta?

### ISSUE THREAD

**Issue by ryoqun** [solana-labs/solana#15530]
#### Problem

https://discord.com/channels/428295358100013066/439194979856809985/813946475263426601

> 10:32 AM mvines | I'll never DM you:
> Tip of master no longer generates bank hash mismatches against mainnet-beta (thanks @jackcmay) but it doesn't keep up.  bvb has been running the tip of master for over an hour now, it's 1600 slots behind and slowly going backwards.   Looks like we have a performance regression on master
> 10:37 AM jackcmay:
> point of info, my validator at 02432a548 was catching up (my gce instance) 

#### Proposed Solution

Fix and debug?

Maybe @carllin is looking into?

**Comment by carllin** [comment]
@ryoqun, @mvines, it seems to be commit 02432a548fa940bd589c88a621952ef66d53145b that's causing my validator running tmpfs to OOM, due to the accounts size blowing up. Maybe we can try reverting that change and see if things improve?

**Comment by mvines** [comment]
`bvb` has been running the tip of master since yesterday (I did just recently restart it though).  I've seen no OOMs

**Comment by mvines** [comment]
But `bvb` still can't catch up.  It's -2k slots right now, and slowly drifting away

**Comment by mvines** [comment]
If you use 02432a54 exactly then it won't work though, there's a fix that Jack made later on master as a follow-up.

**Comment by carllin** [comment]
heh dang yeah, I moved to the tip of master and the Accounts size issue seems to have magically resolved itself. No real clue here then 🐢
