### ISSUE TITLE
Get pre/post account data sizes for transactions

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#15599]
#### Problem

The explorer shows the current account's data size which if the account is drained will be zero.  But that account may have been involved with instructions in the past where it had a non-zero account data size.  Using the transaction history to track the progression of an account is difficult when a transaction contains instructions that made decisions depending on a program's account size.

#### Proposed Solution

Show an account pre/post account data size

**Comment by ngundotra** [comment]
This is dependent on an RPC level change, which I'm not going to do. Closing
