### ISSUE TITLE
explorer: Reviewing a program deployment in explorer is painful due to the number of write instructions

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#15600]
#### Problem

Trying to inspect a deploy instruction in the explorer requires the user to "Load More" through all the write instructions which could be in the thousands in order to get to the instructions prior to the writes.

#### Proposed Solution

Be nice to roll up the write instructions and load them only if the user requests them

**Comment by ngundotra** [comment]
@jackcmay I think this is a great idea!
@CriesofCarrots is it possible to get an RPC method that returns the last deploy/upgrade/finalize transaction for a program? Otherwise we will have to query some other storage.

**Comment by ngundotra** [comment]
Closing this issue based on feedback from Discord: https://discord.com/channels/428295358100013066/488758828330909706/1052819892178526318
