### ISSUE TITLE
Installing from channel `stable` installs outdated version

### ISSUE THREAD

**Issue by Huge** [solana-labs/solana#15619]
#### Problem
As per https://docs.solana.com/cli/install-solana-cli-tools it is stated we can "use one of the three symbolic channel names: `stable`, beta, or edge." I just did that and got
```solana --version
solana-cli 1.4.29 (src:4b0f6fd6; feat:3146620764)
```

#### Proposed Solution
Either remove that from documentation or link to https://github.com/solana-labs/solana/releases instead or have that symbolic channel updated properly.

**Comment by mvines** [comment]
Hi Huge, this is actually working as designed.  The current stable channel is in fact v1.4, but it'll change to v1.5 shortly once we create the v1.6 stabilization branch.

I'm going to close this issue as everything seems fine.  But feel free to comment more if you'd like and we can reopen, thanks!
