### ISSUE TITLE
nit: Network selection dialog stays open after selecting new network

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#15631]
#### Problem

This is probably a matter of opinion so take it or leave it but on the explorer, after selecting a new network the network selection dialog remains open and the user must close it manually.  Doing so seems cumbersome.

#### Proposed Solution

Be nice if the dialog disappeared after the new network was choosen.

**Comment by jackcmay** [comment]
@oJshua fyi

**Comment by CriesofCarrots** [comment]
Explorer is no longer in this repo
