### ISSUE TITLE
No economic incentive for validator consensus

### ISSUE THREAD

**Issue by ericlwilliams** [solana-labs/solana#1567]
In PoW systems, miner's capital expenditure off-chain aligns their incentives with that of a healthy blockchain in order to recoup those costs in the form of block rewards.  PoS systems intend to provide similar incentives but through in-network capital leveraged as value-at-risk.  A high level outline of our current thinking of how PoS in Solana may look can be found in [rfcs/rfc-009-staking.md](rfcs/rfc-009-staking.md)

**Comment by garious** [comment]
Per @ericlwilliams via Discord, protocol rewards should go to validators and fees should go to the leader.

**Comment by ericlwilliams** [comment]
Thanks @garious, 
To recap: protocol rewards to be distributed to validators based on stake-weight and # of votes in a given epoch (their relative activity).  Each transaction fee should have a fixed minimum amount that is allocated to return to the mining pool, and the leader that includes the transaction keeps anything above that amount. 
See Section 2.2 and 2.3 [here](https://docs.google.com/document/d/1sntxE-o_WTgM-jrf8kkzKFEtbwx8sH84q4Bs28Ni5Zo/edit?usp=sharing) for latest thinking

**Comment by garious** [comment]
Closing this ticket, as the new "credits" field in `vote_program` that was added in #2665 solves most of the problem described by this ticket. You can't yet "cash out", but that work is covered in https://github.com/solana-labs/solana/issues/1527.
