### ISSUE TITLE
getEpochInfo transaction count regressions

### ISSUE THREAD

**Issue by leoluk** [solana-labs/solana#15681]
Our mainnnet monitoring regularly encounters transaction count regressions on commitment level `max`:

![image](https://user-images.githubusercontent.com/859697/109847631-b53f0980-7c4f-11eb-91e9-afef8cea7c27.png)

Query:

    solana-validator[834551]: [2021-03-03T17:35:43.164089613Z TRACE jsonrpc_core::io] Request: {"jsonrpc":"2.0","id":1,"method":"getEpochInfo","params":[{"commitment":"max"}]}

(via https://sourcegraph.com/github.com/certusone/solana_exporter@7a6ccbcabc452ec5cdc2a258d2a302848003add6/-/blob/cmd/solana_exporter/slots.go#L76:28)

**Comment by CriesofCarrots** [comment]
Seems like this was probably resolved in runtime work, but please open a new issue if this appears again.
