### ISSUE TITLE
Executable accounts are immutable, don't need to copy account data during load

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#15683]
#### Problem

Once an account is marked executable the data becomes immutable and there is no longer a need to copy its data out of the accounts database each time it is referenced.  Instead, a shared read-only pointer could be used to refer to the account's data.  The whole account could be shared via an `Rc<RefCell<Account>>` except for the possibility of folks transferring lamports to the account.  There is no good reason for folks to do this but if any do, that new balance should be retained.  Also, the benefit of this is somewhat minimized since with upgradeable program's the executable account is quite small and the bulk of the data is stored in the ProgramData account.  One solution could be looking at the authority field and if `None` the program is no longer upgradeable and the ProgramData account could also be shared as immutable.

**Comment by jackcmay** [comment]
fyi @jeffwashington @Lichtso

**Comment by jeffwashington** [comment]
related: #15639

**Comment by jeffwashington** [comment]
also #15633

**Comment by jackcmay** [comment]
@jeffwashington Both #15639 and #15633 are closed, do you see any further action required for this issue?

**Comment by jeffwashington** [comment]
No. I think this does what you wanted.
