### ISSUE TITLE
C-based BPF programs have inherent restrictions, need review

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#1569]
The current implementation of the C-based BPF programs were written as a prototype.  We are planning to open up the ability for others to write their own C-based BPF programs.  Our examples and general model should be reviewed internally first.

https://github.com/solana-labs/solana/tree/master/programs/bpf

**Comment by jackcmay** [comment]
@mvines, @garious

**Comment by mvines** [comment]
sgtm, we can do this work after 0.10 branches but keeping the issue in 0.10 since seems like something for early next week.

**Comment by mvines** [comment]
We'll be reviewing this a part of upcoming demos, but I'm not really sure what else is actionable here so closing.  Please re-open if there's something specific that we should be doing
