### ISSUE TITLE
Built-in programs have overlapping ids and temporary programs are in same id namespace

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#1572]
BudgetProgram and StorageProgram have overlapping program_id's and the rest are sequential from 0.

Instead, any built-in program that is not intended to stay in the bank could be moved to a larger number to give room for the addition of newer built-ins that are intended to stay.

I would propose:
SystemProgram: 0
NativeLoader: 1
BpfLoader: 2

BudgetState: 256
StorageProgram: 257
TokenProgram: 258
TicTacToeProgram: 259
TicTacToeDashboardProgram: 260

(BudgetState, StorageProgram, and TokenProgram could live in the lower id space as 3, 4, 5 respectively).

**Comment by mvines** [comment]
Seems like a nice cleanup to do at a low pri.  There's a minor SDK impact so in some ways just doing it like now would be nice
