### ISSUE TITLE
dropped vote .. failed to match hash  - after moving to the new location

### ISSUE THREAD

**Issue by carambon** [solana-labs/solana#15750]
#### Problem
After moving to the new server validator after catchup is producing such errors and becoming deliquent:

[2021-03-06T10:55:10.869049950Z WARN  solana_vote_program::vote_state] EvnRmnMrd69kFdbLMxWkTn1icZ7DCceRhvmb2SJXqDo4 dropped vote Vote { slots: [67865212], hash: BadNmcMcvNMtdcYL6983nUf8NhFGwADALPKWDMAphY7i, timestamp: Some(1615028110) } failed to match hash BadNmcMcvNMtdcYL6983nUf8NhFGwADALPKWDMAphY7i 4gvGXmrsnW8m1K4SUkxVfcGhrK3HHkCgMhJsdeNTJbw9

OS: Ubuntu 20.04 (Also tried 18.04)
solana-validator 1.5.11 (src:96e587c8; feat:169108138)
validator id: JDScHrbfa4DEmqA4j5JTVc3wtwqXXeDCrjntRo2pWoLP
Hardware: Ryzen 7 3700X, 128 GB RAM 2x1TB NVME raid 0

Validator command line:

ExecStart=/home/carambon/.local/share/solana/install/active_release/bin/solana-validator \
    --expected-shred-version 13490 \
    --expected-genesis-hash 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d \
    --entrypoint mainnet-beta.solana.com:8001 \
    --trusted-validator 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2 \
    --trusted-validator GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ \
    --trusted-validator DE1bawNcRJB9rVm3buyMVfr8mBEoyyu73NBovf2oXJsJ \
    --trusted-validator CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S \
    --dynamic-port-range 8001-8020 \
    --identity /home/carambon/validator-keypair.json \
    --vote-account /home/carambon/vote-account-keypair.json \
    --ledger /home/carambon/validator-ledger \
    --limit-ledger-size \
    --rpc-bind-address 127.0.0.1 \
    --rpc-port 8899 \
    --log /home/carambon/solana.log \
    --no-untrusted-rpc \
    --private-rpc

I have tried any variant to migrate - copy only keys and tower, copy snapshot from the old server or download it from RPC, even copied full ledger, but every time soon after catchup validator failing to match hash.
Returned to the old server - everything is OK.

I have suspicions about hardware, but memtest and stress tests didn't find anything bad, and this problem is reproducible, not a random.

**Comment by mvines** [comment]
@carambon - can you please attach the log you shared in Discord here?

@carambon's machine:
```
bank frozen: 67865227 hash: zy1bA33E776CF6R4zuMKognwHHXcpA9q5bS1UUdWt81 accounts_delta: BqXYEBnGxHV74kN6WYB9QyAYGQMdrSgFQspBhz1gw2PZ signature_count: 636 last_blockhash: 2saoVQYYUZeYnBmuFdUaNWqNVKwLuAszZ7wUwPLDo3e8 capitalization: 490287933769133507
accounts hash slot: 67865227 stats: BankHashStats { num_updated_accounts: 1336, num_removed_accounts: 2, num_lamports_stored: 13188938223569924, total_data_len: 100153244, num_executable_accounts: 40 }
```

Another machine:
```
bank frozen: 67865227 hash: 5jKxNfzPsP3t3i2tgg8nQQu5yzx83aMj2xbvSd1zYWqk accounts_delta: 2Jikhn5btskJf2zqc7CvWRjTF3YDQvahr9XHmyQXTLEw signature_count: 636 last_blockhash: 2saoVQYYUZeYnBmuFdUaNWqNVKwLuAszZ7wUwPLDo3e8 capitalization: 490287933769133507
accounts hash slot: 67865227 stats: BankHashStats { num_updated_accounts: 1813, num_removed_accounts: 2, num_lamports_stored: 13252843842571695, total_data_len: 101932931, num_executable_accounts: 40 }
```

**Comment by mvines** [comment]
Most likely a stale issue
