### ISSUE TITLE
RPC: SPL Token balance changes from inner instructions are not included in {pre,post}TokenBalances

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#15760]
#### Problem

Via Discord.

https://explorer.solana.com/tx/KebgN4uj6oP7pHe2K78VAgsM12qtVrWn4GmX27Wd1L5TiexoN32TWzWiSfmKUWvGc7GZKMF2Pea4fEuDUShFf8E?cluster=testnet

```
$ curl https://testnet.solana.com -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getConfirmedTransaction",
    "params": [
      "KebgN4uj6oP7pHe2K78VAgsM12qtVrWn4GmX27Wd1L5TiexoN32TWzWiSfmKUWvGc7GZKMF2Pea4fEuDUShFf8E",
      "jsonParsed"
    ]
  }
'
```
```
SNIP

      "postBalances": [
        103441384064,
        10000000000,
        2039280,
        9995921439,
        24798480,
        2039280,
        1130582400,
        1128355200
      ],
      "postTokenBalances": [],
      "preBalances": [
        103441394064,
        10000000000,
        2039280,
        9995921439,
        24798480,
        2039280,
        1130582400,
        1128355200
      ],
      "preTokenBalances": [],
      "status": {
        "Ok": null
      }

SNIP

```

#### Proposed Solution

Debug and fix.  Maybe something to do with the calling instruction being unrecognized?

**Comment by t-nelson** [comment]
Similarly, swap instructions seem to only report the first inner transfer's balance change.

https://explorer.solana.com/tx/AExqVNefswx8NGv98v1XNMctScSdviNjRxRmQ5Y7sdoPsmLxbMkZKwcwb6cmduZpKCXBhJqXGgycbCnuhTAZj6g

**Comment by CriesofCarrots** [comment]
@oJshua , can you please take a look at this?

I think it's just an issue with this logic: https://github.com/solana-labs/solana/blob/79280b304bbeeb3c8ce5308188678ab45f30f914/transaction-status/src/token_balances.rs#L63-L65
Currently, the code only checks token balances if `Tokenkeg` is the program-id of an instruction, but needs to check (all accounts) any time `Tokenkeg` is present in the accounts list

**Comment by oJshua** [comment]
@CriesofCarrots thanks, I'll have a closer look.
