### ISSUE TITLE
cli: Add a flag for outputting raw transaction messages to be signed offline

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#15786]
#### Problem
The CLI does not allow creating a raw message that can be sent to a remote signer service for validation and signing. This makes it difficult to integrate into a generic signer service which simply validates and signs messages. The current CLI commands require a signer service to construct a transaction itself which adds extra complexity to a remote signer.

#### Proposed Solution
- Add `--dump-message` (naming?) flag to CLI commands which construct transactions. The cli should output the constructed tx message as base64 (configurable?) as well as the used recent blockhash.

After the message is signed, the signature(s) and recent blockhash should be supplied to the same CLI command according to the existing offline signing flow.

**Comment by jstarry** [comment]
cc @t-nelson @CriesofCarrots 

PS. No need to add a `sign-raw` command yet.

**Comment by t-nelson** [comment]
We can probably just add this as part of the `--sign-only` output

**Comment by YuWT-CN** [comment]
> We can probably just add this as part of the `--sign-only` output

it's great.
can you add raw before sign  and raw after sign together?

**Comment by antoineherzog** [comment]
Really good feature, very useful!

**Comment by jstarry** [comment]
@t-nelson were you planning on taking this one still?

**Comment by t-nelson** [comment]
> @t-nelson were you planning on taking this one still?

Yep!  I got held up a bit.  Should get to it tomorrow though

**Comment by jstarry** [comment]
Great, thanks!
