### ISSUE TITLE
[Program-Test] banks_client.process_transaction times out instead of returning wrong programid error

### ISSUE THREAD

**Issue by paul-schaaf** [solana-labs/solana#15795]
#### Problem
When running a program test using the solana-program-test crate, calling `banks_client.process_transactions(tx)` will time out after 60 seconds if no program is found at the programid inside `tx`.

#### Proposed Solution
Instead of timing out, return an error indicating that there is no program at given address / given account is not executable, just like a real transaction with a wrong program id would.

cc: @joncinque

**Comment by CriesofCarrots** [comment]
Fixed by  #22084, using the `BanksClient::process_transaction_with_preflight` method
