### ISSUE TITLE
solana-install: `update` subcommand only supports channels

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#15797]
#### Problem

`solana-install update` only works if the local install is initialized to a channel (`solana-install init {beta,stable,edge}`).  If instead the local install is initialized to a specific release (`solana-install init vX.Y.Z`), `solana-install update` quietly does nothing.

#### Proposed Solution

Resolve and install the latest patch version of the local install's minor version when initialized to a specific release

**Comment by mvines** [comment]
There's a pile of JSON that `update` could fetch from https://api.github.com/repos/solana-labs/solana/releases to easily locate new releases
