### ISSUE TITLE
Explorer: needs to show more info on token flows and balances

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#15847]
#### Problem

It’s hard to figure out token balances and flows for a system account or programs.   This should cover staking reward as well, but need a separate page/design

#### Proposed Solution

Build a page that displays the current balances and flows in/out of that system account or program, program address, program instance, etc...

Given something like swap, display the total flows in/out of swap, and per instance and current value locked.

**Comment by aeyakovenko** [comment]
More asks: https://twitter.com/austerity_sucks/status/1371132695561043976?s=21

**Comment by aeyakovenko** [comment]
https://twitter.com/austerity_sucks/status/1371134280043261955?s=21

**Comment by aeyakovenko** [comment]
https://twitter.com/austerity_sucks/status/1371135455555649539?s=21

**Comment by ngundotra** [comment]
Do we still want this? https://solana.fm already has this covered
