### ISSUE TITLE
RaidGuild Request: indexed.wtf doc edits and additions

### ISSUE THREAD

**Issue by kittyslasher** [solana-labs/solana#15912]
Hello blessed devs,
@A2nkF @aeyakovenko @danpaul000 @ericlwilliams @garious @jstarry @leoluk @mvines @nathanielparke @rajgokal @Reisen @rmshea @ryoqun @sakridge 

We here at Raid Guild have brought you indexed.wtf and are taking care to make sure the docs we display for each Layer 2 and side-chain project are accurate and filled with information the dev teams would like to highlight specifically. Having easily accessible information about all these solutions will bring more attention to your project.

Please find the markdown for the docs for your project below.

Kindly review, edit and provide any missing details and information at your taste and discretion as project leaders.

Moving forward we aim to keep indexed.wtf as current and beneficial to developers researching the ecosystem as possible. Please feel free at any time to submit an issue or PR to update the displayed information.

Thank you for your attention to this matter.

Best,
The Indexed Army
We stand for accurate data.

www.RaidGuild.org
@chair28980 @kittyslasher

```markdown

# indexed.wtf Template

<!-- Please update the feilds below. Please feel free to update/eliminate/include headers below.-->

### Name
Solana

### Description
Solana is a fast, secure, and censorship resistant blockchain providing the open infrastructure required for global adoption.

### Consensus Type
Proof of Stake

### Tx Cost
*30 gwei*

### Average TPS
*1000*

### Finality Time
*Your Finality Time*

### Governance/validator Token
*yes/no*

### Transactional Token
*ETH*

## Resources
[Website](https://www.solana.com)
[Github](https://github.com/solana-labs/)
[Developer Docs](https://docs.solana.com)


## Social Media & Community
[Twitter]()
[Telegram]()
[Discord](https://discord.gg/m6K4Afvd)
[Medium](https://medium.com/solana-labs)
[Youtube]()
[Career Opportunities]()

```

**Comment by mvines** [comment]
> We here at Raid Guild have brought you indexed.wtf and are taking care to make sure the docs we display for each Layer 2 and side-chain project are accurate 

Hey, Solana isn't a Layer 2 or a side-chain.

**Comment by leoluk** [comment]
You're probably not aware of this, but tagging people individually causes GitHub to send notifications to everyone, regardless of their notification choices. Projects have triage processes in place which ensures that your issues get attention and there's no need to tag every contributor (and it could be seen as impolite - you'll get better responses if you don't do it).

This is exclusively an engineering bug tracker. Please re-submit your request at https://forums.solana.com - you'll get better feedback there!

**Comment by kittyslasher** [comment]
> You're probably not aware of this, but tagging people individually causes GitHub to send notifications to everyone, regardless of their notification choices. Projects have triage processes in place which ensures that your issues get attention and there's no need to tag every contributor (and it could be seen as impolite - you'll get better responses if you don't do it).
> 
> This is exclusively an engineering bug tracker. Please re-submit your request at https://forums.solana.com - you'll get better feedback there!

So I took the advice and went to the forum as directed and got no response. We are actively attempting to bring attention to your project by including you in an index. We are doing all the heavy lifting of getting the site up and running we just simply are trying to get some updated docs. So if github and the forum doesn't seem to be the place for answers where would you suggest next. We are looking to launch in 2 days
