### ISSUE TITLE
SPL Lending program's compute budget requirements increased in master

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#15944]
#### Problem

Worked around with the following PR, but need to identify the source of the increase

https://github.com/solana-labs/solana-program-library/pull/1467

Possible causes:
- Rust toolchain changes from v1.39 to v1.50
- Updated LLVM
- Switch to using LLVM's builtins
- CPI data costs

**Comment by mvines** [comment]
Also back out https://github.com/solana-labs/solana-program-library/commit/eb163ab0c71dd870c0aaee0db46a7505fac5d090 once we figure this out too

**Comment by mvines** [comment]
Let's keep this issue open until 1.6.2 ships, SPL updates to it, and we back-out https://github.com/solana-labs/solana-program-library/commit/eb163ab0c71dd870c0aaee0db46a7505fac5d090

**Comment by jackcmay** [comment]
v1.6.2 shipped
