### ISSUE TITLE
more informative text is needed at explorer's account page with no balance

### ISSUE THREAD

**Issue by ryoqun** [solana-labs/solana#15989]
#### Problem

https://explorer.solana.com/address/HjY7eQrBTe4i6MdbTSCMm5yKvHm4HcMGb5KM4rMuGBdA

![image](https://user-images.githubusercontent.com/117807/111656408-d7d74200-884d-11eb-8b38-4dd71ded30b6.png)

it's a bit hard to tell the address is just unfunded _system_ account. this could mean completely unused address or removed address. 

#### Proposed Solution

- Show owner as system program
- show a notice like this (bonus: be conditional with past transaction):  `This address is in valid address format but it hasn't been used at all or deleted, resulting in/defaulting to a system account with no balance`

**Comment by t-nelson** [comment]
> Show owner as system program
I'm not sure displaying an owner for accounts that aren't in the active set makes sense. Especially in the case of a deleted account that may have been in use by other programs in the past and have transaction history as such.

:100: on the notice though!  I might go so far as to remove the SOL balance as it can only serve to confuse
