### ISSUE TITLE
The max transaction size of 512 is a little limiting

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#1598]
I ran into a simple case where I was unable to fit 3 reasonably sized Instructions in a Transaction and remain under the 512 byte limit.   A couple options to consider here:
1. There's a ton of wasted space in the Transaction wire format right now (64bit numbers were 8 bits will do, etc)
2. Should we bump the max PACKET_SIZE to something a little bigger, like 1k?

Fixing (1) would have kept me under 512 in the case I ran into FWIW.

**Comment by mvines** [comment]
#1531 will make this worse too once a transaction can have multiple signatures

**Comment by sakridge** [comment]
I update the cuda library to take the packet size as input argument, so rust side should be able to be modified without changing the cuda lib once #1602 merges.

**Comment by mvines** [comment]
I just ran into this again, gonna need to fix this sooner than later

**Comment by mvines** [comment]
👢 back to The Future for now.   When this comes up again let's ensure that #1801 is fixed before considering an increase

**Comment by mvines** [comment]
Fixed, we're > 1000 bytes now
