### ISSUE TITLE
Json-RPC getStakeActivation Response 

### ISSUE THREAD

**Issue by yihau** [solana-labs/solana#16021]
#### Problem

I create two whole new stake account A and B in epoch N.

If I do such below
```
curl https://testnet.solana.com -X POST -H "Content-Type: application/json" -d '
  {"jsonrpc":"2.0","id":1, "method":"getStakeActivation", "params": ["A or B address"]}
'
```

I will get rpc error

```
{"jsonrpc":"2.0","error":{"code":-32602,"message":"Invalid param: stake account has not been delegated"},"id":1}
```

I use A to delegate stake and query it. I will get

```
{"jsonrpc":"2.0","result":{"active":0,"inactive":997717120,"state":"inactive"},"id":1}
```

then I query again like below

```
curl https://testnet.solana.com -X POST -H "Content-Type: application/json" -d '
  {"jsonrpc":"2.0","id":1, "method":"getStakeActivation", "params": ["A address", {"epoch": N - 1 }]}
'
```

get

```
{"jsonrpc":"2.0","result":{"active":0,"inactive":997717120,"state":"inactive"},"id":1}
```

why it doesn't response ` stake account has not been delegated` error or  `{"active":0,"inactive":0,"state":"inactive"}` when I query A on epoch N - 1 ?

#### Proposed Solution

I think it would be either

reponse error in epoch N - 1 for A

or

response

```
{"active":0,"inactive":0,"state":"inactive"}
```

for a stake account is valid, just not delegate stake yet.

**Comment by CriesofCarrots** [comment]
Thanks @yihau , I agree this is a bit inconsistent. I think the latter solution is the way to go.
