### ISSUE TITLE
explorer: stake account information is confusing for deactivated and withdrawn stake

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#16044]
STR:
1. Have an active stake account
2. Deactivate it
3. Withdraw all but the rent reserve

The Stake Account balance shows as 0.00228288
But under Stake Delegation:
a. Status: Delegated (inactive) -- "delegated but inactive"? 🤔 
b. Delegated Stake (SOL): 49.99771712 🤔 

Example: https://explorer.solana.com/address/Hfsw8KWRB9A1Fpzxj4WSbyhad4eqqtXQJigpQq4Conku

![image](https://user-images.githubusercontent.com/1281082/111883374-1b2dcf80-8978-11eb-915b-f6470578c4a9.png)

**Comment by t-nelson** [comment]
:wave: https://github.com/solana-labs/solana/issues/13740
