### ISSUE TITLE
explorer: Cluster stats page uses too much polling

### ISSUE THREAD

**Issue by oJshua** [solana-labs/solana#16230]
#### Problem
If you watch the network tab on the Explorer main page, you'll notice around 10-15 requests every 10 seconds. Every so often some of these requests will hit a 503 error / timeout, and the cluster stats will show an error message. 

#### Proposed Solution
A couple options:
- look into batching these requests (would require some web3 work)
- revisit using websockets (would require rpc changes / bolstering websocket implementation)

**Comment by ngundotra** [comment]
Closing bc stale
