### ISSUE TITLE
Explorer: better UX for failure messages for popular contracts

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#16305]
#### Problem

https://twitter.com/icebergy_/status/1377634763331227651?s=21

Under load, market TX fail without a descriptive reason causing frustration to users. 

#### Proposed Solution

inspect the error, show something useful like “outbid by X”

**Comment by ngundotra** [comment]
Can this issue be closed? Otherwise, can move to `solana-labs/explorer`
