### ISSUE TITLE
Add support for multi-sig accounts to stake program

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#16404]
#### Problem
High value stake accounts should be able to be secured via a withdraw authority that is a multi-sig account

#### Proposed Solution
Add support for multi-sig to stake program for account authorities.

**Comment by mvines** [comment]
I think we do this by adding a generic SPL multisig program and then setting it as the withdraw or stake authority.  This'll require Ledger support for the multisig program as well

**Comment by garious** [comment]
@mvines, has anyone done that? I'd love to see that code.

**Comment by t-nelson** [comment]
> @mvines, has anyone done that? I'd love to see that code.

https://github.com/project-serum/multisig

It uses the Anchor framework though.  Would be nice to get an audit on both
