### ISSUE TITLE
Restarting bench-tps causes testnet failure

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#1640]
#### Problem
Testnet runs bench-tps (clients) for a certain duration (e.g. 600 seconds). The bench-tps exits after this duration, and gets restarted.

After some restarts, the client seems to be sending more packets (transactions) to testnet when compared to previous runs (e.g. 250k packets/second, instead of 200k packets/second). This increase in traffic is causing more load on each stage of pipeline on leader and validators.

Currently, the validator's replicate stage is taking longer with each run. This causes validators to start lagging in their votes. The finality increases and testnet fails eventually.
  
#### Proposed Solution
For time being, the client run time duration has been increased to 2+ hours. This is not a solution, but a workaround to keep testnet up for longer. Need to debug more and fix the real issue.

**Comment by pgarg66** [comment]
https://github.com/solana-labs/solana/pull/1639

**Comment by rob-solana** [comment]
can this be re-created with a local testnet?

**Comment by pgarg66** [comment]
The testnet is able to keep up with bench-tps restarting. Closing the issue for now. If the problem resurfaces, we can create a new issue with relevant details.
