### ISSUE TITLE
Request: keep output of CLI tools consistent

### ISSUE THREAD

**Issue by dafyddd** [solana-labs/solana#16406]
#### Problem
I have been using this script to deploy my program:
```
PROGRAM_ID="$(solana program deploy target/deploy/program.so | jq .programId -r)"
```

But now it doesn't work because the output changed from being json to this: 
```
Program Id: CALWc6qfgADgs3rAqYkoV75K3eJQhqxqUxi6UxZRmdkd
```

This breaks some of my automation and I've noticed similar issues with other CLI commands that also changed output. It's hard to automate common commands if output can change for no reason.

#### Proposed Solution
Change the output only if it's necessary

**Comment by CriesofCarrots** [comment]
Sorry for the trouble! We follow this [backward compatibility policy](https://docs.solana.com/developing/backwards-compatibility). The change to `solana program deploy` was made to make the cli more consistent across commands, and happened on the minor version bump to v1.6: https://github.com/solana-labs/solana/releases/tag/v1.6.0

We are definitely open to suggestions to make our change/versioning process and communication better!

For your specific issue, `solana program deploy target/deploy/program.so --output jsonCompact` should produce the json output you had before

**Comment by dafyddd** [comment]
Ah ok, I'll be sure to check the release notes when taking out a new version.
