### ISSUE TITLE
delegate-stake results in wallet returning 32002

### ISSUE THREAD

**Issue by nremond** [solana-labs/solana#16405]
#### Problem

Playing around with the CLI, I wanted to see if I could figure out the staking (without RTFM, sorry)
`solana delegate-stake 6KrRiQqxxG7JeFF8rVP5oiRddCWnWpi4qmVbgDyaeWXH GvZEwtCHZ7YtCkQCaLRVEXsyVvQkRDhJhQgB6akPme1e`

Whatever command I now run results in 32002. I cannot revert this:

```
~ »  solana deactivate-stake 2saKRyvY5WuMMVt94Qy9Ep6eYRpTJkcL5JFcWyEBoXB4                                                                                                              ~ 1 ↵
Error: RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: incorrect program id for instruction [2 log messages]
```

#### Proposed Solution

It sound safe to assume that the `deactivate-stake` shouldn't return such error.

**Comment by CriesofCarrots** [comment]
Hmm, I haven't been able to repro yet. Can you give your full steps to reproduce?

What `solana -V`?
Are you targeting solana-test-validator?
What kind of account is `2saKRyvY5WuMMVt94Qy9Ep6eYRpTJkcL5JFcWyEBoXB4`?
Does `solana deactivate-stake 6KrRiQqxxG7JeFF8rVP5oiRddCWnWpi4qmVbgDyaeWXH` work?

**Comment by t-nelson** [comment]
`6KrRiQqxxG7JeFF8rVP5oiRddCWnWpi4qmVbgDyaeWXH` and `2saKRyvY5WuMMVt94Qy9Ep6eYRpTJkcL5JFcWyEBoXB4` are both system accounts. Only stake accounts can be delegated (and thus deactivated).  See `solana create-stake-account --help`

This error message will be more specific soon. The error is really an "invalid account owner".  While the account owner is _technically_ a program id, in the failure case here the error is that the account specified isn't owned by the expected program (system vs. stake)

**Comment by CriesofCarrots** [comment]
Oh, I see it now! My mistake, I was using `master` branch code, thought I was on stable. 🤦‍♀️ 
Can confirm that more sane messages are coming soon :)

**Comment by t-nelson** [comment]
> Oh, I see it now! My mistake, I was using `master` branch code, thought I was on stable. woman_facepalming
> Can confirm that saner messages are in the pipeline :)

This has bitten me so many times :pensive:

**Comment by nremond** [comment]
Got it, thank you very much for the help.
