### ISSUE TITLE
Support use of BigInt in web3.js somehow

### ISSUE THREAD

**Issue by ryoqun** [solana-labs/solana#16423]
#### Problem

Our RPC response contains numerous fields that can exceed Number.MAX_SAFE_INTEGER in JS land (`postBalances`, `postTokenBalances` and parsed instruction numerical arguments). In that case, least significant bits are rot away and precise accounting will be impossible.

However, the implication of this is rather small. That's because almost all of these fields don't exceed the limit under normal situation.

#### Proposed Solution

The difficult situation is that JS does natively solves the problem with bigint, which isn't universal yet (blame IE, pre-blink Edge)....
This limited availability isn't problem for controlled environment like node.js.

Also, this would break runtime compatibility and typescript definitions. ;)

So, maybe add configurable flag to Connection if keen partners really want fire-proof behaviors by switching drop-in bigint-aware JSON parser?

**Comment by ryoqun** [comment]
some refs:

https://caniuse.com/bigint

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

**Comment by jstarry** [comment]
Thanks for creating a tracking issue for this!

I think we'll want to do a major version release to switch over the token values especially, I think those are the most likely to experience rounding errors. Probably lamports too.

We have a precedent here for reading big integers from raw account data: https://github.com/solana-labs/solana-program-library/blob/34583bf7484d76b5de91ada994b030dd16748b11/token/js/client/token.js#L49
And a precedent here with using string values from rpc: https://github.com/solana-labs/solana/blob/master/explorer/src/components/account/OwnedTokensCard.tsx#L154
