### ISSUE TITLE
crash at build

### ISSUE THREAD

**Issue by keyboardriot** [solana-labs/solana#16473]
#### Problem
I get this error at cargo build step. The server is running Ubuntu and has 64GB of RAM

  = note: collect2: fatal error: ld terminated with signal 9 [Killed]
          compilation terminated.

**Comment by steviez** [comment]
@keyboardriot - Did you figure this out? 64 GB of RAM is plenty, but there could be other things at play, like low swap/disk space:
https://stackoverflow.com/questions/46259776/collect2-fatal-error-ld-terminated-with-signal-9-killer

**Comment by steviez** [comment]
Didn't hear back - assuming you figured it out. If you still encounter issues, please use our Discord for any further assistance
