### ISSUE TITLE
Integrate RBPF CLI in Solana SDK

### ISSUE THREAD

**Issue by dmakarov** [solana-labs/solana#16505]
#### Problem

RBPF CLI is not very accessible to developers

#### Proposed Solution

Move the CLI source code into solana repository and make it part of the SDK.

**Comment by dmakarov** [comment]
cc: @jackcmay @Lichtso @mvines: following up #16454

**Comment by mvines** [comment]
Instead of moving the code, we could alternatively just install the latest published version fo the RBPF CLI into the full Solana cli release, like we do for `spl-token` tool: https://github.com/solana-labs/solana/blob/70f3f7e679baa6a66738acb57d5d813e00c7195a/scripts/cargo-install-all.sh#L129

**Comment by jackcmay** [comment]
To align the cli tool with what is happening in the solana runtime we might
need to finally bring rbpf into the monorepo.  We might also want to
augment program-test so that it can produce the same outputs as the cli
tool or somehow run program-tests within the cli tool.

**Comment by Lichtso** [comment]
> Instead of moving the code, we could alternatively just install the latest published version fo the RBPF CLI into the full Solana cli release, like we do for `spl-token` tool.

The problem is not only that it is hard to find in the first place, but also that it is not integrated. It is stand alone and the user has to manually extract program and data and then feed them separately into the CLI tool.


> To align the cli tool with what is happening in the solana runtime we might need to finally bring rbpf into the monorepo. We might also want to augment program-test so that it can produce the same outputs as the cli tool or somehow run program-tests within the cli tool.

I hope the RBPF repo can stay separate for now. I would move the CLI bin code into the lib part of the crate and then call it from within the monorepo.

**Comment by Lichtso** [comment]
I [moved the most of the CLI bin code into the lib](https://github.com/solana-labs/rbpf/pull/159), as planned. So with the next release of RBPF we can implement the CLI in the mono repo as well.

**Comment by dmakarov** [comment]
I'd like to get this issue resolved.  I'm not sure -- have we reached an agreement about moving the CLI tool into solana repository?  If yes, where should I move it?  Does `sdk/rbpf-cli/` sound ok?

**Comment by Lichtso** [comment]
How about placing it at the root of the repo, the `solana-cli` and `ledger-tool` are similar and also at the root.

**Comment by dmakarov** [comment]
> How about placing it at the root of the repo, the `solana-cli` and `ledger-tool` are similar and also at the root.

Sounds good to me. If no objections, I'll make `rbp-cli` subdirectory at the root of the repository.

**Comment by jackcmay** [comment]
Sounds fine to me too for now.  I would still like to see rbpf moved into the mono-repo, the only reason it exists outside is because it was originally a fork

**Comment by dmakarov** [comment]
> I would still like to see rbpf moved into the mono-repo, the only reason it exists outside is because it was originally a fork

I think I understand your reasoning -- moving solana_rbpf into the mono-repo would guarantee the synchronization of the rbpf with the bpf_loader.  However, if we ever need to bring upstream changes into solana_rbpf, it would be much simpler to do when solana_rbpf and the upstream repository share the common git history.

**Comment by dmakarov** [comment]
The rbpf-cli is now in Solana monorepo. Can I close this issue? New follow-up issues can be created for more specific problems.

**Comment by Lichtso** [comment]
#20881 exposed more of the parameters for the input accounts (in **bold**).

Now there is:
  - **`key: Pubkey,`**
  - `owner: Pubkey,`
  - **`is_signer: bool,`**
  - **`is_writable: bool,`**
  - `lamports: u64,`
  - `data: Vec<u8>,`
