### ISSUE TITLE
Limit number of RPC subscriptions by host

### ISSUE THREAD

**Issue by nathanielparke** [solana-labs/solana#16529]
#### Problem
There is no knob that an rpc node operator can tune to set a limit on the number of rpc subscriptions for a given host. This leads to a situation where a single host could hold many subscriptions and starve other clients if the total number of subscriptions to a node exceeds the `MAX_ACTIVE_SUBSCRIPTIONS` (currently at 100k). 

#### Proposed Solution
Include the host in the `RpcSolPubSub` Metadata and add a CLI flag to set a limit on the number of rpc subscriptions per host. If a host adds a subscription and their total subscriptions exceeds the limit, reject the subscription.

**Comment by thaaddeus** [comment]
@nathanielparke it could that it was me or other users running https://github.com/tardis-dev/serum-vial which under the hood uses WS connection per market and connects to serum RPC nodes by default.
It also subscribes to serum `eventQueue` account changes which are rather large and can cause bandwidth issues.

Sorry about that, I've managed to set up local RPC node for my serum-vial instances and also put large ['NOTE'](https://github.com/tardis-dev/serum-vial#installation) in the readme that it's the most reliable solution.

BTW, perhaps in the future serum-dex could switch to serum-vial server for market data, I bet it would help a lot with RPC servers load.

**Comment by mvines** [comment]
This would be super nice, needs plumbing upstream in the json-rpc crates though and may not even work through a load balancer depending on how the original client IP is routed to the backend
