### ISSUE TITLE
Add support for authenticated requests

### ISSUE THREAD

**Issue by linuskendall** [solana-labs/solana#16538]
For the RPC clusters we are looking for a way to allow applications to make authenticated requests to the RPC endpoint. The best way would be to use JWT bearer tokens, i.e. that the API could optionally send a header `Authorization: Bearer <token>` with every request. 

For long-running applications there may also be a need to be able to cycle the token/set a new token when the old one has expired.

**Comment by mvines** [comment]
The Rust RpcClient should also support this, in addition to the `solana` command-line (something like `solana config set http-auth <token>` perhaps)

**Comment by t-nelson** [comment]
@linuskendall is this going to need to support some sort of MAC as well?

**Comment by linuskendall** [comment]
We'd process any authentication on the loadbalancer before it hits the RPC, using signed JWTs so no we'd not need anything like a MAC.

**Comment by mvines** [comment]
We have some JWT management logic in https://github.com/solana-labs/solana/blob/master/storage-bigtable/src/access_token.rs that currently is specific to GCP's `GOOGLE_APPLICATION_CREDENTIALS ` we might be able to repurpose.

**Comment by linuskendall** [comment]
For our purposes we don't want the backend RPC to handle any of the JWT logic, we'd need to process it before it reaches the backend RPC. I am not sure in general if it would make sense for anyone to run authenticated RPC without a layer in front, like HAproxy?

**Comment by mvines** [comment]
The code I linked to was client-side

**Comment by t-nelson** [comment]
Yeah that's what I was getting at as well.  Wondering if we really need a more generic interface here or whether the proposed auth token is sufficient

**Comment by linuskendall** [comment]
> 
> 
> The code I linked to was client-side

I am no expert here on the app side of things, but from our side I would imagine that even on the client side they wouldn't need much logic/understanding of the JWT. Presumably the app operator would have to run a backend (could even be an AWS Lambda e.g.) that requested a time limited token using their secret credentials. Our backend would issue the JWT to the app operators backend, this gets passed along to frontend and their client software uses the token throughout.

It would be possible to wrap a whole OAuth flow into the cli/web3 etc. but that's probably overkill and I think the apps can likely provide the token issuances logic by themselves?

**Comment by t-nelson** [comment]
It probably makes sense for web3/client to expose a generic third-party header interface.  Service providers can then offer a convenience wrapper that adds their special bits to alleviate our repos of those implementation details

**Comment by oJshua** [comment]
@t-nelson @mvines do we want to cover websocket authentication under this issue? If not, I'll create a follow-up.

**Comment by t-nelson** [comment]
> @t-nelson @mvines do we want to cover websocket authentication under this issue? If not, I'll create a follow-up.

Dealers choice!

**Comment by mvines** [comment]
It'd be nice to confirm that adding websocket auth would work alongside what'd going in via #16599, if we don't end up needing to rework the interface
