### ISSUE TITLE
VoteState tracks only votes, not lockout or rewards

### ISSUE THREAD

**Issue by carllin** [solana-labs/solana#1655]
#### Problem

Create a staking contract to manage account the active set of validators and the stakes/rules for these validators. Currently, stake is just the number of tokens in a validator's accounts.

#### Proposed Solution

The following algorithm for staking is considered:

The program maintains a data structure `votes` with 32 entries that supports both queue and stack operations and front to back iteration.

* New vote V is inserted.
1. pop any old votes that have an old 
```
   while votes.front().height()  + votes.front().lockout() < V.height()
      votes.pop_front()
```
2. double the lockouts of any remaining votes
```
   for v in votes
      v.lockout *= 2
```
3. insert the new vote to the front
```
V.lockout() = DEFAULT;
votes.push_front(V)
```
4. Pop the votes and award
```
while votes.len() < DEFAULT_LEN {
   votes.pop_back()
   //unlock tokens
}
```
#### unlocking tokens
creating the contract with X tokens, allows for unlocking up to X + Y tokens, at a rate of R per vote, which are network defined.

tag: @carllin @ericlwilliams @pgarg66 @rob-sholana

**Comment by garious** [comment]
Bumped this back a release. It's awkward to implement lockouts without also testing slashing conditions.

**Comment by garious** [comment]
@carllin, @aeyakovenko, should this issue be assigned to one of the Beacons patch releases and closed?
