### ISSUE TITLE
spl-token-cli: after creating new spl token and new account for it, cannot query balance for new account

### ISSUE THREAD

**Issue by nukec** [solana-labs/solana#16629]
#### Problem
Running simple commands to create a SPL token via spl-token-cli gives a following error:
```
amel@DESKTOP-P6MTIP0:~/playground/solana$ spl-token create-token
Creating token FaByLiV5uAk6dAssPDZkR3GwzELfx85azQw9zg8xHAJi
Signature: 58UrZdiXGGExodiA2QePrhW1t2SRckce84VDpXD3L1jewgQgejcDiiLjvRiaDfwYmJVdJYmSMkp4RDHt2kyKnig4
```
```
amel@DESKTOP-P6MTIP0:~/playground/solana$ spl-token create-account FaByLiV5uAk6dAssPDZkR3GwzELfx85azQw9zg8xHAJi
Creating account Hrnv9HVW6hH6TEU5VvVuSFCZqjrpVYUHq75hnQEExLyx
Signature: 4jPkKCFsdR9Mq1sj4iRQjdN8RProSPgaGYkdwmqWhdiMziPzLdRyPtnNFPBNNmHttc1b36TULkAiM24i11gQ5vYV
```
```
amel@DESKTOP-P6MTIP0:~/playground/solana$ spl-token balance Hrnv9HVW6hH6TEU5VvVuSFCZqjrpVYUHq75hnQEExLyx
Could not find token account 8YLTPQ1Z1eYbHaKysgKgiYaqtVJTbVjBPssdY7hqU7XR
```

Trying querying the created account's balance returns an error saying it could not find a token account, which address is different than the created one as seen above. The account does exist, verified on the explorer and via JSON RPC.

#### CLI version
spl-token-cli 2.0.10

#### Proposed Solution
-

**Comment by CriesofCarrots** [comment]
Hi @nukec . Try:
```
$ spl-token balance FaByLiV5uAk6dAssPDZkR3GwzELfx85azQw9zg8xHAJi
```
The `spl-token-cli` supports the assicated-token-account standard, which considers the main wallet address and token types as the primary identifiers of your accounts. Your main wallet address is set in the cli config, so you just need to provide the token type (mint address) in the `spl-token balance` command. This implementation is new for v2.0.10, so please let us know if you see incorrect or poor documentation.

Fyi, you should also be able to confirm any/all of your token accounts by running:
```
$ spl-token accounts
```

**Comment by CriesofCarrots** [comment]
I am closing this issue for now, but please feel free to re-open or open a new one if you have additional questions, or if you have any ideas about how we could communicate this standard and system better.
