### ISSUE TITLE
Racy test test_load_account_and_purge_race_without_retry

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#16638]
#### Problem

`test_load_account_and_purge_race_without_retry` is racy
https://buildkite.com/solana-labs/solana/builds/44388#9e5bfd29-91b7-4304-969c-2a8aff9e5b72/125-1941

#### Proposed Solution

debug/fix

**Comment by sakridge** [comment]
cc @ryoqun

**Comment by mvines** [comment]
Please revert https://github.com/solana-labs/solana/pull/16793 when this issue is fixed

**Comment by ryoqun** [comment]
this is indirectly fixed by https://github.com/solana-labs/solana/pull/17319
