### ISSUE TITLE
cluster_info::test_push_votes_with_tower is flaky

### ISSUE THREAD

**Issue by ruuda** [solana-labs/solana#16680]
#### Problem

Running the following command fails in about 8/10 of the runs for me:

```
$ cargo test --package solana-core --release test_push_votes_with_tower
    Finished release [optimized] target(s) in 0.50s
     Running target/release/deps/solana_core-3de16058cf8e4670

running 1 test
test cluster_info::tests::test_push_votes_with_tower ... FAILED

failures:

---- cluster_info::tests::test_push_votes_with_tower stdout ----
thread 'cluster_info::tests::test_push_votes_with_tower' panicked at 'assertion failed: `(left == right)`
  left: `28`,
 right: `31`', core/src/cluster_info.rs:4065:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    cluster_info::tests::test_push_votes_with_tower
```

The left value varies across runs. I can reproduce with both c8b474cd0ba2a66cc948b92149d747a7438d672b and v1.5.18. Without `--release` it does not reproduce.

#### Proposed Solution

I know very little about Solana, but looking at the test itself, there are several sources of nondeterminism, such as the `ThreadRng`, getting the current time, and probably also `KeyPair::new()`? I tried replacing the `ThreadRng` with one with a fixed seed, but that did not solve the problem. Replacing `timestamp()` with `0` makes it pass more often, but then it sometimes fails on a different assertion:

```
thread 'cluster_info::tests::test_push_votes_with_tower' panicked at 'assertion failed: vote_slot != 23', core/src/cluster_info.rs:4079:13
```

**Comment by xiangzhu70** [comment]
@ruuda I tried running this for 10k times.  not seeing the failure.

Not sure how I can reproduce this "about 8/10 of the runs" error rate.

**Comment by ruuda** [comment]
@xiangzhu70 testing now on f8bdedb596a4259d81aa2b114f2d7795a998763a, it looks like the test has been moved from `solana-core` to `solana-gossip`. If you look at the output now, you can see it runs 0 tests:

```
$ cargo +1.60.0 test --package solana-core --release test_push_votes_with_tower 
    Finished release [optimized] target(s) in 0.78s
     Running unittests (target/release/deps/solana_core-61bf83521da13427)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 400 filtered out; finished in 0.00s

     Running tests/fork-selection.rs (target/release/deps/fork_selection-0fb6554197807f26)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 9 filtered out; finished in 0.00s

     Running tests/ledger_cleanup.rs (target/release/deps/ledger_cleanup-b0dacd4f284e7fde)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 2 filtered out; finished in 0.00s

     Running tests/snapshots.rs (target/release/deps/snapshots-6725c36f75d8adb5)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 24 filtered out; finished in 0.00s
```

Changing the crate to `solana-gossip`, the following command still reproduces the failing test on f8bdedb596a4259d81aa2b114f2d7795a998763a:

```
$ cargo test --package solana-gossip --release test_push_votes_with_tower/
```

```
    Finished release [optimized] target(s) in 1.05s
     Running unittests (target/release/deps/solana_gossip-06bc425e7039fe4c)

running 1 test
test cluster_info::tests::test_push_votes_with_tower ... FAILED

failures:

---- cluster_info::tests::test_push_votes_with_tower stdout ----
thread 'cluster_info::tests::test_push_votes_with_tower' panicked at 'assertion failed: vote_slot != 23', gossip/src/cluster_info.rs:3882:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    cluster_info::tests::test_push_votes_with_tower

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 148 filtered out; finished in 0.01s

error: test failed, to rerun pass '-p solana-gossip --lib'
```

**Comment by xiangzhu70** [comment]
@ruuda Thanks for the info!  I can now reproduce the bug.  I could not because I was using the debug version.  It looks the --release flag is necessary to see this failure.

**Comment by xiangzhu70** [comment]
In push_vote_at_index(), gossip_crds.insert() may fail silently.
error!("push_vote failed: {:?}", err); is not effective.

Two problems:

Not handling the error case.
error! not working.
no return value checking.  So this error is not noticed and handled.  The subsequent code assumes insert() succeeds.

The error occurs due to overrides()
In crds.rs:
// Returns true if the first value updates the 2nd one.
// Both values should have the same key/label.
fn overrides(value: &CrdsValue, other: &VersionedCrdsValue) -> bool {
    println!("xov0 value {:?}, other {:?}", value, other);
    assert_eq!(value.label(), other.value.label(), "labels mismatch!");
    // Node instances are special cased so that if there are two running
    // instances of the same node, the more recent start is propagated through
    // gossip regardless of wallclocks.
    if let CrdsData::NodeInstance(value) = &value.data {
        if let Some(out) = value.overrides(&other.value) {
            println!("xov5, return out {}", out);
            return out;
        }
    }
    let ret = match value.wallclock().cmp(&other.value.wallclock()) {
        Ordering::Less => false,
        Ordering::Greater => true,
        // Ties should be broken in a deterministic way across the cluster.
        // For backward compatibility this is done by comparing hash of
        // serialized values.
        Ordering::Equal => {
            let value_hash = hash(&serialize(&value).unwrap());
            let bool_ret = other.value_hash < value_hash;
            println!("xov8, bool_ret {}", bool_ret);
            bool_ret
        }
    };

	In the failing case, the log is below.  Is this logic correct?
xov8, bool_ret false
xov9, ret false

**Comment by xiangzhu70** [comment]
This function  was created by @behzadnouri.  Hi Behzad, could you please clarify the intention here?  Thanks!

**Comment by behzadnouri** [comment]
patched by https://github.com/solana-labs/solana/pull/26554

**Comment by xiangzhu70** [comment]
See the analysis above.  There are multiple problems and questions which not yet answered.  So I reopened this issue.

The patch #26554 does a 5 ms sleep.  This only works around the test to avoid the wallclock being equal condition.  It is still a question whether overrides should return false when the intention is to insert a new value.  If so, why insert() does not return error and there is no logic to handle the insertion failure path.

**Comment by behzadnouri** [comment]
By design, and with the exception of `NodeInstance`, gossip overrides entries if the new value has a more recent wallclock.
It is totally valid for gossip to drop entries if the table already has a more recent entry for the same key.
That is not an error.

**Comment by xiangzhu70** [comment]
> By design, ....That is not an error.

Then the insert() function should inform the caller when the new value is not successfully.  I will add the logic to handle the insertion failure path.

To be complete, the test function really should test both the dropping and passing conditions.

**Comment by CriesofCarrots** [comment]
This test is passing consistently in our CI now.
