### ISSUE TITLE
banking_stage::test_banking_stage_entryfication is flaky

### ISSUE THREAD

**Issue by ruuda** [solana-labs/solana#16684]
#### Problem

The following command fails occasionally:

```
$ cargo test --package solana-core --release test_banking_stage_entryfication
    Finished release [optimized] target(s) in 0.50s
     Running target/release/deps/solana_core-3de16058cf8e4670

running 1 test
test banking_stage::tests::test_banking_stage_entryfication ... FAILED

failures:

---- banking_stage::tests::test_banking_stage_entryfication stdout ----
thread 'banking_stage::tests::test_banking_stage_entryfication' panicked at 'called `Result::unwrap()` on an `Err` value: RocksDb(Error { message: "IO error: lock hold by current process, acquire time 1618941887 acquiring thread 139968334362176: farf/ledger/core/src/banking_stage.rs-1722-H5kWgQfw2u3ivCpd5piABsz7o8Kn2Rj4ew7XBYNe8cbBz/rocksdb/LOCK: No locks available" })', core/src/banking_stage.rs:1784:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    banking_stage::tests::test_banking_stage_entryfication

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 519 filtered out; finished in 3.53s
```

It’s this `unwrap` that fails: https://github.com/solana-labs/solana/blob/08d52536513ad57a6101061f41097b0c4941e3e9/core/src/banking_stage.rs#L1784

I can reproduce with both c8b474cd0ba2a66cc948b92149d747a7438d672b and v1.5.18. Without `--release` it does not reproduce. I’m not sure about the conditions for reproducing, sometimes it passes 50 times in a row, sometimes there’s a streak of 20 runs where it fails maybe 50% of the time. I think it reproduces more easily when CPU utilization of the machine is at 100%, but I haven’t tested this extensively.

I did find #5659 about flakiness in the same test. It was supposedly fixed in e267dfacdd444fc08a44f04e5b6b929312e8dfe6, but there might still be a more subtle source of nondeterminism hiding somewhere.

#### Proposed Solution

Would retrying the `Blockstore::destroy` a few times in case of `Err` be appropriate, or is this lock not supposed to be held at that point at all? I see one `.join()` in the test, are there any other threads that need to shut down before the test ends?

**Comment by xiangzhu70** [comment]
@ruuda, @mvines 
I did 1100 runs, 400 in debug version, 700 in release version, but could not reproduce this error.  Please check if we can close this issue.

**Comment by ruuda** [comment]
I can still reproduce on b26c79b77bd443109097cc78d97060f9b4756663 in fewer than 50 runs.

```
test banking_stage::tests::test_banking_stage_entryfication ... FAILED

failures:

---- banking_stage::tests::test_banking_stage_entryfication stdout ----
thread 'banking_stage::tests::test_banking_stage_entryfication' panicked at 'called `Result::unwrap()` on an `Err` value: RocksDb(Error { message: "IO error: lock hold by current process, acquire time 1656057792 acquiring thread 39807: /home/ruud/repos/solana/core/farf/ledger/core/src/banking_stage.rs-2612-GuwNPU7TpPuS89uChSnwCHqsAQmNwj1yFrzjfi1jZgsB/rocksdb/LOCK: No locks available" })', core/src/banking_stage.rs:2677:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    banking_stage::tests::test_banking_stage_entryfication

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 399 filtered out; finished in 4.63s
```

I made sure to have some fuzzers and compilers running in the background to have 100% CPU usage on the machine. Still not sure if that is what makes a difference, but I suspect it plays a role. @xiangzhu70, are you able to reproduce when the machine is busy?

**Comment by xiangzhu70** [comment]
@ruuda I haven't reproduced the failure yet.  Tried running compilations, but didn't reproduce the error.

When the CPU is busy, I think some timeouts will inevitably happen because they don't get enough CPU cycles from the OS scheduler.  I think it is just expected.  Is it reasonable to consider it as a test failure?

**Comment by ruuda** [comment]
When you run only this test in isolation, the machine isn’t loaded, but when you run the full Solana test suite then many tests run in parallel, and the machine is fully loaded, and then this test fails. This makes the test suite flaky. This is problematic for packaging Solana in Nix, it is problematic for our build automation, and I suppose it is also problematic for your own CI.

If the test is expected to fail due to a timeout, consider adding a retry, bumping the timeout, or deleting the test.

**Comment by CriesofCarrots** [comment]
This test is passing consistently in our CI now.
