### ISSUE TITLE
Airdrops failing in CI

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#1673]
#### Problem

```
Error: StringError("Airdrop failed!")
Failed
```

https://solana-ci-gate.herokuapp.com/buildkite_public_log?https://buildkite.com/solana-labs/solana/builds/4478#stable-perf

**Comment by CriesofCarrots** [comment]
The solana-wallet requests in wallet-sanity can end up going to any of the nodes active during the test. Troubleshooting by @carllin suggests that what we are seeing here are cases where `solana-wallet balance` request is sent to the validator before replication of the successful airdrop has completed. If so, a delay or retry should resolve this issue.

**Comment by mvines** [comment]
> solana-wallet balance request is sent to the validator before replication of the successful airdrop has completed

The balance request goes to the leader, so not sure this theory holds

**Comment by CriesofCarrots** [comment]
The balance request goes to the RPC port 8899, which is open on both leader and validator.
