### ISSUE TITLE
Data from accounts created via CPI is not copied back to caller

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#16825]
#### Problem
When a program calls another program which creates and initializes a new account. The data is *not* copied back to the original caller. Here's an example project with this issue: https://github.com/mithraiclabs/program_associated_account_poc

The above example includes a program which calls the associated token account program via CPI. The associated token
program is able to allocate an account and initialize it just fine. But that account is not passed back to the root caller program.

It looks like this problem went undetected for awhile because the data length *is* passed back correctly:
https://github.com/solana-labs/solana/blob/559d3d8f49e114e9da0cbd27f898a6c4487846c8/programs/bpf_loader/src/syscalls.rs#L2028-L2029

But even after updating the serialized data length, `account_ref.data.len()` isn't updated and so the copy doesn't do anything:
https://github.com/solana-labs/solana/blob/559d3d8f49e114e9da0cbd27f898a6c4487846c8/programs/bpf_loader/src/syscalls.rs#L2031-L2033

The impact of this bug is that caller programs will fail the verify check because the runtime thinks they cleared the data of an account they don't own

#### Proposed Solution
Fix account ref data pointer mutation and test that data is copied when data slice size increases

**Comment by jstarry** [comment]
@tomjohn1028 you can subscribe to this issue for updates on the bug you're seeing

**Comment by JPCreedon** [comment]
We got stuck on this last hackathon.

**Comment by tomjohn1028** [comment]
@jackcmay @jstarry any timeline on when this will get cut into a release? Sorry to ping, but I reviewed the release doc and didn't see a regular release schedule. And I don't believe I can see draft releases. So I'm not sure what's in the pipe to gather an ETA on this landing in a `1.6.X` release.

**Comment by mvines** [comment]
the code will be in the 1.6.7 release, which I think we can ship on Monday.  But the feature can't be activated until 95% nodes upgrade to v1.6.7, which would probably be mid-next week for devnet, a week later for testnet and maybe a couple weeks for mainnet-beta.  Does that work with your timeline?

**Comment by tomjohn1028** [comment]
@mvines that should work for us!
