### ISSUE TITLE
SPL Docs: Token Program: "spl-token balance" does not work as described

### ISSUE THREAD

**Issue by garyrob** [solana-labs/solana#16839]
#### Problem
On page https://spl.solana.com/token, where it describes using `spl-token balance` to show a 0 balance, the command is used with the newly-made account address. However, on my machine, I had to use the token identifier to make it work; using the account address resulted in an error.

That is:
```
➜  solana spl-token create-token
Creating token 2mfk8hNACVotg4y9CppSexocGW2Y5E5sVrXojvSR6bFB
Signature: 3RdvH8iKTJMgsSYRRcmn8wqXgrqi3ymu4cNgMCYcaBbmJQfrmeuTg4jzuVMfHtowDXeFdWig4LcD7H7QT4Pb5yuR
➜  solana spl-token supply 2mfk8hNACVotg4y9CppSexocGW2Y5E5sVrXojvSR6bFB
0
➜  solana spl-token create-account 2mfk8hNACVotg4y9CppSexocGW2Y5E5sVrXojvSR6bFB
Creating account 2sXTvqGUcVicbuF9ZhntVoc6nZXuh5a9fwvyybRfTsFa
Signature: 2kaBnz6VxE8ZNoGk7BWuBhCWVzbK83dRH1j61Cg7d2T9jWBbFHSgyZzCxJJuaeDCixcGFN2uXQwj53wD71pWnUuy
➜  solana spl-token balance 2sXTvqGUcVicbuF9ZhntVoc6nZXuh5a9fwvyybRfTsFa
Could not find token account 7nMYS6wyvypvY5kTQWT1ibrq5zRcXgfDBoCgDzaKPsVy
➜  solana spl-token balance 2mfk8hNACVotg4y9CppSexocGW2Y5E5sVrXojvSR6bFB
0
➜  solana spl-token mint 2mfk8hNACVotg4y9CppSexocGW2Y5E5sVrXojvSR6bFB 100
Minting 100 tokens
  Token: 2mfk8hNACVotg4y9CppSexocGW2Y5E5sVrXojvSR6bFB
  Recipient: 2sXTvqGUcVicbuF9ZhntVoc6nZXuh5a9fwvyybRfTsFa
Signature: em8LL33fa4ex1cm7biZDBmLCFz7DHoiwRhAmZj2yPgP7VEHvV2CG4oNp9YXQjsHGuoNcmg5UD9GgM1fXebJ7jRh
➜  solana spl-token balance 2sXTvqGUcVicbuF9ZhntVoc6nZXuh5a9fwvyybRfTsFa
Could not find token account 7nMYS6wyvypvY5kTQWT1ibrq5zRcXgfDBoCgDzaKPsVy
➜  solana  spl-token balance 2mfk8hNACVotg4y9CppSexocGW2Y5E5sVrXojvSR6bFB
100
```

Also, I don't know where the account address `7nMYS6wyvypvY5kTQWT1ibrq5zRcXgfDBoCgDzaKPsVy`  in the error comes from. I don't know whether there's a problem with the `spl-token balance` command itself or whether it's just a documentation issue.

#### Proposed Solution
I don't have a proposed solution. It seems like one should be able to query the balance of that specific account separately from the token, but at this point I don't see a way to do it.

**Comment by CriesofCarrots** [comment]
Thank you @garyrob !
Those docs are actually here: https://github.com/solana-labs/solana-program-library/tree/master/docs
Hopefully you won't run into any more issues, but if so, do you mind posting to that repo?
