### ISSUE TITLE
RPC: getRecentBlockhash returns expired blockhashes when node is behind

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#16873]
#### Problem
When a node is behind the cluster and hasn't replayed the bank for the requested commitment level, it falls back to its current root. This means that the returned blockhash might already be expired and if used by a transaction, the transaction will be considered invalid and won't be processed.

I took a look at one the mainnet rpc api nodes and saw this log a few times:
```
[2021-04-26T14:57:29.453659067Z WARN  solana_core::rpc] Bank with Max not found at slot: 0
[2021-04-26T15:09:31.536080597Z WARN  solana_core::rpc] Bank with Max not found at slot: 0
[2021-04-26T15:09:31.729123069Z WARN  solana_core::rpc] Bank with Finalized not found at slot: 0
[2021-04-26T15:09:32.723655703Z WARN  solana_core::rpc] Bank with Max not found at slot: 74067603
[2021-04-26T15:20:31.529283589Z WARN  solana_core::rpc] Bank with Max not found at slot: 0
[2021-04-26T15:20:31.585166258Z WARN  solana_core::rpc] Bank with Max not found at slot: 0
[2021-04-26T15:20:32.857433780Z WARN  solana_core::rpc] Bank with Max not found at slot: 74069040
[2021-04-26T15:20:33.232584066Z WARN  solana_core::rpc] Bank with Max not found at slot: 74069040
[2021-04-26T15:20:36.470427635Z WARN  solana_core::rpc] Bank with Max not found at slot: 74069040
[2021-04-26T15:32:05.544369637Z WARN  solana_core::rpc] Bank with Max not found at slot: 0
[2021-04-26T15:32:05.627725484Z WARN  solana_core::rpc] Bank with Max not found at slot: 0
```
This indicates to me that 1) there's some bug where slot becomes 0 (weird) and 2) we're returning the node's root quite a bit.

Relevant code here:
https://github.com/solana-labs/solana/blob/3b8d6b59fb2ee979e9da4e79805175f8b5bf66c6/core/src/rpc.rs#L202-L220

#### Proposed Solution
Stop falling back to the current root, instead return an error or use the gossip confirmed blockhash

cc @ryoqun (you might be interested in this)

**Comment by jstarry** [comment]
Another follow up issue will be if transactions are simulated on a lagging node with a very recent blockhash, might be a little tricky if we don't have the slot for the recent blockhash. Thoughts @mvines?

**Comment by mvines** [comment]
> Another follow up issue will be if transactions are simulated on a lagging node with a very recent blockhash, might be a little tricky if we don't have the slot for the recent blockhash. Thoughts @mvines?

🤔 yeah, a couple ideas that come to mind, none super great:
1. Clients could use finalized blockhashes instead of confirmed.   Gives you less time to send the transaction, but is more resilient against a load balancer with backend nodes at slightly different heights
2. Pass the blockhash slot into sendTransaction, so if the backend node is behind it can reject with a more helpful error than blockhash not found

**Comment by jstarry** [comment]
> Clients could use finalized blockhashes instead of confirmed. Gives you less time to send the transaction, but is more resilient against a load balancer with backend nodes at slightly different heights

That's that they're already doing for the most part since the default behavior of web3 is to use a finalized blockhash. I was thinking 2) as well and doing all that behind the scenes.

**Comment by mvines** [comment]
Yeah, I was thinking the same!  The sdk could track the blockhashes it’s given out and the slot they originated from

**Comment by vae520283995** [comment]
I am an exchange, and I also have this problem. When I get the recentblockhash through api getRecentBlockhash, it sometimes expires.

**Comment by trien-tran** [comment]
> Tôi là một trao đổi, và tôi cũng có vấn đề này. Khi tôi lấy gần đâyblockhash thông qua api getRecentBlockhash, đôi khi nó hết hạn.
same problem

**Comment by CriesofCarrots** [comment]
`getLatestBlockhash` now supports the `minContextSlot` parameter, which returns an error if the blockhash at the specified commitment is older than the specified age (slot). This should allow callers to reject expired blockhashes.
