### ISSUE TITLE
[docs] add bandwidth requirements to validator reqs page

### ISSUE THREAD

**Issue by paul-schaaf** [solana-labs/solana#16887]
#### Problem
Validator requirements page in the docs is missing required/recommended bandwidth (and possibly other network requirements)

#### Proposed Solution
add it

**Comment by danger89** [comment]
> Internet service should be at least 300Mbit/s symmetric, commercial. 1GBit/s preferred

**Comment by t-nelson** [comment]
https://docs.solana.com/running-validator/validator-reqs#networking
