### ISSUE TITLE
solana stakes -u localhost always return timeout error on mainnet-beta

### ISSUE THREAD

**Issue by max-block** [solana-labs/solana#16886]
#### Problem
```
# solana stakes -u localhost
Error: error sending request for url (http://localhost:8899/): operation timed out
```
This command always returns this error on my mainnet-beta node. There is no such a problem when I do the same command on my tds node.

My mainnet-beta node works fine, other command like `solana slot -u localhost` works ok. The problem only with `solana stakes -u localhost`

**Comment by mvines** [comment]
Consider adding an `--account-index program-id` argument to speed up account traversal on your local node:
https://docs.solana.com/running-validator/validator-start#account-indexing

**Comment by max-block** [comment]
I see, thank you!
