### ISSUE TITLE
No keypair generated on `solana program deploy program.so`

### ISSUE THREAD

**Issue by mgild** [solana-labs/solana#16884]
#### Problem
No keypair generated on `solana program deploy program.so`

Meta:
solana-cli 1.6.5 (src:e02bcbda; feat:473508068)
MacOS Big Sur 11.1 (20C69)

**Comment by t-nelson** [comment]
Can you expand?  Describe what you were doing, what happened and what was unexpected.  The keypair generated by that command is typically ephemeral unless an error occurs.  If you always want one, you can generate it manually and pass it as an arg
