### ISSUE TITLE
The max transaction size of 1232 is too limiting for Meta-Transaction

### ISSUE THREAD

**Issue by scottphc** [solana-labs/solana#16906]
#### Problem
The current maximum transaction size is 1280 - 40 - 8 = 1232, but it's too limiting for Meta-Transaction. It's going to wrap original instructions into invoke instructions and also add more public keys (device key, cosigner key and fee payer key). You can check [more details](https://github.com/portto/solana-contract-wallet/blob/9386f5c7faeccd7db8c78d7a5e1491205570dccb/src/program/src/processor.rs#L126) if you're interested in it.

For example, [Raydium Swap](https://github.com/raydium-io/raydium-ui/blob/567a95b640a68cf09bd2693cc8ba235ae28783ad/src/utils/swap.ts#L218) transaction has 5-7 instructions which are around 900 bytes. And after wrapping program wallet invoke instruction, it becomes around 2600 bytes.

Transaction fee is troublesome and confusing for blockchain beginners and Meta-Transaction is a good solution for it. I'd like to seek the possibility of increasing the max transaction size.

#### Proposed Solution
Increase the max transaction size to at least 3000 bytes.

**Comment by scottphc** [comment]
@jstarry @mvines @sakridge Could you give some feedback on this? 🙏

**Comment by aeyakovenko** [comment]
TX size is limited by MTU packet size on the internet.  We can do either 
1. Compress the public keys.  Every epoch index all the pubkeys and allow txs to reference them by a u32 ID
2. Upload the tx into an account that can then be executed as a transaction later.

**Comment by jstarry** [comment]
@scottphc we are in the process of drafting a proposal to solve this. I think in your case you could store the instructions you want to call on-chain in a temporary account and then call those stored instructions later. You shouldn't need to wait for transaction size improvements from us unless you're trying to create transactions that are using ~30 accounts.

Tracking the issue of how to allow transactions with more accounts here: https://github.com/solana-labs/solana/issues/17102

**Comment by XX** [comment]
@jstarry How do I create a temporary account to store instructions? Can you provide a link to an example or documentation?

**Comment by XX** [comment]
@aeyakovenko 
> Compress the public keys. Every epoch index all the pubkeys and allow txs to reference them by a u32 ID

How can I use the compressed public keys and allow txs to reference them by an ID? Can you provide a link to an example or documentation?

**Comment by t-nelson** [comment]
@XX these features are not yet available.  The proposal for v2 transaction format is available at https://docs.solana.com/proposals/transactions-v2
