### ISSUE TITLE
streamer::test_recv_mmsg_batch_size is flaky

### ISSUE THREAD

**Issue by ruuda** [solana-labs/solana#16963]
#### Problem

The following test fails about 1 in 10 times when running with `cargo test --release`:

```
test test_recv_mmsg_batch_size ... FAILED

failures:

---- test_recv_mmsg_batch_size stdout ----
thread 'test_recv_mmsg_batch_size' panicked at 'assertion failed: `(left == right)`
  left: `64`,
 right: `46`', streamer/tests/recvmmsg.rs:28:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test_recv_mmsg_batch_size

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
```

The failing assertion is this one:

https://github.com/solana-labs/solana/blob/3d98321b38966f9e3252a0e545a863f8873625e3/streamer/tests/recvmmsg.rs#L28

#### Proposed Solution

The test is using a local UDP socket. I’m not sure if it is guaranteed that all sends get delivered, or that `recv_msg` will already see all of them by the time it gets called. On a reliable channel, one way to mitigate this is to end the sequence with a stop message, and to read until the stop message is encountered, but if packets are dropped, that would be a problem.

**Comment by xiangzhu70** [comment]
@ruuda 

This assertion is no longer in the code.  I ran this test (release version) for 5000 rounds, all passed.  Could we could this issue?
Thanks!

**Comment by CriesofCarrots** [comment]
This test is passing consistently in our CI now.
