### ISSUE TITLE
RPC: Pubsub becomes unresponsive after exactly 1000 connections

### ISSUE THREAD

**Issue by linuskendall** [solana-labs/solana#17035]
#### Problem

At exactly 1000 connections pubsub becomes responsive. We currently limit some of our servers to 1000 pubsub connections and everything seems fine. However, if I increase that by 1, immediately when the next connection comes the pubsub endpoint (:8900) becomes unresponsive.

Haproxy reports the following and returns a 502 error:
``May  4 10:23:53 localhost haproxy[3096]: xxx:45115 [04/May/2021:10:23:53.122] http-eu~ pubsub-rpc-eu/localhost 0/0/1/-1/1 502 283 - - SH-- 1474/1473/588/588/0 0/0 "GET / HTTP/1.1" pubsub xxx -``

The status is SH meaning that the TCP connection was dropped before any HTTP headers were sent.

I have verified the same using a command line websocket client (skipping haproxy). I can connect to any other server in the cluster fine, but I get an immediate shut down on the connection if I connect to a server with more than 1000 conenctions.

This happens on all servers in cluster, so when I increased the limit we suddenly saw a spike in 502s:

![pubsub](https://user-images.githubusercontent.com/5172293/117004727-062cb600-ad04-11eb-9fd7-c32f56cb7709.png)

Nothing obvious in the log, but if there is something that I can grep for that might shed insight? Attaching log for a few minutes when we had many, many 502 errors / unresponsive pubsub.

[pubsub.log](https://github.com/solana-labs/solana/files/6421129/pubsub.log)

I have not seen anything in the system to indicate that it's a system limit, but it's possible that there is something that is limiting the solana process from handling this. 

#### Proposed Solution

Is this a documented limit and is there a necessary reason for it? IF so, we can just work around it by limiting to 990 or so on each server.

If it is more a smart default, could we potentially have a flag to set it higher?

**Comment by t-nelson** [comment]
I believe this is expected behavior

From `solana-validator --help`
```
        --rpc-pubsub-max-connections <NUMBER>
            The maximum number of connections that RPC PubSub will support. This is a hard limit and no new connections
            beyond this limit can be made until an old connection is dropped. [default: 1000]
```

**Comment by t-nelson** [comment]
Closing as RTFM, per request by @linuskendall on Discord :slightly_smiling_face:
