### ISSUE TITLE
Return to paritytech/jsonrpc

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#1706]
#### Problem
We are currently maintaining our own fork of `jsonrpc`. 

#### Proposed Solution
Paritytech recently published a new version of `jsonrpc` to crates.io, which could allow us to get off our fork.
However, the new package does not include @carllin 's proposed changes (https://github.com/paritytech/jsonrpc/pull/331), so if those fixes are critical to solana and don't get included on crates.io in a timely fashion, our fork may still be needed.

**Comment by carllin** [comment]
That change should not be critical. In the future we won't be shutting down and restarting the RPC services anymore, so I think we can switch back to the Parity version for now.

**Comment by CriesofCarrots** [comment]
Due to unpublished dependencies, paritytech has not published the jsonrpc-ws-server crate, which we use in our notifications service. Thus we're still stuck on our fork for now. Will reopen if/when this changes.
