### ISSUE TITLE
Support Bip32 HD for solana keypair files

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#17093]
#### Problem
Right now, a solana keypair file generated from a particular bip39 seedphrase is a "raw" ed25519 keypair; it does not use the same hashing mechanism from entropy as bip32 master-key derivation does, and does not produce/preserve the chain code that is needed bip32 and bip44 hierarchical derivation.

#### Proposed Solution
Extend solana key files to contain additional data, including the chain code or perhaps even the raw entropy. This would enable solana command-line tools to support bip32 HD from `solana-keygen` key files, following https://github.com/solana-labs/solana/issues/5246

**Comment by CriesofCarrots** [comment]
cc @t-nelson

**Comment by CriesofCarrots** [comment]
Data to store in keyfile:
- seedphrase/entropy
- version
- type, cleartext vs (down-the-road) encrypted 
- base key for verification (either bip32 master key, or solana bip44 base)
- library of derived pubkeys

**Comment by dahifi** [comment]
Is this why we can't import seed phrases derived from Sollet or similar into the `solana-keygen recover`?

**Comment by CriesofCarrots** [comment]
@dahifi , no, you actually can use seed phrases with `solana-keygen recover` using `prompt:` or `ASK` as the keypair parameter:

```
$ solana-keygen recover -h
solana-keygen-recover
Recover keypair from seed phrase and optional BIP39 passphrase
...
ARGS:
    <KEYPAIR>    `prompt:` URI scheme or `ASK` keyword
```
See https://docs.solana.com/wallet-guide/paper-wallet#hierarchical-derivation

**Comment by CriesofCarrots** [comment]
This still seems like a potentially useful idea, but is on no one's any-term radar. I'm going to close for now, but we know where to find this again if we want to pick it up in the future.
