### ISSUE TITLE
1.6.7 Memory Leak

### ISSUE THREAD

**Issue by joesixpack** [solana-labs/solana#17104]
1.6.7 on TDS eats up all available memory + swap then crashes.

![screenshot_2021_05_07_at_06_52_06](https://user-images.githubusercontent.com/23145642/117459951-d1d21900-af00-11eb-8326-675762def45c.png)

**Comment by joesixpack** [comment]
I found the special upgrade parameters inadvertantly left in the systemd file to be the root cause of this memory leak.

**Comment by t-nelson** [comment]
> I found the special upgrade parameters inadvertantly left in the systemd file to be the root cause of this memory leak.

This was `--wait-for-supermajority ...` ?

**Comment by joesixpack** [comment]
Yes, that stuff when the chain forked.
