### ISSUE TITLE
inconsistent behavior 

### ISSUE THREAD

**Issue by somebodyLi** [solana-labs/solana#17106]
#### Problem

why the function `solana_program::pubkey::bytes_are_curve_point()`   with params `[193, 77, 206, 30, 164, 134, 60, 241, 188, 252, 18, 244, 242, 226, 89, 244, 141, 228, 86, 183, 249, 212, 92, 33, 123, 4, 137, 106, 31, 254, 65, 220]
`  has inconsistent behavior compare with python lib pynacl implement `nacl.bindings.crypto_core.crypto_core_ed25519_is_valid_point()`  ???

**Comment by liyanhrxy** [comment]
> Can you expand on what is "inconsistent"?

`solana_program::pubkey::bytes_are_curve_point()` with params `[193, 77, 206, 30, 164, 134, 60, 241, 188, 252, 18, 244, 242, 226, 89, 244, 141, 228, 86, 183, 249, 212, 92, 33, 123, 4, 137, 106, 31, 254, 65, 220] ` return `true`,  `nacl.bindings.crypto_core.crypto_core_ed25519_is_valid_point()` with the same params return `false`

**Comment by liyanhrxy** [comment]
`nacl.bindings.crypto_core.crypto_core_ed25519_is_valid_point() ` The function comes directly from `libsodium `. May be a bug of  `solana_program::pubkey::bytes_are_curve_point()`

**Comment by t-nelson** [comment]
cc/ @jackcmay 

It looks like the nacl on-curve check is a bit more extensive than the recommendation we got for using dalek

https://github.com/pyca/pynacl/blob/b5c7dd110e852bfb47807b0e29eee82948b261a1/src/libsodium/src/libsodium/crypto_core/ed25519/core_ed25519.c#L11-L23

**Comment by jackcmay** [comment]
Hmm, we use https://docs.rs/curve25519-dalek/3.1.0/curve25519_dalek/edwards/struct.CompressedEdwardsY.html#method.decompress which would seem to be sufficient.  i wonder if maybe the python version is more restricted than it needs to be, or maybe decompress has a bug?

**Comment by t-nelson** [comment]
> i wonder if maybe the python version is more restricted than it needs to be, or maybe decompress has a bug?

I'm wondering the same thing.  I pinged @samkim-crypto regarding this issue and he'll be taking a look early next week

**Comment by michaelhly** [comment]
> > i wonder if maybe the python version is more restricted than it needs to be, or maybe decompress has a bug?
> 
> I'm wondering the same thing. I pinged @samkim-crypto regarding this issue and he'll be taking a look early next week

🙏

**Comment by etchao** [comment]
@michaelhly @liyanhrxy I ran into this issue as well and tested out using [this](https://github.com/warner/python-pure25519/blob/master/pure25519/basic.py#L132 ) pure python ed25519 implementation to do the curve check. I quickly cross-checked some points that were failing the libsodium curve check and it seems to provide results consistent with the rust check but I haven't done further validation. That might be a good starting point.

**Comment by liyanhrxy** [comment]
> > I looked into this today and I believe that the issue at hand is summarized in Sections 4.1.2, 4.1.3, 5.4, and the second paragraph of the conclusion (Section 6) in the paper https://eprint.iacr.org/2020/823.pdf. In short:
> > ```
> > * the extra checks in the libSodium does result in stronger security guarantees that is nice to have
> > 
> > * the dalek implementation should still be sufficient for digital signatures in practice
> > ```
> > 
> > 
> >   
> >     
> >     
> >   
> > 
> > 
> > This does mean that the python verification algorithm can reject signatures that are valid with rust implementations.
> 
> Thanks for taking the time to check this one out @samkim-crypto! I think I agree that the Dalek implementation is sufficient for our use. Especially since we're no longer using signatures for replay protection. How do you feel about it @jackcmay?
> 
> Piecing together a compatible check for python seems like the way forward here. There are too many of these accounts in the wild to tighten the Rust/JS checks. @michaelhly / @liyanhrxy is this something you'd feel comfortable taking on?

Well, of course, is there any other progress in the near future? For this reason, our wallet development progress is blocked! ! I personally think that this issue is very important to Solana. The stricter the conditions, the better. After all, the cost of making mistakes is painful.

**Comment by t-nelson** [comment]
> Well, of course, is there any other progress in the near future? For this reason, our wallet development progress is blocked! ! I personally think that this issue is very important to Solana. The stricter the conditions, the better. After all, the cost of making mistakes is painful.

The python package is a third party ecosystem contribution, not maintained by the core team.  @michaelhly is a check, compatible with the Rust/JS implementation, something you feel comfortable implementing?  Perhaps with the alternate ed25519 implementation suggested by @etchao?  IMO implementing the stricter check is a non-starter as we already have addresses live using the current discriminant.  Far too much would break for what does not appear to be of practical benefit.

**Comment by liyanhrxy** [comment]
> Well, of course, is there any other progress in the near future? For this reason, our wallet development progress is blocked! ! I personally think that this issue is very important to Solana. The stricter the conditions, the better. After all, the cost of making mistakes is painful.
> 
hmm, you are right ,it's hard work, I will have an try with @etchao suggest, thanks a lot

**Comment by michaelhly** [comment]
> > Well, of course, is there any other progress in the near future? For this reason, our wallet development progress is blocked! ! I personally think that this issue is very important to Solana. The stricter the conditions, the better. After all, the cost of making mistakes is painful.
> 
> The python package is a third party ecosystem contribution, not maintained by the core team. @michaelhly is a check, compatible with the Rust/JS implementation, something you feel comfortable implementing? Perhaps with the alternate ed25519 implementation suggested by @etchao? IMO implementing the stricter check is a non-starter as we already have addresses live using the current discriminant. Far too much would break for what does not appear to be of practical benefit.

I think we'll try out other packages first before trying to implement it ourselves.

**Comment by michaelhly** [comment]
We ended up porting pure python's ed25519 curve check. Thanks, @etchao and @liyanhrxy.
