### ISSUE TITLE
unable to retrieve private keys from an HD wallet

### ISSUE THREAD

**Issue by solannn** [solana-labs/solana#17114]
#### Problem

Unable to acquire multiple different Keypairs from an HD wallet
Currently only able derive the "base" wallet keypair, but not able to move up/down the tree.
i am able to derive the PUBKEYS in an HD way, but not the corresponding private keys (which are required for importation into Sollet).

I wish to generate the seed + passphrase OFFLINE elsewhere, then use the Solana CLI to derive multiple HD keypairs, where i can then import a few private keys into Sollet for regular "not-very-secure" use, and keep the rest of the keys safely stored.

logic tells me something like this should work : 

`solana-keygen recover -o ./test.json ask://?key=5/0`

but alas, the command is not valid.

#### Proposed Solution

None, i am a newcomer and was unable to access other support channels, discord is an irritating mess with no permissions for new users to ask for help.  This post was a last resort.

**Comment by t-nelson** [comment]
This feature was only recently introduced.  Are you using the v1.6.7 release of the CLI tools?

**Comment by solannn** [comment]
Indeed i am, 

Is there a particular command that i'm supposed to use?

**Comment by t-nelson** [comment]
Ah I see the issue.  `solana-keygen recover` doesn't have any way to specify the derivation path yet.

You can use `ask:?key=A/C` directly as a signer any other command, but will always need the seed phrase handy for re-entry. Which defeats the purpose.

This should be fairly trivial to add.  I can look into it next week

cc/ @CriesofCarrots

**Comment by solannn** [comment]
Yes, fetching the PUBKEY for various derivation paths works fine, its fetching the corresponding private key that's the particular issue im having.  
 

Anyway, i'm glad to see you confirm it's not an official feature yet and that it wasnt an oversight on my part.
