### ISSUE TITLE
No description for vital solana-client Rust crates 

### ISSUE THREAD

**Issue by sham789** [solana-labs/solana#17123]
#### Problem

There's no description for vital solana-client Rust crates.

https://docs.rs/solana-client/1.6.8/solana_client/rpc_client/index.html
https://docs.rs/solana-client/1.6.8/solana_client/rpc_config/index.html
https://docs.rs/solana-client/1.6.8/solana_client/rpc_cache/index.html

 I'm trying to perform a cross-program invocation and face the lack of documentation. At the moment the only way to compose logic is to rely on `solana-program-library` resources. However, there's a slight version deviation (The recent version is 1.6.8, most of the programs are using 1.6.2).

My questions are:
1. How to perform cross-program invocation in recent version.
2. The only way to interact with programs is via byte array payload and account metadata?

**Comment by CriesofCarrots** [comment]
💅 Lots of improvements have been made to solana client docs (eg https://docs.rs/solana-rpc-client/latest/solana_rpc_client/rpc_client/struct.RpcClient.html), and to `solana-program` docs, which is really what's being asked about in this issue (https://docs.rs/solana-program/latest/solana_program/#cross-program-instruction-execution)
