### ISSUE TITLE
Capitalization overflow

### ISSUE THREAD

**Issue by carllin** [solana-labs/solana#17130]
#### Problem
While running a validator lemond on master, encountered the panic:

```
thread 'solana-cleanup-accounts-17' panicked at 'overflow is detected while summing capitalization: TryFromIntError(())', runtime/src/accounts_hash.rs:562:14
```

Logs/ledger/snapshot are all under `/home/carl/solana/DebugConsensus/mb/overflow_err` on lemond

#### Proposed Solution
Debug and fix

**Comment by jeffwashington** [comment]
I just got clearance that alex was done with lemond on Tuesday, IIRC. I restarted a validator on lemond to search for this issue. I was going to monitor it, but I haven't checked since Tuesday.

**Comment by CriesofCarrots** [comment]
Looks like issue hasn't reproduced in over a year. Please re-open if you see this again.
