### ISSUE TITLE
Shreds inserted by master causes panic when read by v1.6

### ISSUE THREAD

**Issue by ryoqun** [solana-labs/solana#17136]
#### Problem

Maybe, #16602 started to cause this problem? (CC: @steviez )

```
$ solana-ledger-tool --ledger bad-deploy-ledger-copy slot 77052081
[2021-05-10T06:40:35.791148527Z INFO  solana_ledger_tool] solana-ledger-tool 1.6.6 (src:fe775a97; feat:3714435735)
[2021-05-10T06:40:35.791215160Z INFO  solana_ledger::blockstore] Maximum open file descriptors: 500000
[2021-05-10T06:40:35.791223466Z INFO  solana_ledger::blockstore] Opening database at "/home/sol/bad-deploy-ledger-copy/rocksdb"
[2021-05-10T06:40:35.815238897Z INFO  solana_ledger::blockstore] "/home/sol/bad-deploy-ledger-copy/rocksdb" open took 24ms
Slot 77052081
thread 'thread 'thread 'blockstore_2blockstore_5' panicked at 'blockstore_3' panicked at '' panicked at 'assertion failed: payload.len() >= expected_data_sizethread 'assertion failed: payload.len() >= expected_data_sizeassertion failed: payload.len() >= expected_data_size', blockstore_0', ', ledger/src/shred.rs' panicked at 'ledger/src/shred.rsledger/src/shred.rs:assertion failed: payload.len() >= expected_data_size::279279:', 279:ledger/src/shred.rs9
:9:note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
9
279
:thread '9blockstore_6
' panicked at 'assertion failed: payload.len() >= expected_data_size', ledger/src/shred.rs:279:9
thread 'blockstore_7' panicked at 'assertion failed: payload.len() >= expected_data_size', ledger/src/shred.rs:279:9
thread 'blockstore_4' panicked at 'assertion failed: payload.len() >= expected_data_size', ledger/src/shred.rs:279:9
thread 'blockstore_1' panicked at 'assertion failed: payload.len() >= expected_data_size', ledger/src/shred.rs:279:9
thread 'blockstore_0' panicked at 'assertion failed: payload.len() >= expected_data_size', ledger/src/shred.rs:279:9
thread 'blockstore_3' panicked at 'assertion failed: payload.len() >= expected_data_size', ledger/src/shred.rs:279:9
thread 'thread 'blockstore_5blockstore_2' panicked at '' panicked at 'assertion failed: payload.len() >= expected_data_sizethread 'assertion failed: payload.len() >= expected_data_size', blockstore_4', ledger/src/shred.rs' panicked at 'ledger/src/shred.rs:assertion failed: payload.len() >= expected_data_size:thread '279', thread '279blockstore_7:thread ':ledger/src/shred.rsblockstore_1' panicked at '9assertion failed: payload.len() >= expected_data_sizeblockstore_69:' panicked at '
', ' panicked at 'ledger/src/shred.rsassertion failed: payload.len() >= expected_data_size
279assertion failed: payload.len() >= expected_data_sizethread ':thread '', :', blockstore_3279blockstore_0ledger/src/shred.rs9ledger/src/shred.rs' panicked at ':' panicked at ':
:assertion failed: payload.len() >= expected_data_size9assertion failed: payload.len() >= expected_data_size279279',
', ::ledger/src/shred.rsledger/src/shred.rs99thread '::

blockstore_2279279' panicked at '::assertion failed: payload.len() >= expected_data_size99',

ledger/src/shred.rsthread ':blockstore_5279' panicked at ':assertion failed: payload.len() >= expected_data_size9',
ledger/src/shred.rs:279:9
thread 'blockstore_4' panicked at 'assertion failed: payload.len() >= expected_data_size', ledger/src/shred.rs:279:9
thread 'blockstore_5' panicked at 'assertion failed: payload.len() >= expected_data_size', ledger/src/shred.rs:279thread ':9blockstore_1
' panicked at 'assertion failed: payload.len() >= expected_data_sizethread '', blockstore_7ledger/src/shred.rs' panicked at ':assertion failed: payload.len() >= expected_data_size279', thread 'blockstore_6' panicked at 'assertion failed: payload.len() >= expected_data_size:ledger/src/shred.rsthread '', thread '9:blockstore_3ledger/src/shred.rsblockstore_4
279' panicked at ':' panicked at '279thread ':assertion failed: payload.len() >= expected_data_sizeassertion failed: payload.len() >= expected_data_sizethread ':blockstore_29', ', blockstore_09thread '' panicked at '
ledger/src/shred.rsledger/src/shred.rs' panicked at '
blockstore_5assertion failed: payload.len() >= expected_data_sizethread '::assertion failed: payload.len() >= expected_data_size' panicked at '', blockstore_1279279', assertion failed: payload.len() >= expected_data_sizeledger/src/shred.rs' panicked at 'thread '::ledger/src/shred.rs', thread ':assertion failed: payload.len() >= expected_data_sizeblockstore_799:ledger/src/shred.rsblockstore_6279', ' panicked at '

279:' panicked at ':ledger/src/shred.rsassertion failed: payload.len() >= expected_data_size:279assertion failed: payload.len() >= expected_data_size9:', 9:',
279ledger/src/shred.rs:
9ledger/src/shred.rsthread '9
:blockstore_3:
279' panicked at '279::assertion failed: payload.len() >= expected_data_size99',

```

#### Proposed Solution

Support reading old format shreds from rocksdb?

**Comment by ryoqun** [comment]
@mvines Hi, I think this is a minor blocker for testnet v1.7 thing. This effectively makes downgrading in case of emergency impossible. Definitely we want to keep the recovery measure for eventual v1.6 => v1.7 on mainnet-beta thing.

**Comment by steviez** [comment]
@ryoqun - To confirm my understanding of this issue, was the node here running master (inserting shreds into blockstore), and then the node started running `v1.16` (ie the invocation to `solana-ledger-tool --ledger bad-deploy-ledger-copy slot 77052081`)

**Comment by steviez** [comment]
@ryoqun - Thanks for the confirmation. Comparing the branches, this is expected behavior (and a scenario I'll admit I didn't really consider at time of that PR) given what is currently in `v1.16`. Thinking this through, there are 4 possible scenarios:
a) shred inserted by master, shred retrieved by master
b) shred inserted by v1.16, shred retrieved by v1.16
c) shred inserted by master, shred retrieved by v1.16
d) shred inserted by v1.16, shred retrieved by master

a) and b) are obviously not an issue since each branch is compatible with itself.
c) is the issue we hit here; master inserted a shred without the zero padding, v1.16 retrieved the shred (and didn't zero-pad out again as master does), and failed the assertion because it was too short
d) is not an issue; master will zero-pad shreds out to `SHRED_PAYLOAD_SIZE` when retrieving from the blockstore so if the shred was inserted by v1.16, the shred will still have the padding and the extend will just be a no-op.

To resolve c), I believe backporting the commit to v1.16 would solve the issue: https://github.com/solana-labs/solana/commit/bc3137879746502762cf9e86f07f207bdec59c2d

**Comment by steviez** [comment]
> To resolve c), I believe backporting the commit to v1.6 would solve the issue: [bc31378](https://github.com/solana-labs/solana/commit/bc3137879746502762cf9e86f07f207bdec59c2d)

This is obviously something I'd like to test out first though, preparing a branch now

**Comment by mvines** [comment]
> > To resolve c), I believe backporting the commit to v1.6 would solve the issue: [bc31378](https://github.com/solana-labs/solana/commit/bc3137879746502762cf9e86f07f207bdec59c2d)
> 
> This is obviously something I'd like to test out first though, preparing a branch now

Would backporting cause the tip of v1.6 to no longer be compatible with the latest v1.6.8 release?

**Comment by mvines** [comment]
why cherrypick at all then?  If we can make the tip of v1.6 compatible with v1.6.8 then we can do the same with the tip of master

**Comment by steviez** [comment]
> Ok cool. Goal: master <-> latest release on mainnet are **always** update/downgrade compatible, and interoperable at runtime.

Understood. For a change like this where there is an explicit break, what would the proper protocol be? Maybe push an "auxiliary commit" that would provide upgrade compatibility from latest release branch (v1.6 in this case) to master, wait for a release in that release branch (ie v1.6.9), and then push the intended change into master?

**Comment by mvines** [comment]
`FeatureSet` is the answer!  https://github.com/solana-labs/solana/blob/master/sdk/src/feature_set.rs

You need to support both and make a decision at runtime to switch to the new behavour based once the Feature has been enabled on the cluster the validator is currently running on

**Comment by steviez** [comment]
> Oh sorry, yeah I this case it's not a runtime feature at all.


No worries, I wasn't aware of `FeatureSet` so a good thing to learn about in the event I have a need for this later.

> So yes, "auxiliary commit" that would provide upgrade compatibility. Then wait for that to roll out to mainnet, and then land the other half on master

Got it - noted for the future

**Comment by steviez** [comment]
https://github.com/solana-labs/solana/pull/17147 fixes the compatibility issue
