### ISSUE TITLE
Event-Based On-Account-Modification Listeners

### ISSUE THREAD

**Issue by jon-chuang** [solana-labs/solana#17144]
The purpose of this issue is to cache the design of some additional components to the runtime which may be of use to some people.

Although it will probably be lost in the noise, I'd put it out there in case anyone would like to build on it.

--- 

Summary: The program "listens" to a particular account. When that account changes, the program runs a transaction.

The original intention of event-based listeners was to allow the continuous monitoring of changes - for instance if stake in a stake account starts deactivating etc. Although this could be done off chain, some on-chain programs could benefit from this.

---
#### Design

Design:
Every account has an `Option<Listeners>` field. Every time a listen is triggered, the Listeners are reordered by randomness generated from hashing some data, such as the listener pubkeys along with the previous hash. 

This ensures that there is a deterministic way of randomizing the next order of listeners. 

To avoid the situation where people submit multiple listeners to get a chance of listening first, we add an integer weight alongside each listener. The listener pays `(1 + multiplier)` of the baseline listening cost, the multiple being the next-heighest weight, in addition to the cost of running the transaction. This means there is a second-price auction for listening.

Unfortunately, this can also lead to attacks where an attacker constructs a very long listening chain or even a circular one. To prevent this, we enforce that the accounts that the listener modifies must have `CAN_LISTEN: bool = false`

Or, if we don't want to allow accounts from setting that to false, we can also let the listener have a max call depth, similar to CPIs. However, this max call depth needs to be pretty conservative (e.g. about 2, if max_listeners is 100, else we can have an exponential blowup in the branching of listeners)

Then, we can also retain only the highest `MAX_LISTENERS` bidders in an account's Listeners, perhaps set at 1000
By default, accounts will have `CAN_LISTEN = true`

----
#### Challenges:
Exogeneous programming is challenging.

**Comment by israelidanny** [comment]
Would be interesting to pick this up. Any pointers / instructions to start on?

**Comment by israelidanny** [comment]
This could also be related use-case wise:
https://github.com/solana-labs/solana/issues/14076

**Comment by jon-chuang** [comment]
I don’t have any ideas beyond the original design, unfortunately. It’s might be doable within the confines of a single program, however. 
But, note that because Solana txs require full account access lists to be included in the header, triggering arbitrary event-based instructions may be difficult to do in practice. 
I’m starting to think this is one for the waste bin...

Nevertheless, just curious what your use case is?

**Comment by gregl83** [comment]
Commented in #14076 but I need to reliably consume events or at worst transactions by an off-chain handler.
