### ISSUE TITLE
RPC getConfirmedBlock so slow when the block has many transactions

### ISSUE THREAD

**Issue by crossle** [solana-labs/solana#17173]
#### Problem
PRC getConfirmedBlock needs 1 ~ 2s to get the blocks on the localhost node. How to improve the query? or add some filter params for only return some types transaction. for example only return the transfer transaction.

```
curl http://localhost:8899 -X POST -H "Content-Type: application/json" -d '
  {"jsonrpc": "2.0","id":1,"method":"getConfirmedBlock","params":[77840564, {"encoding": "json","transactionDetails":"full","rewards":false}]}
'
```

**Comment by CriesofCarrots** [comment]
@crossle , do you need the transaction details? If not, `"transactionDetails":"signatures"` will make the response much smaller.
If you do need the details, consider decoding on the client side: pass `"encoding":"base64"`, and then base64-decode the each transaction payload.
https://docs.solana.com/developing/clients/jsonrpc-api#getconfirmedblock

**Comment by crossle** [comment]
Yes, detail transactions.Test from jsonParsed to json no faster more.

**Comment by vae520283995** [comment]
@CriesofCarrots Hi CriesofCarrots, I am an exchange developer, I need to add solana to our exchange and integrate solana according to the documentation. When I call the api getConfirmedBlock it takes a long time, I only need to transfer transactions, but there are many other transactions in the block, which is an invalid transaction for me , Is there a way to filter transfer transactions

**Comment by vae520283995** [comment]
@crossle btw, Do you use your own node or public node (https://api.mainnet-beta.solana.com)

**Comment by crossle** [comment]
> @crossle btw, Do you use your own node or public node (https://api.mainnet-beta.solana.com)

Own node

**Comment by vae520283995** [comment]
> Own node

Can you give me the node configuration? I am now considering whether to use my own node, because public nodes have rate limits

**Comment by vae520283995** [comment]
> Yes, detail transactions.Test from jsonParsed to json no faster more. Trying base64

Is there any conclusion about this?

**Comment by t-nelson** [comment]
> Can you give me the node configuration? I am now considering whether to use my own node, because public nodes have rate limits

An exchange should definitely be running its own nodes.  The public RPC infrastructure is only suitable for develope and sporadic individual user usecases



> > Yes, detail transactions.Test from jsonParsed to json no faster more. Trying base64
> 
> Is there any conclusion about this?

base64 is certainly faster than either of the JSON options.  There's simply less work to do

**Comment by vae520283995** [comment]
> An exchange should definitely be running its own nodes. The public RPC infrastructure is only suitable for develope and sporadic individual user usecases

 Thanks, I will run my own node

> base64 is certainly faster than either of the JSON options. There's simply less work to do

Is there a better solution? Even if it only returns base64, it is difficult for my program to keep up with the rate of block generation.

**Comment by vae520283995** [comment]
> An exchange should definitely be running its own nodes. The public RPC infrastructure is only suitable for develope and sporadic individual user usecases

Does the exchange also need to run a validator node? We only need to call the api, no voting and other functions. Can you give a recommended configuration? We use a cloud server, thank you

**Comment by shixiaofeia** [comment]
I also called getConfirmedBlock. The response time was too long, and I couldn't keep up with the speed of the block, and I also only want the transaction record of the transfer. Is there any good way to filter out non-transfer transactions and speed up the response speed of this interface Do I run my own node
Below is my filter item
```
	if v.Meta.Err != nil {
		return
	}
	if len(v.Meta.PostBalances) < 2 || len(v.Meta.PreBalances) < 2 || len(v.Transaction.Message.AccountKeys) < 2 || len(v.Transaction.Signatures) < 1 {
		return
	}
	if v.Meta.PostBalances[1]-v.Meta.PreBalances[1] <= 0 {
		return
	}
```

**Comment by crossle** [comment]
> > Can you give me the node configuration? I am now considering whether to use my own node, because public nodes have rate limits
> 
> An exchange should definitely be running its own nodes. The public RPC infrastructure is only suitable for develope and sporadic individual user usecases
> 
> > > Yes, detail transactions.Test from jsonParsed to json no faster more. Trying base64
> > 
> > 
> > Is there any conclusion about this?
> 
> base64 is certainly faster than either of the JSON options. There's simply less work to do

base64 still slowly
