### ISSUE TITLE
Writing account state on every slot inefficient and reduces incremental snapshot efficiency

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#17178]
#### Problem

Some percentage of the accounts is rewritten on each slot.
https://github.com/solana-labs/solana/blob/d4ffd909a4f06318387eb74bf21ff58f5c596284/runtime/src/bank.rs#L3574

This limits the number of append-vecs, but it creates more write IO and makes incremental snapshots larger since there are updates to accounts which are not necessary.

#### Proposed Solution

Don't rewrite on each slot. Be able to combine cross-slot accounts into a single append-vec.

**Comment by sakridge** [comment]
Related to https://github.com/solana-labs/solana/issues/17088

**Comment by ryoqun** [comment]
> it creates more write IO and makes incremental snapshots larger since there are updates to accounts which are not necessary.

yeah, this is kind of waste. but it was easy to address infinite append vec issue and introduce stale acocunt's rent collection and periodic on-chain whole-state check at the time...

I think some slot-based reflink mechanism should alleviate the situation while combining older appendvecs. So, we keep to be apparently rewriting the accounts for inclusion to bank hash for on-chain verification. The trick is that the previous updated slot for given account is deterministic across the cluster. So, we could even embed the slot pointer into delta snapshots.

Or rather, we just can give up this on-chain state check altogether and completely relying on background accounts hash check? I rather avoid it for the very blockchain existence.

**Comment by sakridge** [comment]
> > it creates more write IO and makes incremental snapshots larger since there are updates to accounts which are not necessary.
> 
> yeah, this is kind of waste. but it was easy to address infinite append vec issue and introduce stale acocunt's rent collection and periodic on-chain whole-state check at the time...
> 
> I think some slot-based reflink mechanism should alleviate the situation while combining older appendvecs. So, we keep to be apparently rewriting the accounts for inclusion to bank hash for on-chain verification. The trick is that the previous updated slot for given account is deterministic across the cluster. So, we could even embed the slot pointer into delta snapshots.
> 
> Or rather, we just can give up this on-chain state check altogether and completely relying on background accounts hash check? I rather avoid it for the very blockchain existence.

Yea. At the time it was the right thing. I think we are getting to the point where we need to re-think the compaction strategy though because of the accounts growth and need for incremental snapshots.

**Comment by brooksprumo** [comment]
@aeyakovenko posted [an idea on Discord](https://discord.com/channels/428295358100013066/754723351389536348/936753005238292521) today that could solve this:

* Accounts pay for rent upfront
* Each account would now track when its rent expires (i.e. `rent_expiration_slot`)
* Accounts would need to pre-pay for the next rent duration before the next `rent_expiration_slot` (maybe this could be done automatically?)

This would help the validators, as now they'll be compensated for all accounts (instead of just rent-paying accounts, which are the minority).

This would help the runtime by removing the need to run rent collection by scanning all the accounts every epoch. I.e. `generate_index()` could clean up these accounts when starting up from a snapshot.

Some questions:

* How to handle the pre-paying for the next rent duration? Who checks that? We're trying to remove the need to scan all the accounts...
* How to handle the cleaning up of these accounts? Is generate_index() sufficient? What if a node never reboots? Will it be storing all these now-dead accounts indefinitely? How will this work with/affect the bank capitalization checks?

**Comment by brooksprumo** [comment]
To follow along from my comment above, I was thinking about how to tie in lazy rent collection (i.e. no scanning of accounts) with incentives to find-and-close accounts that should be rent collected.

There are parallels I see to how some DeFi programs that I've heard about do this (from what I remember). Specifically,  accounts that should be liquidated/closed are done via a transaction, not by a runtime. For example, lets say Account A should be closed. Other people (ex Account B) can _send transactions_ to query that account to identify it should be closed, then send _another_ transaction to tell the program to close the account. Then Account B would get some portion of the reward for closing Account A. The remaining portion goes to the program (or runtime/validators in our case).

Regular users are now incentivized to find and close accounts. These are regular transactions, so the economics of transactions already handles this. A new `CloseAccountsAndReapRewards` transaction would have a high enough cost to dissuade users from sending erroneous transactions without being sure the account should actually be closed.

What remains is how much rewards should be given to the user, and where those rewards come from. If accounts should only be closed-and-collected once they've reached a balance of 0 lamports, there would be no additional rewards to collect. 

If accounts can be closed below a threshold (i.e. rent exempt minimum), that could work, but traditionally those rewards have gone 100% to the validators; would the validators now get a smaller reward?

Maybe [creating new accounts should have a fixed upfront cost](https://github.com/solana-labs/solana/issues/21348#issuecomment-973296101) _in addition_ to rent? This way, validators get the rewards when accounts are created, and users get the rewards when accounts are closed?

Obviously still lots of details to nail down, but is this a feasible path to continue investigating?

**Comment by jeffwashington** [comment]
A lot of progress has been made on this. It is making its way to completion.
