### ISSUE TITLE
Sudden memory spikes (RPC servers)

### ISSUE THREAD

**Issue by linuskendall** [solana-labs/solana#17182]
#### Problem

We have several times now experienced sudden (apparently unexplainable) memory spikes. Just had two such instance where the validator memory usage suddenly spikes until we either restart it or  it gets OOM killed.

I have gathered some details for one such instance (sg1, 03:45-04:24) below. In this case, memory usage eventually lead to OOM.. As can be seen from the graph the solana process rapidely took about 100% of 1 TB  memory available.

Traffic pattern in this case seems normal, without any particular spikes either in a particular use of an RPC call or in overall traffic.

After restart or kill the node comes back alright and seems healthy. 

**Timeline**
03:45 Memory usage started climbing
04:17 Node starts falling behind network
04:23 Nodes falls behind >100 slots 
04:24 OOM killed (almost 1 TiB memory use)

**Details from monitoring**

Rpc method calls:
![debug-rpc-calls](https://user-images.githubusercontent.com/5172293/117927164-72687480-b317-11eb-81e5-90ad46d738d9.PNG)

Shows the average RPS per method call (each line is a unique rpc method call), with the blue dotted line being OOM kill.

Haproxy requests:
![debug-traffic](https://user-images.githubusercontent.com/5172293/117927175-75636500-b317-11eb-8ebe-ad97741ef2ee.PNG)

Green line is 200 responses, yellow is 429/ratelimit.

Dashboard with the data:
https://hostedmetrics.com/s/nra0B3Js/prometheus/grafana/d/e5PJ5bjMk/memory-leak-debug?orgId=1

The pubsub stats @Tyera provided also seems without anomaly:
https://metrics.solana.com:3000/d/Xb3wjzCMz/pubsub?orgId=2&from=1620788400000&to=1620793500000&var-datasource=Solana%20Metrics%20(read-only)&var-testnet=mainnet-beta&var-hostid=E7XYctP5NiZE2nE5LzJpGoWVC14kaxjna1DXubTVSmf4

Logs from validator:
[solana-validator.log](https://github.com/solana-labs/solana/files/6463847/solana-validator.log)

Logs from our health check (currently shows slot comparison to other nodes):
[health-check.log](https://github.com/solana-labs/solana/files/6463848/health-check.log)

Solana version:

solana-cli 1.6.7 (src:ebb5fc12; feat:3458834192)

Start up arguments:

```
exec /home/solana/.local/share/solana/install/active_release/bin/solana-validator \
  --identity /home/solana/keypair.json \
    --entrypoint entrypoint.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint2.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint3.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint4.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint5.mainnet-beta.solana.com:8001 \
    --ledger /solana/ledger \
  --accounts /solana/accounts/tmpfs \
  --log - \
  --gossip-port 8001 \
  --rpc-port 8899 \
  --dynamic-port-range 8002-8012 \
  --wal-recovery-mode skip_any_corrupted_record \
  --limit-ledger-size  \
  --private-rpc \
  --no-snapshot-fetch \
  --no-genesis-fetch \
  --no-port-check \
  --no-voting \
  --no-untrusted-rpc \
  --halt-on-trusted-validators-accounts-hash-mismatch \
  --enable-cpi-and-log-storage \
  --enable-rpc-transaction-history \
  --account-index program-id spl-token-owner spl-token-mint \
  --expected-genesis-hash 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d \
  --enable-rpc-bigtable-ledger-storage \
  --snapshot-interval-slots 500 \
  --expected-shred-version 13490 \
  --expected-bank-hash Fi4p8z3AkfsuGXZzQ4TD28N8QDNSWC7ccqAqTs2GPdPu \
  --trusted-validator ChorusmmK7i1AxXeiTtQgQZhQNiXYU84ULeaYF1EH15n \
    --trusted-validator Certusm1sa411sMpV9FPqU5dXAYhmmhygvxJ23S6hJ24 \
    --trusted-validator CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S \
    --trusted-validator DE1bawNcRJB9rVm3buyMVfr8mBEoyyu73NBovf2oXJsJ \
    --trusted-validator GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ
```

#### Proposed Solution

First step, need to find a way to diagnose what is going on. From an external view things look normal, then suddenly memory usage spikes.

**Comment by stakeconomy** [comment]
We see this behavior a few times every day. The dus1 RPC server just restarted with same behavior. memory climbing until nothing left. solana process restarts. 

Because a restart takes ~1 hour currently; this memory problem can really put a cluster resources into trouble if more than one server restarts at the same time.

**Comment by t-nelson** [comment]
Is there a list of method calls and response times over the duration where memory usage is climbing?

**Comment by linuskendall** [comment]
@t-nelson This dashboard has it at the bottom:

https://hostedmetrics.com/s/nra0B3Js/prometheus/grafana/d/e5PJ5bjMk/memory-leak-debug?orgId=1

It's RPS/rpc method ("RPC calls by method"). I believe that the public dash allows you to change the time frame if you want to seem ore.

**Comment by linuskendall** [comment]
We had sudden memory spikes on a series of nodes last night again. This kept repeating on the same node, so it could never finish:

<img width="689" alt="Screenshot 2021-06-08 at 02 35 18" src="https://user-images.githubusercontent.com/5172293/121123109-45d54900-c840-11eb-977d-33564c6a5c8a.png">

<img width="689" alt="Screenshot 2021-06-08 at 01 49 40" src="https://user-images.githubusercontent.com/5172293/121123113-4837a300-c840-11eb-939b-0165159f8f65.png">

It was suggested by  @t-nelson  that this was due to lots forks causing shreds to pile up in memory, so is this sudden memory spike issue actually not a symptom of a particular node issue but rather an issue of the node doing compaction at a certain state of the network?

**Comment by linuskendall** [comment]
Attaching log files:

[dus3-LOG.txt](https://github.com/solana-labs/solana/files/6613705/dus3-LOG.txt)
[dus1-LOG.txt](https://github.com/solana-labs/solana/files/6613706/dus1-LOG.txt)

**Comment by linuskendall** [comment]
**Proposed solutions**

The main issue for us is not that nodes get taken out of service (though we would prefer if not at all) but more that there seems to be some synchronised behaviour. SInce the nodes are often upgraded / restarted in series it also seems compaction events are taking place in a synchronised way (?). This leads to cascading failures of the kind that is very difficult to handle properly.

If this is really due to compaction then there are a few things that could work:

1. Best, some ability to trigger a compaction. We could schedule these on each host and have orderly maintenance for the hos while the compaction event occurs. This could be just a command line we run.
2. Second best, some ability to ensure compaction does not happen in synchronised way within a pool - so an ability to offset nodes from each other. This needs to be on the order for hours, we would prefer not to have nodes restart within say 3-4 hours of each other.
3. Worse solution: Insight into how they get synchronised. Is it due to the upgrade/restart cycles? Is it due to when the node was first started up? In that case we can schedule them far from each other and we can also reinitialise nodes to bring them out of sync of each other.

**Comment by ryoqun** [comment]
@linuskendall maybe can we close this now?

**Comment by linuskendall** [comment]
Agree. We haven't seen this in a long time. Thanks a bunch.
