### ISSUE TITLE
Solana DevNet does not work properly in comparison with Testnet

### ISSUE THREAD

**Issue by sham789** [solana-labs/solana#17208]
#### Problem

I'm trying to send a transaction(program deployment) in Solana DevNet but I face the following error. However, I don't face issues in Solana Testnet. 

Moreover, I face deployment issues (timeout errors) in Testnet from time to time.

#### Failing example:

API server listening at: 127.0.0.1:4633
------- begin message --------
02000103bfb92919a3a0f16abc73951e82c05592732e5514ffa5cdae5f77a96d04922c8538a3dc873b74f3692cf00d644a3c888963a8ccf696bf45e7a41ab473790620650000000000000000000000000000000000000000000000000000000000000000ad52356f8463471d3201273b109ceab16d62ee6c042ee6cdd10207d7c9122c5c0102020001340000000000c82800000000000001000000000000be8f3dc36da246f1c085fd38b1591451bde88f5681ad8418bc6098ae2852d8da
-------- end message ---------
2021/05/13 08:14:20 send tx error, err: Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.
Process exiting with code: 0

**Comment by sham789** [comment]
#### Proposed solution

Make sure of using the same transaction validation algorithm. In other words - guarantee the same validation behaviour in any network.

**Comment by CriesofCarrots** [comment]
Devnet and testnet api nodes are definitely using the same transaction validation algorithm; in fact, they are running the same software version: v1.6.7
However, the two clusters do not have the same account state.
I'm having some trouble decoding your transaction to check the addresses, but the devnet simulation error suggests that one or more of the accounts has not been funded. Perhaps you need to airdrop yourself some devnet SOL? `solana airdrop 1`

**Comment by akriventsev** [comment]
Balance of account in a Devnet is ~45 SOL. https://explorer.solana.com/address/CQruEkwfcFJrApGNwuwfF1cjZHDqYr7XkRyLn6a6rmmW?cluster=devnet

**Comment by t-nelson** [comment]
> Devnet and testnet api nodes are definitely using the same transaction validation algorithm; in fact, they are running the same software version right now: v1.6.7
> However, the two clusters do not have the same account state.
> I'm having some trouble decoding your transaction to check the addresses, but the devnet simulation error suggests that one or more of the accounts has not been funded. Perhaps you need to airdrop yourself some devnet SOL? `solana airdrop 1`

Nailed it.  This is a raw message containing a `SystemInstruction::CreateAccount`, the funding account of which (`DuQdNu6c7nR1TWMuTEv1S3Dh94gW4xnkbguLHTujmm4g`) has a zero-balance on devnet.
