### ISSUE TITLE
start validator `solana-test-validator` Library not loaded error

### ISSUE THREAD

**Issue by interdailytop19** [solana-labs/solana#17222]
#### Problem
I followed the solana hello world guide to the step `solana-test-validator`

error: 
```
dyld: Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib
  Referenced from: /Users/123/.local/share/solana/install/active_release/bin/solana-test-validator
  Reason: image not found
zsh: abort      solana-test-validator
```

m1 chip
macOS 11.3.1
node version v14.16.1

google searched this thread:
https://stackoverflow.com/questions/59006602/dyld-library-not-loaded-usr-local-opt-openssl-lib-libssl-1-0-0-dylib

but can't switch openssl vserion
```
Error: Unknown command: switch
```
```
which openssl
/usr/bin/openssl
```
no openssl@1.1 folder in /usr/local/opt/

tried different node versions,
tried update upgrade brew,
tried brew uninstall then install openssl
tried brew install different version of openssl
tried symlink to brew openssl
tried manually copy the file to `/usr/local/opt/openssl@1.1` from brew openssl
get error `/usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib: mach-o, but wrong architecture`

brew openssl in `/opt/homebrew/Cellar/openssl@1.1/1.1.1k`

**Comment by dwrx** [comment]
I had the same issue, but on Intel chip, and a simple `brew install openssl@1.1` solved it for me.

**Comment by interdailytop19** [comment]
I tried `brew install openssl@1.1` and run `solana-test-validator`, same error as before

**Comment by t-nelson** [comment]
> I tried `brew install openssl@1.1` and run `solana-test-validator`, same error as before

This all needs to be done in Rosetta on M1, AFAIK

**Comment by interdailytop19** [comment]
ok, I install Rosetta, and then install x86 brew follow this stockoverflow post [link](https://stackoverflow.com/questions/64963370/error-cannot-install-in-homebrew-on-arm-processor-in-intel-default-prefix-usr), 

then install openssl@1.1 
`arch -x86_64 /usr/local/homebrew/bin/brew install openssl@1.1`

then smylink x86 brew openssl to `/usr/local/opt/openssl@1.1` by
`ln -s /usr/local/Homebrew/opt/openssl@1.1 /usr/local/opt/openssl@1.1`

then run `solana-test-validator` result this error
```
Ledger location: test-ledger
Log: test-ledger/validator.log
⠁ 
zsh: illegal hardware instruction  solana-test-validator

```

**Comment by interdailytop19** [comment]
#17406

**Comment by interdailytop19** [comment]
#17406

**Comment by gxxcastillo** [comment]
What's the solution here?  

I'm on an M1, running 11.5.2 and I've tried uninstalling / reinstalling openssl then rebuilding from source using `cargo clean 
 && cargo build` but I keep getting the same error: 

```Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib```

I've tried re-installing homebrew.  I've tried in a standard terminal as well as a rosetta 2 terminal

**Comment by nityanandagohain** [comment]
I am facing the same issue as @gxxcastillo  :(

**Comment by cdrappi** [comment]
Have you built the `solana-test-validator` from source using `scripts/cargo-install-all.sh`?

**Comment by gxxcastillo** [comment]
@cdrappi.  After a lot of trial and error I was able to get it running via a manual build (sorry, I didn't document my steps, I should have) and run.

Now, I'm running into [this other issue](https://github.com/solana-labs/solana/issues/18033#issuecomment-906079017), I wonder if it might be related to me being on an M1.

I've tried different demos and all of them have the same issue, when I try to deploy my program. Basically it just gets stuck at `[0/1] Finalizing transaction...`

**Comment by gxxcastillo** [comment]
Update: My issues have been resolved.  I have the solana-test-validator running on my M1 and I've been able to build and deploy.  Going back through and making sure everything: Homebrew, openssl, rust, and the solana tools were installed on x86 and that fixed it.

**Comment by entergmode** [comment]
@gxxcastillo Hi, i'm running into those issues now. Did you build from source on M1?  I can't build due to lots of errors

**Comment by entergmode** [comment]
Okay it works

**Comment by entergmode** [comment]
Guys I summarized what I encountered in this [note](https://medium.com/@entergmode/installing-solana-tooling-on-m1-macbook-b49d2e1f29ed). Hope it helps someone

**Comment by dif71214** [comment]
how do you Delete solana to start from scratch.

**Comment by rav3nh0lm** [comment]
@dif71214 actually good question

**Comment by gxxcastillo** [comment]
@dif71214, @rav3nh0lm, you may just need to delete the solana folder you checked out from github and the `~/.config/solana` folder.

There are [instruction here](https://rust-lang.github.io/rustup/installation/index.html) in case you need to uninstall Rust: `rustup self uninstall`
