### ISSUE TITLE
Documentation Suggestion: prompt:// vs. ASK

### ISSUE THREAD

**Issue by moranbw** [solana-labs/solana#17229]
#### Problem

I was following the instructions here to set up a Paper Wallet: https://docs.solana.com/wallet-guide/paper-wallet#public-key-derivation

When I try to execute the following command: ```solana-keygen pubkey prompt://``` I receive the following error in Debian 10: ```Error: unrecognized signer source```.  However If I try ```solana-keygen pubkey ASK```, I get the expected prompt and experience.

#### Proposed Solution

Should the documentation be updated from ```prompt://``` to ```ASK```?  Or is this different per OS?  If the latter, perhaps there should at least be a mention of ASK?

**Comment by CriesofCarrots** [comment]
Hi @moranbw . We had a slight issue with our docs build today. The `prompt:` url scheme is not yet live -- it is coming in v1.6.9 (later today). The docs got ahead of us. Sorry for the confusion!

**Comment by moranbw** [comment]
@CriesofCarrots so I upgraded today, and tried to verify my pubkey ```solana-keygen verify <PUBKEY> prompt://```

I now do receive the prompt to enter seed phrase and passphrase (if necessary).  However, with ```prompt://``` the verification Failed.  With ```ASK``` it is a Success.

Any ideas why this may be the case?

**Comment by CriesofCarrots** [comment]
> Any ideas why this may be the case?

Yes, `ASK` generates a raw ed25519 keypair from the seed phrase; the `prompt:` default is the solana bip44 base key at derivation-path `m/44'/501'`. (Incidentally, you can choose other bip44 derivation paths by adding the `?key` query string: https://docs.solana.com/wallet-guide/paper-wallet#hierarchical-derivation)

If you run  `solana-keygen pubkey prompt:`, you should see a different pubkey than from `solana-keygen pubkey ASK`, and that pubkey should work in `solana-keygen verify ...`

**Comment by moranbw** [comment]
OK thanks!  I'll read up more on this.  But seems like original issue is fixed so I will close!
