### ISSUE TITLE
[CLI] what is the derivation path?

### ISSUE THREAD

**Issue by clintnetwork** [solana-labs/solana#17240]
Hi,

Just generated a new address with CLI, and unable to import it in `sollet` or in any kind of wallet, it seems that the derivation path is different, I tried all possibilities, any idea?

PS: Sorry to open issue for this

Thanks

**Comment by CriesofCarrots** [comment]
Assuming you generated that keypair with `solana-keygen new`, the result is a raw ed25519 keypair and will not align with any of the sollet derivation paths. However, we do now support HD in the solana cli tools, so you can use your seed phrase and derivation path from sollet to sign with the same keys.

This will also include recovering a keypair json file at the same derivation path as your sollet wallet. We are about to release v1.6.9 which includes this latter facility; once that is out, I will follow up here with a link to documentation.

**Comment by clintnetwork** [comment]
Okey, awesome, thank you for the explainations!

**Comment by farmerxt** [comment]
> Assuming you generated that keypair with `solana-keygen new`, the result is a raw ed25519 keypair and will not align with any of the sollet derivation paths. However, we do now support HD in the solana cli tools, so you can use your seed phrase and derivation path from sollet to sign with the same keys.
> 
> This will also include recovering a keypair json file at the same derivation path as your sollet wallet. We are about to release v1.6.9 which includes this latter facility; once that is out, I will follow up here with a link to documentation.

hey @CriesofCarrots i have the feeling you know how things work

my case is opposite

few years ago i created a wallet in solet later showed (depriciated) but was functional and funds loaded
now i want to import my 12 seed words to solflare or phantom but i cant import the correct deviation path do you maybe know how i can access it ? i had 2 wallets and none show up when i enter the mnenomic

**Comment by CriesofCarrots** [comment]
@farmerxt , please don't necropost on closed issues. This would be a question better addressed on [Solana Stack Exchange](https://solana.stackexchange.com/)
However, quickly, this is the deprecated derivation path that sollet used: https://github.com/project-serum/spl-token-wallet/blob/9c9f1d48a589218ffe0f54b7d2f3fb29d84f7b78/src/utils/walletProvider/localStorage.js#L28
I am not sure if solflare or phantom will let you import it, as it not a valid bip44 derivation path. But you could use `solana-keygen recover prompt:?full-path=m/501/<X>/0/<Y>` to generate a keypair file to use with the solana-cli to transfer any funds to another wallet.
