### ISSUE TITLE
  Path not support hidden folder. OS:Windows

### ISSUE THREAD

**Issue by yin75620** [solana-labs/solana#17252]
#### Problem
OS: windows

Below command has an error after 1.6.8, But fine on 1.5.X
```
solana-keygen new
solana-keygen pubkey
* Error: unrecognized signer source
```

I change to the below command. It work fine. 
```
solana-keygen new -o 123.json
solana-keygen pubkey 123.json
* AtpiSfWpGcd19mvQS8qMLuvJNta5g6qUfxtff1s3XvaU
```

#### Proposed Solution
Could path support hidden folder like previous version (.config)

**Comment by t-nelson** [comment]
This is related to keypair path resolution changes introduced in v1.6.7
