### ISSUE TITLE
Can't send my SOL back to my Binance Wallet

### ISSUE THREAD

**Issue by ErmeloBoy78** [solana-labs/solana#17255]
There is a bug in Sollet.io! When I want to send my SOL back to my Binance Wallet I get a error message ...

failed to send transaction: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x1

Some body please help to resolve this damn bug and get My SOL back to my Binance Wallet

**Comment by mvines** [comment]
Sollet support can be found in the project serum discord: https://discord.gg/aAvQFaEB
