### ISSUE TITLE
"solana transfer --from ..." is broken

### ISSUE THREAD

**Issue by da-steve101** [solana-labs/solana#17267]
#### Problem
I was following the intro on creating wallets and created test fs wallets. Successfully created verified and airdropped on two wallets. When transferring I got file not found. strace showed it was trying to access ~/.config/solana/id.json (which didn't exist) even when I added the '--from' argument to my wallet location. Running:

```
5.4.0-72-generic #80-Ubuntu SMP
```

#### Proposed Solution
Fix the --from option for transfers.

**Comment by mvines** [comment]
Unless you specified the `--fee-payer` argument, `~/.config/solana/id.json` will still be used for the transaction fee payer.  Perhaps this is what you're seeing

**Comment by da-steve101** [comment]
Ah yes, that is the case. Perhaps a better error message?
