### ISSUE TITLE
solana-validator monitor output prints sometimes inline, sometimes new lines

### ISSUE THREAD

**Issue by michaelh-laine** [solana-labs/solana#17264]
#### Problem
When I first set up my testnet validator the output of solana-validator --ledger <DIR> monitor was to print newlines for every update (a few per second). I initially thought this was normal, expected behaviour. After a node restart today I noticed it updates the values inline. This is on a non-fullscreen terminal window (Cygwin) on a Windows machine (logged into the validator machine running Ubuntu 20.04 LTS). 

If I maximize the terminal window it is still updating inline. If I then revert to the non-fullscreen window it prints a few new lines of updates (the ones that occured while it was maximized) and revert to posting inline. 

So while maximized it seems to be buffering updates (while still printing them inline too) then printing them out as new lines when reverted. But originally it was doing everything as newlines.

This is obviously a relatively minor cosmetic issue mainly _(although perhaps when maximized and storing the incoming lines into some kind of memory/buffer this is contributing to the slow memory leak reported on the validator? While not 100% clear when I kept the monitor running and checked the memory usage of my validator using pmap PID | tail -1 it would increase every 3-4 seconds, after closing the monitor after a few minutes the usage dropped by 150MB, a few lines of output below)_

```
solana@sun1:~$ pmap 433124 | tail -1
 total         39476880K
solana@sun1:~$ pmap 433124 | tail -1
 total         39476880K
solana@sun1:~$ pmap 433124 | tail -1
 total         39542424K
solana@sun1:~$ pmap 433124 | tail -1
 total         39575196K
solana@sun1:~$ pmap 433124 | tail -1
 total         39575196K
solana@sun1:~$ pmap 433124 | tail -1
total         39575196K          -------------->> STOPPED MONITOR HERE
solana@sun1:~$ pmap 433124 | tail -1
 total         39607968K          -------------->> A FEW SECONDS AFTER STOPPING, IT INCREASED A BIT FURTHER 
solana@sun1:~$ pmap 433124 | tail -1
 total         39457944K          -------------->> ABOUT 5 MINUTES LATER, 150MB drop
solana@sun1:~$ pmap 433124 | tail -1
 total         39490716K          -------------->> ABOUT 10-20 SECONDS LATER, INCREASING AGAIN (MONITOR NOT RUNNING)
```

#### Proposed Solution

Not sure what the fix would be specifically, I assume this is related to the dashboard.rs file in /validator/src/ and the new_spinner_progress_bar() which references the Indicatif ProgressBar in /validator/src/main.rs

One further comment on dashboard.rs:

Is the let progress_bar = new_spinner_progress_bar(); on line 115 necessary, as the same already appears on line 69 in the same scope.

**Comment by michaelh-laine** [comment]
One further comment on dashboard.rs:

Is the let progress_bar = new_spinner_progress_bar(); on line 115 necessary, as the same already appears on line 69 in the same scope.

**Comment by t-nelson** [comment]
This smells like https://github.com/solana-labs/solana/issues/16449

**Comment by michaelh-laine** [comment]
> This smells like https://github.com/solana-labs/solana/issues/16449

Looks related, I did search for new line and monitor but didn't find that one.

However that issue is closed? This issue definitely persists for me in 1.6.9. another validator confirmed on discord that they also reproduced it

**Comment by t-nelson** [comment]
> Looks related, I did search for new line and monitor but didn't find that one.
> 
> However that issue is closed? This issue definitely persists for me in 1.6.9. another validator confirmed on discord that they also reproduced it

The status output for `solana-validator monitor` uses the same crate as the download utils, so I'm assuming the fix will be similar.  That is, ensuring the format string supports variable widths insofar as that's possible.  This specific issue wouldn't have been fixed by the previous PR

I have this on my list to investigate this evening

**Comment by t-nelson** [comment]
@michaelh-laine can you confirm that the line wrapping only occurs if the terminal width is near the `◎` character in the validator balance amount fields of the status output?

**Comment by michaelh-laine** [comment]
> @michaelh-laine can you confirm that the line wrapping only occurs if the terminal width is near the `◎` character in the validator balance amount fields of the status output?

There is no line wrapping, as in the existing single line doesn't wrap into a new line. Rather at first the terminal was continuously printing new lines with all the same information repeated (but updated, i.e. with every update it would print a new line of information), now the behaviour is changed and it stays in a single line, but when I maximize the window then return to windowed mode it prints out all the updates that occurred while the window was maximized into new lines then continues in a single line, so it appears that at least while maximized, perhaps the entire time though, it's storing every update into memory.

Screenshots of the progression below: Start windowed, maximized, then revert to windowed, see the new lines printed.
![solmonitor1](https://user-images.githubusercontent.com/68944931/118608268-cd87e480-b7b9-11eb-9c74-80a15d423817.png)
![solmonitor2](https://user-images.githubusercontent.com/68944931/118608264-cc56b780-b7b9-11eb-8dff-0422dff8280c.png)
![solmonitor3](https://user-images.githubusercontent.com/68944931/118608272-ceb91180-b7b9-11eb-8c2d-af7bbe815a7b.png)

**Comment by t-nelson** [comment]
AFAICT this is not an issue with the validator dashboard, but with the `indicatif` crate. Further, I'm not sure it's resolvable due to the lack of synchronization between the terminal and app on window resize events.

The issue as specified is incorrect.  There is no "buffering" occurring, rather the status line is being printed with a stale, too long line length, which wraps, then the next status update overwrites the wrapped text.
