### ISSUE TITLE
5 arguments in a `msg!` call defaults to converting all arguments to u64

### ISSUE THREAD

**Issue by Henry-E** [solana-labs/solana#17273]
#### Problem

When using 5 arguments in a `msg!` call it defaults to converting all arguments to u64. This leads to compile errors which are hard to debug. The major issue is when passing in arguments that cannot be converted into u64 format.

https://github.com/solana-labs/solana/blob/6705b5a98c076ac08f3991bb8a6f9fcb280bf51e/sdk/program/src/log.rs#L33-L44

#### Proposed Solution

The best would be to remove this default behaviour so that solana developers can have `msg!` calls with 5 arguments, without them needing to all be u64s

 Try to communicate the error more clearly with a better compile error message if a non-u64 convertible argument is used.

**Comment by ryoqun** [comment]
> @ryoqun - hey is there a way in macro land to check if $arg1 is a `&str` and then redirect to avoid using the 5 x `u64` variant?

@mvines Hmm, sorry for late reply. I think it's doable with slight variation from this (https://users.rust-lang.org/t/how-to-check-types-within-macro/33803/5). however, it looks like we're better off removing the special-cased vestigial macro rule, first of all?

**Comment by mvines** [comment]
Fixed by #21752
