### ISSUE TITLE
Unresolved symbols at runtime, using floating point ops from C

### ISSUE THREAD

**Issue by machacekch** [solana-labs/solana#17301]
#### Problem
Changing [the counter increment in the hello world example](https://github.com/solana-labs/example-helloworld/blob/ad52dc719cdc96d45ad8e308e8759abf4792b667/src/program-c/src/helloworld/helloworld.c#L30) to `*num_greets *= 1.5;` fails at runtime. The error given in transaction simulation is:
```Program failed to complete: ELF error: Unresolved symbol (__floatunsidf) at instruction #99 (ELF file offset 0x230)```

1.5 is a double precision literal, equivalent to Rust's f64. It looks like the C compiler uses [floating point emulation](https://gcc.gnu.org/onlinedocs/gccint/Soft-float-library-routines.html).

#### Proposed Solution
Not sure, but using f64 from Rust does work, so hopefully it's just a small toolchain fix.

**Comment by dmakarov** [comment]
We need to add libcompiler-rt.a to bpf-tools and link BPF .so modules compiled from C sources with the library. I will release new bpf-tools and updated Solana SDK with a fix.

**Comment by dmakarov** [comment]
@machacekch Do you have a Rust example with FP operations that works for you?

**Comment by machacekch** [comment]
> @machacekch Do you have a Rust example with FP operations that works for you?

Yes. For example, take the Rust hello world example and [change the equivalent line](https://github.com/solana-labs/example-helloworld/blob/ad52dc719cdc96d45ad8e308e8759abf4792b667/src/program-rust/src/lib.rs#L43) to `greeting_account.counter = (greeting_account.counter as f64 * 1.5) as u32;`. This compiles and runs correctly.

Also, just about every Rust program that calculates the rent exemption threshold does f64 operations, because the factor is a [f64 in the Rent sysvar](https://github.com/solana-labs/solana/blob/22a18a68e3ee68ae013d647e62e12128433d7230/sdk/program/src/rent.rs#L11).
