### ISSUE TITLE
Missing call to get staking accounts by owner

### ISSUE THREAD

**Issue by refi93** [solana-labs/solana#17303]
#### Problem
There seems to be no call to list all staking accounts belonging to an account which makes it cumbersome/non-scalable to do so (deterministic derivation of staking account keys and sequential discovery, querying them one by one being the only option I can think of). I would expect a call similar to [getTokenAccountsByOwner](https://docs.solana.com/developing/clients/jsonrpc-api#gettokenaccountsbyowner)

Solflare's (probably) proprietary API seems to have a call like this to get stake accounts: https://solflare-api.vgng.io/api/v1/devnet/stakes/78dKNk8H9vhRBeQ59Qw5GF2gLwC2R6Y4Zsh1smV6jZTn

Is there perhaps some other publicly available API/Indexer for Solana that would be usable to track staking accounts owned by a public key?

#### Proposed Solution

Add a call similar to solflare's proprietary API to Solana JSON RPC

**Comment by refi93** [comment]
Ok I think I found a viable alternative - getProgramAccounts can be used to query all stake accounts by providing the stake account id and applying a filter to match a fixed offset within the account data at which the stake authority address resides - should be 12 as far as I tried, so something like this returns the raw stake accounts owned by `78dKNk8H9vhRBeQ59Qw5GF2gLwC2R6Y4Zsh1smV6jZTn` public key

```bash
curl https://api.devnet.solana.com -X POST -H "Content-Type: application/json" -d '
  {"method":"getProgramAccounts","jsonrpc":"2.0","params":["Stake11111111111111111111111111111111111111",{"encoding":"base64","commitment":"singleGossip","filters":[{"memcmp":{"bytes":"78dKNk8H9vhRBeQ59Qw5GF2gLwC2R6Y4Zsh1smV6jZTn","offset":12}}]}],"id":"24cb0485-a59c-441f-843d-56b94151eb68"}
```

Is this approach correct? Are there any pitfalls I should be aware of?

**Comment by CriesofCarrots** [comment]
@refi93 Yes, your filters approach is spot on. This is exactly what `getTokenAccountsByOwner` does under the hood.

The only potential pitfall is that `getProgramAccounts` does a full accounts scan, which can be slow given that we have 60mill+ accounts. That rpc endpoint is really only viable against nodes that are using secondary account indexes, like our public rpc nodes are: https://docs.solana.com/running-validator/validator-start#account-indexing

Also, a nit: `"commitment":"singleGossip"` is deprecated; use `"commitment":"confirmed"` instead.

**Comment by refi93** [comment]
I see, thanks for clarifying! If I understood correctly from the link attached, the accounts index indexes by the program id `Stake11111111111111111111111111111111111111` but doesn't have a "full text" index to search the offsets, so getting stake accounts that way would still require a full scan over all staking accounts - correct? Are there any plans to add indexing by offset in the foreseeable future?

**Comment by CriesofCarrots** [comment]
> so getting stake accounts for a specific stake authority that way would still require a full scan over all stake accounts - correct?

Not quite. Getting stake accounts for a specific stake authority would require a scan over just the accounts owned by the stake program id. There aren't all that many stake accounts, so this scan should be pretty fast.

However, we do have a plan for the future to add a runtime hook into accounts/account updates so that users could implement their own targeted indexing and business logic, like indexing by stake-authority for instance.
