### ISSUE TITLE
[CLI] How to add MINT contract?

### ISSUE THREAD

**Issue by clintnetwork** [solana-labs/solana#17313]
Hey,

Do you have any kind of documentation to add contract with CLI wallet?

And is it possible to export private key too? I tried to use decimal to hex online tool but not works

Thanks

**Comment by CriesofCarrots** [comment]
> Do you have any kind of documentation to add contract with CLI wallet?

If you are asking how to mint your own token, you can use the `spl-token-cli`. There is some documentation for that tool here: https://spl.solana.com/token#example-creating-your-own-fungible-token

> And is it possible to export private key too? I tried to use decimal to hex online tool but not works

Can you be more specific about what you are trying to accomplish?

**Comment by clintnetwork** [comment]
Oh okay, no I guess that to add one new token to our address, we should add this contract to our address, is it right? I wanted to do this with the cli-wallet!

And for the second question, I would like to export my current private key (in `~/.config/solana/id.json`)

Thank you!

**Comment by CriesofCarrots** [comment]
> Oh okay, no I guess that to add one new token to our address, we should add this contract to our address, is it right? I wanted to do this with the cli-wallet!

Oh okay, I think you mean you want to add an existing token to an existing wallet? If so, that is also possible via the `spl-token-cli`:
```
spl-token create-account <MINT_ADDRESS>
```

> I would like to export my current private key (in `~/.config/solana/id.json`)

Export it to where or for what?
If you inspect that file, you will see a json representation of an array of 64 bytes. The first 32 are the private key, and the last 32 are the public key.

**Comment by clintnetwork** [comment]
Oh okay perfect, I though the total array was the private key :)

**Comment by clintnetwork** [comment]
Just one last question @CriesofCarrots, my public key is `4WkbegHcJbMBjxYvB5QUrrTPWDzbVYA3M1UMyjDHFBoo` its 44 characters and not 32, do you have any documentation or link that can help me?

**Comment by CriesofCarrots** [comment]
> Just one last question @CriesofCarrots, my public key is `4WkbegHcJbMBjxYvB5QUrrTPWDzbVYA3M1UMyjDHFBoo` its 44 characters and not 32, do you have any documentation or link that can help me?

That looks right. Public keys are 32 bytes. Pubkey strings are base-58-encoded; the result is a string that is anywhere between 32 and 44 characters long. Most ed25519 pubkeys end up 43 or 44 characters in base 58.
