### ISSUE TITLE
Improve CLI's error for small buffer for upgradeable program deploy

### ISSUE THREAD

**Issue by ryoqun** [solana-labs/solana#17329]
#### Problem

`solana program deploy`'s progress bar could be stuck as loading or sending transactions indefinitely for no obvious reason. This is reported by users.

The root cause is that insufficient buffer for the newly deployed program binary.

#### Proposed Solution

Improve messages. Maybe check the buffer size against new program size?

**Comment by jackcmay** [comment]
@ryoqun Can you provide more details on what "insufficient buffer" means?

**Comment by firememory** [comment]
we deploy failed first time, cli return an buffer key, and then  dev found need change some code (one line), rebuild and try deploy again use the buffer key and meet this problem.

**Comment by jackcmay** [comment]
@firememory Can you provide more detail on what line needed to be changed and why?

**Comment by firememory** [comment]
we change our smart contract code and rebuild, the "so" file size increased( about 300 byte).  we use old buffer to upgrade(deploy) program and then cause the problem. we forget  we change the "so" file size.  this is not your program problem. but we stuck when deploying, so if having a  tip  is good ideal.

**Comment by jackcmay** [comment]
@firememory Can you provide more detail on what line needed to be changed and why?

**Comment by jackcmay** [comment]
When deploying a new buffer is created, populated, and then drained which should dtor it.  Every upgrade should do the same thing.  When you say you use the old buffer what did you mean?

**Comment by jackcmay** [comment]
@firememory were you explicitly passing the orignal buffer to the deploy command, and that buffer was the size of the original and smaller .so?
