### ISSUE TITLE
how to use solana CLI restore sollet.io wallet?

### ISSUE THREAD

**Issue by lly835** [solana-labs/solana#17380]
#### Problem
i create new wallet in sollet.io  
how to use solana CLI restore sollet.io wallet and get address?

**Comment by jon-chuang** [comment]
You need to have taken down the mnemonic phrase. You could then use the cli to generate a file system wallet with the keypair derived from the phrase stored on your device.

**Comment by lly835** [comment]
different address.  use solana CLI restore sollet.io mnemonic phrase and sollet.io website address

**Comment by lly835** [comment]
i have one hundred sollet.io wallets.  i want to use solana CLI transfer amount

**Comment by t-nelson** [comment]
Please don't use Github for user support.  Join our Discord server and post in #wallet-support instead.

https://solana.com/discord
