### ISSUE TITLE
illegal hardware instruction  solana-test-validator

### ISSUE THREAD

**Issue by astronaute77** [solana-labs/solana#17406]
#### Problem
```
$ solana-test-validator
Ledger location: test-ledger
Log: test-ledger/validator.log
 
[1]    35955 illegal hardware instruction  solana-test-validator
```

```
$ solana --version
solana-cli 1.6.9 (src:9e42883d; feat:2960423209)
```

I’m on MacOS M1 and suspect there are some issues with it.
I had to link openssl to /usr/local/opt/openssl@1.1 before even being able to run it.

Any clues?

**Comment by jon-chuang** [comment]
I'm just wondering if it's because their BPF compiler can only compile to x64. On the other hand, I think it's perfectly capable of running in interpreter mode.

**Comment by mvines** [comment]
It's not BPF related.  The M1 emulation doesn't feature AVX instructions, but you can recompile from source for M1 once Rosetta is installed apparently. Details in the README, search for "M1"

**Comment by astronaute77** [comment]
> It's not BPF related. The M1 emulation doesn't feature AVX instructions, but you can recompile from source for M1 once Rosetta is installed apparently. Details in the README, search for "M1"

I actually tried compiling everything from source, with my terminal in rosetta mode, as well as my brew and my Rust etc. I’m on `x86_64-apple-darwin` for sure, validated from Rust itself.

It’s worth noting that using the official release 1.6.9, `solana` works (it gives me the version) but `solana-test-validator` doesn’t.
If I compile 1.6.9 from source, neither of them works (illegal hardware instruction), which is weird.

if I run `./run.sh` in the cloned main repo, it launches the cluster. So there is definitely something wrong with the 1.6.9 release itself.

**Comment by interdailytop19** [comment]
i got the same illegal hardware instruction error after installed Rosetta, closed that issue it duplicated

**Comment by t-nelson** [comment]
As mentioned [above](https://github.com/solana-labs/solana/issues/17406#issuecomment-846436731), the solution here is to build from source under Rosetta

**Comment by crispheaney** [comment]
If you're building from source and you hit: 
```
failed to run custom build command for `openssl-sys v0.9.57`
```

You need to install openssl (which is contingent on you [installing](https://5balloons.info/correct-way-to-install-and-use-homebrew-on-m1-macs/) brew correctly):
```
 brew install openssl
```

**Comment by dabit3** [comment]
Have tried a few versions on M1, including the most recent `v1.7.11`, still getting:

```35955 illegal hardware instruction  solana-test-validator```

Only way I can get the validator to run locally is to build from source, then run `./run.sh`.

**Comment by entergmode** [comment]
I built from source and hit this,

```
  = note: ld: warning: directory not found for option '-L/opt/homebrew/opt/openssl@1.1/lib'
          ld: library not found for -lssl
          clang: error: linker command failed with exit code 1 (use -v to see invocation)


error: build failed
```

Any idea please?

**Comment by dabit3** [comment]
@entergmode have you tried `brew install openssl`?

**Comment by swaroopmaddu** [comment]
For Mac with M1 chip follow this guide [Solana installation on MacBook M1](https://medium.com/@madduswaroop/solana-installation-in-macbook-m1-b08582d50db1)
