### ISSUE TITLE
extra entry found: "accounts/GNUSparseFile.0:  "Load from snapshot failed: UnpackError" issue with solana-test-validator

### ISSUE THREAD

**Issue by secretshardul** [solana-labs/solana#17424]
# Problem

I want `solana-test-validator` to preserve my transaction history. The command runs for the first time, but not when it is stopped with `ctrl+C` and restarted. Sometimes the running validator randomly goes off. I'm unable to restart the validator without deleting `test-ledger` folder, but this removes my testing history. Here are the logs:

## Terminal error

```
(base) user@user my_folder % solana-test-validator
Ledger location: test-ledger
Log: test-ledger/validator.log
```

## Logs inside test-ledger/validator.log

```
[2021-05-24T06:23:57.848220000Z INFO  solana_faucet::faucet] Faucet started. Listening on: 0.0.0.0:9900
[2021-05-24T06:23:57.848342000Z INFO  solana_faucet::faucet] Faucet account address: FVTsw8PpizT87dmwFqv4z5uRfmC7TrrthGL9JtvsFkJs
[2021-05-24T06:23:57.852318000Z WARN  solana_core::validator] identity: B4A5NYxNdVMdxTMjEoFk3FfbDKqezfioDH8S6GjJEYuQ
[2021-05-24T06:23:57.852365000Z WARN  solana_core::validator] vote account: H9uSkxhNm6nX2H59py5xMNgegbbkVmF9bhrsdAk6GkJM
[2021-05-24T06:23:57.852388000Z WARN  solana_core::validator] authorized voter: H9uSkxhNm6nX2H59py5xMNgegbbkVmF9bhrsdAk6GkJM
[2021-05-24T06:23:57.852413000Z WARN  solana_core::validator] CUDA is disabled
[2021-05-24T06:23:57.852426000Z INFO  solana_core::validator] AVX detected
[2021-05-24T06:23:57.852438000Z INFO  solana_core::validator] Initializing sigverify...
[2021-05-24T06:23:57.852451000Z INFO  solana_core::validator] Done.
[2021-05-24T06:23:57.852480000Z INFO  solana_core::validator] Cleaning accounts paths..
[2021-05-24T06:23:57.992619000Z INFO  solana_core::validator] done. clean_accounts_paths took 140ms
[2021-05-24T06:23:57.992667000Z INFO  solana_core::validator] loading ledger from "test-ledger"...
[2021-05-24T06:23:57.998259000Z INFO  solana_core::validator] genesis hash: 27MQi1z2AFKpxrWSpkYtAmV3SrtktzJTRLetpCKF6o4w
[2021-05-24T06:23:57.998378000Z INFO  solana_ledger::blockstore] Maximum open file descriptors: 500000
[2021-05-24T06:23:57.998392000Z INFO  solana_ledger::blockstore] Opening database at "test-ledger/rocksdb"
[2021-05-24T06:23:58.241337000Z INFO  solana_ledger::blockstore] "test-ledger/rocksdb" open took 242ms
[2021-05-24T06:23:58.243967000Z INFO  solana_ledger::bank_forks_utils] Initializing snapshot path: "test-ledger/snapshot"
[2021-05-24T06:23:58.245941000Z INFO  solana_ledger::bank_forks_utils] Loading snapshot package: "test-ledger/snapshot-100-GMvMv3gjfSU7aH8vfMxtEtkmz1bNiEsmDmVMwCA2Uaqp.tar"
thread 'main' panicked at 'Load from snapshot failed: UnpackError(Archive("extra entry found: \"accounts/GNUSparseFile.0/100.102\" Regular"))', ledger/src/bank_forks_utils.rs:75:18
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::option::expect_none_failed
   3: solana_ledger::bank_forks_utils::load
   4: solana_core::validator::new_banks_from_ledger
   5: solana_core::validator::Validator::new
   6: solana_core::test_validator::TestValidator::start
   7: solana_core::test_validator::TestValidatorGenesis::start_with_mint_address
   8: solana_test_validator::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**test-ledger folder**: https://drive.google.com/drive/folders/1ke0-oSxLJFS5gCQdweU-Z_m_L9-Mx3ht?usp=sharing

## Environment

- Intel MacOS Catalina
- `solana-cli 1.6.9 (src:9e42883d; feat:2960423209)`
- `solana-test-validator 1.6.9 (src:9e42883d; feat:2960423209)`

Edit: Updated to v1.6.9 but issue persists.

**Comment by mvines** [comment]
Here's the error:
```
UnpackError(Archive("extra entry found: \"accounts/GNUSparseFile.0/100.102\" Regular"))'
```
I've seen this error reported before once by a user.

**Comment by mvines** [comment]
Pretty sure this has to do with the version of `tar` that's being used to generate the snapshot.  It's creating `GNUSparseFile` files in the archive that we're rejecting on snapshot unpacking

**Comment by mvines** [comment]
@secretshardul - does this reproduce for you consistently?  

What does `tar --version` output for you?

**Comment by secretshardul** [comment]
> @secretshardul - does this reproduce for you consistently?

Yes, it keeps happening. Happened just now.

![image](https://user-images.githubusercontent.com/49580849/119377623-f4bf4400-bcda-11eb-88f1-35b2486eee30.png)


> What does `tar --version` output for you?

Running `tar --version` gives:

```
bsdtar 3.3.2 - libarchive 3.3.2 zlib/1.2.11 liblzma/5.0.5 bz2lib/1.0.6
```

**Comment by mvines** [comment]
Interesting, do you not using APFS as your filesystem?  Here's what my MBP looks like and I can't seem to repro this issue:
```
$ mount | column -t
/dev/disk1s1        on         /                     (apfs,                     local,      read-only,    journaled)
devfs               on         /dev                  (devfs,                    local,      nobrowse)
/dev/disk1s2        on         /System/Volumes/Data  (apfs,                     local,      journaled,    nobrowse)
/dev/disk1s5        on         /private/var/vm       (apfs,                     local,      journaled,    nobrowse)
map                 auto_home  on                    /System/Volumes/Data/home  (autofs,    automounted,  nobrowse)
kbfs@kbfuse0        on         /Volumes/Keybase      (mvines)                   (kbfuse,    nodev,        nosuid,     synchronous,  mounted  by  mvines)
keybase-redirector  on         /Volumes/Keybase      (kbfuse,                   read-only,  synchronous,  nobrowse)
/dev/disk1s4        on         /Volumes/Recovery     (apfs,                     local,      journaled,    nobrowse)
```

**Comment by secretshardul** [comment]
MacOS and the drive holding the ledger folder runs on APFS.

```
(base) hp@MacBook-Pro cyclos_program % mount | column -t
/dev/disk1s5                                                  on         /                                                                                                               (apfs,                     local,         read-only,    journaled)
devfs                                                         on         /dev                                                                                                            (devfs,                    local,         nobrowse)
/dev/disk1s1                                                  on         /System/Volumes/Data                                                                                            (apfs,                     local,         journaled,    nobrowse)
/dev/disk1s4                                                  on         /private/var/vm                                                                                                 (apfs,                     local,         journaled,    nobrowse)
map                                                           auto_home  on                                                                                                              /System/Volumes/Data/home  (autofs,       automounted,  nobrowse)
/dev/disk0s3                                                  on         /Volumes/Untitled                                                                                               (ntfs,                     local,         read-only,    noowners)
/dev/disk0s4                                                  on         /Volumes/ShareDrive                                                                                             (exfat,                    asynchronous,  local,        noowners)
/System/Library/StartupItems/RalinkUtility/AwakeDWA160UI.app  on         /private/var/folders/yt/s6svfxl52mj1qfjvp5z_x9rc0000gn/T/AppTranslocation/1A3C560C-79DB-4DC1-9CE3-71BB01A4AF61  (nullfs,                   local,         nodev,        nosuid,     read-only,  nobrowse,  mounted  by  hp)
```

**Comment by mvines** [comment]
Ok and your definitely not running on those NFS or FAT drives. 🤔 strange

**Comment by secretshardul** [comment]
I'll try [gnu-tar](https://formulae.brew.sh/formula/gnu-tar) on my side and see if the issue persists.

**Comment by mvines** [comment]
I can't repro here with either bsdtar (same version as yours) or gnu tar.  Can you attach the snapshot -*.tar file from your test-ledger/ after this reproduces

**Comment by secretshardul** [comment]
Yep, i'll get back tomorrow if issue returns

**Comment by t-nelson** [comment]
Odd. I thought we added accepts for `GNUSparse` on all file entries :think

**Comment by mvines** [comment]
> Odd. I thought we added accepts for `GNUSparse` on all file entries :think

Na, this is different.  It's not the `GNUSparse` attribute, some tar is literally creating filenames with `GNUSparseFile.0` in them.  Some details at https://www.gnu.org/software/tar/manual/html_node/Sparse-Recovery.html

**Comment by secretshardul** [comment]
Crashes stopped after migrating to GNU tar. The default tar tool could've been bugged. I'll update the thread if the issue returns.

**Comment by vicyyn** [comment]
I still get this error even after migrating to gnu-tar
`Ledger location: test-ledger
Log: test-ledger/validator.log
⠉ Initializing...
Illegal instruction: 4`

Logs
`[2021-07-24T14:12:37.842411000Z INFO  solana_faucet::faucet] Faucet started. Listening on: 0.0.0.0:9900
[2021-07-24T14:12:37.842693000Z INFO  solana_faucet::faucet] Faucet account address: 8qgCAn6E1nXvELUao6w7mS7HeqHEe9JQDggBr7mdKaAQ
[2021-07-24T14:12:37.854244000Z INFO  solana_ledger::blockstore] Maximum open file descriptors: 500000
[2021-07-24T14:12:37.854253000Z INFO  solana_ledger::blockstore] Opening database at "test-ledger/rocksdb"
[2021-07-24T14:12:38.047792000Z INFO  solana_ledger::blockstore] "test-ledger/rocksdb" open took 193ms
`

**Comment by t-nelson** [comment]
> I still get this error even after migrating to gnu-tar
> 
> ```
> Log: test-ledger/validator.log
> ⠉ Initializing...
> Illegal instruction: 4
> 
> Logs
> [2021-07-24T14:12:37.842411000Z INFO  solana_faucet::faucet] Faucet started. Listening on: 0.0.0.0:9900
> [2021-07-24T14:12:37.842693000Z INFO  solana_faucet::faucet] Faucet account address: 8qgCAn6E1nXvELUao6w7mS7HeqHEe9JQDggBr7mdKaAQ
> [2021-07-24T14:12:37.854244000Z INFO  solana_ledger::blockstore] Maximum open file descriptors: 500000
> [2021-07-24T14:12:37.854253000Z INFO  solana_ledger::blockstore] Opening database at "test-ledger/rocksdb"
> [2021-07-24T14:12:38.047792000Z INFO  solana_ledger::blockstore] "test-ledger/rocksdb" open took 193ms
> ```

This is unrelated.  Please open a new issue
