### ISSUE TITLE
Improve `solana program deploy` error messag when default keypair does not exist

### ISSUE THREAD

**Issue by LucasBruder** [solana-labs/solana#17423]
#### Problem

Using the Anchor project Dockerfile as a template to download solana onto my server.

Given I download version v1.6.9,
when I compile my contract and attempt to deploy it to a local testnet by calling `solana program deploy <path>`
then I get os error 2.

This works in v1.6.6

v1.6.9
```
$ solana program deploy /path/to/shared_object.so
Error: Dynamic program error: No such file or directory (os error 2)
$ solana --version
solana-cli 1.6.9 (src:9e42883d; feat:2960423209)
$ anchor --version
anchor-cli 0.6.0
$ solana program deploy
Error: Dynamic program error: No such file or directory (os error 2)
```

v1.6.6
```
$ solana program deploy /path/to/shared_object.so
Program Id: 9A7oBfLrXY8QACcBP4CBzu2Z52eqULMT8cvA5KVnqMW
$ solana --version
solana-cli 1.6.6 (src:fe775a97; feat:3714435735)
$ anchor --version
anchor-cli 0.6.0
$ solana program deploy
Error: Program location required if buffer not supplied
```

#### Proposed Solution
Revert the changes made on this subcommand in between v1.6.6 and v1.6.9

**Comment by mvines** [comment]
Reproduces with:
```
$ mv ~/.config/solana/{,not-}id.json 
$ solana program deploy
Error: Dynamic program error: No such file or directory (os error 2)
```

Workaround, run:
```
$ solana-keygen new`
```


Perhaps we should just have a generic error whenever any cli command is run without a default keypair, to force the user to create one before continuing and avoid having to handle the lack of a default keypair in every single cli subcommand cleanly
