### ISSUE TITLE
TVU does not verify PoH

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#1745]
#### Problem
validators do not verify that Entries are linked with PoH

#### Proposed Solution
add PoH verification to replicate_stage, initially with CPU, but later with GPU or enclave

**Comment by rob-solana** [comment]
Sagar, can you please add tests on top of #1746?

**Comment by sagar-solana** [comment]
Oops just saw this. I'll add tests.

**Comment by sagar-solana** [comment]
@rajgokal, why'd you reopen this?
