### ISSUE TITLE
[spl-token] Can't mint the token via cross-program invocation

### ISSUE THREAD

**Issue by sham789** [solana-labs/solana#17480]
#### Problem

I'm trying to process a token mint via cross-program invocation. The result I get is `Error: Transaction simulation failed: Error processing Instruction 0: Program failed to complete`. What must be the exact input parameters for `mint_to_checked` instruction? Crate docs do not provide detailed info. Also, may be I need to use `invoke_signed` not `invoke`? 

https://github.com/Gravity-Tech/solana-adapter/blob/b33642a0bce7fff1cf53d8fdac6f134b39e4e514/src/gravity-core-adapter/port/src/ibport/processor.rs#L267-L281

**Comment by t-nelson** [comment]
I see you have found our Discord server.  Github is not suitable for support requests.  Please use Discord in the future
