### ISSUE TITLE
solana-keygen recover  how to use /m/44/501/0/0

### ISSUE THREAD

**Issue by AaronSmart** [solana-labs/solana#17498]
#### Problem
i use the same Mnemonic words but generate different public key address ,in sollet.io HD path is /m/44/501/0/0
solana-keygen recover  how to specify  /m/44/501/0/0 

The recently added ask: signer-source with bip32 support (v1.6.7) renamed to prompt:. With no query string, prompt: derives the solana bip44 base key, m/44'/501'

**Comment by CriesofCarrots** [comment]
The command you need is: `solana-keygen recover prompt://?key=0/0`
Docs: https://docs.solana.com/wallet-guide/paper-wallet#hierarchical-derivation

Also, github is not great for support; please use our Discord server for this in the future.
