### ISSUE TITLE
web3 / json-rpc: accountNotification always fetches full account data

### ISSUE THREAD

**Issue by etodanik** [solana-labs/solana#17496]
Currently when interfacing with Solana via a web3 json-rpc and subscribing to an account, the full account data gets sent on every update.

This can get very bandwidth intensive for large accounts (e.g. Serum's event queue which sends 1MB worth of data on every account change).

If the websocket interface had the ability to send one initial message with the full account data, and then switch to incremental diff sending, both response time and bandwidth would be greatly shortened.

**Comment by leonardgee** [comment]
This is a great idea.
