### ISSUE TITLE
Unnecessary BPF verifier restriction on `MUL64_IMM`

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#17520]
#### Problem

The BPF verifier enforces a non-zero imm for the `MUL64_IMM` instruction when it doesn't need to here: https://github.com/solana-labs/solana/blob/6b9d8d41a3fd32a069812bf0ec7d6a392414d874/programs/bpf_loader/src/bpf_verifier.rs#L228

#### Proposed Solution

Featurize and remove this restriction

**Comment by Lichtso** [comment]
https://github.com/solana-labs/rbpf/pull/201

**Comment by Lichtso** [comment]
Ready for feature gating as of #18869.
I marked the relevant line in the config with a `TODO` comment.

Do you want to add the feature flag or should I?

**Comment by jackcmay** [comment]
As we discussed you are going to add it next week, thanks!
