### ISSUE TITLE
Solana Wallet Stuck

### ISSUE THREAD

**Issue by Jajkanu** [solana-labs/solana#17555]
#### Problem

My solana wallet address AxGdz3aVAwrq6NWm6WsYriTwZYptWZMjJEEQsV8Xfgw9 and it hasnt got any SOL but it has USDT and SLM tokens. 

When I want to recieve SOL to the this address or send USDT to another solana address transection is generated by wallets (sollet, solang, gate.io, etc) the transection not founded on solana explorer 

For eg: 4Tkf9orCSVEjGLXBJpYPir2Z6vEW4RmnEkYqoGnuFcwtANPgo823hNBHs8bvqBgD6Kwwavov8JAQjTMAxMBY158u is gererated by gate.io but in the solana exporer shows nothing.

https://explorer.solana.com/tx/4Tkf9orCSVEjGLXBJpYPir2Z6vEW4RmnEkYqoGnuFcwtANPgo823hNBHs8bvqBgD6Kwwavov8JAQjTMAxMBY158u

**Comment by t-nelson** [comment]
Github is not for support requests.  Please visit our Discord server and ask in #wallet-support. https://solana.com/discord
