### ISSUE TITLE
explorer: Display of pubkeys for Serum's ConsumeEvents instructions doesn't match Solanabeach

### ISSUE THREAD

**Issue by ghost** [solana-labs/solana#17598]
#### Problem

- The information shown on the official Solana explorer for Serum's ConsumeEvents instructions does not match what is on Solanabeach.io.
- SolanaBeach is showing pubkey fields for `Coin Fee` and `Pc Fee`, whereas the similiar instruction shown in the Solana Explorer lacks those fields, and instead mixes up the pubkeys.
- Solanabeach: https://solanabeach.io/transaction/2zqw8uHUFxVAFj6Uz6eQzotJyuBZs1dcTY57mbX46r5qsdmfxjMxEtWwSDjij5XWMJtB94MZLTdVRWZDcJJPHet5
- Official explorer: https://explorer.solana.com/tx/2zqw8uHUFxVAFj6Uz6eQzotJyuBZs1dcTY57mbX46r5qsdmfxjMxEtWwSDjij5XWMJtB94MZLTdVRWZDcJJPHet5
- Market ID: 9wFFyRfZBsuAha4YcuxcXLKwMxJR43S7fPfQLusDBzvT

![image](https://user-images.githubusercontent.com/67430414/120086864-8a6e2100-c097-11eb-987a-c17650497452.png)
![image](https://user-images.githubusercontent.com/67430414/120086868-935ef280-c097-11eb-96bc-785335274a55.png)

#### Proposed Solution
Fix Consume Events rendering in the explorer so it matches this contract: https://github.com/project-serum/serum-dex/blob/480cfefdbd7789c1fa2ac4474c6456b507f9a78f/dex/src/instruction.rs#L353-L358

> /// ... `[writable]` OpenOrders
/// accounts.len() - 4 `[writable]` market
/// accounts.len() - 3 `[writable]` event queue
/// accounts.len() - 2 `[writable]` coin fee receivable account
/// accounts.len() - 1 `[writable]` pc fee receivable account
ConsumeEvents(u16),

**Comment by ngundotra** [comment]
Stale
