### ISSUE TITLE
illegal hardware instruction (core dumped) solana-test-validator on Linux Mint 20.1 based on Ubuntu 20.04

### ISSUE THREAD

**Issue by AuroraLantean** [solana-labs/solana#17599]
#### Problem
I cannot run solana-test-validator... here is what I tried:
$ solana-test-validator
... Ledger location: test-ledger
Log: test-ledger/validator.log
⠠ Initializing...
[1]    29233 illegal hardware instruction (core dumped)  solana-test-validator

#### Proposed Solution
Hi I have searched on Google and it seems my CPU Intel i3-3220 is too old... 

#### Question2. How to check which CPU can run Solana?
My current CPU Intel i3-3220:
https://ark.intel.com/content/www/us/en/ark/products/65693/intel-core-i3-3220-processor-3m-cache-3-30-ghz.html
quote "Instruction Set Extensions Intel® SSE4.1, Intel® SSE4.2, Intel® AVX"
and from my terminal $ more /proc/cpuinfo | grep flags
... then it showed avx CPU feature, but no avx2 ... 
You can see this CPU does have AVX feature ... but still cannot run solana-test-validator... why?

Here is another CPU I found online with AVX2: Intel i3-4130
From https://ark.intel.com/content/www/us/en/ark/products/77480/intel-core-i3-4130-processor-3m-cache-3-40-ghz.html
quote " Instruction Set Extensions Intel® SSE4.1, Intel® SSE4.2, Intel® AVX2"
You can see this  i3-4130 has AVX2 feature. So this mean this CPU can run solana-test-validator?

#### Question3. How can I overcome this problem using an AVX CPU like my current CPU i3-3220?
From some Google search... it seems I need to install tensorflow v1.5 via Python...
https://stackoverflow.com/questions/49094597/illegal-instruction-core-dumped-after-running-import-tensorflow
https://tech.amikelive.com/node-887/how-to-resolve-error-illegal-instruction-core-dumped-when-running-import-tensorflow-in-a-python-program/
... then this becomes extremely complicated process and I have tried them all but still cannot get solana-test-validator to work... I tried:

#### Install the released version
https://docs.solana.com/cli/install-solana-cli-tools
navigate to https://github.com/solana-labs/solana/releases/latest
and download the Source Code archive.

What is the missing step? Please help! Thank you

**Comment by AuroraLantean** [comment]
Ok I solved it by building from source:
https://docs.solana.com/cli/install-solana-cli-tools#build-from-source 
$ git clone https://github.com/solana-labs/solana.git solanaRepo
$ cd solanaRepo

$ git fetch --all --tags
$ git checkout tags/v1.7.1 -b v171
$ ./scripts/cargo-install-all.sh .
$ export PATH=$PWD/bin:$PATH
$ solana-install init v1.7.1

$ solana-test-validator

**Comment by bitcard** [comment]
> Ok I solved it by building from source with my CPU Intel i3-3220, which has AVX support
> reference: https://docs.solana.com/cli/install-solana-cli-tools#build-from-source
> $ git clone https://github.com/solana-labs/solana.git solanaRepo
> $ cd solanaRepo
> 
> $ git fetch --all --tags
> $ git checkout tags/v1.7.1 -b v171
> $ ./scripts/cargo-install-all.sh .
> $ export PATH=$PWD/bin:$PATH
> $ solana-install init v1.7.1
> 
> $ solana-test-validator

This 1.7.1 version is ok, supporting without AVX2, why version 1.7.11 not support no AVX2 CPU?

**Comment by sasicodes** [comment]
@AuroraLantean 

```
 solana-install init v1.7.1
```

![image](https://user-images.githubusercontent.com/29498872/144044009-0e802112-2345-4a5b-94bc-8ce0ad704ef3.png)
