### ISSUE TITLE
latest solanda download, report macOS and Windows binary release artifacts are missing

### ISSUE THREAD

**Issue by xiaods** [solana-labs/solana#17600]
#### Problem
macOS and Windows binary release artifacts are missing
Mainnet - v1.6.10

#### Proposed Solution
add macOS and windows release

**Comment by mvines** [comment]
This is documented as a known issue with 1.6.10. Please use 1.6.9 until 1.6.11 ships or build from source

**Comment by xiaods** [comment]
@mvines thanks for your reminder
