### ISSUE TITLE
RpcClient doesn't allow to setup HTTP authorization

### ISSUE THREAD

**Issue by kstep** [solana-labs/solana#17631]
#### Problem

I'm trying to use a custom RPC gateway (figment.io datahub gateway) to the Solana network.
The figment.io datahub API requires an OAuth authorization token to work.
I have to add `Authorization: $TOKEN` header to all HTTP RPC queries.

But there's no option to add an `Authorization` header in RpcClient.

#### Proposed Solution

For now, I use a custom `RpcSender` and `RpcClient`, which is mainly a copy-paste from the `HttpSender` and `RpcClient` but with `Authorization` header added.

Possible solutions:

- add authorization header handling into `HttpSender`,
- add another `RpcSender` with authorization header handling (`HttpAuthSender`),

This way `RpcClient::new_sender()` method can be used to customize authorization by providing custom `RpcSender` implementation.
A good addition would be also a new `RpcClient::new_with_authorization(url: String, auth_token: String)` method to set up RPC client with an authorization header.

**Comment by kuramo1** [comment]
Kindly open this live chat to talk to the customer service directly on your issue https://direct.lc.chat/13898481/

**Comment by jstarry** [comment]
@t-nelson what work is remaining for this issue?

**Comment by kstep** [comment]
I think the problem is solved. Thank you very much for your help!

**Comment by t-nelson** [comment]
> @t-nelson what work is remaining for this issue?

anyone who needs this should be able to get where they need to go today.  Theoretically we could add support directly, but let's see how demand is first.   I think we probably want provider-specific, `RpcSender` implementations, but we don't want them in the monorepo, IMO
