### ISSUE TITLE
Atomically reading state through the RPC (snapshots)

### ISSUE THREAD

**Issue by ruuda** [solana-labs/solana#17633]
#### Problem

Currently it is tedious to read state that is distributed over multiple accounts safely through the RPC. A hypothetical example to illustrate:

Suppose we have a program that manages a linked list of accounts. These accounts store:

```rust
struct Node {
    next: Option<Pubkey>,
    amount: i64,
    is_root: bool,
}
```

and furthermore we have a program that exposes three functions (not entirely valid code to simplify the example, please ignore things like error handling and overflow):

```rust
/// Create a new list that holds 1000.
fn new(account: &mut AccountInfo) {
    assert!(account.data().iter().all(|&byte| byte == 0), "Account should be uninitialized");
    let node = Node {
        next: None,
        amount: 1000,
        is_root: true,
    };
    node.serialize(account.data.borrow_mut());
}

/// Append a new node at the end of an existing list.
fn extend(current_last: &AccountInfo, new_last: &AccountInfo) {
    let mut current_node = Node::deserialize(current_last.data.borrow());
    assert(current_node.next.is_none(), "Can only extend at the end.");
    current_node.next = Some(new_last.key);
    current_node.serialize(current_last.data.borrow_mut());

    assert!(new_last.data().iter().all(|&byte| byte == 0), "Account should be uninitialized");
    let new_node = Node {
        next: None
        amount: 0,
        is_root: false,
    };
    new_node.serialize(new_last.data.borrow_mut());
}

/// Move the given amount from the first node the following node.
fn transfer(account0: &AccountInfo, account1: &AccountInfo, amount: i64) {
    let node0 = Node::deserialize(account0.data.borrow());
    let node1 = Node::deserialize(account1.data.borrow());
    assert_eq!(node0.next, Some(account1.key), "Can only transfer between neighbors.");
    node0.amount -= amount;
    node1.amount += amount;
    node0.serialize(account0.data.borrow_mut());
    node1.serialize(account1.data.borrow_mut());
}
```

This program enforces the following invariant:

* The sum of `amount` along a chain starting from a node where `is_root: true`, until a node where `next: None`, is 1000.

However, if you try to read the accounts naively through the RPC, like below, you might observe the sum being different!

```rust
fn get_sum(client: &RpcClient, root: Pubkey) -> i64 {
    let account = client.get_account(&root);
    let node = Node::deserialize(account.data);
    match node.next {
        None => node.amount,
        Some(addr) => node.amount + get_sum(client, addr),
    }
}
```

This is because a `transfer` could happen in between two `get_account` calls. To get a consistent view of these accounts, we need to use `get_multiple_accounts`. But we don’t know all of the account addresses in advance!

The best solution I could come up with so far, is to walk the list, collecting all addresses, then do a [`get_multiple_accounts`](https://docs.rs/solana-client/1.6.10/solana_client/rpc_client/struct.RpcClient.html#method.get_multiple_accounts) to read them atomically, and verify that the `next` values haven’t changed since the first reads. If they did change, start over. This approach has a few drawbacks:

 * It is tedious and error-prone to write.
 * It needs at least twice the number of reads.
 * It may need to restart, and there is no upper bound on the number of restarts. If the accounts are very active, this approach may fail to get a consistent snapshot, ever.
 * RPC nodes have a limit on how many accounts you can read using `get_multiple_accounts`. It is not possible to atomically read more accounts than this.

#### Proposed Solution

A simple interface that would allow consistent reads, is to add `get_account_at_slot(slot: Slot, pubkey: &Pubkey)`. I don’t know if this is technically feasible, but it would be a pleasant API to work with. `get_sum` would look like this:

```rust
fn get_sum_at_slot(client: &RpcClient, slot: Slot, root: Pubkey) -> i64 {
    let account = client.get_account_at_slot(slot, &root);
    let node = Node::deserialize(account.data);
    match node.next {
        None => node.amount,
        Some(addr) => node.amount + get_sum_at_slot(client, slot, addr),
    }
}

fn get_sum(client: &RpcClient, root: Pubkey) -> i64 {
    get_sum_at_slot(client, client.get_epoch_info().absolute_slot, root)
}
```

A nice property of functions that read the state at a particular slot, is that they can be composed. Suppose in the example above, that I want to sum the amounts in 3 different lists. With three calls to `get_sum`, the accounts can again change in between the reads. But with `get_sum_at_slot`, we can read from the same snapshot.

**Comment by ruuda** [comment]
The example I gave above is a pathological example, but the issue is has real impact. For example, [explorer.solana.com can display token supplies that exceed 100% due to non-atomic reads](https://github.com/solana-labs/solana/issues/19248), and this would be one way to fix that.

**Comment by CriesofCarrots** [comment]
You might be interested in following this issue: https://github.com/solana-labs/solana/issues/18197
The currently proposed solution would not provide historical slot data for all of time, but would provide it for a configurable amount of recent history, allowing operators to index and store every update as their business logic needs.
