### ISSUE TITLE
[Nevermind - my mistake] PBKDF2 Derived Key differs from hashlib and libgcrypt 

### ISSUE THREAD

**Issue by KeithBrodie** [solana-labs/solana#17656]
#### Problem

I have run solana-keygen and generated a wallet. I retrieved the 64-byte master key from id.json and compared that key with keys generated from the same passphrase and salt by two other methods:

- Anaconda python hashlib function pbkdf2_hmac and
- Ubuntu gnuc libgcrypt20 gcry_kdf_derive  

All three methods agree for the first 32 bytes, but the solana key differs in the later 32 bytes. This is odd. If I'd made the calls incorrectly they wouldn't agree for the first 32 bytes.

### Setup
Passphrase: [vapor fix aunt attract wolf peanut change radio soap wink hood client]
Salt: [mnemonic]
Iterations: 2048
SHA512

### Result
Byte | solana-keygen (id.json) | Anaconda Python hashlib | gcc libgcrypt20
0 | 67 | 67 | 67
1 | 155 | 155 | 155
2 | 95 | 95 | 95
3 | 216 | 216 | 216
4 | 167 | 167 | 167
5 | 195 | 195 | 195
6 | 159 | 159 | 159
7 | 61 | 61 | 61
8 | 169 | 169 | 169
9 | 102 | 102 | 102
10 | 65 | 65 | 65
11 | 172 | 172 | 172
12 | 200 | 200 | 200
13 | 143 | 143 | 143
14 | 6 | 6 | 6
15 | 56 | 56 | 56
16 | 251 | 251 | 251
17 | 96 | 96 | 96
18 | 182 | 182 | 182
19 | 154 | 154 | 154
20 | 155 | 155 | 155
21 | 91 | 91 | 91
22 | 163 | 163 | 163
23 | 78 | 78 | 78
24 | 127 | 127 | 127
25 | 124 | 124 | 124
26 | 249 | 249 | 249
27 | 197 | 197 | 197
28 | 25 | 25 | 25
29 | 190 | 190 | 190
30 | 229 | 229 | 229
31 | 239 | 239 | 239
**32 | 230 | 246 | 246**
33 | 62 | 108 | 108
34 | 98 | 222 | 222
35 | 47 | 24 | 24
36 | 96 | 206 | 206
37 | 187 | 184 | 184
38 | 168 | 44 | 44
39 | 170 | 101 | 101
40 | 176 | 16 | 16
41 | 113 | 16 | 16
42 | 226 | 158 | 158
43 | 216 | 118 | 118
44 | 104 | 161 | 161
45 | 69 | 40 | 40
46 | 20 | 215 | 215
47 | 26 | 120 | 120
48 | 167 | 162 | 162
49 | 16 | 118 | 118
50 | 104 | 76 | 76
51 | 172 | 166 | 166
52 | 9 | 213 | 213
53 | 134 | 149 | 149
54 | 73 | 245 | 245
55 | 128 | 233 | 233
56 | 230 | 243 | 243
57 | 175 | 102 | 102
58 | 56 | 95 | 95
59 | 34 | 112 | 112
60 | 160 | 17 | 17
61 | 95 | 108 | 108
62 | 212 | 115 | 115
63 | 131 | 195 | 195

### Python Script
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import json
import hashlib

with open("KeyPhrase.txt","rt") as f:
    klist = f.readlines()

klist = klist[0].split()

jlist = json.load(open('id.json','rt'))


password = ' '.join(klist).encode()
print(password)
salt="mnemonic".encode()
key=hashlib.pbkdf2_hmac('SHA512', password, salt, 2048,dklen=512)
lkey = list(key)

for i in range(64):
    
    print ('{:2d}: {:3d} {:3d}'.format(i,jlist[i],lkey[i]))
    
with open("python_hashlib_mkey.txt","wt") as f:
    for i in range(64):
        f.write("{}\n".format(lkey[i]))
        
with open("Solana id.json.txt","wt") as f:
    for b in jlist:
        f.write("{}\n".format(b))`
```

### C Script (Ubuntu gcc libgcrypt20)
```
#include <stdio.h>
#include <string.h>
#include <gcrypt.h>

#define MAXL 1024

const char *keyphrase_file = "../KeyPhrase.txt";

int main(int argc, char *argv)
{

   unsigned char line[MAXL];
   unsigned char kbuf[64];
   unsigned char *salt = "mnemonic";
   FILE *kpf;
   int i;
   
   kpf = fopen(keyphrase_file,"rt");

   fgets(line, MAXL, kpf);
   
   fclose(kpf);
   
   while (strchr(line,'\n') != NULL)
      *strchr(line,'\n') = '\0';

   printf ("Input Key Phrase\n");
   printf ("Pass [%s] Size %lu\n",line,strlen(line));
   printf ("Salt [%s] Size %lu\n\n",salt,sizeof(salt));
   
   
   /* Initialize libgcrypt */
   
   printf ("PBKDF2 via libgcrypt version %s\n",gcry_check_version(NULL));
   
   gcry_kdf_derive(
     line,                /* Passphrase */
     strlen(line),        /* Length */
     GCRY_KDF_PBKDF2,     /* Algo */
     GCRY_MD_SHA512,      /* Sub-Algo */
     salt,                /* Salt */
     sizeof(salt),        /* Salt Length */
     2048,                /* Rounds */
     64,                  /* Key Size */
     kbuf);
   
   for (i=0;i<64;i++)
   {
      printf("%2d %3d\n",i,kbuf[i]);
   }
   
   {
      FILE *outf;
      outf = fopen("gcrypt_mkey.txt","wt");
      for (i=0;i<64;i++) { fprintf (outf,"%u\n",kbuf[i]); }
      fclose(outf);
   }
   
}
```

#### Proposed Solution

I don't know.  I'm a Rust newbie and I haven't sorted out how to run PBKDF2 in it yet (or where it is for that matter). - but I think the next step is to determine if a 'native' call to PBKDF2 differs from python hashlib and libgcrypt.

**Comment by t-nelson** [comment]
The output of `solana-keygen` is not raw PBKDF2 entropy, it's an ed25519 keypair.  I would not expect that latter 32 bytes to match as they are an ed25519 public key derived from the first 32 bytes of the keypair.

I'm not sure how you're calling `solana-keygen` for these tests, but this is a "Garbage in, garbage out" situation

**Comment by KeithBrodie** [comment]
Ahh - thank you.
