### ISSUE TITLE
Availability of ARM builds

### ISSUE THREAD

**Issue by evertonfraga** [solana-labs/solana#17687]
Hi all, 

Are there plans for ARM builds? I wanted to leverage some newer instance types at AWS for Solana nodes. 

Thank you.

**Comment by GZGavinZhao** [comment]
I was unable to build it from source with my 64bit Raspberry Pi 4B. I get this error while building:
```
error[E0658]: use of unstable library feature 'stdsimd'
    --> core/src/validator.rs:1457:8
     |
1457 |     if is_x86_feature_detected!("avx") {
     |        ^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: see issue #27731 <https://github.com/rust-lang/rust/issues/27731> for more information

error:
        is_x86_feature_detected can only be used on x86 and x86_64 targets.
        You can prevent it from being used in other architectures by
        guarding it behind a cfg(target_arch) as follows:

            #[cfg(any(target_arch = "x86", target_arch = "x86_64"))] {
                if is_x86_feature_detected(...) { ... }
            }

    --> core/src/validator.rs:1457:8
     |
1457 |     if is_x86_feature_detected!("avx") {
     |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
     |
     = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

error: the feature named `avx` is not valid for this target
    --> core/src/validator.rs:1455:18
     |
1455 | #[target_feature(enable = "avx")]
     |                  ^^^^^^^^^^^^^^ `avx` is not valid for this target

error: aborting due to 3 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `solana-core`
```

**Comment by mvines** [comment]
Tip of `master` built for RPI recently for me.  Be sure:
1. You're not building the v1.6 branch, it doesn't work for RPI
2. You are using the latest stable Rust version on the RPI

**Comment by GZGavinZhao** [comment]
Ah I see. I was using the latest stable build (1.6.27).

The Solana build script wants me to use Rust version 1.51.0, so I should ignore that and use the latest version (1.55.0)? I know how to do it, just a bit unsure whether that will create new problems...

**Comment by mvines** [comment]
On your RPI:
1. Checkout the `master` or `v1.7` branch
2. Run `./cargo build` or easier, `./scripts/cargo-install-all.sh desired/output/path`

(2) will ensure you're using the correct Rust version for that branch

**Comment by mvines** [comment]
The BPF JIT is not available for ARM, but you very much run `solana-validator` on the RPI (it won't keep up with mainnet though, RPI is too weak)

**Comment by GZGavinZhao** [comment]
Just built it. It works great! Thank you for your help! <3

**Comment by mrki0620** [comment]
Hi GZGavinZhao.
How did you do it.
I checked out the master and install the libs a proposed in the installation notes, but I still get the below error.

and build it with
cargo build

Do you have any clue?

error[E0512]: cannot transmute between types of different sizes, or dependently-sized types
   --> /home/mrkipi/.cargo/registry/src/github.com-1285ae84e5963aae/solana_rbpf-0.2.14/src/vm.rs:967:35
    |
967 |                         (unsafe { std::mem::transmute::<u64, SyscallFunction::<E, *mut u8>>(syscall.function) })(
    |                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: source type: `u64` (64 bits)
    = note: target type: `for<'r, 's, 't0> fn(*mut u8, u64, u64, u64, u64, u64, &'r MemoryMapping<'s>, &'t0 mut std::result::Result<u64, EbpfError<E>>)` (32 bits)

   Compiling h2 v0.3.3
   Compiling serde_yaml v0.8.21
For more information about this error, try `rustc --explain E0512`.
error: could not compile `solana_rbpf` due to previous error
warning: build failed, waiting for other jobs to finish...

**Comment by mrki0620** [comment]
@t-nelson 
Thanks, you have read the comment more closely than I did.You are of course right and i was even not thinking about the 64bit one, so it was my mistake.Kind regards, Peter

**Comment by lewixlabs** [comment]
My comment for who need to use Solana Tools on Raspberry Pi 4 (arm64)
https://github.com/solana-labs/solana/issues/20570#issuecomment-1030876590

**Comment by t-nelson** [comment]
Just a note that we CANNOT vouch for third party binaries.  Use at your own risk

**Comment by lewixlabs** [comment]
Yes I agree, If you think violates the rules, I delete my post.
I just did it to help community (and to be a part of)

**Comment by lewixlabs** [comment]
But I didn't get error building form scratch, with v1.9.5, extra install I did is libudev-dev

**Comment by andreclaro** [comment]
Is there any plan to release `Arm64` build for solana.

Why this is important:
- Take advantages of running the nodes on top Arm CPU architecture machines, such as, AWS Graviton2/3. The main benefits are costs reduction and performance increase. For further details consult: https://aws.amazon.com/ec2/graviton and https://about.gitlab.com/blog/2021/08/05/achieving-23-cost-savings-and-36-performance-gain-using-gitlab-and-gitlab-runner-on-arm-neoverse-based-aws-graviton2-processor
" Our latest cost analysis and performance benchmarks show that customers can realize cost savings of up to 23% and performance gains of up to 36% by deploying the GitLab application and GitLab Runner on the Arm-based Graviton2 when compared to the x86 based M5/C5 EC2 instances." 

- Enable developers to run `solana` on their MacBook Pro M1/M2 laptops.

**Comment by andreclaro** [comment]
You are already releasing [aarch64-apple-darwin](https://github.com/solana-labs/solana/releases) builds. Can you also release `linux/arm64`/`aarch64-unknown-linux`, so we can run nodes on top of Arm instances, such as, AWS Graviton? Thanks!

**Comment by johncattrall** [comment]
+1 for ARM/Graviton support. Seeing a large demand for this currently.

**Comment by t-nelson** [comment]
there are no labs resources to maintain such an effort at this time.  that said, there is zero reason to depend on labs for such a thing.  the release binaries are purely a convenience, not a requirement.  in fact it is highly _encouraged_ for validators to build their own binaries from the release tag rather than use the precompiled release

**Comment by StarSapien** [comment]
Can anyone here offer advice how to compile Solana from source on Apple M1?

I've tried what every blog, forum, video available suggests and non of it works.

The error message is too long to post here.
