### ISSUE TITLE
Replay Stage feeds realtime instruction execution cost to Cost Model

### ISSUE THREAD

**Issue by taozhu-chicago** [solana-labs/solana#17696]
#### Problem
Cost Model estimates transaction cost by summing up it's instructions execution costs and accounts access cost (see issue #16641), therefore Cost Model needs a way to be updated with execution cost for new and existing on-chain instructions, somewhat in realtime. 

#### Proposed Solution 
Replay Stage can collect instruction execution cost when replaying blockstore to bank, send collected data to Cost Model that is shared with Banking Stage via `RwLock`. 

- The collected data would be `Vec<(program_id: as PubKey, cost: as u64)>`
- Above data are sent to Cost Model at end of each bank's replay
- For new on-chain instructions, it's cost will be simply inserted to `cost_model.instruction_execution_cost` table
- For known instructions, I propose to average the new cost into existing one, so the cost table stay current. (eg `new_cost = AVG(collected_cost, existing_cost)`)

#### Implementation notes
The instruction is executed at `message_processor.execute_instruction(...)`, the path to it from Replay Stage is `replay_stage -> blockstore_process -> bank -> message_processor`; perhaps can utilize `replay_stats.execute_timings` by adding `Vec<(program_id: as PubKey, cost: as u64)>` to pass collected data back to Replay Stage

**Comment by sakridge** [comment]
This one is adding per-program timings already:
https://github.com/solana-labs/solana/pull/17554

**Comment by taozhu-chicago** [comment]
Great! This does all the heavy lifting for me. Left few comments on PR. Can we get it merged?

**Comment by taozhu-chicago** [comment]
#28281 replaced cost estimation with user requested CU. This part of code (replay collects program execution cost, share with cost model) had been removed from codebase. Issue can be closed
