### ISSUE TITLE
Test-drive new coverage tooling in Rust nightly

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#177]
Here's how they hacked it in without Rust modifications:

https://jbp.io/2017/07/19/measuring-test-coverage-of-rust-programs.html

But that was unappealing to us because of the hardcoded LLVM paths and versions. However, in the nightly build, they added a `-Zprofile` which points the compiler to its own copy of LLVM.

Perhttps://github.com/rust-lang/rust/pull/42433:

```
@ofek Same as https://jbp.io/2017/07/19/measuring-test-coverage-of-rust-programs, but use -Zprofile instead of -Cpasses=insert-gcov-profiling -L/usr/lib/llvm-3.8/lib/clang/3.8.1/lib/linux/ -lclang_rt.profile-x86_64.
```

But per https://github.com/rust-lang/rust/issues/42524, it looks like we an expect trouble if we don't pin down the nightly version:

https://github.com/rust-lang/rust/issues/50203

**Comment by garious** [comment]
@mvines, want this one?

**Comment by marco-c** [comment]
It looks like by disabling incremental compilation you should be fine with latest Nightly.
