### ISSUE TITLE
Persist instruction execute timings to blockstore

### ISSUE THREAD

**Issue by taozhu-chicago** [solana-labs/solana#17748]
#### Problem
Validator should start with previously collected `Instruction Execute Timings stats`, so the cost model can better estimate transaction costs with historical data. 

The `Instruction Execute Timings stats` is collected by Replay Stage when transactions are executed into Bank. The unit for collected data is `us`, in format of `HashMap< Program_Key, (accumulated_execute_time_us, count_of_executions)>`. 
 
#### Proposed Solution
Store above `Instruction Execute Timings stats` into blockstore, as part of transaction metadata. Validator can restore and initialize Cost Model from it when (re)starts.

**Comment by taozhu-chicago** [comment]
The `cost` in this domain is essentially the time elapsed for performing tasks (eg, load accounts, execute instructions, store accounts etc), therefore its absolute value depends on local environment. The cost of executing a program would be _a_ for this node, but could be _b_ for another. However, our configured `Max Cost Limit` are universal (as is hard-coded), therefore a faster node (eg., faster machine) calculates smaller cost for given program, hence could pack more transactions into a bank. So there will be variance in each block's density - number of transactions in a block. I assume such difference is tolerated. Is it the case? @sakridge

**Comment by jon-chuang** [comment]
I was wondering if cost estimate could be shared out of band and the median or average of non-extreme values (e.g. 10-90 percentile) is taken. 

Something similar to unixtime sysvar. But out of band.

Since, the block producer wants to produce a block that the validators, on average, can process quickly.

**Comment by taozhu-chicago** [comment]
> I was wondering if cost estimate could be shared out of band and the median or (possible stake-weighted) average of non-extreme values (e.g. 10-90 percentile, or even middle 67%) is taken.
> 
> Something similar to unixtime sysvar. But out of band.
> 
> So every validator gossips their cost data every 10s. Then, each validator determines the "cluster average" based on the stake-weighted average of non-extreme values etc.
> 
> Since, the block producer wants to produce a block that the validators, on average, can process quickly. They don't have an incentive of creating a block that is too dense.

Sounds a good idea to elevate cost from node-based information to cluster-shared concept, allows the TPU to produce blocks sensitive to cluster. Gossip certainly is a fitting candidate for this. 

Would love to get wider feedbacks.
