### ISSUE TITLE
ELF files contain local paths

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#17758]
#### Problem

ELF files generated with the bpf-tools contain local non-relative paths and this can not only reveal user information but also makes it more difficult to compare ELFs across machines.  (though the latter is less of a concern since we strip the ELFs before deployment)

#### Proposed Solution

Remove local absolute paths from the find ELF files

**Comment by dmakarov** [comment]
What ELF files is this issue about .so or some other ones? Where do these paths appear? In .symtab `FILE` entries or somewhere else?

**Comment by jackcmay** [comment]
It shows up heavily in the debug info but I also see it other places.  Just doing a search of the .so for "Users" usually gives me tons of hits if the .so was built on a mac

**Comment by dmakarov** [comment]
Why does it matter in debug info, if the deployed files are stripped of symbols and do not contain debug info? It seems this issue is about protecting development version of .so files, but maybe those shouldn't be distributed/deployed in the first place?

**Comment by jackcmay** [comment]
Search through one of our stripped ELFs, you will see a bunch of local  and absolute paths

**Comment by dmakarov** [comment]
This will be fixed by https://github.com/solana-labs/rust/pull/20

**Comment by jstarry** [comment]
Does this solve reproducible builds @jackcmay ?

**Comment by jackcmay** [comment]
@dmakarov Can you identify anything else that would prevent our ELFs from being build environment agnostic?

**Comment by dmakarov** [comment]
Not that I know of. But if some differences between different binaries that should be the same show up, let me know and I'll see how to fix it.
