### ISSUE TITLE
Include Account Size in TX data, distinguish between storage types (RAM, Persistent)

### ISSUE THREAD

**Issue by jon-chuang** [solana-labs/solana#17760]
#### Problem
The current approach of relying implicitly on cacheing mechanisms makes it difficult to handle the large factor difference between a page hit and a page miss on a modern NVME SSD v.s. RAM (1000-10_000x). Further, persistent device bandwidth can be exhausted by large accounts. (> 16KB: up to 10MB). 

Further, account size cannot currently be captured by the tx cost model prior to being read. 

#### Proposed Solution

Moving forward to >> 30GB or 100GB state to 1TB and more, one ought to allow programs to pay more rent to guarantee staying in RAM. 

This includes popular programs. Although, such programs’ cost of living in RAM is implicitly paid for by txs involving it. But, being able to declare an account as `RAMResident`, means that accessing such accounts have a lower cost.

One ought also to force txs to declare a u8 indicating pow 2 of account size for large accounts. This would piggyback nicely on the planned changes to the `Transaction` format to include asking for account page tables.

**Comment by aeyakovenko** [comment]
The additional software complexity is pretty high for the runtime and for the dev.

our cost model can target NVME IOps bandwidth. modern day NVME have 1m IOps at qd32. we can assume that all the accounts fault on every block and still be within 1m tps on a single card that scales with more SSDs.

optimizing throughput with 2+ NVMEs instead of 1, or going to a remote storage over 200gpbs nic.

**Comment by jon-chuang** [comment]
Actually, what you said is not true on commodity NVMe. It's only true if you use something like Optane with 10us read latency. On an NVME with 200us latency, your throughput using 32 reading threads is capped at 160K ops/s. 

With 10us latency its true that you can scale up to 3.2MM IOPs. But, imagine that you can already reach 1-1.6MM IOPs per thread using aio/io_uring. Meaning, you only ever need a single thread to handle all your I/O. 

Further, it was recently demonstrated, that the Linux kernel implementation of VMA and page tables has very high contention and thus plateaus at 500K IOPs even with increase qd/numthreads:
https://www.usenix.org/conference/atc20/presentation/papagiannis
A better implementation could achieve 6MM IOPs at the software layer, but we don't have the luxury of knowing if and when Linux would change to such an implementation. :-)

When using MMap, to deal with page faults, you could increase queue depth and use even more threads. But that leads to thread contention if your page faults are low, which one expects in normal operation. Just using a threadpool as a queue though incurs a communication and context switch overhead. 

A random read, out of memory benchmark with LMDB with a 2.7TB DB with 256GB RAM in 2015 confirms this https://gist.github.com/hyc/566e6f8313a06dda03ec

LMDB is one of those databases that are "good in theory" and works for normal applications. But its not the most efficient way to extract performance from your NVME. Just imagine, how poorly LevelDB must be written to lose to that.

You may be right that 160K reads on a commodity SSD is "good enough". But

**Comment by jon-chuang** [comment]
Extra data point that suggest that one should not further load the CPU/OS thread scheduler to perform I/O: 
- [Solana’s Aug 2020 time trial](https://forums.solana.com/t/results-individual-time-trial-benchmark-performance-testing/789) - suggesting that offloading CPU intensive verification to GPU generally improves TPS.
