### ISSUE TITLE
cargo build-bpf behaves differently than cargo-build in several situations

### ISSUE THREAD

**Issue by dmakarov** [solana-labs/solana#17849]
#### Problem

- cargo-build-bpf is missing the -p flag,
- cargo-build-bpf is not working with libraries containing hyphens in their name.

**Comment by ruuda** [comment]
It also doesn’t pass `RUSTFLAGS` to `rustc`.

**Comment by dmakarov** [comment]
> It also doesn’t pass `RUSTFLAGS` to `rustc`.

Yes, we'll add reading the value of the variable in cargo-build-bpf and passing it to cargo.

**Comment by dmakarov** [comment]
cargo-build-bpf appears to handle libraries with hyphens in their name without any problem.
