### ISSUE TITLE
Fix TPS regression

### ISSUE THREAD

**Issue by sagar-solana** [solana-labs/solana#1789]
#### Problem
Something broke with master over the weekend. TPS on gce testnets seems to average out to num validators.

#### Proposed Solution
Debug and fix the broken tip.

**Comment by mvines** [comment]
@sagar-solana how are you starting the testnet?  Are you using the GPU-enabled snap build?

**Comment by sagar-solana** [comment]
No I'm not running with Cuda. 

`./gce.sh create -n 10 -c 2 -p testnet-dev-sagar
./net.sh restart -o noValidatorSanity -o noLedgerVerify
`

**Comment by mvines** [comment]
oh good, that excludes a bunch of recent changes I was concerned about

**Comment by sagar-solana** [comment]
I have a pretty broken local testnet but I was able to possibly spot one part of this problem. 

With https://github.com/solana-labs/solana/pull/1759 it seems like bench-tps is unable to validate any transfers beyond the first. Currently working on reverting it.

Here's how to repro - 
```
./multinode-demo/setup.sh
./multinode-demo/drone.sh (in a 2nd shell)
./multinode-demo/leader.sh (in 3rd shell)
./multinode-demo/client.sh
```
The output from client.sh(bench-tps, really) eventually loops forever with "no signature" messages.

```
Get tokens...
Token balance: 0
starting balance 0
Airdropping 24999960 tokens from 192.168.1.18:9900 for 8pmzX8CbKiqB9p7ajsyf2jvGFSV5E4vYmJ1MHMo6fGX1
 INFO 2018-11-13T04:51:35.558757067Z: solana::counter: COUNTER:{"name": "cluster_info-insert-new_entry", "counts": 7, "samples": 6,  "now": 1542084695558, "events": 1}
Token balance: 24999960
adding more tokens 20
funding keys 1249998
creating from... 1
sending... 1
generating... 1 9QmP55w2VZ3c3CVKiW72R1korcLADRZVm3EQ3mLGzvtF
transfering... 1
funded: 5 left: 1249993
creating from... 5
sending... 5
generating... 5 8VNn9qJ7uzPeKf4zD3tNU5oBYdsGSshPM3WjGGDrTYtP
transfering... 5
no signature
generating... 5 4qwpjhqwVC8q4s8zugSQFW6tRXUHtHunZA6XVQWSMM6y
transfering... 5
no signature
generating... 5 4gRaxGXAsELfVMKJMGGJ5FioGPJavKDur9rbB1A6HDGD
transfering... 5
no signature
generating... 5 6K6M6fAkZvx4G44kbo8C1zDgJdy5wXrKWs1wL8urCeFk
transfering... 5
```
