### ISSUE TITLE
"Instruction spent from the balance of an account it does not own" error is misleading, and can be thrown if balance is too low

### ISSUE THREAD

**Issue by ChewingGlass** [solana-labs/solana#17914]
#### Problem

https://github.com/solana-labs/solana/blob/master/runtime/src/message_processor.rs#L134

This error is thrown if the owner is incorrect OR the balance is insufficient. The error message does not indicate this

#### Proposed Solution

Throw a separate error for insufficient balance

**Comment by t-nelson** [comment]
This logic is checking that a program did not reduce the SOL balance of an account that it does not own, which seems to be exactly what the logic states.  The balance check here isn't for insufficient funds, its asserting that the balance of a single account were not reduced.

If you believe that there is still an error here, please elaborate and we can reopen the issue
