### ISSUE TITLE
Bump spl-token to 3.1.1 in solana-account-decoder

### ISSUE THREAD

**Issue by michaelhly** [solana-labs/solana#17936]
#### Problem
I want to bump anchor's spl-token dependency to 3.1.1:
```
    Updating crates.io index
error: failed to select a version for `spl-token`.
    ... required by package `solana-account-decoder v1.7.1`
    ... which is depended on by `solana-client v1.7.1`
    ... which is depended on by `anchor-cli v0.8.0 (/Users/michaelhuang/Projects/anchor/cli)`
versions that meet the requirements `=3.1.0` are: 3.1.0

all possible versions conflict with previously selected packages.

  previously selected package `spl-token v3.1.1`
    ... which is depended on by `anchor-spl v0.8.0 (/Users/michaelhuang/Projects/anchor/spl)`
```

Can we bump spl-token version here to 3.1.1? 
https://github.com/solana-labs/solana/blob/c2191d885dc9689088c0dedcb30433a51a01bf12/account-decoder/Cargo.toml#L26

Also, can we create a new release of the spl-token client?

#### Proposed Solution
Bump versions + create new release.

**Comment by CriesofCarrots** [comment]
spl-token-cli bumped to v2.0.12: https://crates.io/crates/spl-token-cli

**Comment by michaelhly** [comment]
> spl-token-cli bumped to v2.0.12: https://crates.io/crates/spl-token-cli

ahh thank you!! For the client, I was referring to the js client: https://www.npmjs.com/package/@solana/spl-token. :)

**Comment by CriesofCarrots** [comment]
> For the client, I was referring to the js client: https://www.npmjs.com/package/@solana/spl-token. :)

Oh I see. What js functionality/commit are you looking for specifically? @michaelhly

**Comment by michaelhly** [comment]
This commit:
https://github.com/solana-labs/solana-program-library/commit/f5fb183b2d464915c5b0fd480e84cad91f654c07

Currently, I'm just hand-rolling my own `find_program_address`, without the curve check, which I guess is fine.

**Comment by CriesofCarrots** [comment]
> This commit:
> [solana-labs/solana-program-library@f5fb183](https://github.com/solana-labs/solana-program-library/commit/f5fb183b2d464915c5b0fd480e84cad91f654c07)
> 
> Currently, I'm just hand-rolling my own `find_program_address`, without the curve check, which is guess is fine.

Okay, v1.0.6 is now available: https://www.npmjs.com/package/@solana/spl-token
