### ISSUE TITLE
Stake account status in the explorer is incomplete/misleading

### ISSUE THREAD

**Issue by Arrowana** [solana-labs/solana#18002]
#### Problem

The explorer is a bit confused for Activating/Deactivating stake accounts

```
Stake Pubkey: 3xYa8izWaYd5QoPx6eYiw1DGQDU5v4mWvyYbpREX2Pf7
Balance: 0.50228288 SOL
Rent Exempt Reserve: 0.00228288 SOL
Delegated Stake: 0.5 SOL
Active Stake: 0 SOL
Activating Stake: 0.5 SOL
Stake activates starting from epoch: 200
Delegated Vote Account Address: 7MQjPjb6KgNFnBhZPM4HDhNWvPF77UkbWGgK8rb1kdYu
Stake Authority: 6TM6yq1RTR4fMkGD91HcbAzre9EsqdqmaQmcd3NDRrTW
Withdraw Authority: 6TM6yq1RTR4fMkGD91HcbAzre9EsqdqmaQmcd3NDRrTW
```

https://explorer.solana.com/address/3xYa8izWaYd5QoPx6eYiw1DGQDU5v4mWvyYbpREX2Pf7?cluster=testnet
![Screenshot from 2021-06-16 21-06-47](https://user-images.githubusercontent.com/8245419/122208651-eaadf100-cee6-11eb-9190-27ca6dcbee74.png)

It shows Status: Not delegated, which is odd, the `StakeAccount` type is "delegated"
Same for deactivating stake stake account 9sAhGxsQ4cphAn35mHLHS2bU1UfNpzJojmXFVdQzRTKA
![Screenshot from 2021-06-16 21-14-12](https://user-images.githubusercontent.com/8245419/122209402-d3bbce80-cee7-11eb-9177-602bdffa6098.png)

I added screenshots just in case the epoch goes over before someone looks at this

#### Proposed Solution
It should indicate that some stake is Activating or Deactivating.
Status is more complete from `connection.getStakeActivation`

**Comment by t-nelson** [comment]
I just hit this one too.  `StakeActivationData.state` is the way
