### ISSUE TITLE
how to get block by block height instead of slot number?

### ISSUE THREAD

**Issue by islishude** [solana-labs/solana#18003]
#### Problem

the rpc method [`getBlock`](https://docs.solana.com/developing/clients/jsonrpc-api#getblock) is to get slot,not to get block.

the skipped slot isn't necessary for end users

![image](https://user-images.githubusercontent.com/24730006/122224367-9efb4780-cee6-11eb-93d3-93ad9594d2c4.png)

#### Proposed Solution

add a new rpc method to resolve this,and this will save time in data processing afterwards for wallet or exchange

**Comment by t-nelson** [comment]
Blocks are queried by their slot height across the JSONRPC API intentionally.  This is because the range of elapsed slots are a known quantity whereas the range produced blocks is dependent on block production.

What is the use case you envision this API change being optimal in?

**Comment by mvines** [comment]
> add a new rpc method to resolve this,and this will save time in data processing afterwards for wallet or exchange

Note that by using [`getBlocks`](https://docs.solana.com/developing/clients/jsonrpc-api#getblocks) the wallet or exchange can figure which slots do not contain a finalized block
