### ISSUE TITLE
address verify is not strict enough

### ISSUE THREAD

**Issue by liyanhrxy** [solana-labs/solana#18032]
#### Problem
`7aXrw7nxSKijdToRuWUGG3gZ1qB3M59xTxAEn879fD6Y` and `7aXrw7nxSKijdToRuWUGG3gZ1qB3M59xTxAEn879fD6` which is a substring of first , but they are valid by current  verify logic(the trouble with base58, why not base58check???) !!!!!!! 

#### Proposed Solution
add other check in verify logic

**Comment by t-nelson** [comment]
Hi!  Thanks for reporting.  This is a duplicate of https://github.com/solana-labs/solana/issues/6970
