### ISSUE TITLE
GetConfirmedBlock return -32004

### ISSUE THREAD

**Issue by houlei1017** [solana-labs/solana#18056]
#### Problem
I use getSlot with commitment set 'finalized' to get last slot, then use GetConfirmedBlock to get block. some time return error. -32004, Block not available for slot .....
Our self solana vailidator node,  v1.6.9.

#### Proposed Solution
How to get last slot ,and get last solt block is available?

**Comment by houlei1017** [comment]
solana-validator config

solana-validator \
  --identity /data/solana/identity/validator-keypair.json \
  --ledger /data/solana/data \
  --entrypoint entrypoint.mainnet-beta.solana.com:8001 \
  --entrypoint entrypoint2.mainnet-beta.solana.com:8001 \
  --entrypoint entrypoint3.mainnet-beta.solana.com:8001 \
  --entrypoint entrypoint4.mainnet-beta.solana.com:8001 \
  --entrypoint entrypoint5.mainnet-beta.solana.com:8001 \
  --expected-genesis-hash 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d \
  --dynamic-port-range 8001-8011 \
  --rpc-port 8899 \
  --no-voting \
  --enable-rpc-transaction-history \
  --limit-ledger-size \
  --trusted-validator 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2 \
  --trusted-validator GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ \
  --trusted-validator DE1bawNcRJB9rVm3buyMVfr8mBEoyyu73NBovf2oXJsJ \
  --trusted-validator CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S \
  --no-untrusted-rpc \
  --log /data/solana/log/sol.log \
  --no-poh-speed-test \
  --snapshot-compression none \
  --no-snapshot-fetch

**Comment by mvines** [comment]
https://docs.solana.com/developing/clients/jsonrpc-api#getconfirmedblocks provides a list of slots with blocks in them.  But if you have further questions, please join the Solana discord and ask in the #developper-support channel.  Thanks!
