### ISSUE TITLE
BPF+LLVM: Add support for BPF shared objects

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#1805]
A single .o is too limiting

**Comment by jackcmay** [comment]
I have the changes to support LLVM LD's creation of BPF based .so but they are in a local clone of the LLVM github mirror.  Even if we forked LLVM to hold our changes temporarily expecting our users to build LLVM is probably to cumbersome.  We could provide a binary... @mvines any other ideas?

**Comment by mvines** [comment]
Yeah I think for now we simply need to provide LLVM binaries for our main two environments,  macOS and Ubuntu 18.04 (sry WSL...), until the LLVM changes can be upstreamed and released in an official upstream version.   This can take the form initially as a tarball attached to a github release in our fork of the LLVM github mirror.

**Comment by mvines** [comment]
Actually better: let's just provide a docker image containing our forked LLVM.  That'll work everywhere.
@jackcmay -- if you get the solana LLVM fork operational I'm happy to do the docker plumbing and hookup with bpf.mk

**Comment by jackcmay** [comment]
Steps to sync and build the Solana LLVM forks:
```
To sync, build, test llvm ld 
- git clone git@github.com:solana-labs/llvm.git
- git clone git@github.com:solana-labs/lld.git llvm/tools/lld
- mkdir llvn/build
- cd llvn/build
- cmake -G "Unix Makefiles" ..
- make -j check-lld
```
To rebuild lld
```
- cd llvm/build/tools/lld/
- make install
```

I haven't submitted my lld changes there yet, still need to complete my modifications to rbpf/solana to use the ELF shared objects (rather then .o's)

**Comment by jackcmay** [comment]
@mvines For the docker work, want to teach me to fish?

**Comment by mvines** [comment]
Sure!  So we want something that looks like the shellcheck docker image that we use [here](https://github.com/solana-labs/solana/blob/master/ci/shellcheck.sh#L16).   This is a multi-stage Dockerfile, https://github.com/koalaman/shellcheck/blob/master/Dockerfile, that builds shellcheck in one image, then copies the resulting binary to a second image to keep the overall size down.

Also get familiar with our Dockerfiles in the `docker-*` subdirectories of https://github.com/solana-labs/solana/tree/master/ci, we like to use `build.sh` scripts to build and push the images to dockerhub.  Send me your dockerhub account name and I'll add you to our org there so you can push stuff

**Comment by jackcmay** [comment]
Fixed: https://github.com/solana-labs/solana/pull/2012
