### ISSUE TITLE
solana-keygen new --no-outfile fails on version 1.7.1

### ISSUE THREAD

**Issue by wale-e** [solana-labs/solana#18083]
#### Problem
running on command on cli fails
"solana-keygen new --no-outfile" or "solana-keygen new --no-passphrase --no-outfile" on version 1.7.1
issues seems related to --no-outfile flag

#### Proposed Solution
Issue isn't present on 1.6.11

**Comment by CriesofCarrots** [comment]
Thanks, duplicate of https://github.com/solana-labs/solana/issues/17860
Fixed in v1.7.2
