### ISSUE TITLE
Explore sled as a replacement to both rocksdb and accountsdb

### ISSUE THREAD

**Issue by jon-chuang** [solana-labs/solana#18091]
#### Problem
Many separate problems:
1. rocksdb has been reported to have problems. Maybe sled is an answer.
2. AccountsDB: One shouldn't rely on mmap/kernel as a page cache. Sled offers a [page cache](https://github.com/spacejam/sled/tree/main/src/pagecache). 
3. AccountsDB: BTreeMap is slow. Sled uses a lock-free (via optimistic concurrency control), optimised bw-tree.

#### Proposed Solution
[Sled](https://github.com/spacejam/sled) offers 1B ops in < 60s for 95% read 5% write workload in in-memory case (17.5+MOps). 
Sled has support for io_uring (writes). 

#### Open Questions/Issues
1. Is sled index-larger-than-memory friendly? A: yes.
2. LLAMA-based materialized page fragments, while decreasing write amp, increases read amp... Can this be tuned/is this significant in the first place?
3. `AccountsDb` as a whole is very tighly integrated with `AppendVecId`s. But since index needs to be reworked for larger than memory case anyway...
4. Does sled offer io_uring/batched support for reads? A: not yet. But possibly soon.

**Comment by jeffwashington** [comment]
I hope to build this into the current accounts index prototype within the next day or so. I almost have rocksdb 'working'. I have anatoly's buckets working already.
