### ISSUE TITLE
Node start metrics.solana.com:8086 503

### ISSUE THREAD

**Issue by shixiaofeia** [solana-labs/solana#18140]
#### Problem

My node failed to start because the solana.com request failed

![image](https://user-images.githubusercontent.com/63829677/122908157-68aa4600-d386-11eb-91dc-3664408f11e8.png)

My start command

```
solana-validator \
--identity ./validator-keypair.json \
--ledger ./validator-ledger \
--entrypoint entrypoint.mainnet-beta.solana.com:8001 \
--entrypoint entrypoint2.mainnet-beta.solana.com:8001 \
--entrypoint entrypoint3.mainnet-beta.solana.com:8001 \
--entrypoint entrypoint4.mainnet-beta.solana.com:8001 \
--entrypoint entrypoint5.mainnet-beta.solana.com:8001 \
--rpc-port 8899 \
--no-voting \
--enable-rpc-transaction-history \
--limit-ledger-size \
--log ./solana-validator.log \
--no-poh-speed-test
```

**Comment by shixiaofeia** [comment]
And also encounter special errors:
```
Encountered an error: WebSocket Protocol Error: Unable to parse WebSocket key.
Enable a logger to see more information.
```
But there is no valid information in the log

**Comment by t-nelson** [comment]
The metrics errors were a result of some maintenance at the time and should have resolved by now.

The websocket error comes from deep in one of our dependencies as a result of receiving a malformed request.  This is not a problem with the validator, but you should likely close the RPC ports to the internet as these messages tend to arise from port knocking.
