### ISSUE TITLE
Ability to query historic account state

### ISSUE THREAD

**Issue by leoluk** [solana-labs/solana#18197]
#### Problem

For analytics/archival, a user often needs to capture the full history of account state over time. We specifically need this for Pyth data archival, but it's a common requirement for anyone doing in-depth analysis.

The current Pyth implementation uses account subscriptions over Websockets, however, on mainnet-beta, approximately 10% of account updates were dropped in a test with mainnet nodes running on default RPC settings. We had similar results when we tried to use subscriptions for Wormhole. As far as I can tell, websockets are best-effort and weren't designed for lossless capture:

- In case of queue overruns, messages are dropped silently without informing the consumer.
- Large account updates lead to head-of-line blocking.
- Streams cannot be resumed - this is because queues are managed per connection rather than using a log with consumer tracking (like Kafka) or persistent queues (like RabbitMQ). If the stream ends, data is lost till reconnection.

#### Proposed Solution

Solana can already store historic state locally for program logs and account balance changes. This could be extended to include the ability to optionally store account data for specific program-derived accounts as an opt-in feature, similar to `--enable-cpi-and-log-storage`. This would be ideal and allow us to backfill account state using load-balanced unary RPC calls backed by multiple nodes.

Related discussions:

- https://github.com/solana-labs/solana/issues/15461
- https://github.com/solana-labs/solana/issues/10194
- https://github.com/solana-labs/solana/issues/16986 (different use case, but same pull vs. consumer tracking discussion)
- https://github.com/solana-labs/solana/issues/16937
- https://github.com/solana-labs/solana/issues/11904
- https://github.com/solana-labs/solana/issues/9909
- https://github.com/solana-labs/solana/issues/15705
- https://github.com/solana-labs/solana/issues/18587

**Comment by CriesofCarrots** [comment]
Interesting idea as an intermediary step toward supporting historical account-state queries. It does seem possible, although we'll need to do some testing of rocksdb pruning and compaction with long and variable-length accounts (we've seen some notable slow-downs with long transaction-log data, although the recent compaction improvement may make this a non-issue).

For your use-case:
How many accounts would you envision following?
How much data in each account and how often are updates?
How much history would you want to maintain? ie. could it be pruned at the same slot rate as the rest of the ledger?

**Comment by leoluk** [comment]
> Also, how do you envision identifying the accounts to follow? By address or program id?

By program ID (Pyth price accounts, in particular).

> how often are updates?

At least once per slot

> How much history would you want to maintain? ie. could it be pruned at the same slot rate as the rest of the ledger?

Yes, just enough to reliably request and archive it.

**Comment by sakridge** [comment]
Do you need inter-slot updates? Or just the slot-end state?

**Comment by leoluk** [comment]
> How many accounts would you envision following?
> How much data in each account and how often are updates?

- ~8000 price accounts (3 KiB each), updated every slot.
- ~8000 program accounts, 512 bytes each, infrequent updates
- One mapping (20KiB) and parameter (50 KiB) account each, infrequent updates

**Comment by CriesofCarrots** [comment]
Okay, so storing full account data each slot and pruning on the same slot schedule as the rest of the ledger doesn't seem practical. One epoch would mean some 9TB of data for the price accounts. So we'd need a separate pruning schedule for this column.

What about commitment: Do you need the updates on every processed slot? Or would confirmed blocks be sufficient?

**Comment by ryoqun** [comment]
> So we'd need a separate pruning schedule for this column.

Hopefully, this shouldn't be too hard with custom CompactionFilter for the column...

**Comment by leoluk** [comment]
> Do you need inter-slot updates? Or just the slot-end state?

Just the end state

**Comment by CriesofCarrots** [comment]
> What about commitment: Do you need the updates on every processed slot? Or would confirmed blocks be sufficient?

@leoluk , bump on this question ^

**Comment by leoluk** [comment]
> What about commitment: Do you need the updates on every processed slot? Or would confirmed blocks be sufficient?

I'll check with the Pyth team. Current archiving is done with "confirmed" commitment level.

**Comment by leoluk** [comment]
> What about commitment: Do you need the updates on every processed slot? Or would confirmed blocks be sufficient?

Confirmed blocks would be sufficient

**Comment by CriesofCarrots** [comment]
Update from sync: as a short-term solution, we will explore in-memory storage of these historical updates, queryable via rpc. An accountsDB implementation is probably the right direction longer-term.

**Comment by leoluk** [comment]
The plugin framework indeed solves this!
