### ISSUE TITLE
JSON RPC airdrops are broken

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#1819]
This fails with "Internal error":
```
$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":1, "method":"requestAirdrop", "params":["83astBRguLMdt2h5U1Tpdq5tjFoJ6noeGwaY3mDLVcri", 40]}' http://localhost:8899
```
but this doesn't:
```
$ cargo run --bin solana-wallet airdrop 1234
```

`solana-wallet` doesn't use the RPC API to make an airdrop request and instead goes directly to the drone, so that's one difference.

Suspected root cause is f683817b48167d403dfe5ce779793ba413d9ce88, where the thin_client now uses the JSON RPC API to fetch a last_id or check a signature.  

Blocks: https://github.com/solana-labs/solana-web3.js/pull/64

**Comment by mvines** [comment]
In the failure case, https://github.com/solana-labs/solana/blob/master/src/thin_client.rs#L235 blocks until the 10 second read timeout at https://github.com/solana-labs/solana/blob/master/src/wallet.rs#L672 expires, at which point the airdrop signature is found and successfully returned.  But by that time, an "internal error" is already reported to `curl`

**Comment by mvines** [comment]
I'm tempted to just move the drone in the direction of #1754 instead of debugging this loop.  In the world of #1754, the drone's requestAirdrop API just returns a pre-signed transaction back to the caller, and the caller is then responsible for submitting it to the cluster and babysitting the response.

**Comment by CriesofCarrots** [comment]
I looked at this a bit. I was able to reproduce the error only intermittently. Were you able to make it fail every time, @mvines ?
I tried setting a timeout on the rpc_request client in hopes it might help kick out of the stall, but did not seem to have an effect.

**Comment by mvines** [comment]
On edge.testnet.solana.com it’s intermittent for me.  But with a local drone+leader it’s a consistent fail.  I’m going to overhaul the drone interface to avoid this entirely: the client will pass in their pubkey, desired token amount, and a last_id then the drone will create, sign and return a system move transaction for the caller to submit.
