### ISSUE TITLE
Add Bitlive.pro to exchange list

### ISSUE THREAD

**Issue by Solana-Bitlive** [solana-labs/solana#18245]
Hello
Our non-custodial exchange service provides our customers with the ability to exchange cryptocurrencies in over 90,000 exchange pairs.

Our service allows customers to exchange Solana cryptocurrency to more than 250 cryptocurrencies, we provide the most favorable exchange rate, and minimal exchange fees.

We would like to suggest that you place a mention for Solana cryptocurrency holders on your website in the exchange partners section about our service.

Installing our service in your section exchange partners will give Solana holders the opportunity to make instant exchange at favorable exchange rates with minimal commissions, without registration.

The advantage of our service: Non-custodial exchange, Best exchange rate, Round the clock support, Exchange without registration, User-friendly interface.

If anything needs to be provided to place our service in your partners section, please contact us and we will provide everything you need.

Official website https://bitlive.pro/
Regards, Bitlive.pro Affiliate Department

**Comment by t-nelson** [comment]
Try filling out this form https://form.typeform.com/to/JmAKFQdc
