### ISSUE TITLE
ci/test-stable.sh rebuilding in an untouched tree

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#1826]
#### Problem
as of c81a3f6ced1125030bf895bf213e7978b4abeb4e
local tree checks take too long because ci/test-stable.sh is rebuilding way too much.   

suspicion is bpf_c expressed as a feature only some of the time

#### Proposed Solution
bisect issues with changes to test-stable.sh, bpf_c, programs, to identify issue, perhaps decompose solana

**Comment by rob-solana** [comment]
thx

**Comment by rob-solana** [comment]
I've de-featurized bpf_c (i.e. just made it the default, period) but am still getting rebuilds of all of solana's crates for every issuance of "cargo ...".  the issue appears to be that cargo can't tell whether solana_bpf_loader needs to be rebuilt, and so always rebuilds it, triggering rebuilds of all of its dependencies

**Comment by jackcmay** [comment]
Looks like rebuilding is fixed in rust beta 1.31 due early 
January.  

I did see that CI was taking much longer (10 vs 2 mins) to build with beta in docker even though locally beta took the same time.

**Comment by jackcmay** [comment]
Closing this issue, not able to recreate the longer builds outside of CI, we'll deal with 1.31 when it comes out.
