### ISSUE TITLE
web3: return custom transaction error with logs

### ISSUE THREAD

**Issue by beautyfree** [solana-labs/solana#18277]
It will be great to have logs of failed transactions for ability to showing true errors and instant notifications with errors

Some places that could be modificated:
https://github.com/solana-labs/solana/blob/1f1e54b9d8ee8639c9f55df5008b1a6f2e25d8df/web3.js/src/connection.ts#L3540
https://github.com/solana-labs/solana/blob/f228d113c199c8a1c896cc20c942e2fe83b1046c/web3.js/src/connection.ts#L3448

**Comment by jon-chuang** [comment]
Related: https://github.com/solana-labs/solana/pull/17769#issuecomment-865372427

Maintaining custom errors is the key work. I envision it as dapp devs should submit a PR to include their custom errors in explorer/web3.js. interested too to see how the anchor version of custom error conversion will play out

**Comment by beautyfree** [comment]
Yeah, but this issue about other mechanic.

I think we can make custom error in lines like this:
https://github.com/solana-labs/solana/blob/1f1e54b9d8ee8639c9f55df5008b1a6f2e25d8df/web3.js/src/connection.ts#L3540

Where we can return custom Error with logs something like: return TransactionError('failed to send transaction: ' + res.error.message, logs);
And TransactionError will contains property with logs, which we can parse after simulation fails and other transactions errors

**Comment by jstarry** [comment]
I think this sounds useful, would you mind opening a PR with this change?

**Comment by beautyfree** [comment]
#18606

**Comment by yamen** [comment]
I hate to be commenting on a closed issue, but the related commit has a `console.error` call to output the logs, which creates noise in many application usages. Console logging is not used elsewhere in this library. I'm happy to remove this but am not a current contributor and can't open an issue either.

**Comment by jstarry** [comment]
Feel free to make a PR!
