### ISSUE TITLE
Programs should use signed_key() to get the signed key instead of fixed offsets

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#1827]
#### Problem

Tokens should only be able to be deduced from a key which is signed in a transaction.

#### Proposed Solution

Update programs to use signed_key() interface instead of fixed offsets

**Comment by mvines** [comment]
https://github.com/solana-labs/solana/pull/1942 addresses this issue for system, budget is also addressed.  The remaining programs all need auditing/fixing still

**Comment by mvines** [comment]
The remainder of this issue is now blocked until signed keys are surfaced through `sdk/`

**Comment by mvines** [comment]
ttt updated here: https://github.com/solana-labs/example-tictactoe/commit/2b90dc430038b6a934036c16082cc46f968edb99

We're done here!
