### ISSUE TITLE
SDK: remove requestAirdrop from the JSON RPC API 

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#1830]
The JSON `requestAirdrop` API is really just a thin wrapper around a drone, and makes unfortunate assumptions about where the drone is running and it's port.  With #1754 and the potential for many drones running around, we should fully decouple the drone from the RPC API and make the users fully aware of the drone they decide to use.  

Note that the drone itself may choose to implement something that looks very much like the existing JSON `requestAirdrop` API as a convenience for web-based users.

**Comment by garious** [comment]
@mvines, is this still an issue?

**Comment by mvines** [comment]
Yeah
