### ISSUE TITLE
Invoke should cascade ProgramErrors back to caller, not fail unrecoverably

### ISSUE THREAD

**Issue by jon-chuang** [solana-labs/solana#18302]
#### Problem
Currently, invoke fails unrecoverably if it encounters an instruction error.

#### Proposed Solution
Pipe out the instruction error to the caller.

**Comment by jstarry** [comment]
I think there are too many ways this behavior can catch a program developer by surprise, so the drawbacks probably outweigh the usefulness of this change. If a program modifies account state (lamports or data) before invoking another program, the account modifications will be persisted even in the event of an error unless manually rolled back.

**Comment by jon-chuang** [comment]
Hmm yes. Ive decided to take the approach that to trigger the appropriate behaviour, the caller calls `return ProgramError::RecoverableError`. This short-circuits persisting the account changes back to the outer context and returns a status code `0x0b9f_00e1`. This way, you can control what exactly you've rolled back when you want it (any changes lower and including the current cross-program call depth ).

**Comment by jon-chuang** [comment]
I've just read you can't do a self-invoke. So that's a pity. That means you'd have to deploy a separate program to handle controlled rollbacks. That seems suboptimal at best.

**Comment by jon-chuang** [comment]
Actually @jstarry , upon further investigation, I can't seem to agree. `ProgramError`s and `InstructionError`s are meant to be serialized to u64, and thus are suited to being handled by the outer-level program, be that the caller, or the runtime.

This is further complicated by the fact that if an inner program's CPI call panicks, even a method like `invoke_and_handle_error` can't save you. This will make composable programs ever more brittle.

Thus, I would like to register my vote (tentatively) towards piping the error back out.

Usually, programs handle the error by doing `invoke(&ix, ...)?;` as there is currently no ability or reason to try to handle errors. 

Since rust, at the very least, gives warnings if an error result is not utilised, if the error is not handled, it is most certainly failing the outer program. So I think this is not a big issue in terms of backwards compatibility.

**Comment by jon-chuang** [comment]
@jstarry , on further thought, I decided that a new syscall, `invoke_with_rollback`, that pipes through the errors of the invocation is the most robust way forward - giving users the power to rollback while preserving backwards compatibility.

The above idea of controlled rollbacks via self-invokes will also be encompassed.

In the following way:
```rust
fn can_rollback() -> ProgramResult {
    invoke(&ix_0, ..)?;
    invoke(&ix_1, ..)?;
    if !check_resultant_accounts(account_infos) {
        return Err(MyError::InvokeResultsFailedChecks);
    }
    Ok(())
}

fn invoke_with_rollback () {
    let ret = invoke_and_rollback_with_error(
        .. Instruction::CanRollback ...
    );
    if let Err(ProgramError::Custom(MyError::InvokeResultsFailedChecks)) = ret {
        msg!("rolled back invoke on {:?} due to failed checks", account_infos);
    } else {
        ret?;
    }
    Ok(())
}
```
