### ISSUE TITLE
Unified `invoke_with_rollback` syscall

### ISSUE THREAD

**Issue by jon-chuang** [solana-labs/solana#18325]
#### Problem
We want to give users more control over rolling back invoke. We don't want to make it confusing for users who only want `invoke` or `invoke_with_budget`, which are conceptually more straightforward.

#### Proposed Solution
Unified `invoke_with_rollback`

```rust
fn invoke_with_rollback(
    instruction: &Instruction, 

    // `budget` indicates how much of the remaining compute budget
    // one is willing to allow this invocation to consume

    // If set to None, all of the remaining budget will be available.
    
    // `invoke_with_budget_and_rollback` will return a 
    // `InvokeError(ProgramError::ComputationalBudgetExceeded)`
    // if the apportioned budget is exceeded
    budget: Option<u64>,
    
    account_infos: &[AccountInfo],
    signer_seeds: &[&[&[u8]]],
    
) -> Result<(), InvokeError>;

// this is required to prevent error pollution across multiple invocations
pub struct InvokeError(pub ProgramError);
impl From<InvokeError> for ProgramError {
    from(e: InvokeError) -> Self {
        match e.0 {
            ProgramError::Custom(_) => ProgramError::FailedToComplete,
            err => err,
        }
    }
}
```
The extern "C" interface `invoke_with_budget_and_rollback_unified` ingests the corresponding struct
```rust
struct InstructionWithOptions {
    instr_addr: u64,
    // Set to u64::MAX if budget == None
    budget: u64, 
    with_rollback: bool,
}
```

Example usage:
```rust
fn borrow_and_swap() -> ProgramError {
    // borrow logic that consumes variable compute units
    borrow(..)?;
    
    let remaining = sol_remaining_compute_units();
    if remaining > 75_000 {
        // We want to be able to both rollback and set a budget here.
        let ret = invoke_with_rollback(raydium_ix, Some(remaining - 25_000), ...);
        
        match ret {
            InvokeError(ProgramError::ComputationalBudgetExceeded) 
            | InvokeError(ProgramError::Custom(RETRY_ERROR_CODE)) => invoke(serum_ix, ...)?,
            ret => ret?,
        }
    } else {
        let ret = invoke_with_rollback(serum_ix, None, ...);
        if ret == InvokeError(ProgramError::Custom(serum_dex::DexError::ErrorCode(DexErrorCode::RequestQueueFull))) {
            // do something based on error
        } else {
            ret?;
        }
    }
    Ok(())
}
```

Replaces: https://github.com/solana-labs/solana/issues/18302

**Comment by jon-chuang** [comment]
On hindsight, I think we should separate the APIs into
```rust
invoke, invoke_signed
invoke_with_budget, invoke_signed_with_budget
invoke_signed_with_rollback, invoke_signed_with_budget_and_rollback
```
It's very confusing to use a unified API.

**Comment by jstarry** [comment]
This seems useful but it will require nontrivial runtime changes. We need to ensure that if we have 3 programs A, B, and C with the following call flow: A calls invoke_with_rollback(B) -> B calls invoke(C), then any persisted account changes from a successful call from B to C are also rolled back if B returns an error. We need a stack structure to persist all account changes which can add a lot of memory usage if big accounts are used in long call chains

**Comment by jstarry** [comment]
> the implementation is actually just a one-liner:

It's more involved because we only keep one copy of the state that will be persisted. After program C (from example above) processes successfully, `verify_and_update` will update the `pre_accounts` in the transaction wide `InvokeContext`. Those changes would have to be rolled back if program B ran out of compute.

https://github.com/solana-labs/solana/blob/b08f8bd1b042c0a9c49f34694885365f4372c345/runtime/src/message_processor.rs#L968-L971

**Comment by jon-chuang** [comment]
You're absolutely right @jstarry .

Thankfully, it's not necessary to eat up (much) more memory by cloning more accounts. 

Instead of updating the `PreAccount`s in place, a CPI would simply push a new preaccounts  referencing the keyed accounts into the preaccounts stack frame.

#### When to do the checks?
There are two ways of performing the checks:
1. One checks the entire execution segment lying below the CPI call
2. One checks the execution segment since the last check (requiring an additional update)

The difference is summarised in the following diagram, where the latter correponds to the extra `update` steps when popping up into a higher stack frame.

![image](https://user-images.githubusercontent.com/9093549/124149892-9a788680-dac3-11eb-9a0f-5be1a12d9323.png)

The top-level invocation will use the base-layer of preaccounts as it does now.

**Comment by jackcmay** [comment]
We are in the process of eliminating copies of account data and bailing on error was a big step in both minimizing copies as well as security vulnerabilities and developer footguns.  Re-introducing roll-backs will require keeping (and thus copying) intermediate state.  In the example [here](https://github.com/solana-labs/solana/pull/18244#issuecomment-870161863) most of these cases could be achieved off-chain using simulated transactions.  I agree that simulate transaction is not 100% but it should give a good approximate code path based on the operation requested.

**Comment by jon-chuang** [comment]
Hey @jackcmay ,

Thanks for the response.
1. With regards to copies, the approach I implemented doesn't actually do any significant copying - it just copies in the `Arc` pointer in `AccountSharedData` - meaning that at most, memory usage might increase over the duration of execution (by at most 4x corresponding to max invocation depth - and in most situations unlikely to be more than 2x), but copies of large pieces of data has already been eliminated. 
2. Regarding developer footguns, after discussions with jstarry, we decided that exposing the more specialised function `invoke_with_rollback` will limit the risk of unintended data persistence to when devs really need to rollback and know what they are doing.

Regarding security vulnerabilities, I can't quite speak to that. The footprint of the modifications I made are not that large. I also took some care to make sure the errors get propagated appropriately.

With regards to the computational budget - upon closer inspection, it seems to be true that operation CUs have small variance for many on-chain applications like raydium/serum. However, I am currently in the process of developing an application that has very dynamic compute usage. We also need rollbacks as we need to handle errors made by CPIs. I would say that the current situation doesn't necessarily reflect the future situation. 

As programs on Solana increase their cross-dependence, and make decisions more dynamically rather than executing fixed blocks of logic, I can only forsee requests for such capabilities increasing.

**Comment by jon-chuang** [comment]
Hey @jackcmay , 

So to be clear, we no longer want to emphasize the priority of `invoke_with_budget`, but `invoke_with_rollback` is still very much desired to be able to handle CPI errors from within a program.

We have a very concrete use-case for rolling back which we can discuss in private if needed.

I'm perfectly fine with removing the `invoke_with_budget` as a standalone API, or even the capability of limiting budget, if it means being able to push forward `invoke_with_rollback`. 

Nonetheless, I still think there is an argument for supporting budget limits, which is that of high-variance compute usage CPI dependencies.

Do let me know how you'd like to proceed on this, I can clean up the code and open a PR solely for the rollback capabilities if you think it's still on the table.

**Comment by pindaroso** [comment]
@jackcmay The ability to partially revert transactions would be a killer feature. I see this issue is stale, any word on reopening? @jon-chuang Did you end up finding a workout or get this functionality elsewhere?

**Comment by Lichtso** [comment]
In program-runtime-v2 CPI in the form of syscalls will be removed and replaced by program internal function calls. So, the option to have rollbacks will be pretty much gone.
