### ISSUE TITLE
web3.js Transaction.sign runs verify without throwing

### ISSUE THREAD

**Issue by Arrowana** [solana-labs/solana#18346]
#### Problem

When calling `Transaction.sign` we call `_verifySignature` but never do anything with the return value

https://github.com/solana-labs/solana/blob/52290dbd3570cc9eaa80b2ec14f68f7590a2a550/web3.js/src/transaction.ts#L549-L567

I know very little about cryptography, but do we really need to verify something we just signed?

#### Proposed Solution

Remove signature verification or make it throw

**Comment by steveluscher** [comment]
Fixed by #25302.
