### ISSUE TITLE
Allow bool type for get_declaration_packed_len in borsh utils

### ISSUE THREAD

**Issue by ChikinDeveloper** [solana-labs/solana#18408]
#### Problem

Borsh can serialize bool types, but get_declaration_packed_len (sdk/program/src/borsh.rs) fails for a bool declaration

#### Proposed Solution

Allow bool primitive type

line 46 :

```
None => match declaration {
    "u8" | "i8" => 1,
    "u16" | "i16" => 2,
    "u32" | "i32" => 4,
    "u64" | "i64" => 8,
    "u128" | "i128" => 16,
    "nil" => 0,
    _ => panic!("Missing primitive type: {}", declaration),
},
```

**Comment by mvines** [comment]
Oh, is the specification at https://borsh.io/#pills-specification out of date?
