### ISSUE TITLE
solana merge-stake two active stakes in the same validator throwing error

### ISSUE THREAD

**Issue by SiNONiMiTY** [solana-labs/solana#18411]
#### VERSION
solana-cli 1.6.16 (src:86c26f84; feat:2463141184)

#### PROBLEM
I have been trying to merge two active stake accounts under the same validator using the merge-stake command
solana merge-stake --keypair KEY --stake-authority KEY --fee-payer KEY TARGET_ADDRESS SOURCE_ADDRESS

But, it keeps throwing me the error 
Error: RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x6 [6 log messages]

From what I understand from the docs, I can merge two active stake accounts under the same validator but mine fails, any suggestions? Or, how do I view the error thrown by this transaction?

I have no problems merging two stake accounts that are deactivated.

> Merging stake accounts
> 
> Two stake accounts that have the same authorities and lockup can be merged into a single resulting stake account. A merge is possible between two stakes in the following states with no additional conditions:
> 
>     two deactivated stakes
>     an inactive stake into an activating stake during its activation epoch
> 
> For the following cases, the voter pubkey and vote credits observed must match:
> 
>     two activated stakes
>     two activating accounts that share an activation epoch, during the activation epoch
> 
> All other combinations of stake states will fail to merge, including all "transient" states, where a stake is activating or deactivating with a non-zero effective stake.

#### PROPOSED SOLUTION

The documentation must be updated to indicate that the accounts to be merged must be active for at least and epoch and have generated a reward. Also, update the cryptic error message that is being thrown when a transaction fails.

**Comment by SiNONiMiTY** [comment]
UPDATE

After an epoch, I was able to merge the two active stakes. The documentation needs to be updated. It should state that the accounts to be merged must be active for at least an epoch and have generated a reward. Maybe we can also update the cryptic error messages on the solana-cli when transactions fail.

**Comment by mvines** [comment]
Yeah, I definitely agree the cli could detect the credits mismatched error before hand and present a nicer message to the user

**Comment by mvines** [comment]
FTR: Some code for checking for credits mismatch already exists in the stake bot at https://github.com/solana-labs/stake-o-matic/blob/0a44a189caeadf0a5bd09732bbc767e40fb24c8c/bot/src/stake_pool_v0.rs#L438-L469

**Comment by ruuda** [comment]
I also found this out the hard way. @joncinque said this is a known issue with credits, and not a documentation bug; it should be possible to merge the stake accounts immediately when they are active.

**Comment by t-nelson** [comment]
> I also found this out the hard way. @joncinque said this is a known issue with credits, and not a documentation bug; it should be possible to merge the stake accounts immediately when they are active.

It's technically feasible to correct the program logic to allow merging mismatched observed credits, however this change has yet to be scheduled so client side prevention is the best mitigation today
