### ISSUE TITLE
[docs] solana-validator isn't a command anymore

### ISSUE THREAD

**Issue by pjuangph** [solana-labs/solana#18413]
#### Problem
Can you guys update your documentation https://docs.solana.com/running-validator/validator-start#connect-your-validator? The newer version of solana 1.7.3 does not include the command `validator` anymore. 

#### Proposed Solution
I do not know what the replacement command should be. Please update your documentation. Also anything `solana-something` should be replaced with `solana something`

**Comment by AKZhao** [comment]
I guess you were using Windows build with is not supported right now as a validator,  try it in Mac or Linux

**Comment by pjuangph** [comment]
I tried it on ubuntu 20.04 and I get the same results. What version are you running?
