### ISSUE TITLE
Run local net, error Unable to increase the maximum open file descriptor limit to 500000

### ISSUE THREAD

**Issue by stone89son** [solana-labs/solana#18414]
#### Problem
Environment: Ubuntu 20.04

I run a minimal local cluster with command:
`$ ./run.sh`
But error occurs:
**_ERROR solana_ledger::blockstore] Unable to increase the maximum open file descriptor limit to 500000_**

![abc](https://user-images.githubusercontent.com/6795515/124379064-c710e600-dcef-11eb-9161-7df64109fac0.JPG)

**Comment by mvines** [comment]
Try running `solana-test-validator` instead of run.sh, it works better for this use case

**Comment by kookob** [comment]
> Try running `solana-test-validator` instead of run.sh, it works better for this use case

It's under a subdirectory `validator`

**Comment by Ambitiont109** [comment]
Is this problem solved?
I also got this error when I run ```solana-test-validator``` on ubuntu 20.04 WSL

**Comment by devstar0718** [comment]
I am running following commands on centos
# NDEBUG=1 ./multinode-demo/setup.sh
But still get same error.
I am trying to build stable version - 1.8.13.
Please help me to build it.
Thanks

**Comment by t-nelson** [comment]
Hi! We don't use Github for support requests.  Please join #validator-support on https://solana.com/discord instead
