### ISSUE TITLE
rpc_client::send_and_confirm_transaction() aborts transaction confirmation too early

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#18426]
`send_and_confirm_transaction` current waits until `getFeeCalculatorForBlockhash` returns null before declaring the transaction as permanently failed.  This is incorrect as there's a window of time after the transaction blockhash expires that the transaction can still be processed by the network.

A better method is to:
1. Record the `lastValidBlockHeight` associated with the blockhash
2. Monitor `getEpochInfo` until the current block height is greater

**Comment by CriesofCarrots** [comment]
This method uses `RpcClient::is_blockhash_valid` now
