### ISSUE TITLE
Clippy gone wild

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#1845]
Did we pick up a new version of clippy somehow?  All test-stable CI is currently red on a spew of `error[E0658]: scoped lint clippy::doc_markdown is experimental (see issue #44690)` clippy lints.

Revert d4e252d7504f179c74ed2a426149f12deb8e2b03 once this issue is debugged and clippy is back to normal

**Comment by garious** [comment]
1.30.1 is still the latest and to my knowledge, we only see upgraded plugins when the compiler is upgraded.

**Comment by mvines** [comment]
v0.10 was afflicted by this too.  From https://hub.docker.com/r/solanalabs/rust/tags/ I see that the 1.30.1 docker image was updated a couple days ago.  We probably picked up a new clippy-preview (cc: https://github.com/solana-labs/solana/blob/master/ci/docker-rust/Dockerfile#L24)

**Comment by mvines** [comment]
encoding_rs v0.8.11 appears to have been the culprit, fortunately encoding_rs v0.8.12 is now available

https://github.com/hsivonen/encoding_rs/releases

**Comment by garious** [comment]
About time we check Cargo.lock files into release branches?

**Comment by mvines** [comment]
Yeah, master too.  Getting broken like this sucks

**Comment by garious** [comment]
Sure, we can see how that plays out. I worry that'll be overconstraining for any downstream dependencies.

**Comment by mvines** [comment]
How about removing Cargo.lock before publishing to crates.io.  This way we don't get random bustage and downsteam users don't get boxed in

**Comment by garious** [comment]
I like it!

**Comment by mvines** [comment]
Oh well look at that.  `cargo package` strips a Cargo.lock file already.  ❤️
