### ISSUE TITLE
ELF error: Unresolved symbol (sol_keccak256) at instruction #18976 (ELF file offset 0x25018)

### ISSUE THREAD

**Issue by sham789** [solana-labs/solana#18481]
#### Problem

I catch this weird runtime error on `mainnet-beta`. I've faced it once I used `solana_program::keccak::hash` function:

```
> Program log: Instruction: Send Value To Subs
> Program log: checking multisig bft count
> Program log: prev_pulse_id: 87
> Program log: pulse_id: 87
> Invoking Unknown (AH3QKaj942UUxDjaRaGh7hvdadsD8yfU9LRTa9KXfJkZ) Program
  > Program log: Instruction: AttachValue
  > Program log: got the attach!
  > Program log: Creating mint instruction
  > Invoking Token Program
    > Program log: Instruction: MintTo
    > Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 3012 of 176471 compute units
    > Program returned success
  > Program AH3QKaj942UUxDjaRaGh7hvdadsD8yfU9LRTa9KXfJkZ consumed 13145 of 184062 compute units
  > Program returned success
> Program B5WUzWR2uNMwQhziPH882JekyQSmYHUt5N1LtpLdmSNB consumed 29562 of 200000 compute units
> Program returned error: ELF error: Unresolved symbol (sol_keccak256) at instruction #18976 (ELF file offset 0x25018)
> Runtime error: ProgramFailedToComplete
```

Raw Transaction:

```
AVZfVLdKSNPVNgQx3q5bH7z+7Vps/3VsrOipsIkKrZKiDvDaGHQvkYvg1IhCKO44FBNESdnoiMIVW8q5nLpeTgcBAAQKzOxu152xzcCP00/4kByD+hp5GrYgnEtnNDjfQ3d/mY8Lp29qDvFU4+AaGj63TQum6y262sMFQZlFc6qq07tPwXSdPRBtUzGGgTOBpgHEBN9E2Db2mTB0NS08Wa5kE27Ugh68bUSLjhdjA3U1LQgRuMYvycX8JUpj5xMElbjedWWNrK1NEeM1GS2ujdo85ZXidwvp8JqyL9P8QG9ugli/DNVdvG6O6eOvTgHplWiYS3IOpizQ/Ku59VUlSyeu3nU/Bt324ddloZPZy+FGzut5rBy0he1fWzeROoz1hX7/AKmJ1TD6MUVL5OFnBG5/Ykiw981vCraOo2ty1pbmuV1q0pW8h1IK01ZdZ006NUx3DWYTPKEMV06Un96RtBiUZzGQq3EmD7oLyIqO7XT6EDdt6lPRLwVrfz24NMOpNradenBE8GptdJ09GcE+Puc0ctg7wFf2mXnAqXNtK/0krCnkTAEICQACBAYHAwEFCVoDbYh+6h0i8sTNhUPvyUmN8mVtTzUffM33PtVdvG6O6eOvTgHplWiYS3IOpizQ/Ku59VUlSyeu3nU/AAAAAAAAAAJiAAAAAAAAAKOe8X9MPBNVrUqf0oWwYxQ=
```

However, in `DevNet` it works:

https://explorer.solana.com/tx/2CmBDgYvjTj9NHdbz85df74ZqHzBMU7sqVXZaa7U6CNi3Js4d8p9JAjyh8JNtPtdmN4e9vtyipZdVGFhQ97JjqVH?cluster=devnet

The place where `keccak::hash` is called:

https://github.com/Gravity-Tech/solana-adapter/blob/2679fcdaa3a03873518bb4e3c2b9eca6ffb74acd/src/gravity-core-adapter/nebula/src/nebula/state.rs#L156-L171

Source Code of Program:

https://github.com/Gravity-Tech/solana-adapter/blob/feature/ports/src/gravity-core-adapter/nebula

More detailed info is attached (I ran tx simulation):

[Explorer _ Solana.pdf](https://github.com/solana-labs/solana/files/6777790/Explorer._.Solana.pdf)

#### Proposed Solution

I think `BPF Upgradable Loader` fails to recognize the function as we see `> Program returned error: ELF error: Unresolved symbol (sol_keccak256) at instruction #18976 (ELF file offset 0x25018)`. Can we fix this bug on Mainnet as well?

**Comment by Arrowana** [comment]
```
arowana:~$ solana feature status --url https://api.mainnet-beta.solana.com | grep keccak
7Ua8mFtahVfA3WCY9LoXDAJJdvJRJHckvSSr1dD8FTWc | inactive                    | keccak256 syscall
```
Feature not activated on devnet yet

**Comment by sham789** [comment]
> ```
> arowana:~$ solana feature status --url https://api.mainnet-beta.solana.com | grep keccak
> 7Ua8mFtahVfA3WCY9LoXDAJJdvJRJHckvSSr1dD8FTWc | inactive                    | keccak256 syscall
> ```
> 
> Feature not activated on devnet yet

I don't receive any output at all

**Comment by mvines** [comment]
@jackcmay - Do you know if there's a timeframe for when the keccak256 syscall will be enabled on mainnet?

**Comment by jackcmay** [comment]
Early next week

**Comment by jackcmay** [comment]
keccak256 syscall has been enabled on mainnet
