### ISSUE TITLE
would it provides balance changes response in rpc, simulateTransaction ?

### ISSUE THREAD

**Issue by yihau** [solana-labs/solana#18509]
#### Problem

I can't get the exact balance changes via rpc, `simulateTransaction`

For now, I can only get it by twice rpc call. (getBalance and simulateTransaction)

It will cause a problem that I can't call those two rpc in the same context.

I have a chance to get result of `simulateTransaction` which contains one more confirmed block.

#### Proposed Solution

add something like preBalance, postBalance or balance changes in simulateTransaction

or

make getBalance and simulateTransaction can run in the same context. (like specific slot)

**Comment by mvines** [comment]
The `accounts` input array to [simulateTransaction](https://docs.solana.com/developing/clients/jsonrpc-api#simulatetransaction) can be used to request accounts affected by the simulation to be returned, which includes their "postBalance".  I think using this existing feature would solve the program described here.

**Comment by yihau** [comment]
Yes, It contains postBalance but no preBalance.

The scenario is that:

A account transfer to B two times.
The first has sent.
When I want to send the second.

get B account balance (for pre balance) => the first tx confirmed => call simulateTransaction

I will get the balance changes including the first and the second.

I also try to improve this situation like 

get B account balance (for pre balance) => the first tx confirmed => call simulateTransaction => get B account balance again

I check B balance is consist after I call simulateTransaction .
Although the balances match, I still encounter the problem which is the balance changes including the other txs.

**Comment by mvines** [comment]
Got it.  How about a new option to request "preAccounts" from simulateTranstion.  The currently returned "accounts" are essentially "postAccounts" already.  The "preAccounts" would allow the user to obtain the account balance and data at the time of the simulation.

**Comment by yihau** [comment]
I think it works! Thank you.

**Comment by ryoqun** [comment]
(this functionality is needed for one of advanced usages of #17796 )
