### ISSUE TITLE
ContactInfo is one giant structure for all the services

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#1854]
#### Problem
ContactInfo in https://github.com/solana-labs/solana/blob/master/src/contact_info.rs is one giant structure for all the possible services, which may not all be operational for different kinds of nodes.  Right now we work around this problem by setting the address of the invalid services to 0.

#### Proposed Solution

1. Break up https://github.com/solana-labs/solana/blob/master/src/crds_value.rs#L10 into separate Values for the same Pubkey.

*  GossipAddress
* TpuAddress
* TvuAddress
* StorageAddress

2. Move the "Repair" protocol out of Gossip, and add a new service address to the CrdsValue enum

* LedgerSyncAddress

@sakridge (what is the difference between repair and storage?)
tag: @rob-solana @sagar-solana

**Comment by sakridge** [comment]
@aeyakovenko Storage is the interface that replicators would provide. For example something like I have 'xxx' signature, give me the transaction that it corresponds to in your data set. Or whatever interfaces we need for something like the block explorer.

**Comment by garious** [comment]
@rob-solana, @aeyakovenko, does anything in the persistent testnet depend on this cleanup? I'm curious if this one can be pushed back to Grandview.

**Comment by rob-solana** [comment]
can be pushed
