### ISSUE TITLE
Error cors when call devnet.

### ISSUE THREAD

**Issue by xuanlongvts** [solana-labs/solana#18593]
Access to fetch at 'http://devnet.solana.com/' from origin 'http://localhost:3000' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

I have an error when call solana devnet.

**Comment by mvines** [comment]
https://devnet.solana.com/ has been deprecated, please use https://api.devnet.solana.com/ instead
