### ISSUE TITLE
machine architecture is currently unsupported

### ISSUE THREAD

**Issue by adityakm24** [solana-labs/solana#18594]
#### Problem
While installing solona on my windows 10 Laptop I get the following error:
$ sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
solana-install-init: machine architecture is currently unsupported

**Comment by steviez** [comment]
@adityakm24 - Please check the Windows section of the docs for the Windows specific instructions:
https://docs.solana.com/cli/install-solana-cli-tools#windows
