### ISSUE TITLE
Cost model calculations are performed on unsanitized transactions

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#18638]
#### Problem
https://github.com/solana-labs/solana/blob/6829d210d4f5c61ef4fe21abf8bf8757c08fee53/core/src/cost_model.rs#L183 relies on `verify_precompiles` to sanitize program id indexes. This implicit reliance is not very clear and could easily break in the future

tag @taozhu-chicago

**Comment by taozhu-chicago** [comment]
@jstarry Thanks for pointing it out. It is not clear by itself, but `CostModel::calculate_cost` first invoked at banking_stage when transactions are fetched form messages: https://github.com/solana-labs/solana/blob/master/core/src/banking_stage.rs#L1086, at that point, transactions have been verified: https://github.com/solana-labs/solana/blob/master/core/src/banking_stage.rs#L1071. My thought is cost model should only deal with transactions that are ready to be processed. But I can see value of redundant safety check. Perhaps to do similar check `transaction::verify_precompiles()` does: 
```
            // The Transaction may not be sanitized at this point
            if instruction.program_id_index as usize >= self.message().account_keys.len() {
                return Err(TransactionError::AccountNotFound);
            }
```

**Comment by jstarry** [comment]
@taozhu-chicago verification != sanitization. Transactions are not sanitized until much later here: https://github.com/solana-labs/solana/blob/6829d210d4f5c61ef4fe21abf8bf8757c08fee53/runtime/src/accounts.rs#L864

**Comment by taozhu-chicago** [comment]
> @taozhu-chicago verification != sanitization. Transactions are not sanitized until much later here:
> 
> https://github.com/solana-labs/solana/blob/6829d210d4f5c61ef4fe21abf8bf8757c08fee53/runtime/src/accounts.rs#L864

Gotcha. Here we just want to make sure that `instruction.program_id_index` is not out of boundary, which is checked somewhere early. I guess the question is if better to check it again?.

**Comment by jstarry** [comment]
Ah understood, you're relying on `verify_precompiles` to sanitize that for you so this is currently safe. I think it would be better to check again.

**Comment by taozhu-chicago** [comment]
Makes sense, will make a PR for it. Also need to rewire the control flow a bit since now `calculate_cost()` can error.
