### ISSUE TITLE
Thin clients can't verify finality of transactions

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#1867]
#### Problem

A client that can't do PoH verification would not be able to verify that transactions are on the same branch as votes that guarantee finality for those transactions.

#### Proposed Solution

Clients can verify that the votes are at least voting in unison on the same LastId, without proving that the LastIds connect.

1. Each vote should contain a deterministic hash of the votes present in slot that the vote is verifying.
2. A client can then evaluate a chain of votes from each slot and validate that the votes are voting in unison.

This would give a client a guarantee that all the votes are on the same branch, or they should all be slashed.

Note:
I am not sure how well this will work if the slots contain votes for random previous slots.

tag: @pgarg66 @garious @rob-solana @sakridge

**Comment by garious** [comment]
This depends on BankForks. Bumping to Grandview.

**Comment by mvines** [comment]
This issue seems obsolete.  We now have a mechanism to count confirmations and will be exposing it via the RPC API in #2474
