### ISSUE TITLE
BPF program consumes the entire budget on panic with jit

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#18683]
#### Problem

When running a local node with jit and executing the [panic](https://github.com/solana-labs/solana/tree/master/programs/bpf/rust/panic) bpf program the runtime reports that the entire compute budget was consumed when actually only a few thousand were.

This behavior has been observed on mainnet, its not clear there if the issue is only with panic or other program exits as well.

#### Proposed Solution

This appears to have something to do with how jitt'd programs account for compute budget on exit.

This can be recreated by running a local node with jit enabled, deploying the panic program, and sending it an instruction with no accounts and no instruction data.  This should also be recreatable in a unit test but I was not able to observe that.

**Comment by jackcmay** [comment]
Here is another example, this time the program retuned an error: https://explorer.solana.com/tx/55NUP1eDmu5YnnbVDe7FbvYDFoX1UqSSVLMEmwWsBwDDL6i3Cy9z3EKrC1tMRQPGcSEQVZkWRDM6fMBkPWrop6UY

**Comment by Lichtso** [comment]
This only happens if JIT is enabled, right?
What happens if you extract the program and run it in the standalone CLI tool?

**Comment by jackcmay** [comment]
Didn't try that

**Comment by jackcmay** [comment]
This bug will be exposed further to developers via https://github.com/solana-labs/solana/pull/18715

**Comment by Lichtso** [comment]
I just released [RBPF v0.2.14](https://github.com/solana-labs/rbpf/releases/tag/v0.2.14) which should fix this.
Can you check if the issues still occurs on [this branch](https://github.com/solana-labs/solana/pull/18869)?

**Comment by jackcmay** [comment]
Yup, look good!
