### ISSUE TITLE
error on Devnet for transfer

### ISSUE THREAD

**Issue by zaprush** [solana-labs/solana#18691]
when i try to transfer from getting this error on Devnet
Error: RPC response error -32005: Node is behind by 54393 slots

**Comment by alexmanzer** [comment]
I ran into the same problem while developing and started looking for bugs in my code.
I have learned, that you can get the `getHealth` status also via RPC, even if this doesn't help for the problem:
```
~ % curl https://api.devnet.solana.com -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":1, "method":"getHealth"}'
-->
{"jsonrpc":"2.0","error":{"code":-32005,"message":"Node is behind by 59093 slots","data":{"numSlotsBehind":59093}},"id":1}
```
