### ISSUE TITLE
RPC program account subscriptions are not notified when an account is deleted

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#18704]
#### Problem
Unlike individual account subscriptions, program account subscriptions are not notified when an account owned by the subscribed program is deleted.

#### Proposed Solutions

1. RPC program cache
Cache the active program accounts for "confirmed" and "finalized" confirmation levels and check if accounts are missing when program accounts are loaded.

2. Tombstone records
Account subscription notifications are always sent at slot boundaries so deletion detection would need to store what the owner of the deleted account was at the end of the previous slot in order for RPC to notify a program subscriber about the deletion.

**Comment by bmeeder22** [comment]
Is there any plans to pick this up anytime soon?
