### ISSUE TITLE
solana-validator ledger/ is incompatible between master and v1.7/1.6 due to `program_costs` column

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#18729]
A ledger/ that's created by a master validator will panic a v1.7/v1.6 validator:
```
thread 'main' panicked at 'Failed to open ledger database: RocksDb(Error { message: "Invalid argument: Column families not opened: program_costs" })', core/src/validator.rs:1065:6
```

STR to produce the panic:
```
$ solana-install init edge
$ solana-test-validator --reset
^C after it starts running
$ solana-install init beta
$ solana-test-validator --log
```

**Comment by taozhu-chicago** [comment]
Going to stub-out/backport `program_cost` column family and `bank_hash` column family (from PR #18533 )  to v1.7 and v1.6.

**Comment by ryoqun** [comment]
today i learnt: rocksdb all of cfs must be explicitly opened: https://github.com/facebook/rocksdb/blob/84eef260de9c0dc0c7ace8e6f605a2b3efd71038/db/version_edit_handler.cc#L360-L371

**Comment by CriesofCarrots** [comment]
v1.6, v1.7, and master compatible as of column-family stubs ^
