### ISSUE TITLE
Transaction timing used unchecked math

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#18732]
#### Problem

The calculation of transaction timings uses unchecked/unsaturated math

Here are a couple of examples:
https://github.com/solana-labs/solana/blob/2ec81f627d478186461cd0a7985170edd6d7b6a1/runtime/src/bank.rs#L173
https://github.com/solana-labs/solana/blob/2ec81f627d478186461cd0a7985170edd6d7b6a1/runtime/src/bank.rs#L3315
https://github.com/solana-labs/solana/blob/2ec81f627d478186461cd0a7985170edd6d7b6a1/runtime/src/message_processor.rs#L92

#### Proposed Solution

The microsecond timings are for debugging only so I'm not too concerned.  The compute budget counting will be used by the cost model so we may want to safeguard the math from weird behavior.

@CriesofCarrots , you raised the flag, thoughts?
@jeffwashington you use these metrics extensively, thoughts?

**Comment by jeffwashington** [comment]
seems like saturation is the best thing to do. I can implement that if it satisfies your concerns.

**Comment by jackcmay** [comment]
That will also result in bad values, maybe because we know these should never overflow, throw out any entries that do?

**Comment by jeffwashington** [comment]
ah, bad values for your computations? I was assuming metrics that saturated would just be recognized as such and be inconvenient and lose information. I don't expect the metrics to overflow for the purpose of monitoring and perf work. What do you propose we do? Maybe I misunderstood your question.

**Comment by jeffwashington** [comment]
'throw out' means ignore in your computations? So, if we saturated, we'd get a metric showing u64::max or whatever and we'd know it was 'big'. And you'd just ignore u64::max?

**Comment by jackcmay** [comment]
Yeah, true, `u64::MAX` is easier to identify as long as we look at it pre `/ count`

**Comment by CriesofCarrots** [comment]
While I don't feel I have a complete view of how these are used, saturation makes sense to me.

**Comment by jackcmay** [comment]
Resolved via #18735
