### ISSUE TITLE
RPC simulations should allow for passing in user provided account data

### ISSUE THREAD

**Issue by jon-chuang** [solana-labs/solana#18746]
#### Problem
Users may want to simulate transactions based on hypothetical account state.

#### Proposed Solution
Use a json format to pass account data, bank ingests this data and writes over any data fetched from accountsDB when executing transaction.

Related https://github.com/solana-labs/solana/pull/17796

**Comment by ryoqun** [comment]
yeah, I like this additional facility. :)
