### ISSUE TITLE
No design of a node that can support a block explorer

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#1879]
#### Problem

JSON RPC API isn't sufficient for a block explorer. A service needs to observe the gossip network and sit in the same spot as a validator to receive all the transactions in real-time.

#### Proposed Solution

Add an RFC that describes a new command-line tool solana-httpd, a spy node and web server.

**Comment by mvines** [comment]
It would be nice to consider debugger requirements in this RFC as well, the requirements should be very similar to the block explorer.  But if that balloons the scope of this issue too much then feel free to 302.

For the debugger we need the ability to do the following in some form:
1. Fetch the current poh height
2. Fetch the contents of an account at the given poh height
3. Fetch the contents of any transaction given its signature
4. Figure the poh height of a given transaction signature
This should enable a debugging agent to reconstruct the state of a given transaction instruction for single stepping/etc but a TBD tool that repurposes part of the bank and the program execution runtime.
