### ISSUE TITLE
Move snapshot package TempDir creation & hardlinking into ctor for AccountsPackagePre

### ISSUE THREAD

**Issue by brooksprumo** [solana-labs/solana#18815]
snapshot_utils::package_xxx_snapshot() and do_package_snapshot() don't do much besides calling the AccountsPackagePre ctor. So, move that code into ctors for AccountsPackagePre. (Creating the TempDir and doing the hardlinking.)

_Original comment from original PR_

Heh, looking at it again, I think `package_incremental_snapshot` and  `package_snapshot` may just be better off as constructors for `AccountsPackagePre`, where logic like https://github.com/solana-labs/solana/pull/18504/files#diff-c957621ae265a12e03f7b9c5656e7aa74137223e603cc3cfcc2828dda1af5479R398-R405 could be moved into a constructor.

Also has the added benefit of offloading from the `snapshot_utils` module as it's growing rather large.

_Originally posted by @carllin in https://github.com/solana-labs/solana/pull/18504#discussion_r673756619_

**Comment by snOm3ad** [comment]
@brooksprumo I submitted a pull request for this issue, please feel free to take a look at it whenever you have some time. I'd really appreciate any feedback you may have!
