### ISSUE TITLE
Create RFC for programs to reduce their in memory usage

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#1884]
#### Problem
Result of discussion in #1868 

Programs that store state on chain take up RAM in solana.  This RAM is fully replicated through all the validators that are validating the ledger.  Because it is fully replicated, it is expensive.  We need a design for reducing the cost of storing the state in RAM.

#### Challenges
The Account userdata that is owned by the program memory can't change unless it is by the program code only. The user can't spend the Account's coins to 0 unless the program allows it, and that would be in that Program's specific state transition.

#### Proposed Solution

This RFC needs to define way for the Program to reduce an Account's userdata to a hash (some fingerprint) of the userdata, and to restore the state that matches that hash (fingerprint) back into the same Account's userdata. To actually get some savings out of this the OS would need to provide a way for the Program to set the "used size" of the userdata vector. Then the OS can "resize" the vector and store fewer bits in memory.

**Comment by garious** [comment]
I wonder if it'd be sufficient to simply move userdata into a different data structure in the bank, so that the validator can swap it to disk.

**Comment by aeyakovenko** [comment]
@garious A local disk swap is still just fully replicated state.  Should we call it FRS instead of RAM?
