### ISSUE TITLE
Design for on-disk accounts index 

### ISSUE THREAD

**Issue by carllin** [solana-labs/solana#18854]
The accounts index for AccountsDb currently lives entirely in memory, and we are currently exploring various methods of offloading it to disk.

Essentially the functionality that we would need to replicate in any disk-based implementation would be:

1) Representing the index mapping from `Pubkey -> Vec<(Slot, AccountInfo>` on disk, where the `Vec` represents a list of slots in which `Pubkey` was updated.
2) Read: Given a pubkey `P` and a set of ancestor slots and roots `A: Vec<Slot>`, find all the `(Slot, AccountInfo)` updates on `P` for which `Slot` is a member of `A`. (This is how lookup is done on the accounts index today)
3) Update: Given a pubkey `P`, add a new `(Slot, AccountInfo)` to the existing list from 1).

@jeffwashington feel free to add to this list 😃 

For each of the following proposals I've sketched out roughly how the functionality described above would work, and also `Topics for discussion` for things I would like the group to discuss.

### Bucket Map proposal

This implementation was introduced here: https://github.com/solana-labs/solana/pull/18179. 

From the PR description itself, in this implementation:

1. Create a large set of buckets, 32k or more up front
2. Pubkeys based on their first 16 bits are stored in each bucket
3. Each bucket has two mmapped files:
        a) One representing an `index` for the various pubkeys, i.e. offsets into the "data" file
        b) A `data` file where the actual `Vec<(Slot, AccountInfo>` is stored for the corresponding `Pubkey`.

A lookup/read on a `Pubkey` works by picking a random point in the `index` file, then  linearly scanning through the `index` file until the `Pubkey` is found. We then take the offset found and lookup the corresponding spot in the `data` file.

An update for a new slot on a `Pubkey` works by performing the lookup, then inserting the extra `(Slot, AccountInfo)` into the `data` file. If the spot where the vector for this `Pubkey` outgrows the allocated space in the `data` file, then we  engage a "resizing" protocol. In this protocol:
1) Double the size of the allocated vector
2) Find a new spot in the `data` file where this larger vector can fit.
3) Copy the entire vector to the new location

#### Topics for discussion:
1.  In  today's `AccountIndex`, the index is implemented as a sharded `BTreeMap`, where each shard is its own `BTreeMap<Pubkey, RwLock<SlotList>>`. Pubkeys within the same shard only compete for the top level "shard lock" for a single lookup in the map. Once you get the lock for that pubkey, you release the top level `shard` lock and allow other operations to proceed in parallel. </br> In the `BucketMap` there is no such granularity per `pubbkey` - we need to hold the bucket lock for the entire duration of the linear scan/update procedure. This means we need a lot of buckets to reduce intra-bucket conflict.
2. The linear probe on the index might not be the fastest way to do a lookup. Jeff has already noticed some perf degradation in the Kin simulations. Either need a more efficient lookup, or a lot more buckets.
3. Sparseness of data file from a lot of runs of the "resizing protocol", there could potentially be a lot of holes.
4. All the index/data files are mmapped. If instead we had an in-memory cache/background flush model, does this do a poorer job of keeping "hot" accounts in memory and avoiding writes to disk (writes would be buffered to the cache) on the critical path. This could maybe also help with locking contention from 1) if we use nice data structures 😃 

### LSM tree based proposal like RocksDb/Sled

As various other team members like @ryoqun, @steviez, @lijunwangs  have investigated/read papers/considered issues (like 
https://github.com/solana-labs/solana/issues/17959) of LSM-tree based systems like RocksDb/Sled, thought it would be good to collectively brainstorm on this as well.

I think this could be done in two ways, based on how we want to break up the keys

#### Pubkey -> Vec<(Slot, AccountInfo)>
This is the most straightforward migration from today's `AccountIndex`. Downside is the value (the list) can be large and different modifications to the list  require an entirely separate copy of the whole list in the backing files (SST files in Rocks for instance). This might be bad for compaction.

#### (Pubkey, Slot) -> AccountInfo
1) In this model, I imagined instead of storing the entries as `Pubkey -> Vec<(Slot, AccountInfo>`, we would instead store `(Pubkey, Slot) -> AccountInfo` entries
2) Lookup for the slots of a particular `pubkey` would be based on a prefix iterator on the `pubkey`

#### Topics for discussion:
1. Prefix scan performance, how fast will lookups be?
2. Compaction performance? I think in the usual cases we should only have one entry to each `(Pubkey, Slot)` in each backing file because the updates to a pubkey within the same slot should be cached in in-memory buffers until they are flushed out into a backing file after the slot has completed replay.
3.  How fast will clean be? Clean removes unneeded/outdated `(Pubkey, Slot)` keys which will leave tombstones in an LSM-tree based solution like Rocks. If we are cleaning pretty often, there may be a lot of such tombstones. This may affect lookup performance on prefix scans and put more burden on compaction.
4. Comparison of locking performance to bucket map per for lookup/insert/update operations

**Comment by aeyakovenko** [comment]
I feel we should avoid rocks/sled, other than a good performance comparison. Having control over how the data is stored and scan will give us more flexibility down the line.

**Comment by steviez** [comment]
I'd agree that `(Pubkey, Slot) -> AccountInfo` is a better option as well; the [Rocks wiki home page](https://github.com/facebook/rocksdb/wiki) explicitly states "Optimized for storing small to medium size key-values on fast storage". As you mentioned, growing that vector once it's on disk in SST's could be painful.

> 1. Prefix scan performance, how fast will lookups be?

The RocksDB wiki has two existing benchmark pages published. Unfortunately, neither of them use our exact case:
- [This benchmark](https://github.com/facebook/rocksdb/wiki/RocksDB-In-Memory-Workload-Performance-Benchmarks) is for a completely in memory workload, which is what we're trying to get away from. However, this does show that th
- [This benchmark](https://github.com/facebook/rocksdb/wiki/performance-benchmarks) was run on more modest hardware; however, the iteration use case didn't take advantage of prefix seek which should give a boost. Also, there is something in data they list out that looks wrong (they list operations/second and microsecond/operation which should be reciprocal but are not), going to reach out to get some clarification.

> 2. Compaction performance? I think in the usual cases we should only have one entry to each `(Pubkey, Slot)` in each backing file because the updates to a pubkey within the same slot should be cached in in-memory buffers until they are flushed out into a backing file after the slot has completed replay.

Agreed, handling an entire slot in memory would be ideal. After thinking on this some more though, we don't necessarily have a knob to turn that says "flush at the end of S slots". Rather, flushes occur when memtables are full. So, I think a possible scenario is that Rocks transitions memtables while playing out one slot. I'm unsure if this scenario is what you were getting at when you said "in the usual cases"

> 3. How fast will clean be? Clean removes unneeded/outdated `(Pubkey, Slot)` keys which will leave tombstones in an LSM-tree based solution like Rocks. If we are cleaning pretty often, there may be a lot of such tombstones. This may affect lookup performance on prefix scans and put more burden on compaction.

Briefly skimming over the code again, it seems like cleans may be based on a pubkey or on a slot (please correct me if I'm mistaken). Assuming the keys are the concatenation of pubkey and slot bytes with pubkey bytes first, I'm thinking that clean-by-slot case will suffer. Although, I think bucketmap would also hit this?

> 4. Comparison of locking performance to bucket map per for lookup/insert/update operations

This one is a little tricky to answer. The Rocks team has [this blog post](https://rocksdb.org/blog/2014/05/14/lock.html) that talks about some of the optimizations they did around locking.
- Reads: Main points are that there is that reads are nearly lock free, and this is evidenced as the memory-only benchmark shows scaling well to 32-reader threads.
- Writes: Writes hit [memtables](https://github.com/facebook/rocksdb/wiki/MemTable) first; the default memtable implementation (Skiplist) is concurrency friendly.

As the author of that blog post stated, "lock contention is not a bottleneck anymore, which is shown in our memory-only benchmark". Given that we're looking to heavily utilize disk, I'd lean towards saying that sentiment applies here.
