### ISSUE TITLE
WS vs RPC desync

### ISSUE THREAD

**Issue by Fedor-sa** [solana-labs/solana#18868]
#### Problem
Hi, 
I noticed, that WS is sometimes late with Account updates. 
We wrote a script with the following logic
_Setup_
"feature-set": 4293946943,
"solana-core": "1.6.18"
RPC endpoint and WS endpoint : api.mainnet-beta.solana.com

_Steps_
1. Subscribe to `AccountSubscribe` (in particular account `58KcficuUqPDcMittSddhT8LzsPJoH46YP4uURoMo5EB`)
2. Receive WS update, print SLOT, HASH(body), timestamp
3. Send RPC requesting `getAccountInfo` for the same PubKey 
If SLOT in RPC is greater than SLOT in WS, script waits till WS provides update fir the last RPC slor

_Observed_
If we use `encoding: base64` (this account has bid data field), the output may look like
`WS SLOT:  88239644 | 6b0e73e89df091822245bae912d97d60392ae2c4ec5d9a3eb3c84b5fd85b0b51 | 11:33:15.835243 | api.mainnet-beta.solana.com
RPC SLOT:  88239655 | fbdc3e944a759450b9d52f69a77025856826dca3157cbfba73e9f94a725e638b | 11:33:16.739475 | api.mainnet-beta.solana.com
WS SLOT:  88239645 | 6b0e73e89df091822245bae912d97d60392ae2c4ec5d9a3eb3c84b5fd85b0b51 | 11:33:18.138450 | api.mainnet-beta.solana.com
WS SLOT:  88239646 | 6b0e73e89df091822245bae912d97d60392ae2c4ec5d9a3eb3c84b5fd85b0b51 | 11:33:19.535697 | api.mainnet-beta.solana.com
WS SLOT:  88239647 | e438116bc7546a9002c9bc2da9e8939015b2f3e2657ed13054718d53707beae4 | 11:33:20.911273 | api.mainnet-beta.solana.com
WS SLOT:  88239652 | e455aa576164c4bcdda9548239fe95e36510e79e57487a81881e3243c8b6d2c6 | 11:33:21.937706 | api.mainnet-beta.solana.com
WS SLOT:  88239653 | 3a8da0614fbe185c1b014c6f345668378671ba98eb9bd59985e6f101185598f3 | 11:33:23.344345 | api.mainnet-beta.solana.com
WS SLOT:  88239654 | 9af5bf15e6d722b651aa34486a2ce96a23c7b39fed40e1aaa429512bd9665d2a | 11:33:24.737837 | api.mainnet-beta.solana.com
WS SLOT:  88239655 | fbdc3e944a759450b9d52f69a77025856826dca3157cbfba73e9f94a725e638b | 11:33:26.173366 | api.mainnet-beta.solana.com
WS SLOT:  88239656 | fbdc3e944a759450b9d52f69a77025856826dca3157cbfba73e9f94a725e638b | 11:33:27.584319 | api.mainnet-beta.solana.com
RPC SLOT:  88239671 | 30449d018c663b5a7ffb50455072f4bbdff7d26477d359adb3d3f1d4b958b689 | 11:33:28.484613 | api.mainnet-beta.solana.com`

If we use `encoding: base64+zstd` which reduces amount of data to be transferred, it looks more stable but sometimes I see desync like 
`WS SLOT:  88251925 | 6bd3c0192b66a7394781c5285c4770dc9531b909867122cc7d27989edca582d6 | 13:44:17.459645 | api.mainnet-beta.solana.com
RPC SLOT:  88251926 | 6bd3c0192b66a7394781c5285c4770dc9531b909867122cc7d27989edca582d6 | 13:44:17.830741 | api.mainnet-beta.solana.com
WS SLOT:  88251935 | 6bd3c0192b66a7394781c5285c4770dc9531b909867122cc7d27989edca582d6 | 13:44:22.184094 | api.mainnet-beta.solana.com
RPC SLOT:  88251935 | 6bd3c0192b66a7394781c5285c4770dc9531b909867122cc7d27989edca582d6 | 13:44:22.562105 | api.mainnet-beta.solana.com
WS SLOT:  88251954 | 6bd3c0192b66a7394781c5285c4770dc9531b909867122cc7d27989edca582d6 | 13:44:33.936100 | api.mainnet-beta.solana.com
RPC SLOT:  88251949 | 6bd3c0192b66a7394781c5285c4770dc9531b909867122cc7d27989edca582d6 | 13:44:34.316517 | api.mainnet-beta.solana.com
WS SLOT:  88251961 | 6bd3c0192b66a7394781c5285c4770dc9531b909867122cc7d27989edca582d6 | 13:44:41.738260 | api.mainnet-beta.solana.com
RPC SLOT:  88251961 | 6bd3c0192b66a7394781c5285c4770dc9531b909867122cc7d27989edca582d6 | 13:44:42.114829 | api.mainnet-beta.solana.com
WS SLOT:  88251972 | 6bd3c0192b66a7394781c5285c4770dc9531b909867122cc7d27989edca582d6 | 13:44:50.595183 | api.mainnet-beta.solana.com
RPC SLOT:  88251972 | 6bd3c0192b66a7394781c5285c4770dc9531b909867122cc7d27989edca582d6 | 13:44:50.948605 | api.mainnet-beta.solana.com` 

#### Proposed Solution
1. Improve WS performance or
2. Maybe drop WS updates if currently relevant slot value for RPC requests is greater than slot value in WS update packets to be sent to client

**Comment by t-nelson** [comment]
`api.mainnet-beta.solana.com` is load balanced.  I'd hazard to guess what you're observing is that the node servicing your WS connection is behind the one servicing your RPC request(s)

**Comment by brianlong** [comment]
I think that Trent's hazardous guess is on the mark here.

- The load balancer (LB) won't move web sockets when the underlying validator node falls behind.
- The LB will send RPC get requests to a healthy server
- In your experiment above, you can easily be looking at data from two different servers.

The underlying cause is forking and skipped slots on the cluster. Ryo & Stephen are working on validator enhancements to reduce the skip rate. We are working on some extra RPC tooling to mitigate the forks too.

I suggest that you find a place in your code to disconnect & reconnect sockets on a regular basis. When you reconnect, you will receive a healthy server.

FWIW, Many of the app developers have stopped using sockets as much as possible and instead poll RPC with getMultipleAccounts on a reasonable interval.
