### ISSUE TITLE
zeroize ^1.4 failed to download.

### ISSUE THREAD

**Issue by ffakira** [solana-labs/solana#18966]
#### Problem
It seems that it is failing to download the latest zeroize package from Github.

```
error: failed to download `zeroize v1.4.0`

Caused by:
  unable to get package from source

Caused by:
  failed to parse manifest at `/home/${user}/.cargo/registry/src/github.com-1ecc6299db9ec823/zeroize-1.4.0/Cargo.toml

Caused by:
  feature `resolver` is required

  consider adding `cargo-features = ["resolver"]` to the manifest
```

#### Proposed Solution
My proposed solution is to downgrade `zeroize` down to 1.3 in `Cargo.lock`

```
[[package]]
name = "zeroize"
version = "1.3.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "4756f7db3f7b5574938c3eb1c117038b8e07f95ee6718c0efad4ac21508f1efd"
dependencies = [
 "zeroize_derive",
]
```

This workaround was originally suggested by geoff#8895 on Discord, so kudos for him 👍.

**Comment by CriesofCarrots** [comment]
This issue is resolved in v1.7.8 (cc https://github.com/solana-labs/solana/pull/18766), at least as far as solana-tool dependencies are concerned. Please upgrade your solana tools to v1.7.8.

Or, as you note, you can always lock v1.3 of zeroize and keep your `Cargo.lock` committed.
