### ISSUE TITLE
What is recommended value for vm.max_map_count

### ISSUE THREAD

**Issue by kucharskim** [solana-labs/solana#18967]
#### Problem

Solana crashed today with:

```
Jul 29 11:22:20 solana solana-start[1859054]: [2021-07-29T11:22:20.715384003Z ERROR solana_runtime::append_vec] Failed to map the dat
a file (size: 34619392): Cannot allocate memory (os error 12).
Jul 29 11:22:20 solana solana-start[1859054]:     
Jul 29 11:22:20 solana solana-start[1859054]:                         Please increase sysctl vm.max_map_count or equivalent for your platform.
Jul 29 11:22:20 solana solana-start[1859054]: [2021-07-29T11:22:20.717850218Z INFO  solana_metrics::metrics] datapoint: replay-loop-voting-stats vote_push_us=163i vote_send_us=0i generate_vote_us=169i update_commitment_cache_us=7i
Jul 29 11:22:20 solana solana-start[1859054]: [2021-07-29T11:22:20.717862118Z INFO  solana_metrics::metrics] datapoint: replay-loop-timing-stats total_elapsed_us=1007000i collect_frozen_banks_elapsed=250i compute_bank_stats_elapsed=12678i select_vote_and_reset_forks_elapsed=19i start_leader_elapsed=2i reset_bank_elapsed=128i voting_elapsed=31084i select_forks_elapsed=11i compute_slot_stats_elapsed=19i generate_new_bank_forks_elapsed=14390i replay_active_banks_elapsed=245878i process_gossip_duplicate_confirmed_slots_elapsed=9i process_unfrozen_gossip_verified_vote_hashes_elapsed=72i wait_receive_elapsed=700355i heaviest_fork_failures_elapsed=0i bank_count=2i process_duplicate_slots_elapsed=12i
Jul 29 11:22:20 solana solana-start[1859054]: [2021-07-29T11:22:20.737234334Z INFO  solana_metrics::metrics] datapoint: banking_stage-loop-stats id=2i process_packets_count=1i new_tx_count=0i dropped_batches_count=0i newly_buffered_packets_count=1i current_buffered_packets_count=1i rebuffered_packets_count=0i consume_buffered_packets_elapsed=0i process_packets_elapsed=6i handle_retryable_packets_elapsed=0i filter_pending_packets_elapsed=0i packet_duplicate_check_elapsed=4i packet_conversion_elapsed=0i transaction_processing_elapsed=0i
Jul 29 11:22:29 solana systemd[1]: solana.service: Main process exited, code=exited, status=1/FAILURE
```

#### Proposed Solution

Update `docs/src/running-validator/validator-start.md` with recommended value and/or add warning in the code during early startup to check current `vm.max_map_count` value and print recommended minimal value (but do not modify system settings behind operators back!).

**Comment by t-nelson** [comment]
Which cluster is this?

Software version?

Can you upload more log (the hour prior to the crash) somewhere so we can see if the validator was operating normally?

**Comment by kucharskim** [comment]
> Which cluster is this?

Not sure what means cluster in this context.

> Software version?

solana-cli 1.6.16 (src:devbuild; feat:2463141184)
solana-validator 1.6.16 (src:devbuild; feat:2463141184)

> Can you upload more log (the hour prior to the crash) somewhere so we can see if the validator was operating normally?

Sorry, logs rotated and they are gone.

**Comment by kucharskim** [comment]
I have only few seconds before and after the crash.
[solana-journalctl-vm-max_map_count-crash-20210729.log.gz](https://github.com/solana-labs/solana/files/6905570/solana-journalctl-vm-max_map_count-crash-20210729.log.gz)

**Comment by solauto** [comment]
Here's a similar crash from 1.9.29, mainnet.  I can add more log depth before/after if helpful.

[crash.tar.gz](https://github.com/solana-labs/solana/files/8969197/crash.tar.gz)
