### ISSUE TITLE
Test fail, and meaning of balance value.

### ISSUE THREAD

**Issue by djKooks** [solana-labs/solana#190]
Hello,
I just run `cargo test` with newest repo, but caused new fail.

```
...
test tpu::tests::test_replicate ... ok
test tpu::tests::test_to_packets ... ok
test thin_client::tests::test_multi_node ... FAILED

failures:

---- thin_client::tests::test_multi_node stdout ----
        thread 'thin_client::tests::test_multi_node' panicked at 'assertion failed: `(left == right)`
  left: `0`,
 right: `500`', src/thin_client.rs:343:9


failures:
    thin_client::tests::test_multi_node
```

It looks like problem is 'replicant_balance' has zero value.
Also, because I'm still not well in solana, what is difference between 'replicant_balance' and 'leader_balance'?

Thanks.

**Comment by djKooks** [comment]
@garious @aeyakovenko is it solved?

**Comment by garious** [comment]
Test moved to integration tests. I shouldn't be in the way anymore.
