### ISSUE TITLE
solana-test-validator v1.7.9 fails to run, tries to lock test ledger directory twice

### ISSUE THREAD

**Issue by NearlyAlwaysThere** [solana-labs/solana#19006]
#### Problem

solana-test-validator v1.7.9 errors out when trying to run it

#### Proposed Solution

don't try to lock it twice

**Comment by levicook** [comment]
I'm running a fresh install of 1.7.9 and see related problems w/ managing the ledger lock.

```bash
$ solana-test-validator
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', validator/src/bin/solana-test-validator.rs:294:71
```

**Comment by CriesofCarrots** [comment]
Fixed in https://github.com/solana-labs/solana/pull/19007
