### ISSUE TITLE
Feature Proposal: RPC for solana-test-validator to adjust clock

### ISSUE THREAD

**Issue by aaronovz1** [solana-labs/solana#19005]
#### Problem
While using Anchor and writing unit tests it's useful to be able to simulate "blocks" and "time" being increased by a specified amount programatically. For example, in a staking program where rewards are unlocked linearly over a period time, instead of using `sleep` the validator could be progressed to a specified unix timestamp so the client doesn't need to wait the real amount of time.

#### Proposed Solution
Add an RPC to adjust the clock/slots.

**Comment by ppoliani** [comment]
@aaronovz1 have you found any workarounds which you could share?

**Comment by aaronovz1** [comment]
Sorry, I didn't end up finding a workaround. I think this would still be a useful feature to have someday.
