### ISSUE TITLE
Adding a TokenInfo method (similarly to Ethereum EIP-747)

### ISSUE THREAD

**Issue by ffakira** [solana-labs/solana#19001]
#### Problem
Implement [EIP-747](https://eips.ethereum.org/EIPS/eip-747) similarly how Ethereum does it, to be integrated with wallet providers.

#### Proposed Solution
Request:
```json
curl http://api.mainnet-beta.solana.com/ -X Post -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "token_watchAsset",
    "params": ["BQcdHdAQW1hczDbBi9hiegXAR7A98Q9jx3X3iBBBDiq4"]
  }
```

Result:
```json
{
  "jsonrpc": "2.0",
  "result": {
    "price": 1.01,
    "rank": 3,
    "24h_volume": "47.8B",
    "market_cap": "62.4B",
    "overview": {
      "token": "Wrapped USDT (Sollet)",
      "address": "BQcdHdAQW1hczDbBi9hiegXAR7A98Q9jx3X3iBBBDiq4",
      "current_supply": 356033570.000000,
      "decimals": 6,
      "bridge_contract": "0xeae57ce9cc1984f202e15e038b964bb8bdf7229a",
      "logo_uri": "https://raw.githubusercontent.com/solana-labs/token-list/main/assets/mainnet/BQcdHdAQW1hczDbBi9hiegXAR7A98Q9jx3X3iBBBDiq4/logo.png"
    }
  }
}
```

And potentially call via @solana/web3.js `TokenInfo<T>: { method: string; address: PublicKey }`
```ts
/*
 * @dev Adds the token asset to the wallet provider
 */
let usdt: TokenInfo = await solanaWeb3.TokenInfo("token_watchAsset", "BQcdHdAQW1hczDbBi9hiegXAR7A98Q9jx3X3iBBBDiq4");
```

**Comment by t-nelson** [comment]
I think this feature might more appropriately fit into https://github.com/project-serum/sol-wallet-adapter

**Comment by ffakira** [comment]
> I think this feature might more appropriately fit into https://github.com/project-serum/sol-wallet-adapter

I don't think so. Solana still need to expose RPC endpoint on their side, in order for other wallet providers to consume. After all, a wallet provider is a bundled up RPC endpoints, that is friendly for end users.
