### ISSUE TITLE
RPC Client returning incorrect error?

### ISSUE THREAD

**Issue by piazzatron** [solana-labs/solana#19019]
#### Problem

https://github.com/solana-labs/solana/blob/d5961e9d9f005966f409fbddd40c3651591b27fb/client/src/rpc_custom_error.rs#L14

There exists an error code `JSON_RPC_SERVER_ERROR_TRANSACTION_PRECOMPILE_VERIFICATION_FAILURE` which appears unused, at least in this file; it seems that `JSON_RPC_SERVER_ERROR_TRANSACTION_SIGNATURE_VERIFICATION_FAILURE` may be accidentally returned in it's place:

https://github.com/solana-labs/solana/blob/d5961e9d9f005966f409fbddd40c3651591b27fb/client/src/rpc_custom_error.rs#L111

```
            RpcCustomError::TransactionPrecompileVerificationFailure(e) => Self {
                code: ErrorCode::ServerError(
                    // Should this be the the precompile error rather than signature verification failure?
                    JSON_RPC_SERVER_ERROR_TRANSACTION_SIGNATURE_VERIFICATION_FAILURE, // Intentional?
                ),
                message: format!("Transaction precompile verification failure {:?}", e),
                data: None,
            },
```

#### Proposed Solution

Happy to open a PR correcting the error type if this indeed a bug!

**Comment by CriesofCarrots** [comment]
Yep, that looks like a bug that's been there since that error was added 🤕 
Technically that will be a breaking change, but please so open a PR and we'll decide how to roll out. Thank you!
