### ISSUE TITLE
RpcPubsub: Finalized bank notifications may miss updates

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#19040]
#### Problem
Rpc pubsub bank-based notifications are triggered at the end of AggregateCommitmentService runs: https://github.com/solana-labs/solana/blob/master/core/src/replay_stage.rs#L1570
These are in turn triggered by replay-stage votes: https://github.com/solana-labs/solana/blob/d8984cb0f40eafbbf8aa2a95f3c0e43343e80230/core/src/replay_stage.rs#L1570

The highest_confirmed_root passed to rpc-pubsub is whatever the cluster happens to have confirmed at the time of that vote, and only that slot is notified. Since there is no guarantee that votes are happening on the same cadence as cluster confirmations, finalized subscriptions could miss an update if the time to vote spans two cluster-confirmed roots.

#### Proposed Solution
When a new highest_confirmed_root is detected, notify for all ancestors since the previous highest_confirmed_root to catch any that were missed.
(Also consider refactoring and simplifying the interface between the commitment_service and rpc_subscriptions)

cc @carllin @lijunwangs

**Comment by great9** [comment]
bump
