### ISSUE TITLE
(wip) packet drop investigation

### ISSUE THREAD

**Issue by ryoqun** [solana-labs/solana#19079]
#### Problem

discord discussions for reference:
https://discord.com/channels/428295358100013066/478692221441409024/870707709639548989

**Comment by ryoqun** [comment]
v1.7:

![image](https://user-images.githubusercontent.com/117807/128316896-c93c7c57-d0e7-4d3b-8e60-f727b20be8b9.png)

master:

```
$  /proc/$(pgrep -f solana-validator | awk '{print $1}')/exe --version
solana-validator 1.8.0 (src:dfe99efa; feat:1693936682)
$ git show dfe99efa -q
commit dfe99efa7cfaa14390844e7c6cb6594eec3d1afc (origin/master, origin/HEAD)
Author: Jeff Washington (jwash) <75863576+jeffwashington@users.noreply.github.com>
Date:   Wed Aug 4 21:58:53 2021 -0500

    introduce AccountsIndex::default_for_tests() (#19067)
```

![image](https://user-images.githubusercontent.com/117807/128317220-9c6be1a1-7cf7-43ae-adfe-e8c495fc9390.png)

**Comment by ryoqun** [comment]
status: after another round of test, my packet drop monitoring mechanism had a bug leading to false positive of packet drops.... specifically, `conntrack -Z` don't work as intended..

so, it turns out nodes located inside gce don't exhibit packet drops. hope the script is finally got robust; will soon field-test on testnet using it.

**Comment by ryoqun** [comment]
well, there is really a mysterious phenomenon on testnet.

Clearly, testnet's skip rate corresponds to mysterious broadcast/retransmit incoming bandwidth reduction.

here's skip rate:

![image](https://user-images.githubusercontent.com/117807/129360607-8ff88e86-bda8-4296-a36e-4abe3953c81d.png)

and this is incoming packets (violet (local listening port 8002) is `tvu` and skyblue (local listening port 8003) is `tvu_forward`), collected manually from my testnet staked node.

it seems that there was 3 incidents where testnet node experienced quite sudden incoming packet reduction for some reason. and it causes cluster-wide repairs and ultimately bad skip rate.

![image](https://user-images.githubusercontent.com/117807/129360730-8c2a25db-d39f-499c-9b52-5420120b3229.png)

**Comment by behzadnouri** [comment]
> it seems that there was 3 incidents where testnet node experienced quite sudden incoming packet reduction for some reason.

are those near epoch boundaries? or new releases?

**Comment by ryoqun** [comment]
> are those near epoch boundaries?

nope (skip rate fluctuation in the first chart indirectly indicates epoch boundaries)

> new releases?

nope.

v1.7.9 is 2021-08-02 15:00 UTC: https://discord.com/channels/428295358100013066/594138785558691840/871770575696195604 => out of chart
v1.7.10 is 2021-08-12 07:00 UTC:  https://discord.com/channels/428295358100013066/594138785558691840/875271946382761996 => close to most recent spike but it's not aligned.

**Comment by ryoqun** [comment]
hmm

this is number of restarts (this seems a bit correlated?; cross hair is on v1.7.10 release announcement; i excluded outliers, repeating restarts.)

![image](https://user-images.githubusercontent.com/117807/129367136-4c957184-0a56-4824-9862-27f2577532f4.png)

**Comment by behzadnouri** [comment]
This is `cluster_info-num_nodes::broadcast_count` which shows some volatility at the same spots that there was a drop in packets:

![broadcast-count](https://user-images.githubusercontent.com/1288998/129368812-d2ac01d7-944a-41e9-a144-a1c9418eba82.png)

**Comment by ryoqun** [comment]
@behzadnouri that graph is interesting too! yeah, restarts/broadcast_count could be strongly correlated (okay, i strictly aligned those charts this time...): 

incoming turbine packets to my node:

![image](https://user-images.githubusercontent.com/117807/129375688-0ff209f0-6385-44ee-8a07-642acdffe88e.png)

recovered shreds for my node (indirect indicator for turbine quality)

![image](https://user-images.githubusercontent.com/117807/129376777-3bc55baa-972b-43bf-aa62-4e5d0ee9d3a2.png)

cluster wide restarts counts:

![image](https://user-images.githubusercontent.com/117807/129375934-e1f6ccbc-3df6-4197-86b0-59ab567a174f.png)

cluster wide packets relating to retransmission 

![image](https://user-images.githubusercontent.com/117807/129375997-2f292b05-a569-4c95-b069-056994f83d23.png)

well, i thought node restarts should be harmless... after catch-up, the internal state should be identical as if no restarts for the node? is there something to ring in your mind regarding (restarts <=> turbine reduction)?

and with these charts combined, maybe repair increase can't simply explained by temporary increase of restarting (= catching-up/repairing) nodes?

But, I wonder why the strongest spike of v1.7.10 release ann. (and large restarts/broadcast_count reduction) hasn't caused more bad skip-rate??

maybe, there could be node for unexpectedly weighted turbine?

**Comment by ryoqun** [comment]
also, this is the pace of block proposal by leaders and # of shreds.

note that shred number is affected by bad skip-rate (forky network => more vote lockout => less transaction => less shreds):

![image](https://user-images.githubusercontent.com/117807/129380773-4dfc6d51-6cb9-4667-b7fd-ea04453ca0e2.png)

as you can see, the pace of block proposal is flat (means, the same number of leaders were online) => so, I'm guessing this is related to transmission.

**Comment by ryoqun** [comment]
also, another remaining mystery is that why turbine doesn't recover after awhile..?

**Comment by behzadnouri** [comment]
> is there something to ring in your mind regarding (restarts <=> turbine reduction)?

Nothing immediate. But I wonder how much these plots would change if we limit the metrics average to only top staked nodes since turbine prioritizes by stake. Also, just guessing but, the fact that after a restart some nodes might be slow to catch-up (and so additional repair load) might play a part here.

**Comment by ryoqun** [comment]
> so, it turns out nodes located inside gce don't exhibit packet drops. hope the script is finally got robust; will soon field-test on testnet using it.

finally, I managed to capture packet loss of ~3-5% turbine packet loss per hop with some reliability this time over long duration.. I think this number isn't so bad?

purple is retransmission packet bytes from sender's node perspective
blue is retransmission packet bytes from receiver's node perspective

stake ratio for both side of nodes here is are like 1:10~12. so wider difference for each direction (node small -> node large, node small <- node large).

![image](https://user-images.githubusercontent.com/117807/129437813-b020b83b-0ade-4d4f-ad1c-4d9837c30109.png)


so roughly speaking, assuming testnet is currently comprised of 2 layers of turbine, this indicates 3 hops overall? (leader => layer 0 => layer 1)? That means shred drop rate is ~9-15% overall.

So, considering turbine's erasure code, we can tolerate up to 35% of extra shred nonavailability, converting back to 11% packet loss (== delinquent stakes).

note that I need to further investigate how spiky these drops in short time perspective.

**Comment by ryoqun** [comment]
oh, I think i finally getting a clue:

the following is incoming turbine packets by remote ip from conntrack. so, this isn't sampled (= influxdb), rather a complete survey. out of it, i randomly picked nodes for graph plot and specifically selected top of 11 staked nodes.

below circle is around 5000 SOL staked nodes. upper circle is around 46000 SOL stakes nodes. both circle are showing correct bandwidth increase factor according to stake ratio (1:9).

however, rest of top-staked nodes are buried or under performant according their stake:

```
[1] pry(main)> 1348755.04111866 / 46060.912896252
=> 29.28198674995017
[2] pry(main)> 698008.722627206 / 46060.912896252
=> 15.15403579167888
[3] pry(main)> 529052.162400336 / 46060.912896252
=> 11.48592438000475
[4] pry(main)> 257027.105823818 / 46060.912896252
=> 5.580156572292609
[5] pry(main)> 188350.983259204 / 46060.912896252
=> 4.0891717383771224


   2227   9YVpEeZf8uBoUtzCFC6SSFDDqPt16uKFubNhLvGxeUDy  2QBvjQw7bEfoo785Y4ECEdo1RGDQCvGxTPsH1nYCwr5n  100%  89413005 (-10)  89412961 ( -7)  24.12%   117425   1.7.10  101534.318495044 SOL (0.13%)
   2228   NNetet8BiymZxMBWLRPCcNGcBPZDBeEcpgtfTSwdFPX   GFA6pjxZziBivQftE4XrtL3rtgvAbrF8VscSJSETbM1   100%  89413015 (  0)  89412959 ( -9)  26.79%   109655   1.7.10  111097.853353828 SOL (0.15%)
   2229   B2UcYy4WiS1fSYKbMPeAKZoCEzgfQKKt5QBAA8NXLvpZ  5m2h5u5gaCb8d4iG2K1oKGrxDu99UZ1GJbFMJNFbCPmV   10%  89413013 ( -2)  89412961 ( -7)  51.33%   109844    1.7.8  123441.663474085 SOL (0.16%)
   2230   9QxCLckBiJc783jnMvXZubK4wH86Eqqvashtrwvcsgkv  69rUCD1qk6hJ3AqEkCi236QaceHTBSv1isiCEW6EZnVa  100%  89413015 (  0)  89412968 (  0)  28.12%   114551   1.7.10  128104.018147524 SOL (0.17%)
   2231   D52Q6Ap8RVMw1EvJYTdEABP6M5SPg98aToMcqw7KVLD9  A93XLdBKfc4pwEMAvdFeyxnF6HauN5erNDFbUsemWiaB  100%  89413005 (-10)  89412960 ( -8)  29.71%   109155   1.7.10  185198.559130598 SOL (0.24%)
   2232   6ZEbKFxTjEKGC9HUqzy9z4ccJ8Aq3ktPKEzHGDosQJo4  EykacQne8ZwcuucW3uHJ9TgFJGyofDwortRggzsGHtW2    1%  89413015 (  0)  89412968 (  0)  67.84%   114966   1.7.10  187838.241354718 SOL (0.25%)
   2233   BYxEvmSwA1o3vJGhooJoReSjrzou8A9h1TZX9S4xomHP  HApadLChwYdaEy5N1QDZsPLN1372naJfDmBbdV1WJWX6  100%  89413015 (  0)  89412959 ( -9)  26.75%    99345    1.7.8  188350.983259204 SOL (0.25%)
   2234   GcibmF4zgb6Vr4bpZZYHGDPZNWiLnBDUHdpJZTsTDvwe  73zB51M61WsAUZZuKYGStsn1bBhBoEEoQmXLznJphJBo  100%  89413015 (  0)  89412961 ( -7)  30.79%   116627   1.7.10  257027.105823818 SOL (0.34%)
   2235   J7v9ndmcoBuo9to2MnHegLnBkC9x3SAVbQBJo5MMJrN1  HiFjzpR7e5Kv2tdU9jtE4FbH1X8Z9Syia3Uadadx18b5   10%  89413015 (  0)  89412961 ( -7)  45.35%   114384   1.7.10  529052.162400336 SOL (0.69%)
   2236   3iPu9xQ3mCFmqME9ZajuZbFHjwagAxhgfTxnc4pWbEBC  9TNxBa3Cda5zrLxZkvWpxNtNpdJ3QsTcdqTFc1M33G3x   10%  89413005 (-10)  89412960 ( -8)  24.88%   115483   1.7.10  698008.722627206 SOL (0.92%)
   2237   8RsYRsi6f3hiK4EhyLS22Cy5KkrNbuidVYmsaYR1Xx78  ASDjo1U2bJfThuZ1ftJ7Ku9XEz7Gn8gjEMiCoY7pRRvQ    8%  89413015 (  0)  89412959 ( -9)  25.53%   112520   1.7.10  1348755.04111866 SOL (1.77%)

```

For example, 8RsYRsi6f3hiK4EhyLS22Cy5KkrNbuidVYmsaYR1Xx78 must provide the whooping 30x of bandwidth according to stake. but you can't see any line at the level (60M in the chart's scale).

![image](https://user-images.githubusercontent.com/117807/129439536-967b16d7-6056-44c5-bf6a-8dda7819dd9d.png)


I think this is unfair tightening the prior 35% extra turbine bandwidth budget.

**Comment by ryoqun** [comment]
> For example, 8RsYRsi6f3hiK4EhyLS22Cy5KkrNbuidVYmsaYR1Xx78 must provide the whooping 30x of bandwidth according to stake. but you can't see any line at the level (60M in the chart's scale).

well, I think this underperformance is kind of expected: 
![image](https://user-images.githubusercontent.com/117807/129444293-e31f3164-0231-4ffd-abdf-8aef570aa13e.png)

this is outgoing turbine retransmission packet bytes per 10 min for my test node (ryo1vM57RXAayYZhCK6k13d5uS4b9tfH7BhScgqtBCx, 69999.99771712)

so due to large node size of the testnet cluster, even 0.09% node must attain constant outgoing throughput of 53 Mbps:

```
[9] pry(main)> (4000000000 / 600) * 8 / 1000000
=> 53
```

then that means the highest staked node (8RsYRsi6f3hiK4EhyLS22Cy5KkrNbuidVYmsaYR1Xx78) must provide around 1Gbps with turbine traffic alone:

```
[6] pry(main)> 1348755.04111866 / 69999.99771712
=> 19.267929787214737
[10] pry(main)> 53 * 19
=> 1007
```

**Comment by ryoqun** [comment]
well, I lied again. in short, it looks like packet drops / linear stake-weighted bandwidth allocation were just false alarms.

what I'm thinking to explore next (getting short of ideas):

- could repair possibly interrupt the turbine if it's taking longer than expected? (causing the cluster-wide repair)
- add metric to record actually received shred count regardless `is_full` or not for each slot
- introduce sampled (every 1000 slot) comprehensive metrics to track shred propagation
- lift repair budget (seems this is necessarily slowing down things in the case of cluster-wide repair)
- dump large txes (ie with memo ix) against testnet and see how testnet reacts to it.

**Comment by ryoqun** [comment]
also:

- could the testnet cluster have any lingering positive feedback? slow turbine => more repair => instaneous turbine by nearby leaders => more slot turbine => more repair.. like

**Comment by ryoqun** [comment]
yet more:

- what if we level stake weights evenly by asking high staked validators? (yeah, will take some time).

**Comment by ryoqun** [comment]
it looks like i finally caught where the turbine pipe thing is leaking:

there is whopping 75%-99% (and more?) persistent (not spiky) packet drop for this particular validator

the following is bi-directional traffic between the retransmit port and tvu_forward:

Target <=> RefA (RefA => Target; Target's downlink is severely throttled)

![image](https://user-images.githubusercontent.com/117807/130481107-8b01110f-0f95-4197-96ac-e767ba51ea0a.png)

Target <=> RefB (RefB => Target; Target's downlink is severely throttled)

![image](https://user-images.githubusercontent.com/117807/130481647-71c2e268-5a12-45bf-8f08-8d9b1527a8ed.png)

as a comparison, this is expected chart (RefA <=> RefB):

![image](https://user-images.githubusercontent.com/117807/130482023-f1847da8-cac6-4983-b8c5-b1cc89894297.png)

**Comment by ryoqun** [comment]
it seems that sizable portion of ikoula's nodes are throttled?

**Comment by ryoqun** [comment]
it looks like only subset of routes are severely throttled:

ideal look (almost no packet drops):

![image](https://user-images.githubusercontent.com/117807/131209229-b83053fa-a24c-4f48-be57-2c3cecb0aefa.png)

slightly dropped: there's small gap in the upper pair of lines (ignore outlifers due to maybe overflow...)

![image](https://user-images.githubusercontent.com/117807/131209266-bd73337e-cda1-4421-a28c-d555cb11b56b.png)


only one direction of packets are dropped hard; and there's odd ups & downs. maybe DCs are meddling with particular network path?

![image](https://user-images.githubusercontent.com/117807/131209306-ab9a21e0-e8d3-461a-956d-ebcbc0a617fe.png)

**Comment by ryoqun** [comment]
unfortunately, these observed degraded network condition transitions don't correlate to the cluster-wide symptom:

![image](https://user-images.githubusercontent.com/117807/131209454-ef93f5b6-d585-4510-aaca-391ab4cb5903.png)

**Comment by ryoqun** [comment]
![image](https://user-images.githubusercontent.com/117807/131480419-fbf6b44e-7512-48de-b357-aede9398c449.png)


![image](https://user-images.githubusercontent.com/117807/131480552-bf399bdc-d72e-4fec-85b4-41c2adc4f170.png)

**Comment by ryoqun** [comment]
![image](https://user-images.githubusercontent.com/117807/131481157-64e2a0ae-2f5f-4833-a37c-ed7eba928956.png)

**Comment by ryoqun** [comment]
I think there's still massive packet drops? (turbine between; ikoula <=> hetzner)

```
SELECT sum("l8010r8005i_bytes") AS "sum_l8002r8005i_bytes", sum("l8013r8002o_bytes") AS "sum_l8013r8002o_bytes" FROM "tds"."autogen"."udp_lport_rport_test" WHERE time > :dashboardTime: AND time < :upperDashboardTime: AND "local_host_id"='8RsYRsi6f3hiK4EhyLS22Cy5KkrNbuidVYmsaYR1Xx78' AND "remote_host_id"='EKxYfdfsxAR6BSpYKW3LD63UMn9ZWYUNRJ7GUonWSdrK' GROUP BY time(5m), "remote_host_id", "local_host_id" FILL(null)


SELECT sum("l8005r8010o_bytes") AS "sum_l8005r8002o_bytes", sum("l8002r8013i_bytes") AS "sum_l8002r8013i_bytes"  FROM "tds"."autogen"."udp_lport_rport_test" WHERE time > :dashboardTime: AND time < :upperDashboardTime: AND "local_host_id"='EKxYfdfsxAR6BSpYKW3LD63UMn9ZWYUNRJ7GUonWSdrK' AND "remote_host_id"='8RsYRsi6f3hiK4EhyLS22Cy5KkrNbuidVYmsaYR1Xx78' GROUP BY time(5m), "remote_host_id", "local_host_id" FILL(null)
```

![image](https://user-images.githubusercontent.com/117807/133097671-f7a20dcb-e19d-4831-b479-45940fbe0875.png)

![image](https://user-images.githubusercontent.com/117807/133097837-4f0b2406-e474-4d39-af90-98872146dc11.png)

**Comment by ryoqun** [comment]
gcp <=> hetzner (similar chart indicates few packets drops):

```
SELECT sum("l8005r8010o_bytes") AS "sum_l8005r8010o_bytes", sum("l8002r8013i_bytes") AS "sum_l8002r8013i_bytes" FROM "tds"."autogen"."udp_lport_rport_test" WHERE time > :dashboardTime: AND time < :upperDashboardTime: AND "remote_host_id"='8RsYRsi6f3hiK4EhyLS22Cy5KkrNbuidVYmsaYR1Xx78' AND "local_host_id"='CPDrAt4osz1Bi7RRh6KYNszXPEqsmARy7Eimaz6ViXxw' GROUP BY time(5m), "remote_host_id", "local_host_id" FILL(null)

SELECT sum("l8010r8005i_bytes") AS "sum_l8010r8005i_bytes", sum("l8013r8002o_bytes") AS "sum_l8013r8002o_bytes" FROM "tds"."autogen"."udp_lport_rport_test" WHERE time > :dashboardTime: AND time < :upperDashboardTime: AND "local_host_id"='8RsYRsi6f3hiK4EhyLS22Cy5KkrNbuidVYmsaYR1Xx78' AND "remote_host_id"='CPDrAt4osz1Bi7RRh6KYNszXPEqsmARy7Eimaz6ViXxw' GROUP BY time(5m), "remote_host_id", "local_host_id" FILL(null)
```

![image](https://user-images.githubusercontent.com/117807/133099716-2b2c8d3c-7e42-498b-97a2-aff5055b6ae2.png)

![image](https://user-images.githubusercontent.com/117807/133099918-7b41a804-ac19-42ca-8ce5-40f0603827be.png)

**Comment by ryoqun** [comment]
ikoula <=> ikoula

GOOD (almost no packet drops for both direction)

![image](https://user-images.githubusercontent.com/117807/133190628-10953a55-66e5-4226-96b3-1507e12fdc35.png)

```
SELECT sum("l8005r8002o_bytes") AS "sum_l8005r8002o_bytes", sum("l8002r8005i_bytes") AS "sum_l8002r8005i_bytes" FROM "tds"."autogen"."udp_lport_rport_test" WHERE time > :dashboardTime: AND time < :upperDashboardTime: AND ("local_host_id"='EKxYfdfsxAR6BSpYKW3LD63UMn9ZWYUNRJ7GUonWSdrK' OR "local_host_id"='8SRKNfvMerfA1BdU79CAwU4wNfjnDvFrBo3o5f5TS4uv') AND ("remote_host_id"='EKxYfdfsxAR6BSpYKW3LD63UMn9ZWYUNRJ7GUonWSdrK' OR "remote_host_id"='8SRKNfvMerfA1BdU79CAwU4wNfjnDvFrBo3o5f5TS4uv') GROUP BY time(5m), "remote_host_id" FILL(0)
```

ikoula <=> TERASWITCH

BAD (some packet drops for TERASWITCH => ikoula)

```

SELECT sum("l8005r8002o_bytes") AS "sum_l8005r8002o_bytes", sum("l8002r8005i_bytes") AS "sum_l8002r8005i_bytes" FROM "tds"."autogen"."udp_lport_rport_test" WHERE time > :dashboardTime: AND time < :upperDashboardTime: AND ("local_host_id"='EKxYfdfsxAR6BSpYKW3LD63UMn9ZWYUNRJ7GUonWSdrK' OR "local_host_id"='J7v9ndmcoBuo9to2MnHegLnBkC9x3SAVbQBJo5MMJrN1') AND ("remote_host_id"='EKxYfdfsxAR6BSpYKW3LD63UMn9ZWYUNRJ7GUonWSdrK' OR "remote_host_id"='J7v9ndmcoBuo9to2MnHegLnBkC9x3SAVbQBJo5MMJrN1') GROUP BY time(5m), "remote_host_id" FILL(0)
```

![image](https://user-images.githubusercontent.com/117807/133191064-1c222222-bb62-406d-a05a-4658ef09fe6d.png)

**Comment by ryoqun** [comment]
another variant of https://github.com/solana-labs/solana/issues/19079#issuecomment-918225450

 (turbine between; ikoula node 2 <=> hetzner)



![image](https://user-images.githubusercontent.com/117807/133191782-2d81b194-89f5-4916-9e8b-138a542a4983.png)


![image](https://user-images.githubusercontent.com/117807/133191846-6f292c6e-7b5b-44ba-a3a1-b3eed87d96b2.png)


```
SELECT sum("l8005r8010o_bytes") AS "sum_l8005r8002o_bytes", sum("l8002r8013i_bytes") AS "sum_l8002r8013i_bytes"  FROM "tds"."autogen"."udp_lport_rport_test" WHERE time > :dashboardTime: AND time < :upperDashboardTime: AND "local_host_id"='8SRKNfvMerfA1BdU79CAwU4wNfjnDvFrBo3o5f5TS4uv' AND "remote_host_id"='8RsYRsi6f3hiK4EhyLS22Cy5KkrNbuidVYmsaYR1Xx78' GROUP BY time(5m), "remote_host_id", "local_host_id" FILL(null)

SELECT sum("l8010r8005i_bytes") AS "sum_l8002r8005i_bytes", sum("l8013r8002o_bytes") AS "sum_l8013r8002o_bytes" FROM "tds"."autogen"."udp_lport_rport_test" WHERE time > :dashboardTime: AND time < :upperDashboardTime: AND "local_host_id"='8RsYRsi6f3hiK4EhyLS22Cy5KkrNbuidVYmsaYR1Xx78' AND "remote_host_id"='8SRKNfvMerfA1BdU79CAwU4wNfjnDvFrBo3o5f5TS4uv' GROUP BY time(5m), "remote_host_id", "local_host_id" FILL(null)
```


ikoula node 2 <=> terraswitch

```
SELECT sum("l8005r8002o_bytes") AS "sum_l8005r8002o_bytes", sum("l8002r8005i_bytes") AS "sum_l8002r8005i_bytes" FROM "tds"."autogen"."udp_lport_rport_test" WHERE time > :dashboardTime: AND time < :upperDashboardTime: AND ("local_host_id"='J7v9ndmcoBuo9to2MnHegLnBkC9x3SAVbQBJo5MMJrN1' OR "local_host_id"='8SRKNfvMerfA1BdU79CAwU4wNfjnDvFrBo3o5f5TS4uv') AND ("remote_host_id"='J7v9ndmcoBuo9to2MnHegLnBkC9x3SAVbQBJo5MMJrN1' OR "remote_host_id"='8SRKNfvMerfA1BdU79CAwU4wNfjnDvFrBo3o5f5TS4uv') GROUP BY time(5m), "remote_host_id" FILL(0)
```
![image](https://user-images.githubusercontent.com/117807/133191678-2f471af5-0968-4510-b524-ae8e20508fd0.png)

**Comment by ryoqun** [comment]
```
SELECT sum("l8000o_bytes") AS "sum_l8000o_bytes", sum("l8000i_bytes") AS "sum_l8000i_bytes", sum("l8001i_bytes") AS "sum_l8001i_bytes", sum("l8001o_bytes") AS "sum_l8001o_bytes", sum("l8002i_bytes") AS "sum_l8002i_bytes", sum("l8003i_bytes") AS "sum_l8003i_bytes", sum("l8004i_bytes") AS "sum_l8004i_bytes", sum("l8005o_bytes") AS "sum_l8005o_bytes", sum("l8006i_bytes") AS "sum_l8006i_bytes", sum("l8006o_bytes") AS "sum_l8006o_bytes", sum("l8007i_bytes") AS "sum_l8007i_bytes", sum("l8007o_bytes") AS "sum_l8007o_bytes", sum("l8008o_bytes") AS "sum_l8008o_bytes", sum("l8009i_bytes") AS "sum_l8009i_bytes", sum("l8009o_bytes") AS "sum_l8009o_bytes", sum("l8010i_bytes") AS "sum_l8010i_bytes", sum("l8011i_bytes") AS "sum_l8011i_bytes", sum("l8012i_bytes") AS "sum_l8012i_bytes", sum("l8013i_bytes") AS "sum_l8013i_bytes", sum("l8005i_bytes") AS "sum_l8005i_bytes", sum("l8008i_bytes") AS "sum_l8008i_bytes" FROM "tds"."autogen"."udp_lport_test" WHERE time > :dashboardTime: AND time < :upperDashboardTime: AND "local_host_id"='J7v9ndmcoBuo9to2MnHegLnBkC9x3SAVbQBJo5MMJrN1' GROUP BY time(1m) FILL(null)
```

![image](https://user-images.githubusercontent.com/117807/134307564-9edd4015-525b-4abf-bf69-70574c896ca4.png)

**Comment by ryoqun** [comment]
> SELECT sum("l8000o_bytes") AS "sum_l8000o_bytes", sum("l8000i_bytes") AS "sum_l8000i_bytes", sum("l8001i_bytes") AS "sum_l8001i_bytes", sum("l8001o_bytes") AS "sum_l8001o_bytes", sum("l8002i_bytes") AS "sum_l8002i_bytes", sum("l8003i_bytes") AS "sum_l8003i_bytes", sum("l8004i_bytes") AS "sum_l8004i_bytes", sum("l8005o_bytes") AS "sum_l8005o_bytes", sum("l8006i_bytes") AS "sum_l8006i_bytes", sum("l8006o_bytes") AS "sum_l8006o_bytes", sum("l8007i_bytes") AS "sum_l8007i_bytes", sum("l8007o_bytes") AS "sum_l8007o_bytes", sum("l8008o_bytes") AS "sum_l8008o_bytes", sum("l8009i_bytes") AS "sum_l8009i_bytes", sum("l8009o_bytes") AS "sum_l8009o_bytes", sum("l8010i_bytes") AS "sum_l8010i_bytes", sum("l8011i_bytes") AS "sum_l8011i_bytes", sum("l8012i_bytes") AS "sum_l8012i_bytes", sum("l8013i_bytes") AS "sum_l8013i_bytes", sum("l8005i_bytes") AS "sum_l8005i_bytes", sum("l8008i_bytes") AS "sum_l8008i_bytes" FROM "tds"."autogen"."udp_lport_test" WHERE time > :dashboardTime: AND time < :upperDashboardTime: AND "local_host_id"='J7v9ndmcoBuo9to2MnHegLnBkC9x3SAVbQBJo5MMJrN1' GROUP BY time(1m) FILL(null)

![image](https://user-images.githubusercontent.com/117807/134311525-cda24cd7-d486-4ae2-a958-9f53a9081e4e.png)

**Comment by ryoqun** [comment]
```
$ ./target/release/solana -ut validators | grep -E '8SRKNfvMerfA1BdU79CAwU4wNfjnDvFrBo3o5f5TS4uv|J7v9ndmcoBuo9to2MnHegLnBkC9x3SAVbQBJo5MMJrN1'
  8SRKNfvMerfA1BdU79CAwU4wNfjnDvFrBo3o5f5TS4uv  DnpfsM56HNhh695icBktjjcKaLZQP6uXHvG8rZyoRbrA    5%  95038405 ( -2)  95038346 (-19)  34.31%   152430   1.7.12  42959.311631792 SOL (0.05%)
  J7v9ndmcoBuo9to2MnHegLnBkC9x3SAVbQBJo5MMJrN1  HiFjzpR7e5Kv2tdU9jtE4FbH1X8Z9Syia3Uadadx18b5   10%  95038299        95038227        14.50%   151796   1.7.12  605014.699577946 SOL (0.71%)
```

**Comment by ryoqun** [comment]
```
    178.170.47.150    |   712 | 8SRKNfvMerfA1BdU79CAwU4wNfjnDvFrBo3o5f5TS4uv | 1.7.10  | 8000 | 8003 | 8004 | 8001 | 8002 | 8006 | 8007 | 18122
    74.118.136.72     |  2636 | J7v9ndmcoBuo9to2MnHegLnBkC9x3SAVbQBJo5MMJrN1 | 1.7.10  | 8000 | 8003 | 8004 | 8001 | 8002 | 8006 | 8007 | 18122
```

- huge outgoing transfer for turbine and repair (esp, for highly-staked node)
- outgoing gossip is relatively unchanged, but incoming gossip is halved.

**Comment by ryoqun** [comment]
![image](https://user-images.githubusercontent.com/117807/134314835-99649b4b-67d0-41ce-acfe-412a74582ef3.png)

hmm, no noticeable turbine packets drops around the testnet outage.
