### ISSUE TITLE
Error: Account xxxxxxxxxxxxx is not an upgradeable program or already in use

### ISSUE THREAD

**Issue by yunweb** [solana-labs/solana#19080]
#### Error: Account xxxxxxxxxxxxx is not an upgradeable program or already in use

https://github.com/solana-labs/solana-program-library/blob/master/token-lending/README.md

solana program deploy \
  -k owner.json \
  --program-id lending.json \
  target/deploy/spl_token_lending.so

Result: Error: Account xxxxxxxxxxxxx is not an upgradeable program or already in use

**Comment by t-nelson** [comment]
Sounds like there's already a program at that address.  We don't use Github for support.  Join us on Discord https://solana.com/discord
