### ISSUE TITLE
RPC Request: API to return the public key of all accounts that have interacted with a given account / public key

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#19188]
#### Problem

The current way to return all the public keys of all accounts that interacted with an account via a TX  is to do this manually by doing getSignaturesForAddress and then parsing the transaction using getTransaction for every signature returned. But this isn't really viable to do in the client

#### Proposed Solution

Build the API for this.  Should be paginated and take a slot range.

tag @CriesofCarrots

**Comment by CriesofCarrots** [comment]
Can you say more about the need here? What are the blockers for the current client-side process?
`getSignaturesForAddress` is paginated by start/end signature currently. Is the need for slot limiters in additional to signature, or a separate api?

**Comment by tfrizza** [comment]
@aeyakovenko The best intermediate workaround that I found for this in `web3.js` was to feed the resultant signatures from `getSignaturesForAddress` into `getParsedConfirmedTransactions` which calls JSON-RPC in batch, avoiding multiple requests. Slot range would be helpful also though.

There's a nice example of this with chunking from the explorer code: https://github.com/solana-labs/explorer/blob/43c50d379e56c23e6682746e68c6c2304236c3ef/src/providers/accounts/history.tsx#L100-L123

**Comment by Lazar955** [comment]
+1 for this from me, slot range would be super beneficial.
