### ISSUE TITLE
Feature Request: Prune long-delinquent validators from getVoteAccounts

### ISSUE THREAD

**Issue by bji** [solana-labs/solana#19234]
#### Problem

The JSON RPC API call getVoteAccounts currently lists all vote accounts, even those that have been delinquent for a very long time.  The problem then is that user interfaces which show validators continue to display these vote accounts even though they are essentially dead.

This is not a big deal in interfaces that are just informational -- but when presented in a wallet validator selection list, users end up staking to validators which clearly are dead.  For example:

"O% No Fee" validator (vote account NoFeeZ6ddr4377ss9edzF5dscUHzaWuergj5pPwSn4H) has had about 500 SOL delegated to it in the past 10 epochs, despite this validator having not voted for over 189 days.

Yes, it is up to stakers to decide who they stake with; and yes, it's their fault for staking to dead validators.  And yes, it's really wallets that present validator lists for staking that should prune out dead validators on behalf of their users.

#### Proposed Solution

Why not just eliminate these validators from JSON RPC API so that this issue is taken care of completely for all UIs and all wallets in one fell swoop?

I'd propose a policy that if a validator has not voted in 10 epochs, it should be pruned from the list.

As an alternative, if you are averse to any kind of editing of data, then at least provide an optional parameter to the getVoteAccounts() query named something like "epochVoteThreshold" or something, that acts as a filter when specified to filter out validators who have not voted in the past however many epochs are specified by that parameter.  And make the default be 10.

**Comment by jon-chuang** [comment]
I'm quite certain the 500 SOL is either leftover stake from delegators too lazy/inattentive to redelegate, or the node's own stake.

I believe the [web3.js api already gives a partitioned list](https://solana-labs.github.io/solana-web3.js/modules.html#VoteAccountStatus) the first half being non-delinquent.

So it's a matter of the wallets/UI not utilising this information, I suppose.

**Comment by bji** [comment]
I should just implement this and make a PR.  I just would like to know if the Solana Labs team would accept such a feature if I were to implement it, so that I don't waste my time.  I would implement it using the epochVoteThreshold query parameter that I mentioned above.

**Comment by t-nelson** [comment]
I don't think this call should be pruning delinquents.  It's about vote accounts, that that's used as a proxy for validators is a different question

**Comment by bji** [comment]
Sorry I don't understand your comment.  Yes it's about vote accounts, but getVoteAccounts() is what is used (I presume) by most/all UIs that show validator lists, and this therefore is the API call that I think could be modified.  The name of the parameter would not suggest that its purpose is pruning delinquents, it would just be about pruning vote accounts that have not voted recently.  Does that assuage your concern?

**Comment by mvines** [comment]
[getVoteAccounts](https://docs.solana.com/developing/clients/jsonrpc-api#getvoteaccounts) already has a `delinquentSlotDistance` input field.  An additional input, say `abandonedSlotDistance`, that filters out long-standing delinquents seems fine to me.  

Wallets / staking interfaces would still need to decide what value to use for `abandonedSlotDistance` and use it though.  Since wallets need to opt-in, I feel that Client-side filtering would accomplish the same without a new RPC knob.

I'd approve such a PR if it existed, but doesn't seem super useful to me honestly

**Comment by t-nelson** [comment]
`delinquent` is a soft term, not consensus.  I already made this call more configurable [awhile back](https://docs.solana.com/developing/clients/jsonrpc-api#getvoteaccounts). We need to be careful to avoid inconsistent messaging on public community resources though, hence the warning on `delinquentSlotDistance`.

**Comment by bji** [comment]
That's my whole purpose here.  To redefine the base vote account list to not include delinquents, and to do it with a new parameter that by default wouldn't include them, but that does if you include a parameter explicitly instructing the RPC call handler to do so.

The getVoteAccounts() call is defined thusly:

"Returns the account info and associated stake for all the voting accounts in the current bank."

This is contradicted by the presence of a parameter "keepUnstakedDelinquents" that is documented as "Do not filter out delinquent validators with no stake".  So the "all" in the API documentation is incorrect, because in fact the implementation already be default filters out delinquent validators with no stake.

So already the list is curated.  I'm saying, change the default curation to be even more useful -- don't include staked delinquents either.  I guess now that I see all of the parameters that this API call already accepts, the most logical thing would be another - "keepStakedDelinquents", by default false, but if provided with a true value, will allow staked delinquents to be included in the list too.

**Comment by bji** [comment]
Alternately, it is left up to each wallet/ui to do it themselves, and they'll pretty much do the wrong thing, or something inconsistent, or weird.  It's one of those cases where the pedantic correct answer is "this is up to the downstream users of the API to get right", whereas the practical answer is, "just do it for them so that they don't screw it up".

**Comment by bji** [comment]
Meh, I just realized that lots of UIs will use the full list to count total stake and they would be screwed up if some stake suddenly disappeared from their lists.  So I think there is now way to make a strictly better version of getVoteAccounts().  Thanks for your consideration and time anyway ...

**Comment by bji** [comment]
Also I realized that I was totally smoking crack because I forgot that the resulting list was already separated into current and delinquent sub-lists.  So mvines and trent were correct, this API call already has everything required to handle all needs.

**Comment by mvines** [comment]
Stay off the pipe dude!
