### ISSUE TITLE
Explorer token distribution table can show 160% supply

### ISSUE THREAD

**Issue by ruuda** [solana-labs/solana#19248]
#### Problem

I observed this on https://explorer.solana.com/address/8ry9FhmvhifEBwLPJpg89fAu19rmUHskDVvEfKuDbQbT/largest?cluster=testnet

![2021-08-16-solana-explorer-supply](https://user-images.githubusercontent.com/506953/129548313-0044cbf6-000b-4e30-85ed-b469822905b6.png)

After refreshing, it did show the correct numbers.

The problem is that [the explorer makes multiple to RPC calls to show this table](https://github.com/solana-labs/solana/blob/95c998a19e27aa13c065d56855e9e27f8d542d97/explorer/src/components/account/TokenLargestAccountsCard.tsx#L22-L74), and the RPC does not offer atomic reads:

* I’m not sure where the mint info comes from, [this function is involved](https://github.com/solana-labs/solana/blob/95c998a19e27aa13c065d56855e9e27f8d542d97/explorer/src/providers/accounts/index.tsx#L286-L305), but I don’t know which RPC call is ultimately responsible for it. What matters though, is that it is a different RPC call than the next one.
* [`getTokenLargestAccounts`](https://docs.solana.com/developing/clients/jsonrpc-api#gettokenlargestaccounts) to get the balances of the largest accounts.

The problem is that these reads cannot be done atomically. If we read the supply from the mint account, then some tokens get minted after that, and then we get the largest accounts, then the computed percentages will be wrong.

#### Proposed Solution

**With the current Solana RPC, it is impossible to make a correct “largest accounts” page.** However, the percentages can at least be made consistent.

The only primitive that the Solana RPC currently offers for atomic reads is [`getMultipleAccounts`](https://docs.solana.com/developing/clients/jsonrpc-api#getmultipleaccounts). We can do this:

 * Call `getTokenLargestAccounts` to get the addresses of the token's largest accounts.
 * Call `getMultipleAccounts` with these addresses + the mint address.
 * Now we have account data where at least the account balances and the mint’s supply were read from the same consistent snapshot of the on-chain data, so if we compute percentages, those will not exceed 100%. (And if there are no more accounts than returned by `getTokenLargestAccounts`, they will sum to 100% exactly.)
 * **However**, the accounts we have now, might no longer be the largest accounts! As a pathological example, between the call to `getTokenLargestAccounts` and `getMultipleAccounts`, the № 1 token holder could have moved all their tokens to a different account, and now in the snapshot (that is at least consistent), there is this account with a balance of 0 among the top token holders, and the actual top token holder is not part of the snapshot. Note that this is not just a race, where by the time the page renders the situation is different — that race will always exist. What is problematic here is that what we display was never a list of top token holders, not in the past either. (The addresses were, but the balances we would show are not the balances at that time.)

As you can see, atomic reads with the primitives that the Solana RPC offers currently are super subtle, and even something as simple as a top token holders page is impossible to implement correctly. Instead of trying to patch things with `getMultipleAccounts`, it would be nice to offer a more useful primitive instead: [`getAccountAtSlot`](https://github.com/solana-labs/solana/issues/17633). For the token holders case, we would also need a `getTokenLargestAccountsAtSlot`. If this primitive would exist, it becomes easy to render a correct token holders page, with minimal changes to the current structure:
* Get the current highest block number.
* Call `getAccountAtSlot` to read the mint at that slot.
* Call `getTokenLargestAccountsAtSlot` to read the largest accounts and compute the percentages. Even though the call happened later, the mint and the list of largest accounts are consistent, because they were read from the same slot.

**Comment by jon-chuang** [comment]
Generally speaking, front-end code is liable to be inaccurate in multiple ways. Unless your information is truly real-time - in this case, just refreshing the page would do.

If you need real-time accuracy, a different UI design is required, say something like the Serum orderbook UI. I don't believe this is really necessary for the explorer.
