### ISSUE TITLE
Runtime depends on legacy programs

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#1928]
#### Problem

Runtime can't be moved to the SDK without pulling the "legacy" programs along with it.

#### Proposed Solution

Make `execute_transaction()` a method of a new `Runtime` object so that it can host legacy programs in a state variable. Add a `register_legacy_program()` method and use it from the Bank to register the legacy programs.

**Comment by garious** [comment]
This is an easy one. I'll implement it tomorrow if nobody beats me to it.

**Comment by garious** [comment]
Alternatively, turn the legacy programs into proper Account-based, native programs.

**Comment by mvines** [comment]
*yonk*
