### ISSUE TITLE
web3.js - getMultipleAccountsInfo throws exception if any account is missing

### ISSUE THREAD

**Issue by chase-45** [solana-labs/solana#19301]
#### Problem
When getting many accounts via Connection.getMultipleAccountsInfo, if any of the accounts do not exist, the entire promise throws an exception and rejects with an error of similar format to this:

ERROR	StructError: At path: value.4 -- Expected an object, but received: null
    at validate (/var/task/node_modules/superstruct/lib/index.cjs:363:19)
    at Object.create (/var/task/node_modules/superstruct/lib/index.cjs:319:18)
    at /var/task/node_modules/@solana/web3.js/lib/index.cjs.js:2562:29
    at Struct.coercer (/var/task/node_modules/superstruct/lib/index.cjs:948:52)

This error causes the entire promise to reject, and accounts which were successfully retrieved are not returned. This forces the user to call Connection.getAccountInfo in a loop if they are not certain of the status of the accounts they're querying.

#### Proposed Solution
If some accounts do not exist, still resolve the promise, but place 'null' at the corresponding index in the resolved AccountInfo array. This would make the behavior effectively the same as calling Connection.getAccountInfo in a loop. However, this might be considered a breaking change, as the returned arrays currently don't have nulls.

**Comment by Arrowana** [comment]
I don't think it should throw, it should have nulls where data is missing, this keeps it close to the json RPC

Use case "I see a bunch of associated token accounts for an owner and want to find all NFTs":
`getMultipleAccountsInfo` for all tokens mints, with the metadata program PDA for the mint, non null returned are actual NFTs.

There are possible many other similar scenarios
