### ISSUE TITLE
What does "Secondary Elections" mean in the whitepaper?

### ISSUE THREAD

**Issue by 3for** [solana-labs/solana#19339]
I'm reading our [Solana whitepaper](https://solana.com/solana-whitepaper.pdf), What's the meaning of "Secondary Elections" in section 5.9？Does it mean that elect for the next 2 epoch?
And I can not find the corresponding "secondary election" code in our repo?

**Comment by steveluscher** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Solana itself.

Questions like yours deserve a purpose-built Q&A forum. Please post your question to the Solana Stack Exchange using this link: https://solana.stackexchange.com/questions/ask
