### ISSUE TITLE
SendTransactionService retries all transactions indiscriminately

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#19347]
#### Problem
Some transactions are only relevant if they execute promptly, but an rpc node will retry every transaction it receives until the recent blockhash expires, potentially wasting rpc and validator banking-stage cycles.

#### Proposed Solution
Consider adding a no-retry parameter to `sendTransaction` rpc, directing the SendTransactionService to only attempt to submit the transaction to upcoming leaders once.

Note that such a transaction would still be valid until the blockhash expires; the transaction could still land due to validator forwarding or a duplicate submission. If guaranteed reduced liveness is needed, it would be incumbent on the user to include on-chain program logic to reject transactions to enforce the expiration.
Using the no-retry parameter would be a courtesy to the rpc node and the cluster.

**Comment by mvines** [comment]
Perhaps `max_retries: usize`?

**Comment by CriesofCarrots** [comment]
> Perhaps `max_retries: usize`?

Nice, more flexible
