### ISSUE TITLE
Program Deployment Occassionaly Fails Completely

### ISSUE THREAD

**Issue by bonedaddy** [solana-labs/solana#19357]
#### Problem

There are intermittent issues when interacting with a solana node that results in being unable to deploy programs to `mainnet-beta`. When this problem happens the speed at which deployment transactions are broadcast is incredibly slow, and once all transactions that need to be broadcast are sent, the deployment process starts the whole process again.

 Normally I'm able to complete a deployment that requires around 6k transactions in a few minutes (2 -> 3 at most). When this problem happens it will take anywhere from 3x -> 10x the normal time, before failing completely and restarting.

I've managed to reproduce this issue using different solana CLIs, I've had the problem happen on the following solana versions.

* 1.7.4
* 1.7.8
* 1.7.10

It seems to be a network-wide issue as opposed to a node issue as @therealssj  and myself will both be able to experience this problem in different geographical regions, with multiple different nodes.

#### 

* As of 3:49pm PST august 21th we've been experiencing this issue for the last 12 hours across 3 different nodes (2 public RPCs, 1 private RPC)
  * downgrading cli to 1.6.4 fixed the issue

**Comment by aaronovz1** [comment]
I just hit the same problem on `1.7.11` when deploying a program with about ~1600 transactions. Normally it completes within 1 minute, but when this issue popped up it took 5 minutes, and then silently failed and restarted the process again. Each iteration creating a new buffer and chewing up SOL from our deployment wallet.

Downgrading to 1.6.5 seemed to work but this becomes a frustrating juggling task when we compile with 1.7.x and then need to downgrade to 1.6.x to deploy.

**Comment by mvines** [comment]
I'm quite sure #19717 is coming into play here, which is now fixed at the HEAD of the v1.7 branch.  If you don't want to wait until the next 1.7 release, try `solana-install init beta` to get a version of the cli that contains this patch.

I've also made a number of other improvements to program deployment last week on the master branch only (#19695 and #19636).  `solana-install init edge` will allow you to pick up those changes until 1.8.0 ships.

**Comment by dzmitry-lahoda** [comment]
I am on 1.8.14. Main net cluster is on 1.8.14. I have 2 SOL. I try to deploy. ~1.3 SOL  transferred to buffer. Deploy fails with above error.  Tried 2 times. 

I started with 1.9.5. Worked on DEV. failed on main. So I decided it is to new version. But that seems not the case.

**Comment by dzmitry-lahoda** [comment]
I am on 1.8.14 locally and mainnet cluster is 1.8.14. Tried 3 times already. Get 0x1 error. Sometimes it takes money info buffer and errors, sometimes errors without taking.

**Comment by dzmitry-lahoda** [comment]
When I can no money, if fails before any request as 
```
Error: Account XXXXXXXXXXXXXXXX has insufficient funds for spend (1.35394968 SOL) + fee (0.000985 SOL)
```

When I deploy and have money I see
```
⠤ [0/1] Finalizing transaction 4haLezGxCnRZgGdb9NfL5wZ2PoWeMYQbwLkzm9cnLBxnTWrQiqf59dyrBSH6uLANbm64cLaUGrxf4bdWMWbXtyX1
```

and then 
````
Error: Deploying program failed: Error processing Instruction 1: custom program error: 0x1
```

and balance is taken.

**Comment by dzmitry-lahoda** [comment]
i got it

solana deploy - works on old clusters
solana program deploy - is for new
