### ISSUE TITLE
BankingStage may have redundant copies of same transactions

### ISSUE THREAD

**Issue by carllin** [solana-labs/solana#19358]
#### Problem
People submitting the same transactions to multiple RPC nodes could end up forwarding those transactions to the same leader, which leads to redundancy in the leader's transaction queue.

Result of investigation into long `send_transaction_service` retry queues.

tag: @t-nelson, @CriesofCarrots, @sakridge 

#### Proposed Solution
Maybe track signatures of transactions pending in the queue and drop duplicates?

**Comment by sakridge** [comment]
We drop duplicates in banking stage:
https://github.com/solana-labs/solana/blob/6d939811e9e7386de3766a5cb24f23e5e7e36c7e/core/src/banking_stage.rs#L1481

**Comment by taozhu-chicago** [comment]
> We drop duplicates in banking stage:
> https://github.com/solana-labs/solana/blob/6d939811e9e7386de3766a5cb24f23e5e7e36c7e/core/src/banking_stage.rs#L1481

Thanks for pointing it out! I'll familiar myself with this code path while confirming duplicated TXs are filtered.

**Comment by carllin** [comment]
> We drop duplicates in banking stage:

Ah thanks for pointing that out, going to close this for now.
