### ISSUE TITLE
How to obtain full history for a new RPC node?

### ISSUE THREAD

**Issue by viliampucik** [solana-labs/solana#19391]
#### Problem

When a new RPC node (`solana-validator --no-voting`) is started, its ledger history begins from the recent network snapshot. Is there a way to download full Solana history even for a fresh new RPC node?

#### Proposed Solution

There is a possibility to use GCP BitTable, when the RPC node runs in Google Cloud however, this still does not solve the issue and does not work for non-GCP RPC nodes.

**Comment by steveluscher** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Solana itself.

Questions like yours deserve a purpose-built Q&A forum. Please post your question to the Solana Stack Exchange using this link: https://solana.stackexchange.com/questions/ask
