### ISSUE TITLE
web3.js: error on `getRecentPerformanceSamples`

### ISSUE THREAD

**Issue by jon-chuang** [solana-labs/solana#19419]
#### Problem
web3.js 1.24.0 errors when calling `getRecentPerformanceSamples` with :
argument is `undefined`
```
connection.ts:2906 Uncaught (in promise) Error: failed to get recent performance samples: Invalid params: invalid type: map, expected usize.
    at Connection.getRecentPerformanceSamples (connection.ts:2906)
```
argument is `number`
```
connection.ts:2906 Uncaught (in promise) Error: failed to get recent performance samples: Invalid parameters: Expected from 0 to 1 parameters.
    at Connection.getRecentPerformanceSamples (connection.ts:2906)
```

The build in my calling javascript has the following code, which is identical to master:
```js
  /**
   * Fetch recent performance samples
   * @return {Promise<Array<PerfSample>>}
   */
  async getRecentPerformanceSamples(
    limit?: number,
  ): Promise<Array<PerfSample>> {
    const args = this._buildArgs(limit ? [limit] : []);
    const unsafeRes = await this._rpcRequest(
      'getRecentPerformanceSamples',
      args,
    );
    const res = create(unsafeRes, GetRecentPerformanceSamplesRpcResult);
    if ('error' in res) {
      throw new Error(
        'failed to get recent performance samples: ' + res.error.message,
      );
    }

    return res.result;
  }
```

As far as I can tell, this is very strange as the RPC request appears to be correct.

**Comment by jon-chuang** [comment]
Turns out this issue arises only when commitment is not finalized. It is fixed by setting the connection commitment to be finalized

**Comment by swimricky** [comment]
hi @oJshua 
so i also recently ran into this issue using 1.42.0

I noticed one additional detail - 
the call actually only works if you construct a `Connection` without any specified commitment level.  (`connection.commitment` returns `undefined`)

I tried using both `'finalized' as Commitment` and a `ConnectionConfig` with `{commitment: 'finalized'}` and both gave me the same errors from above.

**Comment by steveluscher** [comment]
Fixed in https://github.com/solana-labs/solana/commit/6b82235fab155ef80e990309d693bf2045e2ee4e.
