### ISSUE TITLE
CI unstable test: wallet::tests::test_wallet_request_airdrop

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#1944]

**Comment by mvines** [comment]
https://buildkite.com/solana-labs/solana/builds/5461#3a9a9a4b-bc51-4c49-a66d-192a653e9db5

**Comment by mvines** [comment]
https://buildkite.com/solana-labs/solana/builds/5488#9bf971d9-0122-4384-9d97-66bfb3be90ca
