### ISSUE TITLE
Broken links to diagrams in validator docs

### ISSUE THREAD

**Issue by ccdle12** [solana-labs/solana#19496]
Theres a few missing diagrams that lead to broken links at: https://github.com/solana-labs/solana/tree/master/docs/src/validator.

Specifically:

- anatomy.md
- tpu.md
- tvu.md

**Comment by steviez** [comment]
@ccdle12 - Thanks for taking the time to make an issue. Are you viewing the `.md` files directly in the source tree explorer? If so, I would recommend checking out the hosted docs at:
https://docs.solana.com/validator/anatomy

The image files get generated from [these files](https://github.com/solana-labs/solana/tree/master/docs/art) by [this](https://github.com/solana-labs/solana/blob/master/docs/convert-ascii-to-svg.sh) script when we build the documentation; the links refer to where those generated image files will be such that the built docs will have valid links.

**Comment by ccdle12** [comment]
thanks for the link @steviez, i'll checkout and read the architecture docs on there. I'll close this off since the build script will generate it locally. thanks for the help!

**Comment by steviez** [comment]
No problem @ccdle12 - happy reading / building!
