### ISSUE TITLE
v1.6.22, cargo build failed

### ISSUE THREAD

**Issue by Xib1uvXi** [solana-labs/solana#19518]
#### Problem
![image](https://user-images.githubusercontent.com/13687858/131463008-4b6efe6a-a096-4c62-8a25-4184e4e05d42.png)

**Comment by CriesofCarrots** [comment]
I believe this is an issue building this branch with Rust v1.54. Our v1.6 branch is synced with Rust v1.51: https://github.com/solana-labs/solana/blob/70bdcf06b4372ae1da180104078e2b27f3ef2e31/ci/rust-version.sh#L21
You can either install that version or Rust manually, or use the `/cargo` script in the top level of the repo.

**Comment by Xib1uvXi** [comment]
Thank you for your reply. I've noticed that it's a rust version issue and I've found the relevant build documentation(https://docs.solana.com/cli/install-solana-cli-tools#build-from-source)

There is a suggestion to use rust-toolchain file to specify the rust version(https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file)

[rust-toolchain file example](https://github.com/filecoin-project/bellperson/blob/master/rust-toolchain)
