### ISSUE TITLE
v1.6.22 windows packages miss solana-validator.exe 

### ISSUE THREAD

**Issue by CockyCat** [solana-labs/solana#19576]
#### Problem

How can i get solana-validator.exe on windows?

![)0JV}1E(Q_1}6T4MSG1L{)F](https://user-images.githubusercontent.com/4004100/131839797-230ec9db-6e3a-4895-b339-90197f27dc0f.png)

**Comment by steviez** [comment]
Hi @CockyCat, short answer is you can't. For more details / suggestions, please see https://github.com/solana-labs/solana/issues/17977
