### ISSUE TITLE
Reinstate multi-threaded tests, remove --test-threads=1 from runs of "cargo test --lib" in the CI scripts

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#1959]
#### Problem
solana unit tests do not co-exist well in a multi-threaded environment, as a result, they have to run serially, which is slow.
Socket addresses, http servers, http keep-alive clients seem to be the main sticking point

#### Proposed Solution
root out MT issues and turn --test-threads=1 off in CI

**Comment by garious** [comment]
We moved to `[serial]` tests a while back
