### ISSUE TITLE
I start a validator，but it cannot open the rpc-port(8899 and 8900)

### ISSUE THREAD

**Issue by tttlkkkl** [solana-labs/solana#19663]
#### Problem

Hello, excuse me, I started an RPC node, but why can't I see port 8899 being monitored on my machine.Here are my startup commands:
```bash
#!/bin/bash
solana-validator \
    --identity ~/validator-keypair.json \
    --vote-account ~/vote-account-keypair.json \
    --known-validator 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2 \
    --known-validator GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ \
    --known-validator DE1bawNcRJB9rVm3buyMVfr8mBEoyyu73NBovf2oXJsJ \
    --known-validator CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S \
    --only-known-rpc \
    --ledger /home/solana/ledger \
    --accounts /home/solana/accounts \
    --gossip-port 8001 \
    --rpc-port 8899 \
    --rpc-bind-address 127.0.0.1 \
    --private-rpc \
    --no-port-check \
    --enable-rpc-transaction-history \
    --dynamic-port-range 9000-9100 \
    --entrypoint entrypoint.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint2.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint3.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint4.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint5.mainnet-beta.solana.com:8001 \
    --expected-genesis-hash 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d \
    --wal-recovery-mode skip_any_corrupted_record \
    --account-index 'program-id' \
    --account-index 'spl-token-mint' \
    --account-index 'spl-token-owner' \
    --cuda \
    --log /home/solana/logs/solana-validator.log
```
The node can start normally, but I don't see the 8899 and 8900 ports of the system being used.
![image](https://user-images.githubusercontent.com/8353103/132207491-68cf8d43-e776-4376-8d10-a21c5f31d742.png)
##### solana version:
solana-cli 1.7.11 (src:bdb77b0c; feat:1140394761)

I tried many times, but I still couldn't succeed. I ask for your help. Can you help me see what's wrong. thank you.

**Comment by lcgogo** [comment]
use 1.6.22 stable version

**Comment by tttlkkkl** [comment]
@lcgogo 
Thank you .but unfortunately, I can't open port 8899 after switching the version. Have you ever encountered a similar situation?

**Comment by Merrick17** [comment]
did you find a solution ?

**Comment by let4be** [comment]
Having the same issue, do we have to wait for validator to catch up before it opens RPC ports?

**Comment by t-nelson** [comment]
Hi! We don't use github for support requests. Please join us in #validator-support on https://solana.com/discord instead

**Comment by 1scrooge** [comment]
> Hi! We don't use github for support requests. Please join us in #validator-support on https://solana.com/discord instead

Hi, I don't see a support channel
![image](https://user-images.githubusercontent.com/32951007/152365937-71c3c7d1-4bbc-4daf-843e-d11fb16862ca.png)

**Comment by t-nelson** [comment]
Read the posts in #roles...
