### ISSUE TITLE
devnet error

### ISSUE THREAD

**Issue by xuanlongvts** [solana-labs/solana#19664]
when i airdrop SOL on testnet environment. It shows

Requesting airdrop of 10 SOL
Error: unable to confirm transaction. This can happen in situations such as transaction expiration and insufficient fee-payer funds.

i have to wait about 30s.

**Comment by keikumata** [comment]
This happens to me as well - is devnet not working for some reason? It works with `testnet`.

**Comment by CriesofCarrots** [comment]
The faucet was drained. It should be replenished and working now. In future, you'll likely get better technical support on our Discord server: https://discord.gg/taxxawAt
Github isn't great for this.
