### ISSUE TITLE
bank to export votes and vote data necessary to pick branches

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#1969]
current prev_id, tick_height (probably does already)
vote stack, for each vote:
 *lockout
 *prev_id
 *tick_height?

**Comment by garious** [comment]
@rob-solana, this seems really close to the work I'm doing in: https://github.com/solana-labs/solana/pull/2466.  It serializes one `WeightedElection` into an account per block and validators send votes to that account.  After recording transactions, I'm expecting the bank to query the transaction list for the votes and when there is one, deserialize the account and check to see if that was the *first* vote that triggered `election.voted_weight() >= 2 * election.total_weight() / 3 + 1` (stake-weighted BFT consensus).

**Comment by garious** [comment]
@rob-solana, this ticket makes no sense to me.  What's the problem? What are you proposing should be done about it?

**Comment by rob-solana** [comment]
can be closed, is most likely superseded by other PRs, designs dealing with forks
