### ISSUE TITLE
solana-sdk dependency on solana-program, not friendly to 32-bit architectures

### ISSUE THREAD

**Issue by jnicholls** [solana-labs/solana#19726]
#### Problem
Builds of the solana-sdk targeting 32-bit architectures, including those with no 64-bit atomics support (PowerPC, MIPS) fail to compile. There are a couple of issues:

1. The use of AtomicU64 in a few places in the SDK (solana-program and the AtomicInterval struct).
2. The entrypoint heap starting address of 0x30000000, which is larger than a 32-bit address.

This is not surprising to anyone working on Solana. And specifically, this doesn't matter when compiling on-chain BPF programs.

My use case is using the solana-sdk on HSMs, where I want to understand structured solana transactions and sign them. I do not need much of the sdk to accomplish this, especially not the on-chain BPF program bits. I'm already turning off all features, including the `solana-crate-features` dependency, because I do not need any of them. Specifically, `solana-crate-features` builds `ring` which is not supported on PowerPC nor MIPS (two architectures sometimes found on modern HSMs).

#### Proposed Solution

Perhaps a proper solution is to remove the sdk's dependency on the program crate. In turn this may require splitting up the program crate between on-chain bits and what is commonly needed in the client side sdk and the on-chain program crate. Furthermore, perhaps some things in the client sdk ought be put into their own smaller sub-crate and be features. For my specific use case, not having entanglement between the sdk and the program crate would probably solve my issue.

For now I have forked the the solana repo and made it buildable on PowerPC/MIPS 32-bit architectures. I replaced AtomicU64 with a lazy_static Mutex\<u64>, and I just modified the entrypoint heap address to be smaller because I don't have any other use for it.

With that said, there may be a better approach to what I am doing, and I'd be interested to discuss it further. Thanks in advance.

**Comment by mvines** [comment]
`solana-sdk` is a legacy kitchen-sink type crate. `solana-program` came later and is a subset of `solana-sdk` that works in the more restricted program environment.  I'd be very open to carving out other parts of `solana-sdk` in a similar fashion as  `solana-program` to support other environments like 32bit HSMs

**Comment by jnicholls** [comment]
Thanks @mvines for the response back in September. I apologize for not replying sooner to carry this thread further.

So if I understand correctly, you are saying that `solana-program` was once a part of `solana-sdk` directly, but it was broken out in order to be useful on its own...and you are in favor of further breaking apart `solana-sdk` where it makes sense?

As it turns out, we do make heavy use of the `solana-program` crate, and its `Message` and `Instruction` types to construct new messages. So maybe I'd amend my statement that perhaps `solana-program` should be broken up, because specifically the HEAP_START_ADDRESS in `sdk/src/program/src/entrypoint.rs` is no bueno on 32-bit. I don't know what would be a reasonable solution here to be fair, other than make the parts of `solana-program` that are actually used in BPF compilation separate from the other parts that are used for authoring the program.

Here is a patch I had to make to get 32-bit on PPC/MIPS to work, just to paint a picture of the minor updates that were necessary (and that are not necessarily in a condition to commit upstream).

```diff
diff --git a/sdk/Cargo.toml b/sdk/Cargo.toml
index 21a56867d..836c9766c 100644
--- a/sdk/Cargo.toml
+++ b/sdk/Cargo.toml
@@ -17,24 +17,24 @@ edition = "2018"
 program = []
 
 default = [
-  "full" # functionality that is not compatible or needed for on-chain programs
+  "full", # functionality that is not compatible or needed for on-chain programs
 ]
 full = [
-    "assert_matches",
-    "byteorder",
-    "chrono",
-    "generic-array",
-    "memmap2",
-    "rand",
-    "rand_chacha",
-    "serde_json",
-    "ed25519-dalek",
-    "ed25519-dalek-bip32",
-    "solana-logger",
-    "solana-crate-features",
-    "libsecp256k1",
-    "sha3",
-    "digest",
+  "assert_matches",
+  "byteorder",
+  "chrono",
+  "generic-array",
+  "memmap2",
+  "rand",
+  "rand_chacha",
+  "serde_json",
+  "ed25519-dalek",
+  "ed25519-dalek-bip32",
+  "solana-logger",
+  # "solana-crate-features",
+  "libsecp256k1",
+  "sha3",
+  "digest",
 ]
 
 [dependencies]
@@ -55,7 +55,7 @@ ed25519-dalek-bip32 = { version = "0.1.1", optional = true }
 generic-array = { version = "0.14.4", default-features = false, features = ["serde", "more_lengths"], optional = true }
 hex = "0.4.3"
 hmac = "0.11.0"
-itertools =  "0.10.1"
+itertools = "0.10.1"
 lazy_static = "1.4.0"
 libsecp256k1 = { version = "0.6.0", optional = true }
 log = "0.4.14"
diff --git a/sdk/program/src/blake3.rs b/sdk/program/src/blake3.rs
index d09da7d4a..7305b40cd 100644
--- a/sdk/program/src/blake3.rs
+++ b/sdk/program/src/blake3.rs
@@ -103,11 +103,18 @@ impl Hash {
 
     /// unique Hash for tests and benchmarks.
     pub fn new_unique() -> Self {
-        use std::sync::atomic::{AtomicU64, Ordering};
-        static I: AtomicU64 = AtomicU64::new(1);
+        use std::sync::Mutex;
+        lazy_static::lazy_static! {
+            static ref I: Mutex<u64> = Mutex::new(1);
+        }
 
         let mut b = [0u8; HASH_BYTES];
-        let i = I.fetch_add(1, Ordering::Relaxed);
+        let i = {
+            let mut lock = I.lock().unwrap();
+            let i = *lock;
+            *lock = i + 1;
+            i
+        };
         b[0..8].copy_from_slice(&i.to_le_bytes());
         Self::new(&b)
     }
diff --git a/sdk/program/src/entrypoint.rs b/sdk/program/src/entrypoint.rs
index 8a17cf696..1f974b33d 100644
--- a/sdk/program/src/entrypoint.rs
+++ b/sdk/program/src/entrypoint.rs
@@ -28,7 +28,7 @@ pub type ProcessInstruction =
 pub const SUCCESS: u64 = 0;
 
 /// Start address of the memory region used for program heap.
-pub const HEAP_START_ADDRESS: usize = 0x300000000;
+pub const HEAP_START_ADDRESS: usize = 0x30000000;
 /// Length of the heap memory region used for program heap.
 pub const HEAP_LENGTH: usize = 32 * 1024;
 
diff --git a/sdk/program/src/hash.rs b/sdk/program/src/hash.rs
index e39add147..667320cc5 100644
--- a/sdk/program/src/hash.rs
+++ b/sdk/program/src/hash.rs
@@ -106,11 +106,18 @@ impl Hash {
 
     /// unique Hash for tests and benchmarks.
     pub fn new_unique() -> Self {
-        use std::sync::atomic::{AtomicU64, Ordering};
-        static I: AtomicU64 = AtomicU64::new(1);
+        use std::sync::Mutex;
+        lazy_static::lazy_static! {
+            static ref I: Mutex<u64> = Mutex::new(1);
+        }
 
         let mut b = [0u8; HASH_BYTES];
-        let i = I.fetch_add(1, Ordering::Relaxed);
+        let i = {
+            let mut lock = I.lock().unwrap();
+            let i = *lock;
+            *lock = i + 1;
+            i
+        };
         b[0..8].copy_from_slice(&i.to_le_bytes());
         Self::new(&b)
     }
diff --git a/sdk/program/src/keccak.rs b/sdk/program/src/keccak.rs
index b3df920f1..5f46fb325 100644
--- a/sdk/program/src/keccak.rs
+++ b/sdk/program/src/keccak.rs
@@ -104,11 +104,18 @@ impl Hash {
 
     /// unique Hash for tests and benchmarks.
     pub fn new_unique() -> Self {
-        use std::sync::atomic::{AtomicU64, Ordering};
-        static I: AtomicU64 = AtomicU64::new(1);
+        use std::sync::Mutex;
+        lazy_static::lazy_static! {
+            static ref I: Mutex<u64> = Mutex::new(1);
+        }
 
         let mut b = [0u8; HASH_BYTES];
-        let i = I.fetch_add(1, Ordering::Relaxed);
+        let i = {
+            let mut lock = I.lock().unwrap();
+            let i = *lock;
+            *lock = i + 1;
+            i
+        };
         b[0..8].copy_from_slice(&i.to_le_bytes());
         Self::new(&b)
     }
diff --git a/sdk/program/src/pubkey.rs b/sdk/program/src/pubkey.rs
index e7d3f9d58..27cacb6fb 100644
--- a/sdk/program/src/pubkey.rs
+++ b/sdk/program/src/pubkey.rs
@@ -147,11 +147,18 @@ impl Pubkey {
 
     /// unique Pubkey for tests and benchmarks.
     pub fn new_unique() -> Self {
-        use std::sync::atomic::{AtomicU64, Ordering};
-        static I: AtomicU64 = AtomicU64::new(1);
+        use std::sync::Mutex;
+        lazy_static::lazy_static! {
+            static ref I: Mutex<u64> = Mutex::new(1);
+        }
 
         let mut b = [0u8; 32];
-        let i = I.fetch_add(1, Ordering::Relaxed);
+        let i = {
+            let mut lock = I.lock().unwrap();
+            let i = *lock;
+            *lock = i + 1;
+            i
+        };
         b[0..8].copy_from_slice(&i.to_le_bytes());
         Self::new(&b)
     }
diff --git a/sdk/src/timing.rs b/sdk/src/timing.rs
index f415848a4..7f9bb8f70 100644
--- a/sdk/src/timing.rs
+++ b/sdk/src/timing.rs
@@ -1,6 +1,6 @@
 //! The `timing` module provides std::time utility functions.
 use crate::unchecked_div_by_const;
-use std::sync::atomic::{AtomicU64, Ordering};
+use std::sync::Mutex;
 use std::time::{Duration, SystemTime, UNIX_EPOCH};
 
 pub fn duration_as_ns(d: &Duration) -> u64 {
@@ -62,7 +62,7 @@ pub fn slot_duration_from_slots_per_year(slots_per_year: f64) -> Duration {
 
 #[derive(Debug, Default)]
 pub struct AtomicInterval {
-    last_update: AtomicU64,
+    last_update: Mutex<u64>,
 }
 
 impl AtomicInterval {
@@ -72,13 +72,11 @@ impl AtomicInterval {
 
     pub fn should_update_ext(&self, interval_time: u64, skip_first: bool) -> bool {
         let now = timestamp();
-        let last = self.last_update.load(Ordering::Relaxed);
-        now.saturating_sub(last) > interval_time
-            && self
-                .last_update
-                .compare_exchange(last, now, Ordering::Relaxed, Ordering::Relaxed)
-                == Ok(last)
-            && !(skip_first && last == 0)
+        let mut lock = self.last_update.lock().unwrap();
+        let last = *lock;
+        let should_update = now.saturating_sub(last) > interval_time && !(skip_first && last == 0);
+        *lock = now;
+        should_update
     }
 }
```

**Comment by mvines** [comment]
Directionally those changes to get solana-program happy building on 32bit architectures seems fine.  For `HEAP_START_ADDRESS` in particular that value cannot be changed but we could retype it from `usize` to `u64, which should make a 32bit target build happy

**Comment by mvines** [comment]
Maybe we abstract `AtomicU64` vs. `Mutex<u64>` behind a type to keep the 64bit build output unchanged

**Comment by jnicholls** [comment]
Yeah retyping `HEAP_START_ADDRESS` makes sense for sure. And that was also my thought precisely, that the use of AtomicU64/Mutex<u64> be abstracted accordingly in a proper patch. Those `new_unique` methods seem to only be used in tests, but that's beside the point.

Also, I'm now just coming to the realization that we make no other use of `solana-sdk` except for things inside of `solana-program`...so I think I'll prepare a worthy PR for you to consider. Stay tuned.

**Comment by jnicholls** [comment]
The above PR is ready for review @mvines at your convenience. Thanks for the help.
