### ISSUE TITLE
Solana-test-validator error on mac M1 chip

### ISSUE THREAD

**Issue by AurelienFT** [solana-labs/solana#19743]
#### Problem

I've download Solana using 
```
sh -c "$(curl -sSfL https://release.solana.com/v1.7.11/install)"
```

And when I run `solana-test-validator` I run into this problem :
```
dyld: Library not loaded: /usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib
  Referenced from: /Users/aurelienfoucault/.local/share/solana/install/active_release/bin/solana-test-validator
  Reason: no suitable image found.  Did find:
	/usr/local/opt/openssl@1.1/lib/libssl.1.1.dylib: mach-o, but wrong architecture
	/opt/homebrew/Cellar/openssl@1.1/1.1.1l/lib/libssl.1.1.dylib: mach-o, but wrong architecture
[1]    5799 abort      solana-test-validator
```

#### Proposed Solution

Dunno

**Comment by AurelienFT** [comment]
Ok just saw in the README that we have to use Rosetta.

**Comment by element0xE** [comment]
> The pre-built binary doesn't work, but I was able to build the Solana tools on a M1 Macbook without using Rosetta:
> 
> ![image](https://user-images.githubusercontent.com/7709/136699779-cb50533e-c14c-43a2-b006-7f7ad4ce8c5a.png)

Hello , I compiled solana-test-validator from source, and now I can start it correctly. But when I try to deploy locally, it remains stuck at :

`⠤ [0/1] Finalizing transaction  `

and then 

`Error: Deploying program failed: unable to confirm transaction. This can happen in situations such as transaction expiration and insufficient fee-payer funds`
I'm on M1 as weel , are you facing the same issue ?
Same issue [18033](https://github.com/solana-labs/solana/issues/18033)
