### ISSUE TITLE
Transfer from program account is not allowed, but only when data is set.

### ISSUE THREAD

**Issue by vldm** [solana-labs/solana#19763]
#### Problem
I found that system methods for make transfer from account:
SystemInstruction::Transfer/ SystemInstruction::TransferWithSeed - are not working when you try to transfer from program account with data.
But you still can execute them from program accounts with empty data. **This looks not consistent.**

I found this check https://github.com/solana-labs/solana/blob/master/runtime/src/system_instruction_processor.rs#L183-L186
that prevent it from execution.
```
 if !from.data_is_empty()? {
        ic_msg!(invoke_context, "Transfer: `from` must not carry data");
        return Err(InstructionError::InvalidArgument);
    }
```

I have a quick research, and found that this check was introduced in https://github.com/solana-labs/solana/commit/7e94cc2cc3ef6161de0e89af1c4127bb455b4de2#diff-3f8645400d0e866a22f752c366c32d95e1fab1320db79bbda3c699da1b4e39afR168

If i understand correctly, in this pullrequest you move nonce account logic into system program, and trying to prevent some issues related to fee spending and transfering in same transaction? Like this: https://github.com/solana-labs/solana/issues/7443

#### Proposed Solution

But if understand correctly this check is not fully correct, if you want to prevent special `system_program` accounts from spending money the check should be changed to:

```
if from.owner != system_program::id() || !from.data_is_empty()? {
      ic_msg!(invoke_context, "Transfer: `from` must not carry data");
      return Err(InstructionError::InvalidArgument);
}
```

or if you want also prevent any programs from spending money trough transfer, the checks may extend to:
```
if from.owner != system_program::id() {
      ic_msg!(invoke_context, "Programs should not use Transfer");
      return Err(InstructionError::InvalidArgument);
}
```

And make program writers to always use handwritten snippet:
```
from.lamports -= amount;
to.lamports += amount;
```

**Comment by t-nelson** [comment]
I think you're missing this post-check https://github.com/solana-labs/solana/blob/7aa5f6b8332516347282d0e36ceb8ae020c02ddb/program-runtime/src/instruction_processor.rs#L137-L142. Programs are not allowed to debit the SOL balance of accounts they do not own under any circumstances
