### ISSUE TITLE
Codebase contains lingering legacy python code

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#19795]
#### Problem

We still have some python2.7 in the following scripts.  Python2 is EOL
```
ci/dependabot-pr.sh
system-test/automation_utils.sh
```

#### Proposed Solution

Port them to Python3

**Comment by drewtaylors** [comment]
please assign to me :)

**Comment by CriesofCarrots** [comment]
> please assign to me :)

Done!
