### ISSUE TITLE
explorer: lines mis-indented in new hex viewer

### ISSUE THREAD

**Issue by leoluk** [solana-labs/solana#19825]
<img width="322" alt="2021-09-13_15-54" src="https://user-images.githubusercontent.com/859697/133096464-aeb02260-e20c-48a9-b1cc-48bc1eb2af71.png">

CC @jstarry

**Comment by jstarry** [comment]
Ah dang, thanks will fix

**Comment by jstarry** [comment]
If you have other feedback lmk

**Comment by jstarry** [comment]
@leoluk I wasn't able to repro but pretty I fixed it, can you take a look here to verify? https://explorer-6a8z5ck55-solana-labs.vercel.app/

**Comment by leoluk** [comment]
Confirmed to be fixed! Thanks :)
