### ISSUE TITLE
Can't enter seed phrase in local CLI 

### ISSUE THREAD

**Issue by LordOfTheDings** [solana-labs/solana#19844]
#### Problem
I tried to display the address of my solflare wallet by following the instructions provided in the solana CLI documentation (https://docs.solana.com/cli/conventions#file-system-wallet). However, upon being asked to enter my seed phrase, for some reason I can't paste the latter into the command line. 
![image](https://user-images.githubusercontent.com/55738329/133135109-90186f18-3797-4fe2-8f02-518fa0c11bec.png)
Maybe I'm doing something wrong, but I can't think of what that could be. Is this even the right place to report such an issue?

**Comment by CriesofCarrots** [comment]
For security reasons, the seed phrase won't appear in the console, even if it's pasted correctly.
Are you receiving an error?
Also, I recommend heading to our Discord server. Github is not great for technical support.

**Comment by LordOfTheDings** [comment]
Hi
That makes a lot of sense 😄 
Thanks so much!
