### ISSUE TITLE
Shouldn't be possible to invoke ed25519 and secp256k1 instructions from a program

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#19843]
#### Problem
The `ed25519` and `secp256k1` program instructions are a no-op if not invoked from the tx level and so devs could erroneously believe that verification is happening.

#### Proposed Solution
Prevent cross program invocations of these two programs

tag @jackcmay

**Comment by jackcmay** [comment]
This seems more like a documentation issue than anything else, we should make a clear delineation between programs and pre-compiles
