### ISSUE TITLE
mainnet incident 2021-09-14

### ISSUE THREAD

**Issue by leoluk** [solana-labs/solana#19869]
Network performance degraded shortly before 12:00 UTC, likely related to Raydium IDO launch.

<img width="853" alt="2021-09-14_15-47" src="https://user-images.githubusercontent.com/859697/133269523-742d04a0-2f90-4355-9894-832b36d6ed03.png">

You can upload your logs here:

```
ADDRESS=<your node ID>
TZ=UTC journalctl -u solana.service -o cat --utc --since '2021-09-14 11:00' --until '2021-09-14 14:00' | xz | curl --data-binary @- "http://logbin.certus.one:8080/solana-github-19869/$ADDRESS.log.xz"
```

For plain logfiles (non-systemd):

```
ADDRESS=<your node ID>
xz | curl --data-binary @- "http://logbin.certus.one:8080/solana-github-19869/$ADDRESS.log.xz" < your_logfile.log
```

https://gist.github.com/leoluk/3ea061afa8c073c18e096897a1bca9bd

**Comment by mankinskin** [comment]
Why would an IDO cause this? Shouldn't the network be able to handle that many transactions? And even if it stalled, why would it completely halt?

**Comment by im-0** [comment]
> For plain logfiles (non-systemd):

Does not work with log files rotated daily:

```text
curl: option --data-binary: out of memory                                                                                                                                                                curl: try 'curl --help' or 'curl --manual' for more information
```

I did following instead:

```bash
ADDRESS=<your node ID>
grep -E "^\[2021-09-14T(11|12|13)" your_logfile.log | xz | curl --data-binary @- "http://logbin.certus.one:8080/solana-github-19869/$ADDRESS.log.xz"
```

**Comment by ktkd** [comment]
did it, same way as im-0.

**Comment by eddyjlsh** [comment]
Txs are still being reported on https://explorer.solana.com/, is this issue only on certain nodes? TPS has dropped in the last 15 mins from ~1500tps to ~150tps, is this part of a fix?

**Comment by im-0** [comment]
> Txs are still being reported on https://explorer.solana.com/, is this issue only on certain nodes? TPS has dropped in the last 15 mins from ~1500tps to ~150tps, is this part of a fix?

My guess is that it queries transaction count via different RPC nodes behind a load balancer, and different RPC nodes are stuck at different number of processed transactions. May be not true.

**Comment by leoluk** [comment]
The explorer is confused - there's no transactions being processed right now

**Comment by leoluk** [comment]
https://docs.google.com/document/d/1tyk30UD10jYS-d1tyNznD5dte5CKy_zbPRJrP-wGzME/edit#

Ongoing coordination on Discord in #mb-validators

**Comment by intelliot** [comment]
> Today at 10:29 PM - Supermajority reached, 80% active stake detected, starting up now.
