### ISSUE TITLE
bootstrap-validator.sh Incompatible CPU detected: missing AVX2 support

### ISSUE THREAD

**Issue by bitcard** [solana-labs/solana#19866]
OS: ubuntu 16.04
clang: 3.9.1
rustc: 1.54.0

after cargo build --release
 
run NDEBUG=1 ./multinode-demo/bootstrap-validator.sh meet the follow error.

#### Problem
[2021-09-14T12:31:33.173218233Z WARN  solana_core::validator] CUDA is disabled
[2021-09-14T12:31:33.173233782Z INFO  solana_core::validator] AVX detected
[2021-09-14T12:31:33.173239997Z ERROR solana_core::validator] Incompatible CPU detected: missing AVX2 support. Please build from source on the target
Validator process aborted. The validator log may contain further details
./multinode-demo/bootstrap-validator.sh: line 165: kill: (9343) - No such process
############## validator exited, restarting ##############
./multinode-demo/bootstrap-validator.sh: line 141: kill: (9343) - No such process

**Comment by bitcard** [comment]
version 1.7.1 is ok, https://github.com/solana-labs/solana/issues/17599#issuecomment-921434229

**Comment by romeo555555** [comment]
v1.8 v1.7.11 v1.7.12 at compilation do not work without support of AVX2 commands by the processor

**Comment by romeo555555** [comment]
@bitcard I was able to run the version 17.1.12 of Solana node by virtualizing AVX2 support via Intel® SDE. It looks like <aplication_path>/sde -- <aplication_path>/bin/solana-test-validator in console. Also, when starting on Ubuntu, you first need to perform the settings indicated on the site. https://software.intel.com/content/www/us/en/develop/articles/intel-software-development-emulator.html
