### ISSUE TITLE
Slot rotation vs Vote period

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#1990]
#### Problem

The RFCs conflate slot rotation and voting period.  It makes sense to schedule a single leader for multiple voting periods to amortize the cost of rotation, but to treat each voting period as a rollback point.

#### Proposed Solution

Fix the RFCs.

tag: @rob-solana @carllin

**Comment by rob-solana** [comment]
Would like to nail down terminology to use to make distinct when leaders rotate and when validators vote.

Should a slot be some multiple of voting periods, or should the length of a leader slot, as expressed in voting periods, be something random?

Making distinct slots and periods also means that not every vote requires a checkpoint, because no fork can arise in the middle of a leader's broadcast slot.

**Comment by aeyakovenko** [comment]
@rob-solana
* slot, rollback point
* fortnight, multiple slots that a is leader consecutive

**Comment by rob-solana** [comment]
checkpoints are relatively expensive (currently a deep copy() of last_ids)... without making a checkpoint, the next vote can't contain a hash of state updates for the voting period....

**Comment by rob-solana** [comment]
I suppose the bank could checkpoint the accounts delta separately for each vote, and only checkpoint last_ids at rollback points...

**Comment by rob-solana** [comment]
is the length of a fortnight a network hyper parameter or stake-based?

**Comment by rob-solana** [comment]
slot's a terrible name for a voting period...

**Comment by aeyakovenko** [comment]
@rob-solana, voting needs to be fast for fast confirmations. We can make the deep copy cheaper

**Comment by aeyakovenko** [comment]
Fortnight is just the placeholder name for a chunk of time to be defined later

**Comment by rob-solana** [comment]
how about "turn"?

**Comment by garious** [comment]
How about replacing the term *voting period* with *block interval*?

**Comment by rob-solana** [comment]
#1995 binds the word "block" to the thing on which nodes vote (vote period), and leaves "slot" for leader period
