### ISSUE TITLE
no matches found: prompt://?key=m/44/501

### ISSUE THREAD

**Issue by wandrzejczak** [solana-labs/solana#19907]
#### Problem
I'm trying to run the CLI command for Paper wallet on Mac, I'm copy-pasting the documentation and I get errors like below.
Not sure what I'm doing wrong

```
$ solana-keygen pubkey prompt://?key=m/44'/501'
zsh: no matches found: prompt://?key=m/44/501

$ solana-keygen pubkey prompt://?full-path=m/44/2017/0/1
zsh: no matches found: prompt://?full-path=m/44/2017/0/1
```

Could anyone give me a hint of what I'm doing wrong?
Thank you.

**Comment by t-nelson** [comment]
Your shell is interpreting the `?`, single-quote the URI
