### ISSUE TITLE
Docs typo

### ISSUE THREAD

**Issue by joshwolff1** [solana-labs/solana#19919]
#### Problem

In the docs: https://docs.solana.com/cli/install-solana-cli-tools

> Download the binaries by navigating to https://github.com/solana-labs/solana/releases/latest, download solana-release-x86_64-unknown-linux-msvc.tar.bz2, then extract the archive:

#### Proposed Solution

Should be:

> Download the binaries by navigating to https://github.com/solana-labs/solana/releases/latest, download solana-release-x86_64-unknown-linux-gnu.tar.bz2, then extract the archive:

**Comment by t-nelson** [comment]
The proposal is incorrect given the context around the target text.  A second Windows (WSL) section could be added instead.  A PR for such changes would be great!

**Comment by joshwolff1** [comment]
Then the line "tar jxf solana-release-x86_64-unknown-linux-gnu.tar.bz2" must be incorrect. I think one of the two are

**Comment by joshwolff1** [comment]
Because it tells you to download x file and then tar it, but it uses different names, and only one of thsoe can be correct
