### ISSUE TITLE
Expand program instruction return codes from bool to u32/u64

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#1993]
#### Problem
Program Instructions don't have a way to report useful error codes when something goes wrong with the inputs into an Instruction, they can only report pass/fail.

#### Proposed Solution
Expand ProgramError to include a `UserDefinedError<u32>` enum item, then expose in the `getSignatureStatus` JSON RPC API.

**Comment by mvines** [comment]
#2003 makes progress here for native programs by turning the `bool` into `ProgramError`, but there's still no facility for a program to return a custom error code that is not defined by sdk/

**Comment by mvines** [comment]
Also note that the `ProgramError` from #2003 confusingly contains error codes that can be produced by the runtime.  That should be cleaned up as a part of this issue

**Comment by garious** [comment]
We added the Custom field, but in hindsight, that requires an allocation. Limiting to u64 makes a lot of sense, but it would be good to have a failing testcase before we do.

**Comment by CriesofCarrots** [comment]
Regarding exposing error data in `getSignatureStatus`: cc #3658
