### ISSUE TITLE
Integrate fullnode code with vote signing service

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#2000]
#### Problem
Update fullnode/validator code to call into vote signing service to sign voting transactions.

**Comment by rob-solana** [comment]
is this fixed, now?

**Comment by pgarg66** [comment]
https://github.com/solana-labs/solana/pull/2009
https://github.com/solana-labs/solana/pull/2368
https://github.com/solana-labs/solana/pull/2386
