### ISSUE TITLE
Passing data between instructions is clunky and requires tokens

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#2005]
#### Problem

In #2003, we see the return value of the entrypoint is `Result<(), ProgramError>`. That `()` effectively means that no data is communicated from a successful instruction. To pass data from one instruction to another, one must use an account. It's the Solana equivalent of writing to a file at an agreed upon path in one function and then reading that file from another. That aspect is clunky, but the situation is slightly worse because creating an account should generally require non-zero tokens. If a transaction pays just enough tokens to run 2 instructions, it will not have sufficient funds to create the intermediary account. Even if it did, the transaction would need to tack on an additional `SystemInstruction::Move` refund those tokens. Clunky!

#### Proposed Solution

Change `Result<(), ProgramError>` to `Result<Vec<u8>, ProgramError>` and then pass the `Vec<u8>` as input to the next instruction. This means that instead of returning `Ok(())`, they would all need to return `Ok(vec![])`, which is a little cumbersome, but luckily doesn't require an allocation: https://doc.rust-lang.org/1.26.0/core/ptr/struct.Unique.html.

**Comment by aeyakovenko** [comment]
@garious not sure this will work for that well outside of rust.  The return value would require an allocation, or be preallocated with space from an account and passed to the program.  If it is the latter, might as well just have the user do that directly as an account parameter.

**Comment by aeyakovenko** [comment]
@garious I feel like there are two kinds of programing problems here (1. there is only 1 lame joke about programming)
 * operations that can be performed by the client in several transactions that result in the same state transition
*

**Comment by aeyakovenko** [comment]
@garious what about the space to actually store the vec?  or is this a pointer to account data that is passed in?

**Comment by garious** [comment]
A pointer

**Comment by aeyakovenko** [comment]
@garious Cool, that would work! My only concern is with hardware of-load.  I am not sure how those pointer off-sets would be looked up on a GPU.  Maybe BPF can translate those looks up back into an account index.

**Comment by aeyakovenko** [comment]
@garious I've had another though.
```
enum InstructionArgs {
    /// explicit data encoded into the instruction arguments
    User(Vec<u8>),
    /// returned from an instruction at index
    Return{instruction_index: usize}
}
```
