### ISSUE TITLE
Bpf error

### ISSUE THREAD

**Issue by nehajain20683** [solana-labs/solana#20071]
#### Problem
when I am running cargo build-bpf following error is coming. 
"
BPF SDK: /home/neha/.local/share/solana/install/releases/1.7.8/solana-release/bin/sdk/bpf
Running: rustup toolchain list -v
Running: rustup toolchain link bpf /home/neha/.local/share/solana/install/releases/1.7.8/solana-release/bin/sdk/bpf/dependencies/bpf-tools/rust
error: not a directory: '/home/neha/.local/share/solana/install/releases/1.7.8/solana-release/bin/sdk/bpf/dependencies/bpf-tools/rust/bin' 
"
I have tried installing all the versions greater than 1.7.8. This running fine when using version 1.6.27. But then I am facing other challenges related to resolver. This working fine in a different system. I have updated rust as well. Not sure why this is not working in my system.

**Comment by dmakarov** [comment]
Can you check what is `home/neha/.local/share/solana/install/releases/1.7.8/solana-release/bin/sdk/bpf/dependencies/bpf-tools/rust/bin` on your file system?

**Comment by nehajain20683** [comment]
There is no bin created after installation of this version.
Only this path is created - /home/neha/.local/share/solana/install/releases/1.7.8/solana-release/bin/sdk/bpf/dependencies/bpf-tools/rust

**Comment by dmakarov** [comment]
What does the symbolic link `/home/neha/.local/share/solana/install/releases/1.7.8/solana-release/bin/sdk/bpf/dependencies/bpf-tools` links to?

**Comment by nehajain20683** [comment]
![Screenshot from 2021-09-21 20-40-06](https://user-images.githubusercontent.com/61583732/134198719-7089dd87-da5e-4e4b-a1b5-f616150e4520.png)
![Screenshot from 2021-09-21 20-42-12](https://user-images.githubusercontent.com/61583732/134198723-9caba76b-9691-4d78-9c5a-b28a4bdb033b.png)

**Comment by nehajain20683** [comment]
Its links to three things: llvm, rust, and version.md
But Rust folder is not having bin

**Comment by dmakarov** [comment]
> Its links to three things: llvm, rust, and version.md
> But Rust folder is not having bin

can you paste here the output of running in your shell the command `ls -al /home/neha/.local/share/solana/install/releases/1.7.8/solana-release/bin/sdk/bpf/dependencies/`?

**Comment by nehajain20683** [comment]
neha@neha-VivoBook-15-ASUS-Laptop-X507UAR:~$ ls -al /home/neha/.local/share/solana/install/releases/1.7.12/solana-release/bin/sdk/bpf/dependencies/
total 8
drwxrwxr-x 2 neha neha 4096 Sep 21 22:04 .
drwxr-xr-x 5 neha neha 4096 Sep 21 22:04 ..
lrwxrwxrwx 1 neha neha   39 Sep 21 22:04 bpf-tools -> /home/neha/.cache/solana/v1.9/bpf-tools

**Comment by nehajain20683** [comment]
neha@neha-VivoBook-15-ASUS-Laptop-X507UAR:~$ ls -al /home/neha/.local/share/solana/install/releases/1.7.12/solana-release/bin/sdk/bpf/dependencies/bpf-tools
lrwxrwxrwx 1 neha neha 39 Sep 21 22:04 /home/neha/.local/share/solana/install/releases/1.7.12/solana-release/bin/sdk/bpf/dependencies/bpf-tools -> /home/neha/.cache/solana/v1.9/bpf-tools

**Comment by dmakarov** [comment]
Can you remove `v1.9` directory in `/home/neha/.cache/solana` and also the files `/home/neha/.local/share/solana/install/releases/1.7.8/solana-release/bin/sdk/bpf/dependencies/bpf-tools` and `/home/neha/.local/share/solana/install/releases/1.7.8/solana-release/bin/sdk/bpf/dependencies/bpf-tools-v1.9.md`? and then run `cargo build-bpf` in your project.

**Comment by nehajain20683** [comment]
Wow....Its working now. Thank you so much!!!!!!!

**Comment by dmakarov** [comment]
I'm closing the issue. If something else comes up, please, reopen or create a new one.
