### ISSUE TITLE
devnet airdrop not working

### ISSUE THREAD

**Issue by rigottimarcello** [solana-labs/solana#20086]
Every time I try to get some SOL airdropped on the devnet it is not working
Requesting airdrop of 1 SOL
Error: unable to confirm transaction. This can happen in situations such as transaction expiration and insufficient fee-payer funds

this is what's is happening, I also tried faucet website and same, transaction is never created

**Comment by devbrooklyn** [comment]
Also facing the same issue here.

**Comment by chahakshah111** [comment]
I'm also facing the same issue.

**Comment by t-nelson** [comment]
https://discord.com/channels/428295358100013066/749059399875690557/889550333515300956

**Comment by SuperCipher** [comment]
I got the same problem
```
solana airdrop 5 2qLiUVKmQYYSKqzPDH1MR7BjjBy9Gcs6hZPtX2QkZH2P                                             
Requesting airdrop of 5 SOL
Error: airdrop request failed. This can happen when the rate limit is reached.
```
I got over it by using this https://solfaucet.com/

**Comment by t-nelson** [comment]
> I got the same problem
> 
> ```
> solana airdrop 5 2qLiUVKmQYYSKqzPDH1MR7BjjBy9Gcs6hZPtX2QkZH2P                                             
> Requesting airdrop of 5 SOL
> Error: airdrop request failed. This can happen when the rate limit is reached.
> ```

Respect the rate limits and you won't have problems

> I got over it by using this https://solfaucet.com/

We have no affiliation with that domain and cannot support it
