### ISSUE TITLE
Repair and replay blocks on hard fork to avoid rolling back optimistically confirmed blocks

### ISSUE THREAD

**Issue by carllin** [solana-labs/solana#20153]
#### Problem
When restarting the cluster from some socially agreed upon optimistically confirmed block `S`, we cannot guarantee there was not a later block `T > S` that was also optimistically confirmed

#### Proposed Solution
1. Pick some block we think is the latest optimistic slot ``S based on social consensus
2. We know that any later optimistic slot `T > S` was voted on `2/3+` of the network, so `>1/3+` of the correct validators must have received block. Thus we repair up to the latest slot `T` that has been voted on by > 1/3 of the validators. TODO: Figure out which slots have been completed by > 1/3 of the validators, maybe use something like `EpochSlots`?
3. Let consensus run to root  the actual latest optimistic slot

@aeyakovenko fyi, as per our discussion

**Comment by AshwinSekar** [comment]
closing in favor of https://github.com/solana-foundation/solana-improvement-documents/pull/46
