### ISSUE TITLE
Booting from last proposed optimistic slot on full cluster restart

### ISSUE THREAD

**Issue by AshwinSekar** [solana-labs/solana#20154]
#### Problem
During restart when we boot from a proposed optimistic slot, we have validators verify that there are no missing optimistic slots.

#### Proposed Solution
During restart each validator gossips their last vote's fork as it is connected to the proposed last optimistic slot. Let `N` be the % of stake that participates in the restart. Our current threshold for restart is 80%, so the conditions for restart becomes `N > 80% && max_fork < 66.66% + `K<sub>Safety</sub>` - (100% - N)`. This guarantees that even if the remaining `100-N %` of the stake votes on the max fork, this fork will still not be optimistically confirmed as it will have less than 2/3 of the stake. We additionally add the K<sub>Safety</sub> buffer in order to increase our confidence percentage. 

Example scenario, 1000 evenly staked validators, 665 votes on a slot (insufficient for optimistic confirmation). 800 validators participate in the restart. If K<sub>Safety</sub>` = 0` then we need `max_fork < 46.66`. The probability that this is not satisfied is 
![Screen Shot 2021-09-23 at 8 46 28 PM](https://user-images.githubusercontent.com/9343834/134615097-c54f676c-c44a-443e-bb59-6ad68146812f.png) which is `99.99999%`

However as `N` increases we become more likely to pass this check. Even in this extreme case, if we have `N = 89`, we only have a `27%` chance of failing the check. This is further alleviated if we set an appropriate value for K<sub>Safety</sub>, however depending on how high we set this value we could start running into false positives. 

An additional consideration is if optimistic slot violations are detected. It could be the case that a slot was either incorrectly assumed to be optimistic, or considered optimistic but later reverted because of a validator slashing.

**Comment by aeyakovenko** [comment]
So the other idea we had was that to avoid this mess, validators simply pick a slot in the future that they all stop at until 80%+ stop at that slot.

**Comment by carllin** [comment]
@aeyakovenko why is ~1 hour and 80% synced sufficient? Seems like you could have had an optimistic slot at a point beyond that point in time?

**Comment by AshwinSekar** [comment]
closing in favor of https://github.com/solana-foundation/solana-improvement-documents/pull/46
