### ISSUE TITLE
CORS Error when accessing to api

### ISSUE THREAD

**Issue by ThreadShakur** [solana-labs/solana#20157]
All is working fine on localhost dev server, but on production i got CORS error when trying make request to solana api

![image](https://user-images.githubusercontent.com/17909421/134622274-ec325508-b910-4249-ab9e-2bfe5b386000.png)
Has anyone encountered this?

**Comment by brianlong** [comment]
@ThreadShakur The message says that you have been blocked. The public service is not suitable for product launches or high-traffic applications.

**Comment by kotecaava** [comment]
@ThreadShakur we had the same problem it appears that Solana API had a problem with the .art extension we moved to .com to fix the issue and it worked I don't know the details to explain more about the topic.

**Comment by t-nelson** [comment]
Closing as per https://github.com/solana-labs/solana/issues/20157#issuecomment-926388396

**Comment by ZhoufangErqiangu** [comment]
i have met the same problem, change to serum url is useful.
