### ISSUE TITLE
RPC call to track feature activations

### ISSUE THREAD

**Issue by linuskendall** [solana-labs/solana#20196]
#### Problem

This relates to #20003  . Would it be possible to expose the feature status in an RPC call? In that way we could also add it in to monitoring to highlight when a feature is planned to be activated,

currently I have a bit of a kludge:
```
/home/solana/.local/share/solana/install/active_release/bin/solana feature status --output json | jq -r '.features[] | "solana_feature{id=\"\(.id)\", description=\"\(.description)\", status=\"\(.status)\"} \(.sinceSlot // 0)"' >/var/lib/node_exporter/solana_feature.prom 
```

If possible perhaps the feature set for a particular slot (i.e. next epoch) could be published? in this way we could contrast feature set of current node with feature set of next epoch and warn if the node has a feature set that will not be supported next epoch?

#### Proposed Solution

New RPC call getFeatures to provide details on the features and/or some way to get the feature set identifier for a particular epoch?

**Comment by mvines** [comment]
Nice idea!  I think this could be done entirely within the `solana feature ...` family of commands without adding a new RPC method

For example `solana feature status` could include another flag that allows for easy reporting when the current node's feature set, visible over RPC from `getVersion`:
```
$ curl https://api.mainnet-beta.solana.com -X POST -H "Content-Type: application/json" -d '
  {"jsonrpc":"2.0","id":1, "method":"getVersion"}
'
{"jsonrpc":"2.0","result":{"feature-set":3623616870,"solana-core":"1.6.25"},"id":1}
```

is different from the supermajority, the feature set for all nodes is readable from [getClusterNodes](https://docs.solana.com/developing/clients/jsonrpc-api#getclusternodes)

Most of that code is already in `solana feature status` already

**Comment by linuskendall** [comment]
Right, so yes building it into `feature status` would be very helpful and I can just continue to parse it out from there.

I didn't think about getClusterNodes but actually that helps a lot - we can use getClusterNodes to calculate % on each feature set. Whatever feature set has supermajority we know that it will be the active one next epoch, right? So we can alert on any node which doesn't have that.

**Comment by mvines** [comment]
> Whatever feature set has supermajority we know that it will be the active one next epoch, right? 

Yes, or we risk possible cluster death if any features are activated at that time (the feature activation tooling prevents such a thing from happening in general)

**Comment by linuskendall** [comment]
@mvines Looks like my script above also broke due to --output json includign this:

```
To activate features the stake must be >= 95%
Tool Feature Set: 1824749018
Cluster Feature Sets and Stakes:
  140464022  - 0.15%
  1813598585 - 0.00%
  1824749018 - 93.87%  <-- me
  2013646575 - 0.00%
  2995838076 - 5.73%
```
