### ISSUE TITLE
RPC: Node can't catch up until restart and/or ledger purge

### ISSUE THREAD

**Issue by linuskendall** [solana-labs/solana#20194]
#### Problem

We have increasingly regular seen a pattern where:

 - RPC is pushed off the tip of the network by some traffic event (usually a spike in getPA/getAI/getMA)
 - RPC node falls behind and continues to be unable to catch up, even after traffic has been removed from the node 
 - When the node is restarted and/or ledger purged, it catches up and can continue serving traffic normally

Here's an example of such an event:

Small spike in traffic around 9 am UTC:
<img width="1284" alt="Screenshot 2021-09-25 at 03 06 54" src="https://user-images.githubusercontent.com/5172293/134763029-4071227e-6c11-40a0-b61c-02db275d5f23.png">

<img width="1284" alt="Screenshot 2021-09-25 at 03 05 55" src="https://user-images.githubusercontent.com/5172293/134763036-4cc68ca8-9294-475f-ba96-f8c956268dc5.png">

Node begins to fall behind and continue to fall behind until it is restarted

<img width="1283" alt="Screenshot 2021-09-25 at 02 38 31" src="https://user-images.githubusercontent.com/5172293/134763071-085652a5-1038-4056-af02-000b9de3257f.png">

Here is a view on the traffic:

<img width="640" alt="Screenshot 2021-09-25 at 02 39 46" src="https://user-images.githubusercontent.com/5172293/134763046-5cd33503-776c-4197-9811-a7b606ca5c28.png">

When the green loopback traffic stops, that's when the validator is taken out of cluster. It is clear that it is starting repair at this time as it is receiving more than sending. 

Worth noting is that the node went back to keep in line with the network after a restart, and continued to serve approximately the same overall traffic.

All metrics such as memory, CPU, disk iops etc. look normal throughout the entire time.

#### Proposed Solution

First step would be if there are metrics we can look out on the validator to identify what the issue actually is? Is it livelocks with threads that are running or something else is going on? 

The observed behaviour is that some kind of traffic pattern results in a validator state that locks up and is unable to continue keeping up with the network.

**Comment by ryoqun** [comment]
@linuskendall what cpu usage over the time?
