### ISSUE TITLE
Rust 1.26.0 refactoring

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#202]
Some fun new features in the latest Rust! Check out the release notes and see if you can find ways to make our codebase more approachable for newcomers like you!

https://blog.rust-lang.org/2018/05/10/Rust-1.26.html

For example, anywhere we're using `ref` (`git grep -w ref`), you might see code like:

```rust
fn hello(arg: &Option<String>) {
    match arg {
        &Some(ref name) => println!("Hello {}!", name),
        &None => println!("I don't know who you are."),
    }
}
```

And perhaps it can be changed to this:

```rust
fn hello(arg: &Option<String>) {
    match arg {
        Some(name) => println!("Hello {}!", name),
        None => println!("I don't know who you are."),
    }
}
```

And a little more challenging but functions that end with a call to `collect()` and return a `Vector` can probably be changed into faster streaming functions that return an `Iterator`:

```rust
fn foo() -> impl Iterator<Item = i32> {
```

Go play!

**Comment by jackson-sandland** [comment]
This looks fun. Opening a branch.
