### ISSUE TITLE
No on-chain cluster configuration

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#2020]
#### Problem
 over time, network parameters (e.g. hashes per tick) will need to be changed and the changes need to be agreed by stake holders.  no mechanism exists for this today.

#### Proposed Solution
build a parameters program?

**Comment by mvines** [comment]
We now have the config program (https://github.com/solana-labs/solana/tree/master/programs/config_api) that can be used to store on-chain parameters.
