### ISSUE TITLE
Rename NCP to CPG

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#2026]
#### Problem

The control plane gateway is called the network control plane.

#### Proposed Solution

Rename the network control plane (NCP) to control plane gateway (CPG)

**Comment by garious** [comment]
A few more related name changes. I'd like to describe a fullnode has the composition of a 5 primary components: TPU, TVU, RPU, CPG, and DPG, where those are acronyms for the Transaction Processing Unit, Transaction Validation Unit, Request Processing Unit, Control Plane Gateway and Data Plane Gateway respectively.

So I propose the following changes:

* JSON RPC Service -> RPU
* NCP -> CPG
* BroadcastStage -> DPG

Alternatively, if we don't like the TLAs, I'd propose leaving JSON RPC Service as-is and changing just:

* NCP -> GossipService
* BroadcastStage -> BroadcastService

Thoughts on those names?

**Comment by garious** [comment]
@sagar-solana, @rob-solana, thoughts on names here? NCP is a terrible name. If we're going to change it, I'd like to use this as an opportunity to add consistency with other components.

Also, gossip is technically a form of broadcasting. Is there something more precise we can use to describe that data plane gateway? Maybe MulticastService? I'm looking for a word that is clearly *not* gossip or *not* the control plane.

**Comment by rob-solana** [comment]
could call it avalanche or whatever the new name is

**Comment by rob-solana** [comment]
NCP port could just be renamed to "gossip"
