### ISSUE TITLE
Add Azure support to net/

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#2028]
Should just be a matter of writing a cloud provider plugin like the existing AWS and GCP providers

**Comment by danpaul000** [comment]
Azure has some helpful looking tools in their github:  https://github.com/Azure

Namely, the CLI tools as well as some standard deployment templates we can use to build on top of.
https://azure.microsoft.com/en-us/resources/templates/101-vm-simple-linux/
https://github.com/Azure/azure-quickstart-templates

https://docs.microsoft.com/en-us/cli/azure/install-azure-cli?view=azure-cli-latest
