### ISSUE TITLE
Can't send NFT (SPL Token with decimal 0) on devnet for web wallets

### ISSUE THREAD

**Issue by jamland** [solana-labs/solana#20296]
#### Problem

This is a long-time issue. I've noticed it in June-July for the first time.
I can't send SPL Tokens from phantom or sollet wallet to a different wallet. 
Their support says it is most likely not the issue with the wallet.
Some people say it might be an issue with devnet (and I think the same on testnet). And it works well on mainnet-beta.

Also, I can confirm `spl-token transfer` cli works well on all networks.

phantom output

![image](https://user-images.githubusercontent.com/188568/135130669-00111e88-657e-413b-9d7d-16152756909c.png)

#### Proposed Solution

Is anyone can explain what causes the issue and how to fix it?
Is it network-specific issue or wallet?

**Comment by t-nelson** [comment]
This is a problem with the wallet.  It's constructing transactions with an instruction from a program that's not deployed at the same address as mainnet-beta.  I suggest you report down stream

**Comment by jamland** [comment]
Thank you. I will
