### ISSUE TITLE
RPC: First and last blocks of an epoch are bloated due to rewards

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#20299]
#### Problem
The first block of an epoch can be as large as 32MB uncompressed due to hundreds of thousands of stake accounts. Similarly, the last block of an epoch lists validator rewards due to rent payments and those can have hundreds to thousands of rows depending on how many validators are active in a cluster.

#### Proposed Solution
- Exclude rewards from block responses for now.
- Add separate API for fetching rewards for a given block or epoch and a list of addresses?

cc @CriesofCarrots @mvines

**Comment by CriesofCarrots** [comment]
It would be somewhat breaking to exclude rewards by default, but they can be optionally excluded now by passing the config: `{"rewards": false}` https://docs.solana.com/developing/clients/jsonrpc-api#getblock
You can also request just the rewards and block metadata by passing `{"rewards": false, "transactionDetails": "none"}`

Does that suit the block needs?

Also, this returns rewards for a given epoch for a list of addresses: https://docs.solana.com/developing/clients/jsonrpc-api#getinflationreward

**Comment by jstarry** [comment]
> It would be somewhat breaking to exclude rewards by default, but they can be optionally excluded now by passing the config: {"rewards": false} https://docs.solana.com/developing/clients/jsonrpc-api#getblock

I think we might need to make that breaking change to reduce the load on RPC servers. We could start with a deprecation notice. It just doesn't seem sustainable to allow any kind of responses that large.

> Also, this returns rewards for a given epoch for a list of addresses: https://docs.solana.com/developing/clients/jsonrpc-api#getinflationreward

Ah thanks!
