### ISSUE TITLE
solana-cli 1.6.27 on mainnet-beta unable to delegate stake

### ISSUE THREAD

**Issue by jayhohoho2019** [solana-labs/solana#20304]
#### Problem
solana delegate-stake ~/.config/solana/validator-stake-keypair.json ~/.config/solana/vote-account-keypair.json
Error: Bad parameter: Unable to delegate. Vote account has no root slot

Validator seems to be otherwise running, filling up space in accounts and ledger drives. 

Another issue is that the timestamp in log seems to be UTC or something, not matching system time.  

Ubuntu server 20.04.3
5.4.0-88-generic #99-Ubuntu SMP Thu Sep 23 17:29:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jayhohoho2019** [comment]
Another issue noticed: 
%solana catchup ~/.config/solana/validator-keypair.json
⠒ RPC service not found _[validator pubkey here]

**Comment by jayhohoho2019** [comment]
delegate-stake became possible after my node caught up to the cluster.  catchup works too with the --our-localhost [PORT] arg.  timestamp is still UTC but I'm closing this for now.

**Comment by PoCk3T** [comment]
@jayhohoho2019 how concretely did you get to resolve this?

My node is fully caught up, but if I follow [this step](https://docs.solana.com/running-validator/validator-stake#delegate-stake) and run the command
`solana delegate-stake ~/validator-stake-keypair.json ~/vote-account-keypair.json`
all I get is
`Error: Bad parameter: Unable to delegate. Vote account has no root slot`

My validator-stake-keypair.json is [this stake account](https://explorer.solana.com/address/8aVYQ67HjWs6THo6VpKXw9C5hBTMibzYbeJSQtZfpui8)

My vote-account-keypair.json is [this voting account](https://explorer.solana.com/address/GuayDCCr1dMEE2oM7po3K5DNhzQTqLQCY3uVA5bz8HCV), and indeed, Solana Explorer should show "N/A" for "Root Slot", but I'm not sure how to get a root slot assigned..

PS: I'm way past any "validator stake warm-up", it has been few days I'm fighting with this :(
