### ISSUE TITLE
Remove costly RefCell checks

### ISSUE THREAD

**Issue by armaniferrante** [solana-labs/solana#20311]
The flat cost for CPI overhead is relatively expensive, sitting at about `9678` compute units when measuring a call from `solana_program::invoke_signed` to the entrypoint of the program  being invoked.

Approximately `5815` of these units are spent on this block of code here https://github.com/solana-labs/solana/blob/c02ef395ede79af57ff8eeacf7817ad2ab2d2e0f/sdk/program/src/program.rs#L23-L37, which may not be required since programs can be responsible for ensuring their code doesn't trigger a RefCell induced panic. 

Removing this block would be beneficial for programs that do a lot of CPI.

Tag @jstarry.

**Comment by jstarry** [comment]
Thanks for the issue @armaniferrante! I just spoke with @jackcmay about this and it is important that devs don't accidentally call invoke with account info's which have active mutable borrows for lamports or data as that is not something Rust is happy about. We can add an unsafe option for devs that don't want that safety guarantee though

**Comment by jackcmay** [comment]
Yup, we've considered `invoke_unchecked()` which does not check the refcells.  What do you think about that?

**Comment by armaniferrante** [comment]
> Yup, we've considered `invoke_unchecked()` which does not check the refcells. What do you think about that?

Sounds good to me.

**Comment by armaniferrante** [comment]
We may be able to alleviate the need for the `unchecked` variant by rewriting the checks here. For example,

```rust
    for account_info in acc_infos.iter() {
        let _ = account_info.try_borrow_mut_lamports()?;
        let _ = account_info.try_borrow_mut_data()?;
    }
```

Costs 976 compute units, though this code is breaking.

**Comment by jackcmay** [comment]
Some folks pass their entire account infos and they may have taken borrows on accounts that are not referenced in the instruction.  Is that what you were referring to as the breaking change?

I think giving the option to avoid even the 1k units by providing the unchecked would be handy.  My thinking in the past was that folks who cared enough and wanted to take the risk would write their own `invoke` method to bypass the checks.

**Comment by armaniferrante** [comment]
> Some folks pass their entire account infos and they may have taken borrows on accounts that are not referenced in the instruction. Is that what you were referring to as the breaking change?
> 
> I think giving the option to avoid even the 1k units by providing the unchecked would be handy. My thinking in the past was that folks who cared enough and wanted to take the risk would write their own `invoke` method to bypass the checks.

Correct. If one holds a mutable reference to data for an AccountInfo with `is_writable == false` across a CPI, then the above change will break the program since a mutable and immutable borrow are simultaneously held. Also agreed that an option to avoid the 1k units is useful regardless.

**Comment by bonedaddy** [comment]
> Thanks for the issue @armaniferrante! I just spoke with @jackcmay about this and it is important that devs don't accidentally call invoke with account info's which have active mutable borrows for lamports or data as that is not something Rust is happy about. We can add an unsafe option for devs that don't want that safety guarantee though

@jackcmay 

when using the unchecked/unsafe options, what exactly are the risks? shouldn't anyth

**Comment by jackcmay** [comment]
Rust may make assumptions about the state of r vs rw data when passing accounts to CPI without taking a reference first.

**Comment by bonedaddy** [comment]
i see, so then this should only at worst cause a runtime panic?

**Comment by jackcmay** [comment]
Could result in values being cached in registers that were changes elsewhere

**Comment by bonedaddy** [comment]
What do you mean by elsewhere? How long does the cache last, is it just for the duration of the instruction, or is it persisted in-between transactions.

**Comment by jackcmay** [comment]
This has less to do with Solana and more to do with Rust's compiler.  Registers may hold values that rust thinks are immutable, but since the RefCell was ignored were actually modified.  This could result in stale values being read.  Could be other issues as well

**Comment by bonedaddy** [comment]
Thanks!
