### ISSUE TITLE
 custom program error: 0xc

### ISSUE THREAD

**Issue by rzlong** [solana-labs/solana#20341]
#### Problem
I trade ray/usdt in raydium by rpc api, My expected effect is [https://solscan.io/tx/rj4AxGnb4KAhwe5NVNTAPPCXD3aqkMipjvGCwKSSGGT5wLuew8wg15UDNL5TM9vBaxD7ntwRgkgyhPGUx8HdkWg](url)
it return me `Transaction simulation failed: Error processing Instruction 0: custom program error: 0xc`, what's this?  Thanks!

#### Proposed Solution
I don't know how to solve it.

**Comment by t-nelson** [comment]
This is not an issue with solana. Please report downstream to Raydium

**Comment by steveluscher** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Solana itself.

Questions like yours deserve a purpose-built Q&A forum. Unless you have evidence that this is a bug with Solana itself, please post your question to the Solana Stack Exchange using this link: https://solana.stackexchange.com/questions/ask
