### ISSUE TITLE
solana windows installer link not working

### ISSUE THREAD

**Issue by CLIcoder** [solana-labs/solana#20368]
#### Problem

the link :  https://release.solana.com/v1.7.14/solana-install-init-x86_64-pc-windows-msvc.exe

No source code for windows also

**Comment by macfromtheblock** [comment]
I think they are on it. I posted too.
Meanwhile i'm using version 1.7.12

**Comment by CriesofCarrots** [comment]
Thanks, closing as dupe of #20382
