### ISSUE TITLE
JSON RPC getConfirmedBlock return null blockTime and blockHeight

### ISSUE THREAD

**Issue by oun** [solana-labs/solana#20371]
#### Problem

The blockTime and blockHeight fields are null when calling getConfirmedBlock for some slot.
Is there any workaround to calculate estimated blockTime and blockHeight?

**Comment by CriesofCarrots** [comment]
Yeah, slots before we started storing this block metadata will return `null`.

You can calculate a rough estimate of blockTime by determining the number of slots that elapsed (slot with known blockTime minus desired slot) and multiplying by the estimated slot duration. The target slot duration is 400ms, but the actual duration has been more like 500-700ms.

You can calculate blockHeight precisely by tracking all parent blocks backward using the `getConfirmedBlocks` or `getConfirmedBlocksWithLimit` rpcs. Eg, say slot 10 reports blockHeight 8 and `getConfirmedBlocks` for the range 6-10 returns [6, 7, 9, 10], you know slot 9 = blockHeight 7, slot 7 = blockHeight 6, slot 6 = blockHeight 5.

**Comment by oun** [comment]
Thanks for your help.

**Comment by CriesofCarrots** [comment]
I'm going to close this issue, but please reach out to us on Discord if you have more questions in this area: https://solana.com/discord
