### ISSUE TITLE
benchmarking issues (v1.7.14 only)

### ISSUE THREAD

**Issue by agjell** [solana-labs/solana#20373]
When benchmarking (following [this](https://docs.solana.com/cluster/bench-tps) doc) a single node with v1.7.14 I get a warning during compilation:
```
warning: /mnt/ramdisk/solana-src-v1.7.14/validator/Cargo.toml: unused manifest key: target.cfg(not(target_env = "msvc")).dependencies.jemallocator.feautres
```
Further, I'm able to run `bench-tps.sh`, but it produces a very low score. 1,330 in my case, compared to ~68,000 for the other v1.7.x releases. It works fine with all other releases in the 1.5.x, 1.6.x and 1.7.x ranges.

I usually do three benchmark runs. When starting the second run on v1.7.14 it produces this error:
```
[2021-10-01T17:47:57.821052766Z ERROR solana_metrics::metrics] datapoint: panic program="bench-tps" thread="main" one=1i message="panicked at 'Error requesting airdrop: to addr: 127.0.0.1:9900 amount: 1398135952500000 Err(Custom(\"ForUser(\\"signature not found after 21 seconds\\")\"))', /mnt/ramdisk/solana-src-v1.7.14/bench-tps/src/bench.rs:748:25" location="/mnt/ramdisk/solana-src-v1.7.14/bench-tps/src/bench.rs:748:25"
```

**Comment by CriesofCarrots** [comment]
The warning is fixed here: https://github.com/solana-labs/solana/pull/20351, v1.7: https://github.com/solana-labs/solana/pull/20354
I doubt that's the cause of your tps regression, though.

**Comment by agjell** [comment]
Tried benchmarking the latest v1.7. Warning was gone, but TPS regression persisted. Just like you suspected. Same result with the master branch.

**Comment by sakridge** [comment]
I think related to this: https://github.com/solana-labs/solana/pull/20331
For now, revert if you want to test, we will look into tweaking the parameters to try and resolve the regression.
