### ISSUE TITLE
Add links to guide for Phantom wallet

### ISSUE THREAD

**Issue by lopeselio** [solana-labs/solana#20380]
#### Problem
I was looking to build on Solana. In the wallets section [Web Wallets](https://docs.solana.com/wallet-guide/web-wallets), there is no link provided for developing with Phantom on Solana in the documentation.

#### Proposed Solution
There should be something like 

> Check out our guide for using [Phantom](https://docs.phantom.app/).

**Comment by steviez** [comment]
https://github.com/solana-labs/solana/pull/22999
