### ISSUE TITLE
can't build solana latest version

### ISSUE THREAD

**Issue by rkonda20** [solana-labs/solana#20390]
#### Problem
I am running Ubuntu v 18 and trying to build the latest code

   Compiling libsecp256k1 v0.6.0
error: could not compile `libsecp256k1`

Caused by:
  process didn't exit successfully: `rustc --crate-name libsecp256k1 --edition=2018 /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/libsecp256k1-0.6.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="default"' --cfg 'feature="hmac"' --cfg 'feature="hmac-drbg"' --cfg 'feature="sha2"' --cfg 'feature="static-context"' --cfg 'feature="std"' --cfg 'feature="typenum"' -C metadata=874b71764ec6347d -C extra-filename=-874b71764ec6347d --out-dir /home/ubuntu/solana-test/solana/target/debug/deps -L dependency=/home/ubuntu/solana-test/solana/target/debug/deps --extern arrayref=/home/ubuntu/solana-test/solana/target/debug/deps/libarrayref-1170f8c828ab8d28.rmeta --extern base64=/home/ubuntu/solana-test/solana/target/debug/deps/libbase64-3a8d5a57fd8274f7.rmeta --extern digest=/home/ubuntu/solana-test/solana/target/debug/deps/libdigest-7c04696e4c42676b.rmeta --extern hmac_drbg=/home/ubuntu/solana-test/solana/target/debug/deps/libhmac_drbg-4c12dff52eca0361.rmeta --extern libsecp256k1_core=/home/ubuntu/solana-test/solana/target/debug/deps/liblibsecp256k1_core-5f3c6c6031e9b3bd.rmeta --extern rand=/home/ubuntu/solana-test/solana/target/debug/deps/librand-169c858af48ce82e.rmeta --extern serde=/home/ubuntu/solana-test/solana/target/debug/deps/libserde-d9f9ddfe27b2d698.rmeta --extern sha2=/home/ubuntu/solana-test/solana/target/debug/deps/libsha2-6bbaa12590c3611b.rmeta --extern typenum=/home/ubuntu/solana-test/solana/target/debug/deps/libtypenum-17020373090ddbe4.rmeta --cap-lints allow` (signal: 9, SIGKILL: kill)
warning: build failed, waiting for other jobs to finish...

**Comment by GZGavinZhao** [comment]
You probably don't have enough RAM. How much RAM does your machine have?

Also see [this](https://github.com/rust-lang/rust/issues/51309) issue.

**Comment by t-nelson** [comment]
Yes, almost certainly you have insufficient RAM.  Try limiting `cargo` jobs to RAM_GB/3.

If you have any further issues, please join us on https://solana.com/discord.  We don't use github for support
