### ISSUE TITLE
Issue when sending transactions to a multi node setup on different machines

### ISSUE THREAD

**Issue by deepaltennakoon92** [solana-labs/solana#20391]
#### Problem
Hello,
I connected 1 bootstrap validator, and three other validators across 4 VM machines in OpenStack. Each VM running a solana validator. I changed the IPs from localhost to the relevant IPs of the machines in the validator.sh scripts. I tried to connect the validators using `NDEBUG=1 ./multinode-demo/validator-x.sh --entrypoint <IP-of-bootstrap-validator>:8001`
. Consequently, I spawned a separate VM to act as the client and send transactions. I pointed the IP in multinode-demo/bench-tps.sh to the bootstrap validator IP. However, when I send transactions using NDEBUG=1 ./multinode-demo/bench-tps.sh, I get the following error (attached image also):

> `[2021-10-03T06:06:11.641789142Z INFO  solana_bench_tps::bench] Get lamports...
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("reqwest::Error { kind: Request, url: Url { scheme: \"http\", host: Some(Ipv4(127.0.0.1)), port: Some(8899), path: \"/\", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError(\"tcp connect error\", Os { code: 111, kind: ConnectionRefused, message: \"Connection refused\" })) }")', /home/ubuntu/solana/bench-tps/src/bench.rs:893:64
> stack backtrace:
>    0: rust_begin_unwind
>              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/std/src/panicking.rs:515:5
>    1: core::panicking::panic_fmt
>              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/panicking.rs:92:14
>    2: core::result::unwrap_failed
>              at /rustc/c8dfcfe046a7680554bf4eb612bad840e7631c4b/library/core/src/result.rs:1599:5
>    3: solana_bench_tps::bench::generate_and_fund_keypairs
>    4: solana_bench_tps::main
> note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
> [2021-10-03T06:06:11.915079514Z ERROR solana_metrics::metrics] datapoint: panic program="bench-tps" thread="main" one=1i message="panicked at 'called `Result::unwrap()` on an `Err` value: Custom(\"reqwest::Error { kind: Request, url: Url { scheme: \\"http\\", host: Some(Ipv4(127.0.0.1)), port: Some(8899), path: \\"/\\", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError(\\"tcp connect error\\", Os { code: 111, kind: ConnectionRefused, message: \\"Connection refused\\" })) }\")', /home/ubuntu/solana/bench-tps/src/bench.rs:893:64" location="/home/ubuntu/solana/bench-tps/src/bench.rs:893:64"

`
![image](https://user-images.githubusercontent.com/85627000/135742461-a7cf8bc3-bc7a-41ce-9e95-222861909c2b.png)

The console output for a validator looks as follows:
![image](https://user-images.githubusercontent.com/85627000/135742670-e08d1d7f-359d-4e7b-8e47-c590ce43c820.png)

P.S. - I was successfully able to benchmark Solana in a single VM/machine but not on multiple machines this way. I have joined your discord as well. Not sure who to contact for assistance.

**Comment by usama-nadeem** [comment]
I have been facing the same issue. Did you get any leads?

**Comment by convowork1** [comment]
Why there is no answers to such problems?
