### ISSUE TITLE
https://explorer.solana.com/ does not work since few days.

### ISSUE THREAD

**Issue by Ektwnl** [solana-labs/solana#20396]
#### Problem

https://explorer.solana.com/ does not work since few days.

#### Proposed Solution

it archived. I think that's an issue about the server or something.

**Comment by tredondo** [comment]
Works fine for me.

**Comment by sanjeevgiri** [comment]
This seems to be working now. Can this be closed?

**Comment by t-nelson** [comment]
This was linked back to a misconfigured cloudflare proxy.  Should be all good now

**Comment by Ektwnl** [comment]
now it works! Thx
:)
