### ISSUE TITLE
How to build Wrapper Contract from already deployed contract

### ISSUE THREAD

**Issue by gurucrypto23** [solana-labs/solana#20408]
#### Problem

My name is Justin and going to create wrapper contract of Raydium-io for updating the deposit and redeem function
It would be great if you let me know the best way to do that.

**Comment by t-nelson** [comment]
Raydium folks would be the ones to ask about such an endeavor

**Comment by steveluscher** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Solana itself.

Questions like yours deserve a purpose-built Q&A forum. Unless you've already received a response from Raydium, post your question to the Solana Stack Exchange using this link: https://solana.stackexchange.com/questions/ask
