### ISSUE TITLE
Document how to add funds to an existing stake account

### ISSUE THREAD

**Issue by tredondo** [solana-labs/solana#20400]
https://docs.solana.com/cli/delegate-stake doesn't mention at all how to *add* funds to a stake account. The [Staking](https://docs.solana.com/staking) page suggests that stake accounts are different beasts, so it's not clear how to add funds to them. Would `solana transfer --from <KEYPAIR> <STAKE_ACCOUNT_ADDRESS>` work? The page doesn't explicitly say, and since [withdrawing stake is a special command](https://docs.solana.com/cli/delegate-stake#withdraw-stake), instead of a `transfer` in the opposite direction, adding funds to a staking account isn't obvious.

Also, what happens to those added funds? When/how do they get delegated? Are they automatically assigned to the validator of the stake account?

https://docs.solana.com/cli/manage-stake-accounts doesn't touch on that either.

**Comment by mvines** [comment]
Good point.  https://docs.solana.com/cli/delegate-stake is where I think this information could go, in a new section called Merge Stake (which does the opposite of https://docs.solana.com/cli/delegate-stake#split-stake)

**Comment by t-nelson** [comment]
A good starting point would be the staking FAQ copy.  Fragmented info for the win :pensive: 

https://solana.com/staking#stakeaccounttokens
