### ISSUE TITLE
Explain `<STAKE_ACCOUNT_KEYPAIR>` in deriving stake account addresses

### ISSUE THREAD

**Issue by tredondo** [solana-labs/solana#20416]
#### Problem
At https://docs.solana.com/cli/delegate-stake#advanced-derive-stake-account-addresses, it's not clear what `<STAKE_ACCOUNT_KEYPAIR>` is, and how it's obtained. I tried passing the pubkey of a stake account, and got

> Error: Dynamic program error: missing signature for supplied pubkey

I tried passing an existing .json file [created](https://docs.solana.com/cli/delegate-stake#create-a-stake-account) with `solana-keygen new --no-passphrase -o stake-account.json`, and got

> error: Invalid value for '<STAKE_ACCOUNT_KEYPAIR>': No such file or directory (os error 2)

#### Proposed Solution

Please clarify the docs for end-users without Solana development experience.

**Comment by t-nelson** [comment]
In this case `STAKE_ACCOUNT_KEYPAIR` isn't a keypair at all, but rather the output of `solana create-address-with-seed --from PUBKEY SEED_STRING "STAKE"`, where `--from PUBKEY` is the pubkey of the `--from KEYPAIR` keypair on `solana create-stake -account ...`

Probably the best solution here would be to split the with seed variant out to its own CLI subcommand, while preserving current behavior with hidden args
