### ISSUE TITLE
Bug installing v1.7.14 on Windows

### ISSUE THREAD

**Issue by r4ty34r** [solana-labs/solana#20440]
#### Problem

Problem with following the instructions for the Solana Tool Suite. 

The first command: "curl https://release.solana.com/v1.7.14/solana-install-init-x86_64-pc-windows-msvc.exe --output C:\solana-install-tmp\solana-install-init.exe --create-dirs"     works as intended 

"C:\solana-install-tmp\solana-install-init.exe v1.7.14" 
results in Command Prompt returning  "The system cannot execute the specified program." 

In order to circumvent this issue, I had to delete and install an older version (1.6.27)

**Comment by epsilonb** [comment]
I am having the same problem as well. The problem isn't the "C:\solana-install-tmp\solana-install-init.exe v1.7.14". 
The issue lays with "curl https://release.solana.com/v1.7.14/solana-install-init-x86_64-pc-windows-msvc.exe --output C:\solana-install-tmp\solana-install-init.exe --create-dirs". 
It shows that it's working but the only thing it's downloading is a solana-install-init.exe
