### ISSUE TITLE
How to get the keypair from mnemonic words which uses Ed25519 Bip32

### ISSUE THREAD

**Issue by ricardoalcantara** [solana-labs/solana#20457]
#### Problem
I have a mnemonic words from Phantom Wallet and I want get the Keypair in Rust. How could I do that?

In C# there is the lib https://github.com/bmresearch/Solnet

Which I can get the Keypair with:

```C#
Wallet wallet = new Wallet("words words words words ", WordList.English, "", SeedMode.Ed25519Bip32);
```
Is it possible to get the KeyPair this way?

Sorry for asking it here... I tried discord but nobody answered my question.

**Comment by t-nelson** [comment]
You can generate the same wallet as Phantom via CLI with `solana-keygen recover 'prompt:?key=0/0' --output phantom-wallet.json`.  If you really need to do it in code with Rust, check how that CLI command works in the `keygen/` dir here in the monorepo.

If you need any further support, please use https://solana.com/discord.  We don't provide this type of support over Github
