### ISSUE TITLE
recent master branch failed to resume from the testnet hard-fork

### ISSUE THREAD

**Issue by ryoqun** [solana-labs/solana#20476]
#### Problem

my topic branch for #19912 failed to resume after testnet hard fork (commit: bd0602f1, merge base commit: 03913f6661082dc77584da3ee83d660ddcc5068b)

I'm not seeing immediately wrong logs like bank hash mismatch, which happened several times...

what bothers me is that I'm seeing repeated logs of this (same bank slot is frozen multiple times...). maybe related to the duplicate slot dump logic?: @carllin 

```
[2021-10-06T11:27:59.015519919Z INFO  solana_runtime::bank] bank frozen: 96965691 hash: HJzucNPeqk8cDc2JMZLwURaZWTgdoFaRsZCsNY6MnJom accounts_delta: CXmpaDpbWhcX7gsXTvjeuvNP6v4bykwhJ1zekYCbCV7o signature_count: 1672 last_blockhash: HzdpqKJ1Gav63MbEAm9zDYveqMHADwWkoMLDojdRVFnE capitalization: 1402534022350763907
...
[2021-10-06T11:28:01.876288548Z INFO  solana_runtime::bank] bank frozen: 96965691 hash: HJzucNPeqk8cDc2JMZLwURaZWTgdoFaRsZCsNY6MnJom accounts_delta: CXmpaDpbWhcX7gsXTvjeuvNP6v4bykwhJ1zekYCbCV7o signature_count: 1672 last_blockhash: HzdpqKJ1Gav63MbEAm9zDYveqMHADwWkoMLDojdRVFnE capitalization: 1402534022350763907
```
[failed-master-hard-fork-resume.log](https://github.com/solana-labs/solana/files/7295352/failed-master-hard-fork-resume.log)

#### Proposed Solution

debug and fix

**Comment by carllin** [comment]
Ah yeah looks like your validator found a bank hash that didn't agree with the cluster's version of that bank?

```
[2021-10-06T11:28:03.233718036Z INFO  solana_core::cluster_slot_state_verifier] check_slot_agrees_with_cluster()
            slot: 96965691,
            root: 96965687,
            slot_state_update: BankFrozen(BankFrozenState { frozen_hash: HJzucNPeqk8cDc2JMZLwURaZWTgdoFaRsZCsNY6MnJom, cluster_confirmed_hash: Some(DuplicateConfirmed(2jF66JhQEkXztUmbfm7ZwX9ULwSsqu5yLcJRb8uLMtBx)), is_slot_duplicate: false })
```

This means that your validator froze `HJzucNPeqk8cDc2JMZLwURaZWTgdoFaRsZCsNY6MnJom`, but we saw >52% of the cluster with hash `2jF66JhQEkXztUmbfm7ZwX9ULwSsqu5yLcJRb8uLMtBx`

**Comment by carllin** [comment]
hmmm so the hash I see before the restart from `tv` is 

```
bank frozen: 96965691 hash: EinGmxuS26oZgM6JyAi495HDVdAVvJLEP7DVxZQuumrT accounts_delta: AXnLUDaC9rqiW1PfDdiWtZTutXrAdi4UqasSJzTbLGHw signature_count: 5543 last_blockhash: DAuSegA3cqrEMYvDehX4KxrWAG8AzAG3toK9jMV5KRGd capitalization: 1402534022434755232
```

which doesn't match `HJzucNPeqk8cDc2JMZLwURaZWTgdoFaRsZCsNY6MnJom` either

**Comment by steviez** [comment]
I saw my validator fail in also the exact same way running `master` branch against testnet a few weeks after you made this issue; my validator got stuck in a loop similar to what carllin highlighted in your log:
 
> ```
> [2021-10-06T11:28:03.262925037Z WARN  solana_core::replay_stage] purging slot 96965691
> [2021-10-06T11:28:03.270765896Z INFO  solana_runtime::accounts_db] remove_dead_slots_metadata: slots [96965691]
> [2021-10-06T11:28:03.273537133Z WARN  solana_core::replay_stage] purging descendant: 96965691 with slot_id 9, of slot 96965691
> [2021-10-06T11:28:03.274706843Z INFO  solana_ledger::blockstore] Pruning expired primary index 0 up to slot 0 (max requested: 96965692)
> [2021-10-06T11:28:03.275711966Z WARN  solana_core::replay_stage] Notifying repair service to repair duplicate slot: 96965691
> ```

More details are in https://github.com/solana-labs/solana/issues/21225, but essentially, I had a snapshot and the necessary shreds to be able to run `master` vs. `v1.8.2` and gather enough information for jackmay to identify a bug that was present in `master` (PR linked to the issue).
