### ISSUE TITLE
Failing to load vote program

### ISSUE THREAD

**Issue by carllin** [solana-labs/solana#2050]
#### Problem
Seeing the following error when trying to load the vote program from the native_loader after running net.sh on gce: /home/solana/.cargo/bin/libsolana_vote_program.so: cannot open shared object file: No such file or directory

**Comment by mvines** [comment]
@carllin - could you please share the exact net.sh command you’re using?

**Comment by carllin** [comment]
Sure thing, ./net.sh restart -o noValidatorSanity -o noLedgerVerify

**Comment by mvines** [comment]
Ah, https://github.com/solana-labs/solana/blob/master/net/net.sh#L145 probably needs to run in the MAYBE_DOCKER block.   I assume you were running `./net.sh` natively on macOS
