### ISSUE TITLE
Incorporate cost of account data size to cost calculation

### ISSUE THREAD

**Issue by taozhu-chicago** [solana-labs/solana#20511]
#### Problem

cost model current does not have account data size info to incorporate into transaction cost calculation.

#### Proposed Solution

We should be incorporating the cost of the account data sizes. We could feed that information back to the cost tracker like we currently do for execution costs. If an account size is not in the cache we could keep a list of account size averages per program.

**Comment by jeffwashington** [comment]
this could help provide access:
#16303

**Comment by ericd78** [comment]
I'm not sure what i'm doing yet.

**Comment by taozhu-chicago** [comment]
This one is pretty old, a lot has changed. It looks to me there are at least two actions related to it: 
1. Leaders to include account data size in block packing decision making; (and some clean up in that area)
2. Transaction to be charged with additional fee for loading account data (perhaps charge fee for extra Bytes loaded above some limits)
@jeffwashington is this what you are thinking?
