### ISSUE TITLE
Program deploy not working

### ISSUE THREAD

**Issue by BadConfig** [solana-labs/solana#20539]
#### Problem
We are trying to deploy our program on Solana, firstly it goes with a slow transaction send
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/40150854/136541386-73080be7-1711-47bb-a0c1-7dfdc754f565.png">
After, we get 0 confirmation slots 
<img width="1129" alt="image" src="https://user-images.githubusercontent.com/40150854/136541512-a689ccf0-83b8-4950-ba54-fbb5d7a81c27.png">
Then all cycle repeats, program start sending txns again and after long time it fails on confirmation in 0 slots
.so file of program on google drive
https://drive.google.com/file/d/1jS2BHER5fgDeHnp8x9sb7U22dx00UpsP/view?usp=sharing
Github repo of sc written with project-serum/anchor
https://github.com/Graviton-One/solana-sc
Transaction sender authority
8eXB9mtUWtdN9Jj7u7rJM2nJf18qT7mVyqvZvse2KnxW

**Comment by mvines** [comment]
Are you using Solana v1.7.14 to deploy?
