### ISSUE TITLE
Lower cyclomatic complexity for bin/fullnode main()

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#2056]
#### Problem
The cyclomatic complexity for fullnode/src/main.rs has grown to 31 with voting changes.

#### Proposed Solution
Break main() into smaller functions and move non-CLI functions into src/fullnode.rs, where one would expect to find that function's unit tests.
Also remove clippy override from fullnode/src/main.rs:main()

**Comment by garious** [comment]
Does this really need to be pushed out? Is it more than 30 minutes of work?

**Comment by pgarg66** [comment]
I'll include it in the current PR #2009 . Let me fix the current failures.
Also, this issue will only be introduced if I landed #2009.
