### ISSUE TITLE
Invalid link on the main "Getting Started with Solana Development" page

### ISSUE THREAD

**Issue by rasulkireev** [solana-labs/solana#20564]
#### Problem

There is a broken link on the main "Getting Started with Solana Development" blog post. Here is the sentence:

"You can access these SDKs on the Solana Developers Page." where **Solana Developers Page** is a broken link that leads to http://https//www.solana.com/developers... please fix it to be https://www.solana.com/developers. 

I think the issue is that someone who was writing markdown (presumably Chase Barker) mistyped the semicolon and the markdown parser treated it as part of the domain name.

Apologies if this is the wrong repo. I wasn't sure where else to post this issue.

**Comment by steviez** [comment]
Not sure when, but this did get fixed
