### ISSUE TITLE
My solana node run fail,founds errors:  duplicate running instances of the same validator node: 2g6SDWbq6mNpmnbJQEjKmcF8y7b3K7Nmg7Q7uvh7LDmJ

### ISSUE THREAD

**Issue by luoxiandong** [solana-labs/solana#20619]
#### Problem

solana-validator --identity /root/solana/validator-keypair.json --ledger /data/solana_ledger --entrypoint entrypoint.mainnet-beta.solana.com:8001 --entrypoint entrypoint2.mainnet-beta.solana.com:8001 --entrypoint entrypoint3.mainnet-beta.solana.com:8001 --entrypoint entrypoint4.mainnet-beta.solana.com:8001 --entrypoint entrypoint5.mainnet-beta.solana.com:8001 --expected-genesis-hash 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d --rpc-port 8899 --dynamic-port-range 8000-8010 --no-voting --enable-rpc-transaction-history --limit-ledger-size --no-poh-speed-test --cuda --private-rpc --no-untrusted-rpc  --no-port-check --wal-recovery-mode skip_any_corrupted_record --log  ./sol_node.log

**Comment by t-nelson** [comment]
Hi. All support requests should be made to https://solana.com/discord. Thanks!
