### ISSUE TITLE
NFT GALLERY?

### ISSUE THREAD

**Issue by netcinematics** [solana-labs/solana#20629]
#### Problem
Feature Request - JS GALLERY - in solana-web3.js/examples

Hello I'm new here. - : ) Directions please. Maybe I am in wrong place.

I try to build a CUSTOM NFT GALLERY.
 - NFTs already MINTED. 
 - Just want to [VIEW, INTERACT (dynamically) with] tokens on web3.
 - any example of how to do that?

#### Proposed Solution

I want to LEARN RUST, and awesome SOLANA architecture.

I can contribute, as ecommerce/finance/nft experienced (c && js) react dev.

Looking in web3, Solana JavaScript API - for  JS GALLERY VIEW example.

But not found, so far. I see React views art/artwork!

How to view only art/artwork with test data in localhost?

Trying...

###

USE CASE:  TONS of (creative) NFTs already MINT on SolSea(and many others) - need to VIEW as:

- JS:Html: CUSTOM NFT GALLERY
 
    > (cool stuff)(sequencing NFTs...).

- API: getNFTs by Artist name (name). How?

- API: getNFTs (metadata [creative content] UNIQUE SEQUENCE NUMBER) 

    > for advanced GALLERY. Nice to have.

- TOKEN: custom metadata (sequence num, like 1:2:3:4, etc). 

- Maybe example of showNFT(), displayNFT(), viewNFT() is in wallet?

- I do have Metaplex running localhost -maybe I dig somewhere in there?

Deep dive now...

###

UPDATE - SOLUTION: http://localhost:3000/#/artworks   (the NFTs appear!)

Quickly CUSTOMIZED to ADD NEW TAB called GALLERY, and display on default (no error).

Changes in this 1 (awesome) file: web/src/views/artworks/index

Now jumping into how to change the render based on metadata.

Any suggestions or tips?

This is so cool!

~spazefalcon~ : )

**Comment by roederw** [comment]
These questions are better suited for the [Metaplex discord](https://discord.gg/metaplex).

**Comment by mvines** [comment]
Yes please try asking there

**Comment by faridmovsumov** [comment]
There are several projects which can provide you Nft gallery feature. 

- https://solect.xyz/
- https://nftbucket.com/ 
- https://www.nfteyez.global/
