### ISSUE TITLE
Explorer doesn't display metadata for metaplex NFT's

### ISSUE THREAD

**Issue by pcarvalho75** [solana-labs/solana#20640]
#### Problem
I have minted a token on the devnet using metaplex and included the data, but the image logo does not appear. I assume the path to the logo is supposed to be in the JSON as per metadata. Would appreciate any feedback on how to include this logo.

https://explorer.solana.com/address/2ztxGkMcRbH6jYWyfyTR1ZqSCDo5DFAaAXwnYX9qXu65/metadata?cluster=devnet

**Comment by AIRADLABS** [comment]
Similar problem here starting in the last 24 hours. 
All of my nft's were minted on Solsea. 

The metadata is no longer loading on Explorer.
[](https://explorer.solana.com/address/DXps43e9CEr7tciENzcF6nBAfLdjToyJETF3qPdctzTJ)
![Screenshot (40)](https://user-images.githubusercontent.com/91598981/139776869-84a62ec9-ae56-42c8-a169-1fb66cea3eb9.png)

They are still displaying at:
1. Phantom wallet
2. In my app
3. Solsea
![App](https://user-images.githubusercontent.com/91598981/139776784-86d894b7-6069-48a4-b8d6-bc2f76f183b1.png)
![Screenshot (41)](https://user-images.githubusercontent.com/91598981/139777188-d5902ff6-3801-4448-944b-8a7612b9ca43.png)

**Comment by roederw** [comment]
The issue seems to be caused by [this PR](https://github.com/solana-labs/solana/pull/21120). @oJshua are we sure we want to limit NFTs to require Editions?

**Comment by oJshua** [comment]
I definitely don't want to exclude a whole class of NFTs. @bhgames

**Comment by roederw** [comment]
There is already some ux elements in `NFTHeader` to show that there isn't a MasterEdition present.

**Comment by roederw** [comment]
I have a fix. I'll send out a PR.

**Comment by roederw** [comment]
https://github.com/solana-labs/solana/pull/21132

**Comment by mdergueche** [comment]
@pcarvalho75  do you mind sharing what you have done as change in .htaccess to solve your display issue?
