### ISSUE TITLE
Remove dependency on solana-clap-utils in solana-client

### ISSUE THREAD

**Issue by karim-agha** [solana-labs/solana#20702]
#### Problem

I'm trying to build for the `x86_64-unknown-linux-musl` target so I can call my program from AWS Lambda.  It is failing to cross compile because of hdiapi cross-compile stuff. I do not need hardware wallet as my scenario is running in the cloud.

`hidapi` is referenced by `solana-remote-wallet` which is referenced by `solana-clap-utils` which is referenced by `solana-account-decoder` which is referenced by `solana-client`.

The dependency on `solana-clap-utils` is there to reuse few helper functions that parse strings that are shared between the CLI interface and the RPC interface.

#### Proposed Solution

I propose to either extract those helper functions into a crate that doesn't eventually depend on `hdiapi`, or some other feature-based optional way to disable the one function and 3 unit tests that depend on those helpers in `blockhash_query.rs`.

**Comment by karim-agha** [comment]
Repro steps:

Create a crate that references `solana-client` and try to build it for musl:
`$ cargo build --bin create-user --release --target x86_64-unknown-linux-musl`

Result: 
```
Caused by:
  process didn't exit successfully: /Users/jrieck/projects/solana/flagships/api/target/release/build/hidapi-4e43306149eb176f/build-script-build (exit status: 101)
  --- stdout
  cargo:rerun-if-env-changed=LIBUDEV_NO_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_x86_64-unknown-linux-musl
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_x86_64_unknown_linux_musl
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-musl
  cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_musl
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-musl
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_musl
  cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_SYSROOT_DIR
  cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

  --- stderr
  thread 'main' panicked at 'Unable to find libudev: CrossCompilation', /Users/jrieck/.cargo/registry/src/github.com-1ecc6299db9ec823/hidapi-1.2.6/build.rs:53:54
  note: run with RUST_BACKTRACE=1 environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```

**Comment by t-nelson** [comment]
Feature would be the way to go. Along with whatever refactoring is necessary to minimize the featurized footprint

**Comment by ronanyeah** [comment]
My [render.com](https://render.com/) build is also failing due to this.
