### ISSUE TITLE
BPF implementation does not support BPF to BPF function calls

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#2086]
#### Problem

In order to support multi-file BPF programs and linking in/with libraries, our BPF implementation must support BPF to BPF calls.

#### Proposed Solution

* [x]  BPF to BPF function calls
  * [x] Add BPF symbol resolutions (intra ELF)
  * [x] Handle BPF subroutine return
  * [x] Support BPF subroutine stack frames

Depends on
* [x] Build system support for multi-file projects
       https://github.com/solana-labs/solana/issues/2176
* [x] Respect ELF entry point
       https://github.com/solana-labs/solana/issues/2177

**Comment by mvines** [comment]
I support the right solution that takes longer, (1).  It would be nice to get this into v0.11 but not at the expense of short-term work that we would immediately need to undo and redo.

**Comment by jackcmay** [comment]
Turns out this is more complicated than it originally presented.  The right solution is a combination of both.

**Comment by jackcmay** [comment]
One pain point of the proposed work is that BPF does not interact with the stack in a typical way.  Typically a stack pointer is managed that moves as things a pushed and popped from the stack.  For example, when functions are called, zero or more of their parameters maybe be pushed and the return address is pushed.  BPF programs don't manage a head pointer, instead, a function's stack is a fixed size buffer essentially used as a scratch buffer.  BPF does not pass parameters via the stack (only registers) This comes historically from the fact that all BPF programs are a single function.  This means that each BPF function has its own "stack" frame.  Linux recently added support for BPF to BPF calls and they do this by providing a 512 byte stack frame for each function called with a maximum depth of 8 function calls.
