### ISSUE TITLE
Expand Broadcast to 32:64 data to coding shreds

### ISSUE THREAD

**Issue by carllin** [solana-labs/solana#20965]
#### Problem
New proposal requires expanded coding shreds

cc @aeyakovenko

**Comment by steviez** [comment]
@behzadnouri @carllin - I haven't fully digested the linked papers yet (and honestly they might be beyond my background), but someone from Polkadot mentioned seeing vastly improved performance by changing up their erasure coding scheme here: https://github.com/rust-rse/reed-solomon-erasure/issues/88#issuecomment-986657773

**Comment by behzadnouri** [comment]
@steviez thanks for pointing to that. definitely worth some experiments.

**Comment by behzadnouri** [comment]
This is shelved for now in favor of merkle shreds.
Merkle shreds are being rolled out to testnet.
