### ISSUE TITLE
Stake cache updates hold write lock for too long

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#20998]
Stake cache updates are taking 1/4 of the time we use to store account updates and they also spike up to over half the time occasionally (presumably due to vote filled blocks). Stake cache updates are currently implemented in a way that holds a write lock for the whole time. I think it's worth refactoring so that we don't hold the lock so long and do the vote account deserialization before locking.

<img width="1573" alt="Screen Shot 2021-10-26 at 8 07 13 PM" src="https://user-images.githubusercontent.com/1076145/138944872-6ab16cad-3c36-4614-93b7-84529bfd3329.png">

_Originally posted by @jstarry in https://github.com/solana-labs/solana/issues/20856#issuecomment-952231762_

**Comment by mooori** [comment]
Fixed by #21733 ?

**Comment by jstarry** [comment]
> Fixed by #21733 ?

Yes, thanks!
