### ISSUE TITLE
bug: getSignaturesForAddress RPC returns wrong result when placing no gap signature in before and until option

### ISSUE THREAD

**Issue by BillZong** [solana-labs/solana#21039]
#### Problem

We found a bug in getSignaturesForAddress RPC method

Mostly, the function works great, but when query some programs with millions of transactions like Token Program, its transaction gap seems to be not working right.

When querying option 'before' and 'until' set to the neighboring transaction signatures, it returns several transactions not between them.

##### Example

**Step 1:**

```bash
curl -X POST 'https://api.mainnet-beta.solana.com' \
-H 'Content-Type: application/json' \
-d '{
    "jsonrpc": "2.0",
    "id": 2,
    "method": "getSignaturesForAddress",
    "params": [
        "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
        {
            "before": "4SWKWuwhHq2LRtnqjJWSsChxmAxsd2GXQ6iSTchk39YU3pzcQA37oKGLGkYncqCsCCMJv3h5di3BQojriwrq1EVx",
            "limit": 10
        }
    ]
}
'

Result:
[
    {
            "signature": "4NCmm1AwVM4bxPvsGqogdogjPCxxSUR6PJxJqVDPCw45M4yK9YHPosAutvWMvWBgN1YKgCY4WEscaFnkuxYiQRe3"
    },
    // ...
]
```

**Step 2:**

```bash
curl -X POST 'https://api.mainnet-beta.solana.com' \
-H 'Content-Type: application/json' \
-d '{
    "jsonrpc": "2.0",
    "id": 2,
    "method": "getSignaturesForAddress",
    "params": [
        "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",
        {
            "before": "4SWKWuwhHq2LRtnqjJWSsChxmAxsd2GXQ6iSTchk39YU3pzcQA37oKGLGkYncqCsCCMJv3h5di3BQojriwrq1EVx",
            "until": "4NCmm1AwVM4bxPvsGqogdogjPCxxSUR6PJxJqVDPCw45M4yK9YHPosAutvWMvWBgN1YKgCY4WEscaFnkuxYiQRe3",
            "limit": 10
        }
    ]
}
'

Result:
[
    {
            // which is newer signature than "4SWKWuwhHq2LRtnqjJWSsChxmAxsd2GXQ6iSTchk39YU3pzcQA37oKGLGkYncqCsCCMJv3h5di3BQojriwrq1EVx"
            "signature": "52gsUs9XU2Q3ri5hnrhoe35Dch8creuJq5uiGPr4S6vi6f72RuG49jhuGELB2gLVDq2r6e3v5X8e1qEe8p9DY8dC"
    },
    {
            // which is older signature than "4NCmm1AwVM4bxPvsGqogdogjPCxxSUR6PJxJqVDPCw45M4yK9YHPosAutvWMvWBgN1YKgCY4WEscaFnkuxYiQRe3"
            "signature": "37zNdQry8WRgbSCMyfAdYHWWnwi9e8ToGf4eCicWLpztPnkJUiHkaZo9YQdEA7zW4dpdrj6AGURiSkDfgxNY6Ajn"
    },
    // ...
]
```

#### Proposed Solution

Fix the bug, plz. It's confusing and hard to handled.

**Comment by CriesofCarrots** [comment]
@BillZong , I haven't yet been able to reproduce this.
Your example queries look fine now:
```
$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id":1,"method":"getSignaturesForAddress","params":["TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",{"before":"4SWKWuwhHq2LRtnqjJWSsChxmAxsd2GXQ6iSTchk39YU3pzcQA37oKGLGkYncqCsCCMJv3h5di3BQojriwrq1EVx","limit":5}]}' api.mainnet-beta.solana.com | jq
{
  "jsonrpc": "2.0",
  "result": [
    {
      "blockTime": 1635390257,
      "confirmationStatus": "finalized",
      "err": null,
      "memo": null,
      "signature": "52gsUs9XU2Q3ri5hnrhoe35Dch8creuJq5uiGPr4S6vi6f72RuG49jhuGELB2gLVDq2r6e3v5X8e1qEe8p9DY8dC",
      "slot": 103890663
    },
    {
      "blockTime": 1635390257,
      "confirmationStatus": "finalized",
      "err": null,
      "memo": null,
      "signature": "37zNdQry8WRgbSCMyfAdYHWWnwi9e8ToGf4eCicWLpztPnkJUiHkaZo9YQdEA7zW4dpdrj6AGURiSkDfgxNY6Ajn",
      "slot": 103890663
    },
    {
      "blockTime": 1635390257,
      "confirmationStatus": "finalized",
      "err": null,
      "memo": null,
      "signature": "445UQorZ2j3NTqKVE41WkB97e3iw9bSBRzTxCpDbBgtP3e3XZEMcGj4ZvG33rYvdTYHPseW3qMRNjeeCCnm5y9fB",
      "slot": 103890663
    },
    {
      "blockTime": 1635390257,
      "confirmationStatus": "finalized",
      "err": null,
      "memo": "[44] RZwDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
      "signature": "uD3AyrvHHHXVxNECBxHbQJGUu4q4vSoZMq2RjK4hDfiHwEX2aRp7uuZd7breQ53panScT9F8kGxVTRZ6fDD6myY",
      "slot": 103890663
    },
    {
      "blockTime": 1635390257,
      "confirmationStatus": "finalized",
      "err": null,
      "memo": null,
      "signature": "4NCmm1AwVM4bxPvsGqogdogjPCxxSUR6PJxJqVDPCw45M4yK9YHPosAutvWMvWBgN1YKgCY4WEscaFnkuxYiQRe3",
      "slot": 103890663
    }
  ],
  "id": 1
}
```
The fact that it's working now could be because these signatures have since been pruned from the rpc node, and are now being queried from BigTable long-term storage, where the schema is slightly different.
So if there's an issue, it likely arises when data is recent and queried/returned from the node's local ledger.

However, I have tried various recent signatures I pulled from `Tokenkeg`, and as I said, I have yet to repro.
If you see this again, could you please tag me here or on Discord (@Tyera) so I can check it out in real time?

**Comment by CriesofCarrots** [comment]
Oh also, can you confirm that you were not passing a `commitment` parameter on any of these queries?

**Comment by BillZong** [comment]
> @BillZong , I haven't yet been able to reproduce this. Your example queries look fine now:
> 
> ```
> $ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id":1,"method":"getSignaturesForAddress","params":["TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",{"before":"4SWKWuwhHq2LRtnqjJWSsChxmAxsd2GXQ6iSTchk39YU3pzcQA37oKGLGkYncqCsCCMJv3h5di3BQojriwrq1EVx","limit":5}]}' api.mainnet-beta.solana.com | jq
> {
>   "jsonrpc": "2.0",
>   "result": [
>     {
>       "blockTime": 1635390257,
>       "confirmationStatus": "finalized",
>       "err": null,
>       "memo": null,
>       "signature": "52gsUs9XU2Q3ri5hnrhoe35Dch8creuJq5uiGPr4S6vi6f72RuG49jhuGELB2gLVDq2r6e3v5X8e1qEe8p9DY8dC",
>       "slot": 103890663
>     },
>     {
>       "blockTime": 1635390257,
>       "confirmationStatus": "finalized",
>       "err": null,
>       "memo": null,
>       "signature": "37zNdQry8WRgbSCMyfAdYHWWnwi9e8ToGf4eCicWLpztPnkJUiHkaZo9YQdEA7zW4dpdrj6AGURiSkDfgxNY6Ajn",
>       "slot": 103890663
>     },
>     {
>       "blockTime": 1635390257,
>       "confirmationStatus": "finalized",
>       "err": null,
>       "memo": null,
>       "signature": "445UQorZ2j3NTqKVE41WkB97e3iw9bSBRzTxCpDbBgtP3e3XZEMcGj4ZvG33rYvdTYHPseW3qMRNjeeCCnm5y9fB",
>       "slot": 103890663
>     },
>     {
>       "blockTime": 1635390257,
>       "confirmationStatus": "finalized",
>       "err": null,
>       "memo": "[44] RZwDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
>       "signature": "uD3AyrvHHHXVxNECBxHbQJGUu4q4vSoZMq2RjK4hDfiHwEX2aRp7uuZd7breQ53panScT9F8kGxVTRZ6fDD6myY",
>       "slot": 103890663
>     },
>     {
>       "blockTime": 1635390257,
>       "confirmationStatus": "finalized",
>       "err": null,
>       "memo": null,
>       "signature": "4NCmm1AwVM4bxPvsGqogdogjPCxxSUR6PJxJqVDPCw45M4yK9YHPosAutvWMvWBgN1YKgCY4WEscaFnkuxYiQRe3",
>       "slot": 103890663
>     }
>   ],
>   "id": 1
> }
> ```
> 
> The fact that it's working now could be because these signatures have since been pruned from the rpc node, and are now being queried from BigTable long-term storage, where the schema is slightly different. So if there's an issue, it likely arises when data is recent and queried/returned from the node's local ledger.
> 
> However, I have tried various recent signatures I pulled from `Tokenkeg`, and as I said, I have yet to repro. If you see this again, could you please tag me here or on Discord ((at)Tyera) so I can check it out in real time?

Thanks for paying attention. I can't reproduce it, too.

When I tried this on Oct 28th, there are no transactions between `4SWKWuwhHq2LRtnqjJWSsChxmAxsd2GXQ6iSTchk39YU3pzcQA37oKGLGkYncqCsCCMJv3h5di3BQojriwrq1EVx` and `4NCmm1AwVM4bxPvsGqogdogjPCxxSUR6PJxJqVDPCw45M4yK9YHPosAutvWMvWBgN1YKgCY4WEscaFnkuxYiQRe3` when querying: 
> curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0","id":1,"method":"getSignaturesForAddress","params":["TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA",{"before":"4SWKWuwhHq2LRtnqjJWSsChxmAxsd2GXQ6iSTchk39YU3pzcQA37oKGLGkYncqCsCCMJv3h5di3BQojriwrq1EVx","limit":10}]}' api.mainnet-beta.solana.com | jq

But now, it seems to be OK.

The commitment is needless, since the time elapsed when I wrote the demo, and all transactions are finalized by that time.

I would rather close this issue now, and keep an eye on it.

**Comment by CriesofCarrots** [comment]
> I would rather close this issue now, and keep an eye on it.

Works for me! Do give me a nudge if you see it again.
