### ISSUE TITLE
`cargo build-bpf` fails

### ISSUE THREAD

**Issue by plafer** [solana-labs/solana#21053]
#### Problem
Running `cargo build-bpf` gives the following output:
> cargo-build-bpf
BPF SDK: /home/plafer/.local/share/solana/install/releases/stable-5f867353826b72e39d4b29d023c588889a9d4e0c/solana-release/bin/sdk/bpf
Running: rustup toolchain list -v
Running: rustup toolchain link bpf /home/plafer/.local/share/solana/install/releases/stable-5f867353826b72e39d4b29d023c588889a9d4e0c/solana-release/bin/sdk/bpf/dependencies/bpf-tools/rust
error: not a directory: '/home/plafer/.local/share/solana/install/releases/stable-5f867353826b72e39d4b29d023c588889a9d4e0c/solana-release/bin/sdk/bpf/dependencies/bpf-tools/rust/lib'

It also failed on `1.8.2`. I believe it worked the very first time I ran it, but I `CTRL+C`'d it and now I can't figure out how to make it work anymore. I tried reinstalling solana by deleting the folder `~/.local/share/solana/` and rerunning `sh -c "$(curl -sSfL https://release.solana.com/v1.8.2/install)"`, but that didn't work either.

**Comment by plafer** [comment]
that worked, thanks! Although the only directory there was `~/.cache/solana/v1.12/`.

That should probably be fixed one way or another though.

**Comment by dmakarov** [comment]
> that worked, thanks! Although the only directory there was `~/.cache/solana/v1.12/`.
> 
> That should probably be fixed one way or another though.

I agree. I’ll add some logic to work around such failures.

**Comment by rhamoudi** [comment]
> try removing `~/.cache/solana/v1.18`
> 
> ```
> rm -rf ~/.cache/solana/v1.18
> ```
> 
> if that doesn't help then,
> 
> ```
> rm -rf ~/.cache/solana/v1.15
> ```

Thanks, this worked. Nearly pulled non-existing hairs off my bald head.

**Comment by elliott-w** [comment]
`cargo build-bpf` never works for me because I exceed the 30 second download timeout every single time.

```
 % solana --version
solana-cli 1.8.2 (src:42a2c292; feat:52865992)
 % cargo build-bpf                 
BPF SDK: /Users/elliott/.local/share/solana/install/releases/1.8.2/solana-release/bin/sdk/bpf
thread 'main' panicked at 'Failed to install bpf-tools: "error sending request for url (https://github.com/solana-labs/bpf-tools/releases/download/v1.12/solana-bpf-tools-osx.tar.bz2): operation timed out"', sdk/cargo-build-bpf/src/main.rs:440:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Manually downloading the the solana-bpf-tools takes ~50 seconds for me, but when I extract the tools
```
% tar jxf solana-bpf-tools-osx.tar.bz2
``` 
and run 
```
% cargo build-bpf
```
again, I get a Mac OS notification for every single binary in the package. For example: "cargo" cannot be opened because the developer cannot be verified. Happens for "cargo", "rustc", "librustc_driver-def6b23924f06bf0.dylib", "libstd-00f96240d49798ef.dylib", etc etc.

So I think the timeout needs an increase, but besides that, is there a way I can manually extract and verify the `solana-bpf-tools`?

**Comment by dmakarov** [comment]
I’ll make the timeout longer. After you download the bpf-tools tarball, you could removing the quarantine attribute of the downloaded file before unpacking thr tarball:

```
xattr -c solana-bpf-tools-osx.tar.bz2
```

if that doesn’t help you may need to add an exception in System Settings >> Privacy (or something) to allow unverified programs to be executed. I’m away from a computer and can’t get the details of this setting.

**Comment by jeraldtomada** [comment]
> try removing `~/.cache/solana/v1.18`
> 
> ```
> rm -rf ~/.cache/solana/v1.18
> ```
> 
> if that doesn't help then,
> 
> ```
> rm -rf ~/.cache/solana/v1.15
> ```

got stuck on this as well, but this worked! thank you.

**Comment by tetris-dev-web** [comment]
You can manually install cargo bpf-tool

1. download from https://github.com/solana-labs/bpf-tools/releases (ex v1.22)
2. Extract it and copy it to ~/.local/share/solana/install/releases/[solana-version]/solana-release/bin/sdk/bpf/dependencies/bpf-tools/
 Inside this folder, you can have as following
/llvm
/rust
version.md
3. make a blank file bpf-tools-v1.22.md under ~/.local/share/solana/install/releases/[solana-version]/solana-release/bin/sdk/bpf/dependencies
4. Run ~/.local/share/solana/install/releases/[solana-version]/solana-release/bin/sdk/bpf/env.sh
 Please not forget to give executive permission to env.sh file

Then Cargo bpf-tool can be installed manually and cargo build-bpf command works well...

Enjoy....

**Comment by sparkidea25** [comment]
How can i extract it to here on my macos? Extract it and copy it to ~/.local/share/solana/install/releases/[solana-version]/solana-release/bin/sdk/bpf/dependencies/bpf-tools/

**Comment by tetris-dev-web** [comment]
No. .. you need to go to that folder and run the .sh file as following

cd /home/[User Name]/.local/share/solana/install/releases/[solana-version]/solana-release/bin/sdk/bpf/
chmod 755 env.sh
./env.sh

**Comment by r3ndd** [comment]
This appears to still be an issue. 

```
> helloworld@0.0.1 build:program-rust
> cargo build-bpf --manifest-path=./src/program-rust/Cargo.toml --bpf-out-dir=dist/program

BPF SDK: /home/user/.local/share/solana/install/releases/stable-7d2acbc9a3ddf7fb5131c72c8f12f367d4470b42/solana-release/bin/sdk/bpf
cargo-build-bpf child: rustup toolchain list -v
cargo-build-bpf child: cargo +bpf build --target bpfel-unknown-unknown --release
error: process didn't exit successfully: `rustc -vV` (exit status: 127)
--- stderr
/home/user/.rustup/toolchains/bpf/bin/rustc: error while loading shared libraries: librustc_driver-a8aaff3fbd0bfff2.so: cannot open shared object file: No such file or directory
```

Clearing the cache as mentioned above solved the issue, although it would be nice if it was solvable using standard debugging procedures (i.e. performing a full reinstall of the Solana tools). As far as I can tell there is no such uninstaller, and in my attempts to remove the Solana CLI files I unknowingly left the .cache directory. An uninstaller that can be called from the Solana CLI might be a good idea.

**Comment by AndersenAndreoni** [comment]
For windows users having the same issue activate the developer mode;
follow the instruction on this link:
https://github.com/Schniz/fnm/issues/338
