### ISSUE TITLE
restore account from pharse word

### ISSUE THREAD

**Issue by fallowu** [solana-labs/solana#21060]
#### Problem

I use the same pharse word to restore account ,and get the address and secretKey from solana-web3.js is different with the result from phantom wallet. is some wrong with this code ?

```
      const bs58 = require('bs58')
      let pharseWord =
        'monitor word flag cheap shield split success table course illness company crumble used mail shiver behave drift impact earth settle outer glad ankle only'
      let fromSeedArray = new TextEncoder().encode(pharseWord)
      let account = Web3.Keypair.fromSeed(fromSeedArray.slice(0, 32))
      let address = account.publicKey.toBase58()
      let secretKey = account.secretKey
      console.log(address)
      // HvvHwAyreoLpZKDi2FGPdhgr9PvpwXSy78BrcHYaoqVx
      console.log(secretKey)
      // [109, 111, 110, 105, 116, 111, 114, 32, 119, 111, 114, 100, 32, 102, 108, 97, 103, 32, 99, 104, 101, 97, 112, 32, 115, 104, 105, 101, 108, 100, 32, 115, 251, 139, 7, 247, 125, 140, 35, 96, 231, 98, 187, 175, 113, 203, 111, 163, 155, 254, 37, 94, 139, 4, 53, 241, 185, 155, 190, 177, 238, 224, 146, 111]
      console.log(bs58.encode(account.secretKey))
      // 3BuJbD6ZzgUimq46wsTRQ68EcSBQ69vnBbSSgwB9G7JReTbBpXUMWN8oQXyeGdnxJD1BgBPvUMUVp6xXMCy9H2ei
```

solana-web3.js:
```
address:
HvvHwAyreoLpZKDi2FGPdhgr9PvpwXSy78BrcHYaoqVx
secretKey:
3BuJbD6ZzgUimq46wsTRQ68EcSBQ69vnBbSSgwB9G7JReTbBpXUMWN8oQXyeGdnxJD1BgBPvUMUVp6xXMCy9H2ei
```
phantom wallet :
```
address:
J4NQd17FbmgGzPBgBZqjehwkYH1acwV5ZVpXvXe3h11c
secretKey:
5dMuJ41cqommWqEd6dvc1Z74YipSY1hdtntA27MXHQKdFQp5MQB2kBdnaAYQnVF6FUzgAzkwD5EKvbz2AdsRKPa2
```

#### Proposed Solution
address and secretKey is the same.

**Comment by detinho** [comment]
First of all, never post your secrets in public.
I came across the same problem trying to recover a wallet from phantom, and it happens that phantom uses the 0/0 derivation path.
Don't know the web3 api yet but from the command line it would be something like this:
`solana-keygen recover 'prompt://?key=0/0' -o <file.json>`

**Comment by cbosborn** [comment]
thanks for posting this @detinho. what does the syntax on `'prompt://?key=0/0'` mean?

**Comment by steveluscher** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Solana itself.

Questions like yours deserve a purpose-built Q&A forum. Unless you have evidence that this is a bug with Solana itself, please post your question to the Solana Stack Exchange using this link: https://solana.stackexchange.com/questions/ask
