### ISSUE TITLE
Web3: shortvec decodeLength output does not match encodeLength input

### ISSUE THREAD

**Issue by 0xNilsOlav** [solana-labs/solana#21089]
#### Problem
Output of `decodeLength` does not match the length encoded with `encodeLength`. Reproduction:
1. Create an array `x` with some data
2. Call `encodeLength(x, 1)`
3. Call `decodeLength(x)`

Should expect the output of step three to be the length encoded in step 2 (`1`), but instead get the original data in the array, as shown in the screenshot below.
![image](https://user-images.githubusercontent.com/92005151/139592235-86906723-b1d2-4911-b4a1-2a7d42b75e5a.png)

#### Proposed Solution
It appears that `encodeLength` is adding the length data to the end of the input array while `decodeLength` attempts to read it from the beginning. Resolve by choosing either the beginning or end and making the two functions consistent.

Note: I feel like I must be missing something because, if this issue is valid, it would break the message serialization/deserialization which seems pretty important and something lots of people would notice.

**Comment by steveluscher** [comment]
We have a forum for questions like this now! Post it on Stack Exchange and paste the URL here. I'll answer it there so that it can live on past this GitHub issue being closed.
