### ISSUE TITLE
Explorer: Name specified in external JSON should have precedence.

### ISSUE THREAD

**Issue by cihantas** [solana-labs/solana#21109]
#### Problem
Given an NFT with the following metadata

```json
{
  "name": "foo",
  "uri": "https://example.com/meta.json"
}
```

and external JSON metadata representing the asset at `https://example.com/meta.json` with the content

```json
{
  "name": "bar",
}
```

Solana Explorer currently displays `foo` not `bar`.

#### Proposed Solution

Solana Explorer should use the name specified in the **external** JSON file if available and otherwise fallback to the name used in the Metaplex on-chain program.

The Metaplex Token Metadata Standard specifcies the field `uri` as "URI to the external JSON representing the asset". It therefore makes sense to use this data as the source of truth to represent the asset. From a DX perspective it's also easier to change asset metadata in the JSON in case it's stored centralised.

AFAIK common browser wallets such as Phantom already prefer the name specified inside the JSON. 

I'm happy to provide a PR for this.

**Comment by RTISCOOL** [comment]
I have a PR open which changes the fetching of the external JSON metadata to the header component, should be able to add this in 1 line one thats is merged

**Comment by cihantas** [comment]
Awesome, looking forward. Thanks!

**Comment by roederw** [comment]
Why would the names differ in the first place? At least the on-chain metadata is theoretically "always" available.

**Comment by cihantas** [comment]
> Why would the names differ in the first place?

In our case changing the JSON that is currently hosted off-chain is significantly easier and more efficient to work with. Updating very large amounts of on-chain data can be costly. Many projects I've seen began with hosting the JSON metadata off-chain and later transitioned to on-chain hosting when assets were considered finalised. There are also cases when assets are never finalised and can be considered dynamic.

The existence of the attribute `name` in two places, means that - by design - the values can be different unless this is enforced some other way. But please correct me if conditions like equality are stated somewhere.

> A `uri` isn't always hosted on a chain.

That's correct, and that's a good thing from a cost and DX perspective. I'm happy to expand, if not already answered.

**Comment by ngundotra** [comment]
Stale

**Comment by ngundotra** [comment]
Stale
