### ISSUE TITLE
blobs are weird, complicated...

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#2112]
#### Problem
leaders don't sign their transmissions, providence can't be established, byzantine behavior can't be detected or punished

Blobs carry id (would-be signer), index, slot, and flags hidden in an opaque byte array instead of being out in the Entry or another type

the complication extends to blob_fetch which has its own special definitions for Blobs that differ from Packet

#### Proposed Solution
- [ ] new versions of recvmmsg, recv_from, and streamer that are entity-size agnostic, consume generics that implement a recvmmsgable trait (probably need byte vector, socketaddr, Default)
- [ ] move Blob over to new transport
- [ ] move other Blob fields into the Blob struct
- [ ] deserialize Entries (possibly Vec<Entry>) from Blob bytes

complications: erasure, db_ledger

**Comment by aeyakovenko** [comment]
@rob-solana a leader can just sign the poh value of the entry and store that signature outside of the entry in the blob it transmits.

**Comment by garious** [comment]
This ticket keeps getting bumped. Looking closer, the problem description and proposed solution is quite dense, and the ticket's title doesn't reflect that at all. Consider breaking this up into several tickets so that we can get them assigned and completed.

**Comment by rob-solana** [comment]
cc #2762

**Comment by rob-solana** [comment]
obsolete
