### ISSUE TITLE
Bootstrap with incremental snapshots will never get a snapshot that's a multiple of our full snapshot

### ISSUE THREAD

**Issue by brooksprumo** [solana-labs/solana#21130]
#### Problem

When incremental snapshots are enabled, bootstrap tries to download a snapshot that is a multiple of its full snapshot archive interval. However, snapshots are *taken* based on the *block height*, but *named* based on the *slot*... So basically the check for `is snapshot a multiple of our full snapshot archive interval` will (almost) always be `false`...

#### Proposed Solution

Possible options:

1. Add some way to map a slot number to block height
    - I don't know how this would work. Is it even possible?
2. Put the block height in the snapshot's filename so it can be parsed by bootstrap
    - Would be possible. Would also either cause code bifurcation on snapshot filename parsing, or render old snapshots incompatible for bootstrap.
3. Change when we take snapshots to be based on slot not block height
    - Not a good idea, as then there's a risk snapshots are not taken if slot numbers are skipped. Missing a full snapshot would be bad.
4. Update gossips for `crds_value::IncrementalSnapshotHashes` to include the block height for the base snapshot hash.
    - Could be doable. Would need to make this change ASAP to not cause more backwards incompatibility/issues when upgrading.

Of these options, I'm leaning towards option 4. Are there other possibilities?

Related to #17088

**Comment by brooksprumo** [comment]
@mvines @carllin Can I get your thoughts on this? Are there other possible solutions that I haven't listed? Is option 4 doable?

**Comment by brooksprumo** [comment]
@behzadnouri Can I get your thoughts on this too, since option 4 would add a u64 to `base` in `IncrementalSnapshotHashes`.

**Comment by behzadnouri** [comment]
> @behzadnouri Can I get your thoughts on this too, since option 4 would add a u64 to `base` in `IncrementalSnapshotHashes`.

The way to do it is to rename current `IncrementalSnapshotHashes` to `LegcyIncrementalSnapshotHashes` and then introduce the new `IncrementalSnapshotHashes` crds value.
Kind of similar to `Version` -> `LegacyVersion` done in: https://github.com/solana-labs/solana/pull/12376

**Comment by brooksprumo** [comment]
@mvines @carllin One problem with Option 4 is the startup case, the `StartingSnapshotHashes` in particular.

When a node starts up, it loads from its latest snapshots (full + incr, for this example). Those snapshot hashes are then passed to SnapshotPackagerService, which are then pushed to CRDS. Other nodes use the values from CRDS to find the best snapshots to download.

So here's the issue: node loads from snapshots, where does it get the full snapshot's _block height_ from?

"Why does that matter?", well, when a node during bootstrap is trying to find snapshots, it needs to find full snapshots that are multiple of its full snapshot interval, which is _block height_, not the slot. Where does it get the block height from? If other nodes cannot get the block height from the full snapshot used when starting up, then CRDS will not have valid block height values...

So now there are two problems:

Problem A: The original problem, in the issue's description.
Problem B: When a node starts up, it needs to be able to get the block height from the full snapshot it loaded from.

Unfortunately, Option 4 does not solve Problem B... But, if we also do Option 1, then that would solve both problems. Probably could even do _just_ Option 1, and not need to do Option 4.

I guess my new question is: Is there a way to do Option 1?

**Comment by brooksprumo** [comment]
There may be another possible solution too.

During bootstrap, we may be able to just look for full snapshots that are the exact match as ours, instead of looking for multiples of our full snapshot interval. This is not ideal, since we'll still need to figure out if our full snapshot is just too old to be useful. Ideally in that case then we'd download a full snapshot at our interval so that subsequent nodes that download snapshots during bootstrap would find our new incremental snapshots (since if the "base" for the incremental snapshots are different, they are unusable).

If we were already forward in time where every node already enabled incremental snapshots, then I think the option ^^ might work OK, but I don't think it'd be great yet. But maybe that's the best option? This also means there would be no changes needed to gossip.

**Comment by mvines** [comment]
I'd rather not expose block height into the snapshots if possible. I'm still trying to remember why this wasn't a problem before incremental snapshots existed though 🤔

**Comment by brooksprumo** [comment]
> I'm still trying to remember why this wasn't a problem before incremental snapshots existed though 🤔

My best reasoning is that block height was chosen over slot number to determine when to take a bank snapshot was to ensure the snapshot could not be skipped. Since slots may be skipped, if bank snapshot interval was 100, and slot 100 was skipped, that would skip the bank snapshot. That would be no good, since the bank snapshot is also used by AccountsHashVerifier to do the accounts hash verification.

**Comment by mvines** [comment]
Ah right that makes sense. 

Option 4 seems fine!  We don't need this fortunately:

> The way to do it is to rename current `IncrementalSnapshotHashes` to `LegcyIncrementalSnapshotHashes` and then introduce the new `IncrementalSnapshotHashes` crds value.
> Kind of similar to `Version` -> `LegacyVersion` done in: #12376

since `IncrementalSnapshotHashes` has not yet shipped

**Comment by mvines** [comment]
> So here's the issue: when a node loads from snapshots, where does it get the full snapshot's block height from?

Can we supply the full snapshot's slot height instead?  We do have that in hand

**Comment by brooksprumo** [comment]
> > So here's the issue: when a node loads from snapshots, where does it get the full snapshot's block height from?
> 
> Can we supply the full snapshot's slot height instead? We do have that in hand

Unfortunately no, but we could. During the deserialization process, when the full snapshot is deserialized, I could grab the block height of the full snapshot and then return that information up the call stack.

Phew! This should be doable; just more unsightly plumbing.

**Comment by mvines** [comment]
> I could grab the block height of the full snapshot and then return that information up the call stack.

I think it'll be easier if you just use slots as the units everywhere.

**Comment by brooksprumo** [comment]
> > I could grab the block height of the full snapshot and then return that information up the call stack.
> 
> I think it'll be easier if you just use slots as the units everywhere.

Oh, sorry, I misread your [first](https://github.com/solana-labs/solana/issues/21130#issuecomment-969259826) comment. We do already have the full snapshot's _slot_, but we need its _block height_, because that's the value we need to compare against during bootstrap in the is-multiple-of-our-full-snapshot-interval function.

**Comment by brooksprumo** [comment]
> We don't need this fortunately:
> 
> > The way to do it is to rename current `IncrementalSnapshotHashes` to `LegcyIncrementalSnapshotHashes` and then introduce the new `IncrementalSnapshotHashes` crds value.
> > Kind of similar to `Version` -> `LegacyVersion` done in: #12376
> 
> since `IncrementalSnapshotHashes` has not yet shipped

I see that `IncrementalSnapshotHashes` is already in v1.7 and v1.8; is that an issue?

**Comment by mvines** [comment]
> Oh, sorry, I misread your [first](https://github.com/solana-labs/solana/issues/21130#issuecomment-969259826) comment. We do already have the full snapshot's _slot_, but we need its _block height_, because that's the value we need to compare against during bootstrap in the is-multiple-of-our-full-snapshot-interval function.

When booting we know the slot of our current full snapshot based on the filename and can use that full snapshot slot to filter the `IncrementalSnapshotHashes` values for any incremental snapshots that are newer than the local incremental (if any). I'm missing why block height is important in this?

> > since `IncrementalSnapshotHashes` has not yet shipped
> 
> I see that `IncrementalSnapshotHashes` is already in v1.7 and v1.8; is that an issue?

Should be ok. Incremental snapshots might not actually work on master attached to mainnet until the new CRDS value layout lands and ships in v1.8/v1.7 but that's only a minor inconvenience for us and better than a "Legacy" value for an unshipped feature.

**Comment by brooksprumo** [comment]
> > Oh, sorry, I misread your [first](https://github.com/solana-labs/solana/issues/21130#issuecomment-969259826) comment. We do already have the full snapshot's _slot_, but we need its _block height_, because that's the value we need to compare against during bootstrap in the is-multiple-of-our-full-snapshot-interval function.
> 
> When booting we know the slot of our current full snapshot based on the filename and can use that full snapshot slot to filter the `IncrementalSnapshotHashes` values for any incremental snapshots that are newer than the local incremental (if any). I'm missing why block height is important in this?

The additional step during bootstrap is that a node should prefer to download a full snapshot that is a multiple of its own full snapshot interval. And since the full snapshot interval is really the block height, that means CRDS needs to have the block height info as well.

"Why should a node prefer to download a full snapshot that is a multiple of its own full snapshot interval?"

Good question! And this is more for overall network optimization. Given the following scenario:
1. We're further in the future where basically all nodes have incremental snapshots enabled
2. Many nodes use a non-default value for `full_snapshot_interval`
(note: (1) will happen, and (2) may or may not happen)

- NodeA is a new node joining the network. Its full snapshot interval is set to 100,000.
- During bootstrap, NodeA may find many snapshots from CRDS. In this example, lets say it finds three: 
    - snapshot 1: full @ slot 200,000, incr @ slot 253,000
    - snapshot 2: full @ slot 233,331, incr @ slot 253,000 (full snapshot interval = 33,333)
    - snapshot 3: full @ slot 253,100, no incr (incremental snapshots disabled, full_snapshot_interval = 100

- If NodeA chooses the highest snapshot overall, that would be snapshot 3
    - But, _future nodes_ needing to download an incremental soon will likely not be able to download any incremental snapshots from NodeA, since it's unlikely those future nodes will have an existing full snapshot at this slot
        - This may not be a common case. Both disabling incremental snapshots, and two, in about 11 hours or less, the future node will take another full snapshot at its real interval
    - However, if NodeA already had full snapshot 200,000, then it's likely that downloading an incremental snapshot 100 slots lower will be a net _win_ since the download time will be substantially shorter.

- If NodeA skips snapshot 3, and picks snapshot 2, this would again impact _future nodes_ for the same reason as picking snapshot 3, and have the same issue if NodeA already had full snapshot 200,000.
- If NodeA picks snapshot 1, and future nodes have the same full snapshot interval, then NodeA can be a valid rpc peer to download snapshots from.
    - This is really the ideal, where all nodes are using the same full snapshot interval, so that all the base snapshots (i.e. full) are the same, which enables all the incremental snapshots to be shared.


#### Observations

I think after typing all this out, maybe this isn't really as big of an issue as I initially thought. Or minimally, maybe fully implementing the ideal scenario isn't needed for version 1 of incremental snapshots.

This could be a compromise:

1. Get all the snapshots from peers
2. Get the snapshots with the highest slot, whether that is full+incr or just full
3. Prioritize the snapshots with a full snapshot slot that matches our existing full snapshot slot (and hash) so that we can skip downloading the full snapshot.

That will work, and just be suboptimal—causing unnecessary downloading of full snapshots—hopefully infrequently. Metrics could be added to see how often this actually happens too. (In the example above, we'd download snapshot 3 with this design.)

This has been quite long and meandering... Hopefully it makes enough sense though. What do you think about this path forward, @mvines?

**Comment by mvines** [comment]
That compromise sounds great.  Also mixed in there should be that snapshots, full or inc, that aren't also published by your known validator list should also be ignored -- so as long as your known validators are all configured with the same snapshot interval setting then I think unnecessary downloads of full snapshots should be very uncommon

**Comment by brooksprumo** [comment]
> That compromise sounds great. Also mixed in there should be that snapshots, full or inc, that aren't also published by your known validator list should also be ignored -- so as long as your known validators are all configured with the same snapshot interval setting then I think unnecessary downloads of full snapshots should be very uncommon

Good point. I left out the part about known validators since that isn't changing; but that simplifies this further! With all know validators configured with the same snapshot interval setting, then (3) from above can be skipped (which will make the impl much simpler). We can always revisit this in the future if these assumptions do not hold.
