### ISSUE TITLE
initializeAccount

### ISSUE THREAD

**Issue by ruiyeclub** [solana-labs/solana#21147]
`Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA invoke [1] Program log: Instruction: InitializeAccount Program log: Error: InvalidAccountData Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA consumed 2144 of 200000 compute units Program TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA failed: invalid account data for instruction`

Error when creating token account

**Comment by ceciEstErmat** [comment]
You did not provide enough information for us to give you much help. Can you describe what you did to get this error ?

**Comment by ruiyeclub** [comment]
look this
https://solscan.io/tx/3MPQrqMqop3yxeuoqE5Co7WkJHksGDfvMb4yNRoHvyykZL7yu8NiX3hAPdDypzwZZZghdMckePuocib2wksHfuHp?cluster=testnet

**Comment by ruiyeclub** [comment]
> You did not provide enough information for us to give you much help. Can you describe what you did to get this error ?

look this
https://solscan.io/tx/3MPQrqMqop3yxeuoqE5Co7WkJHksGDfvMb4yNRoHvyykZL7yu8NiX3hAPdDypzwZZZghdMckePuocib2wksHfuHp?cluster=testnet
