### ISSUE TITLE
Problems creating a Solana wallet

### ISSUE THREAD

**Issue by rrrwolf** [solana-labs/solana#21179]
#### Problem
When I choose devnet, the mainnet beta is created, do you know why this happens? And then there is a problem in checking the balance, help me, I'm a beginner
Attached screenshots

#### Proposed Solution
![девнет майннет](https://user-images.githubusercontent.com/93736693/140410130-d4f9e3d0-465d-44c8-b03d-b8c0923e7eac.JPG)
![Ошибка баланс](https://user-images.githubusercontent.com/93736693/140410148-d5cdb885-8fbb-4aa7-8bfe-8174f967eb87.JPG)

**Comment by detinho** [comment]
It seems that you are creating a key pair on a path and setting another path as the default key pair.
Be aware that the file name is different (devnet-test.json vs mainnet-beta-test.json) but also on the first image the config dir does not start with a dot.

**Comment by fanatid** [comment]
You are created a keypair by one path (`devnet-test.json`) and then set a path to the keypair which does not exist (`mainnet-beta-test.json`). Error is expected.

**Comment by steviez** [comment]
The other comments pointed out issue; regardless, we don't use GitHub for support and you should join on Discord for further help/questions https://discord.com/invite/solana.
