### ISSUE TITLE
Trying to install Solana on AWS "Amazon Linux"

### ISSUE THREAD

**Issue by njb69** [solana-labs/solana#21195]
#### Problem
When I download the prebuilts and try to install them with: sh -c "$(curl -sSfL https://release.solana.com/v1.8.2/install)" I get the error: "/tmp/tmp.opOR5dAVoT/solana-install-init: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory"

I found an issue similar to this opened in 2019 (https://github.com/solana-labs/solana/issues/3969), and tried to follow this proposed solution script (https://github.com/solana-labs/solana/blob/379d2e6d95bea2f76763a17625aefd3a8e5af386/net/scripts/install-libssl-compatability.sh), but I'm stuck at the dpkg install command because of dependency issues, and it's become increasingly frustrating/time-consuming to try and force this to work with this weird Amazon Linux. Does anyone know if there's an easier way to do this, or should I just make a new linux instance somewhere outside of AWS?

**Comment by njb69** [comment]
I tried Azure and got it working in minutes :| 

Azure >>>> AWS as it turns out

**Comment by t-nelson** [comment]
I suspect this would have worked fine on whatever "Amazon Linux" is had you installed the prerequisite system dependencies.  We recommend Ubuntu 20.04.

Glad you got it working regardless!
