### ISSUE TITLE
sdk symbols provided by the loader should be marked weak

### ISSUE THREAD

**Issue by jhunsaker** [solana-labs/solana#21198]
#### Problem

attempting to link programs with `-z defs` results in unknown symbols for some symbols provided by the loader

#### Proposed Solution

mark symbols provided by the loader as `weak`

example:

```c
uint64_t sol_invoke_signed_c(
  const SolInstruction *instruction,
  const SolAccountInfo *account_infos,
  int account_infos_len,
  const SolSignerSeeds *signers_seeds,
  int signers_seeds_len
) __attribute__(( weak ));
```

**Comment by Alpsglm** [comment]
uint64_t sol_invoke_signed_c(
  const SolInstruction *instruction,
  const SolAccountInfo *account_infos,
  int account_infos_len,
  const SolSignerSeeds *signers_seeds,
  int signers_seeds_len
) __attribute__(( weak ));
