### ISSUE TITLE
"Sorry there was an error! Failed to fetch" step 6 Metaplex

### ISSUE THREAD

**Issue by mcvalor** [solana-labs/solana#21208]
#### Problem
Start the create NFT flow with a local mp4 file 
Connect a wallet with ~0.258 SOL in it on mainnet
Start the NFT Create flow
Reach step 6 (#/art/create/6)

Receive the following message:
"Sorry there was an error! Failed to fetch"

Confirmed that this reproduces multiple times in Chrome and Firefox

#### Proposed Solution
Ideally, this should not happen

Thank you,
DM.

**Comment by t-nelson** [comment]
Metaplex is not supported in this repository
