### ISSUE TITLE
Transaction format question.

### ISSUE THREAD

**Issue by orestonce** [solana-labs/solana#21221]
#### Problem

After read the "https://docs.solana.com/developing/programming-model/transactions" atrticle, I use command 
`````
solana transfer 5U3bH5b6XtG99aVWLqwVzYPVpQiFHytBD68Rz2eFPZd7 0.001 --sign-only --blockhash EDGLRkGtUSSmfttcCFrVw57n6ZM5WBVAcaebvPjFF84u  --dump-transaction-message
`````
 to build a raw transaction, but it seems something confuse me.

The outout transaction data is 
````
AQABA0b/xor0qjfVx5dxwt1FIHPyiQF0YjyGlJhNEJ9peFbYQlxb88UapZ0T6mWzABhtX/lDiPrAaUMbsl4vmXpBgd4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMRMPTDQTCbnWYLhBYhB16sSC635PHR82OVOiQ5lupQuAQICAAEMAgAAAEBCDwAAAAAA
````
I decode it , and found:
> A message contains a header, followed by a compact-array of account addresses, followed by a recent blockhash,  **followed by a compact-array of instructions.**

After the recent blockhash, I found thus 6 fixed-bytes "0x01, 0x02, 0x02, 0x00, 0x01, 0x0c" - "transaction type (4 bytes)" - "transfer value (8 bytes)"

I don't know the 6 fixed-bytes "0x01, 0x02, 0x02, 0x00, 0x01, 0x0c", I don't know what it means. Where can I read the relevant documents?

**Comment by CriesofCarrots** [comment]
Those bytes are:
0x01 - number of instructions (to follow)

Instruction 0:
0x02 - index of the program id in the account_keys array
0x02 - number of account indexes (to follow)
[0x00, 0x01] - accounts to be passed to the instruction, as indexes into the account_keys array
0x0c - length of passed data (to follow)
(... then the 12 bytes of instruction data that you've already identified)

Here's what that message looks like when decoded and deserialized into a rust Message struct:
```
Message {
    header: MessageHeader {
        num_required_signatures: 1,
        num_readonly_signed_accounts: 0,
        num_readonly_unsigned_accounts: 1
    },
    account_keys: [
        33knknrwE2LqiCvAfpYSLEFM6ktwCXSb2sSYScypWpRY,
        5U3bH5b6XtG99aVWLqwVzYPVpQiFHytBD68Rz2eFPZd7,
        11111111111111111111111111111111
    ],
    recent_blockhash: EDGLRkGtUSSmfttcCFrVw57n6ZM5WBVAcaebvPjFF84u,
    instructions: [
        CompiledInstruction {
            program_id_index: 2,
            accounts: [0, 1],
            data: [2, 0, 0, 0, 64, 66, 15, 0, 0, 0, 0, 0]
        }
    ]
}
```

**Comment by CriesofCarrots** [comment]
If you have more questions, please join us on Discord: https://solana.com/discord
That's the best place for technical support

**Comment by orestonce** [comment]
Thank you.
