### ISSUE TITLE
Incompatible CPU detected: missing AVX2 support. Please build from source on the target

### ISSUE THREAD

**Issue by chenzhijun45** [solana-labs/solana#21233]
Running a Validator Error

solana-cli 1.7.17 (src:5f867353; feat:140464022)

[2021-11-10T10:41:47.039557981Z WARN  solana_perf] CUDA is disabled
[2021-11-10T10:41:47.039589756Z INFO  solana_perf] AVX detected
[2021-11-10T10:41:47.039595490Z ERROR solana_perf] Incompatible CPU detected: missing AVX2 support. Please build from source on the target

My operating system：
Linux version 4.15.0-43-generic (buildd@lgw01-amd64-001) (gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)) #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018

I am a novice，What shall I do ? Help me please

**Comment by detinho** [comment]
From here: https://docs.solana.com/running-validator/validator-reqs

"AVX2 instruction support (to use official release binaries, self-compile otherwise)".

Please run:
`grep avx2 /proc/cpuinfo`
If it returns empty you'll need to build from sources.

**Comment by steviez** [comment]
As @detinho pointed out and as the error message states, you will need to build from source (instructions in this repo's README).

I'd also encourage you to [search the existing issues](https://github.com/solana-labs/solana/issues?q=is%3Aissue+avx2) when looking for help; it is possible that others have run into and resolved the same issues before you.

**Comment by chenzhijun45** [comment]
> From here: https://docs.solana.com/running-validator/validator-reqs
> 
> "AVX2 instruction support (to use official release binaries, self-compile otherwise)".
> 
> Please run: `grep avx2 /proc/cpuinfo` If it returns empty you'll need to build from sources.

It works. Thank you

**Comment by chenzhijun45** [comment]
> As @detinho pointed out and as the error message states, you will need to build from source (instructions in this repo's README).
> 
> I'd also encourage you to [search the existing issues](https://github.com/solana-labs/solana/issues?q=is%3Aissue+avx2) when looking for help; it is possible that others have run into and resolved the same issues before you.

Well, thank you
