### ISSUE TITLE
The UDP monitoring feature prevents the validator starting on WSL

### ISSUE THREAD

**Issue by ix42** [solana-labs/solana#21253]
#### Problem

Since the UDP monitoring feature was added (https://github.com/solana-labs/solana/pull/20587), the validator no longer runs on WSL systems (verify_udp_stats_access will abort starting the validator). 

#### Proposed Solution

Just thought mentioning it, it's your choice if you want it to run on those systems or not. 
Ideally there should be an option if people want to add the monitoring service or not, as that would solve this problem and monitoring adds an overhead anyway.

**Comment by dzmitry-lahoda** [comment]
i cannot use anchor because of this feature

**Comment by mvines** [comment]
Can you share some more details about "verify_udp_stats_access will abort starting the validator".  We'd like to support WSL, yes. 

Are you seeing a message like this "Failed to access UDP stats: <blah blah>" in the log and then the validator exits?

**Comment by ix42** [comment]
Yes, that's the message (the server will exit in validator.rs:454)

This can be prevented via advanced firewall settings in windows, but i believe the easy/proper solution is to make UDP stats optional.

**Comment by mvines** [comment]
@jbiseda - hey can you take a look at this one? I think we just need to remove that `abort();`
