### ISSUE TITLE
trouble installing solana on ubuntu

### ISSUE THREAD

**Issue by modular1** [solana-labs/solana#21263]
#### Problem
Hi i keep getting an error when i want to install solana on ubuntu(on Kali for example it works flawless). The error i get is:

sh -c "$(curl -sSfl https://release.solana.com/stable/install)" 
downloading stable installer
curl: (23) Failure writing output to destination
solana-install-init: command failed: downloader http://release.solana.com/stable/solana-install-init-x86_64-unknown-linux-gnu /tmp/tmp.P3OvZXZKZp/solana-install-init

Tested on PI, VM and proxmox setup with 21.10 and 20.04.

any idea?

**Comment by deadwire-voodoo** [comment]
Not sure how much this helps but I had a very similar experience and wasn't able to pinpoint why exactly. I ended up using 1.8.3     solana-install update isn't updating yet but everything else seems fine
https://github.com/solana-labs/solana/releases/tag/v1.8.3

**Comment by modular1** [comment]
Thank you for the idea. However it produces the same error message for me. Also again this only seems to be a problem on Ubuntu

**Comment by askibin** [comment]
check if you have permissions to write to a temp directory - create it with mktemp -d and then copy paste a file over there or just echo

**Comment by erandasooriyabandara** [comment]
This will help you install Solana with a workaround, https://stackoverflow.com/questions/70736761/solana-installation-failure-with-curl-23-failure-writing-output-to-destinatio

**Comment by steviez** [comment]
Due to inactivity, guessing one of the suggestions above did the trick for you
