### ISSUE TITLE
getBlock RPC does not allow commitment level processed

### ISSUE THREAD

**Issue by buffalu** [solana-labs/solana#21268]
#### Problem
The [getBlock](https://docs.solana.com/developing/clients/jsonrpc-api#getblock) JSON RPC API call does not support using processed commitment level, yet other transaction-related APIs (getBalance, getBlockHeight, ..., accountSubscribe, logsSubscribe, signatureSubscribe, etc.) allow use of processed commitment level.

#### Proposed Solution
Add support for processed, potentially with a disclaimer on shortcomings (may be on fork or small chance of another block coming in).

#### Questions
- Is there a technical or consensus related reason why getBlock doesn't allow using processed? I assume once the slot is completed, it should have the block processed (of course you may run into fork or double block production, but that's what happens with processed anyway).

**Comment by t-nelson** [comment]
@CriesofCarrots do you have any Opinions :tm: here?

**Comment by CriesofCarrots** [comment]
I think that we are now probably collecting all the data we need to potentially turn on processed `getBlock` commitment.

However, the main blocker to robust support may be the time it takes to write the various block transaction and account details to blockstore, which is currently a prerequisite for successful `getBlock` responses. I suspect that in many cases, the cluster will actually confirm the block before it is fully available from blockstore. But perhaps we could mitigate this by composing a populated rpc block to keep briefly in memory.

Alternately, we could almost certainly return processed basic block metadata -- block height, block hash, parent blockhash, etc -- right now with no architecture changes. I don't suppose that meets your needs, does it @buffalu ?

**Comment by CriesofCarrots** [comment]
Oh, and as per your Discord query:

> Note that the block may not be complete.", kinda curious what that means

I believe that is no longer true. At one point in the past, `processed` rpc used to query the current working bank. But now, it queries the latest frozen bank, so it should always be complete.

**Comment by buffalu** [comment]
> Oh, and as per your Discord query:
> 
> > Note that the block may not be complete.", kinda curious what that means
> 
> I believe that is no longer true. At one point in the past, `processed` rpc used to query the current working bank. But now, it queries the latest frozen bank, so it should always be complete. Where do you see that? I'd like to update it.

this is in the rpc docs for commitment level.

**Comment by buffalu** [comment]
> responses

the reason we're asking about this is because we're trying to add a blockSubscribe pub/sub API with different commitment levels and were looking at getBlock for inspiration. We were mainly curious on why processed wasn't supported since (from my limited understanding) you'll have a "processed" block once you receive all shreds and the slot is completed.

**Comment by buffalu** [comment]
its fine, i think geyser provides blocks after processed? will build something around that
