### ISSUE TITLE
Implement `Pubkey::is_on_curve` for BPF

### ISSUE THREAD

**Issue by armaniferrante** [solana-labs/solana#21270]
#### Problem

The `Pubkey::is_on_curve` method is currently not implemented for BPF https://github.com/solana-labs/solana/blob/master/sdk/program/src/pubkey.rs#L127. This would be very useful for programs that want to only allow user wallets to perform a specific action. 

For example, a governance program might not want to allow another program to lock tokens and vote since such composition may open the door to liquid locked token derivatives, which may not be desired.

**Comment by t-nelson** [comment]
This might be better off as a syscall

**Comment by mryalamanchi** [comment]
@t-nelson what's the advantage or any aspect that improves by putting it in the syscalls?

**Comment by t-nelson** [comment]
> @t-nelson what's the advantage or any aspect that improves by putting it in the syscalls?

The point multiplication is expensive in BPF

**Comment by mgild** [comment]
Any updates on this?

**Comment by t-nelson** [comment]
@samkim-crypto would the ed25519 primitive syscalls you've been working on enable implementing this?

**Comment by samkim-crypto** [comment]
Yes, the curve25519 syscalls should cover this case, but I can double check. This should be something that is very useful.

**Comment by 2501babe** [comment]
this is something i might also have use for, although im nor familiar enough with either the runtime or elliptic curve operations to have confidence working on this myself. has the status of this changed since march? i see `sol_curve_validate_point` has a suggestively plausible name and was added in may, but cant speculate further

**Comment by t-nelson** [comment]
i believe `sol_curve_validate_point` is behind feature gate `7rcw5UtqgDTBBv2EcynNfYckgdAaH1MAsCjKgXMkN7Ri`.  if you'd like to speed up its activation, i'd suggest working with @samkim-crypto on stabilization

**Comment by samkim-crypto** [comment]
Yes, this is behind `curve25519_syscall_enabled`, which should pretty much be ready, but I was told to hold off on activating it until some issues with the jit runtime are resolved. I will make sure to let you know when it is activated.

**Comment by 2501babe** [comment]
ok great! lmk if theres anything you need help with

**Comment by vl-dev** [comment]
Any progress on this or any workaround? Need this to ensure that tokens are only sent to ATAs owned by user wallets and not PDAs.

**Comment by ronanyeah** [comment]
Yeah open this up please.
