### ISSUE TITLE
Error: ELF error: ELF error: Incompatible ELF: wrong machine

### ISSUE THREAD

**Issue by cyberpwnn** [solana-labs/solana#21272]
#### Problem
If i compile with `cargo clean` & `cargo build --release` then use `solana program deploy -v <the built .so file>`. I get the following output

```
RPC URL: http://127.0.0.1:8899
Default Signer Path: /home/~~~~~/.config/solana/id.json
Commitment: confirmed
Error: ELF error: ELF error: Incompatible ELF: wrong machine
```

What is happening that is causing wrong machine

#### Proposed Solution
More informative errors or documentation on what these errors mean and how to avoid them

**Comment by alanpilloud** [comment]
@cyberpwnn Hi, did you find what is causing this issue ? Thanks for your help.
