### ISSUE TITLE
Can a maintainer please approve my workflow!

### ISSUE THREAD

**Issue by MadJimJaspers** [solana-labs/solana#21287]
Why is my workflow taking so long to be approved? definitely discouraging for a new developer !
please help!

**Comment by mvines** [comment]
Please provide a link to the workflow you are referring to

**Comment by MadJimJaspers** [comment]
https://github.com/solana-labs/token-list/pull/4159

**Comment by mvines** [comment]
Oh we don't support token-list in this project's issues.  Sorry you'll need to wait there instead
