### ISSUE TITLE
[storage mining] Validator key state needs reworking

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#2129]
#### Problem

Validators are generating encryption keys based on votes seen in the ledger, but they should look at the storage proofs on the ledger and use the keys in the proof transaction that the replicator used to generate the storage proof.

#### Proposed Solution

Implement the storage design where the storage keys will be generated by replicators based on PoH values, posted in storage proofs and then validators should observe those to determine what key to use.

**Comment by sagar-solana** [comment]
@sakridge, qq is the book's "encryption key" the same as what the code calls "storage key"?

**Comment by sakridge** [comment]
@sagar-solana yes, that's right.
