### ISSUE TITLE
which can find the Snapshot of sol node

### ISSUE THREAD

**Issue by cellname** [solana-labs/solana#21315]
My sol node upgrade 1.8.3 resulted in a resynchronization height, I want to find a snapshot for quick synchronization

**Comment by steviez** [comment]
Hello - we don't use GitHub for support requests; rather, please join us on Discord instead at https://discord.com/invite/solana.

Hopefully you figured this out already, but `solana-validator` will download a snapshot if you don't have `--no-snapshot-fetch` argument. Additionally, you can run `solana-validator init` which will download a snapshot, but not actually start running the validator
