### ISSUE TITLE
Implement a way to determine the remaining compute units inside the program

### ISSUE THREAD

**Issue by totikom** [solana-labs/solana#21334]
#### Problem
`solana-program` has function `sol_log_compute_units()` which _logs_ "a message containing the remaining number of compute units the program may consume before execution is halted", but this number is not returned.

My program performs a rather complex computation, which _can_ exceed the computational budget.
The amount of computations depends on input the input data and can not be predicted, however this computation can be split into small chunks of _approximately_ known computational size.

Between those computational chunks the state of the program can be serialized and stored in an `account`.

#### Proposed Solution

```rust
pub fn sol_compute_units() -> u32 {}
```

If there was a function, which _returns_ the remaining number of computational budget, cases like the above-mentioned can be solved easily:
1. Perform one computational chunk
2. if the computation is finished, return "computation successfully finished"
2. Else check the remaining number of comp. units
3. If it is less than a some threshold, serialize the state and return smth like "computation unfinished, send new transaction to continue"
4. Else `goto 1`

**Comment by askibin** [comment]
not exactly a solution, but did you know that you can simulate the transaction? you could determine max size of the chunk this way as a temp workaround

**Comment by totikom** [comment]
Sure, I have a temporary solution based on debug measurements, but it is
1. Hard to implement: I have to automate chunks runs and parse `solana-test-validator` logs to gather the needed data.
2. __Very__ error-prone

That's why I think, that `sol_compute_budget()` will be very usefull part of the API.
