### ISSUE TITLE
Wallet CLI can't create ERC20-like tokens

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#2134]
#### Problem

Can't use the command-line interface to create new ERC20-like tokens or transfer those tokens.

#### Proposed Solution

- [ ] Add a command for spinning up a new token.
- [ ] Add options to the existing commands to specify the token name, and if present, use TokenProgram instead of SystemProgram to do the transfer.

**Comment by CriesofCarrots** [comment]
Supported in spl-token cli: https://github.com/solana-labs/solana-program-library/tree/master/token/cli
