### ISSUE TITLE
Error: Illegal hardware instruction

### ISSUE THREAD

**Issue by team-btg** [solana-labs/solana#21340]
Having issue when doing solana-keygen. Not sure what else should I need to install.

Doing command: `solana-keygen new --outfile ~/mypath/test.json`
Error: Illegal hardware instruction

OS: macOS
Solana: solana-cli 1.8.4

**Comment by totikom** [comment]
Does your CPU support AVX2 instructions?
Solana programs are build with this instructions enabled, so if your CPU can not execute them, solana binaries are incompatible with your PC.

In that case you have to build solana toolchain from source.
