### ISSUE TITLE
Need Token Transfer JS File

### ISSUE THREAD

**Issue by osiz-blockchainapp** [solana-labs/solana#21341]
#### Problem
We created the Token in solana testnet using CLI Commands. We need JS file to implement the token functionalities. So kindly provide sample JS file to transfer and mint the tokens with third party wallets connectivity.

**Comment by mw108** [comment]
There are resources on StackOverflow available on how to do that.

For instance:
https://stackoverflow.com/questions/68236211/how-to-transfer-custom-token-by-solana-web3-js

**Comment by t-nelson** [comment]
Hi! We don't use Github for support.  Please join us in #developer-support on https://solana.com/discord
