### ISSUE TITLE
Missing data in long term storage

### ISSUE THREAD

**Issue by jiezhang** [solana-labs/solana#21350]
#### Problem
Parent of slot 91,598,692 is 91,598,683 according to https://explorer.solana.com/block/91598692, yet the latter cannot be retrieved: https://explorer.solana.com/block/91598683.

I also tried to query 91,598,683 using a node backed by BigTable, and it also returned `RPCError -32009: Slot 91598683 was skipped, or missing in long-term storage`.

Interestingly, child of slot 91,598,662 is also 91,598,692 according to https://explorer.solana.com/block/91598662. Is there a data corruption in slot 91,598,692 which results in the incorrect parent slot?

#### Proposed Solution
If parent of slot 91,598,692 is 91,598,683, 91,598,683 should be available in the long term storage and data in 91,598,662 should be corrected. The chain should be as follows: `91,598,662 => 91,598,683 => 91,598,692`.

If the parent is 91,598,692, the data in 91,598,692 should be corrected. The chain should then become `91,598,692 => 91,598,692.`

**Comment by jiezhang** [comment]
Here's another case:
https://explorer.solana.com/block/91924536: parent is 91924535
https://explorer.solana.com/block/91924535: missing
https://explorer.solana.com/block/91924522: child is 91924536

**Comment by jiezhang** [comment]
Another one:
https://explorer.solana.com/block/91924536: parent is 91924535
https://explorer.solana.com/block/91924535: missing
https://explorer.solana.com/block/91924522: child is 91924536

**Comment by CriesofCarrots** [comment]
Finalized blocks between `[91598662..9159892)` and `[91924523..1924536)` did not get properly uploaded to BigTable.
So the parent slots reported were correct. These gaps have been backfilled, and everything should look sane again.

**Comment by jiezhang** [comment]
@CriesofCarrots We just found another case. Can you please take a look?

https://explorer.solana.com/block/28944110: parent is 28944109
https://explorer.solana.com/block/28944109: missing
https://explorer.solana.com/block/28944078: child is 28944110

**Comment by CriesofCarrots** [comment]
Finalized blocks between `[28944079..28944110)` are now uploaded to BigTable as well.

**Comment by jiezhang** [comment]
@CriesofCarrots Looks like there is another missing block:

https://explorer.solana.com/block/51077205: parent is 51077204
https://explorer.solana.com/block/51077204: missing
https://explorer.solana.com/block/51077203: child is 51077205

**Comment by willhickey** [comment]
https://explorer.solana.com/block/51077204 has been restored

**Comment by jiezhang** [comment]
Here's another case:
https://explorer.solana.com/block/59437029: parent is 59437028
https://explorer.solana.com/block/59437028: missing
https://explorer.solana.com/block/59437027: child is 59437029

**Comment by willhickey** [comment]
https://explorer.solana.com/block/59437028 is available now

**Comment by jiezhang** [comment]
Would you mind taking a look at the following range?
https://explorer.solana.com/block/66856509: parent is 66856508
https://explorer.solana.com/block/66856508: missing
https://explorer.solana.com/block/66856372: child is unavailable

**Comment by willhickey** [comment]
The missing blocks between 66856508 and 66856372 have been restored to bigtable

**Comment by wangwangz18** [comment]
Missing blocks
110613433-110613480, 110300025-110300026 , 110492173-110492183 , 110556317-110556321,  110588572-110588595

**Comment by willhickey** [comment]
> 110613433-110613480, 110300025-110300026 , 110492173-110492183 , 110556317-110556321, 110588572-110588595

These have been restored
