### ISSUE TITLE
Failed to create ledger at test-ledger: blockstore error

### ISSUE THREAD

**Issue by fEyebrow** [solana-labs/solana#21357]
#### Problem
run solana-test-validator:
At first I got this error
![image](https://user-images.githubusercontent.com/18180417/142587098-86fdea9e-5ce0-452f-93a7-3f38b8482556.png)

then I read the [article](https://5balloons.info/correct-way-to-install-and-use-homebrew-on-m1-macs/)
after some steps , I run solana-test-validator again:
![image](https://user-images.githubusercontent.com/18180417/142586851-e42b4daf-97f9-4a28-9d62-0a24cbf0d07c.png)

#### Proposed Solution
do some system tuning
[article](https://5balloons.info/correct-way-to-install-and-use-homebrew-on-m1-macs/)

**Comment by t-nelson** [comment]
Hi! We don't use Github for support requests.  Join us in #developer-support on https://solana.com/discord instread
