### ISSUE TITLE
solana-test-validator websocket does not do anything

### ISSUE THREAD

**Issue by Arrowana** [solana-labs/solana#21359]
#### Problem

solana-test-validator websocket does not update subscriptions

This snippet does not print while it does not complain opening the websocket and creating the subscription
```
PubsubClient::slot_updates_subscribe("ws://localhost:8900",
    move |update| {
        println!("{:?}", update);
    }
)?;
```

#### Proposed Solution
Implement websocket json rpc in solana-test-validator

**Comment by CriesofCarrots** [comment]
`solana-test-validator` does support rpc subscriptions: https://github.com/solana-labs/solana/blob/master/test-validator/src/lib.rs#L490
And `slotsUpdatesSubscribe` works for me locally against a test validator (I'm on v1.8.5). Maybe an issue with your setup? 302 to [Discord](https://solana.com/discord) for technical support

**Comment by Arrowana** [comment]
I was using `slot_updates_subscribe` wrong, I did check with @joncinque before coming to complain here :).
All good now.

**Comment by joncinque** [comment]
Thanks for the response @CriesofCarrots ! My bad, I only looked at the solana-test-validator bin file https://github.com/solana-labs/solana/blob/master/validator/src/bin/solana-test-validator.rs and saw no reference to pubsub
