### ISSUE TITLE
example-webwallet catchup

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#2137]
The example-webwallet is on an older version of solana-web3.js and has a number of stale dependencies (see the webwallet PR list).  Need to freshen this example up before releasing v0.11

**Comment by garious** [comment]
When done, can you tag it and update the book/src/webwallet.md with the same `checkout $TAG` code as used in book/src/tictactoe.md?

**Comment by mvines** [comment]
Done.
* f98d72a30bef024b41babec899d3305f53dd357d
* https://github.com/solana-labs/example-webwallet/releases
