### ISSUE TITLE
Documentation server doesn't start up

### ISSUE THREAD

**Issue by fabioDMFerreira** [solana-labs/solana#21375]
#### Problem
There are a couple of problems starting the server from `docs` directory.

First, it seems there's one file missing.
```
 Error: Bad sidebars file.
These sidebar document ids do not exist:
- cli/usage,
```

After commenting the page ID on `sidebards.js` it throws errors related to static assets missing.

**Comment by t-nelson** [comment]
Sounds like you didn't run `./build.sh` in the `/docs` directory?

It looks like `docs/README` could stand to be re-ordered to make the `build.sh` step more apparently a dependency of `npm run start`. Is that something you'd be willing to PR?

**Comment by fabioDMFerreira** [comment]
You're right. I didn't run that command. 

Yes, I can open it. What do you think of including that script on the `postinstall`?
