### ISSUE TITLE
Solana aidrop method not found

### ISSUE THREAD

**Issue by Manuelandro** [solana-labs/solana#21387]
#### Problem
I followed the Figment Learn tutorial steps to configure solana devnet, create a keypair and aidrop the address with 1 sol but I keep getting the error above.

These are the commands

`solana config set --url https://api.devnet.solana.com`  √
`solana-keygen new --outfile solana-wallet/keypair.json` √

and then
`solana airdrop 1 $(solana-keygen pubkey solana-wallet/keypair.json)`

which returns
Requesting airdrop of 1 SOL
Error: RPC response error -32601: Method not found

#### Platform
macOs Monterey 12.0.1
processorm arm (yes i followed the instructions to install the x86 version with rosetta and so far the cli works)

**Comment by t-nelson** [comment]
Hi!  We don't use Github for support requests.  Please join us at https://solana.com/discord instead
