### ISSUE TITLE
resources that is required for running full node as  a service for monitoring transaction on solana

### ISSUE THREAD

**Issue by behnammohammadkhani** [solana-labs/solana#21381]
#### Problem
i have researched a lot about how to run full node of solana such a things that we have on ethereum (Geth).
it means that i need monitor transactions on solana without rate limiting and i need monitoring like a watcher for deposit to exchange.
for this reason i need to know how much resources we need to run solana full node?

thank you, if anyone have had any experiences in my issue or any idea ,plz comment below.

**Updated**
i'm meaning that how much CPU, RAM, SSD

**Comment by sakridge** [comment]
https://docs.solana.com/running-validator/validator-reqs#hardware-recommendations

**Comment by behnammohammadkhani** [comment]
i saw this doc, i don't want vote transactions ,do i for just monitoring TXs, it's required that provide validator resources?

**Comment by sakridge** [comment]
Just voting is not expensive. Do you want to execute all transactions to see the account state? If so, then you need something like a validator. If you don't care about certain security checks, then you maybe can save something.
