### ISSUE TITLE
Sporadic test issue with test_async_report_metrics

### ISSUE THREAD

**Issue by lijunwangs** [solana-labs/solana#21392]
#### Problem

Seeing the following failure quite a few times:

thread 'qos_service::tests::test_async_report_metrics' panicked at 'assertion failed: `(left == right)`
  left: `4096`,
 right: `2048`', core/src/qos_service.rs:341:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/std/src/panicking.rs:495:5
   1: core::panicking::panic_fmt
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/panicking.rs:107:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/panicking.rs:145:5
   4: solana_core::qos_service::tests::test_async_report_metrics
             at ./src/qos_service.rs:341:9
   5: solana_core::qos_service::tests::test_async_report_metrics::{{closure}}
             at ./src/qos_service.rs:309:5
   6: core::ops::function::FnOnce::call_once
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/ops/function.rs:227:5
   7: core::ops::function::FnOnce::call_once
             at /rustc/547a6ffee0cf4da9929a9e3d49546dc87d607735/library/core/src/ops/function.rs:227:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

https://buildkite.com/solana-labs/solana/builds/59851#5786531d-4ec5-4ef3-a931-e24a6603a676

**Comment by taozhu-chicago** [comment]
#21365 for this.
