### ISSUE TITLE
Can't join Solana Discord and Telegram group via Link ini web and github

### ISSUE THREAD

**Issue by welly87** [solana-labs/solana#21413]
#### Problem

I would like to discuss a couple of implementation choices that interesting from solana. I hope i can join the discord and discuss about this.  However I try to login by this [link](https://discordapp.com/invite/pquxPsq) from this page. 

![image](https://user-images.githubusercontent.com/242694/143221645-0e1c14f1-97ff-4107-93c0-5b052a44f08b.png)

I've reported to solana forum, seems a lot of people facing the same issues, but not resolved yet. 

https://forums.solana.com/t/why-cant-i-join-the-discord/3334/28

#### Proposed Solution

Should check with Discord admin and found out what's the cause

Cheers

**Comment by Jacob-CG** [comment]
Please ping me (JacobCG#3467) and I will look into what your issue is on discord. Closing this issue for now.
