### ISSUE TITLE
getSignaturesForAddress returns nothing

### ISSUE THREAD

**Issue by Flawm** [solana-labs/solana#21442]
#### Problem

Calling `getSignaturesForAddress` to any RPC for this address `6XWjMSt9uMKfJ3bp6778NgVjhxXWZuTw73dRZ4QQNd3S` fails to return any signatures. 

When viewing in solscan, or explorer.solana.com, the result is the same - there is no tx history.
https://solscan.io/account/6XWjMSt9uMKfJ3bp6778NgVjhxXWZuTw73dRZ4QQNd3S
https://explorer.solana.com/address/6XWjMSt9uMKfJ3bp6778NgVjhxXWZuTw73dRZ4QQNd3S

Try to fetch it yourself using the public RPC:

```bash
curl https://api.mainnet-beta.solana.com/ -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getSignaturesForAddress",
    "params": [
      "6XWjMSt9uMKfJ3bp6778NgVjhxXWZuTw73dRZ4QQNd3S"
    ]
  }
'
...
{"jsonrpc":"2.0","result":[],"id":1}
```
----
I've noticed if you pass a limit argument it works, and only works up to `"limit": 6` - not enough for this tokens full history.
```bash
curl https://api.mainnet-beta.solana.com/ -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getSignaturesForAddress",
    "params": [
      "6XWjMSt9uMKfJ3bp6778NgVjhxXWZuTw73dRZ4QQNd3S",
      {
        "limit": 6
      }
    ]
  }
'
...
<expected output>
```

The 6th TX signature can be seen [here](https://explorer.solana.com/tx/4QPktpbfgespAsxjGSDPb94kCMU65jRvyKgqcu7rQSmiZNq84VtD4WFBBKBDJRYZmmai6NpKQc4QQQaQLoXpm9iJ) and if I try to do an after filter it fails similarly, and an until filter works just like the `"limit": 6`

I've tested a quicknode, genesysgo, and the solana main net RPC. None of them work. This leads me to believe this is a systemic issue in Solana. It's like the blockchain history is unquery-able. I've seen this for other mints and other tokens but I thought I was just insane and/or sleep deprived, however this isn't a figment of my imagination and is presently seen here.

#### Proposed Solution

walking through the code I think things start going wrong here - at the very least, the signatures for this slot should've been queried from the db & included in the `Ok(infos)`
https://github.com/solana-labs/solana/blob/dd338b6c9ff1f5f2975605e1c3a98a5bf5f1d435/ledger/src/blockstore.rs#L2497 

additionally things start acting weirder ~20 lines down where the rest of the slots are looped over, either it's not looping over them because `slot > next_max_slot` isn't right, or it goes to iter over them but the db has nothing.

because of the aforementioned, the `highest_slot` argument may be wrong. without being able to debug and step through I can't discern much more

also, the deprecated call from rpc.rs as a catch-all fails to return anything as well - it's likely that the old and new `get_confirmed_signatures_for_address` suffer the same bug

**Comment by moonrank** [comment]
Hi! 

We (MoonRank) are the originators of this issue and we'd love to provide any more info if needed.

We go through the transaction history of millions of tokens and have hit this issue numerous times -- though it usually resolves itself at some point.

The token in question is still... broken for whatever reason.

Brian Long at Triton One said the following:

```
I think you might have uncovered a bug. In rpc.rs#1469, the search should go to BigTable to look for older signatures but it doesn't seem to get there.
```

Thanks!

**Comment by CriesofCarrots** [comment]
Thanks for the report!
I'm not sure if this explains all the times you have seen similar weirdness, but in this case, it looks like there was an incompatible change made to the InstructionError enum at some point between 6 and 7 transactions back that is preventing deserializing from BigTable. (All of the transactions are older than the node's local ledger.)

```
$ GOOGLE_APPLICATION_CREDENTIALS=<CRED> solana-ledger-tool bigtable transaction-history 6XWjMSt9uMKfJ3bp6778NgVjhxXWZuTw73dRZ4QQNd3S 6 -l <LEDGER>
[2021-11-30T22:51:46.596396938Z INFO  solana_ledger_tool] solana-ledger-tool 1.7.15 (src:4892eb4e; feat:2995838076)
[2021-11-30T22:51:46.599566791Z INFO  solana_storage_bigtable::access_token] Requesting token for BigTableDataReadOnly scope
[2021-11-30T22:51:46.658150820Z INFO  solana_storage_bigtable::access_token] Token expires in 3599 seconds
2882CSFx88roWqUG6H5nto1i2EYBQXS2BGx39ZUEn3qn52jDZkEsUPVrJiUnp7FnELjhKCkTW2eqWCjH63RD1BuH
3J6LkRxGKtPwQZ3t8YvzxmTcByQgALZoqqq5dHEhN7PzfmTiRFn6avfg1swkvSWnD9EtzPhmmvHXoWJDZ6q7W3CQ
5TfXaCsUpCi6zjvCQjv1Qovshx1Cgo9mNaFkfLCotjvrSuqNMBqjqwVVMm36bi7ZJwn4Ly3yHkeaeVGvYNUm6Hxi
qrNTqUZ6a5gbryXCEg3QxjTRfN1U3V8nZ7WvxbbrNha9LikX98wdjhdX6q45DcGEpMgBq9cRjUMDeWYeAspERWP
39qr26usKQT9oevNfGUCvebDx2VAYkT2SBzC9PssRwFg3P7HavbXtEgaewybk6ECeReRAKEP6KkfMywjUjKMeC6R
4QPktpbfgespAsxjGSDPb94kCMU65jRvyKgqcu7rQSmiZNq84VtD4WFBBKBDJRYZmmai6NpKQc4QQQaQLoXpm9iJ

$ GOOGLE_APPLICATION_CREDENTIALS=<CRED> solana-ledger-tool bigtable transaction-history 6XWjMSt9uMKfJ3bp6778NgVjhxXWZuTw73dRZ4QQNd3S 7 -l <LEDGER>
[2021-11-30T22:51:53.599361182Z INFO  solana_ledger_tool] solana-ledger-tool 1.7.15 (src:4892eb4e; feat:2995838076)
[2021-11-30T22:51:53.602174497Z INFO  solana_storage_bigtable::access_token] Requesting token for BigTableDataReadOnly scope
[2021-11-30T22:51:53.643941206Z INFO  solana_storage_bigtable::access_token] Token expires in 3599 seconds
BigTableError(ObjectCorrupt("Failed to deserialize: Invalid InstructionError: tx-by-addr/6XWjMSt9uMKfJ3bp6778NgVjhxXWZuTw73dRZ4QQNd3S/fffffffff9eeab87"))
```

**Comment by CriesofCarrots** [comment]
Looks like `InstructionError::IllegalOwner` was only added to one half of convert here: https://github.com/solana-labs/solana/commit/fcabaa7effe35cc80997401e60b5a79081e5e3dd

**Comment by moonrank** [comment]
You're amazing! Thank you!

The previous missing tx cases were just super weird, I'm not really sure what was going on there.

I documented one at the time:

https://twitter.com/MoonRankNFT/status/1449179291237842944?s=20

And you can see like... it returned 1 tx during the "time of weirdness" even though there were earlier tx's and later tx's.

This one took a couple of hours to return good data.

**Comment by CriesofCarrots** [comment]
> I documented one at the time:
> 
> https://twitter.com/MoonRankNFT/status/1449179291237842944?s=20

I'll take a look at those mints, although if they are returning fine now, I may not be able to suss out very much. If you see another example, can you please tag me here or on discord? Thanks @moonrank !

**Comment by moonrank** [comment]
@CriesofCarrots thank you!

I was just wondering... is there a way for me to replicate your (Solana dev) test setup? Is that documented somewhere?

Is there a way to do that without having to procure a big server with lots of RAM/storage etc?

I would love to be able to debug / gather repro for these issues when/if I hit them so I can provide more useful bug reports.

I feel like this would be especially useful for the ones that are transient.

Thanks again!

**Comment by CriesofCarrots** [comment]
@moonrank, the test command I ran required a read-only BigTable credential, so unfortunately it would only really be replicable if you were already running an rpc service.
But I'll take a look at rpc to see if there are improvements we can make in exposing BigTable errors. I think that would allow you to get a lot further in debugging, and help diagnose those transient issues!

**Comment by mattbraz** [comment]
I can add another example of this issue.
The below will query signatures for a very popular nft market, so we know it has many prior transactions.  Change the limit parameter below to 1, and you will get 1 signature returned, limit of 2 returns nothing.  This happens repeatedly on this account about every few days.  Hope this helps.

```
curl https://api.mainnet-beta.solana.com -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getSignaturesForAddress",
    "params": [
        "HZaWndaNWHFDd9Dhk5pqUUtsmoBCqzb1MLu3NAh1VX6B",
        {
            "limit":  2,
            "before": "3z3Lc6L8DXPRjmZr5Q5pXtbybddKv352ukjqzAcmHa6NzPJDJLrtPYXp5miGZpBGQrgZmqe2UqXK6sbA7zbHN7sE"
        }
    ]
  }
'
```

**Comment by CriesofCarrots** [comment]
@mattbraz , yes this is the same issue, fixed [here](https://github.com/solana-labs/solana/pull/21524) and shipped in v1.8.7

**Comment by moonrank** [comment]
@CriesofCarrots I was wondering if you (Solana) see this as s fix worth prioritising for deployment by mainnet participants?

I think I can attempt to convince Triton One to deploy this to staging servers at least... maybe. But it feels to me like missing txns would be of some importance.

**Comment by CriesofCarrots** [comment]
To be clear for posterity, transactions aren't missing; neither from the ledger nor from (BigTable) long-term tx history storage. This was a client bug causing BigTable read queries to exit early if a transaction had failed with a particular error.

@moonrank , v1.8.7 is cut. I expect that we will recommend it for mainnet-beta soon, although I don't think we'll rush that cluster upgrade for this issue. The release should be fine for RPC-provider staging servers and production testing now.

**Comment by moonrank** [comment]
@CriesofCarrots updated the comment. Apologies.

Thanks again for everything.

**Comment by brianlong** [comment]
Hi! We can install this on our staging servers for Moonrank to test & verify the fix.

**Comment by moonrank** [comment]
@CriesofCarrots currently seeing this issue on token `DREU5Pg2mbJiTJvs4XeHM4TR1MGcxD3hmHbU1uKArXxn`

It doesn't make much sense because... it's a fairly newish token and I would expect tx data to still be on local storage but... I guess it's the same issue.

https://solscan.io/token/DREU5Pg2mbJiTJvs4XeHM4TR1MGcxD3hmHbU1uKArXxn

Against our rpcpool.com endpoint:

```
curl https://moonrank.rpcpool.com/XXXXX/ -X POST -H "Content-Type: application/json" -d '
  {       
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getSignaturesForAddress",
    "params": [                         
      "DREU5Pg2mbJiTJvs4XeHM4TR1MGcxD3hmHbU1uKArXxn"
    ]                                               
  }
'
```

```
{"jsonrpc":"2.0","result":[],"id":1}
```

**Comment by moonrank** [comment]
Okay, so on the Triton staging server, it works:

```
curl https://stage.mainnet.rpcpool.com/XXXX/ -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getSignaturesForAddress",
    "params": [
      "DREU5Pg2mbJiTJvs4XeHM4TR1MGcxD3hmHbU1uKArXxn"
    ]
  }
'
```

```
{"jsonrpc":"2.0","result":[{"blockTime":1638382465,"confirmationStatus":"finalized","err":null,"memo":null,"signature":"Zp9bNZJUUUVPudXqcKMXFup2kJjqfen2rVkWCL4GP8h3Hj7eHA2thGr8fGzpJVs9nt9f8EZZ5H3xLnKkex4ecY3","slot":109605867},{"blockTime":1638382071,"confirmationStatus":"finalized","err":null,"memo":null,"signature":"3bVfwZY59nPxXeWJUpU9wH742N39RtfkkpjD5QJLVCgzxAT5W9ApCzYjGYvWhTb9RJ1xyfYTKEfStN6aLeoxNhhZ","slot":109605204},{"blockTime":1638368480,"confirmationStatus":"finalized","err":null,"memo":null,"signature":"237Rw3BabjLs4EnqbmVjZ1pnPHtxEWD3VkN6At5o3STPBRfPx2WS13JQEDnqTCShnbwcU32xAFUAJXrrGv4XHVzr","slot":109582967},{"blockTime":1638368154,"confirmationStatus":"finalized","err":null,"memo":null,"signature":"QEWXJriFp5ssQzFa4HxmCUTUe6P37YQqBpghcfUJyjvbg6oVeyS8qsCfgffTU5mQk6Thc6Zzz9WXsSc8gp2jybw","slot":109582433},{"blockTime":1638330320,"confirmationStatus":"finalized","err":null,"memo":null,"signature":"38Gx11m2WwbSCSXuE9rW6Y46qo7dLN7wWLpjkgjMFctXAR1EnSqEbr2KMBzcsvZ2k3wKzUsfivUfBPDLNTk32bp","slot":109514933},{"blockTime":1638326507,"confirmationStatus":"finalized","err":null,"memo":null,"signature":"5i37arjVpY87N62ERxpXDdxuWGhBbeTC34aXNutgqdPedLwXoFhAsugLbEv2bH3r3LaZegELvSVMFrtKCq2V9RCG","slot":109507888},{"blockTime":1638320267,"confirmationStatus":"finalized","err":null,"memo":null,"signature":"4zGTSLwZV4mPpzDXwLMMt9zoWSSkUvyMiinHW6UhboBexQoLoD1z8jD9XutvH9c4638fd7DuhRAfP1AtYqRef1B3","slot":109496371},{"blockTime":1638320211,"confirmationStatus":"finalized","err":null,"memo":null,"signature":"5mksS9sgaCLfbBQPLMYoKtyB4QkanjeAmsF2UtGbiMKtA3hTiNzdtes6MvggmpMTJ38Hib9dQbnFKZJmhxFaUwtX","slot":109496281},{"blockTime":1638248659,"confirmationStatus":"finalized","err":null,"memo":null,"signature":"49nCmYNBnQw8NMjmMchGN3TrY8Me7ap5JXaxJS7RNoirWzaemiKAcc6DvE5K5otqmJWByW8rZJLo251pZJaCVupV","slot":109371148},{"blockTime":1638247315,"confirmationStatus":"finalized","err":{"InstructionError":[1,"IllegalOwner"]},"memo":null,"signature":"4QjHZkp3Wvm63KDzsohtJ9LjR2tpEckjcYUTSb3vceVtCu3Xm7vV3siRpoo5pw7ja8HTfxD4FAivA6RxeSNXqXVv","slot":109368636},{"blockTime":1638243511,"confirmationStatus":"finalized","err":null,"memo":null,"signature":"SszAAQqUVV6YCkDV98r8BSShrz6R4349NwXgnSQ4r85CRbTc1Uh27WuGyAiF7B2HnnGhPabgcXe8N5j82hbUG4a","slot":109361634},{"blockTime":1638119560,"confirmationStatus":"finalized","err":null,"memo":null,"signature":"c4cHKXyT1hiERnn4TdDoXiXS8AfNgkhtAA6zwTVtr2vd3iLxRZB5xVUiHSxeZNtym3dwfjErYQdGjNhDcQGfTiK","slot":109142153}],"id":1}```

But... I don't understand why... because... 

```
curl https://stage.mainnet.rpcpool.com/XXXX/ -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getVersion",
    "params": [
    ]
  }
'
```

```{"jsonrpc":"2.0","result":{"feature-set":52865992,"solana-core":"1.8.5"},"id":1```

?

**Comment by brianlong** [comment]
I think our admins were upgrading the staging servers while you were running those tests above. Please try again ;-)

**Comment by moonrank** [comment]
@CriesofCarrots Triton deployed 1.8.7 onto the staging servers. It works for some tokens where 1.8.5 didn't.

However, there are still missing tx on like 8% of tokens. This is one example.

In this case, this token is being held by the Magic Eden escrow account. However, the token tx history only has the mint tx and is missing the `CreateAssociatedAccount` tx.

https://solscan.io/token/54Bpd49uvnPftX8wujQLNxr3SfEkJfu9Ds1Kf33ghhPu

```
curl https://stage.mainnet.rpcpool.com/XXXX/ -X POST -H "Content-Type: application/json" -d '
  {       
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getSignaturesForAddress",
    "params": [                         
      "54Bpd49uvnPftX8wujQLNxr3SfEkJfu9Ds1Kf33ghhPu"
    ]                                               
  }
'
```

```
{"jsonrpc":"2.0","result":[{"blockTime":1635368666,"confirmationStatus":"finalized","err":null,"memo":null,"signature":"5jZLWCZVzrFDJtPHkUG2bE6GpZiBZCxE8BL9ymRcFkJNxUutkWpk6569Hfp5FuUn58EekYXB6NP52ksYuqkyn4dK","slot":103846527}],"id":1}

```

Another token from the same set of tokens returns the correct data.

https://solscan.io/token/EDDPkWinLVD6JwFKCWc92UyMTRW9GMcNnZTGzpDcZsH

```
curl https://stage.mainnet.rpcpool.com/XXXX/ -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getSignaturesForAddress",
    "params": [
      "EDDPkWinLVD6JwFKCWc92UyMTRW9GMcNnZTGzpDcZsH"
    ]
  }
'
```

```
{"jsonrpc":"2.0","result":[{"blockTime":1635513552,"confirmationStatus":"finalized","err":null,"memo":null,"signature":"2My1TmR1c2Q6xBrReK3rVsdRRiJX7SJzT286CSL8pAGSoWGPtbHp34A57HsB12wpJfTmfxYYTjak5VzTk2hbVexZ","slot":104134896},{"blockTime":1635368747,"confirmationStatus":"finalized","err":null,"memo":null,"signature":"RrKiuY9vbeMbt2d5tUotpZnRjnSXAvH5ESsGRFF1gP6TqFogYsQQzt9X3hbv6jtwQqo4AtymzBWD3MD5UkBYx6R","slot":103846637}],"id":1}
```

So I guess this is an example of the "transient" issue in the wild... possibly.

**Comment by moonrank** [comment]
@CriesofCarrots one more data point, and it's that this token appears to have the right tx data being returned.

`6R9FcN2XWAE5eNDfntGENDB8bpJmgBUJmBGJdSuwaeK5`

https://explorer.solana.com/address/6R9FcN2XWAE5eNDfntGENDB8bpJmgBUJmBGJdSuwaeK5

https://magiceden.io/item-details/6R9FcN2XWAE5eNDfntGENDB8bpJmgBUJmBGJdSuwaeK5

I'm not really clear what the difference is.

**Comment by CriesofCarrots** [comment]
As we discussed on Discord, each of the  "missing" signatures refers to a transaction that is operating on a token account of a particular mint, but doesn't include that mint as one of the transaction's account keys. Currently, the node TransactionStatusService only indexes signatures by the account keys explicitly included in the transaction, so it is expected that these signatures will not appear in the signature list for the mint.

**Comment by moonrank** [comment]
@CriesofCarrots yeah.

I think there's still a very real issue with:

https://twitter.com/MoonRankNFT/status/1449179291237842944?s=20

But it's not any of the above. Definitely an oversight in the ME contract.

If I see that one specifically again, I'll open a new issue.

Thanks again for your attention to the original issue! :)
