### ISSUE TITLE
Hard Coded Max Genesis Archive Unpacked Size Is Problematic For Large Solana Test Validator Environments

### ISSUE THREAD

**Issue by bonedaddy** [solana-labs/solana#21452]
#### Problem

The [`MAX_GENESIS_ARCHIVE_UNPACKED_SIZE`](https://github.com/solana-labs/solana/blob/9b1bf98aa2c79482b619daa03e47eb3ee096ed41/runtime/src/hardened_unpack.rs#L46) is hard coded to 10MB.  When using `solana-test-validator` to clone a large number of accounts it is fairly trivial to surpass this 10MB limit.

For example I'm attempting to replicate a number of different raydium amms, serum markets, lending reserves, etc.. and ran into an issue with the test validator crashing on startup with a very uninformative error message `Error: failed to start validator: Failed to create ledger at .anchor/test-ledger: blockstore error`.

The source of the error which gets masked by error conversions, is:

```rust
Archive(
        "too large archive: 10533460 than limit: 10485760",
    )
```

Adjusting the hard coded limit to 100MB as a test caused the validator to no longer crash on startup.

Related: https://github.com/solana-labs/solana/issues/21440

#### Proposed Solution

* Increase the hard coded limit
* Allow overriding the hardcoded limit via feature flags
* Use a cli flag to override the limit for the test validator

**Comment by bmeeder22** [comment]
+1 Getting this issue after the solana-test-validator has been up for a little while. This gets manifested by a string of timeout errors: 
```
  RPC connection failure: error sending request for url (http://127.0.0.1:8899/)
Failed to get validator identity over RPC: error sending request for url (http://127.0.0.1:8899/): operation timed out
Failed to get validator identity over RPC: error sending request for url (http://127.0.0.1:8899/): operation timed out
```

Note that it works for ~1 min before the validator crashes.
