### ISSUE TITLE
Logging for compute unit consumption is noisy and unnecessary

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#21489]
#### Problem
The BPF Loader always logs the amount of compute units consumed after processing an instruction (either tx or cpi). However, this logging is noisy and can't be turned off by devs / api servers

#### Suggested Changes
Now that we have a syscall for reporting compute units, I think we should remove this log. That said, it's useful to browse the amount of compute used by programs so I think it would be nice to keep the compute units in the tx metadata (could add this as part of the fix for https://github.com/solana-labs/solana/issues/19467)

**Comment by jackcmay** [comment]
Adding it as part of the inner instruction reporting sounds good.  I've found it very useful when looking at failed txs where the developer may not be doing any additional compute budget logging themselves.
