### ISSUE TITLE
how to know who is leader right now ?

### ISSUE THREAD

**Issue by wade-liwei** [solana-labs/solana#21484]
hello 

I have a focused question:  
how does Verifier know who is the leader right now ? maybe you tell me Verifier maintain herself leader schedule from  ledger state at the start of the previous epoch.  but Verifier's clock is not leader's clock.

**Comment by Jacob-CG** [comment]
You can use [`getSlotLeader`](https://docs.solana.com/developing/clients/jsonrpc-api#getslotleader). For further support questions, feel free to join http://solana.com/discord and ask in **#developer-support**

**Comment by wade-liwei** [comment]
I have tried to join discord  with https://discord.com/invite/pquxPsq,
but discord prompt me: Unable to accept invite.

My discord account is: 923881393@qq.com

**Comment by wade-liwei** [comment]
@Jacob-CG 

If you can ,please add my another discord account into your chat group:  wade#4303
