### ISSUE TITLE
Adopt `reed-solomon-erasure` crate

### ISSUE THREAD

**Issue by Tirka** [solana-labs/solana#21491]
#### Problem
Recent changes to Cargo introduced breaking change which affects crate `reed-solomon-erasure` (`solana-ledger` depends on it)
Related issue: https://github.com/rust-lang/cargo/issues/10111

Fix already merged to master https://github.com/darrenldl/reed-solomon-erasure/pull/87, but crate owner has no interest in maintaining the `reed-solomon-erasure` crate and looking for a new crate owner https://github.com/darrenldl/reed-solomon-erasure/issues/88.

#### Question
Could you "adopt" this crate and publish a fixed version of it? :)

**Comment by steviez** [comment]
Hi @Tirka - incase you didn't see, some new owners were added (same thread that you linked above) and some new tags were published. I haven't verified myself, but thinking we're good here

**Comment by mvines** [comment]
yeah we've already updated to the new version of reed-solomon-erasure as well so this issue can be closed
