### ISSUE TITLE
Connection handler error: client has lagged behind (notification is gone)'

### ISSUE THREAD

**Issue by thaaddeus** [solana-labs/solana#21538]
Hi, I'm sometimes getting: `WARN  solana_rpc::rpc_pubsub_service] connection handler error: client has lagged behind (notification is gone)`. Are the any flags I could set when running RPC node that would make this issue disappear? Like increasing queue capacity or worker threads count for RPC node?

**Comment by t-nelson** [comment]
Hi!  We don't use Github for support.  Join us on https://solana.com/discord instead
