### ISSUE TITLE
Coins have lost from the wallet

### ISSUE THREAD

**Issue by Serg-Mois** [solana-labs/solana#21543]
#### Problem

Address CRi1GEdsxZZND8HDUmaStMzYqgnn2seMwKNqex9J5z1S 
https://solanabeach.io/address/CRi1GEdsxZZND8HDUmaStMzYqgnn2seMwKNqex9J5z1S

last transaction:
https://solanabeach.io/transaction/5RU9N1rkhWYCMQmFAqsSycRi6QP91NmvD6i1CMYb6HinWFniBp4iGp5WmJFyhyA4yDa2SQoxFq4YJvKjLfPVcX96

this address was deposited with 0.000001SOL, 
1. why change is -0.000001439SOL ?
 decreased balance after the deposit ( sounds strange ) - 0.000007422 SOL
2. why now the balance of this address is 0.

**Comment by t-nelson** [comment]
Hi! We don't use Github for support. Join us on https://solana.com/discord instead

tldr; rent. https://docs.solana.com/implemented-proposals/ed_overview/ed_storage_rent_economics
