### ISSUE TITLE
slot not synchronzing

### ISSUE THREAD

**Issue by tkdlqm2** [solana-labs/solana#21580]
#### Problem

I run a Solana full node. Until recently, slot synchronization was going well, but when I checked today, the slot synchronization was not working. When I check the log, there is no error related log. But there are some suspicious logs.

"[solana_core::replay_stage] Waiting to switch vote to 109731251, reseting to slot None for now"

The above log is continuously output, and if you check the number of slots, it stops at a specific slot.

**Comment by CriesofCarrots** [comment]
It sounds like you were on an old version of solana-validator software and got forked off on the epoch boundary due to a feature activation.
However, github is crummy for technical support. Please join us on discord: https://solana.com/discord #validator-support

**Comment by tkdlqm2** [comment]
@CriesofCarrots thank u sir

**Comment by CriesofCarrots** [comment]
Np, but not a sir
