### ISSUE TITLE
unable to start validator 

### ISSUE THREAD

**Issue by Merrick17** [solana-labs/solana#21606]
#### Problem
hello i'm currently trying to start a validator node on a server , following the documentation i made the system file as shown 
`[Unit]
Description=Solana Validator
After=network.target
Wants=solana-sys-tuner.service
StartLimitIntervalSec=0

[Service]
Type=simple
Restart=always
RestartSec=1
User=cmfirpc1
LimitNOFILE=1000000
#LogRateLimitIntervalSec=0
Environment="PATH=/bin:/usr/bin:/home/cmfirpc1/.local/share/solana/install/active_release/bin"
ExecStart=/home/cmfirpc1/bin/validator.sh

[Install]
WantedBy=multi-user.targe`  

and created a validator.sh file like shown bellow , 
` #!/bin/bash
 exec solana-validator \
  --identity ~/validator-keypair.json \
  --vote-account ~/vote-account-keypair.json \
  --rpc-port 8899 \
  --entrypoint entrypoint.mainnet-beta.solana.com:8001 \
  --limit-ledger-size \
  --log ~/solana-validator.log`
however i get the error , 
● sol.service - Solana Validator
     Loaded: loaded (/etc/systemd/system/sol.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Fri 2021-12-03 23:40:44 UTC; 375ms ago
    Process: 263114 ExecStart=/home/cmfirpc1/bin/validator.sh (code=exited, status=203/EXEC)
   Main PID: 263114 (code=exited, status=203/EXEC)

**Comment by Jacob-CG** [comment]
Hi! We don't use Github for support. Join us on https://solana.com/discord instead
