### ISSUE TITLE
Pubsub causes validator crash

### ISSUE THREAD

**Issue by RealAwesomeness** [solana-labs/solana#21608]
<img width="949" alt="image" src="https://user-images.githubusercontent.com/40503841/144695960-11cee9bd-4f88-4105-874d-566b1315ea70.png">
Not sure what causes this issue, but is inside the rpc subscription code and happened when I tried to add a pubsub subscription.

**Comment by CriesofCarrots** [comment]
Thanks for the report! This issue was already fixed here: https://github.com/solana-labs/solana/pull/21420
It is available in v1.8.6+ releases
