### ISSUE TITLE
Explorer: Feature request - Toggle local/UTC zoned timestamps on click

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#21642]
#### Problem

Timestamps in the explorer are displayed in UTC zone, which isn't the right tool for all jobs

#### Proposed Solution

Steal this toggle from buildkite
![Screenshot from 2021-12-06 13-52-50](https://user-images.githubusercontent.com/490004/144921596-808b6d98-d6e9-462e-a21d-fbd5221a4d80.png)

**Comment by lightyaer** [comment]
Hey @t-nelson, js dev here, seeking to work on this issue, let me know we need to fill in more details or I can start on it?

**Comment by t-nelson** [comment]
> Hey @t-nelson, js dev here, seeking to work on this issue, let me know we need to fill in more details or I can start on it?

Hey!  Thanks for taking interest in this request!  I can't think of anything else that needs added.  Feel free to take a crack at it!

**Comment by radupasparuga** [comment]
Gave it a try, here's the current progress on it
<img width="1680" alt="Screenshot 2022-01-20 at 22 59 42" src="https://user-images.githubusercontent.com/17007165/150421339-ceb03fad-e4d4-40f9-84eb-8089e9ce89b6.png">
