### ISSUE TITLE
simulate_transaction: Too many accounts provided

### ISSUE THREAD

**Issue by zfedoran** [solana-labs/solana#21655]
#### Problem
The transaction simulation logic does not check whether the simulation was successful before looking at the `post_simulation_accounts` length. This causes inaccurate errors to be returned. Specifically, if the simulation fails and accounts are requested, the RPC response is `Too many accounts provided; max {}` instead of the simulation error. The number of accounts provided was correct.

https://github.com/solana-labs/solana/blob/b8837c04ec3976c9c16d028fbee86f87823fb97f/rpc/src/rpc.rs#L3544

#### Proposed Solution
The simulation logic should check `result.is_err()` before returning `Too many accounts provided; max {}`.

**Comment by GenniferElla** [comment]
The recent BTC has fallen a lot, will it return to a higher position?
