### ISSUE TITLE
Inconsistent/bad API Response for getSignaturesForAddress when using "until"

### ISSUE THREAD

**Issue by WhoSoup** [solana-labs/solana#21660]
We ran into this issue when following along with transactions for a program. I managed to reproduce this error on the devnet using the public devnet cluster (1.8.5).

* Program ID: [EuK2ckS3ySzubPdPnsxko33LKQJm8vigiGQWbA6fMmFF](https://explorer.solana.com/address/EuK2ckS3ySzubPdPnsxko33LKQJm8vigiGQWbA6fMmFF?cluster=devnet)
* Most recent 4 transactions (according to the solana explorer): 
```
4YYrLsMCaiBpxB8NA7Mw4rqNpBrese33abWTtEP8N7wx5Da6fFWAicuRenHYiag7nUjfZ1D7SdXWFTthbRgHdPXZ (slot 99239125) 
PHYkUfoAkDEBaTSsXCgAf7oFb1EnhLUzn89vYgfpMsyNfwbWj9EZRbpsBZGNyzKos9s3KUDxHQY2cFDsQ5qUAUq (slot 99239125)
5zVUCw1BLsr3yRJvFFsGdg49zWdMqZzf2PWuD5yhWRgZGvgcFTb5zJGoXnreY8gzhbFecNukxV1y8o7w5Hzu7W1X (slot 99239124)
5ea72qSemhtER9hXxxfMuMiTBUmY3MhGzPZuxMpbQb4Q3Tc5ftauN6eynWgY1QBsn6nKcFnzswAWqr3kM7BwouZp (slot 99239108)
```

The problem happens when using the `until` flag in `getSignaturesForAddress`. If I run a request with an 'until' set to the most recent transaction, it returns the second most recent transaction, when it should be returning nothing. If I run a request with an 'until' for the second most recent transaction, it returns the most recent transaction, which works as expected. If I run a request with an 'until' for the third most recent transaction, it returns the two most recent ones with a duplicate copy of the most recent one, which is broken.

This error seems to be caused when multiple transactions happen in the same slot, though it seems to be inconsistent. The three transactions that are involved in the broken state also all have the same blocktime, though they are in two separate slots. All the transactions on the broken devnet state are finalized.

# Examples

## Querying the most recent signature

`curl https://api.devnet.solana.com -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":1, "method":"getSignaturesForAddress", "params": ["EuK2ckS3ySzubPdPnsxko33LKQJm8vigiGQWbA6fMmFF", {"until": "4YYrLsMCaiBpxB8NA7Mw4rqNpBrese33abWTtEP8N7wx5Da6fFWAicuRenHYiag7nUjfZ1D7SdXWFTthbRgHdPXZ"}]}'`

Response:
```json
{
  "jsonrpc": "2.0",
  "result": [
    {
      "blockTime": 1638862343,
      "confirmationStatus": "finalized",
      "err": null,
      "memo": null,
      "signature": "PHYkUfoAkDEBaTSsXCgAf7oFb1EnhLUzn89vYgfpMsyNfwbWj9EZRbpsBZGNyzKos9s3KUDxHQY2cFDsQ5qUAUq",
      "slot": 99239125
    }
  ],
  "id": 1
}
```

According to the explorer, signature `4YYrLsMCaiBpxB8NA7Mw4rqNpBrese33abWTtEP8N7wx5Da6fFWAicuRenHYiag7nUjfZ1D7SdXWFTthbRgHdPXZ` is the most recent signature, so the API should not return any results. This is the way it works for non-broken states.

## Querying the second most recent signature

`curl https://api.devnet.solana.com -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":1, "method":"getSignaturesForAddress", "params": ["EuK2ckS3ySzubPdPnsxko33LKQJm8vigiGQWbA6fMmFF", {"until": "PHYkUfoAkDEBaTSsXCgAf7oFb1EnhLUzn89vYgfpMsyNfwbWj9EZRbpsBZGNyzKos9s3KUDxHQY2cFDsQ5qUAUq"}]}'`

Response:
```json
{
  "jsonrpc": "2.0",
  "result": [
    {
      "blockTime": 1638862343,
      "confirmationStatus": "finalized",
      "err": null,
      "memo": null,
      "signature": "4YYrLsMCaiBpxB8NA7Mw4rqNpBrese33abWTtEP8N7wx5Da6fFWAicuRenHYiag7nUjfZ1D7SdXWFTthbRgHdPXZ",
      "slot": 99239125
    }
  ],
  "id": 1
}
```

This is the counterpart to the above. One of them has to be wrong.

## Querying the third most recent signature
`curl https://api.devnet.solana.com -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":1, "method":"getSignaturesForAddress", "params": ["EuK2ckS3ySzubPdPnsxko33LKQJm8vigiGQWbA6fMmFF", {"until": "5zVUCw1BLsr3yRJvFFsGdg49zWdMqZzf2PWuD5yhWRgZGvgcFTb5zJGoXnreY8gzhbFecNukxV1y8o7w5Hzu7W1X"}]}'`

Response:
```json
{
  "jsonrpc": "2.0",
  "result": [
    {
      "blockTime": 1638862343,
      "confirmationStatus": "finalized",
      "err": null,
      "memo": null,
      "signature": "4YYrLsMCaiBpxB8NA7Mw4rqNpBrese33abWTtEP8N7wx5Da6fFWAicuRenHYiag7nUjfZ1D7SdXWFTthbRgHdPXZ",
      "slot": 99239125
    },
    {
      "blockTime": 1638862343,
      "confirmationStatus": "finalized",
      "err": null,
      "memo": null,
      "signature": "PHYkUfoAkDEBaTSsXCgAf7oFb1EnhLUzn89vYgfpMsyNfwbWj9EZRbpsBZGNyzKos9s3KUDxHQY2cFDsQ5qUAUq",
      "slot": 99239125
    },
    {
      "blockTime": 1638862343,
      "confirmationStatus": "finalized",
      "err": null,
      "memo": null,
      "signature": "4YYrLsMCaiBpxB8NA7Mw4rqNpBrese33abWTtEP8N7wx5Da6fFWAicuRenHYiag7nUjfZ1D7SdXWFTthbRgHdPXZ",
      "slot": 99239125
    }
  ],
  "id": 1
}
```

It returns a duplicate transaction `4YYrLsMCaiBpxB8NA7Mw4rqNpBrese33abWTtEP8N7wx5Da6fFWAicuRenHYiag7nUjfZ1D7SdXWFTthbRgHdPXZ` which seems like an obvious error.

### Querying the fourth most recent transaction

`curl https://api.devnet.solana.com -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":1, "method":"getSignaturesForAddress", "params": ["EuK2ckS3ySzubPdPnsxko33LKQJm8vigiGQWbA6fMmFF", {"until": "5ea72qSemhtER9hXxxfMuMiTBUmY3MhGzPZuxMpbQb4Q3Tc5ftauN6eynWgY1QBsn6nKcFnzswAWqr3kM7BwouZp"}]}'`

Response:
```json
{
  "jsonrpc": "2.0",
  "result": [
    {
      "blockTime": 1638862343,
      "confirmationStatus": "finalized",
      "err": null,
      "memo": null,
      "signature": "4YYrLsMCaiBpxB8NA7Mw4rqNpBrese33abWTtEP8N7wx5Da6fFWAicuRenHYiag7nUjfZ1D7SdXWFTthbRgHdPXZ",
      "slot": 99239125
    },
    {
      "blockTime": 1638862343,
      "confirmationStatus": "finalized",
      "err": null,
      "memo": null,
      "signature": "PHYkUfoAkDEBaTSsXCgAf7oFb1EnhLUzn89vYgfpMsyNfwbWj9EZRbpsBZGNyzKos9s3KUDxHQY2cFDsQ5qUAUq",
      "slot": 99239125
    },
    {
      "blockTime": 1638862343,
      "confirmationStatus": "finalized",
      "err": null,
      "memo": null,
      "signature": "5zVUCw1BLsr3yRJvFFsGdg49zWdMqZzf2PWuD5yhWRgZGvgcFTb5zJGoXnreY8gzhbFecNukxV1y8o7w5Hzu7W1X",
      "slot": 99239124
    }
  ],
  "id": 1
}
```

This is the response that matches up with the order in the explorer and the order in which they were submitted.

If I use "limit" instead of "until" with values of 1, 2, and 3, it will return the correct response. This seems to be a problem specifically when using "until".

**Comment by xrzhuang** [comment]
no response on this? I am having this issue as well, seems like the API is not working as advertised, any solution around this?
