### ISSUE TITLE
solana rpc node not starting specific port 

### ISSUE THREAD

**Issue by Merrick17** [solana-labs/solana#21712]
#### Problem
when starting a new rpc node everything is working fine , exept that the port 8899 is not working , 
when i start netstat -l it's not showing 
#!/bin/bash
exec solana-validator \
  --identity ~/validator-keypair.json \
  --known-validator 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2 \
  --known-validator GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ \
  --known-validator DE1bawNcRJB9rVm3buyMVfr8mBEoyyu73NBovf2oXJsJ \
  --known-validator CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S \
  --only-known-rpc \
  --ledger /home/sol/workspace/ledger \
  --rpc-port 8899 \
  --private-rpc \
  --no-voting \
  --enable-rpc-transaction-history \
 --rpc-bind-address 127.0.0.1 \
  --dynamic-port-range 8000-8010 \
  --entrypoint entrypoint.mainnet-beta.solana.com:8001 \
  --entrypoint entrypoint2.mainnet-beta.solana.com:8001 \
  --entrypoint entrypoint3.mainnet-beta.solana.com:8001 \
  --entrypoint entrypoint4.mainnet-beta.solana.com:8001 \
  --entrypoint entrypoint5.mainnet-beta.solana.com:8001 \
  --expected-genesis-hash 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d \
  --wal-recovery-mode skip_any_corrupted_record \
  --limit-ledger-size 100000000
  --log ~/workspace/solana-validator.log
  
**ps : I already posted on discord but no one answered**

**Comment by t-nelson** [comment]
Hi!  We don't use Github for support.  Please join use in #validator-support on https://solana.com/discord
