### ISSUE TITLE
Same slot chicken and egg signature ordering headaches in getSignaturesForAddress

### ISSUE THREAD

**Issue by svenski123** [solana-labs/solana#21720]
#### Problem

For a single slot chicken and egg, whose signature comes first?

Query one signature before `3j7R...Xsw8` ...

`$ curl -s -H 'Content-Type: application/json' -d '{"id":1799, "jsonrpc": "2.0", "method": "getSignaturesForAddress", "params": ["BuL8cdu4PTo2WWPErd7efeKH196kZEY7TNQaDwDs9BSj", {"limit": 1, "commitment": "finalized", "before": "3j7RKfwZbYMJANihsS3tiVbyFc968b5NU4T4KZUq9N81UNj2EbQgVbExvC48e7Xu6kGJsNKt5VSgwuRJPxUxXsw8"}]}' https://api.mainnet-beta.solana.com`

and you get `4BqH...tSKu` (in slot 110,523,176):

`{"jsonrpc":"2.0","result":[{"blockTime":1638919668,"confirmationStatus":"finalized","err":null,"memo":null,"signature":"4BqHvPibL5EX4J1DaYbhh693i3Q7kns7PEWzrWbLksiDQUBuD1YQc4VZRpD6VLJemFRPAKJVinhaBZAz4ZGwtSKu","slot":110523176}],"id":1799}`

Query one signature before `4BqH...tSKu` ...

`$ curl -s -H 'Content-Type: application/json' -d '{"id":1799, "jsonrpc": "2.0", "method": "getSignaturesForAddress", "params": ["BuL8cdu4PTo2WWPErd7efeKH196kZEY7TNQaDwDs9BSj", {"limit": 1, "commitment": "finalized", "before": "4BqHvPibL5EX4J1DaYbhh693i3Q7kns7PEWzrWbLksiDQUBuD1YQc4VZRpD6VLJemFRPAKJVinhaBZAz4ZGwtSKu"}]}' https://api.mainnet-beta.solana.com`

and you get `3j7R...Xsw8` (in slot 110,523,176):

`{"jsonrpc":"2.0","result":[{"blockTime":1638919668,"confirmationStatus":"finalized","err":null,"memo":null,"signature":"3j7RKfwZbYMJANihsS3tiVbyFc968b5NU4T4KZUq9N81UNj2EbQgVbExvC48e7Xu6kGJsNKt5VSgwuRJPxUxXsw8","slot":110523176}],"id":1799}`

Note limit was set to one above for illustration - in production a data retrieval script went into an infinite loop when iteratively pulling signatures for an address until the most recent signature previously recorded using `before` and `until` as documented in the Solana JSON-RPC docs.

Query before `3j7R...Xsw8` until `b9r1...XA5t` and get:

`$ curl -s -H 'Content-Type: application/json' -d '{"id":1799, "jsonrpc": "2.0", "method": "getSignaturesForAddress", "params": ["BuL8cdu4PTo2WWPErd7efeKH196kZEY7TNQaDwDs9BSj", {"limit": 1000, "commitment": "finalized", "until": "b9r1EpMpPT7CzQxMbFyDBhfhLdcVEDgcwxYBM6VjRXU9EYCEHakBiJsA5DrjWMwEtaTMT73GHnxRTky8safXA5t", "before": "3j7RKfwZbYMJANihsS3tiVbyFc968b5NU4T4KZUq9N81UNj2EbQgVbExvC48e7Xu6kGJsNKt5VSgwuRJPxUxXsw8"}]}' https://api.mainnet-beta.solana.com`

`{"jsonrpc":"2.0","result":[{"blockTime":1638919668,"confirmationStatus":"finalized","err":null,"memo":null,"signature":"4BqHvPibL5EX4J1DaYbhh693i3Q7kns7PEWzrWbLksiDQUBuD1YQc4VZRpD6VLJemFRPAKJVinhaBZAz4ZGwtSKu","slot":110523176}],"id":1799}`

Last (and only) signature is `4BqH...tSKu` so query before `4BqH...tSKu` until `b9r1...XA5t` and get:

`$ curl -s -H 'Content-Type: application/json' -d '{"id":1799, "jsonrpc": "2.0", "method": "getSignaturesForAddress", "params": ["BuL8cdu4PTo2WWPErd7efeKH196kZEY7TNQaDwDs9BSj", {"limit": 1000, "commitment": "finalized", "until": "b9r1EpMpPT7CzQxMbFyDBhfhLdcVEDgcwxYBM6VjRXU9EYCEHakBiJsA5DrjWMwEtaTMT73GHnxRTky8safXA5t", "before": "4BqHvPibL5EX4J1DaYbhh693i3Q7kns7PEWzrWbLksiDQUBuD1YQc4VZRpD6VLJemFRPAKJVinhaBZAz4ZGwtSKu"}]}' https://api.mainnet-beta.solana.com`

`{"jsonrpc":"2.0","result":[{"blockTime":1638919668,"confirmationStatus":"finalized","err":null,"memo":null,"signature":"3j7RKfwZbYMJANihsS3tiVbyFc968b5NU4T4KZUq9N81UNj2EbQgVbExvC48e7Xu6kGJsNKt5VSgwuRJPxUxXsw8","slot":110523176},{"blockTime":1638919668,"confirmationStatus":"finalized","err":null,"memo":null,"signature":"4BqHvPibL5EX4J1DaYbhh693i3Q7kns7PEWzrWbLksiDQUBuD1YQc4VZRpD6VLJemFRPAKJVinhaBZAz4ZGwtSKu","slot":110523176}],"id":1799}`

Last signature is now back to `4BqH...tSKu` but `3j7R...Xsw8` is there now too - either way you never get an empty result (the next siganture before these two in slot 110,523,176 is actually the `until` signature `b9r1...XA5t`) and the loop never exits.

#### Proposed Solution

Querying the RPC endpoint should work correctly in the manner described in the docs and it doesn't currently in these edge cases.

Workarounds include remembering the questions you ask and the answers you receive and figuring out if the answers you've received are questions you've asked or answers you've received before - which is painful and might not work if you have `limit` or more transactions in a single slot.

Pulling the whole block for slots with multiple signatures and then applying the block's transaction ordering can work around the unclear signature ordering from the query.

As the RPC node can pull the block itself, perhaps it's feasible for it to reconstruct the ordering of transactions in the same slot as necessarty and cache it.

**Comment by bennofs** [comment]
Do you have another example where this happens? The one from the issue seems to be no longer working.
