### ISSUE TITLE
No cap on the number of accounts loaded in a transaction

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#21748]
#### Problem
Once versioned transactions are enabled and support up to 256 loaded accounts per transaction, transactions can lock a lot of accounts which can DOS on-chain programs.

#### Proposed Solution
Start with a reasonable cap on the number of accounts that an individual transaction can load until lock contention issues are solved in a more nuanced way.

**Comment by jstarry** [comment]
@jackcmay @sakridge @taozhu-chicago I'd like to discuss the above proposal to reduce the amount of damage that transactions can cause once they are able to load more accounts. Does this seem like a reasonable bandaid to start?

**Comment by taozhu-chicago** [comment]
What is max number of accounts current Transaction can have? Guess that could be the initial cap if we need one. 

Cost_model currently guesstimates cost for write-lock account in CU as a way to regulate write locks, maybe can do same for read-only accounts? Needs a better formula calculates write/read account CUs.

Also, cost_tracker currently tracks and limits number of transaction (to be precise, CUs) can be put on any single writeable account. We could also limit number of CUs on read-only account, if it does not add more complexity.

**Comment by t-nelson** [comment]
>
> What is max number of accounts current Transaction can have? Guess that
> could be the initial cap if we need one.
>
36

>

**Comment by jstarry** [comment]
> What is max number of accounts current Transaction can have? Guess that could be the initial cap if we need one.
> 36
> […](#)

It's actually 35 due to space required for metadata and at least one signature. I suggest we start with 70 to double the current max limit. This should satisfy the requests from on-chain protocols to use more accounts for now.

**Comment by t-nelson** [comment]
> It's actually 35 due to space required for metadata and at least one signature. I suggest we start with 70 to double the current max limit. This should satisfy the requests from on-chain protocols to use more accounts for now.

Ah right, the IX account indexes spill over :+1:
