### ISSUE TITLE
Increase stack size to 10kb

### ISSUE THREAD

**Issue by drewstone** [solana-labs/solana#21753]
#### Problem
I've learned that the stack size in Solana is 4KB large. Are there any hopes this will be increased? I have an hash funtion computation I'd like to execute which requires parameters that are 6-7KB. I cannot execute this hash function without these parameters. Is there are way other than increasing the stack to do so?

For background, there are a number of zkSNARK friendly hash functions that require pre-processed parameters to execute such as the Poseidon hash function. These are called friendly because zk-verification is cheap. I'm looking to build an application that leverages this hash function and Solana is the only chain that cannot do so.

#### Proposed Solution
Increase the stack size.

**Comment by mvines** [comment]
@jackcmay - weren't you proposing a stake size increase not too long ago?  I don't recall where that discussion ended up though

**Comment by jackcmay** [comment]
Ongoing conversation: https://github.com/solana-labs/solana/issues/13391

**Comment by mvines** [comment]
sg, closing this issue as a duplicate then
