### ISSUE TITLE
BPF no support for building and linking libraries (like a libc)

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#2178]
Depends on #2086

**Comment by jackcmay** [comment]
Not a simple quick fix and therefore won't be ready for Beacons, removing milestone.

**Comment by jackcmay** [comment]
BPF can now link in libraries into a single shared object.  @mvines , do you see this issue covering anything more than that?

**Comment by mvines** [comment]
Seems ok to me, this is your issue :)
