### ISSUE TITLE
Error while installing solana 

### ISSUE THREAD

**Issue by makarbaderko** [solana-labs/solana#21803]
#### Problem
macOS 10.15.7

Used commands:
curl https://release.solana.com/stable/install
sudo sh -c ./install 
*Then got*:
downloading stable installer
Error: Unable to download http://release.solana.com/stable/solana-release-x86_64-apple-darwin.yml: error sending request for url (http://release.solana.com/stable/solana-release-x86_64-apple-darwin.yml): operation timed out

**Comment by Jacob-CG** [comment]
We currently don't do tech support on Github. Please ask this question in #developer-support on our discord
https://solana.com/discord
