### ISSUE TITLE
Add possiblity to read program data on Solana explorer

### ISSUE THREAD

**Issue by AurelienFT** [solana-labs/solana#21814]
#### Problem

Currently on Solana programs are an opaque world for non-developers. If you ask for someone which don't know how to develop Solana program to **get data from a program they will probably not be able to do**. Except for tokens because there is some good RPC endpoints for that.

For others programs like DEX or farms it's **impossible to easily get data with a no-code solution**.

I think we can improve that.

What is the most used tools by the people that don't develop to read data on Solana ? **The Explorer**.

We need to be able to provide the informations trough the explorer.

#### Proposed Solution

My solution is inspired by **Etherscan** the most used explorer on Ethereum.

In Etherscan you are able to read some data about a smart contract by using their interface (example : https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7#readContract). We could add it to the Solana explorer also.

**How technically we could implement it ?**

My technical solution is inspired by the tokens informations.

The tokens informations are currently provided by a JSON which is updated often with new tokens.

My solution would be that each program could be able to give some helpers functions so that we can expose and call them and the explorer will have a generic way to call them.

The creator of the program need to create a directory (on his github repository or a special one like token-list don't know yet, need your advices (maybe in Solana github to review and avoid malicious JS code.)) with a standard architecture of file.

The important file in the folder would be a typescript file with the definitions of the functions to get data and a standard array to iterate and call them in the explorer : 

```typescript

interface Information {
    name: string;
    resolver: () => string;
}

const informations: Information[]  = [
    {
        name: "GetData",
        resolver: getData
    }
]

async function getData(): string {
    //Add more parsing
    return program.data;
}
```

In the explorer we could identify each contract by their address and then use their `informations` field (pseudo code):

```typescript
    return (
        {informations.map((information: Information) => {
            <Text onClick={() => information.resolver}>
                {information.name}
            </Text>
        })}
    )
```

With the display of the value after execution.

I want to implement an example with the hello-world program but there is problems that I need to solve : 

- Prevent malicious code (possible solution: centralize typescript file on a repository maintained by Solana)
- Include the typescript file (possible solution: add the main repository as submodule of the explorer and store each file on a folder with their address as a name)

I really need some feedback on this problems and the solution in global.

Thanks for reading.

**Comment by askibin** [comment]
I think this maybe not be a bad idea with some tuning. First of all, external repo with function definitions won't work. It should be stored on-chain along with a program. I think such methods could be marked with some attribute, like #[external], and bpf compiler could store it in a symbols area. Also, on-chain programs will soon be able to return the data. Combine all of the above with transaction simulation, and you should be able to have it similar to etherscan.

**Comment by AurelienFT** [comment]
Thanks for feedback ! I like the way with the procedural macro into the BPF but yes it's seems to be more long term.

**Comment by ngundotra** [comment]
Hey @AurelienFT, just pushed a change that exposes extra information about on-chain programs. I know its not as detailed as what you can find on etherscan, but hopefully it will help a little.

For example, here is Metaplex's program for NFTs: https://explorer.solana.com/address/cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ/anchor-program

**Comment by AurelienFT** [comment]
Very nice !
