### ISSUE TITLE
v1.9.0: vote-account ceased to exist after upgrade

### ISSUE THREAD

**Issue by agjell** [solana-labs/solana#21815]
I upgraded my testnet validator to v1.9.0 on Dec 11, 16:20 UTC. Shortly after the upgrade my validator went delinquent. It turns out my vote-account ceased to exist after the upgrade:
```
[2021-12-11T23:40:20.755873150Z ERROR solana_validator] vote account does not exist: B1PPUQyKFTsQMC3yy8tw16wkrZhZX4btdLS3s7KJFNT
```

I double checked it by running `solana vote-account [...]` and by pasting the pubkey in the Solana Explorer. The key was not identified as a vote account in either.

I'm part of the delegation program, so you can see that my voting history with that account goes back to epoch 197:
https://solana.foundation/sfdp-validators/4jhyvbBHbsRDF6och7pDQ7ahYTUr7wNkAYJTLLuMUtku

After re-creating it I got the validator working again, but all voting history seems to be lost.

(I know the officially recommended release was v1.8.5 at the time)

**Comment by agjell** [comment]
I remembered something else. The times when I tried to start the validator with the non-existing vote account, the Gossip and TPU address in `solana-validator monitor` came up as 127.0.0.1.

Could my issue have something to do with this commit? https://github.com/solana-labs/solana/commit/0e969015fcc03715e6c235e5e5f9edd209e0a00b

**Comment by CriesofCarrots** [comment]
That commit is a purely client-side (cli) change.
Have you been withdrawing from that vote account regularly? I'm wondering if the lamports dropped to zero through withdrawal or rent-collection.

**Comment by agjell** [comment]
Ah ok.
Yes I have. I withdrew from the account right after upgrading to v1.9.0, using the v1.9.0 CLI. I always use `ALL` when I withdraw, including this time, which has left the rent exempt minimum in the account. I suspect the rent exempt minimum was not left in the account on this occasion, however.

**Comment by CriesofCarrots** [comment]
Aha! Then it is related to that commit (https://github.com/solana-labs/solana/commit/0e969015fcc03715e6c235e5e5f9edd209e0a00b) after all.
In moving to common apis for resolving spend amounts, we lost this: https://github.com/solana-labs/solana/blame/f493a882588be8467998ef71ac6cb226683fd41a/cli/src/vote.rs#L964
Will revert the behavior change asap; will be fixed in v1.9.1

**Comment by agjell** [comment]
Oh, awesome! I'm very happy you found the cause. I've been pulling my hair out since it happened trying to find out what I did wrong. Thank you!

**Comment by mvines** [comment]
Oh yikes, nice find.
