### ISSUE TITLE
How to use the prompted <KEYPAIR> of a paper wallet

### ISSUE THREAD

**Issue by israel-gonzalezmedina** [solana-labs/solana#21831]
#### Problem
I am trying to use the  <KEYPAIR> of a paper wallet for use on Solana CLI. From the documentation it says:

In a paper wallet, the keypair is securely derived from the seed words and optional passphrase you entered when the wallet was created. To use a paper wallet keypair anywhere the <KEYPAIR> text is shown in examples or help documents, enter the uri scheme prompt:// and the program will prompt you to enter your seed words when you run the command.

To display the wallet address of a Paper Wallet:

      solana-keygen pubkey prompt://

I am using the above command, entering the  seed words and optional passphrase  and I am getting what is supposed to be the keypair:

       solana-keygen pubkey prompt://
       [pubkey recovery] seed phrase: 
       [pubkey recovery] If this seed phrase has an associated passphrase, enter it now. Otherwise, press ENTER to continue: 
       XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

however, whenever I use this supposed keypair and replace "KEYPAIR" field with the above value in any example I get

        Error: Dynamic program error: missing signature for supplied pubkey: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX

#### Proposed Solution

I expect the keypair generated by the prompt command for a paper wallet can be used in Solana cli commands. What I am doing wrong?

Thanks you in advance

**Comment by CriesofCarrots** [comment]
Most likely you are not providing keypairs everywhere that they are needed for the particular transaction. But I don't see an example of your failed command, so I'm not sure what transaction you are attempting. You can run `solana <SUBCOMMAND> --help` to see which parameters expect a signer.

Github is not ideal for tech support. Please join us on discord: https://solana.com/discord
