### ISSUE TITLE
IsBlockhashValid rpc call not working

### ISSUE THREAD

**Issue by Lazar955** [solana-labs/solana#21851]
#### Problem

The rpc call from [docs](https://docs.solana.com/developing/clients/jsonrpc-api#isblockhashvalid) fails with:
```json
{"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":45}
```

**Comment by CriesofCarrots** [comment]
Thanks. This rpc endpoint is new in v1.9.0, so it will not work against v1.8 clusters.
Working on updating the docs: https://github.com/solana-labs/solana/pull/21864
