### ISSUE TITLE
Tune block cost limits for mainnet-beta

### ISSUE THREAD

**Issue by taozhu-chicago** [solana-labs/solana#21917]
#### Problem

mainnet-beta has upgraded to 1.8.10, which reports BPF compute units to cost model, allows leader qos to estimated transactions' cost better. Block limits defined in `block_cost_limits.rs` should be tuned to align mainnet stats. 

The goal is to pack block as full as possible but not to dense so majority (66%?) of validators can replay it within a slot time.

#### mainet-beta data points
This [dashboard](https://metrics.solana.com:8889/sources/0/dashboards/3?refresh=Paused&tempVars%5Bdb%5D=%22mainnet-beta%22&tempVars%5Bprogram_id%5D=%27EzSXQ2BXf8m4y4jcQQGeZ6nnwXB3ARXP3YQ5SwjKLj82%27&tempVars%5Btime_threshold%5D=100000&lower=now%28%29%20-%2015m) collects cluster cost stats. Sample screenshot: 
<img width="1693" alt="Screen Shot 2021-12-14 at 7 59 46 AM" src="https://user-images.githubusercontent.com/82401714/146129777-805fc1cd-bdff-4278-92a1-3f62ecd0155c.png">
![image](https://user-images.githubusercontent.com/82401714/146133816-da5a26a8-0e28-4ad2-93ed-28f18db9b39e.png)

#### Notes
* why `stake` program takes so long to execute?

#### Proposed Parameters:

Given mainnet-beta average CU/us ratio is `30 CU/us`
Assume validator H/W support concurrent processes = 10;

Two perspectives to determine limits:
* If aim at overall cluster 500K TPS (with cheapest transactions), with 2.5 slot per sec, it's 500k/2.5 = 200k cheap transactions per block. If the cheap transaction has 2us execute time (eg 60 CUs), this block will be 200K * 2us = 400,000us. With CU/us rate defined early, units = 400,000us * 30CU/us = 12,000,000 CUs, per process. with concurrency, **Block_max=120,000,000 CUs**

* if aim at 2.5 slot per sec, eg a block time of 400ms, with CU/us ratio defined early, the units = 400ms * 30 CU/us = 12,000,000 CUs, per process, hence **Block_max=120,000,000 CUs**

**account_max** could be **block_max** without concurrency, hence **12,000,000 CUs**

With above limit, 
* Take vote has 70us execute time, a block can have up to 5,700 votes, 
* Take Raydium that has 1.4m CUs, a block can have up to 85 such transactions. 

#### Testing
* update testnet bench-dos test to send cheapest and most expensive transactions to check against the limits.
* Few data points to measure : tps, CU per Sec, block size, costliest account size, txs per block, replay time.

**Comment by taozhu-chicago** [comment]
@sakridge @jackcmay @aeyakovenko

**Comment by taozhu-chicago** [comment]
@jackcmay brought up this before: should sigverify be excluded from transaction cost, that leader uses to determine packing, since sigverify already happened before banking_stage. wdyt?

**Comment by taozhu-chicago** [comment]
From mainnet, the average block cost is 51,852,741 when account limit is (about) hit: 
![image](https://user-images.githubusercontent.com/82401714/146610052-635818c2-3340-432c-895a-392ecc173ecc.png)
This can be interpreted as cluster average concurrency rate = 51,852,741  / 15,000,000 ~= 3.5

and the acerage account max is

**Comment by jstarry** [comment]
>  This can be interpreted as cluster average concurrency rate = 51,852,741 / 15,000,000 ~= 3.5

I don't really follow why you're interpreting in this way. If you know average CU/us and you know average CU/block, can you use replay time to estimate concurrency?

**Comment by jstarry** [comment]
Also, I think the max compute limits should also take into account that execution is just part of transaction processing pipeline.. we also verify transactions and load and store accounts. So compute units should reflect that so we don't fill 400ms with compute and nothing left for other parts of processing.

**Comment by taozhu-chicago** [comment]
> > This can be interpreted as cluster average concurrency rate = 51,852,741 / 15,000,000 ~= 3.5
> 
> I don't really follow why you're interpreting in this way. If you know average CU/us and you know average CU/block, can you use replay time to estimate concurrency?

Fair, what "concurrency rate" really mean is not well defined. Roughly, it is number of concurrent leader threads that can run entirely independent from each other (no account dependency, for example). In a simplified scenario, each thread process TX for one account, so total block capacity would be each thread/account capacity multiply by number of threads. That interpretation is just a reverse of this.

**Comment by taozhu-chicago** [comment]
> Also, I think the max compute limits should also take into account that execution is just part of transaction processing pipeline.. we also verify transactions and load and store accounts. So compute units should reflect that so we don't fill 400ms with compute and nothing left for other parts of processing.

Not sure if necessary to do that. When cost model calculates transaction cost, all above mentioned parts are aggregated into CUs. Here we basically determines for 400ms block, how many CUs it can hold. When we start to add transactions to it with all costs considered, we'd know the fully packed block would took ~400ms to replay/execute.

**Comment by jstarry** [comment]
> Fair, what "concurrency rate" really mean is not well defined. Roughly, it is number of concurrent leader threads that can run entirely independent from each other (no account dependency, for example). In a simplified scenario, each thread process TX for one account, so total block capacity would be each thread/account capacity multiply by number of threads. That interpretation is just a reverse of this.

I think what matters more is how much replayers can concurrently process transactions though right? We're trying to ensure that replay times remain low. What you're talking about is different, because each banking thread is trying to produce entries that are parallizable

**Comment by jstarry** [comment]
> > Also, I think the max compute limits should also take into account that execution is just part of transaction processing pipeline.. we also verify transactions and load and store accounts. So compute units should reflect that so we don't fill 400ms with compute and nothing left for other parts of processing.
> 
> Not sure if necessary to do that. When cost model calculates transaction cost, all above mentioned parts are aggregated into CUs. Here we basically determines for 400ms block, how many CUs it can hold. When we start to add transactions to it with all costs considered, we'd know the fully packed block would took ~400ms to replay/execute.

How is account loading and committing included in CU's besides just having a fixed byte cost? It's not incorporated in the timings because those are just execution, which is my point.

**Comment by taozhu-chicago** [comment]
> 

Perhaps it's two sides of same coin - the concurrency set on leaders side should matches the capacity on replay side. After all, the main purpose of all this is to make sure block produced can be replayed within a slot time. 
But I can see how it could be intuitive by casting it under replay stage lights.

**Comment by taozhu-chicago** [comment]
> > > Also, I think the max compute limits should also take into account that execution is just part of transaction processing pipeline.. we also verify transactions and load and store accounts. So compute units should reflect that so we don't fill 400ms with compute and nothing left for other parts of processing.
> > 
> > 
> > Not sure if necessary to do that. When cost model calculates transaction cost, all above mentioned parts are aggregated into CUs. Here we basically determines for 400ms block, how many CUs it can hold. When we start to add transactions to it with all costs considered, we'd know the fully packed block would took ~400ms to replay/execute.
> 
> How is account loading and committing included in CU's besides just having a fixed byte cost? It's not incorporated in the timings because those are just execution, which is my point.

Maybe I misunderstood, my point is here we are defining a block can have up to 400ms CPU time (or XYZ CUs, per conversion rate). We dont really care about what that 400ms, or CUs, are for; It is just a fixed block capacity we wanted. When leader adds transactions to block, the cost associated with transaction, including accounts, data, and execution will reduce block available capacity. In another words, the 400ms includes execution as well as other costs. I think that is your point, is it?

**Comment by sakridge** [comment]
> @jackcmay brought up this before: should sigverify be excluded from transaction cost, that leader uses to determine packing, since sigverify already happened before banking_stage. wdyt?

It adds work to the validator to replay the block, I don't see why it should be excluded.

**Comment by jackcmay** [comment]
> > @jackcmay brought up this before: should sigverify be excluded from transaction cost, that leader uses to determine packing, since sigverify already happened before banking_stage. wdyt?
> 
> It adds work to the validator to replay the block, I don't see why it should be excluded.

Agreed that during reply the cost of the signature should be included in the block cost.

**Comment by taozhu-chicago** [comment]
cost limits defined in `runtime/src/block_cost_limits.rs` are currently stable. Limits can be adjusted after major changes to TPU or TVU, until then, it is better to stay as is
