### ISSUE TITLE
Provide standard C++ library binaries in SBF tools

### ISSUE THREAD

**Issue by dmakarov** [solana-labs/solana#21930]
#### Problem

SBF C++ toolchain doesn't include a standard C++ library for on-chain developers to use. This severely limits the development of on-chain programs in C++.

#### Proposed Solution

Provide a restricted version of C++ STL library that doesn't contain global variables. Include the library binary and header files in SBF tools distribution package.

**Comment by OluAgunloye** [comment]
Hello. Any updates on this?

**Comment by OluAgunloye** [comment]
Are there any specific issues or blockers that I (and my team) can be of assistance for? We're particularly interested in getting this feature-set up and running. @dmakarov

**Comment by dmakarov** [comment]
C++ STL library in general relies on global static variables. The Solana run-time is based on BPF virtual machine which doesn't allow programs to use non-readonly global data. This makes it unfeasible to compile a C++ STL to BPF with the goal of linking it to executable on-chain programs. Such programs won't run on our VM.
