### ISSUE TITLE
Discord link doesn't work

### ISSUE THREAD

**Issue by yglukhov** [solana-labs/solana#21956]
The discord link (https://discordapp.com/invite/pquxPsq) on solana.com doesn't work: "Whoops... Unable to accept invite.", for about a month now. Is the project abandoned? 🤔

**Comment by steviez** [comment]
Hi @yglukhov - The project definitely isn't abandoned; we use it daily and I was also able to make a second account just now in a second browser so it is allowing new members.

Just some basic troubleshooting stuff:
- Are you using the mobile app or web app? Have you tried using the other if you have only tried one of these?
- Have you tried in a private/incognito window, or a different browser? Can you maybe try clearing browser cache/settings too if you haven't already?
- Some ideas from [this article](https://unitopten.com/discord-whoops-unable-to-accept-invite/) I found searching your error on the web:
    - Do you already have a Discord account and if so, are you possibly at the server limit (100) already?
    - Can you try from another network incase your IP is being flagged?

**Comment by yglukhov** [comment]
> Can you try from another network incase your IP is being flagged?

That did the trick, thank you. Was trying previously from all sorts of browsers and devices, to no avail. Never considered my ip could be flagged.

**Comment by yglukhov** [comment]
However a bit later in the onboarding process discord suggests I'm banned from this guild. Is there any fix for this?

**Comment by steviez** [comment]
Is this you: `yglukhov#0068`? If so, I see a log of you getting in at 19:21 UTC time today, and no log of you being automatically banned or anything. Are you able to see any of the channels?

**Comment by yglukhov** [comment]
That's me. Strange, now it doesn't say I'm banned, but I'm seeing only `guidelines`, `roles` and `foundation-announcements` channels. Is that what I'm supposed to see?

**Comment by yglukhov** [comment]
My bad, I've picked a role and now it's working. Sorry for the noise.
