### ISSUE TITLE
Use program upgrade authority for buffer authority 

### ISSUE THREAD

**Issue by SebastianBor** [solana-labs/solana#21993]
#### Problem
When deploying program using `buffer solana program write-buffer` the buffer's authority is set by default to the current configured keypair.

It's convenient when the current keypair is also the program's upgrade authority but if the authority is different then it has to be manually specified and it is a common source of errors where the authority over the buffer is irrevocably lost. 

The common scenario when the authority is different is with a multisig solution like `spl_governance` is used to control programs upgrades through PDA.

#### Proposed Solution
Add a flag to fetch the program's upgrade authority and use it as the buffer authority
`--use-authority-of-program PROGRAM_ID`

**Comment by askibin** [comment]
write-buffer accepts this argument:
`--buffer-authority <BUFFER_AUTHORITY_SIGNER>    Buffer authority [default: the default configured keypair]`
and current program authority can be fetched with
`solana program show [prog address] | grep Authority | cut -d' ' -f2`
so theoretically you can build a single command, but for some reason --buffer-authority doesn't work for me and I have to set authority explicitly, not sure if it is a bug or I misunderstood the purpose of the argument

**Comment by CriesofCarrots** [comment]
Incidentally, I surmise that you were hitting the same issue as https://github.com/solana-labs/solana/issues/17890, fixed in https://github.com/solana-labs/solana/pull/29476
