### ISSUE TITLE
Solana Documentation Bug

### ISSUE THREAD

**Issue by brianlmacdonald** [solana-labs/solana#22007]
#### Problem
Hey - I can't fid the website repo so i'm putting this here - 

The slider for https://solana.com/developers isn't working and walkthrough links are getting cut off and unreachable on smaller window sizes. Feel free to move this issue to the right place and close it.

**Comment by jacobcreech** [comment]
@brianlmacdonald Thanks for the issue. I believe this has been since fixed. Feel free to comment if not
