### ISSUE TITLE
Program Closure Leads To Inability To Reuse ProgramID

### ISSUE THREAD

**Issue by bonedaddy** [solana-labs/solana#22005]
#### Problem

Recently the ability to close program accounts was introduced, allowing one to reclaim the lamports used to deploy a program. Iirc one of the selling points was being able to upgrade the program data account to support a large size.

This is not the case, and attempting to deploy to the programId after closing the programData account gives the following error

```
has been closed, use a new Program Id
```

I'm unaware of this functionality being documented, and if this is intended function i'd recommend documenting it. Staging program and funds locked inside are now bricked due to inability to reuse the programid.

#### Proposed Solution

* Allow reusing the programId
* If programId reuse is not allowed, display a clear warning that this will happen, or prevent closing all together if 1 or more program accounts exist

**Comment by justinkook** [comment]
Yes, I would like the ability to reopen closed program Ids to be able to have cross network usability for programs. Once devnet programs are closed, then devnet is no longer an option until you switch programIds.

**Comment by eydelrivero** [comment]
Is there any updates on this issue or any workaround to increase the program's data account size after reaching the limit?

**Comment by danout** [comment]
and if you check the balance of the closed program account, you may find a small amount of sol which can never be reclaimed, which is also anoying.

**Comment by pentameal** [comment]
Hi Solana Labs, 

OptiFi run into the same issue, is there any way to help resolve users' fund? 

https://twitter.com/OptifiLabs/status/1564367455220219904

**Comment by terorie** [comment]
@bonedaddy @justinkook @eydelrivero @pentameal Please see #27460 for a feature proposal resolving this issue
