### ISSUE TITLE
Stable release channel version not listed on Releases

### ISSUE THREAD

**Issue by epomatti** [solana-labs/solana#22014]
#### Problem

When installing from the stable channel I'm getting a version that doesn't exist in the releases. Why?

```sh
$ sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
$ solana --version
output: solana-cli 1.8.12 (src:ddef1563; feat:1006352700)
```

There are no **"v1.8.12"** on the tags.

![image](https://user-images.githubusercontent.com/6530769/146698452-de7e7ba3-2037-40a7-a2f6-c518924fdbd3.png)

If try to install it directly with https://release.solana.com/v1.8.12/install it fails.

**Comment by mvines** [comment]
v1.8.12 will the the next release version in the v1.8 release branch, so what you are reporting is normal.  The stable channel is the latest code on v1.8 release branch, which is currently somewhere between the latest v1.8.11 release and the future v1.8.12 release

**Comment by epomatti** [comment]
I'll stick with the release tags in this case. tx
