### ISSUE TITLE
BanksServer doesn't simulate transactions

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#22029]
#### Problem
BanksServer::process_transaction_with_commitment_and_context() hands off a transaction to a Bank for processing, and then polls for the committed result:
https://github.com/solana-labs/solana/blob/b8eff3456c50558736fe2f3caea4ab98e0fc6370/banks-server/src/banks_server.rs#L268

This works fine for transactions that get committed to the Bank (successful, or instruction errors), but is clunky or confusing in other cases.

For instance, if a client submits two identical transactions, the first of which lands successfully, the second one will also return success because the polling finds the original signature status.

In other cases, the transaction will not be committed, but the polling will continue until the client-provided timeout is reached (default in BanksClient::process_transaction_with_commitment() 50s).

#### Proposed Solution

Add a BanksServer method that takes a config to opt-in for transaction simulation on the locked Bank before processing is attempted, and propagates simulation errors back to the client.

cc @joncinque

**Comment by joncinque** [comment]
The fix for this should also address #17133 and #15795

**Comment by CriesofCarrots** [comment]
#22084 does fix #15795, but #17133 actually seems to be this issue: https://github.com/solana-labs/solana/blob/57986f982a823670adb68ef24b2f77486a8d09c1/program-test/src/lib.rs#L636
