### ISSUE TITLE
web3.js changes writability of accounts

### ISSUE THREAD

**Issue by ptaffet** [solana-labs/solana#22021]
#### Problem
If you create a transaction with multiple instructions that use the same account, but in one instruction the account is not writable and in another it is, then upon serialization, all get converted to writable.

Here's a simple reproducer:
```ts
import {
    PublicKey,
    TransactionInstruction,
    Keypair,
    SYSVAR_RENT_PUBKEY,
    Transaction,
  } from "@solana/web3.js";

let samplePubkey = new PublicKey('So11111111111111111111111111111111111111112');
let feePayer = Keypair.generate();

const transaction = new Transaction();
transaction.recentBlockhash = 'hx1X81qfzypoX2HUg1HdYCprZZkzxst9bAzpyh6pZfb';
transaction.add(new TransactionInstruction({
    programId: SYSVAR_RENT_PUBKEY, // Doesn't matter, can be any program
    keys: [ {pubkey: samplePubkey, isSigner: false, isWritable: false} ]
}));
transaction.add(new TransactionInstruction({
    programId: SYSVAR_RENT_PUBKEY,
    keys: [ {pubkey: samplePubkey, isSigner: false, isWritable: true} ]
}));
transaction.feePayer = feePayer.publicKey;
transaction.sign(feePayer);
console.log("Before serialization:")
transaction.instructions.map(function (ix) { console.log("Is writable: " + ix.keys[0].isWritable); });

let buffer = transaction.serialize();
let tx2 = Transaction.from(buffer);

console.log("After serialization:")
tx2.instructions.map(function (ix) { console.log("Is writable: " + ix.keys[0].isWritable); });
```

This is causing problems with a program that is very picky about which accounts are writable and which are not.

Potentially related to #21722

#### Proposed Solution
Based on Solana's transaction encoding, it seems like this is a bit of a pain to fix, but it seems like a bug to me still.

**Comment by jordansexton** [comment]
This (in itself) isn't a bug. `Message`, which `Transaction.from` uses, [doesn't have information](https://github.com/solana-labs/solana/issues/21722#issuecomment-1067397222) on the writable flags of each instruction. If an account is writable for any instruction, it's writable for all instructions in the same transaction.
