### ISSUE TITLE
Consider switching to faster compression & decompression format for rocksdb inside snapshots

### ISSUE THREAD

**Issue by buffalu** [solana-labs/solana#22034]
#### Problem
Unpacking rocksdb from snapshot takes foreverrrr. It's stored as bz2, which seems to be one of the better compression algorithms from storage size but not performance side.

https://serverfault.com/questions/872749/bzip2-too-slow-multiple-cores-are-avaible

Using `lbzip2` helps, but still seems to be compute limited and not storage bandwidth limited.

#### Proposed Solution
Consider using a faster compression and decompression algorithm.

**Comment by steviez** [comment]
Some discussion here: https://discord.com/channels/428295358100013066/885976714646290473/922595223199162368

**Comment by buffalu** [comment]
computer setup:
us-west2-a
c2-standard-16
8 NVME SSDs in RAID 0

~1 hour to download from storage bucket (IO limited i believe, was seeing ~8G/s)

.tar.bz2 -> .tar
hour later after running lbzip2, it's finally done. 
sitting at 505G with tar.bz2 and 862G with .tar.

.tar -> rocksdb/
on untar, running ~1G/s diskio read and about the same on write.
~20-30 minutes and finally done. 862G after tar.

**Comment by buffalu** [comment]
another thing that would be nice is storing the genesis.bin in the snapshots to make it easier to get going

**Comment by mvines** [comment]
genesis.bin never changes so encoding it in every snapshot doesn't seem great

**Comment by willhickey** [comment]
You might already be doing this, but the decompress and untar can be combined:
tar -I lbzip2 -xf rocksdb.tar.bz2

The increased storage cost associated with using a faster compression is not insignificant. Back of the envelope math: switching to gzip would cost an extra $15k/yr/yr to store the ledger (compared to current compression). That $15k grows as the ledger grows, and will likely grow faster than linear (as adoption increases)

I'm curious if uncompressing snapshots is part of a regular workflow? (I only do it sporadically, but I'm still a Solana newb :-)

**Comment by buffalu** [comment]
> You might already be doing this, but the decompress and untar can be combined: tar -I lbzip2 -xf rocksdb.tar.bz2
> 
> The increased storage cost associated with using a faster compression is not insignificant. Back of the envelope math: switching to gzip would cost an extra $15k/yr/yr to store the ledger (compared to current compression). That $15k grows as the ledger grows, and will likely grow faster than linear (as adoption increases)
> 
> I'm curious if uncompressing snapshots is part of a regular workflow? (I only do it sporadically, but I'm still a Solana newb :-)

haha thanks for reply! 

for our background: we want to index the old data all to gather stats. have a feeling the storage costs to store account state at every slot (and multiple times w/in each slot) would be massive. 

w were then thinking we could just load + replay state on demand, but then run into the time it takes to unpack the snapshots + rocksdb, so then came here :)

will think a little more of the best way to do this

**Comment by steviez** [comment]
>You might already be doing this, but the decompress and untar can be combined:
tar -I lbzip2 -xf rocksdb.tar.bz2

Posting here in case others might benefit - I like using [pv](https://man7.org/linux/man-pages/man1/pv.1.html) as well to get a progress bar. The complete command + progress bar would then look like:
```
$ pv rocksdb.tar.bz2 | tar -x -I lbzip2 -C ~/ledger/
 105GiB 0:10:02 [ 196MiB/s] [====================>  <I removed extra spaces here>   ] 16% ETA 0:50:35
```

**Comment by steviez** [comment]
I benched several compression algorithms this week on the `rocksdb` folder from the epoch 287 backup; findings are screen-shotted from [this document](https://docs.google.com/spreadsheets/d/1duT1hN00hetmbl-v-AgAnrqdTj6Xxl5uPSu9D84AjPU/edit#gid=0):

<img width="1061" alt="image" src="https://user-images.githubusercontent.com/5400107/158886767-0c4186ec-7a3f-4a49-81dd-2ced9220243c.png">

Here are the algorithms ranked best to worst in the 3 categories we'd care about. Note that I'm using lbzip2 with 16 threads; the parallelization allows it to compete with other algorithms, but the CPU cost can't be ignored:
Compressed Size: zstd / lbzip2 / lz4
Compression Speed: lz4 / lbzip2 / zstd
Decompression Speed: zstd / lz4 / lbzip2

Off the bat, I think we can rule out `bzip2` / `lbzip2` in favor `zstd`:
- `zstd` compressed to a smaller file
- `lbzip2` required 16 threads to barely beat `zstd` out in compression time
- `zstd` destroyed `lbzip2` in decompression time; `lbzip2` would probably need `> 32` threads to compete here

Between `zstd` and `lz4`:
- `zstd` compressed 9% smaller from original size than `lz4`
- `lz4` compressed much quicker (1 hour less); however, factoring in the extra time to upload, that difference is down to 45 minu
- `zstd` decompressed quicker which gives a boost for people actually downloading + consuming these

I'm no sure what the cost is per GB on the Google buckets, but the extra 9% (100 GB) is non-trivial. Based on the findings on this sample, I think we should go with `zstd`. We have a little extra time on the upload (one time cost), but this is already a somewhat large number with the upload time. But, we get savings on the download case (for people that consume these). Thoughts @yhchiang-sol @joeaba ?

**Comment by joeaba** [comment]
I think going with zstd is a no brainer, fast enough and the compression will save us some cash.
Thanks for the hustle!

**Comment by t-nelson** [comment]
Did you try playing with compression levels at all?  looks like `zstd` defaults to 3/19, `lz4` 1/12.  `zstd` also support multithreading

**Comment by steviez** [comment]
> Did you try playing with compression levels at all? looks like `zstd` defaults to 3/19, `lz4` 1/12. `zstd` also support multithreading

Thank you, good tips! Let me try a few more combos:
- `zstd` with mutliple threads
- `zstd` and `lz4` with some different compression levels; the CLI's have benchmark arguments to try different levels so I can kick this off with minimal intervention

**Comment by steviez** [comment]
Summary from a few more tests (results in the [same sheet](https://docs.google.com/spreadsheets/d/1duT1hN00hetmbl-v-AgAnrqdTj6Xxl5uPSu9D84AjPU/edit#gid=0)):
- Multithreading `zstd` gave near linear improvement in compression rate with 4 threads (might have been actually linear if IO limit not hit)
- Increasing `zstd` compression level from 3/19 default yielded marginal improvement
   - 4/19 gave 0.8% compressed size improvment with ~25% degradation in compression rate (could compensate with extra thread) over 3/19
   - 6/19 gave 1.6% compressed size improvment with with ~80% degradation in compression rate (probably too many threads to try to compensate) over 3/19
- Increasing `lz4` compression size had marginal gains on compressed size with major hits to compression rate

So, I think `zstd` is still our winner with minimal compressed file size and being able to match `lz4`'s compression rate with small number of threads.

Sample commands might be:
```
# Compress (if fast drives, potentially could add few more threads to shave some time)
$ tar cf rocksdb.tar.zst rocksdb -I "zstd -T4"

# Decompress (T4 likely sufficient to hit IO limit since decompress faster)
$ tar xf rocksdb.tar.zst -C ~/some/ledger/dir/ -I "zstd -T4"

# Decompress with ASCII progress bar
$ pv rocksdb.tar.zst | tar -x -C ~/some/ledger/dir/ -I "zstd -T4"
```

@joeaba - let's close this issue once the ledger backup nodes have been updated to use `zstd`

**Comment by axleiro** [comment]
Yeah thanks! They are already using zstd, I'll change them to zstd -T4 now.
