### ISSUE TITLE
Proposal for spam protection against unwanted accounts/NFTs

### ISSUE THREAD

**Issue by zfedoran** [solana-labs/solana#22063]
#### Problem

At the moment it is possible for a malicious spammer or advertiser to subsidize and create token accounts followed by a transfer of unwanted token(s) to publicly known addresses. Valuable or vulnerable public addresses can easily be found through the domain resolution program, or twitter handles, or listings / NFT sales on popular exchanges, etc...

Once affected, the receiving account holder would then need to either: **A)** spend SOL to remove spam or **B)** create a new account and spend SOL to move existing assets or **C)** accept that there will be unwanted items or ads in their publicly visible account. Additionally, if perusing option B), extra burden is placed on the account holder to not reveal the new public address of the account holder in order to protect themselves from subsequent spam transfers (for example, the new ZK token work). Additionally, if a `.sol` domain points at the public key, then none of these are very effective anyway. 

Another consideration for corporate identities will be that of brand safety on public accounts. 

No one wants to see unwanted NFTs in their account asking to send SOL to an address or face further inappropriate material landing in the account.

#### Proposed Solution

A mechanism to mark an account as read-only for creation of new spl-token accounts without limiting the ability to send or receive tokens on accounts that already exist. This could be implemented as a boolean toggle instruction that requires the signature of the owner.

Alternately, an account level whitelist or blacklist approach would work as well.

If a solution already exists, please comment and I'll gladly close this proposal.

**Comment by pepeneif** [comment]
Maybe just by making the sender to pay for the rent fee to a new account created will be enough to deter the spammers.

**Comment by zfedoran** [comment]
> Maybe just by making the sender to pay for the rent fee to a new account created will be enough to deter the spammers.

This is already the case. The sender are subsidizing the accounts with rent exemption in mind. This isn’t deterring spammers. As an example, you’d typically expect to pay more on Google or Facebook per ad impression than on Solana for a rent exempt token account. Also, when considering brand safety, the rent exemption fees would need to be in the hundreds of dollars to even begin to deter a targeted campaign.

Fees for rent exemption are expected to be lower with release 1.9.

**Comment by Arrowana** [comment]
@zfedoran When you receive a spam token you can burn it and close the token account, thus making `0.00203928 (rent) - 0.000005
 = 0.002 SOL = 0.36$`. I am pretty sure this is magnitudes more expensive than any ad out there per impression, on top of that the user gets money!

The proposed solution doesn't work, the ad mint isn't known beforehand so a read only account cannot be created for those.

**Comment by mvines** [comment]
Most wallets don't support burning tokens/NFTs at the moment, leading people to do desperate things like sending their unwanted NTFs to other addresses like the System Program or the Incinerator. However this is not a core protocol issue, users should raise this issue with their wallet of choice to add token burn support.  I don't see any action required in this repo, so closing the issue.

**Comment by zfedoran** [comment]
First, thank you for the feedback guys. I appreciate the time taken for reviewing this and I'm okay leaving this closed as there doesn't seem to be support for this proposal at the moment. I understand it would require a ton of changes.  

@Arrowana you're correct. However, as Mike has mentioned the wallet support is inadequate at the moment. Specifically, a crafty spammer would likely snipe the rent back unless you put it all into a single transaction. For example, the spammer will likely watch the accounts for changes and get their funds back due to having close authority on the token account. Also, the current 0.36 fee is not exponentially higher, especially considering we're not talking single impressions. Additionally, we're already seeing organizations that have factored in the net gains/losses for subsidizing token accounts.

@mvines I hear you and do agree but I'm not sure how this addresses brand safety. The owner of the public address does not have control over how the account is viewed. For example, Adidas would not want Nike tokens on their public .sol domain. There are many other things that could be inappropriate for a public facing address to display and leaving it to the client side seems insufficient if the owner of the public domain wants control over what should be displayed.

Additionally, as others have asked, there is no good "blocking" mechanism in place for building things like twitter clones.

I guess lets watch and see if demand for this comes back in the future.

Thanks!

**Comment by t-nelson** [comment]
This behavior isn't unique to solana or even cryptocurrencies.  Anyone can deposit into your bank account, call your telephone, send you mail, etc.  It's simply not the problem we're trying to solve.

Further, it can't be solved generically in the runtime (this repository) as program data is opaque at that level.  It _could_ be added to the token program (not this repository), but that would likely be a net negative on the ecosystem as it would detract from composability, break assumptions that are made by popular projects today, and add a UI/UX/support burden for a feature that many would likely never use.
