### ISSUE TITLE
Bank maintains state outside of Accounts

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#2210]
#### Problem

Due to rollback, any state outside of `Accounts` cannot be maintained as consistent.  Any state must be computed from the `Accounts` structure from a desired checkpoint. 

#### Proposed Solution

* move the state out of Bank
* write functions of the form `fn compute_state(bank: &Bank) -> DesiredState`

things that need to be moved:

* finality_time (this might be able to stay in the bank)
* account_subscriptions/signature_subscriptions (needs to specify confirmation depth?)
* leader_scheduler (should just be recomputed every time, this should only run once a day)
* storage_state (not sure)

tag: @mvines @carllin @CriesofCarrots @sakridge

**Comment by aeyakovenko** [comment]
@garious it is a bit more complicated. We basically need to define a TVU bank and a TPU bank.  Which are the global bank state forks for those units.  Computations that depend on either should reference those, but we also have some computation that is derived just from whatever fork is being proposed at the moment.

**Comment by garious** [comment]
@rob-solana, I assigned this one to you under the assumption it's part of what you're already doing as part of taking over #2289.
