### ISSUE TITLE
solana installer times out while installing

### ISSUE THREAD

**Issue by Arrowana** [solana-labs/solana#22120]
#### Problem
Build in CI times out while downloading the installer binaries

Installer seems to be ~250 MB and is given at most 30 seconds according to the reqwest client default.

This leads to this error while building in CI
```
InstalledDir: /usr/bin
downloading v1.9.2 installer
Error: error decoding response body: operation timed out
Error: Process completed with exit code 1.
```

#### Proposed Solution

Override the timeout to something more reasonable that the 30 seconds default, possibly a few minutes at least?
https://github.com/solana-labs/solana/blob/master/install/src/command.rs#L94-L107

Does that sound correct or is this symptom hiding something else?

**Comment by willhickey** [comment]
I can't find any indication that using the default timeout was intentional. Increasing it to a few minutes sounds good.

**Comment by CriesofCarrots** [comment]
@Arrowana , just for my edification, can you link to a CI run that hit this issue? Or are you running CI locally?

**Comment by Arrowana** [comment]
> @Arrowana , just for my edification, can you link to a CI run that hit this issue? Or are you running CI locally?

It is from CI in a private repo :s

The log dump

https://pipelines.actions.githubusercontent.com/BlUVaC3XgH1OrUJ86oDKXywD7EEArcqs9wovLWwK0aRAjTHvn9/_apis/pipelines/1/runs/2841/signedlogcontent/17?urlExpires=2021-12-27T23%3A44%3A59.4788569Z&urlSigningMethod=HMACV1&urlSignature=IQhgk5lwqCU2OUDUlIHwNxjNT0FQLcJ%2BVZ7Hg7Ugxxk%3D

This is done using github CI, and a workflow that install solana with `sh -c "$(curl -sSfL https://release.solana.com/$solana_version/install)"`
