### ISSUE TITLE
Can't run validator in failover mode with etcd

### ISSUE THREAD

**Issue by garceri** [solana-labs/solana#22131]
#### Problem
I'm trying to follow the guide on https://docs.solana.com/running-validator/validator-failover but when I add the required parameters to the command line of ```solana-validator``` eg:
```
  --tower-storage etcd \
  --etcd-cacert-file certs/etcd-ca.pem \
  --etcd-cert-file certs/validator.pem \
  --etcd-key-file certs/validator-key.pem \
  --etcd-endpoint 127.0.0.1:2379

```
Solana complains about:

```
error: Found argument '--tower-storage' which wasn't expected, or isn't valid in this context
        Did you mean --tower?


```
I'm running 1.8.11:
```
$solana-validator --version
solana-validator 1.8.11 (src:423a4d65; feat:2385070269)

```
What am I missing here ?

**Comment by CriesofCarrots** [comment]
Looks like the `--tower-storage` and `etcd` parameters came in v1.9, so you'll need to use a v1.9 release to make this work.
