### ISSUE TITLE
control of payment of the fee

### ISSUE THREAD

**Issue by torugor** [solana-labs/solana#22145]
#### Problem
I am having a problem with Web3.js

I want to send token from a wallet to another. But i want to choose who is the one paying the fees.

Here is my code:

var connection = new solanaWeb3.Connection(solanaWeb3.clusterApiUrl(“mainnet-beta”));
var fromWallet = solanaWeb3.Keypair.fromSecretKey(SENDERSECRET);
var toWallet = solanaWeb3.Keypair.fromSecretKey(RECEIVERSECRET);
varr myMint = new solanaWeb3.PublicKey(token);
var myToken = new splToken .Token(
connection,
myMint,
splToken .TOKEN_PROGRAM_ID,
toWallet
);
myToken.getOrCreateAssociatedAccountInfo(fromWallet.publicKey ).then(fromTokenAccount=>{
myToken.getOrCreateAssociatedAccountInfo(toWallet.publicKey).then(toTokenAccount=>{
let lamportQuantity=1000000000*quantity;
var transaction = new solanaWeb3.Transaction({
feePayer: toWallet.publicKey
}).add(
splToken .Token.createTransferInstruction(
splToken .TOKEN_PROGRAM_ID,
fromTokenAccount.address,
toTokenAccount.address,
fromWallet.publicKey,
,
lamportQuantity
)

            );

            connection.getRecentBlockhash().then(recentBlockhash=>{

              transaction.recentBlockhash = recentBlockhash.blockhash;

              transaction.sign(toWallet)

                solanaWeb3.sendAndConfirmTransaction(connection,transaction,[fromWallet] ).then(signature=>{
});

This code was supposed to send a token from an account to another, choosing toWallet as the fee payer.

But it gives me:
core.es5.js:1020 ERROR Error: Uncaught (in promise): Error: !signature
Error: !signature
at Connection.sendTransaction (connection.ts:3617)

Every time.

What am i doing wrong? And one more thing…can the fee Payer be a wallet that is not the one sending and receiving, but my company wallet?
I want to pay the fees of my customer transactions.

#### Proposed Solution
dont know the solution

**Comment by t-nelson** [comment]
Hi!  We don't use Github for support.  Please join us in #developer-support on https://solana.com/discord
