### ISSUE TITLE
onProgramAccountChange Triggering Events for Invisible Changes

### ISSUE THREAD

**Issue by iamnafets** [solana-labs/solana#22159]
#### Problem
onProgramAccountChange appears to be triggering for accounts that haven't changed. Ex, I got a notification for:

> slot=113,829,971 
> accountId=9XxzP93xJQznF7GKuTQ5JmCVNHZrJQtGsvbUKkNHmFwk 
> mint=Bn8P8KwGZmxgP7c9SxsVFdqaLEVkG4uVabfHUBq9RBLM
> amount= 1

Checking explorer: https://explorer.solana.com/address/9XxzP93xJQznF7GKuTQ5JmCVNHZrJQtGsvbUKkNHmFwk, the last block with a transaction was 113,727,215.

My code is simply subscribing to the spl token program:

```
conn.onProgramAccountChange(splToken.TOKEN_PROGRAM_ID, (keyedAccountInfo, context) => {
```

#### Proposed Solution
RPC subscription notifications should only be generated when there is a transaction that changes the account.

**Comment by davidrakosi** [comment]
same issue here. did any of you guys find something by chance?

**Comment by sultandilaram** [comment]
Got into same issue, I think it is the issue of rpc.

**Comment by jihangli11** [comment]
I got the same issue. The pubkey of the account being update is increased in the alphabetical order. Looks like some part of the program is scanning through all accounts and updating them invisibly.

**Comment by sneljeroen** [comment]
Anyone got a fix for this?

**Comment by thijsdekkers** [comment]
Same issue here. @sultandilaram RPC not at fault here, I run into this issue with different RPC providers.
