### ISSUE TITLE
Does not show Balance change when signing multiple transaction with connected wallet in Browser

### ISSUE THREAD

**Issue by AlexLup06** [solana-labs/solana#22163]
Hi, when i try to sign a transactions with the connected wallet, it is supposed to show this little window where it is asking for approval and shows the balance changes and network fees. 
But in my case when i try to sign multiple transactions it is not able to show the costs of the transactions. It just says: Unable to fetch balance changes.
The method I use to sign all:
`  const signedTxns = await wallet.signAllTransactions(unsignedTxns);
`

When i click approve everything goes according to plan and all transactions go through.

Is it just like this that when you sign multiple transactions with a wallet, that it does not show the balance changes or did i do something wrong?

I tried signing the transactions individually (in a for loop) and it worked perfectly without any problems and showed the balance change like it should.
```
  const signedTxns: any = [];
  for (let i = 0; i < unsignedTxns.length; i++) {
    signedTxns.push(await wallet.signTransaction(unsignedTxns[i]));  // here is the price and approve shown to user
  }
```

But then the person doing the transactions has to approve twice, which is kind of annoying especially if there are more than 2 transactions to sign.

There are too many instructions to put them into one transactions. Already ran into this error. That's why I have to do multiple transactions.

No proposed solution :(

**Comment by t-nelson** [comment]
Hi! We don't use Github for support. Please join us in #developer-support on https://solana.com/discord
