### ISSUE TITLE
How to deploy program using `solana_sdk` tpuclient?

### ISSUE THREAD

**Issue by lilses** [solana-labs/solana#22181]
#### Problem
It says here https://docs.solana.com/developing/on-chain-programs/deploying as program is deployed using a special deploy transaction. Is that bespoke or an instruction that exists in solana sdk?

I could just copy this https://github.com/solana-labs/solana/blob/master/cli/src/program.rs#L1694 but there must exist a command for this. Especially when running stateless environments so upgrading functionality is not needed.

**Comment by steveluscher** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Solana itself.

Questions like yours deserve a purpose-built Q&A forum. Please post your question to the Solana Stack Exchange using this link: https://solana.stackexchange.com/questions/ask
