### ISSUE TITLE
How do I solve "Deploying program failed: Error processing Instruction 0: account data too small for instruction"?

### ISSUE THREAD

**Issue by tanin47** [solana-labs/solana#22190]
I cannot deploy a program to devnet due to this error: `Deploying program failed: Error processing Instruction 0: account data too small for instruction`.

The program is not large. It's ~400 lines.

I commented out some code, and I've found that `invoke_signed` on `spl_token::instruction::set_authority` is the root cause.

The .so file is only ~164K. When commenting out that `invoke_signed` on `spl_token::instruction::set_authority`, the deployment works normally (and the .so size is ~140K)

How do I solve this issue? Thank you!

**Comment by t-nelson** [comment]
Hi! We don't use Github for support.  Please join us in #developer-support on https://solana.com/discord
