### ISSUE TITLE
Title and icon not showing up in wallet 5 days later still?

### ISSUE THREAD

**Issue by aiden280zx** [solana-labs/solana#22219]
#### Problem
I made a token on the Solana network and it seams to not show the icon or title in multiple wallet, always says "Unknown Token" iv tried countless wallets and still no icon or title, my Token is called KEKO, KonekoKoin. BKSrRNHhdJbsuYX4oHCsPa2GwKQD84Tb9a6817T6oCYm

**Comment by t-nelson** [comment]
Hi! We don't use Github for support and SPL Token has nothing to do with this repository.  Please join us on https://solana.com/discord instead
