### ISSUE TITLE
RPC: getProgramAccounts super slow any tips?

### ISSUE THREAD

**Issue by scottandrew** [solana-labs/solana#22213]
#### Problem

I am experimenting with read NFT metadata using getProgramAccounts, running the "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" program, filtering on the mint id (offset 33). However this call is taking 10+ seconds to resolve.  Is there another call to try? Is there a trick to speed this up?

**Comment by askibin** [comment]
number of accounts owned by that program is enormous. You should probably query once and cache results and then parse program's transactions to get recently added accounts (listening for updates over websocket or query for recent account signatures)

**Comment by askibin** [comment]
you can ask further on Metaplex discord for maybe better solution https://discord.gg/metaplex

**Comment by jacobcreech** [comment]
Hey @scottandrew, the general recommendation when reading a ton of program accounts like from the metaplex program is to use accountsDb. For more help regarding this, please visit our developer support on https://solana.com/discord We do most of our dev support on discord
