### ISSUE TITLE
solana-test-validator --slots-per-epoch has no effect (even on brand new ledger)

### ISSUE THREAD

**Issue by johhnsmmith198** [solana-labs/solana#22222]
#### Problem

I am trying to slow down the solana-test-validator to be able to follow the logs to debug an issue I have while deploying a program.
I thought I could use the `--slots-per-epoch 1800` to try to have about 1 slot per minute (might be too slow but just to try something)

but this still create a slot every 400ms creating logs that are impossible to read.

I use docker to be able to run the solana-test-validator in an isolated environment and restart from the genesis block each time I restart docker.
My command is something like this
```
docker run -it --entrypoint solana-test-validator -p 8899:8899 -p 8900:8900 -p 9900:9900 solanalabs/solana:v1.8.11 --slots-per-epoch 1800 --log
```

#### Proposed Solution

Not sure. 
I am surprised I could find no resource about wanting to slow down the solana-test-validator to be usable in development mode locally.
Did anyone used the `--slots-per-epoch` successfully ?

**Comment by t-nelson** [comment]
It doesn't look like `--ticks-per-slot MILLIS` from `solana-genesis --help` has been exposed to `solana-test-validator`.

A PR doing such would very likely be accepted

**Comment by alexspurling** [comment]
I also have the same problem. As short-term work around, could you please document how to use the `solana-genesis` command to start a validator with a custom "ticks-per-slot" config?
