### ISSUE TITLE
Validators are allowed to run too aggressively into potential deep lockout situations

### ISSUE THREAD

**Issue by bji** [solana-labs/solana#22244]
#### Problem

My understanding of the voting mechanism is partial because there are some aspects that are hard to grok from reading code.  But if my understanding is correct, then validators are constantly:

a. Using a "heaviest fork choice" to decide what fork they "want to" be on
b. As long as the heaviest fork choice is their current fork, and there is a new slot on their current fork to vote on, they will vote on it
c. Once the heaviest fork becomes some other fork, then the validator will stop voting while waiting for lockouts on the current fork to expire thus freeing up the validator to switch to the other fork
d. If the current fork becomes the new heaviest fork while waiting in (c), the validator will then continue voting on the current fork

This algorithm allows validators to proceed blithely down very deep forks as long as not enough stake weight has accumulated to tell them to do otherwise.  Going deep onto a fork:

1. Doesn't necessarily help "end users" who typically care only about confirmed slots.  There is some value in voting ahead of a confirmed slot because it results in faster confirmation of not-yet-confirmed slots.  But the further ahead a validator goes, the less likely that their vote is going to contribute to any confirmations in the short term (because it will take time for stake-weighted votes to confirm all prior slots before reaching the currently voted-on slot), and the more likely it is to be deep into lockouts on a fork that is not going to progress.
2. Prevents the validator from switching over to a different fork should the current fork be "dead".

The above means that there is a *cost* to going deep into lockouts, as well as a benefit.  The benefit is:

I. More quickly achieving consensus if the validator is "on the right fork"

The cost is:

II. Less quickly achieving consensus if the validator is "on the wrong fork"

I believe that the current implementation favors (I) over (II) to too high of a degree.  In other words, it is letting validators get too deep into lockouts which then makes overall fork resolution slower (due to a large number of validators locked out and unable to contribute to consensus for a significant period of time) more often than it is faster.

#### Proposed Solution

I have proven already that a different fork selection algorithm that puts a hard limit on how far a validator will allow itself to get ahead of "some fraction of consensus" on a fork can result in more accurate voting.  Earning more vote credits overall implicitly means contributing more to consensus.  The question is, does it contribute enough to timeliness?

Tough questions, and even tougher when trying to consider how the network will behave when the vast majority of stake-weight behaves the same way.

I propose at least considering implementing some mechanisms to "throttle back" voting when a validator detects that it is "too far ahead".  How far ahead, how much to throttle, "ahead of what exactly", these are all relevant parameters to consider.

Of course with the caveat that a validator should always have an escape hatch to "vote anyway" even if consensus is not progressing, to avoid deadlock when there are multiple simultaneous forks.

**Comment by mvines** [comment]
@carllin's probably the right person to noodle on this a little

**Comment by bji** [comment]
Also I'd just like to say that most of the time, if you can find an example where nature has already solved a problem, then you should seriously consider that solution.  I imagine a flock of birds.  They are all trying to get roughly to the same place, but at any one time there are some flying ahead and some flying back, and which ones are ahead and which ones are back dynamically changes all the time.  But no bird ever lets itself get too far ahead of the flock.

**Comment by carllin** [comment]
> As long as the heaviest fork choice is their current fork, and there is a new slot on their current fork to vote on, they will vote on it

This isn't true. We have a "threshold" check: https://github.com/solana-labs/solana/blob/master/core/src/consensus.rs#L860-L865. We don't vote unless > 2/3 of the cluster has voted on the slot that is at depth 8 in your tower

**Comment by bji** [comment]
> > As long as the heaviest fork choice is their current fork, and there is a new slot on their current fork to vote on, they will vote on it
> 
> This isn't true. We have a "threshold" check: https://github.com/solana-labs/solana/blob/master/core/src/consensus.rs#L860-L865. We don't vote unless > 2/3 of the cluster has voted on the slot that is at depth 8 in your tower

Thank you for that.  I thought at one point I knew that but re-reading the code, I couldn't find where that happened.

In this case I think that possibly the numbers could be tuned.  Depth 8 may be too deep?  Do you know what the reasoning was for choosing that number?

**Comment by carllin** [comment]
> Depth 8 may be too deep
Yup there's been discussion about lowering this :)

> Do you know what the reasoning was for choosing that number?
Estimates on partition lengths and acceptable downtime

**Comment by bji** [comment]
Thanks.  I recommend 6, not 8.

I haven't checked to see if the stock code has a safety valve for voting even if check_vote_stake_threshold returns true, but it's been way more than 8 slots since last voting, to prevent deadlock if there are multiple forks none of which could ever achieve 2/3.  I assume there is.  In fact there must be otherwise the cluster would just die if that happened.

**Comment by carllin** [comment]
>  if the stock code has a safety valve for voting even if check_vote_stake_threshold returns true, but it's been way more than 8 slots since last voting

Yeah, newer votes at the top of the tower eventually expire, making the tower shallower. Then the threshold check then happens on an older slot, allowing votes to happen again

**Comment by aeyakovenko** [comment]
The deterministic turbine improvements should dramatically reduce forking, and voting on blocks that didn’t get to the 2/3+
