### ISSUE TITLE
There is no centralized way for program developers to gain a window into their heap usage

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#22278]
#### Problem

There is no centralized way for program developers to gain a window into their heap usage

Programs are bundled with a default, in-program-space heap implementation and the runtime doesn't track how that heap region is used except to enforce boundaries.

#### Proposed Solution

- Very intrusive and special case but possibly instrument the program address translation code to report heap usage read/writes, and for that matter, it could report all memory access by the program.
- Heap specific, but could also provide a featurized implementation of the in-program heap that logs allocations.

**Comment by XpectCoin** [comment]
Wo
