### ISSUE TITLE
Synchronization problem

### ISSUE THREAD

**Issue by wzt-tao** [solana-labs/solana#22298]
#### Problem
Our node cannot synchronize with your mainnet. Is there a problem with network latency recently?
###Node configuration
```
#aws ec2
Instance type: m6i.12xlarge
Disk type: gp3 iops:8000 Throughput (MB/s):1000
```

**Comment by steviez** [comment]
Hi @wzt-tao - we don't use GitHub for support issues like this; please join us at https://solana.com/discord instead.
