### ISSUE TITLE
Consider refactoring `ExecuteTimings` type

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#22325]
#### Problem

`ExecuteTimings` are getting a bit unwieldy to maintain.

#### Proposed Solution

Consider an indexed array structure with common interface for all data points

**Comment by ekong16** [comment]
Hello,
Im interested in contributing to Solana, I am new to the codebase. A search for ExecutionTimings yielded no results for me.
Where can I find this type?

**Comment by t-nelson** [comment]
Sorry, it's `ExecuteTimings`! :sweat_smile:
