### ISSUE TITLE
Research short-term storage solutions for Window

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#2235]
#### Problem

Validators can't be required to maintain an infinite window (there's no reward incentive, so need to assume they won't). They might only need enough window to navigate forks. Old repair requests can use the replicator RPC API.

#### Proposed Solution

Research alternatives. A few options below, but need a more thorough list and analysis:

* `BTreeMap<Vec<u8>, Vec<u8>>`
* https://github.com/mozilla/rkv
* https://github.com/spacejam/sled

**Comment by rob-solana** [comment]
some conclusions (eliminations):
rkv doesn't support anything larger than 4GB (2GB), is optimized for read performance
sled is super, super slow and is apparent overkill for our use case

rocksdb is slower than a custom, file-based db_ledger, but is implemented now, serves the purposes of a ledger while storage nodes are built, and should support speedy pruning of replicated data

**Comment by garious** [comment]
Research was done, no suitable existing solutions were found. @MarkJr94 started implementation of kvstore.
