### ISSUE TITLE
cargo build error

### ISSUE THREAD

**Issue by wangweiwei1188** [solana-labs/solana#22361]
run: cargo build, the "failed to run custom build command for `openssl-sys v0.9.70`" happen
--- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR
  X86_64_UNKNOWN_LINUX_GNU_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  CC_x86_64-unknown-linux-gnu = None
  CC_x86_64_unknown_linux_gnu = None
  HOST_CC = None
  CC = None
  CFLAGS_x86_64-unknown-linux-gnu = None
  CFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CFLAGS = None
  CFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running "perl" "./Configure" "--prefix=/home/weiweiwang/rust/solana-master/target/debug/build/openssl-sys-cda2356ad9360a22/out/openssl-build/install" "no-dso" "no-shared" "no-ssl3" "no-tests" "no-comp" "no-zlib" "no-zlib-dynamic" "--libdir=lib" "no-legacy" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "linux-x86_64" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64"

  --- stderr
  Can't locate IPC/Cmd.pm in @INC (you may need to install the IPC::Cmd module) (@INC contains: /home/weiweiwang/rust/solana-master/target/debug/build/openssl-sys-cda2356ad9360a22/out/openssl-build/build/src/util/perl /usr/local/lib64/perl5 /usr/local/share/perl5 /usr/lib64/perl5/vendor_perl /usr/share/perl5/vendor_perl /usr/lib64/perl5 /usr/share/perl5 /home/weiweiwang/rust/solana-master/target/debug/build/openssl-sys-cda2356ad9360a22/out/openssl-build/build/src/external/perl/Text-Template-1.56/lib) at /home/weiweiwang/rust/solana-master/target/debug/build/openssl-sys-cda2356ad9360a22/out/openssl-build/build/src/util/perl/OpenSSL/config.pm line 18.
  BEGIN failed--compilation aborted at /home/weiweiwang/rust/solana-master/target/debug/build/openssl-sys-cda2356ad9360a22/out/openssl-build/build/src/util/perl/OpenSSL/config.pm line 18.
  Compilation failed in require at ./Configure line 23.
  BEGIN failed--compilation aborted at ./Configure line 23.
  thread 'main' panicked at '

  Error configuring OpenSSL build:
      Command: "perl" "./Configure" "--prefix=/home/weiweiwang/rust/solana-master/target/debug/build/openssl-sys-cda2356ad9360a22/out/openssl-build/install" "no-dso" "no-shared" "no-ssl3" "no-tests" "no-comp" "no-zlib" "no-zlib-dynamic" "--libdir=lib" "no-legacy" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "linux-x86_64" "-O2" "-ffunction-sections" "-fdata-sections" "-fPIC" "-g" "-fno-omit-frame-pointer" "-m64"
      Exit status: exit status: 2

      ', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/openssl-src-300.0.4+3.0.1/src/lib.rs:495:13
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by jacobcreech** [comment]
Hey @wangweiwei1188,  We don't use Github for support. Please join us on https://solana.com/discord instead.
