### ISSUE TITLE
solana-test-validator tpu client freezes after 1 transaction

### ISSUE THREAD

**Issue by evergreen-trading-systems** [solana-labs/solana#22386]
#### Problem

When sending more than 1 transaction through tpu client, only 1 transaction is validated.

**Comment by evergreen-trading-systems** [comment]
Sending transaction in loop. After 1st loop, validator doesn't receive transactions.

https://user-images.githubusercontent.com/4870868/148654615-2a4e3111-60fd-4410-b20f-59a12f67fa1a.mp4

**Comment by CriesofCarrots** [comment]
Join us on discord for technical support: https://solana.com/discord
However, quickly: TpuClient does work for multiple transactions (that's what `solana program deploy` uses). I wonder if you are sending the same exact transaction repeatedly. If so, only the first will land. The duplicates will fail on `TransactionError::AlreadyProcessed` and not be processed by the solana-test-validator. This is the trade-off of using TpuClient; it fires the transaction off to the node's TPU port, bypassing the potential transaction simulation done by the nodes rpc service, which would catch this kind of pre-processing error.
