### ISSUE TITLE
Provide method to retrieve wired Transaction Size

### ISSUE THREAD

**Issue by gitmalong** [solana-labs/solana#22413]
#### Problem

I need to retrieve the so called Wired `Transaction` size in order know if two Transactions can be merged or not.

Web3js Implementation: https://github.com/solana-labs/solana-web3.js/blob/168d5e0/src/transaction.ts#L572

#### Proposed Solution

Implement https://github.com/solana-labs/solana-web3.js/blob/168d5e0/src/transaction.ts#L572 in Rust

**Comment by CriesofCarrots** [comment]
The Rust equivalent of that solana-web3 method is just `bincode::serialize` on the Transaction struct. Here's how the solana-client does it to prep a Transaction to send over rpc: https://github.com/solana-labs/solana/blob/9bc2592da1713faac982233f054ab311a531e4fc/client/src/rpc_client.rs#L4853
You can also use `bincode::serialized_size(&transaction)` to get the wire size.
