### ISSUE TITLE
Cannot import solana web3js in react native

### ISSUE THREAD

**Issue by Haianh9999** [solana-labs/solana#22421]
#### Problem
I can't import solana-web3js to use in my react native project.
I am using ethers everything is working properly but after import solana-web3js error could not detect network

**Comment by Haianh9999** [comment]
@CriesofCarrots can you help me to solve this issue ?

**Comment by t-nelson** [comment]
Hi!  We don't use Github for support requests. Please join us in #developer-support on https://solana.com/discord instead
