### ISSUE TITLE
How do I provide a translation of a document in Chinese?

### ISSUE THREAD

**Issue by Yanren1225** [solana-labs/solana#22420]
#### Problem

I think ![this place](https://github.com/solana-labs/solana/tree/master/docs) should be the Markdown file for the documentation, but I didn't find a translation in another language. I also have ![seen this](https://github.com/solana-labs/solana/tree/master/docs#translations), but he needs me to provide an API TOKEN and I don't know if I should visit <https://solana.crowdin.com> or <https://crowdin.com>. So can someone guide me, thanks guys!

#### Proposed Solution

I have tried using the individual APIs for <https://solana.crowdin.com> or <https://crowdin.com> and then using `npm run crowdin:download`, but that doesn't seem to work.

**Comment by t-nelson** [comment]
cc/ @rmshea

**Comment by EndureBlaze** [comment]
> cc/ @rmshea

What does this mean, I don't understand

**Comment by t-nelson** [comment]
> > cc/ @rmshea
> 
> What does this mean, I don't understand

He manages docs translations and is best to advise on this issue.  Please be patient

**Comment by steveluscher** [comment]
@timhagn, do you have an answer for @EndureBlaze?
