### ISSUE TITLE
Broken links in JSON RPC API documentation

### ISSUE THREAD

**Issue by chris-j-h** [solana-labs/solana#22427]
#### Problem
https://github.com/solana-labs/solana/blob/master/docs/src/developing/clients/jsonrpc-api.md?plain=1#L3195
https://github.com/solana-labs/solana/blob/master/docs/src/developing/clients/jsonrpc-api.md?plain=1#L3211

#### Proposed Solution

```diff
- [transaction id](../../terminology.md#transanction-id)
+ [transaction id](../../terminology.md#transaction-id)
```

**Comment by steviez** [comment]
Hi @chris-j-h, thanks for catching this! Do you care to open a PR so we can properly attribute this to you?
