### ISSUE TITLE
Add ability for programs to check the processed instruction stack

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#22437]
#### Problem

There are certain scenarios where instructions (top-level or via CPI) would like to know what the last instruction processed was.  Some examples are verification of assert instructions or to check memo instructions

#### Proposed Solution

Make at least the last executed instruction available to programs.  With the option of expanding to to a list of all past processed instructions in the tx.  There has already been work done in this general direction so hopefully, this will not be very disruptive.

**Comment by CriesofCarrots** [comment]
I think we may need this in v1.9 timeframe. Will that be possible?

**Comment by jackcmay** [comment]
I think we can make that happen

**Comment by Lichtso** [comment]
"processed instruction stack" is ambiguous, do you mean:
- The list / sequence of recorded instructions
- The invocation / CPI stack

The former is only used by the bank and the later will be exposed in ABIv2 per default (no syscall necessary).

**Comment by jackcmay** [comment]
An ordered list of all the instructions that have been processed before the current one is my understanding

**Comment by Lichtso** [comment]
So a mixture of the two. The thing is, the frames below the current one in the CPI stack are not finished / processed yet. They are just suspended and waiting for the upper ones to finish. Thus, these are two separate concepts that can not be mixed (at least not directly).

**Comment by mvines** [comment]
The immediate need is to discover the previous sibling CPI instruction.  Use case:
* Program A invokes B by CPI
* Program A invokes C by CPI
* C can discover that A previously invoked B

**Comment by CriesofCarrots** [comment]
I think for our current purposes, just the sequence of recorded instructions would be sufficient, assuming it works within an instruction on the CPIs called at that level.

**Comment by jackcmay** [comment]
Yeah, that's my understanding, what about non-cpi sibling instructions.

For example, given the call flow:
```
A
B -> C
B -> D
```
You want D to see C and A, but not B?

**Comment by CriesofCarrots** [comment]
> And at the end B would see D and C?

Yes? Again, not strictly necessary for our purposes, but seems like it could be generically useful.

**Comment by jstarry** [comment]
Note that this feature will not work as expected on testnet and devnet if a transaction contains precompile instructions until the following issue is resolved: https://github.com/solana-labs/solana/issues/24705
