### ISSUE TITLE
hashes per second

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#2245]
#### Problem
The network doesn't have a way to track human time. 

#### Proposed Solution
A network constant "hashes per second" value that is derived from number of hashes over the last fortnight. 

Based on this approximation the network can then derive a human clock for contracts and other economic factors.  To actually get samples of real human time, validator votes should contain their local utc wallclock timestamp.  The median wallclock for each fork can be computed from the stake weight of each vote.

The protocol could further enforce this by not accepting votes outside of the expected wallclock range for the fork they are created for.

**Comment by garious** [comment]
@aeyakovenko, this problem description doesn't describe a problem.

**Comment by garious** [comment]
@rob-solana, is this still an issue or solved with `sysvar::clock`?

**Comment by rob-solana** [comment]
still a problem
