### ISSUE TITLE
Error while creating Nonce Account through offline signatures

### ISSUE THREAD

**Issue by AUQIB92** [solana-labs/solana#22481]
#### Problem
HII, I am facing some issue in creating nonce account will you pls help me out
Network:DevNet
errorMessage request to https://api.devnet.solana.com/ failed, reason: socket hang up

Here is the code I m runing
const orgPubKey = new PublicKey(bs58.encode(hexToBuffer("f37d0f35a573b3244eaf4e3eaca2833e48f6d0683a96764ff26b1b8b33862ee7")));
    const nonceKey = new PublicKey(bs58.encode(hexToBuffer("44a87ebf5fa3746d7f33c5ce2cdc18856f98ca90c241db2ddde0bf33df851e89")));
   

    let tx = new Transaction();
    tx.feePayer = orgPubKey
    //tx.recentBlockhash=(await connection.getRecentBlockhash()).blockhash;
    tx.recentBlockhash = (await connection.getRecentBlockhash()).blockhash
    tx.add(
      // create nonce account
      SystemProgram.createNonceAccount({
        fromPubkey: orgPubKey,
        noncePubkey:nonceKey,
        authorizedPubkey:orgPubKey,
        lamports: await connection.getMinimumBalanceForRentExemption(NONCE_ACCOUNT_LENGTH),
      
      }));
   
  
  
    
    console.log(tx.recentBlockhash)
    console.log(tx.serializeMessage().toString('hex'))
  

    //Adding Signature to make Complete Transaction
  tx.addSignature(orgPubKey, hexToBuffer(signature1));
   tx.addSignature(nonceKey, hexToBuffer(signature2));

    console.log("Final Raw Txn", (tx.serialize().toString('hex')))
    var isOk = tx.verifySignatures();
    console.log('verifySignatures: ' + isOk);
    const hashReal = await sendAndConfirmRawTransaction(connection,tx.serialize());

**Comment by jacobcreech** [comment]
Hello. We do not do support within github issues. Please join us under #developer-support at www.solana.com/discord
