### ISSUE TITLE
Add `latest` tag for Docker image.

### ISSUE THREAD

**Issue by Krout0n** [solana-labs/solana#22485]
#### Problem
When `$ docker pull solanalabs/solana` is executed, no image is pulled because `latest` tag is not specified now. 

#### Proposed Solution
Add `latest` when new version is released, if this is a good first issue, I wanna contribute.

**Comment by t-nelson** [comment]
Definitely a good first issue.  Patches welcome! :slightly_smiling_face:

**Comment by mvines** [comment]
Right now we have three Docker tags: `edge`, `beta` and `stable`.  These correspond to the names of our release channels: https://github.com/solana-labs/solana/blob/master/RELEASE.md#channels

It's not clear to me what a `latest` would mean.  It could be any or all of these three channels depending on what the user is looking for.  This is the main reason why we don't have a `latest`.

The solana Docker image is mostly for internal CI usage anyway.  It's not a public artifact that we advertise for ecosystem use

**Comment by vintageplayer** [comment]
As per convention, the latest points to the latest stable image (safest IMO)

`docker pull solanalabs/solana` right now throws:

> Error response from daemon: manifest for solanalabs/solana:latest not found: manifest unknown: manifest unknown

It's better to get the safest ci to get started. Since the overview page is empty, I ended up cloning the repo and building manually, till I realized other tags exist.

**Comment by xiangzhu70** [comment]
The "https://hub.docker.com/r/solanalabs/solana" page shows Docker Pull Command as "docker pull solanalabs/solana", which assumes the existence of solana:latest tag, hence the error.

The correct pull command should be "docker pull solanalabs/solana:<correct_tag>", such as "docker pull solanalabs/solana:stable"

**Comment by LukasDeco** [comment]
Is this the kind of script we would add the tag to? https://github.com/solana-labs/solana/blob/master/sdk/docker-solana/build.sh Seems like there are a few of these scripts. Or am I looking in the wrong place.
