### ISSUE TITLE
Confirmation time calculation is not correct

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#2248]
#### Problem
Confirmation time calculation does not track when super majority stake successfully voted on an entry. It is instead calculating how long ago latest confirmation was achieved. 

#### Proposed Solution
Implement a data structure that maintains a list of all recent outstanding ticks that are waiting for confirmation from super majority stake nodes. The data structure is configured with total stake of the network (the stake can change over time, so need to put more thoughts here).

When a new vote is received, the voting node's identity, stake information, current tick, and tick on which the node voted, is provided to the data structure. The data structure computes if super majority stakeholders have voted on the tick.

If a super majority has voted, it records the time it took for the tick to get confirmed (i.e. time of confirmation - time when the tick was generated). It evicts the confirmed tick and all lower ticks from its list. 

If the super majority has not yet voted for the tick, it stores the identity of the voting node (to reject duplicate votes), and stake size agains the tick. It also scans any lower tick that has not yet received a vote from this node. If it finds one, it calculates it's supermajority including current node's stake (assuming the node also voted on the lower tick in past).

**Comment by pgarg66** [comment]
@rob-solana , @carllin, @garious FYI. Please add comments if I missed something.

**Comment by garious** [comment]
Good stuff! You're right, we'll need a way to look up stake at a given height.  That's pretty interesting that while a vote applies to all ticks before it, the stake it adds may be different (or even zero) for each tick.

**Comment by aeyakovenko** [comment]
@pgarg66 since it’s sampled randomly, the data should match 1/2 of the confirmation time

**Comment by pgarg66** [comment]
@aeyakovenko do you mean the data in the current implementation? Currently, it's time since last transaction that was confirmed. i.e. if transaction tx was originated at time t1, confirmed at t2, and the confirmation algorithm was run at t3, it's calculating t3-t1 (instead of t2 - t1).

Good news is that actual confirmation time is less than what we are publishing right now (since t3 is >= t2).

**Comment by aeyakovenko** [comment]
@pgarg66  the old method was sampling how far the leader is ahead of the supermajority.  If the samples are random then the median should be 1/2 of confirmation time.

**Comment by pgarg66** [comment]
What you described would be t3-t2 (time leader is ahead of supermajority). I think we are calculating t3-t1.

**Comment by aeyakovenko** [comment]
I think you are right and I am confused :).  I need to whiteboard this out again.

**Comment by garious** [comment]
Booted this from Beacons because there's no longer a plan to thread votes through a single on-chain program. Without that program, the next best 2 options are:

1. What we're currently doing (except that we should double the output, since [I think] that's reporting an average 1/2 confirmation time).
2. Query all vote programs after every vote to check for supermajority.

That second option would give us more precise times, but might slow the system down just to report a metric.

**Comment by aeyakovenko** [comment]
@garious so the average transaction confirmation time would be half of the average confirmation time :).  Transactions, on average, land in the middle of a slot.

**Comment by mvines** [comment]
https://github.com/solana-labs/solana/blob/e76f2ea89ce00567b40637e9c8554bd32fa89bb1/book/src/block-confirmation.md
