### ISSUE TITLE
How should I translate the document

### ISSUE THREAD

**Issue by EndureBlaze** [solana-labs/solana#22482]
#### Problem

I have successfully run the documentation locally, but I can't run `npm run crowdin:download`, it prompts

```shell
$ npm run crowdin:download                                                                                        

> solana-docs@0.0.0 crowdin:download
> crowdin download

❌ Fetching project info     
❌ Failed to collect project info. Please contact our support team for help
❌ You do not have permission to view/edit project with provided id.
```

I have registered at https://solana.crowdin.com and got the api

**Comment by jacobcreech** [comment]
You already have https://github.com/solana-labs/solana/issues/22420 open. Please make the comment there instead, or wait for the resolution of the original issue
