### ISSUE TITLE
Unable to deploy large programs in solana cli v0.19

### ISSUE THREAD

**Issue by tomland123** [solana-labs/solana#22528]
#### Problem

When attempting to deploy large programs in solana cli v0.19 you only get Error: Custom: Invalid blockhash and resuming with solana program deploy --buffer will loop with this error message.

The problem was solved when reverting to solana cli v0.18

**Comment by CriesofCarrots** [comment]
Hello. We do not offer technical support on github. Please join us at #developer-support on Discord: www.solana.com/discord

That said, hopefully you mean some newer versions of solana-cli than v0.XX. I think the `solana program` subcommand was introduced in v1.6 timeframe...

**Comment by tomland123** [comment]
yeah i meant the newest version of solana v 1.9. Had a brain block. I dont understand how this isnt a bug though if it works on 1.8 instead of 1.9

**Comment by CriesofCarrots** [comment]
There certainly could be a bug somewhere, but I was just able to deploy a program using solana-cli v1.9.4 against a solana-test-validator on v1.8.12. Not sure what cluster or test-validator you are trying to deploy against.

**Comment by tomland123** [comment]
I updated the description because it might've been confusing without more context. When I meant large programs, I meant large programs not every program!

**Comment by Henry-E** [comment]
Can confirm that while I was able to deploy a program of size 500kb to the devnet cluster with solana version 1.9.1, I was unable to deploy a program of 1.5mb size to the devnet without getting Invalid Blockhash error.

**Comment by dovahcrow** [comment]
Getting the same issue. My program is 1MB.

**Comment by qbig** [comment]
solana-cli 1.8.12 works

**Comment by qbig** [comment]
@CriesofCarrots maybe reopen this since lots of devs using 1.9.* are struggling to deploy on devnet.. @chaseeb
