### ISSUE TITLE
Add ability for test validator to sync feature set with other cluster

### ISSUE THREAD

**Issue by charlieyou** [solana-labs/solana#22520]
#### Problem
Currently the test validator indiscriminately enables all features, which results in different behavior than on mainnet: https://github.com/solana-labs/solana/blob/master/runtime/src/genesis_utils.rs#L256-L258

Further context from discord: https://discord.com/channels/428295358100013066/517163444747894795/931707245857734676

#### Proposed Solution
Add the ability to sync the feature set of the test validator with another cluster so that developers can be testing their programs in the same environment as they would be deploying to.

**Comment by FrankC01** [comment]
In addition to a having a command switch on `solana-test-validator` to do the above, it would be ideal if we can programmatically access `FeatureSet` directly or through `TestValidatorGenesis` to activate/deactivate features before starting.

Further comments in discord:

https://discord.com/channels/428295358100013066/517163444747894795/931845633986408498
https://discord.com/channels/428295358100013066/517163444747894795/931994025861460020
https://discord.com/channels/428295358100013066/517163444747894795/931995526038171738

**Comment by FrankC01** [comment]
@charlieyou 

So, in here I wrote a crate which gathers feature state across well known clusters:

1. CLI View: https://github.com/FrankC01/solana-gadgets/blob/main/rust/scfsd/README.md
2. Library Crate: https://github.com/FrankC01/solana-gadgets/tree/main/rust/gadgets-scfs

3. I modified a solana fork: https://github.com/FrankC01/solana
4. And created some initial test to prove it works: https://github.com/FrankC01/solana-gadgets/tree/main/rust/scfs-program/tests

I can use 2 in 4 to do a 'parity' with devnet (as an example) but I'd have to rely on the fork whereas I want `gadgets` to work with installed Solana....

I only lightly touched Solana: https://github.com/FrankC01/solana/commit/5ecd8197ecd9fcf3ca7113875fd03cf9aec4c520

But certainly is feasible perspective for a PR or at least get some eyes on it...

**Comment by charlieyou** [comment]
@FrankC01 This is awesome! If you could use a hand on the 2nd part of the change, adding CLI args, would be happy to help on that. LMK

**Comment by FrankC01** [comment]
@charlieyou Will do, waiting for the PR to merge and then "the world is our oyster" :)
