### ISSUE TITLE
How to recover rent for deployed Solana program?

### ISSUE THREAD

**Issue by topherPedersen** [solana-labs/solana#22526]
#### Problem

Hello, I'm trying to figure out how to recover my rent for a deployed Solana program? I tested deploying a simple "hello, world" program tonight which cost roughly $75. Now I'm trying to recover the rent and am running into an error:

$ solana program close 7r4WZjoFccMCgiXs8Rpoc2upwJqbtj6xDX68wdGqMtF3

Error: 7r4WZjoFccMCgiXs8Rpoc2upwJqbtj6xDX68wdGqMtF3 is not a Program or Buffer account

(My programId is 7r4WZjoFccMCgiXs8Rpoc2upwJqbtj6xDX68wdGqMtF3)

How can I go about changing this command to retrieve my rent? I'm assuming this is possible but I haven't been able to find any answers online so far. I'm also assuming that it doesn't cost $75 every time I need to update my program right? Or does it in fact cost $75 every time you want to deploy or update a program?

Any help would be greatly appreciated, thanks!

#### Proposed Solution

Consider updating docs to make it clearer how to recover rent.

**Comment by joncinque** [comment]
Hi there, we don't use GitHub for support and encourage you to join us on Discord in #developer-support at https://discord.gg/XPyr3GJs

To quickly answer this, there's info in the docs at: https://docs.solana.com/cli/deploy-a-program#closing-program-and-buffer-accounts-and-reclaiming-their-lamports
