### ISSUE TITLE
test_3_partitions is unstable in CI

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#2256]
Observed multiple times today:
```
thread 'test_3_partitions' panicked at 'assertion failed: `(left == right)`
  left: `63`,
  right: `100`', tests/fork-selection.rs:583:5
```
One example: https://buildkite.com/solana-labs/solana/builds/231#21a03a5b-b3ab-482b-8ec6-647e4178e021

**Comment by mvines** [comment]
https://buildkite.com/solana-labs/solana/builds/424#0a27b135-84b0-4043-a8c5-184f5507a299

**Comment by mvines** [comment]
https://buildkite.com/solana-labs/solana/builds/1179#3be855bb-6a0b-4d76-94f6-81d777a1e6eb/11080-12482

**Comment by mvines** [comment]
https://buildkite.com/solana-labs/solana/builds/1402#58ee3d20-b913-46c0-b12d-10c6870dcdb1/11083-12456

**Comment by garious** [comment]
@mvines, is anyone looking at this?

**Comment by mvines** [comment]
Doesn't seem like it :-/
Next time I see this test fail we can ignore it until somebody cares enough to fix it

**Comment by mvines** [comment]
https://buildkite.com/solana-labs/solana/builds/1891#8ffe580b-a5c8-40f6-a700-cc5277ef3fab/10112-11265

**Comment by mvines** [comment]
I disabled this test for now: 5333bda2343698f7a660622168bcc0d3142cb685

**Comment by mvines** [comment]
meh, if somebody cares they'' unignore this test one day.  no need to track it
