### ISSUE TITLE
Version bump PR's on versioned branches aren't automerged

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#22576]
automerge automation failed because it requires the web3 github action to pass when web3 files are modified but that action is only run when the PR base branch is master

_Originally posted by @jstarry in https://github.com/solana-labs/solana/issues/22573#issuecomment-1016256163_

**Comment by t-nelson** [comment]
So maybe we just use the hammer here and totally omit web3.js from version bumps?
https://github.com/solana-labs/solana/blob/d343713f6166be2dcbf22aaffc5f1b4930db115d/scripts/increment-cargo-version.sh#L25-L26
