### ISSUE TITLE
Ed25519 Testnet

### ISSUE THREAD

**Issue by ronanyeah** [solana-labs/solana#22588]
#### Problem

`Ed25519SigVerify111111111111111111111111111` is behaving incorrectly for me on testnet. Both of the following SDK instructions work for me against my local validator, but on testnet I get this response:

> Err(ClientError { request: Some(SendTransaction), kind: RpcError(RpcResponseError { code: -32002, message: "Transaction simulation failed: Error processing Instruction 0: invalid instruction data", data: SendTransactionPreflightFailure(RpcSimulateTransactionResult { err: Some(InstructionError(0, InvalidInstructionData)), logs: Some(["Program Ed25519SigVerify111111111111111111111111111 invoke [1]", "Program Ed25519SigVerify111111111111111111111111111 failed: invalid instruction data"]), accounts: None, units_consumed: Some(0) }) }) })

https://docs.rs/solana-sdk/1.9.4/solana_sdk/ed25519_instruction/fn.new_ed25519_instruction.html
https://solana-labs.github.io/solana-web3.js/classes/Ed25519Program.html#createInstructionWithPublicKey

Here's a minimal Rust example that works on localnet but not on testnet: https://gist.github.com/ronanyeah/f216399d32bcb15d00a6245a1fac89df

**Comment by t-nelson** [comment]
The ed25519 sigverify  program hasn't been enabled on testnet yet.
```
$ solana -ut feature status CCu4boMmfLuqcmfTLPHQiUo22ZdUsXjgzPAURYaWt1Bw
CCu4boMmfLuqcmfTLPHQiUo22ZdUsXjgzPAURYaWt1Bw | inactive                    | Requestable heap frame size
```
