### ISSUE TITLE
Deploy solana program FAILED

### ISSUE THREAD

**Issue by DINHQUANGMINH198** [solana-labs/solana#22596]
#### Problem
I build-bpf , and deploy program on devnet , but failed
$ solana program deploy /home/bc_code/solana-escrow/program/target/deploy/solana_escrow.so --keypair solana-wallet/keypair.json

#### Proposed Solution
Blockhash expired. 5 retries remaining
Blockhash expired. 4 retries remaining
Blockhash expired. 3 retries remaining
Blockhash expired. 2 retries remaining
Blockhash expired. 1 retries remaining
===============================================================================
Recover the intermediate account's ephemeral keypair file with
`solana-keygen recover` and the following 12-word seed phrase:
===============================================================================
chaos shrug glance blame output appear kitten angry jacket hurry narrow stumble
===============================================================================
To resume a deploy, pass the recovered keypair as the
[BUFFER_SIGNER] to `solana program deploy` or `solana write-buffer'.
Or to recover the account's lamports, pass it as the
[BUFFER_ACCOUNT_ADDRESS] argument to `solana program close`.
===============================================================================
Error: Data writes to account failed: Custom error: Max retries exceeded

**Comment by t-nelson** [comment]
Hi! We don't use Github for support requests. Please join #developer-support on https://solana.com/discord instead
