### ISSUE TITLE
"io error: failed to fill whole buffer" while broadcasting a transaction

### ISSUE THREAD

**Issue by ahmadrezatmb** [solana-labs/solana#22599]
#### Problem
I'm getting this error while broadcasting a transaction:
`{'code': -32602, 'message': 'io error: failed to fill whole buffer'}`
It's weird that this happens for only specific destination addresses like this :`1NPjnxQJwFbnUC2oLPrs7FRRMpgRryc6kwYL1p6EfQu`. 
is there any solution for this problem ?

**Comment by t-nelson** [comment]
Hi! We don't use Github for support requests. Please join us in #developer-support on https://solana.com/discord instead
