### ISSUE TITLE
Failed to start test-validator on Apple Silicon M1

### ISSUE THREAD

**Issue by WojciechJelen** [solana-labs/solana#22600]
#### Problem
I have built and installed Solana from source, `ver 1.8.5`, on MacOS Monterey with Apple Silicon M1, and when I try to run `solana-test-validator --no-bpf-jit` I got this output with error:

```
Notice! No wallet available. `solana airdrop` localnet SOL after creating one

Ledger location: test-ledger
Log: test-ledger/validator.log
Error: failed to start validator: TestValidator startup failed: Custom { kind: Other, error: "Discover failed" }
```
Installation went smoothly without any errors.

**Comment by mvines** [comment]
Please try the 1.9.4 release and reopen if you still run into an issue. The 1.8 release line has incomplete support for M1s.

**Comment by mvines** [comment]
Following https://docs.solana.com/cli/install-solana-cli-tools on an M1 will get you native binaries as well, no Rosetta needed anymore
