### ISSUE TITLE
Failed to start test-validator on Apple Silicon M1

### ISSUE THREAD

**Issue by WojciechJelen** [solana-labs/solana#22618]
#### Problem
When I  try to run `solana-test-validator `, I get the following terminal output with error:
```
--faucet-sol argument ignored, ledger already exists
Ledger location: test-ledger
Log: test-ledger/validator.log
Error: failed to start validator: TestValidator startup failed: Custom { kind: Other, error: "Discover failed" }
```
I've tried with both installation ways: recommended- via curl and I have also built and installed from source  (both `ver 1.9.4`). 
No errors or warnings during both installations.

**Comment by 19-xiaogao** [comment]
I have the same problem. 
I solana version number : solana-cli 1.9.4.
run `solana-test-validator`:

Ledger location: test-ledger
Log: test-ledger/validator.log
Error: failed to start validator: Failed to create ledger at test-ledger: blockstore error

**Comment by t-nelson** [comment]
Hi! We don't use github for support. Join us in #developer-support on https://solana.com/discord instead
