### ISSUE TITLE
Transaction takes too long

### ISSUE THREAD

**Issue by torugor** [solana-labs/solana#22631]
#### Problem

I am trying to make a token transaction.

Every attempt brings back this message:
Error: Transaction was not confirmed in 60.00 seconds. It is unknown if it succeeded or failed. Check signature 2k2WVcy3u7Q5CGDG1c6sG2JWjgm6hTd6c3UWoCSeHFfsKaKLeNBazNgTLKSHS4iZaPFiM3mgXLL3GqcNc4MW1ayj using the Solana Explorer or CLI tools.

This message used to come in a random way...sometimes more often sometimes didnt come at all and transaction was completed as supposed to be.

But latelly it has come more and more...and begins to be more likelly a transaction dont happen than that it happen.

**Comment by jacobcreech** [comment]
@torugor We do not serve tech support of Github. Please visit us at www.solana.com/discord
