### ISSUE TITLE
Is Solana really schedule all the non-overlapping transactions in parallel?

### ISSUE THREAD

**Issue by DashYang** [solana-labs/solana#22678]
#### Problem
it seems repo sealevel is empty. and I can't find any associated code to prove that bank.rs has thread pool to process non-overlapping transactions in parallel. so is it not implemented yet?

#### Proposed Solution
none

**Comment by sakridge** [comment]
For replay you can see here the blockstore_processor executes batches in parallel:

https://github.com/solana-labs/solana/blob/fd0f5e4d1291dc36c349165a586e64188e794b6c/ledger/src/blockstore_processor.rs#L264

For generation, you can see there are multiple banking threads executing the block transactions:
https://github.com/solana-labs/solana/blob/fd0f5e4d1291dc36c349165a586e64188e794b6c/core/src/banking_stage.rs#L364

**Comment by DashYang** [comment]
`bank_thread_hdls` seems have many threads. each of them receives a transaction batch and process it. they will find an available bank to process a batch of transactions. do these banks process transactions in parallel while these banks are not aware of other banks' transactions? Besides every bank will lock transaction's accounts like:
https://github.com/solana-labs/solana/blob/fd0f5e4d1291dc36c349165a586e64188e794b6c/core/src/banking_stage.rs#L1020
so bank will not process those `AccountInUse` transactions immediately but process them later. why bank just processes those transactions are not `AccountInUse` in parallel? Sealevel says that:
"Schedule all the non-overlapping transactions in parallel."
not `AccountInUse` transactions seems non-overlapping.  can these transactions be processed in parallel? 

Besides, blockstore_processor seems do not lock transaction's accounts.  why?
