### ISSUE TITLE
Webwallet transfer lamports instead of sols

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#2267]
Depends-on: #160, specifically the SDK API changes to support this

**Comment by garious** [comment]
@mvines, planning to squeeze this into Beacons?

**Comment by mvines** [comment]
Not in a big rush to do this, seems a little peripheral to the v0.12 release goals

**Comment by garious** [comment]
On second thought, we might consider Sols being purely a `solana-token` concept. It could be special-cased to use its lamports instead of its account data to implement the ERC20 interface. @aeyakovenko?

**Comment by aeyakovenko** [comment]
@garious, that is one of the biggest complaints about ethereum, that eth/wei are not native erc20’s.

**Comment by mvines** [comment]
I think the path to resolving this issue is to just have a switch in the example-webwallet that allows the user to work in lamports or SOLs (eg, Celsius or Fahrenheit).   But along the way it would be nice to see some conversion helper functions added into https://github.com/solana-labs/solana-web3.js to avoid having to have the example-webwallet client write its own conversion logic.

**Comment by aeyakovenko** [comment]
@mvines the bigger issue is similar to the problem that Ethereum has.  Account's lamports are in the *kernel*.  User defined Tokens are in *userspace*.  

The wallet needs to be aware of the Account's lamports only when dealing with contract state management, but for general purpose tokens it should deal with the *userspace* representation of sols.   We are lacking a general purpose token ABI to allow that.

**Comment by mvines** [comment]
Right. But that bigger issue is well outside the bounds of this particular issue.

So you suggest we just close *this* issue then?

**Comment by aeyakovenko** [comment]
@mvines no, thats fine.  WebWallet should display sols instead of lamports.  kick the token can down the road :)

**Comment by jstarry** [comment]
https://github.com/solana-labs/example-webwallet is archived now
