### ISSUE TITLE
Accountsdb plugin does not know about accounts being closed

### ISSUE THREAD

**Issue by ckamm** [solana-labs/solana#22685]
#### Problem
The accountsdb plugin receives information about account writes. However, when an account's lamports are reduced to 0, the plugin receives no information about that.

This makes connected services go out of sync for these closed accounts.

#### Proposed Solution
Either send an account write message with 0 lamports for closed accounts, or add a new kind of callback for account closure.

@lijunwangs

**Comment by lijunwangs** [comment]
Thanks for your finding. I will look into it.

**Comment by ckamm** [comment]
@lijunwangs To expand on this: My accountsdb plugin filters writes by program pubkey.

After speaking to @m30m it seems likely that the write that withdraws the lamports also automatically changes the account owner to the system program. Then this would not be a solana accountsdb plugin interface issue.

Nevertheless, it means that plugins should generally also look at writes for accounts owned by the system program to be able to catch this kind of event. Maybe add to documentation?

**Comment by ckamm** [comment]
Note that writes for the system program/lamports=0 are not sufficent since the account may be reassigned to another program in the same tx.

**Comment by Arrowana** [comment]
This might be the same problem as listening over websocket on the json rpc. It is quite spaghetti to handle because you can listen to all program owned accounts but if you really want all the changes (returning the account to the system program for instance) then you also need to listen to individual account changes...

**Comment by ckamm** [comment]
Yeah, I think technically this works as-designed, but is inconvenient to users.
