### ISSUE TITLE
Solana Beginners Blog Post Results in 404

### ISSUE THREAD

**Issue by whiskeylips** [solana-labs/solana#22695]
#### Problem
Chrome  97.0.4692.71 Windows 10 64 bit

Clicking the solana beginners blog post results in a 404. You can find the page by "opening in a new tab", but it isn't a great first impression. 

Happy to fix it; point me in the right direction. 

#### Proposed Solution
<img width="901" alt="Capture" src="https://user-images.githubusercontent.com/87833655/150692385-3cc8a610-602b-47e3-a60b-2c22fb74d498.PNG">
<img width="901" alt="Screenshot 2022-01-23 101509" src="https://user-images.githubusercontent.com/87833655/150692386-8e9a4b2c-af82-4877-af56-db78782c1eb0.png">

**Comment by Shubham0850** [comment]
I have checked it, It's working fine.

**Comment by steviez** [comment]
Working fine for me as well
