### ISSUE TITLE
Remove transaction statuses from status cache

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#22710]
#### Problem
The bank status cache is primarily used to prevent recent transactions from being replayed but is also used by RPC to retrieve the execution status of recent transactions. The status of recent transactions are already stored in blockstore (when `enable_rpc_transaction_history` is enabled) so storing the status in memory is redundant.

#### Proposed Solution
- Migrate from the `BankStatusCache` (which stores the message hash, signature, and status for each transaction) to a `RecentTransactionCache` (which only stores message hashes of transactions processed in each fork).
- Remove `get_signature_status` methods from `Bank` and have RPC query blockstore instead

**Comment by jstarry** [comment]
cc @carllin @CriesofCarrots thoughts? Seems like it could help speed up bank squashing and reduce memory pretty substantially

**Comment by carllin** [comment]
This makes sense to me, if the only people using `get_signature_status` is over RPC and nothing in core will be slowed down.

What are the savings here? `type BankStatusCache = StatusCache<Result<(), TransactionError>>;`, so we save a sizeof that result per entry? Is that small compared to the hash?

**Comment by jstarry** [comment]
> What are the savings here though? `type BankStatusCache = StatusCache<Result<(), TransactionError>>;`, so we save a sizeof that result per entry? Is that small compared to the outer blockhash, the inner 20-byte keyslice of the signature, etc?

Yeah, looks like for each tx we save [40 bytes](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=33d2fc05e1e0a8d01c8a1bd4bd59c9da) for the status and 20 bytes for the signature slice.

**Comment by CriesofCarrots** [comment]
Hey, sorry for the slow reply. My main concern here would be the change in speed for clients to get signature statuses. We know from other calls that depend on Blockstore (getBlock, etc) that it can take a while to write all the transaction status metadata. With this change, `get_signature_status` RPC and `signatureSubscribe` pubsub will have to wait to return until that write is complete. Those are I think the methods that users most likely expect/need a quick response.
That said, perhaps the plugin/streaming implementation can meet this need.

There may also be node operators that support `get_signature_status` without `enable_rpc_transaction_history`; clients who are interested in recent history only. This change will break them. But I suppose that may be another need that the plugin/streaming implementation can meet.

**Comment by jstarry** [comment]
I'm curious how many of those clients use confirmed vs processed. If it's just confirmed, we can create a new simpler cache for RPC to use for low latency lookups.

**Comment by CriesofCarrots** [comment]
My gut says the vast majority use confirmed commitment, but we can probably ask RPC service providers if they have any data on that.
