### ISSUE TITLE
solana-web3.js: Support withdraw from Vote account

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#22722]
#### Problem
Solana-web3.js does not support any vote instructions. Some users would like to use them; withdraw, at least.
More specs and context to come

#### Proposed Solution
Implement Vote withdraw (and other ix?) in ts

**Comment by mooori** [comment]
> More specs and context to come

Similar to [`stake-program.ts`](https://github.com/solana-labs/solana/blob/master/web3.js/src/stake-program.ts)? A new class `VoteProgram` with (at least) a `withdraw` method constructing a transaction for [`VoteInstruction::Withdraw`](https://docs.rs/solana-vote-program/1.9.5/solana_vote_program/vote_instruction/enum.VoteInstruction.html#variant.Withdraw).

If that's it, I would like to work up a PR.

**Comment by CriesofCarrots** [comment]
> Similar to [`stake-program.ts`](https://github.com/solana-labs/solana/blob/master/web3.js/src/stake-program.ts)? A new class `VoteProgram` with (at least) a `withdraw` method constructing a transaction for [`VoteInstruction::Withdraw`](https://docs.rs/solana-vote-program/1.9.5/solana_vote_program/vote_instruction/enum.VoteInstruction.html#variant.Withdraw).

@mooori , yes, exactly, plus a decoder to parse a `withdraw` TransactionInstruction. A PR providing those things would be very welcome.

Decoders to parse other Vote instructions might be useful as well. Up to you whether you want to include those in your PR. (I don't think we need TransactionInstruction constructors for the other Vote instructions, though.)

**Comment by mooori** [comment]
Thanks @CriesofCarrots, I will get at it and try to add decoders for other Vote instructions as well.
