### ISSUE TITLE
New Solana CLI Program Deployment Ouput Removed Progress Bar As Of 1.9.x

### ISSUE THREAD

**Issue by bonedaddy** [solana-labs/solana#22736]
#### Problem

Between 1.8.x and 1.9.x the output from `solana program write-buffer` was changed. Instead of being this beautiful progress bar seen below:

![Peek 2022-01-25 12-21](https://user-images.githubusercontent.com/17089485/151053389-e00f6159-8941-46da-8b5c-380be6e2edd5.gif)

It was changed to just spam your console as seen below:
![bad](https://user-images.githubusercontent.com/17089485/151053095-e3e63f7f-50d4-492b-b122-85ceb03a21e5.gif)

#### Proposed Solution

Bring the progress bar back, or at least have it be the default. The spam generated by the current command is pretty much useless as it gives no useful information.

**Comment by bigdefidev** [comment]
Please!

**Comment by t-nelson** [comment]
Maybe some variant of https://github.com/solana-labs/solana/issues/16449
