### ISSUE TITLE
edge testnet deployment was failing due to "Validators make a transaction to advertise their storage last_id"

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#2274]
On the tip of master, run
```bash
$ cd net/
$ ./gce.sh create -n 3 -c 0
$ ./net.sh start
$ ./net.sh sanity
```
The network will fail to start, eg:
* https://buildkite.com/solana-labs/testnet-management/builds/9029#06007229-ad95-4062-bc93-11e004f3c58a
* https://buildkite.com/solana-labs/testnet-management/builds/9005#55176858-f7a4-43cf-a47c-f5b26f18a09e
* https://buildkite.com/solana-labs/testnet-management/builds/8990#9056a107-25bf-4a15-893b-24d208449fbe

**Comment by mvines** [comment]
2d635117425ee4f305e0349e7f585c6d4aac2c0b looks like the prime suspect

**Comment by mvines** [comment]
@sakridge sorry I had to back out your commit.  Let me know if I can help debug further

**Comment by sakridge** [comment]
No problem. I'll take a look.

**Comment by mvines** [comment]
Resolved
