### ISSUE TITLE
Clone multiple nets when starting `solana-test-validator`

### ISSUE THREAD

**Issue by bmeeder22** [solana-labs/solana#22760]
#### Problem
Currently the `solana-test-validator` can only clone accounts from a single net defined by the `--url` parameter. Attempting to startup the `solana-test-validator` on a already existing ledger silently skips cloning accounts, which means it is impossible to clone accounts from both `devnet` and `mainnet` into a `solana-test-validator` if needed. 

#### Proposed Solution
Allow the ability to set multiple `--url` parameters and any `--clones` AFTER a given url will be cloned from that RPC node.

**Comment by bmeeder22** [comment]
Here is where we are cloning the accounts on the solana test validator. All that needs to happen is better parsing of the command arguments to be able to call this function multiple times with different nets: https://github.com/solana-labs/solana/blob/05624266613c11150d717d72c69afac4151cac5f/validator/src/bin/solana-test-validator.rs#L620

**Comment by mvines** [comment]
Making the position of `--url` vs `-clone` significant seems like a bit of a foot gun, I feel a better cli interface could be wrapped around this.  But the feature idea seems nice though!

**Comment by bmeeder22** [comment]
Totally agree that the position is a foot gun, just figured it would be the easiest to implement.

**Comment by Arrowana** [comment]
Seems a bit edge case and that can be fixed by downloading with `solana account ...` then `solana-test-validator --account <ADDRESS> account.json`

An example even mutating an account before loading it https://gist.github.com/Arrowana/3fab798862153ff3d36b6300d2440d02
