### ISSUE TITLE
`getrandom` and `rand_core` crate unexpected compilation behaviour

### ISSUE THREAD

**Issue by lilses** [solana-labs/solana#22810]
#### Problem
I `cargo tree` and see `getrandom:0.1.16` is depended on by solana somewhere as `cargo update -p getrandom:0.1.16 --precise 0.2.4
`  will confirm.

****
`solana-program = {version="1.9.5"}`
Import `getrandom = {version="0.2.4", features=["custom"]}`
When I import `rand_core = { version = "0.5", default-features = false }`, it fails.
When I import `rand_core = { version = "0.6", default-features = false }`, it works.
****

`solana-program = {git="https://github.com/solana-labs/solana"}` // version 1.10
Import `getrandom = {version="0.2.4", features=["custom"]}`.
When I import `rand_core = { version = "0.5", default-features = false }`, it works.
When I import `rand_core = { version = "0.6", default-features = false }`, it works.

This looks like a bug somewhere in the dependencies or feature toggles. It's not clear why this is happening and not expected.

**Comment by yiranlandtour** [comment]
random is not suported yet
