### ISSUE TITLE
Empty field (transactions -> meta) when upgrading from `v1.9.4` to `v1.9.5`

### ISSUE THREAD

**Issue by maurodelazeri** [solana-labs/solana#22821]
#### Problem

After upgrading from `v1.9.4` to `v1.9.5` the field `transactions - > meta` is null

```shell
curl -s -H 'Content-Type: application/json' -d '{"method":"getBlock","jsonrpc":"2.0","params":[110866597, {"encoding": "jsonParsed", "transactionDetails": "full", "rewards": false}]}' 127.0.0.1:8899 | jq '.result.transactions' | grep meta
```

```json
{
    "jsonrpc": "2.0",
    "result": {
        "blockHeight": 106567831,
        "blockTime": 1643386547,
        "blockhash": "3TpFJC6KcZDJnHFby8kcjH8E2aBTpNZn7JhWH5HDhncB",
        "parentSlot": 110866596,
        "previousBlockhash": "8WCv1LaJ7d4E8x8b4jCMDeb4zELFPs1LkcFnEpZKY7ur",
        "transactions": [
            {
                "meta": null,
```

removing the ledger and downgrading the client to `v1.9.4` solves the problem

**Comment by t-nelson** [comment]
I'm not seeing any obvious changes between v1.9.4 and v1.9.5 that should have this effect.  Are you changing your command line arguments in any way during up/downgrade?

**Comment by maurodelazeri** [comment]
nope... the upgraded was done with `solana-install init v1.9.5` and resting the client... when downgrading `solana-install init v1.9.4` but it kept returning `null` so I wiped the ledger folder and restarted again and all good
