### ISSUE TITLE
Solana Ping JSON Output Doesn't Work

### ISSUE THREAD

**Issue by brianlong** [solana-labs/solana#22832]
#### Problem
`solana ping --output json` does not return JSON.

#### Context
I am planning a "Ping Thing" feature on validators.app to collect Solana TX confirmation times from volunteers. We will host a REST endpoint for data gathering and downloading confirmation times. (This may sound familiar to some of you who have been around for a while -- the first version of validators.app was built to collect network ping times between validators.)

In thinking about how to aggregate data, it will be nice for volunteers to run the standard "solana ping" CLI command and pipe the JSON output to a data collection endpoint on validators.app. I think it will be much easier to recruit volunteers if there is minimal/no requirement to install additional software.

I think we might also create some examples for apps to submit data from their web3 clients too.

#### Proposed Solution
Do awesome things and make "-output json" work as expected.

**Comment by brianlong** [comment]
Also, with the ping CLI command, where does the 1 Lamport go? I mistakenly thought that it was sent back to the originating wallet.

**Comment by mvines** [comment]
> Also, with the ping CLI command, where does the 1 Lamport go? I mistakenly thought that it was sent back to the originating wallet.

Prior to this [1] change (ie, v1.8 and current v1.9 releases), the 1 lamport is sent to a derived address and disappears.  But going forward it will be sent back to the sender

[1] https://github.com/solana-labs/solana/pull/22657

**Comment by CriesofCarrots** [comment]
Fair request. Someday, I hope we finally have all the cli things return valid JSON.
@mvines , thoughts on backporting #22657 to v1.8? It's not strictly needed there for rent purposes, but also wouldn't hurt
