### ISSUE TITLE
Can't install Solana-Cli

### ISSUE THREAD

**Issue by LPbigFish** [solana-labs/solana#22831]
Hi, I am trying to install Solana-Cli on my VPS, but error comes up right after I try the easy way:

""
downloading stable installer
curl: (22) The requested URL returned error: 403 
solana-install-init: command failed: downloader http://release.solana.com/stable/solana-install-init-aarch64-unknown-linux-gnu /tmp/tmp.i5gAY8hgrk/solana-install-init
""

I have tried to build from source, but same thing happend:

""
Error: "Unable to parse \"/tmp/.tmpqnJy1P/download\": Message(\"invalid type: string \\\"<?xml version=\\\\\\\"1.0\\\\\\\" encoding=\\\\\\\"UTF-8\\\\\\\"?> <Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>EP51XCJ36BD1PWJW</RequestId><HostId>EsmpQp5jLQNiCT8SVCHEnUFkGYwL6CdB9bli164o5MFRxtWkVML9m9nj+okGMOexO+b1tzyb0Gw=</HostId></Error>\\\", expected struct ReleaseVersion\", Some(Pos { marker: Marker { index: 0, line: 1, col: 0 }, path: \".\" }))"
""

My VPSs architecture is aarch64.

Any ideas how to fix this issue?

**Comment by mvines** [comment]
We have no binaries for linux aarch64, you’ll need to build from source instead for that arch.
