### ISSUE TITLE
Missing blocks in long term storage

### ISSUE THREAD

**Issue by avolkov-dev** [solana-labs/solana#22840]
I am developing integration with solana blockchain and observed number of missing blocks in public testnet node (https://api.testnet.solana.com) and explorer:
- When block is missed in explorer there is `Failed to fetch block` [page ](https://explorer.solana.com/block/114698958?cluster=testnet).
- Node respond with `Slot xxx was skipped, or missing in long-term storage` error.
```
curl --location --request POST 'https://api.testnet.solana.com' \
--header 'Content-Type: application/json' \
--data-raw '{"method":"getBlock","params":[114698958,{"encoding":"json"}],"jsonrpc":"2.0","id":0}'
```
```
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32009,
        "message": "Slot 114698958 was skipped, or missing in long-term storage"
    },
    "id": 0
}
```
Our current indexing algo reads blocks sequentially to detect new transactions related to our addresses and cannot handle gaps in blockchain.

note: 
Interesting that block 114698958 was present in node and blockchain and now disappeared- i have unit test related to this block, that were passing some time ago, but failing now.

Could you point me to the documentation related to missing blocks and proposed solution on how to handle this scenario, please?
In issue https://github.com/solana-labs/solana/issues/21350 i see people posting block number and they are manually fixed, but this is not the way to go right?

**Comment by t-nelson** [comment]
We do not offer as stringent an SLA on testnet historical data.  Missing blocks are considered acceptable.

If further support is needed, please join us in #developer-support on https://solana.com/discord
