### ISSUE TITLE
Temporary failure in name resolution

### ISSUE THREAD

**Issue by ovuruska** [solana-labs/solana#22886]
#### Problem
[2022-02-02T09:15:28Z WARN  metaboss] Using a public RPC URL is not recommended for heavy tasks as you will be rate-limited and suffer a performance hit.
            Please use a private RPC endpoint for best performance results.
Error: error sending request for url (https://api.mainnet-beta.solana.com/): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution

Caused by:
    0: error sending request for url (https://api.mainnet-beta.solana.com/): error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
    1: error trying to connect: dns error: failed to lookup address information: Temporary failure in name resolution
    2: dns error: failed to lookup address information: Temporary failure in name resolution
    3: failed to lookup address information: Temporary failure in name resolution

#### Proposed Solution
I don't have one yet.

**Comment by Hangman2arb** [comment]
Same problem!

**Comment by t-nelson** [comment]
That error implies a client side network configuration problem, not a problem with any solana resources
