### ISSUE TITLE
Implement Sysvar trait for Instructions

### ISSUE THREAD

**Issue by armaniferrante** [solana-labs/solana#22911]
It would be nice to implement the `Sysvar` trait for the [Instructions](https://github.com/solana-labs/solana/blob/master/sdk/program/src/sysvar/instructions.rs#L17-L18) sysvar, so that we can use it with the `Sysvar<T>`  type in Anchor, which will automatically assert the account address. Currently we are required to use `UncheckedAccount` (an alias for AccountInfo) with an address constraint, for example,https://github.com/project-serum/anchor/blob/master/tests/cfo/programs/cfo/src/lib.rs#L525-L526.

**Comment by aeyakovenko** [comment]
tag @jackcmay

**Comment by jackcmay** [comment]
The `Instructions` sysvar doesn't deserialize to a specific type like the others.  Instead, it deserializes based on an index that the `Sysvar` trait does not support.  What did you have in mind?

**Comment by jackcmay** [comment]
Similar to: https://github.com/solana-labs/solana/issues/17017
