### ISSUE TITLE
signal: 7, SIGBUS: access to undefined memory

### ISSUE THREAD

**Issue by joelnet** [solana-labs/solana#22944]
#### Problem

When running any of the following commands the command:

```
anchor test
anchor build
cargo +bpf build --target bpfel-unknown-unknown --release
```

I receive the error message:

```
error: process didn't exit successfully: `rustc -vV` (signal: 7, SIGBUS: access to undefined memory)
```

I am unable to build and unsure how to proceed. Any help appreciated!

**Comment by t-nelson** [comment]
Hi!  We don't use Github for support and further, Anchor is unrelated to this repository.  Please seek help via Anchor channels
