### ISSUE TITLE
web3.js: unused call to `_verifySignatures` in `Transaction.sign`

### ISSUE THREAD

**Issue by kevinheavey** [solana-labs/solana#22966]
#### Problem

Apologies if I've misread the code, but it looks like the `sign` method on the `Transaction` class has a line of code that doesn't achieve anything: https://github.com/solana-labs/solana-web3.js/blob/master/src/transaction.ts#L476

It calls `_verifySignatures` but it doesn't use the result, and `_verifySignatures` seems to have no side effects.

#### Proposed Solution

Delete this line or use the result of `_verifySignatures` somehow.

**Comment by KartikSoneji** [comment]
Just noticed this, and I agree it doesn't seem to be doing anything.

**Comment by kevinheavey** [comment]
I notice this was fixed by @steveluscher  in https://github.com/solana-labs/solana/pull/25302. Thanks Steve!
