### ISSUE TITLE
web3.js library doesn't support passing AbortController's signal

### ISSUE THREAD

**Issue by tomland123** [solana-labs/solana#22971]
#### Problem
I am building a website that uses infinite scroll and I do not want to see stale data from my rpc node appear on my UI due to a race condition. As of late 2017, https://developer.mozilla.org/en-US/docs/Web/API/AbortController has become the accepted standard to cancel api requests in the browser.

#### Proposed Solution

Functions in the Web3 library api should expose an additional Web3Config parameter to pass in options that support commonly supported features like AbortController. This would also be useful if you wanted to pass in custom auth parameters as well on a per function basis etc.

**Comment by steveluscher** [comment]
100% agree.

* Tracking this for `confirmTransaction` specifically in https://github.com/solana-labs/solana/issues/25304
* Generally this will be a principle that will guide the rewrite of web3.js (see principle 8) #25314
