### ISSUE TITLE
Should explorer ignore token-list for executable accounts?

### ISSUE THREAD

**Issue by leoluk** [solana-labs/solana#22980]
#### Problem

A confused user renamed the token program:

<img width="878" alt="image" src="https://user-images.githubusercontent.com/859697/152785238-8deb5acc-b981-41e1-a165-d89782edc9f6.png">

- https://github.com/solana-labs/token-list/commit/1a47919bb2a8c99f286537ac3705b2f4b8aae488

#### Proposed Solution

Ignore token-list for anything that isn't a token?

**Comment by t-nelson** [comment]
> Ignore token-list for anything that isn't a token?

Yes.
