### ISSUE TITLE
unable to get program data when deploy using --bpf-program

### ISSUE THREAD

**Issue by eduardotang** [solana-labs/solana#23004]
#### Problem
solana log will give
Custom program error: 0xbc4
when trying to get program data account

solana-test-validator 1.9.5

please refer to [project-serum/anchor#1400](https://github.com/project-serum/anchor/issues/1400#issuecomment-1031936503)

**Comment by t-nelson** [comment]
Hi!  We don't use Github for support.  Join us in #developer-support on https://solana.com/discord instead
