### ISSUE TITLE
Vote instruction requires passing sysvar account when it no longer needs to

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#23060]
#### Problem

The vote program no longer relies on the pass in sysvar accounts but does not support an instruction version that doesn't require them.  Processing/passing these accounts takes time.

#### Proposed Solution

Expose a new vote instruction that does not require the sysvar accounts

**Comment by mvines** [comment]
An alternative to a new instruction would be to just add a feature that causes the vote program to ignore the sysvars into the existing instructions.  Then once that feature is flipped on, the client-side can be updated to stop including the sysvars

**Comment by jackcmay** [comment]
The vote program already ignores the incoming sysvar accounts and pulls it from `invoke_context`.  But the runtime has to process/generate/pass along these sysvar accounts in the vote instruction.  We can get rid of those pieces too with a new instruction

**Comment by jackcmay** [comment]
Ah, yeah, that would have been cool
