### ISSUE TITLE
Move bad sig test to tpu.rs

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#231]
There's a test in `thin_client.rs` that ought to be in `tpu.rs`. It was put into the thin client module because that library makes it easy to create and send transactions to the server. It'd be even easier if we moved the TPU's composition of SigVerifyStage, BankingStage, and RecordStage into a a separate function. The you can use `packet::to_packets()` to create data for the `packet_receiver` channel, and then check for the expected out put on the `signal_receiver`. No need to mess with UDP sockets and potential timeouts.

https://github.com/solana-labs/solana/blob/4badeacd1dc14515d198385f59a36e8861b9d7ce/src/thin_client.rs#L248

**Comment by mvines** [comment]
`test_bad_sig()` no longer exists
