### ISSUE TITLE
Transactions Record at testnet disappear with no reason

### ISSUE THREAD

**Issue by jiayih1212** [solana-labs/solana#23115]
#### Problem
Recently, I realize many testnet token's transaction records will disappear after 2 days, is there anyone know about this type of issue? Normally, those transactions records which include mintTo, createAccount, transfer should stay there for record. 

I have check on the other testnet token and realize many of the tokens transaction records start missing within 15 January until now. For example :  MetaMalls (Testnet)， BiG Coin (Testnet), USD Coin, Singularity, Singularity DAO, Bouncing Cat Token

**Comment by t-nelson** [comment]
There is no SLA on transaction history for testnet.  We just don't care.   Feel free to run your own archival with stronger guarantees  there if you think it's valuable
