### ISSUE TITLE
Multiple validator info accounts created for one validator

### ISSUE THREAD

**Issue by michaelh-laine** [solana-labs/solana#23133]
#### Problem
Validator SoLiDDAQBEK1LK8apZcZqY7FunqeqDY6nYXMabQZvPB has two validator info accounts:
```
$ solana validator-info get | grep -A3 SoLiDDAQBEK1LK8apZcZqY7FunqeqDY6nYXMabQZvPB
Validator Identity: SoLiDDAQBEK1LK8apZcZqY7FunqeqDY6nYXMabQZvPB
  Info Address: H4hqVttu3AXbUZeUGtV5hxQRg1VUDMXdMzz84P76PLhN
  Keybase Username: dobrician
  Name: SoLiD - NO FEES
--
Validator Identity: SoLiDDAQBEK1LK8apZcZqY7FunqeqDY6nYXMabQZvPB
  Info Address: 4En2EzuCGjsXDAmWpecmQz2Z2sBrPZAfrDqP35qcTUhu
  Keybase Username: dobrician
  Name: SoLiD
```
When using `solana validator-info publish` there is anoption to pass a keypair to which to publish but the CLI first checks and uses an existing keypair. The CLI will check for an existing info key, if none exists it will create a new keypair. It appears that in this case the check for an existing keypair failed resulting in a new one being created and the information being published to that one.

The relevant code is at https://github.com/solana-labs/solana/blob/master/cli/src/validator_info.rs#L266:L279

Could be the GPA RPC query failing in very rare circumstances?

#### Proposed Solution
Not sufficiently familiar to propose a solution, I'd expect perhaps better handling to identify if the RPC query failed vs the result not containing the key.

**Comment by ruuda** [comment]
This also relates to #20593 — it is implementation-dependent how these multiple config accounts are handled. A proper solution would be to abandon the config accounts and put the validator details in the identity account; it would also sidestep a few current footguns in the current design.

**Comment by michaelh-laine** [comment]
> This also relates to #20593 — it is implementation-dependent how these multiple config accounts are handled. A proper solution would be to abandon the config accounts and put the validator details in the identity account; it would also sidestep a few current footguns in the current design.

Is this possible with the identity account currently being a "standard" account owned by the system program? one thing to consider, albeit minor and solvable, is that stake pools use the config program/validator info methodology to publish pool name, etc for use on third party tracking sites, by using the pool manager's key

**Comment by CriesofCarrots** [comment]
The right answer is probably to transition to an on-chain validator info program that stores the details in a PDA derived from the identity account. The existing system predates PDAs 😅
