### ISSUE TITLE
rpc port 8899: Connection refused

### ISSUE THREAD

**Issue by 1scrooge** [solana-labs/solana#23138]
#### Problem
Hello. I have set up solana successfully,  but rpc mehtod curl failed. the 8899 port is not open.
is my cmd has  fault?
thats my cmd:
#!/bin/sh
solana-validator \
     --identity ~/validator-keypair.json 
    --vote-account ~/vote-account-keypair.json 
    --rpc-port 8899 
    --private-rpc 
    --known-validator 5D1fNXzvv5NjV1ysLjirC4WY92RNsVH18vjmcszZd8on
    --known-validator 7XSY3MrYnK8vq693Rju17bbPkCN3Z7KvvfvJx4kdrsSY
    --known-validator Ft5fbkqNa76vnsjYNwjDZUXoTWpP7VYm3mtsaQckQADN
    --known-validator 9QxCLckBiJc783jnMvXZubK4wH86Eqqvashtrwvcsgkv
    --only-known-rpc
    --dynamic-port-range 8100-8120
    --entrypoint entrypoint.testnet.solana.com:8001
    --entrypoint entrypoint2.testnet.solana.com:8001
    --entrypoint entrypoint3.testnet.solana.com:8001
    --limit-ledger-size \
    --no-voting \
    --log /data/solana-node/solana-validator.log \
    --ledger /data/solana-node/ledger/

![image](https://user-images.githubusercontent.com/32951007/154007283-335cb3d3-000d-46bd-a4ec-9f5d7ddd2a00.png)

I've asked in Discord, but there couldn't help me

**Comment by lijunwangs** [comment]
Make sure the validator has started fully (after restoring from snapshot) before you try the connection.

**Comment by t-nelson** [comment]
Hi. We don't use Github for support requests.  Please join us in #validator-support on https://solana.com/discord instead
