### ISSUE TITLE
Out of process ETL

### ISSUE THREAD

**Issue by parv0888** [solana-labs/solana#23144]
#### Problem
No clear way to port the data out of validator process and into an out of process indexer / processor. 
The validator does a lot of work and the core code should not be the place to add hooks to and try to read the information. 
as i see there are multiple changes (committed & in-progress) by @lijunwangs trying to get the data out. 

#### Proposed Solution
We should setup a base framework where every piece of information
Bank (Block), Slot, Account, Transaction information should be published for an out of the process to get access to. 
We should be able to use Unix Sockets or any other socket protocol for this purpose so that any process listening on it (which may be not coded in rust) can make use and distribute the data as needed.

**Comment by t-nelson** [comment]
This can be built fairly easily atop Lijun's binary plugin work.  It's not clear to me what the ask is here or why what's being provided today is insufficient

**Comment by lijunwangs** [comment]
Hi @parv0888 -- You can write your own plugin if you would like local Unix socket support. Please see https://docs.solana.com/developing/plugins/accountsdb_plugin. https://github.com/ckamm/solana-accountsdb-connector
 is a community example of doing that.

**Comment by parv0888** [comment]
@t-nelson , @lijunwangs  - thanks for a prompt reply. 
i will be writing code for the same. 
What i mean here is that the current docs mandate us to write plugins in Rust. Which should not be a requirement and writing a Unix Socket interface would allow anyone with any background in development to easily use that interface and build anything over it. 

@t-nelson 
in my specific use case which im currently trying to write 
I want a way to get notified (through the plugins) of all the bank updates (`Root`, `Frozen`, `Optimistically Confirmed`, `Created`, `Updated`, `Pruned`) and not just the status updates
Where as looking at the code as i saw only `Optimistically Confirmed` banks are being notified through the plugin.
