### ISSUE TITLE
validator: `--only-known-rpc` is ignored when `--no-snapshot-fetch` is passed

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#23179]
#### Problem

We ignore `--only-known-rpc` when `--no-snapshot-fetch` is passed.

https://github.com/solana-labs/solana/blob/577fa4ec0cd1b0a3362001e577ded671c0e7070d/validator/src/bootstrap.rs#L685-L698

#### Proposed Solution

In master, filter the list before checking `--no-snapshot-fetch`.

In <= 1.9, prolly leave it.  Shit's three frames lower and embedded in the snapshot resolution logic

**Comment by BGZHU1** [comment]
Hello @t-nelson, I created a PR for this, let me know if this fix works :)
