### ISSUE TITLE
Remove exit variable from all stages

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#232]
To gracefully shutdown a thread, just drop all its input channels. There's typically only one.

Getting rid of that variable would make stage tests more succinct with no loss of functionality.

**Comment by jackson-sandland** [comment]
@garious can you provide an example? I'd like to do this.

**Comment by garious** [comment]
Check out the tests in record_stage.rs.

**Comment by garious** [comment]
@jackson-sandland, I didn't get much further than you. :) .  #252

**Comment by jackson-sandland** [comment]
@garious curious how approached this. Taking a look :)

**Comment by bgorlick** [comment]
re: @garious comments

A stage listens to some receiver channel for data, processes it, and sends the processed data to its sender channel.

**Comment by garious** [comment]
My opinion here is that a stage should shut itself down if any of its channels are dropped. This would allow either an upstream or a downstream stage to signal the stage to shut down. UDP sockets can be accompanied by an `exit` variable to provide that functionality.

The value in getting rid of the exit variables is for a more predictable pipeline shutdown. Closing the first stage's input channel would signal all stages to shut down *after* the last input had been processed by *all* stages. Using an exit variables means that the TPU is left in an inconsistent state where, for example, the banking stage state may reflect transactions that were not broadcast by the write stage. In production, that shouldn't matter, because the process is about to exit, but for unit tests, I'd expect it to be an annoyance.

**Comment by aeyakovenko** [comment]
I think it attaches a behavior to a channel lifetime that is hard to debug.

**Comment by garious** [comment]
Expanding on my previous comments, instead of an `exit` variable, I think stages containing UdpSockets as their only inputs should be constructed with a `Receiver<()>` as well, and should shutdown if its corresponding `Sender` is dropped.

**Comment by aeyakovenko** [comment]
so service holds it for its join call?   i think the only gnarly problem there is ++ on services.  so a `impl Service for [Service]` .. which will land you in existential object hell

**Comment by garious** [comment]
Can you reword please?

**Comment by garious** [comment]
Per #557, down to 122 instances of the word `exit` in the codebase.
