### ISSUE TITLE
Possible (to be confirmed) Consensus (bank hash) mismatch with v1.9.8

### ISSUE THREAD

**Issue by steviez** [solana-labs/solana#23253]
#### Problem
One of our nodes was running `v1.9.8` and encountered the following:
```
solana_core::cluster_slot_state_verifier] Cluster duplicate confirmed slot 119324256
with hash AegBYCpY5ET8nmWKLWEGsWdFZWJMRHMZi6TrDeTQ2bzM,
but our version has hash B9zJTYie64wnexRt9se7d7c7X5JZDa9fLwRCCfaXYahm
```

Work in progress to confirm / reproduce / track down the issue

**Comment by jstarry** [comment]
I believe the issue is that v1.9.8 included this change: https://github.com/solana-labs/solana/pull/23240 which sets precompile owners to the native loader id. On testnet, the owner of the ed25519 precompile is the system program so v1.9.8 will not be able to reach consensus with v1.9.6 nodes.
