### ISSUE TITLE
Trent is Correct About --timeout <SECONDS>

### ISSUE THREAD

**Issue by brianlong** [solana-labs/solana#23251]
#### Problem
No, I don't have a problem saying that "Trent is Right":tm: ;-).

Trent suggests that using a timeout expressed in seconds can obscure actual confirmation times when the cluster is running slow. Using a short seconds-based timeout can also falsely lead a user to believe that a TX expired when it is still alive.

#### Proposed Solution
For the CLI, provide an alternative timeout switch where the parameter is the number of blocks. For example, `--timeout_blocks <INTEGER> (default 150 or expired block hash)`

Also, provide similar behavior for web3 in a separate PR.

**Comment by steveluscher** [comment]
Web3.js implemented this confirmation strategy in #24211
