### ISSUE TITLE
CLI Commands Assume Old RPC Retry Settings

### ISSUE THREAD

**Issue by brianlong** [solana-labs/solana#23250]
#### Problem
It appears that the CLI commands assume that the RPC server will retry a TX every 2 seconds until the TX lands or the block hash expires. The problem is that the RPC servers are now configured for minimal retries and rely on the client to retry TXs according to application-specific logic.

#### Proposed Solution
Create new 'default' retry logic for CLI commands, to mimic the old behavior from the client, and include some standard CLI switches to override the default settings.

Alternative Solution: Don't change the default retry logic, but do include CLI switches for control over RPC retries.

**Comment by CriesofCarrots** [comment]
Thanks for following up on this. I dug around too and looks like we did strip out basically all client-side retry logic.
I like the idea of CLI knobs. What do you think are reasonable defaults?
