### ISSUE TITLE
Unable to submit transactions on local cluster

### ISSUE THREAD

**Issue by sausage-dog** [solana-labs/solana#23258]
Had no issues with this yesterday, but today can't airdrop or deploy any programs. 

Every attempt gives me:

`Error: unable to confirm transaction. This can happen in situations such as transaction expiration and insufficient fee-payer funds` 

Tried restarting the cluster and reasserting config with `solana config set`.

Only command that works is `solana balance`.

**Comment by qpwo** [comment]
Going extremely slow and occasionally crashing for me

**Comment by qpwo** [comment]
Downgraded to 1.8.16 and everything is running smoothly

**Comment by godmodegalactus** [comment]
I am facing the same issue. What is the solution for this issue?

**Comment by qpwo** [comment]
I think you can still install 1.8.16
