### ISSUE TITLE
Include Solana version deprecation policy in docs

### ISSUE THREAD

**Issue by bausano** [solana-labs/solana#23264]
My understanding is that Solana mainnet cluster supports a range of versions against which we can compile our programs. For example, I have a program which I compile and test against version `1.7.15` and when I deploy it to mainnet, I can expect that it will be executed with the same context. Is my understanding correct?

I cannot immediately upgrade my program because of the change in compute unit budget calculation introduced in `1.8.x`, which renders some of my endpoints broken. What I would like to know is how long can I rely on my program working before the mainnet dumps the support for `1.7.15`. I would like to be able to find this information in docs on Backward Compatibility Policy

**Comment by jstarry** [comment]
> I cannot immediately upgrade my program because of the change in compute unit budget calculation introduced in 1.8.x, which renders some of my endpoints broken.

Can you share some more context on what you mean here? What compute unit budget calculation difference are you seeing? And do you mean "instructions" when you say your "endpoints"?

**Comment by bausano** [comment]
Thank you for your response.

The new version introduced at least these two relevant changes as far as I am aware:
- #18631;
- #22101.

And yes, by endpoints I mean transaction instructions.

**Comment by jstarry** [comment]
Those changes are not version specific, these changes are activated with a runtime feature activation which affectively hard forks the cluster to new runtime behavior.

**Comment by bausano** [comment]
I see, thank you. I suppose what my question boils down to: if my program works on `1.7.x` but not on `1.8.x`, can I expect it to work on mainnet?

**Comment by jstarry** [comment]
> I see, thank you. I suppose what my question boils down to: if my program works on `1.7.x` but not on `1.8.x`, can I expect it to work on mainnet?

It should basically always be the case that if you build and compile your program for a specific version of the `solana-program` crate, it will remain executable without behavior changes indefinitely no matter what version mainnet is on. However, the features you called out impact the amount of compute that will be used by a single program invocation. In order to mitigate any issues, users have the option to request more compute in their transaction to continue using existing on-chain programs.
