### ISSUE TITLE
Hi! We don't use Github for support. Join us in #developer-support on https://solana.com/discord instead

### ISSUE THREAD

**Issue by AsadullahSoomro** [solana-labs/solana#23297]
Hi! We don't use Github for support. Join us in #developer-support on https://solana.com/discord instead

_Originally posted by @t-nelson in https://github.com/solana-labs/solana/issues/23294#issuecomment-1048524921_

@t-nelson

**Comment by AsadullahSoomro** [comment]
![image](https://user-images.githubusercontent.com/46569970/155284658-943d3d0a-0f02-4da2-a55b-1dae26873185.png)
How can I post this issue in discord app

**Comment by t-nelson** [comment]
`#roles` (covered by the server menu) -> assign yourself the `@Developer` role.  Please stop making noise on Github.  People are trying to work.
