### ISSUE TITLE
[feature-request] make the `to_string` part of `sol_log_pubkey` public. / add `pubkey_to_string` syscall

### ISSUE THREAD

**Issue by paul-schaaf** [solana-labs/solana#23298]
#### Problem

We're in the process of adding better logging to anchor.  We'd like to log pubkeys in strings. For example: 
```
msg!("Expected pubkey: {}, Actual pubkey: {}", pubkey1, pubkey2)
```

This is extremely expensive. About 12K CU per `Pubkey::to_string` call.

#### Proposed Solution

But i found the `Pubkey::log` method which uses the `sol_log_pubkey` syscall and only costs ~300CU. At some point, `sol_log_pubkey` has to turn the pubkey into a string. My request is that a new syscall be added that just returns that string instead of logging it so we can take advantage of the lower CU cost.

**Comment by paul-schaaf** [comment]
If we got confirmation that such a feature would be accepted, we could create the PR ourselves.

**Comment by mvines** [comment]
I'd rather we first look at whether it's possible to better optimize the bpf codegen. Every new syscall is an additional attack surface.
