### ISSUE TITLE
WalletSendTransactionError: failed to send transaction: Node is behind by 45682 slots

### ISSUE THREAD

**Issue by best-lucky1030** [solana-labs/solana#23301]
When I tried to stake in my devnet wallet, this error was happened.

![image](https://user-images.githubusercontent.com/89365150/155314582-f6ffeaaa-48f2-4edf-a9c0-46ac94b428e3.png)

Why this error was occurred and what's the solution?

**Comment by terorie** [comment]
This is an issue with your RPC node provider. This is not a bug in the Solana node software. Please close

**Comment by t-nelson** [comment]
> This is an issue with your RPC node provider. This is not a bug in the Solana node software. Please close

Correct!

Additionally, we do not use Github for support requests.  Please join us in #developer-support on https://solana.com/discord
