### ISSUE TITLE
the account cannot send transactions

### ISSUE THREAD

**Issue by wkshare** [solana-labs/solana#23323]
I am learning Solana web3 sdk
I used the allocate command to set the data size for one of my accounts. allocated Data Size 18 byte(s)
When I use this account again, I get the above error.

#### Problem
SendTransactionError: failed to send transaction: Transaction simulation failed: This account may not be used to pay transaction fees

#### Proposed Solution
Please help me.
My Account Info:
https://explorer.solana.com/address/34USVFXvyy6DckMn7aHaZiN8gZZn4Lh572ShyVRjxEGk

Do you help me? and talke to me why. Thank you very much!!!

**Comment by t-nelson** [comment]
Hi! We don't use Github for support. Join us in #developer-support on https://solana.com/discord
