### ISSUE TITLE
solana-keygen accepts BIP32/44 non-compliant paths, generates erroneous pubkeys

### ISSUE THREAD

**Issue by alnoki** [solana-labs/solana#23341]
#### Problem

Static test seed phrase (without passphrase) for all below examples:

```
amateur they wash clutch then flat better voice echo such toward census
```

Running

```
solana-keygen pubkey prompt://\?full-path=m/44/501/0/0/0/0
```

returns

```
CWhy5pPbnBP85Fb4toVANMyFnbBJ8anpU8xKNQWRsKrD
```

and running

```
solana-keygen pubkey prompt://\?full-path=m/44/501/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0/0
```

returns

```
EtnFPdF5tDsyagZDRf6CFJdF88wexsqy7T4rKC49y5SW
```

Both exceed Depth = 3 per [BIP-0032](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki#Master_key_generation)

#### Proposed Solution

Raise error for derivation paths exceeding Depth = 3

**Comment by alnoki** [comment]
@CriesofCarrots mentioning you per your recent review of HD wallet path-related [pull request 23336](https://github.com/solana-labs/solana/pull/23336)

**Comment by t-nelson** [comment]
There is no depth limit of three.  Three is the recommended _minimum_ depth an implementation support for compatibility.

BIP32 allows for a depth of up to 256, given the key depth is encoded as a single byte.

[The Ed25519 adaptation of BIP32](https://drive.google.com/file/d/0ByMtMw2hul0EMFJuNnZORDR2NDA/view?resourcekey=0-5yJh8wV--HB7ve2NuqfQ6A) allows for a depth of up to 2^20
![Screenshot from 2022-02-24 19-07-49](https://user-images.githubusercontent.com/490004/155640431-4c2424c4-ec3d-4d08-b3fe-49325f94b469.png)
