### ISSUE TITLE
Cannot Airdrop Funds Into Wallet

### ISSUE THREAD

**Issue by cctogs** [solana-labs/solana#23356]
Installing Dapp to sell NFT's. Cannot load wallet with Command: Solana Airdrop 2. Getting this message: 
Error: airdrop request failed. This can happen when the rate limit is reached.
There are no funds in this wallet. I am on Devnet.

**Comment by jacobcreech** [comment]
You should try `solana airdrop 1`

We don't do support of Github. Please post your question on https://stackoverflow.com and tag with `solana` or join us in #developer-support at https://solana.com/discord
