### ISSUE TITLE
test-validator change in 1.9.6 makes it super-slow

### ISSUE THREAD

**Issue by ghost** [solana-labs/solana#23376]
#### What

Since `1.9.6` of [Solana Tool Suite](https://docs.solana.com/cli/install-solana-cli-tools), we have been unable to send a burst (or a small bunch) of txs to `solana-test-validator` and have it processed in a timely manner. The test validator denies to process more than ~ 1 to 3 txs/slot. Even though it eventually completes and processes all txs, it takes too much time thanks to this newly introduced behavior/bug.

#### Where

From the user perspective `solana-test-validator`, but the issue can be deep in any lib crate. The last working release is [1.9.5](https://github.com/solana-labs/solana/releases/tag/v1.9.5), the first broken release is [1.9.6](https://github.com/solana-labs/solana/releases/tag/v1.9.6) and it's been broken since then. Here's the [comparison of changes](https://github.com/solana-labs/solana/compare/v1.9.5...v1.9.6).

#### Possible causes
1. The root cause might be somewhere deep in the solana validator code
2. What caught my eye was the commit [28fc733](https://github.com/solana-labs/solana/commit/28fc7338942c64eac34796bee84f9ea94ad9a2a9) introduced in PR #22701. Which basically adds an option to change the number of ticks per slot, or in other words txs per slot if there are txs available. Tried fiddling with it and it makes my test validator not even initialize when set to, let's say 200.

#### What I tried
Another thing I tried was reducing the tx size for our write transactions in deployment, in case you had introduced rate limiting for large txs. It has shown that it's not the case and the txs are processed slowly even when sending deploy txs with 20B write intructions.

#### Why is this important

I'd say this is a severe issue for developers to have this fully working normally ASAP:
1. Simulation of deployment to mainnet by actually deploying to test validator instead of adding program to the genesis block:
    - deployment via `solana program deploy`,
    - deployment via our own code using `solana_client` and `solana_sdk`.
2. Testing some attack vectors, fuzzy testing, etc, on `solana-test-validator`.

### Proposed Solution

- If it's our misunderstanding, please explain it here and post a notice somewhere, so that other developers are not confused as well.
  - In this case, please strongly consider making `solana-test-validator` process txs as in version <=`1.9.5`, it's essential to develop and test, use cases explained above.
- If it's really a bug and not intended behavior, it could be wise to change the version of Solana Tools Suite recommended at https://docs.solana.com/cli/install-solana-cli-tools before it is fixed:
  - The latest mainnet release `1.8.16` according to https://github.com/solana-labs/solana/releases, or `1.9.5` which still works normally.
  - I've also noticed the stable channel actually doesn't download the latest mainnet release, but `1.8.17` instead, which hasn't been formally released yet. **Is it really intended?**

**Comment by GroovierHen** [comment]
@mvines check this.

**Comment by hotshotcoder** [comment]
Verified that the problem still persists in the new recommended mainnet-beta version [1.9.10](https://github.com/solana-labs/solana/releases/tag/v1.9.10).

**Comment by t-nelson** [comment]
The backport is in the v1.9 branch. Looks like no beta channel build for some reason though, so you'd have to build from source to try before release
