### ISSUE TITLE
Port storage to db_ledger (2)

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#2338]
#### Problem

Fix leftovers from #2308 

* [ ] Remove store_ledger_stage
* [ ] Delete `ledger::LedgerWindow`
* [ ] Gut what remains of ledger.rs - the `Block` trait and test helper functions can remain but most of the rest looks to be obsolete.

**Comment by garious** [comment]
Just a note, that Block trait predates our more precise definition in the book.  Consider renaming that to EntrySlice while you're in the neighborhood.
