### ISSUE TITLE
confirmTransaction times out after 60 seconds - I can see the txn is fully confirmed in solscan

### ISSUE THREAD

**Issue by scottwilson312** [solana-labs/solana#23398]
#### Problem
When doing `await connection.confirmTransaction(signature);` it occasionally times out after 60 seconds. However, while that is running, I can see the txn is fully confirmed on solscan.

Even when it doesn't time out on 60 seconds, I can see it fully confirmed on solscan a solid 10-15 seconds before the rpc api confirmTransaction returns.

**Comment by CyberPlayerOne** [comment]
I still have this problem. Anyone?
