### ISSUE TITLE
Cant transfer Solana from spl token account

### ISSUE THREAD

**Issue by stroplet24** [solana-labs/solana#23408]
I tried `solana transfer 5e1nYwx9gi57GkrSDf3tcCGM1TiLLAAzhJQhUAt6TWgN 0.1 --no-wait --allow-unfunded-recipient --keypair spl.json --url https://api.mainnet-beta.solana.com --fee-payer spl.json` , but it throws `Error: RPC response error -32002: Transaction simulation failed: This account may not be used to pay transaction fees`
Then i tried to pay fees from different account but it throws `Error: RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: invalid program argument [3 log messages]`

Account from which i am tiring to transfer from is 4CASLGRDzSNKyx81hLeH6NdNjGAUX7GDJCZJbyoJcW82

**Comment by t-nelson** [comment]
a) `4CASLGRDzSNKyx81hLeH6NdNjGAUX7GDJCZJbyoJcW82` is a known scam account.  You have downloaded your wallet from a malicious source. I suggest you stop what you're doing and get all of you funds off of it
b) we don't use github for support. join us on https://solana.com/discord instead
