### ISSUE TITLE
BPF VM API allows for the verifier to be run optionally, which could lead to it accidentally not being called

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#23433]
#### Problem

The BPF VM API allows for the verifier to be run optionally, which could lead to it accidentally not being called

#### Proposed Solution

Rework the BPF VM API so the verifier is always run and not an extra step for the caller to remember or screw up.

The history behind this architecture is that the different verifiers could be provided based on use case.   Forcing the verifier to always be run may render some of the existing test cases irrelevant, which is probably a good thing.

**Comment by Lichtso** [comment]
https://github.com/solana-labs/rbpf/pull/322
