### ISSUE TITLE
Zero-lamport accounts are cleaned up in multiple spots

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#23434]
#### Problem

Zero-lamport accounts are cleaned up in multiple spots, leading to confusing and potentially corner cases where they are not.  There are multiple spots in the bank and then a check in accounts db, the latter seems to catch all corner cases.

https://github.com/solana-labs/solana/blob/2a17a661e61794cd58f84826f780e9cab15e6d5f/runtime/src/bank.rs#L4687
https://github.com/solana-labs/solana/blob/2a17a661e61794cd58f84826f780e9cab15e6d5f/runtime/src/accounts.rs#L281
https://github.com/solana-labs/solana/blob/2a17a661e61794cd58f84826f780e9cab15e6d5f/runtime/src/accounts.rs#L1227

And lower down

https://github.com/solana-labs/solana/blob/2a17a661e61794cd58f84826f780e9cab15e6d5f/runtime/src/accounts_db.rs#L4966

There is also a bunch of snapshot cleaning of zero-lamport accounts...

#### Proposed Solution

Centralize, clarify, and move up in the stack the clearing of zero-lamport accounts

**Comment by brooksprumo** [comment]
My understanding is that `AccountsDb::clean_accounts()` is the only place where zero lamport accounts are actually cleaned:
https://github.com/solana-labs/solana/blob/2a17a661e61794cd58f84826f780e9cab15e6d5f/runtime/src/accounts_db.rs#L2074-L2078
Other places set account balances to zero lamports (or check balances), but I don't think anywhere else cleans accounts. 

Maybe this is more geared to rent collection though?
