### ISSUE TITLE
impossible to use blake3 module on devnet

### ISSUE THREAD

**Issue by fred227** [solana-labs/solana#23441]
Hi,

My rust program uses hash function in blake3 module that is included in solana-program crate in 1.9.9 version of solana that is used on devnet : `solana cluster-version` = 1.9.9
If everything is fine when deploying on testnet I have an error when trying to deploy on devnet.

I get the error `ELF error: Unresolved symbol (sol_blake3) at instruction XXXX`

Is there an explanation ? 

thanks

**Comment by CriesofCarrots** [comment]
Hi, @fred227 . Yes. The sol_blake3 syscall is not yet available on devnet, but it is on testnet. That's why you're seeing different deploy results.
To follow the devnet activation of the feature that will enable the syscall, install the solana cli tools and run:
```
$ solana feature status HTW2pSyErTj4BV6KBM9NZ9VBUJVxt7sacNWcf76wtzb3 -ud
HTW2pSyErTj4BV6KBM9NZ9VBUJVxt7sacNWcf76wtzb3 | inactive                    | blake3 syscall
```
