### ISSUE TITLE
Transactions are failing, RPC says not enough funds

### ISSUE THREAD

**Issue by megakoko** [solana-labs/solana#23472]
#### Problem

Hello!

We are developing a hardware wallet that uses Solana and we're experiencing an issue when sending transactions via RPC.

Here are the steps:
1. Have two accounts, the sender and the recipient, both have some funds.
2. Try to send ALL funds from the sender to the recipient — we do that by taking the amount of funds on the sender account and subtracting 5000 lamport from it.

In theory that should work but in practice it sometimes doesn't. The RPC error returned states that there are insufficient funds on the sender account. The error suggests the amount that is available to send instead, and the difference between the suggested amount and the one we're trying to send is 46 lamport on devnet. 

46 lamport is the amount required to open an account which is confusing because the recipient account is already open, and has some balance to it.

#### Proposed Solution

Please explain what are we doing wrong, or where can we read up on that topic. What transactions require the additional amount needed to open an account (other than the situations when recipient account is not open)?

Regards,

Andy

**Comment by t-nelson** [comment]
We don't use github for support requests.  Join us on https://solana.com/discord
