### ISSUE TITLE
Unable to deploy a program on solana testnet

### ISSUE THREAD

**Issue by ashlinSajan** [solana-labs/solana#23484]
On deploying a sample program on test net
It shows blockhash expired

@jackcmay could you please help

![Uploading 16463941329364890100799581872298.jpg…]()

These are the commands I executed
![16463942136981441467011925667468](https://user-images.githubusercontent.com/34328137/156757584-b8b91abc-8ef6-489f-98ad-ecadbfb970e2.jpg)
I tried devnet first but couldn't airdrop so switched to testnet but unable to deploy

**Comment by jackcmay** [comment]
This is probably a better issue to file in the example-helloworld repo

I followed the steps in that repo to deploy and run on both local and testnet and both were successful for me.  Deployment on testnet took a bit but completed, maybe give it more time?
