### ISSUE TITLE
No BPF support for native signed division 

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#23487]
#### Problem

BPF does not have a signed division instruction which means instead of jitting directly the compiler pulls in intrinsic which in this case are very inefficient

#### Proposed Solution

Add a new signed division instruction to SBF

**Comment by alessandrod** [comment]
See https://github.com/solana-labs/solana/issues/23487 and https://github.com/solana-labs/llvm-project/pull/28

**Comment by jackcmay** [comment]
> See #23487 and [solana-labs/llvm-project#28](https://github.com/solana-labs/llvm-project/pull/28)

#23487 is this issue, did you mean to cite that here?

**Comment by alessandrod** [comment]
Oops, I meant https://github.com/solana-labs/rbpf/pull/283

**Comment by pgarg66** [comment]
@alessandrod can this be closed?

**Comment by alessandrod** [comment]
Closing as this was fixed a while ago. The feature is planned to be enabled once we roll out ABIv2.
