### ISSUE TITLE
Getting fees for a transaction is confusing in web3.js

### ISSUE THREAD

**Issue by jacobcreech** [solana-labs/solana#23491]
#### Problem

With the current way a `Transaction` object is constructed, the new `getFeeForMessage` RPC call has confused some devs because it isn't obvious how to get the message from a constructed Transaction.

#### Proposed Solution

1. Add `getEstimatedFee(connection: Connection)` function on `Transaction` object that returns the fees from `getFeeForMessage`
2. Add `Transaction` constructor that takes in `Message` and `Signatures[]` like the [rust implementation](https://docs.rs/solana-sdk/latest/solana_sdk/transaction/struct.Transaction.html)
3. Add methods to build `Message` like you would a transaction, using `addSIgnature` and `addInstruction` to match the Rust implemtnation more.

Steps 2 and 3 are to help make it easier to understand what goes into building a transaction in web3.js, and step 1 is to make it simpler to get estimated fees for transactions.

**Comment by marcnjaramillo** [comment]
I'd like to try taking this on.

**Comment by jordansexton** [comment]
Closed by #23579.
