### ISSUE TITLE
Enable moving stakes from one validator to another without losses in 1 epoch seamlessly

### ISSUE THREAD

**Issue by saito-kosuke** [solana-labs/solana#23524]
#### Problem

Staking pool servicers say they can't redistribute their stakes frequently because redistribution leads to losses in 1 epoch that take 20+ epochs to recover through the tiny APY difference.

The losses ensure that it's difficult for new validators to receive stakes from staking pool servicers.

#### Proposed Solution

Enable seamlessly moving stakes from one validator to another without losses in 1 epoch.

**Comment by joncinque** [comment]
Added with https://github.com/solana-labs/solana/pull/26294
