### ISSUE TITLE
run repair outside gossip

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#2353]
#### Problem
dataplane repair is serviced from the control plane clusterinfo::listen(), where it pollutes control-plane construction and testing

#### Proposed Solution
build a new repair service on db_ledger that has its own protocol endpoint

**Comment by garious** [comment]
@aeyakovenko, thoughts?  Seems okay to me that a repair request would come in over the control plane (can't be censored), but that the repair blob would be shipped back out over the data plane (because it's targeting a TVU).

**Comment by aeyakovenko** [comment]
@garious sticking it in there was a hack.  The right thing to do is for nodes to advertise "Repair" service in gossip, and for the repair protocol to live outside of gossip and use its own socket and message/response protocol.

**Comment by rob-solana** [comment]
also consider that spy nodes generally can't help with repair...

**Comment by rob-solana** [comment]
BTW, the repair response is shipped back the way it came (and so is NAT-traversal-capable), and repair requests are sent *from* the TVU/dataplane port...

**Comment by mvines** [comment]
@carllin - Is this issue obsolete with the new repair design changes

**Comment by carllin** [comment]
@mvines, not yet, the repair response logic still lives ini ClusterInfo

**Comment by mvines** [comment]
I'm punting this issue out, if you disagree please bring it back with impact justification

**Comment by rob-solana** [comment]
obsolete
