### ISSUE TITLE
Bank hash mismatch when a validator is offline for more than 512 slots (Slot hashes max entries)

### ISSUE THREAD

**Issue by AshwinSekar** [solana-labs/solana#23545]
#### Problem
When all features are enabled, we have bank hash mismatches if a validator restarts after missing at least 512 slots (the max size of slot hashes). 

To reproduce:
Start local testnet with all features enabled. Stop a node for more than 512 slots. On restart of the node you see errors like the following:
```
[2022-03-03T19:53:34.369924873Z WARN  solana_vote_program::vote_state] HvnW6gWMnCtMyC1DomZ6qDnifnHJFCV6gXex4uGzqzY9 dropped vote slots [3409] failed to match hash 9cqDVL4r11Ud95iiuxcNuTeZb8iervqSDZ6FGX8Qw4A2 CA1KBoNTPGisRMbq8iQ6wzNN7Rz5SQeABCoVyeFyE9KV
[2022-03-03T19:53:34.372908321Z WARN  solana_vote_program::vote_state] Hy3JUoF8FvhGEkGWne4FfvPkC8md3JdAj4VYXBtvg8x8 dropped vote slots [3409] failed to match hash 9cqDVL4r11Ud95iiuxcNuTeZb8iervqSDZ6FGX8Qw4A2 CA1KBoNTPGisRMbq8iQ6wzNN7Rz5SQeABCoVyeFyE9KV
[2022-03-03T19:53:34.372992346Z WARN  solana_vote_program::vote_state] GJWKuaiinG2aiGbyEoBmS2zPSnKbF7z3JgrMadh6AABJ dropped vote slots [3409] failed to match hash 9cqDVL4r11Ud95iiuxcNuTeZb8iervqSDZ6FGX8Qw4A2 CA1KBoNTPGisRMbq8iQ6wzNN7Rz5SQeABCoVyeFyE9KV
[2022-03-03T19:53:34.374294271Z WARN  solana_vote_program::vote_state] 9G9cyxnM8u4u7UH9doG3cKCAG4zLTUmYmVkHSRtqjgdb dropped vote slots [3409] failed to match hash 9cqDVL4r11Ud95iiuxcNuTeZb8iervqSDZ6FGX8Qw4A2 CA1KBoNTPGisRMbq8iQ6wzNN7Rz5SQeABCoVyeFyE9KV
[2022-03-03T19:53:34.375324284Z WARN  solana_vote_program::vote_state] 3KcUESL8aYkfPHSoGBKrnD7isUZs3x6Xyyu7TVAq9a2L dropped vote slots [3409] failed to match hash 9cqDVL4r11Ud95iiuxcNuTeZb8iervqSDZ6FGX8Qw4A2 CA1KBoNTPGisRMbq8iQ6wzNN7Rz5SQeABCoVyeFyE9KV
```

On investigation on why the restarted node has a bank hash mismatch with the rest of the cluster, only one account has a different hash (SysvarRecentB1ockHashes11111111111111111111):
```
pubkey SysvarC1ock11111111111111111111111111111111, hash EiT1ebwuB2gHy8oybJST42oakrs74s24ymY3kwVpkHFX, lamports 1169280
pubkey SysvarRecentB1ockHashes11111111111111111111, hash EEmiyUZL3iVMx1BbZpWJtJ3q2aE9JM6EWwAByjXVwUtj, lamports 42706560
pubkey SysvarS1otHashes111111111111111111111111111, hash 2WNMNmu24PtHKnnuqXadV74fArseaqV5Rx66CAFYQzgr, lamports 143487360
pubkey SysvarS1otHistory11111111111111111111111111, hash FJuojpWF8uVR2mFH1fAQPGFKXbA6DSv4uVnKhJDTB4Jg, lamports 913326000
```
vs
```
pubkey SysvarC1ock11111111111111111111111111111111, hash EiT1ebwuB2gHy8oybJST42oakrs74s24ymY3kwVpkHFX, lamports 1169280
pubkey SysvarRecentB1ockHashes11111111111111111111, hash 6i6E4ego5Zexq9bZZHdBUaYJJhFZeVbhXzc3GDnPfJZ8, lamports 42706560
pubkey SysvarS1otHashes111111111111111111111111111, hash 2WNMNmu24PtHKnnuqXadV74fArseaqV5Rx66CAFYQzgr, lamports 143487360
pubkey SysvarS1otHistory11111111111111111111111111, hash FJuojpWF8uVR2mFH1fAQPGFKXbA6DSv4uVnKhJDTB4Jg, lamports 913326000
```

**Comment by t-nelson** [comment]
can you dser/dump the account's state on both sides?

**Comment by steviez** [comment]
It could be interesting to see the transaction details as well; specific program might jump out at someone:
```
solana-ledger-tool slot SLOT --ledger <LEDGER_DIR> -vv | grep SysvarRecentB1ockHashes11111111111111111111
```
--
Also, the following steps have been useful for me when debugging consensus failures (such as https://github.com/solana-labs/solana/issues/23180); it will require you to re-run with `RUST_LOG=debug` if you didn't (do this on all nodes to have full good & bad logs for comparison if needed)
- Recreate the issue with `debug` level logging
- Comb the logs in the same way to find the slot where the restarted node deviated
- Run the command I posted above to figure out the transaction details, and namely, note the signature; let this be `<SIGNATURE>`
- Run something like `$ < validator.log grep <SIGNATURE> -B 10`

Presumably the transaction had some different result (possibly/probably failing) on the node that was restarted; this extra log statement might show more details. For example, in that issue I linked above, doing the above steps showed me the transaction was failing and a specific error:
```
[2022-02-15T22:33:56.060566898Z DEBUG solana_runtime::bank] tx error: InstructionError(0, UnsupportedProgramId) ...
```
That at least got me looking at the right areas of code before someone more knowledgable than me saw the details and fixed the issue 😄

**Comment by AshwinSekar** [comment]
Upon further investigation the exact difference seems to be the lamports_per_signature for the exact block after the snapshot on restart. We are off by 500 lamps.

**Comment by t-nelson** [comment]
was this against MB?  If so, might be the first time we hit congestion fees :partying_face:

**Comment by AshwinSekar** [comment]
was a gce cluster

**Comment by AshwinSekar** [comment]
The issue is related to how we perform fee calculations with the `FeeRateGovernor`. We adjust the `lamports_per_signature` by looking at the `lamports_per_signature` from the previous block and computing the gap between that and the `target_lamports_per_signature`. To produce smooth increase/decrease, we adjust the gap by 5% while using the min and max values to [bound](https://github.com/solana-labs/solana/blob/master/sdk/program/src/fee_calculator.rs#L145).

The issue occurs when we have to restart a validator from a snapshot. The recent blockhashes sysvar keeps track of a `FeeRateGovernor` for each block it contains. However [we don't serialize](https://github.com/solana-labs/solana/blob/master/sdk/program/src/fee_calculator.rs#L51) the `lamports_per_signature`, so on deserialization of the root bank this value is set to 0. 

On the following block we will try to adjust 5% of the `target_lamports_per_signature` (10,000 -> 500), however because of the min/max bound check this will result in the new `lamports_per_signature` being 5000 (min is 50% of target and max is 1000% of target). This usually doesn't pose an issue because from observation it seems that we are almost always around 5000.

The issue occurs if we line up a fee rate increase on this exact block, all of the other validators are able to adjust 5000 -> 5500, however because our restarted validator has a `base_fee_rate_governor.lamports_per_signature` of 0, this adjustment is lost in the min/max bounds and still ends up being `5000`. This is a pretty rare occurrence which probably explains the non deterministic nature of reproducing this bug.

**Comment by mvines** [comment]
Oh nice find. Looks like we need to add `lamports_per_signature` to the snapshotted bank to address this :-/

**Comment by brooksprumo** [comment]
Would removing `#[serde(skip)]` from `FeeRateGovernor:: lamports_per_signature` also fix this?
https://github.com/solana-labs/solana/blob/3c7022014211b26bca03793f198c31e986e4dbd1/sdk/program/src/fee_calculator.rs#L52-L56
I imagine that a snapshot format version bump would be required to support that change, yes? And I'm assume that's why adding `lamports_per_signature` is the preferred solution here?

**Comment by AshwinSekar** [comment]
Yeah that was my initial thought but it would require a snapshot version change, not sure if we want that?

**Comment by brooksprumo** [comment]
> Yeah that was my initial thought but it would require a snapshot version change, not sure if we want that?

Probably not, its _very_ involved.

**Comment by brooksprumo** [comment]
Reopening since #25181 was reverted.
