### ISSUE TITLE
[feature-request] Support for rust based web frontends?

### ISSUE THREAD

**Issue by shravanshetty1** [solana-labs/solana#23552]
1. Solana-client crate is not wasm compatible due to dependencies and blocking code.
2. Api is not documented using openAPI, hence client cannot be generated either.

Its possible to create transactions since I can serialize transaction object from rust side and send it to javascript where solana/web3.js can parse the transaction object and send it using browser extension - but this is also not straight forward

Are there any known workarounds?Are there any plans to add support for this?

**Comment by russellwmy** [comment]
@shravanshetty1 I created a simple solution by wrapping window object. You can even wrap web.js. However, it is a temporary solution. (https://github.com/russellwmy/yew-dapp-examples/tree/main/solana-dapp-example)

The better way, we can fork and modify `Rust-Web3` package to support Solana. Here is the repository: https://github.com/tomusdrw/rust-web3

**Comment by russellwmy** [comment]
@shravanshetty1  I am building a library to do that. https://github.com/russellwmy/web3-rs. I built it for own use case. but if you are interest in that. you can check this out.

**Comment by shravanshetty1** [comment]
@russellwmy Actually I made rust wrapper of solana-web3.js for my usecase but I think your solution would be better so will try it.
Planning on making rust wrapper for wallet as well - will link it here soon
