### ISSUE TITLE
Reference vote signer needs to persist registered nodes

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#2355]
Currently a fullnode receives a new `vote_account_id` on every restart.  This causes the fullnode to need to reinitialize its vote account with the vote program, costing it tokens unnecessarily.

Instead the reference vote signer should persist the vote account keypair, somewhere it's cleared on a `multinode-demo/setup.sh`, such that a fullnode can reuse its previous vote account until the ledger is reset.

As a part of fixing this issue please revert these commits:
* [ ] 4e80fcfe005a793589d10344d85d43ed5f5fe622
* [ ] 735f2ffb5fe3c2609b0d4c994ee4a1df6fb11682

**Comment by pgarg66** [comment]
Hi @mvines , @aeyakovenko and I discussed this last week. Persisting the private key for vote signing introduces a security risk. The current workaround (give bootstrap leader more tokens) is good for v0.12.0. We can keep the issue open for future milestone and revisit it once we have secure signing in place.

**Comment by sagar-solana** [comment]
This is obsolete since #3199, staking accounts are created and funded via wallet and not the node's balance directly.
