### ISSUE TITLE
Very large cost were calculated for `cndy`

### ISSUE THREAD

**Issue by taozhu-chicago** [solana-labs/solana#23575]
#### Problem
Identified in `devnet` that `cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ` has very large cost - much larger than block max limit. Causing its transactions not land at all.

##### Test Setup
To identify if transaction cost calculation produced error. I downloaded 7 days worth `per-program-timings` metrics from devnet, for above `cndy` program_id, into a csv file.

```
SELECT "accumulated_units", "count", "execute_us", "errored_count", "errored_units" FROM "devnet"."autogen"."per_program_timings" WHERE time > :dashboardTime: AND time < :upperDashboardTime: AND "pubkey"='cndy3Z4yapfJBmL3ShUp5exZKqR3z33thTzeNMm2gRZ'
```

The downloaded data include accumulated CUs for successfully executed IXs, as well as CUs consumed by errored-out IXs. 

##### EMA algo
In the inner part, cost_model uses Exponentially Weighted Moving Average and Variance to calculate cost to be `ema + 2* stddev`. So the first step I took is to feed download 7-days data into this algo to verify calculation result. The test code is [here](https://github.com/solana-labs/solana/pull/23573/files#diff-1dc781bcd9d7db8218a06cdf4d3ff69bc65f1110144906d29fd2447eb4c9fa3eR335-R360). 

The result is: 
<img width="698" alt="image" src="https://user-images.githubusercontent.com/82401714/157579171-1953f745-c21d-4bfd-b414-953a66491490.png">
The Red are the reported CUs from successful `cndy` execution, the Blue is the calculated `cost` (again `=ema + 2*stddev`). The Blue line clear follows the input data nicely, it maxes out at 220,000 CUs. So the EMA algo seems to be OK, no bad math there.

##### Cost updating logic
Before EMA algo, there is a cost updating logic. It does two things: sending successfully executed CUs to EMA algo (above), and run a logic to report unsuccessfully executed CUs. 

I build this [test](https://github.com/solana-labs/solana/pull/23573/files#diff-ac1c9242801e4863b57ea311a3f0e3f5a2b0f68c2c4dfdf109dad27a6ec0f8e3R421-R470) to feed the same downloaded data to "cost updating" codepath. The result is: 
<img width="689" alt="image" src="https://user-images.githubusercontent.com/82401714/157580290-ad7be912-3c05-4c17-bdb5-016843da1637.png">
Same as above, Red is successfully executed CUs, Blue is calculated cost, Yellow is unsuccessfully executed CUs. At one one point, the calculated cost hit ~68m CUs. This is wrong.

###### The cause
The cause is the combination of how the errored-out execution's CUs were reported, and how EMA works. 

How errored-out IX's CUs are reported: to capture the cost of failed IX, it's consumed CUs are reported. However, TX can fail at early stage of its execution, when a little CUs were consumed. To avoid such small number of CUs to skew the average down, a logic was added to take max(current_cost, actual_used_CUs) as reported CUs. 

The current_cost (again) is `ema + 2 * stddev`. 

So every time there is a failed execution (of `cndy`), the combined logic are basically companding `2*stdev` to calculated cost (just a basic idea, detailed math can be easily deducted), cause cost to raise exponentially. As seen in above chart.

#### Proposed Solution
Perhaps it makes better sense to use `ema` instead of `current_cost` in determine failed IX's CUs. I propose [this small change](https://github.com/solana-labs/solana/pull/23573/files#diff-ac1c9242801e4863b57ea311a3f0e3f5a2b0f68c2c4dfdf109dad27a6ec0f8e3R160-R165), then ran the same test, the result looks like this: 
<img width="690" alt="image" src="https://user-images.githubusercontent.com/82401714/157581781-489d3f5d-091b-4d43-96b5-274f153923d4.png">
The blue line go back to normal.

The above mentioned tests and proposed change are in this draft: #23573

**Comment by taozhu-chicago** [comment]
@t-nelson @carllin @sakridge wdyt ^^^

**Comment by carllin** [comment]
@taozhu-chicago thanks for the detailed analysis!

So the main problem is in how we handle errors, specifically in the call to the cost model `find_instruction_cost()` method. 

This is currently used to compute the cost of erroring transactions in the following way: `max(find_instruction_cost(), erroring_cost)`.

However the issue is that `find_instruction_cost()` does not actually return the *current* average cost, but returns a cost 2 standard deviations higher (this is for preventing price undercutting according to the PR comments here: https://github.com/solana-labs/solana/pull/22286

For this, I think the fix you proposed here https://github.com/solana-labs/solana/pull/23573/files#diff-ac1c9242801e4863b57ea311a3f0e3f5a2b0f68c2c4dfdf109dad27a6ec0f8e3R160-R165 makes sense. Will add review comments there!

**Comment by taozhu-chicago** [comment]
Exactly, it was OK when `find_instruction_cost()` returned simple average. But when it was changed to (mean + 2*stddev), feeding it to algo is adding (2*stddev) to it, the really intention should be just (mean)
