### ISSUE TITLE
eBPF question: mapping bytecodes to Solana-specific functions

### ISSUE THREAD

**Issue by caballa** [solana-labs/solana#23586]
`rbpf` (`https://github.com/solana-labs/rbpf`) allows to register Solana-specific functions via functions such as `register_syscall_by_hash` and `register_syscall_by_name`. This functionality is called from the file `programs/bpf_loader/src/syscalls.rs`. However, the actual eBPF bytecode for CALL takes a parameter an integer. For example, this is the output of `llvm-objdump` on the `helloworld` example:

```
      33:	b7 02 00 00 2f 00 00 00	r2 = 47
      34:	85 10 00 00 ff   ff   ff   ff	call -1
```

**Question**: where in the code I can find the mapping from -1 to the corresponding function name that will be passed to `register_syscall_by_name`? I believe that -1 corresponds to `sol_log` but I would like to know the mapping for sure.

**Comment by terorie** [comment]
Most likely, this is a placeholder that will be filled by the ELF loader through a relocation.

**Comment by caballa** [comment]
@terorie : could it be here https://github.com/solana-labs/rbpf/blob/main/src/elf.rs#L565 ?

**Comment by caballa** [comment]
Note that this code relocates the call except if `call -1`. So I wonder  now what `call -1` means

**Comment by terorie** [comment]
https://github.com/solana-labs/rbpf/blob/a4bbd2417209e483daac843e6eddf2e46cd0e6d3/src/elf.rs#L222

**Comment by caballa** [comment]
Got it. Thanks a lot!
