### ISSUE TITLE
Solano Not Installing on Ubuntu Server 21.10

### ISSUE THREAD

**Issue by roaringsundew40** [solana-labs/solana#23590]
Hi All,

#### Problem

I tried installing Solano on a 64-bit Raspberry Pi 4 running Ubuntu Server 21.10. I wanted to start using Solana after I watched [NetworkChuck's Video](https://www.youtube.com/watch?v=befUVytFC80) on how to make your own Solana Token. I was trying to do that using the command that was provided which was 
`sh -c "$(curl -sSfL https://release.solana.com/v1.8.6/install)"`.
This gives me the error of 
`downloading v1.8.6 installer`
`sh: 156: /tmp/tmp.hs229PZaWp/solana-install-init: Exec format error`
I went onto the Solana docs and tried installing the latest version but also got the same error. No article that I looked at could help me fix this problem...

Thanks in Advance

**Comment by mvines** [comment]
You'll need to build from source on a Raspberry Pi.  Pre-built binaries aren't provided for this platform.  Some details at https://github.com/solana-labs/solana#building

For more support please join us on Discord instead: https://solana.com/discord
