### ISSUE TITLE
Add way to set data size for filler accounts

### ISSUE THREAD

**Issue by brooksprumo** [solana-labs/solana#23593]
#### Problem

Filler accounts offer a great way to model and test the code with more accounts than actually exist. Currently, all the accounts are created without data, so their on-chain data size is all zero. It would be beneficial to exercise the code with additional on-chain data as well.

#### Proposed Solution

Add a new command line option to set the size for filler accounts' data (this will default to zero), and plumb that through to where the filler accounts are created.

##### Details

- Add CLI args to both `solana-validator` and `solana-ledger-tool`

For validator:
https://github.com/solana-labs/solana/blob/b1da7cff66b6e5b41c6b501c5c67e140cae0251a/validator/src/main.rs#L1555-L1560

For ledger-tool
https://github.com/solana-labs/solana/blob/b1da7cff66b6e5b41c6b501c5c67e140cae0251a/ledger-tool/src/main.rs#L908-L913

Here's the specific line for setting the size for each filler account:
https://github.com/solana-labs/solana/blob/1e20bd8f9a0a2056193919ba513533145f8d7ac5/runtime/src/accounts_db.rs#L6856

- To plumb this new arg down, it would make sense to add a new `FillerAccountsConfig` struct to bundle the various filler account configurations together.

- The CLI arg should take size _per account_ in bytes. So the total filler accounts size will be `filler_accounts_count * filler_accounts_size`.

**Comment by mrbuzz** [comment]
Hey, I'd like to take that

**Comment by mrbuzz** [comment]
Hey @brooksprumo! Just made a PR
