### ISSUE TITLE
Enforce Cargo.toml tables are sorted in CI

### ISSUE THREAD

**Issue by brooksprumo** [solana-labs/solana#23608]
#### Problem

The tables in Cargo.toml files do not have to be sorted ...yet. When lines are added, it would be nice to have CI enforce they were sorted.

This came up as a comment in another PR:

> bonus points if you enforce it in `ci/test-sanity.sh`

_Originally posted by @t-nelson in https://github.com/solana-labs/solana/issues/23602#issuecomment-1064778212_

#### Proposed Solution

Add `cargo-sort` to CI, and then run `cargo sort --workspace --check` as part of `ci/test-sanity.sh`.

**Comment by heyAyushh** [comment]
Hey, I would love to contribute on this issue @brooksprumo

**Comment by brooksprumo** [comment]
@heyAyushh Great! Please go for it.
