### ISSUE TITLE
Secp256k1 Program is hard to safely use

### ISSUE THREAD

**Issue by tlambertz** [solana-labs/solana#23617]
The documentation/SDK around the Secp256k1 Program could be greatly improved. Every project we know of that uses the Secp256k1 program has done something critically wrong in the past:

- not checking instruction sysvar correctly
- only needing to check one signature, so hardcoding parsing of one SecpOffset struct, ignoring the count field
- not checking the instruction_index fields.

An error in signature checking almost always is a critical bug, so some more guidelines around safe usage would be great.

The [current docs](https://docs.solana.com/developing/runtime-facilities/programs#secp256k1-program) are technically enough to use it securely, but they don't mention security explicitly. Ideas for improvement:

- Mention the three issues above explicitly, so users are aware of them.
- Recommend to parse and check every field of the secp instruction.
- add pseudocode on how to correctly parse the IX.

This brings up another issue: The API with the SecpOffset list at the beginning of the instruction is really annoying to parse. All consumers I have seen so far implement their own version of the same concept:

"I know what message I want signed. Please fetch me all the Pubkeys that have signed this exact message. Check that the pubkeys are in my list of oracles/the admin key/whatever".

You could implement an SDK function that does this. Advanced users would still have to roll their own code, but this common use-case could be done via a single function:

```rust
/// given a msg and instruction sysvar, return all addresses that signed the message in the first secp instruction
/// This function requires that all signatures in the secp instruction are for the same message.
fn secp256k1_get_message_signers(msg: &[u8], instruction_sysvar: &AccountInfo<'_>) -> Result<Vec<Secp256k1Pubkey>, Error> {
    // verify instruction_sysvar
    // parse instruction sysvar, loop through it to determine the first secp IX (or hardcode it to use the IX before the current IX, as that's something most programs do?)
    // parse secp IX, parse offsets, verify message is the same everywhere and matches the passed msg
    // return a vec of all pubkeys that have signed.

    // in all other cases (multiple msg signed, different message signed, ...) error.
}

```

The recently added `secp256k1_recover` syscall has much nicer UX at the cost of more compute (25000 vs 720). But as far as I can see, it is documented nowhere, (except for [docs.rs](https://docs.rs/solana-program/1.9.12/solana_program/secp256k1_recover/fn.secp256k1_recover.html), without docstring. For simple projects/seldomly called contracts this is currently much simpler and easier to safely use.

Not sure if you want to recommend it to everyone, since it can't be nicely parallelized. Though I'd argue security >> speed. But with a nice SDK function, the usability would be similar.

**Comment by tlambertz** [comment]
I don't know of a nice example that's open source that you could simply copy, since the required checks are usually distributed. Stuff like solana-pubkey/owner checks at the beginning of an instruction, and integrated signature-pubkey verification with immediate abort in the parsing code.

I am aware of three open source implementations:

## Wormhole
They have up to N signatures of the same message in one secp transaction, and enforce all to have the same message. Parsing code is pretty manual though, not sure if you want to copy that. They also have owner/id checks outside of the parsing function: https://github.com/certusone/wormhole/blob/2b64e5a10c76b48d7175c4bf1ab872858950c874/solana/bridge/program/src/api/verify_signature.rs#L92-L154

## Neon
Only requires/expects exactly one signature, and hardcodes this fact.
They went the other way and don't actually parse the secp instruction, but construct it from known data and then compare if it maches. https://github.com/neonlabsorg/neon-evm/blob/50fd88edfc43a10a4043c40c88ae4a001a2b561a/evm_loader/program/src/transaction.rs#L26-L81

## Audius
Can have multiple signatures, but enforces 1 signature per secp instruction and uses multiple instructions if needed.(https://github.com/AudiusProject/audius-protocol/blob/a73f1c56a9a550215c50acc4e77bce2f396ee89d/solana-programs/audius_eth_registry/src/processor.rs#L39-L90)

**Comment by brson** [comment]
Just an update that I have been working on this and have documentation and example patches in progress.

I am considering also adding examples to the spl, and augmenting the APIs with more foolproof helpers.

**Comment by brson** [comment]
This api now has a huge amount of docs.
