### ISSUE TITLE
CostTracker limits should use Option

### ISSUE THREAD

**Issue by brooksprumo** [solana-labs/solana#23612]
#### Problem

Originally from [this PR comment](https://github.com/solana-labs/solana/pull/23537#discussion_r824255487), the limits in CostTracker should be `Option<u64>` to better articulate intent. Tests/benches set these to `u64::MAX` to effectively say "no limit"; it would be nice to set these to `None` to clearly state no limit.

#### Proposed Solution

Update the CostTracker limits to be Option-wrapped.

**Comment by antidmg** [comment]
@brooksprumo I'd be happy to take a stab at this!

**Comment by brooksprumo** [comment]
@antidmg Great! Have at it!

**Comment by antidmg** [comment]
@brooksprumo Just making sure I understand this correctly - would we want to keep these default limit values, and only update the tests and bench code?

```rust
account_cost_limit: MAX_WRITABLE_ACCOUNT_UNITS,
block_cost_limit: MAX_BLOCK_UNITS,
vote_cost_limit: MAX_VOTE_UNITS,
```

**Comment by brooksprumo** [comment]
@antidmg 

> [...] would we want to keep these default limit values, and only update the tests and bench code?

Basically anywhere that is currently `u64::MAX`, replace that with `None`. If there was a limit where `value != u64::MAX`, it'll become `Some(value)`.

Since the `MAX_XXX` constants are not `u64::MAX`, you'll wrap 'em in `Some`:

```rust
account_cost_limit: Some(MAX_WRITABLE_ACCOUNT_UNITS),
block_cost_limit: Some(MAX_BLOCK_UNITS),
vote_cost_limit: Some(MAX_VOTE_UNITS),
```

**Comment by antidmg** [comment]
Thanks for the clarification!

**Comment by brooksprumo** [comment]
Closing this issue as the consensus is to not implement.
