### ISSUE TITLE
[feature-request] PDAs without bumps / On-curve PDAs

### ISSUE THREAD

**Issue by paul-schaaf** [solana-labs/solana#23613]
#### Problem

PDAs are great but dealing with bumps is error-prone and feels like an unnecessary implementation detail. We try to hide them as best as we can in anchor but this means using `find_pda` on-chain which can be compute-intensive.

This led us to think, what if we could have PDAs without bumps? 

#### Proposed Solution

A new syscall like `create_program_address` that uses no bump and is ok with the resulting address existing on the curve. These new PDAs would work exactly like the current PDAs (including using them as program signers). In theory, unlike the current PDAs, they could be used to sign transactions (which is why bumps were introduced I assume?) but that probability is negligible.

**Comment by paul-schaaf** [comment]
I think I might be missing something here. Am I understanding correctly that you dont want on-curve PDAs because someone could guess the private key of the PDA and sign a transaction with it outside the runtime (i.e. not using cpi pda pseudo signatures)? If yes, isn't the chance of guessing a private key practically 0?

**Comment by mvines** [comment]
Sure but when the address is explicitly off curve the risk is exactly zero.  That’s hard to beat!

**Comment by t-nelson** [comment]
there are additional benefits in that, with high probability, an address that fails to decompress to a valid ed25519 pubkey is program-controlled.

i would say there's basically no chance that we would make or accept the suggested change. the benefits are too great and the costs too small.  after all, there's precedent for folks grinding fee optimized address on ethereum.  nothing stopping someone from doing the same looking for a base address that resolves to a PDA with bump=255.

**Comment by vladwix** [comment]
Wouldn't it be better to separate address space by some flag? One bit or one byte of an address would determine whether it's a keypair or PD address. It could probably even be backwards compatable if new addresses are extended and not shrunk.

**Comment by vladwix** [comment]
Regarding current approach: it's still possible that some set of seeds with all possible bumps would lie on the curve, making some program broken. That probability is somewhat around private key guessing. Are there any plans to make it zero as well?
