### ISSUE TITLE
solana-web3.js: Automatically batch requests made via JSON RPC

### ISSUE THREAD

**Issue by epicfaace** [solana-labs/solana#23627]
#### Problem

Many of the existing methods for interacting with JSON RPC don't support batching.

#### Proposed Solution

It would be nice to have an option that would automatically batch requests made via JSON RPC. We could batch requests sent every 100ms, for example.

**Comment by steveluscher** [comment]
I gave this a good think, and wrote down my thoughts here: https://twitter.com/steveluscher/status/1532443998488363008

I actually think that JSON-RPC 2.0 batching is a _huge_ footgun, and might actually lead to _worse_ application performance overall. Read the thread above and let me know what you think!

**Comment by epicfaace** [comment]
@steveluscher Interesting thread. I agree with your thread, but only in some cases in which the number of requests you're trying to batch is small enough. If you have too many requests that are running at the same time, though, then this overcomes the drawbacks of batching and makes batching way better.

Let me explain my use case: I had an app that would make 20-30 requests, all at the same time. Each request was pretty simple and just fetched data. But running that many requests at once made things super slow. This is particularly because Google Chrome has a maximum of [6 concurrent requests per host name.](https://blog.bluetriangle.com/blocking-web-performance-villain#:~:text=Chrome%20has%20a%20limit%20of,host%20at%20the%20same%20time.) Essentially, this made things _really_ slow and the best way to solve this is to batch.

Does this sound like a case for ‘yes, absolutely, we need that.’??

**Comment by steveluscher** [comment]
Ah yes, I remember the 6 request limit. The thing with that limit is that it's not real.

https://codesandbox.io/s/sweet-surf-qu60i3?file=/src/index.js

https://user-images.githubusercontent.com/13243/171733616-7a3b97c5-611f-42b2-b832-881d25821e16.mov

I'd be interested to replicate the slowness you observed, to see if there isn't some _other_ cause. If you have a repro that you can share with me, let's dig into it!

**Comment by epicfaace** [comment]
@steveluscher this intrigued me, I investigated further, and aha, it _is_ real!

https://codesandbox.io/s/friendly-dream-oercmt?file=/src/index.js

<img width="1765" alt="image" src="https://user-images.githubusercontent.com/1689183/172072452-b602c344-f028-495e-86b5-6ed70c532657.png">

For your demo, the requests were too fast for humans to actually notice the 6-request concurrent limit. My reproduction, which uses 5-second requests, makes the limit clearer.

**Comment by steveluscher** [comment]
We're both right!

<img width="589" alt="image" src="https://user-images.githubusercontent.com/13243/172215299-61128192-4dc2-4a07-9019-68527cfe01ea.png">

In your example, `deelay.me` serves files over the ancient HTTP/1.1. In my example, `jsonplaceholder.com` serves them over HTTP/3.

Now please, please, please, please, please, please, please, please, please, please, please, please, please, please tell me that the validator RPC isn't HTTP/1.1…

**Comment by steveluscher** [comment]
> Now please, please, please, please, please, please, please, please, please, please, please, please, please, please tell me that the validator RPC isn't HTTP/1.1…

Shit.

**Comment by steveluscher** [comment]
https://github.com/solana-labs/solana/issues/25796 👀

**Comment by steveluscher** [comment]
Thanks for helping me discover that the Solana-hosted RPC nodes are running in HTTP/1.1 mode. Changing that is going to have a huge impact on the ecosystem overall.

With respect to this GitHub issue though, I don't think we're going to pull this into the core library. The good news, though, is that you can implement this as a custom `fetch` function!

Supply your own `fetch` function here:

```
const connection = new Connection(URL, {customFetch: myBatchingFetchFn});
```

The implementation of `myBatchingFetchFn` basically:

* intercepts requests
* coalesces requests received within a time window
* makes requests in a single batch
* fans the responses out

**Comment by epicfaace** [comment]
@steveluscher amazing! What a find.

**Comment by devDesu** [comment]
> Thanks for helping me discover that the Solana-hosted RPC nodes are running in HTTP/1.1 mode. Changing that is going to have a huge impact on the ecosystem overall.
> 
> With respect to this GitHub issue though, I don't think we're going to pull this into the core library. The good news, though, is that you can implement this as a custom `fetch` function!
> 
> Supply your own `fetch` function here:
> 
> ```
> const connection = new Connection(URL, {customFetch: myBatchingFetchFn});
> ```
> 
> The implementation of `myBatchingFetchFn` basically:
> 
> * intercepts requests
> * coalesces requests received within a time window
> * makes requests in a single batch
> * fans the responses out

@steveluscher could you please share the fn impl?
Btw, how do you manage rpc rate limit using mentioned fn? In my project I have to manually wait between rpc requests to prevent rate-limit errors

**Comment by steveluscher** [comment]
I have nothing to share @devDesu – I would have to write it from scratch! If you need such a thing, I'm sure that you can find a community of builders to collaborate with you on it.

**Comment by huybuidac** [comment]
Maybe too late,
You can use [connection.getmultipleaccounts ](https://solana.com/docs/rpc/http/getmultipleaccounts#parameters)
Or you still want independence fetch account but auto collect requests in 100s to batch. You can use [solana-batch-requests](https://github.com/huybuidac/solana-batch-requests?tab=readme-ov-file#usage)
