### ISSUE TITLE
Downloading incremental snapshot logic

### ISSUE THREAD

**Issue by diman-io** [solana-labs/solana#23625]
#### Problem

Looks the logic of downloading incremental snapshot is not very friendly for validators.

I have read the code and for my mind the main issue is detecting the bests full and diff snapshots in the same time.

#### Proposed Solution

To my mind will be better to first get the best full snapshot (with previous logic: using only age).

And only after that try to get incrimental snapshot (when information about actual local full snapshot exist). This search loop need to be limit some tries, 10 for example. If any right one doesn't exist in gossip, than the best way is conitnuing to bootstrap validator from full snapshot only.

And second, it's very strange to see such comments, because as node operator I need full automatic restart process, while something wrong and I sleep for example. I don't want to be depended from know-validator configs. It may be long catchup (because full snapshot is very old), but I want to be sure that it will start and work.

![image](https://user-images.githubusercontent.com/71597545/158013242-95145af3-ac90-4613-9e28-0bb92161b6f4.png)

**Comment by diman-io** [comment]
Or may be a smart way is to calculate the best time (downloading full&diff + catchup, using local + downloading diff + catchup,  etc) and to choose it.

**Comment by brooksprumo** [comment]
Hi @diman-io 

Thanks for raising this issue. I think the code hopefully functions as you would like, but the comments are outdated and incorrect.

Specifically:

* If incremental snapshots are disabled, nothing about bootstrap has changed.
* Specifying known validators to bootstrap from has not changed. The known validators that are specified in the CLI args are used to whitelist the snapshot hashes that are valid from the rest of the cluster.
* When picking snapshots from the cluster to download, they are picked based on:
    1. match a snapshot hash from the known validators
    2. have the highest full snapshot slot
    3. have the highest incremental snapshot slot

  This means that the snapshot with the highest slot will always been chosen. It may be just a full snapshot, or it may be a combination of a full snapshot plus an incremental snapshot.

Other points:

* Validators may disable downloading snapshots, that has not changed. Use `--no-snapshot-fetch`.
* There are retry logic and limits within bootstrap currently. If I understand correctly, these could be expanded to ensure they cover your desired usage.
* I believe there is existing logic that calculates the best restart time/window. This can be seen in the `wait-for-restart-window`:
https://github.com/solana-labs/solana/blob/17cc095d2892654225b5efe91b55c19eb932bfd3/validator/src/main.rs#L1747-L1749
https://github.com/solana-labs/solana/blob/17cc095d2892654225b5efe91b55c19eb932bfd3/validator/src/main.rs#L275-L279

Let me know if I've missed anything. Thanks!

**Comment by brooksprumo** [comment]
@diman-io This issue was auto-closed due to me merging PR #23664. Please re-open this issue if you feel that it has not been sufficiently addressed. Thank you!
