### ISSUE TITLE
Cannot deploy programs to the devnet

### ISSUE THREAD

**Issue by Beardev118** [solana-labs/solana#23639]
#### Problem
I can't deploy the program to the devnet

![image](https://user-images.githubusercontent.com/55624311/158085959-d25bb7ce-fab5-4a9a-98ff-30de9bf414bc.png)

**Comment by qbig** [comment]
anecdotally 1.9.* solana-cli cannot deploy to devnet. https://github.com/project-serum/anchor/issues/1157#issuecomment-1065828414

try using 1.8.12 ?

**Comment by Beardev118** [comment]
Hello, qbig
I have already changed the cli version to 1.8.12, but result was same.

**Comment by t-nelson** [comment]
Can you try with, newly released, v1.9.12?

**Comment by Beardev118** [comment]
Yeah, @t-nelson

**Comment by t-nelson** [comment]
and?

**Comment by Beardev118** [comment]
But result is same :(

**Comment by dafyddd** [comment]
I have the same issue. Tried latest 1.9 and also 1.11 and still can't deploy to devnet. I was able to get one deployment through but I get Invalid blockhash other times. It also takes a long time. So I think we're fetching the blockhash too soon or something.

**Comment by dafyddd** [comment]
@t-nelson suggested I use solana cli 1.10.4 or higher and add `--skip-fee-check` to solana program deploy. This worked. But he also mentioned this is a short term hack and not ideal.

**Comment by t-nelson** [comment]
correct. if you're going to try this flag, be _sure_ that you have well more than enough SOL in the deploy wallet to complete the operation. if you don't know how to calculate that, don't use the flag.  it's hidden for a reason (we don't want to support it)

**Comment by Beardev118** [comment]
Yeah, I'm using the new 1.10.5 version without flag, devnet deploy is okay.
So, I close this issue
