### ISSUE TITLE
Solana - Web3.js - Expo error

### ISSUE THREAD

**Issue by rares-munteanu** [solana-labs/solana#23635]
#### Problem

Environment - expo ( react native ) 

Anything I try to use from the solana web3.js sdk gives me this error : 

![image](https://user-images.githubusercontent.com/49690340/158082821-638a44ab-73bc-4135-a115-65df1ad2ba6e.png)

Already tried : 

https://github.com/solana-labs/solana/issues/22429
https://github.com/solana-labs/solana/pull/22433
https://stackoverflow.com/questions/52917733/cross-fetch-doesnt-work-with-react-native

**Comment by t-nelson** [comment]
Hi! We don't use github for support requests.  Please join us in #developer-support on https://solana.com/discord instead
