### ISSUE TITLE
Solana - Web3.js Transaction.from(tx.serialize()) changing account meta.

### ISSUE THREAD

**Issue by ArpitAgrawal321** [solana-labs/solana#23631]
#### Problem

All Solana Web3.js versions (tested above 1.25.0) mark account as writable/signer in all instructions if even one instruction has marked the Account as writable/signer. This provides the wrong account meta incase a transaction targets multiple programs.

E.G : One may have, Instruction1 with account1, programId1 with acc1 set as `writable: true`. But Instruction2 with account1, programId2 with acc1 set as read only (`writeable: false`).

The transaction obtained from `Transaction.from(tx.serialize())` has account1 set as writable for all instructions irrespective of other differences(`isSigner`, target `programId`) etc.

Also, Solana web3.js versions <1.31.0 give signature verification error when any non signer account is marked as writable. (when doing `Transaction.from(tx.serialize())`). This was apparently an account order issue that was fixed in web3.js@1.32.0 onwards but I still got signature verification errors with web3.js 1.35.0.

Not sure if these two issues are related.

Sample tx - 
```
{
  "signatures": [
    {
      "signature": {
        "type": "Buffer",
        "data": [
          3,
          62,
          141,
          24,
          211,
          242,
          184,
          136,
          6,
          180,
          127,
          142,
          247,
          51,
          53,
          90,
          122,
          8,
          68,
          123,
          103,
          244,
          65,
          31,
          118,
          115,
          245,
          178,
          9,
          168,
          211,
          41,
          133,
          46,
          160,
          177,
          110,
          65,
          255,
          71,
          211,
          90,
          178,
          72,
          12,
          241,
          188,
          202,
          204,
          93,
          147,
          180,
          68,
          222,
          163,
          29,
          134,
          39,
          253,
          25,
          120,
          114,
          132,
          1
        ]
      },
      "publicKey": "H4py5pqP3iXmc6Nqk69huVivS5dBBmvv3YMGMVHmvXua"
    }
  ],
  "feePayer": "H4py5pqP3iXmc6Nqk69huVivS5dBBmvv3YMGMVHmvXua",
  "instructions": [
    {
      "keys": [
        {
          "pubkey": "H4py5pqP3iXmc6Nqk69huVivS5dBBmvv3YMGMVHmvXua",
          "isSigner": true,
          "isWritable": true
        },
        {
          "pubkey": "27N9L8Uzg8PqKqiJVpJw9VRC6RDLiP2MqLUHtvavi1aT",
          "isSigner": false,
          "isWritable": true
        }
      ],
      "programId": "HJkHwWnipAYpaULgMasGdwX2nffWzknVSsEJyXfajqxw",
      "data": {
        "type": "Buffer",
        "data": []
      }
    },
    {
      "keys": [
        {
          "pubkey": "77HGAEaXKC2U299fczgF8Vkzu5Ex2gKMJbAdRNWsc1nq",
          "isSigner": false,
          "isWritable": false
        }
      ],
      "programId": "edx6VwBdA2mTATpFJA56RgdiH8YiLPgPXiCGSv3NayN",
      "data": {
        "type": "Buffer",
        "data": []
      }
    },
    {
      "keys": [
        {
          "pubkey": "5G1PNGra6mJ87yXEQ2aDdkK2wkMxMZqoQoLh7zizbu5M",
          "isSigner": false,
          "isWritable": true
        }
      ],
      "programId": "HMuYttVDGW4P3cZifsPUjtr1h9KtSsJ2rY88ik2mr6bj",
      "data": {
        "type": "Buffer",
        "data": []
      }
    },
    {
      "keys": [
        {
          "pubkey": "H4py5pqP3iXmc6Nqk69huVivS5dBBmvv3YMGMVHmvXua",
          "isSigner": true,
          "isWritable": true
        },
        {
          "pubkey": "27N9L8Uzg8PqKqiJVpJw9VRC6RDLiP2MqLUHtvavi1aT",
          "isSigner": false,
          "isWritable": false
        },
        {
          "pubkey": "5G1PNGra6mJ87yXEQ2aDdkK2wkMxMZqoQoLh7zizbu5M",
          "isSigner": false,
          "isWritable": false
        },
        {
          "pubkey": "77HGAEaXKC2U299fczgF8Vkzu5Ex2gKMJbAdRNWsc1nq",
          "isSigner": false,
          "isWritable": true
        }
      ],
      "programId": "amDDZsGy82QJHcC42rNXFVYkq4oXJUQUSWmMQ6EWtTw",
      "data": {
        "type": "Buffer",
        "data": []
      }
    }
  ],
  "recentBlockhash": "HZaTsZuhN1aaz9WuuimCFMyH7wJ5xiyMUHFCnZSMyguH"
}
```

After Transaction.from(tx.serialize()):

```
{
  "signatures": [
    {
      "signature": {
        "type": "Buffer",
        "data": [
          3,
          62,
          141,
          24,
          211,
          242,
          184,
          136,
          6,
          180,
          127,
          142,
          247,
          51,
          53,
          90,
          122,
          8,
          68,
          123,
          103,
          244,
          65,
          31,
          118,
          115,
          245,
          178,
          9,
          168,
          211,
          41,
          133,
          46,
          160,
          177,
          110,
          65,
          255,
          71,
          211,
          90,
          178,
          72,
          12,
          241,
          188,
          202,
          204,
          93,
          147,
          180,
          68,
          222,
          163,
          29,
          134,
          39,
          253,
          25,
          120,
          114,
          132,
          1
        ]
      },
      "publicKey": "H4py5pqP3iXmc6Nqk69huVivS5dBBmvv3YMGMVHmvXua"
    }
  ],
  "feePayer": "H4py5pqP3iXmc6Nqk69huVivS5dBBmvv3YMGMVHmvXua",
  "instructions": [
    {
      "keys": [
        {
          "pubkey": "H4py5pqP3iXmc6Nqk69huVivS5dBBmvv3YMGMVHmvXua",
          "isSigner": true,
          "isWritable": true
        },
        {
          "pubkey": "27N9L8Uzg8PqKqiJVpJw9VRC6RDLiP2MqLUHtvavi1aT",
          "isSigner": false,
          "isWritable": true
        }
      ],
      "programId": "HJkHwWnipAYpaULgMasGdwX2nffWzknVSsEJyXfajqxw",
      "data": {
        "type": "Buffer",
        "data": []
      }
    },
    {
      "keys": [
        {
          "pubkey": "77HGAEaXKC2U299fczgF8Vkzu5Ex2gKMJbAdRNWsc1nq",
          "isSigner": false,
          "isWritable": true (changed from false to true)
        }
      ],
      "programId": "edx6VwBdA2mTATpFJA56RgdiH8YiLPgPXiCGSv3NayN",
      "data": {
        "type": "Buffer",
        "data": []
      }
    },
    {
      "keys": [
        {
          "pubkey": "5G1PNGra6mJ87yXEQ2aDdkK2wkMxMZqoQoLh7zizbu5M",
          "isSigner": false,
          "isWritable": true
        }
      ],
      "programId": "HMuYttVDGW4P3cZifsPUjtr1h9KtSsJ2rY88ik2mr6bj",
      "data": {
        "type": "Buffer",
        "data": []
      }
    },
    {
      "keys": [
        {
          "pubkey": "H4py5pqP3iXmc6Nqk69huVivS5dBBmvv3YMGMVHmvXua",
          "isSigner": true,
          "isWritable": true
        },
        {
          "pubkey": "27N9L8Uzg8PqKqiJVpJw9VRC6RDLiP2MqLUHtvavi1aT",
          "isSigner": false,
          "isWritable": true (changed from false to true)
        },
        {
          "pubkey": "5G1PNGra6mJ87yXEQ2aDdkK2wkMxMZqoQoLh7zizbu5M",
          "isSigner": false,
          "isWritable": true (changed from false to true)
        },
        {
          "pubkey": "77HGAEaXKC2U299fczgF8Vkzu5Ex2gKMJbAdRNWsc1nq",
          "isSigner": false,
          "isWritable": true
        }
      ],
      "programId": "amDDZsGy82QJHcC42rNXFVYkq4oXJUQUSWmMQ6EWtTw",
      "data": {
        "type": "Buffer",
        "data": []
      }
    }
  ],
  "recentBlockhash": "HZaTsZuhN1aaz9WuuimCFMyH7wJ5xiyMUHFCnZSMyguH"
}
```

Demo Repo - https://github.com/torusresearch/solana-serialization-bug

#### Proposed Solution

Do not alter the account meta while generating the Transaction in `Transaction.from()`, `Transaction.populate()`

**Comment by bji** [comment]
I do not believe that writeability and signerness being transaction-wide properties is correct behavior.

Please give me a moment and I will describe my use case for which this promotion causes problems.  Will take some time for me to gather the details.

**Comment by jordansexton** [comment]
Please see https://github.com/solana-labs/solana/issues/21722#issuecomment-1067397222 for a more detailed explanation.

> `Message`, and the wire format of the message, does not store information that allows `AccountMeta` to be recreated per instruction. Only the number of signatures required, and the numbers of read-only accounts (signed and unsigned) are stored in the message header.
>
> In short, because of [this], `Transaction` to `Message` performs lossy compression. You can’t deterministically serialize a `Transaction` to a `Message` and deserialize this `Message` back to the original `Transaction`.

Once a `Transaction` is compiled to a `Message`, there is only one list of accounts, and the signer and writable flags are set on those accounts for the whole transaction. This is the expected behavior.

**Comment by bji** [comment]
My transaction has an instruction which takes three accounts:

- An account which is the "admin" account which must have signed the transaction.  For the transaciton, this account is { signer, read-only }.

- An account which is the funding account, which will be the source of funds for the transaction.  For this transaction, this account is { signer, read-write }.

- An account which is the program derived account to create.  This account is { read-write }.

In effect, this is a transaction which creates a PDA but only does so if the "admin" account has signed the transaction.

My program scrupulously checks the transaction to ensure that it satisfies the following criteria:

1. There are three accounts listed in the instruction's AccountMetas.
2. The first account is the admin account and is a signer and read-only
3. The second account is signer and read-write
4. The third account is read-write

Now if I use the web3.js transaction encoder, and if I specify the admin account and the funding account as the same account, then:

The transaction encoder will conflate the "admin" account with the "funding" account.  Even though I specified the keys array to correctly separately identify the admin account and funding account, the encoding will "promote" the admin account when representing the accounts in the AccountMetas.  As a result my program will be delivered a transaction that fails check (2) above because the admin account will be listed in the transaciton as read-write, but my program wants to ensure that this account is read-only.

I think my program should be allowed to expect that accounts will be listed with the properties I expect them to have, and that my sanity checks should not be invalidated by the web3.js encoding scheme.

**Comment by jordansexton** [comment]
I get it, and this was surprising to me too. You cannot check in a program that only your instruction has the account as writable or a signer. If it was flagged for one, it's flagged for all.

At its core, this is an issue with the serialization format of transaction messages, not with web3.js. Because it's fundamental, this seems unlikely to change, and if it were to change, it wouldn't change in web3.js first.

**Comment by bji** [comment]
> I get it, and this was surprising to me too. You cannot check in a program that only your instruction has the account as writable or a signer. If it was flagged for one, it's flagged for all.
> 
> At its core, this is an issue with the serialization format of transaction messages, not with web3.js. Because it's fundamental, this seems unlikely to change, and if it were to change, it wouldn't change in web3.js first.

When you say "You cannot check in a program that only your instruction has the account as writable or a signer. If it was flagged for one, it's flagged for all." are you saying that the runtime will pass AccountMetas that have been similarly conflated regardless of the transaction encoding?

Because it's definitely possible to encode transactions that have not conflated permissions.

**Comment by jordansexton** [comment]
Please see https://github.com/solana-labs/solana/issues/21722#issuecomment-1067397222. `MessageHeader` does not contain information on per-instruction `AccountMeta` flags. This means it's possible to serialize a web3.js `Transaction` with instructions with different flags, but this is a bit of an illusion. Over the wire, `AccountMeta` are transaction wide, which means the program will see them as such.

**Comment by bji** [comment]
I do not agree that "over the wire, AccountMeta are transaction wide".  From this document:

https://docs.solana.com/developing/programming-model/transactions

We see:

"Instruction Format[#](https://docs.solana.com/developing/programming-model/transactions#instruction-format)

An instruction contains a program id index, followed by a compact-array of account address indexes, followed by a compact-array of opaque 8-bit data. The program id index is used to identify an on-chain program that can interpret the opaque data. The program id index is an unsigned 8-bit index to an account address in the message's array of account addresses. The account address indexes are each an unsigned 8-bit index into that same array."


Each instruction has its own compact-array of account address indexes.  The account indexes for each instruction can be different than the other instructions in the same transaction.  Therefore one instruction can refer to the read-only entry for a given account address, and another instruction can refer to the read-write entry for a given account address.

Therefore the following is possible

In the transaction's Message header:

Address index 0 (signed, read-write): Address A
Address index 1 (signed, read-only): Address A
Address index 2 (unsigned, read-write): Address A
Address index 3 (unsigned, read-only): Address A

Instruction 0
Account Address Index 0
Account Address Index 3

In this case, instruction 0 references Address A both as signed-read write (in its first address index reference) and as unsigned read-only (in its second address index reference).

This is absolutely possible with the transaction encoding format.

What I am less sure of is how the actual program runtime handles these addresses.  I'm mostly concerned with cross-program invocation.  I had assumed that if I had read-only AND read-write entries for the same address in my transaction, that a given instruction could choose which "version" to pass on to a separate program via CPI.  But I am worried that there is something more global about how address permissions are treated as transactions are executed and that even if I pass a read-only account index into a CPI invocation, if that account was actually loaded read-write by my transaction, that the CPI-invoked program will still either see it as read-write, or be able to elevate their permissions somehow to read-write.

**Comment by bji** [comment]
> You are mistaking an [`Instruction`](https://github.com/solana-labs/solana/blob/bb9f9c8dd51073477a57707580e2befe1eed8866/sdk/program/src/instruction.rs#L324-L334) which is a client-side, transaction construction concept, with [`CompiledInstruction`](https://github.com/solana-labs/solana/blob/bb9f9c8dd51073477a57707580e2befe1eed8866/sdk/program/src/instruction.rs#L625-L634) which is what goes over the wire and is interpreted by the runtime. The latter has `AccountMeta`s aggregated into the `Message` in a lossy way

I don't think I am though.  The transaction format is clearly defined.  I'm not using Instruction or CompiledInstruction.  I'm hand rolling bytes of the transaction and sending them.

Here is a base64 encoded example of such a tranaction:

Ahrh21PAuv8/X4ubAMJ2cz1cF/XrlBlTv4ts6r6hpY4Cyt+AcVd0KUkMm5sj7yDmXWhXi+O93pb5
82r3VJFPpAUa4dtTwLr/P1+LmwDCdnM9XBf165QZU7+LbOq+oaWOAsrfgHFXdClJDJubI+8g5l1o
V4vjvd6W+fNq91SRT6QFAgEDBqS7up5fkKlhItz5vTA/pE1GDdZnG7GctNMnBXNztD1apLu6nl+Q
qWEi3Pm9MD+kTUYN1mcbsZy00ycFc3O0PVrg8UpYFJtuhOLoRodzKXiXCmAshBAH+WTz3sby3/sP
IpBiZxj5+7AhIrlqzdgGGF0bPR3bYuXlRq/Ie2mTrblipLu6nl+QqWEi3Pm9MD+kTUYN1mcbsZy0
0ycFc3O0PVoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIXI6NwNPN+AfqBiOrEwIuTQ
WFrzg9dZTDvZIaPhR3HeAgMFBAEABQIqAAAQJwAAAAAAAGQAAAAAAAAACgAAAAAAAABkAAAAAAAA
AOgDAAAAAAAAAwMEAQKaAQEAECcAAAAAAABkAAAAAAAAAAoAAAAAAAAAZAAAAAAAAAABAAAAAAAA
ADgwAAAAAAAACwAAAAAAAAB7AAAAAAAAALwEAAAAAAAAU1oAAAAAAABUWgAAAAAAAHsAAAAAAAAA
6gAAAAAAAABZAQAAAAAAAHgDAAAAAAAAbwAAAAAAAAD6kgMAAAAAAEIAAAAAAAAA6AMAAAAAAAA=

You can plug this into the "Inspector" on the solana block explorer:

https://explorer.solana.com/tx/inspector?cluster=testnet&signatures=%255B%2522YB2MQRxS9osjvTL1RNdyT9P5dxhUr2hxnxENB2ehjmkMsMz4xmKveLVCg72MB4xy7UbghMFYpambykfDNfKEAGt%2522%252C%2522YB2MQRxS9osjvTL1RNdyT9P5dxhUr2hxnxENB2ehjmkMsMz4xmKveLVCg72MB4xy7UbghMFYpambykfDNfKEAGt%2522%255D&message=AgEDBqS7up5fkKlhItz5vTA%252FpE1GDdZnG7GctNMnBXNztD1apLu6nl%252BQqWEi3Pm9MD%252BkTUYN1mcbsZy00ycFc3O0PVrg8UpYFJtuhOLoRodzKXiXCmAshBAH%252BWTz3sby3%252FsPIpBiZxj5%252B7AhIrlqzdgGGF0bPR3bYuXlRq%252FIe2mTrblipLu6nl%252BQqWEi3Pm9MD%252BkTUYN1mcbsZy00ycFc3O0PVoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIXI6NwNPN%252BAfqBiOrEwIuTQWFrzg9dZTDvZIaPhR3HeAgMFBAEABQIqAAAQJwAAAAAAAGQAAAAAAAAACgAAAAAAAABkAAAAAAAAAOgDAAAAAAAAAwMEAQKaAQEAECcAAAAAAABkAAAAAAAAAAoAAAAAAAAAZAAAAAAAAAABAAAAAAAAADgwAAAAAAAACwAAAAAAAAB7AAAAAAAAALwEAAAAAAAAU1oAAAAAAABUWgAAAAAAAHsAAAAAAAAA6gAAAAAAAABZAQAAAAAAAHgDAAAAAAAAbwAAAAAAAAD6kgMAAAAAAEIAAAAAAAAA6AMAAAAAAAA%253D

You will see that the transaction does in fact have the same account listed multiple times.

**Comment by bji** [comment]
> If you're going to insist on writing your own serializer, I suggest you start [here](https://github.com/solana-labs/solana/blob/master/sdk/program/src/message/legacy.rs#L321).

I'm done already, but thanks.  I started with documentation, not cribbing code ... yes, you run into more rough edges and unexpected dark corners this way, but I believe I understand those rough edges and dark corners better for it.

I think probably there is some additional documentation that could help the next person.  I'll see what I can do ...

**Comment by jordansexton** [comment]
Can we agree that this isn't specifically an issue with web3.js and close? 🤝

**Comment by bji** [comment]
> Can we agree that this isn't specifically an issue with web3.js and close? handshake

Yes thank you for indulging me.
