### ISSUE TITLE
multinode tests ignored, likely borken

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#2363]
#### Problem
lots of multinode tests (integration tests) have been written, but commented out over time due to flakiness, changing underlying software (e.g. switch to db_ledger from ledger)

#### Proposed Solution
review multinode tests to see what's worth keeping, what should be moved into unit tests, what should be dropped altogether

**Comment by mvines** [comment]
Mostly addressed as a part of #2443.  New issues, #2481 and #2482, track the remaining work required to fully restore all the multinode tests.
