### ISSUE TITLE
Report of a scam wallet 

### ISSUE THREAD

**Issue by Funmilayo21** [solana-labs/solana#23640]
9g68a62FCo2Y1bws3DskPuH42kB9s4FmkURz6nfSzAZh

Someone that can't be regonize scam of alot people about 1000 +
 Sol ,by a creating a fake link of phantom  

He is using this to wallet to withdraw from peoples account when he have hack there wallet ,which am among the victim of which he scammed 

C3wYXM7y7xNM8vov5iHFg6vuArhVWPpWY6TYbdCNW2Ai

KwdWLkrpkGrQque5mzhRkRrwj7N8Q9zDCvaY7pJAVt8

From this above two  wallet ,he will now transfer it to the first wallet 

9g68a62FCo2Y1bws3DskPuH42kB9s4FmkURz6nfSzAZh

Kindly block the account  sir , your faithfully

**Comment by t-nelson** [comment]
There is no way to block accounts on Solana.  Please do not report scams on github.  It is not the appropriate venue.  There is nothing devs can do about them.
