### ISSUE TITLE
Unpacking genesis.tar.bz2 could clobber rocksdb files

### ISSUE THREAD

**Issue by steviez** [solana-labs/solana#23666]
#### Problem
A genesis archive `genesis.tar.bz2` may contain several files (namely, `genesis.bin` and RocksDB files that correspond to having inserted slot 0 into the blockstore):
https://github.com/solana-labs/solana/blob/17cc095d2892654225b5efe91b55c19eb932bfd3/runtime/src/hardened_unpack.rs#L461-L475

When starting up, a check will be run to see if `genesis.bin` can be located. If not, the code will attempt to unpack `genesis.tar.bz2`:
https://github.com/solana-labs/solana/blob/17cc095d2892654225b5efe91b55c19eb932bfd3/runtime/src/hardened_unpack.rs#L396-L408

This issue occurs in the second case when the user has `genesis.tar.bz2` file but not `genesis.bin`:
- With a brand new ledger (that doesn't have anything in `rocksdb` directory yet), there are no issues in fully expanding `genesis.tar.bz2`.
- With a ledger that has existing blockstore data, the expansion of the archive could "mix" RocksDB files from the existing `rocksdb` and from what is in the archive; this mix can put RocksDB into a bad state.

It seems unlikely to hit this situation while running a node; the operator would have to do something like wipe their `genesis.bin` file without wiping their `rocksdb` directory. However, one could easily encounter this situation while assembling a ledger to replay slots with `solana-ledger-tool verify`.

Even if we don't want to make this situation work, we could probably be friendlier about detecting this issue and avoiding it as this scenario may cause a user to lose the data that was in their ledger.

#### Proposed Solution
~~Open to opinions on this; a couple options that come to mind quickly (going to circle back here later):~~
- ~~Error out~~
- Extract only the `genesis.bin` file from `genesis.tar.bz2`
- ~~Extra all file to temp directory, and then "merge" the rocksdb instances~~
   - ~~This might look similar to `solana-ledger-tool copy` with existing `rocksdb` as target and extracted `rocksdb` as source~~

Per comment from mvines below, we'll go with only extracting the `genesis.bin` from the archive

**Comment by mvines** [comment]
Removing/ignoring the rocksdb from `genesis.tar.bz2` would be fine. A while back I even modified the testnet and mainnet genesis.tar.bz2 archives on the Labs servers to manually remove their `rocskdb/`

**Comment by steviez** [comment]
Thanks for chiming in @mvines.
>A while back I even modified the testnet and mainnet genesis.tar.bz2 archives on the Labs servers to manually remove their rocskdb/

Nice - the reason we even encountered this was using `genesis.tar.bz2` from this bucket:
```
gs://mainnet-beta-ledger-us-ny5/genesis.tar.bz2
```
I'll look into checking / updating the `genesis.tar.bz2` in this bucket (as well as the other mainnet and testnet warehouse buckets)

**Comment by steviez** [comment]
Also - I'm now wondering if we needed this
https://github.com/solana-labs/solana/pull/23236/files#diff-487ddb1f71c5dc12093c4109146b9fc0aac6a6b9c2fd875fa5a22a3672b616a0R470-R472

**Comment by mvines** [comment]
> Nice - the reason we even encountered this was using genesis.tar.bz2 from this bucket:

Ah, yeah i wasn't so evil to rewrite the genesis archives in the gcp buckets :)

> Also - I'm now wondering if we needed [this](https://github.com/solana-labs/solana/pull/23236/files#diff-487ddb1f71c5dc12093c4109146b9fc0aac6a6b9c2fd875fa5a22a3672b616a0R470-R472).

Na, not really.  Probably harmless though. 

I think ideally we just modify `solana-genesis` to stop including rocksdb, regardless of how it's stored.  This is mostly for the benefit of future custom clusters of course.

**Comment by CriesofCarrots** [comment]
Turns out another upshot of this issue is that a node booting from a freshly unpacked `genesis.tar.bz2` rocksdb will always think its first-available block is 0 until that slot is pruned.
While it is technically true that block 0 is available, it breaks assumptions that the ledger of a fresh node will start at the snapshot slot, which is how a node booted fresh but with a local `genesis.bin` will behave.

This is causing issues for the bigtable_upload_service, which uses first-available block in its logic.

**Comment by steviez** [comment]
>I think ideally we just modify solana-genesis to stop including rocksdb, regardless of how it's stored. This is mostly for the benefit of future custom clusters of course.

@mvines - The function in question that (used by `solana-genesis`) includes rocksdb is this one
https://github.com/solana-labs/solana/blob/178eba4912ffbe83fc1e3b7d81790033af5333b9/ledger/src/blockstore.rs#L3807-L3815
And specifically the inclusion of `blockstore_dir` in the tar args here:
https://github.com/solana-labs/solana/blob/178eba4912ffbe83fc1e3b7d81790033af5333b9/ledger/src/blockstore.rs#L3853-L3861

We have a decent number of tests that use this function (mostly indirectly through convenience macros), so making this change may break some tests. Updating tests is fine, but I just want to make sure we wouldn't be breaking anything else.

The slot full of ticks in slot 0 that is currently inserted is configured be genesis' tick_per_slot and hashes_per_tick, and additionally, they chain off genesis hash. So, this slot could easily and reliably be recreated. In a hypothetical new cluster (such as the ones we spin up to test), the bootstrap leader would do this, so there is no need to include slot 0 with genesis; does this sound correct or am I missing anything?

**Comment by mvines** [comment]
i've been thinking that a real nice way to solve this would be for `solana-genesis` to write a snapshot for the slot 0 bank in addition to the genesis tarball (without rocksdb/).  With that in place, we could reduce the ledger loading code to always require a snapshot (and interestingly slot 0 would then longer exist in the ledger)

**Comment by steviez** [comment]
Hmm, that's an interesting thought and would definitely remove some "special case" code in in blockstore_processor.

That change might be a little more involved, and regardless, we could still have `genesis.tar.bz2`'s in the wild that have `rocksdb` that we need to ignore. As such, do you mind if I sum up the relevant conversation around modifying `solana-genesis` and make that into a separate issue?

**Comment by mvines** [comment]
> As such, do you mind if I sum up the relevant conversation around modifying solana-genesis and make that into a separate issue?

Not at all.
