### ISSUE TITLE
code coverage doesn't see constructors, other lines with hidden panic code

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#2367]
#### Problem
code coverage doesn't see constructors, other lines with hidden panic code, resulting in wrongish coverage metrics, weird artifacts like very basic code (Poh::new()) not being in the "covered" space...

https://codecov.io/gh/solana-labs/solana/src/master/src/poh.rs

https://github.com/rust-lang/rust/issues/55352

Rustc adds line-number information for unhittable panic handlers ...

#### Proposed Solution
??

**Comment by garious** [comment]
My understanding is that a panic handler called a *landing pad* is implicitly added by default and that the way to disable it is passing LLVM the `-Z no-landing-pads`.  This test demonstrates how it works: https://github.com/rust-lang/rust/blob/master/src/test/run-pass/no-landing-pads.rs

@rob-solana says he experimented with add that flag after `-Zprofile` here: https://github.com/solana-labs/solana/blob/master/scripts/coverage.sh#L16, but didn't see any change in coverage.

I think we need to find a way to see what code is being generated with and without that flag to ensure it's not dropped by the Rust toolchain somewhere along the way.

**Comment by garious** [comment]
@jackcmay, not a super high priority, but can you keep this one on your radar?

**Comment by bossmc** [comment]
A warning, disabling landing pads breaks some other things (e.g. `#[expect_panic]` tests, and thread death reporting).  Maybe that's fine for your use case, but you should be aware 😄.
