### ISSUE TITLE
Linker could do a better job of concatenating sections

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#23711]
#### Problem

Linker could do a better job of concatenating sections

#### Proposed Solution

Reduce the overhead for the loader at runtime, by letting the linker concatenate sections to become consecutive in virtual address space

**Comment by alessandrod** [comment]
https://github.com/solana-labs/rust/pull/52

**Comment by pgarg66** [comment]
@dmakarov can this be closed?
