### ISSUE TITLE
Proposal for how frontends for dapps will deal with rollback

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#2372]
#### Problem
When state is rolled back in a validator, the app needs to reflect that in its UI.

#### Proposed Solution

1. Apps should always display the "latest" state
2. When rollback occurs, a validator will notify any subscribed dapps of accounts that were rolled back.

Subscriptions are distributed amongst all the validators, so the number of queries against the rollback set of accounts should be small.

##### TODO
What do we do with concurrent non yet voted on forks that are modifying the same state?

tag: @mvines

**Comment by mvines** [comment]
Dup of #2373 ;)
