### ISSUE TITLE
Client API semantics undefined in the context of rollback

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#2373]
When the ledger is rolled back, RPC API users need to be notified somehow that this event has occurred so they can update their front-ends according to the new (err, old) state of the cluster.

One cheap solution could be a pubsub notification that a rollback has occured.  Virtually front-ends should subscribe to this and use it as a signal to reinitialize themselves.

There's a couple distinct parts of this issue:
* [ ] The fullnode notification mechanism itself
* [ ] Surfacing that notification via the solana-web3.js API
* [ ] Augmenting the example apps to use it

cc: #2372

**Comment by aeyakovenko** [comment]
What do we do about concurrent forks?

**Comment by mvines** [comment]
IMO the RPC API for a given node should only operate on the most likely correct fork, however we define that, and if/when the RPC API jumps to a different fork it emits a "reset" notification.   
Surfacing concurrent forks to the RPC API would be a nightmare for the front-end author

**Comment by mvines** [comment]
We could also provide a "confidence level" API -- for a given transaction signature, how confident is the node that the transaction won't be rolled back.

**Comment by aeyakovenko** [comment]
> IMO the RPC API for a given node should only operate on the most likely correct fork, however we define that, and if/when the RPC API jumps to a different fork it emits a "reset" notification.
> Surfacing concurrent forks to the RPC API would be a nightmare for the front-end author

**Comment by garious** [comment]
One more idea, how about we return the value at all active forks and a finalized root? Very similar to the confidence level ideal, but providing more information about what the value *might* be.  If there are, for example, only 2 different values and they are very close, the client could conclude "good enough for me!".

**Comment by mvines** [comment]
#2474 is what we need I think, we never do an online rollback
