### ISSUE TITLE
The CPI sanity test suite fails without optimization

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#23739]
#### Problem

TOB-SOL-022

If optimization is disabled using opt-level = 0, the resulting BPF program contains stack frames larger than the limit of 0x1000 bytes. This causes access errors when the BPF program is invoked in the test test_program_bpf_invoke_sanity.

```
0000000000000e88 <solana_bpf_rust_invoke::processor::process_instruction>
465 7b 5a a0 ba 00 00 00 00 466 7b 4a 88 ba 00 00 00 00 467 7b 3a 90 ba 00 00 00 00 468 7b 1a 98 ba 00 00 00 00 469 7b 2a 38 bc 00 00 00 00
*(u64 *)(r10 - 0x4560) = r5
*(u64 *)(r10 - 0x4578) = r4
*(u64 *)(r10 - 0x4570) = r3
*(u64 *)(r10 - 0x4568) = r1
*(u64 *)(r10 - 0x43c8) = r2
470 18 01 00 00 89 cc 05 00
472 b7 02 00 00 13 00 00 00
473 85 10 00 00 76 23 00 00
474 79 a5 a0 ba 00 00 00 00
475 79 51 08 f0 00 00 00 00
476 7b 1a a8 ba 00 00 00 00
477 79 51 00 f0 00 00 00 00
478 7b 1a b0 ba 00 00 00 00
479 05 00 00 00 00 00 00 00
00 00 00 00 00 00 00 00 r1 = 0x5cc89 ll r2 = 0x13
   call 0x2376 ; <solana_program::log::sol_log>
   r5 = *(u64 *)(r10 - 0x4560)
   r1 = *(u64 *)(r5 - 0xff8)
   *(u64 *)(r10 - 0x4558) = r1
   r1 = *(u64 *)(r5 - 0x1000)
   *(u64 *)(r10 - 0x4550) = r1
   goto +0x0 <LBB1_1>
```

#### Proposed Solution

Short term, depending on the planned dynamic stack frame feature, consider rewriting the test to ensure that the stack frame does not exceed the limits. This ensures that the tests can complete with both optimized and unoptimized code.

Long term, as with previous stack related issues, the implementation of a dynamic stack frame size eliminates this problem.

**Comment by dmakarov** [comment]
This issue depends on and resolved by #23481.
