### ISSUE TITLE
Insufficient transaction sanitization documentation

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#23740]
#### Problem

TOB-SOL-023

In several places, the code claims that a condition is impossible given that a relevant transaction has been “sanitized.” However, the guarantees provided by a sanitized transaction are unclear and seemingly undocumented, making it difficult to verify such claims.
The declaration of a sanitized transaction appears below. Its description consists of a single sentence.

```
/// Sanitized transaction and the hash of its message
#[derive(Debug, Clone)]
pub struct SanitizedTransaction {
   message: SanitizedMessage,
   message_hash: Hash,
   is_simple_vote_tx: bool,
   signatures: Vec<Signature>,
}
```

The function try_create seems to be the primary means of creating a sanitized transaction (below). Its arguments are complex and consist of more than just an unsanitized transaction.

```
/// Create a sanitized transaction from an unsanitized transaction.
   /// If the input transaction uses address tables, attempt to lookup
   /// the address for each table index.
   pub fn try_create(
       tx: VersionedTransaction,
       message_hash: Hash,
       is_simple_vote_tx: Option<bool>,
       address_loader: impl Fn(&[MessageAddressTableLookup]) ->
Result<LoadedAddresses>,
   ) -> Result<Self> {
```
  
 try_create is wrapped by several different functions. In banking_stage.rs, the function is wrapped by transactions_from_packets: 

```
      // This function deserializes packets into transactions, computes the blake3 hash
of transaction
   // messages, and verifies secp256k1 instructions. A list of sanitized
transactions are returned
   // with their packet indexes.
   #[allow(clippy::needless_collect)]
   fn transactions_from_packets(
       packet_batch: &PacketBatch,
       transaction_indexes: &[usize],
       feature_set: &Arc<feature_set::FeatureSet>,
       votes_only: bool,
       address_loader: impl Fn(&[MessageAddressTableLookup]) ->
transaction::Result<LoadedAddresses>,
   ) -> (Vec<SanitizedTransaction>, Vec<usize>) {
       transaction_indexes
           .iter()
           .filter_map(|tx_index| {
               let p = &packet_batch.packets[*tx_index];
               if votes_only && !p.meta.is_simple_vote_tx() {
                   return None;
               }
               let tx: VersionedTransaction =
limited_deserialize(&p.data[0..p.meta.size]).ok()?;
               let message_bytes = Self::packet_message(p)?;
               let message_hash = Message::hash_raw_message(message_bytes);
               let tx = SanitizedTransaction::try_create(
                   tx,
                   message_hash,
                   Some(p.meta.is_simple_vote_tx()),
                   &address_loader,
               )
               .ok()?;
               tx.verify_precompiles(feature_set).ok()?;
               Some((tx, *tx_index))
})
.unzip() }
```
in rpc.rs, the function is wrapped by sanitize_transaction:

```
   fn sanitize_transaction(transaction: VersionedTransaction) ->
Result<SanitizedTransaction> {
   let message_hash = transaction.message.hash();
   
SanitizedTransaction::try_create(transaction, message_hash, None, |_| {
       Err(TransactionError::UnsupportedVersion)
})
   .map_err(|err| Error::invalid_params(format!("invalid transaction: {}", err)))
}
```

In bank.rs, the function is wrapped by prepare_entry_batch (figure 23.5), though apparently only for tests:

```
/// Prepare a transaction batch from a list of versioned transactions from
   /// an entry. Used for tests only.
   pub fn prepare_entry_batch(&self, txs: Vec<VersionedTransaction>) ->
Result<TransactionBatch> {
       let sanitized_txs = txs
           .into_iter()
           .map(|tx| {
               let message_hash = tx.message.hash();
               SanitizedTransaction::try_create(tx, message_hash, None, |_| {
                   Err(TransactionError::UnsupportedVersion)
               })
})
           .collect::<Result<Vec<_>>>()?;
       let lock_results = self
           .rc
           .accounts
           .lock_accounts(sanitized_txs.iter(), &FeatureSet::all_enabled());
       Ok(TransactionBatch::new(
           lock_results,
self,
           Cow::Owned(sanitized_txs),
       ))
}
```

The need for multiple wrappers raises questions, as does the fact that production and test code use different wrappers

#### Proposed Solution

Short term, two recommendations:
● Document that properties that a sanitized transaction is meant to exhibit.
● If the non-transaction arguments to try_create can be obtained from a Bank,
then consider adding a method to Bank that wraps try_create and whose only argument is a transaction.
Performing these steps will reduce the risk of bugs being introduced because the guarantees provided by a sanitized transaction are misunderstood.
  
Long term, review other data types that can be “sanitized.” A cursory review of those data types suggests that they too lack sufficient documentation. Addressing the problem for other data types will help to ensure bugs are not introduced with respect to them.

**Comment by rtviii** [comment]
God, yeah. Thanks @jackcmay for bringing this up. All the primary and adjacent datatypes could use a few more words of disambiguation.

**Comment by rtviii** [comment]
What is being sanitized to begin with, for example..
