### ISSUE TITLE
zk syscalls are untested

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#23746]
#### Problem

QSP-4

The following system calls are not tested:
• sol_zk_token_elgamal_op;
• sol_zk_token_elgamal_op_with_lo_hi; and • sol_zk_token_elgamal_op_with_scalar.

#### Proposed Solution

Add tests

**Comment by jackcmay** [comment]
A security auditors brought this up, @samkim-crypto. can we get these tests in?

**Comment by samkim-crypto** [comment]
Yep, on it now.

**Comment by samkim-crypto** [comment]
These syscalls have been removed [(26311)](https://github.com/solana-labs/solana/pull/26311) and replaced by the curve25519 syscalls.

**Comment by samkim-crypto** [comment]
@jackcmay The curve operations use the dalek library implementation. Currently, there are just tests for native code in the `zk-token-sdk`
- https://github.com/solana-labs/solana/blob/master/zk-token-sdk/src/curve25519/edwards.rs#L217
- https://github.com/solana-labs/solana/blob/master/zk-token-sdk/src/curve25519/ristretto.rs#L219
and in `bpf/rust`
- https://github.com/solana-labs/solana/blob/master/programs/bpf/rust/curve25519/src/lib.rs

These syscalls have not been activated yet. If there are places that require more tests before activation, then I'd be happy to add more in.

**Comment by jackcmay** [comment]
Glad to hear there are tests for the curve operations themselves.  We should also have tests for the syscalls themselves (in/out param handling, compute unit consumption, etc...).  Take a look at the test for the other syscalls, they are located at the bottom of the file that declares/defines the syscalls

**Comment by joncinque** [comment]
We'll definitely want these tests if they don't exist -- @samkim-crypto do the tests exist now?

**Comment by samkim-crypto** [comment]
Yes these tests have been added long time ago. I think it is safe to close this.
