### ISSUE TITLE
Come up with a better name for accounts_data_len

### ISSUE THREAD

**Issue by brooksprumo** [solana-labs/solana#23759]
>lgtm, beyond that `accounts_data_len` name that I still think is a little misleading.
> 
> `total_accounts_size`?

_Originally posted by @mvines in https://github.com/solana-labs/solana/pull/23714#pullrequestreview-913798686_

`Bank::accounts_data_len` tracks the total on-chain size of the accounts data. What is a better name to communicate that description?

* total or no?
* account or accounts?
* data or no?
* len or size?

This name (and some variants) also live in:
* AccountsDataMeter
* CostTracker
* banking stage
* replay stage
* instruction errors
* transaction errors

If the Bank field is renamed, should all these others get renamed as well?

**Comment by t-nelson** [comment]
`global_accounts_data_bytes`?  `cumulative_accounts_data_bytes`?

:bike: :hut:
