### ISSUE TITLE
make verifykey with solana

### ISSUE THREAD

**Issue by mufarex** [solana-labs/solana#23768]
#### Problem
Hi. I'm a python-dev and I'm using solana to make wallets. after getting the pubkey I want to connect the wallet to dextools site since the site has two steps; step one is connecting the wallet and step two is wallet verification I should approve it in the code so I need Solana to make the verification code for me with the personal-sign that dextools sends to me. please guide me with the commands that I should use in the command line to make Solana do this. thank you

**Comment by t-nelson** [comment]
hi. we don't use github for support requests. please join us in #developer-support on https://solana.com/discord instead
