### ISSUE TITLE
How to get fee for a transaction that contains multiple instructions ?

### ISSUE THREAD

**Issue by walshe** [solana-labs/solana#23782]
#### Problem
stupid question but if I combine 2 instructions into one transaction, I get one signature right ? bit when I look up this transaction signature in the explorer it only has the fee that relates to one of the instructions. Is there a way I can find both related fees easily ?

The reason I ask is that in my app I keep a record of every signature and later on (asynchronously) I look up the transaction to also make a record of the fee in lamports.

**Comment by CriesofCarrots** [comment]
There is only one fee per transaction. Currently, that fee changes based on the number of signatures, and it may vary in the future based on other things (account locks, compute-units used by the instructions, etc.), but it will still be applied at the transaction level.

**Comment by walshe** [comment]
but when i execute a transaction with 2 instructions , and then check my wallet I see pointers to 2 links in the explorer both with a fee - on testnet anyway

**Comment by t-nelson** [comment]
hi. we don't use github for support requests. please join us in #developer-support on https://solana.com/discord
