### ISSUE TITLE
Deployment of large program binaries has low success rates.

### ISSUE THREAD

**Issue by xjcaa** [solana-labs/solana#23800]
#### Problem

When deploying a large program binary, (8.8mb) for us, it is very difficult to successfully write the full buffer. As a result, we just have to keep retrying until we hit a successful deployment (up to a few hours in off peak times)

There are two issues that I observe.

1. Blockhash expiration isn't tracked correctly.

Since a 8.8mb binary requires 8800 transactions to be sent (at least on the first attempt), by the time all transactions are sent, the blockhash *should* have already expired (roughly 88 seconds), which is greater than 150 slots ~= 60 seconds. 

When deploying a binary of such a size, it will keep retrying on the same blockhash until it has determined the block hash has expired, which is well beyond 150 slots. (As such any subsequent sending of transactions do not progress the deployment progress bar past the first attempt). 

I don't think the CLI properly tracks the slots elapsed while sending the tx's in the first place, given the CLI does display something like;
```
[block height X; re-sign in Y blocks]
```
though Y seems to only progress in between the sending of deployment transactions.

2. Block hash retry limit of 5.

This limit given issue 1 means it is really a roll of the dice as to whether we can get all the transactions required to successfully write our buffer.

#### Proposed Solution

1. Easy fix - allow CLI user to specify max number of block hash retries instead of capping it at 5. This way at least I can specify a higher N and know it'll succeed eventually, instead of getting pretty close and failing at 95% deployed on the last blockhash.
2. Use a new blockhash every time, instead of waiting X blocks to re-sign.

**Comment by soloffame** [comment]
Have also seen this intermittently deploying my program which is 400KB.

**Comment by xjcaa** [comment]
Update: a workaround solution that works for me is to:
1. Skip fee check in the deployment (which stops the hanging until invalid blockhash), on the CLI seen in 1.9.x.
2. Custom build the solana binary with a much higher retry amount.

**Comment by rinswend** [comment]
This is a dup of #23427
