### ISSUE TITLE
Incorrect stats with Quic Forwarding

### ISSUE THREAD

**Issue by ryleung-solana** [solana-labs/solana#23819]
#### Problem
See #23817 - forwarding packets via Quic currently returns incorrects values on the number of packets successfully sent in the case of a failure. In the interest of shipping Quic support, this has been allowed for now, but we want to return correct values eventually.

#### Proposed Solution
Implement reporting of number of succeeded buffers in quic-client, and propagate this information up.

**Comment by t-nelson** [comment]
Can you elaborate what makes this difficult to implement now?
