### ISSUE TITLE
Evaluate if necessary to persist program's cost to blockstore

### ISSUE THREAD

**Issue by taozhu-chicago** [solana-labs/solana#23848]
#### Problem

`Replay_stage` sends each Program's execution cost `Units` to `cost_model`, which runs a variation of average function to keep tracking Program's average cost. 

The map of `<Program_Id, average_cost_units>` can be persisted into blockstore like [this](https://github.com/solana-labs/solana/blob/7aa1fb4e2494a372ba513b2775d1134180aff3a1/core/src/cost_update_service.rs#L182-L206). 

This block of code was temporally removed due to issue described in #23575. For context, wrong average value was produced and consequently persisted into blockstore, which is used to initialized in-memory Program's cost table during validator startup.   That caused the average algorithm continuously running bad data, eventually it assigned an unreasonable large cost Units for `cndy` that prohibits landing in block. 

So the issue is _"is it necessary to persist Program costs to blockstore?"_ 

The main motivation of persisting is it provides continuity of Program cost between Validator restart. But as above incidence demonstrate there is a need to reset persisted value; This can be done via separate tool (perhaps ledger-tool to erase table content), or through an additional command-line param for Validator to skip loading (or resetting) persisted cost table. 

If cost table is not persisted, then restarting Validator will give it a clean state to start with. The in-memory cost table will be populated by validator replaying blocks from ledger after start up. 

#### Proposed Solution

I propose to not to persist cost table to blockstore, because: 
- Persisting has little value (eg., in-memory cost table can be initialized by replaying blocks after startup)
- Persisting requires additional tool/method to reset table, adds operational cost,
- Persisting incurs additional run-time cost. 

Would like feedback on this. If agreed to not to persist, [ProgramCosts table](https://github.com/solana-labs/solana/blob/master/ledger/src/blockstore.rs#L172) can be removed from blockstore.

**Comment by taozhu-chicago** [comment]
@carllin @t-nelson @sakridge wdyt

**Comment by t-nelson** [comment]
Do we have an estimate of how long it takes the cost estimates to stabilize upon restart?

**Comment by taozhu-chicago** [comment]
> Do we have an estimate of how long it takes the cost estimates to stabilize upon restart?

That starting value `v(1)` of the average function is the first input data `x(1)`, after that `v(n) = avg(v(n-1), x(n))`. So if input data is stable, it technically takes 1 data point to catch up; otherwise, if same `program`'s cost is rather volatile, then it might be a separate issue itself.
