### ISSUE TITLE
Feature request: Validator failover without etcd

### ISSUE THREAD

**Issue by ruuda** [solana-labs/solana#23842]
#### Problem

The [validator failover support introduced in 1.10](https://docs.solana.com/running-validator/validator-failover) is cool, but putting etcd on the critical path is also a risk. It’s one more thing that can fail or that can be misconfigured. If it’s on a separate machine, `P(both machines experience no error) < P(one machine experiences no error)`.

#### Proposed Solution

It would be nice to be able to tell one validator “you should validate for identity _x_ until slot _y_” and then tell a different instance “you should validate for identity _x_ as of slot _y_ + 1”. Making sure that both commands use the same value of _y_ would be the responsibility of the operator, instead of letting etcd coordinate this. It could lead to double votes if the operator makes a mistake, but that can already happen just by starting two validators with the same private keys.

To make it safer, instead of a command to say “validate until slot _y_”, a command to say “stop validating and output the last slot that you voted on” might be helpful. This could also wait for a gap in the leader schedule, like `solana-validator exit` does, so it doesn’t stop validating when it may have received some transactions already when it is going to be a leader soon.

There is still a class of mistakes that operators can make: they can ignore the output of the old validator, and enter an incorrect slot number to resume at. Taking this one step further, instead of just emitting the last slot that a validator voted on, the old instance might emit a signed message with the last slot that it voted on, and the new instance would only continue from there if the signature is valid. Now you can no longer manually enter a slot number, you have to copy the proof from the validator that exited.

Operators can still enter that proof into _two_ new instances though. Taking this one step further, an instance could generate a (disposable) unique session identifier for itself when the process starts. Then if you want to fail over from one instance to the other, you provide the session identifier of the instance to fail over to, and the old validator emits a signed message with the last slot it voted on, and the session identifier of its successor. This ensures that that message can only be used to resume validating on one particular instance.

As an additional safety margin, the new instance might watch the on-chain vote account, and only start voting once its identity has not voted for _n_ slots, to confirm that the old instance is really no longer voting.

@mvines, what do you think?

**Comment by mvines** [comment]
Have you seen this? https://github.com/mvines/validator-Identity-transition-demo

**Comment by ruuda** [comment]
I think I glanced over it before but I didn’t realize this was without etcd. This is exactly what we need, thanks :heart:
