### ISSUE TITLE
Do not use floating point values in sysvars

### ISSUE THREAD

**Issue by bji** [solana-labs/solana#23854]
#### Problem

The Rent sysvar includes a floating point value "exemption_threshold" which is a number of years.  This means that any program that wants to reference this value has to include floating point emulation support.  That seems like a very unnecessary introduction of such a dependency; specifying rent exemption threshold in number of seconds as a u64 would be equally functional and not require floating point.

#### Proposed Solution

Make a new sysvar RentV2 or something like that and don't use floating point in it.

**Comment by anoushk1234** [comment]
> any program that wants to reference this value has to include floating point emulation support

Which programs are currently struggling with this?

**Comment by migui3230** [comment]
ill take this on!

**Comment by migui3230** [comment]
#24082

**Comment by bji** [comment]
> > any program that wants to reference this value has to include floating point emulation support
> 
> Which programs are currently struggling with this?

C programs don't have floating point support in BPF without alot of additional hoop jumping.

**Comment by bji** [comment]
Practically speaking, Solana Labs will never take action on this, so closing.
