### ISSUE TITLE
Bug: solana version wrong

### ISSUE THREAD

**Issue by antonya86** [solana-labs/solana#23918]
#### Problem

I tested identity transition for zero-downtime upgrades of solana validator which became available on branch v1.9 (see https://github.com/mvines/validator-Identity-transition-demo) and I faced a bug with indication of solana version.

Reproduce procedure

1. Primary validator: it is on version `v1.9.12` synced and validating. 
2. Secondary validator: it is on version v1.9.13 synced and **not** validating.
3. Primary validator: switching to unstaked identity `solana-validator -l ledger set-identity keys/unstaked-identity.json`
4. Copy **tower** file from primary to secondary validator.
5. Secondary validator: switching to staked identity to start validation `solana-validator -l ledger set-identity --require-tower keys/staked_identity.json`

Right after **step 5** secondary validator start to advertise to cluster that it is on version v1.9.12 but it is not true. In fact v1.9.13 binary is running there. Looks like a bug. Maybe it is linked to tower file because it is the only thing migrated from primary validator with version v1.9.12.

Just for info, solana version is checked via "solana validators | grep {validator identity}" 

`solana-validator --version` works as expected:
> solana-validator 1.9.13 (src:3ac7e043; feat:1070292356)

#### Proposed Solution

For command `solana-validator set-identity` should be added handler to check if solana version changed and update it whenever needed for proper behavior.

**Comment by antonya86** [comment]
@mvines I was wondering if you could check it out.

**Comment by mvines** [comment]
This *may* be due the version only being pushed into gossip once at validator startup. Additionally pushing the version on runtime identity change may help.

Here's a way to bludgeon the version into gossip, but I don't recommend using this patch in general:
```diff
diff --git a/gossip/src/cluster_info.rs b/gossip/src/cluster_info.rs
index f6a1c3e2df..717afbf199 100644
--- a/gossip/src/cluster_info.rs
+++ b/gossip/src/cluster_info.rs
@@ -469,6 +469,7 @@ impl ClusterInfo {
         self.my_contact_info.write().unwrap().wallclock = now;
         let entries: Vec<_> = vec![
             CrdsData::ContactInfo(self.my_contact_info()),
+            CrdsData::Version(Version::new(self.id())),
             CrdsData::NodeInstance(self.instance.read().unwrap().with_wallclock(now)),
         ]
         .into_iter()

**Comment by antonya86** [comment]
Sure, I will test it out asap.
