### ISSUE TITLE
CLI: solana deploy command docs

### ISSUE THREAD

**Issue by sayantank** [solana-labs/solana#23953]
#### Problem
In the Solana CLI, `solana --help` doesn't list the `deploy` command, but the functionality seems to be present. Has it been deprecated?

The `--help` docs also don't specify the difference between `solana deploy` and `solana program deploy`.

#### Proposed Solution

If `solana deploy` has not been deprecated, then we should add the appropriate `clap::Arg`. Also, proposal to update the `--help` docs for `solana program deploy` to mention that it uses the **upgradeable loader**, which I believe `solana deploy` does not.

**Comment by t-nelson** [comment]
`solana deploy` is deprecated and deliberately hidden. `solana program deploy` fully covers its functionality
