### ISSUE TITLE
`getMultipleAccountsInfo` does not support `jsonParsed` encoding anymore

### ISSUE THREAD

**Issue by hritique** [solana-labs/solana#23961]
#### Problem
On 4 Jan,2022, a feature was added to the `getMultipleAccountsInfo` function to specify the encoding to `jsonParsed` via [this](https://github.com/solana-labs/solana/commit/33ad74fbcda33f2548d6021ec568257c3be56730) commit (v1.32.0).
But it was removed on 3 Mar, 2022 via [this](https://github.com/solana-labs/solana/commit/41ab690a6173b8ecef0b4a4e446d021477285f5a) commit (v1.36.0). This commit returns context along with the accounts info.

I'm not sure what was the reason to remove the encoding param to this function. It would be great if we can have that back.

**Comment by crypt0miester** [comment]
probably because jsonParsed takes time to analyze 1000s of data. it is less expensive for the node to do it than you do it on the frontend. 

simply decode it and then parse the data yourself.
