### ISSUE TITLE
solana bpf bug - incorrect function arguments

### ISSUE THREAD

**Issue by paul-schaaf** [solana-labs/solana#23978]
#### Problem

Im forwarding this issue (https://github.com/project-serum/anchor/issues/1693) which describes the problem.

we are able to reproduce it but dont believe this is an anchor issue.

We did some testing ourselves and believe this might be a bug in solana itself. The twelve `253` arrive correctly in the ix data (the instruction args begin at index 8. the first 8 bytes are anchor's instruction discriminant) and are also deserialized correctly by borsh. 

To test this, check out the repo mentioned in the issue above and adjust the `Cargo.toml` anchor-lang version to
```
anchor-lang = {git = "https://github.com/paul-schaaf/anchor", branch = "log_deserialized_ix_args"}
```
This is where I put the logs https://github.com/paul-schaaf/anchor/blob/b90f97453f39e5be362576e03d90db922c936420/lang/syn/src/codegen/program/handlers.rs#L733.

This fork logs the ix data and the deserialized args right before they are passed to the user defined handler function and then panics so the solana js client prints the logs.

Running `anchor expand` in the repo shows that the arguments are passed correctly to the user defined handler function.

comparisons are also failing so it's not the `msg!` macro displaying wrong numbers

**Comment by kklas** [comment]
FWIW, I've added a [ProgramTest test](https://github.com/kklas/debug-anchor/commit/f5e441b4dfa9227a3196751acb663639994064aa) and running it with `cargo test-bpf` reproduces the issue (solana v1.9.15):

```
Program log: 128, 0, 96, 160, 192, 224, 32, 64, 96, 128, 160, 160
```
