### ISSUE TITLE
Build from source fails.

### ISSUE THREAD

**Issue by kelvindoe22** [solana-labs/solana#23979]
#### Problem
ERROR HERE:  

error: failed to run custom build command for `openssl-sys v0.9.70`

Caused by:
  process didn't exit successfully: `C:\Users\PC\Downloads\solana-1.10.5\target\release\build\openssl-sys-8b6c3ddd4fafded4\build-script-main` (exit code: 101)
  --- stdout
  cargo:rustc-cfg=const_fn
  cargo:rerun-if-env-changed=X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR
  X86_64_PC_WINDOWS_MSVC_OPENSSL_NO_VENDOR unset
  cargo:rerun-if-env-changed=OPENSSL_NO_VENDOR
  OPENSSL_NO_VENDOR unset
  running "perl" "./Configure" "--prefix=C:\\Users\\PC\\Downloads\\solana-1.10.5\\target\\release\\build\\openssl-sys-4c1833d0e4d6ee14\\out\\openssl-build\\install" "no-dso" "no-shared" "no-ssl3" "no-tests" "no-comp" "no-zlib" "no-zlib-dynamic" "--libdir=lib" "no-legacy" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-capieng" "no-asm" "VC-WIN64A"

  --- stderr
  thread 'main' panicked at '

  Error configuring OpenSSL build:
      Command: "perl" "./Configure" "--prefix=C:\\Users\\PC\\Downloads\\solana-1.10.5\\target\\release\\build\\openssl-sys-4c1833d0e4d6ee14\\out\\openssl-build\\install" "no-dso" "no-shared" "no-ssl3" "no-tests" "no-comp" "no-zlib" "no-zlib-dynamic" "--libdir=lib" "no-legacy" "no-md2" "no-rc5" "no-weak-ssl-ciphers" "no-camellia" "no-idea" "no-seed" "no-capieng" "no-asm" "VC-WIN64A"
      Failed to execute: program not found

      ', C:\Users\PC\.cargo\registry\src\github.com-1ecc6299db9ec823\openssl-src-300.0.5+3.0.2\src\lib.rs:544:9
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by zhenpingfeng** [comment]
If you are building on Redhat/CentOS, you can try to install perl-IPC-Cmd package ```sudo dnf install perl-IPC-Cmd```, this solves this issue for me.

**Comment by t-nelson** [comment]
hi. we don't use github for support requests. please join us in #developer-support on https://solana.com/discord instead
