### ISSUE TITLE
refactor return code to include error reasons

### ISSUE THREAD

**Issue by taozhu-chicago** [solana-labs/solana#23971]
#### Problem

in `runtime/src/execute_cost_table.rs` function: 
```
    /// returns inflated program cost units, which is `ema + 2*stddev`, or None
    /// if program doesn't exist in table. In this case,
    /// `get_default_units()`, `get_average_units()` or `get_statistical_mode_units()`
    /// can be used to assign a value to new program.
    pub fn get_inflated_program_units(&self, key: &Pubkey) -> Option<u64> {
        let aggregated_variance_stats = self.table.get(key)?;
        Some(aggregated_variance_stats.get_ema() + 2 * aggregated_variance_stats.get_stddev())
    }
```
It'd be good to do `checked_*` math at last line of code. Then change the return type from `Option` to `Result<>` to discern if a `None` returned is due to the value not existing in the map or being non-normal

#### Proposed Solution
Make above suggested changed after #23948 is landed

**Comment by bijiezhu** [comment]
Hello, I will work on this. @taozhu-chicago

**Comment by taozhu-chicago** [comment]
Hey @bijiezhu thanks for taking on it. But I believe this will not longer be an issue if #23948 lands. Because that PR eliminates the possibility of `f64` becomes not normal.

**Comment by taozhu-chicago** [comment]
updated description

**Comment by BGZHU1** [comment]
@taozhu-chicago Ok, I will take a look at the updated description then :)

**Comment by BGZHU1** [comment]
I assume the updated description is the new problem to work on ? @taozhu-chicago

**Comment by taozhu-chicago** [comment]
> I assume the updated description is the new problem to work on ? @taozhu-chicago

Yep, two steps: 
1. replace `Some(aggregated_variance_stats.get_ema() + 2 * aggregated_variance_stats.get_stddev())` with something like ` aggregated_variance_stats.get_stddev().checked_mul(2).and_then(|v| v.checked_add(aggregated_variance_stats.get_ema())`, this checked_* math returns `Option`
2. distinguish `None` from step1 from "not in map", return `Result`

**Comment by lhendre** [comment]
@BGZHU1 have you had any luck?

**Comment by BGZHU1** [comment]
> @BGZHU1 have you had any luck?
Hi @lhendre , I almost forget this. I was waiting the dependent pull request [#23948 ](https://github.com/solana-labs/solana/pull/23948) to be landed. Thanks for @ me. I will do it this weekend.

**Comment by taozhu-chicago** [comment]
Now that banking_stage applies actual CUs to cost_tracker after execution, #23948 isn't as pressing, but better estimated CU can still help. I have re-opened it for review. Please feel free to comment on it

**Comment by taozhu-chicago** [comment]
no longer need cost estimated by #28281 , close this issue
