### ISSUE TITLE
support fetching a subset of account data in solana-client

### ISSUE THREAD

**Issue by 2501babe** [solana-labs/solana#23997]
#### Problem
as it stands `RpcClient` exposes three wrappers on the `getAccountInfo` rpc call:
* `get_account`, which accepts a pubkey and returns the full account struct
* `get_account_data`, which accepts a pubkey and returns the data as a u8 vec
* `get_account_with_commitment`, which accepts a pubkey and commitment level and returns the full account struct

the third of these constructs a `RpcAccountInfoConfig` with `encoding` and `data_slice` (offset and length) hardcoded

there should be a public method that lets the user supply/specify `data_slice` somehow. my usecase is i wanna fetch the first however many bytes of program data accounts to get the update authority and slot without being Rude to our friendly public rpc nodes

#### Proposed Solution
this is a simple addition and more a matter of style, the two possibles are:
* add a new function `get_account_with_config` which allows providing a `RpcAccountInfoConfig` struct, and make `get_account_with_commitment` a wrapper on that. this adds a new function to the public-facing api
* change `get_account_data` to accept a pubkey plus two usize for offset and length. this breaks the interface

im in favor of the latter if its allowed because honestly its kinda useless, all it does is access the `data` field on the returned struct, and because exposing `encoding` seems pointless

also if we are allowed to break the interface im not sure why the first funtion returns a type alias of `Result<Account>` whereas the other two return an alias of `Result<Option<Account>>`

i can pr this but wanted to ask before doing the documentation and testing effort. ty!

edit: actually upon further reflection, it might be preferable to return the full account object, rather than just the data vec. open to interface suggestions ofc

**Comment by mvines** [comment]
I like the motivation.  We don't want to break any interfaces until we bump the major crate version number.

>  im not sure why the first funtion returns a type alias of Result<Account> whereas the other two return an alias of Result<Option<Account>>

Just legacy gunk, `Result<Option<Account>>`would be preferred.

The `RpcAccountInfoConfig` approach sounds great to me

**Comment by t-nelson** [comment]
The latter could be implemented as the primary interface, with `get_account_data` as a wrapper requesting the full range
