### ISSUE TITLE
Rename function to better reflect its intention

### ISSUE THREAD

**Issue by taozhu-chicago** [solana-labs/solana#24015]
#### Problem

function `get_average_units()` defined [here](https://github.com/solana-labs/solana/blob/master/runtime/src/execute_cost_table.rs#L52) is to get average of all recorded programs. Renaming to `get_global_average_units` might better reflect its true intention. 

#### Proposed Solution
rename

**Comment by jaeheonji** [comment]
Hi! I'm a big fan of Solana. Could I try to contribute this?

**Comment by jstarry** [comment]
I don't think a function rename is a good first issue, it's too trivial

**Comment by OfficialSiddharthBisht** [comment]
https://github.com/solana-labs/solana/pull/24205 Made a PR of the same
