### ISSUE TITLE
Refactor thin_client::create_client

### ISSUE THREAD

**Issue by ryleung-solana** [solana-labs/solana#24011]
#### Problem
thin_client::create_client currently takes a tuple of addresses rather than the addresses as separate parameters. This is unnecessary and unintuitive.

#### Proposed Solution
Refactor thin_client::create_client to take the addresses separately

**Comment by BGZHU1** [comment]
Hello @ryleung-solana, I am new to solana, looks like a good beginner issue, I will take a look at :)

**Comment by ryleung-solana** [comment]
Hello @BGZHU1 I think that's a great idea! Thanks for the help!

**Comment by BGZHU1** [comment]
@ryleung-solana  Hello, can you check my commit?  Thank you :)
