### ISSUE TITLE
getSupply and getLargestAccounts block other requests

### ISSUE THREAD

**Issue by kvhees** [solana-labs/solana#24022]
When I make getSupply or getLargestAccounts calls to my RPC endpoint, the RPC server stops responding to future requests until the request has completed (10 minutes). I assume these are resource intensive calls, but it blocking other RPC requests is problematic, especially for public RPCs. 

Does anyone have any idea on how to resolve this?

**Comment by t-nelson** [comment]
hi. we don't use github for support requests. please join us in #rpc-servers on https://solana.com/discord instead
