### ISSUE TITLE
Failover fallback from secondary validator back to primary validator causes downtime

### ISSUE THREAD

**Issue by mllnd** [solana-labs/solana#24041]
#### Problem

We've been testing out `etcd` failover setup on Solana Testnet `v1.10.2` and are having a few issues when switching back to the primary validator.

First and foremost, we trigger the failover on the secondary node with:
```
solana-validator wait-for-restart-window --identity ./validator-keypair.json \
  && solana-validator set-identity ./validator-keypair.json
```

As a result, the primary validator process exits and secondary validator acquires the lock, everything works well 👍🏻. 

However, we've encountered an issue when re-starting the primary validator process. It seems that the lock is **immediately acquired** from `etcd`, without checking if the validator has actually caught up with the network. As a result, the secondary validator will shut down, while primary validator is still syncing, resulting in a downtime. 

On a side note, node dies with `SIGSEGV` after it loses its primary validator identity, which means there might be a bug in the etcd failover code path.

Would be happy if someone could confirm if this issue is valid, or are we missing something on our configuration side.

#### Proposed Solution

A potential fix would be to wait for validator to catch-up, before acquiring the lock from `etcd`.

**Comment by dezpriest** [comment]
I managed to make it work.

You need to have following setup for validator identity keys:
- unstaked validator identity keypair for Node 1 (unstaked-node1.json)
- unstaked validator identity keypair for Node 2 (unstaked-node2.json)
- staked validator identity keypair (vote account and authorized withdrawer are generated with it) (staked.json)

Both validators are started with their unstaked keys:
Node 1:
```
...
--identity unstaked-node1.json \
--vote-account vote-account-keypair.json \
--authorized-voter staked.json \
--no-check-vote-account \
...
```
Node 2:
```
...
--identity unstaked-node2.json \
--vote-account vote-account-keypair.json \
--authorized-voter staked.json \
--no-check-vote-account \
...
```

To trigger initial start (once validator on node up and catched up)
```
solana-validator set-identity staked.json
```

Manual failover can be done with a default command (on node you want to failover to):
```
solana-validator wait-for-restart-window --identity staked.json \
  && solana-validator set-identity staked.json
```

If node crashes, to fail-over it ti another (on running one)
```
solana-validator set-identity staked.json
```

**Comment by mvines** [comment]
What @dezpriest writes makes sense to me. Always start as an unstaked node and dynamically set the identity to primary once the node has caught up. 

Some additional text in the [failover documentation](https://github.com/solana-labs/solana/blob/75ba03b8d2352be4b63414251d0156a1f91911ac/docs/src/running-validator/validator-failover.md) discussing this scenario would be welcome!

**Comment by McSim85** [comment]
This is an excellent Issue that explains the failover method in short, and its top 5 search results.
I just wanted to mention that `--no-check-vote-account` has been deprecated long time ago https://github.com/solana-labs/solana/pull/28250

https://github.com/anza-xyz/agave/blob/b39364f087a643a9684dad2e03f089ba5cf6ac38/validator/src/cli.rs#L2122-L2130

**Comment by McSim85** [comment]
While the parameter is deprecated, the validator cannot start voting without that parameter.
If I use `agave-validator set-identity identity.json` without `--no-check-vote-account`, then I get these errors:
```
[2024-11-05T12:19:30.930064881Z INFO  solana_core::replay_stage] Vote account node_pubkey mismatch:  <set_pubkey> (expected: <slave_pubkey>).  Unable to vote
```
