### ISSUE TITLE
Deprecated anchor properties of program class

### ISSUE THREAD

**Issue by Vipulsin13** [solana-labs/solana#24044]
I am trying to send an instruction to my anchor program. But instruction, rpc and transaction -- all get a cross mark across them in VS code. I checked and found out that these properties of the Program class are deprecated. I want to know what the new method to send the transaction is? Also could somebody help me with this --- I have my solana wallet adapter in the header component.. But the UI button to send the transaction is in the main component. But on console logging wallet --- const wallet = useWallet(), I get an empty object in the main component. Can that be the reason behind not being able to send the transaction as sendTransaction is a method of useWallet(). The error message previously was about the property of program --- program.instruction.create. But now it says, cannot identify property sendTransaction of wallet.. The crossed property of program is still there though.. Also how can I send the wallet as a prop or anything from the header component to the main component --- both children of the app component if at all the empty object logging of wallet is the case?? Any help is much appreciated.. I really need to move on..
const handleCreate = () => {
        if (walletAddresses.length > 0){
            // console.log(wallet);
            wallet.sendTransaction(
                new anchor.web3.Transaction().add(
                    program.transaction.createraffle(new anchor.BN(wallet.publicKey),{
                        accounts: {
                            wallet:wallet.publicKey,
                            owner:wallet,
                            escrowAccount:escrowAccount.publicKey,
                            // escrowData,
                            systemProgram: anchor.web3.SystemProgram.programId,
                            rent: anchor.web3.SYSVAR_RENT_PUBKEY
                        },
                        signers: [wallet.publicKey]
                    })
                ), 
                connection,{signers: [wallet.publicKey]})
        }
    };
This is my handler..  
This is the error I am getting "Uncaught Error: Assertion failed" which seems to be quite vague. Searched for the error but not getting anything relevant.

**Comment by t-nelson** [comment]
hi. we don't use github for support. please join us in #developer-support on https://solana.com/discord
