### ISSUE TITLE
Solana command line via proxy

### ISSUE THREAD

**Issue by raymondshe** [solana-labs/solana#24075]
#### Problem
As I am in a restricted network, I need a proxy to connect to devnet.
```
% solana config get
Config File: /Users/raymond/.config/solana/cli/config.yml
RPC URL: https://api.devnet.solana.com 
WebSocket URL: wss://api.devnet.solana.com/ (computed)
Keypair Path: /Users/raymond/.config/solana/id.json 
Commitment: confirmed 
```

So as usual, I set proxy environment:
```
export ALL_PROXY=socks5://127.0.0.1:10010
```

As a result, curl works fine so that I can connect to devnet.
```
% curl https://api.devnet.solana.com 
<html>
    <head><title>Solana RPC</title></head>
    <body>
        <p>
            Solana RPC service running on par16.rpcpool.com in region EU on network devnet.
        </p>
        <p>
            For any questions or inquries about this service e-mail <a href="mailto:support@rpcpool.com">support@rpcpool.com</a> or join on <a href="https://t.me/joinchat/K0ONdq7fE4s0Mjdl">Telegram</a>.
        </p>
        <ul>
            <li><a href="/haproxy_status">What's the status of this server?</a></li>
            <li><a href="/haproxy_load">Is load ok on this server? </a></li>
        </ul>
    </body>
</html>
```
but solana remote command doesn't work.
```
% solana cluster-version      
Error: error sending request for url (https://api.devnet.solana.com/): operation timed out
% solana airdrop 1      
Requesting airdrop of 1 SOL
Error: RPC request error: cluster version query failed: error sending request for url (https://api.devnet.solana.com/): operation timed out

```

Here is more information about my binaries.
```
% solana --version
solana-cli 1.10.5 (src:5eb085fc; feat:3235626988)
% file `which solana`
/Users/raymond/tools/solana-release/bin/solana: Mach-O 64-bit executable x86_64
```
#### Proposed Solution
I am not sure if there is some alternatives for proxy setting. But propose we can support socks5 proxy.

**Comment by SypoolProtocol** [comment]
Is there any workaround on this or we had to set up a brige network mode between WSL and windows?

**Comment by raymondshe** [comment]
> Is there any workaround on this or we had to set up a brige network mode between WSL and windows?

I don't know, but probably we need looking into code to find out more.

**Comment by boerzi** [comment]
curl https://api.devnet.solana.com
`<html>
    <head><title>Solana RPC</title></head>
    <body>
        <p>
            Solana RPC service running on hk32.rpcpool.com in region AP on network devnet.
        </p>
        <p>
            For any questions or inquries about this service e-mail <a href="mailto:support@rpcpool.com">support@rpcpool.com</a> or join on <a href="https://t.me/joinchat/K0ONdq7fE4s0Mjdl">Telegram</a>.
        </p>
        <ul>
            <li><a href="/haproxy_status">What's the status of this server?</a></li>
            <li><a href="/haproxy_load">Is load ok on this server? </a></li>
        </ul>
    </body>
</html>`

you can 
`solana airdrop 2 --http://hk32.rpcpool.com/ devnet`

Here's how I solved it bro, you can try

**Comment by steveluscher** [comment]
That's generally not how you set HTTP proxies. Post a question using the link below and I'll answer it there!

**Comment by steveluscher** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Solana itself.

Questions like yours deserve a purpose-built Q&A forum. Unless you have evidence that this is a bug with Solana itself, please post your question to the Solana Stack Exchange using this link: https://solana.stackexchange.com/questions/ask
