### ISSUE TITLE
unable to download release for windows - docs point to testnet release which does not include windows build

### ISSUE THREAD

**Issue by lelandjobson** [solana-labs/solana#24092]
#### Problem

[Docs ](https://docs.solana.com/cli/install-solana-cli-tools#windows) has code for grabbing latest release of solana which as of now is testnet 1.10.5 but that release tag doesn't posses a windows release, so the command 
`curl https://release.solana.com/v1.10.5/solana-install-init-x86_64-pc-windows-msvc.exe --output C:\solana-install-tmp\solana-install-init.exe --create-dirs` doesn't seem to be doing anything.

#### Proposed Solution

Not sure if this is right but..point windows users to older distro (mainnet 1.9.14) or incl windows release into latest

**Comment by willhickey** [comment]
Thanks! I'm looking into the failing WIndows builds now
