### ISSUE TITLE
logsSubscribe with mentions doesn't seem to work

### ISSUE THREAD

**Issue by deian** [solana-labs/solana#24094]
I've played with the web3.js client and just connecting to the websocket manually. As far as I can tell `logsSubscribe` works fine with the `"all"` parameter, but not with a `mentions` filter as described in the docs:

```json
{"jsonrpc":"2.0","id":1,"method":"logsSubscribe","params":[{"mentions":["..."]}]}
```

**Comment by t-nelson** [comment]
hi we don't use github for support requests. join us in #developer-support on https://solana.com/discord instead
