### ISSUE TITLE
broadcast_stage ignores network errors

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#2411]
#### Problem
as of #2389, broadcast stage does not track transmit index, which means it does not retry failures that result from a network with no peers or UDP sendto() failures, which means we fall back to repair or we lose this leader's slot of data

#### Proposed Solution
re-institute tracking transmit index, re-serve those blobs from db_ledger

**Comment by rob-solana** [comment]
@pgarg66 is this still relevant?

**Comment by pgarg66** [comment]
@rob-solana yes, it is still relevant. The `standard_broadcast_run` does not track which shred failed in the transmission. So it relies on repairs or erasure recovery.

**Comment by rob-solana** [comment]
can we retire this issue with "rely on repairs and erasure"?

**Comment by pgarg66** [comment]
Yes. Makes sense.
