### ISSUE TITLE
Solana cli: `solana program deploy` should support proxy for `wss://`

### ISSUE THREAD

**Issue by LinXueyuanStdio** [solana-labs/solana#24118]
#### Problem

it's a little difficult to access wss://api.devnet.solana.com/ without socks5 proxy.

the error below occurs when I run `anchor deploy` who calls `solana program deploy`:

```shell
Error: Pubsub error: ConnectionError(Url(UnableToConnect("wss://api.devnet.solana.com/")))
There was a problem deploying: Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "" }.
```
But I can connect to wss://api.devnet.solana.com/ with proxy as follows:

```shell
websocat wss://api.devnet.solana.com/ --socks5 127.0.0.1:1080
```
where `websocat` is a tool to connect to devnet via web socket secure protocol `wss://xxx`.

#### Proposed Solution

there can be something like this:

```shell
solana program deploy --socks5 127.0.0.1:1080
```
or
```shell
solana program deploy --proxy socks5://127.0.0.1:1080
```

**Comment by billzhengC** [comment]
Same issue here. Have to work behind a proxy.

Current workaround is to use something like proxifier to route everything through a proxy server, but hope solana could natively support wss proxy

**Comment by andrewpedia** [comment]
> Any workaround for this?
> 
> Well, turn to `proxychains`,
> 
> > proxychains solana program deploy

how is the proxychains configured ?  what protocl is set? socks4 or socks5?

**Comment by linxux** [comment]
> > Any workaround for this?
> > Well, turn to `proxychains`,
> > > proxychains solana program deploy
> 
> how is the proxychains configured ? what protocl is set? socks4 or socks5?

Depends on your proxy configuration.
For my config,

> socks5 	127.0.0.1 1080

**Comment by amber0515** [comment]
Same issue here, Has anyone solved it?

**Comment by amber0515** [comment]
I solved this issue with tool proxychains: https://github.com/rofl0r/proxychains-ng
```
brew install proxychains-ng
cd /opt/homebrew/etc/
vim proxychains.conf
```
Modify the last line to the proxy address, then run
`proxychains4 solana program deploy .....`

**Comment by amber0515** [comment]
> I solved this issue with tool proxychains: https://github.com/rofl0r/proxychains-ng
> 
> ```
> brew install proxychains-ng
> cd /opt/homebrew/etc/
> vim proxychains.conf
> ```
> 
> Modify the last line to the proxy address, then run `proxychains4 solana program deploy .....`
@LinXueyuanStdio

**Comment by sunz7** [comment]
using proxychains, but I'm getting the following, any ideas?
`[proxychains] DLL init: proxychains-ng 4.16
[proxychains] Strict chain  ...  127.0.0.1:7890  ...  127.0.0.1:7890  ...  OK
Error: RPC request error: cluster version query failed: error sending request for url (https://api.devnet.solana.com/): error trying to connect: unexpected eof while tunneling
There was a problem deploying: Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "" }.`

**Comment by Ricy137** [comment]
> EDIT: solved it by downloading proxifier and add socket5 config to route all traffic thru vpn. I was using ClashX but it doesn't seem to support wss://
> 
> using proxychains, but I'm getting the following, any ideas? `[proxychains] DLL init: proxychains-ng 4.16 [proxychains] Strict chain ... 127.0.0.1:7890 ... 127.0.0.1:7890 ... OK Error: RPC request error: cluster version query failed: error sending request for url (https://api.devnet.solana.com/): error trying to connect: unexpected eof while tunneling There was a problem deploying: Output { status: ExitStatus(unix_wait_status(256)), stdout: "", stderr: "" }.`

@sunz7 , I met the same problem with clashX, and my vpn don't provide port in windows. I've been trapped here for a few says, may I ask you which vpn did you use? Thanks a lot <3.
