### ISSUE TITLE
Websocket closes unexpectedly on client side

### ISSUE THREAD

**Issue by qleguennec** [solana-labs/solana#24131]
#### Problem

I'm subscribing on multiple (5555) accounts on a websocket connection.

After a while (timing seems unrelevant but I need to gather more data to be sure), the websocket closes unexpectedly with status code 1006 and no reason.

Is this a known issue?

**Comment by t-nelson** [comment]
hi! we don't use github for support. please join us in #developer-support on https://solana.com/discord
