### ISSUE TITLE
1.10.6 missing x86-apple binaries which breaks installer

### ISSUE THREAD

**Issue by zdtcrypto** [solana-labs/solana#24153]
#### Problem

https://github.com/solana-labs/solana/releases/tag/v1.10.6 does not have x-86 apple binaries.

This breaks installer:

> sh -c "$(curl -sSfL https://release.solana.com/v1.10.6/install)"

> curl: (22) The requested URL returned error: 403 
solana-install-init: command failed: downloader https://release.solana.com/v1.10.6/solana-install-init-x86_64-apple-darwin /var/folders/5k/lzf8xs354vbdq4bxyb3qzpmc0000gn/T/tmp.M2nfSEQF/solana-install-ini

#### Proposed Solution

Build the x86 apple binaries and add them to the release.

**Comment by CriesofCarrots** [comment]
Thanks, those are in progress

**Comment by CriesofCarrots** [comment]
Mac binaries available now: https://github.com/solana-labs/solana/releases/tag/v1.10.6
