### ISSUE TITLE
Need a design of how we deal with multiple checkpoints in the system

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#2415]
#### Problem

The following checkpoints are possible:
    * TPU fork (leader fork)
    * Finalized trunk fork (validator will not rollback this point)
    * Frozen forks that are in the middle (forks that have been voted)
    * In progress TVU forks (forks that have not been voted)

The current code assumes on a single fork that will never rollback and does computation from that fork.  Forks that are latest in local wallclock time may not be latest in PoH height.  Also see #2162 

#### Proposed Solution
Factor out state from the bank. *Bank* maintains a checkpoints DAG.  It provides access to *BankState* for current TPU fork, finalized trunk, and latest tvu fork.  ReplayStage sets the latest tvu fork.  BankingStage sets the latest tpu fork.

Long running state like leader scheduler, or replicator state computation occurs when *finalized* fork height moves from < P to >= P, where P is the block height for that computation to refresh. 
- [ ] we might be able to get away with a "trunk" fork and a "live" fork
- [ ] Bank state factored out of the bank (https://github.com/aeyakovenko/solana/blob/forking/src/bank_state.rs)
- [ ] Bank maintains a checkpoint DAG (https://github.com/aeyakovenko/solana/blob/forking/src/checkpoints.rs)
- [ ] Bank provides access to current tpu fork (https://github.com/aeyakovenko/solana/blob/forking/src/bank.rs#L91)
- [ ] Tracking the finalized fork (TODO: should be done here https://github.com/aeyakovenko/solana/blob/forking/src/checkpoints.rs)
- [ ] leader scheduler is recomputed when the finalize fork is updated above the refresh height
- [ ] replication state is recomputed when the finalize fork is updated
- [ ] APIs to get the latest account state, or from any of the forks

tag: @rob-solana @mvines @garious

**Comment by pgarg66** [comment]
@aeyakovenko I think this is taken care of with the current bank and bank_forks. Is that correct?

**Comment by mvines** [comment]
I think this issue is now obsolete.  If not please reopen with new details
