### ISSUE TITLE
Implement subscription pooling in web3.js/connection

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana#24176]
#### Problem

If two callers subscribe, for instance, using `onAccountChange()` for the exact same address, we set up two subscriptions.

#### Proposed Solution

Implement subscription pooling.

Create a map of people who care about a given subscription:

```
const accountChangeListeners: Map<
  string,  // Pubkey
  AccountChangeCallback[]
> = new Map();
```

When that list of callbacks goes from zero to one, set up the subscription. When it falls from 1 to zero, unsubscribe.

When a subscription publishes a payload, broadcast it to all of the callbacks.

**Comment by LeFinc** [comment]
I second this - was just looking at this issue and handling it locally at the moment! Subscription pooling would be great,

**Comment by steveluscher** [comment]
Nice! Any feedback on our implementation @LeFinc? #24473.
