### ISSUE TITLE
broken stake account

### ISSUE THREAD

**Issue by vadbes46** [solana-labs/solana#24174]
#### Problem
Hello community,

Not sure whether it is an issue or a lack of information in docs about the following case:
I got corrupted stake account after withdrawal from stake to itself.
After this action there is no way to get out the balance whether using **solana withdraw-stake** nor **solana transfer**.
Comparing to the healthy stake account what I see:
![image](https://user-images.githubusercontent.com/31437063/162274582-9f1ac932-d458-4242-a8b7-e3b097695340.png)
The normal situation is:
![image](https://user-images.githubusercontent.com/31437063/162274822-4a8b5f2f-c7a1-4702-8429-cd4f82503af3.png)
It is missing withdrawal authority and stake authority.

It is still a stake account:
![image](https://user-images.githubusercontent.com/31437063/162275205-2b1e7b02-9a1f-475c-8e2e-63c6414c5b37.png)
But seems to be invalid or empty in blockchain.

Because trying to withdrawal funds I get this:
![image](https://user-images.githubusercontent.com/31437063/162276812-984cb46a-2c98-4ace-9bd0-367c8e916816.png)
![image](https://user-images.githubusercontent.com/31437063/162277403-6359aa4a-39b8-4a18-be89-e763a5f71133.png)

Tried different options with no success
Could you please point me how to withdrawal funds?

PS this is observed in testnet but seems to be valid for mainnet. This is the main concern that someboby could reach this. Version 1.10.6 was in test.

#### Steps to repeat
1. create stake account 
solana create-stake-account --fee-payer ident-key.json stake-key-new.json 1
2. withdrawal to itself
solana withdraw-stake stake-key-new.json stake-key-new.json 1
![image](https://user-images.githubusercontent.com/31437063/162279777-8ca2e95e-ab8a-4119-a519-2a728b7f23c5.png)
3. observe stake account is missing authorities and not able to do something with funds
![image](https://user-images.githubusercontent.com/31437063/162280005-2d619348-1b72-4534-ba39-ec289d1a54b1.png)

**Comment by diman-io** [comment]
If you have private key of stake account you can withdraw your funds.

**Comment by vadbes46** [comment]
I am using private key if you can see

**Comment by vadbes46** [comment]
> For signing of withdrawing

try it yourself please

**Comment by diman-io** [comment]
```
solana-keygen new -o tmp.json --silent --no-passphrase
solana transfer tmp.json 1
solana withdraw-stake stake.json tmp.json ALL -k stake.json --fee-payer tmp.json
```

**Comment by vadbes46** [comment]
> ```
> solana-keygen new -o tmp.json --silent --no-passphrase
> solana transfer tmp.json 1
> solana withdraw-stake stake.json tmp.json ALL -k stake.json --fee-payer tmp.json
> ```

so you didn't **broke** a stake account first?
Please reread

**Comment by diman-io** [comment]
Try this in your state:
`solana withdraw-stake stake-key-new.json ident-key.json ALL -k stake-key-new.json --fee-payer ident-key.json`

**Comment by vadbes46** [comment]
greate!!! Thank you))

**Comment by vadbes46** [comment]
seems that main thing was **-k stake-key-new.json** but not identity

**Comment by diman-io** [comment]
Yep, I wrote this in my first message :)
