### ISSUE TITLE
Withdraw all from vote account caused validator node stop working

### ISSUE THREAD

**Issue by WinterValidator** [solana-labs/solana#24183]
#### Problem
I am running withdraw script. There are some error on scrip that it can't detect correct current amount of vote account and then withdraw all and halt the validator node. I am looking for any other error on setting up validator node also.

solana --version
solana-cli 1.10.6 (src:8d5c7b7d; feat:3235626988)

Transaction details:
https://solanabeach.io/transaction/FaA3Gce9PUXfKGp2ewYD68ATTDYbEPpUD9GSmLEy2oyLWXwYnUC58nKhzqYR1Vbva29nETbefBotexAw5cZkwX7

Log for withdrawing from vote account at this time:
**__Wed Apr  6 07:04:01 +07 2022__**
Validator account: 4mJhW6Un4CHbTicj39Yuu9GQt5VAxKFzKGHFcSftVnVq
Balance:  SOL
Vote account: 2giMniq7L6WLUaZwDsfP2fmTbTnsJgVDyBDZJ5vnmtE3
Balance:  SOL
**Sending 1 from vote account to validator account.**
solana withdraw-from-vote-account -k /var/sol/keys/asia.mainnet/withdraw-keypair.json --commitment finalized 2giMniq7L6WLUaZwDsfP2fmTbTnsJgVDyBDZJ5vnmtE3 4mJhW6Un4CHbTicj39Yuu9GQt5VAxKFzKGHFcSftVnVq 1
Validator account final balance:
Vote account final balance: 0 SOL
Distributed account final balance:

#### Proposed Solution
Re-create vote account.

**Comment by CriesofCarrots** [comment]
We do have a feature coming to help protect you from yourself: https://github.com/solana-labs/solana/pull/22651
It's not active on any clusters yet, but coming to testnet soon.

Sounds like your script could use some guardrails, though. You definitely don't want to empty an active vote account.
