### ISSUE TITLE
RPC endpoints should not be closed and re-opened on leader rotation in src/fullnode.rc

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#2419]
* [x] RPC JSON API
* [ ] RPC websocket pubsub API

If we can avoid re-creating the bank, this issue becomes trivial.   Otherwise the rpc_pubsub.rs may be involved as it maintains a list of notification subscriptions that must be transferred over to the new bank.

**Comment by garious** [comment]
Can we move the subscriptions outside the bank? Perhaps into RpcClient? Also seems like RpcClient should wait until confirmation before sending any notifications.
