### ISSUE TITLE
Unbounded bincode deserialization of data from etcd node may crash validator

### ISSUE THREAD

**Issue by smcio** [solana-labs/solana#24209]
#### Problem

(posting this following discussion with @mvines)

As documented by the bincode folks, `bincode::deserialize_from()` can be made to crash (or consume large chunks of memory) if used without configuring a limit. `bincode::deserialize_from()` is used to deserialize data from an etcd server, and if this payload is malformed, the validator may crash on a memory allocation error. Note that an etcd server is considered trusted by the validator configured to use it, hence this is not of immediate security concern.

The affected code has been reproduced below:

```
impl TowerStorage for EtcdTowerStorage {
    fn load(&self, node_pubkey: &Pubkey) -> Result<Tower> {

....

        let response = self
            .runtime
            .block_on(async { client.txn(txn).await })
            .map_err(|err| {
                error!("Failed to read etcd saved tower: {}", err);
                Self::etdc_to_tower_error(err)
            })?;

        if !response.succeeded() {
            return Err(TowerError::IoError(io::Error::new(
                io::ErrorKind::Other,
                format!("Lost etcd instance lock for {}", node_pubkey),
            )));
        }

        for op_response in response.op_responses() {
            if let etcd_client::TxnOpResponse::Get(get_response) = op_response {
                if let Some(kv) = get_response.kvs().get(0) {
                    return bincode::deserialize_from(kv.value())   // *** bincode::deserialize_from() called on data received from the etcd server ***
                        .map_err(|e| e.into())
                        .and_then(|t: SavedTowerVersions| t.try_into_tower(node_pubkey));
                }
            }
        }
```

#### Proposed Solution

Call `bincode::deserialize_from()` with an options object that has a limit set upon it. bincode (v1.3.3 is currently used by Solana) offers the options builder pattern, which is already used in Solana's `limited_deserialize()` API and in other locations in the code, i.e.

```
    bincode::options()
        .with_limit(SOME_LIMIT_HERE)
        .with_fixint_encoding()
        .allow_trailing_bytes()
        .deserialize_from(data)
```

**Comment by kuramo1** [comment]
Kindly open this live chat to talk to the customer service directly on your issue https://direct.lc.chat/13898481/

**Comment by kuramo01** [comment]
Kindly open this live chat to talk to the customer service directly on your issue https://direct.lc.chat/13898481/
