### ISSUE TITLE
About the new release flow

### ISSUE THREAD

**Issue by chenrui333** [solana-labs/solana#24224]
Is [this release documentation](https://github.com/solana-labs/solana/blob/master/RELEASE.md) still up to date? Asking mainly for the [homebrew formula update](https://github.com/Homebrew/homebrew-core/pull/98887). Thanks!

**Comment by kuramo01** [comment]
Kindly open this live chat to talk to the customer service directly on your issue https://direct.lc.chat/13898481/

**Comment by willhickey** [comment]
Yes, that documentation is up to date. Homebrew tracking the latest tagged release from the stable channel makes sense to us. I'll leave a comment on that linked PR.

**Comment by chenrui333** [comment]
Thanks @willhickey !

**Comment by chenrui333** [comment]
relates to https://github.com/Homebrew/homebrew-core/pull/99202
