### ISSUE TITLE
validator is missing vote opportunities

### ISSUE THREAD

**Issue by brianlong** [solana-labs/solana#24231]
#### Problem
The validator is missing vote opportunities that could be used to help form consensus.

From @bji on Discord:

<img width="1039" alt="Screen Shot 2022-04-10 at 8 54 14 AM" src="https://user-images.githubusercontent.com/79186/162625475-17c2f2d1-0a68-48c3-a8b4-c08447b5ee80.png">

#### Proposed Solution
Please review the validator voting logic to make sure we are not missing any vote opportunities.

**Comment by brianlong** [comment]
Text from the above screenshot to make it easier to quote replies:

Yeah I'm just going to come out and say it.  The major performance improvement comes from not just dropping vote slots when there is a FailedThreshold situation.  The validator code base is soooo leaky with votes.  If FailedThreshold happens (because consensus is slow and your validator is N slots ahead of consensus and wants to wait for others to catch up before resuming voting), it just never votes on those slots.  It just moves on and re-evaluations at the next slot, and when the network has finally "caught up" and it's no longer ahead, it resumes voting.  But all those slots when it was in FailedThreshold, those slots just never get voted on.  Even though they could be.

To illustrate: validator votes on slots A through H, then when it gets to I it sees that A is still not confirmed by 66% of stake weight.  Its "what slot should I vote on next"logic starts saying "FailedThreshold" -- you can't vote, because you are now more than 8 slots aheadof 66%.  So it doesn't vote.  It waits for J.  Evaluates J.  Maybe gets the same result because A still isn't at 66% (nor is B at this point!).  But eventually the network catches up; say that when the validator is at slot P, finally slot J is at 66%.  Now the validator is like, "cool I can vote on P, it's not too far ahead".

But what happened to votes on slots I (where it started into a FailedThreshold state), J, K, L, M, N, and O?  It never votes on them!  But they are valid slots to vote on, they're on the fork, there was never any lock out, the validator was just being conservative and waiting not to vote too far ahead.  So all you gotta do is, go back and add those slots into your vote instead of just forever forgetting them and never voting on them.

Putting it another way: the validator code base turns a transient situation (too far ahead of consensus) into permanent vote loss.  And that's not necessary.

So I have code that on every vote, looks back through slot history to find slots that could have been voted on -- are legal vote slots -- but weren't, and includes those too.

That's 90% of the vote credits improvement.
At this point I just want the network to work.
If the above helps, great.
My changes are janky and not really something that I would propose as a PR because I implemented them as I was learning what was happening.

And the replay stage code is quite frankly somewhat janky to begin with.
The reason that me and Leapfrog are so far ahead the last few epochs is because the network has been working so poorly, establishing consensus so late, that we've all been hitting FailedThreshold so soo sooo often.  And the more that happens, the more we vote on those slots but the rest of you do not.
Now what's gonna happen is that someone is gonna take what I wrote above, make a patch, and sell it to testnet validators.
Yay

**Comment by michaelh-laine** [comment]
When the validator checks the fork depth in consensus.rs it stops voting when it goes beyond the specified threshold depth (8 slots by default): https://github.com/solana-labs/solana/blob/master/core/src/consensus.rs#L978

This returns into the replay_stage's compute_bank_stats function is called in the main replay_stage loop: https://github.com/solana-labs/solana/blob/master/core/src/replay_stage.rs#L565

The replay stage then loops through those stats and pulls the result of that function into the fork_stats which is passed into the select_vote_and_reset_forks function: https://github.com/solana-labs/solana/blob/master/core/src/replay_stage.rs#L2538

That function will push a failure if the vote threshold fails (https://github.com/solana-labs/solana/blob/master/core/src/replay_stage.rs#L2683). At this point the slot could also be pushed into a Vec or other data struct where it is stored until the vote threshold succeeds and all pending votes in that struct are then checked to see if they have been voted on and are on the same fork, and should then be all voted on together with the now-current slot for which the threshold check succeeded.

Just sharing the above to help anyone wishing to push a PR

**Comment by brianlong** [comment]
<img width="1000" alt="Screen Shot 2022-04-10 at 9 19 21 AM" src="https://user-images.githubusercontent.com/79186/162626609-fe853235-37df-47be-a23e-acba2d27e97c.png">

**Comment by kuramo01** [comment]
Kindly open this live chat to talk to the customer service directly on your issue https://direct.lc.chat/13898481/

**Comment by carllin** [comment]
> But eventually the network catches up; say that when the validator is at slot P, finally slot J is at 66%. Now the validator is like, "cool I can vote on P, it's not too far ahead". But what happened to votes on slots I (where it started into a FailedThreshold state), J, K, L, M, N, and O

Before you vote on slot `P`

```
A B C D E F G H I
```

You check that `A` has reached the threshold, then you vote on `P`, and maybe double lockouts on the tower (depending if its the first time each slot has seen the tower at this height before)

Now the next time you try to vote, the threshold check will be on `B`, which will need to pass the threshold check before you double the lockouts.

However, if you  backfill `J, K, L, M, N, and O` this is dangerous because suddenly this increases the lockout on everything less than `J` without incurring further threshold checks.

**Comment by brianlong** [comment]
@carllin Thanks for explaining that. I am more concerned about safety than vote credits. If there is room to **safely** increase vote credits, we should go for it. Otherwise, perhaps, more explanations about unsafe behavior will be helpful.

**Comment by Benhawkins18** [comment]
> However, if you backfill J, K, L, M, N, and O this is dangerous because suddenly this increases the lockout on everything less than J without incurring further threshold checks. 

Do you have any more insight on that concern. Going back and voting on this is great opportunity for vote credits so I'd like to better understand the risks and concerns.

**Comment by mvines** [comment]
Carl basically explained it well. You're increasing your lockout without checking the vote threshold, so you can get yourself locked out on a fork for much longer than expected -- assuming your modified validator software correctly respects lock outs before voting, which if it doesn't could subject it to future slashing.

Correctly/safely backfilling votes would be a significant architectural change to how consensus is current implemented, if even possible. So I think it's a solid assumption to say that any one or two line changes that "improve voting" will be incorrect/unsafe.

**Comment by brianlong** [comment]
Can we also assume that changing the constant values, without changing any code, to improve voting behavior is also incorrect/unsafe?

**Comment by Benhawkins18** [comment]
> Carl basically explained it well. You're increasing your lockout without checking the vote threshold, so you can get yourself locked out on a fork for much longer than expected -- assuming your modified validator software correctly respects lock outs before voting, which if it doesn't could subject it to future slashing.
> 
> Correctly/safely backfilling votes would be a significant architectural change to how consensus is currently implemented, if even possible. So I think it's a solid assumption to say that any one or two line changes that "improve voting" will be incorrect/unsafe.

I certainly think its possible to implement with out violating lock out but you are 100% correct in thinking that a simple 1 or two line change can't implement it safely.

**Comment by mvines** [comment]
Unsure about just tweaking constants for a small number of nodes. At network scale I’d be concerned because we don’t have too much analysis to justify the current values, only the track record to show that they seem to work well (which may or may not be the case for other values)

I was talking about adding EXTRA votes (“backfilling”) without performing the necessary threshold checks to respect the possibility of new lockouts due to those extra votes that the existing (and quite complex) consensus subsystem didn’t case. This is very nontrivial to do correctly

**Comment by bji** [comment]
> > But eventually the network catches up; say that when the validator is at slot P, finally slot J is at 66%. Now the validator is like, "cool I can vote on P, it's not too far ahead". But what happened to votes on slots I (where it started into a FailedThreshold state), J, K, L, M, N, and O
> 
> Before you vote on slot `P`
> 
> ```
> A B C D E F G H I
> ```
> 
> You check that `A` has reached the threshold, then you vote on `P`, and maybe double lockouts on the tower (depending if its the first time each slot has seen the tower at this height before)
> 
> Now the next time you try to vote, the threshold check will be on `B`, which will need to pass the threshold check before you double the lockouts.
> 
> However, if you backfill `J, K, L, M, N, and O` this is dangerous because suddenly this increases the lockout on everything less than `J` without incurring further threshold checks.

The technique would not be to vote on J through O unless they also pass threshold.

**Comment by bji** [comment]
If I didn't vote on slot A, B, C, or D because they failed threshold checks, then if suddenly I see votes land in slot E that put all 4 of those at 66% consensus, is there a danger in voting on A, B, C, or D?  They have already achieved 66% threshold, my validator hasn't voted on a newer slot yet, so what is the harm in voting on those in addition to E?

Honest question.

**Comment by mvines** [comment]
Voting for E alone only increases your commitment to that fork by 1 vote, whereas voting for A, B, C, D and E adds four additional lockouts for that fork. So your lockout on that fork is now 5 instead of 1, meaning there’s 2^5 more slots to wait for if you want to jump to another fork later. Imagine instead there’s 10 or more earlier blocks, now you’re locked out on a fork for hours or potentially days.

Essentially you’ve only observed 66% consensus on E but then additionally assumed 66% consensus on A, B, C, D as well, which is likely not reflective of the rest of the network.

**Comment by brianlong** [comment]
(not in reply to Michael's comment above) What if validators are using different settings for VOTE_THRESHOLD_DEPTH & threshold_size? Validator A may think those are valid votes with their settings, but they may not be valid with validator B's settings.

Is there a way to verify that the thresholds/settings used for a vote or switching proof from another validator match mine?

**Comment by brianlong** [comment]
Michael, In this screenshot, the middle column is the root distance, and the column on the right is the vote distance. It is normal to see root distance spikes like those shown in the 1st & 3rd rows. The "Abnormal" chart in the middle never goes above 2-3. The unnamed validator in the middle row (it is not Shinobi) is known to run aggressive vote mods.

<img width="618" alt="Screen Shot 2022-04-17 at 9 34 46 PM" src="https://user-images.githubusercontent.com/79186/163750810-94d794cd-600c-43a2-8c4d-df13ad6504de.png">

My original thought was that the middle validator was quickly jumping from one fork to the next highest fork. Based on your insight above, I think the opposite is happening -- the validator is actually stuck voting for an older fork and the newer forks are getting dropped in favor of the older fork. So, the validator seems to always be voting on the 'correct' fork. 

HOWEVER, if 34% of the active stake was stuck for days/hours and couldn't switch, we could lose consensus (when they should switch, but can't).

Does that all make sense? Is that a possible explanation for what I see on the charts?

Any attempt to mess with code or constants in `consensus.rs` feels super dangerous.

**Comment by bji** [comment]
> Voting for E alone only increases your commitment to that fork by 1 vote, whereas voting for A, B, C, D and E adds four additional lockouts for that fork. So your lockout on that fork is now 5 instead of 1, meaning there’s 2^5 more slots to wait for if you want to jump to another fork later. Imagine instead there’s 10 or more earlier blocks, now you’re locked out on a fork for hours or potentially days.
> 
> Essentially you’ve only observed 66% consensus on E but then additionally assumed 66% consensus on A, B, C, D as well, which is likely not reflective of the rest of the network.

Yes but the validator is quite happy to commit 5 votes to a fork almost all the time, so why is this situation any different?

**Comment by brianlong** [comment]
On Discord, @bji asked me to provide some extra commentary on why I think the backfill voting described above explains the pattern that I see on the charts. We know that the extra backfill votes extend the lockout period for the validator. If that lockout period is sufficiently long, the "Abnormal" validator won't be able to switch forks. Therefore it will remain on a fork with a lower root (compared to new forks).

In the charts, the "Normal" validators can switch forks more quickly. So the spikes we see are those validators forking away from the branch with the lower root (line goes up), and then switching back (line goes down).

Just because the Abnormal validator stayed on the fork with the lower root doesn't automatically make it better. When taken to a possible extreme, the cluster could lose consensus if validators with 34% of the active stake can't switch (in a timely manner) when there is a valid reason to do so.

Unfortunately, we don't have visibility into the mods that the Abnormal validator is using. However, the pattern of voting & root distance suggests that they are backfilling votes to earn credits at the expense of very long lockout periods.

QQ: Is the max lockout 2^31?

**Comment by brianlong** [comment]
> Also, if a validator is not switching roots quickly, it will lose out on votes won't it? Because not switching implies lockout which then implies missed votes. So it would work against "earn maximum credits" strategies.
They are always backfilling to catch the missing credits.

> Is it possible that the root distance chart always being low means that the validator is actually switching roots _more quickly_, resulting in the difference in root between the new fork and the old fork being so low as to not cause a spike on the graph?
This was the gist of my question/concern about "surfing". However, the long lockout suggests that they can't. Also, switching comes at a cost, correct?

**Comment by bji** [comment]
> > Also, if a validator is not switching roots quickly, it will lose out on votes won't it? Because not switching implies lockout which then implies missed votes. So it would work against "earn maximum credits" strategies.
> 
> They are always backfilling to catch the missing credits.

Yes but you can't backfill votes that were locked out.  If you are experiencing lockout, those are just missed votes completely, you can't vote on those slots.  The backfill only happens in situations which are *not* lockout, which are not the situations you describe as "should be spikes".

**Unless** the validator were violating lockout rules and switching rapidly to the new fork without waiting for lockout to pass.  But that's just conjecture, it would require seeing the votes on both forks to prove that the validator was violating lockouts.

**Comment by michaelh-laine** [comment]
> Michael, In this screenshot, the middle column is the root distance, and the column on the right is the vote distance. It is normal to see root distance spikes like those shown in the 1st & 3rd rows. The "Abnormal" chart in the middle never goes above 2-3. The unnamed validator in the middle row (it is not Shinobi) is known to run aggressive vote mods.
I've mentioned this a few times on Discord but you haven't really addressed my explanation for this: There has to always be a some amount of validators (66%) on the right fork, for whom he root distance does not change, so I think your conclusion based on those three charts alone is premature. 

All validators can't have a spiking root distance score, by the very definition of how consensus works. _someone_ is always on the right fork

**Comment by nikhayes** [comment]
> > Voting for E alone only increases your commitment to that fork by 1 vote, whereas voting for A, B, C, D and E adds four additional lockouts for that fork. So your lockout on that fork is now 5 instead of 1, meaning there’s 2^5 more slots to wait for if you want to jump to another fork later. Imagine instead there’s 10 or more earlier blocks, now you’re locked out on a fork for hours or potentially days.
> > Essentially you’ve only observed 66% consensus on E but then additionally assumed 66% consensus on A, B, C, D as well, which is likely not reflective of the rest of the network.
> 
> Yes but the validator is quite happy to commit 5 votes to a fork almost all the time, so why is this situation any different?
> 
> I mean, the validator would have voted on A, B, C, D, and E if the first time it saw each slot, that slot was less than 8 slots ahead of consensus. But the happenstance of the timing of votes landing causes the situation to be that consensus was "stuck" on some prior slot before jumping ahead, why is it better in that situation for the validator to "commit less" to the fork?

Hmm it seems like a lot of these issues and extreme advantages at times mainly come down to validators missing votes in slots that they should have landed them in (they probably weren't processed because the costtracker triggered block limit early, preventing votes from being included). When the costtracker issues are fully fixed I wonder how many votes will still be missing their mark.

Also, is backfilling somehow different from the "refresh_last_vote" logic mentioned here? Seems like both are an attempt to vote on older slots that were missed?
https://github.com/solana-labs/solana/issues/24230

**Comment by bji** [comment]
> > > Voting for E alone only increases your commitment to that fork by 1 vote, whereas voting for A, B, C, D and E adds four additional lockouts for that fork. So your lockout on that fork is now 5 instead of 1, meaning there’s 2^5 more slots to wait for if you want to jump to another fork later. Imagine instead there’s 10 or more earlier blocks, now you’re locked out on a fork for hours or potentially days.
> > > Essentially you’ve only observed 66% consensus on E but then additionally assumed 66% consensus on A, B, C, D as well, which is likely not reflective of the rest of the network.
> > 
> > 
> > Yes but the validator is quite happy to commit 5 votes to a fork almost all the time, so why is this situation any different?
> > I mean, the validator would have voted on A, B, C, D, and E if the first time it saw each slot, that slot was less than 8 slots ahead of consensus. But the happenstance of the timing of votes landing causes the situation to be that consensus was "stuck" on some prior slot before jumping ahead, why is it better in that situation for the validator to "commit less" to the fork?
> 
> Hmm it seems like a lot of these issues and extreme advantages at times mainly come down to validators missing votes on slots that they should have landed them in, in normal network situations -- they probably weren't landing properly because the costtracker bugs triggered the block compute limit early, preventing votes from being included -- which is why the validators who were backfilling had a huge advantage during chronic congestion times. During these times maybe more backfilling would have improved confirmation times and potentially saved consensus if not enough votes were landing in blocks? When the costtracker issues are fully fixed I wonder how many votes will still be missing their mark.
> 
> Also, is backfilling somehow different from the "refresh_last_vote" logic mentioned here? Seems like both are an attempt to vote on older slots that were missed? #24230

refresh_last_vote is about sending the same vote that was sent previously, but hasn't been seen as having landed yet on chain.  Nothing is changed about the vote except that the "timestamp" in the vote is updated to be more accurate for the time that the "refreshed" vote is sent.  This is all about concluding that a vote that was already cast got lost (UDP packet loss) and so sending it again.

This is different than "backfilling", which is about detecting when the validator has skipped over voting for slots that at the time that initially could have been voted on, were found to not be within 8 slots of consensus, and thus "failed threshold", but then later when consensus progresses, are found to be now within 8 slots of consensus, and can be voted on.

Backfilling augments votes with slots that weren't yet voted on, whereas refresh just repeats votes that were already cast but don't seem to have landed.

For what it's worth, the replay stage code is broken and doesn't actually invoke the refresh code to re-send votes anyway.  That could be fixed too, but it's independent of this issue.

**Comment by nikhayes** [comment]
Ahh I see. Hmm so maybe what was happening then is that slots were slow to confirm during congestion --> main fork got pretty far ahead of itself --> sparse voting. Seems like there's a risk of consensus stalling without backfilling and/or the retries.

**Comment by brianlong** [comment]
> I've mentioned this a few times on Discord but you haven't really addressed my explanation for this: There has to always be a some amount of validators (66%) on the right fork, for whom he root distance does not change, so I think your conclusion based on those three charts alone is premature.
> 
> All validators can't have a spiking root distance score, by the very definition of how consensus works. _someone_ is always on the right fork

Those spikes are short-lived and never reach 66%. In my validator logs, I see many cases where the validator does not receive blocks from the prior leader and it creates a new fork. When the blocks finally arrive, the prior fork is now the heaviest and I switch back. This is extremely common and totally explains the forking activity shown on the charts. You can see some examples on this log deep dive I did a while ago https://www.validators.app/log-deep-dives/slot-72677728?locale=en&network=mainnet and you can confirm the same in your own logs. Look for lines like this: `Waiting to switch vote to 72677730, resetting to slot None on same fork for now`. They indicate that you are locked out and waiting to switch.

**Comment by brianlong** [comment]
> > Ahh I see. Hmm so maybe what was happening then is that slots were slow to confirm during congestion --> main fork got pretty far ahead of itself --> sparse voting on slots. Seems like there's a risk of consensus stalling without backfilling and/or the retries.
> 
> I agree with that. The fact that validators are not refreshing (i.e. re-sending) votes, and yet are also not backfilling votes, I think would lead to the strong possibility of just not landing votes at all during times of lots of packet loss (i.e. spam events). I think, but do not know, that this could be a contributor to the high forking and low vote success rate during stress times.

I was a little surprised to learn that the vote retry logic is not the same as regular TXs. It makes sense that a validator should attempt to retry valid votes until they land or expire. Related to the title of this issue, this is where the "validator is missing vote opportunities." I hope someone on the Labs team or the community can work on a PR for this. Retrying votes doesn't affect the consensus logic (consensus.rs) in any way and I don't see any safety issues.

**Comment by Benhawkins18** [comment]
> I was a little surprised to learn that the vote retry logic is not the same as regular TXs. It makes sense that a validator should attempt to retry valid votes until they land or expire. Related to the title of this issue, this is where the "validator is missing vote opportunities." I hope someone on the Labs team or the community can work on a PR for this. Retrying votes doesn't affect the consensus logic (consensus.rs) in any way and I don't see any safety issues.

One could write some middleware that tracks tx sent saves them and check constantly to see if they have landed and have some threshold where it resends the transaction. This could be done fully independent of the validator process.
