### ISSUE TITLE
Self::refresh_last_vote in Replay_stage.rs never gets called

### ISSUE THREAD

**Issue by Trenbolone682** [solana-labs/solana#24230]
#### Problem

Ive noticed that if I add a else error!() to the:
if let Some(my_latest_landed_vote) = progress.my_latest_landed_vote(heaviest_bank_on_same_voted_fork.slot())

I always get the error from else, which means the function never gets called.

This can be found in Replay_stage.rs at l.590

#### Proposed Solution

I have no solution since im not an experienced rust dev but I think someone should look into this.

**Comment by kuramo01** [comment]
Kindly open this live chat to talk to the customer service directly on your issue https://direct.lc.chat/13898481/

**Comment by bji** [comment]
I can confirm this.  This is a big problem as it defeats the vote refresh logic, which may reduce the rate at which votes are landed because validators don't ever attempt to send them again if they haven't been received.

**Comment by bji** [comment]
If you undo the Deref trait implementation for ProgressMap, and add in pass-through functions for all of the HashMap functions used throughout the code on ProgressMap, you can then change the name of insert to insertyy and let the compiler find all of the places where insert is called.  And there aren't any beyond initialization functions.  So clearly insert() is never called which is why there is never any progress map updates of the "my latest voted slot" which is what breaks vote refresh.

**Comment by bji** [comment]
The easy solution is to use tower.last_voted_slot_in_bank() instead of progress_map.  I will be submitting a PR for this soon.

**Comment by t-nelson** [comment]
cc/ @carllin

**Comment by Trenbolone682** [comment]
Just out of curiosity, is there a bug bounty on this ?

**Comment by carllin** [comment]
`last_voted_slot_in_bank` is updated here: https://github.com/solana-labs/solana/blob/ee6bb0d5d38218efdc9a1ee0442088b044e49def/core/src/replay_stage.rs#L2442

> The easy solution is to use tower.last_voted_slot_in_bank() instead of progress_map. I will be submitting a PR for this soon.

This would work, but requires an extra deserialization of the vote state on every iteration of replay stage

> Ive noticed that if I add a else error!() to the:
if let Some(my_latest_landed_vote) = progress.my_latest_landed_vote(heaviest_bank_on_same_voted_fork.slot())

Hmm are you running this on a voting validator? If so, the latest vote should always be found when analyzing the bank state and a vote account that matches yours is found: https://github.com/solana-labs/solana/blob/master/core/src/consensus.rs#L296-L297

**Comment by Trenbolone682** [comment]
Yes I was running it on a voting validator, which was also very strange to me both testnet and with new identity on Mainnet. Later I analysed the same situation on my main Mainnet validator, which is now closed. There the last vote has been found, so im not sure what has caused the bug. Both machines were identical but with one validator I assume the vote account was never found in the bank state.

**Comment by bji** [comment]
I have enabled vote refresh and one unfortunate consequence is that votes that are issued to do refresh pay a transaction fee because they use a different timestamp than in the "original" vote and thus have a different signature.  I am finding that that on mainnet right now this adds a noticeable number of extra vote transactions.  It will be hard on smaller validators to pay even more vote fees.

**Comment by michaelh-laine** [comment]
> So clearly insert() is never called which is why there is never any progress map updates of the "my latest voted slot" which is what breaks vote refresh.
> 
> `last_voted_slot_in_bank` is updated here:
> 
> https://github.com/solana-labs/solana/blob/ee6bb0d5d38218efdc9a1ee0442088b044e49def/core/src/replay_stage.rs#L2442
> 
> not using the insert function
> > The easy solution is to use tower.last_voted_slot_in_bank() instead of progress_map. I will be submitting a PR for this soon.
> 
> This would work, but requires an extra deserialization of the vote state on every iteration of replay stage
> 
> > Ive noticed that if I add a else error!() to the:
> > if let Some(my_latest_landed_vote) = progress.my_latest_landed_vote(heaviest_bank_on_same_voted_fork.slot())
> 
> Hmm are you running this on a voting validator? If so, the latest vote should always be found when analyzing the bank state and a vote account that matches yours is found:
> 
> https://github.com/solana-labs/solana/blob/c31db81ac48771d50c3bdecc4d30ac5785a47a44/core/src/consensus.rs#L296-L297

just a follow up on this, was there a PR submitted?

**Comment by nikhayes** [comment]
> I have enabled vote refresh and one unfortunate consequence is that votes that are issued to do refresh pay a transaction fee because they use a different timestamp than in the "original" vote and thus have a different signature. I am finding that that on mainnet right now this adds a noticeable number of extra vote transactions. It will be hard on smaller validators to pay even more vote fees.

Maybe the refresh logic could be made so that the wait is longer before trying to recast the vote? Could be made more easily adjustable I guess given the voting credit timeliness changes.

**Comment by diman-io** [comment]
it doesn't work on zero staked validators only

https://github.com/solana-labs/solana/blob/4ee318b2b29a08563f6069040ab012c9cf744540/core/src/consensus.rs#LL285-L287

so you can patch like below
```
if voted_stake == 0 && key != *vote_account_pubkey {
```

**Comment by carllin** [comment]
not convinced this needs fixing, non staked validators shouldn't need a refresh. Refresh is only needed when there's not enough stake on a fork to allow for switching, non staked validators will not contribute to progress towards this. 

Only staked validators need to refresh to ensure there is sufficient stake on a fork, at which point the non staked validators will naturally start voting again

**Comment by diman-io** [comment]
This was used during the testing of voting mods on non-staked validators, as I understand
I think the issue starter just didn't figure out why they are getting different results from the function
