### ISSUE TITLE
Consistently failing deploy: Invalid Blockhash

### ISSUE THREAD

**Issue by jkbpvsc** [solana-labs/solana#24241]
#### Problem
When deploying to devnet through the solana cli, deploys are consistently failing with `Error: Custom: Invalid blockhash`

Using `solana-cli 1.10.7 (src:8bce2dd4; feat:1122441720)`

On `macOS 12.1 21C52 arm64 (M1)`

**Comment by jkbpvsc** [comment]
Deploy works on `v1.8.16`

**Comment by gelopfalconEdify** [comment]
I'm getting the same error using
```
solana-cli 1.9.5 (src:39a4cc95; feat:3125401026)
```

**Comment by willhickey** [comment]
I just successfully deployed to devnet using `solana-cli 1.9.14 (src:edb38c4b; feat:1070292356)` and `solana-cli 1.10.7 (src:8bce2dd4; feat:1122441720)`. Are you still seeing this error and if so can you post steps to reproduce?

**Comment by jkbpvsc** [comment]
Failed with `solana-cli 1.9.14 (src:caa55bb0; feat:1070292356)` and `solana-cli 1.10.7 (src:8bce2dd4; feat:1122441720)`
`Error: Custom: Invalid blockhash` in both cases.

Steps to reproduce: 
1. Build program
2. `solana program deploy <program location> -u d`

After running the command it just hangs without any output and errors out after 2m
```
time solana program deploy <path> -u d
===============================================================================
Recover the intermediate account's ephemeral keypair file with
`solana-keygen recover` and the following 12-word seed phrase:
===============================================================================
...
===============================================================================
To resume a deploy, pass the recovered keypair as the
[BUFFER_SIGNER] to `solana program deploy` or `solana write-buffer'.
Or to recover the account's lamports, pass it as the
[BUFFER_ACCOUNT_ADDRESS] argument to `solana program close`.
===============================================================================
Error: Custom: Invalid blockhash
solana program deploy  -u d  0.29s user 0.19s system 0% cpu 1:59.87 total
```

**Comment by jkbpvsc** [comment]
Also not sure how relevant.
Intermittently getting this error
`Error: HTTP status server error (503 Service Unavailable) for url (https://api.devnet.solana.com/)`

**Comment by acamill** [comment]
Same issue here

**Comment by y2kappa** [comment]
same here, can only deploy with 1.8.*

**Comment by rinswend** [comment]
Same issue with `solana-cli 1.10.21 (src:7aeebb57; feat:2072158692` on Ubuntu 18.04.1 x86_64

**Comment by rinswend** [comment]
This is a dup of #23427

**Comment by jkbpvsc** [comment]
Not seeing this anymore, closing
