### ISSUE TITLE
remove tick_height from Entry

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#2424]
Regarding `tick_height` in `Entry` (https://github.com/solana-labs/solana/blob/master/src/entry.rs#L45), what prevents a malicious leader from putting whatever `tick_height` it wants there?

**Comment by rob-solana** [comment]
putting tick_height in Entry was a band-aid for figuring out how to chain Entries back to a previous slot.  it should be removed, but there is some code using it now, as an optimization
