### ISSUE TITLE
Quic clients could use the server's TLS certificate

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#24258]
#### Problem

QUIC server presents a TLS cert signed by the node's key (unless that has been removed) but the client doesn't 

#### Proposed Solution

Should we add the same cert as a client cert now for TPU traffic between staked nodes?

**Comment by VinceTorrel** [comment]
Good suggestion. Just beware of rogue certificate authorities. If this gets implemented, then I think there should be a hardcoded list of acceptable authorities which requires a Github edit to alter.
