### ISSUE TITLE
Inconsistent PoH count between leaders and validators

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#2425]
#### Problem

PohService is configured to use "low power" mode:

https://github.com/solana-labs/solana/blob/master/src/fullnode.rs#L298

That means the PoH count per tick will vary per entry and the validator cannot filter blobs sent by the incorrect leader unless it uses `Entry::tick_height` (which can't be verified for the same reason).

#### Proposed Solution

Only use "low power" mode in tests. Consider abandoning low-power mode entirely.

**Comment by mvines** [comment]
Fixed already
