### ISSUE TITLE
Error when building from source Docker container no AVX2

### ISSUE THREAD

**Issue by dmitryr117** [solana-labs/solana#24268]
I have no AVX2 support on my CPU and so have to build from source. I am trying to build a docker container so it can be reused. 
However when I try to build Solana from source using the following Dockerfile:

```
FROM ubuntu:20.04

ENV TZ="America/Edmonton"

ENV PATH="/root/.cargo/bin:${PATH}"

ADD solana /solana

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
		echo $TZ > /etc/timezone && \
		apt-get update && apt-get upgrade -y && \
    apt-get install -y curl build-essential libssl-dev pkg-config libudev-dev && \
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y && \
    rustc --version

WORKDIR /solana

RUN apt-get install libssl-dev libudev-dev pkg-config zlib1g-dev llvm clang make -y

RUN ./scripts/cargo-install-all.sh .

CMD ["tail", "-f", "/dev/null"]
```
I get this error:
```
...
   Compiling dlopen v0.1.8
   Compiling zeroize v1.3.0
error: failed to run custom build command for `prost-build v0.10.0`

Caused by:
  process didn't exit successfully: `/solana/target/release/build/prost-build-59aa3170065af3a5/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=/root/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.10.0/third-party/protobuf/cmake
  CMAKE_TOOLCHAIN_FILE_x86_64-unknown-linux-gnu = None
  CMAKE_TOOLCHAIN_FILE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_TOOLCHAIN_FILE = None
  CMAKE_TOOLCHAIN_FILE = None
  CMAKE_GENERATOR_x86_64-unknown-linux-gnu = None
  CMAKE_GENERATOR_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_GENERATOR = None
  CMAKE_GENERATOR = None
  CMAKE_PREFIX_PATH_x86_64-unknown-linux-gnu = None
  CMAKE_PREFIX_PATH_x86_64_unknown_linux_gnu = None
  HOST_CMAKE_PREFIX_PATH = None
  CMAKE_PREFIX_PATH = None
  CMAKE_x86_64-unknown-linux-gnu = None
  CMAKE_x86_64_unknown_linux_gnu = None
  HOST_CMAKE = None
  CMAKE = None
  running: "cmake" "/root/.cargo/registry/src/github.com-1ecc6299db9ec823/prost-build-0.10.0/third-party/protobuf/cmake" "-DCMAKE_INSTALL_PREFIX=/solana/target/release/build/prost-build-3a2e4204f1fb9b36/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Debug"

  --- stderr
  thread 'main' panicked at '
  failed to execute command: No such file or directory (os error 2)
  is `cmake` not installed?

  build script failed, must exit now', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/cmake-0.1.46/src/lib.rs:974:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
error: build failed
```
Anyone has any idea why this happens? My CPU is an AMD FX-8350. It supports AVX, but not AVX2.

**Comment by mvines** [comment]
From the error message:
> is `cmake` not installed?

so is it?

**Comment by dmitryr117** [comment]
Thank you.

That was part of the problem. I confused `cmake` with `make`, and thought I already had it installed. It still did not want to compile on an AMD FX-8350 and was giving some long error. So I tried compiling it on another desktop with a Xeon E3-1230 V2. It has no AVX2 as well. It compiled on that one, and when I tested the docker image on my FX-8350 machine - the validator was running fine. I pushed the docker image to Docker Hub under `dmitryr117/solana-noavx2:1.10.8` for anybody who may have the same problem as I did, and does not have another system to try to compile it. 

To use the image - run it, and then log into it using `docker exec -ti` pattern, and then run whatever Solana commands you need inside the container. I also recommend to use docker-compose to configure external ports and other settings for convenience. Rust 1.60.0 is also installed.

**Comment by steveluscher** [comment]
Unless there's more discussion needed here, I'm going to close this. If you think that your discovery would be useful to more people in the community, I'd love it if you would post your question _and_ the answer to the Solana Stack Exchange using this link: https://solana.stackexchange.com/questions/ask
