### ISSUE TITLE
db_ledger iterator returns non-contiguous Entries

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#2426]
#### Problem
on validator restart, future, non-contiguous entries may be present in the ledger, which we attempt to play into the bank on startup

#### Proposed Solution
db_ledger needs to look at meta() during enumeration and stop when the entry_height reaches consumed

**Comment by rob-solana** [comment]
@sakridge here's the most likely source of what you're seeing

**Comment by sakridge** [comment]
@rob-solana sweet, thanks for looking into that!
