### ISSUE TITLE
CUDA enabled error running validator

### ISSUE THREAD

**Issue by SlimJUC** [solana-labs/solana#24276]
#### Problem

CUDA is installed as per nvidia official docs

but when running validator with --cuda flag we get this

[2022-04-12T13:13:23.386752078Z INFO  solana_perf::perf_libs] perf-libs found at "/root/.local/share/solana/install/releases/1.10.8/solana-release/bin/perf-libs"
[2022-04-12T13:13:23.388005175Z WARN  solana_perf::perf_libs] CUDA installation not found
[2022-04-12T13:13:23.388015775Z INFO  solana_perf::perf_libs] Loading "libcuda-crypt.so"
[2022-04-12T13:13:23.388232374Z ERROR solana_perf::perf_libs] Unable to load "libcuda-crypt.so": Could not open library: libcuda-crypt.so: cannot open shared object file: No such file or directory

#### Proposed Solution

validator should work with nvidia official installation of CUDA

**Comment by Lazydayz137** [comment]
Same issue....ever find a resolution?

**Comment by Lazydayz137** [comment]
https://github.com/solana-labs/solana-perf-libs

Trying to compile, add, and recompile solana.  Updated to Cuda 11 24 days ago, which I am running.

Fingers crossed.

**Comment by Lazydayz137** [comment]
It is a mess.  Cuda 11 update my foot.  I mean, it does run with Cuda 11 it seems, they just don't make the correct directories basically.  Pain in the ass.  If you need help, hit me up.

**Comment by ncarrara** [comment]
Having the same issue

**Comment by Unded** [comment]
Faced with the same problem on **Ubuntu 20.04**, **CUDA 10.1** 
Steps:
1. Prepared files according to the README: https://github.com/solana-labs/solana-perf-libs
2. Built solana from the source code

**Solution**:
The https://github.com/solana-labs/solana/blob/master/perf/src/perf_libs.rs#L114 requires `CUDA_HOME`
After adding the `CUDA_HOME` I got another error: 
```
Unable to load "~/solana/bin/perf-libs/cuda/libcuda-crypt.so": Could not open library: ~/solana/bin/perf-libs/cuda/libcuda-crypt.so: cannot open shared object file: No such file or directory
```
Only after coping files from `~/solana/bin/perf-libs/cuda-10.1` to `~/solana/bin/perf-libs/cuda` I was able to run the validator

**Comment by Navoos** [comment]
In linux, if you have installed solana from the docs you will have to set the ``CUDA_HOME`` variable to
/home/$USER/.local/share/solana/install/active_release/bin/perf-libs/cuda-10.2
"cuda-10.2" will be subject to change according to the version you have installed.
