### ISSUE TITLE
simulateTransaction overriding recentBlockhash is destructive

### ISSUE THREAD

**Issue by dvcrn** [solana-labs/solana#24279]
#### Problem

After hours of debugging weird issues with transactions changing in between adding signatures we finally figured out that  `simulateTransaction` is overriding `recentBlockhash` whenever it's used, which caused our Transaction object to get a new recentBlockhash because the same reference was used: 

https://github.com/solana-labs/solana/blob/master/web3.js/src/connection.ts#L3891=

blockhash is needed to simulate properly, but overriding of an existing blockhash was not expected behavior

#### Proposed Solution

Simulating transactions should be non-destructive. Some ideas how to solve this:

- Throw error when a `recentBlockhash` is not set (eg. do nothing)
- Set only if not set yet
- Set only when populating from Message (creating a new instance altogether)
- Make a copy of the Transaction instance

**Comment by jstarry** [comment]
Closed by https://github.com/solana-labs/solana/pull/24280
