### ISSUE TITLE
No windows build from 1.19.15

### ISSUE THREAD

**Issue by mbenoukaiss** [solana-labs/solana#24275]
#### Problem
Starting from Mainnet 1.9.15 (and testnet 1.10) there are on windows build on the release (and therefore the docs don't work since the release exe returns access denied https://docs.solana.com/cli/install-solana-cli-tools#windows)

**Comment by steviez** [comment]
@mbenoukaiss - To elaborate, this was a known issue on `v1.10` but not `v1.9` branch; @willhickey figured out the issue with `v1.9.15` and looks to have uploaded the Windows assets at https://github.com/solana-labs/solana/releases/tag/v1.9.15. And as CriesofCarrots mentioned above, upcoming `v1.10` release should be fixed as well
