### ISSUE TITLE
[RpcClient] GenesysGo RPC authentication problem

### ISSUE THREAD

**Issue by anselsol** [solana-labs/solana#24318]
#### Problem
Since the big update of GenesysGo and to limit botting, they have added an `Authorization` header that takes a token and authenticates requests (the token is too large to be added to the query params of the URL)

#### Proposed SolutionProblem
Add a place in the `RpcClient` config to push a list of headers (https://github.com/solana-labs/solana/blob/master/client/src/rpc_client.rs#L49)

**Comment by brianlong** [comment]
That header should be consumed by a load balancer in front of the RPC client.

**Comment by anselsol** [comment]
Hey @brianlong! What do you mean? I should have a load balancer that just handles the header (knowing that the token is already generated on my API)?

**Comment by brianlong** [comment]
Hi @anselsol, apologies -- I see that you are specifically talking about the Rust RPC client. My comments were about the RPC servers. The RPC nodes should have a load balaner or something like NGINx in front to handle token auth, rate limits, etc. It looks like my comment was out of context. Cheers

**Comment by anselsol** [comment]
Hey @brianlong no worries! Sorry if I wasn't specific enough!

My comment is exactly about the Rust RPC client (when you want to connect to RPC nodes from your rust program). Right now we can only specify a URL but there is no way to add an `Authorization` header to the mix. That's what I'd like to see if we can fix :)

**Comment by levicook** [comment]
FYI  https://github.com/solana-labs/solana/issues/17631

**Comment by jstarry** [comment]
Seems like #17631 covers this, we can discuss over there
