### ISSUE TITLE
Feature Gate: drop redundant turbine propagation path

### ISSUE THREAD

**Issue by behzadnouri** [solana-labs/solana#24352]
### Description

Most nodes in the cluster receive the same shred from two different
nodes: parent, and the first node of their neighborhood:
https://github.com/solana-labs/solana/blob/a8c695ba5/core/src/cluster_nodes.rs#L178-L197

https://github.com/solana-labs/solana/pull/24351 simplifies the broadcast tree by dropping the redundant
propagation path and removing the 2x fanout at root node.

All nodes in the cluster should adopt the new propagation tree at the same time;
otherwise because different nodes construct the propagation tree differently, 
shreds don't get propagated fully across the cluster.
Therefore the change should be feature gated.

### Feature ID

4Di3y24QFLt5QEUPZtbnjyfQKfm6ZMTfa6Dw1psfoMKU

### Activation Method

Single Core Contributor

### Testnet Activation Epoch

326

### Devnet Activation Epoch

324

**Comment by blocknxt** [comment]
Any thoughts on when this will go live on MB ?.

**Comment by behzadnouri** [comment]
@blocknxt doing some performance optimizations throughout the pipeline; after that will activate this feature.
Curious why you would be interested in this feature activation?

**Comment by brennanwatt** [comment]
Reminder to please update [Turbine documentation](https://docs.solana.com/cluster/turbine-block-propagation) when this feature is enabled on MNB
