### ISSUE TITLE
Slow locks in Rust standard library

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#2436]
#### Problem

Rust's default thread synchronization libraries are a bit slow and we're starting to workaround that slowness in ways that don't offer a clear path forward. For example, in the Bank, rather than wrapping each account with a RwLock, we maintain a separate `HashSet<Pubkey>` of all "locked" accounts on the side.

#### Proposed Solution

First try the parking_lot library as a drop-in replacement. If it goes well, consider replacing that `HashSet<Pubkey>` with `RwLock<Account>`.

https://docs.rs/parking_lot/0.7.1/parking_lot/

**Comment by sambley** [comment]
@garious, @pgarg66, tried moving over RwLock and Mutex to parking lot but the results are worse for our case. The average TPS went down by 77% after moving over to use RwLock/Mutex from parking_lot.

From the raw benchmark numbers, write locks are much slower and read lock / mutex operations are faster. 

- Running with 10 writer threads and 10 reader threads
parking_lot::RwLock  - [write]    109.170 kHz [read]     55.892 kHz
std::sync::RwLock    - [write]      7.401 kHz [read]   4430.701 kHz

       name         |    average     |     median     |    std.dev.   
parking_lot::Mutex   |     27.596 kHz |     27.513 kHz |      0.368 kHz
std::sync::Mutex     |     53.418 kHz |     53.395 kHz |      0.351 kHz

Most likely the write lock threads in our use case are not getting scheduled fast enough which probably is contributing significantly to the processing of transactions.

**Comment by garious** [comment]
Thanks for the analysis @sambley. If no other thoughts on how to replace that `HashSet<Pubkey>` with something more elegant, can you unassign this issue? Plenty of other fish to fry.
