### ISSUE TITLE
Closed programs owned by BPFLoaderUpgradeab1e shows as executable

### ISSUE THREAD

**Issue by ratulb** [solana-labs/solana#24364]
#### Problem
When we retrieve a program account owned by BPFLoaderUpgradeab1e11111111111111111111111 post closure - account executable flag is still true.  

Account pointed by 'ProgramData Address' - gets wiped out.

But the executable flag still remains true.

#### Proposed Solution
While closing an upgradable program - account's executable flag should be set to false.

**Comment by jstarry** [comment]
> While closing an upgradable program - account's executable flag should be set to false.

The runtime doesn't allow executable accounts to ever change actually. Can you describe what problems this is causing for you?

**Comment by ratulb** [comment]
Let's say - I have following program in testnet:

solana account **2RqzMz6fdBQgNZ6WFygqF4hwwegx7SgzWUmV3DzNBkCN**
Public Key: 2RqzMz6fdBQgNZ6WFygqF4hwwegx7SgzWUmV3DzNBkCN
Balance: 0.00114144 SOL
Owner: BPFLoaderUpgradeab1e11111111111111111111111
**Executable: true**
Rent Epoch: 310
Length: 36 (0x24) bytes
0000:   02 00 00 00  e4 73 35 6a  7a 76 ea 17  96 d9 7e 1a   .....s5jzv....~.
0010:   5a f3 78 48  28 e7 18 4e  e4 6c 7c a9  5d c8 b9 f5   Z.xH(..N.l|.]...
0020:   29 0a f5 61          

I fire following command:

me@ws$ **solana program show 2RqzMz6fdBQgNZ6WFygqF4hwwegx7SgzWUmV3DzNBkCN**
Program Id: 2RqzMz6fdBQgNZ6WFygqF4hwwegx7SgzWUmV3DzNBkCN
Owner: BPFLoaderUpgradeab1e11111111111111111111111
ProgramData Address: **GNmr5eXCwueMQqUbi5GqRko5ksoK6gkEmkbSsHjQ3Zkc**
Authority: FEnkBg8oxhE3jEAQBuHqvuSJTJZCdDkmBTsyuRDM9358
Last Deployed In Slot: 128549427
Data Length: 111760 (0x1b490) bytes
Balance: 0.77905368 SOL

I fire another command fetch ProgramData address account - I get to see that there is data.

me@ws$ **solana account GNmr5eXCwueMQqUbi5GqRko5ksoK6gkEmkbSsHjQ3Zkc | head -5**
Public Key: GNmr5eXCwueMQqUbi5GqRko5ksoK6gkEmkbSsHjQ3Zkc
Balance: 0.77905368 SOL
Owner: BPFLoaderUpgradeab1e11111111111111111111111
Executable: false

Now, I close the the program - which will wipe out the content from ProgramData address shown above:

me@ws$ **solana program close 2RqzMz6fdBQgNZ6WFygqF4hwwegx7SgzWUmV3DzNBkCN**
Closed Program Id 2RqzMz6fdBQgNZ6WFygqF4hwwegx7SgzWUmV3DzNBkCN, 0.77905368 SOL reclaimed

If I again query the ProgramData address - it will be gone - as can be shown below:

**me@ws$ solana account GNmr5eXCwueMQqUbi5GqRko5ksoK6gkEmkbSsHjQ3Zkc | head -5
Error: AccountNotFound: pubkey=GNmr5eXCwueMQqUbi5GqRko5ksoK6gkEmkbSsHjQ3Zkc**

Now I again query the program account - this will still show the program as executable whereas - actually - binary content the program is pointing to is gone:

me@ws$ **solana account 2RqzMz6fdBQgNZ6WFygqF4hwwegx7SgzWUmV3DzNBkCN**
Public Key: 2RqzMz6fdBQgNZ6WFygqF4hwwegx7SgzWUmV3DzNBkCN
Balance: 0.00114144 SOL
Owner: BPFLoaderUpgradeab1e11111111111111111111111
**Executable: true**
Rent Epoch: 310
Length: 36 (0x24) bytes
0000:   02 00 00 00  e4 73 35 6a  7a 76 ea 17  96 d9 7e 1a   .....s5jzv....~.
0010:   5a f3 78 48  28 e7 18 4e  e4 6c 7c a9  5d c8 b9 f5   Z.xH(..N.l|.]...
0020:   29 0a f5 61     

Hope, this clarifies the issue that I am describing.

**Comment by jstarry** [comment]
I understand that this is happening but not sure how it's an issue for you. It's expected that even after a program is closed, it's still marked as executable.

Using `solana account` will show you the raw account info. When using the `solana program show` command, the output is more descriptive as shown below:
```
$ solana program show 2RqzMz6fdBQgNZ6WFygqF4hwwegx7SgzWUmV3DzNBkCN -ut
Error: Program 2RqzMz6fdBQgNZ6WFygqF4hwwegx7SgzWUmV3DzNBkCN has been closed
```

**Comment by ratulb** [comment]
So,
What should be the approach to determine if a program is closed from a client programmatically ? I don't find an API in the RpcClient equivalent to `solana program show` - and RpcCleint -> get_account(..) -> Account-> executable would be returning true always!

**Comment by jstarry** [comment]
Upgradeable programs store their executable data in the program data account which is always stored at a derived address. You can calculate the derived address like so:
```rust
let (programdata_address, ..) = Pubkey::find_program_address(&[your_program_id.as_ref()], &solana_program::bpf_loader_upgradeable::id());
```

**Comment by ratulb** [comment]
Thanks. This helps. 
I was getting it done in a round about way:

```
Ok(program_account) => {
                let owner = program_account.owner.to_string();
                match owner.as_ref() {
                    //Upgradable bpf loader returns true even if the program may have
                    //been closed. Hence we are checking program account data to make
                    //sure program really exists
                    BPF_LOADER_UPGRADABLE => {
                        let state: std::result::Result<UpgradeableLoaderState, _> =
                            program_account.state();
                        match state {
                            Ok(UpgradeableLoaderState::Program {
                                programdata_address,
                            }) => {
                                //We are good if we can retrieve the account - otherwise
                                //close call would have emptied the account
                                let program_binary_acc =
                                    self.client.get_account(&programdata_address);
                                match program_binary_acc {
                                    Ok(_) => {
                                        println!("Binary address {}", programdata_address);
                                        Ok(())

````

**Comment by ratulb** [comment]
Please go ahead and close this issue.

**Comment by jstarry** [comment]
Cool, your approach works as well but it's a bit faster to directly derive the address. By the way I do agree that disabling "executable" would be more intuitive but it's a risky change so I'd prefer not doing it for the time being.
