### ISSUE TITLE
Lack of consistency checks for stakes cache

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#24376]
#### Problem
After the feature gate for https://github.com/solana-labs/solana/issues/24278 is activated, validators will calculate stake rewards using vote and stake account state cached in the `StakesCache`. However, there are currently no consistency checks that ensure that the stakes cache accurately reflects the state of all active vote and stake accounts in accounts db.

One potential pitfall is that the stakes cache implementation assumes that stake and vote accounts cannot have their owner changed during transaction processing. This is safe now but the stake and vote programs could introduce a future change that resets the owner of a closed account and break that assumption.

Context: https://github.com/solana-labs/solana/pull/24200#discussion_r849935444

#### Proposed Solution

TBD

**Comment by jeffwashington** [comment]
@behzadnouri , @t-nelson , @HaoranYi can one of you please help clarify? Is this an issue for activation? An issue that still needs work done on it?

**Comment by t-nelson** [comment]
this was addressed in https://github.com/solana-labs/solana/pull/24200

**Comment by jeffwashington** [comment]
Sorry to be pedantic.
@behzadnouri @t-nelson @HaoranYi just being clear.
This issue has `do-not-close` from @behzadnouri last month.
@t-nelson says it is addressed in #24200, which looks like it went in over a year ago.
@behzadnouri can you please confirm? Thank you.

**Comment by behzadnouri** [comment]
The source of inconsistency was patched in https://github.com/solana-labs/solana/pull/26479 and the sanity checks here
https://github.com/solana-labs/solana/blob/936d2cf3c/runtime/src/stakes.rs#L224-L263
will cause panic at start-up if stakes-cache is inconsistent with accounts-db:

https://github.com/solana-labs/solana/pull/24200 only added these metrics:
https://github.com/solana-labs/solana/blob/936d2cf3c/runtime/src/bank.rs#L1092-L1094
to track if there are inconsistencies between cache and accounts-db before feature activation; but the feature activation will bypass those metrics.
