### ISSUE TITLE
BroadcastStage doesn't broadcast per-slot blob indexes

### ISSUE THREAD

**Issue by carllin** [solana-labs/solana#2440]
#### Problem
BroadcastStage broadcasts a monotonically increasing blob index, regardless of slot. This means that blobs are not slot-specific and will be misinterpreted by the db_ledger.

#### Proposed Solution
Restart blob index for each slot to support new per-slot blob index format in db_ledger

**Comment by garious** [comment]
@carllin, fixed in #2277?

**Comment by carllin** [comment]
Yup!
