### ISSUE TITLE
ERROR occurred while installing solana cli

### ISSUE THREAD

**Issue by ayushch80** [solana-labs/solana#24415]
#### Problem
Getting an error while executing `sh -c "$(curl -sSfl https://release.solana.com/stable/install)"` in termux

`downloading stable installer
curl: (22) The requested URL returned error: 403
solana-install-init: command failed: downloader https://release.solana.com/stable/solana-install-init-armv7l-unknown-linux-gnu /data/data/com.termux/files/usr/tmp/tmp.sDVnwgl2oA/solana-install-init`

Waiting for HELP !!

**Comment by jstarry** [comment]
We only build releases for the architectures listed in the artifacts here: https://github.com/solana-labs/solana/releases/tag/v1.9.16 For `armv7l-unknown-linux-gnu` you'll have to build from source
