### ISSUE TITLE
Efficient strategy for repair on forks

### ISSUE THREAD

**Issue by carllin** [solana-labs/solana#2442]
#### Problem
When there was only one slot, db_window would then have a global concept of the "consumed" index or latest blob_index in the consecutive block of entries. It would then try to perform repair starting from the tip of that block of consecutive entries.

With the change here: https://github.com/solana-labs/solana/pull/2277, which introduces multiple slots and potential forks, the repair scheme based on a single slot and a global "consumed" index no longer works. There is currently no strategy for figuring out and prioritizing which slots to repair across slots and forks.

**Comment by garious** [comment]
@carllin, fixed in #2277?

**Comment by carllin** [comment]
Not quite, the current repair strategy is still pretty silly and more of a bandaid than a holistic solution

**Comment by garious** [comment]
@carllin, any updates here?

**Comment by carllin** [comment]
@garious, small improvement was made here https://github.com/solana-labs/solana/pull/3581, but the current thinking is that erasure will be used to keep lagging validators up to date. It is to be seen if that will be sufficient or we will also need to make further improvements to repair.
