### ISSUE TITLE
ReplayStage needs to query db_ledger for updates

### ISSUE THREAD

**Issue by carllin** [solana-labs/solana#2444]
#### Problem
ReplayStage does not query db_ledger for updates, which makes it hard to ask for fork-specific information.

#### Proposed Solution

Currently ReplayStage gets updates from RetransmitStage. Instead, based on the newly proposed design in: https://github.com/solana-labs/solana/pull/2253, ReplayStage needs to wait for signals from db_ledger and directly query db_ledger for updates.

1) Block on signal from db_ledger for updates
2) Query db_ledger for updates
3) Break up pipeline so that ReplayStage no longer get updates from RetransmitStage (will need to rework the shutdown logic here as well)
4) Delete logic from db_ledger that returns entries in the write API's as ReplayStage will directly query for updates. Delete the logic in db_window.rs that sends consecutive entries from write_shared_blobs() and passes them on to ReplayStage.
5) On startup, bank is still built from the old ledger, and doesn't process db_ledger. We need to process db_ledger, record the latest slot and blob index within that slot, and expose these two pieces of information to ReplayStage so it knows where to begin looking in DbLedger for updates

**Comment by garious** [comment]
I'm confused by the architectural change here.  The ReplayStage has always been this very dumb thing that blindly processes whatever entries are sent to it. Its purpose is to accept or reject entries.

The RetransmitStage has been the service that keeps ReplayStage dumb. It takes the role of ensuring that ReplayStage doesn't process entries until it has them in the right order (such that PoH verify succeeds).  To have ReplayStage take the role is surprising. Does it suggest RetransmitStage will no longer exist?  Or perhaps its role is reduced to managing repair requests?
