### ISSUE TITLE
Reduce logging from bank_process_transaction_counters

### ISSUE THREAD

**Issue by HaoranYi** [solana-labs/solana#24456]
#### Problem

https://github.com/solana-labs/solana/issues/24319
For rpc node, the metric agent is unable to catching up with the log at info level.

bank_process_transaction_counters are one of the heaviest loggers. 

https://github.com/solana-labs/solana/pull/24385/files/d50da6bf0165d27e701a826595b6eeff91b0daaf#diff-ed47b4a0198313377e091bb3957bbbc63d937805426d1b2b6de39d0a50d32a0c

#### Proposed Solution

- aggregate those counters to report per slot

**Comment by carllin** [comment]
Changing this to only be reported at the end of the slot by the leader producing that block
