### ISSUE TITLE
Partial Sign Transaction

### ISSUE THREAD

**Issue by beargrilo** [solana-labs/solana#24462]
#### Problem

After upgrading solana/web3.js to 1.39.1 the following code stop working, giving me the error: `Transaction mutated after being populated from Message`

This is the code:

```
...

transaction.partialSign(bankKeypair)

const serializedTransaction = transaction.serialize({
    requireAllSignatures: false
})

encodedTransaction = serializedTransaction.toString('base64')

...

<send encodedTransaction over axios call>

....

const recoveredTransaction = Transaction.from(Buffer.from(encodedTransaction, 'base64'))

const signedTransaction = await window.solana.signTransaction(recoveredTransaction)
const result = await connection.sendRawTransaction(signedTransaction.serialize());
```

The code is working on 1.37.1

Cheers

**Comment by beargrilo** [comment]
Also, not sure if it's relevant for the case:

I'm unable to signAndSendTransaction (Phantom method) a transaction that's recovered like stated above (even in 1.37.1).
But the transaction shows up OK with all the instructions correct and fees calculated in Phantom Wallet.

Ty.

**Comment by obaidaalam** [comment]
it not fixed i updated my package.json to 1.39.1 same problem

**Comment by jstarry** [comment]
> it not fixed i updated my package.json to 1.39.1 same problem

Looks like the web3 release pipeline is broken, the fix will be released in 1.39.2 but it hasn't been published yet. I'll post an update when we fix this, thanks for your patience! For now, you can downgrade to 1.38.0

**Comment by aaronovz1** [comment]
We just got plagued by this problem - any word on a fix? Cheers

**Comment by leofisG** [comment]
@aaronovz1 Downgraded to `1.38.0` seems to be working for us.

**Comment by jstarry** [comment]
Fixed on [1.40.1](https://www.npmjs.com/package/@solana/web3.js/v/1.40.1) now

**Comment by yazeed** [comment]
Still getting this on 1.41.2, not sure if it's properly fixed.

**Comment by jstarry** [comment]
> Still getting this on 1.41.2, not sure if it's been properly fixed.

It's still possible to get the `Transaction mutated after being populated from Message` error if you sign for a key which isn't known by the transaction yet. I assume you're running into that issue?

**Comment by yazeed** [comment]
To be honest, I'm not sure what you mean, can you please elaborate on what I could be doing wrong?

**Comment by jstarry** [comment]
> To be honest, I'm not sure what you mean, can you please elaborate on what I could be doing wrong?

Let's say you craft a transaction which requires a single singer A and then sign it with two private keys A and B. The signature for A will get inserted into the transaction just fine but the signature for B would cause the transaction to be mutated because it needs to record that there actually 2 signers for the transaction. This mutation would trigger the error above.

**Comment by apeTim** [comment]
> > To be honest, I'm not sure what you mean, can you please elaborate on what I could be doing wrong?
> 
> Let's say you craft a transaction which requires a single singer A and then sign it with two private keys A and B. The signature for A will get inserted into the transaction just fine but the signature for B would cause the transaction to be mutated because it needs to record that there actually 2 signers for the transaction. This mutation would trigger the error above.

I'm facing this issue atm and I found an interesting thing. Doing like this, it requests a new recent blockhash automatically and often it does not match with the recent blockhash that was used when creating a transaction, thus the transaction is not the same and it gives this error. However the initial recent blockhash is saved in _json and _message field. How can I fix this?
![image](https://user-images.githubusercontent.com/88082374/166746725-2dcc51a5-0dc6-484d-99a6-31f54342d4de.png)

**Comment by gv1122** [comment]
anyone end up finding a fix to this?

**Comment by jstarry** [comment]
It should be fixed, if you are seeing the issue still, please create a new issue describing how you encountered it.
