### ISSUE TITLE
Feature Gate: Add compute cost for executable accounts used in CPIs

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#24512]
### Description

Charge executable accounts a compute budget cost to account for handling their data.

### Feature ID

7GUcYgq4tVtaqNCKT3dho9r4665Qp5TxCZ27Qgjx3829

### Activation Method

Single Core Contributor

### Testnet Activation Epoch

331

### Devnet Activation Epoch

330

### Mainnet-Beta Activation Epoch

323

**Comment by jstarry** [comment]
Feature gate code cleaned up in https://github.com/solana-labs/solana/pull/26500
