### ISSUE TITLE
`onLogs()` doesn’t work properly.

### ISSUE THREAD

**Issue by muhitrhn** [solana-labs/solana#24536]
#### Problem
The `onLogs()` sometimes logs the data and most of the times doesn't log anything at all. What am I doing wrong? 
Is it necessary to unSubscribe from an event?
What happens when the code is force stoped?

I’m making a account tracking discord bot. Is there any problem if I subscribe to onLogs for all the wallets at once or with a time gap in-between each sub? 

Here is the code (Same code is used to track multiple wallets, separate child process for each wallet) -
```
const { clusterApiUrl, Connection, PublicKey } = require('@solana/web3.js');

(async () => {
    const connection = new Connection(clusterApiUrl('mainnet-beta'), {
        commitment: 'finalized',
        wsEndpoint: 'wss://api.mainnet-beta.solana.com'
    });

    connection.onLogs(new PublicKey('M2mx93ekt1fmXSVkTrUL9xVFHkmME8HTUi5Cyc5aF7K'), async (log) => {
        console.log(log.signature);
    }, 'finalized');
})();```

**Comment by steveluscher** [comment]
I made a fix to the validator that was related to log subscriptions 6 days after you filed this issue. Can you take a read through https://github.com/solana-labs/solana/pull/24215 and let me know if that sounds like what's been happening to you?

**Comment by steveluscher** [comment]
Feel free to reopen this if it turns out _not_ to have been fixed by the fix noted above!

**Comment by nicKondratiev** [comment]
Mate did you solve the problem? I'm facing the same problem where I'm receiving data in the inconsistent manner. Thank you in advance.

**Comment by LegendaryDev320** [comment]
I also have problems with onLogs. It does not catch all transaction logs on solana chain. How can I solve it?

**Comment by CriesofCarrots** [comment]
https://github.com/solana-labs/solana-web3.js isn't part of this repository. Please don't necropost.
