### ISSUE TITLE
Expose warp_to_slot via endpoint on local-test-validator

### ISSUE THREAD

**Issue by jacobcreech** [solana-labs/solana#24610]
#### Problem

Currently the only way to test cases where you need to switch x slots in the future is to either restart the local validator with `--warp-slot` or use the `program-test` crate with `warp_to_slot()`. Javascript and other language frameworks would love to have a way to test with this feature without jumping into Rust or restarting the local validator.

[An example of a user trying to use warp_to_slot functionality in javascript.](https://stackoverflow.com/q/71925184/17245830)

#### Proposed Solution

Expose a way to warp_to_slot via a RPC endpoint on the local test validator. [Code for reference](https://github.com/solana-labs/solana/blob/dd15193c69f5292ff566b84837516097bc0b8f57/program-test/src/lib.rs#L1101-L1157)

**Comment by stegaBOB** [comment]
@jacobcreech I'm going to take a crack at this over the weekend. Been a pain point for quite some time.

**Comment by mvines** [comment]
This is likely going to be a pretty invasive change, just FYI. I don't mean to discourage you, just be sure you well understand the replay and banking stages as well as how PoH works before getting in too deep.

**Comment by stegaBOB** [comment]
Even better! Been wanting to do a deep dive on how everything works but haven't really had a great reason to. Worst case scenario, I can't get this to work but end up with quite a bit of useful core Solana knowledge that will help me in the future. :)
