### ISSUE TITLE
Run fee prioritization tests on Tds

### ISSUE THREAD

**Issue by carllin** [solana-labs/solana#24617]
#### Problem
Need to confirm prioritization works

#### Proposed Solution
1. Run bench-tps on Tds creating high traffic situation
2. Submit high priority transaction using additional fees that *don't contend for the same lock as the transactions from 1.* (This is important because the prioritization on highly contended accounts is not yet handled)
3. See that high priority transactions land

**Comment by taozhu-chicago** [comment]
This one prolly should be done after #24615 

Can use `solana ping --additional-fee <lamports>` in step #2, it has implemented in cli at #23513

**Comment by taozhu-chicago** [comment]
Running various tests on testnet, results are in this spreadsheet: 
https://docs.google.com/spreadsheets/d/11ioOPvKQRlGNn4fsx8EmH9q7k-oZG-q41EG3xv0mPEw/edit?usp=sharing
