### ISSUE TITLE
Add actual computation of transaction weight/fee-per-cu

### ISSUE THREAD

**Issue by carllin** [solana-labs/solana#24615]
#### Problem
This depends on #24613 landing. 

In #24613 we restructured `BankingStage` to support a heap that organizes packets by weight. However, the weight of all the packets is equal in this implementation (other than by sender stake). We need to actually compute the fee-per-cu using additional fees and base fees.

**Comment by taozhu-chicago** [comment]
To clarify if we are good to set fee_priority without `base fee` as discussed in [discord here](https://discord.com/channels/428295358100013066/560496939779620864/967254251606802442).

Basically given the `base fees` (eg sig fee, write lock fee, compute fee etc) are constant at the moment, we can simply use `additional_fee` of `compute_budget` instruction to deterministically set `fee_priority = compute_budget_ix.additional_fee / compute_budget_ix.requested_CUs`. This would greatly simply implementation as we don't need a `bank` but just look into transaction to determine fee_priority.
