### ISSUE TITLE
Unexpected response from RPC API `getSignaturesForAddress` when `until` sig not found

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#24620]
#### Problem
When an RPC node receives a `getSignaturesForAddress` request and cannot find the signature used in the `until` parameter, it will just return a list of the most recent signatures (up to the limit). This is unexpected in cases where a signature has been confirmed by the cluster but the contacted RPC node has not yet confirmed the signature yet because it is slightly behind. See issue here: https://github.com/solana-labs/solana/issues/24417

#### Proposed Solution
If `until` cannot be found, return an error response

**Comment by jstarry** [comment]
@CriesofCarrots what do you think about the proposed solution here?

**Comment by CriesofCarrots** [comment]
I think we may want different handling depending on whether a provided `before` signature is found or not -- I want to think through that a little more. But in the case of no `before` and not-found `until`, yes, I think an error response makes a lot of sense.

**Comment by Legendree** [comment]
This is still an issue, any updates on this? thanks

**Comment by arturferreira** [comment]
I'm also facing this issue, when hiting the same RPC (tried quicknode, Genesys Go, Ankr, etc). Also they're the most recent transactions, but hours old, so everything should be confirmed. What I've noticed, is that when this happens, the transactions belong to the same block.

E.g.
Tx 1 - block 2
Tx 2 - block 2
Tx 3 - block 2
Tx 4 - block 1

If I do a getSignaturesForAddress until Tx3, it returns Tx 1 and Tx 2 (correct).
Then if I do a getSignaturesForAddress until Tx1, it will return 2 and 3 (incorrect).

In my example, both Tx1, 2 and 3 are 5h old and I can reproduce this consistently.

E.g. Transactions
5zCk4r61KrxS6wrVevGfM9Si4E4mStcNWp5fdYVKH1dR2Qia59sLy5Rf5WHXrZ9kYhjHiVcEVnqFzeoK1AiUN72P
3UjqKvrNDaDexj41c4fQmmfFMkDeEZox2XNWr1bkuhcsbBiKSgsCoQicf8SaQq2Vk9wwPha4PiGuWvsKhQpZuzbF
2YJ2Eb192NZbSivMyZsu75ACzLqgFBRoLHAVcp1MRndMTXDZdwgqGuVeyU4cRYh68qVpWpHMty11f5CwLWuy4c4p
on wallet https://solscan.io/account/Cngze9zz4nRuzDcCahEprRdtTvH7mFG3fb1Ys8bU4H5v

**Comment by CriesofCarrots** [comment]
The proposed fix isn't completely trivial to implement, since we support before/until signatures that don't involve the specified address, and since we check both Blockstore and Bigtable for results. I'd be happy to look a PR for this, though, @jstarry
