### ISSUE TITLE
[storage mining] Replicator repair corruption

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#2463]
#### Problem

When a replicator is added to a network and serves repair requests to a validator, it may not be serving the correct blobs because corruption is seen in the validators in the form of failed PoH checks.

**Comment by sakridge** [comment]
@MarkJr94 can you take this issue as well? First step is to write a test to see that the replicator is serving the correct blobs. Can use test_replicator_startup and just download more blobs and run entry.verify() function to see if they are correct and pass PoH.

**Comment by garious** [comment]
@MarkJr94, ping

**Comment by garious** [comment]
@MarkJr94, ping

**Comment by MarkJr94** [comment]
@garious i don't think so

**Comment by sakridge** [comment]
Not sure this is a problem anymore.
