### ISSUE TITLE
install error 

### ISSUE THREAD

**Issue by DavidYenATUM** [solana-labs/solana#24631]
#### Problem C:\Users\atumw\Downloads\Solana\metaplex-master (2)>C:\solana-install-tmp\solana-install-init.exe v1.10.8
The system cannot execute the specified program. 

I cant down Solana to use the candy machine

**Comment by AnhTuDo1998** [comment]
Hey are you using Windows 10 or other version?

**Comment by DavidYenATUM** [comment]
11

**Comment by t-nelson** [comment]
we don't use github for support. try #developer-support on https://solana.com/discord
