### ISSUE TITLE
Persist AccountDB Index along with snapshot

### ISSUE THREAD

**Issue by HaoranYi** [solana-labs/solana#24643]
#### Problem

When a validator starts, it spends a signifcant time to rebuild the AccountDB
index. Rather than rebuiding the index from the loaded snapshot at startup, is
it possible that we save the AccountDB index in addtion to the snapshot?

#### Proposed Solution
Save AccountDB index in addition to AccountDB in the snapshot file.

**Comment by sakridge** [comment]
What's the additional size though?

**Comment by HaoranYi** [comment]
Good question. @jeffwashington @brooksprumo Do we have any metrics for the AccountDB index size?

**Comment by jeffwashington** [comment]
# bins is a cli arg. Will likely need to increase as # accounts increase.

**Comment by mvines** [comment]
We could also just persist the index for local snapshots, as a separate artifact.

Rebuilding the index on boot is a major contributor to node startup time so any reductions will be welcome by all.

**Comment by abourget** [comment]
We have done work to increase boot time by implementing what we called `boot-snapshot`, which keeps the previous snapshot, and upon reboot, continues exactly where it left off when shutdown (avoiding the need to redownload a snapshot, untar it, etc..).

The code is here: https://github.com/solana-labs/solana/compare/832cb76e45d4b43f15a95bdd25a60e3113c16bdc...streamingfast:fast-boot?expand=1

I'd love for this to be merged in some ways, and made to work.
It worked for the most part, but there were some stability issues.

**Comment by abourget** [comment]
I can jump on a call any time to give an overview of the `fast-boot` design. Find me on the StreamingFast Discord, all our team is there, linked from streamingfast.io

**Comment by HaoranYi** [comment]
@abourget Nice work. 

We have implemented a similar feature in the validator. The idea is similar to yours. 
https://github.com/solana-labs/solana/issues/23452

If you pass `no-snapshot-fetch` on the cli, and you have the the snapshot file locally, validator will skip cleaning and shrinking at startup. This will cut about half of the start up time.

Compare with your approach, the above one still have the cost of untaring, which I hope this work 
https://github.com/solana-labs/solana/issues/24798  will reduce that by a factor of 10.
