### ISSUE TITLE
Speculate Bank Transactions Execution

### ISSUE THREAD

**Issue by HaoranYi** [solana-labs/solana#24656]
#### Problem

In the current validator system, when walidator receiving and processing block
data from the network, it runs signature verification speculatively and in
parallel. But, the actual Execution of the bank transactions doesn't run
speculatively. Hence, transactions execution are not parallel acorss different
banks. Since we can run sigverify speculatively, correspondingly, in theory, we
could execute transactions in the banks speculatively as well. Practically, how
possible is it to speculatively execute an bank, when all its data shred has
arrived, in the current validator system?

**Comment by nikhayes** [comment]
Hmm that idea sounds similar to Aptos' Block-STM idea? @terorie posted about it in the core-research channel in Discord the other day. https://arxiv.org/abs/2203.06871
