### ISSUE TITLE
Permission Denied (os 13) when installing `bpf-tools` via `cargo build-bpf` 

### ISSUE THREAD

**Issue by hacker-jak** [solana-labs/solana#24668]
## The issue:
When running `cargo build-bpf` for the first time it attempts to install `bpf-tools` and fails with a `Permission Denied (os 13)` message.

## Analysis 
During this process a couple of symlinks are made (`bpf-tools`, and `criterion`) in a sub directory `./sdk/bpf/dependencies/` where `.` is the current process (`cargo-build-bpf`) directory. 
These symlinks point to the downloaded `bpf-tools`/`criterion` directories `$HOME/.cache/solana/<version>/[bpf-tools/criterion]`
[L188 in cargo-build-bpf main.rs](https://github.com/solana-labs/solana/blob/3426433f99dcac191cf9bafb90782d391cb589c7/sdk/cargo-build-bpf/src/main.rs#L188) is the symlink line.

### Package manager install issue
When installing solana with a package manager it is normally installed in a `/` root directory. 
In my case, using `pacman`, the [solana-bin](https://aur.archlinux.org/packages/solana-bin) package was installed (via [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=solana-bin) instructions) to `/opt/solana-release`. 
This is a protected directory (owned by root), and cannot be written to by a user without the use of `sudo`. 
Therefore this error occurs when solana is properly installed and a `cargo build-bpf` command is attempted.

This isn't an issue if you're installing solana from source in a `$HOME` directory path, however, using a package manager to install solana poses an issue in this case. Pacman (Arch package manager) only installs to root `/` directories and it's considered bad practice to alter PKGBUILDs to install anywhere else.

## Workaround
In order to run `cargo build-bpf` without `sudo` permissions I added +rwx ACL permissions for my user for `/opt/solana-release/bin/sdk/bpf/dependencies/`. 
This worked.

I was able to remove these permissions after `bpf-tools` successfully installed (symlinks created) and `cargo build-bpf` works just fine.

## Solutions
I'm not sure what the ideal solution would be. I think having a way to install `bpf-tools` separately with `sudo` would be an easy way to handle it. That way `cargo build-bpf` doesn't fail with such an obscure message, it would just be missing `build-tools` and maybe reference how to install it.

**Comment by t-nelson** [comment]
we don't maintain, nor support any third party package manager installed bin. Please report to the corresponding package maintainers instead
