### ISSUE TITLE
Feature Gate: Automatically rewind stake credits when vote-account credits are zeroes

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#24674]
### Description

Currently [this bug](https://github.com/solana-labs/solana/issues/22512) means that stake-account credits observed on a vote account that has been destroyed and recreated are wrong.

This feature gate will sync (reset) such a stake account's observed credits on the epoch boundary following the vote-account credit-wiping.

### Feature ID

BUS12ciZ5gCoFafUHWW8qaFMMtwFQGVxjsDheWLdqBE2

### Activation Method

Single Core Contributor

### Minimum Beta Version

v1.11.0

### Minimum Stable Version

v1.11.0

### Testnet Activation Epoch

355

### Devnet Activation Epoch

432

### Mainnet-Beta Activation Epoch

464

**Comment by refi93** [comment]
@CriesofCarrots any ETA on this feature being activated on mainnet-beta?

**Comment by mvines** [comment]
Per https://github.com/solana-labs/solana/wiki/Feature-Gate-Activation-Schedule#current-schedule, it's the fourth feature that will be activated once mainnet upgrades to 1.14.
