### ISSUE TITLE
Add a way to get stake minimum delegation from RPC

### ISSUE THREAD

**Issue by brooksprumo** [solana-labs/solana#24690]
### Problem

From RPC, we cannot query the minimum stake delegation.

#### Proposed Solution

Add a new RPC endpoint.

We cannot use `simulate_transaction()` here, as it fails when loading accounts.

#### Previous proposed solution

> How about an `RpcClient` helper under the hood that performs `simulate_transaction` and returns parsed `return_data` of type T? I think we're going to want something similar for `spl_token::instruction::GetAccountDataSize`

_Originally posted by @CriesofCarrots in https://github.com/solana-labs/solana/issues/24690#issuecomment-1109933456_

#### Initial Description

> how about moving this into solana-program, so we don’t need a new dep in ledger/
When it’s moved into solana-program, we could probably remove the FeatureSet as well (since that’s only available in solana-sdk) and instead just always use 1 SOL

_Originally posted by @mvines in https://github.com/solana-labs/solana/pull/24660#discussion_r858083345_

**Comment by mvines** [comment]
Ah, I see.  

My initial comment was made from the perspective of an off-chain user who's looking through `RpcClient`, such as the solana-cli.

They don't really have a nice way to determine the minimum delegation currently -- downside of our decision to not use a Sysvar.  Their current choices seem to be:
1. Hardcode a value
2. Try to create the stake account with whatever stake amount the user provided, and attempt to gracefully handle the error from transaction simulation (or worse case, see the transaction fail)
3. Simulate a transaction with `StakeInstruction::GetMinimumDelegation` in it to retrieve the current minimum

**Comment by brooksprumo** [comment]
I was wondering if I should add a command to the CLI to get the stake minimum delegation. Would that be useful in this case?

**Comment by mvines** [comment]
An `RpcClient` method that does this would certainly be useful to the cli internally, so we can add the appropriate error handling when the user tries to create a new stake or split a stake with less than the minimum (ie, choice 3!)

**Comment by CriesofCarrots** [comment]
How about an `RpcClient` helper under the hood that performs `simulate_transaction` and returns parsed `return_data` of type T? I think we're going to want something similar for `spl_token::instruction::GetAccountDataSize`
