### ISSUE TITLE
solana-web3.js v1.40.0 missing lib folder when installed

### ISSUE THREAD

**Issue by badass-commits** [solana-labs/solana#24695]
#### Problem
When installed as npm dependency, solana-web3.js is missing lib folder.
@mvines Can you please check?

**Comment by badass-commits** [comment]
@mvines I don't think build script runs after npm install because type gen script uses files outside of included folders.

**Comment by johnrees** [comment]
related https://github.com/solana-labs/solana/issues/24689

**Comment by mvines** [comment]
Please don't summon me

**Comment by steveluscher** [comment]
1.40.0 is now deprecated with a message that links here. 1.40.1 has been published by @yihau. Sorry for the trouble, everyone!
