### ISSUE TITLE
tests/multinode.rs::test_full_leader_validator_network() is unstable

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#2481]
When `test_full_leader_validator_network()` is run repeatedly it periodically fails an assert.  Rather than marking the test `[ignore]` and thus destining the full test to rot and decay, just the offending assert has been commented out as a part of #2443 until the issue will be further analyzed.

https://github.com/solana-labs/solana/blob/b03d1d88942d1ec6656f9395e32f239cb6b4f1b7/tests/multinode.rs#L1656-L1662

**Comment by sakridge** [comment]
@mvines test doesn't exist... close?
