### ISSUE TITLE
some blocks are unavailable

### ISSUE THREAD

**Issue by panchengj** [solana-labs/solana#24823]
I had an error like Block cleaned up, does not exist on node. 
 failed to get confirmed block: Block 1723519 cleaned up, does not exist on node. First available block: 1841838).stack=Error: failed to get confirmed block: Block 1723519 cleaned up, does not exist on node. First available block: 1841838

Why some blocks are unavailable? 
my command like:  solana-test-validator --limit-ledger-size 9999999

**Comment by joncinque** [comment]
Hi there, we don't use GitHub for support, please join us on Discord at #developer-support https://discord.gg/solana or by asking a question on StackOverflow with the "solana" tag
