### ISSUE TITLE
solana-validator -h typo

### ISSUE THREAD

**Issue by codemonkey6969** [solana-labs/solana#24824]
#### Problem
Wording on solana-validator -h for "--gossip-validator" is incorrect. It should say push/pull rather than pull/pull         

--gossip-validator <VALIDATOR IDENTITY>...
            A list of validators to gossip with.  If specified, gossip will not pull/pull from from validators outside
            this set. [default: all validators]

#### Proposed Solution

Change wording on solana-validator -h for "--gossip-validator"to say push/pull rather than pull/pull

**Comment by t-nelson** [comment]
just pr it?
