### ISSUE TITLE
web3: unused Tx.verifySignatures

### ISSUE THREAD

**Issue by rjeli** [solana-labs/solana#24822]
signing a Transaction will verify the signatures then throw away the result instead of throwing on false. this isn't great because tweetnacl.js takes around 10ms per verify on my machine

https://github.com/solana-labs/solana/blob/0e0065a3f23a718731fd1d849e5b0f3a3d9f4408/web3.js/src/transaction.ts#L556

**Comment by steveluscher** [comment]
Ooh. Thanks for pointing this out. Interesting. I wonder how that line of code came to be.
