### ISSUE TITLE
EIP-1559-like adaptive transaction fees

### ISSUE THREAD

**Issue by ruuda** [solana-labs/solana#24827]
#### Problem

Transaction fees on Solana are constant. This means that users can’t pay more to get their transactions prioritized at times of high contention, so they have to resort to other measures, such as spamming the leaders and soon-to-be leaders. This has lead to degraded performance of the network almost daily in the past two weeks, because large validators get DoS'ed.

#### Proposed Solution

There is a proposal in https://github.com/solana-labs/solana/issues/22820. I think it is generally a good idea, but filtering and sorting transactions by fee is going to be an invasive change, and I don’t think it can be done in the short term, so the network will continue to go down.

Instead, we could make the transaction fee adaptive à la EIP-1559. If the blocks are full, the fee would go up, if the blocks are no longer full, fees would go down again. During times of high contention, the transaction price would go up rapidly, which would make spamming more expensive, ideally to the point where it is no longer profitable.

I expect that making the standard transaction fee adaptive is a less invasive change than adding a priority fee. There is still the possibility of adding a priority fee later on.

**Some considerations**:

* On Ethereum, at times of high contention the base fee adjusts slowly, and the priority fee makes up for the rapid change. See e.g. [this talk by Matt Cutler](https://www.youtube.com/watch?v=HYPGD2bOMOo&t=21007s), [slides](https://docs.google.com/presentation/d/1ijPMm-R_30gVpf3uJkhym2USlFqfxfuYsUsVcDe1W5w/edit#slide=id.g12554a7656d_0_656). Perhaps on Solana it would be less of a problem, due to the lower block times.
* It’s unclear what the optimal parameters are to make the trade-off between responsive but volatile fees vs. stable/predictable fees but slow response times.
* Should vote transactions pay the same fees as every other transaction? On the one hand, it would risk consensus in times of high contention if tx fees go up for votes, as validators may decide that the income from voting is not worth the cost. But on the other hand, that does free up capacity to have more transactions for users at times when users want it most.

**Comment by nikhayes** [comment]
I think the issue right now is that blocks can't be fully packed to the 48mil compute limit with two non-vote txn banking threads with the current batch transaction processing design and scenarios like NFT drops where you have a large majority of txns being contentious and non-parallelable. And there are some other issues where all the spam is overloading other parts of the validator so it can't even normally pack blocks. The fee priority changes seem to be coming relatively soon but I worry that the UX might be kinda unpredictable in situations like NFT drops where everyone will send a lot of transactions simultaneously. 

I have an idea to charge for "stale" transactions. There would be a second blockhash window where the fee payer could be charged for an old transaction and the compute required would be less than that of a transfer apparently, meaning the tps could likely be higher than the 100k tps benchmarks done on testnet. Bots aren't afraid of sending millions of transactions because they can only get charged for a very small portion of those sent. Validators should be able to capture the value from the excess transactions and bandwidth being taken up, rather than being forced to constantly accommodate spamming with higher and higher bandwidth. Quic will probably help but may move some spam bottlenecks to the RPC layer and not sure how that will affect the UX for users.

**Comment by ruuda** [comment]
> I have an idea to charge for "stale" transactions. There would be a second blockhash window where the fee payer could be charged for an old transaction and the compute required would be less than that of a transfer

That’s a neat idea to make it more costly to spam. Some thoughts:

* If transaction fees are low, it will still be worth spamming. It makes sense to spam until the expected profit matches the cost to spam. At 0.000005 SOL per signature, it would still be profitable to send send 100,000 transactions if one of them lands a 0.51 SOL profit. So on its own this would not fix the spamming issue, but it would definitely help, together with adaptive fees.
* Validators would need to store those transactions in memory, in order to still put them on the chain later. With >10 Gbps traffic, as has been the case recently, that would quickly fill up the memory of even very overprovisioned machines in seconds to minutes.

**Comment by ruuda** [comment]
I was discussing this with @joncinque and he had a great idea:

* Non-deterministic fees (when you don’t know how much you’ll pay at the time you submit your transaction) are a bad user-experience. Even if the fee is adaptive, it would be nice to have it not change under your feet.
* Solution: Every block has an associated fee (adaptive, computed based on the preceding blocks). The fee you pay is not the fee of the block the transaction lands in, but the fee of the block referenced by the transaction’s recent blockhash.
* Now you know ahead of time what fee you’ll pay, at the cost of introducing a few minutes delay in the adaptive fee mechanism.

Some considerations:

* If I’m a bot trying to get my transaction in, and the fee is ramping up ... I want to pay as little as possible, so I’m going to reference as old a block hash as possible. The transaction expires soon, but then I can just spam a new one.
* However, the underlying problem that creates spam, is that bots cannot pay more to get their transaction prioritized. If the fees are ramping up, they actually have a very nice way to _choose_ a fee: choose an older blockhash for cheaper transactions, or a more recent one to pay more.
* The validators want to put the most expensive transactions in their block, because they get part of the transaction fee, so actually bots will reference recent transactions to get prioritized, and they will pay the full fee.

What would it look like on the validator side? Instead of maintaining a vector of transactions and including them FCFS, maintain a priority queue ordered by fee.

Of course this will not fix all problems, a user-specified priority fee should help more. But that is an invasive change, and making the existing fee adaptive could possibly be done sooner, to mitigate the current congestion issues.

**Comment by nikhayes** [comment]
> > I have an idea to charge for "stale" transactions. There would be a second blockhash window where the fee payer could be charged for an old transaction and the compute required would be less than that of a transfer
> 
> That’s a neat idea to make it more costly to spam. Some thoughts:
> 
> * If transaction fees are low, it will still be worth spamming. It makes sense to spam until the expected profit matches the cost to spam. At 0.000005 SOL per signature, it would still be profitable to send send 100,000 transactions if one of them lands a 0.51 SOL profit. So on its own this would not fix the spamming issue, but it would definitely help, together with adaptive fees.
> * Validators would need to store those transactions in memory, in order to still put them on the chain later. With >10 Gbps traffic, as has been the case recently, that would quickly fill up the memory of even very overprovisioned machines in seconds to minutes.

Ah whoops I meant to reply. So with this I would have it so the "stale" txn would cost the same as the entire transaction would have cost otherwise (with compute unit pricing). You could even add in some sort of congestion pricing related to it perhaps (related to the local account-based congestion fees).

I think it would be cool if the fees went into a pool that would get shared at the end of epoch (this could also go back to stakers too, to essentially reimburse them for having to deal with spam and maybe getting charged for some transactions) because this would encourage validators to share and keep track of transactions that have been sent and could be charged. Zan @bji was thinking there could be some way of keeping track of the amount of stale transaction forwards validators make so that the fee pot could be split based on forwarding contributions.

I'm about to read your newest comment.

**Comment by nikhayes** [comment]
> I was discussing this with @joncinque and he had a great idea:
> 
> * Non-deterministic fees (when you don’t know how much you’ll pay at the time you submit your transaction) are a bad user-experience. Even if the fee is adaptive, it would be nice to have it not change under your feet.
> * Solution: Every block has an associated fee (adaptive, computed based on the preceding blocks). The fee you pay is not the fee of the block the transaction lands in, but the fee of the block referenced by the transaction’s recent blockhash.
> * Now you know ahead of time what fee you’ll pay, at the cost of introducing a few minutes delay in the adaptive fee mechanism.
> 
> Some considerations:
> 
> * If I’m a bot trying to get my transaction in, and the fee is ramping up ... I want to pay as little as possible, so I’m going to reference as old a block hash as possible. The transaction expires soon, but then I can just spam a new one.
> * However, the underlying problem that creates spam, is that bots cannot pay more to get their transaction prioritized. If the fees are ramping up, they actually have a very nice way to _choose_ a fee: choose an older blockhash for cheaper transactions, or a more recent one to pay more.
> * The validators want to put the most expensive transactions in their block, because they get part of the transaction fee, so actually bots will reference recent transactions to get prioritized, and they will pay the full fee.
> 
> What would it look like on the validator side? Instead of maintaining a vector of transactions and including them FCFS, maintain a priority queue ordered by fee.
> 
> Of course this will not fix all problems, a user-specified priority fee should help more. But that is an invasive change, and making the existing fee adaptive could possibly be done sooner, to mitigate the current congestion issues.

Looks like I had a kinda similar idea! I was thinking some form of queue would be nice, to somehow prioritize those who spam more... (maybe by signer?). I wonder if your fee-priority idea could work with the fee-priority thing that theyve been working on. Have you seen that? I can link if not.

**Comment by ruuda** [comment]
> I think it would be cool if the fees went into a pool that would get shared at the end of epoch

The validator is selfish. A mechanism is less effective if the validator doesn’t benefit from it proportionally.

There is a similar situation with the block times. If all validators would produce blocks faster — for example by having faster CPUs that can run the PoH clock faster — there would be more blocks per year, and validation revenue would be higher. But for an individual validator, the change in revenue due to lower block times caused by their own blocks is tiny, and for smaller validators, for sure that gain is smaller than the cost of a faster CPU, so in practice there is no pressure to produce blocks faster.

Also, half of the transaction fees currently get burned, which is effectively the same as distributing it proportionally to all SOL holders.

> to somehow prioritize those who spam more...

Again, the validator is selfish, the validator wants to build the most profitable blocks. The challenge is to set up the protocol in such a way that what is good for a selfish validator is also good for the network. Making spammers pay more for failed transactions, I don’t know if the net effect is going to be positive:

* If failed spam transactions are lucrative for the validator to include in the block, it will make it more expensive to spam, which would discourage spamming in the long run.
* At the same time, including those spam transactions comes at the cost of valid transactions which are less lucrative to include. So in the short term, it makes the chain less usable.

But either way, let’s not get sidetracked on this issue, this issue is about EIP-1559-like adaptive fees, we can continue the discussion about other mechanisms in #25211.
