### ISSUE TITLE
tests/multinode.rs::test_dropped_handoff_recovery() fails

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#2482]
`test_dropped_handoff_recovery()` fails to successfully complete as the "next leader" never assumes the leader role.

May be related to #2383

In the meantime, the part of the test that fails has been disabled with a large comment as a part of #2443 

https://github.com/solana-labs/solana/blob/b03d1d88942d1ec6656f9395e32f239cb6b4f1b7/tests/multinode.rs#L1419-L1426

**Comment by sagar-solana** [comment]
@mvines looks like this has been fixed on master. closing it.

**Comment by garious** [comment]
@sagar-solana, running the test-suite still causes this message to be output:

```
ERROR multinode] TODO: FIX https://github.com/solana-labs/solana/issues/2482
```

**Comment by sagar-solana** [comment]
Oh my bad. I didn't realize it was tied to this. The test itself seems to pass and I wasn't running with --no-capture.

**Comment by sagar-solana** [comment]
@garious, if this is indeed related to #2383, we may not be able to address till every node is running a poh_service.

**Comment by garious** [comment]
deleted multinode tests
