### ISSUE TITLE
bad CPU type in executable: solana

### ISSUE THREAD

**Issue by TaylorChen** [solana-labs/solana#24832]
#### Problem

mac os version :
Darwin Kernel Version 18.6.0
xnu-4903.261.4~2/RELEASE_X86_64 x86_64
Run solana command get bad following errors:
```
solana --version
zsh: bad CPU type in executable: solana
```
#### Proposed Solution
How did  run it  correctly ?

**Comment by t-nelson** [comment]
we don't use  github for support.  try #developer-support on https://solana.com/discord
