### ISSUE TITLE
TPU has no way of recording only its block of transactions in such away that is consistent with the TVU

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#2486]
#### Problem
TPU has no way of recording only its block of transactions in such away that is consistent with the TVU.  Current implementation would require the TVU to replay TPUs work.

#### Proposed Solution

Change the TPU pipeline to this:

1. lock accounts (some locks could fail)
2. process transactions (Some transactions could fail.  If all fail GOTO 5)
3. record (Record only successful transactions into an entry.  Record could fail for the whole entry if PoH is higher than block height for this leader.  If record fails GOTO 5)
4. commit (only successful transactions)
5. unlock accounts (only locks that succeeded)

record would fail if the PoH height is greater than the last block tick.

tag: @rob-solana @garious

**Comment by garious** [comment]
PohRecorder stops producing entries after max_tick_height. Instead of failing afterward, PohService can implement what's currently called TPU Forwarder.

**Comment by aeyakovenko** [comment]
@garious That seems like the wrong place to do that.  I think PoH service should return an error, which will cause commit to be skipped, and banking stage can decide to do forward or broadcast based on that error.
