### ISSUE TITLE
Show error message when no TPS/Ping data is available

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana#24877]
#### Problem

When there is no TPS/Ping data available, you can find yourself with a chart that looks like this:

![image](https://user-images.githubusercontent.com/13243/166168126-3fb8efeb-dcc0-4ec4-b3d6-a557eea6e412.png)

#### Proposed Solution

Rather than a blank space, we should either show a message or not render the charts.

**Comment by jstarry** [comment]
Was this fixed? I believe I saw an error message for this yesterday

**Comment by steveluscher** [comment]
Nope! I've still been on the hunt for a repro. @chaseeb said he saw this on Chrome on mobile.

**Comment by jstarry** [comment]
Hmm maybe the request is successful but the datapoint list was empty. I saw the error message when the request failed completely
