### ISSUE TITLE
Ledger-tool doesn't save new snapshots to --snapshot-archive-path

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#24875]
#### Problem
If a validator uses `solana-ledger-tool create-snapshot` without an output-path arg (2nd positional arg), the new snapshot gets saved by default in the dir specified by `--ledger`, even if a `--snapshot-archive-path` is provided. This is unintuitive.

#### Proposed Solution
Respect `--snapshot-archive-path` for ledger-tool snapshot creation when explicit output-path not provided

**Comment by diman-io** [comment]
It has always pissed me off too

**Comment by steviez** [comment]
Incase anyone wants to take a stab at it ..., the positional argument is read here:
https://github.com/solana-labs/solana/blob/546730cf4264eb9d3b53166564e876bb57830e57/ledger-tool/src/main.rs#L2187-L2188

`--snapshot-archive-path` is read here:
https://github.com/solana-labs/solana/blob/546730cf4264eb9d3b53166564e876bb57830e57/ledger-tool/src/main.rs#L1695-L1697

At first glance, it seems some logic in `unwrap_or_else()` could try to fall back on `snapshot_archive_path` before falling back on `ledger_path.clone()`

**Comment by diman-io** [comment]
@steviez looks like you didn't see the PR sent 8 hours ago? ))

**Comment by CriesofCarrots** [comment]
@diman-io , I edited your PR description to link back to (close) this issue. I know it's a simple change, but can you please also fill out the `Summary of Changes`? Thanks!

**Comment by diman-io** [comment]
@CriesofCarrots Done
