### ISSUE TITLE
Development Analysis - a Cyb3r Sh4man research

### ISSUE THREAD

**Issue by Cyb3r-Sh4man** [solana-labs/solana#24884]
#### Problem
I analyzed the **DEVELOPMENT PROCESS** of Solana.
There are good news and bad news.
[https://youtu.be/Zr2RMFtUcXc](url)

#### Proposed Solution
Some solutions where explained in the video. Others can be discussed here. Please mention anyone you think should watch this.
Please tell me were you think there is a mistake or misunderstanding so I can avoid that in the future.

**Comment by mvines** [comment]
nice promo attempt

**Comment by Cyb3r-Sh4man** [comment]
@mvines 
If it was what you think, I could do that 132 days ago when the video was uploaded to have maximum effect.

But I'm looking for some **PROFESSIONAL OPINIONS here**, not on YouTube.(and tell you about Issue management problems, Labeling, etc.)

Anyway, I'm trying to look at the positive side of your reaction: **Response Time** has improved a lot! 3 hours. :)

And just because you closed the issue without watching the video, here are some images about what I found and why I needed your opinions. 

![community metrics - Solana](https://user-images.githubusercontent.com/88320379/166267585-36ba0df0-2e45-47db-8236-b7970def5aad.png)
![Labels - Solana](https://user-images.githubusercontent.com/88320379/166267610-c94ba970-92b9-4767-8da9-f7cdb632124f.png)
![Programming metrics - Solana](https://user-images.githubusercontent.com/88320379/166267627-10c9f4fe-fc4a-4afc-b840-8723d5634d94.png)
![rocd50g - Solana](https://user-images.githubusercontent.com/88320379/166267685-3393a935-8c38-46c1-beb3-b17715b13b2b.png)



I will not comment here after this one to respect your decision.
