### ISSUE TITLE
Both instances of SigVerifyStage report metrics under the same datapoint

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#24928]
#### Problem
We have two instances of sigverifystage, one for general txs and one for votes. They both report metrics under the "sigverify_stage-total_verify_time" datapoint

#### Proposed Solution
Use new datapoint for vote sigverifystage metrics

@taozhu-chicago do you mind picking this up?

**Comment by sakridge** [comment]
This is already fixed by this, no? https://github.com/solana-labs/solana/pull/24744

**Comment by jstarry** [comment]
Oh never mind, noticed it wasn't the case in v1.9 and didn't check master
