### ISSUE TITLE
Error: Your configured rpc port: 8899 is already in use

### ISSUE THREAD

**Issue by blockchain-app12** [solana-labs/solana#24929]
Hi all,

I can't able to run the cargo test command. I hope solana-test-validator is working properly in my machine. Please give me some tips for this

#### Problem

![Screenshot from 2022-05-03 15-25-15](https://user-images.githubusercontent.com/48212011/166438639-7a86fabd-7cb3-4007-a58e-31e3188ea58d.png)

**Comment by joncinque** [comment]
Hi there, we don't use GitHub for support -- please head to #developer-support on the Solana Tech Discord https://discord.gg/solana

**Comment by developdeez** [comment]
Same here. been struggling since yesterday
