### ISSUE TITLE
1.9.19 compiled binary won't execute on Ubuntu 20.04

### ISSUE THREAD

**Issue by michaelh-laine** [solana-labs/solana#24962]
#### Problem
Checking out tags/v1.9.1 9 and building with `./cargo build --release` with no additional RUSTFLAGS results in a `solana` binary that can't be executed.

```
$ ./solana --version
-bash: ./solana: cannot execute binary file: Exec format error
```

Compiled on WSL Ubuntu 20.04 LTS, same system I have compiled 1.9.18 and many other releases back to 1.6 branch on, can't execute on either the build machine or on the validator server which runs native Ubuntu 20.04 LTS.

`solana-validator`, `solana-ledger-tool`, `solana-sys-tuner`, `solana-keygen`, `solana-install`, `solana-tokens` are other binaries I checked which CAN be executed. This issue has been identified **only** in the `solana` binary.

I checked out tags/v1.9.18 and compiled with the exact same command (`./cargo build --release`) and the `solana` binary is executable on both machines. 

All tests using stock tags with no modifications. Compile CPU is Ryzen 5900X, validator CPU is Epyc 7443P, same architecture.

**SOLUTION**
Compiling with target-cpu=native fixes this issue. However this wasn't required on 1.9.18 or any previous version that I recall so somehow it's not compiling for the right architecture by default?

@willhickey @t-nelson 

~~FYI `1aine15iEqZxYySNwcHtQFt4Sgc75cbEi9wks8YgNCa` is up on 1.9.19 and metrics open if you need more data before announcing~~

We're rapidly dropping credits on .19 vs .18, reverting to .18. After restart we were ranked ~850th by credits (~80th pre restart) and dropped to 1100th after about 60 minutes, observed a continuous degradation to that point, not a jump. We've underperformed the cluster average vote credits by 2.9% according to Cogent's credit tracker tool, over a sample period of 1400 slots:

```
reporting from slot 1651663372 to slot 1651664763
cluster average:                             1.4927764198418356
top 100 average:                             1.5060819554277496
DeadGodP9cErFezDuWRBQk4foLZbZfyBWmzHxGu6BLTo: 1.5276779295470884
Cogent51kHgGLHr7zpkpRjGYFXM57LgjHjDdqXd4ypdA: 1.531272465851905
**1aine15iEqZxYySNwcHtQFt4Sgc75cbEi9wks8YgNCa: 1.4507548526240115**
Ninja1spj6n9t5hVYgF3PdnYz2PLnkt7rvaw3firmjs: 1.5248023005032352
FLVgaCPvSGFguumN9ao188izB4K4rxSWzkHneQMtkwQJ: 1.4938892882818116
7y5VhV4fkz6r4zUmH2UiwPjLwXzPL1PcV28or5NWkWRL: 1.520488856937455
Frog1Fks1AVN8ywFH3HTFeYojq6LQqoEPzgQFx2Kz5Ch: 1.5305535585909418
PUmpKiNnSVAZ3w4KaFX6jKSjXUNHFShGkXbERo54xjb: 1.4766355140186915
6TkKqq15wXjqEjNg9zqTKADwuVATR9dW3rkNnsYme1ea: 1.488138030194105
```

the vote credit underperformance persists on .18 so not related to .19, ignore all the above except the binary format issue

**Comment by willhickey** [comment]
I just compiled and ran the CLI on one of our servers running Ubuntu 20.04.3 and it worked correctly. I wonder if the issue is specific to WSL? There's only 15 commits from 1.9.18 to 1.9.19... if you want to git bisect those the source of the problem might become obvious.

If the vote credit underperformance persists in a way that you believe is a regression let's open a separate issue to track it.

**Comment by michaelh-laine** [comment]
The labs binaries from `solana-install` do work for me btw, so only self compiled is an issue
