### ISSUE TITLE
allow solana-test-validator to log to stderr similar to solana-validator 

### ISSUE THREAD

**Issue by xoac** [solana-labs/solana#24963]
This is how `--log` flag looks for `solana-validator`
> -o, --log <FILE>
            Redirect logging to the specified file, '-' for standard error. Sending the SIGUSR1 signal to the validator
            process will cause it to re-open the log file
            
This allow to easy use solana-validator in container and redirect logs to standard output. 

The `solana-test-validator` do not support such feature. It will be useful to use for example in docker to see logs with `docker logs`

**Comment by t-nelson** [comment]
```
$ solana-test-validator --help
solana-test-validator 1.10.3 (src:bb9f9c8d; feat:3801236799)
...
        --log                                    Log mode: stream the validator log
...
```

**Comment by xoac** [comment]
Oh sorry. I do not now why I tried add argument to this flag
