### ISSUE TITLE
Cargo build-bpf not found

### ISSUE THREAD

**Issue by rohitas-git** [solana-labs/solana#25005]
### Problem

I have an issue that I reinstall solana and thus, rust which was linked with previous solana files has changed. Previously I could use cargo build-bpf but now, I am shown error : 

BPF SDK path does not exist: /Users/user_name/.cargo/bin/sdk/bpf: No such file or directory (os error 2)

Also I can't uninstall rust by : rustup self uninstall

I am confused how to proceed. No solution found from searching in google.

**Comment by t-nelson** [comment]
we don't use github for support requests. try https://solana.com/discord instead
