### ISSUE TITLE
Feature Gate: Require static program ids in transactions

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#25034]
### Description

Transaction ingestion cannot do static analysis over transaction program instructions to determine user fees, precompile usage, and estimated compute without first loading addresses from on-chain lookup tables. This feature gate adds a sanitization requirement that top-level program ids for transaction instructions are in the raw transaction and not loaded from a lookup table.

### Feature ID

8FdwgyHFEjhAdjWfV2vfqk7wA1g9X3fQpKH7SBpEv3kC

### Release

v1.10.13

### Activation Method

Single Core Contributor

### Testnet Activation Epoch

348

### Devnet Activation Epoch

358

### Mainnet-Beta Activation Epoch

355

**Comment by ptaffet-jump** [comment]
Unless I'm misunderstanding something, this is active in Mainnet (transaction UKCkK8Nm5b1TmhM98Ji3x6mmpfmy7mPBvqUV3JwxVQDMHi6fYeQ2RhzjoGahPBCYtmnqXhT1rgRfCWYEb1sFeGU). Would you mind updating the status and/or closing the issue?

**Comment by CriesofCarrots** [comment]
> Would you mind updating the status and/or closing the issue?

I added the mnb activation epoch. We typically close these issues when the feature-gating logic has been cleaned up in master.

**Comment by ptaffet-jump** [comment]
Makes sense. Thanks!
