### ISSUE TITLE
Unknown Instruction: instruction data is not displayed

### ISSUE THREAD

**Issue by alex-altarey** [solana-labs/solana#25046]
#### Problem
In this transaction, I see the arguments and values as an array: 
[https://explorer.solana.com/tx/549bVbg7Q7NYj4hpHa3uZyNf36poFPgxwV4ukRuDEmGX78bwdizEBQojXa1pVwocfidcwHXTKp27GeXatAds8msC](https://explorer.solana.com/tx/549bVbg7Q7NYj4hpHa3uZyNf36poFPgxwV4ukRuDEmGX78bwdizEBQojXa1pVwocfidcwHXTKp27GeXatAds8msC)

![arguments](https://user-images.githubusercontent.com/104500126/167172472-46032a51-ccae-49cb-a773-64ceb39715dc.png)

When I create a transaction, I see only such data:

[https://explorer.solana.com/tx/4FG8JbtRxi8k11HecNARmaXKjK6cEYdD67LBwxnQngfD3TK8RfffEK3EdbP9dEQWwMc6mHUnW8Bj4AzZyTs4qto3?cluster=testnet](https://explorer.solana.com/tx/4FG8JbtRxi8k11HecNARmaXKjK6cEYdD67LBwxnQngfD3TK8RfffEK3EdbP9dEQWwMc6mHUnW8Bj4AzZyTs4qto3?cluster=testnet)

![arguments 2](https://user-images.githubusercontent.com/104500126/167172258-59db11f5-8376-48f5-a90f-6750f0a74577.png)

My TypeScript code:
```typescript

function createSayHelloInstructionData(): Buffer {
  let params = { space: 100 };

  let allocateStruct = {
    index: 8,
    layout: struct([
      u32('instruction'),
      ns64('space'),
    ])
  };

  let data2 = Buffer.alloc(allocateStruct.layout.span);
  let layoutFields = Object.assign({instruction: allocateStruct.index}, params);
  allocateStruct.layout.encode(layoutFields, data2);

  return data2;
}

// let publicKeyNew : PublicKey = new PublicKey('AE9EeukgpthYBp8jyviJzh74kutx1M8WYGEYCJGLmWJj');
// let programIDNew = new PublicKey('5BByj4eMoYthSJojQagFRbtq54FjrcZefifmL9UDPhnx');

/**
 * Say hello
 */
export async function sayHello(): Promise<void> {
  let keypair = await getPayer();
  console.log('Saying hello to', greetedPubkey.toBase58());
  const instruction = new TransactionInstruction({
    keys: [{pubkey: greetedPubkey, isSigner: false, isWritable: true}],
    programId,
    data: createSayHelloInstructionData(), // All instructions are hellos
  });
  await sendAndConfirmTransaction(
    connection,
    new Transaction().add(instruction),
    [payer, keypair],
  );
}
```

  
  
I want to display data in a transaction: Argument name, type, value. What do I need to do for this?
fyi @gleb-altarey

**Comment by jstarry** [comment]
Good question! The screenshot above shows the decoded instructions for a program built with the Anchor framework. If you build your program with anchor and deploy your program's IDL on-chain, the explorer will automatically decode your instructions. You can read more about Anchor and its IDL here: https://book.anchor-lang.com
