### ISSUE TITLE
Feature Gate: Support `SetComputeUnitPrice` compute budget instruction

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#25050]
### Description

Compute instruction's additional fee type is too small for the current use cases, increase to u64

### Feature ID

98std1NSHqXi9WYvFShfVepRdCoq1qvsp8fsR2XZtG8g

### Releases

v1.10.14

### Activation Method

Single Core Contributor

### Testnet Activation Epoch

332

### Devnet Activation Epoch

332

### Mainnet-Beta Activation Epoch

329

**Comment by jstarry** [comment]
Behavior updated by https://github.com/solana-labs/solana/pull/25178
