### ISSUE TITLE
web3.js Connection http agent hanging tests and cli utilities

### ISSUE THREAD

**Issue by kklas** [solana-labs/solana#25069]
#### Problem

In the Connection class the [AgentManager](https://github.com/solana-labs/solana/blob/master/web3.js/src/connection.ts#L947) is used in order to pool http connections to the rpc server. Since the [keepAlive option is used](https://github.com/solana-labs/solana/blob/master/web3.js/src/agent-manager.ts#L13), the agent will hang until destroy() is called. To go around this there is a [timeout](https://github.com/solana-labs/solana/blob/master/web3.js/src/agent-manager.ts#L38) which will destroy the agent 5 seconds after the last request.

But this still **hangs the node process for 5 seconds** which is an issue for **CLI utilities** and **tests** which use Connection. For example, it causes the following message when running jest tests (which I'm sure many have encoutered due to this):
```
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
```

#### Proposed Solution

Either / or:
1) add ability to pass a custom agent to be used via an option in the Connection constructor
2) add a `connection.close()` method which will call `agent.destroy()` to clean up the connection gracefully

cc @steveluscher @jstarry

**Comment by steveluscher** [comment]
Love it. Thanks for pointing this out.

**Comment by rabbygit** [comment]
Is there any update about this issue?

**Comment by steveluscher** [comment]
Hey! No update, no. Still worth doing though! We just have to do it thoughtfully. I haven't sat down to really think about whether making the Agent an explicit input is the right thing to do (breaking change) or whether to add a destructor (not effective unless people use it).

**Comment by DavidPesta** [comment]
Thanks for working on this. Looking forward to this being resolved. :+1:

**Comment by steveluscher** [comment]
K, I wasn't comfortable creating a whole bunch of new API surface area, so what I ended up doing was to:

1. Let you override or disable the default agent via config on `Connection`
2. Automatically disable the default agent when `process.env.NODE_ENV` is `test`, which should cover you in Jest.

#29125.
