### ISSUE TITLE
Solana CLI Deploying Programs Issue

### ISSUE THREAD

**Issue by baileyspraggins** [solana-labs/solana#25063]
#### Problem
Whenever I am deploying a program to the solana devnet it says no default signer found and run "solana-keygen new -o /home/.Config/solana/id.json". After running this command I get a os error 45. How do I solve this. It is incredibly frustrating.

<img width="657" alt="Screen Shot 2022-05-06 at 10 20 30 PM" src="https://user-images.githubusercontent.com/62624378/167236010-994538ae-c6ca-4767-91fa-2746a199718e.png">

**Comment by crypt0miester** [comment]
are you sure it is .Config and not .config?

**Comment by t-nelson** [comment]
we don't use github for support.  try https://solana.com/discord instead
