### ISSUE TITLE
Missing blocks in long term storage

### ISSUE THREAD

**Issue by kilkka** [solana-labs/solana#25068]
#### Problem

There appears to be a new occurrence of https://github.com/solana-labs/solana/issues/21350. I am unable to query blocks between slots 130015988 and 130030888 inclusive. 

According to https://explorer.solana.com/block/130030889, 130030888 should be the parent, but the parent block will not load at https://explorer.solana.com/block/130015988 and the RPC is returning a -32009 error of `Slot 130030888 was skipped, or missing in long-term storage`.

#### Proposed Solution

Backfill the finalized blocks between 130015988 and 130030888 as was done to resolve https://github.com/solana-labs/solana/issues/21350

**Comment by CriesofCarrots** [comment]
Backfill is in progress

**Comment by joeaba** [comment]
The gap has been patched, thanks for reporting.
