### ISSUE TITLE
wasm-bindgen is always exported by solana-sdk even if I'm not using wasm-bindgen in my app

### ISSUE THREAD

**Issue by PirosB3** [solana-labs/solana#25073]
#### Problem

I'm building some Rust WASM applications that use `solana-sdk` crate. My applications targets `wasm32-unknown-unknown` however, since the host is not running Node and my app is not meant to run in the browser, I am not using [wasm-bindgen](https://rustwasm.github.io/wasm-bindgen/) but I'm using [waPC](https://wapc.io/) (which is a very thin wrapper around pure wasm) + Golang as host.

My app compiles perfectly using waPC however, when I look at the generated wasm function imports table, I notice that it contains all the `wasm_bindgen` exports even if I won't be using `wasm_bindgen`. Essentially, if I want to use `solana-sdk` and target WASM, I can only do so via `wasm_bindgen`.

While many will use WASM on the browser, making the assumption that Solana's Rust code (targeting WASM) will only run on a browser is going to limit future application development. In my particular use case, my application is targeting WASM because of WASM's security guarantees and sandbox, which allows me to run unprotected/risky code on my backend with low overhead.

#### Proposed Solution

Move `wasm_bindgen` macros into their own feature flag that can be explicitly disabled via Cargo crate.

**Comment by katopz** [comment]
Nearly same problem here, via `yew` and even worst `init` function at `solana 1.9.22` (which required by `anchor 0.24.2`) are conflicted with yew  wasm generated function that will cause ...

```
Uncaught SyntaxError: Identifier 'init' has already been declared (at foo_gen-501f7c0bf88ee0df.js:1224:1)
```

Workaround is manually remove `// #[wasm_bindgen]` or wait for `anchor` to support newer solana (which is somehow changed `init` name to `solana_program_init`) so no conflict but still useless there.

Able to disable this `wasm_bindgen` would be nicer.

**Comment by gwertem** [comment]
@PirosB3 @katopz did you find a solution? I have a WASM module that imports `anchor_lang` version `0.29.0`. Running it via wasmer in Rust gives me error

```
thread 'main' panicked at indexer-core/src/main.rs:20:71:
called `Result::unwrap()` on an `Err` value: Link(Import("__wbindgen_placeholder__", "__wbg_new_16b304a2cfa7ff4a", UnknownImport(Function(FunctionType { params: [], results: [I32] }))))
```

**Comment by PirosB3** [comment]
My understanding is that this has been fixed (I remember reading it
somewhere in the changelogs) but I have not effectively tried using the
WASM bindings yet

*************

PirosB3

https://github.com/PirosB3
