### ISSUE TITLE
Error: range end index 8 out of range

### ISSUE THREAD

**Issue by brianlong** [solana-labs/solana#25072]
#### Problem
I get this on v1.9.20, v1.9.19, & v1.9.18

`[2022-05-08T02:43:21.564634800Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="?" one=1i message="panicked at 'range end index 8 out of range for slice of length 0', runtime/src/cache_hash_data.rs:56:34" location="runtime/src/cache_hash_data.rs:56:34" version="\"1.9.20 (src:d22f2234; feat:2945818700)\""`

See attached logs.

#### Proposed Solution
TBD

[validator_crash_log.txt](https://github.com/solana-labs/solana/files/8646290/validator_crash_log.txt)
[validator_crash_log_2.txt](https://github.com/solana-labs/solana/files/8646292/validator_crash_log_2.txt)
[validator_crash_log_3.txt](https://github.com/solana-labs/solana/files/8646293/validator_crash_log_3.txt)

**Comment by t-nelson** [comment]
I'm assuming this only occurs with accounts disk index enabled?

**Comment by t-nelson** [comment]
cc/ @jeffwashington

**Comment by jeffwashington** [comment]
This is caching on the accounts hash calculation. Shouldn't have anything to do with disk index.

**Comment by t-nelson** [comment]
seems to have been addressed by https://github.com/solana-labs/solana/pull/25077
