### ISSUE TITLE
onProgramAccountChange not running for tx's which close accounts

### ISSUE THREAD

**Issue by bmeeder22** [solana-labs/solana#25097]
#### Problem
When a program account gets closed (all data deleted, and SOL removed from account). `onProgramAccountChange` does not trigger an associated event. This can be problematic for applications which want to watch for these types of events and process them accordingly. 

#### Proposed Solution
Make onProgramAccountChange trigger for when an account that was previously owned by a program, gets closed.

**Comment by jstarry** [comment]
Thanks for reporting, this has been a long standing bug as noted here as well: https://github.com/solana-labs/solana/issues/18704

**Comment by bmeeder22** [comment]
Closing do to duplication

**Comment by yongkangc** [comment]
is this fixed?
