### ISSUE TITLE
web3.js: _updateSubscriptions running in infinite recursion, crashing developed app

### ISSUE THREAD

**Issue by awojciak** [solana-labs/solana#25133]
#### Problem
When using latest release of @solana/web.js (1.41.4) and getting errors like this one:
![obraz](https://user-images.githubusercontent.com/48929607/167848255-2ebe13e7-2d0e-4fe0-914d-4075c7f10674.png)
developed app is crashing.
I suspect this happens because of recursion there, which seems to run indefinitely: 
![obraz](https://user-images.githubusercontent.com/48929607/167849170-4bb31a9b-c9ca-4b49-b3a1-d0586a52da4d.png)
When using version not containing this change in code (1.41.1), crashing doesn't happen.

#### Proposed Solution
Use one of solutions mentioned in TODO comment ("Maybe add an 'errored' state or a retry limit?")

**Comment by steveluscher** [comment]
Can't tell @jstarry didn't tell me so! :)

Do you have a reliable repro for this @awojciak; something that you could share with me? Or is this just showing up in your server logs?

**Comment by steveluscher** [comment]
The presence of the `socket not ready` error is helpful information though. I'll try to create such an environment synthetically.

**Comment by awojciak** [comment]
Hi, thanks for the response. Here you can check preview of environment where this situation happens: https://github.com/invariant-labs/webapp/pull/311. Open dev tools console in browser, set network in app to devnet and for example try to swap two tokens (use faucet to get our mock tokens) - then app will freeze and console will be full of these errors. I hope this will be helpful.

**Comment by steveluscher** [comment]
I stood the app up, but every time I use the dropdown to switch to devnet the whole app refreshes and returns to mainnet-beta. What am I missing?

**Comment by awojciak** [comment]
> ~I stood the app up, but every time I use the dropdown to switch to devnet the whole app refreshes and returns to mainnet-beta. What am I missing?~
> 
> Nevermind. I tried Chrome and it worked. You might like to test the app on Firefox – you might have a bug there that causes the whole page to refresh!

Weird, I've looked now on app on Firefox, network change works fine (but refresh is an intended behavior in this case)

**Comment by steveluscher** [comment]
<img width="796" alt="image" src="https://user-images.githubusercontent.com/13243/168177589-02b31505-c8df-4699-bd78-3fa4a7ab3fe8.png">

One interesting thing I notice is that you're making a lot of `accountSubscribe` subscriptions, one for every token in a long list of tokens. What's the idea behind this? I wonder if this high volume of subscriptions is related to your disconnects.

**Comment by awojciak** [comment]
> <img alt="image" width="796" src="https://user-images.githubusercontent.com/13243/168177589-02b31505-c8df-4699-bd78-3fa4a7ab3fe8.png">
> 
> One interesting thing I notice is that you're making a lot of `accountSubscribe` subscriptions, one for every token in a long list of tokens. What's the idea behind this? I wonder if this high volume of subscriptions is related to your disconnects.

I think these might be subscriptions for user tokens accounts, to fetch latest balances.

**Comment by steveluscher** [comment]
https://user-images.githubusercontent.com/13243/168186953-c5e70e92-c6b1-479d-b7ef-57ce198ee55e.mov

Interestingly, after these many `accountSubscribe` subscriptions are made, the sockets repeatedly close with error `1013 Try again later` (‘Temporary server condition forced blocking client's request’).

**Comment by steveluscher** [comment]
OK. I think I have a fix to make, but the larger curiosity is why the devnet socket server keeps closing the connection on you (with a 1013) error.

**Comment by steveluscher** [comment]
Try the latest version of web3.js @awojciak. I think your infinite recursion problem will be fixed, but the fact that devnet drops the socket on you with a 1013 is a separate problem, perhaps related to the sheer number of subscriptions that the app makes.

**Comment by awojciak** [comment]
@steveluscher App still freezes and there is a lot of these errors: 
![image](https://user-images.githubusercontent.com/48929607/168428847-1eef28fd-7563-476a-af9c-b95638ce49c4.png)
Code line indicated in error:
![image](https://user-images.githubusercontent.com/48929607/168428923-184ad121-40e7-4af9-9ef7-eb49dd575e06.png)
For me it seems like there is still some recursion retrying way too many times. Here you can check preview: https://github.com/invariant-labs/webapp/pull/312 - reproduction steps are the same as earlier. Anyway, thanks for your help.
