### ISSUE TITLE
Partial Sign Transaction jupiter api

### ISSUE THREAD

**Issue by Arshavir-Gharibyan** [solana-labs/solana#25137]
#### Problem
the following code stop working, giving me the error:  "Transaction mutated after being populated from Message"
version is 1.41.4, I also tried the other version

        const connection = new Connection("https://solana-api.projectserum.com");

        const transactions = await (
            await fetch('https://quote-api.jup.ag/v1/swap', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json'
                },
                body: JSON.stringify({
                    route: routes[0],
                    userPublicKey: walletSolana.publicKey.toString(),
                    wrapUnwrapSOL: true
                })
            })
        ).json()
    const { setupTransaction, swapTransaction, cleanupTransaction } = transactions
        // Execute the transactions
        for (let serializedTransaction of [setupTransaction, swapTransaction, cleanupTransaction].filter(Boolean)) {
            // get transaction object from serialized transaction
            const transaction = Transaction.from(Buffer.from(serializedTransaction, 'base64'))
            // perform the swap
            const txid = await connection.sendTransaction(transaction, [wallet.payer], {
                skipPreflight: true
            })
            await connection.confirmTransaction(txid)
            console.log(`https://solscan.io/tx/${txid}`)
        }

**Comment by jstarry** [comment]
> @jstarry can you also check this pls?

sure thing, I just opened a PR which I think should fix this. Thanks for the report!

**Comment by Arshavir-Gharibyan** [comment]
> > @jstarry can you also check this pls?
> 
> sure thing, I just opened a PR which I think should fix this. Thanks for the report!

can you also check this part?
Error: Transaction was not confirmed in 60.01 seconds. It is unknown if it succeeded or failed. Check signature

 if (response === null) {
      const duration = (Date.now() - start) / 1000;
      throw new Error(
        `Transaction was not confirmed in ${duration.toFixed(
          2,
        )} seconds. It is unknown if it succeeded or failed. Check signature ${signature} using the Solana Explorer or CLI tools.`,
      );
    }

**Comment by jstarry** [comment]
Please keep the issue focused
