### ISSUE TITLE
Ledger Nano S Plus support

### ISSUE THREAD

**Issue by silvesterdrago** [solana-labs/solana#25139]
#### Problem
I'm trying to use Solana CLI with my Ledger but Solana can't recognise it.

How to reproduce:
- Close Ledger Live
- Unlock device and run Solana app on it
- Run Solana-keygen

It works perfectly with Ledger Nano X
```
❯ solana-keygen pubkey usb://ledger
6Nwg...sHSo
```
But it can't find Ledger Nano S Plus
```
❯ solana-keygen pubkey usb://ledger
Error: no device found
```

Do you have any plans to support it?

**Comment by jstarry** [comment]
I don't believe this is within our control, cc @t-nelson to confirm

**Comment by t-nelson** [comment]
sounds like you need to update your udev rules to include the s+ usb vid/pid pair(s).  I have yet to obtain one of these devices though, so maybe more to it

**Comment by steviez** [comment]
Answered at:
https://solana.stackexchange.com/questions/207/error-no-device-found-when-using-ledger-nano-s-plus-with-solana-cli
