### ISSUE TITLE
v1.9.21 makes the accounts folder trigger the I/O at 100%

### ISSUE THREAD

**Issue by iammelea** [solana-labs/solana#25135]
this version makes the accounts folder trigger the I/O at 100%, it didn't happen in previous versions and it doesn't happen in +v1.10 either.
![Screenshot from 2022-05-11 13-11-56](https://user-images.githubusercontent.com/38863192/167874743-6e1917b6-a286-4cd9-9a99-51522c35a951.png)

here grafana charts before the upgrade and after

**Comment by jstarry** [comment]
@iammelea which version did you upgrade from? @CriesofCarrots maybe this is related to the tokio patch

**Comment by CriesofCarrots** [comment]
Perhaps. @iammelea , did you try v1.9.20? What v1.10 patch(es) have you tried?

**Comment by iammelea** [comment]
> @iammelea which version did you upgrade from? @CriesofCarrots maybe this is related to the tokio patch

from v1.19.18 to .21

**Comment by iammelea** [comment]
> Perhaps. @iammelea , did you try v1.9.20? What v1.10 patch(es) have you tried? Also, this is a non-RPC node, right?

no try v1.9.20, try v1.10.10 and v1.10.12 the v1.10 was oke

**Comment by jstarry** [comment]
@jeffwashington any ideas here? Do you think it could be from https://github.com/solana-labs/solana/pull/24948 which got released in 1.9.20?

**Comment by jeffwashington** [comment]
> @jeffwashington any ideas here? Do you think it could be from #24948 which got released in 1.9.20?

If the log contains "purge_slots_from_cache_and_store:" then this new code is running. The code is designed to do a post mortem after we have already mismatched. It will read all accounts from an append vec and log them. But that doesn't seem overly i/o. Do we know if the i/o is read/write or read? It seems unlikely this change is the cause.

**Comment by CriesofCarrots** [comment]
Fwiw, I'd be surprised if it's the tokio patch, since it doesn't do much on a non-rpc node (and nothing at all in accounts on such a node, that I'm aware of).

**Comment by yhchiang-sol** [comment]
I will take a stab to do the bisect between v1.9.18 and v1.9.21 to see whether I can get the repro.

@iammelea: when you started the validator with v1.9.21, can I know how long it takes to observe the abnormal I/O activities?  And you also mentioned that there's no repro on v1.10.10 and v1.10.12.  Am I right at this part?

**Comment by iammelea** [comment]
> I will take a stab to do the bisect between v1.9.18 and v1.9.21 to see whether I can get the repro.
> 
> @iammelea: when you started the validator with v1.9.21, can I know how long it takes to observe the abnormal I/O activities? 

_Not sure, I just realized when getting the alarm for unusual disk activity_

And you also mentioned that there's no repro on v1.10.10 and v1.10.12. Am I right at this part?

_yes you right_

**Comment by yhchiang-sol** [comment]
@iammelea: got it.  So in your first message where you created the issue, did the upgrade happen between 12:00 to 16:00 on May 10 as the disk and memory activities went higher?

**Comment by yhchiang-sol** [comment]
@iammelea: So I ran the validators with both v1.9.18 and v1.9.21, and I am both able and not able to reproduce the issue.

In summary, I am able to reproduce the increased disk activity on the account-db disk after upgrading from v1.9.18 to v1.9.21.  However, in my experiment, the disk activity does go down after ~25 minutes.  And here're the details  

First, I started the validator with v1.9.18, and things went normal as expected.  The account-db disk wrote 5.24MB/sec.
<img width="590" alt="Screen Shot 2022-05-12 at 5 45 46 PM" src="https://user-images.githubusercontent.com/93241502/168205929-83da72b0-facb-4912-a85e-ee8c67a8b5ad.png">

Then, I upgraded the validator to v1.9.21, and I did notice the increased activities on both ledger and account-db disks where the account-db disk wrote 11MB/sec, twice as many as it had in v1.9.18.

<img width="830" alt="Screen Shot 2022-05-12 at 6 15 34 PM" src="https://user-images.githubusercontent.com/93241502/168206181-b58c02d8-d06f-4991-bc6d-67096131deca.png">

However, after running longer, the disks activities started going down and eventually went normal
<img width="1025" alt="Screen Shot 2022-05-12 at 8 39 52 PM" src="https://user-images.githubusercontent.com/93241502/168206727-d37871c1-274a-4501-b5fc-39dc0732845a.png">

But in your data points, look like the disk activity never went down even after a day.  Given that there's also no repro on newer versions, @iammelea do you happen to remember whether there're anything different when you upgraded from v1.9.18 to v1.9.21?

**Comment by jstarry** [comment]
@yhchiang-sol nice investigation! Are you still trying to bisect to find where the doubling in IO was introduced? It would be really helpful to narrow that down still I think

**Comment by iammelea** [comment]
> @iammelea: So I ran the validators with both v1.9.18 and v1.9.21, and I am both able and not able to reproduce the issue.
> 
> In summary, I am able to reproduce the increased disk activity on the account-db disk after upgrading from v1.9.18 to v1.9.21. However, in my experiment, the disk activity does go down after ~25 minutes. And here're the details
> 
> First, I started the validator with v1.9.18, and things went normal as expected. The account-db disk wrote 5.24MB/sec. <img alt="Screen Shot 2022-05-12 at 5 45 46 PM" width="590" src="https://user-images.githubusercontent.com/93241502/168205929-83da72b0-facb-4912-a85e-ee8c67a8b5ad.png">
> 
> Then, I upgraded the validator to v1.9.21, and I did notice the increased activities on both ledger and account-db disks where the account-db disk wrote 11MB/sec, twice as many as it had in v1.9.18.
> 
> <img alt="Screen Shot 2022-05-12 at 6 15 34 PM" width="830" src="https://user-images.githubusercontent.com/93241502/168206181-b58c02d8-d06f-4991-bc6d-67096131deca.png">
> 
> However, after running around 25 minutes, the disks activities started going down and eventually went normal <img alt="Screen Shot 2022-05-12 at 8 47 56 PM" width="1015" src="https://user-images.githubusercontent.com/93241502/168207451-8b9465b7-cfac-4fd2-bb59-0a86b4ec5315.png">
> _How much stake does that validator have? where I have had the problem has around 1m of SOL stake_
> But in your data points, look like the disk activity never went down even after a day. Given that there's also no repro on newer versions, @iammelea do you happen to remember whether there're anything different when you upgraded from v1.9.18 to v1.9.21? 
_No, nothing_

**Comment by yhchiang-sol** [comment]
> How much stake does that validator have?

@iammelea: The validator I have is very low in stake as it's a validator only for developing / testing purposes.

> where I have had the problem has around 1m of SOL stake, I guess that validator where you run the test, is very low stake, also after one restart the high I/O around 25minutes is normal meanwhile the validator is starting, loading ledger and creating the accounts db.

@iammelea: do you happen to have multiple validators where only those with 1m or more SOL stake have issues with v1.9.21?

**Comment by yhchiang-sol** [comment]
Offline discussed with @jeffwashington.  The amount of stake should make no difference on the account db.

@iammelea: was the problematic validator happens to be the leader when you observed the spike?

> @yhchiang-sol nice investigation! Are you still trying to bisect to find where the doubling in IO was introduced? It would be really helpful to narrow that down still I think

@jstarry yep, I am still trying to get a stable repro.  Will probably continue by switching between v1.9.18 and v1.9.21 to see whether I can get any repro or any findings.

**Comment by iammelea** [comment]
> > How much stake does that validator have?
> 
> @iammelea: The validator I have is very low in stake as it's a validator only for developing / testing purposes.
> 
> > where I have had the problem has around 1m of SOL stake, I guess that validator where you run the test, is very low stake, also after one restart the high I/O around 25minutes is normal meanwhile the validator is starting, loading ledger and creating the accounts db.
> 
> @iammelea: do you happen to have multiple validators where only those with 1m or more SOL stake have issues with v1.9.21?
**operate few validators = yes
 install the same version in all the validators at the same time = NO. I test in one first, observe this behavior = of course no install in more validators or nodes.**

Offline discussed with @jeffwashington. The amount of stake probably make no difference on the account db.
**Probably wrong about that. from my experience make a lot difference run a validator with low stake and other with more or almost nothing.**

@iammelea: was the problematic validator happens to be the leader when you observed the spike?

**Not related**

**Comment by jstarry** [comment]
Stake probably matters for accountsdb usage because there's a lot of extra account loading that happens in banking stage when trying to select transactions to include in a block. Low staked validators don't produce many blocks so they only need to load accounts for transactions that are included.

**Comment by steviez** [comment]
@yhchiang-sol - One other thing you may want to double check is memory usage. Even if you don't have have a `tmpfs` setup for accountsdb, I've observed my GCE nodes (with plenty of RAM) mostly keep accountsdb in memory via the file cache. If one version is actively using more memory, there'd be less memory for file cache and potentially more IO.

> However, in my experiment, the disk activity does go down after ~25 minutes

The 25 minutes seems like it could correspond with time to catchup with cluster. In general, nodes have to "work harder" (more CPU / IO / memory) to catchup which makes sense since we're processing slots at a faster rate than steady state. It could be a good sanity check to ensure that your runs are getting snapshot of similar age. Similarly, it might be nice to note the time at which the node has caught up to the cluster so we can be sure we're comparing catchup-to-catchup and steady-to-steady IO rates between versions.

**Comment by yhchiang-sol** [comment]
> Stake probably matters for accountsdb usage because there's a lot of extra account loading that happens in banking stage when trying to select transactions to include in a block. Low staked validators don't produce many blocks so they only need to load accounts for transactions that are included.

Got it!  Thanks for the information.  I think that might explain the difference.

@jstarry:  If we want to cover such behavior, is there a way that we can create/simulate/mimic stakes or extra accounts to make the test validator have similar activities?

**Comment by yhchiang-sol** [comment]
I am still in the process of verifying the increased disk activities that I previously observed even without the stack and stack accounts since I have some samples showing that v1.9.19 might not have such increased disk activities.  Will keep you guys posted here once I have more data points.

As for testing with more stake accounts, I will try to see if this is something we can simulate in the test net.

**Comment by yhchiang-sol** [comment]
Here're some data points and current findings so far.

Each run begins with a clean start from v1.9.18.  Once it catches up with the leader's progress, I restart the validator instance using a newer version with `--no-snapshot-fetch`.  Below are some data points showing the disk activities on account-db where I mark the time period when I observe increased disk activities during the start time.  The graph shows that v1.9.21 has a longer time period of increased disk activities.  I've repeated the experiment several times and so far it's constantly reproducible.

If the experiments and the below data points are correct, then we might have a regression between v1.9.20 and v1.9.21.

<img width="1145" alt="Screen Shot 2022-05-17 at 9 31 26 AM" src="https://user-images.githubusercontent.com/93241502/168862345-b0289526-716d-4e2c-94a5-d784d338dddd.png">

I will continue testing with v1.9.20 and v1.9.21 and begin the bi-sect between v1.9.20 and v1.9.21.

**Comment by iammelea** [comment]
Issue closed meanwhile this version is deprecated
