### ISSUE TITLE
Feature Request: Relax `Sized` bound in `Transaction` APIs

### ISSUE THREAD

**Issue by Qwaz** [solana-labs/solana#25145]
#### Problem

Number of `Transaction` APIs (e.g., [`new()`](https://docs.rs/solana-sdk/1.10.13/solana_sdk/transaction/struct.Transaction.html#method.new)) require `T: Signers` bound. This definition implies that `T` should be `Sized`, preventing `&[&impl Signer]` type to be passed.

For instance, the following function does not compile due to this limitation (`self` is a wrapper around `ProgramTest`):
```rust
pub async fn instructions_to_tx(
    &self,
    instructions: &[Instruction],
    signers: &[&Keypair],
) -> Result<Transaction, BanksClientError> {
    let message = Message::new(instructions, Some(&self.payer().pubkey()));
    Ok(Transaction::new(
        signers,
        message,
        self.client().get_latest_blockhash().await?,
    ))
}
```

#### Proposed Solution

Makes them `T: Singers + ?Sized`.

**Comment by blackghost1987** [comment]
Yeah, this is a serious limitation! I'm not even sure why `Signers` is implemented on stuff like `Vec<Box<dyn Signer>>` and `[Box<dyn Signer>]` if you can't use it with trait objects anyway?

I'll probably open a PR with this change soon.
