### ISSUE TITLE
Parsing AccountInfo from onAccountChange

### ISSUE THREAD

**Issue by docongminh** [solana-labs/solana#25157]
#### Problem
Hi everyone,
I am using `onAccountChange` method to listen transaction in specify account. But data received in Buffer encode. And i dont know how to decode account data. Could anyone here support me ?
![Screen Shot 2022-05-12 at 15 48 52](https://user-images.githubusercontent.com/34453681/168031620-8a2b285f-daef-4491-8fcb-b5060608df00.png)

**Comment by jacobcreech** [comment]
We don't do technical support on Github. Please ask your question on [StackOverflow](https://stackoverflow.com/) with the `solana` tag and it can be answered there.
