### ISSUE TITLE
./node_modules/@solana/buffer-layout-utils/lib/esm/web3.mjs Can't import the named export 'PublicKey' from non EcmaScript module (only default export is available) 

### ISSUE THREAD

**Issue by zihangg** [solana-labs/solana#25197]
**Current Behavior**
AWS fails to build the website citing this error.

Did a fresh install locally to replicate the error. Seems like web3 forcing the installation of this module when it didn't previously.

**Expected Behavior**
Build successful without facing this issue.

**Steps to Reproduce**
npm install

**Web3.js Version**
1.7.0

**Environment**
Operating System: Windows
Browser: Brave/Chrome
Node.js Version: 16.4.0
NPM Version: 7.18.1
Anything Else?

**Comment by steveluscher** [comment]
Version 1.7.0 is rather old (current version is 1.41.8) and I believe from before a time that we fixed a lot of these ESModule-adjacent build errors. Are you able to upgrade web3.js to a newer version and try again?

**Comment by gabrielhicks** [comment]
I am also receiving this error on build

solana/web3.js v1.41.10

**Comment by steveluscher** [comment]
If you have a sample repository that exhibits this, or a small set of steps to reproduce, I’ll take a look and try to debug!

**Comment by barhouum7** [comment]
Same here, got the same issue today after adding React Moralis Provider

**Web3.js Version**

> 1.3.0

**Environment**

- Operating System: WSL
- Browser: Brave
- Node.js Version: v16.14.0
- NPM Version: 8.5.4

![image](https://user-images.githubusercontent.com/28789723/168448990-c25c2cec-2098-4572-a998-338397799c9e.png)

**Comment by steveluscher** [comment]
Can you folks send me a link to a GitHub repository that I can clone, run, and reproduce the problem?

**Comment by gabrielhicks** [comment]
> Can you folks send me a link to a GitHub repository that I can clone, run, and reproduce the problem?

Step 1: Clone `https://github.com/exiled-apes/candy-machine-mint`

Step 2: Delete `yarn.lock`

Step 3: Run `yarn install`

Step 4: Run `yarn build`

I used these steps and was able to replicate, see this repo: `https://github.com/gabrielhicks/cm-test-repo`

**Comment by michalko** [comment]
I have same problem, updated to newest libs and it happened:

    "@solana/spl-token": "^0.1.8",
    "@solana/spl-token-registry": "^0.2.268",
    "@solana/wallet-adapter-base": "^0.6.0",
    "@solana/wallet-adapter-react": "^0.12.0",
    "@solana/wallet-adapter-react-ui": "^0.4.1",
    "@solana/wallet-adapter-wallets": "^0.10.0",
    "@solana/web3.js": "^1.42.0",

after npm start:
```
Failed to compile.

./node_modules/@solana/buffer-layout-utils/lib/esm/web3.mjs
Can't import the named export 'PublicKey' from non EcmaScript module (only default export is available)
```

**Comment by michalko** [comment]
This issue is since https://github.com/solana-labs/solana-web3.js/commit/980f460e0e22dd8f82d25e067da9d636c2841d08

**Comment by michalko** [comment]
This fix it for me https://github.com/solana-labs/wallet-adapter/issues/265#issuecomment-1025285873

**Comment by steveluscher** [comment]
@michalko nailed it. We simply have moved on to ESModules, and Create React App version 4 is no longer supported out-of-the-box. The solution is to follow the steps in https://github.com/solana-labs/wallet-adapter/issues/265#issuecomment-1025285873.

**Comment by gabrielhicks** [comment]
Ahh Ive been using this off and on and it didnt even occur to me since its usually a different package. Thanks!

**Comment by barhouum7** [comment]
> @michalko nailed it. We simply have moved on to ESModules, and Create React App version 4 is no longer supported out-of-the-box. The solution is to follow the steps in [solana-labs/wallet-adapter#265 (comment)](https://github.com/solana-labs/wallet-adapter/issues/265#issuecomment-1025285873).

I'm trying to follow the steps in [solana-labs/wallet-adapter#265 (comment)](https://github.com/solana-labs/wallet-adapter/issues/265#issuecomment-1025285873), but I'm getting the below error when running this command `sed -i '' 's/react-scripts /react-app-rewired /g' package.json`

> sed: can't read s/react-scripts /react-app-rewired /g: No such file or directory

**Comment by barhouum7** [comment]
> @barhouum7 just open `package.json` and manually replace `react-scripts` with `react-app-rewired` everywhere that it appears.

Thanks for the reply, even in the dependencies, should I change the dependency name of react-scripts? or just change it in my scripts?

**Comment by steveluscher** [comment]
I don't remember, but they have you covered with setup instructions! https://github.com/timarney/react-app-rewired

**Comment by barhouum7** [comment]
Followed your solution mentioned here https://github.com/solana-labs/wallet-adapter/issues/265#issuecomment-1025285873, and it helped me to fix this issue. Thanks!
But still compiling with warnings

![image](https://user-images.githubusercontent.com/28789723/169168363-3816d28a-1508-4ec1-bcf6-05c2406079e5.png)

**Comment by steveluscher** [comment]
At this point, it's time to take the questions to Discord where your problem can get more eyes on it! https://discord.gg/cVjnnQVg

**Comment by Arabellanft** [comment]
./node_modules/@liqnft/candy-shop-sdk/node_modules/@solana/spl-token/lib/esm/actions/createMint.mjs
Can't import the named export 'Keypair' from non EcmaScript module (only default export is available) facing this error 
please help
