### ISSUE TITLE
Block gaps in ledger

### ISSUE THREAD

**Issue by avolkov-dev** [solana-labs/solana#25191]
#### Problem
On testnet we observed weird behaviour - block gaps in ledger.
For instance now it is possible to retrieve block 1324316**56** and 1324316**58**, but block 1324316**57** is missed.
```

curl --location --request POST 'https://api.testnet.solana.com' \
--header 'Content-Type: application/json' \
--data-raw '{"jsonrpc":"2.0","id":1, "method":"getBlock", "params": [132431657]}'

```
responds with:
```
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32007,
        "message": "Slot 132431657 was skipped, or missing due to ledger jump to recent snapshot"
    },
    "id": 1
}
```
On our own node we observe the same gap. What causes it? Is this block really exist? Is it possible to configure node to avoid such gaps?

**Comment by steviez** [comment]
There was no block in `132431657`; note `132431658`'s parent is `132431656` as shown below:
https://explorer.solana.com/block/132431658?cluster=testnet

As the message alluded to, the slot was [skipped](https://docs.solana.com/terminology#skipped-slot). This could happen for several reasons and is normal operation. Given that this isn't a bug, I'm going to close this issue and encourage you to checkout our [Discord](https://discord.com/invite/solana) as a better place to ask questions / get support / etc.
