### ISSUE TITLE
Remove support of RequestUnitsDeprecated::additional_fee when prioritization_fee_type_change feature is activated

### ISSUE THREAD

**Issue by taozhu-chicago** [solana-labs/solana#25201]
#### Problem

Concern raised [here](https://github.com/solana-labs/solana/pull/25178#pullrequestreview-971781478).

#### Proposed Solution
remove support of `RequestUnitsDeprecated::additional_fee` when feature `prioritization_fee_type_change` is activated

**Comment by jstarry** [comment]
The concern I raised in https://github.com/solana-labs/solana/pull/25178 has been resolved for now, but I think we should still eventually deprecate this instruction

**Comment by taozhu-chicago** [comment]
feature gate to remove deprecated ix has been scheduled and is pending. Close this Issue, tracing removal at https://github.com/solana-labs/solana/issues/27500
