### ISSUE TITLE
Validator reports incorrect version in gossip

### ISSUE THREAD

**Issue by bartenbach** [solana-labs/solana#25217]
#### Problem
When querying local RPC, validator reports correct version:
```json
{
  "jsonrpc": "2.0",
  "result": {
    "feature-set": 2945818700,
    "solana-core": "1.9.21"
  },
  "id": 1
}
```
Command line reports correct version:

```
% solana --version
solana-cli 1.9.21 (src:5b413da9; feat:2945818700)
```

Validator startup log confirms correct version is being used:
```
[2022-05-11T23:57:48.818803608Z INFO  solana_validator] solana-validator 1.9.21 (src:5b413da9; feat:2945818700)
```

However gossip continues to show 1.9.18 even after multiple software upgrades and validator restarts.

#### Proposed Solution
No known solution. Simply logging the issue in case anyone else experiences this.

**Comment by mvines** [comment]
Fixed by https://github.com/solana-labs/solana/pull/23924 and is in v1.10 or greater (ie, not in v1.9)
