### ISSUE TITLE
cargo-build-bpf fails on ubuntu

### ISSUE THREAD

**Issue by giorgiocc** [solana-labs/solana#25223]
#### Problem
```
rustc --version = rustc 1.60.0 (7737e0b5c 2022-04-04)

solana --version = solana-cli 1.10.8 (src:623ac656; feat:1122441720)

npm --version = 8.5.1

node --version = v12.22.9

```
os: ubuntu 22.04 lts

after i run: "[npm run build:program-rust](https://github.com/solana-labs/example-helloworld)" i am getting this error.

`/home/[user]/.rustup/toolchains/bpf/bin/cargo: error while loading shared libraries:libssl.so.1.1: cannot open shared object file: No such file or directory`

#### Proposed Solution
same problem with anchor.
![OoTZT](https://user-images.githubusercontent.com/56062823/168440799-d12dff61-e069-4ecd-9887-3665c70a6ae2.png)
i found this libssl location will it help me?
![490Gz](https://user-images.githubusercontent.com/56062823/168440801-6a2795f9-8f1d-4673-a622-5a2f94eca833.png)

**Comment by monomadic** [comment]
you need to install libssl-dev

**Comment by giorgiocc** [comment]
> you need to install libssl-dev

i have installed. and?

**Comment by FlorianMilcendeau** [comment]
if you have a solution, I am interested 🙂 because I have the same error.

**Comment by giorgiocc** [comment]
> if you have a solution, I am interested 🙂 because I have the same error.

I think the cargo wasn't on a standard path. and fixed everything by reinstalling Linux. I had it just for testing. actually moved to Debian -> reinstalled packages and everything working properly now.

**Comment by ItsAditya-xyz** [comment]
"reinstalled linux" oh wow, that's such a easy way lmaoo.

so no solution other than it?
