### ISSUE TITLE
Feature Gate: Enable `BpfUpgradeableLoader::UpgradeAndResize` instruction

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#25234]
### Description

Now that the realloc feature is activated on all clusters, the `BpfUpgradeableLoader` should provide a way for users to reallocate deployed programs when upgrading their programs. It also removes the need for pre-allocating 2x large accounts to plan for future upgrades.

### Feature ID

8Zs9W7D9MpSEtUWSQdGniZk2cNmV22y6FLJwCx53asme

### Activation Method

Single Core Contributor

**Comment by vpontis** [comment]
@jstarry this is very cool. Is this something that is definitely going to happen? And will it have a maximum size?

I'm curious since we are deploying some programs and it would be nice not to pay a bunch to allocate space for the future. :)

**Comment by vpontis** [comment]
Thanks @jstarry I agree that it would be super useful! But for now, I'll deploy programs w/ the assumption that they won't be able to be resized 👍.

**Comment by mgild** [comment]
Very excited for this feature :)

**Comment by jstarry** [comment]
Closing in favor of https://github.com/solana-labs/solana/issues/26385
