### ISSUE TITLE
Block and slot definitions are confusing in the context of EntryTree and LockTower

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#2524]
#### Problem

```
block

A contiguous set of entries on the ledger covered by a vote. The duration of a block is some cluster-configured number of ticks. Also called voting period.
```
This is confusing because a leader transmits some variable number of ticks to connect to a previous block, and a fixed number of ticks and entries that are voted on.

```
slot

The time (i.e. number of blocks) for which a leader ingests transactions and produces entries.
```
Does this mean the number of blocks that the leader is consecutively scheduled for?  Or the number of blocks the leader generated to connect to its scheduled voting period?  

The number of consecutive blocks a leader is scheduled for is not significant and shouldn't have a definition.

#### Proposed Solution
```
block

A contiguous set of entries and ticks on the ledger covered by a vote. A block is produced by a single leader.  The last tick is the block id.  The leaders slot is a fixed number of ticks at the end of the block, spanning any entries containing data produced by the leader. The starting ticks, if any, connect this block to a previous block.
```

```
slot

The range of time time in ticks for which a leader is scheduled to ingest transactions and produce entries.
```

tag: @garious @rob-solana

**Comment by rob-solana** [comment]
I think it might be useful to have some word for the consecutive slots, but this works fine.

**Comment by rob-solana** [comment]
so: a block would include any virtual ticks required to chain to the previous slot

**Comment by garious** [comment]
@rob-solana, a set of consecutive slots derived from a single *active set* is called an *epoch*.

**Comment by garious** [comment]
@aeyakovenko, 

> A contiguous set of entries and ticks on the ledger covered by a vote. A block is produced by a single leader.  

cool

> The last tick is the block id.

"The last tick's id is the block id."

> The leaders slot is the last set of entries and ticks in the block.

Probably shouldn't mention "slot" in the definition of "block". You don't describe atoms in terms of molecules.

**Comment by aeyakovenko** [comment]
@garious but slot is not defined in terms of blocks

**Comment by garious** [comment]
Its duration is defined as a number of blocks.

**Comment by aeyakovenko** [comment]
@garious, the proposal defines a slot in terms of ticks

**Comment by rob-solana** [comment]
a slot's duration is exactly one block under Anatoly's proposal

**Comment by rob-solana** [comment]
@garious I meant "consecutive slots by the same leader"

**Comment by garious** [comment]
No, we can't have one block per slot. The block duration is about minimizing confirmation time. The slot duration is about decentralization at the expense of TPS. We need to make that slot length as long as possible.

**Comment by aeyakovenko** [comment]
@garious this is a proposal to change the definition of a slot. Because scheduling a leader for consecutive periods of time is not significant enough to warrant its own name.
