### ISSUE TITLE
replay of blockstore could continue on once transactions come out of the pipeline

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#25268]
#### Problem

If we have transactions which take different amounts of time, then the longer transactions will stall the pipeline.

#### Proposed Solution

If we can now detect when the transaction exits the pipeline we can see if we can start to lock the next entry and start to replay it while the longer transaction is still in the pipeline.

**Comment by jstarry** [comment]
First and foremost, I think there is a lower hanging fruit. As we know, transactions within one entry can be processed in parallel but the validator doesn't process intra-entry transactions in parallel yet. I think that should be the first thing that is addressed.

As for your stated problems..
1. Yes, it seems safe to me to unlock accounts for individual transactions after they are committed. Currently we always commit the full batch of transactions together, but I don't see any reason we can't commit transactions eagerly to unblock transactions in other batches.

2. Agreed with your assessment. However, I think we can go a step further and start processing any transaction in the next entry which can be locked, we don't need need to wait for the full entry to be lockable.

3. Yes, I think we can probably remove the concept of batches altogether in replay stage and operate over transactions.
