### ISSUE TITLE
Fee is not collected on transactions that fail with a ProgramError

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#2526]
While we write transactions that fail with a ProgramError to the ledger, it appears that we don't actually collect the fee for such a transaction.   As the return is not `Ok()` from such transactions, the bank doesn't store the accounts.  This is correct but the fee is collected in the `Ok()` case as a side-effect of storing, so on a ProgramError we need to do a little additional work to still debt the fee.

**Comment by mvines** [comment]
(@pgarg66 assigning this to you based on our discussion earlier today)

**Comment by garious** [comment]
Two parts to this. The TPU should credit itself. The TVU should credit the pubkey that signed the blob containing the transaction.
