### ISSUE TITLE
Apply cost model before adding transactions to banking_stage unprocessed_packet_batches buffer

### ISSUE THREAD

**Issue by taozhu-chicago** [solana-labs/solana#25270]
#### Problem

Transactions that will eventually _not_ pass cost model (eg exceed account limit, or block limit) therefore _not_ land in block can clog banking_stage buffer, reduce leader throughput. 

Example: 
Say there are writeable account `A`, `B` and `C`. `An` represents transaction wants to write to `A`.

Assume inbound 8 transactions are: `A1, A2, A3, A4, A5, B1, C1, B2`, buffer limit is 5, priority order is An > Bn > Cn.

With current prioritized buffer, after receiving above inbound transaction, the buffer contains `A1, A2, A3, A4, A5`, transactions write to `B` and `C` not make into buffer because their priority is lower than transactions want to write to `A` (scenario when bots bump up fee for NFT or IDO events). 

This buffer is poor in parallelism. Further assume leader has 2 slots, and single `A` transaction will hit account limit; The leader therefore would generate bock 1 contains only `A1`, block 2 contains only `A2`, `A3, A4, A5` may be forwarded. 

If cost model is applied to transactions before being inserted into buffer, then instead of `A3, A4, A5`, `B1, B2, C1` would be added into buffer and made into block: the buffer would be `A1, A2, B1, B2, C1` in order of priority, blocks could be `A1, B1, C1` and `A2, B2` with no forwarding. Much higher block density in this case.

#### Proposed Solution

- initiate `unprocessed_packet_batches` with `n` number of `cost_tracker`s, maybe 4, or 8, as part of `UnprocessedPacketBatches`, like this: 
```
#[derive(Default)]
pub struct UnprocessedPacketBatches {
    pub packet_priority_queue: MinMaxHeap<Rc<ImmutableDeserializedPacket>>,
    pub message_hash_to_transaction: HashMap<Hash, DeserializedPacket>,
    pub cost_trackers: Vec<CostTracker>, // <<--
    batch_limit: usize,
}
```
- upon receiving transaction during [`DeserializedPacket::new_internal`](https://github.com/solana-labs/solana/blob/master/core/src/unprocessed_packet_batches.rs#L90-L116) , using its estimated or user requested compute units check if it would fit into `n` cost_tracker limit, which checks both account and block limits, plus some other (eg account data size). If not, drop the packet by returning `DeserializedPacketError::ExceedCostLimit`;
- otherwise [`insert_batch`](https://github.com/solana-labs/solana/blob/master/core/src/unprocessed_packet_batches.rs#L198) will inserted in into prioritized buffer, and add its cost to the first `cost_tracker` that has room for it. Should a packet being pushed out due to inserting new packet, the `cost_tracker`s will be updated with its cost by called `update_cost(&tx)` similar to [this](https://github.com/solana-labs/solana/blob/master/core/src/unprocessed_packet_batches.rs#L198).
- ~during packet consuming, for successfully processed packet, or failed but not retryable, remove its cost from `cost_tracker`s in similar fashion as above step~. Consumed and non-retryable packets should have their compute units taken from `cost_trackers`

This essentially moves logic of "forwards packets by account buckets" to front of buffering. So when it comes to forwarding, leader probably can simple forward whatever left in buffer. 

wdyt @sakridge @carllin @aeyakovenko

**Comment by nikhayes** [comment]
>"using its estimated or user requested compute units check if it would fit into n cost_tracker limit"

I think Starry was thinking that RPCs would probably want to add a buffer amount to the requested compute so that the simulated compute doesn't end up being too little, which would cause transactions to fail prematurely. The added buffer to the requested compute could be rebated back to the users (https://github.com/solana-labs/solana/pull/25178#issuecomment-1126864337). Given this, it probably wouldn't be safe to use the requested compute units for any of the estimations? There would be no penalty afaik if someone set the requested compute very high, which would result in block underpacking?

**Comment by taozhu-chicago** [comment]
> > "using its estimated or user requested compute units check if it would fit into n cost_tracker limit"
> 
> I think Starry was thinking that RPCs would probably want to add a buffer amount to the requested compute so that the simulated compute doesn't end up being too little, which would cause transactions to fail prematurely. The added buffer to the requested compute could be rebated back to the users ([#25178 (comment)](https://github.com/solana-labs/solana/pull/25178#issuecomment-1126864337)). Given this, maybe it wouldn't be optimal to use the requested compute units for any of the cost_tracker associated calculations?

Yeah, I was preparing to have a separate discussion for estimated vs user-request compute units.

Estimated compute units based on historical data points, per program_id, has its issue with accuracy, also, perhaps more importantly, has very little predicting power. Estimated cost can be made stable when aggregated, but can be very inaccurate in individual cases. https://github.com/solana-labs/solana/pull/23948 uses EMA, maybe that provide some stability, but they often over estimated transactions. 

On the other hand, one would expect users have incentives to provide most accurate value in requested-units since the fee is directly based on it. While it might be true for most responsible users, we can't currently stop bad actors to set requested-units to max to intentionally slow down TPS. Using user requested units solely makes system vulnerable from such attack, plus it also requires most, if not all, user to adapt and use compute_budget IX.

**Comment by apfitzge** [comment]
This makes sense to be included in the centralized scheduler: https://github.com/orgs/solana-labs/projects/8
