### ISSUE TITLE
ws rpc report 'Method not found' error

### ISSUE THREAD

**Issue by wetezos** [solana-labs/solana#25273]
#### Problem

When i access the api via http, it's ok, but ws report Method not found, how can i slove this error?

` wscat -c ws://142.x.x.x:8900
connected (press CTRL+C to quit)
> {"jsonrpc":"2.0","id":1, "method":"getEpochInfo"}
  < {"jsonrpc":"2.0","error":{"code":-32601,"message":"Method not found"},"id":1}`

My command:
`
solana-validator \
    --identity ~/validator-keypair.json \
    --entrypoint entrypoint.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint2.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint3.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint4.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint5.mainnet-beta.solana.com:8001 \
    --ledger ~/validator-ledger \
  --gossip-port 8001 \
  --rpc-port 8899 \
  --rpc-bind-address 142.x.x.x \
  --dynamic-port-range 8002-8020 \
  --wal-recovery-mode skip_any_corrupted_record \
  --limit-ledger-size  \
  --private-rpc \
  --no-voting --no-snapshot-fetch\
  --full-rpc-api \
  --enable-rpc-transaction-history \
  --account-index program-id spl-token-owner spl-token-mint \
  --expected-genesis-hash 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d \
  --account-index-exclude-key kinXdEcpDQeHPEuQnqmUgtYykqKGVFq6CeVX5iAHJq6 \
  --account-index-exclude-key TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA \
  --known-validator 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2 \
  --known-validator GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ \
  --known-validator DE1bawNcRJB9rVm3buyMVfr8mBEoyyu73NBovf2oXJsJ \
  --known-validator Cu9Ls6dsTL6cxFHZdStHwVSh1uy2ynXz8qPJMS5FRq86 \
    --known-validator CMPSSdrTnRQBiBGTyFpdCc3VMNuLWYWaSkE8Zh5z6gbd \
    --known-validator GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ \
    --known-validator 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2 \
    --known-validator FSVdqBzx5D4UsqBLnvmH5dFx2dCm1pTPAbQWJ1PYzTJ2 \
    --known-validator FLVgaCPvSGFguumN9ao188izB4K4rxSWzkHneQMtkwQJ \
  --known-validator CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S
`

**Comment by t-nelson** [comment]
the ws endpoint only exposes the notification subscription endpoints
