### ISSUE TITLE
Consider queueing transactions that fail due to AccountInUse

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#2527]
Currently we reject new transactions who's accounts conflict with in-flight transactions with an AccountInUse error.  This error occurs very early on in transaction processing, looks like even before we check if the new, conflicting, transaction is well formed: valid signature, valid fee, etc.

If the conflicting transaction is in fact well formed, the node could instead collect the fee for the transaction and queue it instead of rejecting with AccountInUse.  This would significantly simplify loader programs notably.

**Comment by garious** [comment]
I like the idea of getting rid of the AccountInUse error. The transaction can stay queued until it finds an Entry to jump into or is rejected with a `TransactionError::BlockhashNotFound`.
