### ISSUE TITLE
`getBlock` responds with `Transaction version (0) is not supported`

### ISSUE THREAD

**Issue by avolkov-dev** [solana-labs/solana#25287]
Requests
```
curl --location --request POST 'https://api.testnet.solana.com' \
--header 'Content-Type: application/json' \
--data-raw '{"jsonrpc":"2.0","id":1, "method":"getBlock", "params": [132937946]}'
```
fails with:
```

{
    "jsonrpc": "2.0",
    "error": {
        "code": -32015,
        "message": "Transaction version (0) is not supported"
    },
    "id": 1
}
```

Any idea what is wrong?

**Comment by avolkov-dev** [comment]
The explorer experiencing the same issue
https://explorer.solana.com/block/132937946?cluster=testnet
![image](https://user-images.githubusercontent.com/57129370/168796415-3ba81810-6fbf-4012-bee0-e0d1a3f49831.png)

**Comment by yakud** [comment]
Same for our self hosted node
solana-validator 1.10.13

**Comment by CriesofCarrots** [comment]
This block must contain a new v0 Transaction. As per [the jsonrpc docs](https://docs.solana.com/developing/clients/jsonrpc-api#getblock), try adding the `maxSupportedTransactionVersion` config parameter. Eg:
```
curl --location --request POST 'https://api.testnet.solana.com' \
--header 'Content-Type: application/json' \
--data-raw '{"jsonrpc":"2.0","id":1, "method":"getBlock", "params": [132937946,{"maxSupportedTransactionVersion":0}]}'
```

@jstarry , seems like we need some comms around this ^

**Comment by nixxholas** [comment]
Can we close this? It's done!

**Comment by jstarry** [comment]
Closed by https://github.com/solana-labs/solana/pull/28249
