### ISSUE TITLE
web3.js: Implement a nonce-based transaction confirmation strategy

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana#25303]
#### Problem

We have no strategy for confirming nonce-based transactions other than ‘wait 60 seconds.’ In fact, nonce-based transactions expire either:

1. If the blockhash that the transaction was signed with is not the same as the blockhash in the nonce account from the get-go, or
2. If the nonce is ‘advanced’ before the transaction is confirmed.

#### Proposed Solution

1. Follow the pattern established by `BlockheightBasedTransactionConfimationStrategy`; create a `NonceBasedTransactionConfimationStrategy`
2. Create a `TransactionExpiredNonceAdvancedError`
3. Augment `new Transaction` to take nonce-based constructor args.
4. Augment `confirmTransaction()` to accept `NonceBasedTransactionConfimationStrategy`
5. Write expiry logic that polls the nonce account, watching for a mismatch between the blockhash that the transaction was signed with, and the blockhash in the nonce account. Throw a `TransactionExpiredNonceAdvancedError` when this happens.

**Comment by marcnjaramillo** [comment]
I'm trying to wrap up some other things, but I'm happy to continue working on this later this week.
