### ISSUE TITLE
status.solana.com displays a negative TPS

### ISSUE THREAD

**Issue by ruuda** [solana-labs/solana#25327]
#### Problem

From https://status.solana.com/#week:

![2022-05-18-solana-negative-tps](https://user-images.githubusercontent.com/506953/169072697-41c701a8-8946-49e4-b7c2-398c0a519149.png)

The transactions per second should not drop below zero.

#### Proposed Solution

I don’t know where this data comes from, I don’t know how to fix it.

**Comment by axleiro** [comment]
We have remove those metrics from Status Page for now.
