### ISSUE TITLE
Tokio Version In v1.10 Branch Should Update To Latest Available Version

### ISSUE THREAD

**Issue by bonedaddy** [solana-labs/solana#25350]
#### Problem

Tokio version used by the releases in the `1.10.x` category  seem to be `1.14.2`. There have been 2 major tokio releases since then which added a number of big fixes, optimizations, etc.. that will be very useful to have for backend services importing the 1.10 solana releases.

#### Proposed Solution

* Update tokio to 1.18.2
* Enable the `rt-multi-threaded` runtime

**Comment by CriesofCarrots** [comment]
Please see this issue and comment: https://github.com/solana-labs/solana/issues/24644#issuecomment-1120004999
We'll be keeping tokio pinned until we can find a fix either in our code or upstream.
