### ISSUE TITLE
GetBlock(latest slot) ocasionally returns -32004 if called immediatly after getSlot()

### ISSUE THREAD

**Issue by chandraprakash** [solana-labs/solana#25398]
#### Problem
Env: testnet version 1.10.11; No voting validator testnet node
Commitment finalized for all the rpc calls.

`GetBlock(latest slot)` occasionally returns -32004 if called immediately after `getSlot()`.
On retrying after a second, it is available. 

Error : "Block not available for slot 133354927"

My understanding is that, getSlot gets the latest Block/Slot available at node. So in order to obtain latest Slot number and its Block, I am doing following.
latest slot number = `GetSlot()` params:  `[{"commitment": "finalized"}]`

latest block = `GetBlock(latest slot number)` params : `{"encoding": "base64", "transactionDetails": "none", "rewards": False,                                  "commitment": "finalized"}`

**Note**: If this is expected behavior, please provide a way to get the latest block available on Node.

**Comment by jstarry** [comment]
It's possible that after getting the latest finalized slot from one node, you then send a `GetBlock` request to another node which hasn't finalized that slot yet. So you can try again to get the block.

**Comment by chandraprakash** [comment]
Thanks for 

> 



> It's possible that after getting the latest finalized slot from one node, you then send a `GetBlock` request to another node which hasn't finalized that slot yet. So you can try again to get the block.

Thanks for your response. 
I am sending all the rpcs to just one node which I am running in no-vote mode.

**Comment by jstarry** [comment]
I see, sometimes the metadata for transactions isn't quite ready yet even after a slot is finalized. I think this is probably the issue you are hitting. @CriesofCarrots what do you think about adding a call to `check_status_is_complete` to ensure consistent responses and avoid the above behavior?

**Comment by CriesofCarrots** [comment]
> what do you think about adding a call to `check_status_is_complete` to ensure consistent responses and avoid the above behavior?

@jstarry , do you mean adding that check to getSlot? Or all the calls that support processed commitment?

**Comment by jstarry** [comment]
Hmm maybe all, but was specifically thinking `getSlot`

**Comment by chandraprakash** [comment]
Thanks a lot for looking into this issue.
Any idea on when are you planning to put a fix for this please?

**Comment by jstarry** [comment]
@chandraprakash it probably won't be for awhile, for now you can retry when you get this error
