### ISSUE TITLE
Most builtin programs do not consume compute units

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#25401]
#### Problem
BPF programs use a compute meter while processing instructions but builtin native programs don't so they do not consume any compute units for processing instructions.

#### Proposed Solution
Consume a reasonable amount of compute units for each builtin program instruction

tag @jackcmay @taozhu-chicago

**Comment by taozhu-chicago** [comment]
cost_model counts native program costs separately from BPF programs. It gives static CUs to some native programs, defined at [here](https://github.com/taozhu-chicago/solana/blob/forwarder_with_bucket_prioritization/runtime/src/block_cost_limits.rs#L31-L43).

If native programs will consume similar CUs, then cost_model can be simplified as it no longer need to distinguish native programs from BPF.
