### ISSUE TITLE
Comparison of a Result instead of usize

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#25416]
#### Problem

The is_duplicate function checks for duplicate accounts by comparing the indexes
returned by the get_index_in_transaction function implemented for the
InstructionContext struct. However, the return type of get_index_in_transaction
is Result<usize, InstructionError>, and the result is not unwrapped before the
comparison operation. This has the effect that two Results are compared instead of the
index contained in the Result.

```rust
/// Look for a duplicate account and return its position if found
pub fn is_duplicate(
   instruction_context: &InstructionContext,
   index_in_instruction: usize,
) -> Option<usize> {
   let index_in_transaction =
   instruction_context.get_index_in_transaction(index_in_instruction);
   (instruction_context.get_number_of_program_accounts()..index_in_instruction).position(
      |index_in_instruction| {
      instruction_context.get_index_in_transaction(index_in_instruction)
         == index_in_transaction
      },
   )
}
```

**Comment by Lichtso** [comment]
I was thinking about refactoring the deduplication logic anyway, as it is recalculated in many places and only needs to be done once. Potentially just storing a reference index in each instruction account to the first occurrence (pointing to itself if it is the first).
