### ISSUE TITLE
JIT cache could exist on disk to store more programs

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#25420]
#### Problem

JIT compilation is relatively expensive and we can only hold a limited number in memory.

#### Proposed Solution

To save memory and be able to store more programs, the JIT result could be written to disk.

**Comment by bji** [comment]
In addition this would enable a compute unit fee for JIT.  Right now you can fairly easily crush a leader by:

- Uploading a bunch of programs
- Waiting until they're all uploaded
- Submit a bunch of tx all at once that hit those programs

The JIT operation which must be immediately performed for all those transactions ends up hosing the block.  I've seen this happen on testnet when I did it with 10 programs all at once.

If the JIT operation is performed at the same time by all validators, during the transaction that completes the upload, then it can be charged a CU fee in that transaction, which would then bound the number of JIT operations that could be done in a block (thus preventing the block from being hosed by a bunch of not-paid-for JIT costs).  The JIT'd version would be written to disk and all subsequent transactions which use that program would just load the JIT'd version directly.

**Comment by steviez** [comment]
We did a bit of a deep dive on a specific slot that occurred during some congestion / high forking period, slot 134163979.

On our one node that would report per program times, we observed a disproportionate execution time in relation to compute units for `ZETAxsqBRek56DhiGXrn75yj2NHU3aYUnxvHXpkf3aD`. Our node spent `582564 us == 582 ms` on `728926 CUs`. Query below:
```
SELECT "slot", "errored_units", "execute_us", "accumulated_units", "count", "errored_count", "pubkey", "host_id" FROM "mainnet-beta"."autogen"."per_program_timings" WHERE time > :dashboardTime: AND time < :upperDashboardTime: AND "slot" = 134163979 AND "pubkey" <> 'all'. Query below:
```
Upon further inspection, this node spent `553614 us == 553 ms` in the area captured by `execute_details_create_executor_jit_compile_us`. This is NOT per program, but still shows 550 ms of time spent.
```
SELECT "execute_details_create_executor_jit_compile_us" FROM "mainnet-beta"."autogen"."replay-slot-stats" WHERE time > :dashboardTime: AND time < :upperDashboardTime: AND "slot" = 134163979 AND "host_id" = '7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2'
```

We replayed this slot on a local ledger, and observed much more normal times (55 ms):
```
ProgramTiming {
	accumulated_us: 54875,
	accumulated_units: 728926,
	count: 12,
	errored_txs_compute_consumed: [50778, 23331, 23489, 23489, 23331, 23489, 23331, 23489, 23331, 23489],
	total_errored_units: 261547
},
```
This datapoint supports the JIT compilation really hurting us.
