### ISSUE TITLE
Sending vote transactions is unnecessarily complex

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#2545]
#### Problem

Sending vote transactions is unnecessarily complex. VoteSignerProxy currently queries ClusterInfo for the TPU address, wraps the transaction as a blob, sends the blob to a channel. On the other side of that channel is a `responder`, which then unwraps the blob to get that TPU address, and sends it via a UDP socket.  If the sending thread did the TPU query, there'd be no use for the blob type.

#### Proposed Solution A

Instead of sending a blob to a channel, do an async send of the serialized transaction to the UDP socket. Instead of sending it to the real TPU, send it to the TPU port on localhost and let the TPU Forwarder query ClusterInfo and send it.

#### Proposed Solution B

Instead of sending a blob, send the transaction.  Instead of using a `responder`, send it to the same channel the TPU's FetchStage sends transactions. Like the first proposal, let the channel endpoint forward those transactions as needed.

#### Proposed Solution C

Instead of sending the vote to the TPU, send it to ClusterInfo #2562

**Comment by aeyakovenko** [comment]
see #2562
