### ISSUE TITLE
Add way from CLI to find all the stake accounts for a given withdraw authority

### ISSUE THREAD

**Issue by brooksprumo** [solana-labs/solana#25462]
#### Problem

There is not a way from the CLI (that I know of) to find all the stake accounts for a given withdraw authority. Both [Step Finance](https://app.step.finance/) and [Sonar Watch](https://sonar.watch/) support this query, and the CLI should be able to as well.

#### Proposed Solution

From @mvines

> `solana stakes` _could_ easily do this too. Here’s the gist of a patch to do so, sans the necessary plumbing to surface a new cli option to the user:
> 
> ```diff
> diff --git a/cli/src/cluster_query.rs b/cli/src/cluster_query.rs
> index f39b64cde0..02004fb590 100644
> --- a/cli/src/cluster_query.rs
> +++ b/cli/src/cluster_query.rs
> @@ -1753,9 +1753,9 @@ pub fn process_show_stakes(
>                      ),
>                      encoding: Some(rpc_filter::MemcmpEncoding::Binary),
>                  }),
> -                // Filter by `Delegation::voter_pubkey`, which begins at byte offset 124
> +                // Filter by `Meta::authorized::withdrawer`, which begins at byte offset 44
>                  rpc_filter::RpcFilterType::Memcmp(rpc_filter::Memcmp {
> -                    offset: 124,
> +                    offset: 44,
>                      bytes: rpc_filter::MemcmpEncodedBytes::Base58(
>                          vote_account_pubkeys[0].to_string(),
>                      ),
> @@ -1795,11 +1795,11 @@ pub fn process_show_stakes(
>                          });
>                      }
>                  }
> -                StakeState::Stake(_, stake) => {
> +                StakeState::Stake(meta, _stake) => {
>                      if vote_account_pubkeys.is_none()
>                          || vote_account_pubkeys
>                              .unwrap()
> -                            .contains(&stake.delegation.voter_pubkey)
> +                            .contains(&meta.authorized.withdrawer)
>                      {
>                          stake_accounts.push(CliKeyedStakeState {
>                              stake_pubkey: stake_pubkey.to_string(),
> ```

**Comment by c3pko** [comment]
@brooksprumo where can I find the byte offset for withdrawer/voter?

**Comment by brooksprumo** [comment]
> @brooksprumo where can I find the byte offset for withdrawer/voter?

@c3pko Maybe @mvines can answer this one?

**Comment by CriesofCarrots** [comment]
> where can I find the byte offset for withdrawer/voter?

@c3pko , they aren't defined as constants anywhere, but you can work them out by starting here: https://github.com/solana-labs/solana/blob/328cca9fcdadcd16a75d1cf698c9821d1f8eac4d/sdk/program/src/stake/state.rs#L24
Offset of withdrawer in Initialized or Delegated accounts: 4 bytes state variant + 8 bytes rent_exempt_reserve + 32 bytes staker = 44
Offset of vote pubkey in Delegated accounts: 4 bytes state variant + 120 bytes Meta struct = 124
Or you can just trust mvines' snippet above ;)

**Comment by c3pko** [comment]
Thanks @CriesofCarrots! Should the bytes encode be the same for withdrawer as it was for vote_account_pubkeys? Here:

`    if let Some(withdraw_authority_pubkeys) = withdraw_authority_pubkeys {
    // if let Some(vote_account_pubkeys) = vote_account_pubkeys {
        // Use server-side filtering if only one vote account is provided
        if withdraw_authority_pubkeys.len() == 1 {
            program_accounts_config.filters = Some(vec![

                //Filter by StakeState::Stake(meta, _stake) => {

                rpc_filter::RpcFilterType::Memcmp(rpc_filter::Memcmp {
                    offset: 0,
                    bytes: rpc_filter::MemcmpEncodedBytes::Base58(
                        bs58::encode([1, 0, 0, 0]).into_string(),
                    ),
                    encoding: Some(rpc_filter::MemcmpEncoding::Binary),
                }),
                // Filter by `Meta::authorized::withdrawer`, which begins at byte offset 44
                rpc_filter::RpcFilterType::Memcmp(rpc_filter::Memcmp {
                    offset: 44,
                    bytes: rpc_filter::MemcmpEncodedBytes::Base58(
                        withdraw_authority_pubkeys[0].to_string(),
                    ),
                    encoding: Some(rpc_filter::MemcmpEncoding::Binary),
                }),
            ]);
        }
    }`

**Comment by godmodegalactus** [comment]
@c3pko  are you working on this issue?

**Comment by brooksprumo** [comment]
> I can look into it if no one is working on it.

@godmodegalactus Please do!

**Comment by godmodegalactus** [comment]
I have created a PR : https://github.com/solana-labs/solana/pull/25939
