### ISSUE TITLE
Why not all version are published to crates.io

### ISSUE THREAD

**Issue by xoac** [solana-labs/solana#25476]
#### Problem
I wanted to compile https://github.com/solana-labs/solana-accountsdb-plugin-postgres against 1.9.22 

 but some crates wasn't published as 1.9.22 version. For example: 
 
- https://crates.io/crates/solana-core/1.9.22
- https://crates.io/crates/solana-local-cluster/1.9.22

[The geyser plugin use `=` to specify exactly version that should be used](https://github.com/solana-labs/solana-accountsdb-plugin-postgres/blob/736d3f98d8aa0f8da2219ece2d692fba54dbd168/Cargo.toml#L43-L44)

#### Proposed Solution

- Publish all version to crates.io 
- publish lacking version into crates.io

**Comment by CriesofCarrots** [comment]
This is due to `cargo publish` pulling in a newer version of the `lru` crate on the v1.9 branch. Will pin `lru` for the upcoming v1.9.23.

**Comment by xoac** [comment]
@CriesofCarrots 

I saw there are 2 new versions (1.9.23 and 1.9.24) . Both didn't published the listed crates.

**Comment by CriesofCarrots** [comment]
@xoac , those crates are now both available on v1.9.23

**Comment by CriesofCarrots** [comment]
v1.9.24 will be available tomorrow, after the crates all publish
