### ISSUE TITLE
two successful nonced-transaction with same nonce blockhash

### ISSUE THREAD

**Issue by 0xx400** [solana-labs/solana#25541]
#### Problem
I found, that for some reason there is ability to send two nonced-transaction with same blockhash.

nonceaccount1: [7arXhy4WoydBoGJrXFA49Edx9x9KQueoqoyfrRHoXGMe](https://explorer.solana.com/address/7arXhy4WoydBoGJrXFA49Edx9x9KQueoqoyfrRHoXGMe?cluster=devnet)
@May 25, 2022 at 04:10:08   requested nonce-blockhash of nonceaccount1   nonce-blockhash was   2LCgS2qDg3Y3C8wmvgmk4biPVEGcsJPG4ceusEyZqvuH

@May 25, 2022 at 04:13:08   send nonced-transaction  TzVLjuGfhr5tQ.... (with blockhash 2LCgS2qD...)
https://explorer.solana.com/tx/TzVLjuGfhr5tQekB61ypDGZ4meHsq2b3AYRHijbaPEZK1PQKMx64ADoH2PMHD7XhM2hBiBtKk793mvxrqALH4Hj?cluster=devnet

@May 25, 2022 at 04:13:14  got new nonce for nonce-account1. it's 9h9AUUN6Sm1BBhoDyCjGAgdpB7oEdCvpew1mTn5t3jtf
(https://explorer.solana.com/block/136526112?cluster=devnet)

@May 25, 2022 at 04:13:34 send nonced-transaction   3Z6EnCjn3Fp4.... (with blockhash  9h9AUUN6Sm1BBhoDyCjGAgdpB7oEdCvpew1mTn5t3jtf)
https://explorer.solana.com/tx/3Z6EnCjn3Fp4DcNHrbc5ejNkCJTT9kx17pBBnyb7osyMKAYGy5YGiuKBPt7CuwspCqqVy8nYhEhF34jAwktUT4ra?cluster=devnet

@May 25, 2022 at 04:13:46  got new nonce for nonce-account1. it's 2m7QKCDeWZ5YFg5wDQZP89Ai9RMCMWfHTXZCaiG62m27
(https://explorer.solana.com/block/136526179?cluster=devnet)

@May 25, 2022 at 04:14:06 send nonced-transaction   3vtxG1AYK.... (with blockhash  **9h9AUUN6Sm1BBhoDyCjGAgdpB7oEdCvpew1mTn5t3jtf**   !!!!)
https://explorer.solana.com/tx/3vtxG1AYKHM1fMKB4xqCAuxAGrF8dKBKKw6onsG4VjdBTMEPUxrKr6RXZYbwXuYfvCB32ZoVFUajrBoQxZjfakyB?cluster=devnet

This transatcion was included in block and success passed despite wrong blockhash.  It's advance nonce of nonceaccount to new value (4TxUiYVJZU6tXJZjZS5Y1iE2Jb5QgUwTG2capbXeUgWW from old 2m7QKCDeWZ5YFg5wDQZP89Ai9RMCMWfHTXZCaiG62m27)

@May 25, 2022 at 04:14:35  got new nonce for nonce-account1. it's 4TxUiYVJZU6tXJZjZS5Y1iE2Jb5QgUwTG2capbXeUgWW
(https://explorer.solana.com/block/136526261?cluster=devnet)

according documentation

> The AdvanceNonceAccount instruction is used to manage the account's stored nonce value. It stores the cluster's most recent blockhash in the account's state data, failing if that matches the value already stored there. This check prevents replaying transactions within the same block.

https://docs.solana.com/implemented-proposals/durable-tx-nonces

**Comment by jstarry** [comment]
Hey @z3000z3000z3000, this is quite confusing behavior, thanks for opening this issue. The documentation that you linked is actually correct but doesn't explain the full story as you've discovered.

First, the primary reason for using either a recent blockhash for a transaction or a blockhash stored in a nonce account, is to prevent processing the same transaction message twice in the full history of the ledger. In your case, the two transactions that use the same blockhash (9h9) have different messages so we didn't violate that double processing rule there. However, you would expect that if you use a nonced tx, you would never be able to use the same nonced blockhash twice. This is usually true, but there is an exception that you have encountered...

_Any_ transaction that uses a "recent" blockhash will bypass the check that matches the nonce account's blockhash with the transaction's blockhash. Yes, this includes nonced transactions that use a "recent" blockhash. Your first tx (3Z6) and your second tx (3vt) both used a recent enough blockhash to skip the nonce blockhash check. The advance nonce ix will still run no matter what as you've observed. But the mental model you can use is that the nonce behavior of transactions only kicks in if the tx's blockhash isn't recent anymore. If it's still recent, we process it as a normal tx.

You may wonder why we don't always process nonced tx's consistently... Well, it's cheaper to check if the transaction's blockhash is recent and then skip over the (relatively expensive) nonce detection if we don't need to do it.

Hope this helps!

**Comment by jstarry** [comment]
FYI @z3000z3000z3000 we plan to investigate what the perf impact of properly detecting durable transactions and not processing them as normal transactions to remove this confusing behavior.
