### ISSUE TITLE
Add support for associated-token-account's CreateIdempotent instruction

### ISSUE THREAD

**Issue by zaa** [solana-labs/solana#25550]
#### Problem

https://github.com/solana-labs/solana-program-library/pull/2883 added support for the CreateIdempotent instruction, but Solana's transaction-status crate does parse the instruction at the moment.

#### Proposed Solution
Modify https://github.com/solana-labs/solana/blob/6f56b4d8ecd35c1dd8ac3bcbd0d3d71fab12e5e0/transaction-status/src/parse_associated_token.rs#L17 to parse invocations of the new instruction.

cc: @joncinque

**Comment by joncinque** [comment]
Added with https://github.com/solana-labs/solana/pull/26921
