### ISSUE TITLE
getFeeForMessage base-64 encoded message

### ISSUE THREAD

**Issue by KorayBarkin** [solana-labs/solana#25551]
In JSON RPC API of getFeeForMessage takes a base-64 encoded message parameter but it is unclear where or how to obtain this encoded hash code. I'm not sure but I guess this hash consists from address, to address and the amount. Based on this input calculates the gas fee, however, how can I generate this hash parameter for any transaction?

```
{
  "id":1,
  "jsonrpc":"2.0",
  "method":"getFeeForMessage",
  "params":[
"AQABAgIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEBAQAA",
    {
      "commitment":"processed"
    }
  ]
}
```
How do I generate "params"?

**Comment by jstarry** [comment]
Transactions are made up of a list of signatures and a "message." The message can be serialized to a buffer and then you can encode that buffer as a base64 string. If you're using web3, you can call `tx.compileMessage()` to get the message and then call `message.serialize().toString("base64")` to get a base64 encoded version of the message.

**Comment by KorayBarkin** [comment]
> Transactions are made up of a list of signatures and a "message." The message can be serialized to a buffer and then you can encode that buffer as a base64 string. If you're using web3, you can call `tx.compileMessage()` to get the message and then call `message.serialize().toString("base64")` to get a base64 encoded version of the message.

I believe tx is the transaction object in here? So, firstly I create a transaction object then we run it with compileMessage() like: `let transaction = tx.compileMessage();` then `let result = transaction.serialize().toString("base64");`

**Comment by KorayBarkin** [comment]
> > Transactions are made up of a list of signatures and a "message." The message can be serialized to a buffer and then you can encode that buffer as a base64 string. If you're using web3, you can call `tx.compileMessage()` to get the message and then call `message.serialize().toString("base64")` to get a base64 encoded version of the message.
> 
> I believe tx is the transaction object in here? So, firstly I create a transaction object then we run it with compileMessage() like: `let transaction = tx.compileMessage();` then `let result = transaction.serialize().toString("base64");`

It gives me this error I don't know what supposed to pass as a String :/
```

/Users/icrypexbilisim/solanaservices/node_modules/base-x/src/index.js:66
    if (typeof source !== 'string') { throw new TypeError('Expected String') }
                                            ^

TypeError: Expected String
    at decodeUnsafe (/Users/icrypexbilisim/solanaservices/node_modules/base-x/src/index.js:66:45)
    at Object.decode (/Users/icrypexbilisim/solanaservices/node_modules/base-x/src/index.js:109:18)
    at Message.serialize (/Users/icrypexbilisim/solanaservices/node_modules/@solana/web3.js/lib/index.cjs.js:2322:49)
    at test (/Users/icrypexbilisim/solanaservices/test.js:56:19)
```

**Comment by steveluscher** [comment]
That fatal is coming from `Message#serialize`. The only call to `decode` that I can see are these: 
https://github.com/solana-labs/solana/blob/442e6c325fa157d39f0479a4682b819ecc4f2e22/web3.js/src/message.ts#L121

https://github.com/solana-labs/solana/blob/442e6c325fa157d39f0479a4682b819ecc4f2e22/web3.js/src/message.ts#L209

There's either a problem with one of your instructions' data, or a problem with the `recentBlockhash`. `console.log` them and see what's up?

In any case, GitHub issues is not the right place for support. Try https://solana.com/discord or add your commitment here: https://twitter.com/therealchaseeb/status/1526384828161171456
