### ISSUE TITLE
Rent Exemption with `realloc` on Program Account

### ISSUE THREAD

**Issue by callensm** [solana-labs/solana#25565]
#### Problem

With the availability of the `realloc` capability, what is the idiomatic way of handling the increase in the rent exemption amount when reallocating the size of a program account?

I thought maybe a simple lamport transfer from an authoritative wallet would do the trick, but that resulted in:

```
Error: failed to send transaction: Transaction simulation failed: Error processing Instruction 0: instruction spent from the balance of an account it does not own
```

and the use of the token program's `transfer` instruction doesn't work either since the destination isn't a token account.

Has this been solved for and I'm missing it in the documentation somewhere?

**Comment by jstarry** [comment]
@callensm only the owner program can spend the lamports of an account and the error indicates that your tx is violating that rule. Keep in mind that a system transfer won't work if you're spending lamports from a non-system account so be sure that the source account of the system transfer is actually a system owned account.

**Comment by callensm** [comment]
@jstarry right I understand all of that - I guess my question was more geared towards inquiring about an existing example of the proper method of handling the lamport transfer within a program to convert the rent increase that is resulted from `realloc`.

**Comment by callensm** [comment]
I suppose one method would be to have a program owned token account that acts as a vault to transfer from for these types of situations.

**Comment by jstarry** [comment]
I see, yeah you have to pass in a system-owned signer account to your instruction. There is an example here: https://github.com/solana-labs/solana/blob/ae9513f00a8f5e905fa1f7b8f42b709ff24369ba/programs/address-lookup-table/src/processor.rs#L218 (note that this is a native program rather than a bpf program so some things are a bit different)

**Comment by jstarry** [comment]
I think it will be more common to have users pay for the data they are allocating. But I can imagine some programs will want to subsidize the cost for a better user experience too.

**Comment by jstarry** [comment]
> program owned token account

And just to clarify, you cannot use an spl-token account to pay for realloc unless the spl-token program supported that functionality (which it doesn't)
