### ISSUE TITLE
Expired checkpoints aren't freed

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#2556]
#### Problem

Checkpoints cannot be stored forever because they take up space.

#### Proposed Solution

#2289 

The checkpoint is `merged_into_root` in the forks.rs module

**Comment by mvines** [comment]
@aeyakovenko - do you know if this is still an issue?

**Comment by aeyakovenko** [comment]
Nope

**Comment by pgarg66** [comment]
Looks like the checkpoints now map to bank (per slot). The bank objects get freed when they get merged with root. Also, any bank that cannot be merged, gets pruned.

So, this issue should be fixed. @aeyakovenko does that sound right?
