### ISSUE TITLE
Forwarder price filters: a way for leaders to tell forwarders what transactions the leader is looking for

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#25586]
#### Problem

Bots will spam the next 100 leaders with the same tx, leaders[0..100], 95 of them forward to  leader[0] resulting in duplicate message amplification.

#### Proposed Solution
N: number of leaders to look ahead by, should be less than blockhash expiration / leader slots, 40?
L: leaders current slot
forwarding range: start = L - (2 * num slots per leader), end = L + N, a range of nodes that leader is expecting to receive forwarded transactions from.
PriceFilter: list of top write accounts and min price to be included for that account, and the min price to be included in the block. a single MTU sized quic message should fit 32 of accounts and their min price.

1. rpcs send to next N nodes until they get quic ACK, means packet was sent reliably
2. Only leaders in the forwarding range forward, other nodes drop TPU txs.
3. forwarding range nodes:
  a. send txs once per leader allowed by the remote PriceFilter.
  b. After forwarding leader should keep the tx in the pending queue
  c. pending queue is cleared when forwarder is not scheduled within the forwarding range.
4. each node when making blocks or forwarding is continuously updating its own current PriceFilter
5. Leader then sends the PriceFilter to the forwarding range nodes once a slot starting at the L-1 slot
6. When forwarding range nodes receive the PriceFilter, they only forward txs that pay above what is in the PriceFilter
7. RPC retries when confirmed block passes the quick ACK leader slot and message wasn't confirmed
8. TPU stage no longer needs to track if the tx has been forwarded before.  Forwarders only send txs that match the PriceFilter

The leader needs to know its own current PriceFilter, and the remote active leader's PriceFilter. Remote PriceFilter is invalidated, set to own, as the leader switches unless the new leader has updated it.  TXs that are below the price for the remote PriceFilter stay in the pending queue until they expire. TXs below the current's own PriceFilter * 0.5 can be dropped at the TPU.

tag @t-nelson @carllin @pgarg66 @taozhu-chicago @jstarry @sakridge

**Comment by carllin** [comment]
> PriceFilter: list of top write accounts and min price to be included for that account, and the min price to be included in the block. a single MTU sized quic message should fit 32 of accounts and their min price.

Do we also also need to factor in the price of contending reads on the same accounts? Those deny writes and take up room in the buffer. Factoring in reads may drastically raise that minimum threshold for a write to be processed in read heavy workloads.

A rough way of enforcing this might be by sorting the reads/writes on the same account based on fee and count consecutive runs of reads (up to banking thread count) towards the compute units.

So assuming number of banking threads is 4, as in today's code:

If the sorted fee-based queue looks like this:

`W1 - (R1 - R2 - R3 -R4) - (R5 - R6) - W2 - W3 - (R7)`

If this queue saturates all the account's compute limits, then the minimum fee in the PriceFilter is the fee for `R7`, whereas without accounting for this, the minimum fee might be `W3`


> rpcs send to next N nodes until they get quic ack, means packet was sent reliably
> L-2 and L+N leaders forward like usual
> > TPU stage no longer needs to track if the tx has been forwarded before. Forwarders only send txs that match the PriceFilter

These statements are a bit conflicting. Do leaders forward like usual, or only when they get a PriceFilter request?

If it's like "usual" i.e. today's code, then the rpcs forward to 20 next leader nodes, and then all 20 leader nodes will forward the same packets to who they think is the leader?

> as leader is making blocks or forwarding its continuously updating its current PriceFilter

Steps for this seems like:

1. Only consider transactions with blockhashes that will not expire once you become leader later
2. Of these transactions track CU's towards accounts as suggested above
3. Update minimum PriceFilter

> Starting at L-1 slot leader then sends the PriceFilter to L-2 up to L+N leaders once a slot

So every time you are the leader, you query the previous 2 and next 20 leaders to see if they have any transactions that fit your PriceFilter.

> When L-2 leaders and L+N receive the PriceFilter, they only forward what they have that bids above what is in the PriceFilter

If they've already sent certain packets in a previous forward to the same leader, do they send them again?

> RPC retries when block passes the "ack" slot and message wasn't confirmed

What is the "ack" slot?

**Comment by aeyakovenko** [comment]
@carllin 

> These statements are a bit conflicting. Do leaders forward like usual, or only when they get a PriceFilter request?

When they get an updated PriceFilter from the leader, they can retry the txs if they bid above the price

> If it's like "usual" i.e. today's code, then the rpcs forward to 20 next leader nodes, and then all 20 leader nodes will forward the same packets to who they think is the leader?

yea, but they would also keep them in their own pending queue until they are confirmed.

> What is the "ack" slot?

The slot that the RPC had a reliable submit to one of the nodes.
