### ISSUE TITLE
Can I get rent per epoch from JSON RPC API?

### ISSUE THREAD

**Issue by moderatelyOldMan** [solana-labs/solana#25581]
#### Problem
There doesn't seem to be a way of getting amount of rent per epoch via JSON RPC API. The only mentions of rent in official API docs are about rent exemption and a rent Sysvar, that's supposedly holds rent-related info, but there's no obvious or documented way of retrieving that information from API. So my question is: is there a way to get rent per epoch from JSON RPC API without using any CLI or local tools and libraries?

**Comment by jstarry** [comment]
There isn't an easy way to do that right now, but the concept of rent paying per epoch has been deprecated and all new accounts must be rent exempt. I don't think we'll be adding support for an API like that.
