### ISSUE TITLE
Voting corner case attack vectors or stalls

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#2558]
#### Problem

A node could withhold its vote for the length of the LastId timeout before sending all the votes for all the accepted forks.  

The votes for the previous block could expire in terms of LastId ticks if there is a large network outage.  Since the newly proposed forks would have generated more Ticks than transaction window would allow for.  The problem is that each proposed fork may have different LastIds depending on which block it is based on, so nodes would not be able to guess what LastId to use.
  
#### Proposed Solution

LastId window could be based on the previous blocks slot.  This would require the votes to recently generated to be accepted, but long lived with regards to network failures.

tag: @garious @rob-solana

**Comment by rob-solana** [comment]
is this still relevant, given #4381 ?

**Comment by aeyakovenko** [comment]
@rob-solana we should mark stale votes as ineligible for reward.  If a vote is entered older than 2 slots or something like that.

**Comment by rob-solana** [comment]
ok, a separate "too old" config. I wonder if 2 slots is a bit aggressive

**Comment by ParthDesai** [comment]
Not applicable in new design.
