### ISSUE TITLE
Create API to fetch transactions during a time range

### ISSUE THREAD

**Issue by topcoder1208** [solana-labs/solana#25580]
I have built a program and deployed on devnet.
I'd like to get transactions list of my program for special period.
What is solution?

**Comment by jstarry** [comment]
I've wondered this as well. @CriesofCarrots is the account transaction history in bigtable only indexed by signature? It'd be nice to be able to the transactions for a particular program over a specified slot range.

**Comment by CriesofCarrots** [comment]
That table is indexed by slot first in both blockstore and bigtable, so it would definitely be possible to write an api that bounds a query by a slot range.
Perhaps we can implement this after I fix the ordering/indexing within the slot.

**Comment by jstarry** [comment]
@CriesofCarrots that's great news. I would love to use an API like that to add a data query tool to the explorer for browsing historical transactions.

**Comment by topcoder1208** [comment]
So, will web3 rpc API be added in the future? Is there no function for this now?

**Comment by jstarry** [comment]
> So, will web3 rpc API be added in the future? Is there no function for this now?

If added, it won't be for awhile. There's no function for this now.
