### ISSUE TITLE
Transaction prioritization should include all fees

### ISSUE THREAD

**Issue by ckamm** [solana-labs/solana#25604]
#### Problem

Currently the transaction priority depends only on the `cu_price`, i.e. the number of microlamports per cu the sender is willing to pay extra.

This means that:
- a 1M CU transaction that pays 1 microlamport/cu extra -- so 1 lamport extra total -- gets priority value 1
- a 2k CU transaction that does not pay extra gets priority value 0

#### Proposed Solution

If the total amount of fees per microlamport was used as the priority value, we'd get
- a 1M CU transaction that pays 1 microlamport/cu extra and has 1 signature -- so 5000 + 1 lamports total -- gets priority value 5001 lamports / 1M cu = 5001 microlamports/cu
- a 2k CU transaction with one signature pays 5000 lamports total and gets priority value of 5000 lamports / 2000cu = 2.5e6 microlamports/cu

The effect would be significant: The expensive transaction would need to pay 2.5 lamports/cu to outpriority the tiny tx, i.e. pay a fee of around 0.0025 SOL. That makes sense because it's 500x more expensive.

@taozhu-chicago

**Comment by nikhayes** [comment]
So your worry is that it's too economically easy to outprioritize the small transactions currently?

If so, I had an idea that the priority parameter should be a whole number multiplier of a Solana-wide base fee/cu rate. This would be easy UX and a large transaction would need to pay at least double the underlying base rate per cu to get ahead of other transactions (not micro adjustments). I explained more here: https://github.com/solana-labs/solana/issues/25300

**Comment by taozhu-chicago** [comment]
potentially can use `get_fee` ([here](https://github.com/solana-labs/solana/blob/master/program-runtime/src/prioritization_fee.rs#L50-L52)) instead of `get_priority()` for prioritization.

**Comment by ckamm** [comment]
> potentially can use `get_fee` ([here](https://github.com/solana-labs/solana/blob/master/program-runtime/src/prioritization_fee.rs#L50-L52)) instead of `get_priority()` for prioritization.

I don't think that's right? get_fee() isn't per-requested-cu and doesn't include the signature fees.

**Comment by taozhu-chicago** [comment]
> > potentially can use `get_fee` ([here](https://github.com/solana-labs/solana/blob/master/program-runtime/src/prioritization_fee.rs#L50-L52)) instead of `get_priority()` for prioritization.
> 
> I don't think that's right? get_fee() isn't per-requested-cu and doesn't include the signature fees.

Yea, `get_fee()` isn't the same as your proposal. I am just thinking out loud that it might be an option to include "expensiveness" into prioritization. But the problem with this is expensive tx will easily out-prioritize cheap ones even with smaller rate (eg microlamports/cu). So sounds like using `get_priority()` to prioritize is fairer. The 1M CU tx will pay higher fee anyway.

**Comment by taozhu-chicago** [comment]
Need a bank to calculate `total_fee`, vs right now can quickly look at transaction for `compute_budget` ix to get prioritization fee.

**Comment by ckamm** [comment]
@aeyakovenko We don't have a good path from the current state where noone pays priority fees to the world where everyone pays priority fees.

What I think will happen very soon is this: Big players notice prioritization is live, works and is essentially free. Now their expensive transactions will make it into blocks with priority and crowd out normal user transactions -- until their wallets upgrade to send compute budget instructions with every spl token transfer.

If we instead bias transaction priority against compute use (like I suggest here), all the apps that send big transactions may suddenly have even more trouble getting their transactions into blocks until they start paying for more priority.

I don't have a good path forward. Possibly priority should be stochastic instead of absolute?

**Comment by taozhu-chicago** [comment]
In scenario that expensive transactions can pay little (1 lamport per 1M cu tx) to crowd out normal wallet transactions, we are working on new RPC query (#26561) to support wallets to provide user estimated priority fee for transactions. A separate thought, the possibility wallet transactions might be crowd out could motivate quicker upgrades. 

If deemed necessary to mitigates it while wallets are being upgraded, another possibility is to set up an temporarily minimum priority fee ; for example, if we set min priority fee to be 1,000 micro-lamports, then any fee below it will be round down to 0. For big players to take advantage while small players are not yet ready, they have to pay 1,000 micro-lamports or above. It works like speed bump that might level the playground a bit during initial phrase. It can be removed when fee markets have stabilized.
