### ISSUE TITLE
Consider using a `rust-toolchain.toml` file

### ISSUE THREAD

**Issue by ruuda** [solana-labs/solana#25603]
#### Problem

Solana depends intimately on the particular `rustc` version used. One example of this was https://github.com/solana-labs/rbpf/commit/5394026f4b9ec0d26125880b042c70fcf5974ee7, where before that change in `rbpf` was merged, Solana would segfault when compiled with the wrong `rustc` version.

However, for the default approach of building a Rust project (`cargo build`), `rustup` uses the system-wide default toolchain, not the one suitable for the particular Solana release. Fortunately, the right Rust version _is_ recorded in the repository: https://github.com/solana-labs/solana/blob/24634b6e255118a7d340f20ca41442795fbe4a6b/ci/rust-version.sh#L21 However, it’s in a nonstandard location, and it’s not used by `rustup`’s `cargo` proxy binary.

#### Proposed Solution

Add a [`rust-toolchain` or `rust-toolchain.toml` file](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file) to pin the stable toolchain using `rustup`’s standard mechanism. The existing `ci/rust-version.sh` can still manage the nightly toolchain. As far as I am aware, there is no standardized way to manage multiple toolchains.

@mvines, you seem to most often update the Rust version, what do you think?

**Comment by mvines** [comment]
sounds like a good idea!

**Comment by KirillLykov** [comment]
The plan is to split [one huge PR](https://github.com/solana-labs/solana/pull/27018) into several smaller:
1. Add `./cargo-nightly`, use it instead of `./cargo` https://github.com/solana-labs/solana/pull/29319
2. Add toolchain file, take version from it https://github.com/solana-labs/solana/pull/29320
3. Get rid of `./cargo` in (depends on 1 and 2)
* `cargo-fmt.sh` , `cargo-for-all-lock-file.sh`, `cargo-install-all.sh`, `coverage-in-disk.sh`, `coverage.sh`
* `cargo-build-sbf` etc
* `build-downstream-*.sh`
* `docs/build-cli-usage.sh`
* remaining `ci` scripts, if any

**Comment by yihau** [comment]
I'm thinking should we use the pattern below to replace `./cargo` instead of only `cargo` 🤔 

```sh
source ci/rust-version.sh stable

... (omit)

cargo +"$rust_stable"

```

the concern is that if someone set `rustup override`, I think the priority will be higher than `cargo-toolchain.toml`.

**Comment by KirillLykov** [comment]
> 

I think the main idea of using `cargo build` is that it is simple and expected procedure. If a user has set up rust version using overrides, I would assume that he/she knows what he/she is doing and it is up to developer.

**Comment by steviez** [comment]
Switching this from "not planned" to "closed"; we still depend on the custom cargo script for some aspects (ie running `fmt` and `clippy` with `nightly`), but, we do have a `rust-toolchain.toml` file as of https://github.com/solana-labs/solana/pull/29320 so the basic case of just building the repo is supported.

Any further work to try to reduce usage of this scripts can probably take place in new PR's / issue(s)
