### ISSUE TITLE
web3.js: Deprecate async methods “recently” made sync

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana#25648]
#### Problem

`createProgramAddress` and `findProgramAddress` are async methods, despite having no awaitables in their implementation. A developer using these methods will incorrectly presume that _their_ code needs to be made async. This leads to a proliferation of async/await in the ecosystem which reduces the overall reliability and performance of apps.

#### Proposed Solution

Discourage people from using them by marking their method signatures as [`@deprecated`](https://www.typescriptlang.org/docs/handbook/jsdoc-supported-types.html#deprecated).

#### Alternate solution

The only reason that these methods were made sync was because the [last bit of async code was removed from `createProgramAddress`](https://github.com/solana-labs/solana/pull/20822). That code was replaced with a sync version because it was incompatible in some way with React Native. cc/ @dr497

Instead, we might consider doubling down on _restoring_ the former glory of the async version, by using an async hash method, then adding a React Native compatible hashing algorithm using the `__forks__` directory. Last step would be to build a React Native bundle.

**Comment by tomland123** [comment]
I think the only person in the world who cares about these optimizations is me, but it's a bit irritating to watch thousands of hours of engineering work get forgotten and be replaced with a simpler abstraction that works.

I am fine with deprecating it. Shipping speed is more important than my bikeshedding

**Comment by steveluscher** [comment]
I care. It's hard to know the global maximum is here, while all of these things are true:

* 🚀 There exists the opportunity to produces hashes on multiple threads in Node.
* 🌍 That notwithstanding, JavaScript isn't multithreaded and the same browser APIs typically can't make use of multiple threads.
* 💤 `async/await` code is difficult to reason about and the degree to which folks in the ecosystem find it difficult to reason about is laying waste to the reliability and performance of ecosystem apps.

All of the asymmetry here either makes things malperformant, confusing, or complex. It's like an iron triangle but where each point is only bad things.

**Comment by jordansexton** [comment]
Woah, are we really importing the entire Ethers lib just to use that one utility function?

**Comment by jordansexton** [comment]
> Yeah, the question is whether the ethers library is tree-shakable or not.

As originally imported, it was grabbing `ethers.utils.sha256` which imports the entire set of `utils` (including a bunch of other hash functions). But https://github.com/solana-labs/solana/commit/b82539075210847d6f6925b7a3a8a6f0ea143039 fixed this.

**Comment by steveluscher** [comment]
Yeah, that's never the whole story with tree-shaking though. For instance, the `sha2.ts` file imports `createHmac` which `sha256()` doesn't use. Whether `createHmac` gets tree-shaken out is a function of whether or not:

* Ethers has marked their package as `sideEffects: false` (they have)
* Ethers is actually side-effect free (¯\_(°ペ)_/¯)
