### ISSUE TITLE
Startup can pointlessly get stuck in `SearchingForRpcService` for a long time

### ISSUE THREAD

**Issue by ruuda** [solana-labs/solana#25659]
#### Problem

Sometimes `solana-validator` startup is stuck in the `ValidatorStartProgress::SearchingForRpcService` for a long-ish time (can be up to 10 minutes). During this time it will try to connect to various RPC nodes that in the gossip network claim they have their RPC enabled, discover that it is unable to connect (likely these nodes firewalled off their RPC port), blacklist that node, and try again. This process can go on for a long time, my most recent run only found a good node after 32 bad ones.

Then, only after finding the peer, `solana-validator` compares its local snapshot age against that of the peer, and concludes it is still recent enough to use its own local snapshot, and it never uses the RPC connection to that peer again:

https://github.com/solana-labs/solana/blob/02b26ddd823c60f6051f02890f2f9e245523ce7e/validator/src/bootstrap.rs#L496-L505

(It does use the peer to download a snapshot from, but if it decides to not download a snapshot, it doesn’t need the peer.)

<details>
<summary>Aside, there is a super misleading indentation mistake in the code here</summary>

https://github.com/solana-labs/solana/blob/02b26ddd823c60f6051f02890f2f9e245523ce7e/validator/src/bootstrap.rs#L448-L457

It looks like the code in the `and_then` is a new scope, but it is actually nested one level deeper than it appears to be. So from the indentation you don’t expect `rpc_client` to be available inside the closure passed to `and_then`, but it is.

</details>

What do we need to decide if our local snapshot is recent enough?
We need the snapshot version, which we get from here: https://github.com/solana-labs/solana/blob/02b26ddd823c60f6051f02890f2f9e245523ce7e/validator/src/bootstrap.rs#L442

Confusingly, `snapshot_hash` is not the snapshot hash, it’s a tuple of `(Slot, Hash)`, returned by `get_rpc_node`. There is only one place in that function that returns a non-None value, which is here: https://github.com/solana-labs/solana/blob/02b26ddd823c60f6051f02890f2f9e245523ce7e/validator/src/bootstrap.rs#L751

Where does the “snapshot hash” (actually tuple) come from? It is initialized here: https://github.com/solana-labs/solana/blob/02b26ddd823c60f6051f02890f2f9e245523ce7e/validator/src/bootstrap.rs#L672-L673

And overwritten here if we find a peer in the gossip network with a higher hash: https://github.com/solana-labs/solana/blob/02b26ddd823c60f6051f02890f2f9e245523ce7e/validator/src/bootstrap.rs#L692-L698

But crucially, getting the snapshot version depends only on information from gossip, we don’t actually need to connect to the node! https://github.com/solana-labs/solana/blob/02b26ddd823c60f6051f02890f2f9e245523ce7e/validator/src/bootstrap.rs#L682-L683

So **tl;dr**: `solana-validator` spends several minutes trying to connect to nodes in the gossip network that advertise RPC but aren’t actually reachable, only to ignore that peer and use a local snapshot. This unnecessarily delays the `SearchingForRpcService` phase of startup.

#### Proposed Solution

Move the test if we want to start from a local snapshot to be a bit earlier, so that if we decide to start from a local snapshot, there is no need to connect to a peer with RPC, and peers with unreachable RPC ports do not delay the startup process.

**Comment by ruuda** [comment]
@brooksprumo you have worked in this module a lot, what do you think?

**Comment by brooksprumo** [comment]
@ruuda Yes, lots of good insights here; thanks for bringing this up.

> #### Problem
> Sometimes `solana-validator` startup is stuck in the `ValidatorStartProgress::SearchingForRpcService` for a long-ish time (can be up to 10 minutes). During this time it will try to connect to various RPC nodes that in the gossip network claim they have their RPC enabled, discover that it is unable to connect (likely these nodes firewalled off their RPC port), blacklist that node, and try again. This process can go on for a long time, my most recent run only found a good node after 32 bad ones.

Yeah... This can take quite some time.


> Then, only after finding the peer, `solana-validator` compares its local snapshot age against that of the peer, and concludes it is still recent enough to use its own local snapshot, and it never uses the RPC connection to that peer again:
> 
> (It does use the peer to download a snapshot from, but if it decides to not download a snapshot, it doesn’t need the peer.)

The peer is also used to download the genesis hash. But yeah, if we already have a snapshot and genesis, then all that's done is to check the vote account (which can also be bypassed with `--no-check-vote-account`).


> Aside, there is a super misleading indentation mistake in the code here

Yeah... That can definitely be fixed. There's some cargo-fmt issue for this, but I don't have it handy. Will need a manual PR to fix.


> What do we need to decide if our local snapshot is recent enough?

That comes from the `--maximum-local-snapshot-age`, specified in slots. Default is 2,500.


> Confusingly, `snapshot_hash` is not the snapshot hash, it’s a tuple of `(Slot, Hash)`

Yes. I thought the same thing. I tried to change this earlier, but I didn't get buy-in.


> Where does the “snapshot hash” (actually tuple) come from? It is initialized here:
> 
> And overwritten here if we find a peer in the gossip network with a higher hash:

We get the local snapshot hash from the node's local snapshots, and the rest from gossip. You may find the code in `mod with_incremental_snapshots` easier to grok (or at least I did, but I'm biased since that's the part I wrote).


> But crucially, getting the snapshot version depends only on information from gossip, we don’t actually need to connect to the node!

Correct, we do not connect to the node to get snapshot information; it all comes from gossip.


> So **tl;dr**: `solana-validator` spends several minutes trying to connect to nodes in the gossip network that advertise RPC but aren’t actually reachable, only to ignore that peer and use a local snapshot. This unnecessarily delays the `SearchingForRpcService` phase of startup.

Agreed.


> #### Proposed Solution
> Move the test if we want to start from a local snapshot to be a bit earlier, so that if we decide to start from a local snapshot, there is no need to connect to a peer with RPC, and peers with unreachable RPC ports do not delay the startup process.

Sounds like a good idea to me!

It probably can go somewhere around here:
https://github.com/solana-labs/solana/blob/ed68c0b88972fd2c820edaba5ea245d614261efe/validator/src/bootstrap.rs#L90-L92

Since the genesis file is needed, if genesis fetch is _disabled_ and snapshot fetch is _enabled_, then checking for local snapshots could happen and skip the rest.
