### ISSUE TITLE
blockstore clean and compact is quite slow with wait-for-supermajority purge

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#25710]
#### Problem

blockstore clean and compact is quite slow with wait-for-supermajority purge and can take 20-30 minutes.
https://github.com/solana-labs/solana/blob/b80a82a9e5bda5aac721298ba83b3e2b6d9a2b81/core/src/validator.rs#L446

#### Proposed Solution

Maybe the compaction is not actually needed? Or can we detect whether a compaction is actually needed? Or maybe kick the compaction to a background thread once we delete everything and then try to get into the mode to wait for the restart.

**Comment by sakridge** [comment]
@yhchiang-sol Can you take a look?

**Comment by yhchiang-sol** [comment]
Sure thing.  Will take a look!

**Comment by yhchiang-sol** [comment]
It looks to me that compaction is not needed as the clear part has been handled by `blockstore.purge_slots(start_slot, end_slot, PurgeType::Exact);`, which restores the blockstore shred version by issuing range-delete.  We can let rocksdb's automatic background compaction later reclaim the disk storage from those deleted entries.

Let me create a PR for this.

**Comment by yhchiang-sol** [comment]
Created follow-up issue https://github.com/solana-labs/solana/issues/25868.
