### ISSUE TITLE
explorer: JS error for mints/tokens with crazy amount of decimals

### ISSUE THREAD

**Issue by turshija** [solana-labs/solana#25756]
#### Problem
Created a mint with 100 decimals to test some edge cases in our project and explorer is crashing for that mint
https://explorer.solana.com/address/BZDqLovd5XbDBqNSzrYhezmtKSjZdx9iXzjLQrdYS6Zs

![image](https://user-images.githubusercontent.com/933433/171876339-f5b3e4d3-1ee7-4708-a3e9-9bbec6bf740a.png)

**Comment by steveluscher** [comment]
Yup. Turns out the maximum is 20 as per the spec. https://tc39.es/ecma402/#sec-defaultnumberoption

**Comment by nixxholas** [comment]
Working on this.
