### ISSUE TITLE
Cargo test-bpf - no way of passing args to inner build command.

### ISSUE THREAD

**Issue by ftelnov** [solana-labs/solana#25779]
#### Problem

There is no(at least documented) way of passing arguments to the build-bpf command that is called inside test-bpf command.

#### Proposed Solution

Provide documented way of passing arguments directly to build-bpf command.

**Comment by dmakarov** [comment]
Which option would you like to pass to build-bpf?  The two commands have matching sets of command line options, so that if you use an option on the cargo-test-bpf command line, that option is also passed to cargo-build-bpf, if it is meaningful to do so.
