### ISSUE TITLE
Feature Gate: enable durable nonce

### ISSUE THREAD

**Issue by behzadnouri** [solana-labs/solana#25773]
### Description

https://github.com/solana-labs/solana/pull/25744 adds two features gates.
The 1st one separates durable nonce and blockhash domains with a
feature gate. A 2nd feature added enables durable nonce
at least one epoch after the 1st feature.
By the time 2nd feature is activated, some nonce accounts will have an
old blockhash, but no nonce account can have a recent blockhash.
As a result no transaction (durable or normal) can be executed twice.

### Feature ID

4EJQtF2pkRyawwcTVfQutzq4Sa5hRhibF6QAK1QXhtEX

### Activation Method

Single Core Contributor

### Min Release Versions

v1.9.29, v1.10.25

### Testnet Activation Epoch

330

### Devnet Activation Epoch

327

### Mainnet-Beta Activation Epoch

320

**Comment by jstarry** [comment]
Feature gate code removed in https://github.com/solana-labs/solana/pull/26470
