### ISSUE TITLE
When you type spl-token create-token on a Ubuntu 22.04 LTS VPS

### ISSUE THREAD

**Issue by miguelgargallo** [solana-labs/solana#25823]
#### Problem
When you type type spl-token create-token on a Ubuntu 22.04 LTS VPS you get this:
miguelgargallo@canarchain:/usr/lib64$ sql-token create-token
spl-token: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory

#### Proposed Solution
ln -s libssl.so.3 libssl.so
sudo ldconfig

**Comment by robertpye** [comment]
Hi @miguelgargallo this didn't work for me on 22.04 LTS. 
Getting the same error even with the link you suggest.
Any thoughts?

**Comment by askibin** [comment]
check if libssl1.1 is installed:
```
apt list --installed | grep -i libssl1.1
```
if not, install it with:
```
sudo apt-get install libssl1.1
```
