### ISSUE TITLE
Use io_uring For The Networking Stack (Zero Copy Networking, Etc...)

### ISSUE THREAD

**Issue by bonedaddy** [solana-labs/solana#25851]
#### Problem

Networking stack could be much faster, but will eventually (if not already) reach an upper bound of how fast it can be using traditional tooling.

#### Proposed Solution

Adopt `io_uring` into the networking stack to enable zero-copy networking.

Some resources:
* https://lwn.net/Articles/879724/
* https://unixism.net/loti/what_is_io_uring.html#io-uring-performance

**Comment by nikhayes** [comment]
[GitHub - tokio-rs/tokio-uring: An io_uring backed runtime for Rust](https://github.com/tokio-rs/tokio-uring)

**Comment by leoluk** [comment]
AF_XDP might be worth looking into as well.

**Comment by sowhu** [comment]
Io_ring saves a lot of system call overhead on the tx side. Coupling with zero copy it could become something like DPDK, and still leverage the kernel network stack.  
XDP can be used to filter out unwanted packets on the rx side at runtime. 

Can both of these be applied?

**Comment by KirillLykov** [comment]
Regarding io_uring to reduce syscalls overhead, it might be that it will not be that performant as one could expect:
* is there GRO/GSO? Might be that io_uring alone will not perform better than sendmmsg with gro/gso as some people noted
* zero-copy option is not there: there is a almost accepted [patch](https://lwn.net/Articles/879724/) for send but not for recv

QUIC implementation in rust: looks like io_uring should be introduced on the level of QUIC implementation (correct me if I'm wrong), but according to [discussion in quinn](https://github.com/quinn-rs/quinn/issues/915#issuecomment-1167182350) it seems that quinn is not able to prioritize this work.

Regarding io_uring and rust,  there are 3 popular choices: glommio (datadog), tokio-uring, monoio (bytedance).
Monoio has published some [benchmarks plots](https://github.com/bytedance/monoio/blob/master/docs/en/benchmark.md) and it seems that tokio-uring is the least performant choice

Regarding AF_XDP, my understanding is that it routes packets to ringbuffers to rapidly transfer to userspace buffers. So it solves the same problem as io_uring (correct me if I'm wrong). But io_uring is more widely accepted and there are new features added often, I don't see such an activity around AF_XDP.

XDP for filtering packets seems to be a performant way to implement filtering.

**Comment by KirillLykov** [comment]
Another thing is that I haven't found benchmarks which would allow to compare different QUIC implementations. Such bmks might take into account distribution of packet sizes, percent of invalid packets, peak/mean performance. If we want to do some performance improvements on quinn, it seems to be a prerequisite.
