### ISSUE TITLE
leader looks at the crds for any votes that are valid for the above checkpoint that haven't been registered yet

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#2589]
#### Problem
votes available in gossip that were censored/missed by a prior leader are not run through any TPU

#### Proposed Solution
TPU checks for any votes in gossip that have not been seen by the bank (using signature status?) and runs them in the current fork

**Comment by aeyakovenko** [comment]
#2562 is the pr for this

**Comment by rob-solana** [comment]
dup of #2545 ?

**Comment by aeyakovenko** [comment]
yea, this is a dup
