### ISSUE TITLE
Validator isn't choosing a fork before voting

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#2593]
#### Problem

Validator isn't choosing a fork before voting

#### Proposed solution

Replay stage should pick the "best" Bank in BankForks [Fork Selection](books/src/fork-selection.md) and vote.

**Comment by garious** [comment]
@rob-solana, I added "stretch goal" here, but it's actually in the critical path, right?

**Comment by garious** [comment]
Unless, is this ticket for full and proper fork selection versus quick and dirty?

**Comment by rob-solana** [comment]
cheap and cheesy longest voted thing should be fine for Beacons, I think

**Comment by mvines** [comment]
Obsolete
