### ISSUE TITLE
Confusing durable nonce function call convention

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#25950]
#### Problem

From Halborn:

The nonce patch (#25788) changes definitions of several functions which previously required the caller to provide a DurableNonce and now require a tuple with a DurableNonce and a boolean, indicating the separation of blockhash and nonce domains.

If this boolean is set to true, DurableNonces are generated from a hash
of the most recent blockhash and a fixed seed to prevent transaction
replay.

This boolean parameter used is in multiple function calls across the
codebase and is usually accompanied by a comment. This inconsistency
might be confusing to developers unfamiliar with the bug and previous
nonce format, which may lead to them writing incorrect code.

#### Proposed Solution

Consider introducing a new type with a verbose name to better explain the
meaning of the separate_domains variable value.

**Comment by jackcmay** [comment]
@behzadnouri What do you think of adding an enum instead boolean in a tuple?

**Comment by behzadnouri** [comment]
> @behzadnouri What do you think of adding an enum instead boolean in a tuple?

The boolean parameter is due to the feature gate.
It will be removed with the rest of the feature gate code once the feature is activated.
It won't stay there for long anyways.
