### ISSUE TITLE
Add option to CLI to set prioritization fee

### ISSUE THREAD

**Issue by taozhu-chicago** [solana-labs/solana#25966]
#### Problem

CLI should be able to set `compute-unit-price` to prioritize transactions it sends. 

#### Proposed Solution
- add new option `--compute-unit-price <MICRO-LAMPORTS>    Set the price in micro-lamports of each transaction compute unit`
- include `compute_budget` ix in transactions if above option presents.

**Comment by taozhu-chicago** [comment]
@mvines @CriesofCarrots  wdyt is the best way to add _optional_ Option `--compute-unit-price <MICRO-LAMPORTS>` to cli so it can prioritize transactions it sends? 

Is it better to make it global option by adding it to `Config` in `cli-config/src/config.rs` so any command that sends transactions can read it and add `compute_budget` instruction if needed; 

Or adding it as local option to specific commands that send transactions, basically to duplicate what's done for `ping` command [here](https://github.com/solana-labs/solana/blob/master/cli/src/cluster_query.rs#L276) to others.

I'm leaning to the first approach, but am not super familiar with cli, appreciate your guys inputs.

**Comment by mvines** [comment]
What is a MICRO-LAMPORT?

**Comment by mvines** [comment]
How about we start with a pull request to add to https://docs.solana.com/terminology!

**Comment by taozhu-chicago** [comment]
> hmmm, but lamports aren't fractional so it's either 1 or 2 lamports?
> 
> But to answer your original question, I feel like adding it to specific commands should be sufficient. Check out `cli/src/memo.rs` for how the memo arg was added to various cli commands

Yep, it's be round up to whole lamports. Sorry for bad example. 

Thanks for the pointer, will take the path of specific command.

**Comment by taozhu-chicago** [comment]
> How about we start with a pull request to add to https://docs.solana.com/terminology!

#26093

**Comment by ashpoolin** [comment]
Hey there. Just wanted to throw my hat in the ring to try to contribute to this issue. I added compute-unit-price to the CLI transfer options, but have yet to get the bulk of the changes to compile correctly. I was basically copying what I saw was done for the `ping` feature. Happy to work with others on this, share what I have, or if anybody has tips/suggestions please send my way. Can find me in the Solana discord, too. Thanks, Ashpool
