### ISSUE TITLE
[web3.js] Implement `AuthorizeWithSeed` and `AuthorizeCheckedWithSeed` in the vote program

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana#25974]
#### Problem

https://github.com/solana-labs/solana/pull/25928 added two new instructions to the vote program that we now need to add to web3.js

#### Proposed Solution

Add 'em!

**Comment by steveluscher** [comment]
@CriesofCarrots, I forget what we decided. Did we decide to leave these out?

**Comment by CriesofCarrots** [comment]
> I forget what we decided. Did we decide to leave these out?

I think we'll still need them, if you're willing
