### ISSUE TITLE
Javascript web3 - getSignatureStatus does not seem to be working

### ISSUE THREAD

**Issue by grimAgent** [solana-labs/solana#25971]
#### Problem

`getSignatureStatus` seems to be returning `null` both on mainnet and devnet

Running 
```javascript
        const solConnection = new web3.Connection(process.env.SOLANA_RPC_ENDPOINT);
        const signatureStatus = await solConnection.getSignatureStatus('4xvYwvVnZrf5wjjWpFXiq2tCxxi5WdsgGAbBt2opbhGwiEad9HJTU4z5diZr4FxVZGL4pnb9vqyPXb867FNt4nws')
        console.log(signatureStatus)
```

returns 

```javascript
{ context: { slot: 137551365 }, value: null }
```

But running 

```javascript
        const parsedTransaction = await solConnection.getParsedTransaction('4xvYwvVnZrf5wjjWpFXiq2tCxxi5WdsgGAbBt2opbhGwiEad9HJTU4z5diZr4FxVZGL4pnb9vqyPXb867FNt4nws')
```

does return valid information, so the transaction does exist

This is happening on `"@solana/web3.js": "^1.44.0"`

**Comment by steveluscher** [comment]
CLI repro:

```
curl https://api.mainnet-beta.solana.com -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getSignatureStatuses",
    "params": [
      [
        "4xvYwvVnZrf5wjjWpFXiq2tCxxi5WdsgGAbBt2opbhGwiEad9HJTU4z5diZr4FxVZGL4pnb9vqyPXb867FNt4nws"
      ]
    ]
  }
'
```

**Comment by steveluscher** [comment]
Is this because the signature has fallen out of the status cache, and we don't look any further, @CriesofCarrots?

**Comment by CriesofCarrots** [comment]
> Is this because the signature has fallen out of the status cache, and we don't look any further, @CriesofCarrots?

Yes, that's correct. Requests need to include the `"searchTransactionHistory":true` parameter if looking further back is resired.

**Comment by steveluscher** [comment]
@grimAgent TypeDoc maybe doesn't make it obvious, but if you click on `config?: SignatureStatusConfig` the docs for `SignatureStatusConfig` appear!
