### ISSUE TITLE
Missing meta values for transactions in long term storage

### ISSUE THREAD

**Issue by kilkka** [solana-labs/solana#25979]
#### Problem

For at least 5K transactions between blocks 67681336 and 67769677,  the `meta` field is not populated. This field is quite important because it indicates if a transaction succeeded or not.

Here are a couple examples:

Transaction: `QSYn1vjUuuKseJQby9mFg6R82inRxfJJQazcq6j5i6QyGrVuDkfEBixeqevSxFX1g83nAzkJVDcepGNtwDBRxsS`
Response:
`{
    "jsonrpc": "2.0",
    "result": {
        "blockTime": 1614971188,
        "meta": null,
        "slot": 67769677,
        "transaction": {
            "message": {...`

Transaction: `c4FMuVba6gRV6ZbdzJUW51Qr1b891T9E2qzsynM36ye2LoMbHpPVjHLQitnLpKHZXNPJ3VoNptTUx1xBiT5dHsF`
Response:
`{
    "jsonrpc": "2.0",
    "result": {
        "blockTime": 1614910700,
        "meta": null,
        "slot": 67681336,
        "transaction": {
            "message": {`

#### Proposed Solution

Reprocess the transactions between blocks 67681336 and 67769677 (inclusive) to fill in the missing values.

**Comment by 0xEdgar** [comment]
i assume you're using an RPC pointed at the solana warehouse bigtable? looks like some bug where the warehouse nodes failed to correctly upload meta for some reason? 

i think steps to fix on solana's side (or if you happen to run your own warehouse node) would be: 
- replay missing slot ranges
-  reprocess missing blocks using ledger tool and upload to warehouse node

**Comment by 0xEdgar** [comment]
threw a quick script together, the missing metas only seem to span block ranges 67681336 - 67681670 , so it's only really a couple hundred blocks.

**Comment by jstarry** [comment]
@joeaba ^

**Comment by kilkka** [comment]
Thanks for investigating it @0xEdgar. There are missing metas beyond 67681670 - for example, this transaction from  67769677 is missing them too: `QSYn1vjUuuKseJQby9mFg6R82inRxfJJQazcq6j5i6QyGrVuDkfEBixeqevSxFX1g83nAzkJVDcepGNtwDBRxsS`

Perhaps there are multiple shorter spans between 67681336 and 67769677, at least for the token program (which is all I'm looking at).

**Comment by kilkka** [comment]
Hey @joeaba, saw you've self-assigned this issue (thank you!). Please let me know if you need any more information.
