### ISSUE TITLE
Make Ledger Store reclaim disk space more efficiently and effectively

### ISSUE THREAD

**Issue by yhchiang-sol** [solana-labs/solana#26003]
#### Problem
Ledger store uses two ways to delete entries: range deletions and compaction filter.  Both require the underlying storage, rocksdb, to issue compactions in order to reclaim disk space.

To make rocksdb reclaim disk space based on our deletion pattern, it requires one of the following conditions:

* rocksdb compaction picks the right SST file that includes range deletion entries and compacts it into lower levels.  This may require several iterations of compaction in order to pass down the range-deletion entries to lower levels to eventually purge the obsolete entries and reclaim disk space.

* rocksdb compaction happens to pick an SST file where most of its entries will be filtered out by our compaction filter.

However, when rocksdb picks a file to compact, it neither prioritizes those files with range deletion entries (while it does prioritize files with many deletion entries) nor understands user-defined compaction filter logic to pick the file to compact that contains more obsolete entries.

As a result, obsolete entries might occupy disk space for a while and might contribute to the ledger disk out of space issue like https://github.com/solana-labs/solana/issues/23248.

#### Proposed Solution
Here're possible ways to make rocksdb smarter in picking the right sst files to compact.  One for range-deletion and one for compaction filter.

* [SuggestCompactRange](https://github.com/facebook/rocksdb/blob/main/include/rocksdb/experimental.h#L14-L17) approach: issue `rocksdb::SuggestCompactRange()` when we issue range-deletion that has a wider range.  This will make rocksdb prioritize those key ranges to compact.

* [CompactFiles](https://github.com/facebook/rocksdb/blob/main/include/rocksdb/db.h#L1284) based approach: Use a background thread that periodically checks the percentage of obsolete entries of each SST file and issue `CompactFiles` on those with a higher percentage.  As our compaction filter is based on the slot-id embedded in the key, the percentage of obsolete entries can be obtained based on the starting and ending key from the SST file metadata.  With this approach, we can ensure those SST files with a high percentage of obsoleted entries are processed.

* [FIFO Compaction](https://github.com/facebook/rocksdb/blob/main/include/rocksdb/advanced_options.h#L33): FIFO compaction can also help ledger store reclaim storage efficiently and effectively, as it will immediately delete the oldest file when the column family size exceeds the configured limit.  This compaction style can be enabled on data and coding shreds column families when `--rocksdb-shred-compaction` is set to `fifo` and `--rocksdb-fifo-shred-storage-size` is properly set.  The current missing part of the FIFO compaction is full ledger-tool support and smooth migration from the default level compaction to fifo compaction.

**Comment by steviez** [comment]
Thanks for breaking this into its' own issue / the writeup; thought about this a little today and some thoughts:

> [SuggestCompactRange](https://github.com/facebook/rocksdb/blob/main/include/rocksdb/experimental.h#L14-L17) approach: issue rocksdb::SuggestCompactRange() when we issue range-deletion that has a wider range. This will make rocksdb prioritize those key ranges to compact.

The range-deletion would be in a higher level (ie L0); could this potentially cause a cascade of compactions as that range-deletion propagates to lower levels? Also, it looks like `SuggestCompactRange` may skip the lowest level (note the `- 1` in loop condition in link below)? If that is correct, it seems that this function may not fit our use case, as I could imagine our oldest slot-based data hitting the lowest layer.
https://github.com/facebook/rocksdb/blob/a6691d0f65aec6ce6ff64e8e911d7cebe00621b0/db/db_impl/db_impl_experimental.cc#L38

> As our compaction filter is based on the slot-id embedded in the key, the percentage of obsolete entries can be obtained based on the starting and ending key from the SST file metadata

This seems like it could work well. Additionally, if we can get start/end key from metadata, it seems like we may be able to discard the entire file right off the bat without scanning individual keys. For example, supposed `ledger_cleanup_service` sets the `lowest_cleanup_slot` to 1000 after it issues a range-delete up to slot 1000. If any SST file contains only items in key range [200, 399], we immediately know the entire file can be discarded without having to scan. Seems like this could save some significant I/O & cycles.

**Comment by steviez** [comment]
> However, when rocksdb picks a file to compact, it neither prioritizes those files with range deletion entries (while it does prioritize files with many deletion entries) nor understands user-defined compaction filter logic to pick the file to compact that contains more obsolete entries.

I stumbled upon another option that we can tune; `CompactionPri` enum:
https://github.com/facebook/rocksdb/blob/4d31d3c2ed392657a2c28fe7362f00bced7f19c9/include/rocksdb/advanced_options.h#L41-L58

The default is:
```
  // First compact files whose ratio between overlapping size in next level
  // and its size is the smallest. It in many cases can optimize write
  // amplification.
  kMinOverlappingRatio = 0x3,
```
whereas the following would probably be more beneficial for reclaiming space quicker given that ledger_cleanup_service deletes the oldest slots
```
  // First compact files whose data's latest update time is oldest.
  // Try this if you only update some hot keys in small ranges.
  kOldestLargestSeqFirst = 0x1,
```
I might pursue this on the side; I still think your solution could give better performance / control, but this could be a potentially quicker stopgap given that it only requires setting a single value in the options struct at startup

**Comment by yhchiang-sol** [comment]
> This seems like it could work well. 

Yes, CompactFiles-based approach with start/end key would be ideal for our case.  Compared to our existing approach where we trigger compaction for any SST file whose timestamp is older than a day, the CompactFiles-based approach may be able to reclaim up to 30% additional space based on the data points we have. 

> Additionally, if we can get start/end key from metadata, it seems like we may be able to discard the entire file right off the bat without scanning individual keys. For example, supposed ledger_cleanup_service sets the lowest_cleanup_slot to 1000 after it issues a range-delete up to slot 1000. If any SST file contains only items in key range [200, 399], we immediately know the entire file can be discarded without having to scan. Seems like this could save some significant I/O & cycles.

In our case, the consistency should hold if we directly delete the entire SST file if the file's starting key is older than the oldest slot as well.  But the DeleteFile API is marked as deprecated because it could lead RocksDB into an inconsistent state if the deleted file happens to have any deletion entries or any keys that are also in a lower level.

**Comment by yhchiang-sol** [comment]
> The range-deletion would be in a higher level (ie L0); could this potentially cause a cascade of compactions as that range-deletion propagates to lower levels? Also, it looks like SuggestCompactRange may skip the lowest level (note the - 1 in loop condition in link below)? If that is correct, it seems that this function may not fit our use case, as I could imagine our oldest slot-based data hitting the lowest layer.

Yes, you're right about the current limitation of SuggestCompactRange.  I can post a PR that allows SuggestCompactRange to take CompactionOptions similar to CompactRange has.

> This seems like it could work well. Additionally, if we can get start/end key from metadata, it seems like we may be able to discard the entire file right off the bat without scanning individual keys. For example, supposed ledger_cleanup_service sets the lowest_cleanup_slot to 1000 after it issues a range-delete up to slot 1000. If any SST file contains only items in key range [200, 399], we immediately know the entire file can be discarded without having to scan. Seems like this could save some significant I/O & cycles.

Yes, with start / end keys, we only trigger compaction when we find the file has enough obsoleted entries.

**Comment by yhchiang-sol** [comment]
Updated the issue and also include FIFO compaction.

**Comment by steviez** [comment]
@yhchiang-sol - We can probably close this issue out right? https://github.com/solana-labs/solana/pull/26651 gets thing much better for level, and we have since introduced fifo as well

**Comment by yhchiang-sol** [comment]
Closing the issue as https://github.com/solana-labs/solana/pull/26651 and https://github.com/solana-labs/solana/pull/27571 have greatly improved the ledger clean-up performance and efficiency.
