### ISSUE TITLE
QUIC server connection table size can be corrupted

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#26021]
#### Problem
If a client uses the same IP:PORT pair to create multiple connections, the total size of the quic server connection table can be corrupted because it assumes that there is only one connection per IP:PORT tuple.

#### Proposed Solution
Check how many connections were removed in `fn remove_connection` and decrement that value from the total size
https://github.com/solana-labs/solana/blob/752c851070873a180d815f8b4e447e8b83be2a38/streamer/src/nonblocking/quic.rs#L377

**Comment by sakridge** [comment]
@pgarg66 can you take a look at this please?

**Comment by sakridge** [comment]
Actually I see @pgarg66 is looking at another one. @ryleung-solana can you take a look?
