### ISSUE TITLE
Refactor ConnectionCache constructor to easily deprecate UDP usecase

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#26117]
`ConnectionCache` is something we expect users of solana-client to be aware of right? 

If so, then I think it's better for `ConnectionCache::new()` to imply QUIC and there's a different constructor, `ConnectionCache::with_tpu()`, for the TPU case that can be later deprecated and removed. Otherwise we're stuck with that first `use_quic` arg even well after QUIC is enabled.

_Originally posted by @mvines in https://github.com/solana-labs/solana/pull/26105#discussion_r903095982_

**Comment by nrempel** [comment]
Hello!

I came up with a solution for this in https://github.com/solana-labs/solana/pull/26235. I would love to hear your thoughts on the approach.

cc: @mvines
