### ISSUE TITLE
`solana-keygen new`  nor `solana-keygen new -o C:\Users\Awesome\.config\solana\id.json` is not working on windows 10.  

### ISSUE THREAD

**Issue by wg-d** [solana-labs/solana#26128]
I am trying to generate key pairs to run solana locally.

But the commands mentioned are not working on my machine.

Are they for linux or mac only?

Here is the screenshot

![Screenshot_2](https://user-images.githubusercontent.com/86578241/174953920-0f14bd63-f6fa-4c6e-8415-b0f4aeea87db.png)
.

**Comment by amTechie** [comment]
I tried with cmd on windows and it worked.

**Comment by wg-d** [comment]
Thanks!
