### ISSUE TITLE
Enable callback composability

### ISSUE THREAD

**Issue by mschneider** [solana-labs/solana#26134]
#### Problem

It's increasingly difficult for integrations with Mango to reliably identify when their orders got filled. There are multiple ways to implement it, but the only way that works with >99% uptime is our core dev team to operate off-chain infrastructure for this purpose. This poses immediate concerns wrt. to censorship and decentralization, but also makes it extremely difficult for teams like cellfi to build AMMs on top of CLOBs. We consider this a major barrier of entry and want to simplify onboarding to allow more traders to operate on-chain market making.

We evaluated passing control flow to external programs via CPI from our own on-chain program state machine and leverage our decentralized keeper infrastructure that anyone can run. The only way we would consider this currently possible is to audit and statically link their integration code and ensure that it executes within a predictable compute limit. We would also force them to use immutable program code. This is all very constraining and scaling our existing off-chain approach seems like the best approach short term.

#### Proposed Solution

I think it would be good to think about how this can be realized on-chain as this is effectively offloading a lot of development overhead on a large number of teams, duplicating their efforts and slowing down ecosystem progress due to constraints in the runtime, that seems to lack primitives to support lambda / first class functions.

Ideally 3rd party programs could just register progam id and address map with my program and I can invoke their code with a fixed limit, let's say 100k CU. This should allow for double dispatch or so-called re-entrancy as well, i'd like them to be able to use my program anyway they want in this callback. In case the CU limit is hit or their program throws an error, my program should continue to execute and be able to advance it's state machine, so that this callback can not cause liveness issues for my program.

**Comment by thesoftwarejedi** [comment]
To be clear:

> In case the CU limit is hit or their program throws an error

In this case, you would expect any state that **their** program mutated was reverted back to the state it was when you initiated the CPI.  Am I correct?  Like a checkpoint and rollback.

**Comment by bonedaddy** [comment]
https://fravoll.github.io/solidity-patterns/checks_effects_interactions.html
 
> The only negative consequence of using the Checks Effects Interactions pattern is, that it is counterintuitive to use, when coming from a different programming paradigm. In other programming languages it is common procedure to apply effects after the interactions already happened. This is because it is good practice to wait for a return, stating that the function execution was successful, before making any further changes relying on the results.

> Once this mental hurdle is overcome, the Checks Effects Interactions pattern is a great way to limit the attack surface of a contract, particularly against re-entrancy attacks, because multiple encapsulated function invocations are not possible anymore. Most of the times it is easy to apply the pattern by only taking the functional code order into account, without having to change any logic. It is a good habit to use this pattern in any function making external calls, regardless of whether the other party is trustworthy or not, because even trusted external parties could transfer control to a third party, which could turn out to be malicious.

This is asking for bugs to happen, and increases developer overhead because now they need to handle error conditions returned from CPI, which could be upwards of a dozen different error conditions. This makes life as a solana developer more complicated than it already is, and any extra complications should be avoided at all cost.

**Comment by jhlx** [comment]
I think this is a great idea. Would be great to be able to fine-tune the permissions/constraints to address @bonedaddy's concern. e.g. Developers must explicitly state if it should catch reverts, if there is a CU limit, and if it should allow re-entrancy as 3 separate parameters. The existing CPIs will all obey the same semantics that exist currently.

**Comment by bonedaddy** [comment]
> I think this is a great idea. Would be great to be able to fine-tune the permissions/constraints to address @bonedaddy's concern. e.g. Developers must explicitly state if it should catch reverts, if there is a CU limit, and if it should allow re-entrancy as 3 separate parameters. The existing CPIs will all obey the same semantics that exist currently.


An opt-in format as you described sounds good, notably it wouldn't lead to vulnerabilities that arise out of this type of callback from impacting programs that either do not need to, or do not want to adopt this form of callback.
