### ISSUE TITLE
I can't able to fetch the data from the PDA account after transfer the nft.

### ISSUE THREAD

**Issue by blockchain-app12** [solana-labs/solana#26201]

**Comment by godmodegalactus** [comment]
I think you have already borrowed the reference for order above. I can see order.bump on line 49. May be you can use same reference for authority a line 56.

**Comment by blockchain-app12** [comment]
its working now.

afterwards, i can’t able to fetch the data from pda accounts.
when try to get the account details. its give the null response.

await mainProgram.provider.connection.getAccountInfo(
order.orderAccount
);

can you please explain me. it’s possible to manage the nft token in pda account.
