### ISSUE TITLE
Exit flag is not used in some stages/services

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#2621]
#### Problem
For example, broadcast service gets exit_sender flag as input parameter to new(). It creates a Finalizer object using it (to detect when the Finalizer object is dropped, and set the exit_sender flag). It also creates a new exit_signal on the stack, and uses it to exit from its run() loop. But this exit_signal is not set by any piece of code.

#### Proposed Solution
If exit_signal is not required, remove it from the code. If it's needed, hook it up with exit_flag.
Similar pattern is there in some other services/stages.

**Comment by garious** [comment]
Generally there should be an exit flag when listening on a UDP socket and nowhere else. The others can close after either all input channels are closed.

**Comment by mvines** [comment]
We've shaved a lot of yaks that roam these parts.  We're likely good here, if not re-open with more details
