### ISSUE TITLE
bench-tps udp and quic stress tests

### ISSUE THREAD

**Issue by joeaba** [solana-labs/solana#26232]
#### Problem
The UDP and QUIC stress tests are running as cron jobs from GCP clients that are currently running 24/7 which is not efficient

#### Proposed Solution
Create a buildkite pipeline that deploys X clients on GCP, builds the latest 1.10 and master, runs the tests above and reports from Influx Cloud.

**Comment by KirillLykov** [comment]
What are the metrics we are interested in for these tests?
