### ISSUE TITLE
Transfer NFT with zero amount

### ISSUE THREAD

**Issue by docongminh** [solana-labs/solana#26238]
Hi everyone. 
I conducted transfer an NFT from my wallet to another wallet. But when i re-check transaction on solscan. It showed that I transferred an NFT with amount = 0 (image below). Transaction signature on [solscan](https://solscan.io/tx/4GcftVyC1kc2mjUShURuMDtUxPm3r1x9YVyp7oBeK6zW7S9WtG9hzfKibY1quwmCPfg4fejUBkU12ELRgTnbYtyR). Could any one here help me explain why it occured ?
Actually, before this transaction occured, there is another NFT transaction to another wallet [solscan](https://solscan.io/tx/3WqsUSE53PCxg9c9gdQYBeeFjSbc1rHGpEf4Ufntofx8JfdSbpsJr1DkDrXKmoc9pLvp9ubLGZjuirjvUdr11xKH) already

![Screen Shot 2022-06-27 at 15 02 05](https://user-images.githubusercontent.com/34453681/175890511-d75bcaf1-3501-485c-ad17-3dc1e847ba05.png)

**Comment by docongminh** [comment]
@jstarry  Hi. Could you help me about this issue. Thank you !

**Comment by jstarry** [comment]
This looks like a solscan issue, please reach out to them about this issue
