### ISSUE TITLE
Solana Mobile news page missing images and has placeholder content

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana#26255]
#### Problem

https://solanamobile.com/news

<img width="1264" alt="image" src="https://user-images.githubusercontent.com/13243/176001556-c6c7470d-f1f2-4002-9f90-7bd0058dca76.png">
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/13243/176001596-81cf0ed5-2a6a-40a6-9754-aa0c175b1c26.png">
<img width="1264" alt="image" src="https://user-images.githubusercontent.com/13243/176001644-e5251019-9677-455b-bca7-574d091d2cdb.png">

**Comment by mvines** [comment]
Wrong repo!

**Comment by steveluscher** [comment]
Guh.

**Comment by timhagn** [comment]
@steveluscher And already fixed ; ).
