### ISSUE TITLE
web3.js: When `maxRetries` is set to zero, it's stripped out

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana#26295]
#### Problem

This code will fail to send the `maxRetries` parameter when it's zero.

https://github.com/solana-labs/solana/blame/89e5640c63a6683c2bd90fb963c837300ece9307/web3.js/src/connection.ts#L4239-L4241

#### Proposed Solution

Null-check the value, instead of falsey-checking it.

**Comment by steveluscher** [comment]
Interested in fixing this one up, @hareeshnagaraj?

**Comment by Mark-777-0** [comment]
I'm new to open source Could I fix this? Would you assign it to me?

**Comment by steveluscher** [comment]
Do it to it, @Mark-777-0!

**Comment by Mark-777-0** [comment]
On it!

**Comment by Mark-777-0** [comment]
I did a few tests with it and it seems to be working, it's just set up the same way as the statement below it.  And follows your proposed solution.

Let me know if I broke any etiquette. Very new to pull requests :). Not sure how to properly link it here
