### ISSUE TITLE
Gossip connection takes a while to connect in startup

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#26290]
#### Problem

When looking at startup time, waiting for entries to come in via gossip is somewhat a bottleneck for finding a snapshot to download if needed.

#### Proposed Solution

A special startup mode to prioritize ContactInfo and snapshot hashes might be used to fetch the relevant data more quickly.

**Comment by behzadnouri** [comment]
cross posting from discord:
https://discord.com/channels/428295358100013066/439194979856809985/1063104262709719110

`7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2` for recent restart around `2023-01-10 04:58` took like ~30 seconds to do the initial sync (on mainnet).
![gossip-sync](https://user-images.githubusercontent.com/1288998/212357496-585c780a-9d30-4dc1-b8ec-dfeae06894b9.png)

**Comment by behzadnouri** [comment]
Double checked this on mainnet for recent restarts of `bv[1-4]` nodes.
The data consistently shows that it takes less than 1 minute to obtain 95%+ of gossip table.
![gossip-sync](https://github.com/solana-labs/solana/assets/1288998/d3d9bb0d-4ef0-4bea-bc87-86524b59305e)
