### ISSUE TITLE
Default::default() makes code unreadable

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#2630]
#### Problem

Rust offers us this convenient feature of setting any type that implements `Default` to its default using `Default::default()`. Unfortunately it makes the code unreadable.

#### Proposed Solution

Replace most of the 72 instances in current code with an explicit type. For example, if the function accepts a `Pubkey`, replace `Default::default()` with `Pubkey::default()`.

**Comment by ryoqun** [comment]
seems clippy now supports natively: https://rust-lang.github.io/rust-clippy/v0.0.212/index.html#default_trait_access
