### ISSUE TITLE
web3.js Roadmap – July 2022 – Discussion thread

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana#26342]
What do you want to see accomplished in @solana/web3.js in the month of July 2022?

Milestone: https://github.com/solana-labs/solana/milestone/198

**Comment by beeman** [comment]
It would be great if we could improve compatibility with running `@solana/web3.js` in the browser like so:

```html
<script type="module" >
  import { Connection, Keypair, clusterApiUrl } from "https://unpkg.com/@solana/web3.js"
 
  const kp = Keypair.generate()
  const conn = new Connection(clusterApiUrl('devnet'))
</script>
```

[Example here](https://jsfiddle.net/9p7mh4kv/)

It might be easier to aim at making it work with Skypack:

```html
<script type="module" >
  import { Connection, Keypair, clusterApiUrl } from "https://cdn.skypack.dev/@solana/web3.js"
 
  const kp = Keypair.generate()
  const conn = new Connection(clusterApiUrl('devnet'))
</script>
```

[Example here](https://jsfiddle.net/9p7mh4kv/1/)

SkyPack seems to fail on `uuid4` that's a dependency of `json`:
![image](https://user-images.githubusercontent.com/36491/176823459-8a3dae65-f346-4aff-9770-4fbaa4e55967.png)

If it's hard to fix these upstream deps another option might be to ship a fatter bundle that includes some of the deps. By far not ideal (and basically the opposite of #20673) but it would make Solana work on platforms without a build step (no-code solutions, CMS, web-based IDEs, etc).

**Comment by beeman** [comment]
## Support for mnemonic phrases

Currently, any application that wants to support mnemonic phrases needs to look at how others implement this to maintain compatibility with the rest of the ecosystem. 

It would be good to standardize this and implement it in an official Solana library like `@solana/keypair` (possibly together with the other Keypair classes).

**Comment by steveluscher** [comment]
Created issue to address browser bundles: #26371.

**Comment by beeman** [comment]
## Serialize lastValidBlockHeight on Transaction

The `lastValidBlockHeight` property is not serialized on the `Transaction` object.

I would expect this to pass when added [here](https://github.com/solana-labs/solana/blob/master/web3.js/test/transaction.test.ts#L617)

```ts
expect(deserializedTransaction.lastValidBlockHeight).to.eql(9999);
```

I looked at adding it but it doesn't seem trivial. I'm also not sure what we lose in not having that property being de-serialized on the API.

**Comment by steveluscher** [comment]
> Serialize lastValidBlockHeight on Transaction

There is a set of unfortunate properties on `Transaction` that:

1. Only exist because `sendAndConfirmTransaction()` wants them,
2. Should not be there.

These are properties like `lastValidBlockHeight` and `minContextSlot`. They are ultimately ‘transaction confirmation’ details, and don't belong on the transaction object.

We _should_ have made `sendAndConfirmTransaction` take both a transaction _and_ confirmation params, but alas, we'll have to wait for #25314.

**Comment by steveluscher** [comment]
> Support for mnemonic phrases

Before this discussion thread gets closed out @beeman, do you want to move this into a GitHub issue? I don't know exactly where this should live, or if it should be Solana Labs Official™, but I don't want the thought to be lost as July turns to August.

**Comment by steveluscher** [comment]
That's a wrap on July! Onward to August. https://github.com/solana-labs/solana/milestone/199.

**Comment by beeman** [comment]
> > Serialize lastValidBlockHeight on Transaction
> 
> There is a set of unfortunate properties on `Transaction` that:
> 
>     1. Only exist because `sendAndConfirmTransaction()` wants them,
> 
>     2. Should not be there.
> 
> 
> These are properties like `lastValidBlockHeight` and `minContextSlot`. They are ultimately ‘transaction confirmation’ details, and don't belong on the transaction object.
> 
> We _should_ have made `sendAndConfirmTransaction` take both a transaction _and_ confirmation params, but alas, we'll have to wait for #25314.

Ok, that makes sense. In that case, I'll keep on sending `lastValidBlockHeight` to the backend separately instead of serializing.
