### ISSUE TITLE
PubsubClient subscription channel disconnects

### ISSUE THREAD

**Issue by callensm** [solana-labs/solana#26343]
#### Problem

Using the `PubsubClient::logs_subscribe` function, the `crossbeam_channel::unbonded` disconnects after a random amount of time (typically within 30 seconds - 2 minutes) with:

```
receiving on an empty and disconnected channel
```

Code that produces unexpected results:

```rs
use solana_client::pubsub_client::PubsubClient;
use solana_client::rpc_config::{RpcTransactionLogsConfig, RpcTransactionLogsFilter};
use solana_sdk::commitment_config::CommitmentConfig;

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let (_sub, receiver) = PubsubClient::logs_subscribe(
        MY_WSS_ENDPOINT,
        RpcTransactionLogsFilter::Mentions(vec![
            MY_PROGRAM_ID.into()
        ]),
        RpcTransactionLogsConfig {
            commitment: Some(CommitmentConfig::processed()),
        },
    )?;

    loop {
        match receiver.recv() {
            Ok(logs) => {
                if !logs.value.logs.is_empty() {
                    for log in logs.value.logs {
                        if let Some(l) = log.strip_prefix("Program data: ") {
                            println!("{}", l);
                        }
                    }
                }
            }
            Err(e) => {
                println!("[ERR] {}", e);
                std::process::exit(1);
            }
        }
    }
}
```

> Uses `solana-client` and `solana-sdk` version `1.10`.

I would expect this to continuously listen and print program logs as the are received through the `receiver` channel from the subscription, but perhaps there is something that is causing unexpected websocket connection drops or channel mishandling in the implementation (?).

> This only occurs with the Rust client subscriptions. I have already tried with the nodejs/ts and golang clients without issue.

Has anyone else experienced this inconsistency in ws/channel performance using this client?

**Comment by itsfarseen** [comment]
I am trying to debug this using [`websocat`](https://github.com/vi/websocat) 
It looks like it's failing on this line up on receiving websocket ping/pong message: https://github.com/solana-labs/solana/blob/2481ebb1501f1f02937b1b1ea925943254125af2/client/src/pubsub_client.rs#L171

**Comment by TovarishFin** [comment]
Hey so I ran into the same thing today and got pretty annoyed with this. Some hunch led me to try the async version of this and it seemed to work. It still seems that the non-async version of the pubsub_client is broken... but if, practically speaking, you are trying to get things done... just use the non-blocking version. This would be something like the following:

```rust
use anyhow::Result;
use futures::prelude::*;
use solana_client::{
    nonblocking::pubsub_client::PubsubClient,
    rpc_config::{RpcTransactionLogsConfig, RpcTransactionLogsFilter},
};
use solana_sdk::commitment_config::CommitmentConfig;

// const RPC_URL: &str = "https://api.devnet.solana.com";
const WS_URL: &str = "wss://api.mainnet-beta.solana.com";

#[tokio::main]
async fn main() -> Result<()> {
    let client = PubsubClient::new(WS_URL).await?;
    let (mut stream, _) = client
        .logs_subscribe(
            RpcTransactionLogsFilter::All,
            RpcTransactionLogsConfig {
                commitment: Some(CommitmentConfig::processed()),
            },
        )
        .await?;

    loop {
        let slot = stream.next().await.unwrap();
        println!("slot: {:?}", slot);
    }
}
```
