### ISSUE TITLE
Incomprehensible growth of `accounts`

### ISSUE THREAD

**Issue by diman-io** [solana-labs/solana#26375]
#### Problem

Time on the pictures is **UTC+3**

Last 30 days:
Drops on the chart are restarts.
<img width="634" alt="image" src="https://user-images.githubusercontent.com/71597545/177007237-f1da5eb6-7752-48c1-8d3c-c60fc1f2c275.png">

Last 24 hours:
<img width="630" alt="image" src="https://user-images.githubusercontent.com/71597545/177007253-57e1c60c-149c-4a6b-a9f7-5e4e529469ab.png">

Last 2 hours:
<img width="628" alt="image" src="https://user-images.githubusercontent.com/71597545/177007316-cc0a9333-7d60-4592-9596-239cff4b753c.png">

Log from 14:00 to 14:30 (17:00 - 17:30 on the picture)
https://drive.google.com/file/d/1Pe569W9u0Iv-mid-Q-2r16UMwO93pjVa/view

First time I mentioned this here https://github.com/solana-labs/solana/issues/26259#issuecomment-1169116655

**Comment by yokosta** [comment]
only the growth of the given metric, update the node, and again
<img width="1403" alt="example" src="https://user-images.githubusercontent.com/79849905/183063257-3b8cbbd1-a069-4f2d-b4e9-6321be8b07ab.png">
.

**Comment by jeffwashington** [comment]
Andrew and I ran into this issue today. We are investigating with @brooksprumo.

**Comment by jeffwashington** [comment]
https://discord.com/channels/428295358100013066/1008859241689399297/1008861578956918794

**Comment by diman-io** [comment]
I found that the jump in the number of open files does not start when snapshots are enabled.
Before that it was disabled (*-snapshot-interval-slots 0).
After it were enabled a smooth growth continues, but there is no rapid growth.
So this trick can be used for debugging (But the jump event will have to wait one-two days :( )

**Comment by diman-io** [comment]
@jeffwashington @brooksprumo I'm sorry for pinging, just to make sure you don't miss 👆

**Comment by diman-io** [comment]
@brooksprumo I didn't see this issue on my testnet node anytime

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/71597545/190891896-ac9ec653-e11e-42e1-9d13-b434ba2e0619.png">

Thank you, I'll pull in #27650 at next update.
