### ISSUE TITLE
client: Use `skip_serializing_none` in rpc_config.rs

### ISSUE THREAD

**Issue by kevinheavey** [solana-labs/solana#26374]
#### Problem

There are dozens of optional fields in [rpc_config.rs](https://github.com/solana-labs/solana/blob/6b82235fab155ef80e990309d693bf2045e2ee4e/client/src/rpc_config.rs). While the RPC server supports omitting these optional fields, `solana_client` serializes them as `"fieldName":null` instead of omitting them. For example, `RpcContextConfig { commitment: None, min_context_slot: 1234 }` gets JSON-serialized as `{"commitment":null, "minContextSlot":1234}` instead of just `{"minContextSlot":1234}`.

This bloats the payload and is (in my opinion) messier.

#### Proposed Solution (Edited 2022-07-04)

Use [skip_serializing_none](https://github.com/solana-labs/solana/blob/6b82235fab155ef80e990309d693bf2045e2ee4e/client/src/rpc_config.rs) from the `serde_with` crate along with `#[serde(default)]`. For example, `RpcContextConfig` would change from this:

```
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RpcContextConfig {
    #[serde(flatten)]
    pub commitment: Option<CommitmentConfig>,
    pub min_context_slot: Option<Slot>,
}
```

to this:

```
#[skip_serializing_none]
#[derive(Debug, Clone, Copy, Default, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RpcContextConfig {
    #[serde(flatten, default)]
    pub commitment: Option<CommitmentConfig>,
    #[serde(default)]
    pub min_context_slot: Option<Slot>,
}
```

I'm happy to make a PR for this if it'll get approved.

**Comment by CriesofCarrots** [comment]
@kevinheavey, you're just talking about input fields that get sent to the RPC server, correct?
If so, I think we could actually do this. I'd review a PR to do this, if you're still willing after all this time!
