### ISSUE TITLE
TpuClient problem in bench-tps when running own cluster

### ISSUE THREAD

**Issue by KirillLykov** [solana-labs/solana#26379]
#### Problem

TpuClient doesn't work when running `bench-tps` towards private cluster created with `net` scripts:

```bash
=== Client start: Wed 29 Jun 2022 02:20:14 PM PDT
$     solana-bench-tps       --entrypoint 10.138.0.201:8001       --duration 7500       --sustained       --threads 4       --use-tpu-client       --read-client-keys ./client-accounts.yml
[2022-06-29T21:20:14.575090048Z INFO  solana_bench_tps] Connecting to the cluster
[2022-06-29T21:20:14.957000793Z INFO  solana_bench_tps::keypairs] Reading ./client-accounts.yml
[2022-06-29T21:22:31.602104002Z INFO  solana_bench_tps::bench] Get lamports...
[2022-06-29T21:22:31.697126218Z INFO  solana_bench_tps::bench] Funding keypair balance: 0 max_fee: 5000 lamports_per_account: 1001816866 extra: 998100 total: 1400646152671466
[2022-06-29T21:22:31.697161840Z ERROR solana_bench_tps::bench] funder has ◎0.000000000, needed ◎1400646.152671466
Error could not fund keys: AirdropFailure
=== Client start: Wed 29 Jun 2022 02:20:14 PM PDT
```

At the same time ThinClient works fine.
Didn't manage to reproduce the problem in the test environmet or using multinode-demo scripts.

**Comment by KirillLykov** [comment]
Some evidences from Lijun:

* Change in 934da5ef992899f7eb5f061f575c69d19ffa78ce might be the source of issue
* To have progress on his issue, he had to hack that change out:
commenting out the following code:  
```rust
ledger-tool/src/main.rs
    if let Some(halt_slot) = process_options.halt_at_slot {
        // Check if we have the slot data necessary to replay from starting_slot to halt_slot.
        //  - This will not catch the case when loading from genesis without a full slot 0.
        if !blockstore.slots_connected(starting_slot, halt_slot) {
            eprintln!(
                "Unable to load bank forks at slot {} due to disconnected blocks.",
                halt_slot,
            );
            exit(1);
        }
    } 
 ```
 
 * The problem is with doing the airdrops. Without airdrops I cannot do the tests which requires accounts to have lamports.
 ```
./net/net.sh stop
./net/net.sh start --internal-nodes-stake-lamports 1000000000000 --extra-primordial-stakes 3 --faucet-lamports 500000000000000000 --slots-per-epoch 432000 --tpu-use-quic
```

**Comment by KirillLykov** [comment]
The same is true for `--use-rpc-client`

**Comment by sowhu** [comment]
When using tpu or rpc client, need to tell the lcient the location of the RPC node, using --url/-u parameter. With this, now I see the tpu client can successfully run. But rpc client encounters a panic:

thread 'main' panicked at 'transfer: ClientError(Error { request: Some(SendTransaction), kind: RpcError(RpcResponseError { code: -32002, message: "Transaction simulation failed: Attempt to debit an account but found no record of a prior credit.", data: SendTransactionPreflightFailure(RpcSimulateTransactionResult { err: Some(AccountNotFound), logs: Some([]), accounts: None, units_consumed: Some(0), return_data: None }) }) })', /home/sol/solana/bench-tps/src/send_batch.rs:248:34
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5
   3: core::result::Result<T,E>::expect
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1055:23
   4: <alloc::vec::Vec<(T,solana_sdk::transaction::Transaction)> as solana_bench_tps::send_batch::SendBatchTransactions<T>>::send
             at ./bench-tps/src/send_batch.rs:248:9
   5: <alloc::vec::Vec<(T,solana_sdk::transaction::Transaction)> as solana_bench_tps::send_batch::SendBatchTransactions<T>>::send_transactions
             at ./bench-tps/src/send_batch.rs:221:13
   6: <alloc::vec::Vec<(&solana_sdk::signer::keypair::Keypair,solana_sdk::transaction::Transaction)> as solana_bench_tps::send_batch::FundingTransactions>::fund
             at ./bench-tps/src/send_batch.rs:379:9
   7: solana_bench_tps::send_batch::fund_keys::{{closure}}
             at ./bench-tps/src/send_batch.rs:86:13
   8: core::iter::traits::iterator::Iterator::for_each::call::{{closure}}
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/iter/traits/iterator.rs:784:29
   9: core::iter::traits::iterator::Iterator::fold
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/iter/traits/iterator.rs:2370:21
  10: core::iter::traits::iterator::Iterator::for_each
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/iter/traits/iterator.rs:787:9
  11: solana_bench_tps::send_batch::fund_keys
             at ./bench-tps/src/send_batch.rs:85:9
  12: solana_bench_tps::bench::fund_keypairs
             at ./bench-tps/src/bench.rs:983:9
  13: solana_bench_tps::bench::generate_and_fund_keypairs
             at ./bench-tps/src/bench.rs:912:5
  14: solana_bench_tps::keypairs::get_keypairs
             at ./bench-tps/src/keypairs.rs:66:9
  15: solana_bench_tps::main
             at ./bench-tps/src/main.rs:226:20
  16: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5

There might be something other parameters are missing when running rpc client.

**Comment by KirillLykov** [comment]
it was resolved meanwhile
