### ISSUE TITLE
Feature Gate: Enable the `ExtendProgram` ix for the bpf upgradeable loader

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#26385]
### Description

See #26386

Add a feature gate to enable a new `ExtendProgram` instruction which is permission less and allows extending the program data by a specified number of bytes so that developers don't need to pre-allocate program data accounts.

#### Note
Do NOT activate this before [enable program redeployment cooldown](https://github.com/solana-labs/solana/issues/29135).

### Feature ID

8Zs9W7D9MpSEtUWSQdGniZk2cNmV22y6FLJwCx53asme

### Activation Method

Single Core Contributor

### Minimum Version

v1.16.0

### Testnet Activation Epoch

492

### Devnet Activation Epoch

547

### Mainnet-Beta Activation Epoch

532

**Comment by mgild** [comment]
What is eta for this?

**Comment by jstarry** [comment]
> What is eta for this?

Needs to get reviewed, audited, and then activated via feature gate. I'm hoping to get this feature into v1.11 and will activate it once each cluster is fully upgraded to that version.

**Comment by zlex7** [comment]
thanks for working on this @jstarry! any guidance on earliest possible 1.11 release?

**Comment by jstarry** [comment]
> thanks for working on this @jstarry! any guidance on earliest possible 1.11 release?

It will be enabled on testnet soon but it's quite difficult to predict when mainnet will be updated to v1.11 at this time

**Comment by mardragon** [comment]
It's great change @jstarry. Will `solana program deploy` CLI command handle resizing automatically ? 

In description you wrote `extending`, I assume we can also shrink it and recover unused SOL ?

**Comment by jstarry** [comment]
> Will solana program deploy CLI command handle resizing automatically ?

That would be a nice feature, but not implemented yet in the CLI

> I assume we can also shrink it and recover unused SOL ?

The length of the program data isn't stored in the metadata so it's not possible to know how much data can be shrunk safely. That could be implemented though and added as a separate feature.

**Comment by iurage** [comment]
@jstarry Would you have any idea when this would hit mainnet?

**Comment by jstarry** [comment]
> @jstarry Would you have any idea when this would hit mainnet?

When mainnet is running v14.. hopefully not too long but it could take months

**Comment by Timikcool** [comment]
> > @jstarry Would you have any idea when this would hit mainnet?
> 
> When mainnet is running v14.. hopefully not too long but it could take months

sheesh we need it a lot

**Comment by enzoampil** [comment]
hope this is out soon, badly needed for our side as well

**Comment by ADBalici** [comment]
Yeah also hope this is deployed soon.

**Comment by dr497** [comment]
Is there a rough ETA for when it will be deployed?

**Comment by mvines** [comment]
This gate is on the schedule at https://github.com/solana-labs/solana/wiki/Feature-Gate-Activation-Schedule, and is the 25th (if I counted right) feature gate in the 1.14 release line. So best case, it'll be activated 25 epochs after mainnet adopts the 1.14 release line

**Comment by Lichtso** [comment]
Sorry everybody who has been patently waiting. We will have to delay this until we fix our executor cache (https://github.com/solana-labs/solana/issues/29803).

**Comment by ilmoi** [comment]
@Lichtso do you have a rough timeline in mind?

**Comment by Lichtso** [comment]
> do you have a rough timeline in mind?

It is making good progress so we should have something on testnet by the next release cycle. Though it will take a lot longer until it hits MNB. Unfortunately our current design makes it hard to implement this right.

---

@ilmoi @dr497 @ADBalici @enzoampil @Timikcool @iurage @mardragon @zlex7 @mgild
Hate to ping you all like this, but if you are still interested in improving the program management workflow, I would like some feedback on the design of our new loader built-in program, which also comes with a new program management workflow over here: https://github.com/solana-labs/solana/pull/30318

**Comment by blockiosaurus** [comment]
Are there any updates on the timeline of this feature? It looks like it got pushed back several minor versions but we're really hurting for more binary space.

**Comment by FoxyDev42** [comment]
Would like an update on this too, out of space on multiple programs, very hard to fit in due to evolving metaplex updates and stuff.

**Comment by mvines** [comment]
This feature is still on the master branch, will ship in the v1.16 release line. When this reaches mainnet depends on how quickly the validators choose to adopt the v1.14 release so that we can begin stabilizing v1.16

**Comment by Flawm** [comment]
excellent

**Comment by KuGau0xxx** [comment]
> What is eta for this?

https://fineasier.com/credit-card-wells-fargo-reflect-rec/?utm_source=email&utm_medium=email&utm_campaign=e09seq02em01-us-cc

**Comment by Lichtso** [comment]
It is place 3 in the [Feature-Gate-Activation-Schedule](https://github.com/solana-labs/solana/wiki/Feature-Gate-Activation-Schedule) of MNB so should be in the next few weeks.

**Comment by jstarry** [comment]
FYI this feature was activated a few days ago in epoch 532 on mainnet-beta

**Comment by jstarry** [comment]
Once the feature gate code is cleaned up it will be closed
