### ISSUE TITLE
Is ed25519ph signature supported by Solana

### ISSUE THREAD

**Issue by chandraprakash** [solana-labs/solana#26389]
#### Problem
Hi Team,
Is ed25519ph signature supported by Solana.
I tried to submit ed25519ph signed transaction to Solana testnet and it failed preflight check with `Transaction signature verification failure`.

On disabling the preflight check, I got the tx id, but unable to find it on solana testnet explorer.

ed25519ph is similar to ed25519 with a difference.
In ed25519ph, we first sha512 hash the message and then pass it to the signer. Signer skips the the initial hashing and signs the hash.
Found this article useful to understand the difference between ed25519 and ed25519ph: 
https://www.cryptologie.net/article/497/eddsa-ed25519-ed25519-ietf-ed25519ph-ed25519ctx-hasheddsa-pureeddsa-wtf/ 

Please let me know if it supported (or supported in future).
Thanks!

**Comment by mvines** [comment]
Answered on Discord

**Comment by chandraprakash** [comment]
thanks!
