### ISSUE TITLE
client: move non-IO parts of solana-client into their own crate (or put the other stuff behind a feature gate)

### ISSUE THREAD

**Issue by kevinheavey** [solana-labs/solana#26384]
#### Problem

`solana_client` has some components that are useful for building RPC requests even if you're not using `solana_client` to actually send those requests. However, the networking parts of `solana_client` have some dependencies that aren't portable (such as `solana_streamer`).

For example, I'm trying to use `rpc_config` and `rpc_filter` in `solders`, but `solana_streamer` [doesn't compile](https://github.com/kevinheavey/solders/runs/7179140890?check_suite_focus=true) on all the platforms I want to support.

#### Proposed Solution

Extract `rpc_config`, `rpc_filter`, `rpc_request`, and `rpc_response` into a separate crate, or put the I/O parts of `solana_client` behind a feature gate.

**Comment by acheroncrypto** [comment]
This was a problem for `wasm32` target as well. It would be great to have it in the main repo but time was important to me so I made couple of crates for my usecase, one of them being [solana-client-wasm](https://crates.io/crates/solana-client-wasm).

**Comment by CriesofCarrots** [comment]
@kevinheavey , I believe your use-case is addressed with the `solana-rpc-client-api` crate that will come with v1.15: https://github.com/solana-labs/solana/tree/master/rpc-client-api
Can you confirm? Thanks!

**Comment by kevinheavey** [comment]
@CriesofCarrots I will check and confirm but iirc the reqwest dependency there is enough to break portability

**Comment by CriesofCarrots** [comment]
I do have removing reqwest on the radar here: https://github.com/solana-labs/solana/issues/27352
This issue only refers to `solana-streamer` by name, however, so not clear to me what else is a blocker. Thanks!
