### ISSUE TITLE
AccountsDB could store diff updates

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#26405]
#### Problem

Some transactions like to reference a larger account buffer but may only do a small update on each transaction. AccountsDB will 
store the complete version of the new state which could be on the order of multiple MB when only a few Kb of state is updated.

Market order books are a good example of this

#### Proposed Solution

Look into storing diff updates from a previous state in AccountsDB.

**Comment by terorie** [comment]
To assist with diff generation, the SBF VM could track which account regions are written to via a hook in the memory address translation function.
