### ISSUE TITLE
bincode is not optimal

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#26406]
#### Problem

For serialize/deserialize the validator uses bincode in many cases but bincode is known to not be optimal.

#### Proposed Solution

Convert bincode use-cases to other faster serialization libraries like speedy/borsh/capnproto. A more universal format would be nicer for interconnection with other languages and environments as well.

- [ ] Transactions
- [ ] Repair
- [ ] Gossip
- [ ] Shred payload

**Comment by brennanwatt** [comment]
The major hangup I've encountered hacking at this quickly is deriving traits for the GenericArray struct (part of Signature struct)

**Comment by brennanwatt** [comment]
Quick comparison between bincode and borsh running `cargo test --release --package solana-ledger --lib -- shredder::tests::test_data_shredder --exact --nocapture`:
Bincode (Default)
- 1000 entries with size 64B
- serialize_time = 209us
- 251 shreds with size 184
- deserialize_time = 845us

Borsh
- 1000 entries with size 64B
- serialize_time = 169us
- 262 shreds with size 184
- deserialize_time = 311us

**Comment by brennanwatt** [comment]
Given how sensitive our system is to shred volume, I'm wondering if something like [postcard](https://crates.io/crates/postcard) is the best option
