### ISSUE TITLE
How to Traverse the blocks of transactions in solana blockchain

### ISSUE THREAD

**Issue by DubheAlkaid** [solana-labs/solana#26430]
#### Problem

I want to get all transactions by [Solana Cluster RPC Endpoints](https://docs.solana.com/cluster/rpc-endpoints). [JSON RPC API](https://docs.solana.com/cluster/rpc-endpoints) provide [getBlock](https://docs.solana.com/developing/clients/jsonrpc-api#getblock) to get transactions of block, it's limit `Maximum number of requests per 10 seconds per IP: 100`.

我想通过公共的 JSON RPC API 遍历 Solana区块得到所有的交易，但是Solana出块速度太快了，超过了  JSON RPC API调用限制。如何得到所有区块

**Comment by steveluscher** [comment]
Thanks for your question!

We want to make sure to keep signal strong in the GitHub issue tracker – to make sure that it remains the best place to track issues that affect the development of Solana itself.

Questions like yours deserve a purpose-built Q&A forum. Please post your question to the Solana Stack Exchange using this link: https://solana.stackexchange.com/questions/ask
