### ISSUE TITLE
When creating a snapshot, ledger tool should check the blockstore has the desired slot

### ISSUE THREAD

**Issue by buffalu** [solana-labs/solana#26475]
#### Problem
The feedbackk loop for determining if blockstore has a desired slot is super slow. Takes ~15 minutes to find out that you don't have a desired slot when trying to create a snapshot.

#### Proposed Solution
When blockstore is loaded, check to make sure the desired slot you'd like to replay to is present

**Comment by steviez** [comment]
@buffalu - Which version of `solana-ledger-tool` were you using? The following PR makes it so we traverse across slots to their children to see if it can make it to the desired snapshot slot.
https://github.com/solana-labs/solana/pull/25632

If you are using a version that has this commit, then it is possible that there is a bug or some case that @apfitzge and I didn't consider in that check

**Comment by buffalu** [comment]
i think it might be another issue which i mentioned in discord. pasting the full comment here:

```
$ cat bounds.txt
Ledger has data for 414702 slots 138670243 to 139104028
  with 370127 rooted slots from 138670243 to 139103980
  and 42 slots past the last root
$ RUST_LOG=info solana-ledger-tool -l /mnt/disks/disk2 create-snapshot 138671999
... tons of logs
[2022-07-07T16:42:11.862188957Z INFO  solana_ledger::blockstore_processor] ledger processed in 17 ms, 429 µs and 285 ns. root slot is 138670016, 1 bank: 138670016
Error: Slot 138671999 is not available
```

so the first snapshot at the top level is snapshot-138670016-....tar.zst. 
the first one in hourly is snapshot-138680309-....tar.zst.
the ledger is supposedly 138670243 to 139104028.

time ->
-----snapshot 138670016 --------- ledger start 138670243 ----- snapshot 138680309


is the problem that this snapshot has a gap from the top level snapshot to the start of ledger? you basically need to start at the snapshot that's above the minimum ledger start slot?

**Comment by buffalu** [comment]
this was downloaded from ny bucket 5 snapshot 138670016.

perhaps the issue is that there's no snapshot that lines up with the beginning of ledger start, so you can only start processing from the first snapshot you have?

**Comment by steviez** [comment]
> which i mentioned in discord

Thanks for transcribing - I prefer GH once we hone in on a specific problem.

> is the problem that this snapshot has a gap from the top level snapshot to the start of ledger?

Yes

> you basically need to start at the snapshot that's above the minimum ledger start slot?

Yes, a full snapshot at slot `S` will give you the full account state at slot `S`. If you want to know the account state for slot `S + n`, you need the blocks in `[Sc, S + n]` where `Sc` is `S`'s direct child.

Also, the folder you included is for epoch 321; the [slot range](https://explorer.solana.com/epoch/321) is `[138_672_000, 139_103_999]`. So, that first snapshot is technically outside of the epoch bounds.

**Comment by steviez** [comment]
Also, you probably already know this but just incase someone less familiar is reading along - the snapshots in `hourly` subdirectory won't be found by `solana-ledger-tool`. That is, if you pass `--snapshot-archive-path <SOME_DIR>` to `solana-ledger-tool`, snapshots in `<SOME_DIR>/sub_directory/` won't be found.

**Comment by buffalu** [comment]
i didn't know that, thanks for the heads up

**Comment by steviez** [comment]
I'd have to dig further to confirm, but I believe we put them in the `hourly` subdirectory to avoid having the automatic snapshot retention policy nuke them on warehouse nodes.

> Takes ~15 minutes to find out that you don't have a desired slot when trying to create a snapshot.

Bringing things back to actionable items, did you check which version of `solana-ledger-tool` you were using? That check I previously mentioned happens before snapshot is unpacked, so there should be minimal time wasted if we don't have the proper blockstore data to advance from existing snapshot slot to desired snapshot creation slot

**Comment by buffalu** [comment]
i was running 1.10.29. 

is the issue that blockstore had those slots so that passed, but it didn't have the snapshot so it just loaded what it had?

**Comment by steviez** [comment]
> i was running 1.10.29.

Ahh, the check was added to master recently, and wasn't backported. So only in master / v1.11.

**Comment by steviez** [comment]
> is the issue that blockstore had those slots so that passed, but it didn't have the snapshot so it just loaded what it had?

To provide more detail, that error comes from here:
https://github.com/solana-labs/solana/blob/d9eee72edb29f90bdd307ffd143739e34eb2bbf0/ledger-tool/src/main.rs#L2515-L2523

This is after bank_forks are loaded; processing stopped much earlier so we don't have the bank for desired snapshot creation slot. This error could probably be better, I'll look at tweaking the message to be more clear

**Comment by buffalu** [comment]
right, it takes ~15 minutes to get there even if you don't have that snapshot. would be nice to catch it earlier

**Comment by steviez** [comment]
> That check I previously mentioned happens before snapshot is unpacked, so there should be minimal time wasted

> the check was added to master recently, and wasn't backported. So only in master / v1.11.

We catch it earlier in master

**Comment by steviez** [comment]
Closing this - https://github.com/solana-labs/solana/pull/25632 added a check in `v1.11` that verifies appropriate slots exist prior to creating snapshot
