### ISSUE TITLE
getSignaturesForAddress/getTransaction will not return reliable result if called on node started from snapshot

### ISSUE THREAD

**Issue by chandraprakash** [solana-labs/solana#26497]
#### Problem

Hi Team,
I am running a testnet node (no vote mode). I have started it with a snapshot and now all synced up. 
Now for a given address/account which existed before I started my testnet node, I am unable to get all the transactions using getSignaturesForAddress rpc.
Calling same rpc to public node is returning me all the transaction signature for my account. 
Also, when I try to call getTransaction for older transactions (happened before my node started) on my node, it doesn't return the transactions.

My question is:
1. Is it the correct behavior of the system (Nodes started from snapshot will not even have information about previous transaction signatures / transactions)?
2. Will there be any difference on behavior on using mainnet?

Thanks

**Comment by GeassV** [comment]
Same issue on mainnet, any solution yet?

**Comment by CriesofCarrots** [comment]
> 1. Is it the correct behavior of the system (Nodes started from snapshot will not even have information about previous transaction signatures / transactions)?

Yes, this is the correct behavior. Unless it is hooked up to a historical archive, a node booted from a snapshot will not have ledger data from before the snapshot.
