### ISSUE TITLE
Feature Gate: preserves rent_epoch for rent exempt accounts

### ISSUE THREAD

**Issue by behzadnouri** [solana-labs/solana#26509]
### Description

https://github.com/solana-labs/solana/pull/22292 prevents rent paying account creation going forward. As a result
`rent_epoch` field for rent exempt accounts is redundant, and advancing
this field will incur expensive account rewrites and cause discrepancy
between accounts-db and cached vote/stake accounts.

https://github.com/solana-labs/solana/pull/26479 adds a feature which upon activation preserves `rent_epoch`
field for rent exempt accounts so that the field is frozen and is no
longer advanced.

### Feature ID

HH3MUYReL2BvqqA3oEcAa7txju5GY6G4nxJ51zvsEjEZ

### Activation Method

Single Core Contributor

### Minimum Beta Version

`v1.11.5`

### Minimum Stable Version

`v1.10.34`

### Testnet Activation Epoch

350

### Devnet Activation Epoch
372

### Mainnet-Beta Activation Epoch
362

**Comment by bardo-hub** [comment]
33
