### ISSUE TITLE
Need an RPC api to estimate the fee user should pay

### ISSUE THREAD

**Issue by taozhu-chicago** [solana-labs/solana#26561]
#### Problem

Users need to know the estimated minimum compute-unit price that their transactions should have in order to land in block.

The estimation should be taken from recent (up to 150) blocks; for each block, it checks:
1. The min compute-unit price of transactions in that block; and
2. The min compute-unit price for each writeable accounts in user's transaction, in that block;
The estimated min compute-unit price for user's transaction should therefore be `max(#1, #2)`. Note, there could be multiple values in `#2` - one for each writable account.

##### For example:
A block has following transactions:
```
TX,  compute-unit price, write accounts
--------------------------------------
#1   100                 A, B, C
#2   50                  A, C
#3   1                   D
```
Then
1. The min compute-unit price for block is `1`, set by transaction 3;
2. The min compute-unit price for account A is `50`, set by transaction 2;
3. The min compute-unit price for account B is `100`, set by transaction 1;
4. The min compute-unit price for account C is `50`, set by transaction 2;
5. The min compute-unit price for account D is `1`, set by transaction 3;
6. The min compute-unit price for any other accounts will be `0`;

So based on this block, the min estimated fee for a transaction that writes to account A, D and Z would be `max(min_block_fee, min_account_A_fee, min_account_D_fee, min_account_Z_fee) = max(1, 50, 1, 0) = 50`.

For user query of "what is the estimated min compute-unit price for my transaction that writes to A, D and Z", RPC service would respond by applying above analyze to recent (up to 150) blocks, return with aggregated value, such as top 5%, or average of top 95% etc.

#### Proposed Solution

1. Create `priority_fee_cache` struct that contains min compute-unit prices for each block
   ```
   struct priority_fee_cache {
       // slot ID for this block,
       slot: Slot,

       // The min compute-unit price for the block
       min_block_fee: u64,

       // hash_map of min compute-unit prices for each write account in this block
       min_account_fees: HashMap<pubkey, u64>,
   }
   ```
2. Create a wrapper struct that holds up to 150 `priority_fee_cache`s and support API for RPC query
   ```
   struct priority_fee_caches {
       // capacity of caches, up to 150
       capacity: u64,

       // number of caches, one per block
       caches: HasMap<Slot, priority_fee_cache>,
   }
   ```
3. Populate/update priority_fee_caches during replay, commit when a bank is_complete().
   ```
   trait replay_stage_updates_priority_fee_caches {
       fn update_block_fee(self, slot: SLot, fee: u64) -> u64;
       fn update_account_fee(self, slot: SLot, account_key: &Pubkey, fee: u64) -> u64;

       // called when bank.is_complete() to make a block's fee cache available for RPC query
       // also handles the logic to prune old caches if more than `capacity`
       fn commit(self, slot: Slot);
   }
   ```
4. Support RPC query
   ```
   trait rpc_query_api {
       // return top 5% min fee for transaction writes to write_accounts
       fn get_min_fee_top_5%(self, write_accounts: Vec<Pubkey>) -> u64;

       // other APIs, tbd
   }
   ```

##### Additional consideration:
On average there are about 4,000 writable accounts per block (by querying "mainnet-beta.autogen.cost_tracker_stats"), majority of them are non-contested accounts. To optimize memory footprint, can prune accounts from `priority_fee_cache.min_account_fees` if account's min fee is less than and equal to block min fee.

**Comment by taozhu-chicago** [comment]
@CriesofCarrots wdyt

**Comment by jdavis103** [comment]
Tao, is there a reason to use a hashmap for the priority_fee_caches, rather than a rolling buffer?

**Comment by CriesofCarrots** [comment]
> Tao, is there a reason to use a hashmap for the priority_fee_caches, rather than a rolling buffer?

Tao's current implementation writes to the cache on each batch processing, and then finalizes the slot -- making it available for querying -- on Bank::freeze. So the HashMap is needed to access each slot repeatedly. However, we discussed other options here: https://github.com/solana-labs/solana/pull/26709#discussion_r930463115
I do think a rolling buffer would be better, if we can make the writes work cleanly.

**Comment by taozhu-chicago** [comment]
> > Tao, is there a reason to use a hashmap for the priority_fee_caches, rather than a rolling buffer?
> 
> Tao's current implementation writes to the cache on each batch processing, and then finalizes the slot -- making it available for querying -- on Bank::freeze. So the HashMap is needed to access each slot repeatedly. However, we discussed other options here: [#26709 (comment)](https://github.com/solana-labs/solana/pull/26709#discussion_r930463115) I do think a rolling buffer would be better, if we can make the writes work cleanly.

Yeah, my thought was `replay_active_banks()` could replay entries from multiple slots, so could have events sequence such like this: `updates_for_bank_1, updates_for_bank_3, updates_for_bank_4, updates_for_bank_1, freeze_bank_1, ...`. HashMap seems to be an easy choice to quick find `prioritization_fee` by slot. Maybe I am wrong?

IN any case, I agree that a rolling buffer, or a ring buffer with fixed capacity, would be more efficient. That also guarantees "up to 150 blocks" without additional work. Can do that as improvement for sure.
