### ISSUE TITLE
leader schedule is generated "on time"

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#2657]
#### Problem
in order for the network to agree on stakes and schedule, the leader schedule needs to be generated "ahead of time"

#### Proposed Solution
move calls for generate_schedule() to a deadline that's close to max_lockout from the end of an epoch (current code generates at end of epoch)

this implies that an epoch is something larger than max_lockout * block_height ticks...

**Comment by mvines** [comment]
I've got a v0.1 of this working now actually, I'll update #2563 once I finish reworking `test_full_leader_validator_network()` today

**Comment by aeyakovenko** [comment]
This is what I was thinking for LS and forking. #2714

**Comment by garious** [comment]
I closed this issue too soon. Will wait until the new on-time leader schedule generation is actually integrated into fullnode.

**Comment by garious** [comment]
The new LeaderScheduler is now integrated. It generates leader schedules on-demand using the `staked_nodes()` some pre-configured number of slots in the past (currently set to slots_per_epoch). The number of slots is high enough to assume there exist no forks and that all validators will derive identical leader schedules for any given epoch height.

tag: @rob-solana, @sagar-solana
