### ISSUE TITLE
cargo build-bpf stopped working after upgrade, uses wrong rustc

### ISSUE THREAD

**Issue by ckamm** [solana-labs/solana#26583]
#### Problem
Processes spawned by `cargo-build-bpf` use the wrong rustc:
```
$ cargo build-bpf
BPF SDK: /home/kamm/dev/mango/solana-release/bin/sdk/bpf
cargo-build-bpf child: rustup toolchain list -v
cargo-build-bpf child: cargo +bpf build --target bpfel-unknown-unknown --release
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/home/kamm/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc - --crate-name ___ --print=file-names -Zremap-cwd-prefix= --target bpfel-unknown-unknown --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit status: 1)
  --- stderr
  error: the option `Z` is only accepted on the nightly compiler
```

where 
- `cargo --version` is `cargo 1.62.0 (a748cf5a3 2022-06-08)`. 
- `solana --version` is `solana-cli 1.10.29 (src:7f1fb145; feat:1425680972)`

Note how it tries to run against `.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc` instead of `.rustup/toolchains/bpf/bin/rustc`

For older versions of `cargo-build-bpf` that don't pass `-Zremap-cwd-prefix=` yet, the error will be
```
error: Error loading target specification: Could not find specification for target "bpfel-unknown-unknown". 
Run `rustc --print target-list` for a list of built-in targets
```

Going back to an older toolchain version with rustup does (surprisingly) not help. The error persists after a `rustup default 1.59.0-x86_64-unknown-linux-gnu`.

#### Analysis

The issue seems to be a RUSTC environment variable that cargo sets before calling `cargo-build-bpf`. This can be seen by passing `--generate-child-script-on-failure` and inspecting the resulting script.

In fact I can reproduce the error with `RUSTC=~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/bin/rustc cargo +bpf build --target bpfel-unknown-unknown --release`

#### Proposed Solution

Workaround 1: `cargo +bpf build-bpf`.

Workaround 2: Use an old cargo version explicitly: `~/.rustup/toolchains/1.59.0-x86_64-unknown-linux-gnu/bin/cargo build-bpf`

Possibly unset `RUSTC` in `cargo-build-bpf`? But it's possible that whatever changed also had other effects.

**Comment by chlenc** [comment]
Hi everyone 👋
I have the same issue

```
BPF SDK: /Users/alexey/.local/share/solana/install/releases/1.10.31/solana-release/bin/sdk/bpf
cargo-build-bpf child: rustup toolchain list -v
cargo-build-bpf child: rustup toolchain link bpf /Users/alexey/.local/share/solana/install/releases/1.10.31/solana-release/bin/sdk/bpf/dependencies/bpf-tools/rust
cargo-build-bpf child: cargo +bpf build --target bpfel-unknown-unknown --release
error: failed to run `rustc` to learn about target-specific information

Caused by:
  process didn't exit successfully: `/Users/alexey/.rustup/toolchains/stable-aarch64-apple-darwin/bin/rustc - --crate-name ___ --print=file-names -Zremap-cwd-prefix= --target bpfel-unknown-unknown --crate-type bin --crate-type rlib --crate-type dylib --crate-type cdylib --crate-type staticlib --crate-type proc-macro --print=sysroot --print=cfg` (exit status: 1)
  --- stderr
  error: the option `Z` is only accepted on the nightly compiler
```

About my enviroment
OS `Macbook m1pro Monterey`

`> rustc -Vv `
```
rustc 1.62.0 (a8314ef7d 2022-06-27)
binary: rustc
commit-hash: a8314ef7d0ec7b75c336af2c9857bfaf43002bfc
commit-date: 2022-06-27
host: aarch64-apple-darwin
release: 1.62.0
LLVM version: 14.0.5
```

`> rustup toolchain list `
```
stable-aarch64-apple-darwin (default)
bpf
```

`yarn  --version && solana --version && anchor --version `
```
3.2.1
solana-cli 1.10.31 (src:77a40cd8; feat:4192065167)
anchor-cli 0.25.0
```

Thanks!

**Comment by oeble** [comment]
If this can help anyone. I execute this script after solana installation in our CI as a workaround:
```sh
# Avoid issues with RUSTC var being forced to rustup install instead of solana's
mv ~/.local/share/solana/install/active_release/bin/cargo-build-bpf ~/.local/share/solana/install/active_release/bin/cargo-build-bpf-orig
echo "#!/bin/bash" >> ~/.local/share/solana/install/active_release/bin/cargo-build-bpf
echo "unset RUSTC" >> ~/.local/share/solana/install/active_release/bin/cargo-build-bpf
echo '${BASH_SOURCE%/*}/cargo-build-bpf-orig' >> ~/.local/share/solana/install/active_release/bin/cargo-build-bpf
chmod +x ~/.local/share/solana/install/active_release/bin/cargo-build-bpf
```

**Comment by chlenc** [comment]
@oeble Thanks a lot!!!
It helped

**Comment by oeble** [comment]
It seems there is an upstream fix https://blog.rust-lang.org/2022/07/12/Rustup-1.25.1.html

**Comment by nabeel99** [comment]
> It seems there is an upstream fix https://blog.rust-lang.org/2022/07/12/Rustup-1.25.1.html

thank you for posting this here, 1.25.1 fixes the issue.
