### ISSUE TITLE
getStakeActivation for previous epochs returns the currently staked amount as active stake for the requested epoch

### ISSUE THREAD

**Issue by tmazhuan** [solana-labs/solana#26622]
#### Problem
When calling getStakeActivation with a previous epoch the result properly shows the state of the stake, but the "active" property contains the currently staked amount instead of the amount actually staked in the requested period. 

#### Proposed Solution
The result of the getStakeActivation-Call should contain the staked amount during the requested epoch

Example for 928rNywZEZxvxLVtXvgWS8bsY6Y4v6kzsZU1ECGxqvQq on mainnet
256: RpcStakeActivation { state: Inactive, active: 0, inactive: 6313519376692 }
257: RpcStakeActivation { state: Inactive, active: 0, inactive: 6313519376692 }
258: RpcStakeActivation { state: Inactive, active: 0, inactive: 6313519376692 }
259: RpcStakeActivation { state: Inactive, active: 0, inactive: 6313519376692 }
260: RpcStakeActivation { state: Activating, active: 0, inactive: 6313519376692 }
261: RpcStakeActivation { state: Active, active: 6313519376692, inactive: 0 }
262: RpcStakeActivation { state: Active, active: 6313519376692, inactive: 0 }
263: RpcStakeActivation { state: Active, active: 6313519376692, inactive: 0 }
264: RpcStakeActivation { state: Active, active: 6313519376692, inactive: 0 }
265: RpcStakeActivation { state: Active, active: 6313519376692, inactive: 0 }
266: RpcStakeActivation { state: Active, active: 6313519376692, inactive: 0 }
267: RpcStakeActivation { state: Active, active: 6313519376692, inactive: 0 }
268: RpcStakeActivation { state: Active, active: 6313519376692, inactive: 0 }
269: RpcStakeActivation { state: Active, active: 6313519376692, inactive: 0 }
270: RpcStakeActivation { state: Active, active: 6313519376692, inactive: 0 }
.
.
.
323: RpcStakeActivation { state: Active, active: 6313519376692, inactive: 0 }
324: RpcStakeActivation { state: Active, active: 6313519376692, inactive: 0 }
325: RpcStakeActivation { state: Active, active: 6313519376692, inactive: 0 }
326: RpcStakeActivation { state: Active, active: 6313519376692, inactive: 0 }
327: RpcStakeActivation { state: Active, active: 6313519376692, inactive: 0 }

**Comment by nyunyunyunyu** [comment]
Hi @ryoqun @CriesofCarrots I'm wondering the expected behavior of `getStakeActivation` because I saw your conversation at #13605.
Let's assume a stake account becomes active at epoch X with 100 active stake and it earns 5 rewards each epoch. In my understanding the expected response of `getStakeActivation`  for this stake account be:
```
epoch X: RpcStakeActivation { state: Active, active: 100, inactive: 0 }
epoch X+1: RpcStakeActivation { state: Active, active: 105, inactive: 0 }
epoch X+2: RpcStakeActivation { state: Active, active: 110, inactive: 0 }
epoch X+3: RpcStakeActivation { state: Active, active: 115, inactive: 0 }
```

But based on [this test](https://github.com/solana-labs/solana/blob/12d2147efaaf5d06fa6338c0f9e209c82780d81b/programs/stake/src/stake_state.rs#L2296), if the current epoch is X+1, the expected response is:
```
epoch X: RpcStakeActivation { state: Active, active: 115, inactive: 0 }
epoch X+1: RpcStakeActivation { state: Active, active: 115, inactive: 0 }
epoch X+2: RpcStakeActivation { state: Active, active: 115, inactive: 0 }
epoch X+3: RpcStakeActivation { state: Active, active: 115, inactive: 0 }
```

Let me know if I misunderstand this API. Thanks!

**Comment by GuyMcComb** [comment]
Is there a way I can upvote this issue?

I agree with the first example. If the second example is the desired outcome, then the epoch parameter that is passed in should be removed since it is misleading.

**Comment by CriesofCarrots** [comment]
Find spent some time on this. It's definitely broken. I think the preferred solution at this time is to remove the past-epoch functionality, ie. return an error when any value other than the current epoch is used.

**Comment by CriesofCarrots** [comment]
It seems technically possible to use reward history and some logic about splits or merges to calculate the delegation amount in past epochs in order to fix this. But that effort currently seems too high.
