### ISSUE TITLE
Testnet does not stay up for more than a few minutes

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#2662]
#### Problem
The replay stage is reporting duplicate signature error. This seems be related to bloom filter for storing signature status in StatusCache.

#### Proposed Solution
The StatusCache bloom is created once when the bank is initially created. The number of bits and hash is not sufficient to store signatures for the lifetime of the bank. The status cache should be recreated, or the bloom filter needs to be configured with more bits.

This issue might already being worked on as part of bank forking. Please close if it's duplicate.

**Comment by pgarg66** [comment]
@aeyakovenko , @rob-solana just FYI

**Comment by mvines** [comment]
Obsolete
