### ISSUE TITLE
UiParsedMessage does not contain public key for wallet receiving NFT

### ISSUE THREAD

**Issue by abcalphabet** [solana-labs/solana#26636]
#### Problem

`solana_transaction_status::UiParsedMessage::account_keys` in the case of sending an NFT does not contain the public key of the receiving wallet anymore after upgrading to solana `1.11.2` from version `1.10.3`.

This issue is also present on the latest stable release `1.10.29`.

Further note, the token sent does not have to be an NFT, this issue occurs with other token programs as well.

#### Proposed Solution

Have `solana_transaction_status::UiParsedMessage::account_keys` contain the receiving public key again.

**Comment by CriesofCarrots** [comment]
I suspect this is a change on the part of your wallet, rather than a solana version issue. However, examples would be useful to determine this for sure.

**Comment by abcalphabet** [comment]
You are correct. I wasn't able to reproduce this behaviour in a minimal example using the different versions.
