### ISSUE TITLE
explorer: metadata for existing fungible token will not be used

### ISSUE THREAD

**Issue by jiayih1212** [solana-labs/solana#26656]
#### Problem

The code will continue using the legacy token list in the spl-token registry. Hence, those users which create or update the metadata for the fungible token will not able to show the correct logo, symbol and name.

[labs/solana/blob/a8be960e05f65d6dfcfa3072441ba899d3499523/explorer/src/pages/AccountDetailsPage.tsx#L171](https://github.com/solana-labs/solana/blob/a8be960e05f65d6dfcfa3072441ba899d3499523/explorer/src/pages/AccountDetailsPage.tsx#L171)

Example of the token: https://explorer.solana.com/address/4KZ2KMyar3NK8uXHE8G5vXskD5Zr4PgE5g9XztCJEpFT/metadata?cluster=devnet 

#### Proposed Solution
Change the code by checking is there any metadata created or updated, instead of using the data in spl-token registry directly.

**Comment by yihau** [comment]
maybe it helps #26751
