### ISSUE TITLE
Seeing a high skip rate but my vote rate is extremely high. 

### ISSUE THREAD

**Issue by codemonkey6969** [solana-labs/solana#26681]
Hey all, I had a conversation with Tim and he suggested I open a github issue to track this. I have passed the logs to Tim for internal distribution. We are seeing issues from a skiprate perspective. The common denominator seems to be a 2 block skiprate in the first 2/4 blocks of the leader schedule. Our identity is FLVgaCPvSGFguumN9ao188izB4K4rxSWzkHneQMtkwQJ. Thanks!

**Comment by tigarcia** [comment]
Can you describe the frequency of this. How long have you observed this problem? Is it correlated with any validator version?

**Comment by nikhayes** [comment]
There has been weird periodicity in the "vote dropped hash mismatch" metrics for quite a while now where you get these regular large spikes that are also evident in the bank error metrics (expected I guess)... I mentioned this in mb validators quite a while ago when I was looking for anything that looked odd during all the network issues. This is 7layer btw. I can hunt down when it was that I was seeing this -- it must have been months ago.
<img width="308" alt="Votedropped" src="https://user-images.githubusercontent.com/63567985/180275856-fdd11f64-1c0a-487a-841b-bc2b340ac77f.PNG">
<img width="345" alt="bankvote" src="https://user-images.githubusercontent.com/63567985/180275886-3a76fe3a-c5df-4d88-b6fc-4f93c1f04135.PNG">

**Comment by nikhayes** [comment]
It looks like it was there even in January
<img width="396" alt="votehash" src="https://user-images.githubusercontent.com/63567985/180280201-f7c87132-d0e4-4b25-a277-73a724459e34.PNG">

**Comment by nikhayes** [comment]
> There has been weird periodicity in the "vote dropped hash mismatch" metrics for quite a while (photos below are taken from the edge dashboard as of 5min ago) now where you get these regular large spikes that are also evident in the bank error metrics (expected I guess)... I mentioned this in mb validators quite a while ago when I was looking for anything that looked odd during all the network issues. I can hunt down when it was that I was seeing this -- it must have been months ago. <img alt="Votedropped" width="308" src="https://user-images.githubusercontent.com/63567985/180275856-fdd11f64-1c0a-487a-841b-bc2b340ac77f.PNG"> <img alt="bankvote" width="345" src="https://user-images.githubusercontent.com/63567985/180275886-3a76fe3a-c5df-4d88-b6fc-4f93c1f04135.PNG">

The pattern in the bank errors is really strange. It looks like there's normally some baseline, then you get the mismatch spike, then errors go to 0 essentially, and then return to baseline

**Comment by nikhayes** [comment]
Sorry I'm dumb, I thought I was responding to the thread where Brennan had made some odd vote observations. Face palm https://github.com/solana-labs/solana/issues/24887#issuecomment-1190919971

**Comment by Z-4-Z** [comment]
I have same - vote credits very good, skip rate always 28-32% (average over last 30 days) - I think a lot of people have this problem.

**Comment by nikhayes** [comment]
What geographic area? Ganges tends to have very good voting/credit performance (top 20) but skip rate doesn't look great either. They're in Mumbai https://www.validators.app/validators/Df8inLU7AzpYMPUZXVdU6Vuy29cuWBuqv3kevNQsn9zu?locale=en&network=mainnet&order=&refresh=
