### ISSUE TITLE
Proposal for Core Docs Restructure/Rewrite

### ISSUE THREAD

**Issue by jacobcreech** [solana-labs/solana#26699]
# Problem

The most common answer on how to improve a developer's experience on Solana is having better/good documentation.

1. [@italoacasas](https://twitter.com/italoacasas/status/1541872902379032577)
2. [@almostefficient](https://twitter.com/almostefficient/status/1545580801848266752?s=21&t=0rAm2TT8cqfVnGob_oBUeA)
3. [@nickfrosty](https://twitter.com/nickfrosty/status/1545524970956152834?s=20&t=4XfSIrQHi46rne5mkAvEuw)

Most notably from [@dumbcontract2's](https://twitter.com/dumbcontract2) popular [introduction to Solana](https://2501babe.github.io/posts/solana101.html) on our current documentation:

`i think the material in them is very valuable and comprehensive but its probably adapted from someones notes or something. in particular its not organized into dependency ordered chapters. ie, if you read in order some stuff in earlier sections is incomprehensible until you read later ones.`

The content in the documentation is great, but we need a little structure.

# Proposed Solution

Let's add some better structure and fill in any missing gaps.

### 1. Make docs.solana.com accommodate the following audiences using well defined paths:

- The Solana-Curious
- Developers
- Validators
- RPC Operators
- Core Contributors

To help achieve the first goal we can structure the page like Stripe does to help people get to where they want to go quickly.

<img width="577" alt="Screen Shot 2022-07-20 at 11 54 48 AM" src="https://user-images.githubusercontent.com/82475023/180039534-7294df4c-9ff5-47bd-85c3-39030ed25eb9.png">

The tabs and separate sidebars will keep audiences from getting "information overload" while still being able to get to where they need to go. Everything else goes to content.

### Move docs.solana.com to solana.com/docs/*

**Reasoning**: SEO-wise this is a better place. Having more documentation around solana on the `solana.com` domain vs the `docs.solana.com` subdomain is better for SEO. The subdomain is treated differently by search engines, fragmenting the authority.

### Where possible give cURL, CLI, Rust, or web3.js examples

**Reasoning**: The core documentation has a decent amount of examples throughout showing how to build on Solana. Whether this be how to use the [JSON RPC API](https://docs.solana.com/developing/clients/jsonrpc-api#example-1) with cURL, or CLI on [how to determine rent exemption costs](https://docs.solana.com/developing/programming-model/accounts#rent-exemption), we should also give other the same example using Rust/JS/CLI/cURL when possible.

This would be similar to how the [Solana Cookbook](https://solanacookbook.com/references/basic-transactions.html#how-to-send-sol) has multiple examples of doing one thing in tabs, or how you can select what language to use when working with [Stripe's API](https://stripe.com/docs/api/metadata).

## New Structure Proposal:

Below is a proposed new structure for the core docs. Pages that already exist are linked. Otherwise they are brand new pages.

Introduction `/introduction`
- [What is Solana?](https://docs.solana.com/introduction)
- How do I use Solana?
- What is Solana used for?
- How do the economics work?
- Getting started with Solana
  - [Wallets](https://docs.solana.com/wallet-guide)
  - [Staking](https://docs.solana.com/staking)

Developing  `/developing`
- [Overview](https://docs.solana.com/developing/programming-model/overview)
- Getting Started
  - What are Programs?
  - What are dapps?
  - What is web3?
  - What is a block?
  - Transaction Fees
  - What is Rent?
- Core Concepts
  - [Transactions](https://docs.solana.com/developing/programming-model/transactions)
  - [Accounts](https://docs.solana.com/developing/programming-model/accounts)
  - Programs
  - Program Derived Addresses
  - [Calling Between Programs](https://docs.solana.com/developing/programming-model/calling-between-programs)
  - [Compute Budget](https://docs.solana.com/developing/programming-model/runtime#compute-budget)
- Writing Programs
  - Program Languages
  - Program frameworks
  - [Building Programs](https://docs.solana.com/developing/on-chain-programs/developing-rust)
  - [Deploying](https://docs.solana.com/developing/on-chain-programs/deploying)
  - Optimizing
- Native Programs
  - [System Program](https://docs.solana.com/developing/runtime-facilities/programs#system-program)
  - [Config Program](https://docs.solana.com/developing/runtime-facilities/programs#config-program)
  - [Stake Program](https://docs.solana.com/developing/runtime-facilities/programs#stake-program)
  - [Vote Program](https://docs.solana.com/developing/runtime-facilities/programs#vote-program)
  - [BPF Loader](https://docs.solana.com/developing/runtime-facilities/programs#bpf-loader)
  - [Ed25519 Program](https://docs.solana.com/developing/runtime-facilities/programs#ed25519-program)
  - [Secp256k1 Program](https://docs.solana.com/developing/runtime-facilities/programs#secp256k1-program)
- Local Development
  - [Solana Test Validator](https://docs.solana.com/developing/test-validator)
- Developer Tools
- Clients

Validator `/validator`
- Overview
- Getting Started
  - [What is a Validator?](https://solana-validator-guidebook.vercel.app/solana-introduction/what-is-a-validator)
  - [What is a RPC?](https://solana-validator-guidebook.vercel.app/solana-introduction/what-is-an-rpc-node)
  - [Validator Requirements](https://docs.solana.com/running-validator/validator-reqs)
- Voting Setup `/validator/voting`
  - [Running a Validator](https://docs.solana.com/running-validator/validator-start)
  - [Managing your Vote Account](https://docs.solana.com/running-validator/vote-accounts)
  - [Monitoring a Validator](https://docs.solana.com/running-validator/validator-monitor)
  - [Staking](https://docs.solana.com/running-validator/validator-stake)
  - [Publishing your Validator Info](https://docs.solana.com/running-validator/validator-info)
  - [Validator Failover Setup](https://docs.solana.com/running-validator/validator-failover)
  - [Troubleshooting](https://docs.solana.com/running-validator/validator-troubleshoot)
- RPC Setup `/validator/rpc`
  - [Running a RPC Node](https://solana-validator-guidebook.vercel.app/validator-setup/rpc-startup-command)
  - Running an Archival Node
  - Working with BigTable
- Geyser `/validator/geyser`
  - Setting up Geyser
  - [Geyser Plugins](https://docs.solana.com/developing/plugins/geyser-plugins)
- Best Practices
  - Operational Best Practices
  - Security Best Practices

Architecture `/architecture`
- [What is a Solana Cluster?](https://docs.solana.com/cluster/overview)
- Consensus `/architecture/consensus`
  - How does Consensus work?
  - Proof of Stake
  - [Proof of History](https://docs.solana.com/cluster/synchronization)
  - [Leader Rotation](https://docs.solana.com/cluster/leader-rotation)
  - [Fork Generation](https://docs.solana.com/cluster/fork-generation)
  - [Managing Forks](https://docs.solana.com/cluster/managing-forks)
  - [Turbine Block Propogation](https://docs.solana.com/cluster/turbine-block-propagation)
  - [Secure Vote Signing](https://docs.solana.com/cluster/vote-signing)
  - [Stake Delegation and Rewards](https://docs.solana.com/cluster/stake-delegation-and-rewards)
- Validator `/architecture/validator`
  - [Overview](https://docs.solana.com/validator/anatomy)
  - [TPU](https://docs.solana.com/validator/tpu)
  - [TVU](https://docs.solana.com/validator/tvu)
  - [Blockstore](https://docs.solana.com/validator/blockstore)
  - [Gossip Service](https://docs.solana.com/validator/gossip)
  - [The Runtime](https://docs.solana.com/validator/runtime)
  
Integrating `/integrating`
- [Add Solana to your Exchange](https://docs.solana.com/integrations/exchange)

Proposals `/proposals`
- Everything under proposals today

CLI `/cli`

RPC API `/rpc`

Terminology `/terminology`

**Comment by nickfrosty** [comment]
I think this restructure of the docs is a good and important idea!

The current state of the docs makes it difficult for new people/developers to decide to join the Solana ecosystem.

These proposed changes will make the docs easier to sift through, surfacing the content new developers and Solana curious people want to dive deeper into the ecosystem.

**Comment by DataKnox** [comment]
This is great. I would love the opportunity to contribute to these docs.

**Comment by AlmostEfficient** [comment]
I'd love to give feedback wherever possible. I've thoroughly gone through the docs for Polygon, Flow, Avalanche, Terra and Solana. 

As a developer that prefers learning by building, I had the easiest time getting started with [Terra](https://docs.terra.money/docs/develop/get-started.html) (current version is a bit messy lol). Their "start building" section is the first thing you see on their landing page - it gives you a decent overview of the resources available and it walks you through basic environment setup.

The main thing missing in your proposed structure is a path for noobs to start with actually _building._ The closest thing on there right now is the [Solana Tool Suite install guide](https://docs.solana.com/cli/install-solana-cli-tools), which I often use as a reference when setting up on a new machine. This only needs to cover the absolute basics IMO. I have a deploy cheatsheet you might find helpful [here](https://hackmd.io/@raza/deploy15)

A dedicated resources section like the [Chainlink references](https://docs.chain.link/docs/other-tutorials/) page or [the Ethereum learn by coding)(https://ethereum.org/en/developers/learning-tools/#main-content) page is a must-have IMO. It lets readers know where to go for further learning/building.

Finally, I'd also include overview pages at every top level. If I click "Learn" on the current docs, it takes me straight to [cluster overview](https://docs.solana.com/cluster/overview). This is just confusing lol, I don't even know what I'm learning. I'm a big fan of how [Thirdweb](https://portal.thirdweb.com/smart-contracts) does it, I'm able to build a mental map of the areas I've explored.

Also a big fan of the [Chainlink docs](https://docs.chain.link/). Less is more.

Stuff to check out
1. [Terra get started docs](https://docs.terra.money/docs/develop/get-started.html)
2. [Solana deploy cheatsheet](https://hackmd.io/@raza/deploy15)
3. [Chainlink references page](https://docs.chain.link/docs/other-tutorials/)
4. [Chainlink docs](https://docs.chain.link/)
5. [Thirdweb docs](https://portal.thirdweb.com/)

**Comment by jacobcreech** [comment]
> As a developer that prefers learning by building, I had the easiest time getting started with [Terra](https://docs.terra.money/docs/develop/get-started.html) (current version is a bit messy lol). Their "start building" section is the first thing you see on their landing page - it gives you a decent overview of the resources available and it walks you through basic environment setup.

Planning on having this immediately as the `/developing` overview page

> The main thing missing in your proposed structure is a path for noobs to start with actually building. The closest thing on there right now is the [Solana Tool Suite install guide](https://docs.solana.com/cli/install-solana-cli-tools), which I often use as a reference when setting up on a new machine. I'd just expand this a bit with a hello world app and cover common commands and workflows. I have a deploy cheatsheet you might find helpful [here](https://hackmd.io/@raza/deploy15)

In general for this first stage I think we're going to avoid writing full on tutorials in the core docs. At least given this rewrite. We do plan on giving examples everywhere possible though.

The core docs are more for explaining concepts than giving how-to guides. [Solana Cookbook](https://solanacookbook.com/) handles references. Resources linking to outside tutorials/how-to guides are a good idea though

Tool Suite installation will still exist, likely under `/cli` with references to it from `/developing` and other areas in the docs.

> A dedicated resources section like the [Chainlink references](https://docs.chain.link/docs/other-tutorials/) page or [the Ethereum learn by coding](https://ethereum.org/en/developers/learning-tools/#main-content) page is a must-have IMO. It lets readers know where to go for further learning/building.

Overview on `/developing`! First thing you're introduced to

> Finally, I'd also include overview pages at every top level. If I click "Learn" on the current docs, it takes me straight to [cluster overview](https://docs.solana.com/cluster/overview). This is just confusing lol, I don't even know what I'm learning. I'm a big fan of how [Thirdweb](https://portal.thirdweb.com/smart-contracts) does it, I'm able to build a mental map of the areas I've explored.

Goal is to have each main `/developing`, `/validator`, etc to drop you first on a page like [Stripe has](https://stripe.com/docs/payments) to help guide you where to go next.
