### ISSUE TITLE
cli: Query stake minimum delegation before delegating

### ISSUE THREAD

**Issue by brooksprumo** [solana-labs/solana#26695]
The CLI command to delegate stake should query the minimum delegation before attempting to perform the delegation. This way the user can see a better message than their transaction failed.

Probably also useful to do something similar for splitting stake accounts. If the source account is already delegated, then the split amount needs to be at least the minimum as well.

### Original Context

should we also hook this up to `solana delegate-stake` and fail too small delegation attempts client-side so the user sees something nicer than some `TransactionError`?  separate PR ofc

_Originally posted by @t-nelson in https://github.com/solana-labs/solana/pull/26645#pullrequestreview-1044482044_

**Comment by ameya-deshmukh** [comment]
@brooksprumo is this still open? Would love to give it a shot!

**Comment by kunal-gg** [comment]
@ameya-deshmukh did you manage to solve this?

**Comment by michaelh-laine** [comment]
Working on this here: https://github.com/solana-labs/solana/pull/31897

Core functionality is done, will work to add tests
