### ISSUE TITLE
Missing Inner Instructions in slots

### ISSUE THREAD

**Issue by gulshngill** [solana-labs/solana#26736]
#### Problem
Similar to https://github.com/solana-labs/solana/issues/25880, we found slots that have missing inner instructions.
Due to this issue, we can not correctly identify token transfers that occurred or other contracts that were called due to an instruction. 

[Example of Serum Settle Funds with missing instructions](https://solscan.io/tx/5HNoiUDDVwzzqQSqZK3oHh7pxZG5QJaCbWcVcZ5w3xBtot1KRBGh8v4sxu6USc9YcGDM2fgtZqYke7Tkta36S2Ry)

[Serum Settle Funds with inner instructions](https://solscan.io/tx/5mYLYQAefv5TNGXwDDRRPwa3jyiffmeurWwR85XoiwscwDfAFhox7iAgorHm2PJ57MqxQ1nvdKYFCEwwB1ZhDoYr)

#### Proposed Solution

Backfill the slots with missing inner instructions.

Here's a list of slots that we've compiled which we suspect has missing inner instructions (~7.8 mil slots):
[Solana Slots with missing Inner Instructions](https://drive.google.com/file/d/12gANSmYaJkW8B5x9GN-BTWMhGT55WuT1/view?usp=sharing)

We got this by getting all the slots where `innerInstructions` is `null` in the response instead of `[]`.

**Comment by jstarry** [comment]
Unfortunately we didn't persist inner instructions in tx metadata for a period of time after support for CPI's was first enabled. Can you confirm that this only impacts slots from over a year ago?

**Comment by gulshngill** [comment]
Hey @jstarry, we do see for slots from this year too.  
It's difficult to determine exactly which slots are the ones with missing instructions. 
The method we used to get this is to find any transaction that returns `null` rather than `[]` for inner instructions which isn't perfect but currently the best way we know to determine them.

**Comment by jstarry** [comment]
> The method we used to get this is to find any transaction that returns null rather than [] for inner instructions which isn't perfect but currently the best way we know to determine them.

This is the correct way to determine it 👍🏻 

> Is there any internal effort to backfilling this?

There is an effort for more recent slots but not for transactions that processed before instruction recording was implemented. Typically the gaps occur consistently over a range of some number of slots rather than in isolated instances. If you could provide a few recent ranges, we'll make a best effort to backfill

**Comment by gulshngill** [comment]
Hi @jstarry , here's the list of slots we found that do not have inner instructions
[solana_missing_inner_instructions.txt.zip](https://drive.google.com/file/d/12gANSmYaJkW8B5x9GN-BTWMhGT55WuT1/view).
Looks like there's only about 60 or so slots from this year with this issue but they are not in a range.
 The rest are from over a year ago
