### ISSUE TITLE
Explorer: support v0 transactions

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#26741]
#### Problem

Version-0 transactions are starting to come through on devnet, but explorer.solana.com does not support v0-transaction display. This is part of #26391 ; just breaking it out for explicit examples and discussion.

- Raw transactions have been updated to pass the `maxSupportedTransactionVersion: 0` parameter, but they do not include address-lookup-table details: https://explorer.solana.com/tx/3nX2dbk1EBr51h5FTU8PQzahvVwGGUNrx8ubka39YBXZRh4t9R4L4DPP8QTD4bpjo5nNAETLguWP5TrseRzDbUEL/inspect?cluster=devnet
- Parsed transactions do not load details at all: https://explorer.solana.com/tx/3nX2dbk1EBr51h5FTU8PQzahvVwGGUNrx8ubka39YBXZRh4t9R4L4DPP8QTD4bpjo5nNAETLguWP5TrseRzDbUEL?cluster=devnet

#### Proposed Solution
Figure out how we want to display extended account lists from address-lookup tables and implement in explorer.
Also add `maxSupportedTransactionVersion: 0` to the jsonParsed `getTransaction` request.

**Comment by jstarry** [comment]
Fixed by https://github.com/solana-labs/solana/pull/27825
