### ISSUE TITLE
Solana slots no longer increase.

### ISSUE THREAD

**Issue by blockchen-admin** [solana-labs/solana#26764]
Solana slots no longer increase.

#curl http://localhost:8899 -X POST -H "Content-Type: application/json" -d '
  {"jsonrpc":"2.0","id":1, "method":"getSlot"}
'
{"jsonrpc":"2.0","result":142641054,"id":1}

The maximum height of the slot is when the Solana node started 3 days ago.
No longer climbs from this slot height.

------------------------------------------------------------------------
Solananode was executed as follows.

solana-validator \
--full-rpc-api \
--enable-rpc-bigtable-ledger-storage \
--enable-extended-tx-metadata-storage \
--ledger /data/ledger \
--identity /data/config/validator-keypair.json \
--trusted-validator 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2 \
--trusted-validator GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ \
--trusted-validator DE1bawNcRJB9rVm3buyMVfr8mBEoyyu73NBovf2oXJsJ \
--trusted-validator CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S \
--expected-genesis-hash 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d \
--entrypoint entrypoint.mainnet-beta.solana.com:8001 \
--entrypoint entrypoint2.mainnet-beta.soana.com:8001 \
--entrypoint entrypoint3.mainnet-beta.solana.com:8001 \
--entrypoint entrypoint4.mainnet-beta.solana.com:8001 \
--entrypoint entrypoint5.mainnet-beta.solana.com:8001 \
--no-voting \
--rpc-port 8899 \
--gossip-port 8801 \
--dynamic-port-range 8000-8020 \
--no-port-check\
 --wal-recovery-mode \
skip_any_corrupted_record \
--enable-rpc-transaction-history \
--enable-cpi-and-log-storage \
--init-complete-file /data/init-completed \
--snapshot-compression none \
--require-tower \
--no-wait-for-vote-to-start-leader \
--no-poh-speed-test \
--accounts /data/accounts \
--log

**Comment by steviez** [comment]
Cleaning up old issues - support for running a node is handled on Discord: https://solana.com/discord
