### ISSUE TITLE
Solana web3.js is too big to be used with AWS Lambda

### ISSUE THREAD

**Issue by SenudaJayalath** [solana-labs/solana#26766]
#### Problem

When we install the latest solana web3.js library its size is around 260mb. This can't be directly used with AWS Lambda because the maximum folder size is 250mb.
#### Proposed Solution
It is really important that we should modularize the solana web3.js package as the current package is really large.

**Comment by steveluscher** [comment]
We agree! It's going to take time, but there's a plan: #25314.

**Comment by steveluscher** [comment]
I'm curious though, where this 260mb number comes from. Are those binaries being built in for Node that take up all that room? It's certainly not JavaScript.
