### ISSUE TITLE
Enable QUIC client path by default

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#26778]
#### Problem

UDP transaction path is the default with quic enabled by a flag.

#### Proposed Solution
QUIC server is enabled, now enable QUIC client by default.

- [x] Merge change to enable quic client send by default into master (forwarding transactions and send-transaction-service)
- [x] Make a 1.11 release with this change
- [x] Deploy said 1.11 to testnet
- [x] Deploy 1.14 with quic enabled by default to testnet
- [x] Turn off UDP in master
- [x] Deploy 1.14 with UDP disabled
- [ ] Move to 1.14 to mainnet

**Comment by t-nelson** [comment]
need to discern between server and client enablement
