### ISSUE TITLE
Feature Gate: Use default units per instruction in fee calculation

### ISSUE THREAD

**Issue by taozhu-chicago** [solana-labs/solana#26785]
### Description

When `bank` calculates transaction fee, it's hardcoded to _not_ to use default units per instruction, which is a feature already enabled in mainnet-beta. It _should_ use default units. This change needs to be feature gated.

### Feature ID

8sKQrMQoUHtQSUP83SPG4ta2JDjSAiWs7t5aJ9uEd6To

### Activation Method

Single Core Contributor

### Minimum Beta Version

1.11.5

### Testnet Activation Epoch

423

### Devnet Activation Epoch

509

### Mainnet-Beta Activation Epoch

478

**Comment by taozhu-chicago** [comment]
When this feature is activated in mainnet-beta, it can be cleaned up together with "default units per instruction" feature (as PR #26684 demostrated)

**Comment by Kosty233** [comment]
привет
