### ISSUE TITLE
Solana network probably DDoS itself

### ISSUE THREAD

**Issue by kszysiu94** [solana-labs/solana#26789]
#### Problem
Hello

According to api.testnet.solana.com We are hosting multiple Solana validator nodes from testnet cluster in our Datacenter. From month or two We started to receive "false-positives" from time to time that traffic to those servers exceeded 2-3gbit (average from 10 seconds). It wasn't frequent, but it happend maybe once a week or less. Our mitigation software detected that traffic is mainly on udp 8000-8005 ports or sometimes on 11000 udp ports. It causes filtering this traffic or even blackholing those servers for few minutes.

From last few days, there are multiple DDoS alerts about those servers, today there were 20 or so anomalies detected. Traffic for solana validators is rising to very high levels. At this moment there are at least 2 blackholed solana validators in our network due to traffic to those servers are reaching even 10gbits while those servers are connected with 1gbit network interface.

Example (cut down to few lines, 6,5gbit of traffic detected)

2022-07-26 11:21:42.287626 162.55.2.98:8000 > victim_ip:8000 protocol: udp frag: 0  packets: 1 size: 1095 bytes ttl: 0   
2022-07-26 11:21:42.289706 198.244.202.107:8001 > victim_ip:8000 protocol: udp frag: 0  packets: 1 size: 587 bytes ttl: 0   
2022-07-26 11:21:42.289714 141.95.124.181:8000 > victim_ip:8000 protocol: udp frag: 0  packets: 1 size: 837 bytes ttl: 0   
2022-07-26 11:21:42.289717 141.95.146.95:8000 > victim_ip:8000 protocol: udp frag: 0  packets: 1 size: 837 bytes ttl: 0   
2022-07-26 11:21:42.289795 198.244.213.74:8000 > victim_ip:8000 protocol: udp frag: 0  packets: 1 size: 1095 bytes ttl: 0   
2022-07-26 11:21:42.289800 198.244.176.35:8000 > victim_ip:8000 protocol: udp frag: 0  packets: 1 size: 1095 bytes ttl: 0   
2022-07-26 11:21:42.289802 141.95.124.181:8000 > victim_ip:8000 protocol: udp frag: 0  packets: 1 size: 1095 bytes ttl: 0   
2022-07-26 11:21:42.289866 85.10.192.148:8000 > victim_ip:8000 protocol: udp frag: 0  packets: 1 size: 837 bytes ttl: 0   
2022-07-26 11:21:42.289937 142.132.197.178:8000 > victim_ip:8000 protocol: udp frag: 0  packets: 1 size: 1095 bytes ttl: 0   
2022-07-26 11:21:42.289946 85.10.205.8:8001 > victim_ip:8000 protocol: udp frag: 0  packets: 1 size: 587 bytes ttl: 0   
2022-07-26 11:21:42.289948 142.132.131.184:8001 > victim_ip:8000 protocol: udp frag: 0  packets: 1 size: 1095 bytes ttl: 0   
2022-07-26 11:21:42.295370 65.108.79.224:8001 > victim_ip:8000 protocol: udp frag: 0  packets: 1 size: 837 bytes ttl: 0   
2022-07-26 11:21:42.295383 65.108.131.32:8000 > victim_ip:8000 protocol: udp frag: 0  packets: 1 size: 846 bytes ttl: 0   
2022-07-26 11:21:42.295439 142.132.154.126:8000 > victim_ip:8000 protocol: udp frag: 0  packets: 1 size: 1095 bytes ttl: 0   
2022-07-26 11:21:42.295449 144.76.85.108:8001 > victim_ip:8000 protocol: udp frag: 0  packets: 1 size: 587 bytes ttl: 0   
2022-07-26 11:21:42.295452 144.76.100.219:11000 > victim_ip:8000 protocol: udp frag: 0  packets: 1 size: 1095 bytes ttl: 0   
2022-07-26 11:21:42.295456 95.217.202.225:8001 > victim_ip:8000 protocol: udp frag: 0  packets: 1 size: 286 bytes ttl: 0   
2022-07-26 11:21:42.296632 198.244.176.35:8000 > victim_ip:8000 protocol: udp frag: 0  packets: 1 size: 1095 bytes ttl: 0   

I checked few of those are on api.testnet.solana.com and they are on list of nodes too - so in theory it's "normal" solana traffic, not DDoS attack.

All in all traffic in Solana is very... "spiky". In fact We have problems with Solana traffic for few months now. We have from time to time reports from clients (Solana users) that servers network "is working bad" - it's due to nonlinear nature of this traffic. 300mb/s average traffic can "kill" 1gbit interface, Traffic is overfilling interface buffers. This effect is called microbursting.

#### Proposed Solution

I am not familiar with validators protocol, but Solana network needs better bandwidth handling. 

Maybe the problem is using UDP protocol. I know it's fast, but it's hard to handle in such distributed scenarios. Maybe Solana network should be working over TCP where protocol takes care of those problems by itself. I know that in small enviroments UDP could be faster and have less latency, but with such problems with "self-DDoSing" and microbursting in fact TCP could perform much better.

If its not doable, my second idea is per ip outgoing traffic policing - maybe it could lead to minimise bursting, increasing stability and - in fact - performance

**Comment by solauto** [comment]
In builds that have QUIC enabled, I get blackholed too due to perceived incoming DDoS events due to bandwidth in the 5-10gbps range, where server has 3gbps.  This might be a problem with the network supporting both UDP and QUIC, where typical UDP spamming by bots causes flooding in the server-to-server QUIC forwarding.  The cloud provider suggested using DDoS scrubbing instead, but dropping traffic might cause a validator to become desync'd with the network.

**Comment by buffalu** [comment]
what datacenter is this?

**Comment by kszysiu94** [comment]
Hello
AS201814 - mevspace.com
We are hosting more than 200 servers in testnet. This day looks much better so far, no 'incidents' today. For every anomaly looking like Solana yesterday I disabled DDoS protection (so no filtering, just few minutes blackholing when traffic exceed interface possibilities), but those peaks are not looking good.

Second problem I would like to discuss are those microbursts.

For example I am looking right now at one server statistics, which receives in average ~200mb/s (like almost every solana server) of traffic on 1g interface, at 25k pps rate and we are observing ~700pps discards on that interface. so 2.8% of packets are not arriving at destination server due to microbursts overfilling buffer for that interface. and its just at ~20-30% of interface ratings. such discards appears only on servers that are hosting Solana Validators.

For comparison iperf3 udp test with ~950mbit of bandwidth creates only few discards per second or any at all. And most of servers - beside Solana Validators - do not exceed few pps discards, while most of Solana Validators reach ~700pps of discards.

It looks like validators are just flooding with packets without checking if server on the other side is able to receive all those data.

**Comment by kszysiu94** [comment]
Hello
So there are much more "DDoSes" today. I noticed over 50 solana based anomalies in last 24h. most of them are in 6-9gbit range.

**Comment by kszysiu94** [comment]
So at 11:45 UTC We received allert, that ~30 servers were blackholed. in same minute. "best one" had almost 12g of traffic - it's average from 10 or 20 seconds. I removed ips but all of them were solana validators. 
IP x.x.x.x triggered blackholing with 1940868.4 bits/s UDP on [TPIX]
IP x.x.x.x triggered blackholing with 2975295.0 bits/s UDP on [TATA]
IP x.x.x.x triggered blackholing with 6921841.5 pkts/s UDP on [TATA]
IP x.x.x.x triggered blackholing with 2919596.0 bits/s UDP on [TATA]
IP x.x.x.x triggered blackholing with 2875005.5 bits/s UDP on [TATA]
IP x.x.x.x triggered blackholing with 7451481.0 pkts/s UDP on [TATA]
IP x.x.x.x triggered blackholing with 6873471.5 pkts/s UDP on [TATA]
IP x.x.x.x triggered blackholing with 4632700.5 pkts/s UDP on [TATA]
IP x.x.x.x triggered blackholing with 4309459.0 pkts/s UDP on [Cogent]
IP x.x.x.x triggered blackholing with 7436969.5 pkts/s UDP on [Cogent]
IP x.x.x.x triggered blackholing with 7436969.5 bits/s UDP on [Cogent]
IP x.x.x.x triggered blackholing with 7006465.0 pkts/s UDP on [Cogent]
IP x.x.x.x triggered blackholing with 4072610.2 bits/s UDP on [Cogent]
IP x.x.x.x triggered blackholing with 8046747.5 pkts/s UDP on [Cogent]
IP x.x.x.x triggered blackholing with 4119694.5 bits/s UDP on [Cogent]
IP x.x.x.x triggered blackholing with 3664221.0 bits/s UDP on [Cogent]
IP x.x.x.x triggered blackholing with 7356868.0 pkts/s UDP on [Cogent]
IP x.x.x.x triggered blackholing with 7235238.5 pkts/s UDP on [Cogent]
IP x.x.x.x triggered blackholing with 3970872.0 bits/s UDP on [TPIX]
IP x.x.x.x triggered blackholing with 2981401.2 bits/s UDP on [TPIX]
IP x.x.x.x triggered blackholing with 3596558.2 bits/s UDP on [TPIX]
IP x.x.x.x triggered blackholing with 3889464.8 bits/s UDP on [TPIX]
IP x.x.x.x triggered blackholing with 4001901.8 bits/s UDP on [TPIX]
IP x.x.x.x triggered blackholing with 4711153.5 pkts/s UDP on [TPIX]
IP x.x.x.x triggered blackholing with 6429689.5 pkts/s UDP on [TATA]
IP x.x.x.x triggered blackholing with 9030135.0 pkts/s UDP on [TATA]
IP x.x.x.x triggered blackholing with 4192355.8 pkts/s UDP on [Cogent]
IP x.x.x.x triggered blackholing with 4620140.5 pkts/s UDP on [Cogent]
IP x.x.x.x triggered blackholing with 7588010.5 pkts/s UDP on [Cogent]
IP x.x.x.x triggered blackholing with 7316411.5 pkts/s UDP on [Cogent]
IP x.x.x.x triggered blackholing with 3818746.5 bits/s UDP on [TPIX]
IP x.x.x.x triggered blackholing with 3157785.0 bits/s UDP on [TPIX]
IP x.x.x.x triggered blackholing with 11891018.0 pkts/s UDP on [Cogent]

**Comment by kszysiu94** [comment]
Stats from last days.
8.08 - 100 "DDoS attacks" by solana validators
9.08 - 50 "DDoS attacks" by solana validators
today - 400!!! in 9h!!!!!
at this moment there are 15 servers blackholed, even tho We are only blackholing for 3 minutes.

Any conclusions? I can see that enabling quic limited number of discards on interfaces - so there are less microbursts, but those "DDoSes" are ridiculous.

**Comment by buffalu** [comment]
![image](https://user-images.githubusercontent.com/85544055/187316308-35a71a03-ec9b-4ee9-854f-055372a04363.png)

traffic from gossip on start
