### ISSUE TITLE
Hash calculation for incremental snapshots can be faster

### ISSUE THREAD

**Issue by brooksprumo** [solana-labs/solana#26799]
#### Problem

Computing the accounts hash for snapshots historically used the index to perform this calculation; the calculation was changed to use the on-disk stores. This calculation needs to read all the stores to find the most recent version of each account, which is quite slow and likely thrashes the cache for everything else.

Incremental snapshots also need the accounts hash. We're currently computing the hash for the full accounts set. Is it possible to only hash what's in just the incremental snapshot instead?

#### Proposed Solution

Hash the accounts in the incremental snapshot. When loading from an incremental snapshot, its hash will need to be combined with the full snapshot hash to produce the correct accounts hash that the bank will verify. This work will likely need to be behind a feature-gate or a different snapshot version (or both).

**Comment by jeffwashington** [comment]
I spilled a lot more ink on #26848 and did not find this issue first. Closing this one.
