### ISSUE TITLE
Couldn't deserialize bigtable data

### ISSUE THREAD

**Issue by barath-kanna** [solana-labs/solana#26806]
> I have data from my warehouse node in my bigtable instance, but when I try to fetch the data using numerous ways, this is the output that I have.
It's in protbuf format, how do we deserialize it back to human readable format

```

---------------------------------------
3vu111m4NNyBYSaDKw77CG2Se9jm8eYetjp3aHX5TF4bXPY4L45qanN7v2LyvzyRa5vTb1sSDArwDefaRTaNtam1
  x:bin                                    @ 2022/07/23-17:31:38.290000
    "\x00\x00\x00\x00\xc1|\x83\b\x00\x00\x00\x00\x89\x01\x00\x00\x00\x00"

----------------------------------------
`3vu111tuX9JhBV3zp7Zdc6PGs3ENtZTrR2yhFVEtEvV78YU7eUtbj92oB6rkoxLefEiHL7spvy5MY6dd5HWis4S`
  x:bin                                    @ 2022/07/21-13:55:46.086000
    "\x00\x00\x00\x00\x98\x96~\b\x00\x00\x00\x00\xf3\x01\x00\x00\x00\x00"

----------------------------------------
3vu112JB4x4Q3w2PQoYbmAQaxm5oeybXgUvq6YTQsWxkPnyYPEnkphHocmSZ69vcH3teJM6pGJSJfvgPNB8UP4mf
  x:bin                                    @ 2022/07/26-21:50:37.318000
    "\x00\x00\x00\x00=P\x8a\b\x00\x00\x00\x00\xa8\x00\x00\x00\x00\x00"
```

**Comment by barath-kanna** [comment]
How to approach this exactly, Should we write a plugin that converts it back to readable format, or an API to convert and serve to our front end. Kindly suggest the best practices to implement this

**Comment by barath-kanna** [comment]
[https://github.com/solana-labs/solana/blob/master/storage-bigtable/init-bigtable.sh](url) Is it possible to do it with a shell script like this ine that you have posted

**Comment by barath-kanna** [comment]
> How to approach this exactly, Should we write a plugin that converts it back to readable format, or an API to convert and serve to our front end. Kindly suggest the best practices to implement this

How to approach this exactly, Should we write a plugin that converts it back to readable format, or an API to convert and serve to our front end. Kindly suggest the best practices to implement this

**Comment by RdeWilde** [comment]
Also note x:bin, which would suggest it is binary serialization, not protobuf
