### ISSUE TITLE
Metrics show 2x more TPU votes than gossip

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#26819]
#### Problem

The gossip votes seen in banking stage seem to be occuring at a rate almost 2x over the gossip votes, these are the relevant queries:

`SELECT mean("receive_and_buffer_packets_count") AS "gossip_only_votes" FROM "mainnet-beta"."autogen"."banking_stage-loop-stats" WHERE time > :dashboardTime: AND time < :upperDashboardTime: AND id =0`

`SELECT (mean("Vote-pull") + mean("Vote-push"))/2 AS total_votes_inserted_to_gossip FROM "mainnet-beta"."autogen"."cluster_info_crds_stats" WHERE time > :dashboardTime: AND time < :upperDashboardTime:`

#### Proposed Solution

Debug and explain why.

**Comment by sakridge** [comment]
<img width="1438" alt="Screen Shot 2022-07-27 at 9 32 43 PM" src="https://user-images.githubusercontent.com/1024962/181356784-24147f77-2f17-4994-b0e9-891a97a9f3ba.png">

**Comment by carllin** [comment]
So the idea is `SELECT (mean("Vote-pull") + mean("Vote-push"))/2 AS total_votes_inserted_to_gossip FROM "mainnet-beta"."autogen"."cluster_info_crds_stats" WHERE time > :dashboardTime: AND time < :upperDashboardTime:` is supposed to find all the votes that arrived through gossip to the local node? Why do we need to divide by 2?

If I'm reading this correctly: https://github.com/solana-labs/solana/blob/8d69e8d44772d2c2be77e99cca8b685e2ce4ba66/gossip/src/crds.rs#L665-L666
1. Vote-push is incremented every time there's a push to us
2. Vote-pull is incremented every time there's a pull response to our pull request

**Comment by behzadnouri** [comment]
> Why do we need to divide by 2?

divide 2 is because gossip metrics are reported every 2 seconds.
other metrics are apparently reported every 1 second.

**Comment by carllin** [comment]
> <img alt="Screen Shot 2022-07-27 at 9 32 43 PM" width="1438" src="https://user-images.githubusercontent.com/1024962/181356784-24147f77-2f17-4994-b0e9-891a97a9f3ba.png">

Man this query is taking me forever to run, I'm assuming the blue is the number of votes ingested via the vote gossip thread?

**Comment by carllin** [comment]
<img width="1650" alt="image" src="https://user-images.githubusercontent.com/3374799/181361361-3cd9b400-56dd-434a-99a8-0f97969c3dce.png">
Seems like the gossip thread is seeing about 3k gossip votes per block, of which only 100 or so are committed

**Comment by carllin** [comment]
<img width="1657" alt="image" src="https://user-images.githubusercontent.com/3374799/181362617-dd4c5dae-0ff8-47a2-b942-d4dec5cbbfde.png">

From this we can see the leader is attempting execution of almost 20k gossip votes per slot, but only 100 or so are making it.  This part requires some more investigation.

But if this is the behavior, then the amplification makes sense because gossip will retry sending votes to banking threads that didn't make it into the block, so the amplification of the number of total votes seen by banking threads should be equal to number of blocks per second, which is roughly 2.

**Comment by carllin** [comment]
<img width="1650" alt="image" src="https://user-images.githubusercontent.com/3374799/181364486-97b97223-0e46-4ef0-8a0c-bca291a0f79c.png">
Seems like a lot of the failures are retryable errors

1. When the votes attempted is over 40k, mostly cost model errors
2. Otherwise seems to be AccountInUse? Is there some other retryable error other than AccountInUse and the CostModel?

**Comment by carllin** [comment]
Ah I wonder if this is because the 128 votes from the bankingstage heap are being popped off at the same time, 127 of which will be from the same validator, and will conflict with AccountInUse

**Comment by brennanwatt** [comment]
> <img alt="image" width="1657" src="https://user-images.githubusercontent.com/3374799/181362617-dd4c5dae-0ff8-47a2-b942-d4dec5cbbfde.png">
> 
> From this we can see the leader is attempting execution of almost 20k gossip votes per slot, but only 100 or so are making it. The rest are failing. This part requires some more investigation.
> 
> But if this is the behavior, then the amplification makes sense because gossip will retry sending votes to banking threads that didn't make it into the block, so the amplification of the number of total votes seen by banking threads should be equal to number of blocks per second, which is roughly 2.

This aligns with my observations recorded in #24887 . Here's some relevant data from that issue:

> Collected some more interesting data to better understand the interaction between turbine and gossip votes. Data was collected for reporting nodes between slots 142426995 and 142428995 (~830 reported slots):
> 
> Successfully committed turbine votes = 1,172,497 (89.4% of total successful votes)
> Successfully committed gossip votes = 138,804 (10.6% of total successful votes)
> Non-retryable failures for turbine votes = 305,401
> Non-retryable failures for gossip votes = 252,654
> Turbine vote failures can be further broken down as follows:
> 
> account_not_found = 618
> blockhash_not_found = 235,44
> blockhash_too_old = 285
> instruction_error = 240,631 --> VoteTooOld
> already_processed = 40,323
> Gossip vote failures can be further broken down as follows:
> 
> account_not_found = 53,934
> blockhash_not_found = 25,473
> blockhash_too_old = 11,214
> instruction_error = 72,183 --> VoteTooOld
> already_processed = 89,850

**Comment by carllin** [comment]
@AshwinSekar has a rework of how banking stage vote threads organize their unprocessed queues https://github.com/solana-labs/solana/pull/26722. Could be useful for the retries here as well.

**Comment by brennanwatt** [comment]
> <img alt="image" width="1657" src="https://user-images.githubusercontent.com/3374799/181362617-dd4c5dae-0ff8-47a2-b942-d4dec5cbbfde.png">
> 
> From this we can see the leader is attempting execution of almost 20k gossip votes per slot, but only 100 or so are making it. The rest are failing. This part requires some more investigation.
> 
> But if this is the behavior, then the amplification makes sense because gossip will retry sending votes to banking threads that didn't make it into the block, so the amplification of the number of total votes seen by banking threads should be equal to number of blocks per second, which is roughly 2.

Not sure I follow this. The `banking_stage-loop-stats.receive_and_buffer_packets_count` metric shouldn't increment for transactions that are retried. This should only be incremented for new packets coming in from `ClusterInfoVoteListener` -> `bank_send_loop`

**Comment by brennanwatt** [comment]
Took a look at these stats across the entire cluster (as opposed to limited validator set), and it appears to align with the data cited above:
![image](https://user-images.githubusercontent.com/44715351/181379753-0ebac1e6-f0d2-4e77-810e-2021523cc226.png)
You can also see number of votes sent from `cluster_info_vote_listener` lines up with what we're seeing received by the banking threads

**Comment by carllin** [comment]
> Not sure I follow this. The banking_stage-loop-stats.receive_and_buffer_packets_count metric shouldn't increment for transactions that are retried. This should only be incremented for new packets coming in from ClusterInfoVoteListener -> bank_send_loop

@brennanwatt  "because gossip will retry sending votes to banking", by this I meant the actual `cluster_info_vote_listener` thread will resend the votes to the banking thread

**Comment by brennanwatt** [comment]
> > Not sure I follow this. The banking_stage-loop-stats.receive_and_buffer_packets_count metric shouldn't increment for transactions that are retried. This should only be incremented for new packets coming in from ClusterInfoVoteListener -> bank_send_loop
> 
> @brennanwatt "because gossip will retry sending votes to banking", by this I meant the actual `cluster_info_vote_listener` thread will resend the votes to the banking thread

Gotchu, yep, makes perfect sense.

Gossip --> ClusterInfoVoteListener --> Banking Stage
              ^                                              ^
       Once per vote                     Once per slot --> same vote gets re-sent to banking stage for multiple slots

The amplification factor seems to line up as well. I'm seeing ~1.67x amplification, which would correlate with 600ms slot times
