### ISSUE TITLE
Need a dashboard for fee market

### ISSUE THREAD

**Issue by taozhu-chicago** [solana-labs/solana#26818]
#### Problem

Need a dashboard for min block/account fee, ideally correlates to traffic volume/type

#### Proposed Solution

build a dashboard with following data points: 

1. Check block priority fee stats:

| Measurements | Fields | Note |
|---|---|---|
| block_prioritization_fee | slot | measures are reported by slot |
| block_prioritization_fee | total_prioritization_fee | total priority fee in block |
| block_prioritization_fee | total_writable_accounts_count | total writable accounts in block |
| block_prioritization_fee | relevant_writable_accounts_count | number of writable accounts has min priority fee greater than block min fee |

2. Check min priority fee:

| Measurements | Fields | Note |
|---|---|---|
| block_min_prioritization_fee | slot | measures are reported by slot |
| block_min_prioritization_fee | min_prioritization_fee | min prioritization fee |
| block_min_prioritization_fee | entity | entity of min prioritization fee, could be "block" or top 10 writable accounts in block |

3. Check block and account cost limit status

| Measurements | Fields | Note |
|---|---|---|
| cost_tracker_stats | bank_slot | slot number |
| cost_tracker_stats | block_cost | total CUs per block |
| cost_tracker_stats | costliest_account_cost | total CUs for the most contended account in block |
| cost_tracker_stats | costliest_account_cost | number of writable accounts in block |
| cost_tracker_stats | transaction_count | number of transactions landed in block |

4. Check cost limits counters

| Measurements | Fields | Note |
|---|---|---|
| qos-service-errors | bank_slot | slot number |
| qos-service-errors | id | banking thread id, non-votes are id > 1 |
| qos-service-errors | retried_txs_per_block_limit_count | number of transactions being retried due to block limit |
| qos-service-errors | retried_txs_per_account_limit_count | number of transactions being retried due to account limit |

**Comment by taozhu-chicago** [comment]
@pieceofr wdyt if above data good starting point? I put them together at https://metrics.solana.com:8889/sources/5/dashboards/82?refresh=Paused&lower=now%28%29%20-%2015m.

**Comment by taozhu-chicago** [comment]
Dan Saber shared some charts: https://dune.com/crypto_notte/solana-additional-fee-analysis, and https://dune.com/crypto_notte/solana-additional-fee-analysis

**Comment by overclock-validator** [comment]
Down to give feedback if I can get access :) I'm probably one of the most picky/interested people in this stuff -7Layer

**Comment by taozhu-chicago** [comment]
> Down to give feedback if I can get access 

What access do you need?

> can one infer how many transactions get dropped from the block based on "retried_txs_per_block_limit_count" "retried_txs_per_account_limit_count"?

Well, transactions are not dropped due to limits, but being put back to queue for retry. There is a separate "drop" count for transactions are too old (or already executed etc)

> Another thing that might be helpful is median fee priority

Agree, some kind of fee distribution would be useful.

**Comment by overclock-validator1** [comment]
>What access do you need?
Just the dashboard but nbd if you can't share. https://metrics.solana.com:8889/sources/5/dashboards/82?refresh=Paused&lower=now%28%29%20-%2015m.

>Well, transactions are not dropped due to limits, but being put back to queue for retry. There is a separate "drop" count for transactions are too old (or already executed etc)
Ohh I see, so retry for the next slot then I'm guessing.

The only other thing I can think of which could be cool would be some measure of how effective priority is. Idk how to encapsulate that though. I guess you'd need to look at priority spread across tick height in a block. It would be very cool actually if someone adds tick height to the transaction info in one of the explorers. I know some of the people in the Jito discord have been trying to figure out how to see if fee priority is actually effective for what they're doing. I'm actually not sure how to find tick height info for transactions.
