### ISSUE TITLE
RPC service panics / segfaults on 1.10.32

### ISSUE THREAD

**Issue by codemonkey6969** [solana-labs/solana#26826]
Attached are logs during the 5 seconds leading up to the crash. The big indicators I see that cut off are the following lines:

1. "[2022-07-28T04:38:03.652785299Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="blockstore_13" one=1i message="panicked at 'Shred with"
2. [2022-07-28T04:38:03.657152844Z INFO  solana_metrics::metrics] datapoint: accounts_index count_in_mem=234196850i count=234196850i bg_waiting_percent=0 bg_throttling_wait_percent=0 min_in_bin_mem=27875i max_in_bin_mem=75638i count_from_bins_mem=234196850i median_from_bins_mem=28581i gets_from_mem=1013198i get_mem_us=161031i gets_missing=10518i get_missing_us=932i entries_from_mem=0i entry_mem_us=0i entries_missing=56i entry_missing_us=0i updates_in_mem=131846i get_range_us=0i inserts=56i deletes=0i active_threads=11i items=14i items_us=7120i keys=0i

**I have not had this happen before prior to 1.10.32.** 

![unknown](https://user-images.githubusercontent.com/67477461/181428857-f53d200c-4492-4303-a961-6f233a005ef4.png)
[logs.txt](https://github.com/solana-labs/solana/files/9205693/logs.txt)

**Comment by CriesofCarrots** [comment]
Do you have the complete panic log?

**Comment by t-nelson** [comment]
Was the node shutdown cleanly prior to experiencing this panic?

**Comment by mvines** [comment]
Fixed in v1.10.34 by "Bump spl-token to v3.3.1" (https://github.com/solana-labs/solana-program-library/pull/3416)

**Comment by mvines** [comment]
yes you have listed multiple panics in this issue, which makes it pretty unusable. At least one of your panics is resolved in 1.10.34. feel free to create new issues for each unique panic, do not roll them all into one uber issue
