### ISSUE TITLE
cargo-build-bpf broken on master (and all v1.11 releases so far)

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#26830]
#### Problem

```
$ cd solana
$ ./cargo-build-bpf --manifest-path ../solana-program-library/token/program-2022/Cargo.toml
+ [[ ! -f ./sdk/bpf/syscalls.txt ]]
+ [[ ! -f ./target/debug/cargo-build-sbf ]]
+ exec ./cargo run --manifest-path ./sdk/cargo-build-bpf/Cargo.toml -- --bpf-sdk ./sdk/bpf --manifest-path ../solana-program-library/token/program-2022/Cargo.toml
+ exec cargo +1.60.0 run --manifest-path ./sdk/cargo-build-bpf/Cargo.toml -- --bpf-sdk ./sdk/bpf --manifest-path ../solana-program-library/token/program-2022/Cargo.toml
   Compiling solana-program v1.11.5 (/solana/sdk/program)
   Compiling solana-sdk v1.11.5 (/solana/sdk)
   Compiling solana-cargo-build-bpf v1.11.5 (/solana/sdk/cargo-build-bpf)
    Finished dev [unoptimized + debuginfo] target(s) in 7.06s
     Running `target/debug/cargo-build-bpf --bpf-sdk ./sdk/bpf --manifest-path ../solana-program-library/token/program-2022/Cargo.toml`
Warning: cargo-build-bpf is deprecated. Please, use cargo-build-sbf
cargo-build-bpf child: target/debug/cargo-build-sbf --sbf-sdk ./sdk/bpf --manifest-path ../solana-program-library/token/program-2022/Cargo.toml --arch bpf
error: not a directory: '/solana/sdk/bpf/dependencies/bpf-tools/rust/lib'
```

```
$ solana-install init 1.11.4
  ✨ 1.11.4 initialized
$ cd solana-program-library/token/program-2022
$ cargo build-bpf
Warning: cargo-build-bpf is deprecated. Please, use cargo-build-sbf
cargo-build-bpf child: /.local/share/solana/install/active_release/bin/cargo-build-sbf --arch bpf
error: not a directory: '/.local/share/solana/install/releases/1.11.4/solana-release/bin/sdk/bpf/dependencies/bpf-tools/rust/lib'
```

#### Proposed Solution
Troubleshoot and fix

**Comment by dmakarov** [comment]
Do you have more context for these failures?  When I run both commands locally in solana-labs/solana clone top level directory, everything works correctly.

**Comment by CriesofCarrots** [comment]
> Do you have more context for these failures? When I run both commands locally in solana-labs/solana clone top level directory, everything works correctly.

Ah, looks like it's broken on MacOS. Errors in the description are from mac.

Works on linux, although it's not printing any of this text anymore:
```
cargo-build-bpf child: /../.local/share/solana/install/releases/1.10.33/solana-release/bin/sdk/bpf/dependencies/bpf-tools/llvm/bin/llvm-readelf --dyn-symbols /../solana-program-library/target/deploy/spl_token_2022.so

To deploy this program:
  $ solana program deploy /../solana-program-library/target/deploy/spl_token_2022.so
The program address will default to this keypair (override with --program-id):
  /../solana-program-library/target/deploy/spl_token_2022-keypair.json
  ```
  
What other context do you need?

**Comment by dmakarov** [comment]
> Ah, looks like it's broken on MacOS. Errors in the description are from mac.

I run the commands on macOS and they work.

> What other context do you need?

Everything that would help me top reproduce the issue - environment variables values, the path to cargo-build-bpf executable that `cargo build-bpf` runs, in what path the commands where executed, what are the symbolic links in `solana/sdk/bpf/dependencies/` subdir, essentially a sequence of steps to reproduce the failures.

**Comment by CriesofCarrots** [comment]
> environment variables values, 

I am not passing any envars, and don't have anything relevant exported.

> the path to cargo-build-bpf executable that `cargo build-bpf` runs,

This is included in the issue description snippets

> in what path the commands where executed

I've updated the snippets above to make this clear

> what are the symbolic links in `solana/sdk/bpf/dependencies/` subdir

This doesn't seem relevant for the prepackaged v1.11.4 case, but when running from solana monorepo root:
```
$ cd sdk/bpf/dependencies/
$ find . -type l -ls
50282849        0 lrwxr-xr-x    1 ..     ..                  49 Jul 27 16:48 ./bpf-tools -> /../.cache/solana/v1.28/bpf-tools
50282847        0 lrwxr-xr-x    1 ..     ..                  50 Jul 27 16:48 ./criterion -> /../.cache/solana/v2.3.2/criterion
50282750        0 lrwxr-xr-x    1 ..     ..                  49 Jul 27 16:48 ./sbf-tools -> /../.cache/solana/v1.28/sbf-tool
```

**Comment by dmakarov** [comment]
Is it possible to run the commands with -v command line option and paste the output in here?

```
$ ./cargo-build-bpf --manifest-path ../solana-program-library/token/program-2022/Cargo.toml -v
```
and
```
$ cargo build-bpf -v
```

**Comment by CriesofCarrots** [comment]
> run the commands with -v command line option

It doesn't seem like there's additional verbose information..

```
$  ./cargo-build-bpf --manifest-path ../solana-program-library/token/program-2022/Cargo.toml -v
+ [[ ! -f ./sdk/bpf/syscalls.txt ]]
+ [[ ! -f ./target/debug/cargo-build-sbf ]]
+ exec ./cargo run --manifest-path ./sdk/cargo-build-bpf/Cargo.toml -- --bpf-sdk ./sdk/bpf --manifest-path ../solana-program-library/token/program-2022/Cargo.toml -v
+ exec cargo +1.60.0 run --manifest-path ./sdk/cargo-build-bpf/Cargo.toml -- --bpf-sdk ./sdk/bpf --manifest-path ../solana-program-library/token/program-2022/Cargo.toml -v
    Finished dev [unoptimized + debuginfo] target(s) in 0.27s
     Running `target/debug/cargo-build-bpf --bpf-sdk ./sdk/bpf --manifest-path ../solana-program-library/token/program-2022/Cargo.toml -v`
Warning: cargo-build-bpf is deprecated. Please, use cargo-build-sbf
cargo-build-bpf child: target/debug/cargo-build-sbf --sbf-sdk ./sdk/bpf --manifest-path ../solana-program-library/token/program-2022/Cargo.toml -v --arch bpf
error: not a directory: '/../solana/sdk/bpf/dependencies/bpf-tools/rust/lib'
```

```
$ cargo build-bpf -v
Warning: cargo-build-bpf is deprecated. Please, use cargo-build-sbf
cargo-build-bpf child: /../.local/share/solana/install/active_release/bin/cargo-build-sbf -v --arch bpf
error: not a directory: '/../.local/share/solana/install/releases/1.11.4/solana-release/bin/sdk/bpf/dependencies/bpf-tools/rust/lib'
```

**Comment by dmakarov** [comment]
Are the paths in error messages exactly as they are printed or you edited the prefixes? These errors are printed by rustup when it sets up toolchain link for bpf toolchain. The paths don’t look right. If they’re edited and actual paths include your home directory prefixes it may be that something is messed up in ~/.cache/solana/v1.28/bpf-tools on your filesystem. Could you remove that directory and rerun one of the commands? It should try to download and install bpf-tools anew.

**Comment by CriesofCarrots** [comment]
> Are the paths in error messages exactly as they are printed or you edited the prefixes? These errors are printed by rustup when it sets up toolchain link for bpf toolchain. The paths don’t look right. If they’re edited and actual paths include your home directory prefixes it may be that something is messed up in ~/.cache/solana/v1.28/bpf-tools on your filesystem. Could you remove that directory and rerun one of the commands? It should try to download and install bpf-tools anew.

Sorry, I edited the prefixes because I don't want my home directory path on github.
I'll remove the `~/.cache/solana/v1.28/bpf-tools` dir and try again

**Comment by CriesofCarrots** [comment]
Oh hey, that worked. Will close this. Any idea why my bpf-tools could have been borked?

**Comment by dmakarov** [comment]
> Oh hey, that worked. Will close this. Any idea why my bpf-tools could have been borked?

It's hard to say. The cargo-build-sbf code that downloads and installs the tools package should fail on any error so that the symbolic links are not left in an inconsistent state, but apparently the code is not fully fail-proof.

**Comment by dmakarov** [comment]
> Does build on linux, although it's not printing any of this text anymore:

it's a bit unfortunate all the messages were switched to logger messages. To see the cargo-build-sbf information messages it's now necessary to set `RUST_LOG=info`, e.g.

```
RUST_LOG=info cargo build-bpf
```
