### ISSUE TITLE
rpc request timed out and stuck

### ISSUE THREAD

**Issue by Tab-ops** [solana-labs/solana#26841]
### the current instance type
```
aws ec2
r6i.8xlarge
disk 
gp3 2048 
```
### script to run
```
#!/bin/bash
#mainnet sol
export SOLANA_METRICS_CONFIG="host=https://metrics.solana.com:8086,db=mainnet-beta,u=mainnet-beta_write,p=password"
exec solana-validator \
  --identity ~/validator-keypair.json \
  --vote-account ~/vote-account-keypair.json \
  --known-validator 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2 \
  --known-validator GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ \
  --known-validator DE1bawNcRJB9rVm3buyMVfr8mBEoyyu73NBovf2oXJsJ \
  --known-validator CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S \
  --only-known-rpc \
  --no-port-check \
  --full-rpc-api \
  --enable-cpi-and-log-storage \
  --ledger /data/SOL/ledger \
  --enable-rpc-transaction-history \
  --rpc-port 8899 \
  --dynamic-port-range 8000-8020 \
  --entrypoint entrypoint.mainnet-beta.solana.com:8001 \
  --entrypoint entrypoint2.mainnet-beta.solana.com:8001 \
  --entrypoint entrypoint3.mainnet-beta.solana.com:8001 \
  --entrypoint entrypoint4.mainnet-beta.solana.com:8001 \
  --entrypoint entrypoint5.mainnet-beta.solana.com:8001 \
  --expected-genesis-hash 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d \
  --no-voting \
  --log /data/SOL/ledger/solana-validator.log \
  --wal-recovery-mode skip_any_corrupted_record \
  --limit-ledger-size
```
### problem lies in
1、Upgrade to Mainnet - v1.10.32 latest
sh -c "$(curl -sSfL https://release.solana.com/v1.10.32/install)"
2、After restarting and running for a while, when I use the interface to request port 8899, it has been stuck with no data
```
curl -s -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":1, "method":"getEpochInfo"}' http://localhost:8899|jq
```
![image](https://user-images.githubusercontent.com/53932327/182154793-22f82ff0-1639-43d5-ae59-08be49d2ebe4.png)

Is there any solution to my problem?

**Comment by dudebing99** [comment]
I encountered the same issue with the same hardware and the `1.10.32` version.

It seems like the hardware resources are sufficient, but the rpc request got stuck after the node running for a while.

**Comment by Tab-ops** [comment]
@dudebing99 
Have you solved it now, my current node is not back to normal yet

**Comment by dudebing99** [comment]
> 

Nope. I've no idea how to solve the problem. Restart the node and it will work normally only for a while ...

**Comment by Tab-ops** [comment]
In the same situation as me, I don't know how to solve the problem, and the official discord didn't reply to my question.

**Comment by airstring** [comment]
I've been doing this for three days, same problem, up for half an hour, then dead with no error.Using r6i.12xlarge is the same problem.

**Comment by dudebing99** [comment]
The testnet seems well, but the mainnet has the problem. I tried for sevseral versions but none worked.

**Comment by corpocott** [comment]
I am seeing this as well

**Comment by ultd** [comment]
I am seeing this as well

**Comment by airstring** [comment]
Have you solved the problem？

**Comment by Tab-ops** [comment]
@airstring  I don't know how to solve this problem, is your node still normal?

**Comment by airstring** [comment]
@Tab-ops I changed the type to r6i.12xlarge.The process will not stop and will always be normal.But sometimes the service is accessible and sometimes it is not.
![image](https://user-images.githubusercontent.com/26688391/182105524-f1296533-8a84-46bf-b588-c794d6a1458c.png)

**Comment by corpocott** [comment]
i ended up just creating a cron job to restart the process every 2 hours. Not ideal but better than nothing

**Comment by Tab-ops** [comment]
@corpocott How to ensure data integrity after restarting the node?

**Comment by dudebing99** [comment]
It makes no sence without data integrity for me, besides it lasts too long before the rpc service ready while restarting the node.

**Comment by corpocott** [comment]
yeah, this bandaid probably isn't for everybody. Was just trying something to make it a tiny bit better until the problem is fixed

**Comment by Tab-ops** [comment]
I thought it was the problem of my UDP buffer size, but it didn't seem to be the case, and I adjusted the system parameters according to the official operation. My Recv-Q value is very high, and it feels like this affects my rpc response
![image](https://user-images.githubusercontent.com/53932327/182179561-e481a2c5-5897-47d3-956e-18d151ff8930.png)

**Comment by CriesofCarrots** [comment]
Have any of you checked your validator logs to determine if your node is still progressing and making roots?
ie. is this a validator issue or an RPC service issue

**Comment by Tab-ops** [comment]
@CriesofCarrots Upgrading from version Mainnet - v1.10.29, feels like it's under attack, sync is slow, and rpc interface doesn't respond

**Comment by ricewang666** [comment]
I have the same problem, can anyone solve it?

**Comment by ricewang666** [comment]
please help us @jeffwashington @mvines @garious @CriesofCarrots @jstarry @jackcmay @solana-labs 
We have been out of service for over a week now，please help ！！！！！

**Comment by ricewang666** [comment]
and the log keeps repeating

**Comment by ricewang666** [comment]
and the log keeps repeating
<img width="1794" alt="WX20220805-174338@2x" src="https://user-images.githubusercontent.com/29854424/183051193-6894c545-a868-4f1a-baed-2eb7727ec2f6.png">

**Comment by ricewang666** [comment]
and the log keeps repeating
<img width="1839" alt="WX20220805-174556@2x" src="https://user-images.githubusercontent.com/29854424/183051399-6c86fd90-5846-465c-8baf-68231bc4593e.png">

**Comment by jstarry** [comment]
It would be helpful to know if any older versions have the same issue. Can you try versions v1.10.31 and lower to see when the issue started?

Any other information about the behavior of your server / request logs before the issue starts would be helpful too

**Comment by corpocott** [comment]
I started seeing the issue with 1.10.31

**Comment by jstarry** [comment]
@joeaba have you heard of any rpc freezing issues with v1.10.31?

**Comment by joeaba** [comment]
I haven't seen this in any of our servers yet, I've asked to the RPC operators if any has hit it again.

**Comment by ultd** [comment]
Hey we were experiencing this on `1.10.28`, `1.10.32` and `1.10.34`. 

### Our Node:

CPU: AMD Epyc 7313 (16 Cores) 
RAM: 512GB
Disk: 4TB+ NVME SSD
Account indexes: `spl-token-mint`, `spl-token-owner`, `program-id`
Account index exclude: `kinXdEcpDQeHPEuQnqmUgtYykqKGVFq6CeVX5iAHJq6` (only)


After looking at our data, 2 things were happening at the same time. 

### 1. Our WS usage increased significantly as shown below (nothing to do with Validator): 

![image](https://user-images.githubusercontent.com/12675427/183252838-b17b9fe2-b29b-4055-8718-ee671083b33c.png)

This was due to a rogue customer. We addressed this. 

### 2. Our nodes were running OOM even at `512GB` RAM which caused pauses/crashes:

![image](https://user-images.githubusercontent.com/12675427/183252997-549a64e5-63d6-44d4-9482-905ff287e9fb.png)

We have since increased SWAP space to `200GB` which has subsided our pausing/crashing problems.

### Solution? 

We are now just making sure we have enough memory (including SWAP) to ensure these pauses/crashes don't happen. All nodes are running `1.10.34`. It seems to be working thus far but may just be a bandaid for a much larger problem. The fact that we're over 600-700GB in memory usage (RAM + SWAP) consistently (and growing) may point to a memory leak of some sort? 

Hopefully this helps.

**Comment by dudebing99** [comment]
My node returns to normal finally today without any manual operations.

**Comment by airstring** [comment]
> please help us @jeffwashington @mvines @garious @CriesofCarrots @jstarry @jackcmay @solana-labs We have been out of service for over a week now，please help ！！！！！

Have you solved it?

**Comment by CriesofCarrots** [comment]
@ultd , do you have any data about the specific RPC requests your node was serving when you saw the issue?

**Comment by ricewang666** [comment]
@airstring  Our self-built node has been deleted, and we are now using the managed node service

**Comment by ricewang666** [comment]
@airstring  https://www.quicknode.com/

**Comment by airstring** [comment]
@ricewang666 I see. My SOL node isn't back up yet either
