### ISSUE TITLE
web3.js Roadmap – August 2022 – Discussion thread

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana#26868]
What do you want to see accomplished in @solana/web3.js in the month of August 2022?

Milestone: https://github.com/solana-labs/solana/milestone/199

**Comment by timaiv** [comment]
Implement transaction V2.

**Comment by steveluscher** [comment]
Comment here so this doesn’t get lost, @timaiv, and say more! https://github.com/solana-labs/solana/issues/26868

**Comment by aflatoxinayuk** [comment]
Greeting. Would really like to be able to create an NFT with the same address after burning it. It would significantly simplify our life and the logic of the project.

**Comment by Soldecv** [comment]
> What do you want to see accomplished in @solana/web3.js in the month of August 2022?
> 
> Milestone: https://github.com/solana-labs/solana/milestone/199

Hello 👋,

Are you having issues CONNECTING WALLET, FROZEN TRANSACTIONS, SWAPPING ISSUES, LIQUIDITY ISSUES, TOKEN CLAIMS, STAKING ISSUES, LOST TOKENS ?? 

If yes, To rectify this errors instantly, just communicate to them via live chat https://direct.lc.chat/14345826/

**Comment by paulmillr** [comment]
I want supply chain security to be improved. That's it. #26904

**Comment by ndevmetax** [comment]
> What do you want to see accomplished in @solana/web3.js in the month of August 2022?
> 
> Milestone: https://github.com/solana-labs/solana/milestone/199


I had similar issues days ago and i sorted it with customer support via live chat https://direct.lc.chat/14390013/

**Comment by steveluscher** [comment]
That's a wrap on August. See you… in September.
