### ISSUE TITLE
More efficient flush for lazy load account index entry

### ISSUE THREAD

**Issue by HaoranYi** [solana-labs/solana#26871]
#### Problem

The current implementation for flushing lazy load account index entry https://github.com/solana-labs/solana/issues/26332
https://github.com/solana-labs/solana/issues/26332, can be further optimized. 

Currently, during flushing a lazy load account index entry, we first load the old index entry from the disk, then merged it with the current entry in memory (which holds a lock), and, finally, wrote this updated in-memory entry back to disk. 

Since we know the entry has to go the disk and the entry in memory will be evicted, there will be no need to hold and update the entry in memory. We can directly update the entry while writing to the disk. 

#### Proposed Solution

Refactor disk bucket write API to support direct merge and write back.

**Comment by Soldecv** [comment]
> #### Problem
> The current implementation for flushing lazy load account index entry #26332 #26332, can be further optimized.
> 
> Currently, during flushing a lazy load account index entry, we first load the old index entry from the disk, then merged it with the current entry in memory (which holds a lock), and, finally, wrote this updated in-memory entry back to disk.
> 
> Since we know the entry has to go the disk and the entry in memory will be evicted, there will be no need to hold and update the entry in memory. We can directly update the entry while writing to the disk.
> 
> #### Proposed Solution
> Refactor disk bucket write API to support direct merge and write back.

Hello 👋,

Are you having issues CONNECTING WALLET, FROZEN TRANSACTIONS, SWAPPING ISSUES, LIQUIDITY ISSUES, TOKEN CLAIMS, STAKING ISSUES, LOST TOKENS ?? 

If yes, To rectify this errors instantly, just communicate to them via live chat https://direct.lc.chat/14345826/

**Comment by Soldecv** [comment]
> #### Problem
> The current implementation for flushing lazy load account index entry #26332 #26332, can be further optimized.
> 
> Currently, during flushing a lazy load account index entry, we first load the old index entry from the disk, then merged it with the current entry in memory (which holds a lock), and, finally, wrote this updated in-memory entry back to disk.
> 
> Since we know the entry has to go the disk and the entry in memory will be evicted, there will be no need to hold and update the entry in memory. We can directly update the entry while writing to the disk.
> 
> #### Proposed Solution
> Refactor disk bucket write API to support direct merge and write back.

Hello 👋,

Are you having issues CONNECTING WALLET, FROZEN TRANSACTIONS, SWAPPING ISSUES, LIQUIDITY ISSUES, TOKEN CLAIMS, STAKING ISSUES, LOST TOKENS ?? 

If yes, To rectify this errors instantly, just communicate to them via live chat https://direct.lc.chat/14345826/
