### ISSUE TITLE
Feature Request: Geyser for solana-ledger-tool verify

### ISSUE THREAD

**Issue by terorie** [solana-labs/solana#26886]
#### Problem

`solana-ledger-tool verify` replays a part of blockchain history on demand.

This generates useful historical state data internally but there is currently no way to surface this data to consumers.

#### Proposed Solution

Support `--geyser-plugin-config` for ledger-tool.

**Comment by terorie** [comment]
I'm currently working on this ^

**Comment by Soldecv** [comment]
> #### Problem
> `solana-ledger-tool verify` replays a part of blockchain history on demand.
> 
> This generates useful historical state data internally but there is currently no way to surface this data to consumers.
> 
> #### Proposed Solution
> Support `--geyser-plugin-config` for ledger-tool.

Hello 👋,

Are you having issues CONNECTING WALLET, FROZEN TRANSACTIONS, SWAPPING ISSUES, LIQUIDITY ISSUES, TOKEN CLAIMS, STAKING ISSUES, LOST TOKENS ?? 

If yes, To rectify this errors instantly, just communicate to them via live chat https://direct.lc.chat/14345826/

**Comment by Soldecv** [comment]
> #### Problem
> `solana-ledger-tool verify` replays a part of blockchain history on demand.
> 
> This generates useful historical state data internally but there is currently no way to surface this data to consumers.
> 
> #### Proposed Solution
> Support `--geyser-plugin-config` for ledger-tool.

Hello 👋,

Are you having issues CONNECTING WALLET, FROZEN TRANSACTIONS, SWAPPING ISSUES, LIQUIDITY ISSUES, TOKEN CLAIMS, STAKING ISSUES, LOST TOKENS ?? 

If yes, To rectify this errors instantly, just communicate to them via live chat https://direct.lc.chat/14345826/

**Comment by cavemanloverboy** [comment]
I believe this should be closed

**Comment by steviez** [comment]
> I believe this should be closed given https://github.com/solana-labs/solana/pull/26909

Agreed
