### ISSUE TITLE
`solana-ledger-tool verify` OOM's with master on mnb

### ISSUE THREAD

**Issue by steviez** [solana-labs/solana#26895]
#### Problem

Running `solana-ledger-tool verify` with the tip of master OOM's after processing a . For example, with a snapshot a from epoch 333, I see an OOM after processing < 250 slots. I believe this has been an issue for a little bit, as jwash also reported hitting some OOM's with `master` roughly 1 month back:
https://discord.com/channels/428295358100013066/439194979856809985/992161854686240778

mvines had a potential fix with https://github.com/solana-labs/solana/pull/26349 that enabled `AccountsBackgroundService` when running `verify`; however, I still encountered the OOM with this.

Some things that have already been verified:
- roots are being made (`BankForks::set_root()` is getting called)
- banks are getting dropped (`Bank::Drop()` is getting called)

#### Proposed Solution
Debug and fix, several methods to approach
- Idea 1: Profile (heaptrack) and look for any obvious offender
- Idea 2: git bisect (1.10 does not show the issue)
   - The common base between v1.10.32 and tip of master is https://github.com/solana-labs/solana/commit/15357480ec61ae90093f752ddb30e059b2a9cffc which leaves about ~1700 commits (assuming the base is good and something that changed on master caused the OOM) ... not great but doable
   
#### Testing Results
The following are for attempting to process roughly 10k slots from a recent mainnet beta ledger.
```
9cdd84bb5e66d9db01ef9aa5c3e0277731c3f00e ==> No OOM // v1.10.32 tag
224550d65fca059a46f6293d41cee7055986a638 ==> OOM    // jwash recent improvement; also OOM'd with mvines PR on top
```

**Comment by steviez** [comment]
Luckily I pinged @jeffwashington and he had just put in a fix that makes things better: https://github.com/solana-labs/solana/commit/224550d65fca059a46f6293d41cee7055986a638
- Without this change, I was sometimes seeing as few as ~200 processed before OOM
- With this change, my single run made it through ~5500 processed slots before OOM

A definite improvement, but I think there is still something worth investigating here

**Comment by jeffwashington** [comment]
maybe related to 83e041299a
specifically removal of `exhaustively_free_unused_resource`

**Comment by Soldecv** [comment]
> #### Problem
> Running `solana-ledger-tool verify` with the tip of master OOM's after processing a . For example, with a snapshot a from epoch 333, I see an OOM after processing < 250 slots. I believe this has been an issue for a little bit, as jwash also reported hitting some OOM's with `master` roughly 1 month back: https://discord.com/channels/428295358100013066/439194979856809985/992161854686240778
> 
> mvines had a potential fix with #26349 that enabled `AccountsBackgroundService` when running `verify`; however, I still encountered the OOM with this.
> 
> #### Proposed Solution
> Debug and fix, several methods to approach
> 
> * Idea 1: Profile (heaptrack) and look for any obvious offender
> * Idea 2: git bisect (1.10 does not show the issue)
>   
>   * The common base between v1.10.32 and tip of master is [1535748](https://github.com/solana-labs/solana/commit/15357480ec61ae90093f752ddb30e059b2a9cffc) which leaves about ~1700 commits (assuming the base is good and something that changed on master caused the OOM) ... not great but doable

Hello 👋,

Are you having issues CONNECTING WALLET, FROZEN TRANSACTIONS, SWAPPING ISSUES, LIQUIDITY ISSUES, TOKEN CLAIMS, STAKING ISSUES, LOST TOKENS ?? 

If yes, To rectify this errors instantly, just communicate to them via live chat https://direct.lc.chat/14345826/

**Comment by steviez** [comment]
Unfortunately, doing a `git bisect` doesn't have a good path. There was some fairly trivial patches to get compatibility with the new snapshot / ledger on older commits; however, processing sputters out form some TX's. I would essentially have to bisect to find commits that would create compatibility ... we could do this if we get desperate, but going to pursue other angles at the moment.

For completeness incase we come back, here were the commits to get snapshot / ledger compatible:
- If a commit is unable to open snapshot, cherry-pick 8caced68ce8dff7b18566ed90b94bc077bd6f370
- If a commit is unable to open rocksdb, use `ldb` to drop `optimistic_slots` column

**Comment by jeffwashington** [comment]
I have done all this already and have the branches.
I am pretty sure this is it:
> 83e041299a - Run real snapshot packager while processing blockstore at validator startup (3 months ago) <Michael Vines>

**Comment by jeffwashington** [comment]
I was after a different issue, but ledger tool perf was the main thing.

**Comment by steviez** [comment]
> specifically removal of exhaustively_free_unused_resource

In support of this, I looked at incidence rate of the datapoint metrics that are reported by the gc functions:
```
v1.10.32
  accounts_db-flush_accounts_cache ==> 183 instances
  clean_accounts ==> 215
  shrink_stats ==> 278
tip-of-master
  accounts_db-flush_accounts_cache ==> 0 instances
  clean_accounts ==> 0
  shrink_stats ==> 0
tip-of-master + mvines make ABS run in solana-ledger-tool verify
  accounts_db-flush_accounts_cache ==> 0 instances
  clean_accounts ==> 1
  shrink_stats ==> 2
```
So, these cleanup functions are clearly not getting called in tip of master
