### ISSUE TITLE
Tpu forwarder doesn't efficiently propagate transactions as nodes drift

### ISSUE THREAD

**Issue by carllin** [solana-labs/solana#2695]
#### Problem
Non-leader  nodes currently forward transactions received on the TPU port to the one node they believe to be the leader. However, especially with fast leader rotation and as nodes individual PoH drifts apart, this forwarding procedure can cause circular communication (nodes that think each other are the leader will ping-pong transactions between each other) and can cause transactions to back up before flooding a specific node when the network finally converges. Is there a better scheme for propagating transactions throughout the network?

#### Proposed Solution
@aeyakovenko, @sagar-solana, @pgarg66, @rob-solana, @garious @MarkJr94

**Comment by garious** [comment]
That'd mean neither node is voting, right? PoH should reset to the hash of the latest fork it voted on, effectively synchronizing it to some recent leader.

**Comment by aeyakovenko** [comment]
A couple of ideas:


* Stick them in gossip.  Raw transactions would need to appear as CrdsValues without an additional wrapper.  Each transaction would be keyed by the fee paying account.  The wallclock would be based on the lastid.  Gossip automatically cleans up values without pings every 15 seconds.  So the data won’t persist for a long time. 


* forward once per 1/2 * last_id timeout at a random slot.   cache until you are the next leader or the tx expires.  Clear out any observed transactions. Leaders should probably scan any unrolled blocks for transactions they could pick up.

**Comment by pgarg66** [comment]
Loops can be detected if every forwarder tags the transaction with its public key. Whenever a node receives a forwarded transaction, it can check if its own public key is in the tags of the forwarded transaction. If it's there, then the transaction has been looping around, and could be dropped (or cached until next leader slot).

**Comment by pgarg66** [comment]
Or, we can add a TTL to the forwarded transaction. Every forwarder will decrement the TTL. If it drops to 0, the transaction will not be forwarded.

**Comment by aeyakovenko** [comment]
@pgarg66, gossip does a lot of that already. Storing the tx by the fee signers public key would allow us to throttle the usage by bandwidth.  But it’s a bit overkill I think, because the tx ends up sent to everyone twice.

@carllin,
TCP to the leader would remove any retransmits, and sets us up for all the validators being an ingress point that can filter out invalid transactions before they get forwarded.  It would be really hard to DDoS.

**Comment by pgarg66** [comment]
@aeyakovenko the tx shouldn't be sent to everyone twice. The first node that sees its own signature in the previous signature list stops forwarding the transaction. Gossip solution should be fine too. That would get rid of entire forwarding cycling. The confirmation time might suffer a bit.

**Comment by aeyakovenko** [comment]
@pgarg66, gossip will end up with the transaction sent twice.  Once through gossip and then retransmitted. 


It’s possible to leverage that knowledge and do some compression.  The leader could send a bloom filter of the entries, and nodes could reconstruct the entry using the bloom filter and erasure codes.

**Comment by aeyakovenko** [comment]
@carllin @pgarg66 my preference is to use tcp to forward just because it’s simple we don’t need to build retransmission and failure detection.

**Comment by pgarg66** [comment]
@aeyakovenko, not sure if TCP helps with the original issue that @carllin mentioned. The network can create loops for TPU forward even when TCP is being used.

I am not saying that TCP should not be used. Just that we need a solution for this issue on top of that.

**Comment by aeyakovenko** [comment]
@pgarg66, the reciever would share their state.  Leader or not, and the sender would be synchronized

**Comment by aeyakovenko** [comment]
But, the gossip path sounds like way more fun :)

**Comment by pgarg66** [comment]
@carllin  I think with recent fixes and optimizations, this issue can be closed

**Comment by pgarg66** [comment]
#3712 #3750 #3757 #3871 #3935 #3948
