### ISSUE TITLE
Bad allocation from `solana-validator`

### ISSUE THREAD

**Issue by steviez** [solana-labs/solana#26961]
#### Problem

Someone reported seeing the following error running their validator (version v1.10.32):
```
memory allocation of 13226403602517458946 bytes fail
```
https://discord.com/channels/428295358100013066/837340113067049050/1004514331007909980

It seems likely that this is the result of some unchecked math somewhere. The individual mentioned it is fairly repeatable on their setup.

#### Proposed Solution
Diagnose and debug. The following could be done to instrument out the allocator so we can get a stack trace from this bad allocation:
- Following the steps [here](https://github.com/solana-labs/solana#readme), build a binary for `v1.10.32` tag (if not already running from source)
- Restart validator with this binary and ensure that the same failure is still seen
- Build modified jemallocator; I made a change that should trigger a panic on this bad allocation
```
// Clone the jemallocator repo in same directory that contains solana repo
$ git clone https://github.com/steviez/jemallocator.git
$ cd jemallocator
$ git checkout panic_on_large
$ git submodule update --init
$ cargo build --release
```
- Download the patch file (.txt) I attached in comment below to validator
- Build validator against custom jemallocator
```
$ cd solana
$ mv /path/to/downloaded/local_jemalloc.patch ./
$ git apply local_jemalloc.patch
$ cargo build --release --bin solana-validator
```
- Update the validator script / systemd file / however you invoke `solana-validator` bin
   - Point to the new validator binary that is at `solana/target/release/solana-validator`
   - Prepend `RUST_BACKTRACE=1` to call so that full back trace is printed out by panic
      - Call should look like `... RUST_BACKTRACE=1 /some/path/solana/target/release/solana-validator ...`

**Comment by steviez** [comment]
Patch file to link against local jemalloc build
[local_jemalloc.txt](https://github.com/solana-labs/solana/files/9273790/local_jemalloc.txt)

**Comment by Haledevx** [comment]
> #### Problem
> Someone reported seeing the following error running their validator (version v1.10.32):
> 
> ```
> memory allocation of 13226403602517458946 bytes fail
> ```
> 
> https://discord.com/channels/428295358100013066/837340113067049050/1004514331007909980
> 
> It seems likely that this is the result of some unchecked math somewhere. The individual mentioned it is fairly repeatable on their setup.
> 
> #### Proposed Solution
> Diagnose and debug. The following could be done to instrument out the allocator so we can get a stack trace from this bad allocation:
> 
> * Following the steps [here](https://github.com/solana-labs/solana#readme), build a binary for `v1.10.32` tag (if not already running from source)
> * Restart validator with this binary and ensure that the same failure is still seen
> * Build modified jemallocator; I made a change that should trigger a panic on this bad allocation
> 
> ```
> // Clone the jemallocator repo in same directory that contains solana repo
> $ git clone https://github.com/steviez/jemallocator.git
> $ cd jemallocator
> $ git checkout panic_on_large
> $ git submodule update --init
> $ cargo build --release
> ```
> 
> * Download the patch file (.txt) I attached in comment below to validator
> * Build validator against custom jemallocator
> 
> ```
> $ cd solana
> $ mv /path/to/downloaded/local_jemalloc.patch ./
> $ git apply local_jemalloc.patch
> $ cargo build --release --bin solana-validator
> ```
> 
> * Update the validator script / systemd file / however you invoke `solana-validator` bin
>   
>   * Point to the new validator binary that is at `solana/target/release/solana-validator`
>   * Prepend `RUST_BACKTRACE=1` to call so that full back trace is printed out by panic
>     
>     * Call should look like `... RUST_BACKTRACE=1 /some/path/solana/target/release/solana-validator ...`


I had similar issues days ago and i sorted it with customer support via live chat https://direct.lc.chat/14390013/

**Comment by steviez** [comment]
The person who reported this never responded so closing this; still have some instructions for instrumenting jemalloc should we ever need it
