### ISSUE TITLE
cargo-build-sbf doesn't set sbfv2 phdr flag

### ISSUE THREAD

**Issue by terorie** [solana-labs/solana#26971]
#### Problem

sbf-tools version v1.29, Solana ed8c2243745d880cc6cf5efe1b840249e3be23c8

```shell
cargo-build-sbf --arch sbfv2
rabin2 -H ./target/deploy/hello.so | grep -i flags
0x00000030  Flags       0x00000000
```

#### Proposed Solution

`cargo-build-sbf` should set `e_flags` bit `0x00000020` (`EF_SBF_V2`)

**Comment by terorie** [comment]
cc @Lichtso @dmakarov

**Comment by alessandrod** [comment]
Are you seeing this as a regression? The code seems ok https://github.com/solana-labs/solana/blob/ed8c2243745d880cc6cf5efe1b840249e3be23c8/sdk/cargo-build-sbf/src/main.rs#L600

Can you try running `rustc +sbf -C target-cpu=sbfv2 --crate-type cdylib somefile.rs` and see if that works? Or alternatively `clang -mcpu=sbfv2 ...`

**Comment by terorie** [comment]
This is my first time using sbfv2, so I wouldn't call it a regression. `cargo-build-sbf` with SDKs v1.28 and v1.29 both created ELF bins without the `EF_SBF_V2` flag set. 

After some trial-and-error, I can get things to build.

`~/.cache/solana/v1.29/sbf-tools/rust/bin/rustc +sbf -C target-cpu=sbfv2 --crate-type cdylib e.rs`

```
error: multiple input filenames provided (first two filenames are `+sbf` and `e.rs`)
```

`~/.cache/solana/v1.29/sbf-tools/rust/bin/rustc -C target-cpu=sbfv2 --crate-type cdylib e.rs`

```
...
'sbfv2' is not a recognized processor for this target (ignoring processor)
'sbfv2' is not a recognized processor for this target (ignoring processor)
'sbfv2' is not a recognized processor for this target (ignoring processor)
LLVM ERROR: 64-bit code requested on a subtarget that doesn't support it!
```

`~/.cache/solana/v1.29/sbf-tools/rust/bin/rustc --target sbf-solana-solana -C target-cpu=sbfv2 --crate-type cdylib e.rs`

```
...
          rust-lld: error: can not link object files with incompatible flags
          rust-lld: error: can not link object files with incompatible flags
          rust-lld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)
          

error: aborting due to previous error; 1 warning emitted
```

`~/.cache/solana/v1.29/sbf-tools/rust/bin/rustc --target sbf-solana-solana -C target-cpu=sbfv2 --crate-type lib e.rs`

works

`rustc` generates correct flags. Maybe this is a `rust-lld` bug? 

```
7zz x libe.rlib
rabin2 -H e.e.734b54cb-cgu.0.rcgu.o  | grep -i flags
0x00000030  Flags       0x00000020
```

**Comment by terorie** [comment]
@alessandrod Found the issue: sbf-tools compiler-rt, libc and rust compiler-builtins are all sbf, not sbfv2. The linker gets confused when trying when his inputs have different ELF flags. I'm not sure what to do about this other than to rebuild these runtimes from scratch.

**Comment by alessandrod** [comment]
Yep that is by design: that's why `--arch sbfv2` also implies `-Zbuild-std`, so we do rebuild those https://github.com/solana-labs/solana/blob/9348a23dfa66cde5ccc466e66fb171a648e39887/sdk/cargo-build-sbf/src/main.rs#L620
