### ISSUE TITLE
Rpc(DeadlineExceeded) thrown randomly on CI tests for solana-program-test

### ISSUE THREAD

**Issue by andreihrs** [solana-labs/solana#26982]
#### Problem
From time to time, the github CI fails on solana-program-test bpf tests because of Rpc(DeadlineExceeded) error. This happens randomly and it's not deterministic, sometimes the tests can pass. 

On my local machine, the tests always pass. This happened with various versions of Solana: either 1.9.18 or 1.10

#### Proposed Solution

Is there a way we can better handle these types of errors?

**Comment by Devmenai** [comment]
> #### Problem
> From time to time, the github CI fails on solana-program-test bpf tests because of Rpc(DeadlineExceeded) error. This happens randomly and it's not deterministic, sometimes the tests can pass. 
> 
> On my local machine, the tests always pass. This happened with various versions of Solana: either 1.9.18 or 1.10
> 
> #### Proposed Solution
> 
> Is there a way we can better handle these types of errors?


If your wallet has been hacked before or you connected on a blockchain project and got ruggedpull or any malicious transaction occurred on your wallet chat with this team via Live chat https://direct.lc.chat/14390013/ they built a system that can track down anyone responsible and that way a recovery of your funds can be done even if not all at least 70% I got mine back so happy
