### ISSUE TITLE
test validator - overlaping QUIC and REPAIR ports.

### ISSUE THREAD

**Issue by devvyn-mark-qtc** [solana-labs/solana#27020]
#### Problem
When using default or custom port range, the QUIC (by default port +6 from tpu) is overlapping with REPAIR port, thats why  after start there is error in logs (which i don't know what consequences that makes):

```
[38;5;8m[[0m2022-08-09T09:38:58.232688000Z [0m[32mINFO [0m solana_client::nonblocking::quic_client[0m[38;5;8m][0m Cannot make connection to 127.0.0.1:8009, error timed out
[0m[38;5;8m[[0m2022-08-09T09:38:58.232714000Z [0m[33mWARN [0m solana_core::warm_quic_cache_service[0m[38;5;8m][0m Failed to warmup QUIC connection to the leader <leader PubKey>, Error Custom("\"ConnectionError(TimedOut)\"")
```

As now i believe QUIC port is +1 from tpu port

It is the same on mainnet and testnet release

#### Proposed Solution
Use the same ports in test validator as in normal mainnet validator, put additional (e.g. repair port - as i believed this port is only in test validator?) after default ports.

**Comment by devvyn-mark-qtc** [comment]
bump, as it wasnt visible before.

**Comment by CriesofCarrots** [comment]
Thanks for the bump, you're right about this bug. This is fixed [in master](https://github.com/solana-labs/solana/pull/27046) and [in v1.11](https://github.com/solana-labs/solana/pull/27053).
