### ISSUE TITLE
QUIC to RPC works, but not to QUIC port on local test validator

### ISSUE THREAD

**Issue by devvyn-mark-qtc** [solana-labs/solana#27022]
#### Problem
hello,

I'm able to connect with QUIC to my local validator to RPC port, but im not able to connect to QUIC port to send serialized tx. There is correct connection status, but after that status there is instant connection close recived with error `code 0x178, reason peer doesn't support any known protocol`:
```
TLS State.CLIENT_HANDSHAKE_START -> State.CLIENT_EXPECT_SERVER_HELLO
Network path ('::ffff:127.0.0.1', 8006, 0, 0) discovered
QuicConnectionState.FIRSTFLIGHT -> QuicConnectionState.CONNECTED
Connection close received (code 0x178, reason peer doesn't support any known protocol)
QuicConnectionState.CONNECTED -> QuicConnectionState.DRAINING
Discarding epoch Epoch.INITIAL
Discarding epoch Epoch.HANDSHAKE
Discarding epoch Epoch.ONE_RTT
QuicConnectionState.DRAINING
```
The port 8004 is on test validator the quic port, as 8009 is Repair port.

I believe it comes from rustls implementation while making handshake - [RaiseErrorPlace](https://rust.velas.com/src/rustls/server/hs.rs.html#171), but it does not accept any ALPN - i think i have checked all of them :D

Any clue why is it working on RPC but not on QUIC port?

#### Proposed Solution
No clue

**Comment by devvyn-mark-qtc** [comment]
bump, as it wasnt visible before.

**Comment by KirillLykov** [comment]
did this https://github.com/solana-labs/solana/pull/27096 fix the issue?

**Comment by CriesofCarrots** [comment]
Thanks for the issue. This is already fixed [in master](https://github.com/solana-labs/solana/pull/27046) and [in v1.11](https://github.com/solana-labs/solana/pull/27053).
