### ISSUE TITLE
Most validator info accounts are below rent exempt minimum

### ISSUE THREAD

**Issue by michaelh-laine** [solana-labs/solana#27032]
#### Problem
It has been discovered that many validator info accounts (Config program Config1111111111111111111111111111111111111) have a balance which is below the rent exempt minimum.

This was discovered as part of an investigation into why a validator's meta data no longer appeared on some website (melea 1, identity 6TkKqq15wXjqEjNg9zqTKADwuVATR9dW3rkNnsYme1ea).

From the logs of stakewiz.com I ascertained the former info account was F5jShAZ9HM1BMgySf7Zbb2wDztX3MszP1Qmx3WXGDLxB and upon checking it the account shows in explorer as a balance of 0.

`solana validator-info get F5jShAZ9HM1BMgySf7Zbb2wDztX3MszP1Qmx3WXGDLxB` returns no account found.

From the stakewiz logs the disappearance of this account was narrowed down to the time frame 2022-08-05 09:20:00 to 2022-08-05 09:21:06 (UTC). Reviewing the blocks in this range (144641054 to 144641172) identified a rent charge in block 144641072

`  F5jShAZ9HM1BMgySf7Zbb2wDztX3MszP1Qmx3WXGDLxB       rent        -◎0.000007403   `

After reporting this in #mb-validators on Discord further investigation by @bji found that a vast majority of validator info accounts are below rent exempt minimum. With rent at 7403 lamports the next lowest account will be deleted in approximately 5 epochs. 

#### Proposed Solution
- Amend the CLI to check rent exempt minimum on account update and fund the account sufficiently when updating validator info (and ensure it is being funded sufficiently on creation). 
- Inform validators to check their accounts and fund them appropriately.

**Comment by Benhawkins18** [comment]
To prevent this from being an issue I just went ahead and funded all of the info accounts to 00536616

**Comment by michaelh-laine** [comment]
Everstake's info account has been deleted today as it ran out of rent. 

Info address: `HtTXbo54LZCeAfn6CQsyPNYdGH4qZLajjkAzvDnSZoyT`
Vote identity: `9QU2QSxhb24FUX3Tu2FpczXjpK3VYrvRudywSZaM29mF`

**Comment by michaelh-laine** [comment]
```
"vote_identity","time"
"52HBJgFBWwMSk6maAqMshgc1iniQKrRiTgXsQCCT66XA","2022-08-09 11:17:03.618705+00"
"H3GhqPMwvGLdxWg3QJGjXDSkFSJCsFk3Wx9XBTdYZykc","2022-08-08 19:30:08.946681+00"
"9QU2QSxhb24FUX3Tu2FpczXjpK3VYrvRudywSZaM29mF","2022-08-05 21:13:07.776122+00"
"ateamaZDqNWDztxnVKZhRsp4ac53KvT1rVKyU5LnL6o","2022-08-05 19:26:09.657522+00"
"GMpKrAwQ9oa4sJqEYQezLr8Z2TUAU72tXD4iMyfoJjbh","2022-08-05 14:19:04.600334+00"
"GvZEwtCHZ7YtCkQCaLRVEXsyVvQkRDhJhQgB6akPme1e","2022-08-05 09:21:06.253065+00"
"76nwV8zz8tLz97SBRXH6uwHvgHXtqJDLQfF66jZhQ857","2022-08-05 09:19:05.615108+00"
"9hRVfSz8GudfGFQd3X7HTjaGRiuwj7dpjS3jtuy8c7mk","2022-08-03 16:27:32.226752+00"
"9v5gci7uDiaGKRmQ2dn6WJMB94YqFaVFBTiFzBzNhyaw","2022-08-03 12:36:04.423853+00"
"9ALSmhwUWrpTyVMLb6YbH3jp1VxctRYjXv73hyDh67X8","2022-08-03 04:20:17.738594+00"
"6ffMj7zE7u9PKBzQHfv5nsHEGvDXZkntLnFeXRRudEEH","2022-07-31 22:33:32.244236+00"
"DY4dSYQXFYzaZKapkNHt1iG2yxBf6y2mxSD7UfWfvMee","2022-07-13 20:35:07.694375+00"
"8C49wG9uXaParCrhCP8mv48NYV4P952rUoQf8AwoJyQj","2022-07-13 20:35:04.697813+00"
"5PyiGb6dNrCaKTkMfovKRQPYgH5zizcsvXp9YUAVWqbo","2022-07-12 12:01:32.652751+00"
"HgovzvawYMRPY6Go2kaQF1vLR4rNixooHKrUWSH6aW4C","2022-07-12 10:08:32.673164+00"
"s1V1Y1XFHfr6pqs6edVNzA3W1kf9ye2J3VhrgKMQyb5","2022-07-12 08:24:38.999192+00"
"HcHHb1ZfmCxpyJmXWcvsGqPjYGCyUTfXs7nMKYesVicm","2022-07-12 08:04:32.757438+00"
"3hHSwKHgnrbVDBWfkx6TJY1WABUoRs7Ve57sRTg9rAY9","2022-07-12 07:13:02.913708+00"

```

CSV of validators likely affected by this in the past month (data isn't perfect so might not all be affected and might not be a complete list)
