### ISSUE TITLE
web3.js: potential bug with confirmTransaction

### ISSUE THREAD

**Issue by samlaf** [solana-labs/solana#27078]
Hello, I'm running into an issue when using web3.js that my `createAccount` transactions are not being awaited when running through confirmTransaction with commitment "confirmed". I've written the issue in detail on [stackexchange](https://solana.stackexchange.com/questions/1868/confirmtransaction-not-waiting-for-createaccount-to-have-been-created) so I won't repeat it here.

Would really appreciate some help figuring out what I am misunderstanding if this is not a bug...
Thank you :)

**Comment by Fahad-pnw** [comment]
you figured a solution on this? @samlaf

**Comment by Fahad-pnw** [comment]
just gone over your stackexchange link, could you confirm that commitment status finalized ensures that a transaction has been executed?
also, if you can give me a hint on figuring if a tx was successful or not, that would be TERRIFIC!

**Comment by steveluscher** [comment]
Let's keep all of the discussion in Stack Exchange! I'll answer you there.

**Comment by samlaf** [comment]
Thanks guys. Haven't touched Solana since I wrote this question, so I'm forgetting the details... :\
But thanks for answering! I will definitely come back to this when I get back to Solana.
