### ISSUE TITLE
Re-Enable spl in downstream-projects CI build

### ISSUE THREAD

**Issue by steviez** [solana-labs/solana#27093]
#### Problem

We recently updated the rocksdb dependency version in https://github.com/solana-labs/solana/pull/26949. This update was needed to address a [security advisory with rocksdb](https://discord.com/channels/428295358100013066/560503042458517505/1007294037264453702). However, CI didn't pass for `downstream-projects` in that PR.

This repo builds `solana-program-library` (spl) as part of `downstream-projects` CI step. However, spl depends on specific crate versions of this repo. Currently, spl depends on v1.10 solana crates, and thus, version `1.59.0` of rust/cargo. As Tyera called out [here](https://discord.com/channels/428295358100013066/560503042458517505/1007332476311588874
), that older version is preventing cargo from "finding" the newer release of rust-rocksdb.

As such, we are temporarily disabling `spl` from the CI step.

#### Proposed Solution
Re-enable spl in CI once spl updates to v1.11 solana crates

**Comment by steviez** [comment]
FYI @joncinque

**Comment by steviez** [comment]
To my surprise, disabling this step in CI seems unnecessary:
https://github.com/solana-labs/solana/pull/27089#issuecomment-1212580541

This was a PR that was based on the rocksdb version update commit, and all steps passed as-is

**Comment by joncinque** [comment]
This was recently re-enabled, so we can close as complete
