### ISSUE TITLE
Consider renaming or formally defining "last_id"

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#2710]
We use the term "last_id" to define the entry id of a recent tick what needs to be included in a transaction to avoid double spends.  The term is pervasive through the main code base and is exposed in client APIs yet it is not defined in the Solana Architecture book.   Further a last_id is in no way the “last” entry id, it's just an id recently generated by the cluster.

Some options:
1. Keep the term "last_id" and add it to the Solana Architecture terminology.
2. Rename "last_id" to "recent_tick_id", since that's what it currently is
3. If by the time work starts on this issue, we have modified transactions to require a block id  (which at this time doesn't exist in the code base) instead of an entry id, rename "last_id" to "recent_block_id".

**Comment by garious** [comment]
I'd also like to restrict the use of the term "id" to only public keys.  `recent_tick_hash` seems like the most precise term to me.

**Comment by mvines** [comment]
Switching from `tick id` to `block id` is growing on me:
1. The current sub-second resolution feels like overkill, 8x the state for each node to store, and the slower rate might actually accidentally help prevent double spends by dumb clients that retry too fast (more likely they hit a duplicate signature error).  
2. `block id`s are also tied to confirmation time and is probably what users will really care about, so not having to worry about how a user maps `tick id` to `block id` is also compelling to me.

**Comment by rob-solana** [comment]
are there any cases where a programs might want to issue 2 TXs that would be identical save their last_id?  at present, programs are limited to 8 such TXs/s.  this move would make that 1 such TX/s.

the main cost of a last_id isn't the ID itself, but the status caches attached to them.  with the bloom filter-based dup protection, those would have to grow (but only by logN, saving space). we wouldn't save space on errors, though.

**Comment by mvines** [comment]
> are there any cases where a programs might want to quickly issue 2 TXs that would be identical save their last_id?

I can't think of any realistic use cases for wanting to do this.

**Comment by rob-solana** [comment]
i+=1 ? ;)

**Comment by mvines** [comment]
If incrementing faster than block production, why not send `i += n` in a single transaction.  It'll be cheaper and more reliable.

**Comment by rob-solana** [comment]
I'm only suggesting that instructions might be really simple and that programs might not like having to wait, but I suppose they're already waiting an eternity in computer time.

**Comment by mvines** [comment]
Ok so the current plan is to rename `last_id` to `recent_block_hash`

1. Modify [Bank::register_tick](https://github.com/solana-labs/solana/blob/b9524217feeea6a377127c1bbdeab683977f070c/runtime/src/bank.rs#L308) to only register the last tick in a block as a `last_id`.   This turns `last_id`s into `block hash`, where the hash of a block is defined by it's final tick hash.
2. Global rename of `last_id` to `recent_block_hash`.
3. Global rename of anything Hash-like to `hash` instead of `id` (reserve `id` only for pubkey identities).

**Comment by garious** [comment]
@mvines What do you think of `blockhash` one word?  And instead of `recent_blockhash_queue`, how about just `blockhash_queue`?

**Comment by mvines** [comment]
[This](https://github.com/solana-labs/solana/blob/b9524217feeea6a377127c1bbdeab683977f070c/src/entry.rs#L48) would be an example of an `entryhash` then?

**Comment by garious** [comment]
hmm, you talked me out of it.  How about `block_hash` and `hash_queue`, where a HashQueue that's used to store block hashes is called `block_hash_queue: HashQueue`?

**Comment by mvines** [comment]
sgtm!

**Comment by sunnygleason** [comment]
@mvines one thing I wondered about, does this hash refer to "time", and/or a notion of "convergence"? From a client perspective, wondering what happens if a different fork gets chosen. Is it, "replay all previous transactions against the new block hash"? In which case, there might be a pileup > 1rq/s maybe?

**Comment by mvines** [comment]
The `hash` is derived by running PoH and processing transactions until the end of a block.  So it represents a unique location in the ledger, and if you had a second `hash` it would be possible to compute a rough estimate of time elapsed between those two hashes.

A hash can only exist in one fork.  If you find yourself on a different fork that doesn't contain a given hash you knew about in the past, the client may need to resend any transactions that didn't make it.  The cluster won't migrate transactions for you between forks
