### ISSUE TITLE
Benchmark real-data for proposed scheduler(s)

### ISSUE THREAD

**Issue by apfitzge** [solana-labs/solana#27114]
Benchmark proposed scheduler using real network data for comparison with other proposed/current scheduling algorithms

**Comment by mschneider** [comment]
I have been working on a more realistic testnet benchmark that simulates a bunch of market makers trading on mango. LMK if you start working on this, hope we can help here.

**Comment by mschneider** [comment]
also added this metric so we can see how often the current scheduler stalls accounts due to concurrent access from multiple threads: https://github.com/solana-labs/solana/pull/27654
