### ISSUE TITLE
Unable to build vue3 application with Solana as a dependency (BigNumber issue)

### ISSUE THREAD

**Issue by boostie** [solana-labs/solana#27155]
Hi all, 

I am not able to execute Vue3 application running as Nuxt + Vipe with the following error:

```
Big integer literals are not available in the configured target environment ("chrome87", "edge88", "es2020", "firefox78", "safari13" + 2 overrides)

    node_modules/@solana/web3.js/lib/index.browser.esm.js:4466:20:
      4466 │     const U64_MAX = 2n ** 64n - 1n;
```

The package is being built with target of 'esnext' and I have tried transpiling the dependency, switching the target and adding libs for es2020, but without luck. Anyone experienced the same issue?

**Comment by Yusuf-Uluc** [comment]
@boostie did you find a solution? tried the same things and I am using Nuxt3 as well.

**Comment by Yusuf-Uluc** [comment]
I think this likely has to do with Vite 3

**Comment by steveluscher** [comment]
To add to that, stackoverflow is probably a better place to ask for help, because this is a JavaScript build issue, and not a Solana issue.

For reference, see the [compatibility](https://github.com/solana-labs/solana/blob/master/web3.js/README.md#compatibility) section of the web3.js README!
