### ISSUE TITLE
Infinite loop with accountSubscribe 

### ISSUE THREAD

**Issue by laterbreh** [solana-labs/solana#27167]
We are currently on 1.52 (https://github.com/solana-labs/solana-web3.js/releases/tag/v1.52.0) and we are still experiencing this issue. 
(wallet address ommited)
`accountSubscribe error for argument [
  'XXXXXXXXXXXXXXXXXXXX',
  { encoding: 'base64', commitment: 'finalized' }`
  
  We never get more than 3 to 5 subscriptions. We actively track and unsubscribe from the wallets every X minutes. When this occurs, we hit 99% cpu usage and our gateway locks up.

_Originally posted by @laterbreh in https://github.com/solana-labs/solana/issues/26665#issuecomment-1214200115_

**Comment by steveluscher** [comment]
I still believe this to be due to a bug in `rpc-websockets` (#25578). Are you finding, too, that the library believes the websocket to still be open, when in fact it has closed?

**Comment by steveluscher** [comment]
@laterbreh, if you're still experiencing this problem, can you try to upgrade to an experimental release, by running `yarn add @solana/web3.js@pr-29195`? That's a package built from PR #29195.

Let me know if that fixes anything.
