### ISSUE TITLE
CLI `solana deploy` makes no mention of being non-upgradeable

### ISSUE THREAD

**Issue by coudron** [solana-labs/solana#27228]
### Problem
Running `solana deploy --help` makes no mention of deploying non-upgradeable program. 

#### Proposed Solution
Add a warning that tells users this will deploy a non-upgradeable program. If they want deploy an upgradable program, use `solana program deploy`

**Comment by CriesofCarrots** [comment]
True, `solana --help` avoids mentioning the `deploy` subcommand for this very reason.
A pull request adding this warning would be very welcome

**Comment by coudron** [comment]
@CriesofCarrots PR opened here: https://github.com/solana-labs/solana/pull/27264
