### ISSUE TITLE
Signing transactions with derived addresses on Ledger gives confusing output on the command line

### ISSUE THREAD

**Issue by Gsuz** [solana-labs/solana#27230]
#### Problem
We saw this when signing a multisig transaction using the spl-token program. When outputting the text "Waiting for your approval on ledger. It always shows your default ledger public Key and not the one you're actually signing with.
For example. 

spl-token authorize --multisig-signer $'usb://ledger/?key=1'

gives the following result in the following output:

Waiting for your approval on Ledger hardware wallet usb://ledger/(Default ledger public Key)    <-- not the public Key I'm signing with.

After signing you get the correct output.

(correct publicKey for key=1) = signature

#### Proposed Solution
output the correct address when waiting for approval on the ledger hardware wallet.

**Comment by CriesofCarrots** [comment]
The cli uses the default ledger public key as an identifier for the device. The intent of that print is to let the user know which device to go to for signing.
But I can see how it would be useful to reiterate the current signing key. What about something like:
```
Waiting for your approval on Ledger hardware wallet usb://ledger/<DEFAULT_KEY>
Signing as `<AUTHORITY_TYPE>` with key: `?key=1`
```

**Comment by Gsuz** [comment]
> The cli uses the default ledger public key as an identifier for the device. The intent of that print is to let the user know which device to go to for signing. But I can see how it would be useful to reiterate the current signing key. What about something like:
> 
> ```
> Waiting for your approval on Ledger hardware wallet usb://ledger/<DEFAULT_KEY>
> Signing as `<AUTHORITY_TYPE>` with key: `?key=1`
> ```

This would be clarifying.
