### ISSUE TITLE
Bug: Details page for address lookup table accounts does not appear

### ISSUE THREAD

**Issue by Arrowana** [solana-labs/solana#27287]
#### Problem
#27133 does not show Table entries for address Lookup table accounts because the validator returns jsonParsed so `details.rawData` is undefined

I tested with a local test validator,

the woraround to make it appear is to add the raw fetch in `fetchAccountInfo` `rawData: (await connection.getAccountInfo(pubkey))?.data`

#### Proposed Solution
I think it is indeed more straightforward to deserialize the data `Buffer` rather than handle the parsed json.

I think it could be fixed by fetching the necessary `AccountInfo<Buffer>` account in the `AddressLookupTableAccountSection`

**Comment by Arrowana** [comment]
Example https://explorer.solana.com/tx/45xmWZvuCHGX88eMimUzSautudjigmk4Wr6fMYUhuZj4d7E8J1Qv8zVxBa8Z6ceFut293LNWua59onmHbQurauKn?cluster=devnet

**Comment by jstarry** [comment]
Thanks for the report @Arrowana!
