### ISSUE TITLE
Need a design proposal that covers all the slashing conditions

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#2731]
#### Problem

Slashing is something that is mentioned in fork selection, leader rotation.  But there is no explicit list of how slashing proofs work for each slashable offense.

#### Proposed Solution

Write the doc.  Should cover:

* slashing due to contentious fork at lockout. 
* slashing due to voting back in time
* duplicate ledger generation

The slashing proofs need to be fast to verify by the network.

**Comment by mvines** [comment]
"a 72 hour freeze is prolly what we should start with" - anonymous

**Comment by aeyakovenko** [comment]
maybe a 1-5% slashing as well.
