### ISSUE TITLE
Client reorg follow-up

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#27352]
#### Problem
https://github.com/solana-labs/solana/pull/27246 splits `solana-client` so that its constituent clients can be more-easily imported downstream. But some follow-up work would make the arrangement even better.

#### Proposed Solution
- [x] Replace all monorepo imports of solana-client with specific client crate
- [ ] Rework ClientErrorKind so that the common `rpc-client-api` crate doesn't depend on reqwest
- [ ] Rework modules in solana-tpu-client so that quic- and udp-clients can be split to their own modules - started here https://github.com/solana-labs/solana/pull/28080
- [x] Move rpc_client with_spinner methods behind a feature, making indicatif dependency optional
- [ ] Consider moving mock_sender to its own crate
- [x] Ask @brson to correct any documentation snafus I made 🙏

**Comment by brson** [comment]
I'll take another pass at the various client crate docs once https://github.com/solana-labs/solana/pull/27188 lands.
