### ISSUE TITLE
My lamports can`t transfer to another account

### ISSUE THREAD

**Issue by pengten** [solana-labs/solana#27369]
#### Problem

If there are 891000 lamports in my account, i can`t transfer all of these to another rich account. 
It say "Transaction simulation failed: Transaction results in an account (0) without insufficient funds for rent".

**Comment by pengten** [comment]
No,Maybe this is a bugfix.

**Comment by CriesofCarrots** [comment]
```
$ solana rent 0 -um
Rent per byte-year: 0.00000348 SOL
Rent per epoch: 0.000002439 SOL
Rent-exempt minimum: 0.00089088 SOL

$ solana fees -um
Blockhash: ...
Lamports per signature: 5000
Last valid block height: ...
```
If your original account is the fee payer for the transaction, it needs to have 5000 lamports (transaction fee) + 890880 lamports (rent-exempt minimum for new account) = 895880. You'll need to use a different fee-payer to empty an account with that balance.

This could have been answered more quickly on Solana Stack Exchange. Cheers.

**Comment by pengten** [comment]
> You'll need to use a different fee-payer to empty an account with that balance (891000).

But it transfer to an account not new,  i don`t care the rent-exempt minimum for the the account.   
exp:  account A has 891000 SOL, account B has 1000000000 SOL.   I want transfer all SOL from A to B.
