### ISSUE TITLE
Feature Gate: Raise minimum stake delegation to 0.1 SOL

### ISSUE THREAD

**Issue by michaelh-laine** [solana-labs/solana#27395]
### Description

Increase the minimum delegation for new stake accounts to 0.1 SOL to reduce the creation of many small accounts that impact performance.

To be approved through governance vote.

### Feature ID

3Ynd8eXcJQVc79V75dH1Ut4JR5taoRG7j4oYJKQUpaGd

### Activation Method

Staked Validator Vote

**Comment by bardo-hub** [comment]
b
