### ISSUE TITLE
Investigate "large-allocation pool" idea

### ISSUE THREAD

**Issue by apfitzge** [solana-labs/solana#27449]
Explore and test idea of having a large-allocation pool.

This would involve:
1. Having some allocation limit (possibly dynamic?) above which a tx would be considered/labeled a "large allocation"
2. Transactions that have large allocations would need to write-lock a "large allocation pool account"

By forcing large allocation transactions to write-lock a large allocation account, the proposed scheduling logic would make large allocations dynamically priced via additional user-fees.

This should only be explored after the improved schedulers have been implemented.

Anatoly posted idea here in discord: https://discord.com/channels/428295358100013066/941012574978318467/1000301339278057542

**Comment by aeyakovenko** [comment]
I think we might also need to consider to run a longer auction for large allocations.  Otherwise it maybe a latency game.
