### ISSUE TITLE
Refactor fullnode pipeline to split TVU

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#2752]
#### Problem
The ReplayStage is not directly connected with the RetransmitStage. It should be pulled out of TVU to simplify the TVU pipeline.

#### Proposed Solution
The ReplayStage can be pulled out of TVU. The rest of fullnode also needs a refactor based on this proposal: https://github.com/solana-labs/solana/pull/2742

**Comment by garious** [comment]
@pgarg66, bump this one back a milestone?

**Comment by pgarg66** [comment]
Sure. We also need to see if this is relevant anymore since the refactor.

**Comment by rob-solana** [comment]
how does TVU get simpler?  right now its just a grouping of services that have to be up in a fullnode that's validating, right?

**Comment by pgarg66** [comment]
Yeah, I don't think TVU itself is getting simpler as it stands today. ```tvu.rs``` has two disjoint pipelines in it. The idea is to split them into their own. It's more of a code cleanup, than design change.

**Comment by mvines** [comment]
>  It's more of a code cleanup, than design change.

That's enough justification for me to punt this to a much later milestone.  :)
