### ISSUE TITLE
@solana/web3.js: CRA fails to compile

### ISSUE THREAD

**Issue by jaytecch** [solana-labs/solana#27535]
Once I import the Solana web 3.js library. My react code fails to compile with an error. 

Failed to parse source map from '/data/data/com.termux/files/home/alchemi/node_modules/@solana/buffer-layout/src/Layout.ts' file: Error: ENOENT: no such file or directory, open '/data/data/com.termux/files/home/alchemi/node_modules/@solana/buffer-layout/src/Layout.ts

Please I really need your help to get this to work

**Comment by steveluscher** [comment]
A source map is not source code, and the error you pasted in says ‘Failed to parse source map.’ Figure out what's trying to parse a source map and why.

**Comment by janeklb** [comment]
This error started showing up for me too once I updated to webpack5. The full warning output is

```
WARNING in ../../node_modules/@solana/buffer-layout/lib/Layout.js
Module Warning (from ../../node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '/Users/janek/git/<REDACTED>/node_modules/@solana/buffer-layout/src/Layout.ts' file: Error: ENOENT: no such file or directory, open '/Users/janek/git/<REDACTED>/node_modules/@solana/buffer-layout/src/Layout.ts'
 @ ../../node_modules/@solana/web3.js/lib/index.browser.cjs.js 12:19-51
 @ ../../libs/shared/src/lib/common-types/solanaKeys.ts 2:0-44 7:87-106 7:111-120 11:8-17
 @ ../../libs/shared/src/index.ts 34:0-46 34:0-46
 @ ./src/components/Auth/auth.context.tsx 5:0-62 46:34-48 47:56-65
 @ ./src/app.tsx 6:0-76 15:26-38 16:34-46
 @ ./src/main.tsx 5:0-28 16:32-35

```
