### ISSUE TITLE
RPC API getSignaturesForAddress sends undocumented field "confirmationStatus"

### ISSUE THREAD

**Issue by serejke** [solana-labs/solana#27569]
#### Problem

[getSignaturesForAddress](https://docs.solana.com/developing/clients/jsonrpc-api#getsignaturesforaddress) RPC API responds with **undocumented** `confirmationStatus`, for example, given an RPC request:
```
curl https://api.mainnet-beta.solana.com -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getSignaturesForAddress",
    "params": [
      "pxymi438mp6UpMjgXs4oRJGEwfF94vbnNkyEWLbWKbR",
      {
        "limit": 1
      }
    ]
  }
'
```

the response:
```
{
  "jsonrpc": "2.0",
  "result": [
    {
      "blockTime": 1662094092,
      "confirmationStatus": "finalized",
      "err": null,
      "memo": null,
      "signature": "5F8XLZ5hghz77GQP93BLwEYt8AU2pSw5qTdKevR8g1BEPkQ9aH53CothbLaHbUvjgA2n431kZNpDtjd8DYm657Ta",
      "slot": 148749545
    }
  ],
  "id": 1
}
```

The field `confirmationStatus` is not documented in the [RPC response](https://docs.solana.com/developing/clients/jsonrpc-api#results-30) although it is very *useful*. I've encountered this problem during development of an on-chain game http://solana-place.com/ where I need to show changes history. Without that field I would need to make additional [getSignatureStatus](https://docs.solana.com/developing/clients/jsonrpc-api#getsignaturestatuses) calls to get the finality of transactions.

I'm wondering whether I can rely on its presence in RPC responses. Unfortunately, that field is not present in the `solana-web3`'s [ConfirmedSignatureInfo](https://github.com/solana-labs/solana-web3.js/blob/4f2d052e82422d64ab7d2819575418bd0932d14e/src/connection.ts#L2359) so I need to do an unchecked cast like
```
const confirmedSignatureInfoAny: any = confirmedSignatureInfo
const confirmationStatus: "confirmed" | "finalized" = confirmedSignatureInfoAny['confirmationStatus']
```

#### Proposed Solution
Document the `confirmationStatus` field if it is a de-facto part of the RPC response.

**Comment by CriesofCarrots** [comment]
A pull request updating the docs would be very welcome

**Comment by serejke** [comment]
@CriesofCarrots I'll be glad to make a PR. Just wanted to reassure that the mentioned field is mandatory of the RPC response. At least on Mainnet API & Alchemy & Quicknode this is true.

**Comment by CriesofCarrots** [comment]
> I'll be glad to make a PR. Just wanted to reassure that the mentioned field is mandatory of the RPC response. At least on Mainnet API & Alchemy & Quicknode this is true.

Thanks. I'm not sure "mandatory" is the right word, but that response field has been in the code for 17 months so it definitely should be in the docs.
