### ISSUE TITLE
More granular details in `solana-validator monitor` for LoadingLedger phase

### ISSUE THREAD

**Issue by DaveWK** [solana-labs/solana#27581]
#### Problem
The startup of a node takes a while, and can get slowed down or stuck for a variety of reasons. For most stages of this startup, the `solana-validator monitor` command provides some helpful information to know where the node is in the startup process, which helps narrow down the scope for troubleshooting. The problem is, that the `LoadingLedger` state takes a very long time and has a number of subtasks which are hidden to the end user. This makes it hard to identify performance bottlenecks or issues.

#### Proposed Solution
The LoadingLedger phase should be broken up into smaller phases, or expose more details of the subphases.

Some subphases could be:
IndexingAccounts (including which index name it is creating, which indicies it has already made, and which are remaining)
HardenedUnpack (including the progress)
Shrinking RocksDB (including the target size vs current size)
Deleting Dead Account Metadata (and progress)

some of these steps may be concurrent, in which case they should be included on the same screen for good legibility.

**Comment by steviez** [comment]
I assume this comment is directed at v1.10.

In > v1.10, there is additional clarity on this step via https://github.com/solana-labs/solana/pull/27055 and https://github.com/solana-labs/solana/commit/05f32f287c7.

Namely, the part that is taking a while is replaying slots in blockstore_processor. This new change prints updates on replay progress every 2 seconds.

**Comment by DaveWK** [comment]
Sounds good to me -- I'll keep an eye out for it in the upcoming releases. No need to backport, but happy to get a bit more visibility into potential bottlenecks for self-service investigation in the future. Thanks! I'll close.
