### ISSUE TITLE
Problems with `cargo-build-(bpf|sbf)`

### ISSUE THREAD

**Issue by c410-f3r** [solana-labs/solana#27598]
On `1.11.10` (toolchain and crates), `cargo build-bpf` shows:

```
$ cargo build-bpf
Warning: cargo-build-bpf is deprecated. Please, use cargo-build-sbf
cargo-build-bpf child: $HOME/.local/share/solana/install/active_release/bin/cargo-build-sbf --arch bpf
error: not a directory: '$HOME/.local/share/solana/install/releases/1.11.10/solana-release/bin/sdk/bpf/dependencies/bpf-tools/rust/lib'
```

`cargo build-sbf` and `cargo build-sbf --arch=sbfv2` show:

```
...
...
...
Finished release [optimized] target(s) in 0.92s
$HOME/.local/share/solana/install/releases/1.11.10/solana-release/bin/sdk/bpf/scripts/strip.sh: line 23: $HOME/.local/share/solana/install/releases/1.11.10/solana-release/bin/sdk/bpf/dependencies/bpf-tools/llvm/bin/llvm-objcopy: No such file or directory
```

After a quick inspection, at least for `sbf`, it seems that the correct location should be `$HOME/.local/share/solana/install/releases/1.11.10/solana-release/bin/sdk/bpf/dependencies/sbf-tools/llvm/bin/llvm-objcopy` because  `$HOME/.local/share/solana/install/releases/1.11.10/solana-release/bin/sdk/bpf/dependencies/bpf-tools/` is mostly empty.

**Comment by 4mo4ever** [comment]
Did you solve it? I have same problem.

**Comment by c410-f3r** [comment]
For sbf, locally changing `$HOME/.local/share/solana/install/releases/1.11.10/solana-release/bin/sdk/bpf/scripts/strip.sh` to point to `$HOME/.local/share/solana/install/releases/1.11.10/solana-release/bin/sdk/bpf/dependencies/sbf-tools` made the project compile but is out of my reach to tell if such thing is right or wrong.

**Comment by mateolafalce** [comment]
`sh -c "$(curl -sSfL https://release.solana.com/v1.10.0/install)"`

**Comment by ExoticCoder16** [comment]
> For sbf, locally changing `$HOME/.local/share/solana/install/releases/1.11.10/solana-release/bin/sdk/bpf/scripts/strip.sh` to point to `$HOME/.local/share/solana/install/releases/1.11.10/solana-release/bin/sdk/bpf/dependencies/sbf-tools` made the project compile but is out of my reach to tell if such thing is right or wrong.

sorry can you teach me how to change it ?

**Comment by c410-f3r** [comment]
> > For sbf, locally changing `$HOME/.local/share/solana/install/releases/1.11.10/solana-release/bin/sdk/bpf/scripts/strip.sh` to point to `$HOME/.local/share/solana/install/releases/1.11.10/solana-release/bin/sdk/bpf/dependencies/sbf-tools` made the project compile but is out of my reach to tell if such thing is right or wrong.
> 
> sorry can you teach me how to change it ?

These are files of a unix-like system so any command-line text editor or visual text editor will modify such files. Example:

```
nano $HOME/.local/share/solana/install/releases/1.11.10/solana-release/bin/sdk/bpf/scripts/strip.sh
```

The official Solana team didn't reply this thread but it seems that everything is solved in the latest version. If you guys can confirm, try removing the old installation.

```
rm -rf $HOME/.local/share/solana
rm -rf $HOME/.config/solana
rm -rf $HOME/.cache/solana
```

As well as the old toolchain.

```
rustup toolchain uninstall sbf
rustup toolchain uninstall bpf
```

And then install the new version.

```
solana-install-init 1.14.2
```

**Comment by ExoticCoder16** [comment]
> > > For sbf, locally changing `$HOME/.local/share/solana/install/releases/1.11.10/solana-release/bin/sdk/bpf/scripts/strip.sh` to point to `$HOME/.local/share/solana/install/releases/1.11.10/solana-release/bin/sdk/bpf/dependencies/sbf-tools` made the project compile but is out of my reach to tell if such thing is right or wrong.
> > 
> > 
> > sorry can you teach me how to change it ?
> 
> These are files of a unix-like system so any command-line text editor or visual text editor will modify such files. Example:
> 
> ```
> nano $HOME/.local/share/solana/install/releases/1.11.10/solana-release/bin/sdk/bpf/scripts/strip.sh
> ```
> 
> The official Solana team didn't reply this thread but it seems that everything is solved in the latest version. If you guys can confirm, try removing the old installation.
> 
> ```
> rm -rf $HOME/.local/share/solana
> rm -rf $HOME/.config/solana
> rm -rf $HOME/.cache/solana
> ```
> 
> As well as the old toolchain.
> 
> ```
> rustup toolchain uninstall sbf
> rustup toolchain uninstall bpf
> ```
> 
> And then install the new version.
> 
> ```
> solana-install-init 1.14.2
> ```

Thank you ! I solved the problem by using your "remove" series command lines and re-install the latest version from the official website command line

**Comment by ExoticCoder16** [comment]
> > > For sbf, locally changing `$HOME/.local/share/solana/install/releases/1.11.10/solana-release/bin/sdk/bpf/scripts/strip.sh` to point to `$HOME/.local/share/solana/install/releases/1.11.10/solana-release/bin/sdk/bpf/dependencies/sbf-tools` made the project compile but is out of my reach to tell if such thing is right or wrong.
> > 
> > 
> > sorry can you teach me how to change it ?
> 
> These are files of a unix-like system so any command-line text editor or visual text editor will modify such files. Example:
> 
> ```
> nano $HOME/.local/share/solana/install/releases/1.11.10/solana-release/bin/sdk/bpf/scripts/strip.sh
> ```
> 
> The official Solana team didn't reply this thread but it seems that everything is solved in the latest version. If you guys can confirm, try removing the old installation.
> 
> ```
> rm -rf $HOME/.local/share/solana
> rm -rf $HOME/.config/solana
> rm -rf $HOME/.cache/solana
> ```
> 
> As well as the old toolchain.
> 
> ```
> rustup toolchain uninstall sbf
> rustup toolchain uninstall bpf
> ```
> 
> And then install the new version.
> 
> ```
> solana-install-init 1.14.2
> ```

Thank you ! I solved the problem by using your "remove" series command lines and re-install the latest version from the official website command line
sh -c "$(curl -sSfL https://release.solana.com/v1.14.3/install)"

**Comment by lincot** [comment]
> > > For sbf, locally changing `$HOME/.local/share/solana/install/releases/1.11.10/solana-release/bin/sdk/bpf/scripts/strip.sh` to point to `$HOME/.local/share/solana/install/releases/1.11.10/solana-release/bin/sdk/bpf/dependencies/sbf-tools` made the project compile but is out of my reach to tell if such thing is right or wrong.
> > 
> > 
> > sorry can you teach me how to change it ?
> 
> These are files of a unix-like system so any command-line text editor or visual text editor will modify such files. Example:
> 
> ```
> nano $HOME/.local/share/solana/install/releases/1.11.10/solana-release/bin/sdk/bpf/scripts/strip.sh
> ```
> 
> The official Solana team didn't reply this thread but it seems that everything is solved in the latest version. If you guys can confirm, try removing the old installation.
> 
> ```
> rm -rf $HOME/.local/share/solana
> rm -rf $HOME/.config/solana
> rm -rf $HOME/.cache/solana
> ```
> 
> As well as the old toolchain.
> 
> ```
> rustup toolchain uninstall sbf
> rustup toolchain uninstall bpf
> ```
> 
> And then install the new version.
> 
> ```
> solana-install-init 1.14.2
> ```

removing `$HOME/.cache/solana` fixed this for me

others should be careful when removing `$HOME/.config/solana` because it contains `id.json` keypair

**Comment by jia-ayo** [comment]
i got this error after running cargo-build-sbf
```
$ cargo-build-sbf
info: uninstalling toolchain 'sbf'
info: toolchain 'sbf' uninstalled
   Compiling getrandom v0.1.16
   Compiling rustversion v1.0.9
   Compiling bv v0.11.1
   Compiling memchr v2.5.0
error: target is not supported, for more information see: https://docs.rs/getrandom/#unsupported-targets
   --> src\lib.rs:267:9
    |
267 | /         compile_error!("\
268 | |             target is not supported, for more information see: \
269 | |             https://docs.rs/getrandom/#unsupported-targets\
270 | |         ");
    | |__________^

error[E0433]: failed to resolve: use of undeclared crate or module `imp`
   --> src\lib.rs:291:5
    |
291 |     imp::getrandom_inner(dest)
    |     ^^^ use of undeclared crate or module `imp`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `getrandom` due to 2 previous errors
warning: build failed, waiting for other jobs to finish..
```

**Comment by c410-f3r** [comment]
This `getrandom` error is unrelated. The Solana team didn't reply this thread so you are probably better off asking the responsible people through other channels or opening a new issue.

**Comment by jia-ayo** [comment]
thanks i have done just that

**Comment by drjvtlkr** [comment]
Thanks this worked for me
