### ISSUE TITLE
Update cost model to use requested_cu instead of estimated cu

### ISSUE THREAD

**Issue by taozhu-chicago** [solana-labs/solana#27608]
#### Problem

Transactions' execution CU can be over/under estimated with large margin, potentially result under/over packing blocks. If requested_cu are reliable, it would be a better candidate to use; but it potentially opens for attack. Need to re-evaluate when fee market are adapted.

**Comment by mschneider** [comment]
i'd like to work on this, i do think we could improve ComputeBudget adoption this way. Could you fill me in on the attack vectors?

**Comment by taozhu-chicago** [comment]
Transaction could request max CU (1.4mn CU) and min compute-unit-price (1 micro-lamports) so it only pays 1.4 lamport additional fee. 10 such transaction can saturate an account (account limit is 12mn CU), 40 can saturate a block (block limit is 48mn CUs).

**Comment by taozhu-chicago** [comment]
#23948 uses EMA, attempts to get better estimation. Could be an incremental step

**Comment by nikhayes** [comment]
I think the priority should be a multiplier of base compute per cu fee. I.e. base fee per cu would be 1 micro lamport per cu. A priority of 1x would be 1.4million cu × 1 micro lamport =  1.4 lamports.

**Comment by mschneider** [comment]
yeah agreed, we should update the compute budget increases to be micro lamport per cu, this is already tracked in a separate issue https://github.com/solana-labs/solana/issues/25604

**Comment by taozhu-chicago** [comment]
> I do think milli-lamports are better... a lot of priority is people setting it to 0.000005002 or so per transaction which is basically nothing.

I agree a coarse grained might be better for initial introduction of prioritization fee. But I do see eventually it'd be fine grained to allow better pricing. An alternative is to introduce something like speed-bump in prioritization fee for now - say prioritization fee increments every 1000 micro-lamports, so if one pays 999 micro-lamports, it is prioritized the same as 0 lamports; effectively same as milli-lamports. But this speed-bump can be add/remove without feature gates.

**Comment by mschneider** [comment]
Started working on bypassing the estimator, also would like to get rid of it. (see draft PR https://github.com/solana-labs/solana/pull/28281)

Compute budget for mango crank is not trivial. we are currently running 2 cranks:
a) 50k CU budget with high frequency and high priority fee
b) high (1M?, not sure) CU budget with low frequency and minimal priority fee

For serum taker orders we know that a large limit order that matches with 20+ orders on top of the book can easily run into the 200kCU limit. It's very difficult to restrict compute budget for those.

The estimator is really good for this kind of workload, i imagine that a hybrid solution estimator + override through compute budget instruction would be a clear improvement. In addition we could try estimator based on a compound key: program id and first byte (instruction) to get a better performance profile.

**Comment by nikhayes** [comment]
> Transaction could request max CU (1.4mn CU) and min compute-unit-price (1 micro-lamports) so it only pays 1.4 lamport additional fee. 10 such transaction can saturate an account (account limit is 12mn CU), 40 can saturate a block (block limit is 48mn CUs).
> 
> I'd like t o see what compute-unit-fee would be in real life, maybe we can raise min from 1 micro-lamport to something larger to disincentivize such transactions.

I'm curious about this still.... a higher base fee per cu seems reasonable especially since within-slot latency will still matter quite a bit even with the priority system in place I imagine. You wouldnt want massive low cost transactions landing first and starving out space for other things for too cheap.

**Comment by mschneider** [comment]
Thank you for the comments, it makes it way more clear to me, how big of a change it would be to remove these data structures.

I think the transaction cost vs compute units confusion is a reflection of the state of the code. CostModel::calculate_cost and ComputeBudget::process_instructions simply have different approaches. I'll try to write down a full proposal of how a solution could look like, will probably start implementation from scratch afterwards.

Things to agree on:
1) Remove / Keep / Improve ExecuteCostTable 
2) ComputeBudget instruction limits gross transaction cost or just net execution cost

**Comment by aeyakovenko** [comment]
Remove the estimator!  Everything should run correctly from the requested cu's.

**Comment by taozhu-chicago** [comment]
this sounds like a big change, seems to include at least few tasks:
1. changes to ComputeBudget instructions, 
2. somewhat how fee model works (a side note, "FeeModel" is a term currently used to refer using Prioritization Fee to compete for resources)
3. "make fees dependent on all costs not only on compute units" (not sure if this is well thought of)
4. the least - simple remove BPF instruction cost estimation, replace with compute_budget.compute-unit-limit.

Perhaps we can start with #4 only, it pretty much is self-contained and its result can be directly measured. Just a thought.

**Comment by overclock-validator** [comment]
Will this include charging for the amount of cu requested? i.e. request 1 million cu and pay for the 1 million cu according to some base fee per cu cost? Right now larger cu transactions pay the same as very small cu transactions -- it just takes more $ to prioritize them, but given that it's still not that clear whether or not priority is helping on mainnetbeta yet I think it makes sense that larger transactions should pay a higher base cost? Eventually we may have bankless leaders and in that system there will need to be incentive for users to very accurately estimate the compute they'll request given that leaders will need to base their block size estimates completely from requested compute?

**Comment by taozhu-chicago** [comment]
Good point. Requesting more CUs does increase transaction fee rn, perhaps just not significant enough. 

Transaction_fee = signature_fee + write_lock_fee + prioritization_fee + compute_fee. (https://metrics.solana.com:8889/sources/5/dashboards/82?refresh=Paused&lower=now%28%29%20-%2015m), where prioritization_fee = compute_unit_limit * compute_unit_price. (eg. requested CU * priority rate). Since the priority rate is pretty small atm, the overall prioritization fee must be insignificant compare to signature fee, nonetheless, it's baked in.

Once fee_structure is agreed upon, different costs are assigned to CU bins, expensive transactions will pay fees more accurately reflect costs.

**Comment by overclock-validator** [comment]
Thanks for the input.

Unfortunately I can't see those grafana metrics :/ Perhaps that and the compute related metrics would be really nice to see on the public grafana dashboard. There was the issue of oracle transactions going stale last week and I think people might have noticed earlier had we seen that account/block compute limits were close to saturation.

**Comment by taozhu-chicago** [comment]
Right, an issue https://github.com/solana-labs/solana/issues/26818 is in the queue to make a public dashboard for these metrics.

**Comment by taozhu-chicago** [comment]
#28281 merged to master
