### ISSUE TITLE
Add support to RPC API for querying the size of a specific secondary index key.

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#27661]
#### Problem

Secondary account indexes can become quite large for certain keys which have many associated accounts in the system and thus require many GB of ram to store and can cause the validator to OOM. When the RPC call is made to the validator it also will just spin in a core and allocate memory and the resulting request will be too large to transmit over a single RPC request requiring many seconds and hitting connection timeouts. So often even indexing these keys is not useful at least with the current apis.

#### Proposed Solution

- [ ] Add support to RPC API for querying the size of a specific secondary index key.

Separate Issues will address the larger Secondary Index problems:
(1) Add support to RPC API for querying the size of a specific secondary index key. - #28666
(2) Add pagination support for getTokenAccountsByOwner/getProgramAccounts/etc such that a large set could be queried with multiple calls. This would fix the request size but it wouldn't fix the RAM problem. - #28667
(3) Page-out infrequently-used secondary indexes to disk using the mmap primitives we use for the accounts index. - #28668
(4) Implement getProgramAccounts over a geyser-produced SQL or kafka and remove secondary indexes altogether

Long term we would like to go to solution (4) and remove the secondary indexes altogether, but I think a decent short-term solution could be (1) while we work on (4). For (2) I think we'll need a paginated API whether we remove the secondary indexes or not. It's just a question if we implement it also with the current validator or go straight to implementing it over the SQL or kafka database.

**Comment by IntokuSatori** [comment]
Addressed in: https://github.com/solana-labs/solana/pull/28383
