### ISSUE TITLE
Merging the active fork into root uses a simple BankDelta count instead of voted forks for rollback distance

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#2767]
#### Problem

Active forks in (#2689) are merged on simple BankDelta distance instead of actual voted blocks.

#### Proposed Solution

Add a bit to BankDelta which indicates if it has an active vote or not.  As votes expire and unroll, the replay stage can clear the bit.  When root is merged, it should count the number of active votes to decide if root should be merged or not.

When a BankDelta crosses the epoch boundary regardless of the vote bit set, that BankDelta is used to calculate the leader schedule.

tag: @garious @rob-solana

**Comment by mvines** [comment]
This issue is likely stale, @aeyakovenko  do you agree?

**Comment by aeyakovenko** [comment]
Stale, leader schedule has a stable calculation.
