### ISSUE TITLE
Bump `jayson` to version `4.0.0` in `/web3.js`

### ISSUE THREAD

**Issue by ndrewtl** [solana-labs/solana#27679]
#### Problem

The `jayson` library brings with it a dependency on `lodash`, which adds a significant size to any bundle including `@solana/web3.js`. 

#### Proposed Solution

This has been changed in `jayson` `v4.0.0`. Therefore, if we bump our `jayson` version to `v4.0.0`, the bundle size of any application using `@solana/web3.js` will decrease significantly.

**Comment by steveluscher** [comment]
So, here's the thing. The only place that we import `jayson` is here:

```
import RpcClient from 'jayson/lib/client/browser';
```

…and even in the _current_ version of `jayson`, the `lib/client/browser/` code does not use `lodash`.

Check out the [bundlephobia](https://bundlephobia.com/package/@solana/web3.js) report. You can see that lodash never gets pulled in. Updating to v4 won't actually change the size of `@solana/web3.js` at all.

Super glad that you're pitching in to reduce `web3.js` bundle size though; thanks!
