### ISSUE TITLE
Starting from 1.53.0 web3.js breaks compatibility with React Native

### ISSUE THREAD

**Issue by lexer** [solana-labs/solana#27685]
#### Problem

Starting from 1.53.0 web3.js breaks compatibility with React Native

I suspect some changes that uses BigInt might have caused this. BigInt is not supported in React Native. 

Error log:

```
SyntaxError: 256428:32:BigInt literal is not supported, js engine: hermes
```

**Comment by paulmillr** [comment]
> BigInt is not supported in React Native

it is supported in react native 0.70, you need to upgrade

**Comment by steveluscher** [comment]
You're absolutely correct! You can read all about the new requirements going forward, here:

* [Cookbook](https://solanacookbook.com/integrations/react-native.html#how-to-use-solana-web3-js-in-a-react-native-app)
* [Updated RN scaffold](https://github.com/solana-developers/dapp-scaffold-react-native/commit/ae79970bb5e172a87916aee7d792cf37b6a1bb3b)
* [Tweet](https://twitter.com/steveluscher/status/1565232091260157952)

**Comment by steveluscher** [comment]
Added some notes to the web3.js `README` about this.

**Comment by lexer** [comment]
@steveluscher After upgrading to React Native 0.70 I'm getting a new error
```
TypeError: Cannot convert BigInt to number, js engine: hermes
```

**Comment by lexer** [comment]
I think I made it work. 

Needed this change in babel.config.js:
```
module.exports = {
  presets: [
    [
      'module:metro-react-native-babel-preset',
      {unstable_transformProfile: 'hermes-stable'},
    ],
  ],
};
```

**Comment by steveluscher** [comment]
Yep! It’s all in the Cookbook. Make sure to read the whole thing, there might be more things to configure!
