### ISSUE TITLE
Staker can get duplicate rewards for the same credits

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#2775]
#### Problem

Since the entrypoint takes an instruction, not a transaction, there's no atomic check, and an attacker could redeem credits multiple times without clearing credits after each.

#### Proposed solution 1

Add another entrypoint to programs that passes in all instructions and the instruction index. The Rewards program can then validate VoteInstruction::ClearCredits is the following instruction.

#### Proposed solution 2

Come up with a way linking the VoteAccount and RewardAccount such that no atomic transaction is needed. @aeyakovenko proposes this:

```rust
/// sets the reward program account
/// can only be set once
VoteInstruction::AssosciateRewardAccount

/// votes, increases the vote_counter if the vote is accepted
VoteInstruction::Vote


/// sets the associated vote program account
/// can only be set once
RewardInstruction::AssociateVoteAccount

/// Claim the reward if the vote_account is associated with this reward account
/// pays out a reward only if the `VoteInstruction::vote_counter` is newer than the last stored value
/// copies the VoteInstruction::vote_counter in self
RewardInstruction::Claim(&mut self, vote_account: &Account)
```

**Comment by rob-solana** [comment]
obsoleted by passive staking?
