### ISSUE TITLE
Voting Rewards algorithm different than what's described in the book

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#2776]
#### Problem

The voting Rewards algorithm is dead-simple; it rewards a percentage of the stake for each voting credit. It doesn't implement the proposed rewards algorithm from the book which depends on more data.

#### Proposed Solution

https://solana-labs.github.io/book-edge/staking-rewards.html

**Comment by rob-solana** [comment]
this should probably be changed to a book update @ericlwilliams 

the stages of staking, covered by the stake program instructions are:
1. **_create_**: but usually combined with delegation
2. **_delegate_**: exposes some portion of the stake accounts lamports for rewards generation.  Stake is not immediately exposed, rather it "warms up" over some number of epochs.  the stake program limits total stake warmup to some percentage (default is 15%/epoch) of the previous epoch's total effective stake.  Lamports in the stake account covered by any activating stake are  unavailable for withdrawal.  Lamports staked are exposed to slashing.
3. **_redeemvotecredits_** : as vote credits accrue in the delegate's vote account, rewards redemption is run against stake accounts.  vote credits are recorded on a per-epoch basis, so as a stake warms up, the correct number of rewards per epoch can be calculated
4. **_deactivate_** : this marks the stake account as "cooling down".  as a stake account cools down, more and more lamports are available for withdrawal and become immune to slashing.
5. **withdraw**: can be run at any time to get lamports in excess of activated stake, e.g. rewards.  we do not yet support automatic re-investment of rewards.

**Comment by garious** [comment]
Obsolete
