### ISSUE TITLE
Voting Rewards algorithm assumes stake is static

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#2777]
#### Problem

The Rewards algorithm uses the latest stake to calculate rewards instead of the state at the time of the vote it is being rewarded for.

#### Proposed Solution

Reference the staking account at the time of voting so that its value can be cached in the Vote program and utilized by the Rewards program.

**Comment by rob-solana** [comment]
this was fixed a while back.  vote accounts keep track of credits per epoch, and redemption code calculates stake from epoch
