### ISSUE TITLE
Rewards program isn't available to testnet users

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#2778]
#### Problem

The Rewards program isn't added the ledger and therefore can't be used by testnet users.

#### Proposed Solution 1

Keep the monolith going and and the Rewards program to the Bank builtins.

#### Proposed Solution 2

Add the list of builtins to the genesis block

#### Proposed Solution 3 (Greg's favorite)

Add a mechanism for adding entries just after the genesis block and add it as a user would any other on-chain program - with a transaction.

**Comment by rob-solana** [comment]
fixed a while back with stake_api::genesis()
