### ISSUE TITLE
SlotMeta is_connected field isn't updated as expected

### ISSUE THREAD

**Issue by steviez** [solana-labs/solana#27820]
#### Problem

The `SlotMeta::is_connected` field was originally designed to indicate whether a given slot `n` had a full replayable sequence back to genesis without any holes. It follows that all slots in this sequence must be full in order to be replayable. In a more compact form, we're saying
```rust
is_connected(n) = is_connected(parent_of_n) && is_full(n)
```
where `n` is the direct child of `parent_of_n`.

What this design failed to account for is that validators might start from a snapshot at some slot `s` > 0. This is a perfectly valid way for a validator to bootstrap (recall that by definition, `s` is a root); however, that validator doesn't / didn't have a path back to genesis. As such, `is_connected` will be false for all slots that this validator processes. This has a potential ripple effect as the `is_connected` field is currently being used to signal to `ReplayStage` when there is more work to do. See https://github.com/solana-labs/solana/pull/27786, which is what sparked the dig into this issue.

#### Proposed Solution
From some discussion, an initial idea is to expand `is_connected` to link back to geneiss OR to a slot that we load snapshot from.
- Starting completely clean (no snapshot or blockstore) seems like it'd be easy enough; mark snapshot slot as connected (although we wouldn't technically have these shreds) and then as additional slots are inserted, they'll be able to get marked as is_connected inductively as well
- Starting with a fetched snapshot but existing blockstore would require a little extra. For example, suppose the blockstore has slots in the range `[b_start, b_end]` and we fetch a snapshot at slot `s`:
    - Fetching a snapshot for `s > b_end` has no issues; `s` marked as connected and progresses onward (so functionally similar to starting without any blockstore)
    - Fetching a snapshot for `b_start < s < b_end` would mark `s` as connected, but if slots `(s, b_end]` are already present in blockstore, their connected status wouldn't change.
        - Maybe we could update `blockstore_process::load_frozen_forks()` to mark these slots as connected ?
    - Fetching a snapshot for `s < b_start` would be similar to above case; mark `s` connected and then potentially need to update slots as connected in `load_frozen_forks()`

Technically, when we fetch a snapshot at slot `s`, we don't actually need `s` in the blockstore as the bank unpacked from the snapshot is frozen after playing `s`. There might be some subtlety with getting this correct 

#### Additional Context / Reading
The original design doc for [blockstore](https://docs.solana.com/validator/blockstore#blockstore-design) is here, and below is the `SlotMeta` struct in code.

https://github.com/solana-labs/solana/blob/1a4b8b5b79a91398dea83ae7f8d1a529e1a2174d/ledger/src/blockstore_meta.rs#L16-L45

**Comment by steviez** [comment]
Quick thought that needs more examination would be to change `is_connected` field to be `is_parent_connected`. `is_connected` currently contains duplicate information as we can determine from other fields whether we are full or not (see how `SlotMeta::is_full()` is implemented). This bit of information is useful for knowing if there is work to be done in the issue I linked above; however, there might be other consequences of making the change.

Ultimately, it'd be nice to not have to change the struct layout of `SlotMeta` as that raises all sorts of compatibility issues

**Comment by steviez** [comment]
In regards to my previous comment, I think we need two bits of state:
- `is_connected`
- `is_parent_connected`

My defense for that is that when we start from a snapshot at slot `S`, we may not necessarily have the shreds for slot `S`. So, depending on `is_full() && is_parent_connected` to tell us whether a slot is connected won't work. And, the whole reason for this discussion is that `is_connected` doesn't capture the subtlety that work can be done before a slot is completed.

We can capture both of these bits in the same amount of space that the boolean previously occupied; however, this is a compatibility issue regardless as trying to decode a byte that is not one of `{0, 1}` is a deserialization error.

**Comment by steviez** [comment]
For completeness, another option that would avoid modifying `SlotMeta` would be querying the blockstore for the parent SlotMeta in `Blockstore::slot_has_updates()` and in `Blockstore::handle_chaining_for_slot()` as these are both instances where we need to know if the parent is connected so that we can potentially mark a child as connected

**Comment by t-nelson** [comment]
regarding avoiding the struct layout change avoidance, the existing field is a `bool` which encodes to a `u8` where `false` is strictly `0x00u8` and `true` `0x01u8`, so we have some free bits to play with.

* treat it as an `#[repr(u8)]` enum, and reserve variants `0` and `1` as legacy values
* treat it as a `bitflags!{struct Flags: u8 { ... }}` from the [`bitflags` crate](https://docs.rs/bitflags/latest/bitflags/), where the LSB is legacy
