### ISSUE TITLE
Geyser plugin: slots streaming starts late

### ISSUE THREAD

**Issue by bmuddha** [solana-labs/solana#27842]
#### Problem
Slots streaming starts later than accounts, if validator started with old snapshot. Here's what happens step by step:
1. After fresh validator start, it usually downloads snapshot in order to reconstruct AccountsDB. 
2. All the accounts from snapshot are streamed to plugin. 
3. After snapshot upload is complete, there's short break in plugin activity (roughly 10 minutes). 
4. Then activity is resumed, and if snapshot was fresh enough the first account received by `GeyserPlugin::update_account` after pause has slot number newer or equal to that of the first slot received by `GeyserPlugin::update_slot_status`
5. But if snapshot was old, then after the pause, account updates generation start earlier than that of slots, which leads to the following problem: there's no way to find out the status of the account updates which occurred during the time frame, when no slots were sent to plugin, because the plugin never received any of these slots and their statuses via `GeyserPlugin::update_slot_status`. 

Usually it's pretty easy to figure out the status of particular account update if you know the status of its slot. The plugin under normal circumstances receives those status updates for all slots, at which account updates occurred, and the problem only happens when using old snapshot. 

It's hard to define what _old snapshot_ means, we have tested with snapshot, after which validator starts with only ~2000 slot lag, and no such issue was observed, but if it starts with 10K slot lag or more, then there's always a delay between resumption of accounts generation and that of the slots. 

It's also hard to guarantee that validator will always start with the most fresh snapshot, so the issue when some of the account updates will have unknown status might arise.  

It seems that the culprit here is the validator itself, and not Geyser plugin manager, but I'm not sure. 

**Solana validator version**: 1.10.38
**Geyser plugin version**: 1.10.38

**Comment by bobs4462** [comment]
Can we assume, that account updates, received by plugin during this interval (after snapshot upload and when no slots are being received yet), are finalized, i.e. the slots when those updates occurred have rooted status?
