### ISSUE TITLE
`test-bpf` and `build-bpf` does not support dependency inheritance (cargo 1.64)

### ISSUE THREAD

**Issue by totikom** [solana-labs/solana#28059]
#### Problem
As stated in the title: this tools use previous version of `cargo` (1.59) and does not support [Dependency inheritance](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html#inheriting-a-dependency-from-a-workspace)

#### Proposed Solution
Update `cargo` in the stable channel of solana tool suite.

**Comment by dmakarov** [comment]
SBF tools use the version of cargo matching the rust toolchain the tools are based on. When we upgrade the rust toolchain to 1.64 the tools will be upgraded to cargo 1.64 too.
