### ISSUE TITLE
getHealth causes: solana_rpc::rpc_health health check: latest_known_validator_account_hash_slot not available

### ISSUE THREAD

**Issue by DaveWK** [solana-labs/solana#28061]
#### Problem

These validators were previously working on Devnet and Testnet on v1.10.38. I have another testnet node with the same hardware configuration which does not have this issue and works normally.

I am seeing this issue in both on v1.10.39 and v1.14.2.

After I upgraded and restarted, the node goes through it's normal startup process, and successfully passes the Port check. 

After the node got back into sync, I noticed it did not report the "Slots Behind" in the health check and just returns the generic: 
```
  "error": {
    "code": -32005,
    "message": "Node is unhealthy",
    "data": {
      "numSlotsBehind": null
    }
```

I noticed that it does seem based on the block height to be keeping up with the network.

In the logs I see:
```
[2022-09-25T15:20:21.983251125Z INFO  solana_rpc::rpc_service] health check: unknown
[2022-09-25T15:20:22.764818523Z WARN  solana_rpc::rpc_health] health check: latest_known_validator_account_hash_slot not available
```
whenever it calls the getHealth rpc.

I assumed this might be an issue with the ledger getting corrupted after a restart, so I deleted the ledger folder to try and resync the chain.

When I restarted at that point, the validator is unable to retrieve snapshots. I noticed in the logs at this point that none of the validators that show up in the RPC list before have a filled in "version" column in the table that gets printed. After it loops for a while (I let this go for a few hours just in case) it then gives up.

At this point I assumed it might be something to do with the entrypoint/bootstrap, so I stopped the node and did a wget for the latest snapshot/incremental snapshots from the node. I then was able to start the validator, re-index, and the block height progresses, suggesting it is caught up to the network.

It then gives me the same error; `latest_known_validator_account_hash_slot not available` and tells me the node is unhealthy in the RPC.

Another interesting note is that when I run `solana gossip` and get the list of nodes back, the nodes all have their version filled in correctly, and returns the table very quickly. The validator logs never seem to return a version number whenever it prints out the table.

#### Proposed Solution

Besides bisecting and figure out which commit/feature has caused the problem, and either fix it or revert it, I think there's a few things which would be helpful.

- If this turns out to be a network connectivity issue, I would have expected the port check on start to have caught this issue. If this is the case, please adjust the check accordingly.

- It is strange that the `solana gossip` call returns so much faster with all the versions of validators than the table being printed in the logs. Is there some better logic on the `gossip` call than `solana-validator` is using in it's process that would make the results return faster with more information?

- I didn't see any WARN level log entries besides that latest_known_validator_account_hash_slot message. If there is a reserved/blocked port or response that does not return, it would be nice if there was another WARN log message to indicate what port it was blocked from using.

**Comment by DaveWK** [comment]
Solved.
The issue was that the time on 2 of the servers was in the future by 1 minute.  After setting the correct time, the healthcheck and version info shows up in the list.

It seems like there should be some kind of startup check or health check when the server clock is too far off from the cluster?

**Comment by manuelmanx** [comment]
I get the same issue right now, how to fix it?

**Comment by DaveWK** [comment]
> Solved. The issue was that the time on 2 of the servers was in the future by 1 minute. After setting the correct time, the healthcheck and version info shows up in the list.
> 
> It seems like there should be some kind of startup check or health check when the server clock is too far off from the cluster?

^^ As stated in my last reply, my system clock had drifted about 1 minute into the future. make sure chrony is configured properly, and restart the chronyd service to see if it makes an adjustment.
