### ISSUE TITLE
Committed votes rate drops when block space is contended

### ISSUE THREAD

**Issue by taozhu-chicago** [solana-labs/solana#28092]
#### Problem

Votes and non-vote transactions race for block space, when expensive transactions took up block space, less votes were able to commit to blocks. This became more pronounced when non-vote threads increased.

For example, during a bunch of expensive transactions filled up block at 05:52, the tpu vote committed rate dropped significantly: 
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/82401714/192386113-431837f9-1911-45d6-a13d-5506495c400c.png">

#### Proposed Solution
Few options top of my mind, still looking for better ones.

1. increase vote threads in proportion to non-vote threads. Eg, if there are 4 non-vote threads, can match that with 2 gossip votes, 2 tpu votes. In that line, try to enforce threads pinning.
2. currently there is max block space (75%) votes can take, maybe reserve a min space for votes as well? Maybe can do this dynamically to reserve block space for x% of queued votes.
3. Set all votes to high than average priority, say the max priority for current block is X, then all votes in queue will have X * 75% priority. This requires to add one priority queue in front of block. (maybe more a `scheduler` thing)

**Comment by taozhu-chicago** [comment]
@AshwinSekar @carllin

**Comment by buffalu** [comment]
what UTC time was this?

**Comment by taozhu-chicago** [comment]
> what UTC time was this?

2022-09-21 04:30 - 07:30 (at top-right corner of screenshot)

**Comment by AshwinSekar** [comment]
I like the second solution, we could reserve a minimum space for votes based on how big the queues are. I think with the split change we will be closer to having at most 1 vote per validator per block so it should be possible to dynamically decide this minimum for each block.

**Comment by taozhu-chicago** [comment]
tag @overclock-validator.

**Comment by overclock-validator** [comment]
I think the number of votes are going down due to non vote cu's going up quite a lot the past few days.

![Screenshot_20230103_213429_Chrome](https://user-images.githubusercontent.com/116830051/210490106-bb40fc96-6f8a-4c5c-a621-69b156bd18ab.jpg)

@apfitzge posted this increase in block sizes earlier. I also saw nearly 70% of blocks full during stretches earlier today.
![blocksizes](https://user-images.githubusercontent.com/116830051/210490594-6c99e9a1-a95d-4bf3-961c-bdabc9e69178.png)
