### ISSUE TITLE
web3.js: Connection not passing custom headers to the Websocket client

### ISSUE THREAD

**Issue by alebusse** [solana-labs/solana#28112]
#### Problem
Im currently using an RPC node that uses an Authorization header, but im unable to connect through WS since the headers are missing on the Websocket client.
The custom headers on a new Connection() are not being passed to the Websocket client

https://github.com/solana-labs/solana-web3.js/blob/master/src/connection.ts#L2711-L2714

#### Proposed Solution
Adding it like this may fix the issue

```
this._rpcWebSocket = new RpcWebSocketClient(this._rpcWsEndpoint, {
      autoconnect: false,
      max_reconnects: Infinity,
      headers: httpHeaders
    });
```

**Comment by steveluscher** [comment]
Hey there! This comes up every now and again; read this prior discussion for more! https://github.com/solana-labs/solana/pull/24833#issuecomment-1165657477

**Comment by alebusse** [comment]
@steveluscher thanks for the info, i tried searching for a similar problem in the prs and issues, but didnt find it, im gonna try implementing a route-like auth in the url.
