### ISSUE TITLE
[Explorer] Showing wrong token change in UI

### ISSUE THREAD

**Issue by Tolsee** [solana-labs/solana#28130]
#### Problem

https://explorer.solana.com/tx/5u4b6VSPkcLdrnznbyPvgnmXgHg3RGGWKrHKNufekAWutPZz5tZVJHXAeyp9E4qfkEop6CGk7i24jneMcN528auo

For this, we can see from `preTokenBalances` and `postTokenBalances` that the owner of that NFT was changed. 

https://explorer.solana.com/tx/3HRBhnuU27VLVjM2sqJmVTDDMjXY3ur123XdMh7KeKzrKHZhv5tUfdfY9rZGJm1GH8K2BCveoMWPKAYY5SyNM8wX
For this we see that we have `preTokenBalances` but empty `postTokenBalances`. 

For both of these scenarios, we should have shown changes in token balances.

**Comment by jstarry** [comment]
> For this, we can see from preTokenBalances and postTokenBalances that the owner of that NFT was changed.

Please create a new issue for displaying ownership changes of tokens. It's not supported yet.

>  For this we see that we have preTokenBalances but empty postTokenBalances.

Good point, this should be fixed
