### ISSUE TITLE
Streamer cannot compile using musl

### ISSUE THREAD

**Issue by motoras** [solana-labs/solana#28156]
#### Problem
Hi guys,
I was trying to compile solana with musl as target and I got the following error:
```
 --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/solana-streamer-1.14.3/src/recvmmsg.rs:103:70
    |
103 |         unsafe { libc::recvmmsg(sock_fd, &mut hdrs[0], count as u32, MSG_WAITFORONE, &mut ts) };
    |                  --------------                                      ^^^^^^^^^^^^^^ expected `u32`, found `i32`
    |                  |
    |                  arguments to this function are incorrect
    |
note: function defined here
   --> /home/user/.cargo/registry/src/github.com-1ecc6299db9ec823/libc-0.2.134/src/unix/linux_like/linux/musl/mod.rs:702:12
    |
702 |     pub fn recvmmsg(
    |            ^^^^^^^^
help: you can convert an `i32` to a `u32` and panic if the converted value doesn't fit
    |
103 |         unsafe { libc::recvmmsg(sock_fd, &mut hdrs[0], count as u32, MSG_WAITFORONE.try_into().unwrap(), &mut ts) };
    |                                                                                    ++++++++++++++++++++
```
I used the cargo command ```cargo build --release --target x86_64-unknown-linux-musl``` with rust ```rustc 1.63.0 (4b91a6ea7 2022-08-08)``` I needed to compile for musl, as I was planing to use solana from an aws lambda function written in rust(aws rust runtime requires to compile your rust function with musl).

**Comment by 1saf** [comment]
Did you manage to solve this? Having the same problem

**Comment by motoras** [comment]
> 

No. I just avoided using musl, by using  a more recent cargo lambda and compiling for arm.

**Comment by 1saf** [comment]
@steveluscher would it be possible to support MUSL rust by implementing the change to use .into() ?

**Comment by steveluscher** [comment]
I don't know, but feel free to open an issue here, phrased as a feature request!

**Comment by billythedummy** [comment]
think this is a rust libc issue: https://github.com/rust-lang/libc/issues/2945 . Given [their breaking change policy](https://github.com/rust-lang/libc/blob/master/CONTRIBUTING.md#breaking-change-policy) it'll probably take a while before the new versions of libc are release with this fixed. `.try_into().unwrap()` would probably work as a temporary workaround before then but idk if we should introduce this potential tech debt
