### ISSUE TITLE
It takes too long for DataBudget limit to ramp up

### ISSUE THREAD

**Issue by HaoranYi** [solana-labs/solana#28158]
#### Problem

![image](https://user-images.githubusercontent.com/219428/193318876-2797efa3-b442-4639-8372-b75af27c6bea.png)

This figure shows that gossip pull response is limited by the DataBudget at startup. When starting, DataBudget is initialized to 0. It takes a long time for the limit to ramp up to meet the bandwidth of response traffic.

This problem also affects repairs service response and bank forwarding packets at the start.

#### Proposed Solution

Support non-zero initial value for DataBudget and pick appropriate intial value for starting.

**Comment by t-nelson** [comment]
can you add details?  kinda hard to grok a screenshot with all of the labels cropped out

**Comment by HaoranYi** [comment]
> can you add details? kinda hard to grok a screenshot with all of the labels cropped out

![image](https://user-images.githubusercontent.com/219428/193318876-2797efa3-b442-4639-8372-b75af27c6bea.png)

```
SELECT mean("output_filter_size") AS "mean_output_filter_size", mean("output_filter_overshoot") AS "mean_output_filter_overshoot" FROM "tds"."autogen"."cluster_info_stats2" WHERE time > '2022-09-30 09:20:00' AND time <= '2022-09-30 09:50:00'  AND "host_id"='FS8AEVgZsicd7ktXkcAdYyhhsCtMdVUpcfyH9F7DX7MZ' GROUP BY time(60s) FILL(null) tz('America/Chicago')
```

**Comment by HaoranYi** [comment]
red herring. data budget should be ramping up very quickly and would not be the limiting factor.
