### ISSUE TITLE
cargo build-bpf failed on M1 macbook

### ISSUE THREAD

**Issue by basharsalleh** [solana-labs/solana#28175]
> cargo build-bpf 

`   Compiling crossbeam-epoch v0.9.11
error: target is not supported, for more information see: https://docs.rs/getrandom/#unsupported-targets
   --> /Users/basharsaleh/.cargo/registry/src/github.com-1ecc6299db9ec823/getrandom-0.2.7/src/lib.rs:240:9
    |
240 | /         compile_error!("target is not supported, for more information see: \
241 | |                         https://docs.rs/getrandom/#unsupported-targets");
    | |_________________________________________________________________________^`
    
    
[dependencies]
solana-program = "1.9.9"

[dev-dependencies]
solana-program-test = "1.9.9"
solana-sdk = "1.9.9"

[lib]
crate-type = ["cdylib", "lib"]    
   
   
 **Any solution for it ?**

**Comment by jamesnaftel** [comment]
@basharsalleh I believe I saw the same issue.  I solved it by installing (with brew in my case) coreutils.
