### ISSUE TITLE
web3.js Roadmap – October 2022 – Discussion thread

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana#28180]
What do you want to see accomplished in `@solana/web3.js` in the month of October 2022?

Milestone: https://github.com/solana-labs/solana/milestone/201

**Comment by mschneider** [comment]
I was recently chatting with justin who mentioned, it would be a good idea to merge Mango's transaction retry routines into web3. One particular issue with merging them is, that we use an abstraction to make our library functions work transparently with solana/wallet-adapter as well as regular keypais:

```
export type WalletSigner = Pick<
  SignerWalletAdapter,
  "publicKey" | "signTransaction" | "signAllTransactions"
>;
```

One one hand it would be great if more users could benefit from our tx submission code. On the other I'm not sure it's a good idea to introduce this one into web3. What's your take on this? Should we make a new package?

**Comment by steveluscher** [comment]
Hey @mschneider! There's so much work I want to do on that code. Would implementing #25955 essentially bring us in line with Mango's implementation?

**Comment by mschneider** [comment]
confirmation is one part of the problem
retrying submission is also an issue

**Comment by mschneider** [comment]
So no I don’t think solving that issue is enough. We have some time to port some of this logic over, make prs and so on. Just waiting for your guidance if to make everything part of web3 or rather spin up a separate package

**Comment by mschneider** [comment]
it looks to me like the solana web3js could use 3 upgrades:

1) confirm transaction patches so it's as good as ours https://github.com/blockworks-foundation/mango-client-v3/blob/d34d248a3c9a97d51d977139f61cd982278b7f01/src/client.ts#L546

2) a combined send and confirm transaction method, similar to this one: https://github.com/blockworks-foundation/mango-client-v3/blob/d34d248a3c9a97d51d977139f61cd982278b7f01/src/client.ts#L444 

the current mango code is not configurable enough for solana, so well make everything very easy to configure for both methods: confirmation level, preflight skipping, resend timer, blockhash vs time expiry 

3) batch send and sign, this one allows to send large batches of transactions in parallel or small batches in sequence, we have been using this in realms and another unreleased project

**Comment by steveluscher** [comment]
I'll parcel these out in to issues so they don't get lost, @mschneider. Thanks for the contributions!

**Comment by archseer** [comment]
Can you link to these follow-up issues?

**Comment by steveluscher** [comment]
Batching: #28785
Confirmation improvements: #25955

Regarding a combined send and confirm function, we [have one](https://github.com/solana-labs/solana/blob/master/web3.js/src/utils/send-and-confirm-transaction.ts), and it _should_ inherit the confirmation improvements from #25955.
