### ISSUE TITLE
Missing metrics for dupe slots

### ISSUE THREAD

**Issue by joeaba** [solana-labs/solana#28210]
#### Problem
We don't have a way to easily monitor for dupe slots

#### Proposed Solution
Add a metric here:
https://github.com/solana-labs/solana/blob/adc4e633a/core/src/window_service.rs#L142-L153
or here:
https://github.com/solana-labs/solana/blob/adc4e633a/core/src/replay_stage.rs#L1462

**Comment by joeaba** [comment]
@yihau @pieceofr have you guys added metrics yet?

**Comment by yihau** [comment]
just found this. is it the same thing? https://github.com/solana-labs/solana/pull/28176

**Comment by joeaba** [comment]
lol yes, closing this
