### ISSUE TITLE
explorer: display of reaped accounts frequently confuses users

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#28273]
#### Problem

Accounts that have a transaction history, but have since been closed and reaped by the runtime are displayed with a zero-lamport balance, which users mistakenly interpret as presently existing on chain

![Screenshot from 2022-10-06 11-56-24](https://user-images.githubusercontent.com/490004/194386286-742c8240-e8a2-4a31-b4d9-b61b05c02889.png)

#### Proposed Solution

* remove the lamports balance
* add a message along the lines of "account no long exists on chain"

**Comment by jstarry** [comment]
Why is it an issue that users think an empty account with no SOL exists on chain? I recently expanded the fields of empty accounts to also say that there is no allocated data and the owner is the system program, does that help or make this worse?

https://explorer.solana.com/address/AVpktMrf8bHHDfQrh8XMtEwUnfB2YxnM7Rw1dyNspRCV
<img width="754" alt="Screen Shot 2022-10-17 at 10 01 59 AM" src="https://user-images.githubusercontent.com/1076145/196073499-b9004056-9901-4597-96d9-008ccd7a3c1a.png">

**Comment by yahya-cloud** [comment]
Is  zero-lamport  balance enough to identify that account no longer exists on chain?

**Comment by ngundotra** [comment]
@yahya-cloud can you PR your change to fix this issue when you get a chance <3

**Comment by yahya-cloud** [comment]
hello @ngundotra, is the changes in pr fine or something else is also required ?

**Comment by ngundotra** [comment]
@yahya-cloud Yes!!! Thank you

**Comment by ngundotra** [comment]
Reopened based on feedback from @mvines to rename this to say "Account does not exist"
