### ISSUE TITLE
explorer: Anchor method arguments display is not complete for enum

### ISSUE THREAD

**Issue by Arrowana** [solana-labs/solana#28306]
#### Problem

Example tx https://explorer.solana.com/tx/48Bke4VRYoKc6tsZpZTesB5NdZvrMiQXBSjHFXVMDmFxN22mLkkrXFG1QMDT47edMsP49AebXQshAYWbjgg5BUdh#ix-2

The decoded argument named Swap Leg is a rust enum with quite some depth but it only show the variant name without its field.

It should be deserialized in an object, something like:

```typescript
{
    chain: {
        swapLegs: [
            split: {
                splitLegs: [
                    { percent: 80, swap_leg: { swap: { lifinity } } }.
                    { percent: 20, swap_leg: { swap: { gooseFx } } }
                ]
            }
        ]
    }
 }
```

The rust enums
```rust

pub struct SplitLeg {
    pub percent: u8,
    pub swap_leg: SwapLeg,
}

pub enum SwapLeg {
    Chain { swap_legs: Vec<SwapLeg> },
    Split { split_legs: Vec<SplitLeg> },
    Swap { swap: Swap },
}

pub enum Swap {
    Saber,
    ...
    TokenSwap,
    ...
}
```

This is what is done to an enum in the explorer right now, it simply shows the name of the variant
https://github.com/solana-labs/solana/blob/d3460acee09a8dc8f79c1f14c1493743e3b00391/explorer/src/utils/anchor.tsx#L282-L293

#### Proposed Solution

Enchance the representation, since the IDL should give the entire rust enum with all it's field since the IDL has all the data necessary

**Comment by ngundotra** [comment]
@Arrowana can you check the link now? I think i fixed, but if i didn't, pls reopen a new issue

**Comment by Arrowana** [comment]
> @Arrowana can you check the link now? I think i fixed, but if i didn't, pls reopen a new issue

Yes it is, very nice thanks! I was thinking about doing it but never did
