### ISSUE TITLE
This is a common error just because of a capital letter?

### ISSUE THREAD

**Issue by PeruxD** [solana-labs/solana#28313]
Has anyone experienced a case like this? . Wrong address in 1 letter, it must be small K so it must be big K

https://solscan.io/account/GZ1pEMABhFXKVUbCyat9jndVVxDZLJoaWr44LH75DbwA

https://solscan.io/account/GZ1pEMABhFXkVUbCyat9jndVVxDZLJoaWr44LH75DbwA

Difference of wallet for the letter K large loss of money

210 USDC

**Comment by steviez** [comment]
Yes, addresses are [base58](https://en.wikipedia.org/wiki/Binary-to-text_encoding#Base58) so case is relevant. This type of mistake should be completely avoidable if you only copy/paste the address instead of manually retyping.
