### ISSUE TITLE
Asking for public security audit concern to profanity vulnerability

### ISSUE THREAD

**Issue by psixoz-korvin** [solana-labs/solana#28360]
Good day, Solana adopters, as i'm a part of big solana dev familiy, I'm trully worried about profanity well known vulnerability in Eth network. As we know profanity gave an opportunity to create "smooth adresses" like 0x9999111110000aaabf
on Eth using BIP-39 base such as Solana. 
https://github.com/johguse/profanity/issues/61 showed security vulnerability of "smooth adresses" -> generated public\private keys based on eliptic curve encryption and that they much more likely can be force bruted.

So i would rather ask a team memebers, if it's possible, to audit and sound the results of such security audit: if Solana public keys\vote keys like these ones:
[Frog1Fks1AVN8ywFH3HTFeYojq6LQqoEPzgQFx2Kz5Ch](https://www.validators.app/validators/Frog1Fks1AVN8ywFH3HTFeYojq6LQqoEPzgQFx2Kz5Ch?locale=en&network=mainnet&order=&refresh=)
[LSV1G6qbrCWhsPQLmm623cqXU58Ha2mZKHJ9ZadbcLv](https://www.validators.app/validators/LSV1G6qbrCWhsPQLmm623cqXU58Ha2mZKHJ9ZadbcLv?locale=en&network=mainnet&order=&refresh=)
[C1ocKDYMCm2ooWptMMnpd5VEB2Nx4UMJgRuYofysyzcA](https://www.validators.app/validators/C1ocKDYMCm2ooWptMMnpd5VEB2Nx4UMJgRuYofysyzcA?locale=en&network=mainnet&order=&refresh=)
[Cogent51kHgGLHr7zpkpRjGYFXM57LgjHjDdqXd4ypdA](https://www.validators.app/validators/Cogent51kHgGLHr7zpkpRjGYFXM57LgjHjDdqXd4ypdA)
[Certusm1sa411sMpV9FPqU5dXAYhmmhygvxJ23S6hJ24](https://www.validators.app/validators/Certusm1sa411sMpV9FPqU5dXAYhmmhygvxJ23S6hJ24?locale=en&network=mainnet&order=&refresh=)
are fully secure. 
Thank you.

**Comment by steveluscher** [comment]
Asked our resident cryptographer @samkim-crypto for some input here, and it sounded to me like there's nothing concrete we can do here. If you have suggestions, please feel free to reopen this!
