### ISSUE TITLE
Packet meta struct is not stable

### ISSUE THREAD

**Issue by ripatel-fd** [solana-labs/solana#28376]
#### Problem

Interoperability with C (Firedancer) requires a stable ABI.
One of the core types `solana_sdk::packet::Meta` contains `std::net::IpAddr`  which has unknown size and undefined binary layout.

https://github.com/solana-labs/solana/blob/84acef007cb7560f61c4e2b4753b0ed76342ebf5/sdk/src/packet.rs#L33

#### Proposed Solution

- Define a replacement IP address type with `#[repr(C)]` as `struct IpAddr([u8; 16])` with From conversion trait impl for std types.
- Replace type in Meta
- Add unit tests asserting struct field offsets on amd64 and arm64

Go defines a stable and efficient dual-stack IP address type using [IPv4-mapped IPv6](https://www.ibm.com/docs/en/zos/2.2.0?topic=addresses-ipv4-mapped-ipv6)

https://cs.opensource.google/go/go/+/refs/tags/go1.19.2:src/net/netip/netip.go;l=38

They also include an IPv6 zone param, but I'm not sure we need that.

**Comment by jstarry** [comment]
cc @behzadnouri

**Comment by steviez** [comment]
We may want this after all; re-opening for now and assigning myself, will post updates as they come.
