### ISSUE TITLE
Add verification check to make sure shreds come from Turbine

### ISSUE THREAD

**Issue by wen-coding** [solana-labs/solana#28384]
If someone bypass Turbine and send shreds directly to different parts of the network, it's possible to send different shreds to different people in an attempt to divide the network. We should add some check to verify the shreds come from Turbine.

**Comment by wen-coding** [comment]
@behzadnouri please ping me when the redundant shreds propagation path is dropped from turbine

**Comment by buffalu** [comment]
fwiw we and a few others (@brianlong bloxroute) have systems that bypass turbine for low latency access to shreds. this would interfere with those systems, so we'd just rip it out

**Comment by wen-coding** [comment]
Do you have pointers and/or code what you are doing and what you are trying to accomplish so I can take a look?

**Comment by brianlong** [comment]
We'd rip it out of some, but not all, of our servers too. In our case, we are retransmitting to nodes that we control.

I understand that you are trying to suppress malicious shreds, and that sounds good. Please include a startup parameter that we can use to shut off those checks.

**Comment by buffalu** [comment]
we hook into broadcast and retransmit and send to our rpc servers for low latency access to shreds

**Comment by wen-coding** [comment]
If you use it mostly for RPC servers that's fine, we will give you a flag to turn it off.

**Comment by carllin** [comment]
@t-nelson private p2p soooooonn
