### ISSUE TITLE
Last Restart Slot Sysvar

### ISSUE THREAD

**Issue by jarry-xiao** [solana-labs/solana#28380]
#### Problem
Solana makes a tradeoff between security and liveness in favor of security. If you can't have both, this is clearly the right decision (despite what naysayers on Twitter will have to say). The biggest issue with network restarts is for DeFi protocols that have stale prices, as the state on restart is representative of the chain state prior to halting.

While liveness issues are obviously not desirable, the system should give developers the necessary tools to adapt to the most adverse situations. It is the responsibility of the protocol builders to understand how programs behave, especially when there are user funds at play.

Right now the biggest liability from restarts is that arbitrage bots will swoop in immediately to take out stale quotes. This is a huge risk for anyone supplying liquidity on-chain. Essentially, the first slot back post restart becomes a race.

#### Proposed Solution
While there is no way to solve this problem for market mechanisms that rely on arbitrage, introducing a `LastRestartSlot` sysvar will help a lot. Suppose I had a program that recorded the slot every time a writable action hit the contract: 

```
struct State {
    pub snapshot_slot: u64,
}

/// new Sysvar
struct LastRestartSlot {
   pub slot: u64,
}
```

My contract can then implement logic that looks roughly like the following:
```
let current_slot = Clock::get()?.slot;
let last_restart_slot = LastRestartSlot::get()?.slot;
let snapshot_slot = State::load(state_account)?.snapshot_slot;
if last_restant_slot >= snapshot_slot && current_slot >= last_restart_slot {
   .... // Perform actions to prevent negative externalities to the network
}
```
These types of solutions improve the chain's robustness to liveness problems. Both core and application devs should coordinate to design clean solutions to these worst case scenarios.

**Comment by jarry-xiao** [comment]
An alternative solution would be to have the first `N` slots on a restart be vote-only. The basic idea is that programs need to be able to utilize context from the chain to infer liveness issues, and this context should affect the way protocols handle new interactions. I don't really care how we get there

**Comment by mschneider** [comment]
i definitely like this idea, we do see a lot of first slot arbitrage. i don't know how we can solve this though practically in a way that it handles all possible scenarios.

**Comment by jarry-xiao** [comment]
Yeah there's no foolproof solution, but implementing program heartbeats seems like a reasonable way to address part of the problem. Something is better than being completely in the dark

**Comment by losman0s** [comment]
> An alternative solution would be to have the first `N` slots on a restart be vote-only. The basic idea is that programs need to be able to utilize context from the chain to infer liveness issues, and this context should affect the way protocols handle new interactions. I don't really care how we get there

At first glance less in favour of this than the original proposal. The sysvar practically enables protocols to introduce liveness failure circuit breakers which is quite flexible, and allows both logic-based and manual resets (which avoids a time constraint like with the N vote-only slots, for instance).

**Comment by jarry-xiao** [comment]
I believe there is push back from the core team to add in a new sysvar. I do agree that it is the most unambiguous way to solve the problem (that I can think of). Not sure how else the VM can get context about the runtime environment status.

**Comment by losman0s** [comment]
Would love to hear the specific concerns with this.

**Comment by steviez** [comment]
Going to close this issue as it became stale. A last restart slot sysvar has since been implemented and pushed into master. The feature itself should land in v1.17 and become available after the feature is enabled. See https://github.com/solana-labs/solana/issues/32177 for links to the SIMD discussion + implementation PR
