### ISSUE TITLE
Improve TpuConnectionCache and finish splitting quic and udp clients

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#28401]
#### Problem
#28080 landed, but some tasks still remain to be able to pull in only a quic or a udp client (separately).

#### Proposed Solution

- [ ] Improve TpuConnectionCache apis:
  - [ ] convert to fallible methods and use errors appropriately
  - [x] Remove Default implementations for TpuConnectionCache and TpuConfig #28788
  - [ ] Streamline connection "Result" structs
  - [ ] Return futures from async trait methods
- [x] Separate quic-client and udp-client files into their appropriate crates https://github.com/solana-labs/solana/pull/28762
  - [x] Move ConnectionCache back into solana-client, since we don't want to support it in the slimmed solana-tpu-client
  - [x] Handle TpuClient (consider how much backward compatibility to preserve)
- [ ] Deprecate ConnectionCache (ThinClient, TpuClient)
- [ ] Replace uses of ConnectionCache with TpuConnectionCache (new ThinClient, TpuClient)
- [ ] DRY anything that can be deduped
- [ ] Add proper rust docs

**Comment by KirillLykov** [comment]
One thing I thought might be generally useful is to place wrapper for all three clients (now in bench-tps) to a common place in solana repo so that it can be accessible by clients
