### ISSUE TITLE
docs: transaction format overview doesn't mention versioned transactions

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#28576]
#### Problem
The [transaction overview docs](https://edge.docs.solana.com/developing/programming-model/transactions) make no mention of versioned transactions, for which there's an entire page

#### Proposed Solution

Add a short blurb and link out to the full versioned transaction docs

**Comment by bji** [comment]
Something more than a link out is needed in my opinion. That page gives a detailed explanation of the binary format of a transaction.  The page I've seen about v0 transactions does not include anything like this, instead being a list of "programming for dummies" links.

**Comment by bji** [comment]
That is assuming that there has been a change to the binary format, which is not at all clear to me.

**Comment by bji** [comment]
This page has a Rust description of the version transaction format:

https://edge.docs.solana.com/proposals/versioned-transactions

I think that the Rust part is mostly noise given that 
https://docs.solana.com/developing/programming-model/transactions

is complete, clear, and language-agnostic.  I think that the following text:

"Size changes[#](https://edge.docs.solana.com/proposals/versioned-transactions#size-changes)

    1 extra byte for the version field
    1 extra byte for the address_table_lookups length
    34 extra bytes for each address table lookup which includes 32 bytes for the address of the table and a byte each for the lengths of the writable_indexes and readonly_indexes fields
    1 extra byte for each lookup table index"
    
 is meant to describe the differences in the binary formats?

**Comment by bji** [comment]
Looks to me like the simplest way to convert legacy transactions to v0 transactions assuming that no address table lookups are being used, is to add a single 0 byte to the beginning and a single 0 byte to the end of the message.

**Comment by t-nelson** [comment]
> Looks to me like the simplest way to convert legacy transactions to v0 transactions assuming that no address table lookups are being used, is to add a single 1 byte to the beginning and a single 0 byte to the end of the message.

no one should be converting anything and the docs ought not be suggesting otherwise

**Comment by bji** [comment]
> > Looks to me like the simplest way to convert legacy transactions to v0 transactions assuming that no address table lookups are being used, is to add a single 1 byte to the beginning and a single 0 byte to the end of the message.
> 
> no one should be converting anything and the docs ought not be suggesting otherwise

Sorry "convert" is the wrong word.  What I meant is, converting code that generates transaction bytes.  Not all of it is done in Rust or Javascript using Solana's code.  Any code generating legacy transactions can, assuming that Address Table Lookup stuff is not needed, just prepend 0xF0 to the message (which is high bit set, version number v0) and appending 0 (which is "no Address Table Lookup entries") to the message.

I'm just kind of thinking out loud here and also trying to verify that my understanding of those docs is correct.

**Comment by t-nelson** [comment]
i would simply build a legacy transaction should i not need any ALTs. they're legacy, not deprecated

**Comment by LukasDeco** [comment]
Does it still make sense to add this given the page is the very next page in documentation? Just double checking.
