### ISSUE TITLE
Commission rugs

### ISSUE THREAD

**Issue by janlegner** [solana-labs/solana#28628]
#### Problem
Validators can change commission at any time to any value. How to rug:
1) Be a validator with 0 % commission, who has attracted some stake (e.g. from stake pools)
2) Wait for final slots of the epoch and change commission to 100 %
3) Wait for the first slots of the epoch and change commission to 0 %
...
4) Profit

Let's say a validator does this in epoch `N` and stakers notice in epoch `(N + 1)` and immediately unstake. The validators then keeps 100 % of rewards from 2 epochs.

Examples of such behaviour by validators, who try to change commission very quickly (this one was a bit more difficult to catch):
| Validator | Epoch | Epoch slot | Commission set to | Tx |
|-|-|-|-|-|
| `EbLCgt91hyCi1RNZMDmVHGWBJ8oxrBeZLeJ24uqxdskM` | 350 | 431724 | 100 % | [3frtXYL2Wx8oDkmA2Me9xxKWDXp6vcdnJDT2Bcf7w17jNiVZ4vkAn9EQNqqUdJDnPoGpPDry7YTy8KSnjx8wtUD9](https://explorer.solana.com/tx/3frtXYL2Wx8oDkmA2Me9xxKWDXp6vcdnJDT2Bcf7w17jNiVZ4vkAn9EQNqqUdJDnPoGpPDry7YTy8KSnjx8wtUD9?cluster=mainnet) |
| `EbLCgt91hyCi1RNZMDmVHGWBJ8oxrBeZLeJ24uqxdskM` | 351 | 148 | 0 % | [4DS6MYpbsfL3p2afkbE16gcT5WtbW4ndQK4P3jCMWenrvkxnGBM3kXbkhkphB4KcS7DJBCDCMFsGRbigxREcDajn](https://explorer.solana.com/tx/4DS6MYpbsfL3p2afkbE16gcT5WtbW4ndQK4P3jCMWenrvkxnGBM3kXbkhkphB4KcS7DJBCDCMFsGRbigxREcDajn?cluster=mainnet) |
|-|-|-|-|-|
| `FkkTaE7A969ZLNrqDe3cWYLkd9igYUo3tQCHguCvv5xW` | 364 | 263 | 0 % | [4LHgCbgD7Q1HHfqKLmt528cajjRfwbAsHeq6F2CueL6pBcNtA8L3WuqefghUqMJt5yVcniU4w1i9w37wj8RdxDyN](https://explorer.solana.com/tx/4LHgCbgD7Q1HHfqKLmt528cajjRfwbAsHeq6F2CueL6pBcNtA8L3WuqefghUqMJt5yVcniU4w1i9w37wj8RdxDyN?cluster=mainnet) |
| `FkkTaE7A969ZLNrqDe3cWYLkd9igYUo3tQCHguCvv5xW` | 364 | 431988 | 100 % | [3nx6GhUkTVNg7JcNV5GFEFoBx3tCtPgxbqe7NX3o8ZWbM3s4U2aWfSm1ExcMRWprfqaZ9nCoZJedbSU26u9EEiZ](https://explorer.solana.com/tx/3nx6GhUkTVNg7JcNV5GFEFoBx3tCtPgxbqe7NX3o8ZWbM3s4U2aWfSm1ExcMRWprfqaZ9nCoZJedbSU26u9EEiZ?cluster=mainnet) |
| `FkkTaE7A969ZLNrqDe3cWYLkd9igYUo3tQCHguCvv5xW` | 365 | 282 | 0 % | [QgXGHawoM8vePwNASfhvMRvm8LgLNinUM5bdeSZMtoehnyP3VLHt2MFUNeyRNP1wGJs5VqrxQPXuxskMMvzjY7E](https://explorer.solana.com/tx/QgXGHawoM8vePwNASfhvMRvm8LgLNinUM5bdeSZMtoehnyP3VLHt2MFUNeyRNP1wGJs5VqrxQPXuxskMMvzjY7E?cluster=mainnet) |

Last vote of the first validator (`EbLCgt91hyCi1RNZMDmVHGWBJ8oxrBeZLeJ24uqxdskM`) happened in slot 152078890 (epoch 352, right after Marinade blacklisted this validator)
Incidentally, the 'other' validator (`FkkTaE7A969ZLNrqDe3cWYLkd9igYUo3tQCHguCvv5xW`) was first detected by Marinade at epoch 352. (This suggest either someone else got immediately inspired or that this is the same guy)

With gains from the first rug the attacker could have easily spun 20 validator nodes and run them for a month, making the next rug even more successful.

#### Proposed Solution
I am not sure what the best approach would be but I have a few suggestions:
- Limit the possibility to change commission to first 50 % of the epoch. (This still allows the rug but makes it easier to notice and unstake early, e.g. in the first epoch it happens, giving the attacker only 1 epoch worth of rewards.)
- Introduce `activation_epoch` for the commission changes.
- Introduce concept of `commission confirmation`: E.g. in epoch `N` an instruction is called to set `next_commission`, in epoch `N + 1` an instruction is called which sets `commission` to a value previously stored in `next_commission`, effectively confirming this is the new commission but giving heads up to stakers.

**Comment by t-nelson** [comment]
the best approach today is public ~shaming~ awareness.  [track offenders](https://www.validators.app/commission-changes?locale=en&network=mainnet) and make a stink

there are no free bits in the stake state today to epoch-gate commissions changes. there has been consideration for this taken in a proposed next-generation stake account format, https://github.com/joncinque/solana/blob/83ffb25bd06396cb093219545e648e60b87673da/docs/src/proposals/stake-v2.md

**Comment by janlegner** [comment]
Sadly, ~shaming~ awareness is not really good enough as this kind of rug can be quite profitable. Tracking offenders is difficult (e.g. the case I presented here is not even visible in validators.app) and once they change identity? Nothing to be really done. Luckily, Marinade's new dashboards (coming soon :tm:) will provide accurate insight.

Thanks for pointing me at the stake v2, I was not aware commission history was baked there - that should take care of it. Closing the issue, then.

**Comment by c3pko** [comment]
@janlegner one non technical addition you could make to marinade's delegation strategy is requiring that the validators you stake to have at least X amount of stake from other delegators. this would've caught vote account 9eG63CdHjsfhHmobHgLtESGC8GabbmRcaSpHAZrtmhco--they had 0 external delegations. it would not have caught 44H7DtZPMDxK2siQoGhDGeVNutWfYNi7XZenuPDrc97Y but it's at least a start.
