### ISSUE TITLE
Debug slots repaired ~100% by majority of the cluster

### ISSUE THREAD

**Issue by behzadnouri** [solana-labs/solana#28637]
#### Problem
* From `shred_insert_is_full` metric we sometimes observe slots which the majority (if not almost all) of the cluster repair ~100% of data shreds in that slot.
* Given the randomized shuffling of nodes for each shred propagated through Turbine tree, no single node in the cluster other than the leader itself can cause such degradation.
* Therefore this is most likely not a problem with Turbine propagation but at the link from the leader to the root of the Turbine propagation tree (which is a random node for each shred in slot), possibly caused by congestion, packet drop, or something else at the leader node.
* Given that repair is slower than turbine, nodes take much longer time to obtain all shreds in the slot, and ultimately the slot is not rooted. Therefore the cluster only wastes bandwidth and computation to repair an ultimately dead slot.
* Ideally the cluster will skip such slots sooner and would not waste resources to repair the slot if most of nodes have not received the shreds from Turbine.

#### Proposed Solution
Debug why the repair service chooses to repair such slots instead of skipping them sooner.

**Comment by jbiseda** [comment]
see also: ~1% of nodes are repairing almost every shred in almost every slot #33166
