### ISSUE TITLE
Add pagination support for large secondary index RPC queries.

### ISSUE THREAD

**Issue by IntokuSatori** [solana-labs/solana#28667]
Secondary account indexes can become quite large for certain keys which have many associated accounts in the system and thus require many GB of ram to store and can cause the validator to OOM. When the RPC call is made to the validator it also will just spin in a core and allocate memory and the resulting request will be too large to transmit over a single RPC request requiring many seconds and hitting connection timeouts. So often even indexing these keys is not useful at least with the current apis.

Proposed Solution

- [ ]  Stage 2: Add pagination support for getTokenAccountsByOwner/getProgramAccounts/etc such that a large set could be queried with multiple calls. This would fix the request size but it wouldn't fix the RAM problem.

Separate Issues will address the larger Secondary Index problems:
(3) Page-out infrequently-used secondary indexes to disk using the mmap primitives we use for the accounts index. - #28668
(4) Implement getProgramAccounts over a geyser-produced SQL or kafka and remove secondary indexes altogether

Long term we would like to go to solution (4) and remove the secondary indexes altogether. For Stage 2, I think we'll need a paginated API whether we remove the secondary indexes or not. It's just a question if we implement it also with the current validator or go straight to implementing it over the SQL or kafka database.

**Comment by t-nelson** [comment]
fwiw, we should generally be pushing people _away_ from using `gPA` and secondary indexes, instead towards a geyser plugin based DB solution.  incentivizing use of `gPA` through improvements should be discouraged

**Comment by IntokuSatori** [comment]
> fwiw, we should generally be pushing people _away_ from using `gPA` and secondary indexes, instead towards a geyser plugin based DB solution. incentivizing use of `gPA` through improvements should be discouraged

So... basically saying not to do this?

**Comment by t-nelson** [comment]
more of a "what problem is this solving that a geyser-based solution can't?"
