### ISSUE TITLE
Add an RPC API that can query the list of "Top N" secondary index keys and their sizes.

### ISSUE THREAD

**Issue by IntokuSatori** [solana-labs/solana#28666]
Secondary account indexes can become quite large for certain keys which have many associated accounts in the system and thus require many GB of ram to store and can cause the validator to OOM. When the RPC call is made to the validator it also will just spin in a core and allocate memory and the resulting request will be too large to transmit over a single RPC request requiring many seconds and hitting connection timeouts. So often even indexing these keys is not useful at least with the current apis.

Proposed Solution

- [x] Stage 1: Add an RPC API that can query the list of secondary index keys and their sizes such that we can figure out which keys are taking a lot of ram and add them to the exclusion list

Separate Issues will address the larger Secondary Index problems:
(2) Add pagination support for getTokenAccountsByOwner/getProgramAccounts/etc such that a large set could be queried with multiple calls. This would fix the request size but it wouldn't fix the RAM problem. - #28667
(3) Page-out infrequently-used secondary indexes to disk using the mmap primitives we use for the accounts index. - #28668
(4) Implement getProgramAccounts over a geyser-produced SQL or kafka and remove secondary indexes altogether

Long term we would like to go to solution (4) and remove the secondary indexes altogether, but I think a decent short-term solution could be Stage 1 while we work on (4). For (2) I think we'll need a paginated API whether we remove the secondary indexes or not. It's just a question if we implement it also with the current validator or go straight to implementing it over the SQL or kafka database.

**Comment by RdeWilde** [comment]
Is there a way to overrule MAX_NUM_RETURNED_LARGEST_KEYS with max_entries for RPC, where max_entries > 10? I'm not sure how I can influence MAX_NUM_RETURNED_LARGEST_KEYS without changing code. 🤔  Other than that, thanks a lot 👍🏼

**Comment by IntokuSatori** [comment]
> Is there a way to overrule MAX_NUM_RETURNED_LARGEST_KEYS with max_entries for RPC, where max_entries > 10? I'm not sure how I can influence MAX_NUM_RETURNED_LARGEST_KEYS without changing code. 🤔

Thats not currently exposed via an RPC API, there are limits because of the way the largest accounts are managed. When account removals happen, the entire index is not rescanned for a new largest to replace it as it would create too much overhead, it relies on accounts being re-touched by the index to do any updates to this list. When all the account are loaded this list is made, but entries aren't updated unless the account is touched by the system. Thus this pool of 100 but only return 10 gives us about ~90 replacement candidates to account for removals before a "largest" account is re-touched. This gives us better guarantees this list is still accurate without needing to rescan the entire index on each removal and instead enables us to only rescan the top 100. 

How many more entires did you want to get returned? It would need to expand the scan pool to do this with any accuracy or the list could quickly go out of date.

**Comment by RdeWilde** [comment]
Thanks for explaining. I'm trying to get a list of the largest accounts to then exclude them from indexing, if that make sense.

What do you mean by "replacement candidates to account for removals"? I'm not yet up to speed with solana's codebase and would like to understand.

The RPC uses the minimum of `MAX_NUM_RETURNED_LARGEST_KEYS` and the amount passed as a parameter. I would expect to throw an error if parameter amount >`MAX_NUM_RETURNED_LARGEST_KEYS` as the response might be unexpected. Requesting 100 where only 10 are returned suggests there are no more.

**Comment by IntokuSatori** [comment]
> Thanks for explaining. I'm trying to get a list of the largest accounts to then exclude them from indexing, if that make sense.

Makes perfect sense, thats what it's intended to be used for. 

> What do you mean by "replacement candidates to account for removals"? I'm not yet up to speed with solana's codebase and would like to understand.

So if we maintain a list of the top 10 for instance, that list is updated as we add accounts to the secondary index. So when we first build the index it is accurate, and as we add new accounts it remains accurate. This would be the ideal world. We could make that 10 into any number and it wouldn't matter. 

The issue however comes when an account is removed. Now what if one of the items in the top 10 is no longer supposed to be in the top 10 because it lost an account its for example, the owner of. In the ideal case here, we would rescan the entire Accounts DB to update the list. However, this is hundreds of million of accounts in some cases, and is just not feasible. 

Thus we have a pool of "candidates" that are searched instead. This is the 90 other accounts we keep around. We need a pool of candidates that is fairly deep in relation to the top accounts so that we can keep the top accounts accurate with a reasonable level of certainty that they will remain accurate as account churn happens. This is achieved by the ratio of candidate accounts being large in relation to the top accounts we can return. Statically, the other accounts chose for replacement should be accurate unless we get a large amount of accounts removed from a large number of the top accounts without any accounts being added back in between, which is highly unlikely to happen. 

> The RPC uses the minimum of `MAX_NUM_RETURNED_LARGEST_KEYS` and the amount passed as a parameter. I would expect to throw an error if parameter amount >`MAX_NUM_RETURNED_LARGEST_KEYS` as the response might be unexpected. Requesting 100 where only 10 are returned suggests there are no more.

I can deff change the return to an error instead of just maxing out. As far as increasing the return size to 100, I can probably also accommodate as I'd increase the pool of top accounts to ~1000, which is likely still manageable.

**Comment by IntokuSatori** [comment]
@CriesofCarrots @t-nelson Any opposition to the proposed changes:

1. Increase the top tracked accounts to 1000, limit the max returned at 100. (instead of the 100/10 split it has now)
2. Change the return to an error if the number of accounts is above the max number the API is allowed to return.

**Comment by t-nelson** [comment]
let's not worry about feature requests for features that aren't complete
