### ISSUE TITLE
Building for BPF fails using the latest mainnet release

### ISSUE THREAD

**Issue by ozgb** [solana-labs/solana#28711]
#### Problem

Building with the latest Solana (v1.13.4) causes a dependency-not-found issue. Tested on **Linux & Windows toolchains locally** and **Github Actions Ubuntu-latest**, building a new project causes this issue:

```
❯ cargo build-bpf
BPF SDK: /home/oscar/.local/share/solana/install/releases/1.13.4/solana-release/bin/sdk/bpf
cargo-build-bpf child: rustup toolchain list -v
cargo-build-bpf child: cargo +bpf build --target bpfel-unknown-unknown --release
    Updating crates.io index
error: failed to select a version for the requirement `time = "^0.3"`
candidate versions found which didn't match: 0.3.15, 0.3.14, 0.3.13, ...
location searched: crates.io index
required by package `rcgen v0.9.3`
    ... which satisfies dependency `rcgen = "^0.9.2"` (locked to 0.9.3) of package `solana-streamer v1.13.4`
    ... which satisfies dependency `solana-streamer = "=1.13.4"` (locked to 1.13.4) of package `solana-client v1.13.4`
    ... which satisfies dependency `solana-client = "=1.13.4"` (locked to 1.13.4) of package `solana-banks-server v1.13.4`
    ... which satisfies dependency `solana-banks-server = "=1.13.4"` (locked to 1.13.4) of package `solana-program-test v1.13.4`
    ... which satisfies dependency `solana-program-test = "*"` (locked to 1.13.4) of package `mock_clock v0.1.0 (/home/oscar/source/repos/mock_clock)`
```

Reverting to e.g. Solana version v1.9.29 fixes this. I tried v1.10.40 and it has the same issue.

I was building using [this repo+commit](https://github.com/oscarbailey-tc/mockclock/commit/9bceaa53d039a1be518fce38794b9661804ca984), where the only dependency is `solana-program`.

#### Proposed Solution

I have a project on my filesystem set to Solana version v1.13.3 and it builds fine, but if I setup a new project with that version it fails to build. Looks like something has changed in the crates.io index recently that's caused this issue? Not sure.

**Comment by majchrzamemil** [comment]
I've encountered the same issue with version 1.10.35

**Comment by oscarbailey-tc** [comment]
> I've encountered the same issue with version 1.10.35

[Looks like a potential solution is to use the solana 14.4.7 tools](https://github.com/pyth-network/pyth-sdk-rs/pull/85)

> Uses Solana cli tools of v1.14.7 that have sbf instead of bpf. It seems that since bpf is outdated, for whatever reason, crates.io index cannot detect a suitable dependency for time that matches the flags/architecture. This change solves that problem.

Solana version 1.13.4 in dependencies, compilation now works for me

**Comment by oscarbailey-tc** [comment]
More info on this, building with new tools you should still use the `cargo build-bpf` command - I got this error when using `cargo build-sbf`:

```
error[E0107]: this struct takes 0 lifetime arguments but 1 lifetime argument was supplied
   --> src/lib.rs:375:20
    |
375 |     StdoutLock(io::StdoutLock<'a>),
    |                    ^^^^^^^^^^---- help: remove these generics
    |                    |
    |                    expected 0 lifetime arguments

error[E0107]: this struct takes 0 lifetime arguments but 1 lifetime argument was supplied
   --> src/lib.rs:376:20
    |
376 |     StderrLock(io::StderrLock<'a>),
    |                    ^^^^^^^^^^---- help: remove these generics
    |                    |
    |                    expected 0 lifetime arguments

For more information about this error, try `rustc --explain E0107`.
error: could not compile `termcolor` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
```

**Comment by dmakarov** [comment]
> More info on this, building with new tools you should still use the `cargo build-bpf` command - I got this error when using `cargo build-sbf`:

Interesting. Underneath `cargo build-bpf` invokes `cargo build-sbf` to build a crate.

**Comment by Henry-E** [comment]
FYI this also breaks one of anchor's CI tests. I'm playing around with some of the solutions suggested here, like changing versions but not having any luck yet.

**Comment by 0xripleys** [comment]
running into the same issue with 1.10.29

**Comment by mvines** [comment]
We don't support obsolete branches like the v1.10 release line. Please use the latest 1.14 release and if the problem persists then it can be looked at

**Comment by 0xripleys** [comment]
yeah using 1.14 works. fyi i think a lot of people are blocked because the latest anchor release only supports 1.10. i think that'll be fixed soon though

**Comment by oscarbailey-tc** [comment]
> We don't support obsolete branches like the v1.10 release line. Please use the latest 1.14 release and if the problem persists then it can be looked at

The issue here is with current mainnet version (v1.13.X)

The v1.14 releases are marked as not-recommended for mainnet so I haven't been using them.

**Comment by 0xripleys** [comment]
I'm still running into this issue with 1.13.5 unfortunately

**Comment by 0xnetfox** [comment]
Running with the issue with `1.13.17` too, updating the cli to version to 1.14.17 seems to work, but it's a bit weird that the fix is using testnet releases for stuff that will go on mainnet
