### ISSUE TITLE
Solana 1.13 (stable) branch uses an outdated rustc

### ISSUE THREAD

**Issue by ARitz-Cracker** [solana-labs/solana#28743]
(According to [this](https://github.com/solana-labs/sbf-tools/issues/38#issuecomment-1067387386), I should open an issue here)
Hey there, I'd like to use some features available in the last couple versions of rust, Most notably workspace-wide dependencies, and `if let else`. I'm currently using the "stable" branch which currently serves 1.13.x as we're targeting mainnet.

I've discovered that the stable release includes `sbf-tools/bpf-tools` v1.27, which uses rustc v1.59.0, which released around 9 months ago.

I understand that the solana program building toolchain is undergoing some major changes over on testnet, and any new releases of the toolchain is targeting that, however, is there anything that can/will be done to use more recent rust and cargo features while still targeting mainnet?

**Comment by steviez** [comment]
As the bot message says, can you please ask this on stack exchange (or maybe even check if this has already been asked / answered).

If this question has not been asked/answered yet, post the stack exchange link here and I will answer it if someone doesn't beat me to it

**Comment by ARitz-Cracker** [comment]
@steviez How is this a question applicable for the stack exchange? My issue is that the version of rustc and cargo that ships with the 1.13 solana program toolchain is outdated and prevents me from using newer rust features I'd like to use.

Even though I have rustc 1.65.0 installed on my system, I am limited to 1.59 features as that's the version of rust `cargo build-bpf` calls upon.

**Comment by dovahcrow** [comment]
> @steviez How is this a question applicable for the stack exchange? My issue is that the version of rustc and cargo that ships with the 1.13 solana program toolchain is outdated and prevents me from using newer rust and cargo features I'd like to use.
> 
> Even though I have rustc 1.65.0 installed on my system, I am limited to 1.59 features as that's the version of rust `cargo build-bpf` calls upon.

Right I have the same feeling that having every question on stakeoverflow is a very bad idea.
