### ISSUE TITLE
Inconsistency w.r.t. determining if an instruction is top-level

### ISSUE THREAD

**Issue by metaproph3t** [solana-labs/solana#28763]
#### Problem

In [invoke_context.rs](https://github.com/solana-labs/solana/blob/0347d9cf78847d4a4f572fa9d2c52edd2927c0db/program-runtime/src/invoke_context.rs#L663-L666), the following is written:

```rust
let nesting_level = self
            .transaction_context
            .get_instruction_context_stack_height();
let is_top_level_instruction = nesting_level == 0;
```

In [transaction_context.rs](https://github.com/solana-labs/solana/blob/0347d9cf78847d4a4f572fa9d2c52edd2927c0db/sdk/src/transaction_context.rs#L260-L264), the following is written:

```rust
/// Gets instruction stack height, top-level instructions are height
/// `solana_sdk::instruction::TRANSACTION_LEVEL_STACK_HEIGHT`
pub fn get_instruction_context_stack_height(&self) -> usize {
    self.instruction_stack.len()
}
```

In [instruction.rs](https://github.com/solana-labs/solana/blob/0347d9cf78847d4a4f572fa9d2c52edd2927c0db/sdk/program/src/instruction.rs#L728-L729), the following is written:
```rust
// Stack height when processing transaction-level instructions
pub const TRANSACTION_LEVEL_STACK_HEIGHT: usize = 1;
```

Evidently (unless I am missing something, which has a greater than 25% probability), these three things cannot be true at the same time. Top-level instructions cannot be both at stack height 1 and 0. Perhaps the comment is wrong and top-level instructions are at height TRANSACTION_LEVEL_STACK_HEIGHT - 1?

**Comment by joncinque** [comment]
The code is definitely tough to read around here, but it's correct! The checks for `get_instruction_context_stack_height() == 0` are right before a call to `invoke_context.push()`, ie https://github.com/solana-labs/solana/blob/0347d9cf78847d4a4f572fa9d2c52edd2927c0db/program-runtime/src/invoke_context.rs#LL689C9-L689C22, so at that point, the stack height is actually at 0, and only hits 1 when you're actually processing an instruction.

I don't know the code well enough to judge if the checks should be refactored to be done after the call to `push()`, but it's correct from what I'm seeing.

**Comment by metaproph3t** [comment]
Makes sense, thank you sir.
