### ISSUE TITLE
Error: Data writes to account failed: Custom error: Max retries exceeded

### ISSUE THREAD

**Issue by choldas-rwaltz** [solana-labs/solana#28764]
#### Problem
I am trying to deploy the smart contract on Solana but getting an error. I followed all the required steps.
Even though I have created a new wallet and new program Id but still not able to deploy.

I have contacted to support team but they said
"I saw ping times going up a few hours ago in the Devnet cluster. Temporary network degradations could be the cause of the issue https://explorer.solana.com/?cluster=devnet
It appears the block hash you used to submit this transaction expired before it could make it to the chain."

I have tried to deploy the program using the below command,
```
anchor build
anchor deploy 
solana program deploy /opt/projects/demo/rust-demo/tokenc/target/deploy/tokenc.so
solana program deploy /opt/projects/demo/rust-demo/tokenc/target/deploy/tokenc.so --skip-fee-check
```

I am using Ubuntu 20.04.4 LTS and Anchor Framework for program development. Below are the software versions.
```
rustc 1.63.0 (4b91a6ea7 2022-08-08)
rustup 1.25.1 (bb60b1e89 2022-07-12)
anchor-cli 0.25.0
solana-cli 1.10.29 (src:7f1fb145; feat:1425680972)
cargo 1.63.0 (fd9c4297c 2022-07-01)
node v14.17.0
```

**Cargo.toml**
```
[package]
name = "tokenc"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "tokenc"

[features]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
cpi = ["no-entrypoint"]
default = []

[dependencies]
anchor-lang = "0.25.0"
anchor-spl = {version = "0.25.0"}
spl-token = {version = "3.3.0", features = ["no-entrypoint"]}
```

**Anchor.toml**
```
[features]
seeds = false
skip-lint = false
[programs.devnet]
tokenc = "CLzytgbkZo8XzJ4MZdcP1xq5j88Z1HBRVY4iWHDTkpta"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/choldas/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
```

Is it a devnet cluster problem or a software version issue? 
Please suggest a solution. 

![Screenshot from 2022-11-04 10-57-59](https://user-images.githubusercontent.com/108717926/200483126-f7698dda-6e8b-4861-94eb-13240674812f.png)

**Comment by z3000z3000z3000** [comment]
update solana to 1.14 ?
