### ISSUE TITLE
snapshot finder

### ISSUE THREAD

**Issue by rozum-dev** [solana-labs/solana#28811]
#### Problem
At the start of running node process it is not clear from where and what snapshot is downloaded, at what speed etc. The download status is not obvious as a result the process may hang downloading the snapshot for more than an hour. 
On the other hand, a community member has developed a useful tool for downloading snapshots, which is actively used by validators. It has a large number of settings that allows to select and download the appropriate snapshot and run the node as quickly as possible.
https://github.com/c29r3/solana-snapshot-finder

#### Proposed Solution
1. Is it possible to transfer the logic of the snapshot search utility to the native client?
2. Consider giving a grant to a developer for a useful, actively used tool.

**Comment by KirillLykov** [comment]
The default way of loading snapshots is:
* time consuming
* time to download is unpredictable, sometimes it just takes too long and user restarts the process

To address these problems, an alternative tool is available: https://github.com/c29r3/solana-snapshot-finder
It allows to
* setup constraints (min download speed, etc)
* find the best node to download 
* download snapshot from this node using wget
* download incremental snapshot

Open questions:
1. Does snapshot-finder download only from RPC nodes?
2. Can we have a comparable user experience with default method? 
3. Do we want to change default way or introduce a new tool?

**Comment by steviez** [comment]
I just booted up a node so I could remind myself about these things.

>  not clear from where and what snapshot is downloaded,

Running v1.14.7, `solana-validator monitor` displays this information
```
$ solana-validator --ledger ~/ledger/ monitor
⠂ Validator startup: DownloadingSnapshot { slot: 161181806, rpc_addr: 145.40.93.177:80 }...
```
As to "what snapshot", once a node has been selected, their latest snapshot is chosen for download. 

>  at what speed etc. The download status is not obvious

It could be nice to have download speed bubbled up to `solana-validator monitor` (not sure how invasive that would be), but this information is present in logs:
```
2022-11-15T16:28:13.242003218Z INFO  solana_download_utils] downloaded 4416934312 bytes 11.5% 53070276.0 bytes/s
[2022-11-15T16:28:19.253699316Z INFO  solana_download_utils] downloaded 4735891064 bytes 12.3% 53056036.0 bytes/s
[2022-11-15T16:28:25.265968577Z INFO  solana_download_utils] downloaded 5054985376 bytes 13.1% 53073860.0 bytes/s
```
Additionally, there are validator args to control a minimum acceptable download speed

```
        --maximum-snapshot-download-abort <MAXIMUM_SNAPSHOT_DOWNLOAD_ABORT>
            The maximum number of times to abort and retry when encountering a slow snapshot download. [default: 5]

        --minimal-snapshot-download-speed <MINIMAL_SNAPSHOT_DOWNLOAD_SPEED>
            The minimal speed of snapshot downloads measured in bytes/second. If the initial download speed falls below
            this threshold, the system will retry the download against a different rpc node. [default: 10485760]
```

> as a result the process may hang downloading the snapshot for more than an hour

Assuming you encountered this, what were your validators args, specifically `known-validators`. Did you pick out nodes that were geographically close to you, possibly in the same data center?

> a community member has developed a useful tool for downloading snapshots, which is actively used by validators.

I have not personally used this tool, but I have seen it mentioned before. An issue I've seen is some validator operators just used the args from here [here](https://docs.solana.com/clusters) without fully understanding what all of the args do. With those example args, validators limit themself to download from the 4 listed nodes. As a result, those 4 nodes (which are all run by Solana Labs) are constantly slammed serving snapshots, and depending on where a validator is positioned, those 4 nodes may not provide the quickest download speed to them.

This is important to call out as a major difference between what the tool does and what `solana-validator`:
- The tool considers all nodes except those that have been explicitly noted to avoid
- solana-validator with `--only-known-rpc` considers only nodes that are on the approved list as specified by validator args

We typically lean towards cautiousness and `--only-known-rpc` is in line with that. The hope was that operators would grow their own list of trusted operators by interacting with other validators, using various validator performance tracking sites, etc. Allowing snapshot downloads from anyone could allow a malicious actor to distribute malformed snapshots.

> Is it possible to transfer the logic of the snapshot search utility to the native client?

Yes, some aspects (such as min download speed) are already there, others pieces such as doing a quick speed check have been started but back-burnered for various reasons: https://github.com/solana-labs/solana/pull/27154

**Comment by overclock-validator** [comment]
It works pretty well but one of the issues has been that it grabs 1.10 snapshots from some old rpcs apparently and this leads to an incompatibility like this: 
[2022-11-08T23:41:32.156396684Z WARN  solana_runtime::snapshot_utils] Snapshot Error: "invalid snapshot data file: /mnt/md0/solana-mainnet/ledger/snapshot/tmp-snapshot-archive-2FV9Pz/snapshots/160037629/160037629 has 495007557 bytes, however consumed 495007523 bytes to deserialize"

My validator partner patched this so that you can specify the version but we need to submit the PR... I'll let him know. I think he had some other ideas on this as well.

**Comment by KirillLykov** [comment]
@overclock-validator Having a PR would really help, any ideas about this matter (or related) are appreciated

**Comment by brennanwatt** [comment]
Agree with the general sentiment that making snapshot download faster, more consistent, more reliable, etc. would be a great thing. It looks like @steviez covered things really well but I'll add a couple comments:

1. Both #27154 and https://github.com/c29r3/solana-snapshot-finder are only looking at a single archive format for testing download speed. #27154 looks at TarZstd while snapshot finder looks at Bzip2. Maybe this is good enough for a best effort speed test, but a more intelligent selection of archive format could be worthwhile.

2. When manually observing snapshot download behavior, I observed it's not always straightforward which node to attempt download from. The most recent snapshot node might have 10MBps download speed, but the second most recent might be capable of 40MBps. In this case, it's almost certainly worth it to go with the second most recent, but how exhaustively should we check?

In my experience, we need to measure download speeds sequentially for multiple seconds to have some confidence in the results, so checking large number of RPCs is non-negligible cost. For #27154, I ended up using 2 thresholds: one to define a "super node" - if I see one of these, early out and download from it, and a second threshold for a minimum viable download speed. I'll check the set of RPC nodes containing the most recent snapshot and move forward with a min viable node if no super node is found.

Personally, I like the idea of collecting all of the best ideas from these efforts and incorporating into the native client

**Comment by KirillLykov** [comment]
@brennanwatt 
1. Do you propose to have an option to select archive format or just do more experiments to find the best one? I wonder what could be relevant metrics beside of compression rate: do we care about mem/cpu load on rpc machines?
2. My understanding is that we want to solve something like the following:
```
Let S_i - size of the snapshot on i-th node,
v_i -- download speed on i-th node
T_i -- (most recent snapshot size - i-th snapshot size)
V -- speed of downloading incremental snapshots

j = arg max_j { S_i/v_i + T_i/V}
```
Assuming that we can download incremental snapshots from somewhere with speed `V`.
I guess we can try to find the optimal solution if number of nodes is small or do some good-enough heuristic (like you've proposed).

**Comment by KirillLykov** [comment]
@brennanwatt for 1, I guess there are two ways to support different formats -- one is to link with corresponding compression library, another is to run a process to compress a snapshot. I guess you have in mind the second to avoid introducing additional dependencies.

For 2, because we need to estimate each RPC node download speed your approach makes sense. Do we want to download using something like libcurl or manually? https://github.com/c29r3/solana-snapshot-finder uses wget because downloading from some nodes at max speed might lead to spam attack alert (https://github.com/c29r3/solana-snapshot-finder/issues/11)

**Comment by brennanwatt** [comment]
> @brennanwatt for 1, I guess there are two ways to support different formats -- one is to link with corresponding compression library, another is to run a process to compress a snapshot. I guess you have in mind the second to avoid introducing additional dependencies.
> 
> For 2, because we need to estimate each RPC node download speed your approach makes sense. Do we want to download using something like libcurl or manually? https://github.com/c29r3/solana-snapshot-finder uses wget because downloading from some nodes at max speed might lead to spam attack alert ([c29r3/solana-snapshot-finder#11](https://github.com/c29r3/solana-snapshot-finder/issues/11))

@KirillLykov - I believe we already support Bzip2, Gzip, TarZstd, TarLz4, etc. compression formats and can specify which archive format to use from the command line. On the download side, we likely just need to take what we can get from the RPC (whatever's there).

I don't have a strong preference for which download method is used. We use the reqwest crate on the native client today

**Comment by overclock-validator** [comment]
> @overclock-validator Having a PR would really help, any ideas about this matter (or related) are appreciated

@dubbelosix 's changes to snapshot finder are here. It's still just a small change but allows you to get snapshots from a certain version. https://github.com/overclock-validator/autoclock-rpc/blob/master/templates/snapshot-finder.py

I think one thing to consider is that if certain nodes are getting hit by snapshot requests quite a bit it might burden them with egress costs... perhaps there's a way to rotate around.
