### ISSUE TITLE
accounts.merge_parents() should verify that no account locks are held during merge

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#2882]
#### Problem
multiple threads may access a live bank during a merge_parents in the current, linear PoH, though they really shouldn't, we won't catch them 

#### Proposed Solution
to maybe catch them, assert!(accounts.locks.is_empty()) at the start of merge_parents

**Comment by garious** [comment]
Sounds pretty error prone. Maybe we can clone the child, squash in the parent, and then `mem::swap` the Arc.

**Comment by rob-solana** [comment]
this issue is a tracker for me to go back and add the check that used to be there...

I agree that we play fast and loose with Arc<Bank>

**Comment by mvines** [comment]
@rob-solana is this issue still relevant?

**Comment by rob-solana** [comment]
yes, @carllin was chasing Friday

**Comment by mvines** [comment]
sg, thanks.  There's been no update here in months so the issue looked stale.

**Comment by carllin** [comment]
https://github.com/solana-labs/solana/pull/3819
