### ISSUE TITLE
v0 transactions don't have partialSign method available

### ISSUE THREAD

**Issue by Alwin24** [solana-labs/solana#28849]
#### Problem
I am trying to replicate the following with VersionedTransaction - Backedend API -

```
        transaction.partialSign(devWalletKey)
        let serializedTransaction = transaction.serialize({ requireAllSignatures: false })
        let transactionBase64 = serializedTransaction.toString("base64")

        return res.json({ success: true, transactionBase64 })
```
Frontend -
```
    let response = await axios.post(`${API_URL}withdrawToken`, { wallet: wallet.publicKey!.toBase58(), amount })

    let txn: string = response.data.transactionBase64

    let recoveredTxn = Transaction.from(Buffer.from(txn, 'base64'))
    let signedTxn = await wallet.signTransaction!(recoveredTxn)

    let tx = await solConnection.sendRawTransaction(signedTxn.serialize())
```
But with versioned transactions @solana/web3.js library there is no partialSign method or serialize without requiring all signatures, so when I try to deserialize it I get an error saying **signatures.length does not match**
#### Proposed Solution
Implementing **transaction.partialSign(Keypair)** and **transaction.serialize({ requireAllSignatures: false })** as in legacy transactions for v0 transactions.

**Comment by steveluscher** [comment]
Hey there! I think your problem stems from some confusion about the API. Can you tag me after you post this as a Stack Exchange question, and I'll hop in and answer it? The answer will go on to help others that have the same trouble.

**Comment by bhgames** [comment]
How does one serialize without requiring all signatures? The stack exchange didn't really explain that from what I could tell.

**Comment by bhgames** [comment]
I think Im going to have to go back to legacy transactions due to this. Shame!
