### ISSUE TITLE
multinode test complains about BlobError(VerificationFailed)

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#2885]
Run the multinode test, note that while it passes stdout is full of `[solana::replay_stage] process_entries failed: BlobError(VerificationFailed)` error messages.  Do we have a borken test?

**Comment by carllin** [comment]
I think there's a race between when 1) the replay stage sets the last id, and 2) when it checks the slot.consumed to get the blob index in ReplayStage::new(). Additional blobs (call them set B) could have come in between steps  1 and 2 (the TVU already has started), so when you set the current_blob_index to slot.consumed in step 2), you'll skip those blobs in set B, and poh verification will fail

**Comment by mvines** [comment]
Sounds like carl found it, ❤️. Assigning to him
