### ISSUE TITLE
Switch integration with BigTable from gRPC-based to ODBC-based to remove vendor lock-in

### ISSUE THREAD

**Issue by frbrkoala** [solana-labs/solana#28866]
#### Problem
Solana RPC/Warehoise nodes use Google’s BigTable service as their primary store for [Long term RPC Transaction History feature](https://docs.solana.com/implemented-proposals/rpc-transaction-history) (https://docs.solana.com/implemented-proposals/rpc-transaction-history). There are two consequences of this decision:

* The costs of BigTable service is quite expensive for majority of potential Web3 startups and starts with thousands of USD monthly with rapid growth rate [[source](https://twitter.com/guisalberto/status/1586473202938937344)] (data should never be deleted).
* Solana’s dependency on a BigTable for Archive nodes exposes the network to vendor lock-in and introduces centralization of storage of the complete transaction history on a propitiatory service of a single cloud provider.

#### Proposed Solution
1. Replace the current [gRPC-based integration with CGP BigTable](https://github.com/solana-labs/solana/tree/master/storage-bigtable) with more generic interface based on [ODBC standard](https://cloud.google.com/bigquery/docs/reference/odbc-jdbc-drivers) to allow community members to choose other database/warehouse solutions for storing Solana Long term History data.
2. Provide full Solana transaction history data set for rapid data warehouse initialization in a more commonly used compressed data format like Apache Avro or Apache Parquet.
3. For Solana Foundation to explore cost-effective ways of sharing data with community members with other cloud providers ([current the design is very GCP-specific](https://github.com/solana-labs/solana-bigtable#import-solanas-bigtable-instance))

**Comment by linuskendall** [comment]
@frbrkoala Triton along with a few others have a shared slack space where we're discussing a replacement. If you e-mail me lk@triton.one with a little introduction I can add you to it.

**Comment by frbrkoala** [comment]
Hi Linus. Thank you for your comment. Sent you e-mail from my work address. Will be happy to join the conversation.
