### ISSUE TITLE
Not to load builtin programs and their accounts into memory

### ISSUE THREAD

**Issue by taozhu-chicago** [solana-labs/solana#28864]
#### Problem

Builtin programs have their accounts that contain their name, and are stored in AccountsDB to make sure the owner field is `native_loader`. Builtin programs are loaded during transaction loading only to resolve the executable chain. By loading these program into memory, they unnecessarily consume transaction's account data size limit. 

#### Proposed Solution
- not to load builtin programs during transaction loading.

**Comment by taozhu-chicago** [comment]
tag @jstarry @Lichtso @brooksprumo @sakridge

**Comment by Lichtso** [comment]
This is implicitly a part of #34057.
