### ISSUE TITLE
Geyser interface seems to not notify slots / block metadata on startup correctly

### ISSUE THREAD

**Issue by linuskendall** [solana-labs/solana#28871]
#### Problem

We have been observing that the Geyser interface does not report metadata and slot notifications during start up.  In particular, it looks like there is about 100-150 slot gap where we are not receiving slot updates or block metadata updates but we _are_ getting account updates.

Here's an example slot for which no slot or block metadata update was sent (the `geyser_pg::postgres` logs the messages received via geyser - in this case only a Account Write was notified for slot 191209332 but no slot or block meta update):

```
Nov 15 17:39:47 pit30 solana-rpc.sh[29611]: [2022-11-15T17:39:47.340803227Z INFO  solana_runtime::accounts_db] calculate_accounts_hash_without_index: slot (exclusive): 161209332 (d81b6NdHsX8RAGN9RKN8iXqgqQa6VGku3cjRWMe4S7k, 533683442109160944)
Nov 15 17:39:49 pit30 solana-rpc.sh[29611]: [2022-11-15T17:39:49.234396666Z DEBUG geyser_pg::postgres] Message: Account(false 161209332 SysvarS1otHashes111111111111111111111111111 500651326888)
Nov 15 17:39:49 pit30 solana-rpc.sh[29611]: [2022-11-15T17:39:49.249386841Z INFO  solana_metrics::metrics] datapoint: bank-timestamp-correction slot=161209332i from_genesis=1648852672i corrected=1668533405i ancestor_timestamp=1668533404i
Nov 15 17:39:49 pit30 solana-rpc.sh[29611]: [2022-11-15T17:39:49.249520276Z INFO  solana_metrics::metrics] datapoint: bank-new_from_parent-heights slot=161209332i block_height=145799501i parent_slot=161209331i bank_rc_creation_us=2i total_elapsed_us=15296i status_cache_rc_us=0i fee_components_us=2i blockhash_queue_us=2i stakes_cache_us=1i epoch_stakes_time_us=0i builtin_programs_us=0i rewards_pool_pubkeys_us=0i cached_executors_us=0i transaction_debug_keys_us=0i transaction_log_collector_config_us=0i feature_set_us=0i ancestors_us=2i update_epoch_us=0i update_sysvars_us=15164i fill_sysvar_cache_us=111i
Nov 15 17:39:49 pit30 solana-rpc.sh[29611]: [2022-11-15T17:39:49.601108319Z WARN  solana_runtime::bank] bank frozen: 161209332 hash: DCo7jzkUQcTM1F2GqCsuRHcs1WhwfVkB7qdRtDYGgzg4 accounts_delta: 2mM3CXE9pugz8BxjcQ81piptxoNgTR1WyQu2yC28frQ7 signature_count: 4282 last_blockhash: BWbHSVY4x1zztt9K1MRExH8Ez1ENixx1d7HotcUT3wAv capitalization: 533683442098270030
Nov 15 17:39:49 pit30 solana-rpc.sh[29611]: [2022-11-15T17:39:49.601137324Z INFO  solana_runtime::bank] accounts hash slot: 161209332 stats: BankHashStats { num_updated_accounts: 8828, num_removed_accounts: 16, num_lamports_stored: 3287785262901409, total_data_len: 33729863, num_executable_accounts: 0 }
Nov 15 17:39:49 pit30 solana-rpc.sh[29611]: [2022-11-15T17:39:49.601315585Z INFO  solana_metrics::metrics] datapoint: bank-forks_set_root elapsed_ms=0i slot=161209332i total_parent_banks=2i total_banks=1i total_squash_cache_ms=0i total_squash_accounts_ms=0i total_squash_accounts_index_ms=0i total_squash_accounts_cache_ms=0i total_squash_accounts_store_ms=0i total_snapshot_ms=0i tx_count=2787i prune_non_rooted_ms=0i drop_parent_banks_ms=0i prune_slots_ms=0i prune_remove_ms=0i dropped_banks_len=1i accounts_data_len=75179499432i
Nov 15 17:39:49 pit30 solana-rpc.sh[29611]: [2022-11-15T17:39:49.602506031Z INFO  solana_metrics::metrics] datapoint: bank-new_from_parent-heights slot=161209333i block_height=145799502i parent_slot=161209332i bank_rc_creation_us=3i total_elapsed_us=1162i status_cache_rc_us=0i fee_components_us=1i blockhash_queue_us=7i stakes_cache_us=1i epoch_stakes_time_us=0i builtin_programs_us=0i rewards_pool_pubkeys_us=0i cached_executors_us=2i transaction_debug_keys_us=0i transaction_log_collector_config_us=0i feature_set_us=0i ancestors_us=1i update_epoch_us=0i update_sysvars_us=1041i fill_sysvar_cache_us=91i
Nov 15 17:39:49 pit30 solana-rpc.sh[29611]: [2022-11-15T17:39:49.602511381Z INFO  solana_metrics::metrics] datapoint: bank-executor-cache-stats slot=161209332i hits=1390i misses=112i evictions=0i insertions=44i replacements=5i one_hit_wonders=5i
```

This only happens at start up of the node, when it is processing the snapshot and starting to catch up. After start up notifications of slot/block arrives as expected.

Here's an example:

- On start up, the first account write we received was at slot  160979363, this account write had  is_startup=true
- Then we received some 290M account_writes with same slot (160979363)
- The we get the 'end of startup'/startup complete message from geyser
- Then we received account_writes for slots 160979364....160979513 with is_startup=False
- Then we received slot processed notification for 160979513. Then, we received Confirmed slot status updates for slots 160979478...160979512. We do not receive block meta data or Rooted slot notification for these slots (only confirmed afaict).
- Finally,  we received Processed, Confirmed, Rooted for slot 160979513+ (so after 160979513 it all seems normal)

This leaves a gap between 160979363 ...  160979512 where we receive no Slot update or Block metadata update.

160979363 could be considered 'implicitly rooted' though it would still be good to receive slot updates.

Logs (>400 mb) can be sent on request.

#### Proposed Solution

The expected behaviour for me would be:

 1. Node starts from account snapshot at slot 160979363
 2. We receive block metadata and slot rooted status update for 160979363
 3. We receive all account_writes with is_startup=True at slot 160979363
 4. Then for each following slot 160979364.... we receive block metadata and at least one slot update (Rooted - but perhaps we could also receive Processed and Confirmed, I am assuming that the 'catchup'/'repair' process has some form of replay for this?)

**Comment by linuskendall** [comment]
This might be a duplicate of issue: https://github.com/solana-labs/solana/issues/27842

**Comment by jeff-delonge** [comment]
Did you get to the bottom of this?

I'm wondering if it's safe to assume that the account updates received after `notify_end_of_startup` but before the first `update_slot_status:Processed` notification are rooted.

If that's not a safe assumption, I believe there's no way to track the canonical state of the chain using only the data provided by the Geyser plugin interface.
