### ISSUE TITLE
[web3.js] Discrepancy between legacy Transaction API and new VersionedTransaction API

### ISSUE THREAD

**Issue by vovacodes** [solana-labs/solana#28900]
#### Problem

Version: `@solana/web3.js@1.66.2`

Combination of `VersionedTransaction.deserialize` and `TransactionMessage.decompile` produces different result from the legacy `Transaction.from` API when deserializing the same exact transaction.

Reproduction below (note the difference in the `isWritable` flag of the last `key`)
<img width="1140" alt="Screenshot 2022-11-20 at 23 31 41" src="https://user-images.githubusercontent.com/1524432/202930141-aa4e9f91-ce3e-44ab-87e0-f74a631958a5.png">

https://codesandbox.io/p/sandbox/funny-ride-1zmikd

While not 100% sure, I believe the legacy API produces the correct result and the new API is being wrong.

<details><summary>Serialized transaction</summary>

```
AQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAUHLl06XmBMUgEaGqFEDWXlrfuG9BxuqyiqilWnn+lBhO3ljbFniLvsim6dTEc5cyoTN2b5SA3mE/vy52heCKtBsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACK/25BBZJGavm0hr5XZ58vaLQc3cMeAgkndKj2Ni7RPDGxjMPhSKClKTgYkg7frtqzkeSTNsC3TbZp0QRwNCSwUhn4magdT/hPtZPS7fipCsGzqzQlj33yM+pQMCsb0uBX82VZkozhurrbZbi12eMbon+FOb7GAsyxrcKvufRnDqK6IjeTZQF0WwCoTTZmOO6HR7bBk26zWjZL9jPKBtpQEFBgAGAQMEAhHyI8aJUuHytv5AQg8AAAAAAA==
```
</details>

**Comment by steveluscher** [comment]
Thanks for this! Super helpful. I'll take a look in a bit.

**Comment by steveluscher** [comment]
Found the bug. I'm so grateful for your find!
