### ISSUE TITLE
Solana development

### ISSUE THREAD

**Issue by mottaghipour** [solana-labs/solana#28947]
I am a new developer in blockchain and I know programming and other concepts of blockchain. I want to know how to learn Solana architecture and how to contribute to this project? Do you have a roadmap?

**Comment by amorriscode** [comment]
@mottaghipour there are a ton of great resources provided by Solana: https://solana.com/developers

**Comment by steveluscher** [comment]
The Solana Discord is the right place to ask questions like this: https://solana.com/discord
