### ISSUE TITLE
Admin RPC service --> solana-rpc

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#28967]
#### Problem

It's easy to miss the Admin RPC service tucked away in `/validator`

#### Proposed Solution
Move it to the `solana-rpc` crate

**Comment by CriesofCarrots** [comment]
Unfortunately, it's not a straight drag-and-drop, as `admin_rpc_service.rs` depends on `solana-core`, which is downstream of `solana-rpc`

**Comment by cavemanloverboy** [comment]
definitely easy to miss. Also, there is no example usage

**Comment by CriesofCarrots** [comment]
Probably the best we could do here is add a `solana-admin-rpc` crate, which seems generally not worth it.
