### ISSUE TITLE
Reconsider UnprocessedPacketBatches Design

### ISSUE THREAD

**Issue by apfitzge** [solana-labs/solana#28985]
#### Problem
Current `UnprocessedPacketBatches` stores a priority queue of the original packets, as well as a map from message hash to `DeserializedPacket`. Design is inconvenient for use, has led to bugs such as #28978 

#### Proposed Solution
Discuss alternatives here

**Comment by apfitzge** [comment]
Tagging @taozhu-chicago

**Comment by apfitzge** [comment]
Some initial thoughts:
1. Remove the message hash map, and have the priority-queue store `DeserializedPacket`s directly.
2. 1 + store SanitizedTransactions in priority queue, a struct wrapping `(DeserializedPacket, Arc<SanitizedTransaction>)`

Map from message hash to deserialized packet does not seem necessary, as duplicates are already prevented in the deduper.
If we store sanitized transactions directly and at deserialization time, then we don't have to re-sanitize them in the case of retryable errors, would also make the `should_process` for MI simpler

**Comment by taozhu-chicago** [comment]
Here is another proposal to refactor banking_stage buffer: #28577

**Comment by apfitzge** [comment]
Another buffer idea was included in: #26362 (global priority-queue + priority sorted account queues)

account specific priority queues enable blocking by the lowest-priority conflicting tx.
