### ISSUE TITLE
web3.js: Add `transactionDetails` config to `getBlock`

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana#28999]
#### Problem

This code throws:

```ts
await connection.getBlock(164000050, {
  maxSupportedTransactionVersion: 0,
  transactionDetails: 'none'
});
```

#### Proposed Solution

Implement the missing config.

**Comment by ProfMoo** [comment]
@steveluscher Just pulled in the new version `1.68.0` and it works great :). Thanks!
