### ISSUE TITLE
Check crate owner

### ISSUE THREAD

**Issue by yihau** [solana-labs/solana#29002]
#### Problem

https://discord.com/channels/428295358100013066/560503042458517505/1047589288449151008

#### Proposed Solution

create a GA for checking all crates owner.

**Comment by yihau** [comment]
cc @joeaba

**Comment by t-nelson** [comment]
bonus points for a new script that takes the new crate name, generates a tempdir with the minimum viable `Cargo.toml`,makes the dummy publication and cleans up after itself
