### ISSUE TITLE
Change snapshot parameters through admin RPC 

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#29046]
#### Problem

Would it be possible to make the validator snapshot parameters adjustable through the admin interface of a running validator? (--no-incremental-snapshots, --full-snapshot-interval-slots, --incremental-snapshot-interval-slots, --snapshots <DIR>)

#### Proposed Solution

Add options through admin RPC

**Comment by brianlong** [comment]
Thanks. This will help us in cases where we need to experiment with parameters or shut off snapshots while investigating a problem.
