### ISSUE TITLE
testnet version info is not updated in "solana validators"

### ISSUE THREAD

**Issue by SlavaMo** [solana-labs/solana#29069]
#### Problem
My validator is still seen as version 1.14.7 in `solana validators`.  It was updated to latest 1.14.19 as soon as it was released. Restart does not help.

Testnet pubkey: `AEPNDgaApdcfZEZpww458Az9i2NZrwxsVCdiUih4EaRh`

```
$ solana validators | grep AEPNDgaApdcfZEZpww458Az9i2NZrwxsVCdiUih4EaRh
⚠️ AEPNDgaApdcfZEZpww458Az9i2NZrwxsVCdiUih4EaRh  DPDfFstkJRVFzU1u8s9GsCvxDNJbC1o6djJtRBJqn9V4   10%  165135787        165135750          -       13099   1.14.7       125.775082787 SOL (0.00%)
$ solana --version
solana-cli 1.14.9 (src:af329cf4; feat:3036606309)

```

Validator is voting successfuly, running without problems, just version info in rpc is not updated. For example, when i stop it - it becomes delinquent. When i restart it - it becomes online again. removed database fully, downloaded new snapshot, checked config file for unneeded flags from network restart. Nothing helps to update version (and i lost foundation stake in TdS because of this)

#### Proposed Solution
i do not know what to do

**Comment by linuskendall** [comment]
Have you checked that the time is set correctly on your node? Check with ntp/chrony that you're in sync. Have seen this issue with validators that have more than a few seconds lag in time sync.

**Comment by SlavaMo** [comment]
Thank you @linuskendall 
That helped!
