### ISSUE TITLE
Change `--vote-account` via admin socket/rpc

### ISSUE THREAD

**Issue by linuskendall** [solana-labs/solana#29066]
#### Problem

For failover, we can already change the node identity on runtime which is all good. However, if you have more than one voting validator, it would be helpful to be able to change not just the node identity / authorized voter via command line but also the `vote-account`. 

This would greatly help failover and we could for example automate node upgrades by having a single spare node which we update the node identity of / vote account of while we're powering down validator 1 and once validator 1 is done, we could move to another validator we manage and do the same thing. 

#### Proposed Solution

Add a command to the admin socket that would allow change the vote account. If it could override the `--no-voting` flag too that would be great, but it is not required. Rather just let the node be started up with one vote account but then later updated with another.

**Comment by mvines** [comment]
fwiw, I investigated changing the vote account dynamically when I added support for dynamic identity accounts. The vote account is much more sticky in the current implementation. So while I recognize the attraction with such a feature, the plumbing work to enable it will require some dedication.
