### ISSUE TITLE
Re-enable some sort of stalebot, to close stale PRs, if not also stale issues

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana#29093]
#### Problem

Often, PRs and issues get left open because someone:

* …is waiting for feedback from the author
* …has requested changes

A side effect of languishing PRs/issues is that they give the _appearance_ of something being worked on when it's not, which can dissuade other contributors from jumping in.

#### Proposed Solution

* Have a bot close stale PRs, and possible also issues
* Create a tag you can add to PRs/issues to exempt them from being closed
* Make the bot as unobtrusive as possible

**Comment by steveluscher** [comment]
This seems rather promising, in so far as it's highly configurable (assignee exemptions, separate thresholds for PRs and issues, cap on operations-per-run, etc.)

https://github.com/marketplace/actions/close-stale-issues

**Comment by joeaba** [comment]
@yihau , I think you can help here, this one seems promising and should be easy to implement.
Check the discussion here:
https://discord.com/channels/428295358100013066/560503042458517505/1049470177605062686
