### ISSUE TITLE
multinode-demo has an unmet dependency on solana-keygen

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#2910]
#### Problem

CI currently builds the world which covers up missing inter-package dependencies.  multi-node demo has a dependency on solana-keygen but is not explicitly requiring solana-keygen to be built.

While running `ci/localnet-sanity.sh`:
```
++solana-keygen -o /mnt/buildkite-agent/builds/arthur-poe-1/solana-labs/solana/config-local/mint-id.json
multinode-demo/setup.sh: line 87: solana-keygen: command not found
```

#### Proposed Solution

multinode-demo should ensure its dependencies are built

**Comment by mvines** [comment]
@jackcmay, Can you please provide updated/improved STR.  I don't get the described error when I run `ci/localnet-sanity.sh`

**Comment by mvines** [comment]
Can't reproduce
