### ISSUE TITLE
Unmet dependencies in the tree are forcing CI to build the world

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#2911]
#### Problem

CI builds the world when testing the workspace root.  Instead, it should be building and testing just itself and what it needs.

This PR is a band-aid and should be reverted: https://github.com/solana-labs/solana/pull/2896

The reason it persists is there are unmet dependencies in the tree that can be exposed if the PR is reverted.  (one example is https://github.com/solana-labs/solana/issues/2910).

#### Proposed Solution

Revert the mentioned PR and track down all failures.  Also, a re-org to convert the Solana workspace to a virtual where the root does not have any sources.

**Comment by mvines** [comment]
>  Also, a re-org to convert the Solana workspace to a virtual where the root does not have any sources.

This part has been done.

**Comment by mvines** [comment]
I think we're good here now
