### ISSUE TITLE
Cannot do lamports transfer on empty accounts through a program

### ISSUE THREAD

**Issue by solwhitey** [solana-labs/solana#29122]
#### Problem

When transferring a small amount of SOL, like 0.0001 SOL, through a program to an empty account that is not a PDA, we get the error 'Transaction result in an account (12) without insufficient funds for rent'

As a temp fix, I need to fund the empty address with some SOL (I don't know the precise amount to send but it guess that I need to send more than the minimum rent exempt).

#### Proposed Solution

Remove this check when it's a transfer on a fresh account that is not a PDA, and that is not the signer.

**Comment by CriesofCarrots** [comment]
We don't plan to relax the rent-exempt requirement for any accounts, which is a protection against spam account creation. So I'm going to close this issue.

You can get the rent-exempt minimum for an account with no data (any account, PDA or not) with this cli command:
```
$ solana rent 0 -um
Rent per byte-year: 0.00000348 SOL
Rent per epoch: 0.000002439 SOL
Rent-exempt minimum: 0.00089088 SOL
```
So any SOL balance greater than 0.00089088 SOL will work.
