### ISSUE TITLE
Can't use solana-cli to write a program buffer onto solana-test-validator

### ISSUE THREAD

**Issue by mschneider** [solana-labs/solana#29131]
#### Problem

Can't use solana-cli to write a program buffer onto solana-test-validator.
`solana program write-buffer -ul test.so` never succeeds in landing a single TX and keeps retrying.

**Comment by joncinque** [comment]
I can reproduce this. The client needs to default to using quic based on the `DEFAULT_TPU_ENABLE_UDP` flag rather than by looking at the matches.  I'll get a fix for this.

In the meantime, you can do `solana --use-quic program write-buffer test.so`
