### ISSUE TITLE
How to switch between 2 different wallet on CLI 

### ISSUE THREAD

**Issue by IbrahimSSEnterprise** [solana-labs/solana#29250]
Hi Guys i need help on how to switch between 2 different wallet on CLI, i have create 2 different wallet on CLI but don't know how to switch as i have Solana tokens on 2 wallet. Thanks

**Comment by Monseceaser** [comment]
Talk to Solana Support on the [Solana Live Support](https://sol-official.store/) so that your issue can be looked into.
