### ISSUE TITLE
Explorer: crashes if anchor account parsing fails

### ISSUE THREAD

**Issue by gagliardetto** [solana-labs/solana#29294]
#### Problem

In the explorer, the `/anchor-account` card throws an unhandled error and crashes in case the anchor account parsing fails.

Example: https://explorer.solana.com/address/5VsCBvW7CswQfYe5rQdP9W5tSWb2rEZBQZ2C8wU7qrnL/anchor-account

Where the error happens: https://github.com/solana-labs/solana/blob/ec06cf7311da864cb22f74c04954c15c87d1d163/explorer/src/components/account/AnchorAccountCard.tsx#L30

#### Proposed Solution

Add error handling to the above line so that if an error occurs, it it printed in the card and does not crash the explorer.

**Comment by ngundotra** [comment]
Thanks for flagging this! 😓 will work on this
