### ISSUE TITLE
Clean up references to Rent in docs

### ISSUE THREAD

**Issue by brooksprumo** [solana-labs/solana#29302]
#### Problem

There are multiple references to rent in the docs, but some are out of date and other may be best to remove.

Original context:

        > Can you remove the old rent docs as well.

@aeyakovenko Which old rent docs are you referring to? I found a few that mention rent:

1. https://docs.solana.com/developing/programming-model/accounts#rent
2. https://docs.solana.com/developing/intro/rent
3. https://docs.solana.com/implemented-proposals/rent
4. https://docs.solana.com/implemented-proposals/ed_overview/ed_storage_rent_economics
5. https://docs.solana.com/developing/runtime-facilities/sysvars#rent

I assume we wouldn't want to remove the rent sysvar docs (5), nor the implemented rent proposal (3). The info in (1) and (2) have a lot of overlap, but still seem useful. And I don't know what's up with (4), it just looks like a duplicate of this file I'm modifying in this PR.

_Originally posted by @brooksprumo in https://github.com/solana-labs/solana/issues/29256#issuecomment-1352157735_

**Comment by nickfrosty** [comment]
There is also the page located at: https://docs.solana.com/storage_rent_economics

Realistically, until the proposals are moved out of the docs portion of the mono repo, those pages will likely stay there.

I am working on some docs restructuring that will fix/remove the duplicated pages and close this PR
