### ISSUE TITLE
Rust 1.65-1.66 comparability

### ISSUE THREAD

**Issue by depool-live** [solana-labs/solana#29354]
solana-validator version 1.14.9 - 1.14.11 crash, if binary build with rust version 1.65 - 1.66

kernel: [1730992.034891] solBstoreProc03[1563031]: segfault at 0 ip 000055c8f8142648 sp 00007ee318eba6f0 error 4 in solana-validator[55c8f67a1000+1a07000]
kernel: [1730992.034903] Code: 00 00 00 c0 81 e3 f0 00 00 00 4c 01 e3 48 8b 43 30 49 39 c6 0f 85 99 05 00 00 4c 89 e8 48 c1 e8 09 25 f8 ff 1f 00 48 03 43 38 <48> 8b 30 48 8b 44 24 28 64 48 2b 04 25 28 00 00 00 0f 85 cf 05 00

**Comment by steviez** [comment]
This could potentially be an interesting thing to investigate; however, we only claim to support the specified rust version for a given branch. You'll see [here](https://github.com/solana-labs/solana/blob/v1.14/ci/rust-version.sh#L21) that 1.60.0 is the pinned version on v1.14 branch.

While the [build instructions](https://github.com/solana-labs/solana/tree/master#3-build) do specify to use the [cargo script](https://github.com/solana-labs/solana/blob/master/cargo) (which will use the correct rust version for any given branch), habit may cause someone to invoke cargo directly and could lead to hitting this issue. FWIW, we are doing additional work to put up more guardrails (ie we just recently added a toolchain file).

In any case to get you not segfaulting, use 1.60.0 for v1.14 branch.

**Comment by depool-live** [comment]
Rust 1.64 build good binary too
