### ISSUE TITLE
Explorer: reenable getTransaction for multiple transactions at once

### ISSUE THREAD

**Issue by iraykhel** [solana-labs/solana#29396]
I have been using explorer.solana.com's API as a source of Solana transaction data for my website (defitaxes.us, free tax prep for blockchain transactions), but today discovered that the JSON call to https://explorer-api.mainnet-beta.solana.com/ with method getTransaction no longer supports providing multiple transaction signatures in the same call (responds with 429, "Too many requests for a specific RPC call, contact your app developer or support@rpcpool.com." if more than 1 signature is provided). Would it be possible to reenable this method to allow for multiple signatures provided at once? I have tried every single available Solana transaction data provider on the market, and explorer.solana.com provides the best quality solana API data, which is important for tax prep. I will not be able to use it for data if I can only get 1 tx/request.

**Comment by iraykhel** [comment]
Same for getAccountInfo :(

**Comment by ngundotra** [comment]
Please try a different RPC provider: https://solana.com/rpc
