### ISSUE TITLE
[1.13.6] Test Validator Fails to Transact

### ISSUE THREAD

**Issue by Nader-Sl** [solana-labs/solana#29491]
**Solana Version:** [1.13.6 ](https://github.com/solana-labs/solana/tree/ab8180121d35f47895def5cb6a68ad3109d91b6c)
**Solana CLI** : 1.13.5+ (including latest 1.14.x)
**Issue**:
Solana CLI airdrops and transfers fail after the timeout with this message : 
`Error: unable to confirm the transaction. This can happen in situations such as transaction expiration and insufficient fee-payer funds`

Validator Log Repeats:
```
[solana_send_transaction_service::send_transaction_service] Retrying transaction: ZNFaSAHKtX1jR9Ts33yxnM9aLSxkDegerVhc7inRxhXBkTzFDpnvx6k6QxgQtrmqnh2V9mKNn4ZRnEYDyMwrdiY
```

**Comment by OhFlohre** [comment]
Got the same issue on 1.14.15. How did u manage to resolve it @Nader-Sl ?
