### ISSUE TITLE
Block compute capacity filling up due to lack of fees per compute units

### ISSUE THREAD

**Issue by anoushk1234** [solana-labs/solana#29492]
#### Problem
- Blocks are hitting their compute unit limit of 48 million very frequently, as you can see in the graph below. Most of these are transactions that don't require the extra compute like mev trades.
<img src="https://user-images.githubusercontent.com/32778608/210402161-aa47c282-0144-4276-a8b0-b4e2f5f6ad81.png" width="400">
The problem was first reported by @overclock-validator 

#### Proposed Solution
- Charge a fee per compute unit so that network doesn't get burdened with transactions that take up all the compute. This can either be a fixed fee, for example 5*10^-6 sol/(vote cu) per CU

Tagging @taozhu-chicago 🙏

**Comment by mschneider** [comment]
Blocks have been hitting their CU limit for as long as it is tracked. ComputeBudget allows opt-in prioritization, why should the network enforce it? Users that are not happy with QoS can upgrade anytime.

**Comment by taozhu-chicago** [comment]
Block being filled up isn't necessarily a bad thing. Agree with @mschneider that Prioritization fee gives users chance to land transactions even block is filling up. 

[FeeStructure.compute_fee_bins](https://github.com/solana-labs/solana/blob/master/sdk/src/fee.rs#L21-L22) would charge lamports per CUs if the economics were figured out. Currently default is used which does not charge for CU. So I am curious your thoughts behind `5*10^-6 sol/(vote cu) per CU`, may help to define `compute_fee_bins`

**Comment by lurais** [comment]
@anoushk1234 you mean that the transactions like mev trades don't use the extra compute so the block is filled with them? That will reduce the normal transactions? Is that right?
