### ISSUE TITLE
Consensus (bank hash) mismatch between v1.13.5 and v1.14.11/master (mainnet)

### ISSUE THREAD

**Issue by steviez** [solana-labs/solana#29576]
#### Problem

v1.14 exhibited a consensus divergence from mainnet which was predominately running v1.13.5 at the time. [The team](https://discord.com/channels/428295358100013066/1061497492899897384) quickly figured out that the divergence started in slot `171368705` per the below warning in logs.
```
Cluster duplicate confirmed slot 171368705 with hash FnqP3rQAnKW9CLSoe6kgxexdcVCQmTz8cWpHpjNQW6as,
but our version has hash CvjTyiBwi7CPsxREiYNzbQXYD69KjadDKWn4LcEmhFqD
```

Here is the correct bank that the cluster rooted, reproduced with v1.13.5:
```
bank frozen: 171368705
hash: FnqP3rQAnKW9CLSoe6kgxexdcVCQmTz8cWpHpjNQW6as
accounts_delta: 37rBeBLPqgfCF9pSA8L6L3nxvX9mXMUJS1p668c6S3wU
signature_count: 1915
last_blockhash: EjGTZiLw8FLGnEbDPBAP4CDrFoxqHN5fQVnQWVBdPFXV
capitalization: 538008947565764051

accounts hash slot: 171368705 stats: BankHashStats {
    num_updated_accounts: 4978,
    num_removed_accounts: 43,
    num_lamports_stored: 2366998472543196,
    total_data_len: 39150361,
    num_executable_accounts: 0
}
```
vs the incorrect bank that the v1.14 nodes produced; this specifically reproduced with v1.14.11:
```
bank frozen: 171368705
hash: CvjTyiBwi7CPsxREiYNzbQXYD69KjadDKWn4LcEmhFqD
accounts_delta: dcZV7vSTSZDMgvwugPTffP6KjHSYEKsbVVKEzuMg9wa
signature_count: 1915
last_blockhash: EjGTZiLw8FLGnEbDPBAP4CDrFoxqHN5fQVnQWVBdPFXV
capitalization: 538008947565764051

accounts hash slot: 171368705 stats: BankHashStats {
    num_updated_accounts: 4980,
    num_removed_accounts: 43,
    num_lamports_stored: 2367006605811276,
    total_data_len: 40319042,
    num_executable_accounts: 0
}
```
We clearly see that v1.14 incorrectly updated two additional accounts. I dumped the updated accounts for each version and diff'd the lists; the additional accounts that were updated in v1.14 show that the following transaction is the offender:
[4wu8LzkuxD8amEAe2Pykqw...](https://explorer.solana.com/tx/4wu8LzkuxD8amEAe2PykqwVFN3Uew6tar7Qkupk2w54RME2JS3xzGnsQpmgdvKR98FBinq9jAF5H1zEuMuCHZyQK)

The above link on explorer shows the following logs:
```
> Program logged: "VERSION:"3.1.0""
> Program logged: "GOVERNANCE-INSTRUCTION: CreateProgramGovernance { config: GovernanceConfig { community_vote_threshold: YesVotePercentage(60), min_community_weight_to_create_proposal: 18446744073709551615, min_transaction_hold_up_time: 0, voting_base_time: 259200, community_vote_tipping: Strict, council_vote_threshold: YesVotePercentage(60), council_veto_vote_threshold: YesVotePercentage(60), min_council_weight_to_create_proposal: 1, council_vote_tipping: Strict, community_veto_vote_threshold: Disabled, voting_cool_off_time: 0, deposit_exempt_proposal_count: 10 }, transfer_upgrade_authority: true }"
> Program invoked: System Program
  > Program returned success
> Program consumed: 38568 of 200000 compute units
> Program returned error: "Unaligned pointer"
> Program returned error: "Program failed to complete"
```
As expected, my v1.13 `solana-ledger-tool` logs show the same error getting hit:
```
Program GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw invoke [1]
Program log: VERSION:"3.1.0"
Program log: GOVERNANCE-INSTRUCTION: CreateProgramGovernance { config: GovernanceConfig { community_vote_threshold: YesVotePercentage(60), min_community_weight_to_create_proposal: 18446744073709551615, min_transaction_hold_up_time: 0, voting_base_time: 259200, community_vote_tipping: Strict, council_vote_threshold: YesVotePercentage(60), council_veto_vote_threshold: YesVotePercentage(60), min_council_weight_to_create_proposal: 1, council_vote_tipping: Strict, community_veto_vote_threshold: Disabled, voting_cool_off_time: 0, deposit_exempt_proposal_count: 10 }, transfer_upgrade_authority: true }
Program 11111111111111111111111111111111 invoke [2]
Program 11111111111111111111111111111111 success
Program GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw consumed 38568 of 200000 compute units
Program failed to complete: Unaligned pointer
Program GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw failed: Program failed to complete
```
However, v1.14 `solana-ledger-tool` logs do not show the same failure; rather, the tx succeeded with v1.14:
```
Program GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw invoke [1]
Program GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw consumed 39102 of 200000 compute units
Program GovER5Lthms3bLBqWub97yVrMmEogzX7xNjdXpPPCVZw success
```

#### Proposed Solution
Debug further to figure out what caused the change of behavior, and then patch to allow compatibility between v1.13 and v1.14 branches

**Comment by steviez** [comment]
I took a look at the code; there is only file that raises this `UnalignedPointer` error:
v1.13 : https://github.com/solana-labs/solana/blob/v1.13/programs/bpf_loader/src/syscalls.rs
v1.14: https://github.com/solana-labs/solana/blob/v1.14/programs/bpf_loader/src/syscalls/mod.rs

I noticed the logic to gate whether we perform the check is slightly different between the two. Here is v1.13 code:
https://github.com/solana-labs/solana/blob/ab8180121d35f47895def5cb6a68ad3109d91b6c/programs/bpf_loader/src/syscalls.rs#L614-L618
vs v1.14 code
https://github.com/solana-labs/solana/blob/b8f2a9d865dae7659238992b40a56f2c9b55cf32/programs/bpf_loader/src/syscalls/mod.rs#L454-L456

There are two instances of this logic in each file, but I just included one per version above. Seeing the change of behavior for checking loader_id vs. the value of `check_aligned`, I added the following snippet as a quick and dirty test in each of the two location where `return Err(SyscallError::UnalignedPointer.into());` appears in v1.14 file:
```rust
    let rhs = (host_addr as *mut T as usize).wrapping_rem(align_of::<T>()) != 0;
    if check_aligned && rhs {
        return Err(SyscallError::UnalignedPointer.into());
    }

    if !check_aligned {
        panic!("check_aligned = {}, rhs = {}", check_aligned, rhs);
    }
```
Sure enough, re-running I saw the following:
```
thread 'solBstoreProc05' panicked at 'check_aligned = false, rhs = false', programs/bpf_loader/src/syscalls/mod.rs:464:9
```
So, it would seem that we are passing the `check_aligned` flag in as `false`, which results in us NOT checking the alignment since the if statement short circuits.

**Comment by alessandrod** [comment]
> It seems as if `check_aligned` should be `true`, or else we'll never perform the check

Did it panic while executing the diverging instruction or another instruction (maybe in another transaction)?. Because the if as you had it above would panic on every execution of the `bpf_loader_deprecated` loader

**Comment by steviez** [comment]
> Did it panic while executing the diverging instruction or another instruction (maybe in another transaction)?. Because the if as you had it above would panic on every execution of the bpf_loader_deprecated loader

Good point, it was the end of a late night and I didn't fully think through the considerations of that hacked check I added. I'll strike my comment out above; luckily there was still enough for Lichtso to go off of to find actual root cause.

**Comment by alessandrod** [comment]
> Good point, it was the end of a late night and I didn't fully think through the considerations of that hacked check I added. I'll strike my comment out above; luckily there was still enough for Lichtso to go off of to find actual root cause.

Nah great write up it was super helpful. I've been looking more into this and I think the cuprit is this line in the original patch:

https://github.com/solana-labs/solana/pull/26737/files#diff-0192bd50fa609efedbf530b1c80796aea767fc384a1505345c6b4ef78a496b9bL869

Before the patch we used to check for pointer alignment at CPI entry. After the patch we check for pointer alignment at CPI exit **but only if the account length has changed**. If the account changes but not its length, we don't detect unalignment and the instruction succeeds.

**Comment by alessandrod** [comment]
Also just for the record before I move to other things, I double checked and in the runtime and program sdk we never create unaligned pointers to that particular field (so, I don't think we have another bug somewhere else). You have to intentionally go through some hoops to make it so that that field is unaligned, and so... hello "security researcher"  watching this issue 👋
