### ISSUE TITLE
Devnet airdrop intermittently fails with "internal error"

### ISSUE THREAD

**Issue by sohrab-** [solana-labs/solana#29574]
#### Problem

Airdrop functionality in devnet fails (intermittently) with the response "internal error".

I have replicated this on the main RPC and Trinton so far. Will need access to the RPC endpoints logs to see what's going on here.

Code example: https://codesandbox.io/p/sandbox/eloquent-morning-y9xshk

https://twitter.com/sohrabwashere/status/1611880162479734784

#### Proposed Solution

🤷

**Comment by CryptoManSam** [comment]
God I thought I was the only one. I can't find anything on this online that's helpful. 
As someone attempting to develop in the space for the first time, hitting a roadblock like this so early is very off-putting.
