### ISSUE TITLE
RPC write txs stopped working while read txs work

### ISSUE THREAD

**Issue by codemonkey6969** [solana-labs/solana#29691]
Randomly, all write txs on our rpc node stopped working but reads were working perfectly. This has happened for a 2nd time now so seems like a bug. Have logs for both times. 

Log first time: https://snapshots.nodemonkey.io/snapshots/validator_write.log
Log second time: https://snapshots.nodemonkey.io/snapshots/validator_write2.log

**Comment by steviez** [comment]
A few notes:
- For the distinction of reads v. writes, specific RPC calls would be helpful to try to qualify the workload your node(s) experienced
- Having a rough time for when the issue occurred is helpful. Ie absolute date/time in UTC
- Related to above, some of the logs you loaded up were pretty big (think I saw one at ~45 GB) ... this is a lot for someone to sift through if they're not exactly sure what/when they're looking for.
    - I didn't scan your full logs so maybe you already did this, but trimming the logs down to time range around incident make things a little less cumbersome
- Version / host_id (if submitting metrics) would be useful to as well

I recently saw another issue of someone having RPC issues (https://github.com/solana-labs/solana/issues/29902). They have already done some of the narrowing down, so if that seems like the same issue, I'm inclined to move conversation there to avoid split and/or duplicate conversations
