### ISSUE TITLE
CLI tools are incompetent

### ISSUE THREAD

**Issue by ctrlcctrlv** [solana-labs/solana#29751]
#### Problem
1.
    ```bash
    solana transaction-history $(solana address) --output json 2> /dev/null
    ```
    ```
    3pLFLC59T6AKAqT8DJr5wjrH1y7RQUcZNKpKahzuEQGnNL3WtLpe8P6Q4d6a9W6ijqynrCJW9eGEp5A5t1GMZttg
    1 transactions found
    ```
    
    [](https://github.com/solana-labs/solana/blob/55d743c49a9e2f3321fb86b6b35bc68b65a3c284/cli-output/src/display.rs#L191)https://github.com/solana-labs/solana/blob/55d743c49a9e2f3321fb86b6b35bc68b65a3c284/cli-output/src/display.rs#L191
2. `solana transfer` requires an undocumented """blockhash""" https://twitter.com/fr_brennan/status/1615588104479424512
#### Proposed Solution
rewrite them tbh

**Comment by CriesofCarrots** [comment]
PRs welcome

**Comment by ctrlcctrlv** [comment]
naturally :-)
