### ISSUE TITLE
Bugs in turbine docs

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#29766]
#### Problem

[Turbine docs](https://docs.solana.com/cluster/turbine-block-propagation) have typos and bugs.  Reported by researches looking at the code and documentation.

<img width="659" alt="Screen Shot 2023-01-18 at 1 45 41 PM" src="https://user-images.githubusercontent.com/1029046/213302017-80f7dbd1-c9b3-4659-af1c-161773d23acc.png">

#### Proposed Solution

fix them

tag @behzadnouri @jbiseda

**Comment by brennanwatt** [comment]
Here are the items I've spotted that need to be cleaned up (in order of appearance from top to bottom):

1. Note that we _possibly_ share shreds with neighbors. We will stop doing this once Redundant Turbine Path feature is enabled.
2. Layer 0 is actually a special case Root node. Layer 1 = neighborhood 0
3. Neighborhood assignment seed is derived from shred index + _type_
4. Include root in diagrams/explanations in Layer & Neighborhood structure sections
5. Mention or link to Redundant Turbine Path feature and how this impacts flows.
6. Typo: trails --> trials*
7. Shred group failure rate is actually computing the success rate. Add a 1 - to invert this
8. Trials number is wrong for 16:16 FEC example 64 --> 32*
9. Neighborhoods section should likely be moved under Layer and Neighborhood Structure section
