### ISSUE TITLE
api.mainnet-beta.solana.com returns invalid validator node version.

### ISSUE THREAD

**Issue by atomlab** [solana-labs/solana#29778]
#### Problem
`api.mainnet-beta.solana.com`  returns invalid data. Wrong validator node version.
My validator node - "1.13.6". Public api returns - "1.13.5"
I have faced the problem after upgrade from "1.13.5" to "1.13.6". This has never happened before.

**Get version from public node**
```
curl -s  https://api.mainnet-beta.solana.com  -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0", "id":1, "method":"getClusterNodes"}' | jq '.result[] | select(.pubkey == "EwUVzgSPe1zy2hfUGZxJAEP7Y1wheNgNsgratbzPELru") | .version'
```
result
```
"1.13.5"
```

**Get version from validator host**
1. get validator host
```
node_host=$(curl -s https://api.mainnet-beta.solana.com -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0", "id":1, "method":"getClusterNodes"}' | jq '.result[] | select(.pubkey == "EwUVzgSPe1zy2hfUGZxJAEP7Y1wheNgNsgratbzPELru")'| jq -r .rpc)
```

2. get the actual version
```
curl http://${node_host}  -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":1, "method":"getVersion"}'
```
output
```
{"jsonrpc":"2.0","result":{"feature-set":1775889670,"solana-core":"1.13.6"},"id":1}
```

#### Proposed Solution
I expect that `api.mainnet-beta.solana.com` returns valid validator node version.

**Comment by atomlab** [comment]
> You are probably running two nodes by accident with the same identity. one one 1.13.5, the other on 1.13.6

I have single server for mainnet.  If I run two nodes with the same identity key validator wouldn't work. It will delinquent. Validator works well last 7 days. Skip rate 0-7%. How could that be possible?

**Comment by im-0** [comment]
I checked this when @atomlab posted their question on Discord:

```
$ solana validators | grep EwUVzgSPe1zy2hfUGZxJAEP7Y1wheNgNsgratbzPELru
  EwUVzgSPe1zy2hfUGZxJAEP7Y1wheNgNsgratbzPELru  438C7o4cJrbchdmxEPvFgaE5g9DocWKeSc1k4E1aY7qw   10%  173290090 ( -1)  173290059 ( -1)   0.00%    45551   1.13.5    100893.213464691 SOL (0.03%)

$ solana gossip | grep EwUVzgSPe1zy2hfUGZxJAEP7Y1wheNgNsgratbzPELru
66.248.204.3    | EwUVzgSPe1zy2hfUGZxJAEP7Y1wheNgNsgratbzPELru | 8000   | 8003  | 66.248.204.3:8899     | 1.13.5  | 1365939126

$ curl http://66.248.204.3:8899 -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0","id":1, "method":"getVersion"}'
{"jsonrpc":"2.0","result":{"feature-set":1775889670,"solana-core":"1.13.6"},"id":1}
```

And this is still reproducible right now.

Is it even possible that running two validators with the same identity keypair result in inconsistent contact info in gossip: version from one instance but addresses from another one?

**Comment by im-0** [comment]
By the way... @atomlab, are you deliberately made RPC public or this was accidental? Enabling public RPC is not recommended if you do not want to run RPC node specifically. Especially for staked nodes. But this is not relevant to this issue.

**Comment by atomlab** [comment]
I have restarted `ntp` on my server. It helped! 

```
systemctl restart ntp
```
status
```
# ntpq -p
     remote           refid      st t when poll reach   delay   offset  jitter
==============================================================================
 0.ubuntu.pool.n .POOL.          16 p    -   64    0    0.000   +0.000   0.000
 1.ubuntu.pool.n .POOL.          16 p    -   64    0    0.000   +0.000   0.000
 2.ubuntu.pool.n .POOL.          16 p    -   64    0    0.000   +0.000   0.000
 3.ubuntu.pool.n .POOL.          16 p    -   64    0    0.000   +0.000   0.000
 ntp.ubuntu.com  .POOL.          16 p    -   64    0    0.000   +0.000   0.000
 ```
 
 After 20 minutes  release has updated. 
 
 ```
 curl -s  https://api.mainnet-beta.solana.com  -X POST -H "Content-Type: application/json" -d '{"jsonrpc":"2.0", "id":1, "method":"getClusterNodes"}' | jq '.result[] | select(.pubkey == "EwUVzgSPe1zy2hfUGZxJAEP7Y1wheNgNsgratbzPELru") | .version'
```
result
```
"1.13.6"
```

**Comment by mvines** [comment]
oh I see. The time on your server was wrong, so the gossip messages being sent from your 1.13.6 instance were being discarded by the rest of the network and thus the old 1.13.5 data was persisting in gossip
