### ISSUE TITLE
Vote program doesn’t check that slot height matches transaction lastid

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#2977]
#### Problem

Vote program doesn’t check that slot height matches transaction lastid.   This would allow any slots to be voted on at any time. 

#### Proposed Solution

Runtime should provide lastid slot height, and current slot height, as well as the Hash.  Vote program should verify the hash is valid and matches the voted slot.

Tag: @carllin @garious

**Comment by garious** [comment]
Good point!  How about we start a "Program entrypoint overhaul" Github project? @jackcmay, want to own that one? We're starting to build a good-sized queue of issues that depend on more Transaction data getting into `solana_entrypoint!`.

**Comment by jackcmay** [comment]
New Github project?  What did you have in mind?

**Comment by garious** [comment]
Not a new repo, just a "project" instead of an issue.  https://github.com/solana-labs/solana/projects

**Comment by rob-solana** [comment]
is this obsoleted by syscall accounts?

**Comment by aeyakovenko** [comment]
@rob-solana we need something to track that votes for the wrong slot height are not entered.

**Comment by rob-solana** [comment]
@aeyakovenko can you give me an example of a vote for the wrong slot height?  we're checking a vote's slot and hash against a list of valid slot+hash tuples supplied by the bank, now

**Comment by aeyakovenko** [comment]
@rob-solana sweet, we can close it.
