### ISSUE TITLE
Add VersionedTransaction support to BanksClient

### ISSUE THREAD

**Issue by kevinheavey** [solana-labs/solana#29780]
#### Problem

`BanksClient` in `solana_program_test` doesn't support `VersionedTransaction`:

```
pub fn send_transaction(
    &mut self,
    transaction: Transaction
)
```

#### Proposed Solution

I suppose imitating `solana_client` would make sense:

```
fn send_transaction(
    &mut self,
    transaction: &impl SerializableTransaction
)
```

**Comment by gnapoli23** [comment]
@kevinheavey If ok with you I can take a look at it.

**Comment by kevinheavey** [comment]
Fine by me!

**Comment by gnapoli23** [comment]
@kevinheavey Mmm it was actually supported in this commit https://github.com/solana-labs/solana/commit/737160872241516f1d6a1dd52c37d38e8de3fd4a
```
pub fn send_transaction(
    &mut self,
    transaction: impl Into<VersionedTransaction>,
) 
```

**Comment by kevinheavey** [comment]
Ah
