### ISSUE TITLE
Debug flaky test test_duplicate_shreds_broadcast_leader from local-cluster-slow-1

### ISSUE THREAD

**Issue by wen-coding** [solana-labs/solana#29792]
#### Problem
https://buildkite.com/solana-labs/solana/builds/88498#0185cb90-96c9-4e38-b318-a850bd5e40fe

It fails at this unwrap so far
https://github.com/solana-labs/solana/blob/0a0c532c86456bbd1190f383f8787a66d6009b2d/core/src/heaviest_subtree_fork_choice.rs#L589

**Comment by wen-coding** [comment]
Checking further, the sequence is like this:
1. Some tree got split off from fork_infos, the split off node will have a parent which is invalid (the parent is actually in the original tree, not in this tree).
2. We do a merge of another tree with this split off tree, the tree being merged is actually the descendant of the split off tree
3. As part of the merge, the stake in the merged tree need to be propagated to the split off tree, it follows the parent chain and finds this non-existent parent in the split off node
4. the thread panicks

**Comment by steviez** [comment]
I think there may be another issue with this test. Someone from community submitted a PR, and it failed on this same test `test test_duplicate_shreds_broadcast_leader`; I'm not sure if they had rebased on top of #29770, but in any case, the failure was different ([link here](https://buildkite.com/solana-labs/solana/builds/88880#0185ea17-6827-4d97-bd78-e26b1e017d69)):

```
thread 'main' panicked at 'assertion failed: loop_start.elapsed() < loop_timeout', local-cluster/src/cluster_tests.rs:324:9

stack backtrace:
   0: rust_begin_unwind
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
   2: core::panicking::panic
             at /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:115:5
   3: solana_local_cluster::cluster_tests::check_for_new_roots
   4: solana_local_cluster::local_cluster::LocalCluster::check_for_new_roots
   5: core::ops::function::FnOnce::call_once
   6: serial_test::serial_code_lock::local_serial_core
```
The buildkite failure that was linked in the issue also shows this panic; however, the job I linked didn't exhibit the `thread solRepairSvc panicked at 'called Option::unwrap() on a None value` panic.

**Comment by AshwinSekar** [comment]
This has been an issue for a while unfortunately with the slowness of this test. Created #29917 to investigate, can take a look when i have some cycles.
