### ISSUE TITLE
passing minContextSlot value in getSignaturesForAddress, but result doesn't change

### ISSUE THREAD

**Issue by AiltonSavio** [solana-labs/solana#29801]
Hello,

I'm using solana/web3.js library. When I try to filter the results on getSignaturesForAddress using minContextSlot passing a specific slot, it returns the same result as when I omit this option. I've tried using both Quicknode and Alchemy for the RPC connection. Here is the code:

`const signatures = await this.solanaConnection.getSignaturesForAddress(pubKey, { minContextSlot: fromSlot });`

**Comment by CriesofCarrots** [comment]
While I don't know the details of your queries, I think perhaps there is a misunderstanding about how the `minContextSlot` configuration works. It is not a filter for the returned signatures, but sets the slot that the node must have reached (at the specified commitment) to evaluate the request. This config is more relevant for some RPC endpoints than others.

Anyway, I confirmed that the `minContextSlot` is being respected for `getSignaturesForAddress` by the RPC server.
