### ISSUE TITLE
Possibility of Making a Data Science Program in Solana

### ISSUE THREAD

**Issue by Killpit** [solana-labs/solana#29871]
Is it possible to use Python libraries like NumPy, Pandas and scikit-learn for scientific calculations.

My proposed solution is to use Solana.Py and to allow the same use with Python libraries for data science such as NumPy, Pandas and scikit-learn.

**Comment by overclock-validator** [comment]
Hey this question isnt for the github. I'd check out the Lamport dao developer discord or the solana stack exchange. https://discord.gg/pHVuJX9y

**Comment by steviez** [comment]
Not exactly sure what your question was, but in any case, this repo is separate from [Solana.py](https://github.com/michaelhly/solana-py) so closing this issue.
