### ISSUE TITLE
Make validators restartable

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#299]
- [x] Leader writes to a log file, all the validators rsync this file with --append
- [x] After validators boot up and run the log file through their banking stage, they need to sync any additional entries that were added since the log was synced. This should happen automatically as part of repairing the window. 
- [x] connect to network without needing leader's full config

**Comment by rob-solana** [comment]
why can validators assume that generators only append to genesis.log?
validator.sh doesn't use rsync --append, but should as part of this issue?

**Comment by garious** [comment]
Validators can assume the transaction log is append-only if the leader either:

1. Postpones writing to the log until after the election results are in
2. Never outputs invalid transactions

At the time of this writing, we're on path 2. There's an open ticket for path 1 assigned to the v0.8.0 milestone.

Correct, validator.sh currently doesn't use `rsync --append`. We believe that it should, but do whatever you think is best.

**Comment by garious** [comment]
For v0.7.0, we'll hold the leader role, so no concern of it inserting spam. If a validator spots an invalid transaction on the log, it's because there's a bug in either the leader or validator. I'm aware of one such bug. I'll buy you a beer if you can spot it. :)

**Comment by garious** [comment]
Two beers if you add the missing testcase to bank.rs (hint).

**Comment by aeyakovenko** [comment]
The sync should happen automatically as part of repairing the window.

**Comment by rob-solana** [comment]
left to do on this (I think):
1. a persistent ledger (not stdin+stdout), based on Entry height (aka blob index)
2. leader and validator support for repairing from the persistent ledger (i.e. an infinite window)

**Comment by rob-solana** [comment]
completed with #524
