### ISSUE TITLE
RPC Service Locked Up

### ISSUE THREAD

**Issue by buffalu** [solana-labs/solana#29902]
#### Problem
- RPC service locked up on several v1.14.13-jito RPC servers around 11:17PM CT time, Tuesday Jan 24
- Node continued to replay ontime. Pubsub + geyser continued to work.
- Likely to be batched getMultipleAccounts, getTokenAccountsByOwner

Likely deadlock in RPC Servers or getMA?

Relevant rpc cli args:
- --rpc-threads 8
- --account-index-exclude-key kinXdEcpDQeHPEuQnqmUgtYykqKGVFq6CeVX5iAHJq6
- --account-index-exclude-key TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA

#### Proposed Solution
Determine lockup cause and fix

**Comment by buffalu** [comment]
https://cdn.discordapp.com/attachments/837340113067049050/1067692312420945940/telegram-cloud-photo-size-1-5082650279769385563-y.jpg

https://cdn.discordapp.com/attachments/837340113067049050/1067695770360356924/Screen_Shot_2023-01-25_at_12.41.44_AM.png

**Comment by buffalu** [comment]
![Screen Shot 2023-01-25 at 10 05 34 AM](https://user-images.githubusercontent.com/85544055/214614054-0bdea82f-1c20-4115-853c-53bfa9e379fa.png)

non-potato picture

**Comment by steviez** [comment]
I'm not super dialed in on this one, but I think there has been some investigation / theory on potential culprit: https://github.com/solana-labs/solana/issues/24644

> RPC service locked up on several v1.14.13-jito RPC servers

Obligatory question comes to mind as to whether the stock software shows the issue. But, given the issue we have + some reports I've heard from others, this is seemingly not an issue that jito commits introduce.

**Comment by buffalu** [comment]
@mschneider might find this interesting

**Comment by mschneider** [comment]
So we observed some users of the mango rpc using massively batched gMA and gPA to avoid rate limits, we ended up blocking any form of batching involving these requests.

**Comment by mschneider** [comment]
If you were to direct request workload through a reverse proxy you might be able to create a log of the RPC combination that lead to the issue

**Comment by buffalu** [comment]
> Curious: did websocket / pubsub connections that were opened before still transmit data?

yes and geyser. Everything kept running except rpc. 

> If you were to direct request workload through a reverse proxy you might be able to create a log of the RPC method combination that lead to the issue

the chart I sent is from our proxy showing the rpc methods that caused it
