### ISSUE TITLE
`rpc_filter::MemCmp` irreconcilable deprecation warning

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#29920]
#### Problem

https://github.com/solana-labs/solana/blob/b4d1769688c8cffa65b9fccc5a5cfbcb97eda78a/rpc-client-api/src/filter.rs#L140-L144

the `encoding` field of `rpc_filter::Memcmp` was deprecated in v1.11.2. unfortunately, when using struct literal instantiation, removing `encoding` produces a missing field error.

see https://github.com/rust-lang/rust/issues/102777

#### Proposed Solution

???

deprecate all of the fields, suggest a constructor instead, remove `pub` markers in v2?

**Comment by t-nelson** [comment]
cc/ @CriesofCarrots

**Comment by CriesofCarrots** [comment]
> deprecate all of the fields, suggest a constructor instead, remove pub markers in v2?

Not a bad idea at all. I probably should have added a recommendation to use a constructor to the existing deprecation method.
