### ISSUE TITLE
ledger-tool fails to create snapshot from ledger with large number accounts  ~750M

### ISSUE THREAD

**Issue by HaoranYi** [solana-labs/solana#29934]
#### Problem

On kin-sim, the following snapshot generation command failed.

```
RUST_BACKTRACE=1 ./src/solana/target/release/solana-ledger-tool --ledger /home/sol/ledger/ create-snapshot 1103712 --remove-account capRxUrBjNkkCpjrJxPGfPaWijB7q3JoDfsWXAnt46r --hard-fork 1103712
```

```
Bus error (core dumped)
```

#### Proposed Solution

Debug and fix it.

**Comment by steviez** [comment]
Don't suppose you ran out of space? Think I saw `Bus error` from that once

**Comment by HaoranYi** [comment]
I had thought about this too. But there are 7T disk on the box, plenty of space. 
It seems that when running `create-snapshot` subcommand, ledger-tool use `/tmp` directory to store account_index. And the `tmpfs` on the box only has 200G space. So, it runs out of space and hit the `Bus error`. 
A potential fix is to use `<ledger>/account_index.ledger_tool` for account_index.

**Comment by steviez** [comment]
> A potential fix is to use <ledger>/account_index.ledger_tool for account_index.

That seems reasonable to me, and is in line with what we do for the other stuff such as `accounts.ledger-tool`
