### ISSUE TITLE
get_vote_accounts() doesn't work with forks

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#2994]
#### Problem
when setting a vote account balance to zero in a child fork, the parent fork is also cleared

#### Proposed Solution
introduce a forks-oriented index for the vote accounts cache

**Comment by rob-solana** [comment]
CC @sakridge

**Comment by sakridge** [comment]
@rob-solana this seems to be the same problem we fix by filtering account.tokens == 0 in the Accounts::load* functions, seems like there can be an Accounts::get_vote_accounts which does this filtering in the same fashion, what do you think?

**Comment by rob-solana** [comment]
@sakridge, I don't think that's the issue.  try uncommenting and running that test, which shows that the vote_accounts are deleted in the *parent*

**Comment by rob-solana** [comment]
vote_accounts probably needs to have a form that's similar to transaction_count
