### ISSUE TITLE
EpochSlots are not updated when slots are dumped

### ISSUE THREAD

**Issue by AshwinSekar** [solana-labs/solana#30068]
#### Problem
When validator dumps a previously frozen slot because it has the wrong version, it does not update EpochSlots and the cluster still views it as having that block frozen. This causes repair to be less effective as it could be chosen as an eligible peer for requests. 

#### Proposed Solution
Introduce pathway for validator to remove slot from EpochSlots in gossip. 

Or better yet, remove EpochSlots from gossip entirely and reconstruct a slot list view from votes in blockstore.

**Comment by mvines** [comment]
> Or better yet, remove EpochSlots from gossip entirely and reconstruct a slot list view from votes in blockstore.

Yes! Overall we want to reduce what's gossiped anyway. Full support towards using this issue as an excuse to remove EpochSlots entirely from gossip
