### ISSUE TITLE
Consensus (bank hash) mismatch between v1.13.5/6 and v1.14.13/master (mnb)

### ISSUE THREAD

**Issue by steviez** [solana-labs/solana#30060]
#### Problem

v1.14 exhibited a consensus divergence from mnb on slot 175475896; mnb was predominately running v1.13.5/6 at the time. Many operators running v1.14.x observed a panic (https://github.com/solana-labs/solana/issues/30049). However, this panic was hit in the first place because a slot was purged due to differing from the cluster:

```
Cluster duplicate confirmed slot 175475896 with hash GSgpmbzC21XqNJmdNd84MQwjfn5njpeyvSSPo1RFRyHY,
but our version has hash 9nMFwd2SnQqy4z8LyHpyakvt2hFkS2kyGmcrQBYaXTMA
```

The issue reproduces in replay with `solana-ledger-tool`; here is the correct hash from a `v1.13.6` node:
```
bank frozen: 175475896 hash: GSgpmbzC21XqNJmdNd84MQwjfn5njpeyvSSPo1RFRyHY
accounts_delta: 6h8JrMuDY23RyNCNaq7dDM36SRRdxrcSwnZBtgFzP3T9
signature_count: 5451
last_blockhash: 5iXEeC4g2kxhBQdJxguQNneqriXjBLhgsaMzcUpCnrkg
capitalization: 539 871 054 781 759 143

Accounts hash slot: 175475896 stats: BankHashStats {
    num_updated_accounts: 11554,
    num_removed_accounts: 15,
    num_lamports_stored: 2 302 459 823 051 189,
    total_data_len: 16 173 352,
    num_executable_accounts: 0
}
```
And the incorrect hash from a `v1.14.13` node:
```
bank frozen: 175475896 hash: 9nMFwd2SnQqy4z8LyHpyakvt2hFkS2kyGmcrQBYaXTMA
accounts_delta: 7n8XBwGB11PrkkDtWfjeTuXsy549u6sj3BjtZi7MXyd
signature_count: 5451
last_blockhash: 5iXEeC4g2kxhBQdJxguQNneqriXjBLhgsaMzcUpCnrkg
capitalization: 539 871 054 781 159 143

accounts hash slot: 175475896 stats: BankHashStats {
    num_updated_accounts: 11554,
    num_removed_accounts: 15,
    num_lamports_stored: 2 302 459 823 051 189,
    total_data_len: 16 173 352,
    num_executable_accounts: 0
}
```
Narrowing things down, I found two accounts to have different state between the versions:
- DF45Keju1iXGz45smompKNYMnspgQcHBMurHo56boRVf
    - [Here is the only tx](https://explorer.solana.com/tx/3h7bqkKdi9msHBKVn55kpYhquWDf8zFaVS4aVE3CbxkvdD6hTnGnhoSfkpFG2CLv8fB1eXU8ptkGTQRoApmFAm8x) that touched this account in slot 175475896
- Ninja1spj6n9t5hVYgF3PdnYz2PLnkt7rvaw3firmjs
    - Ninja1 was the leader for slot 175475896 and running v1.14 so this is seemingly a symptom and not a cause
    - For completeness, [here is the only tx](https://explorer.solana.com/tx/39MYqw7Yd21XxK9e2tH1T8UFsQ5jEQYnQ9Cr5yW4nBv4Ay2mKDLFRzCRgBDGcn11o23FS2rPDW3izfctsc6tx6jf) (vote) that involved this account in 175475896

Examining  v1.14.13 log output from `solana-ledger-tool` replay, `3h7bqkKdi9msHBKVn55kpYhquWDf8zFaVS4aVE3CbxkvdD6hTnGnhoSfkpFG2CLv8fB1eXU8ptkGTQRoApmFAm8x` failed on `v1.14.13` with:
```
tx error: InstructionError(3, ProgramFailedToComplete) ...
```
The program logs for `v1.14.13`:
```
Program log: Error: memory allocation failed, out of memory
Program E1XRkj9fPF2NQUdoq41AHPqwMDHykYfn5PzBXAyDs7Be consumed 475197 of 599976 compute units
Program failed to complete: BPF program panicked
Program E1XRkj9fPF2NQUdoq41AHPqwMDHykYfn5PzBXAyDs7Be failed: Program failed to complete
```
Interesting, `v1.13.6` also shows the same error / has similar logs:
```
Program log: Error: memory allocation failed, out of memory
Program E1XRkj9fPF2NQUdoq41AHPqwMDHykYfn5PzBXAyDs7Be consumed 475197 of 599976 compute units
Program failed to complete: BPF program panicked
Program E1XRkj9fPF2NQUdoq41AHPqwMDHykYfn5PzBXAyDs7Be failed: Program failed to complete
```

**Comment by bji** [comment]
> capitalization: 539871054781759143

> capitalization: 539871054781159143

You probably noticed this already, but these capitalization values differ by 600,000 lamports ...

**Comment by Lichtso** [comment]
No not a coincidence, because the divergent account is also the fee payer.
The program runtime sees the account:

```
     (
        DF45Keju1iXGz45smompKNYMnspgQcHBMurHo56boRVf,
        Account {
            lamports: [DIVERGENT],
            data.len: 0,
            owner: 11111111111111111111111111111111,
            executable: false,
            rent_epoch: 361,
        },
    ),
```

* v1.13 starts with `lamports: 2224435988,` (that value is reported by the explorer)
* v1.14 starts with `lamports: 2223235988,`
* v1.13 ends with `lamports: 2208233108,`
* v1.14 ends with `lamports: 2207033108,`
* v1.13 - v1.13 = 1200000 = 600000 CU * 2 lamports per CU (as requested by the first two instructions)
* all other accounts and the log output are exactly the same

Because the lamport values of `DF45Keju1iXGz45smompKNYMnspgQcHBMurHo56boRVf` are already different in `loaded_transaction.accounts` at the very beginning of `Bank::execute_loaded_transaction()`, this means it is not a problem in the VM or program runtime, but the compute budget program and fee payer logic that happens upfront during transaction loading.

**Comment by taozhu-chicago** [comment]
This sounds like 1.13 somehow got prioritization_fee to `0` while 1.14 have it correctly at `1,200,000`, then the fee was deducted from payer during `accounts::validate_fee_payer()` (when account was loaded). That could explain, but I don't see how yet

**Comment by t-nelson** [comment]
`accounts::validate_fee_payer()` doesn't actually apply the fee, just checks that the payer can afford it

https://github.com/solana-labs/solana/blob/0a3e52ba8b4f63c3675fa91fc89c4f54f69e5855/runtime/src/accounts.rs#L443-L448

**Comment by taozhu-chicago** [comment]
right! i misunderstood it.

**Comment by steviez** [comment]
Per suggestion, I instrumented out `Bank::calculate_fee()`. I tried to use the same variable names as the function parameters / intermediate variables. I used the fee payer (`DF45Keju1iXGz45smompKNYMnspgQcHBMurHo56boRVf`) from the tx in question to filter the results down; there were two invocations (two instructions):

v1.13.6
https://github.com/solana-labs/solana/blob/46fde27b3dd95a4d06020150ab3e1c0e93746db7/runtime/src/bank.rs#L4436-L4491
```
>>>>>>>> Function params
    lamports_per_sig=5000,
    fee_structure=FeeStructure { lamports_per_signature: 5000, lamports_per_write_lock: 0, compute_fee_bins: [FeeBin { limit: 1400000, fee: 0 }] },
    tx_wide_compute_cap=true,
    support_set_compute_unit_price_ix=true
>>>>>>>> Computed Values
    prioritization_fee_details=PrioritizationFeeDetails { fee: 0, priority: 0 },
    signature_fee=5000,
    write_lock_fee=0,
    compute_fee=0,
    calculated fee=5000
>>>>>>>> Function params
    lamports_per_sig=5000,
    fee_structure=FeeStructure { lamports_per_signature: 5000, lamports_per_write_lock: 0, compute_fee_bins: [FeeBin { limit: 1400000, fee: 0 }] },
    tx_wide_compute_cap=true,
    support_set_compute_unit_price_ix=true
>>>>>>>> Computed Values
    prioritization_fee_details=PrioritizationFeeDetails { fee: 0, priority: 0 },
    signature_fee=5000,
    write_lock_fee=0,
    compute_fee=0,
    calculated fee=5000
```
v1.14.13:
https://github.com/solana-labs/solana/blob/ec320644dbc89d870c21df1d0346931226e798d7/runtime/src/bank.rs#L4639-L4688
```
>>>>>>>> Function Params
    lamports_per_sig=5000,
    fee_structure=FeeStructure { lamports_per_signature: 5000, lamports_per_write_lock: 0, compute_fee_bins: [FeeBin { limit: 1400000, fee: 0 }] },
    support_set_compute_unit_price_ix=true,
    use_default_units_per_instruction=false
>>>>>>>> Computed Values
    prioritization_fee_details=PrioritizationFeeDetails { fee: 1200000, priority: 2000000 },
    signature_fee=5000,
    write_lock_fee=0,
    compute_fee=0,
    calculated fee=1205000
>>>>>>>> Function Params
    lamports_per_sig=5000,
    fee_structure=FeeStructure { lamports_per_signature: 5000, lamports_per_write_lock: 0, compute_fee_bins: [FeeBin { limit: 1400000, fee: 0 }] },
    support_set_compute_unit_price_ix=true,
    use_default_units_per_instruction=false
>>>>>>>> Computed Values
    prioritization_fee_details=PrioritizationFeeDetails { fee: 1200000, priority: 2000000 },
    signature_fee=5000,
    write_lock_fee=0,
    compute_fee=0,
    calculated fee=1205000
```

**Comment by taozhu-chicago** [comment]
looks like the culprit is the `Compute Budget Program: Request Heap Frame` in the[ transaction in question](https://explorer.solana.com/tx/3h7bqkKdi9msHBKVn55kpYhquWDf8zFaVS4aVE3CbxkvdD6hTnGnhoSfkpFG2CLv8fB1eXU8ptkGTQRoApmFAm8x). 

v1.13 does not seem to allow transaction to request heap size [here](https://github.com/solana-labs/solana/blob/v1.13.6/runtime/src/bank.rs#L4458), so the compute_budget will return error [here](https://github.com/solana-labs/solana/blob/v1.13.6/program-runtime/src/compute_budget.rs#L216-L225), v1.13 `calculate_fee()` then set prioritization_fee_detail to default [here](https://github.com/solana-labs/solana/blob/v1.13.6/runtime/src/bank.rs#LL4462C27-L4462C27). 

v1.14 [does not restrict request heap size](https://github.com/solana-labs/solana/blob/v1.14.13/program-runtime/src/compute_budget.rs#L211-L222), so it's have correct prioritization fee (1,200,000) for that transaction.

That explains why `calculate_fee` was correct most of time.

**Comment by taozhu-chicago** [comment]
https://github.com/solana-labs/solana/pull/30077 adds feature gated changes to set v1.14+ inline with v1.13 in mainet-beta

**Comment by Sriharsh1103** [comment]
getting same error at frontend side of calling my contract but working fine when i hit those function of solana playground .. what might be the issue ? any solution or hint regarding this
