### ISSUE TITLE
Rust RPC Client cannot be instantiated to send gzip header

### ISSUE THREAD

**Issue by fabioberger** [solana-labs/solana#30078]
#### Problem

I would like to enable gzip compression on Solana JSON-RPC client responses. However, I cannot instantiate the `RpcClient` with a custom HttpSender that adds the `AcceptEncoding: gzip` header because `HttpSender` is private and not exported by the package. 

#### Proposed Solution

Export `HttpSender` from the package.

**Comment by CriesofCarrots** [comment]
`HttpSender` is already a public struct, and in master and v1.15, the `http_sender` module is exported in `solana-rpc-client`:
https://github.com/solana-labs/solana/blob/fd3f26380e48f50188c110606edc711563fd972c/rpc-client/src/http_sender.rs#L29
https://github.com/solana-labs/solana/blob/fd3f26380e48f50188c110606edc711563fd972c/rpc-client/src/lib.rs#L3

Unless an urgent need comes up for this to be backported to v1.14 stable releases, we will let it ride the normal release train.
