### ISSUE TITLE
measure effectiveness of retransmit_latest_unpropagated_leader_slot

### ISSUE THREAD

**Issue by jbiseda** [solana-labs/solana#30127]
#### Problem
What is the effectiveness of retransmitting a leader slot which have not observed to be propagated?

#### Proposed Solution
Add metrics to measure if a retransmitted slot is subsequently rooted/skipped.

**Comment by behzadnouri** [comment]
Is this a duplicate of https://github.com/solana-labs/solana/issues/30098 ?
What is the difference?

**Comment by jbiseda** [comment]
Duplicate, closing
