### ISSUE TITLE
Validator 1.14.13 segfault

### ISSUE THREAD

**Issue by Deniskore** [solana-labs/solana#30140]
To reproduce the segfault, it is sufficient to use an empty geyser plugin with the following notify_transaction implementation

```Rust
    fn notify_transaction(
        &mut self,
        transaction_info: ReplicaTransactionInfoVersions,
        _slot: u64,
    ) -> Result<()> {
        let (mut keys, loaded_addresses) = match transaction_info {
            ReplicaTransactionInfoVersions::V0_0_1(replica) => (
                replica.transaction.message().account_keys().iter(),
                replica.transaction.get_loaded_addresses(),
            ),
            ReplicaTransactionInfoVersions::V0_0_2(replica) => (
                replica.transaction.message().account_keys().iter(),
                replica.transaction.get_loaded_addresses(),
            ),
        };

        trace!("{:#?}, {loaded_addresses:#?}", keys.next());
        Ok(())
    }
```
The crash happens right after the snapshot is unpacked.
There is no backtrace, unfortunately.

I guess the problem is somewhere in the Pubkey implementation.

**Comment by Deniskore** [comment]
It looks like the validator is still being built with Rust version 1.60, although the Rust version has been updated several times:
https://github.com/solana-labs/solana/pull/28741
https://github.com/solana-labs/solana/pull/29827

Everything works if build the plugin with version 1.60

**Comment by CalebEverett** [comment]
I was getting a seg fault error including a geyser plugin starting both a test and regular validator with solana version 1.13.3 and rustc version 1.67. I was able to build and run downgrading rustc to version 1.66.1.
