### ISSUE TITLE
Unable to delegate stake while setting up my local solana network

### ISSUE THREAD

**Issue by shivesh1999** [solana-labs/solana#30159]
Hi, i am trying to run the solana network on my local host, i am able to setup the bootstrap node using the benchmark instruction present on the documentation, i am also able to setup a node on the same system and my node is able to catchup with the cluster.

while following the next step to become a validator which is staking some SOL, i am following the instruction present in the validator setup documenation and while delegating stake i am getting a error of :

Error: Bad parameter: Unable to delegate. Vote account has no root slot

Here are my vote account details : 
Account Balance: 0.02685864 SOL
Validator Identity: 63Y2Lk3q4mB4jGM887EFPu68nUqSh6eNGurqHUeYb4MW
Vote Authority: {0: "63Y2Lk3q4mB4jGM887EFPu68nUqSh6eNGurqHUeYb4MW"}
Withdraw Authority: GoggS5Z7n8TspK94BpCu8uxy5tyg4fc8U59UBFa4bM1t
Credits: 0
Commission: 100%
Root Slot: ~
Recent Timestamp: 1970-01-01T00:00:00Z from slot 0

As you can see there is no root slot present here, and there is also some issue with the timestamp. I have followed all the steps form the solana official documentation but  still facing this issue.Since i am not able to do this step i am not able to add a validator to my network.

**Comment by blockinator** [comment]
@shivesh1999 Did you figure it out?

**Comment by shivesh1999** [comment]
@blockinator i was not able to find the reason for this, but a workaround is to use --force flag with the delegate command.

**Comment by bw-solana** [comment]
Yes, currently have to use `--force` for initial delegation of stake to the vote-account. Something like this:
`NDEBUG=1 ../..//multinode-demo/delegate-stake.sh --keypair ./identity.json --vote-account ./vote-account.json --stake-account ./stake-account.json --force`

For subsequent delegations, the `--force` param should not be necessary.
