### ISSUE TITLE
solana cluster 1.15.0 on testnet unable to delegate stake

### ISSUE THREAD

**Issue by vinodsharmak** [solana-labs/solana#30160]
Validator is running but while delegating stake facing below error
Credits: 0
Commission: 100%
Root Slot: ~
Recent Timestamp: 1970-01-01T00:00:00Z from slot 0

Error: Bad parameter: Unable to delegate. Vote account has no root slot

please suggest

**Comment by steviez** [comment]
Hard to provide much help when you clipped part of the command output that would allow us to identify and inspect the validator in question.

In any case, the output that you did provide would indicate the specified vote account hasn't landed any votes. My guess is some sort of misconfiguration (node not configured to vote, insufficient testnet SOL to vote, node not actually running correctly) or something like incorrectly specifying the vote account address
