### ISSUE TITLE
geyser plugin docs lack build guidance

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#30183]
#### Problem

the [geyser plugin docs](https://docs.solana.com/developing/plugins/geyser-plugins) have no guidance for building a plugin.  especially the strict requirements that the toolchain and solana crate versions linked against match that of validator software version that the plugin will be deployed on.

#### Proposed Solution

add them!

**Comment by darraghmahns** [comment]
@t-nelson Is this still a work in progress? Would like to contribute.

**Comment by t-nelson** [comment]
> @t-nelson Is this still a work in progress? Would like to contribute.

there seems to be some more guidance and code examples on that page now.  feel free to read through and propose any additions/changes that you think would be appropriate.

i'm going to close this issue since it does seem to have been generally resolved
