### ISSUE TITLE
Improve CRDT convergence

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#302]
when we get an answer back with updates, we can also get the remote table from that node.  we can compare it to our remote table and see if any of the nodes have more updates then we are aware of, and prioritize those.

**Comment by carllin** [comment]
@aeyakovenko, currently the get_updates_since function returns all the ReplicatedData with index greater than the requested update index: https://github.com/solana-labs/solana/blob/master/src/crdt.rs#L478.

Could you clarify what other information you would like from the remote table and how you see it being used?

**Comment by carllin** [comment]
I can take this :) 

@aeyakovenko, to implement the prioritization of the nodes with more updates than our local node is aware of, it could be fun to use a treap where the key is the node_id and the priority is the difference between the two remote table's values for that node_id. Then we can update the priorities by node_id on every update request, and pop off higher priority peers from the treap during the periodic gossip requests.

More practically, we can just extend our "remote" hashmap in the CRDT to also keep track of the "highest_seen_index" for each node, and just scan through the Hashmap to find higher priority peers.

**Comment by aeyakovenko** [comment]
Peers have liveness and remote versions of their peers. Those can be shared during updates.  If two nodes just exchanged their data they can take the max of each other remote and liveness tables.  The tricky part is that we can’t trust this info and have to weight it by stake.

**Comment by aeyakovenko** [comment]
So for example, for sharing liveness, you can keep a table called `external_liveness` that is aggregated observations from external pings, and we can weight them by their stake when we implement stakes.  I think for testing you can set the stake size to be equal to 1, or maybe the first byte of the public key to make it interesting.

**Comment by aeyakovenko** [comment]
@carllin the idea is to keep a separate table to aggregate rumors.  and only use that result to weight the probability of picking a specific node.  So a bad actor with no stake can't influence the network.
