### ISSUE TITLE
Solana program test issue

### ISSUE THREAD

**Issue by dr497** [solana-labs/solana#30271]
#### Problem

Hi! I am facing an issue with Solana program test. The issue recently appeared in code bases where tests used to pass  when trying to create associated token accounts (example code [here](https://github.com/dr497/bug))

```
[2023-02-11T09:32:14.847263000Z DEBUG solana_runtime::message_processor::stable_log] Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL invoke [1]
[2023-02-11T09:32:14.847698000Z DEBUG solana_runtime::message_processor::stable_log] Program log: Create
[2023-02-11T09:32:14.848095000Z DEBUG solana_runtime::message_processor::stable_log] Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL consumed 5475 of 200000 compute units
[2023-02-11T09:32:14.848140000Z DEBUG solana_runtime::message_processor::stable_log] Program failed to complete: Invoked an instruction with data that is too large (12178014311288245306 > 10240)
[2023-02-11T09:32:14.848156000Z DEBUG solana_runtime::message_processor::stable_log] Program ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL failed: Program failed to complete
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: TransactionError(InstructionError(0, ProgramFailedToComplete))', src/main.rs:25:10
```

I initially suspected it could be a versioning issue given that I had recently updated my Solana CLI so I tried to downgrade and then got the following error

```
Failed to create BPF VM: syscall #4389387904 was not registered before bind
```

I am using the following versions of rust and Solana

```
$ solana --version
solana-cli 1.14.15 (src:48aa6342; feat:3488713414)
```

```
$ rustc --version
rustc 1.67.0 (fc594f156 2023-01-24)
```

#### Proposed Solution

I don't have a solution at the moment

**Comment by steviez** [comment]
> $ rustc --version
rustc 1.67.0 (fc594f156 2023-01-24)

I suspect that your Rust version may be the issue here; your Cargo.toml file would indicate that you're building against v1.15 solana crate versions, so I believe the version of the CLI that you have in your $PATH (v1.14.15) isn't relevant.
https://github.com/dr497/bug/blob/master/Cargo.toml

Give Rust 1.66.1 a try for v1.15.x crate deps:
https://github.com/solana-labs/solana/blob/v1.15/rust-toolchain.toml

**Comment by dr497** [comment]
@steviez Thanks a lot for your help, rust was indeed the culprit! For anyone else reading this and having the same issue:

```
rustup install 1.66.1 && rustup default 1.66.1
```

**Comment by rahulkp220** [comment]
@ellttBen did the solution proposed by @dr497 work for you?
I am facing the same issue on rust 1.69.0
```
└─> rustc --version
rustc 1.69.0 (84c898d65 2023-04-16)

└─> solana --version
solana-cli 1.16.0 (src:a5275f88; feat:574325836, client:SolanaLabs)

└─> anchor --version
anchor-cli 0.27.0
```

**Comment by rahulkp220** [comment]
Okay, got this working by downgrading solana version from `1.16.0` to `1.15.2`.

**Comment by sausage-dog** [comment]
Is there a fix that doesn't require dropping Solana version as that breaks other things for me?

**Comment by ilmoi** [comment]
Is there no fix without dropping version to 1.14?

**Comment by steviez** [comment]
Several people asked about a "fix without clearing stating the problem they're encountering.

In general, the goal is to have consistent stack.
- Step 1 is making sure you are using the correct Rust version for whichever solana version you're using. As an example, this file shows that for the v1.16.7 versions of Solana crates, you should be using Rust v1.69.0
https://github.com/solana-labs/solana/blob/v1.16.7/rust-toolchain.toml
- Step 2 is aligning dependency versions of whatever you're using with Solana. For example, Anchor 0.28.0 appears to align with Solana v1.16 crates as specified in TOML files for that tag. For example, here is one I picked at random:
https://github.com/coral-xyz/anchor/blob/v0.28.0/cli/Cargo.toml
- With the two above items stated, it seems that there might be some problems with programs built with old version (ie v1.14) with current versions (ie v1.16). https://github.com/solana-labs/solana/issues/31960 has more discussion on the matter

**Comment by snawaz** [comment]
> Okay, got this working by downgrading solana version from `1.16.0` to `1.15.2`.

I don't get this. Even if it worked on _your_ machine using `1.15.2`, how would it work on the mainnet which is using `1.16.x`? Looks like `1.16.0`. You cannot downgrade mainnet's solana version, can you?

Looks like everyone who is targeting the mainnet, has to upgrade their versions. All programs need to be changed. `

`1.16.x` is backward-**incompatible** ?
