### ISSUE TITLE
`test_incremental_snapshot_download_with_crossing_full_snapshot_interval_at_startup` fails intermittently

### ISSUE THREAD

**Issue by bw-solana** [solana-labs/solana#30291]
#### Problem
`test_incremental_snapshot_download_with_crossing_full_snapshot_interval_at_startup` fails intermittently with 

```
thread 'solSnapshotPkgr' panicked at 'failed to archive snapshot package: IoWithSourceAndFile(Os { code: 2, kind: NotFound, message: "No such file or directory" }, "archive path stat", "/solana/local-cluster/farf/.tmpbX2VXD/tmp-snapshot-archive-99.tar.bz2")', core/src/snapshot_packager_service.rs:92:22
```

We seem to be getting a "No such file or directory" error while trying to read the metadata for the archived snapshot, which is odd because we created the archive immediately before this step.

stack backtrace:
```
0: rust_begin_unwind
at        /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
1: core::panicking::panic_fmt
at        /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
2: core::result::unwrap_failed
at        /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/result.rs:1791:5
note: Some details are omitted, run with        `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'main' panicked at 'snapshot_packager_service: Any        { .. }', core/src/validator.rs:1199:22
stack backtrace:
0: rust_begin_unwind
at        /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/std/src/panicking.rs:575:5
1: core::panicking::panic_fmt
at        /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/panicking.rs:65:14
2: core::result::unwrap_failed
at        /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/result.rs:1791:5
3: solana_core::validator::Validator::join
4: <solana_local_cluster::local_cluster::LocalCluster        as solana_local_cluster::cluster::Cluster>::exit_node
5:        local_cluster::test_incremental_snapshot_download_with_crossing_full_snapshot_interval_at_startup::{{closure}}
6: serial_test::serial_code_lock::local_serial_core
7: core::ops::function::FnOnce::call_once
8: core::ops::function::FnOnce::call_once
at        /rustc/90743e7298aca107ddaa0c202a4d3604e29bfeb6/library/core/src/ops/function.rs:251:5
```

#### Proposed Solution
Debug and fix

**Comment by bw-solana** [comment]
> Was this when running locally or in CI? Can you attach a full log (or link the buildkite failure)?

I've seen this twice in CI. I haven't been able to reproduce locally yet, but I've got it running in a loop to try.

[BK link](https://buildkite.com/solana-labs/solana/builds/90195#01864bd5-b00f-4c7a-aa39-e628354de68e)

**Comment by bw-solana** [comment]
I got it to fail on my dev machine running local cluster tests in a loop:
`for i in {0..10}; do cargo test --package solana-local-cluster --test local_cluster -- --nocapture &>> bw_temp_output; done`
Failed with the exact same signature (again on incremental snapshot slot 99)

So far it has failed 1 time out of 8 runs.

**Comment by bw-solana** [comment]
Nice! I can move over to your faster repro method.

I was able to capture an additional failure last night w/ a couple code additions. I grabbed the metadata:
```
let metadata = fs::metadata(&archive_path).map_err(|e| {
    SnapshotError::IoWithSourceAndFile(e, "archive path stat", archive_path.clone())
})?;
```
in two additional places: (1) after creating the archive path and (2) after creating the archive file. Both of these additional metadata gets succeeded. The run failed in the usual spot, grabbing the metadata before the rename for incremental snapshot slot 99.

**Comment by bw-solana** [comment]
Hacked something to run 10 concurrent instance of  `test_incremental_snapshot_download_with_crossing_full_snapshot_interval_at_startup` and I can get it to fail very quickly now.

I'm observing that at some point between archiving the files and checking metadata, we are deleting some files.

After archiving files, directory `/home/sol/brennan/local-cluster/farf/.tmptgcCC1/` contains:
```
/home/sol/brennan/local-cluster/farf/.tmptgcCC1/remote
/home/sol/brennan/local-cluster/farf/.tmptgcCC1/incremental-snapshot-45-81-8cfh9D8EBQBqeRUyDMNNuSrp8PLK1qVeS3F78BDVRMEw.tar.bz2
/home/sol/brennan/local-cluster/farf/.tmptgcCC1/tmp-snapshot-archive-108.tar.bz2
/home/sol/brennan/local-cluster/farf/.tmptgcCC1/tmp-snapshot-archive-108-DEq0WL
/home/sol/brennan/local-cluster/farf/.tmptgcCC1/incremental-snapshot-90-99-BY3n5UBvGNsmeEdbpcDrFiFyhcjKyW8jffE8trHHtWFy.tar.bz2
```

When checking metadata of `/home/sol/brennan/local-cluster/farf/.tmptgcCC1/tmp-snapshot-archive-108.tar.bz2` directory `/home/sol/brennan/local-cluster/farf/.tmptgcCC1/` contains:
```
/home/sol/brennan/local-cluster/farf/.tmptgcCC1/remote
/home/sol/brennan/local-cluster/farf/.tmptgcCC1/tmp-snapshot-archive-108-DEq0WL
```

**Comment by bw-solana** [comment]
Looks like the files are getting removed as part of this process:
```
[2023-02-15T16:13:05.297882442Z INFO  local_cluster] Delete all the snapshots on the validator and restore the originals from the backup...
[2023-02-15T16:13:05.297914503Z INFO  local_cluster]            deleting file /home/sol/brennan/local-cluster/farf/.tmpzIH7wb/snapshot-90-Am8MaGrV5e4gsRJfs7eM636WrTkN7pyn6BGGiSckb9XP.tar.bz2...
[2023-02-15T16:13:05.298002099Z INFO  local_cluster]            deleting file /home/sol/brennan/local-cluster/farf/.tmpzIH7wb/remote/snapshot-45-AQ1fr8n3ad9XusZGX5hecNH3E81prVESWCTywamyBcFs.tar.bz2...
[2023-02-15T16:13:05.298064417Z INFO  local_cluster]            deleting file /home/sol/brennan/local-cluster/farf/.tmp3b2kFw/tmp-snapshot-archive-108.tar.bz2...
[2023-02-15T16:13:05.298087350Z INFO  local_cluster]            deleting file /home/sol/brennan/local-cluster/farf/.tmp3b2kFw/incremental-snapshot-45-81-H9GAaMreXvw8Sp5v3JY2wn5Zw5JcA2Q5JSBTVXTCW7BF.tar.bz2...
[2023-02-15T16:13:05.298312496Z INFO  local_cluster] Delete all the snapshots on the validator and restore the originals from the backup... DONE
```

**Comment by bw-solana** [comment]
> The folders are different; likely different for the leader and the validator. Can you confirm the files deleted are for the same node that's asserting?

Yes, one of the folders is for the full and one is for incremental snapshot archive. The same validator that is asserting is the one that created/deleted these folders. Seems like we have a race condition between the main thread and a sub-thread to chase down

**Comment by bw-solana** [comment]
Confirmed we have a race condition between the SnapshotPackagerService (SPS) and the main test thread. SPS calls `archive_snapshot_package` at the same time the main test thread is deleting snapshots. If it happens to delete things in-between the time the archive is created and when we try and check the archive, we'll panic.

@brooksprumo - Any ideas how best to sync these threads?

**Comment by jstarry** [comment]
@brooksprumo I'm seeing this fail again, don't think it's related to my changes: https://buildkite.com/anza/agave/builds/5187#018fc658-2f19-4792-bd34-36aab0e8e98b
