### ISSUE TITLE
Bank reference in SamplePerformanceService held too long

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#30312]
#### Problem
[This bank reference](https://github.com/solana-labs/solana/blob/27f18f96e81233880265d23f6d4aae956f30713c/core/src/sample_performance_service.rs#L54) is never dropped, because `bank` in the loop scope is initialized as a new variable. This means we'll hold onto a reference to this `Bank` for the lifetime of `SamplePerformanceService`, which is the same as the lifetime of the `solana-validator` process.

Aside from leaking memory directly in the `Bank`, this long-lived reference may prevent `AccountsDb` from performing normal cleanup of on-disk / mmapped storage.

Additionally, relevant to note that this issue is only present on RPC nodes since only RPC nodes run SamplePerformance Service.

#### Proposed Solution
Wrap https://github.com/solana-labs/solana/blob/27f18f96e81233880265d23f6d4aae956f30713c/core/src/sample_performance_service.rs#L54-L66 in a block that returns the sample so the Bank reference may be safely dropped

**Comment by CriesofCarrots** [comment]
cc @steviez @ilya-bobyr

**Comment by CriesofCarrots** [comment]
Thought on merging something like #30316 first for backporting purposes?

**Comment by ilya-bobyr** [comment]
> Thought on merging something like #30316 first for backporting purposes?

This change is simpler.  So maybe merge it first and backport?
And then I can rebase #30316 on top.

**Comment by ilya-bobyr** [comment]
> Thought on merging something like #30316 first for backporting purposes?

Totally makes sense.
Refactoring in #30297 is much bigger.
I can easily rebase it on top of #30316.
