### ISSUE TITLE
[CRITICAL] Security Issues

### ISSUE THREAD

**Issue by abebeos** [solana-labs/solana#30328]
#### Problem

Those dormant security issues make me nervous:

https://github.com/solana-labs/solana/issues?q=is%3Aopen+is%3Aissue+label%3Asecurity+sort%3Aupdated-asc

#### Proposed Solution

Process each issue, move to a private repo if the issue has some severity.

If kept public, document, thus a visitor knows that it has low severity and can be kept in public.

**Comment by abebeos** [comment]
(as a sidenote: I really dislike the `community` label)

**Comment by t-nelson** [comment]
do you plan on being more proactive about this than necroposting a bunch of 2yr old issues that are irrelevant today?

**Comment by steviez** [comment]
> (as a sidenote: I really dislike the `community` label)

What's wrong with the community label ?

**Comment by CriesofCarrots** [comment]
Here is our current security policy: https://github.com/solana-labs/solana/blob/master/SECURITY.md

**Comment by abebeos** [comment]
> do you plan on being more proactive about this than necroposting a bunch of 2yr old issues that are irrelevant today?

No (for the time being).

**Comment by abebeos** [comment]
> Here is our current security policy: https://github.com/solana-labs/solana/blob/master/SECURITY.md

Ty (long document). But this issue is just about one thing:

* Issues labeled `security`, open, unprocessed since months/years.

Please realize this:

> Those dormant security issues make me nervous:

I cannot apply the "proposed solution" myself. This is core-team work (that should have been done since months/years).
