### ISSUE TITLE
Consider moving "The Future" Milestone to a Project

### ISSUE THREAD

**Issue by abebeos** [solana-labs/solana#30358]
#### Problem

https://github.com/solana-labs/solana/milestone/15

#### Proposed Solution

Move those issues to a dedicated github project:

https://github.com/solana-labs/solana/projects

To allow for a better visualization/categorization of this "low-priority-backlog" (one list-view, one board-view)

**Comment by mvines** [comment]
Thanks for the suggestion. We'll keep it as is.
