### ISSUE TITLE
High repair traffic on mainnet

### ISSUE THREAD

**Issue by behzadnouri** [solana-labs/solana#30374]
#### Problem
For ~2 hours within `2023-02-09 22:00` till `2023-02-10 02:00`, mainnet sustained very high repair traffic where most of the repair request were dropped. Other metrics look fine though.

Repair requests received:
![repair-requests-received](https://user-images.githubusercontent.com/1288998/219479892-cae6cd1d-7657-4a74-88f7-aaefd9ac7641.png)

Repair requests sent:
![repair-requests](https://user-images.githubusercontent.com/1288998/219479979-b224d8f5-4ebd-4873-832e-ff092d821b21.png)

% of shreds repaired within the slot look normal though:
![repair-ratio](https://user-images.githubusercontent.com/1288998/219483373-d10716a9-75c6-42e6-83ba-d38999e875a5.png)

Also propagation time per shred and block sizes look fine:

![turbine_millis_per_shred](https://user-images.githubusercontent.com/1288998/219728999-77cf3b83-c9fe-4535-9244-3fcd96b2758f.png)
![num_data_shreds](https://user-images.githubusercontent.com/1288998/219729298-7fb6e512-c7b3-4d70-83b3-aeb05a8b580b.png)

#### Proposed Solution

Debug what caused high repair traffic.

cc @jbiseda @bw-solana

**Comment by jbiseda** [comment]
Corresponds with version mismatch and failed shred recovery:

shred_fetch_repair:
![Screenshot 2023-02-16 at 11 55 37 PM](https://user-images.githubusercontent.com/1054614/219585980-5b8eab19-b758-4d25-836d-447fc037848d.png)

blockstore-insert-shreds:
![Screenshot 2023-02-16 at 11 18 46 PM](https://user-images.githubusercontent.com/1054614/219586072-54921d3d-8690-49ca-abda-ad8a970e7da1.png)

Is there a duplicate node?

**Comment by bw-solana** [comment]
I'm guessing it's related to the bank hash mismatch on v1.15

```
thread 'solReplayStage' panicked at 'We have tried to repair duplicate slot: 178114337 more than 10 times and are unable to freeze a block with bankhash GkTuscdwprNteWUMUjNRCJxZf3Gg55bt1tzV8QkhKgv5, instead we have a block with bankhash Some(3ncx1EbLUoGPQUoNgwpqYJ8cmaK3BiUwwzN7tLJJ5rmQ). This is most likely a bug in the runtime. At this point manual intervention is needed to make progress. Exiting
```

**Comment by behzadnouri** [comment]
> I'm guessing it's related to the bank hash mismatch on v1.15

The repair spikes are from 2/9. So a week ago.

**Comment by behzadnouri** [comment]
> Corresponds with version mismatch and failed shred recovery:
> Is there a duplicate node?

Mismatching `shred_version`s are filtered out very early in the pipeline:
https://github.com/solana-labs/solana/blob/3a4ba72da/core/src/shred_fetch_stage.rs#L97-L106
https://github.com/solana-labs/solana/blob/3a4ba72da/ledger/src/shred.rs#L918-L924

If they cause high repair anyways, then we definitely have some bugs somewhere.

**Comment by bw-solana** [comment]
Looks like `closest-completion-repairs` is the request type that popped:
![image](https://user-images.githubusercontent.com/44715351/219697183-d8169e68-a049-49a1-aaf9-7cd3067d3abf.png)

**Comment by jbiseda** [comment]
Closest completion repair type may be unnecessary. Looking to see if this should be removed.

**Comment by behzadnouri** [comment]
> Closest completion repair type may be unnecessary.

That sounds like a separate issue which might need to be addressed if there is enough evidence to support it.
But for this issue specifically we need to understand what caused repair to sustain such an elevated bandwidth for ~2 hours. Even if closest-completion-repair is unnecessary, we don't see such levels sustained for this long at other times.

**Comment by jbiseda** [comment]
I found a couple issues in `get_closest_completion ` see: #30433

**Comment by RdeWilde** [comment]
Could this relate to the mainnet outage today?

**Comment by bw-solana** [comment]
> Could this relate to the mainnet outage today?

Looking through metrics, I'm not seeing any fat blocks around this time period. Closest one was on 2/12. I suspect these are distinct issues

**Comment by RdeWilde** [comment]
Thanks for looking into this @bw-solana 👍🏻

I'm not sure if we can safely assume the "fat block" was the cause, or it was the result of another root cause. Also, I'm not sure if the cause is it being "fat". This doesn't help us getting to anything, other than not completely ruling this out.

Some things do actually happen in both issues, especially the high number of repairs. Hopefully solving this issue will give us also insight on the cause of the mainnet outage or vice versa.

It being two distinct issues might even make things worse 🙈 Do the metrics after the "fat" block match? In terms of repairs/shreds/retransmits. Hope someone can get to the root of this 💪🏼
