### ISSUE TITLE
v1.15.2 solana-test-validator --bpf-program flag seems to be broken

### ISSUE THREAD

**Issue by ananas-block** [solana-labs/solana#30402]
#### Problem
Programs deployed with the following command:

```solana-test-validator --bpf-program <program_id> <path>```

throw the following error at invocation:

```Error: failed to send transaction: Transaction simulation failed: This program may not be used for executing instructions```

Programs work fine when deployed manually with solana program deploy.
The program accounts look different in local explorer when deployed with --bpf-program and solana program deploy.

[See this repo for screenshots and to replicate the issue.](https://github.com/ananas-block/exec_test)

**Comment by godmodegalactus** [comment]
Yes after further analysis I found out that the programs loaded are not with the correct loader but the old loader.
And they are represented as `Account` instead of `ProgramAccount` which flags this program as `invalid_program`.

**Comment by KirillLykov** [comment]
@ananas-block how urgent for you is this problem?

**Comment by godmodegalactus** [comment]
Actually you can just over come this issue by deploying program manually.

```sh
solana-test-validator --account MangoCzJ36AjZyKwVj3VnYU4GTonjfVEnJmvvWaxLac bin/mango-mint.json &

sleep 5s

solana program deploy bin/mango.so --program-id bin/mango.json
# idle waiting for abort from user
( trap exit SIGINT ; read -r -d '' _ </dev/tty ) ## wait for Ctrl-C

pkill -9 solana
```

**Comment by CriesofCarrots** [comment]
Ah, yes, it looks like this PR only updated the program_id, but didn't construct the program and programdata accounts correctly to use the upgradeable loader: https://github.com/solana-labs/solana/pull/29051

**Comment by azerpas** [comment]
For those who are getting this error while using `anchor test`, the following steps did the trick for me:
- downgrade to v1.14
- delete `Cargo.lock`
- delete `target` folder
