### ISSUE TITLE
Solana validator v1.15.2 localnet setup doesn't work

### ISSUE THREAD

**Issue by KirillLykov** [solana-labs/solana#30403]
#### Problem

Solana validator 1.15.2 doesn't work for local cluster setup:
```bash
# panel 1
./multinode-demo/setup.sh
./multinode-demo/faucet.sh
# panel 2
sudo $(command -v target/debug/solana-sys-tuner) --user $(whoami) > sys-tuner.log 2>&1 &# <-- if you want to use many transactions
./multinode-demo/bootstrap-validator.sh 2> err.txt
```

Now start client
```bash
 #panel 3
./multinode-demo/bench-tps.sh
2023-02-20T14:24:14.975825735Z INFO  solana_gossip::gossip_service] discovering...
    IP Address        |Age(ms)| Node identifier                              | Version |Gossip|TPUvote| TPU  |TPUfwd| TVU  |TVUfwd|Repair|ServeR|ShredVer
    ------------------+-------+----------------------------------------------+---------+------+-------+------+------+------+------+------+------+--------
    none            me|  5218 | AC9uZDqJzXdfebhMWWfio5jeLH7aN1rekbe46RSuT5DQ | 1.15.2  | none |  none | none | none | none | none | none | none | 0
    Nodes: 0
    Spies: 1
```

If use `tpu-client`, will also not work. 
Looks like something is broken on validator side.

Originally found by @godmodegalactus on their local validator setup for 1.15.3:
In file https://github.com/solana-labs/solana/blob/master/tpu-client/src/nonblocking/tpu_client.rs#L325 returns vector of size 0 so transactions are not forwarded to any leader for the local cluster.

#### Proposed Solution

1. Checkout other versions: 
- [x] v1.14.9, 
- [x] v1.15.0
- [&cross;] v1.15.1, 
- [&cross;] v1.15.2, 
- [&cross;] branch v1.15,
- [&cross;] master
2.  find when was introduced: between 15.0 and 15.1

**Comment by godmodegalactus** [comment]
I also found out that `getClusterNodes` rpc call return an empty array.

**Comment by KirillLykov** [comment]
Looks like the PR which breaks it is https://github.com/solana-labs/solana/pull/29992

**Comment by KirillLykov** [comment]
This is a duplicate for https://github.com/solana-labs/solana/issues/30157
