### ISSUE TITLE
unable to confirm transaction. This can happen in situations such as transaction expiration and insufficient fee-payer funds

### ISSUE THREAD

**Issue by OhFlohre** [solana-labs/solana#30435]
When I build from source I keep getting this error on the solana-test-validator when using airdrop:
`Error: unable to confirm transaction. This can happen in situations such as transaction expiration and insufficient fee-payer funds`

**Comment by CriesofCarrots** [comment]
I am not able to reproduce this. Are you sure that you are sending your `solana airdrop` command to your test-validator with the right `--url` parameter?

**Comment by KirillLykov** [comment]
@OhFlohre could you provide more details about how you've set up validator, airdrop, etc?

**Comment by davidwei19930915** [comment]
Hello, are you interested in creating a new online virtual currency, which is rarer than traditional virtual coins, can drive manufacturing and employment problems for ordinary people, and more importantly, it is more suitable for Americans. And it has a lot to do with Starlink.  
If you are interested, please contact me My email address is <daivdwei19930915@outlook.com>

**Comment by Crypto2** [comment]
I'm getting this most of the time now when using the spl-token command line to transfer SPL tokens.
