### ISSUE TITLE
BanksClient is still missing some support for VersionedTransaction and VersionedMessage

### ISSUE THREAD

**Issue by kevinheavey** [solana-labs/solana#30434]
#### Problem

#28739 allowed some methods to support both legacy and versioned transactions. The following methods still only support legacy transactions:

- process_transaction_with_commitment
- process_transaction_with_preflight_and_commitment
- process_transaction_with_preflight
- process_transaction
- simulate_transaction_with_commitment
- simulate_transaction

As for versioned messages, `get_fee_for_message_with_commitment_and_context` only supports legacy `Message`.

#### Proposed Solution

Probably just need to do what #28739 does for the remaining methods

Tasks:

- [x] versioned transaction support
- [ ] versioned message support

**Comment by KirillLykov** [comment]
Looks generally reasonable but I don't know context of these changes. @joncinque do you think it is something we want to do?

**Comment by mvines** [comment]
seems reasonable to me

**Comment by joncinque** [comment]
Yeah definitely! It'll be an easy change to use `impl Into<VersionedTransaction>` everywhere. I went down a rabbit hole for `Message`... looks like we might need to make some SDK changes to properly do conversions there

**Comment by KirillLykov** [comment]
> Yeah definitely! It'll be an easy change to use `impl Into<VersionedTransaction>` everywhere. I went down a rabbit hole for `Message`... looks like we might need to make some SDK changes to properly do conversions there

Is the issue with `Message` blocking for the work in this issue? If not I though to take it if noone else wants to take it

**Comment by CriesofCarrots** [comment]
We can probably add an implementation of `impl From<Message> for VersionedMessage` and use the same approach for `get_fee_for_message_with_commitment_and_context()`

**Comment by kevinheavey** [comment]
@CriesofCarrots I'd be equally happy with a breaking change so that it expects `VersionedMessage` instead of `Message` but no idea if that would inconvenience people

**Comment by KirillLykov** [comment]
Would be nice to update the issue with what has been done and what is remaining because it looks abandoned and not clear per se if [related PR](https://github.com/solana-labs/solana/pull/30958) resolved it completely or partially. To simplify tracking, [task lists](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/about-task-lists#creating-task-lists) work

**Comment by kevinheavey** [comment]
Updated the issue to add a task list. Versioned transaction support is done, versioned message support is not done. I vaguely remember that it's a bit trickier but I can't remember what problems I ran into
