### ISSUE TITLE
Unable to open /data/sol/validator-ledger/genesis.bin

### ISSUE THREAD

**Issue by zhy827827** [solana-labs/solana#30529]
#### Problem

IO error: No such file or directory:
Failed to open ledger genesis_config at "/data/sol/validator-ledger": Unable to open "/data/sol/validator-ledger/genesis.bin": Os { code: 2, kind: NotFound, message: "No such file or directory" }, IO error: No such file or directory (os error 2)

solana-validator 1.13.6 (src:8f2c8b83; feat:1775889670)

**Comment by zhy827827** [comment]
[2023-02-25T17:27:59.423041294Z WARN  solana_runtime::hardened_unpack] Failed to open ledger genesis_config at "/data/sol/validator-ledger": Unable to open "/data/sol/validator-ledger/genesis.bin": Os { code: 2, kind: NotFound, message: "No such file or directory" }, IO error: No such file or directory (os error 2)
[2023-02-25T17:28:00.662189600Z INFO  solana_validator] solana-validator 1.13.6 (src:8f2c8b83; feat:1775889670)
[2023-02-25T17:28:00.662237553Z INFO  solana_validator] Starting validator with: ArgsOs {
        inner: [
            "/home/ubuntu/solana-release/bin/solana-validator",
            "--ledger",
            "/data/sol/validator-ledger",
            "--dynamic-port-range",
            "8002-8020",
            "--identity",
            "/home/ubuntu/validator-keypair.json",
            "--no-voting",
            "--gossip-port",
            "8001",
            "--rpc-port",
            "8899",
            "--log",
            "/data/sol/logs/sol.log",
            "--private-rpc",
            "--full-rpc-api",
            "--wait-for-supermajority",
            "153139220",
            "--no-snapshot-fetch",
            "--no-genesis-fetch",
            "--incremental-snapshots",
            "--snapshot-archive-format",
            "tar",
            "--full-snapshot-interval-slots",
            "20000",
            "--incremental-snapshot-interval-slots",
            "2000",
            "--maximum-full-snapshots-to-retain",
            "2",
            "--maximum-incremental-snapshots-to-retain",
            "4",
            "--maximum-local-snapshot-age",
            "2000",
            "--accounts-db-caching-enabled",
            "--limit-ledger-size",
            "50000000",
            "--entrypoint",
            "mainnet-beta.solana.com:8001",
            "--expected-shred-version",
            "11762",
            "--expected-bank-hash",
            "4kL82HMacFEPTpvwBhNpFTmw2GeSCvvDn3xPi7Whdntc",
            "--rpc-send-leader-count",
            "8",
        ],
    }

**Comment by CriesofCarrots** [comment]
Do have reason to suspect that `genesis.bin` should exist in `/data/sol/validator-ledger`? Have you inspected that directory?

**Comment by zhy827827** [comment]
I don't know that genesis.bin needs to download by myself?

**Comment by CriesofCarrots** [comment]
`--no-genesis-fetch` is in your startup arguments...
There may also be a place to download genesis for the public clusters manually; you could ask the validator community on discord.
However, if the node has been up before, you should still have genesis and snapshots in your ledger.

**Comment by zhy827827** [comment]
I have another question to ask you：
mysql sol config is this:

`ExecStart=/home/ubuntu/solana-release/bin/solana-validator \
  --expected-shred-version 11762 \
  --identity /home/ubuntu/validator-keypair.json \
  --ledger /data/sol/validator-ledger/ \
#  --bind-address 127.0.0.1 \
  --rpc-port 8899 \
  --no-voting \
  --no-os-network-stats-reporting \
  --enable-rpc-transaction-history \
  --limit-ledger-size 300000000 \
  --account-index spl-token-owner \
  --log /data/sol/logs/sol.log \
  --known-validator 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2 \
  --known-validator GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ \
  --known-validator DE1bawNcRJB9rVm3buyMVfr8mBEoyyu73NBovf2oXJsJ \
  --known-validator CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S \
#  --entrypoint 34.83.231.102:8001 \
#  --entrypoint 145.40.67.83:8001 \
#  --entrypoint 147.75.38.117:8001 \
#  --entrypoint 145.40.93.177:8001 \
#  --entrypoint 86.109.15.59:8001 \
#  --entrypoint 58.254.182.23:8001 \
    --entrypoint entrypoint.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint2.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint3.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint4.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint5.mainnet-beta.solana.com:8001 \
  --dynamic-port-range 8000-9000 \
  --no-port-check \
  --full-rpc-api \
 --expected-genesis-hash 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d \
 --wal-recovery-mode skip_any_corrupted_record \
 --expected-bank-hash 4kL82HMacFEPTpvwBhNpFTmw2GeSCvvDn3xPi7Whdntc`


Can't download the snapshot all the time：

[2023-02-26T01:45:22.957836057Z INFO  solana_validator::bootstrap] Searching for an RPC service with shred version 11762 (Retrying: No snapshots available)...
[2023-02-26T01:45:22.957917881Z INFO  solana_validator::bootstrap] Total 206 RPC nodes found. 0 known, 0 blacklisted

**Comment by CriesofCarrots** [comment]
Sorry, I answered your first question in hopes of helping in the middle of a restart, but we don't offer technical support on github.
Best places to ask questions are [Solana Stack Exchange](https://solana.stackexchange.com/) and #validator-support on [discord](https://solana.com/discord).
