### ISSUE TITLE
backup_and_clear_blockstore() doesn't work with rocksdb fifo compaction

### ISSUE THREAD

**Issue by steviez** [solana-labs/solana#30528]
#### Problem

https://github.com/solana-labs/solana/blob/cbcd3ef27e61f323f9d532e6dbb543246fcaf1bc/core/src/validator.rs#L1786 takes the ledger path, but not the compaction type that a validator can specify. As such, in restart situations, the ledger under `rocksdb_fifo` won't be cleared.

#### Proposed Solution
Plumb the validator compaction type specified by argument to this function.

Probably worth checking to see if there are any other places in `Validator` where we call `Blockstore::open()`, which uses default of level.

**Comment by steviez** [comment]
FYI @yhchiang-sol (for fifo stuff) and @mvines ([reported issue in Discord](https://discord.com/channels/428295358100013066/1078921440620986388/1078990214913077320))

**Comment by sakridge** [comment]
Seems like we should have more test coverage for this path as well. Automated restart local-cluster test?

**Comment by steviez** [comment]
I closed this issue as the targeted bug fix, but opened another issue for how we can test / adjust to avoid similar bugs down the road:
https://github.com/solana-labs/solana/issues/30595
