### ISSUE TITLE
Retrying: No snapshots available

### ISSUE THREAD

**Issue by zhy827827** [solana-labs/solana#30533]
sol version:1.13.5

my sol config is this:

ExecStart=/home/ubuntu/solana-release/bin/solana-validator \ 
--expected-shred-version 11762 \ 
--identity /home/ubuntu/validator-keypair.json \ 
--ledger /data/sol/validator-ledger/ \ 
--rpc-port 8899 \ 
--no-voting \ 
--no-os-network-stats-reporting \ 
--enable-rpc-transaction-history \ 
--limit-ledger-size 300000000 \ 
--account-index spl-token-owner \ 
--log /data/sol/logs/sol.log \ 
--known-validator 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2 \ 
--known-validator GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ \ 
--known-validator DE1bawNcRJB9rVm3buyMVfr8mBEoyyu73NBovf2oXJsJ \ 
--known-validator CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S \ 
--entrypoint entrypoint.mainnet-beta.solana.com:8001 \ 
--entrypoint entrypoint2.mainnet-beta.solana.com:8001 \ 
--entrypoint entrypoint3.mainnet-beta.solana.com:8001 \ 
--entrypoint entrypoint4.mainnet-beta.solana.com:8001 \ 
--entrypoint entrypoint5.mainnet-beta.solana.com:8001 \ 
--dynamic-port-range 8000-9000 \ 
--no-port-check \ 
--full-rpc-api \ 
--expected-genesis-hash 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d \ 
--wal-recovery-mode skip_any_corrupted_record \ 
--expected-bank-hash 4kL82HMacFEPTpvwBhNpFTmw2GeSCvvDn3xPi7Whdntc

Can't download the snapshot all the time：

```
[2023-02-26T01:45:22.957836057Z INFO solana_validator::bootstrap] Searching for an RPC service with shred version 11762 (Retrying: No snapshots available)...
[2023-02-26T01:45:22.957917881Z INFO solana_validator::bootstrap] Total 206 RPC nodes found. 0 known, 0 blacklisted
```

What parameter is it?  Pls give me help! thankcccccc~

**Comment by bw-solana** [comment]
I believe the possible candidates are getting filtered out by `retain_peer_snapshot_hashes_that_match_known_snapshot_hashes`

Known validators snapshot hashes don't match the RPC peers snapshot hashes

**Comment by zhy827827** [comment]
Remove：
--expected-shred-version 11762  
          --known-validator ChorusmmK7i1AxXeiTtQgQZhQNiXYU84ULeaYF1EH15n \
          --known-validator EvnRmnMrd69kFdbLMxWkTn1icZ7DCceRhvmb2SJXqDo4 \

**Comment by bw-solana** [comment]
> but  solana can't catch up with block height！
> 
> [ERROR] Solana Height diff mainnet:2697
> 

Does the node ever catch up? As of now, it's not uncommon to start a few thousand slots behind the cluster. Once repair based shred insertion subsides (and turbine based shred insertion takes over), the node often starts catching up quickly

**Comment by bw-solana** [comment]
Here's the function that computes the shred version:
```
pub fn compute_shred_version(genesis_hash: &Hash, hard_forks: Option<&HardForks>) -> u16 {
    use byteorder::{ByteOrder, LittleEndian};

    let mut hash = *genesis_hash;
    if let Some(hard_forks) = hard_forks {
        for (slot, count) in hard_forks.iter() {
            let mut buf = [0u8; 16];
            LittleEndian::write_u64(&mut buf[..8], *slot);
            LittleEndian::write_u64(&mut buf[8..], *count as u64);
            hash = extend_and_hash(&hash, &buf);
        }
    }

    version_from_hash(&hash)
}
```
Setting `expected--shred-version` will ensure you're getting what you expect from peers
