### ISSUE TITLE
Ledger Tool Warts

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#30531]
#### Problem
There are things about `solana-ledger-tool` that impede ledger analysis and snapshot generation, especially in an urgent situation like a cluster restart. This is a kitchen-sink issue for these warts to be recorded; can be split out to separate issues later.

- [ ] Ledger-tool should check path permissions and writeability before executing any long-running operations
- [ ] On `create-snapshot`, consider handling of shreds from forks, non-ancestor snapshots
- [ ] Filter metrics logs by default?
- [x] Disable compaction by default in `purge` command
    - **v1.14**: https://github.com/solana-labs/solana/pull/30965
    - **master**: https://github.com/solana-labs/solana/pull/30891
- [x]  Avoid use of `/tmp/` path (several operators saw failures for disk out of space)
  - **master**: https://github.com/solana-labs/solana/pull/30707 (Would also need to BP https://github.com/solana-labs/solana/pull/29975)
  - **v1.14**: https://github.com/solana-labs/solana/pull/33225
- [x] Enable use of `--accounts` flag for all commands, not just those with `Primary` Blockstore access
    - **v1.14**: https://github.com/solana-labs/solana/pull/30754 
    - **master**: https://github.com/solana-labs/solana/pull/30228 and https://github.com/solana-labs/solana/pull/30236
- [x] Ledger-tool throws `Failed to analyze unsupported transaction` warnings about VersionedTransactions (in print command)
    - **v1.14**: https://github.com/solana-labs/solana/pull/30705
    - **master**: https://github.com/solana-labs/solana/pull/30575
- [x] Make ledger-tool retain all snapshots / avoid purging snapshots by default (see svenski123's comment below)
    - **v1.13**: https://github.com/solana-labs/solana/pull/30768
    - **v1.14**: https://github.com/solana-labs/solana/pull/30539
    - **master**: Previously done in https://github.com/solana-labs/solana/pull/27788
- [x] ~~Ledger-tool should support full and incremental snapshots in different locations~~
    - This is not an actual issue as noted in [comment below](https://github.com/solana-labs/solana/issues/30531#issuecomment-1445955901)
    - **v1.13**: Neither ledger-tool or validator support independent location
    - **v1.14**: Both ledger-tool and validator already support independent locations
    - **master**: Both ledger-tool and validator already support independent locations

**Comment by svenski123** [comment]
Ledger tool create-snapshot automatically purges "older" snapshots from the snapshot output directory which can unfortunately include the snapshot it just created. A command called "create-snapshot" should never delete snapshots

**Ledger tool log output**
```
[2023-02-25T21:22:15.863636691Z INFO  solana_runtime::snapshot_utils] Generating snapshot archive for slot 179526403
[2023-02-25T21:33:04.327841570Z INFO  solana_runtime::snapshot_utils] Purging old snapshot archives in snapshots-out, retaining up to 2 full snapshots and up to 4 incremental snapshots
[2023-02-25T21:33:06.504541765Z INFO  solana_runtime::snapshot_utils] Successfully created "snapshots-out/snapshot-179526403-FUdrVxEUnbp4AzZ5qNPgYB3viRQEGo2n1xq5n382Y8sC.tar.zst". slot: 179526403, elapsed ms: 650560, size=41430958346
Successfully created snapshot for slot 179526403, hash 69p75jzzT1P2vJwVn3wbTVutxHDcWKAgcbjqXvwCVUDE: snapshots-out/snapshot-179526403-FUdrVxEUnbp4AzZ5qNPgYB3viRQEGo2n1xq5n382Y8sC.tar.zst
Shred version: 56177
```
**Generated snapshot has been deleted**
```
$ ls -l snapshots-out/snapshot-179526403-FUdrVxEUnbp4AzZ5qNPgYB3viRQEGo2n1xq5n382Y8sC.tar.zst
ls: cannot access 'snapshots-out/snapshot-179526403-FUdrVxEUnbp4AzZ5qNPgYB3viRQEGo2n1xq5n382Y8sC.tar.zst': No such file or directory
```
**Two previously generated snapshots at higher slot numbers remain**
```
$ ls -l snapshots-out
total 83197212
-rw-r--r--. 1 solana solana 43726124195 Feb 25 16:23 snapshot-179526408-9kUTC2pYALrYD8rb93E1mY2vG4QG8jCX132Z4CEhBHgJ.tar.zst
-rw-r--r--. 1 solana solana 41467815091 Feb 25 21:44 snapshot-179526412-HEVzdwwhxTAR8n7D7ged5KvHhCDvxfKgYZfJY28qf9Xb.tar.zst
```

**Comment by steviez** [comment]
> Ledger-tool should support full and incremental snapshots in different locations

This is incorrect, `ledger-tool` and `solana-validator` are consistent with each other across versions.
- v1.13 ledger-tool and validator do NOT support different locations
- v1.14+ ledger-tool and validator support different locations due to https://github.com/solana-labs/solana/commit/2fa9bc3e709

**Comment by steviez** [comment]
> A command called "create-snapshot" should never delete snapshots

I came to a similar conclusion a while back and made https://github.com/solana-labs/solana/pull/27788 but this PR was never backported. I can't remember if not backporting was an oversight on my end or if it was deemed not critical enough to warrant a backport (this was around the time when we were trying to stabilize MNB on QUIC and every backport was under intense scrutiny so I might have just passed this one off)

> especially in an urgent situation like a cluster restart

This became much more apparent this last restart, and moving forward, ledger-tool bug fixes (and possibly improvements) should definitely be backported.

**Comment by ryoqun** [comment]
how about these?:

- [ ] don't use `/tmp` at all inside snapshot creation. (i saw people was troubled with NOSPC in /tmp/)...
- [ ] Change default behavior not to do compaction by default. i.e enable `--no-compaction` by default (iirc, v1.14+'s validator startup always skips compaction. but other non-important code path still does the potentially long compaction. like `solana-ledger-tool purge`...

**Comment by steviez** [comment]
> how about these?:

Agreed on both of these, copying them from your comment up to the top level TODO list.
