### ISSUE TITLE
My NFT file is not loading

### ISSUE THREAD

**Issue by blockfy20** [solana-labs/solana#30542]
Hi There,

I used NFT storage to store my NFT file, and my NFT file type is GLB. My all NFT was loading correctly and displayed in Solscan well. But few days ago I noticed it's not loading and when I search GLB file link, it will receive "Gateway Time-out". This is my collection and all nfts are loading well in open sea but I think it's previous loaded cash https://opensea.io/collection/blockfy-nft

Please assist to solve this problem.

Thank you

**Comment by CriesofCarrots** [comment]
Sorry, we don't offer general technical support here. This repository is for the labs solana-validator client and supporting crates. If the bug is in solscan's display, you'll need to contact them.
