### ISSUE TITLE
Feature Gate: Remove unnecessary check in loading of upgradeable program account

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#30559]
### Description

The `accounts.rs` code currently checks if the message includes upgradeable loader key, if an upgradeable program is being loaded for writing. The check looks necessary and harmless at quick glance. But its unnecessary, as the transaction will fail due to other checks in the execution. The check is making it harder to refactor the code for the runtime V2/Cache replacement (#29803). This feature gate is needed to remove this check consistently across the network.

### Feature ID

5ZCcFAzJ1zsFKe1KSZa9K92jhx7gkcKj97ci2DBo1vwj

### Activation Method

Single Core Contributor

### Testnet Activation Epoch

530

**Comment by Lichtso** [comment]
Cleaned up in #34840
