### ISSUE TITLE
Can not deploy Solana Program: Error: Data writes to account failed: Custom error: Max retries exceeded

### ISSUE THREAD

**Issue by MBenz12** [solana-labs/solana#30578]
I have a problem when trying to deploy a solana program. It repeat
`0.0% | Waiting for next block, 196 pending...   [block height 162745398; re-sign in 257 blocks] `
until
`Error: Data writes to account failed: Custom error: Max retries exceeded `
the version I use:
```
anchor-cli 0.26.0
solana-cli 1.14.16 (src:0fb2ffda; feat:3488713414)
```
please help me to deploy

**Comment by MBenz12** [comment]
I am using ubuntu 22.04
should I use 20.04?

**Comment by AlexiaM07** [comment]
Hello @MBenz12, have you been able to resolve this issues yet?

**Comment by MBenz12** [comment]
thanks for your consideration
I just fixed it, I reinstalled ubuntu and it worked.
but not sure about the original reason
I can find the same issues for other users, but not sure about the exact reasons.
