### ISSUE TITLE
快高度

### ISSUE THREAD

**Issue by Jackiewangjie** [solana-labs/solana#30592]
我部署的solana节点块，总是追不上高度，总是差3500-4000个块高度，这个什么好的解决办法吗。

**Comment by cavemanloverboy** [comment]
你在使用间歇泉插件吗？

如果不是，您的计算机规格是什么？

**Comment by Jackiewangjie** [comment]
aws ec2，32core，mem：256g，

**Comment by bw-solana** [comment]
How long has the validator been running? We have seen cases of an hour or more to catchup to the cluster when downloading snapshot.

Can you provide the pubkey for your node so we can look at metrics?

**Comment by Jackiewangjie** [comment]
> How long has the validator been running? We have seen cases of an hour or more to catchup to the cluster when downloading snapshot.
> 
> Can you provide the pubkey for your node so we can look at metrics?

half of an hour to catchup to the cluster.
Metrics？I do not understand what you mean.

**Comment by bw-solana** [comment]
> half of an hour to catchup to the cluster. Metrics？I do not understand what you mean.

One option that can improve startup time is the --accounts-db-skip-shrink flag. This will prevent blocking on cleaning/shrinking accounts. Note: It can result in more load during runtime and unpredictable performance.

If your node is configured for it, it will push metrics into an influx database that can be used to understand what is bottlenecking startup.
