### ISSUE TITLE
[Feature Request] Blockhash expired. 5 retries remaining.

### ISSUE THREAD

**Issue by 0xtrou** [solana-labs/solana#30642]
#### Problem

Deploying/Upgrading contracts these days was a nightmare for me.

The problem came from the `Max Retries` policy. Even with the progress at ~80%, it can be failed. Since my contract needs to send over ~600x transactions, it takes approx 10 minutes a time. 

Then I must deploy the contract all day if the deployment/upgrade won't succeed due to the retries policy.

#### Proposed Solution

Probably I need a custom retries policy that can be configurable. For example: 

`solana program deploy target/deploy/<my-program>.so --buffer <buffer-seed-path> -k <keypair-path> -u mainnet-beta --max-retries 20`

**Comment by 0xTraderTrou** [comment]
<img width="836" alt="image" src="https://user-images.githubusercontent.com/109982124/223695762-b1eea819-2103-4de2-a771-d84ea0172aae.png">
look at this, this failed at ~80% again

**Comment by 0xTraderTrou** [comment]
<img width="716" alt="image" src="https://user-images.githubusercontent.com/109982124/224217834-2a7094e6-495e-4c62-9b10-d61303b18652.png">
I'm using the latest one

> which solana version are you on?
> 
> I was on 1.15.2 and it was veeery slow. I installed 1.14.7 it got better.

**Comment by rahulkp220** [comment]
This is annoying at this point.

**Comment by airicyu** [comment]
> which solana version are you on?
> 
> I was on 1.15.2 and it was veeery slow. I installed 1.14.7 it got better.

guys, i hit this issue as well. And i followed previous comments to use 1.14.17, and the deploy is obviously smoother.
This is a workaround. But I think the maintainers should look at this issue and make some proper fix for 1.15.2.

**Comment by b1acKr0se** [comment]
This needs more attention.

**Comment by crypt0miester** [comment]
> This needs more attention.

this needs priority fees.

**Comment by b1acKr0se** [comment]
> > This needs more attention.
> 
> this needs priority fees. its on its way.

I had to downgrade to 1.14 yesterday to be able to deploy my program. The DX needs more serious improvements.

**Comment by algotradingstrategies** [comment]
Having the same issue. solana-cli 1.18.4  . If I downgrade to 1.14, and run   solana program deploy --buffer recover.json target/xxxx again, will it resume fine? (Don't want to lose the 1+ SOL I already spent on it )

**Comment by b1acKr0se** [comment]
> Having the same issue. solana-cli 1.18.4 . If I downgrade to 1.14, and run solana program deploy --buffer recover.json target/xxxx again, will it resume fine? (Don't want to lose the 1+ SOL I already spent on it )

Yes, it will work, but it does not exactly resume the deployment, all it does is skipping the first transaction to create and initialize the buffer account (which stores your SOL), all the other transactions to upload the program binary will be restarted from scratch.

**Comment by algotradingstrategies** [comment]
Unfortunately, that didn't solve my problem. I downgraded solana to to 1.14.1. 

But then when running "anchor build", I get 
"error: package `borsh-derive v1.3.1` cannot be built because it requires rustc 1.67.0 or newer, while the currently active rustc version is 1.62.0-dev"  (as well as for other packages). 

I also tried deploying the version I build with solana 1.18.4 (i.e. "anchor build" under 1.18.4, then downgarde to 1.14.1 and "anchor deploy" without running "anchor build" first). But that also didn't work ("Error: Pubsub error: ConnectionError(Protocol(ResetWithoutClosingHandshake)). There was a problem deploying:")

Any ideas how can I get my program deployed?

**Comment by moon-ferry** [comment]
anyway to import my solana cli wallet to other wallets extension on chrome ?

**Comment by rcolomina** [comment]
Same here, I am having blockhash expired. It seems to be really slow even using a non public RPC.

**Comment by joncinque** [comment]
This was fixed in https://github.com/anza-xyz/agave/pull/364 and https://github.com/anza-xyz/agave/pull/277, among others. Please upgrade to 1.18.8 and set your priority fees as you wish

**Comment by georgiod9** [comment]
> Having the same issue. solana-cli 1.18.4 . If I downgrade to 1.14, and run solana program deploy --buffer recover.json target/xxxx again, will it resume fine? (Don't want to lose the 1+ SOL I already spent on it )


you can recover your "lost" sol. In your case, the deployment has likely failed and the sol is stored in the buffer account. You can retrieve it with:
```
solana program close --buffers
```

You can also list the buffer accounts that exist:
```
solana program show --buffers
```
