### ISSUE TITLE
How can a validator comfirm a poh from the leader?

### ISSUE THREAD

**Issue by lurais** [solana-labs/solana#30651]
#### Problem
The validator don't have the fully data .how can a validator comfirm a poh from the leader? What if the leader is evil and make some fake transactions? And why don't use just pos instead poh? Does the poh is really necessary? Where I can find some info about these questions as I can not find the info in the doc?

**Comment by bw-solana** [comment]
These seem like great questions to ask over at the [Solana Stack Exchange](https://solana.stackexchange.com)

**Comment by lurais** [comment]
> These seem like great questions to ask over at the [Solana Stack Exchange](https://solana.stackexchange.com)

@bw-solana Thanks for your help

**Comment by lurais** [comment]
> These seem like great questions to ask over at the [Solana Stack Exchange](https://solana.stackexchange.com)

@bw-solana @CriesofCarrots  but no one talk about that https://solana.stackexchange.com/questions/6100/how-can-a-validator-comfirm-a-poh-from-the-leader
