### ISSUE TITLE
Use Drop trait instead of Service for cleanup

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#3065]
#### Problem

`Service::join` isn't compatible with `Drop::drop`, and it would be cleaner to use the simple Drop trait to cleanup all the threads and system resources.  `Service::join` takes a `self`, while `Drop::drop` requires a `&mut self`.

#### Proposed Solution

* Refactor the `Service::join` to be Drop trait compatible.  
* Service should also have an `exit` method to signal the exit, but not do a synchronous join

Drop could be implemented for all objects that implement Service, by calling `Service::exit` then `Service::join`.

**Comment by mvines** [comment]
Most services now receive an exit boolean flag at construction that is used to signal a shutdown by the caller.   So such services no longer need an `exit` method (and I've recently removed most of them) -- instead the shutdown protocol is the caller sets the exit flag, then `join` (or Drop) the service

**Comment by aeyakovenko** [comment]
@mvines ah right.  So we need 3 things

* Service to support `exit` and `join`.  
* Drop to implement `close`

The problem is that `Drop` works over a `&mut self` but `join` requires a `self`

**Comment by svenski123** [comment]
Is this still wanted?
I see no `Service` trait but a bunch of types which end in `Service`, have an `Arc<AtomicBool>` and close(), join(), exit() etc. so I presume these are the intended targets.
The join() methods return a `Result` which you won't get if it's dropped (I gather not an issue though).
Looks like `core/src/local_vote_signer_service.rs` can go - no reference to `LocalVoteSignerService` anywhere.
Some join() methods (i.e. PubSubService) don't set the exit flag and so would block forever if caller is not careful - same would apply in a Drop implementation.
Finally dropped JoinHandles apparently detach the thread (accord to rust docs) - would a Service thread ever need to be detached? (I gather no but the question needs asking).

Apologies if questions above are disjoint - this looks straightforward to crank out (... famous last words ...).

**Comment by aeyakovenko** [comment]
@svenski123 might not be relevant anymore.  It's usually a footgun to try to cleanup threads in an object destructor.  I am not sure you'll succeed given how gnarly some of the service dependencies have become.
