### ISSUE TITLE
Set up leader on cloud service

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#307]
- [x] Choose a cloud service
- [x] Open UDP ports up, 8000-10000 to public
- [x] Allocate an IP address
- [x]  testnet.solana.com should resolve to the leader in the world
- [ ] the crdt may need to handle virtual and physical addresses

**Comment by aeyakovenko** [comment]
@mvines I have a google cloud quota set up.  lets just use that.

**Comment by mvines** [comment]
Do we want a couple leaders?
1. A `HEAD` leader that auto updates/restarts on every new commit into the `master` branch (or perhaps updates nightly)
2. A more "stable" leader that is updated whenever a new release is tagged

We could start with (1) initially either way.

**Comment by mvines** [comment]
Recommended GPU size is 4 x K80

**Comment by mvines** [comment]
testnet.solana.com is now configured from the infra side.  It points to a GCP static address with w/ rsync and UDP port firewall rules setup.   The VM that currently backs it is *not* ready for use yet, please stay clear for a while long.  🚧

**Comment by mvines** [comment]
This is all done from the infra side.  Filed #458 for the remaining runtime issue
