### ISSUE TITLE
Replace current VOB mode with dialing back to 25% CU and only send 1 block in 4-block leader slot

### ISSUE THREAD

**Issue by wen-coding** [solana-labs/solana#30777]
#### Problem
When the local tower distance is very large, meaning we are not confirming new blocks in a normal speed, it's probably wise to not pound the system with too many new blocks.

Currently we will be in VOB mode, this helps save some resource, but block distribution and confirmation itself consumes quite some resources, so this isn't enough to save us in the past outages (outage [20230225](https://solana.com/news/04-30-22-solana-mainnet-beta-outage-report-mitigation), [20220430](https://solana.com/news/04-30-22-solana-mainnet-beta-outage-report-mitigation)). This would not help much if there is significant consensus mismatch (outage [20220930](https://solana.com/news/09-30-22-solana-mainnet-beta-outage-report) and outage [20220601](https://solana.com/news/06-01-22-solana-mainnet-beta-outage-report-2)) though, but fewer new blocks there also will not make things worse.

Here we will try to shrink CU to 1/4 and only send 1 block in 4-block leader slot, hopefully this can shed enough load to help ensure that the system can survive whatever event is hammering the system.

#### Proposed Solution
Change current VOB mode (shrink CU to 0%) to: shrink CU to 25% and only send 1 block in 4-block leader slot. This way hopefully we can shed enough load so the system can survive under extreme load.

This behavior is different from current VOB mode because we are shrinking CU to 25% instead of 0%, if there is an outage, we would find the highest optimistically confirmed slot and manually restart from there. VOB may help us a little there because we can safely discard vote only banks without impacting users, but if there is a manual restart and snapshot generation, the help from VOB shouldn't be that big. The chance a user has a VOB bank locally is similar to a CU 25% bank. Also, VOB mode is bad for defi, they need some minuscule amount of transactions to keep working.

**Comment by mvines** [comment]
I feel like some of the motivation for this change is missing from the description.

> Currently we will be in VOB mode, this helps save some resource, but block distribution and confirmation itself consumes quite some resources, so this isn't enough to save us in the past outages

If this is the sole concern, retaining the existing VOB while cutting block production to 25% would be a better way to achieve it. *Adding* 25% of CUs in addition will increase resource usage, as votes will still need to land.

**Comment by wen-coding** [comment]
Good point, I added Anatoly's feedback that defi needed some tiny amount of transactions to keep working to the description.

**Comment by wen-coding** [comment]
We are planning to use wen_restart instead. https://github.com/orgs/solana-labs/projects/46
