### ISSUE TITLE
Clean up Blob header

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#308]
Clean up the `Blob` header. It's currently a set of methods on `Blob` to get the sender's ID and index.

The header is embedded into the blob data in an awkward way.  The streamer interfaces that use them sometimes use the header and sometimes clobber it with data.

**Comment by garious** [comment]
@aeyakovenko, this ticket describes the current set of affairs, but not what should be done, or why do it? Can you please comment here?

**Comment by aeyakovenko** [comment]
edited issue

**Comment by aeyakovenko** [comment]
I don't think this is critical, lets move it to 0.8.0

**Comment by garious** [comment]
@aeyakovenko, want this ticket?

**Comment by garious** [comment]
@aeyakovenko, ping

**Comment by aeyakovenko** [comment]
I am not sure what t should be. @rob-solana @pgarg66 have been hacking close to this. I think they can take it over

**Comment by rob-solana** [comment]
I'd like to make packet and streamer run on generics and get rid of all the blob<->packet replicode.  Which I think is a precursor to erasure cleanup.

**Comment by garious** [comment]
@rob-solana, what are the odds this work makes it into the Beacons release?

**Comment by rob-solana** [comment]
1 in 2

**Comment by garious** [comment]
This is a poorly written, vague, task-oriented ticket with multiple assignees (which historically has meant nobody does it). I'll create a new one for the blob<->packet replicode.
