### ISSUE TITLE
Snapshot compatibility between versions/builds is not tested

### ISSUE THREAD

**Issue by brooksprumo** [solana-labs/solana#30858]
#### Problem

There are not automated tests that ensure snapshots are compatible between builds/versions. If incompatibility is introduced, it is not caught until runtime, which is more painful to debug.

Specifically

* snapshots created by `edge` must be compatible with `beta`
* snapshots created by `beta` must be compatible with `stable`
* it would be good for snapshots to be compatible from build-to-build on `master` as well

This compatibility needs be in both directions.

#### Proposed Solution

Add an automated test to:

* spin up a local cluster
* run a node (1) with the commit from the PR
* have the node generate snapshots (full and incremental)
* startup another node (2) *from the previous commit* and snapshots from node (1)
* startup another node (3) *from the previous version* and snapshots from node (1)
* restart node (1) with new snapshots from node (2)
* restart node (1) with new snapshots from node (3)

**Comment by t-nelson** [comment]
seems like we should be able to skip the local-cluster and all the node ops flakiness. instead craft a `GenesisConfig` with minimal accounts to fully exercise snapshot compatibility, make a `Bank` from it and immediately write it out to a snapshot. do the same as part of the release process for beta and stable tags, upload the artifacts somewhere ci can get to them later.  pull down latest test_snapshot and ledger-tool bin for each, then attempt to load every permutation of (ledger-tool, test_snapshot)
