### ISSUE TITLE
Publishing validator info is failing due to keybase.pub sunset

### ISSUE THREAD

**Issue by saberistic** [solana-labs/solana#30898]
#### Problem

Running
`solana validator-info publish --keypair validator-keypair.json "Baxus Devnet Validator" -n baxus -w "https://sol-dev.baxus.co"`

 I am getting this error

`Error: Bad parameter: Invalid validator keybase username: error sending request for url (https://keybase.pub/baxus/solana/validator-7yMMUa153jRnkdnQMyiccvzdz66qxwR7b5mPPGsHNdS8): error trying to connect: dns error: failed to lookup address information: No address associated with hostname`

It looks like keybase has stopped their web file service and this will fail no matter what. Documents also pointing to this solution that needs to get updated.
 
#### Proposed Solution
Not sure if I fully understand the complexity of this but one solution could be simply relying on a DNS record verification or similar.

**Comment by mvines** [comment]
Keybase was shut down recently unfortunately. We probably just need to remove the keybase integration entirely

**Comment by saberistic** [comment]
that sounds about how I was thinking. How do you wanna approach publishing validators info then?

**Comment by mvines** [comment]
I’m hoping the validator community can decide how they want to do it going forward

**Comment by Digitalenergyllc** [comment]
I've been having the same issue.  Is this also where I would have been able to upload a profile image/logo for my validator?  I was able to publish my name and website.  However, same issue with regards to --keybase username.  Thanks in advance.  Frank

**Comment by tigarcia** [comment]
Resolved in https://github.com/solana-labs/solana/pull/31852
