### ISSUE TITLE
Vote Program should have an Instruction to authorize a vote signer

### ISSUE THREAD

**Issue by sagar-solana** [solana-labs/solana#3092]
#### Problem

Vote program requires `Vote` instructions to be signed by the vote account keypair. Instead it should only enforce that if the transaction isn't signed by the Authorized Vote Signer. 

#### Proposed Solution

Vote program should have an AuthorizeVoteSigner(Pubkey) instruction.  key[0] in `Vote` instructions only needs to be signed if not signed by that key.

**Comment by sagar-solana** [comment]
@garious, a qq about this. I left wording the same as your comment earlier.

> key[0] in Vote instructions only needs to be signed if not signed by that key.

Instructions aren't signed individually right? Does this line mean " Key[0] in Vote instructions only needs to be the _signer_ if the _transaction_ is not signed by the Authorized Vote Signer " ?

**Comment by garious** [comment]
A transaction may include zero or more signatures. BuilderInstruction can specify which instructions require a signature. We may find it simplest to have two separate Vote instructions. The current one requires the staker's signature. A new instruction might require the signature of only the second key, the "authorized vote signer".  The vote account would still be in `key[0]`, but would not require a corresponding signature.

**Comment by garious** [comment]
Looks like you only need a new constructor, not a new instruction. The current one is correct:

https://github.com/solana-labs/solana/blob/master/programs/vote_api/src/vote_instruction.rs#L52

`new_authorized_vote` would look like this:

```rust
BuilderInstruction::new(id(), &VoteInstruction::Vote(vote), vec![(vote_account_id, false), (authorized_voter_id, true)])
```

where `vote_account_id` is annoyingly still called `vote_id` and should be called `staker_id` and where `authorized_voter_id` should be called `voter_id`.

I'd highly recommend changing the name of "vote" program to "stake" program before doing any of this work. Then we can update this ticket to stop doing all the terminology gymnastics.

**Comment by sagar-solana** [comment]
@garious, Agreed on all naming stuff. I will be using `staking_id` instead of `staker_id` though. Staker isn't really in the picture here afaik. 

I think we'd still need a new instruction or we'll end up with ugly checks for the keyed_accounts' length inside `vote_state::process_vote`

**Comment by garious** [comment]
I know it's a little weird, but even though we'll have a `staking_account`,  the owner of its pubkey should be called `staker_id`, not `staking_id`.

A separate instruction isn't needed and you won't need a length check. If the account specifies a signer, then we'll look for that `key[1]` signature, otherwise look for a `key[0]` signature.

**Comment by sagar-solana** [comment]
D'oh!, you're right. 

I get what you're saying with `staking_id`, but `vote_account_id` is the account id of the staking account itself. Not the staker right?

**Comment by garious** [comment]
They are precisely the same.

**Comment by sagar-solana** [comment]
Already implemented afaik.
