### ISSUE TITLE
Rust BPF: Add support for float and signed division

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#3102]
#### Problem

The BPF instruction set does not contain a signed-division instruction and Rust's use of floats includes code that attempts to generate one.  Either the Rust code needs to be rewritten, the LLVM back-end needs to compensate and lower those operations to something compatible, or BPF must add a new instruction to support it.  Currently, floats are mostly disabled in the core libraries.

**Comment by dmakarov** [comment]
This is related to #17793.
