### ISSUE TITLE
cargo build fail 

### ISSUE THREAD

**Issue by dorname** [solana-labs/solana#31060]
![image](https://user-images.githubusercontent.com/49684048/230008623-8001cf33-2b03-4e84-9666-6091d9fcec54.png)
BPF SDK: /home/kyle/.local/share/solana/install/releases/stable-616d8d67978c325087cc5a9f33307f54eee48b6e/solana-release/bin/sdk/bpf
Failed to install bpf-tools: Unable to write "/home/kyle/.cache/solana/v1.27/bpf-tools/tmp-solana-bpf-tools-linux.tar.bz2": Custom { kind: Other, error: reqwest::Error { kind: Body, source: hyper::Error(Body, Custom { kind: UnexpectedEof, error: IncompleteBody }) } }

**Comment by dorname** [comment]
should I open a issue here ?
Really need some help

**Comment by dorname** [comment]
I can manual download it 
but through cargo always has this problem?
its a network problem?

**Comment by dmakarov** [comment]
If you can manually download it, untar it in `/home/kyle/.cache/solana/v1.27/bpf-tools`

```
cd /home/kyle/.cache/solana/v1.27/bpf-tools
tar xjf solana-bpf-tools-linux.tar.bz2
```

**Comment by dmakarov** [comment]
Also try removing previous download
```
rm -f /home/kyle/.cache/solana/v1.27/bpf-tools/tmp-solana-bpf-tools-linux.tar.bz2
```
