### ISSUE TITLE
[wip] migrating the docs to a different repo

### ISSUE THREAD

**Issue by nickfrosty** [solana-labs/solana#31085]
**Note:** This issue is to help track ideas and the conversation around moving Solana docs out of this monorepo. 

### Problem

Several people have expressed different ideas and concerns about the docs being inside this monorepo and migrating them outside of it. Below are some of these collected ideas, in no particular order, on this "docs migration".

#### 1. General solana docs vs labs validator client docs

Segmenting some of the pages of the current monorepo docs into two primary categories:
- general solana information, ("common docs")
- and the labs validator specific pages

The end result would have these two groups of docs living in different places, and published on different domains. And would need a review of all the current docs to determine which pages would go where.

#### 2. SPL docs

Note: Not technically part of this monorepo's docs, but related enough I thought worth mentioning here as well.

Migrating some portion (or maybe all?) of the spl docs into the same site that houses the "common docs". This would aid people finding all the solana docs in one place. 

### Other things to consider

- other clients, like Firedancer. their design decisions and how they may fit into solana docs
- searchability and discoverability of the various docs being on separate domains

**Comment by bw-solana** [comment]
Playing devil's advocate.. by having the "common docs" in the monorepo, it's much easier to keep them in sync with the behavior of the underlying code. General information definitely makes sense to punt out of the monorepo

**Comment by mvines** [comment]
Here are some of the top-level doc categories that I feel could be evicted from the monorepo to start with:

1. https://docs.solana.com/introduction
1. https://docs.solana.com/cluster/overview (partial)
1. https://docs.solana.com/wallet-guide
1. https://docs.solana.com/developers
1. https://docs.solana.com/economics_overview
1. https://docs.solana.com/integrations/exchange
1. https://docs.solana.com/integrations/retrying-transactions

JSON RPC API probably remains associated with the Labs client for now. Likewise the [CLI](https://docs.solana.com/cli)

**Comment by nickfrosty** [comment]
@bw-solana while yes, it would in theory be easier to keep all the various docs in sync if they were all in the same mono repo. 

But the majority of the "common docs" don't really get changed that much. They really only get some small minor changes over a several month period.

When a more sizable change gets made to the content that would be normally included within these common docs, it is usually a slower rollout. For example: prioritization fees.

**Comment by nickfrosty** [comment]
@mvines I agree with most of your listed recommendations to remove from the mono repo, with a few comments:

For `/developers` - are you saying to remove all the "developer" doc files that are in the [`docs/src/developing`](https://github.com/solana-labs/solana/tree/master/docs/src/developing) directory?

From a content discovery and UX perspective, I think having the RPC pages together with the common docs makes a lot of sense. I understand why you want them to with the labs client, both for keeping it correctly in sync with the labs client work and the potential for other validator clients (e.g. TinyDancer) having different RPC methods/API.

We could always keep the RPC pages in the mono repo at first? At least until further discussions are made around a specific spec for RPC API support?

If there was an accepted spec for the RPC API, do you see any reason to not have it with the rest of the "common docs"?

**Comment by mvines** [comment]
> If there was an accepted spec for the RPC API, do you see any reason to not have it with the rest of the "common docs"?

Nope. That'd be perfect in that case.

> We could always keep the RPC pages in the mono repo at first? At least until further discussions are made around a specific spec for RPC API support?

Yep that's what I was thinking too.

> For /developers - are you saying to remove all the "developer" doc files that are in the [docs/src/developing](https://github.com/solana-labs/solana/tree/master/docs/src/developing) directory?

More or less, yeah. This content seems to be pretty common
