### ISSUE TITLE
Rust BPF: Rust BPF modules don't depend directly on the Solana SDK definitions for account, Pubkey, etc...

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#3111]
#### Problem

The Solana SDK depends on the Rust standard libraries and Rust BPF programs cannot.

#### Proposed Solution

Extract `no_std` versions of Solana SDK types needed by Rust BPF programs and make them available to both Solana and Solana's Rust BPF programs.

**Comment by garious** [comment]
If it helps, you can rip GenericArray out of Pubkey. We don't make use of that. It's an artifact of the earliest days where we used the size of the GenericArray to avoid accidentally mixing arrays with pubkeys and arrays with signatures.
