### ISSUE TITLE
`solana-metrics` can't be compiled for wasm

### ISSUE THREAD

**Issue by nevi-me** [solana-labs/solana#31182]
#### Problem

`solana-metrics` depends on `gethostname` https://github.com/solana-labs/solana/blob/master/metrics/Cargo.toml#L14.
This causes issues when compiling for wasm32 targets if some other crate relies on solana-metrics.

In my instance, the address lookup program includes solana-metrics via the below dependency tree:

```
gethostname v0.2.3
└── solana-metrics v1.14.13
    └── solana-program-runtime v1.14.13
        └── solana-address-lookup-table-program v1.14.13
```

I'm building a crate which relies on the lookup program as it imports a program that uses the lookup program, and compiling it for wasm causes the below issue.

```
@jet-lab/margin:build: error[E0425]: cannot find function `gethostname_impl` in this scope
@jet-lab/margin:build:   --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/gethostname-0.2.3/src/lib.rs:58:5
@jet-lab/margin:build:    |
@jet-lab/margin:build: 58 |     gethostname_impl()
@jet-lab/margin:build:    |     ^^^^^^^^^^^^^^^^ not found in this scope
@jet-lab/margin:build: 
```

I first checked with the author of gethostname if they would be willing to accept a contribution that creates a stub for `gethostname_impl()` above, however their position is that it's not the best place to fix this https://github.com/swsnr/gethostname.rs/issues/9.

#### Proposed Solution

I see 2 potential solutions:

1. Expand the feature gate at https://github.com/solana-labs/solana/blob/c847236147f5b2e7db57ef4e65fe0f0766091567/programs/address-lookup-table/Cargo.toml#L24 to also exclude wasm targets. I can do the work here and submit a PR.

2. Add a feature flag that allows us to opt in to the `processor` module on the lookup table program. The program-runtime crate is only used here https://github.com/solana-labs/solana/blob/c847236147f5b2e7db57ef4e65fe0f0766091567/programs/address-lookup-table/src/processor.rs#L9, and I'd imagine that most users of the lookup program wouldn't be interested in the processor (I think we'd be if running tests)

Option 2 is probably the easiest one

**Comment by kevinheavey** [comment]
Just commenting to remark that solana-metrics causes this kind of problem in many places. There are a lot of crates in this repo that would have nice dependencies if not for solana-metrics.

**Comment by wiseaidev** [comment]
I am getting this error msg using `solana-client` on a wasm target. Adding support for wasm would be awesome. Thanks!
