### ISSUE TITLE
Fix TPS regression

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#312]
A performance regression slipped in since v0.5.0. It's most likely in the BankingStage, but we need to isolate it and see what can be done about it.

**Comment by sakridge** [comment]
@garious have you checked the multithreaded fix we put in for the balances table?

**Comment by garious** [comment]
@sakridge, no, which are you referring to?

**Comment by sakridge** [comment]
commit 1acd2aa8cfa40a8fe8cb01d7ae78157651058998
Author: Greg Fitzgerald <garious@gmail.com>
Date:   Thu May 10 19:07:12 2018 -0600

    Fix race condition in Accountant::apply_payment()

**Comment by garious** [comment]
When there's a preexisting `to` account, that patch is a no-op.

**Comment by garious** [comment]
@sakridge says there was no measurable gain from his key-sharding experiments, which aimed to minimize thread contention for the account memory.

**Comment by sakridge** [comment]
@garious @aeyakovenko
Tried to shard on bits in the public key for apply_debits -> apply_payment call flow, but I didn't manage to rework the register_entry_id() so it was still taking a write-lock. Also, apply_credits could be sharded. 

Some results from https://github.com/solana-labs/solana/pull/411 :

Macbook Pro 2016 15", i7-6920HQ (2.9ghz, 4c, 8t)

test | pre opt (ns) | with opt (ns)
---- | ------------ | ---------
bench_process_transaction | 7,718,997 | 6,467,792
bench_banking_stage_multi_accounts | 611,069,540 | 68,183,547
bench_banking_stage_single_from | 237,442,138 | 58,952,941

Intel i7-5930k Haswell-E (3.5ghz, 6c, 12t) 'newton'

test | pre opt (ns) | with opt (ns)
---- | ------------ | ---------
bench_process_transaction | 6,707,948 | 3,093,161
bench_banking_stage_multi_accounts | 134,240,486 | 54,333,284
bench_banking_stage_single_from | 64,350,103 | 39,567,869

AWS p2.8xlarge, Intel Xeon CPU E5-2686 v4 (?c, 32t)

test | pre opt (ns) | with opt (ns)
---- | ------------ | ---------
bench_process_transaction | 9,070,171 | 4,074,513
bench_banking_stage_multi_accounts | 383,623,579 | 69,790,144
bench_banking_stage_single_from |  | 29,107,990

Intel Xeon E5-2620 v4 (2.1ghz, 8c, 16t)

test | pre opt (ns) | with opt (ns)
---- | ------------ | ---------
bench_process_transaction | 10,039,101 | 4,960,617
bench_banking_stage_multi_accounts | 202,239,418 | 88,446,154
bench_banking_stage_single_from | 95,234,199 | 49,350,139

**Comment by garious** [comment]
@sakridge, can you post newton to sagan TPS numbers here so we can close this ticket?

**Comment by sakridge** [comment]
`Highest TPS: 270133.73 sampling period 1s total transactions: 4947370 clients: 1`

**Comment by sakridge** [comment]
Are we good with that?

**Comment by garious** [comment]
Yes, perfect. Thanks so much for all this work!
