### ISSUE TITLE
Feature Gate: Clean up delegation errors

### ISSUE THREAD

**Issue by 2501babe** [solana-labs/solana#31206]
### Description

see #31202

### Feature ID

Bj2jmUsM2iRhfdLLDSTkhM5UQRQvQHm57HSmPibPtEyu

### Activation Method

Single Core Contributor

### Minimum Beta Version

v1.14.18

### Minimum Stable Version

v1.14.18

### Testnet Activation Epoch

479

### Devnet Activation Epoch

521

### Mainnet-Beta Activation Epoch

490

**Comment by mvines** [comment]
Can the title be filled out here please, also add this new feature gate to the end of the big long table in https://github.com/solana-labs/solana/wiki/Feature-Gate-Activation-Schedule too 🧮
