### ISSUE TITLE
logsSubscribe method not allowing for multiple addresses

### ISSUE THREAD

**Issue by 0gf** [solana-labs/solana#31217]
#### Problem
According to the Solana documentation you should be able to listen to logs for multiple addresses (as base-58 encoded strings) using the [logsSubscribe](https://docs.solana.com/api/websocket#logssubscribe) Websocket method. Whenever calling this method with a RPC call such the one below it returns the message `'Invalid Request: Only 1 address supported'` - which is strange because the documentation states it should be able to do multiple addresses

Call:
```
   let subscription = JSON.stringify({
        "jsonrpc": "2.0",
        "id": 1,
        "method": "logsSubscribe",
        "params": [{
            "mentions": ["addressOne", "addressTwo"]
        }, {
            "commitment": "finalized"
        }]
    })

    socket.send(subscription);
```

#### Proposed Solution
Change documentation if it's just a typo, else fix the bug.

**Comment by CriesofCarrots** [comment]
It looks like this got rewritten in https://github.com/solana-labs/solana/pull/29772 to explicitly reference multiple pubkeys (cc @nickfrosty ). Currently the server implementation does only support one mentioned address; the array input type is so a longer list could be supported in the future.

A PR to clarify the docs would be most welcome.

**Comment by nickfrosty** [comment]
@CriesofCarrots I will get a PR out shortly to correct the docs.

**Comment by nickfrosty** [comment]
@0gf what version is your RPC provider using?
