### ISSUE TITLE
Add RPC call to estimate block time even when block is missing

### ISSUE THREAD

**Issue by refi93** [solana-labs/solana#31243]
#### Problem
The `getBlockTime()` call expects a block that exists in node's storage which isn't suitable e.g. to transform abitrary slots to time, e.g. if a wallet wants to show the user their staking rewards history. To tackle this, a wallet basically needs to first determine which slots contain a valid block with the `getBlocks` call for each slot, and even then some blocks may be missing from node's storage (https://support.quicknode.com/hc/en-us/articles/5793700679441-Why-are-slots-blocks-missing-on-Solana-) which makes fetching of such basic information quite cumbersome and inefficient

#### Proposed Solution
One solution I can think of is to introduce a more graceful version of the call, called e.g. `estimateSlotTime()` which would try to extrapolate the time for given slot taking into consideration existing block times, that would make retrieval of times for slots a lot easier and would be good enough for most usecases, where usually a few seconds or even hours of deviation usually don't matter that much

**Comment by mvines** [comment]
> https://support.quicknode.com/hc/en-us/articles/5793700679441-Why-are-slots-blocks-missing-on-Solana-

This help article is lacking a bit of precision:
a. slots don't go missing. a slot is a scheduled window of time in which a block may be produced.
b. blocks don't go missing or are skipped. block N is always built on block N-1, none are missed or skipped.

Rather not every slot produces a block that ends up being finalized into the permanent ledger history. It's subtle but an important difference from what that help article claims.

**Comment by refi93** [comment]
makes sense, still the `getBlockTime()` call, as per the docs, expects a slot (which may or may not have a block) and in practice, it seems to be pretty prone to return an error instead of a time as the slot may have been skipped or the respective block is missing for some reason from the RPC node's storage, or am I missing something?

**Comment by refi93** [comment]
> Your primary concern is around figuring staking rewards over RPC more efficiently right

Yes, that's the place where it currently hurts us the most, also determining epoch start to show it to the user is a bit awkward, but not so much
