### ISSUE TITLE
Feat: allow geyser to request account snapshot from validator

### ISSUE THREAD

**Issue by linuskendall** [solana-labs/solana#31242]
#### Problem

Currently if a geyser plugin wants to access account state outside of account state that has been updated it needs to use the JSONRPC api to fetch account state from the validator. This adds unnecessary serialization/deserialization of JSON data between validator and plugin. It would be handy if there was a way for plugin to ask the validator to deliver account state for example into the ACC stream.

#### Proposed Solution

A few different possibilities come to mind:

1) The admin socket could have a command that we can send to trigger delivery of account updates to the plugin in a similar way to how this happens during startup.

2) The plugin itself could request particular accounts, set of accounts or all accounts from the validator.

3) Geyser could have a hook into the account snapshotting routines so that when the validator generates an account snapshot to disk it also calls back to geyser (plugin could then decide what to do with the snapshot accounts, e.g. filter them).

4) Geyser could connect into the RPC client by having some kind of channel that it can send RPC requests to the validator over.

5) We do none of this and let geyser use JSONRPC to communicate with the validator. We can improve speed of this by adding unix socket support for IPC between plugin and validator.

**Comment by lijunwangs** [comment]
I am a little confused by the following ``` Currently if a geyser plugin wants to access account state outside of account state that has been updated it needs to use the JSONRPC api to fetch account state from the plugin. ``` I do not get the plugin need to access from the plugin part. Can you shed more light on the use case? Are you trying to support obtaining account state from your plugin which your plugin does not have handle and keep in the database?

**Comment by linuskendall** [comment]
> I am a little confused by the following `Currently if a geyser plugin wants to access account state outside of account state that has been updated it needs to use the JSONRPC api to fetch account state from the plugin.` I do not get the plugin need to access from the plugin part. Can you shed more light on the use case? Are you trying to support obtaining account state from your plugin which your plugin does not have handle and keep in the database?

Sorry I meant the `validator` :)

**Comment by lijunwangs** [comment]
Thanks, I understand now it is the plugin to load account state from the validator. But I am not sure I understand what is the use case making it necessary. At the validator startup, all accounts are notified from the snapshots. After that is finished, when the account is modified, it will be notified as well. So for such plugin, you should have all the state. I think what probably makes sense is the case, there was an account which you were not interested in earlier and at runtime decided to watch it and you request its original state. Or for a plugin dynamically loaded after startup? @linuskendall

**Comment by linuskendall** [comment]
The main issue is the one raised in the PR #32094 . Maintaining complete state inside the plugin for every account makes the plugin very bloated and complex. For the use case of something like gRPC subscriptions, currently the plugin only process account updates for the accounts that it has active subscriptions. However, clients do request the ability to access snapshots of accounts, especially at the start of the stream.

In order to implement that we would need to make the plugin considerably more complex if it not only needs to deal with subscriptions but also needs to keep a complete locally resolved state (ie. at all commitment levels for all accounts).

**Comment by lijunwangs** [comment]
I think the option 5 sounds the simplest

>>> We do none of this and let geyser use JSONRPC to communicate with the validator. We can improve speed of this by adding unix socket support for IPC between plugin and validator.

**Comment by linuskendall** [comment]
However, since the stated goal ***@***.***) is to remove the RPC server from
the validator … it doesn’t seem like 5 is really the long term choice here.
