### ISSUE TITLE
replay_time spiked while block cost remained stable

### ISSUE THREAD

**Issue by taozhu-chicago** [solana-labs/solana#31325]
#### Problem
validator metrics reported: 

> There were spikes in the mean of  replay-slot-stats.replay_time and the mean of replay-slot-stats.replay_total_elapsed starting on the 18th at 22:00 UTC and ending on the 19th at 05:30 UTC.  During the same period, block cost remained stable.

**Comment by taozhu-chicago** [comment]
Query confirmed the `replay_time` spikes are closely, if not solely, related to spikes in `execute_accessories_process_instructions_process_executable_chain_us`, which measures time spent to execute program chain.

Query: 
```
SELECT mean("replay_time") AS "mean_replay_time", mean("store_us") AS "mean_store_us", mean("confirmation_time_us") AS "mean_confirmation_time_us", mean("execute_accessories_process_instructions_process_executable_chain_us") AS "mean_execute_accessories_process_instructions_process_executable_chain_us", mean("execute_accessories_process_instructions_total_us") AS "mean_execute_accessories_process_instructions_total_us", mean("execute_accessories_process_instructions_verify_callee_us") AS "mean_execute_accessories_process_instructions_verify_callee_us" FROM "mainnet-beta"."autogen"."replay-slot-stats" WHERE time > :dashboardTime: AND time < :upperDashboardTime: GROUP BY time(:interval:) FILL(null)

```

Suspect some programs may took much longer to execute than its requested Units implies. Querying `per-program-timings` indicated it might be the case:  
<img width="1252" alt="image" src="https://user-images.githubusercontent.com/82401714/234035551-dc362e80-49ba-41aa-8f37-21c84500f558.png">

Further look into programs have average execute_us greater than 400ms: 
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/82401714/234037617-c969f725-9f63-43ba-a307-2dd7d8cc7cb0.png">

Looks like `1atrmQs3eq1N2FEYWu6tyTXbCjP4uQwExpjtnhXtS8h` took more than 400ms to execute, therefore spiked block replay_time. An example transaction: https://explorer.solana.com/tx/67mPME2jPYNEmziCHYLWaZnwiUCHGxAofZyqgB77tNkN5e5mui8sZTd6esaw7DqKtDWnhcGRr1GKLQ5vY8CjJEDN

**Comment by taozhu-chicago** [comment]
Going to replay ledger for mode details. 

tag @Lichtso

**Comment by bw-solana** [comment]
tag @apfitzge @ilya-bobyr @KirillLykov as part of replay invalidator scenarios

**Comment by KirillLykov** [comment]
@taozhu-chicago it might be that some programs are cheap in terms of CU but expensive in terms of load created by VM when executing them. I'm writing some programs like these ones for the testing purpose

**Comment by taozhu-chicago** [comment]
Yes, we saw some of that before. When I get around, I will replay those transactions to identify which instruction(s) take most time, then perhaps we can adjust CU accordingly.

**Comment by taozhu-chicago** [comment]
For instruction-by-instruction timing for Helium transaction, I copied mainnet-beta ledger for slot `189234458`, replayed with additional log on consumed cu and execution time. 

This slot happens to executed `1atrmQs3eq1N2FEYWu6tyTXbCjP4uQwExpjtnhXtS8h` 11 times, their consumed_cu and execute_us are: 
```
1atrmQs3eq1N2FEYWu6tyTXbCjP4uQwExpjtnhXtS8h, 462910, 34945
1atrmQs3eq1N2FEYWu6tyTXbCjP4uQwExpjtnhXtS8h, 549327, 87841
1atrmQs3eq1N2FEYWu6tyTXbCjP4uQwExpjtnhXtS8h, 545770, 94436
1atrmQs3eq1N2FEYWu6tyTXbCjP4uQwExpjtnhXtS8h, 544945, 85053
1atrmQs3eq1N2FEYWu6tyTXbCjP4uQwExpjtnhXtS8h, 441246, 32619
1atrmQs3eq1N2FEYWu6tyTXbCjP4uQwExpjtnhXtS8h, 463199, 32891
1atrmQs3eq1N2FEYWu6tyTXbCjP4uQwExpjtnhXtS8h, 504030, 25810
1atrmQs3eq1N2FEYWu6tyTXbCjP4uQwExpjtnhXtS8h, 496102, 48154
1atrmQs3eq1N2FEYWu6tyTXbCjP4uQwExpjtnhXtS8h, 485182, 46298
1atrmQs3eq1N2FEYWu6tyTXbCjP4uQwExpjtnhXtS8h, 490449, 46300
1atrmQs3eq1N2FEYWu6tyTXbCjP4uQwExpjtnhXtS8h, 490152, 42918
== total_cu 5,473,312 total_us 577,265 average_CU/us 9.48145 ==
```
It sort of matches the metrics return above, indicates the CU for the instruction are under-counted (ave CU/us should be around 30-40)

Taking one such instence, break down to chained IXs: 
```
4BdqCHsdvSMcb99Ewc6MbUiXJQ7J93mRPEUhoGUJDUp4, 1311817, 802
11111111111111111111111111111111, 0, 9
11111111111111111111111111111111, 0, 8
11111111111111111111111111111111, 0, 1
metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s, 17077, 212
noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV, 39, 24
noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV, 39, 55
cmtDvXumGCrqC1Age74AVPhSRVXJMd8PJS91L8KbNCK, 10119, 2482
BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY, 85927, 6487
hemjuPXBpNvggtaUnN1MwT3wrdhttKEfosTcc2P9Pg8, 180527, 12472
11111111111111111111111111111111, 0, 11
11111111111111111111111111111111, 0, 1
metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s, 17077, 212
noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV, 39, 27
noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV, 39, 41
cmtDvXumGCrqC1Age74AVPhSRVXJMd8PJS91L8KbNCK, 10395, 8137
BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY, 107372, 23301
hemjuPXBpNvggtaUnN1MwT3wrdhttKEfosTcc2P9Pg8, 223241, 39480
----------------------------------------------------------------------
1atrmQs3eq1N2FEYWu6tyTXbCjP4uQwExpjtnhXtS8h, 545770, 94436
```

Looks like `hemjuPXBpNvggtaUnN1MwT3wrdhttKEfosTcc2P9Pg8` and `BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY` are the low hanging fruits.
