### ISSUE TITLE
solana-sdk compilation is inefficient

### ISSUE THREAD

**Issue by kevinheavey** [solana-labs/solana#31373]
#### Problem
Compiling solana-sdk leaves a lot of CPU resources on the table because it gets stuck compiling sequential dependencies. [Here](https://htmlpreview.github.io/?https://gist.githubusercontent.com/kevinheavey/c00c340169a5b672015896011278189d/raw/57565af90b7f22615822c705baf29add51451c93/solana-sdk-timings.html) is the result of running `cargo build --timings` in the sdk/ directory. [Here](https://gist.githubusercontent.com/kevinheavey/c00c340169a5b672015896011278189d/raw/57565af90b7f22615822c705baf29add51451c93/solana-sdk-timings.html) is the raw HTML in case that previewer stops working. And here is a screenshot for convenience: 
![image](https://user-images.githubusercontent.com/24635973/234925343-4619416d-450e-4983-a605-a74df0ad2133.png)

As you can see, CPU usage drops off a lot in the last third of the build. `solana-program` has to wait on the ark* crates to compile and then `solana-sdk` has to wait on solana-program to finish before it can start.

#### Proposed Solution
Split up solana-program and solana-sdk into multiple crates but re-export everything from those two crates for backwards compatibility and convenience. This way downstream crates that are sensitive to compile times can pick and choose what they need. This should be pretty effective for these crates as they perform a lot of disjoint tasks.

I suppose this covers two problems:
1. solana-sdk itself is slower to build than it could be.
2. Needing to compile all of solana-sdk is suboptimal for downstream dependencies that are sensitive to build times, since they usually only need a small fraction of it.

**Comment by KirillLykov** [comment]
It is proposed to return back to this problem after sdk will be extracted, see https://github.com/solana-labs/solana/pull/31394#issuecomment-1650325542
