### ISSUE TITLE
Remove leader QoS adjustment logic

### ISSUE THREAD

**Issue by tao-stones** [solana-labs/solana#31379]
#### Problem

The [QoS adjustment logic](https://github.com/solana-labs/solana/blob/master/core/src/banking_stage/consumer.rs#L427-L432) still alive in leader code. 
1. It _should_ have been removed after cost model replaced "estimated cost" with "requested cu". 
2. It _needs_ to be removed if leader is bankless. 

But It cannot be removed yet, because the benefit of adjusting with actual consumed CUs prevents transactions with unnecessary high compute-unit-limits to degrade cluster. 

This is because:
1. transaction base fee is signature based, transaction can request max 1.4 Mil CUs without paying additional base fee. Without the Adjustment in question, few such transactions can take up entire block space.

2. prioritization fee is `= compute-unit-limit * compute-unit-price`, but compute-unit-print is "micro-lamport", so 1Mil CU transaction only pays 1 lamport more than 1CU transaction. Without the Adjustment in question, transactions with high compute-unit-limit can prioritize out normal transactions, and degrade cluster performance. 

#### Proposed Solution
1. adjust `compute-unit-price` rate #31378 
2. implement base fee based on compute-units (https://github.com/solana-foundation/solana-improvement-documents/pull/19, and https://github.com/solana-foundation/solana-improvement-documents/pull/4.)
3. remove Qos Adjustment logic.
4. Still be able to revert qos-selected transaction if they are/would fail to be executed (due to accountInUse, Invalid Payer account, etc)

**Comment by taozhu-chicago** [comment]
Note: #32285 corrected the logic, the `remove` part of code should always be there, so any transactions that not committed (therefore won't be seen by replay_stage) should revert their CU from cost tracker. This issue should only remove the feature gated `update` part of code
