### ISSUE TITLE
Sol.service got kill by oom

### ISSUE THREAD

**Issue by zhy827827** [solana-labs/solana#31400]
I am going to build a solana rpc node, Solana version 1.13.7 and my machine is 256G ram and 12T ssd disk, when I run the node at :

```
/home/ubuntu/solana-release/bin/solana-validator \
  --identity /home/ubuntu/key/validator-keypair.json \
  --known-validator 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2 \
  --known-validator GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ \
  --known-validator DE1bawNcRJB9rVm3buyMVfr8mBEoyyu73NBovf2oXJsJ \
  --ledger /opt/rockx/sol/validator-ledger/ \
  --no-voting \
  --rpc-port 8899 \
  --log /opt/data/sol/logs/sol.log \
  --entrypoint entrypoint.mainnet-beta.solana.com:8001 \
  --entrypoint entrypoint2.mainnet-beta.solana.com:8001 \
  --entrypoint entrypoint3.mainnet-beta.solana.com:8001 \
  --entrypoint entrypoint4.mainnet-beta.solana.com:8001 \
  --entrypoint entrypoint5.mainnet-beta.solana.com:8001 \
  --dynamic-port-range 8000-9000 \
  --enable-rpc-transaction-history \
  --limit-ledger-size 700000000 \
  --account-index  spl-token-owner \
  --expected-genesis-hash 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d \
  --wal-recovery-mode skip_any_corrupted_record \
  --no-port-check \
  --full-rpc-api \
  --enable-cpi-and-log-storage \
  --known-validator CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S
```

Its ok at the beginning and I can get the node data , but when time pass , the solana service got oom kill by linux, is there any method to decrease the need of solana RAM , since I just need rpc node ,not validator node.

**Out of memory: Killed process 106044 (solana-validato) total-vm:620826344kB, anon-rss:255661268kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:1167624kB oom_score_adj:0
[1194983.849488] oom_reaper: reaped process 106044 (solana-validato), now anon-rss:0kB, file-rss:0kB, shmem-rss:0kB**

**Comment by bw-solana** [comment]
The only thing sticking out to me is the ledger size limit. Note this limit corresponds to number of shreds (as opposed to bytes). IIRC, the default size is 200M (as opposed to the 700M you're using here) and the min is 50M. Might be worth trying

**Comment by zhy827827** [comment]
--limit-ledger-size 700000000  In order to save  slots data for 5-6 days. I'll remove --account-index parameter and try memory consumption

**Comment by steviez** [comment]
Closing this issue out - mnb has already progressed to `v1.14` branch and is in the midst of progressing to `v1.16` branch.

But, as bw-solana mentioned, `--acccount-index` increases memory usage and 256 GB **may** not be enough for running all of the indexes you want
