### ISSUE TITLE
Measure accounts loading and storing cost

### ISSUE THREAD

**Issue by tao-stones** [solana-labs/solana#31411]
#### Problem

Need to measure accounts loading and storing performance in `us`, and in `CU`. 

Motivation is to set transaction accounts read/write lock cost, which can be used as input for base fee calculation.

Few parameters for measuring: type of accounts (eg program account, data account and PDA), size of accounts, 

#### Proposed Solution
using ledger-tool to replay mainnet-beta ledger, collect `measure_us` for accounts load and store at different circumstances.
Note: loading program accounts should be more expensive than loading normal data and PDA accounts.

**Comment by KirillLykov** [comment]
Regarding the way CU per tx could be computed, I'm thinking about using empirical approach. 
In this particular case, as input we have:
*  number of accounts `n`,
*  size of each account `s`.

The observable function of choice is time per tx, call it `t(s, n)`.

This function is different from cost per transaction, lets denote by `c(s, n)`.
But if the idea of 48M CU per block is to fit into 400ms block construction time, we can say that `c(s, n) = 48M/0.4 [CU/sec] * t(s, n)`, where in the `[]` I specify units.

We can do simulations and find triples `(s_i, n_i) -> t_i` and with this data estimate parameters of function `t` which I think can be described by `t(s, n) = a[sec]*n + b[sec/mb]*n*s`. 
* `a` is "time cost" of write lock of an account (assuming it doesn't depend on the size),
* `b` is "time cost" of writing 1MB of data.

So all we need is to find  estimations for `a` and `b`.

**Comment by taozhu-chicago** [comment]
> But if the idea of 48M CU per block is to fit into 400ms block construction time, we can say that c(s, n) = 48M/0.4 [CU/sec] * t(s, n), where in the [] I specify units.

Assuming there are 4 parallel processes during replay, currently the CU per nano-sec is defined as
```
/// Cluster averaged compute unit to micro-sec conversion rate
pub const COMPUTE_UNIT_TO_US_RATIO: u64 = 30;
```
so equation can be simplified to `c(s, n) = 30[CU/us] * t(s, n)`

**Comment by taozhu-chicago** [comment]
> function `t` which I think can be described by `t(s, n) = a[sec]*n + b[sec/mb]*n*s`.
> 
> * `a` is "time cost" of write lock of an account (assuming it doesn't depend on the size),
> * `b` is "time cost" of writing 1MB of data.

Few points I am not entirely clear: 
- are there "time cost" of loading accounts? Especially loading cold account?
- what does "time cost of write lock" mean exactly, is it the wall clock of acquiring write lock on account (which should be cheap)? or includes waiting time till the account becomes available for write lock?
- will there be similar "time cost" of read lock? 

ig I'm thinking alone the line of:
cost of read-only account = cost of loading
cost of write-lock account = cost of loading + cost of write-back (eg storing).
Not clear how to define "cost of read/write lock" yet, but if we do, they shall be added to above accordingly.

**Comment by KirillLykov** [comment]
>  * are there "time cost" of loading accounts? Especially loading cold account?

To be honest, I didn't dig much into this thing. What I observe is that loading time reported [here](https://github.com/solana-labs/solana/blob/a799a90a62958dcf91080671eb0bc70862f60433/runtime/src/bank.rs#L5254) is quite high (1/2 of execute time). Didn't consider that there is a cache for loaded accounts. Need to check the size of the cache to say if my accounts are hot or not.

> * what does "time cost of write lock" mean exactly, is it the wall clock of acquiring write lock on account (which should be cheap)? or includes waiting time till the account becomes available for write lock?
> * will there be similar "time cost" of read lock?

I though about artificial scenario with minimized number of lock contention, so just acquiring the lock.

**Comment by KirillLykov** [comment]
In regard to this, I'm not sure that my mental model for the accounts load is accurate. I have in mind something like:
1. for each account participating in the transaction, try locking it
2. copy the accounts data from accountsdb to some cache
3. during execution of tx, fetch account from this cache if requested and copy it.
4. write to the account and write it back though the cache to the accountsdb

So from (3), if we compare program that only reads accounts and one that writes, the load phase of both should be the same but the execution will be longer for write program because, I think, the time to copy modified accounts data is part of execution.

@alessandrod could you tell me if it fits the reality?

**Comment by KirillLykov** [comment]
> ig I'm thinking alone the line of:
cost of read-only account = cost of loading
cost of write-lock account = cost of loading + cost of write-back (eg storing).
Not clear how to define "cost of read/write lock" yet, but if we do, they shall be added to above accordingly.

Well, if we say that lock time is negligible, `cost of write-lock account = cost of loading + cost of write-back` makes sense. From the simulation point of view, `cost of read-only account` and `cost of write-lock account` might be both estimated empirically

**Comment by taozhu-chicago** [comment]
> From the simulation point of view, cost of read-only account and cost of write-lock account might be both estimated empirically

I played a bit on timing on storing accounts. Somewhat surprised to notice that same transaction took *very* different time to store accounts between ledger replays. The first replay took about 14ms to store accounts for a transaction, the second (re)run took only 1ms. Not sure why, @brooksprumo do you have a pointer to where should I look? Also, I thought you did accounts loading/storing performance measure, are there something we can use here?

**Comment by taozhu-chicago** [comment]
> I did some histograms for loading accounts, but not on storing accounts. So I don't think that'll apply here (based on this and other threads, seems that writes/stores are the issue).

Data on loading is helpful too. 

The overarching idea is loading/storing/locking accounts, as part of execution, are underpriced, so it leads to either few transactions are packing into block, or elevate replay time. @KirillLykov correct me if i'm wrong. 

This issue aims to identify following: 
- micro-second/10k-bytes for loading, on average
- micro-second/10k-bytes for storing, on average
- and micro-second/locking, both read & write.

**Comment by alessandrod** [comment]
¡

> @KirillLykov to follow up on our call, my understanding of "loading account", which could be wrong, consists two steps:
> 
>     1. load account from db to read-only-cache.
> 
>     2. serialize and memcpy into VM, so it's available for program;
>        first step happens at [accounts_db.load()](https://github.com/solana-labs/solana/blob/master/accounts-db/src/accounts_db.rs#L5032), Brooks PR above reports this operation's time, it is also folded into metrics `replay-slot-end-to-end-stats.load_us`
>        I am not clear about second step, maybe it is part of "execution"?
> 
> 
> As for cost of "storing account", I assume is a reverse process: deserialize and memcpy from VM to accounts' write-cache, then store to accounts-db [here](https://github.com/solana-labs/solana/blob/master/accounts-db/src/accounts_db.rs#L8435). metrics `replay-slot-end-to-end-stats.store_us` captures it.

Yep this is correct, the serialize* and deserialize* execution metrics track the time to write accounts into the vm and then parse them back respectively.

**Comment by KirillLykov** [comment]
@taozhu-chicago my understanding of the metrics is the following:

Cost of load:
1. Cost of read from AccountsDB
* checks in write and later read accounts caches. So we should observe spike in this metric when accounts are first used. Need to find the size of caches.
* metric is `replay-slot-end-to-end-stats.load_us`

2. Cost of serialization
* happens before VM executes the program
* includes cost of copying accounts data into the buffer used by VM [see write_data](https://github.com/solana-labs/solana/blob/master/programs/bpf_loader/src/serialization.rs#L93)
* metric is `replay-slot-end-to-end-stats.execute_details_serialize_us`

3. Cost of execution
* metric for time to execute instruction without serialization/deserialization is `replay-slot-end-to-end-stats.execute_details_execute_inner_us`
* But there also other metrics which include this one. In the order of call stack: 
 `execute_acessories_process_message -> execute_accessories_process_instruction_total_us -> execUte_acessories_process_instruction_executable_chain_us -> execute_deatils_execute_inner_us`

4. Cost of deserialization
* happes after execution
* includes cost of copying accounts data
* metric is `replay-slot-end-to-end-stats.execute_details_deserialize_us`

**Comment by taozhu-chicago** [comment]
Amazing! perhaps you can also add `replay-slot-end-to-end-stats.store_us` as cost of storing?
