### ISSUE TITLE
solana-ledger-tool verify command is too slow

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#3155]
`solana-ledger-tool verify` takes ~5minutes to run during a testnet sanity check (cc: #2314).  Culprit is very likely `process_blocktree()`.

Decide if we should just disable ledger verification as a part of `./net.sh sanity` or try to optimize.

Example: https://buildkite.com/solana-labs/testnet-management/builds/23148#4b97278e-1ad9-4eeb-9028-5a0467d81f85/228

**Comment by mvines** [comment]
#3192 switches `process_blocktree()` to use `par_process_entries()` under the hood, but that didn't seem to produce an meaningful speed up in a quick test of processing a ledger output by a couple minutes of `./run.sh`. 

@sambley - how hard is it to create those profiling flame graphs?  Any docs on how?  I think the next step here is to grab a profile of `process_blocktree()` and see where the time is going

**Comment by sambley** [comment]
This link has the required information to generate the profiling information
https://blog.anp.lol/rust/2016/07/24/profiling-rust-perf-flamegraph/

**Comment by sambley** [comment]
@mvines, let me know if you want to take a look at it

**Comment by sambley** [comment]
Looks like significant amount of time is spent in iterating over StatusCache::has_signature(). In this run it was taking around 55 secs to complete the verify.
[flame.pdf](https://github.com/solana-labs/solana/files/2948115/flame.pdf)

**Comment by sambley** [comment]
This change has an update to increase NUM_TICKS_PER_SECOND to 100 from 10 which seems to improve the peformance a bit
https://github.com/solana-labs/solana/pull/3211/commits/766f3ec35742683a24c8c6d2a000acc65e036c5b

**Comment by sambley** [comment]
Looks like the bottleneck is inside accounts squash, looking into it
