### ISSUE TITLE
QUIC streamer and connection-cache are unaware of identity hot-swap

### ISSUE THREAD

**Issue by behzadnouri** [solana-labs/solana#31557]
#### Problem
Both QUIC streamer and connection-cache are initialized with identity keypair:
https://github.com/solana-labs/solana/blob/312d31aca/core/src/tpu.rs#L143-L161
https://github.com/solana-labs/solana/blob/312d31aca/core/src/validator.rs#L853-L864

But neither is updated when there is an identity hot-swap:
https://github.com/solana-labs/solana/blob/312d31aca/validator/src/admin_rpc_service.rs#L703-L727

#### Proposed Solution
Update keypairs/certificates in QUIC streamer and connection-cache when there is an identity hot-swap.

**Comment by behzadnouri** [comment]
> Where are we seeing problems from this cert not being updated? 

When an unstaked node hot-swaps to a staked identity, from the perspective of other nodes in the cluster it retains its old pubkey, and so will not get the right bandwidth allocations.

> Do we want to drop all existing connections for the client/server when we do the change, and or only apply it to new connections?

If all connections are eventually dropped after a reasonable amount of time, then only applying to new connections might work.

**Comment by behzadnouri** [comment]
@ryleung-solana were you able to test this and confirm if it works?

any chance we can add a local-cluster test or something which ensures this keeps working?

**Comment by ryleung-solana** [comment]
If you look at the PR there was a reverted testing change that I used on a
validator running on testnet to test the change.

**Comment by behzadnouri** [comment]
do you think we can have a local-cluster test or something to ensure that this does not break in the future?
