### ISSUE TITLE
Have the test validator start with a performance sample

### ISSUE THREAD

**Issue by mcintyre94** [solana-labs/solana#31695]
#### Problem

- The test validator starts with no performance samples, and doesn't have any for 60 seconds after starting up
- This makes it impossible to test code that uses the `getRecentPerformanceSamples` API against a test validator in eg a CI efficiently
- See eg. https://github.com/solana-labs/solana-web3.js/pull/1297

#### Proposed Solution

- We could start the test validator with a performance sample consisting of all 0s
- Going a step further it'd be great to be able to pre-seed the performance samples with JSON data, in a similar way to with accounts. This would allow testing the API more fully

**Comment by steviez** [comment]
I don't think modifying `SamplePerformanceService` would be a good idea; however, I think it would be pretty easy to write a test function to insert some dummy data into the blockstore. The method is already public:
https://github.com/solana-labs/solana/blob/32072da36bdf645b6f09e9e1f453fbfe4db2f3e9/ledger/src/blockstore.rs#L2778
