### ISSUE TITLE
`getTransaction` fallback behavior for `jsonParsed` encoding documented incorrectly

### ISSUE THREAD

**Issue by steveluscher** [solana-labs/solana#31701]
#### Problem

The [docs for `getTransaction`](https://docs.solana.com/api/http#gettransaction) state:

> If jsonParsed is requested but a parser cannot be found, the instruction falls back to regular JSON encoding (accounts, data, and programIdIndex fields).

I believe this is wrong. If no parser is found, the instructions get returned as ‘partially decoded instructions’ of the form:

```ts
{
  accounts: readonly Base58EncodedAddress[];
  data: Base58EncodedBytes;
  programId: Base58EncodedAddress;
}
```

Note the difference between the `instructions` returned by these two calls:

```
curl https://api.mainnet-beta.solana.com -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getTransaction",
    "params": [
      "3YAwhU39jDggAKnvhnuCM3esC6GkmHQsBqN1HnmV4RXhyiq8JGD6Tb2wav1oA5G6mBmyQMsKxE4i7Lf84u8skf9f",
      "json"
    ]
  }
'
```

```
curl https://api.mainnet-beta.solana.com -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getTransaction",
    "params": [
      "3YAwhU39jDggAKnvhnuCM3esC6GkmHQsBqN1HnmV4RXhyiq8JGD6Tb2wav1oA5G6mBmyQMsKxE4i7Lf84u8skf9f",
      "json"
    ]
  }
'
```

#### Proposed Solution

If I'm correct, 

1. update [this details box](https://github.com/solana-labs/solana/blob/bd8289e1149fa412220215c5825089eecc413c0b/docs/src/api/methods/_getTransaction.mdx?plain=1#L54-L55).
2. audit the docs and see where else we might have gotten this wrong

**Comment by steveluscher** [comment]
cc/ @nickfrosty @CriesofCarrots @mcintyre94

**Comment by CriesofCarrots** [comment]
I agree, the docs are wrong. This same inaccuracy probably exists in `getBlock`.
