### ISSUE TITLE
Missing data in long term storage

### ISSUE THREAD

**Issue by jiezhang** [solana-labs/solana#31751]
#### Problem

According to https://explorer.solana.com/block/13334480, its parent slot is https://explorer.solana.com/block/13334463.
But according to https://explorer.solana.com/block/13334463, its child slot is https://explorer.solana.com/block/13334464

This problem is similar what I reported in https://github.com/solana-labs/solana/issues/21350

#### Proposed Solution
Fix the slots between [13334463, 13334480].

**Comment by steviez** [comment]
Thanks for bringing this to our attention. I downloaded a ledger backup and snooped through the blocks in question:
```
Slot 13334463
    parent_slot: 13334462
    next_slots: [13334464, 13334480, 13335812]
    
Slot 13334464
    parent_slot: 13334463
    next_slots: [13334465]

// No skips in [13334464, 13334475]

Slot 13334475
    parent_slot: 13334474,
    next_slots: []

Slot 13334480
    parent_slot: 13334463,
    next_slots: [13334481]

// The 13335812 fork was not confirmed either
```
A few notes:
 - As you can see, there was some forking at `13334463` given the multiple children. Obviously only one of these children can be valid, so non cluster confirmed blocks were accidentally uploaded here.
 - Parent slot is embedded within the block itself so we know that `13334463 ==> 13334480` is a valid parent ==> child relationship.
 - The `[13334464, 13334465, ..., 13334475]` fork ends at `13334475`. So, there is no path from `13334464` to `13334480` and this is the minority fork that was accidentally uploaded.

Thus, it looks like we need to purge `[13334464, 13334475]` from the storage.

**Comment by CriesofCarrots** [comment]
Purge complete. Now, https://explorer.solana.com/block/13334463 reports a child slot of https://explorer.solana.com/block/13334480
