### ISSUE TITLE
Validator --dynamic-port argument inconsistency

### ISSUE THREAD

**Issue by steviez** [solana-labs/solana#31779]
#### Problem

When passing in a custom value for the `--dynamic-port-range` argument, some basic validation is done on the supplied range:
https://github.com/solana-labs/solana/blob/a3fc622550c2db95dfb623659980a3fd0c1ea9df/validator/src/cli.rs#L1989-L2005

The `if` case ensures that the range is wide enough for the validator as defined by `MINIMUM_VALIDATOR_PORT_RANGE_WIDTH`. We also mention this value (13) in the docs:
https://github.com/solana-labs/solana/blob/a3fc622550c2db95dfb623659980a3fd0c1ea9df/docs/src/running-validator/validator-reqs.md#L102-L103

The `else if` case is meant to be defensive to with how we choose the `tpu_quic` port as illustrated below:
https://github.com/solana-labs/solana/blob/a3fc622550c2db95dfb623659980a3fd0c1ea9df/gossip/src/cluster_info.rs#L3049-L3055

Namely, if
- `tpu_port` ended up being assigned to the last port in the passed in `port_range` (this is possible, see notes under Proposed Solution) AND
- `std::u16::MAX - QUIC_PORT_OFFSET < port_range.end`
then applying `QUIC_PORT_OFFSET` to `tpu_port` for picking `tpu_quic` port would overflow.

Even in the absence of overflow, it is possible that a port could get assigned outside of the operator specified `--dynamic-port-range`; this obviously isn't ideal and could cause problems with other things running on a node and/or firewall settings.

#### Proposed Solution
Within `solana/gossip/src/cluster_info.rs`, services/protocols (tpu, tvu, repair, etc) claim a port in a fixed order. This **typically** leads to each service having the same offset from `port_range.start` from run-to-run and node-to-node. However, that isn't guaranteed as the algorithm for selecting ports allows for some minor failures that would result in different service-to-port mapping:
https://github.com/solana-labs/solana/blob/a474cb24b9238f5edcc982f65c0b37d4a1046f7e/net-utils/src/lib.rs#L429-L439

Maybe we just modify the functions in `Node` to each try to bind in a range that is one port wide (like we do for `tpuc_quic` and `tpu_forwards_quic`) instead of across the entire `port_range`. This would make the system more sensitive to "transient" issues, but would be more strict about not using a port that we said we wouldn't.

**Comment by t-nelson** [comment]
i think @behzadnouri is killing that dumb `QUIC_PORT_OFFSET`, so this might resolve itself if/when that lands

**Comment by behzadnouri** [comment]
We can remove `QUIC_PORT_OFFSET` once the cluster is fully migrated to the new `ContactInfo`.
