### ISSUE TITLE
Fix logs `INFO:<unknown>: RequestUpdates 0` print something useful instead of <unknown>

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#318]
Note, this is not specifically just RequestUpdates message. Everywhere we use trace!/debug!/info! macros with env_logger we get unknown as the subject.

I'm not sure exactly what the best info would be but file/function/line-number and/or maybe a timestamp would be better.

I'm not sure if we need to switch from env_logger to some other rust trace library, there are a few out there.

**Comment by garious** [comment]
I ran the logger in a different Rust project and see that `<unknown>` is supposed to be a timestamp.
