### ISSUE TITLE
Dual (nightly+stable) clippy run is forced under ci due to its bug

### ISSUE THREAD

**Issue by ryoqun** [solana-labs/solana#31834]
#### Problem

temporarily run stable clippy as well to scan the codebase for `redundant_clone`s, which is disabled as nightly clippy is buggy:

https://github.com/rust-lang/rust-clippy/issues/10577

i bisected to a particular upstream pr: https://github.com/rust-lang/rust/pull/108944#issuecomment-1564451009

#### Proposed Solution

remove the dual run as soon as the upstream fixes this bug and we bump to the fixed nightly toolchain: https://github.com/rust-lang/rust-clippy/issues/10577

**Comment by CriesofCarrots** [comment]
@ryoqun , is this still relevant?

**Comment by ryoqun** [comment]
> @ryoqun , is this still relevant?

yeah. sadly, we have move on: https://github.com/anza-xyz/agave/pull/1661
