### ISSUE TITLE
Suspected memory leak in TpuClient and/or Connection Cache

### ISSUE THREAD

**Issue by godmodegalactus** [solana-labs/solana#31939]
#### Problem
While using solana tpu manager in lite-rpc we noticed that memory increased and increased forever. Initially, lite-rpc consumed more or less 500 MBs of memory but after running it for around a day it consumed more than 3Gbs of memory. Moreover, after a long run transactions sent over TPU client were never confirmed, i.e they never reached the leader. We solved this issue by destroying and recreating the TPU Client and Connection Cache every 5 minutes. After recreating it every 5 minutes the memory usage was stable. We suspect some underlying issue with TPUClient and/or ConnectionCache.

To test the issue I have designed a simple program that sends 100 transactions using TPU Client every second.
https://github.com/godmodegalactus/solana-tpu-client-test
 
The program also logs memory usage using the crate procinfo: https://docs.rs/procinfo/latest/procinfo/pid/struct.Statm.html

Testing parameters : 
solana-sdk = 1.14.18
cluster = testnet
RPC = private testnet rpc without any rate limits

Initially consuming 60MBs of memory the process consumes more than 400 Mbs of memory and crashes within an hour with error.
```
thread 'main' panicked at 'QuicLazyInitializedEndpoint::create_endpoint bind_in_range: Os { code: 24, kind: Uncategorized, message: "Too many open files" }', /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/solana-client-1.14.18/src/nonblocking/quic_client.rs:98:10
```

memory logs :
First log: 
```
Stats after 60 s 
 Statm {
    size: 311150,
    resident: 6262,
    share: 2330,
    text: 1326,
    data: 13899,
}
```
Last log
```
Stats after 2940 s 
 Statm {
    size: 408815,
    resident: 110947,
    share: 2362,
    text: 1326,
    data: 122078,
}
```

This issue cannot be reproduced on local cluster, it requires a cluster with log of nodes.
Please follow readme file of the repo to test.

#### Proposed Solution
Solve the memory issue with solana tpu client of connection cache.

**Comment by KirillLykov** [comment]
@ryleung-solana looks relevant

**Comment by ryleung-solana** [comment]
Thanks for pointing this out. Will look into this ASAP.

**Comment by mvines** [comment]
@ryleung-solana - hey have you had change to look into this at all?

**Comment by ryleung-solana** [comment]
Apologies, was on vacation/digital detox, and this fell under my radar. Taking a look now.

**Comment by ryleung-solana** [comment]
@godmodegalactus can you please share more details of the cluster setup you're using the reproduce this problem? Can you please clarify the meaning of 

> This issue cannot be reproduced on local cluster, it requires a cluster with log of nodes.

If it means "a lot of nodes", how many should there be? What kind of network are you testing this with? Is this reproducible with just a cluster spun up on GCE for instance? Are you using any custom validators? Is the memory leak happening in the tool or the validator? Has the problem been repro'd in a validator?

**Comment by godmodegalactus** [comment]
> @godmodegalactus can you please share more details of the cluster setup you're using the reproduce this problem? Can you please clarify the meaning of
> 
> > This issue cannot be reproduced on local cluster, it requires a cluster with log of nodes.
> 
> If it means "a lot of nodes", how many should there be? What kind of network are you testing this with? Is this reproducible with just a cluster spun up on GCE for instance? Are you using any custom validators? Is the memory leak happening in the tool or the validator? Has the problem been repro'd in a validator?

Yes *Lot of nodes* typically mainnet of testnet number of nodes. Personally I think there is a leak somewhere is connection cache as it adds the leaders to the connection cache. So the more the better. Anyways this problem is on the client side and not validator side, I do not see an issue to it on testnet for instance.

**Comment by godmodegalactus** [comment]
On validator we use TPU client to send batch of transactions to the next leader. So kind of also an issue on the validator side.

**Comment by ryleung-solana** [comment]
Is this on a custom validator or the stock validator? Has this been seen in the wild?

**Comment by ryleung-solana** [comment]
@godmodegalactus so after going over the bug description again, it seems this has currently only been reproduced with Mango's custom validator/client? If so, I am tempted to triage this as relatively low priority. As well, could you please share if you have a network that meets the size requirements that one might use to test this? I am a little hesitant to run this against mainnet, and in any case, it mentions that one should use a private rpc without rate limits, which we currently do not have many of

**Comment by godmodegalactus** [comment]
> @godmodegalactus so after going over the bug description again, it seems this has currently only been reproduced with Mango's custom validator/client? If so, I am tempted to triage this as relatively low priority. As well, could you please share if you have a network that meets the size requirements that one might use to test this? I am a little hesitant to run this against mainnet, and in any case, it mentions that one should use a private rpc without rate limits, which we currently do not have many of

Actually we do not have a custom validator client per-se. We noticed this problem while implementing lite-rpc.
But I have created this https://github.com/godmodegalactus/solana-tpu-client-test example to illustrate the issue ?
Do you have testnet access with no rate limits?
If you DM me I could share with you my private testnet triton testnet token for you to test.

**Comment by godmodegalactus** [comment]
gmgalactus

**Comment by ryleung-solana** [comment]
Ok @godmodegalactus so by limiting the size of the connection cache to a smaller MAX_CONNECTIONS constant value (10), I've managed to get the memory usage stabilized to 

`Stats after 21300 s 
 Statm {
    size: 308296,
    resident: 6477,
    share: 2290,
    text: 1359,
    data: 16066,
}
`

It basically just looks like our connection cache size limit is a little large, such that when you have a large network with many nodes, it's possible to (slowly) actually get the connection cache to creep up to the size limit (1024 entries). This results in increasing mem usage for a while, but will not result in unbounded mem usage. Furthermore, the crash reported in the original report is not due to mem usage, but simply due to the UDP port space allocated to the client being filled up by the large number of Quic connections. Due to performance problems we encountered with using the same Quinn endpoint for all the connections, we use different endpoints for the connections, such requires a different UDP port. We are currently looking into how we might be able to share the same Quinn endpoint between the multiple connections performantly, but this is a longer-term thing we are looking at. For now, you can work around the problem by increasing the port range for the validator.

**Comment by godmodegalactus** [comment]
> Ok @godmodegalactus so by limiting the size of the connection cache to a smaller MAX_CONNECTIONS constant value (10), I've managed to get the memory usage stabilized to
> 
> `Stats after 21300 s Statm { size: 308296, resident: 6477, share: 2290, text: 1359, data: 16066, } `
> 
> It basically just looks like our connection cache size limit is a little large, such that when you have a large network with many nodes, it's possible to (slowly) actually get the connection cache to creep up to the size limit (1024 entries). This results in increasing mem usage for a while, but will not result in unbounded mem usage. Furthermore, the crash reported in the original report is not due to mem usage, but simply due to the UDP port space allocated to the client being filled up by the large number of Quic connections. Due to performance problems we encountered with using the same Quinn endpoint for all the connections, we use different endpoints for the connections, such requires a different UDP port. We are currently looking into how we might be able to share the same Quinn endpoint between the multiple connections performantly, but this is a longer-term thing we are looking at. For now, you can work around the problem by increasing the port range for the validator.

Good analysis, Thank you for your response. But shouldn't TPU client remove the connections from connection cache time to time. So that we do not have these kind of issues. Is this the expected behavior ?

**Comment by behzadnouri** [comment]
> We are currently looking into how we might be able to share the same Quinn endpoint between the multiple connections performantly

@ryleung-solana is there a tracking issue for this?

**Comment by ryleung-solana** [comment]
@godmodegalactus the connection cache does remove connections once full (num_entries > 1024) - this was tested by lowering the size limit and seeing that the memory usage stabilized (sooner). But the basic problem here is not memory usage but port usage, caused by the fact that we don't reuse Quinn endpoints between connections due to an observed perf problem. We are currently working on that problem.

**Comment by godmodegalactus** [comment]
> @godmodegalactus the connection cache does remove connections once full (num_entries > 1024) - this was tested by lowering the size limit and seeing that the memory usage stabilized (sooner). But the basic problem here is not memory usage but port usage, caused by the fact that we don't reuse Quinn endpoints between connections due to an observed perf problem. We are currently working on that problem.

Ok, Let me retest with your suggestions.

**Comment by ryleung-solana** [comment]
@behzadnouri I don't believe we previously had an issue for this, it was just based on @lijunwangs perf testing. I have created an issue at https://github.com/solana-labs/solana/issues/32377 cc @lijunwangs to add more details.
