### ISSUE TITLE
Geyser no `notify_end_of_startup` when starting from genesis

### ISSUE THREAD

**Issue by Arrowana** [solana-labs/solana#32068]
#### Problem

There is some ambiguity in the geyser plugin, It isn't clear that when starting from genesis there won't be a `notify_end_of_startup` notification. As a result any plugin relying on it (to skip startup update...), will not work properly for a validator starting from genesis.

When trying to run a geyser plugin with solana-test-validator `notify_end_of_startup` never fires because it starts from genesis.

This is caused by the branching where starting from genesis doesn't load a snapshot
[https://github.com/solana-labs/solana/blob/v1.14.16/ledger/src/bank_forks_utils.rs#L119-L120](https://github.com/solana-labs/solana/blob/0fb2ffda2ec4abd71816f1c7f47223d547132c6d/ledger/src/bank_forks_utils.rs#L119-L120)

An example where the confusion happened
https://github.com/rpcpool/yellowstone-grpc/issues/131

#### Proposed Solution
Call `notify_end_of_startup` when starting from genesis, not sure where this has to be in the call stack

**Comment by Arrowana** [comment]
> Got the same problem as [rpcpool/yellowstone-grpc#131](https://github.com/rpcpool/yellowstone-grpc/issues/131) when trying to test some stuff using TestValidator started from genesis and Yellowstone gRPC Plugin.
> 
> Fixed by adding `notify_end_of_restore_from_snapshot` in the end of `blockstore_processor::process_blockstore_for_bank_0` (Couldn't find a better spot but I guess that will do)
> 
> Is PR needed? _btw, thx @Arrowana for all the debugging you did beforehand, without you I would be stuck here forever

It looks like it has been fixed in yellowstone-grpc for other reasons
https://github.com/rpcpool/yellowstone-grpc/pull/230

Since one could argue that we never reach the end of restore from snapshot since there wasn't a restore to start with this should be it?

**Comment by passingBySol** [comment]
> > Got the same problem as [rpcpool/yellowstone-grpc#131](https://github.com/rpcpool/yellowstone-grpc/issues/131) when trying to test some stuff using TestValidator started from genesis and Yellowstone gRPC Plugin.
> > Fixed by adding `notify_end_of_restore_from_snapshot` in the end of `blockstore_processor::process_blockstore_for_bank_0` (Couldn't find a better spot but I guess that will do)
> > Is PR needed? _btw, thx @Arrowana for all the debugging you did beforehand, without you I would be stuck here forever
> 
> It looks like it has been fixed in yellowstone-grpc for other reasons [rpcpool/yellowstone-grpc#230](https://github.com/rpcpool/yellowstone-grpc/pull/230)
> 
> Since one could argue that we never reach the end of restore from snapshot since there wasn't a restore to start with, this should be it?

Can confirm. Indeed yellowstone-grpc works without the "fix" of mine. Turns out it was some other issue, most likely in how I configured the yellowstone-grpc config.
