### ISSUE TITLE
Gossip CrdsValue::Vote messages are not properly signed

### ISSUE THREAD

**Issue by sagar-solana** [solana-labs/solana#3207]
#### Problem

`CrdsValue::Vote`s in gossip were being signed (even though the vote tx contained within is signed) only because the tx doesn't carry a wallclock

#### Proposed Solution

Consider adding wallclocks to vote transactions so that votes on gossip are secure again.

**Comment by aeyakovenko** [comment]
@sagar-solana A vote doesn't need a wallclock per-se.  The blockhash that the vote is signed for can be translated to a wallclock.  Replay stage can register any blockhash it observes with cluster_info, which can then use the mapping to translate into a wallclock.  Any votes that are not in the mapping can be dropped.

**Comment by sagar-solana** [comment]
Oh that's smart. Okay I'll think about it and bug you if I have questions ;)
