### ISSUE TITLE
Ensure Gosssip performance remains high in an Adversarial network 

### ISSUE THREAD

**Issue by sagar-solana** [solana-labs/solana#3214]
#### Problem

We need more data and possible Gossip protocol changes to ensure Gossip performance remains high for the highly staked nodes in an Adversarial network. 

Currently it might be possible for lowly staked nodes to spam the networks such that it impacts the efficiency of Gossip message propagation to the High stake holders.

#### Proposed Solution

We should try a network simulation with a heavily unbalanced setup, like so: 
`400 nodes, 4 staked, the rest unstaked`
The goal would be ensure gossip performs well in even such an imbalanced network.

A collection of thoughts of different things to build on top of the current implementation. These need to be verified.
- We don’t want a low stake node between a high staked one. Aka prunes between high stakers might end up resulting in a low staked node being on the critical path between two high stake holders
- Maybe active set should be more random in the way it picks nodes. Today it's weighted and tries not to pick the same node repeatedly
- Number of nodes being pushed to should have some minimum combined stake (for example, 2x the local node's stake). This makes the push set dynamic and random.
- Consider accumulating pushes from lower stake nodes before sending them out and only forward messages when they hit a certain stake weight

Tag: @aeyakovenko

**Comment by aeyakovenko** [comment]
The node sending the prune messages has control over the route.  It should aggregate the duplicates until they add up to the originators stake weight.

If the originator has X stake, don't ask to prune until the duplicates add up to > X.  Don't forward to the duplicate routes.

**Comment by aeyakovenko** [comment]
To put it another way.  A min cut of a path between two nodes should be at least the min stake weight of the two nodes.
