### ISSUE TITLE
Feature Gate: Enable partitioned epoch reward distribution

### ISSUE THREAD

**Issue by HaoranYi** [solana-labs/solana#32166]
### Description

Enable partitioned epoch reward distribution.

See https://github.com/solana-foundation/solana-improvement-documents/pull/15

### Feature ID

41tVp5qR1XwWRt5WifvtSQyuxtqQWJgEK8w91AtBqSwP

### Activation Method

Single Core Contributor

### Deployment Considerations

monitor epoch rewards distribution at the epoch boundary.

### Minimum Beta Version

v1.18.0

**Comment by jstarry** [comment]
Blocked on activation of this feature: https://github.com/solana-labs/solana/issues/33888

**Comment by CriesofCarrots** [comment]
This feature now also includes https://github.com/solana-labs/solana/pull/34624
I am updating the beta branch accordingly
