### ISSUE TITLE
bench-tps degraded performance 

### ISSUE THREAD

**Issue by apfitzge** [solana-labs/solana#32179]
#### Problem
bench-tps has recently been performing poorly on master.

In #32175, the introduction of the issue was tracked to #32031.
Reverting #32031 is not the path forward, as we want our clients to use the configuration we pass. 
It appears that the configuration for the bench-tps client is not sufficient for multi-node tests. 

#### Proposed Solution
Investigate a proper fix.

**Comment by apfitzge** [comment]
In the performance test, right before the client is started we run `$ solana validators`:
```
   Identity                                      Vote Account                            Commission  Last Vote        Root Slot     Skip Rate  Credits  Version            Active Stake

  boot1Z6jb15CLqpaMTn2CxktktwZpRAVAgHZEW6SxQ7   4NA4iPVdY5CTddbjF1EdYhasromaEkdvBkoDzTRJ1meB  100%        297 (  0)        266 (  0)   0.00%       75   1.17.0  
```

when the client starts, we likely aren't seeing all 5 nodes.

Working theory, stakes in connection cache are not updated while running and so the client only ever sends to the nodes it was aware of at start-up.

If that's the case, it's also curious why the forwarding is not efficient.

**Comment by apfitzge** [comment]
Dug into the logs from the test job. The changes made in #32175 shouldn't have any effect - the path of code is not happening in the logs.

**Comment by apfitzge** [comment]
Originally it appeared that f2f1dab5ea was the beginning of performance degradation. It has become clear that the performance is only sometimes degraded. Re-running performance benchmarks several times to try to prove that f2f1dab5ea was where the issues began.

**Comment by apfitzge** [comment]
@yihau is a champ and ran nightly perf-tests 3 more times on 8937fd9bd6 (the commit before f2f1dab). We saw good performance on all 3 runs, which puts us at at least 4 runs all with good performance - strongly indicates f2f1dab as the point where we began seeing degraded performance, as we originally thought.

<details>
<summary>perf details</summary>

```
mean_tps: 27806
max_tps: 97740
mean_confirmation_ms: 954
max_confirmation_ms: 6766
99th_percentile_confirmation_ms: 4257
max_tower_distance: 45
last_tower_distance: 31
slots_per_second: 2.700
```

```
mean_tps: 25391
max_tps: 97743
mean_confirmation_ms: 812
max_confirmation_ms: 4650
99th_percentile_confirmation_ms: 2978
max_tower_distance: 40
last_tower_distance: 31
slots_per_second: 2.661
```

```
mean_tps: 24394
max_tps: 96403
mean_confirmation_ms: 864
max_confirmation_ms: 8023
99th_percentile_confirmation_ms: 4169
max_tower_distance: 43
last_tower_distance: 31
slots_per_second: 2.622
```
</details>

**Comment by apfitzge** [comment]
Have been investigating this further. Setting up a 4 node cluster on GCE I am still seeing poor performance, even after reverting f2f1dab.

Looked closer at some metrics. All packets are going through a single node, which then for forwarding to other nodes - unclear to me that that is the intent for a bench-tps client.

Regardless, as I was looking at forwarding metrics of the node that directly receives from the client I noticed there were 20 slot periods prior to it becoming leader that it was not sending any packets. This caused other nodes to have no packets to consume, and TPS to drop.

Found that I introduced a bug in #30618. Fixing it now.

However, if 30618 was the only cause of poor performance we'd have seen it after that was merged. Which we did not.

After fixing the bug, we do see generally better performance but still periods of awful performance. I shall continue to investigate.

**Comment by apfitzge** [comment]
Unable to replicate the super terrible performance on local GCE cluster.
Looking at logs from buildkite, validator logs don't have anything that stands out.

However, pulling the the client logs shows that the performance degredation is primarily due to the client-side performance:
```
[2023-07-17T06:19:35.343612873Z INFO  solana_bench_tps::bench] Tx send done. 25861 ms 96.66885 tps
```

Should run w/ debug logging on the client to see if we can figure out what is going on.

**Comment by apfitzge** [comment]
Got some logs with client debugging on.

It seems there's potentially more than one issue presenting itself in different ways.

In my previous comment, we saw that the client was sending at a very low rate which would easily explain why the validators had low throughput.

However, the run with client debug logging on actually had good throughput on the client-side, never dropping below 6ktps output on each of its' threads.

**Comment by apfitzge** [comment]
Continuing to debug logs. Went through the logs I mentioned in my previous comments.

So in this case there's a few interesting things.
1. bench-tps is only forwarding to a single node - we'll call it NODE1
2. NODE1 is the bootstrap, has the most stake and is leader about 80% of the time
3. NODE1 is very often the leader after other nodes; rarely the case that 2 other nodes are leader back-to-back

These 3 points will already give us decreased performance in 1/4 of our slots for non-NODE1 leaders. In their last slot, if NODE1 is the next leader then NODE1 will be in the HOLD decision and not forward them any transactions.

However, there are also long stretches where NODE1 is the leader for say 16+ slots in a row.
Digging into one such stretch, it's clear that the packets the client is sending are NOT reaching banking stage. Unclear where they are being dropped. They don't seem to be making it to sigverify either, since those would appear as tracer-stats in banking stage.

Assumption at this point is the QUIC connection changes is making validators filter these packets out earlier. Where is that happening in https://github.com/solana-labs/solana/commit/f2f1dab5ea7ac66757b85e88ddd5cc9846e5640c.

**Comment by apfitzge** [comment]
A few interesting finds from deep dive this afternoon. All these logs are for the buildkite run here: https://buildkite.com/solana-labs/solana-local-cluster/builds/637

- When the benchmark begins we initially see good performance, with NODE3 correctly forwarding packets. We see the numbers reflected in the NODE1 (leader) logs in `quic_streamer_tpu_forwards` metrics.
- Test begins around `2023-07-17T18:48:31.418087690Z`
- We begin to see stream_read_timeouts on NODE1:
```
Timestamp stream_read_timeouts
18:48:59.760249634 61
18:49:04.766135378 668
18:49:09.772201710 5909
```
which stays high the remainder of the run.

The first timestamp we see these timeouts corresponds roughly to slot 1448. We had a few sub-thousand tx slots prior to this, but this is exactly the slot where we begin to see shit TPS numbers.

Looking at `num_packets` fields in `connection_cache_tpu` metrics on NODE3:
```
18:48:34.249388664 38450
18:48:36.255227292 51284
18:48:38.261525826 49560
18:48:40.269885116 53208
18:48:42.270413295 48567
18:48:44.301283104 46435
18:48:46.309849047 40247
18:48:48.324641754 35249
18:48:50.330983940 57106
18:48:52.343897968 56786
18:48:54.368478743 50408
18:48:56.370455070 40259
18:48:58.374664542 21025
18:49:00.378744077 495
18:49:02.393050106 1887
18:49:04.396244915 4000
18:49:06.467671072 5840
18:49:08.481345797 8054
18:49:10.538255556 7445
18:49:12.541889721 3765
18:49:14.548162233 4895
```
we become terrible at `18:49:00.378744077`. This is the same time the other metrics indicate.
Unclear what's happening at this time to make things go to shit suddenly when it was working fine before.

**Comment by apfitzge** [comment]
Note that `BankingStage` on NODE3 is consistently receiving from the client, and forwarding metrics indicate it is **attempting** to forward packets at a mostly consistent and high rate even after 18:49:00.

**Comment by t-nelson** [comment]
client log is pretty wrecked with quinn debug messages. was `RUST_LOG=debug` inadvertently set instead of `RUST_LOG=solana=debug`?

i'd recommend switching the cluster config to using primordial stakes to avoid, warmup epochs and waiting.  couldn't really tell from the messy client logs how things played out later, but it only saw two nodes at startup

**Comment by apfitzge** [comment]
Was able to narrow it down to `maybe_staked_nodes` and `maybe_client_pubkey`:
Code change from master is in the QuicConnectionManager in `quic-client/src/lib.rs`:
```rust
    fn new_connection_config(&self) -> QuicConfig {
        let QuicConfig {
            client_certificate: cloned_client_certificate,
            maybe_staked_nodes: cloned_maybe_staked_nodes,
            maybe_client_pubkey: cloned_maybe_client_pubkey,
            client_endpoint: cloned_client_endpoint,
        } = self.connection_config.clone();

        QuicConfig {
            // client_certificate: cloned_client_certificate,
            maybe_staked_nodes: cloned_maybe_staked_nodes,
            maybe_client_pubkey: cloned_maybe_client_pubkey,
            // client_endpoint: cloned_client_endpoint,
            ..QuicConfig::new().unwrap()
        }
    }
```


https://buildkite.com/solana-labs/solana-local-cluster/builds/697#01898ea2-c930-4d03-b982-1a90aaf891fb

**Comment by apfitzge** [comment]
@lijunwangs doesn't look to be a difference in the `max_parallel_streams` used in the good vs bad runs.

Logs for same build producing good then bad run: https://buildkite.com/solana-labs/solana-local-cluster/builds/698#01898f2c-6f92-4b6c-92ed-b71b24650275

```
Good run (with same change):
- client -> 128
- node 1 -> 128 then 2048
- node 2 -> 128 then 2048
- node 3 -> 128 then 2048
- node 4 -> 128 then 2048
- node 5 -> 128 then 2048
Bad run (with same change):
- client -> 128
- node 1 -> 2048
- node 2 -> 128 then 2048
- node 3 -> 128 then 2048
- node 4 -> 128 then 2048
- node 5 -> 128 then 2048
```

On the bootstrap node on the bad run we don't see an initial calculation using 128 max parallel streams, like we did on the good run. I'm not sure if that's important.

**Comment by t-nelson** [comment]
> Yeah, but client didn't seem to be too important for that run. In some runs the perf

i was less concerned about the perf than being able to read the log :sweat_smile:

**Comment by apfitzge** [comment]
Yeah, enabling debug there basically didn't help anyways. 🤷‍♂️
