### ISSUE TITLE
solana node can't catch up

### ISSUE THREAD

**Issue by creater-zhys** [solana-labs/solana#32200]
problams:
(mainnet)
1. Solana took  about 7 hours to start the 8899 port;
2. My solana node can't catch up 
![E80F25C6-118E-465C-9F28-2A6BA5B1EFC5](https://github.com/solana-labs/solana/assets/75056458/9b4a5d30-a37c-4e5a-ab83-000d789466e4)

node configuration ：
128GBRAM;
2T disk;

software version:
1.14.17

Launch parameters：
nohup /home/solana/solana-release/bin/solana-validator \
    --identity ~/validator-keypair.json \
    --vote-account ~/vote-account-keypair.json \
    --known-validator 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2 \
    --known-validator GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ \
    --known-validator DE1bawNcRJB9rVm3buyMVfr8mBEoyyu73NBovf2oXJsJ \
    --known-validator CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S \
    --gossip-validator 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2 \
    --gossip-validator GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ \
    --gossip-validator DE1bawNcRJB9rVm3buyMVfr8mBEoyyu73NBovf2oXJsJ \
    --gossip-validator CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S \
    --gossip-validator 2npYpAQcNWcZo85eB43DnSMyeeVCiks7g65YaWVKp8TX \
    --only-known-rpc \
    --ledger /data2/validator-ledger \
    --accounts /data2/accounts \
    --rpc-port 8899 \
    --private-rpc \
    --no-port-check \
    --full-rpc-api \
    --no-voting \
    --enable-accounts-disk-index \
    --dynamic-port-range 8000-8020 \
    --entrypoint entrypoint.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint2.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint3.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint4.mainnet-beta.solana.com:8001 \
    --entrypoint entrypoint5.mainnet-beta.solana.com:8001 \
    --expected-genesis-hash 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d \
    --wal-recovery-mode skip_any_corrupted_record \
    --limit-ledger-size \
    --log /data2/solana-validator.log &

please help me resolve this issue

**Comment by steviez** [comment]
Hello @creater-zhys - we don't do validator support here on GitHub. Rather, please head to our Discord at, and specifically, check out `#validator-support` once you have read through the guidelines:
https://solana.com/discord

That being said, for running full RPC, I suspect that 128 GB may not be enough. Also, please see the release notes for concerns related to you passing `--enable-accounts-disk-index`:
https://github.com/solana-labs/solana/releases/tag/v1.14.17
