### ISSUE TITLE
The `jsonrpc` crate is outdated. Are there any plans to rewrite `JSON-RPC` component?

### ISSUE THREAD

**Issue by fishseabowl** [solana-labs/solana#32269]
#### Problem

The `jsonrpc` crate is no longer actively developed. Does Solana have any plans to utilize the successor `jsonrpsee` or other alternatives to rewrite the JSON-RPC component?

**Comment by steviez** [comment]
This has been discussed in https://github.com/solana-labs/solana/issues/30911; closing this issue as it is a duplicate
