### ISSUE TITLE
Panic in bench-tps

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#3227]
#### Problem
Noticing a panic in bench-tps while running testnet. The panic is at this line
https://github.com/solana-labs/solana/blob/8bba11367e3170dba8bba8a0905c0363d36d7484/bench-tps/src/bench.rs#L64

![image](https://user-images.githubusercontent.com/40076733/54166411-607ea480-4422-11e9-8127-981c21228282.png)

The bug seems to lie in fullnode code, where bank is being reconstructed.

#### Proposed Solution
Triage and fix

**Comment by mvines** [comment]
@pgarg66 do we still see this on master with the fix from #3563?

**Comment by pgarg66** [comment]
Looks like #3563 was not merged.

**Comment by mvines** [comment]
heh right.  github navigation fail.

**Comment by pgarg66** [comment]
Fixed by https://github.com/solana-labs/solana/pull/3899
