### ISSUE TITLE
run solana-test-validator failed

### ISSUE THREAD

**Issue by DaviRain-Su** [solana-labs/solana#32332]
#### Problem

always  report: `RPC connection failure: error sending request for url (http://127.0.0.1:8899/): connection closed before message completed`
```
WebSocket PubSub URL: ws://127.0.0.1:8900
  RPC connection failure: error sending request for url (http://127.0.0.1:8899/): connection closed before message completed               Identity: B7GVHHgJzLX7QhEFxgUXq95txY6okit4wovSNaHXuD1Y
Genesis Hash: 9sofeTDsCiECYioh51dPU7f5VxVFzZo7NotjtfxPZmWk
Version: 1.16.1
Shred Version: 1434
Gossip Address: 127.0.0.1:1024
TPU Address: 127.0.0.1:1027
JSON RPC URL: http://127.0.0.1:8899
WebSocket PubSub URL: ws://127.0.0.1:8900
  RPC connection failure: error sending request for url (http://127.0.0.1:8899/): connection closed before message completed               Identity: B7GVHHgJzLX7QhEFxgUXq95txY6okit4wovSNaHXuD1Y
Genesis Hash: 9sofeTDsCiECYioh51dPU7f5VxVFzZo7NotjtfxPZmWk
Version: 1.16.1
Shred Version: 1434
Gossip Address: 127.0.0.1:1024
TPU Address: 127.0.0.1:1027
JSON RPC URL: http://127.0.0.1:8899
WebSocket PubSub URL: ws://127.0.0.1:8900
  RPC connection failure: error sending request for url (http://127.0.0.1:8899/): connection closed before message completed               Identity: B7GVHHgJzLX7QhEFxgUXq95txY6okit4wovSNaHXuD1Y
Genesis Hash: 9sofeTDsCiECYioh51dPU7f5VxVFzZo7NotjtfxPZmWk
  RPC connection failure: error sending request for url (http://127.0.0.1:8899/): connection closed before message completed               Identity: B7GVHHgJzLX7QhEFxgUXq95txY6okit4wovSNaHXuD1Y
Genesis Hash: 9sofeTDsCiECYioh51dPU7f5VxVFzZo7NotjtfxPZmWk
  RPC connection failure: error sending request for url (http://127.0.0.1:8899/): connection closed before message completed               Identity: B7GVHHgJzLX7QhEFxgUXq95txY6okit4wovSNaHXuD1Y
Version: 1.16.1
Shred Version: 1434
Gossip Address: 127.0.0.1:1024
TPU Address: 127.0.0.1:1027
JSON RPC URL: http://127.0.0.1:8899
WebSocket PubSub URL: ws://127.0.0.1:8900
```

on mac

**Comment by oulaoba** [comment]
I had this problem too , resolved by removed `./cache/solana/* && ./cache/local/share/solana/* && ./config/solana/*` ,and reinstalled  .

**Comment by EigenSolver** [comment]
This issue is also raised when accessing the internet with a proxy (e.g Clash or Shadowsocks). Close the proxy will resolve the issue. (Pitty for the developers from China)

**Comment by EigenSolver** [comment]
This issue is also raised when accessing the internet with a proxy (e.g Clash or Shadowsocks). Close the proxy will resolve the issue. (Pitty for the developers from China)

**Comment by muluolantian** [comment]
> This issue is also raised when accessing the internet with a proxy (e.g Clash or Shadowsocks). Close the proxy will resolve the issue. (Pitty for the developers from China)

oh my god ! this is it !

**Comment by DazKins** [comment]
> (Pitty for the developers from China)

Unfortunately I fall into this category 😢

My workaround is to:

1. Disable all proxies, i.e: `unset http_proxy https_proxy all_proxy` and then manually disable the system proxy setting in my network settings.
2. Run the `solana-test-validator`
3. Re-enable the system proxy in network settings, set all necessary proxy environment variables again

It appears as long as the proxies are disabled on first execution, the validator can continue to work when they are turned back on 🤷‍♂️

You can automate steps 1 and 2 with some console commands and attach it to a script/alias, but it depends exactly how your system proxy is setup.
