### ISSUE TITLE
Kill `jsonParsed` 🔪

### ISSUE THREAD

**Issue by kevinheavey** [solana-labs/solana#32342]
I would like to propose removing all `jsonParsed` support from the RPC. I think this should be solely the client's job, for the following reasons:

1. The existence of `jsonParsed` encoding makes it much more complicated to build an RPC client that parses responses. Not only are there more return types, but the return types of many methods become enums with parsed and unparsed variants. For example, [this file](https://github.com/kevinheavey/solders/blob/main/crates/rpc-responses-common/src/lib.rs) in solders has way more extra code that exists only because of `jsonParsed`. You search it for "JsonParsed" to get an idea.
2. Lack of good client support due to (1). Below is the `ParsedAccountData` type in web3.js. As you can see, the `parsed` field is just `any`. Granted, there is some dynamic parsing of the `parsed` field in web3.js, but having the `any` type makes it much less useful. And at the same time it would be a fair bit of work to fix the type definition.
```
export type ParsedAccountData = {
  /** Name of the program that owns this account */
  program: string;
  /** Parsed account data */
  parsed: any;
  /** Space used by account data */
  space: number;
};
```
3. Having a response that may or may not be `jsonParsed` is a footgun. The caller needs to know whether they're querying data that has `jsonParsed` support. It's better if the caller knows what data they're querying and parses it themselves.
4. It makes the RPC code much more complicated for a minor gain, and makes it harder to reimplement in another language.

I'm sure this would break something but I want to start the discussion.

**Comment by mschneider** [comment]
Would like to propose that we map out a v2 of the json rpc api and remove all these weird features and push them into the client library instead of on the server.
