### ISSUE TITLE
core doc: Synchronisation.md 

### ISSUE THREAD

**Issue by hydrogenbond007** [solana-labs/solana#32358]
#### Problem
Looks like there are a few updates that need to be made to the core [sync.md](https://github.com/solana-labs/solana/blob/master/docs/src/cluster/synchronization.md) doc

- Block times are written to be 800ms
- No description about ticks 
- Need to write about the solana clock and its properties
-->

#### Proposed Solution
If its cool can make a small pull request with the proposed changes!

**Comment by steviez** [comment]
> If its cool can make a small pull request with the proposed changes!

PR's are always welcome, no need to ask for permission to make one!

**Comment by hydrogenbond007** [comment]
@steviez  Done! made small edits and more specifications, feel free to drop edits and suggestions! 
https://github.com/solana-labs/solana/pull/32373
