### ISSUE TITLE
Test of storage mining logic has commented assertion

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#3236]
#### Problem

Storage program is returning an error when it should not and an assert is commented in the test_bank_storage test.

#### Proposed Solution

Uncomment this assertion, debug why and fix it.

**Comment by sakridge** [comment]
@MarkJr94 this could be a good one to look into: https://github.com/solana-labs/solana/blob/7b35114c0f0e6f37b2a0ff85cf90a9102218ab33/programs/storage/tests/storage.rs#L82

**Comment by sagar-solana** [comment]
@sakridge, this is happening because the mining proof being submitted is for entry_height 0 on a storage account that has no other proofs.
I don't know what the expected behavior here is but right now this check fails since both lhs and rhs are 0

```
if segment_index >= current_segment_index {
    return Err(ProgramError::InvalidArgument);
}
```

**Comment by sakridge** [comment]
@sagar-solana the segment index should be updated from the AdvertiseStorageLastId. The plumbing for that may not be right. Can you see about why that is not updated by this transaction:

https://github.com/solana-labs/solana/blob/7b35114c0f0e6f37b2a0ff85cf90a9102218ab33/programs/storage/tests/storage.rs#L73

That should update the current segment height.

**Comment by sagar-solana** [comment]
@sakridge, because `new_mining_proof` is using the wrong keypair. We're advertising on bob's account and then running new_proof on jack's account. Making the following change fixes the test.

```
-    let tx = StorageTransaction::new_mining_proof(
-        &jack,
+    let tx = StorageTransaction::new_mining_proof(
+        &bob,
```

**Comment by sakridge** [comment]
Cool, thanks. Can you make PR?
