### ISSUE TITLE
Re-enable downstream builds for spl and openbook-dex

### ISSUE THREAD

**Issue by KirillLykov** [solana-labs/solana#32378]
#### Problem

We disabled downstream project builds [in this commit](https://github.com/solana-labs/solana/pull/30975/commits/f5dd5e222b396947840367e1f91c60d341e2d20e)

Why: due to upgrade of borsh from 0.9.3 to 0.10.3

#### Proposed Solution

To re-enable them "we'll have to add a fix to maintain borsh's transitive dependency on hashbrown to 0.12.3, since cargo will automatically upgrade it during the downstream build, causing the program builds to fail." (https://github.com/solana-labs/solana/pull/30975#issuecomment-1621586229)

- [x] Re-enable spl https://github.com/solana-labs/solana/pull/32429
- [ ] Re-enable openbook-dex

**Comment by KirillLykov** [comment]
Looks like spl build has been disabled again. But now I believe it can be re-enabled. 
My understanding is that these scripts we used before for buildkite are deprecated because we migrated to gitactions

Regarding re-enabling openbook, we need to add openbook-dex-v2 which is a new version written from scratch. I will take it but I might need some guidance from @yihau regarding these gitactions

**Comment by yihau** [comment]
sure. in #32677, I added some new files

1. `.github/scripts/purge-ubuntu-runner.sh` => a tool to get more space on a runner. if you don't use all default space, you don't need it.
2. `.github/scripts/downstream-project-spl-common.sh` => I extracted logic from old scripts. you can do similar thing to openbook-dex or just write it in an action
3. `.github/workflows/downstream-project-spl.yml` => the main script we need. I added `workflow_call` to have it reusable
4. `.github/workflows/downstream-project-spl-nightly.yml` => basically run `.github/workflows/downstream-project-spl.yml` but triggering by the cron mechanism.
