### ISSUE TITLE
Quic Client Creates Excessive Number of Quinn Endpoints

### ISSUE THREAD

**Issue by ryleung-solana** [solana-labs/solana#32377]
#### Problem
The Quic client creates a new Quinn Endpoint for each connection pool. This can result in excessive port usage in large networks (as each Endpoint uses a separate UDP port).

#### Proposed Solution
The above behavior was based on performance problems in Quinn observed by @lijunwangs with a single Quinn Endpoint. We should root-cause this perf problem and propose a fix to Quinn, so that we may use a single Quinn Endpoint for all the connection pools.

**Comment by apfitzge** [comment]
The issues as described in #32179 began with changes to connection cache which affects quic.

**Comment by behzadnouri** [comment]
From my observations at least, this still seems to be an issue.
i.e. same quinn Endpoint creates contention across connections or send/receive operations on that Endpoint..

**Comment by behzadnouri** [comment]
> @behzadnouri interesting... what stats are you looking at that show this as a bottleneck?

Testing turbine on quic, I see evidence that hints to contention on quic endpoint across connections or send/receive operations.
