### ISSUE TITLE
Solana CLI improperly showing balances for stake accounts `solana stakes`

### ISSUE THREAD

**Issue by ashpoolin** [solana-labs/solana#32381]
#### Problem
I have found instances where the solana CLI `solana stakes` function is showing outdated balances. I've often thought it was strange that this tool often shows `delegatedStake` balances that exceed the `accountBalance` (many many examples), but only now do I think that it is a mistake.

The example I found relates to a large stake unlock coming up in August, for what the CLI reports as an account with 2.9M sol delegated: cGCSVim9tca6HXknaHYrHCqM3ZfY5N8NnvpT8m27bgA.

Funny thing is, the custodian allowed a withdrawal of the full balance (prior to the lockup expiry) to a different stake account, HcTDaQXACrWUGZY6q1mWYFoxaQvqiBRR1D7JqFJgXrHM, which got a new lockup date of 1677974400 / 2023-03-05; already expired. The obvious issue is that with the old lockup still in solana stakes, they will anticipate that a large unlock can be expected. However, there's actually no money in this account (cGCSVim9tca6HXknaHYrHCqM3ZfY5N8NnvpT8m27bgA). In general, the discrepancies between what is shown in `solana stakes` and reality are significant enough that they should be corrected. I will also note that *both* solscan.io and solana.fm seem to believe the cGCS account still has a delegated balance of 2.9M SOL in it. I don't know where they get their data, but looks like the source of it is the same.

I have attached two images. The first is what `solana stakes` *thinks* the account balances are (note: 2.911M sol in cGCS delegatedStake field):
![image](https://github.com/solana-labs/solana/assets/103349226/505709d7-aca4-4568-ad5a-2d00533a8e3b)

 The second image comes from `solana stake account $address`, which tells you the correct balance, as far as I can tell:
![image](https://github.com/solana-labs/solana/assets/103349226/4dbdc3e1-5aca-40e0-83da-6b14d0c3936d)

#### Proposed Solution
This is above my pay grade. I don't know how to fix it. But I think that the root of the issue is that `solana stakes` is reporting outdated info for the `delegatedBalance`, which is a bug. My belief is that `accountBalance` and `activeStake` fields are correct.

Thanks for looking into this!

-Ash

**Comment by ashpoolin** [comment]
Here's what you get if you sum all of the account balance, delegated and active stake columns from the `solana stakes` output (Note, I call `solana stakes --output json` | in2csv --format json > solana_stakes.csv` to convert it to a csv):
![image](https://github.com/solana-labs/solana/assets/103349226/d70ed876-9c62-4ad2-b777-72b9b440cec8)

If this is an issue, and I'm not just being stupid somehow, the scope of the issue is large... The delegated stake shows nearly 517M SOL, yet the total account balances are only 417M (100M difference). So how could that be?

**Comment by 2501babe** [comment]
i looked into this and im inclined to say its working as intended, albeit maybe confusing. with `--output json`, all this is doing is putting the raw data from these structs into json:
```
  {
    "stakePubkey": "cGCSVim9tca6HXknaHYrHCqM3ZfY5N8NnvpT8m27bgA",
    "stakeType": "Stake",
    "accountBalance": 54065413,
    "creditsObserved": 100672267,
    "delegatedStake": 2911021051782533,
    "delegatedVoteAccountAddress": "CertusDeBmqN8ZawdkxK5kFGMwBXdudvWHYwtNgNhvLu",
    "activationEpoch": 223,
    "deactivationEpoch": 285,
    "staker": "HKd8LdhjUyhp2z4kYgpJxc4pzKCCKR4yC14EFSLNENtw",
    "withdrawer": "HKd8LdhjUyhp2z4kYgpJxc4pzKCCKR4yC14EFSLNENtw",
    "unixTimestamp": 1691971200,
    "epoch": 0,
    "custodian": "Mc5XB47H3DKJHym5RLa9mPzWv5snERsF3KNv5AauXK8",
    "rentExemptReserve": 2282880 
  },
```

this account was activated at epoch 223 and deactivated at 285, then someone withdrew most but not all of the lamports. the delegation struct isnt updated for inactive accounts. if someone were to reactivate this account, the delegated amount would be updated to account balance minus rent exempt reserve

the default view from `solana stakes` without the output flag is identical to `solana stake-account`:
```
Stake Pubkey: cGCSVim9tca6HXknaHYrHCqM3ZfY5N8NnvpT8m27bgA
Balance: 0.054065413 SOL
Rent Exempt Reserve: 0.00228288 SOL
Stake account is undelegated
Stake Authority: HKd8LdhjUyhp2z4kYgpJxc4pzKCCKR4yC14EFSLNENtw
Withdraw Authority: HKd8LdhjUyhp2z4kYgpJxc4pzKCCKR4yC14EFSLNENtw
Lockup Timestamp: 2023-08-14T00:00:00Z
Lockup Custodian: Mc5XB47H3DKJHym5RLa9mPzWv5snERsF3KNv5AauXK8
```

**Comment by ashpoolin** [comment]
Thanks Hana, I follow the analysis which is very good.

Are inactive coins technically delegated? If not, it seems the delegated struct [balance] might be better off being zeroed out after deactivation is complete (pretty sure this is what you are describing in that last line).

Thanks again for weighing in on this question, very helpful.

**Comment by 2501babe** [comment]
theres no point in rewriting the onchain data in `Stake` after deactivation, it would require another transaction and more code complexity inside the stake program for no benefit. dashboards and stuff just need to handle the deactivation case
