### ISSUE TITLE
cargo build-bpf  doesn't work 

### ISSUE THREAD

**Issue by oulaoba** [solana-labs/solana#32397]
#### Problem
when i run "cargo build-bpf" i got a ERROR 
```
[2023-07-06T08:42:54.813332000Z ERROR cargo_build_sbf] Failed to execute /Users/xh/.cache/solana/v1.37/platform-tools/rust/bin/rustc: No such file or directory (os error 2)
```

this is my env ⬇️ . i installed Solana by [Local Development Quickstart](https://docs.solana.com/getstarted/local).
but my ".cache/" folder is empty , nothing in this folder
```
    ~ ····································································································· 17:01:28 
❯ rustup --version
rustup 1.26.0 (5af9b9484 2023-04-05)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.72.0-nightly (d9c13cd45 2023-07-05)`

    ~ ····································································································· 17:01:38 
❯ rustc --version
rustc 1.72.0-nightly (d9c13cd45 2023-07-05)

    ~ ····································································································· 17:02:01 
❯ cargo --version
cargo 1.72.0-nightly (5b377cece 2023-06-30)

    ~ ····································································································· 17:02:10 
❯ solana --version
solana-cli 1.16.2 (src:02d5647b; feat:2891131721, client:SolanaLabs)
```
my computer information is ⬇️
···
macOS Ventura 13.4.1
cpu Intel Core i7 6 core
···

**Comment by parjanyaacoder** [comment]
Facing same issue. Any solution ? 

```
rustup --version
rustup 1.26.0 (5af9b9484 2023-04-05)

rustc --version
rustc 1.70.0 (90c541806 2023-05-31)

cargo --version
cargo 1.70.0 (ec8a8a0ca 2023-04-25)

solana --version
solana-cli 1.10.31 (src:77a40cd8; feat:4192065167)
```

**Comment by oulaoba** [comment]
Damn it ! solana env config is killing me ! 

i switch `solana-cli` version to `1.14.20 `. and run `cargo build-bpf` again , solana say :
`error: package 'solana-program v1.16.2' cannot be built because it requires rustc 1.68.0 or newer, while the currently active rustc version is 1.62.0-dev`

then ,i switch rust toolchain versioin to  `1.62.0 && 1.68.0`, it still  tell me 
`'solana-program v1.16.2' cannot be built because it requires rustc 1.68.0 or newer, while the currently active rustc version is 1.62.0-dev`

i install and uninstall again and again , set the default , restart  my computer . It's still doesn’t work !

God ! save me plz !!!

**Comment by oulaoba** [comment]
Tried various solutions, finally downgrading `solana-cli` version to `1.16.1` solved the problem.
@parjanyaacoder

**Comment by Sam-Berman1** [comment]
Disable Norton Data Protection (for the command duration) 
-this worked

**Comment by Sam-Berman1** [comment]
nvm.. I uninstalled the .local/solana directory, reinstalled at 11.6.3
was having the same issue still.
disabled data protection
got a warning my computer was trying to use .github 
and now...

$ cargo build-bpf
info: uninstalling toolchain 'solana'
info: toolchain 'solana' uninstalled
error: no such command: `+solana`

        Cargo does not handle `+toolchain` directives.
        Did you mean to invoke `cargo` through `rustup` instead?

I think this is antivirus related

**Comment by KirillLykov** [comment]
> 



> Damn it ! solana env config is killing me !
> 
> i switch `solana-cli` version to `1.14.20 `. and run `cargo build-bpf` again , solana say : `error: package 'solana-program v1.16.2' cannot be built because it requires rustc 1.68.0 or newer, while the currently active rustc version is 1.62.0-dev`
> 
> then ,i switch rust toolchain versioin to `1.62.0 && 1.68.0`, it still tell me `'solana-program v1.16.2' cannot be built because it requires rustc 1.68.0 or newer, while the currently active rustc version is 1.62.0-dev`
> 
> i install and uninstall again and again , set the default , restart my computer . It's still doesn’t work !
> 
> God ! save me plz !!!

Maybe because it complains about the rustc version that `cargo-build-sbf` downloads? See https://github.com/solana-labs/solana/issues/31428

**Comment by 6amson** [comment]
Hello, is anyone getting this error at all "[2024-04-03T16:51:26.963362217Z ERROR cargo_build_sbf] Failed to install platform-tools: error sending request for url (https://github.com/solana-labs/platform-tools/releases/download/v1.37/platform-tools-linux-x86_64.tar.bz2): operation timed out"  i cant seem to find a solution anywhere.

**Comment by 0xrin1** [comment]
> Hello, is anyone getting this error at all "[2024-04-03T16:51:26.963362217Z ERROR cargo_build_sbf] Failed to install platform-tools: error sending request for url (https://github.com/solana-labs/platform-tools/releases/download/v1.37/platform-tools-linux-x86_64.tar.bz2): operation timed out" i cant seem to find a solution anywhere.

i have this problem too

**Comment by Martin896** [comment]
ERROR cargo_build_sbf] Failed to execute /home/martinmary/.local/share/solana/install/releases/1.18.8/solana-release/bin/sdk/sbf/dependencies/platform-tools/llvm/bin/llvm-readelf: Exec format error (os error 8)

**Comment by oulaoba** [comment]
> Hello, is anyone getting this error at all "[2024-04-03T16:51:26.963362217Z ERROR cargo_build_sbf] Failed to install platform-tools: error sending request for url (https://github.com/solana-labs/platform-tools/releases/download/v1.37/platform-tools-linux-x86_64.tar.bz2): operation timed out" i cant seem to find a solution anywhere.

Did your proxy Opend?

**Comment by oulaoba** [comment]
> Opend



> > Hello, is anyone getting this error at all "[2024-04-03T16:51:26.963362217Z ERROR cargo_build_sbf] Failed to install platform-tools: error sending request for url (https://github.com/solana-labs/platform-tools/releases/download/v1.37/platform-tools-linux-x86_64.tar.bz2): operation timed out" i cant seem to find a solution anywhere.
> 
> i have this problem too

Show more information, such as OS info, rustc version, and solana version.

**Comment by oulaoba** [comment]
> ERROR cargo_build_sbf] Failed to execute /home/martinmary/.local/share/solana/install/releases/1.18.8/solana-release/bin/sdk/sbf/dependencies/platform-tools/llvm/bin/llvm-readelf: Exec format error (os error 8)


Show more information, such as OS info, rustc version,solana version.
