### ISSUE TITLE
Recent builds attempt to use "Snappy" Compression with rocksdb, which is not included as a feature

### ISSUE THREAD

**Issue by DaveWK** [solana-labs/solana#32402]
#### Problem

In some of the recent builds of solana (can't remember when this started) there seems to be a misconfigured default for the rocksdb compression. I have just seen this on v1.16.2 as well.

When I run the ledger, it eventually gives me the error:

```[2023-07-06T18:32:37.523019853Z INFO  solana_ledger::blockstore] Opening database at "/data/sol/ledger/rocksdb"
thread 'main' panicked at 'Failed to open ledger database: RocksDb(Error { message: "Not implemented: Unsupported compression method for this build: Snappy" })', core/src/validator.rs:1586:10
```
then a stack trace, and:

```[2023-07-06T18:32:37.544714738Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at 'Failed to open ledger database: RocksDb(Error { message: \"Not implemented: Unsupported compression method for this build: Snappy\" })', core/src/validator.rs:1586:10" location="core/src/validator.rs:1586:10" version="1.16.2 (src:00000000; feat:2891131721, client:SolanaLabs)"```

and it restarts. 

I noticed that there appears to be a hidden flag to specify the compression at:
https://github.com/solana-labs/solana/blob/0da01270efe72d5d4c6652199d223a373c6f839e/validator/src/cli.rs#L603
but when I tried adding `--rocksdb-ledger-compression lz4` to my start-up it still crashed and complained about snappy

To work around this, I changed the rocksdb dep in the ledger Cargo.toml to:
```
[dependencies.rocksdb]
# Avoid the vendored bzip2 within rocksdb-sys that can cause linker conflicts
# when also using the bzip2 crate
version = "0.21.0"
default-features = false
features = ["lz4", "snappy"]
```
and then it is able to continue running (I assume by using snappy for rocksdb compression)

I did notice that at:
https://github.com/solana-labs/solana/blob/0da01270efe72d5d4c6652199d223a373c6f839e/ledger/src/blockstore_options.rs#L115
https://github.com/solana-labs/solana/blob/0da01270efe72d5d4c6652199d223a373c6f839e/validator/src/main.rs#L1622

it appears snappy and zlib are in the list along with lz4. 

#### Proposed Solution
I'd either remove the snappy/zlib options from the code I outlined above, or add snappy and zlib as features for the rocksdb dep. 

Alternatively (probably too much work) you could do something like is done with `perf` and AVX2: https://github.com/solana-labs/solana/blob/0da01270efe72d5d4c6652199d223a373c6f839e/perf/src/lib.rs#L64 where it skips compression types that are not enabled.

**Comment by t-nelson** [comment]
what's your output of `cargo tree --invert librocksdb-sys --depth 0`? i'm guessing this is something to do with how the c bindings are configuring the sys crate

**Comment by DaveWK** [comment]
```
cargo tree --invert librocksdb-sys --depth 0
  Downloaded serial_test_derive v0.9.0
  Downloaded test-case-macros v2.2.2
  Downloaded gag v1.0.0
  Downloaded bytecount v0.6.3
  Downloaded test-case v2.2.2
  Downloaded unarray v0.1.4
  Downloaded rand_xorshift v0.3.0
  Downloaded doc-comment v0.3.3
  Downloaded normalize-line-endings v0.3.0
  Downloaded wait-timeout v0.2.0
  Downloaded serial_test v0.9.0
  Downloaded bit-set v0.5.2
  Downloaded rusty-fork v0.3.0
  Downloaded predicates-core v1.0.2
  Downloaded difflib v0.4.0
  Downloaded predicates v2.1.5
  Downloaded assert_cmd v2.0.8
  Downloaded float-cmp v0.9.0
  Downloaded proptest v1.2.0
  Downloaded regex-syntax v0.6.29
  Downloaded dashmap v5.2.0
  Downloaded filedescriptor v0.8.1
  Downloaded predicates-tree v1.0.4
  Downloaded termtree v0.2.3
  Downloaded raptorq v1.7.0
  Downloaded 25 crates (826.4 KB) in 0.94s
librocksdb-sys v0.11.0+8.1.1
```

**Comment by DaveWK** [comment]
A lot of the C bindings only are activated when there's an explicit `<Name>_LIB_DIR` env var set (which I am not setting) -- The snappy build section: https://github.com/rust-rocksdb/rust-rocksdb/blob/master/librocksdb-sys/build.rs#L260 is a little different it  seems. I do have snappy's libs installed via os package manager, which kind of adds an odd piece to that puzzle, since I would have expected it to dynamically link to the os lib if it was using it for the binding

**Comment by t-nelson** [comment]
can you try removing the os package manager's -dev package, `cargo clean` and rebuild?  i don't see much in the way of suspect, recent changes in the rocks crates

cc/ @yhchiang-sol @steviez

**Comment by DaveWK** [comment]
So I just did a build on a system without the snappy-devel package, and it did not have this issue, so it does seem like or some reason the rocksdb C binding is being "overly helpful" and detecting that package from my /usr/lib64  despite the feature not being enabled, but then either doesn't dynamically link it, or blocks it from being used because it was not enabled in the Cargo.toml..

Would probably need to produce a sample for the rocksdb folks to reproduce it more concisely, but according to the rust docs, Snappy should only be the default if the feature is enabled: https://docs.rs/rocksdb/latest/rocksdb/struct.Options.html#method.set_compression_type so something in their logic is "half-enabling" Snappy as default then blocking it from running.

Could be potentially better from a defensive coding standpoint to always explicitly define the compression before instantiating a rocksdb handle to avoid unexpected defaults (IE https://github.com/solana-labs/solana/blob/v1.16.2/ledger/src/blockstore_db.rs#L1816 could gather all the rocksdb params and include them in the `new()` vs re-configuring them each after it's created.

Thanks for the help!

**Comment by DaveWK** [comment]
For posterity, filed a bug with rocksdb: https://github.com/rust-rocksdb/rust-rocksdb/issues/799

**Comment by steviez** [comment]
Looks like you already narrowed it down, but agreed that we haven't touched anything around this in our `ledger` create in a while, so my gut was upstream as well.

> Could be potentially better from a defensive coding standpoint to always explicitly define the compression before instantiating a rocksdb handle

I agree with that - I don't really love the default behavior of that function changing based on whether the feature is enabled or not. Threw together a quick PR at https://github.com/solana-labs/solana/pull/32426

**Comment by yhchiang-sol** [comment]
> I agree with that - I don't really love the default behavior of that function changing based on whether the feature is enabled or not. Threw together a quick PR at https://github.com/solana-labs/solana/pull/32426

Thanks @steviez for creating https://github.com/solana-labs/solana/pull/32426.

I'm not 100% following all changes in rust-rocksdb, but in the C++ RocksDB, Snappy compression is the default compression.  I think https://github.com/solana-labs/solana/pull/32426 is the correct fix to ensure our ledger's default behavior.
