### ISSUE TITLE
Inconsistent use of "pubkey" and "id"

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#3241]
#### Problem

Our  code randomly calls the public key of a keypair  either "pubkey" or  "id", and sometimes calls it just "key".

#### Proposed Solution

Switch to "pubkey". Justification: while  our codebase nearly always uses public keys to uniquely  identify things, other types can too. For example, we use signatures to uniquely identify transactions. Also, there's a whole world of blockchain identity solutions out there that we'll be interacting with more. It's easy to imagine our use  of the term "id" will be confusing (and it's  already leaked into SDK via ProgramId). "pubkey" is short and precise.

**Comment by garious** [comment]
Thinking more on this, how about account.rs alias `Pubkey` as `AccountId`?  Then all the `ProgramId` uses can be left untouched. Names like `alice_id` could optionally be extended to `alice_account_id`.

**Comment by mvines** [comment]
Turns out before 0.15 branching I renamed a bunch of the _id variables to _pubkey (alice_id => alice_pubkey).  ProgramId is the one exception
