### ISSUE TITLE
StandardBroadcastRun panicked on pop net cluster

### ISSUE THREAD

**Issue by steviez** [solana-labs/solana#32466]
#### Problem

@jeffwashington and I were looking at one of the pop-net (the large number of accounts cluster) nodes that panicked within `StandardBroadcastRun`:
```
   0: rust_begin_unwind
             at ./rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at ./rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at ./rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:114:5
   3: <solana_turbine::broadcast_stage::standard_broadcast_run::StandardBroadcastRun as solana_turbine::broadcast_stage::BroadcastRun>::run
   4: solana_turbine::broadcast_stage::BroadcastStage::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2023-07-11T23:42:38.497235025Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solBroadcast" one=1i message="panicked at 'called `Option::unwrap()` on a `None` value', turbine/src/broadcast_stage/standard_broadcast_run.rs:445:61" location="turbine/src/broadcast_stage/standard_broadcast_run.rs:445:61" version="1.17.0 (src:00000000; feat:461617547, client:SolanaLabs)"
```
Unfortunately, the node did not have `RUST_BACKTRACE=full` set, but as jwash and I browsed through the code, we think we able to narrow down the call-path a little. This is a rough working theory as neither jwash or I have spent a lot of time in this are of the codebase. Lastly, the node was running commit 9b405b21ff438444a5b1b46cce83439c4fb7db2a for the sake of examining line numbers.

The panic itself is an unwrap of a `None`:
https://github.com/solana-labs/solana/blob/9b405b21ff438444a5b1b46cce83439c4fb7db2a/turbine/src/broadcast_stage/standard_broadcast_run.rs#L444-L445

The function `report_and_reset_stats` has two callers: `finish_prev_slot()` and `process_receive_results()`. However,
- `finish_prev_slot()` matches on `self.unfinished_slot`
- `finish_prev_slot()` can only call `report_and_reset_stats` if `self.unfinished_slot` is a `Some(...)`
    - More specifically, this only gets called if we had an unfinished slot and just received entries for a new bank (ie the node decided to bail on a leader slot)

So, the `.unwrap()` is ok and `finish_prev_slot()` is seemingly not the offender.

Looking at `process_receive_results()`, this function calls `finish_prev_slot()` AND `entries_to_shreds()`, both of which touch `self.unfinished_slot`:
https://github.com/solana-labs/solana/blob/9b405b21ff438444a5b1b46cce83439c4fb7db2a/turbine/src/broadcast_stage/standard_broadcast_run.rs#L248-L271

- Per above, we know `finish_prev_slot()` itself did not panic. But, this function gets called first and has the ability to set `self.unfinished_slot` to `None`
- `entries_to_shreds()` will result in `self.unfinished_slot` being a `Some(...)` unless one of the three early returns is hit.
   - Two of the early returns are an `Err` which would result in a panic since the result of `.entries_to_shreds()`is unwrapped on line 271. The node did not panic on this unwrap, so we know neither of these cases were hit.
   - The other early return can occur when `self.unfinished_slot` is `None` coming into `entries_to_shreds()`; this return is NOT an `Err` and leaves `self.unfinished_slot` as a `None` ... this case is seemingly the culprit.
https://github.com/solana-labs/solana/blob/9b405b21ff438444a5b1b46cce83439c4fb7db2a/turbine/src/broadcast_stage/standard_broadcast_run.rs#L131-L142 

#### Proposed Solution
- Figure out how the node was able to get into this state
- As a side note, we can probably avoid the `.unwrap()` below and use `?` to pass the `Result` up the call chain. The two `Err` cases correspond to a slot being too bit so failing makes sense, but guessing we may handle that `Result` a little more gracefully higher up
https://github.com/solana-labs/solana/blob/9b405b21ff438444a5b1b46cce83439c4fb7db2a/turbine/src/broadcast_stage/standard_broadcast_run.rs#L271

**Comment by jeffwashington** [comment]
we hit this again last night:
```
[2023-07-14T11:45:32.037909926Z INFO  solana_metrics::metrics] datapoint: banking_stage-vote_packet_counts id=5i slot=588765i dropped_gossip_votes=0i dropped_tpu_votes=0i
   0: rust_begin_unwind
             at ./rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at ./rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
   2: core::panicking::panic
             at ./rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:114:5
   3: <solana_turbine::broadcast_stage::standard_broadcast_run::StandardBroadcastRun as solana_turbine::broadcast_stage::BroadcastRun>::run
   4: solana_turbine::broadcast_stage::BroadcastStage::run
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[2023-07-14T11:45:32.070214958Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solBroadcast" one=1i message="panicked at 'called `Option::unwrap()` on a `None` value', turbine/src/broadcast_stage/standard_broadcast_run.rs:444:61" location="turbine/src/broadcast_stage/standard_broadcast_run.rs:444:61" version="1.17.0 (src:00000000; feat:461617547, client:SolanaLabs)"
```
pop-net-sv15-3
