### ISSUE TITLE
Geyser notifying accounts without changes (cont)

### ISSUE THREAD

**Issue by linuskendall** [solana-labs/solana#32493]
#### Problem

Geyser is notifying accounts without changes to them and which doesnt appear in any transactions. It has bee npreviously reported that this is related to rent management, however some of the reported account changes being notified that we have observed is not clear whether they are related to this?

Using the gRPC plugin and the MEv2 program we can reproduce this activity easily:

```
./grpcurl  -proto geyser.proto  -d '{ "accounts": {"test": {"owner": "M2mx93ekt1fmXSVkTrUL9xVFHkmME8HTUi5Cyc5aF7K"}} }' geyser-endpoint:443 geyser.Geyser/Subscribe | jq '.account.account | select(.txnSignature == null)' 
```

This will show a large number of account updates for accounts that have last had their transaction updated 4-5 months ago. We can see that some of these have rentEpoch set and others do not. In the case of the ones that have rentEpoch set, the rentEpoch is currently reported as 361 (we are right now in epoch 475). This query returns no responses (i.e. there are no entries where the rentEpoch is not either null or 361):

```
./grpcurl  -proto geyser.proto  -d '{ "accounts": {"test": {"owner": "M2mx93ekt1fmXSVkTrUL9xVFHkmME8HTUi5Cyc5aF7K"}} }' geyser-endpoint:443 geyser.Geyser/Subscribe | jq '.account.account | select(.txnSignature == null) | select(.rentEpoch != "361") | select(.rentEpoch != null)'
```

Looking at the account stream which does not have any rentEpoch sepecified with this query:

```
./grpcurl  -proto geyser.proto  -d '{ "accounts": {"test": {"owner": "M2mx93ekt1fmXSVkTrUL9xVFHkmME8HTUi5Cyc5aF7K"}} }' geyser-endpoint:443 geyser.Geyser/Subscribe | jq '.account.account | select(.txnSignature == null) | select(.rentEpoch != "361")'
```

We get some responses like this:

```
{
  "pubkey": "Hp1V4nFmkKiomviVBTvHMjFq/Ss7qfFKJAn/QI41228=",
  "lamports": "2011440",
  "owner": "BSGfiZqB1P+E+1k9Lt+KkKwbOrNCWPffIz6lAwKxvS4=",
  "data": "yKSZu3Y8yDPDGxjMPhSKClKTgYkg7frtqzkeSTNsC3TbZp0QRwNCS9uTXoSM8D7ECG++7T2pLJpANeJtc0ZgIQXMqaPMGbJNCK/25BBZJGavm0hr5XZ58vaLQc3cMeAgkndKj2Ni7RMAvKBlAQAAAFidgFB4RzTYbBuYEsvfgZbv0PU7jp8aNLwJdVjlK41│·1UAQAAAAAAAAD/AAAAAAAAAAA=",
  "writeVersion": "786354622200"
}
{
  "pubkey": "Hp1tKdOdP72l4cSn1Szfb+wJpb4dWLCACRoRzf2Uvwg=",
  "lamports": "2234160",
  "owner": "BSGfiZqB1P+E+1k9Lt+KkKwbOrNCWPffIz6lAwKxvS4=",
  "data": "Ae5IiYoV/vnDGxjMPhSKClKTgYkg7frtqzkeSTNsC3TbZp0QRwNCS6OGKZSUd5kLGVezMQKRSPQgPZvzl0LyNBA01+rQvOZsCK/25BBZJGavm0hr5XZ58vaLQc3cMeAgkndKj2Ni7RMAIUFSAAAAADF+51fIew6YsAU9BkEe4/9AVVpVV0jNbjE2DILtx7N│·N4cHBiUFcIRaejbfdYjuAn5/nJeORne5ZKHXHLV9yqmOABAAAAAAAAAP7//////////w==",
  "writeVersion": "786354622425"
}
{
  "pubkey": "Hp12yaYhnX8cwv+BrG+DDjkm1jlHm53z4Pk4LalFCb8=",
  "lamports": "2011440",
  "owner": "BSGfiZqB1P+E+1k9Lt+KkKwbOrNCWPffIz6lAwKxvS4=",
  "data": "yKSZu3Y8yDPDGxjMPhSKClKTgYkg7frtqzkeSTNsC3TbZp0QRwNCS0y0S/aRYoiJJJhtchvLyS3kaPbyCXS5aQR/LtBbrq4WCK/25BBZJGavm0hr5XZ58vaLQc3cMeAgkndKj2Ni7RMAasBhAAAAAMGkqZOpjDosOrKgmjmZlH/VBVhiRNfLh0+wi6ZWyNO│·OBAQAAAAAAAAD/6D7YZAAAAAA=",
  "writeVersion": "786354622535"
}
{
  "pubkey": "Hp11lTpZO8WEtUKgGx2NgogtvPzElKeMxOcV+CNalhY=",
  "lamports": "3118080",
  "owner": "BSGfiZqB1P+E+1k9Lt+KkKwbOrNCWPffIz6lAwKxvS4=",
  "data": "wzcuKTYH4ZvDGxjMPhSKClKTgYkg7frtqzkeSTNsC3TbZp0QRwNCSwZuHrQz2GoWYcYTDctMOtHeWahFpOygc3FngSh4bFnaYDH94PpmQbBCGmGgi3aiJioX2BXpO+Eq1NPDuMECr7CAJTWWAgAAAKbF94xxcg6QFeXvu9w75FxHiVL7Y3wvKgUO28kHZ8r│·rhAQAAAAAAAAD9J606ZgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA│·AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
  "writeVersion": "786354622550"
}
{
  "pubkey": "Hp2Ju3/SWEW+n0ICn69t5NmcFcPRZ3p9wCvzblrCIxY=",
  "lamports": "2011440",
  "owner": "BSGfiZqB1P+E+1k9Lt+KkKwbOrNCWPffIz6lAwKxvS4=",
  "data": "yKSZu3Y8yDPDGxjMPhSKClKTgYkg7frtqzkeSTNsC3TbZp0QRwNCS0y0S/aRYoiJJJhtchvLyS3kaPbyCXS5aQR/LtBbrq4WCK/25BBZJGavm0hr5XZ58vaLQc3cMeAgkndKj2Ni7RMANHfrDgAAAMIBB1TH3AtJ9xyZtmUHEMZUwsueRNnyqXMYbPtg/96│·63AQAAAAAAAAD/QQ3YZAAAAAA=",
  "writeVersion": "786354624582"
}
```

The notifications are coming in pubkey ordering from the looks of this?

The sample keys from the responses above are:
- 34WNzkEpmPWrVVhCKk3LVU6J7KTpU4HL2koFgVmNEaR4
- 34WTfHTPWP1PRPHTLALQyCYAKG9vyN8tFwsrVfGy5Rp3
- 34WVb8mNp7ibMf21FYihUvS8h3yFUcBJeHqfpuSpaT9G
- 34WVM8ggwsDZu2wAvp9Wc8C3iw4AykxBTr5rhjZCc8sX
- 34WZPJYx9nQBQAowKfULm1BAMRHpUnxqsy2u4QCfN4q3

Some of these accounts have been touched recently, some have not been modified in 5-7 months? There doesnt seem to be a clear relationship between these accounts.

A few questions:
- Why are we getting accounts reported with rentEpoch 361?
- What are the notifications with rentEpoch == null and txSig == null? 

It seems that in order to explain this there is more going on that just rent collection notifications? In several of these cases the accounts are maybe rent exempt and do not have a rentEpoch ? Also it seems that the rentEpoch value of 361 seems a very long time ago for those accounts that have this value to be notified now?

#### Proposed Solution 

First establish why are these notifications being sent over the geyser interface? This would allow us to determine whether or not these are really of interest to the end user or not. It might be worth separating these types of notifications into a separate stream not to do callbacks to the plugin if these are not relevant to most users. Otherwise, at least we should have some clear ability to segregate these out and filter them for the user.

Presently we could separate them by filtering for notifications where the tx signature is missing and/or rentEpoch is missing. However, without a clear idea of why these notifications are happening it is not sure whether it is advisable to do so or not.

Tag @Arrowana @fanatid

**Comment by t-nelson** [comment]
cc/ @lijunwangs

**Comment by ADanilychevJr** [comment]
Have noticed this for quite a while, would be interested in a resolution on this - if these are in-fact redundant updates, flagging & filtering these would improve resource utilization for indexers that rely on Geyser

**Comment by ADanilychevJr** [comment]
@lijunwangs mentioned we can filter based on the txn field of ReplicaAccountInfoV3, so when txSig==null we can drop

**Comment by buffalu** [comment]
I’ve seen this subscribing to lookup table program updates
