### ISSUE TITLE
Using Compute Budget ix `requestUnits` fails on 1.16

### ISSUE THREAD

**Issue by jacobcreech** [solana-labs/solana#32549]
#### Problem

Using the `requestUnits` ix on the Compute Budget program times out when sending transaction via RPC on Devnet.

Cluster: Devnet

Reproducible code:
```javascript
import {
  Keypair,
  Connection,
  LAMPORTS_PER_SOL,
  sendAndConfirmTransaction,
  ComputeBudgetProgram,
  SystemProgram,
  Transaction,
  clusterApiUrl,
} from "@solana/web3.js";

(async () => {
  const payer = Keypair.generate();
  const toAccount = Keypair.generate().publicKey;

  const connection = new Connection(clusterApiUrl("devnet"), "confirmed");

  const airdropSignature = await connection.requestAirdrop(
    payer.publicKey,
    LAMPORTS_PER_SOL
  );

  await connection.confirmTransaction(airdropSignature);

  const modifyComputeUnits = ComputeBudgetProgram.requestUnits({
    units: 1_000_000,
    additionalFee: 0,
  });

  const transaction = new Transaction()
    .add(modifyComputeUnits)
    .add(
      SystemProgram.transfer({
        fromPubkey: payer.publicKey,
        toPubkey: toAccount,
        lamports: 10000,
      })
    );

  const signature = await sendAndConfirmTransaction(connection, transaction, [
    payer,
  ]);
  console.log(signature);
  const result = await connection.getParsedTransaction(signature);
  console.log(result);
})();
```

IXs `setComputeUnitLimit` and `setComputeUnitPrice` still work fine. 

#### Proposed Solution

The ix `requestUnits` should not break until feature `EfhYd3SafzGT472tYQDUc4dPd2xdEfKs5fwkowUgVt4W` is activated.

**Comment by taozhu-chicago** [comment]
One possibility is `RequestUnitsDeprecated` cannot be used with `SetComputeUnitPrice` nor `SetComputeUnitLimit` in same transaction, otherwise it'd fail with `duplicate_instruction_error`. 

Above script does not seem to be the case, just to share while I am working on repro.

**Comment by t-nelson** [comment]
> just to share while I am working on repro

was the patch to `solana transfer` that i provided last night insufficient?

**Comment by taozhu-chicago** [comment]
Yea, it's very helpful to reproduce against testnet. Needed to do same against `-u localhost` and to confirm a finding. Pretty sure this https://github.com/solana-labs/solana/blob/v1.16.4/runtime/src/transaction_priority_details.rs#L31 is the cause - leader priority queue doesn't seem want to support deprecated ix, tx with deprecated ix is dropped off leader's queue. Wondering why, or maybe relates to some other changes. In any case, should have a PR soon.

**Comment by apfitzge** [comment]
@taozhu-chicago yeah, that's the place.

I figured this was supposed to be able to return `None` for an unprioritized transaction - turns out no - in `ImmutableDeserializedPacket::new`:
```rust
        // drop transaction if prioritization fails.
        let mut priority_details = sanitized_transaction
            .get_transaction_priority_details(packet.meta().round_compute_unit_price())
            .ok_or(DeserializedPacketError::PrioritizationFailure)?;
```

**Comment by taozhu-chicago** [comment]
right, I'm looking at the same thing.  Difference between "if not explicitly set priority, use default" and "if no priority, drop tx" caused it. What would be the most proper solution: 
1. change `false` to `true` so to always support deprecated ix (which can be removed when feature is enabled);
2. use default priority if not explicitly set by user;

**Comment by t-nelson** [comment]
why are these feature gate values hard coded instead of respecting the feature set?

https://github.com/solana-labs/solana/blob/83ac15dd976282fc559c218d77a1c3b79c23d001/runtime/src/transaction_priority_details.rs#L28-L35

also that comment on ln31 using language that's inverted from the name of the variable that it's setting is very :face_with_head_bandage: 

https://github.com/solana-labs/solana/blob/83ac15dd976282fc559c218d77a1c3b79c23d001/program-runtime/src/compute_budget.rs#L181

**Comment by taozhu-chicago** [comment]
> why are these feature gate values hard coded instead of respecting the feature set?

Not a satisfying answer, but `get_transaction_priority_details()` was meant to requires nothing but `tx` itself. As feature gates status keep being added to compute_budget, they became required here too. But plumbing current bank's feature_set to `ImmutableDeserializedPacket` then to `get_transaction_priority_details` isn't trivial. As an alternative, for the purpose of getting transaction priority details, we'd parse explicitly set priority with assumption that all feature gates are enabled, using `default` as catch all. 

> also that comment on ln31 using language that's inverted from the name of the variable that it's setting is very 🤕

Agree, twisted it is. (status quo is "support", so the gate is to "stop supporting", to emulate gates activated which is "not supporting" therefore `false`). 🤕

**Comment by t-nelson** [comment]
> status quo is "support"

this is probably a proocess bug.  we should most likely encourage all symbols that references a feature gate to use it's module name explicitly.  we've been bitten by inconsistencies like this in the past too
