### ISSUE TITLE
Improve Benchmark a Cluster document: from one machine local cluster to a multipe machines local cluster 

### ISSUE THREAD

**Issue by KunPengRen** [solana-labs/solana#32554]
#### Problem
Hi I would like to ask how to easily run a multiple nodes testnet with multiple machines. Because the current document [Benchmark a cluster](https://docs.solana.com/cluster/bench-tps#configuration-setup) only shows how to run multiple nodes in one machine. The performance result has the bottleneck of one machine's capability. I would ask how to run with multiple machines using the script under the ./multinode-demo folder.

#### Proposed Solution
TBD

**Comment by bw-solana** [comment]
You should be able to essentially follow the multinode-demo folder instructions, but update the `--entrypoint` parameter to point to the IP and gossip port of the bootstrap validator
