### ISSUE TITLE
Solana program deploys on devnet with Solana 1.16 are slow

### ISSUE THREAD

**Issue by ChewingGlass** [solana-labs/solana#32595]
#### Problem
Solana program deploys, after the release of solana 1.16 against devnet are much slower.

#### Proposed Solution
My guess is it's a new bug with the TPU client in 1.16. Fix that.

**Comment by mvines** [comment]
Does deploying with the v1.14 tools make a difference? 
Can you also please characterize "much slower".
The more details you provide, the faster the team will be able to help you

**Comment by ChewingGlass** [comment]
https://github.com/solana-labs/solana/assets/83885631/2b101dd7-6d73-4575-b169-c92db6a53f8d

Sorry, github will only allow potato quality. Here's a video. 

Solana 1.14.19 deploy works just fine. 1.16.1 is super slow, almost like it's only sending one at a time.

**Comment by godmodegalactus** [comment]
https://github.com/solana-labs/solana/pull/32631 PR which is build upon #32388 will help solve deployment issues.

Check this youtube video which compares deployment of spl_governance contract on testnet cluster.

https://www.youtube.com/watch?v=aNsZHmjsCFA

It took nearly 4 minutes with previous program deploy and with this implementation, it takes only 25 seconds and is much more reliable without any retries.

**Comment by ChewingGlass** [comment]
@godmodegalactus We use the TPU client in a variety of other utilities that bulk submit transactions. Is this just going to leave TPU client broken and you need to use these new methods in the PR instead?

**Comment by godmodegalactus** [comment]
> @godmodegalactus We use the TPU client in a variety of other utilities that bulk submit transactions. Is this just going to leave TPU client broken and you need to use these new methods in the PR instead? 

TPU client works well with staked identity. Sending transactions over unstaked quic connection is very very hard only 1 of 50 transactions get through. In previous logic we send transaction over TPU first and then RPC. Usually sending transaction over TPU is broken and it will wait for quic timeout before sending to RPC. So now we send it to RPC directly. TPU client will always we good to send transaction from one staked validator to another.

**Comment by ChewingGlass** [comment]
Why is the TPU client from an unstaked quic connection so much faster than bulk submitting in say, JavaScript? Will we need to change our code to keep it this way? We basically copied the old program deploy code. Which still seems to be working fast in 1.14. Does 1.16 change the validators in such a way this will no longer be true? Or have there just been changes to the rust impl behind TpuClient that make it slower?

**Comment by ChewingGlass** [comment]
https://github.com/helium/helium-program-library/blob/master/utils/hpl-utils/src/lib.rs#L23

Ugly implementation, but we use it a good amount.

**Comment by godmodegalactus** [comment]
> Why is the TPU client from an unstaked quic connection so much faster than bulk submitting in say, JavaScript? Will we need to change our code to keep it this way? We basically copied the old program deploy code. Which still seems to be working fast in 1.14. Does 1.16 change the validators in such a way this will no longer be true? Or have there just been changes to the rust impl behind TpuClient that make it slower?

I suspect moving from UDP to QUIC is the culprit here.

**Comment by KirillLykov** [comment]
I did some experiments with `program deploy` with different versions of solana-cli.
Result of each experiment is element of the array in the corresponding cell:

  Version  | Time |
| -------- | ------- |
| v1.14.18 | [0m15.9s, 0m15.35s, 0m16s] |
| v1.16.2  | [0m48s, 2m36.97s, 2m27s] |
| v1.17.0 (master, 1999138e124e47332985f0ff543bd37c34ddce81)  | [1m30s, 1m45s, 3m36s, 1m10s, 0m34s] |

So it looks like the problem persists in 1.16 and 1.17. The variance of the time is more impressive than the mean value

**Comment by AnderUstarroz** [comment]
Same problem! trying to deploy using Anchor `v0.28` and Solana CLI `v1.16.9`, but the deployment is so slow, I get `Blockhash expired` even using paid RPC:

```
anchor upgrade --provider.cluster https://MY_DEVNET_RPC_ADDRESS/  --program-id MY_PROGRAM_ADDRESS  target/deploy/my_program.so
...
...
Blockhash expired. 4 retries remaining
⠈   0.0% | Sending 4/517 transactions    
```

**Comment by AnderUstarroz** [comment]
Thanks @KirillLykov, 
Updated Solana CLI to 1.16.10 and deployments are fast again. All good.

**Comment by Bansalayush247** [comment]
I am using anchor 0.29.0 and getting the same error

**Comment by KirillLykov** [comment]
> I am using anchor 0.29.0 and getting the same error

I think it is more important what solana cli version in this context

**Comment by MubeenAbid001** [comment]
I have been receiving the same error and I am using Solana CLI 1.18.4 and trying to deploy on devnet, so I updated to 1.18.10 and then to 1.18.12  and it started sending the transactions much faster but I get the Timed Out error now, I still cannot deploy the smart contract on dev net. Any suggestions on how to solve it?

**Comment by MubeenAbid001** [comment]
> I have been receiving the same error and I am using Solana CLI 1.18.4 and trying to deploy on devnet, so I updated to 1.18.10 and then to 1.18.12 and it started sending the transactions much faster but I get the Timed Out error now, I still cannot deploy the smart contract on dev net. Any suggestions on how to solve it?

Update: We can re use the buffer created by saving the buffer keypair through command "solana-keygen recover --outfile <path to save keypair>" and then using it again to deploy using the command "solana program deploy --buffer <path to buffer keypair file>", that way is continues the deployment, it is not very effective because it took 2 retires for the spl_token (125 tx total) and for spl_token_2022 (over 600 tx total) it will take around 8-9 tries but it works.
