### ISSUE TITLE
Feature Gate: enable ZK Token proof program

### ISSUE THREAD

**Issue by samkim-crypto** [solana-labs/solana#32613]
### Description

Enable [ZK Token proof program](https://edge.docs.solana.com/developing/runtime-facilities/zk-token-proof).

### Feature ID

zk1snxsc6Fh3wsGNbbHAJNHiJoYgF29mMnTSusGx5EJ

### Activation Method

Single Core Contributor

### Deployment Considerations

The program is still pending an extra audit.

**Comment by willhickey** [comment]
This feature gate was replaced:
https://github.com/orgs/anza-xyz/projects/9/views/1?pane=issue&itemId=73058762&issue=anza-xyz%7Cfeature-gate-tracker%7C26

**Comment by hackingbutlegal** [comment]
404
