### ISSUE TITLE
Add howto guide for how to setup a validator and attach to the testnet

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#3261]
Let's add a howto guide (perhaps as a section of the book) that details how a 3rd party can setup a validator on the testnet.  This guide should not use `multinode-demo/` scripts in any form, instead should describe how to do this from the pure solana program deliverables.  Include how to setup the updater implemented at #3222 to keep the validator node up to date.

**Comment by mvines** [comment]
Current `solana-install`-based node bootstrap looks like this:
```bash
$ wget https://github.com/solana-labs/solana/releases/download/v0.13.0-infratest1/solana-install-x86_64-unknown-linux-gnu
$ chmod +x solana-install-x86_64-unknown-linux-gnu 
$ ./solana-install-x86_64-unknown-linux-gnu init --url http://api.beta.testnet.solana.com/
$ ./solana-install-x86_64-unknown-linux-gnu update
$ export PATH=~/.local/share/solana/install/bin:$PATH
```

**Comment by aeyakovenko** [comment]
how do we point to the testnet?

**Comment by mvines** [comment]
> how do we point to the testnet?

Like this:
```bash
/tmp/solana-install init --url http://api.beta.testnet.solana.com/
```
The default URL is http://api.testnet.solana.com/ so a regular user who just wants “the testnet” can just run `/tmp/solana-install init1st with no arguments

**Comment by mvines** [comment]
As of #3417, we now have a much nicer bootstrap process than described at https://github.com/solana-labs/solana/issues/3261#issuecomment-475116527

```bash
$ curl -sSf https://raw.githubusercontent.com/solana-labs/solana/v0.13.0/install/solana-install-init.sh | sh

**Comment by mvines** [comment]
The remaining work here is to add some plumbing to `net/` to run `solana-install deploy` as new versions of the stable testnet is deployed to release the matching binaries to downstream users. 

Flagging this as blocked for now as I'd like to do this work once 0.13 moves to beta and stabilizes first.

**Comment by mvines** [comment]
#3729 addresses the previous comment.   I'll keep this issue open for a while longer to:
1. Periodically remind myself to check that the `solana-install` deployment works against testnet-edge
2. Update https://github.com/solana-labs/solana/blob/master/book/src/testnet-participation.md to describe how to use `solana-install`
