### ISSUE TITLE
ci: common path orientation logic not sufficiently general

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#32634]
#### Problem
a lot of our scripts have logic like
```bash
cd "$(dirname "$0")/.."

source ci/_
source ci/...

# etc
```

this includes scripts that are intended to be `source`ed, where `$0` is the path of the script _calling_ `source`, not the `source`ed script itself

the problem occurs when a script is called from a path deeper than the level `ci/` lives at. when the script `cd`s to the source root, then `source`s another script, which attempts to canonicalize the calling script's basedir again, which is invalid since the `..` components have been stripped from `PWD`

repro:
```
$ cd runtime
$ ../ci/test-checks.sh
realpath: ../ci/..: No such file or directory
```

the failing `realpath` call is from ln8 of `ci/_`

#### Proposed Solution

avoid canonicalizing `$0` from scripts intended to be `source`ed throughout. may need some refactoring if we have some scripts with mixed `exec`/`source` usage

**Comment by t-nelson** [comment]
cc/ @yihau 

low priority!

**Comment by yihau** [comment]
what do you think about this changes:

folder view
```
.
└── ci
    ├── _.sh
    └── main.sh
```

main.sh
```diff
- cd "$(dirname "$0")/.."

- source ci/_
+ source "$(dirname ${BASH_SOURCE[0]})"/_
- source ci/...
+ source "$(dirname ${BASH_SOURCE[0]})"/...

# etc
```

I don't use `cd` cuz don't want it have a side effect to path. also I don't store it in a variable like `here="$(dirname ${BASH_SOURCE[0]})"` cuz when source other scripts, their `here` may rug ours

this one looks cumbersome but I think it is a safer solution.

**Comment by t-nelson** [comment]
with this proposal, every path would be specified relative to the current file? `BASH_SOURCE` seems to be a stack :thinking: 

> this one looks cumbersome 

yes. it _does_ work though

> cuz when source other scripts, their `here` may rug ours

i wish `local` could also handle execution unit scoping, not just in functions :face_with_head_bandage: 

i've been playing a bit and `declare -r here=...` isn't the worst (assuming `set -e`), but probably get's tedious with a lot of nested sourcing :thinking:

**Comment by yihau** [comment]
yeah. `BASH_SOURCE` seems to be a good var to solve this path issue 😈 

> i wish local could also handle execution unit scoping, not just in functions 🤕

true 😢 

> i've been playing a bit and declare -r here=... isn't the worst (assuming set -e), but probably get's tedious with a lot of nested sourcing 🤔

when we use readonly variable, a scenario is that:

folder view
```
example
├── f
│   └── runner.sh
├── common.sh
└── hello.sh
```

hello.sh
```
#!/usr/bin/env bash

hello() {
  echo "hello"
}
```

common.sh
```
#!/usr/bin/env bash

declare -r here="$(dirname ${BASH_SOURCE[0]})"

source "$here"/hello.sh
```

runner.sh
```
#!/usr/bin/env bash

declare -r here="$(dirname ${BASH_SOURCE[0]})"

source "$here"/../common.sh

hello
```

when we execute `runner.sh`, we can't find the `hello` function cuz we make `here` become a const. for this situation, we probably need to add a prefix to `here` variable. like `common_here` and `runner_here` ... but collision still can't avoid.

(btw, the above example works fine if we replace `"$here"` to `"$(dirname ${BASH_SOURCE[0]})"`)

**Comment by t-nelson** [comment]
> when we execute `runner.sh`, we can't find the `hello` function cuz we make `here` become a const.

isn't this because with no `set -e`, the second attempt to assign `here` fails, but excution continues, the path is wrong, so `source` fails, then we have no hello 'cause we've never seen it?

**Comment by yihau** [comment]
ah! nvm. I think I misunderstand what you mean 😢 I will prepare some PRs next week!
