### ISSUE TITLE
User defined tokens cannot be transferred and exchanged by other user defined programs

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#3266]
#### Problem

User defined tokens implemented with different programs cannot be exchanged by other user defined programs.

In a single program, it should be possible to change and update ownership of arbitrary units of tokens implemented by other programs.

Alice requests X amount of token implemented by program Token1, in exchange for Y amount of token implemented by program Token2.

Bob offers X + 1 amount of token implemented by program Token1, in exchange for Y - 1 amount of token implemented by Token2.

Dan pairs Bob and Alice, and the result ownership changes:

* Alice owns X of Token1,
* Bob owns Y - 1 of Token2,
* Dan owns 1 of Token1 and 1 of Token2,

Another example:

Alice offers X amount of Token1 to the winner of TicTacToe.

Bob offers Y amount of Token2 to the winner of the same game of TicTacToe.

The game charges a commission, the ceiling of the percentage of the tokens.  The
winner takes ownership of both tokens minus the commission.  The commission is
transferred to the address designated by the game.

It is not required that the transfer occurs at runtime.  The transfer of ownership can be executed by the new owner as a separate transaction.

#### Proposed Solution

#3216 

tag: @garious

**Comment by garious** [comment]
Without this capability, what's the workaround?

**Comment by aeyakovenko** [comment]
@garious, 

Tokens that implement some a transfer mechanism could be exchanged by a centralized custodian.  But each token would need to be supported separately.

**Comment by garious** [comment]
Gotcha, so the feature is support for an on-chain, permissionless token exchange. We can currently do either, but not both.

**Comment by aeyakovenko** [comment]
The idea here 
https://github.com/solana-labs/solana/pull/3216/files#diff-b7ebb48edb608710626522355699cb96R159

Is to allow for things like budget or TicTacToe or some custom m/n signature scheme to control transfer of units of external tokens.

**Comment by aeyakovenko** [comment]
Fixed with cross chain invoke and program addresses
