### ISSUE TITLE
Add versioning to Account struct

### ISSUE THREAD

**Issue by godmodegalactus** [solana-labs/solana#32665]
#### Problem
Currently, it is very hard to update the Account structure. The main argument is that this structure does not support versioning yet.  With the depreciation `rent_epoch` field in `Account`, it is an ideal time to add versioning to implement SIMD-16 and other future features like EIP-1559.

#### Proposed Solution
Currently, we have a lot of free space in the `Account` structure.

```Rust
#[repr(C)]
pub struct Account {
    /// lamports in the account
    pub lamports: u64,              // size = 8, align = 8, offset = 0
    /// data held in this account
    #[serde(with = "serde_bytes")]
    pub data: Vec<u8>,              // size = 24, align = 8, offset = 8
    /// the program that owns this account. If executable, the program that loads this account.
    pub owner: Pubkey,              // size = 32, align = 1, offset = 32
    /// this account's data contains a loaded program (and is now read-only)
    pub executable: bool,           // size = 1, align = 1, offset = 64
    /// the epoch at which this account will next owe rent
    pub rent_epoch: Epoch,          // size = 8, align = 8, offset = 72
}
```

So we have around 7 bytes free between executable and rent_epoch.

We could add a new field version:u8 in this field.

The issue is with storing this version information inside the accounts db. For starters, we will not add more space to the account structure in accountsdb. Rent epoch will be deprecated in 2 years' time.
The current epoch is 482, assuming that two days for two years means a maximum of 365 epochs < 900 epochs. So the maximum theoretical value of this field is 900, and in reality, we will not even get close because we no longer support accounts that are not rent-free. So we need only `u16` to store rent epoch instead of `u64`.

So we can use the 1-byte MSB of `rent_epoch` to store the version number in the accounts db.
We store U64::MAX for rent-free accounts in rent_epoch, so 1byte MSB is either 255 or 0 -> where 255 is for accounts that are rent free and 0 for accounts that have rent. So we can have the following algorithm :

| Version flag byte | Version |
|-------------------|---------|
| 0 / 255           | 0       |
| 1                 | 1       |
| 2                 | 2       |
| ...                 | ...       |

With this method, we can have 254 versions which would be sufficient as we expect this core structure to rarely change.

**Comment by apfitzge** [comment]
Might be misremembering, but isn't @yhchiang-sol looking at something very similar to this wrt the new storage format?

**Comment by yhchiang-sol** [comment]
> Might be misremembering, but isn't @yhchiang-sol looking at something very similar to this wrt the new storage format?

Yes, the on-going new storage format will include version and format information.  [Here](https://github.com/yhchiang-sol/solana/blob/master/runtime/src/tiered_storage/footer.rs#L90-L144)'s code snipe of its footer struct that includes format version and detailed format information of each block in one tiered storage file.

The new account meta format also includes optional fields, which also allows us to deprecate fields smoothly.

**Comment by godmodegalactus** [comment]
> > Might be misremembering, but isn't @yhchiang-sol looking at something very similar to this wrt the new storage format?
> 
> Yes, the on-going new storage format will include version and format information. [Here](https://github.com/yhchiang-sol/solana/blob/master/runtime/src/tiered_storage/footer.rs#L90-L144)'s code snipe of its footer struct that includes format version and detailed format information of each block in one tiered storage file.
> 
> The new account meta format also includes optional fields, which also allows us to deprecate fields smoothly.
 
 So accounts db will take care of accounts versioning with the new format ?
 This versioning then should be reflected back in Accounts structure.

**Comment by yhchiang-sol** [comment]
> So accounts db will take care of accounts versioning with the new format ?
This versioning then should be reflected back in Accounts structure.

That's also correct.  Let's include @Lichtso in the discussion as he is working on the new program runtime that also affects the executable field.

**Comment by Lichtso** [comment]
The `executable` is being deprecated with most of its use sites gone from transaction loading and program loading in v1.16 already. It is still passed into the VM and available to BPF programs but I think we can also substitute that by a calculated flag from the owner field instead. So it should be possible to completely remove it in v1.17, thus I would not include it in any new design for the accounts DB format. @pgarg66 Thoughts?

**Comment by pgarg66** [comment]
> The `executable`-flag is being deprecated with most of its use sites gone from transaction loading and program loading in v1.16 already. It is still passed into the VM and available to BPF programs but I think we can also substitute that by a calculated flag from the owner field instead. So it should be possible to completely remove it in v1.17, thus I would not include it in any new design for the accounts DB format. @pgarg66 Thoughts?

Yes, this makes sense to me. We can deduce `executable` flag by the program owner. It should be doable for v1.17.

**Comment by godmodegalactus** [comment]
Ok then we can add the version for account structure during this development ?

So that we can reuse the unused space in account structure for other features.

**Comment by godmodegalactus** [comment]
Hello @yhchiang-sol what is the timeline for the new format of accounts in accounts db.
