### ISSUE TITLE
[cli] Add a `solana-install list` command

### ISSUE THREAD

**Issue by metaproph3t** [solana-labs/solana#32688]
#### Problem

The `solana-install` tool can be used to easily switch between solana CLI versions. However, right now, unless there is a method I am unaware of, the only way to see your currently installed versions is to `ls ~/.local/share/solana/install/releases/`.

#### Proposed Solution

It would be nice to have a `solana-install list` command which lists one's installed versions

**Comment by jim4067** [comment]
this sounds awesome. let me try working on it.
