### ISSUE TITLE
Slots missing from long term storage

### ISSUE THREAD

**Issue by alecalve** [solana-labs/solana#32714]
#### Problem

Several slot ranges are missing from long term storage:

- [x] between 1_634_073 and 1_690_556. I'm not the first one to have noticed this one (see [here](https://solana.stackexchange.com/questions/1775/missing-slots-with-getblock?rq=1)).
- [x] between 15_984_013 and 15_984_074

#### Proposed Solution

Backfill the finalized blocks as was done to resolve https://github.com/solana-labs/solana/issues/21350 https://github.com/solana-labs/solana/issues/25068 https://github.com/solana-labs/solana/issues/25880

**Comment by steviez** [comment]
HI @alecalve - Thank you for bringing this to our attention. I'll take a look at this today

**Comment by steviez** [comment]
The `[15_984_013, 15_984_074]` range has been corrected; there is a slight hiccup with the other range that will require a little additional effort. Will post back when that one has been resolved.

**Comment by alecalve** [comment]
> The `[15_984_013, 15_984_074]` range has been corrected; there is a slight hiccup with the other range that will require a little investigation / effort to resolve. Will post back when that one has been resolved.

Any update on the remaining slot range?

**Comment by steviez** [comment]
Finally got around to getting a binary built with correct version, and I have finished uploading the second range `[1,634,073 and 1,690,556]`. I spot-checked the boundaries of this previously missing range as well as some miscellaneous slots in between and didn't see any remaining issues. So, closing as complete
