### ISSUE TITLE
cli: Relax stake split destination check

### ISSUE THREAD

**Issue by joncinque** [solana-labs/solana#32735]
#### Problem

In the CLI, `process_stake_split` checks that the destination stake account doesn't exist, and errors if it does. In most cases, this saves from getting an on-chain error from trying to split into some other account.

https://github.com/solana-labs/solana/blob/849525735f784f8e2e0fca19ba5699aea6b1724e/cli/src/stake.rs#L1884-L1893

However, it's possible to pre-seed some lamports into a system account before splitting into it, to keep the full amount delegated, so this check is needlessly strict.

#### Proposed Solution

Relax the check by allowing the destination split account to be owned by the system program, with some lamports, and no data. It can error in every other case still.

**Comment by fowlerlee** [comment]
@joncinque is this still open for work, i would like to do this issue.

**Comment by joncinque** [comment]
@fowlerlee #31897 has done most of the work for this, so feel free to ask about collaborating with the PR owner there!

**Comment by joncinque** [comment]
Closing in favor of https://github.com/anza-xyz/agave/issues/147
