### ISSUE TITLE
HashQueue fails age check for hashes that are equal to the max_age

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#3276]
#### Problem

If the MAX_RECENT_BLOCKHASHES evaluates to 0, then hash_queue will never let any txs through.

#### Proposed Solution

Allow any hash whose age is <= max_age

**Comment by pgarg66** [comment]
@sagar-solana

**Comment by mvines** [comment]
I'm curious why this is a problem?  Some unit test is upset?

**Comment by sagar-solana** [comment]
@mvines, yeah primarily. Shouldn't be a real world problem.

**Comment by mvines** [comment]
There should be no real world impact because `solana-genesis` always creates a ledger with slot 0 full of ticks

**Comment by sagar-solana** [comment]
@mvines, I think you'll see what I mean when I push a PR. Afk. The fix is in the hash_queue::check_entry_age. It doesn't handle a boundary condition of 0

**Comment by mvines** [comment]
sg.  That problem is just confusing to me -- "If the bank only contains genesis block, last_blockhash() does not return the hash of the genesis block.".   Frankly that's not a problem, it's just a fact.  So what's the problem ;)

**Comment by sagar-solana** [comment]
@mvines, Actually the issue description is incorrect. Haven't had the chance to update it since we triaged the failure. :)
