### ISSUE TITLE
leader could add information to allow for parallel entries

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#32764]
#### Problem

Entries are played serially today since the replayer has no information about if an Entry is independent to previous entries. If a replayer gets Entry 1 and 4 for instance, and entries 2 and 3 do not touch any accounts in Entry 4, then the replayer could play Entry 4 without getting 2 and 3.

#### Proposed Solution

An Entry could have a parent Entry included to indicate what the dependencies really are without have all the Entry's of the block. The block producer would add this information when constructing the block. Replayers would have to do a check to make sure the Entry's are truly independent after having all the data. If the entry's are not independent, the block should be marked invalid since nodes could have replayed them differently and gotten different results.

**Comment by sakridge** [comment]
cc @taozhu-chicago

**Comment by taozhu-chicago** [comment]
To get a sense how inter-dependent entries are within each block, I hacked ledger-tool ([draft PR](https://github.com/solana-labs/solana/pull/33006)) to exam recent mainnet-beta ledger. it simply does:
- get entries from blockstore for each slot,
- extract `AccountLocks` for each entry,
- check each non-tick entry if it has conflict with any of *earlier* entries, using much the same logic `accounts.lock_accounts()` uses.
- for each block, it calculates the percentage of entries have zero conflicts of total non-tick entries. This serves as an proxy of how parallelize non-confililct entries could improve perf.

Of 1_000 slots examined, the percentage of non-conflict entries per block is averaged at 30% (chart below). This says there are room to improve replay performance by parallelize those non-conflict entries. If I can figure out how to find timestamp of each entry's timestamp, then can further simulate for more realistic projection.

<img width="1122" alt="image" src="https://github.com/solana-labs/solana/assets/82401714/2a195e04-101b-451f-9bae-bbf8b8927c99">
