### ISSUE TITLE
web3.js: add searchTransactionHistory: true to getSignatureStatus in confirmTransaction

### ISSUE THREAD

**Issue by richardwu** [solana-labs/solana#32785]
#### Problem

getSignatureStatus was added to confirmTransaction in #28290 for signatures that confirm before the onSignatureResult message arrives.

The issue is for older signatures that are no longer in the signatures cache, this will still hang because getSignatureStatus will not see the sig.

#### Proposed Solution

Add `searchTransactionHistory: true` (or expose it in confirmTransaciton) to the getSignatureStatus call.

**Comment by steveluscher** [comment]
@linuskendall, @brianlong: if web3.js added `searchTransactionHistory` to all `getSignaturesStatuses` calls made by the transaction confirmer, would your RPC explode, or would this be a non-event?

**Comment by CriesofCarrots** [comment]
No longer in this repository
