### ISSUE TITLE
[docs] Certain links in docs.solana.com do not link to the proper version published by the crate

### ISSUE THREAD

**Issue by jnwng** [solana-labs/solana#32790]
#### Problem
1. Broken link from [docs.solana.com](https://docs.solana.com/developing/runtime-facilities/programs) leading to [docs.rs page](https://docs.rs/solana-program/1.16.7/solana_program/system_instruction/enum.SystemInstruction.html) where the docs page complains about "requested version does not exist"
    - Why? docs.rs is not picking up the newest version of the `solana-program` crate
    - ![image](https://github.com/solana-labs/solana/assets/1118534/f5ad4bb4-e714-4ecc-b2c3-7f78a175f0ef)
    - ![image](https://github.com/solana-labs/solana/assets/1118534/9b82f9cb-7f8f-4434-b437-a0492b7a0744)

#### Proposed Solution
Figure out why docs.rs is not picking up the docs published in the latest version of the `solana-program` crate

**Comment by nickfrosty** [comment]
Closing since this was fixed per https://github.com/rust-lang/docs.rs/issues/2189
