### ISSUE TITLE
QUIC TPU Client ignores the QUIC errors

### ISSUE THREAD

**Issue by godmodegalactus** [solana-labs/solana#32792]
#### Problem

TPU Client returns true even if sending over the QUIC connection fails.

The `send_data` function in TPU client file `nonblocking/quic_client.rs` ignores the error raised by the method `send_buffer`. It just updates the stats and returns `Ok(())`, it should instead return a correct error.

#### Proposed Solution

Raise the error and handle it correctly in other methods. For example send transaction will return error only if all the sending data over all the connections fails.

**Comment by KirillLykov** [comment]
https://github.com/solana-labs/solana/blob/master/quic-client/src/nonblocking/quic_client.rs#L571
