### ISSUE TITLE
account_hash_ignore_slot behaves incorrectly at genesis

### ISSUE THREAD

**Issue by ripatel-fd** [solana-labs/solana#32800]
#### Problem

Feature `account_hash_ignore_slot` removes the slot field from the BLAKE3 accounts hash.
On Solana Labs v1.17 test ledgers, this feature is activated by default (meaning there is a genesis account for the sysvar).

At slot 0, the bank's accounts delta hash is constructed from the hashes of all genesis accounts. 

But even though this feature is active _at the genesis slot_, it uses the old method (before feature activation) to compute the genesis account hashes.

#### Proposed Solution

- Make sure features are activated before computing the account hash. 
- Extend unit tests to cover genesis too.

**Comment by jeffwashington** [comment]
fyi #33692
@t-nelson , @ripatel-fd 
I can manage this pr once we figure out it is right.
