### ISSUE TITLE
Feature Gate: Timely vote credits 

### ISSUE THREAD

**Issue by AshwinSekar** [solana-labs/solana#32857]
### Description

This will change the vote credit mechanism https://github.com/solana-foundation/solana-improvement-documents/blob/main/proposals/0033-timely-vote-credits.md, which will break consensus unless feature gated.

Additionally this will require community vote to approve. 

### Feature ID

~2oXpeh141pPZCTCFHBsvCwG2BtaHZZAtrVhwaxSy6brS~
tvcF6b1TRz353zKuhBjinZkKzjmihXmBAHJdjNYw1sQ

### Activation Method

Staked Validator Vote

### Deployment Considerations

Monitor vote credits upon activation. 

### Minimum Version

1.18.8

### Testnet Activation Epoch

675

### Devnet Activation Epoch

735

### Mainnet-Beta Activation Epoch

703

**Comment by buffalu** [comment]
PLEASE LET ME KNOW BEFORE THIS SHIPS!!!!!!11!!1

This will break the currently deployed (as of October 5, 2023) version of the Jito Tip Distribution Program, which prevents Jito-Solana validators from operating correctly (not fatal to network, just a severe annoyance).

luckily my rebase just caught this as of commit 6f1922b4fd04092dd2b0c802a87b1c778c8f3de4 in solana repo as we test tip distribution program functionality during CI

there are other jito programs that will likely be live that parse vote accounts on-chain as well that this will break, but those are less severe than this.

**Comment by AshwinSekar** [comment]
definitely will do, i believe the feature you want to track is this one:
https://github.com/solana-labs/solana/issues/31264

When turned on this will migrate old `VoteState` into the new format.
