### ISSUE TITLE
rpc: getSignaturesForAddress returns some weird results

### ISSUE THREAD

**Issue by yihau** [solana-labs/solana#32865]
### Context 
<details><summary>from this query we can get a list</summary>

```bash
curl https://api.mainnet-beta.solana.com -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getSignaturesForAddress",
    "params": [
      "6HW8dXjtiTGkD4jzXs7igdFmZExPpmwUrRN5195xGup",
      {
          "before": "3JUQff8XqVv3FyPDfLcrHdgcbiYJrCnBPTPLw7znPdEqsPfUc85jn8iGPEx2J7UVbMdiWr6XgvdGLj3hE5YXe6fq",
          "limit": 5
      }
    ]
  }
' | jq '.result[] | .signature'
```

</details> 

```
"HP6Y64q6vWv13syWeLgaywtzh1wiX6a1ud4qzU6jEN6dn7iHFj8aQ7irEdjBX4A2vgznmTctXvpXhnCgBU8ERQN"
"WkyhYXwiu2yD1VmxUuKhEzbYAGzhLwPFUEXYjhvB7GD259GwHwkvbsk9ZvjudYAPkFWxD4sdEBFyynp1X6dZz1Z"
"3T328x4H2Rbp2FWnuBc4yQjHcmRTwyHhqyagMEB3BF9MsJRVGPWWCL8jETzsuLX8VyTW6evrhwPgrKrxjz8sEuui"
"3Rivhuvy3haGdpYe6569jRK9vcfc31vGoQpYJif5gnX3GKU7zpq2fF9VGTDFmDb2yJhGFT7fmA3jifmEESEzXN9k"
"4kS6ZLLtPKbHwWZ6hZ3pSXJq64B7avCRJXsAoMKeAwfUrS4pK7ahdf8LjMB1VysNT4JUz7ipdUVfcM8Zo9b8X4hm"
```

### Case 1

<details><summary>query</summary>

```bash
curl https://api.mainnet-beta.solana.com -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getSignaturesForAddress",
    "params": [
      "6HW8dXjtiTGkD4jzXs7igdFmZExPpmwUrRN5195xGup",
      {
          "before": "HP6Y64q6vWv13syWeLgaywtzh1wiX6a1ud4qzU6jEN6dn7iHFj8aQ7irEdjBX4A2vgznmTctXvpXhnCgBU8ERQN",
          "until": "WkyhYXwiu2yD1VmxUuKhEzbYAGzhLwPFUEXYjhvB7GD259GwHwkvbsk9ZvjudYAPkFWxD4sdEBFyynp1X6dZz1Z"
      }
    ]
  }
'
```

</details> 

When we query with
- before `HP6Y64q6vWv13syWeLgaywtzh1wiX6a1ud4qzU6jEN6dn7iHFj8aQ7irEdjBX4A2vgznmTctXvpXhnCgBU8ERQN`
- until `WkyhYXwiu2yD1VmxUuKhEzbYAGzhLwPFUEXYjhvB7GD259GwHwkvbsk9ZvjudYAPkFWxD4sdEBFyynp1X6dZz1Z`

as expectaton, It returns an empty result. 

### Case 2

<details><summary>query</summary>

```bash
curl https://api.mainnet-beta.solana.com -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getSignaturesForAddress",
    "params": [
      "6HW8dXjtiTGkD4jzXs7igdFmZExPpmwUrRN5195xGup",
      {
          "before": "WkyhYXwiu2yD1VmxUuKhEzbYAGzhLwPFUEXYjhvB7GD259GwHwkvbsk9ZvjudYAPkFWxD4sdEBFyynp1X6dZz1Z",
          "until": "3T328x4H2Rbp2FWnuBc4yQjHcmRTwyHhqyagMEB3BF9MsJRVGPWWCL8jETzsuLX8VyTW6evrhwPgrKrxjz8sEuui"
      }
    ]
  }
'
```

</details> 

However when we query with
- before `WkyhYXwiu2yD1VmxUuKhEzbYAGzhLwPFUEXYjhvB7GD259GwHwkvbsk9ZvjudYAPkFWxD4sdEBFyynp1X6dZz1Z`
- until `3T328x4H2Rbp2FWnuBc4yQjHcmRTwyHhqyagMEB3BF9MsJRVGPWWCL8jETzsuLX8VyTW6evrhwPgrKrxjz8sEuui`

I suppose it should return me an empty result but I got `3Rivhuvy3haGdpYe6569jRK9vcfc31vGoQpYJif5gnX3GKU7zpq2fF9VGTDFmDb2yJhGFT7fmA3jifmEESEzXN9k`.

### Case 3

<details><summary>query</summary>

```bash
curl https://api.mainnet-beta.solana.com -X POST -H "Content-Type: application/json" -d '
  {
    "jsonrpc": "2.0",
    "id": 1,
    "method": "getSignaturesForAddress",
    "params": [
      "6HW8dXjtiTGkD4jzXs7igdFmZExPpmwUrRN5195xGup",
      {
          "before": "3Rivhuvy3haGdpYe6569jRK9vcfc31vGoQpYJif5gnX3GKU7zpq2fF9VGTDFmDb2yJhGFT7fmA3jifmEESEzXN9k",
          "until": "4kS6ZLLtPKbHwWZ6hZ3pSXJq64B7avCRJXsAoMKeAwfUrS4pK7ahdf8LjMB1VysNT4JUz7ipdUVfcM8Zo9b8X4hm"
      }
    ]
  }
'
```

</details> 

However when we query with
- before `3Rivhuvy3haGdpYe6569jRK9vcfc31vGoQpYJif5gnX3GKU7zpq2fF9VGTDFmDb2yJhGFT7fmA3jifmEESEzXN9k `
- until `4kS6ZLLtPKbHwWZ6hZ3pSXJq64B7avCRJXsAoMKeAwfUrS4pK7ahdf8LjMB1VysNT4JUz7ipdUVfcM8Zo9b8X4hm`

I suppose it should return me an empty result but I got `3T328x4H2Rbp2FWnuBc4yQjHcmRTwyHhqyagMEB3BF9MsJRVGPWWCL8jETzsuLX8VyTW6evrhwPgrKrxjz8sEuui`.

It seems that something affect the order between `3T328x4...` and `3Rivhuv...`

**Comment by wei1769** [comment]
Having this issue as well using quicknode mainnet rpc.

**Comment by yihau** [comment]
yeah. I think should be the same issue. let's discuss there
