### ISSUE TITLE
solana-client v.1.16 depends on pinned tokio version (~1.14.1) compared to solana-client v.1.14 (tokio ^1)

### ISSUE THREAD

**Issue by andreisilviudragnea** [solana-labs/solana#32878]
#### Problem

- [solana-client v1.16.8](https://crates.io/crates/solana-client/1.16.8/dependencies) depends on [tokio ~1.14.1](https://crates.io/crates/tokio/1.14.1) - it allows updating tokio only to `1.14.x` versions
- [solana-client v.14.24](https://crates.io/crates/solana-client/1.14.24/dependencies) depends on [tokio ^1](https://crates.io/crates/tokio/1.32.0) - it allows updating tokio to `1.x.x` versions

Using [solana-client v1.16.8](https://crates.io/crates/solana-client/1.16.8/dependencies) forces the clients of this crate to downgrade `tokio` to a version more than a year old. This problem has been introduced by #29893, when the `tokio` version specified for `solana-client` changed from `^1` to `~1.14.1`.

Fixed by #33058.

**Comment by buffalu** [comment]
YES PLZ

**Comment by mvines** [comment]
`solana-storage-bigtable` is another v1.16 crate that could use this same treatment

**Comment by andreisilviudragnea** [comment]
It should be fixed by #33058.
