### ISSUE TITLE
solana-cli v1.14.23 and v1.14.24 missing from crates.io

### ISSUE THREAD

**Issue by andreisilviudragnea** [solana-labs/solana#32931]
#### Problem

Why are `solana-cli` v1.14.23 and v1.14.24 missing from crates.io?

#### Proposed Solution
Upload the missing releases.

@solana-grimes

**Comment by yihau** [comment]
thank you for the reporting! we noticed this issue and finally I had some time to fix it. just uploaded them!

**Comment by andreisilviudragnea** [comment]
Thank you for the fix.
