### ISSUE TITLE
Timing constants can conflict with GenesisBlock configuration

### ISSUE THREAD

**Issue by sagar-solana** [solana-labs/solana#3293]
#### Problem

In `timing.rs` the following constants may conflict with the genesis_block configuration.
```
pub const DEFAULT_TICKS_PER_SLOT: u64 = 160;
pub const DEFAULT_SLOTS_PER_EPOCH: u64 = 16;
```
We have derived constants that are based on the above two, like `MAX_RECENT_BLOCKHASHES` but if the genesis_block uses non-default values for any of the above then `MAX_RECENT_BLOCKHASHES` will be incorrect.

There are other usages of these constants that may or may not be correct based on how genesis is configured

#### Proposed Solution

Find an alternative to these constants and/or derive them from genesis. Maybe move them out of ~genesis~ sdk.

Tag: @rob-solana

**Comment by garious** [comment]
I put those constants there. Probably the wrong choice. I did it to break up module dependencies and not to make that an alternative to using the values in the genesis block.  How about moving non-pub versions of those constants into genesis? Force everything else to derive it from genesis?

**Comment by rob-solana** [comment]
kill them with fire
