### ISSUE TITLE
v1.16.9 = 300% excessive disk usage on MB

### ISSUE THREAD

**Issue by iammelea** [solana-labs/solana#33053]
#### Problem

![Screenshot from 2023-08-29 12-23-31](https://github.com/solana-labs/solana/assets/38863192/4e0f6934-2fe2-42fb-8333-c243f93f0711)

![Screenshot from 2023-08-29 12-24-14](https://github.com/solana-labs/solana/assets/38863192/bd740d49-f721-4667-a3ba-79f73a55717a)

#### Proposed Solution

halt the MB upgrade to v1.16.9 meanwhile disk I/O is too much high

**Comment by anvme** [comment]
+ 1.16.10

**Comment by iammelea** [comment]
Close meanwhile te team is working on the issue.
