### ISSUE TITLE
solana-cli v1.16.11 missing from crates.io

### ISSUE THREAD

**Issue by andreisilviudragnea** [solana-labs/solana#33084]
#### Problem

`solana-cli` v1.16.11 is missing from crates.io: https://crates.io/crates/solana-cli/versions

#### Proposed Solution
Upload the missing release.

@yihau

**Comment by yihau** [comment]
Thank you for the report. The crate has been uploaded. Actually, we have many crates that need to be uploaded, so it takes time. You can expect that it takes at least 2h to get ready.
