### ISSUE TITLE
vote cost

### ISSUE THREAD

**Issue by taozhu-chicago** [solana-labs/solana#33269]
#### Problem
Be good to know how the vote cost in mainnet-beta look like, 
- the percentage of 2 sig vs 1 sig
- the min/max/median of tx data size
- the min/max/median of account sizes

**Comment by taozhu-chicago** [comment]
replaying mainnet-beta ledger, looks like vote transactions load static amount of accounts: 
- first signer account (node account): 0 bytes
- vote account: 3731 bytes
- `SysvarC1ock111...`, 40 bytes
- `SysvarS1otHashes111...`, 20488 bytes
- `Vote111...`, 19 bytes.
So that total to 24_278 bytes.

Didn't see any 1 signature votes. 

It gives me confidence to set a static CU for vote transactions: `2 * signatures + 2 * write locks + 1 vote builtin ix + 24_278 bytes cost = 4140`. 

Hopefully I didn't miss anything, wdyt @t-nelson @AshwinSekar @apfitzge

**Comment by 7layermagik** [comment]
Hmm I think that is probably wrong actually -- most votes just pay 0.000005 sol and have one signer as far as I know.  Having two signers for all those votes is a pretty huge cost. Here's an example transaction from us: https://explorer.solana.com/tx/5UCfUbvNmU2KMSZzoptEg64n9BAb6mTNcZ7YrohQg3zP2vG2tDKwzTYA4n7kyCY6yXN8SMv7GaCSCLkt434AW8EX

**Comment by taozhu-chicago** [comment]
thanks for pointing out, I'll rerun with larger data set.

**Comment by taozhu-chicago** [comment]
Ah, my script mis-labeled write-locks to "signatures". updated [comment](https://github.com/solana-labs/solana/issues/33269#issuecomment-1721709351).

**Comment by t-nelson** [comment]
this is just the cost of votes that fit `is_simple_vote()`, right?

**Comment by taozhu-chicago** [comment]
> this is just the cost of votes that fit `is_simple_vote()`, right?

correct. 

Are there other vote transactions allowed other than "simple-vote"? Does it not drop/ignore vote if it comes with part of normal transaction (eg a normal transaction includes a vote instruction)?

**Comment by t-nelson** [comment]
shouldn't be dropped, no. but won't be prioritized as a vote, just treated as normal transaction
