### ISSUE TITLE
Write tests and get KvStore to at least 90% line coverage

### ISSUE THREAD

**Issue by MarkJr94** [solana-labs/solana#3333]
#### Problem
Code is not currently well tested

#### Proposed Solution
Implement more tests, possibly use this as a tracking issue

Whenever a bug in KvStore is fixed, attempt to add a test that will fail if it's reintroduced

**Comment by mvines** [comment]
We could also drive this by code coverage.   Goal: get to at least 90% line coverage using our existing code coverage tooling.

**Comment by MarkJr94** [comment]
Sounds good.
