### ISSUE TITLE
Why don't charge transaction fee like eth?

### ISSUE THREAD

**Issue by lurais** [solana-labs/solana#33391]
#### Problem
As I know, eth will charge transaction fee just according to the resources it used, and solana just charge fee accroding to the  number of signatures, so  why don't charge just like eth? Is it really fair and reasonable to charge according to the number of signatures?
#### Proposed Solution
not now

**Comment by lurais** [comment]
@mvines

**Comment by CriesofCarrots** [comment]
Hi, we use issues in this repository to track bugs in the code contained here. General blockchain economics discussions belong elsewhere.
You can follow various proposed protocol changes here: https://github.com/solana-foundation/solana-improvement-documents

Also, it's rude to tag someone out of the blue.
