### ISSUE TITLE
Deduper Performance

### ISSUE THREAD

**Issue by apfitzge** [solana-labs/solana#33406]
#### Problem

- BankingStage is seeing a large percentage of duplicate packets - 45% on the MNB node I had banking-trace data for
- Most duplicate packets are arriving within a reasonable amount of time of the original packet
- `Deduper` should be doing a better job, failing to do so wastes resources in:
	- SigVerify
	- BankingStage

#### Proposed Solution

- Change `MAX_DEDUPER_AGE` to a more appropriate number so more packets are caught by `Deduper`
  	- Should this be configurable? CLI or ENV?
- Ensure that under load a longer `MAX_DEDUPER_AGE` does not lead to too many saturations

**Comment by apfitzge** [comment]
Did some exploration to see what a more appropriate value for `MAX_DEDUPER_AGE` might be.
Most of the duplicate packets we see are caused by forwarding.

Setup and assumptions:

- We have 4 slot leader allocations, and slots are exactly 0.4s. Thus a leader has 1.6s allocated
- We have a `Dedup` period of `L` seconds. Assume `L > 1.6s`.
- Our leader allocation begins at a random uniformly distributed time, `T`, within the `Dedup` period

{{< mermaid >}}
gantt
    title Dedup - Slots
    dateFormat s.SSS
    axisFormat %
    tickInterval %

    section Leader
      Dedup           :s0, 0.000, 2.0s
      Slots           :s0, 0.800, 1.6s
{{< /mermaid >}}

If an RPC sent to both us and the previous leader, then we want the previous leader's allocation within the same `Dedup` window as when they will forward to us.
The probability that the beginning of the previous leader's allocation is also within this `Dedup` window is `1 - 1.6/L`.

| Dedup Period | Probability |
| ------------ | ----------- |
| 2s           | 0.200       |
| 3s           | 0.467       |
| 4s           | 0.600       |
| 5s           | 0.700       |

A more generic look, if we want some fraction, `x`, of the previous leader's allocation to be within the `Dedup` window, the probability will be: `1 - 1.6x/L`.
If we take some transaction, sent to the previous leader, and assume it is randomly and uniformly distributed within their allocation, the probability that it will also be within our dedup window is equivalent to the average of `1 - 1.6x/L` for x in range [0, 1].
This results in: `1 - 0.8/L`:

| Dedup Period | Probability |
| ------------ | ----------- |
| 2s           | 0.600       |
| 3s           | 0.733       |
| 4s           | 0.800       |
| 5s           | 0.840       |

**Comment by KirillLykov** [comment]
Looks like this issue is still relevant
