### ISSUE TITLE
`cargo build-bpf` doesnt seem to apply the patch

### ISSUE THREAD

**Issue by dhruvja** [solana-labs/solana#33411]
#### Problem
I wanted to use solana-program with an updated curve25519-dalek package ( bumped from 3.2.1 to 4.1.1). So i forked the solana-program (v1.16.3) and updated the package and fixed issues caused due to upgrade. But when i am using the forked version of solana-program as patch, i get the below error.

```
error: failed to resolve patches for `https://github.com/rust-lang/crates.io-index`

Caused by:
  patch for `solana-program` in `https://github.com/rust-lang/crates.io-index` failed to resolve

Caused by:
  The patch location `https://github.com/dhruvja/solana?branch=main` does not appear to contain any packages matching the name `solana-program`.
```
The program compiles when i run with `cargo build` but fails when i run with `cargo build-bpf`.

Doesnt the `cargo build-bpf` crawl the git repo to find crates which match the name specified. What do u think i am missing?

**Comment by dmakarov** [comment]
cargo build-bpf simply runs `cargo +solana build` where `solana` is the Solana platform-tools toolchain linked to rustup toolchains (see `rustup toolchain link --help` for help on custom toolchain linking). It doesn't do any .toml file processing or anything more than running a _normal_ cargo with additional command-line options that specify which toolchain to use to compile the package. you can add RUST_LOG=info environment variable setting when running `cargo build-bpf` to see what it does.

**Comment by dhruvja** [comment]
> cargo build-bpf simply runs `cargo +solana build` where `solana` is the Solana platform-tools toolchain linked to rustup toolchains (see `rustup toolchain link --help` for help on custom toolchain linking). It doesn't do any .toml file processing or anything more than running a _normal_ cargo with additional command-line options that specify which toolchain to use to compile the package. you can add RUST_LOG=info environment variable setting when running `cargo build-bpf` to see what it does.

I am getting this info, though it doesnt say why it is not able to resolve it.
```
[2023-09-26T14:54:36.895360000Z INFO  cargo_build_sbf] SBF SDK: /Users/dhruvjain/.local/share/solana/install/releases/1.14.18/solana-release/bin/sdk/bpf
[2023-09-26T14:54:36.896270000Z INFO  cargo_build_sbf] cargo-build-sbf child: rustup toolchain list -v
[2023-09-26T14:54:36.921638000Z INFO  cargo_build_sbf] cargo-build-sbf child: cargo +bpf build --release --target bpfel-unknown-unknown

```

**Comment by dmakarov** [comment]
The log messages confirm what I explained earlier. `cargo build-bpf` doesn't resolve dependencies on its own, but runs `cargo +bpf build ...` (we renamed bpf toolchain to solana some time ago).  Why `cargo` fails to resolve patches in your case, I don't know.

**Comment by dhruvja** [comment]
The issue was with the `platform-tools` version which i was using an older one ( 1.14 ) instead of 1.16. It worked when i updated my platform tools. Closing it now.
