### ISSUE TITLE
[BUG] Box Size Unresponsiveness causing overflow of text

### ISSUE THREAD

**Issue by IAlgorithmia** [solana-labs/solana#33449]
#### Problem

The text was written under Case Study Hivemapper overflows out of the box when the screen width is reduced. 

#### How to find the problem

1. Go to the official [Solana Home Page](https://solana.com/)
2. Scroll down to the Case Studies Section
3. Open inspect feature of the browser and reduce the width of the webpage
4. The text overflows out of the designated box
![image](https://github.com/solana-labs/solana/assets/40685465/7572a442-25fc-4e59-ab52-799547f7ced3)

#### Proposed Solution

Modify the height of each box, either increase them all (preferred), or make changes in the mentioned box only

**Comment by CriesofCarrots** [comment]
This repository doesn't house the code for solana.com or track issues for that website.

Unfortunately, I don't have a better avenue to suggest; it appears the solana.com web team doesn't have any system in place to accept public bug reports. Sorry about that.
