### ISSUE TITLE
Hash leaves in parallel when constructing the Merkle Tree

### ISSUE THREAD

**Issue by anoushk1234** [solana-labs/solana#33486]
#### Problem
When constructing a Merkle Tree using the [solana-merkle-tree](https://github.com/solana-labs/solana/blob/master/merkle-tree/src/merkle_tree.rs) the data is hashed and pushed to the vector sequentially. This is not great for performance and can be a problem with large blocks.
 
#### Proposed Solution
The solution would be to use fork-join parallelism using a parallel iterator from something like Rayon.
Here's the code snippet, we use this:
```rust
let mut hashed_nodes: Vec<Hash> = items
            .par_iter()
            .map(|leaf| {
                let item = leaf.as_ref();
                hash_leaf!(item)
            })
            .collect();
            
```
Instead of what is currently used:
```rust
    for item in items {
            let item = item.as_ref();
            let hash = hash_leaf!(item);
            mt.nodes.push(hash);
        }
```

Here's a benchmark of how much faster it actually is, I'm using 1 million, 500k and 5k random signatures respectively as data for the leaves.
![image](https://github.com/solana-labs/solana/assets/32778608/a462606a-defe-401d-a7c2-10d40d4ce2d4)
![image](https://github.com/solana-labs/solana/assets/32778608/6ccaf6da-c515-410e-9908-b44ded69cf77)
![image](https://github.com/solana-labs/solana/assets/32778608/1821999e-b636-41b3-be33-254509ca842e)

As we can see here we're saving about 87ms for 1 million leaves which is quite significant relative to our 400ms slot times and about half as much time for the other two.

Here's a [repository](https://github.com/anoushk1234/solana-optimised-merkle) that you can cargo bench with the change.

**Comment by behzadnouri** [comment]
These isolated benchmarks rarely capture an actual validator runtime.
A better benchmark is that a mainnet validator with and without this change shows any significant improvement in any of the core metrics.
