### ISSUE TITLE
[zk-token-sdk] Potential overflow due to unchecked shift operation in range proof calculation (ottersec #4)

### ISSUE THREAD

**Issue by samkim-crypto** [solana-labs/solana#33507]
#### Problem

The logic for creating range proofs uses unchecked shift operation `>>` to calculate bit-lengths for Pedersen commitment inputs, which can panic.

Note: This is client side logic and does not impact on-chain programs.

#### Proposed Solution
Add length checks on the shift operations.

**Comment by joncinque** [comment]
Fixed with #34065
