### ISSUE TITLE
[zk-token-sdk] Range proof scalar inner product panics if input lengths are different (ottersec #8)

### ISSUE THREAD

**Issue by samkim-crypto** [solana-labs/solana#33510]
#### Problem

The inner product helper function when computing range proofs panics with a custom message if the input lengths of two input vectors are different.

This function is never really called on differing length inputs during range proof generation, but it would be better to error more gracefully since this is a public function.

#### Proposed Solution
Update the range proof helper function to return a custom error type when the input vectors have differing lengths.

**Comment by joncinque** [comment]
Fixed with #34065
