### ISSUE TITLE
[zk-token-sdk] Potential for a malicious prover to generate proofs over `MAX_COMMITEMNTS` (ottersec #7)

### ISSUE THREAD

**Issue by samkim-crypto** [solana-labs/solana#33525]
#### Problem

In Batched range proofs u64/u128/u256 the `MaxCommitments` are checked using if statement while creating a proof but not included in proof, which leads dishonest prover to prove a crafted proof which has over or greater than  `MaxCommitments` by a verifier. The verifier needs to ensure the length of `bit_lengths` is less than `MaxCommitments`.

#### Proposed Solution
Add a check to verify `bit_lengths` in range proof verification.

**Comment by joncinque** [comment]
Fixed with https://github.com/solana-labs/solana/pull/34165
