### ISSUE TITLE
[zk-token-sdk] The fee sigma proof allows transfer fee can be greater than the transfer amount (ottersec #1 & #2)

### ISSUE THREAD

**Issue by samkim-crypto** [solana-labs/solana#33526]
#### Problem

The fee sigma proof in combination with range proof allows transfer fees to be greater than the transfer amount in some edge cases.

This stems from:
- Off-by-1 error in the way `delta_fee` is computed in fee sigma proof
- Absence of a mechanism in range proof to certify that the transfer fee is less than the transfer amount

#### Proposed Solution
- Add the condition that `transfer_amount - transfer_fee` is a positive number in the way range proof is computed
- Update the range proof logic so that the condition `0 <= delta_fee < 10_000` is checked instead of the condition `0 <= delta_fee <= 10_000`.

**Comment by joncinque** [comment]
Fixed with https://github.com/solana-labs/solana/pull/34314
