### ISSUE TITLE
The issue of solana restarting data loss

### ISSUE THREAD

**Issue by zhy827827** [solana-labs/solana#33619]
Baremetal
System Ubuntu 20.04
CPU AMD EPYC 7413
RAM 256 GB
Disk 12T

When Solana restarts, it redownloads the snapshot. causing the data block to lose. For example synchronize to block height 203000000 before restarting. After rebooting download snapshot, the block height starts from 203002000, which results in 20300000-203002000 blocks lost, how to solve this issues?
I set --limit-ledger-size=70000000, the theory is to retain 3 days+data

**Comment by CriesofCarrots** [comment]
Pass `--no-snapshot-fetch` in the command line to start from the node's local snapshot instead of downloading a new one.
