### ISSUE TITLE
Geyser plugins do not have any tests, integration or benchmark

### ISSUE THREAD

**Issue by godmodegalactus** [solana-labs/solana#33672]
#### Problem
Currently, we want to implement and integrate a few PR to change the geyser interface, which is primordial to implement the new RPC-v2 interface. We plan to stream all the data out over the geyser for the new RPC implementation.

But any changes to the geyser interface is difficult to merge because there is not enough testing on this part.
We want to ensure that any changes to this interface do not break Solana validator, existing infrastructure or degrade the performance.

#### Proposed Solution

* Create a vanilla Geyser Plugin which can stream out data over QUIC or UDP.
* Test the plugins impact on the validator.
* Write unit-tests that the plugin always work as intended.
* Implement benchmarking infrastructure to test that plugins performance is not degraded because of commits.

**Comment by KirillLykov** [comment]
I think there are two things regarding regression tests for geyser.
1. verify that whatever changes in the geyser do not affect the throughput of geyser.
2. verify that whatever changes in the geyser do not affect the QoS of the network of validators.

For this, we need to have minimum overhead plugin. This will be also useful to measure the overhead of real plugin that is going to be used.

Another dimension on this is timeline. As far as I understand these PRs need to be merged and, hence, tested in the next month or so. For that some intermediate testing solution might be sufficient. Like develop this vanilla plugin and measure the throughput before/after changes on testnet to address (1). For (2), probably need to simulate conditions when throughput of this plugin is at max and meanwhile check that the key validator metrics are as expected (best effort approach for now).

**Comment by godmodegalactus** [comment]
Some PRs that i would like to be merge eventually.

**Comment by godmodegalactus** [comment]
https://github.com/solana-labs/solana/pull/33401

**Comment by godmodegalactus** [comment]
https://github.com/solana-labs/solana/pull/33292
