### ISSUE TITLE
systune recommendations can create vote-only validators in some configurations

### ISSUE THREAD

**Issue by bji** [solana-labs/solana#33789]
#### Problem

There are a few dozen Solana mainnet-beta validators who emit vote-only blocks.  Some debugging by validator operators has determined that some of the systune recommendations are the cause.  When those operators removed some of the systune settings, their validators stopped emitting vote-only blocks and started emitting blocks with user tx in them.

In addition, some of the systune recommendations are contrary to what was in the Solana validator docs; and those settings from the docs have been proven to be sufficient for thousands of validators.  This means that the additional settings recommended in the code are unnecessary and possibly harmful.

The specific recommended settings which are unnecessary and harmful are:

net.core.optmem_max=0
net.core.netdev_max_backlog=0

#### Proposed Solution

Remove those recommendations from the code base.

**Comment by R-K-H** [comment]
Can confirm with our own testing. From our ansible build:

  # NOTE: EVEN THOUGH SOLANA RECOMMANDS 0 FOR THESE, DO NOT USE IT!!!
  # RESULTS IN THE RPC REQUESTS HANGING IF VALUES OF 0 ARE USED
  net.core.optmem_max: 20480
  net.core.netdev_max_backlog: 8192

**Comment by t-nelson** [comment]
forgot we had an issue for this.  closed by #34149
