### ISSUE TITLE
Accounts with data in them can be drained by the holder of the account keypair

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#3380]
A (non-system) account with non-zero data typically can be thought of as the custodian of the lamports assigned to that account and/or representing ownership of some item or token.  As such the account should only be deleted by the account owner.

However all such accounts originate from a keypair generated by some off-chain entity.  That entity should in almost all cases *forget* that keypair.    But if they don't (intentionally or maliciously), then that keypair could be used to drain all lamports from the account by using the account to pay the transaction fee for arbitrary transactions.

Therefore it seems wise to limit the accounts that may pay transaction fees to accounts with zero data.

**Comment by rob-solana** [comment]
fixing this would require fixing all the current programs to issue from a system account?

**Comment by mvines** [comment]
I'm having a bit of trouble parsing "issue from" in ^.   But regardless I don't think all current programs would need to change, it's not too common to fund a Transaction from an account with data in it (tic-tac-toe being an exception)

**Comment by rob-solana** [comment]
by "issue from", I mean that every instruction would need a "this instruction is from" as in "this guy is issuing this instruction", i.e. paying the fee, and "that guy" would always have to be a system account.

vote_program doesn't honor this form...  most instructions are from the vote_account itself, which I guess is weird.

if we can change your "typically" above to a hard rule enforced by the runtime, I think we might be better-off long-term.

**Comment by mvines** [comment]
I was thinking we’d also want to support “that guy” being a non-system account with a zero data length as well.  This allows a program to share lamports with the user in a way that only permits the user to use those lamports only for transaction fees, little jet lagged so brain isn’t working fully yet, but I think there’s a bit of additional utility there that is worth retaining.

**Comment by mvines** [comment]
(bouncing to v0.14, not critical to fix in v0.13)

**Comment by mvines** [comment]
Blocked by #4173

**Comment by rob-solana** [comment]
is #4173 the only blocker as far as you know?

**Comment by mvines** [comment]
Yes so far, but I haven’t picked this up yet so maybe others are lurking.

**Comment by mvines** [comment]
Also blocked by #4189

**Comment by mvines** [comment]
Storage account is also trying to pay for transactions fees

**Comment by rob-solana** [comment]
do we have an issue filed for that?  @sagar-solana

**Comment by sagar-solana** [comment]
No issue for that yet.
