### ISSUE TITLE
Commission decrease should be allowed at any time

### ISSUE THREAD

**Issue by bji** [solana-labs/solana#33843]
#### Problem

The commission_updates_only_allowed_in_first_half_of_epoch feature disallows commission decrease in the second half of epoch.  Given that the purpose of this feature was to prevent 'rug pulls' which are accomplished by *increasing commission* at the end of epoch and then *decreasing commission* at the beginning of next epoch, disallowing decreases during the second half of epoch is unnecessary.

Disallowing commission decreases in the second half of epoch prevents an operational technique that I use with my validator: when I have an operator error that results in reduced stake account rewards for the epoch, I reduce commission to 0% to ensure that stake accounts are not disadvantaged by my actions.  Not being allowed to do this in the second half of an epoch is a real problem for me.

#### Proposed Solution

Add a feature which will enable set-commission logic to first check whether the proposed commission change is a decrease, and if so, do not invoke the "only allow commission change in first half of epoch" rule.

**Comment by joncinque** [comment]
The feature gate issue to track this is #33994
