### ISSUE TITLE
Replay time trended up maybe caused by instructions CU under-counting

### ISSUE THREAD

**Issue by taozhu-chicago** [solana-labs/solana#33869]
#### Problem

2023-10-25 13:00 - 19:00 UTC, replay time trended up: https://discord.com/channels/428295358100013066/560496939779620864/1166742945769201664

Found most `execute_us` was spent within `execute_accessories_process_instructions_process_executable_chain_us`
<img width="1261" alt="image" src="https://github.com/solana-labs/solana/assets/82401714/74e06d2a-4e31-4298-8589-d8fa90b5536b">

Tuned one of our node in MNB to start publish _trace_ level `per-program-timings`, identified one program that consistently spending more than 300ms: 
![image](https://github.com/solana-labs/solana/assets/82401714/322e4cea-528a-44ac-84d6-9db7f8b2290e)

Do a rough calculation of CU/us ratio for Bubblegum instructions, it's at 6CU/us with spikes:
<img width="1273" alt="image" src="https://github.com/solana-labs/solana/assets/82401714/1c0c16eb-564f-4211-9048-5d843b06e212">

Currently cluster average is 30CU/us. So this program might be under-counted for CU, which would have contributed to elevated replay-time in MNB.

#### Proposed Solution
- replay ledger to identify and adjust CU for this program.

**Comment by taozhu-chicago** [comment]
tag @alessandrod

**Comment by taozhu-chicago** [comment]
An similar issue before: #31325

**Comment by steviez** [comment]
I already had a node running so I stored a ledger off for ~10k slots that @taozhu-chicago mentioned as occurring during this period of interest. I've uploaded a ledger (snapshot + rocksdb + genesis.bin) that should be replayable for:
`[225933817, 225944964]`:

Ledger can be obtained from:
gs://ledger-snapshot-service/225933817/

**Comment by taozhu-chicago** [comment]
Replayed slot 225934272 few times, doesn't look like keccak hash is under priced. It consume 85 CU as base cost, plus additional CU for bytes it hashes (somewhere between 32 CU to 100+CU), in few micro seconds. On average it's 76 CU/us on my equnix dev box.

**Comment by taozhu-chicago** [comment]
to capture some finding from slack channel: 
```
alessandro
I just started looking at this and it looks like your regular serialization issue
large accounts, should be fixed by direct mapping
(you can see that execution is largely dominated by serialization, serialization is underpriced and mostly invisible to the scheduler)

when you replay the ledger, you also see an issue with the rbpf jit compiler running all the time at startup
this is a known issue I discovered a couple of weeks ago, being addressed in https://github.com/solana-labs/solana/pull/33715
that issue only manifests when starting a validator, it's a program cache issue, once the cache is warmed up the issue isn't visible

```

**Comment by taozhu-chicago** [comment]
To sum it up: the root cause is large account (~8MB) being copied many times (30+) between instructions, adding extra execution time. Direct Mapping addresses this, which is scheduled to be feature activated sometime. Meanwhile there is a short term patch #33914 to prevent prolonged replay time degrade cluster into vote-only, however the patch carries the risk of reducing TPS. Patch's cost/benefit can be discussed in its PR. Closing this issue since its cause and long term solution have been identified.
