### ISSUE TITLE
Geyser hotreload doesn't work or seems to be platform specific

### ISSUE THREAD

**Issue by segfaultdoc** [solana-labs/solana#33884]
#### Problem
Geyser hotreload seems to use a cached version of the dll.

Steps to Repro:
1. Load Geyser plugin
2. Change and recompile plugin
3. Reload the plugin
4. Notice it uses the old compiled version

The workaround is to rename the `.so` file on each compilation to correctly pull it in.

#### Proposed Solution
Not sure what the solution is here but here's a related issue:
https://github.com/mitchmindtree/hotlib/issues/5

**Comment by segfaultdoc** [comment]
```
#[cfg(test)]
mod tests {
    use {super::*, std::fs};

    #[test]
    fn test_load_lib() {
        unsafe {
            let libpath = "/Path/to/some/existing/file.dylib";
            let libpath = PathBuf::from(libpath.clone());
            let _lib = Library::new(libpath.clone()).unwrap();
            drop(_lib);

            fs::remove_file(libpath.clone()).unwrap();
            let libpath = PathBuf::from(libpath);
            let _lib = Library::new(libpath).expect_err("expected an error");

            let libpath = "/Path/to/some/non-existing/file.dylib";
            let libpath = PathBuf::from(libpath);
            let _lib = Library::new(libpath).expect_err("err");
        }
    }
}
```
this test case fails on my mac. seems like issue with libloader Library

**Comment by t-nelson** [comment]
sounds like this is the crux, https://github.com/nagisa/rust_libloading/issues/59#issuecomment-545450865

not sure there's really anything we can do about that. the plugin would have to not link to std

**Comment by godmodegalactus** [comment]
Yes we also faced the same issues with grpc plugins.
