### ISSUE TITLE
Solana CLI `spl-token`:  Command `set-transfer-hook-program`:  Unclear how to provide "Transfer Hook Authority"

### ISSUE THREAD

**Issue by andirayo** [solana-labs/solana#33938]
#### Versions
* `spl-token-cli 3.2.0`
* `solana-cli 1.16.18 (src:612616be; feat:4033350765, client:SolanaLabs)`

#### Problem
It is unclear how the _"Transfer Hook Authority"_ has to be provided to the Solana CLI (`spl-token`), command `set-transfer-hook-program`.

Using the option `--program-authority transfer-hook-authority-wallet.json` does not work. The `--program-authority` option seems to be ignored and the Solana CLI just uses the default client keypair.

#### Reproduce
This command failed against Solana DevNet cluster:
```
spl-token set-transfer-hook-program 2Z2oEHTifRh9qXQXZJtvPzqNW9qPkNZwk77Nj4u8WMgx D5NkkHKzk6G9VGrnyW7Uqt3swiTAwsqvSJdyKsyRUdYc --program-authority admin_account.json
```
Error message:
```
Error: "Mint 2Z2oEHTifRh9qXQXZJtvPzqNW9qPkNZwk77Nj4u8WMgx has transfer hook authority 3M42uZcVZb5ynr1oCJEgAnbv2XEmGFjsaAcbJ8ZRCcd4, but FBN8aSfNQi51ownFYjhtWnUKibtGzpm8pvKKaZubH3gU was provided"
```
- `3M42uZcVZb5ynr1oCJEgAnbv2XEmGFjsaAcbJ8ZRCcd4` is the pubkey of admin_account.json
- `FBN8aSfNQi51ownFYjhtWnUKibtGzpm8pvKKaZubH3gU` is the pubkey of the default client keypair

#### Notes
The documentation lists
```
--program-authority <SIGNER>    Specify the authority keypair. Defaults to the client keypair address.
```

- It's unclear why the value is described as `<SIGNER>` because this does not seem to align with the description _"Specify the authority keypair."_, particularly because usually a keypair is described as `<KEYPAIR>` (not as `<SIGNER>`).
- Providing a keypair / wallet file does not work and/or is ignored.

**Comment by norwnd** [comment]
Hey @andirayo,
- I can reproduce the issue you are describing, sketched out a PR that possibly resolves it (looks like there is a bug when parsing the parameter you mention): https://github.com/solana-labs/solana-program-library/pull/5722, maybe @joncinque  can take a look ?
- `<SIGNER>` is typically a synonym for `<KEYPAIR>`, it refers specifically to "private key" in that key pair (since private key is the key you will be signing this command with)

**Comment by buffalojoec** [comment]
Thanks for sniffing this one out guys @andirayo @norwnd it should now be fixed.

In the future, open an issue like this in the [SPL repo](https://github.com/solana-labs/solana-program-library) instead! Thanks.
