### ISSUE TITLE
Lack of partial load and store of account causes unnecessary read/write of account data

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#33975]
#### Problem
Lack of partial load and store of account causes unnecessary read/write of account data. The Direct Mapping feature will work more optimally if a portion of the account data could be read and written to.

This is a placeholder issue to enable design discussions and explore the possibility of implementing this.

tag: @brooksprumo, @alessandrod, @Lichtso

**Comment by cavemanloverboy** [comment]
Is the thinking here only from an optimization perspective, or are we also thinking about further parallelization within the runtime?

e.g. transaction_1 takes write lock on account A from byte 0 to 127, transaction_2 takes write lock on accounts A from byte 128 to 255 --> both txs run in parallel

**Comment by alessandrod** [comment]
This is only about optimizing the existing implementation, no external API changes.
