### ISSUE TITLE
Gradual memory growth on validator

### ISSUE THREAD

**Issue by willhickey** [solana-labs/solana#34018]
#### Problem
In tracking the epoch boundary memory growth (see [#debug-epoch-boundary-memory-increase on Discord](https://discord.com/channels/428295358100013066/1163581882521374860/1172186012324204624)) we've discovered an unrelated memory growth. It is small, so not currently a priority, but documenting here for posterity:

|Host|Channel|Commit|
|----|---------|-------|
|mce7|edge|c588f25e|
|mcb7|beta|542b53e5|
|mcs7|stable|197a8165|

[This query](https://metrics.solana.com:8889/sources/27/chronograf/data-explorer?query=SELECT%20mean%28%22used_bytes%22%29%20AS%20%22used_bytes%22%20FROM%20%22canaries-mb%22.%22autogen%22.%22memory-stats%22%20WHERE%20time%20%3E%20%3AdashboardTime%3A%20AND%20time%20%3C%20%3AupperDashboardTime%3A%20AND%20%28host_id%20%3D~%20%2Fmc%5Bebs%5D7%2F%29%20GROUP%20BY%20time%28%3Ainterval%3A%29%2C%20%22host_id%22%20FILL%28null%29) shows the growth. The screenshot and csv show the data as of today. Over the 19 day period from 2023-10-21 to 2023-11-10 the memory usage by each node grew 1-1.5GB

![image](https://github.com/solana-labs/solana/assets/3044442/50965b43-bb7c-4eb1-b60c-a25bc334328e)
[30 day memory growth.csv](https://github.com/solana-labs/solana/files/13321854/30.day.memory.growth.csv)

**Comment by cavemanloverboy** [comment]
total outsider chiming in, so sorry if not helpful, but how much growth is expected from fragmentation over time (from jemalloc)?

**Comment by cavemanloverboy** [comment]
what fixed this? @willhickey
