### ISSUE TITLE
public testnet demo

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#341]
make sure something like this works:

## Public testnet

Testnet is reset every TBD minutes.

Register a node 

```
 cargo run --release --bin solana-fullnode-config -- -d -b PORT > validator.json
```

Run the validator 
```
./multinode-demo/validator.sh validator.json -t testnet.solana.com:8000
```
register a client, which will be granted some testnet tokens
```
 cargo run --release --bin solana-client-config -- -t testnet.solana.com:8000 > client.json
```
run the client demo, which will spend the testnet tokens as fast as it can
```
 cargo run --release --bin solana-client-demo -- client.json validator.json
```
the demo will show the account state on the leader, and on your local validator.

**Comment by garious** [comment]
I don't understand the point of `solana-client-config` here. Seems like the same thing as `solana-mint-demo`.

**Comment by aeyakovenko** [comment]
@garious how about `solana-config --client testnet.solana.com`

**Comment by garious** [comment]
Confusing. The parameter to `--client` is the server address?  How about something like `solana-config --node-type=client --server=testnet.solana.com`?

**Comment by aeyakovenko** [comment]
for the server:
```
solana-config --node-type=server --network=testnet.solana.com
```

**Comment by garious** [comment]
This all works now, right? Close it?

**Comment by mvines** [comment]
I was leaving this open until I'm confident that the last bit works:
> ... and on your local validator.

I'm not right now, aka #538

**Comment by mvines** [comment]
Validators may not be voting right in the public testnet ATM, debugging

**Comment by mvines** [comment]
Looks pretty solid now
