### ISSUE TITLE
Panic due to a duplicate block produced (1.16.17, Jito)

### ISSUE THREAD

**Issue by kernelpanic9** [solana-labs/solana#34142]
Validator-client panicked with the following error:

`[2023-11-16T23:05:33.903111347Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solReplayStage" one=1i message="panicked at 'We are attempting to dump a block that we produced. This indicates that we are producing duplicate blocks, or that there is a bug in our runtime/replay code which causes us to compute different bank hashes than the rest of the cluster. We froze slot 230441996 with hash Some(BLCYQ6iWx4E3MUM3Hf2e1AV9CqJpv4nedTExYouzGnF6) while the cluster hash is 82zqB1jue3sExE47yXyicRB4C5RRdLYcLnaoasquyB14', core/src/replay_stage.rs:1346:29" location="core/src/replay_stage.rs:1346:29" version="1.16.17 (src:00000000; feat:4033350765, client:JitoLabs)"`

Logs: 
[solana_crash_20231117.log.tar.gz](https://github.com/solana-labs/solana/files/13390850/solana_crash_20231117.log.tar.gz)

**Comment by infwonder** [comment]
We are still seeing this error on v1.16.19...

**Comment by mattharrop** [comment]
[234724640-Aa6nkjaUumitWNYQmA9BnHn8dxJzXCrUHGDwFrYGecRT.json](https://github.com/solana-labs/solana/files/13617574/234724640-Aa6nkjaUumitWNYQmA9BnHn8dxJzXCrUHGDwFrYGecRT.json)

**Comment by steviez** [comment]
This issue has been resolved via https://github.com/solana-labs/solana/pull/34382

**Comment by steviez** [comment]
This issue has been resolved via https://github.com/solana-labs/solana/pull/34382

**Comment by infwonder** [comment]
Hi @steviez I did not see this patch being mentioned in recent solana release, when will this patch be included? Thanks!

**Comment by steviez** [comment]
> Hi @steviez I did not see this patch being mentioned in recent solana release, when will this patch be included? Thanks!

The patch didn't get explicitly mentioned in release notes, but running with `>= v1.16.23` on the v1.16 line OR `>= v1.17.9` on the v1.17 line will ensure your have the patch

**Comment by infwonder** [comment]
> > Hi @steviez I did not see this patch being mentioned in recent solana release, when will this patch be included? Thanks!
> 
> The patch didn't get explicitly mentioned in release notes, but running with `>= v1.16.23` on the v1.16 line OR `>= v1.17.9` on the v1.17 line will ensure your have the patch

Thank you!
