### ISSUE TITLE
Allow clients to request tokens from the mint

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#342]
People will want to interact with the public testnet. The slow way is to set up a validator and wait for it to pay out from transaction fees. We shouldn't make that the only way, because it requires making ports on that node accessible to the leader node, which is considerably harder than spinning up the client demo.

Instead, add a new executable `solana-drone` that does testnet airdrops. Clients should send it its `PublicKey` and the drone should give it some tokens, if there are any left in that time slice.

```bash
$ cat mint-demo.json | solana-drone
```

`solana-drone` should implement some form of rate limiting on IP addresses, such as 1 request per minute per IP.  but this can be done in a later release

**Comment by aeyakovenko** [comment]
- [ ] solana-drone daemon that waits for client requests, then sends a transaction form the mints key to the clients public key.  we can do some rate limiting on IP addresses, like 1 request per minute per IP
- [ ] `solana-client-config --testnet testnet.solana.com`  should ask for tokens and generate a client config with an identity that owns those tokens
