### ISSUE TITLE
Extend net/ to support launching a testnet in multiple regions of a cloud providers 

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#3420]
net/ currently only supports launching a testnet in a single region of a single cloud provider, let's extend this to support multiple regions with the same provider.

One way to do this could be to extend the `-z` option to accept a list of zones instead of just a single zone, eg:
```bash
$ ./net/gce.sh create -z us-west1-b,us-east1-c,us-west2-a
```

cc: #2027

**Comment by mvines** [comment]
@pgarg66 - this is done now right?

**Comment by pgarg66** [comment]
👍
