### ISSUE TITLE
My wallet got hacked somehow and my SOL is GONE!

### ISSUE THREAD

**Issue by NarithChesda** [solana-labs/solana#34265]
#### Problem
Here is my account wallet, 7 days after I withdraw from binance after the CZ news to my mobile phantom wallet app.
![image](https://github.com/solana-labs/solana/assets/90504714/be8fcb55-3876-475d-9e49-3dabc2533206)

Here is the hacker account wallet and address: 3smcYnTv17cUycLFWmAmpYNQnPFqeFWKpkrjhzhKE21y
![image](https://github.com/solana-labs/solana/assets/90504714/f096f612-7c9b-4585-ba6e-7138ac0c9739)

How can I recover my SOL? if not then how can I find the leak?

**Comment by buffalojoec** [comment]
Hey, we let you know in the last issue you commented on that this wasn't the place for posting this.
