### ISSUE TITLE
Allow mixed replay descendant + gossip tracking for optimistic confirmation

### ISSUE THREAD

**Issue by AshwinSekar** [solana-labs/solana#34279]
#### Problem

Optimistic confirmation for slot S is aggregated in 2 separate pathways:
- Replay rollup: count votes for slot S and its descendants, compare against threshold
- Cluster rollup: count replay votes and gossip votes for exactly slot S, compare against threshold

There is a potential speedup case that we are missing:
- Count replay votes for slot S + descendants *and* gossip votes for exactly slot S

This is a potential timesave when there is a competing fork. Imagine a potential scenario:
1) Some validators are in a threshold check, 1/3 of the cluster votes for slot S but the tx sends to a minor fork leader
2) 1/3 of the cluster cannot vote on slot S because of threshold check but votes on slot S + 1 a descendant of S which lands in the major fork leader 

Although S has supermajority stake vote, we have to wait until the validators from (1) vote on a descendant of S + 1 which lands in the major fork leader in order to optimistically confirm a block on the fork.
The potential timesave is allowing a mixture of descendants and gossip, as (1) would land in gossip and (2) would land in descendant rollup.

**Comment by AshwinSekar** [comment]
@carllin following up from your comment https://github.com/solana-labs/solana/pull/34014#discussion_r1410171442

The proof https://docs.solana.com/proposals/optimistic_confirmation works with `Range(v)`:
```
Optimistic Confirmation - A block B is then said to have achieved "optimistic confirmation" if >2/3 of stake have voted with votes v where Range(v) for each such v includes B.slot.
```

Why is it the case that OC can't be safely rolled up?

**Comment by AshwinSekar** [comment]
I understand that's the case for gossip votes, but for replay votes you have the ancestors available right?

**Comment by jstarry** [comment]
Ah I see, you're talking about "duplicate confirmed"

**Comment by AshwinSekar** [comment]
just OC, duplicate confirmed does use the same pathway so maybe a benefit there as well, but was mostly focusing on OC here.
