### ISSUE TITLE
can`t execute testnet node.

### ISSUE THREAD

**Issue by Junkyfunk777** [solana-labs/solana#34283]
#### Problem Can`t execute my testnet node. No snapshots available. Nothing going on after executing validator.sh.
Cant move on. In validator.sh is only default code, what is in docs.solana written. Here is some information when i tail logs, or doing ` ps - aux ` command.

`:~$ ps aux | grep solana-validator
sol       549240  0.0  0.0   6436   656 pts/0    S+   15:55   0:00 grep --color=auto solana-validator`

`:~$ tail -f /home/sol/solana-validator.log
    69.197.24.57      |   143 | 8KXc4uGJQvc54YHENRGLLGBbKWhwxDkKKCyVGywjVBp | 1.16.20 | 8899 | 8900 | 5106
    69.197.14.17      |   224 | 3W4fe5WTAS4iPzBhjGP8a1LHBTx8vbscqThXT1THqEGC | 1.16.20 | 8899 | 8900 | 5106
    172.93.103.65     |    32 | 3BCokPfahX9rLYMh6E6uYTEFuchiKd9wZcXUvwDHFYiH | 1.16.20 | 8899 | 8900 | 5106
    74.51.198.6       |   828 | HCBwcEBW67UCjqTsmmtBUSudAZg4qAggGQYtCHvhTSjJ | 1.17.6  | 8899 | 8900 | 5106
    188.32.4.60       | 38852 | DXzf8NkPoFAa1bDyjhrNxbtDH8oE3osqT5ZvNKQaLtDW | 1.17.6  | 8899 | 8900 | 5106
    149.50.98.43      |   795 | 45M6om8quE2DnLh3cYnty8kx1D4AYbMUzZMpytku6Gff | 1.16.20 | 18899| 18900| 5106
    46.181.169.199    |   213 | HQSjbVY7YUjqbSEZ1K9EeEfLsw3pYYVz8hwRG7SWgCmb | 1.16.20 | 8899 | 8900 | 5106
    69.197.27.9       |   424 | BoBAsggJ9YHha1zHK28owCzyL1qwzBS2PXvHzRvqzhuj | 1.16.20 | 8899 | 8900 | 5106
    139.178.68.207    |   503 | 5D1fNXzvv5NjV1ysLjirC4WY92RNsVH18vjmcszZd8on | 1.16.20 | 80   | 80   | 5106
    RPC Enabled Nodes: 761`

What could i do? Need some more information? I`m newbie in this, so i am sorry :)

**Comment by CriesofCarrots** [comment]
We don't provide technical support here; this issue tracker is for software bugs.
You can try #validator-support on discord: solana.com/discord
But I recommend you do some searching through the server history to ensure that your questions are as informed and targeted as possible.
