### ISSUE TITLE
Add a client demo that requests airdrops from solana-drone

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#343]
`solana-client-demo` is configured with `mint-demo.json`, which includes mint's keypair. That gives the demo access to all unallocated tokens. We need a new client demo that doesn't have access to that keypair and instead requests tokens from `solana-drone` (#342). Using the drone to request an airdrop will allow many different users should be able to run this demo without concern that tokens will all be used up by another user.

- [x] client creates or loads a keypair
- [x] We run solana-drone as a daemon on a machine that has a public ip, preferably testnet.solana.com (see #307)
- [x] client make TCP request to testnet.solana.com:DRONE_PORT
- [x] client request should include the public key of the client
- [x] drone should make a transaction from the mint to the client public key

**Comment by garious** [comment]
@aeyakovenko, can you help us scope this ticket? After this client demo gets some tokens, what should it do? We already have a TPS-focused demo. Should this one do something much simpler like send a handful of transactions and check up on them?

**Comment by aeyakovenko** [comment]
@garious 
- [ ] create or load a keypair
- [ ] run solana-drone as a daemon on a machine that has a public ip, preferably testnet.solana.com (see #307)
- [ ] make TCP request to testnet.solana.com:DRONE_PORT
- [ ] request should include the public key of the client
- [ ] drone should make a transaction from the mint to the client public key

**Comment by mvines** [comment]
My current plan is to fix #307 first then use the cloud infra developed there to run the drone as well.  @CriesofCarrots, I'm guessing you're working on #342 first as well? 
Seems like once either of us has finished our respective dependent issue we can rendezvous back here and figure out who does what next.

**Comment by CriesofCarrots** [comment]
Yes, exactly, sounds great.
Right now, the drone's sole function will be to make an airdrop of sols to the public key of a requesting client. That should enable the client demo to perform basic user functions, like send transactions, check transaction status, and check balance. But if you can foresee anything else we might need from the drone for this ticket, do let me know.

**Comment by mvines** [comment]
De-assigning myself, as the infra part of this is all done.  If I can help with something else here please LMK
