### ISSUE TITLE
solana-rpc-client` (lib) due to 2 previous errors

### ISSUE THREAD

**Issue by airdro153** [solana-labs/solana#34308]
#### Problem
error[E0599]: no method named `send_and_confirm_transaction_with_spinner` found for reference `&nonblocking::rpc_client::RpcClient` in the current scope
   --> C:\Users\haikal\.cargo\registry\src\index.crates.io-6f17d22bba15001f\solana-rpc-client-1.17.7\src\rpc_client.rs:681:40
    |
681 |             (self.rpc_client.as_ref()).send_and_confirm_transaction_with_spinner(transaction),
    |                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: there is a method with a similar name: `confirm_transaction_with_spinner`

error[E0599]: no method named `send_and_confirm_transaction_with_spinner_and_commitment` found for reference `&nonblocking::rpc_client::RpcClient` in the current scope
   --> C:\Users\haikal\.cargo\registry\src\index.crates.io-6f17d22bba15001f\solana-rpc-client-1.17.7\src\rpc_client.rs:693:18
    |
692 | /             (self.rpc_client.as_ref())
693 | |                 .send_and_confirm_transaction_with_spinner_and_commitment(transaction, commitm...
    | |                 -^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: there is a method with a similar name: `confirm_transaction_with_commitment`
    | |_________________|
    | 

For more information about this error, try `rustc --explain E0599`.
error: could not compile `solana-rpc-client` (lib) due to 2 previous errors

 *  The terminal process "C:\Users\haikal\.cargo\bin\cargo.exe 'run', '--package', 'botUnmintGst', '--bin', 'botUnmintGst'" terminated with exit code: 101. 
 *  Terminal will be reused by tasks, press any key to close it.

#### Proposed Solution

lib error

**Comment by buffalojoec** [comment]
Hey there, could you possibly provide some more context around this issue? Are you insinuating this is a bug in the library?

At first glance, the requested function appears to be there in `v1.17.7`.
https://docs.rs/solana-rpc-client/1.17.7/src/solana_rpc_client/nonblocking/rpc_client.rs.html#721-724
