### ISSUE TITLE
How to listen to block events since `block_subscribe` is deprecated?

### ISSUE THREAD

**Issue by dhruvja** [solana-labs/solana#34379]
#### Problem

I want a listen to a stream of finalized blocks and the [block_subscribe](https://docs.rs/solana-pubsub-client/1.17.3/solana_pubsub_client/nonblocking/pubsub_client/struct.PubsubClient.html#method.block_subscribe) is the one i need. But seems like it is deprecated and i couldnt find any other alternative. There seems to be a workaround by passing a flag to the validator but i was wondering if I could listen to the events without running it since i would be needing it on mainnet.

Please tell me what i can use to listen to block events.

**Comment by buffalojoec** [comment]
Hey there, this really isn't an issue or bug report for the code, so it doesn't belong here.

To answer your question, the argument - which isn't a _workaround_ it's just an explicit flag to tell the node to use an unstable feature - can be passed to a local validator while you test locally. On your way up to higher clusters (devnet -> mainnet-beta), you'll need to find an RPC provider who offers `BlockSubscribe`.

**Comment by dhruvja** [comment]
> Hey there, this really isn't an issue or bug report for the code, so it doesn't belong here.
> 
> To answer your question, the argument - which isn't a _workaround_ it's just an explicit flag to tell the node to use an unstable feature - can be passed to a local validator while you test locally. On your way up to higher clusters (devnet -> mainnet-beta), you'll need to find an RPC provider who offers `BlockSubscribe`.

Ok thanks i will keep a note of that. What is the right place to ask these types of questions?

Thanks for answering the question, i will try to find the rpc provider which offers that.
