### ISSUE TITLE
Vulnerability when stake activation waiting

### ISSUE THREAD

**Issue by abaykanat** [solana-labs/solana#34395]
hello!
closing the loophole/vulnerability for scammers and returning the money to the deceived user. Here's how I suggest doing it:

1.prohibit changing Stake Authority Address and Withdraw Authority Address if the stake account is waiting for the start of a new epoch to be activated. this will protect many people and they will not lose their stake account, like me and many others;
2.after deactivating staking, return deactivating sol to the address that created this stake account. this will return the sol to its true owners.
Example:
my account 7ZxRGZcKRgARNe35fPq6rkfdTWBZQe3KdofEnBmBeZzu created a stake account FuAqLX55WcSkSdVYtpmRWDvpC71YiezvkzcN4RYjHNd8 (https://solscan.io/tx/51AKRzWTtZDrfg5Mf1RPLLdxcRLxHWuHQ mK5kKyAGQbssaU3Q3CM5Qo59DEcKVqySp681Lhr5oUVguraShNP6xiu). but in the next transaction the scammers changed the Stake Authority Address and Withdraw Authority Address in this account (https://solscan.io/tx/5AmutirdmMujU6hLXJezB9d3NcQsN3sgCrz1FHgHxKw3GKKye3Updyz3Dc4myuaBaZxEfmfrR7bzycj2RXJqaTK4).
It is necessary that after deactivating staking, Solana returns to my address 7ZxRGZcKRgARNe35fPq6rkfdTWBZQe3KdofEnBmBeZzu, which created the stake address FuAqLX55WcSkSdVYtpmRWDvpC71YiezvkzcN4RYjHNd8.

**Comment by buffalojoec** [comment]
Hey, I believe we responded to you in [this issue on the Solana Program Library](https://github.com/solana-labs/solana-program-library/issues/5972). Closing!

**Comment by abaykanat** [comment]
Why will the proposed improvements make life more difficult for users? maybe suggest another solution to the problem?
My funds were not taken directly from my account, but my account stake was stolen. I worry not only about myself, but in general about the future of the network and future users.
