### ISSUE TITLE
Website docs fixes

### ISSUE THREAD

**Issue by alfiedotwtf** [solana-labs/solana#34397]
I couldn't find the repo to apply the patch to, so I'm creating an issue here:

On the page https://solana.com/news/proof-of-history

    - On Other Chains Railways
    + On Other Chains' Railways

    - no schedule.The train
    + no schedule . The train

    - validate a blockchain one at a time
    + validate one piece at a time

    - Other Chain Railways
    + Other Chains' Railways

On that, maybe the website/website docs should go into a Gitub repo?

**Comment by alfiedotwtf** [comment]
There's another isssue here:

    https://www.soldev.app/course

Under "Module 2", for some reason, "4 Program Testing" is blurred out and when you click it, it goes back to the same page.

**Comment by CriesofCarrots** [comment]
This repository doesn't house the code for solana.com or track issues for that website.

Unfortunately, I don't really have a better avenue to suggest; it appears the solana.com web team doesn't have any system in place to accept public bug reports. Sorry about that.
You can try emailing hello@solana.com

**Comment by alfiedotwtf** [comment]
I've emailed hello@solana.com a few times with website documentation bugs, but it looks like that inbox is currently unmanaged.

Maybe @jstarry might be able to ping somebody to respond, or create a new repo for the website docs?
