### ISSUE TITLE
Scalabilité limitée

### ISSUE THREAD

**Issue by 9000000uhb** [solana-labs/solana#34392]
Problème : Scalabilité limitée
La blockchain de Solana est conçue pour être rapide et évolutive, mais elle peut rencontrer des problèmes de scalabilité lorsque le nombre de transactions augmente considérablement. Cela peut entraîner des retards dans la confirmation des transactions et une congestion du réseau.

Solution proposée : L'utilisation de sharding
Une solution possible pour résoudre le problème de scalabilité est l'utilisation de sharding sur la blockchain de Solana. Le sharding consiste à diviser la blockchain en plusieurs "shards" ou fragments, permettant à plusieurs transactions d'être traitées simultanément.

Chaque shard fonctionne de manière indépendante et peut traiter ses propres transactions, ce qui permet d'augmenter considérablement la capacité de traitement de la blockchain dans son ensemble. En utilisant le sharding, Solana pourrait traiter un plus grand nombre de transactions en parallèle, ce qui améliorerait la vitesse et l'efficacité du réseau.
Cependant, il est important de noter que l'introduction du sharding nécessite des ajustements au niveau du protocole et peut entraîner des compromis en termes de sécurité et de décentralisation. Il est donc essentiel de mener des recherches approfondies et d'implémenter soigneusement le sharding pour garantir la robustesse et la sécurité du réseau.

**Comment by joncinque** [comment]
On n'a pas de projets d'introduire du sharding dans le réseau. Tu peux même voir que l'ancien titre du podcast de Solana était "No Sharding"!
