### ISSUE TITLE
RPC node simulate transaction consumed units

### ISSUE THREAD

**Issue by Arrowana** [solana-labs/solana#34445]
#### Problem

The JSON RPC simulate_transaction method does not return a meaningful `consumed_units`. It returns what is consumed by the successful ixs only. Rather than the total consumed units.

Example:

https://explorer.solana.com/tx/3KMqaFZQwWaL9evSZYWHzptxdqZfS7o1XhQDgLmvPzU1hsAgssnWqQJTWYfXbqBMH4MimSEjLSepQg74aYxe9GN2

Simulating this transaction returned `consumed_units` 19165

However, it consumed 111,898 units. That value is correct in the transaction meta after submitting as we can see in the explorer

#### Proposed Solution

@joncinque found it should be an easy fix by adding `total_errored_units` to `accumulated_units`
https://github.com/solana-labs/solana/blob/2dfcdce630cd9d1da2b93cb54b6d4dde45400d27/runtime/src/bank.rs#L4359-L4365

**Comment by kantik001** [comment]
In the example transaction you provided, consumed_units is indeed 19,165, while the total number of units used (according to the transaction metadata) is 111,898. However, it must be borne in mind that consumed_units refers only to successfully executed usage instructions (ixs), and not to all instructions used. In this case, the number of successful ixs is 545, and they used a total of 19,165 units. This means that on average, each successful instruction manual used about 35 units.

Thus, the information that simulate_transaction returns only the number of successful ixs used, and not the total number of units used, is correct. However, this is not an error, but rather a feature of this method.

Regarding the proposed solution, adding total_errored_units to accumulated_units may be useful if you want to get a more accurate estimate of the total number of units used.

**Comment by joncinque** [comment]
According to the docs for `simulateTransaction` at https://docs.solana.com/api/http#simulatetransaction, the `unitsConsumed` field is "The number of compute budget units consumed during the processing of this transaction", which means that it should probably be reporting all units consumed, even from an errored instruction.

**Comment by CriesofCarrots** [comment]
Whoa, is that AI spam? I wonder where it got the 545 value.
"each successful instruction manual" is my favorite part.
Okay, I'll shut up now, in case this will encourage it.

**Comment by kantik001** [comment]
I wanted to look a little smarter 😄
