### ISSUE TITLE
Add priority fee option/instruction for solana program deploy

### ISSUE THREAD

**Issue by Jac0xb** [solana-labs/solana#34444]
#### Problem

Experiencing deployment failure caused by <1% of transactions failing  every time. This has never happened so consistently before (have tried several RPC providers).

#### Proposed Solution

- Add priority fees option to `solana program deploy` either microlamport or lamport amount to spend on entire deployment. Only issue is this means more transactions too since this new instruction will have ix data / account overhead. 

- `solana deploy program --buffer` seems to restart process rather than just resuming from previous deployment. If this is possible then this is preferred.

- Options to set max retry for failed buffer loading transactions. What good is failing the entire process if I can't resume from previous deployment attempt.

**Comment by Jac0xb** [comment]
This is still an issue, anyone with context around the CLI would be most helpful if they could lend a hand on this?

**Comment by swimricky** [comment]
not an direct solution but i had issues with my deployments failing back when solana was on 1.9.x - 1.10.x and one workaround was to use https://beta.solpg.io/ to do deployments

**Comment by b1acKr0se** [comment]
It's so frustrated to be unable to deploy an upgrade to my program after fixing the bugs. Please someone take a look at this. A simple config to set priority fees is enough for now.

**Comment by verata-veritatis** [comment]
With the current network conditions, this is a must...

**Comment by shrestha-roshan** [comment]
It worked when i use https://beta.solpg.io/ and set priority fee to max.

**Comment by solidquant** [comment]
I've been failing all my deploys... max retries for 5 times and 3~4 resumes for a couple of hours and still fails. I think priority fees could help with this

**Comment by LobsterMonkey** [comment]
Can something be done please ? It's starting to get ridiculous not being able to deploy for days

**Comment by webstar1117** [comment]
I also face this issue. I am failing to deploy my program on chain continuously. someone can give me solution??

**Comment by wphan** [comment]
if anyone wants a quick solution, this was how i hardcoded priority fees for `solana program deploy`:

https://github.com/wphan/solana/pull/1

**Comment by joncinque** [comment]
Added in https://github.com/anza-xyz/agave/pull/364 and present in 1.18.8, please upgrade to the latest tools
