### ISSUE TITLE
disable gen snapshot

### ISSUE THREAD

**Issue by YuXiaoCoder** [solana-labs/solana#34522]
#### Problem
How can I set a parameter to disable the local generation of snapshot files?

**Comment by steviez** [comment]
1) Unless you have some sophisticated scheme with multiple nodes sharing snapshots, not creating snapshots means your node will almost assuredly have a long period of delinquency whenever you need to restart it (ie software upgrades)
2) We do not provide support on GitHub; try SSE or our [Discord](https://discord.com/invite/solana)
