### ISSUE TITLE
install rpc node failed  with download snapshot

### ISSUE THREAD

**Issue by riyue121** [solana-labs/solana#34539]
Hi
         After starting the validator, the snapshot file will be automatically downloaded, but after the file download is completed, the following error will appear, prompting that the directory does not exist.

errors:

thread 'solDeletePath' panicked at 'background delete: IoWithSourceAndFile(Os { code: 2, kind: NotFound, message: "No such file or directory" }, "background remove_dir_all", "/data/solana/accounts/run_to_be_deleted")', /var/lib/buildkite-agent/builds/kong-1/solana-labs/solana-secondary/runtime/src/snapshot_utils.rs:555:18stack backtrace:
   0:     0x557b7d34799a - std::backtrace_rs::backtrace::libunwind::trace::ha9053a9a07ca49cb
       at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x557b7d34799a - std::backtrace_rs::backtrace::trace_unsynchronized::h9c2852a457ad564e
            at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x557b7d34799a - std::sys_common::backtrace::_print_fmt::h457936fbfaa0070f
              at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x557b7d34799a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h5779d7bf7f70cb0c
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x557b7d370f5e - core::fmt::write::h5a4baaff1bcd3eb5
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/fmt/mod.rs:1232:17
   5:     0x557b7d3423b5 - std::io::Write::write_fmt::h4bc1f301cb9e9cce
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/io/mod.rs:1684:15
   6:     0x557b7d347765 - std::sys_common::backtrace::_print::h5fcdc36060f177e8
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x557b7d347765 - std::sys_common::backtrace::print::h54ca9458b876c8bf
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x557b7d3490ef - std::panicking::default_hook::{{closure}}::hbe471161c7664ed6
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:271:22
   9:     0x557b7d348e2b - std::panicking::default_hook::ha3500da57aa4ac4f
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:290:9
  10:     0x557b7ccff4fe - solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}::hfd7e9cb3cbd139c5
  11:     0x557b7d34981d - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h6507bddc3eebb4a5
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/boxed.rs:2001:9
  12:     0x557b7d34981d - std::panicking::rust_panic_with_hook::h50c09d000dc561d2
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:696:13
  13:     0x557b7d349599 - std::panicking::begin_panic_handler::{{closure}}::h9e2b2176e00e0d9c
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:583:13
  14:     0x557b7d347e06 - std::sys_common::backtrace::__rust_end_short_backtrace::h5739b8e512c09d02
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys_common/backtrace.rs:150:18
  15:     0x557b7d3492a2 - rust_begin_unwind
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/panicking.rs:579:5
  16:     0x557b7b324bb3 - core::panicking::panic_fmt::hf33a1475b4dc5c3e
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/panicking.rs:64:14
  17:     0x557b7b325063 - core::result::unwrap_failed::hdff5465d74574b44
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/core/src/result.rs:1750:5
  18:     0x557b7b885f4b - std::sys_common::backtrace::__rust_begin_short_backtrace::h4e384b21b6ca76b9
  19:     0x557b7b831f3c - core::ops::function::FnOnce::call_once{{vtable.shim}}::hf81a7dabc8b8e672
  20:     0x557b7d34d1f3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h39990b24eedef2ab
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/boxed.rs:1987:9
  21:     0x557b7d34d1f3 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h01a027258444143b
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/alloc/src/boxed.rs:1987:9
  22:     0x557b7d34d1f3 - std::sys::unix::thread::Thread::new::thread_start::ha4f1cdd9c25884ba
                               at /rustc/84c898d65adf2f39a5a98507f1fe0ce10a2b8dbc/library/std/src/sys/unix/thread.rs:108:17
  23:     0x7f602bf4dac3 - <unknown>
  24:     0x7f602bfdf660 - <unknown>
  25:                0x0 - <unknown>
[2023-12-20T10:11:54.585539536Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="solDeletePath" one=1i message="panicked at 'background
delete: IoWithSourceAndFile(Os { code: 2, kind: NotFound, message: \"No such file or directory\" }, \"background remove_dir_all\", \"/data/solana/accounts/run_to_be_deleted\")', /var/lib/buildkite-agent/b
uilds/kong-1/solana-labs/solana-secondary/runtime/src/snapshot_utils.rs:555:18" location="/var/lib/buildkite-agent/builds/kong-1/solana-labs/solana-secondary/runtime/src/snapshot_utils.rs:555:18" version=
"1.16.23 (src:85e3058b; feat:4033350765, client:SolanaLabs)"

**Comment by riyue121** [comment]
Version
 solana-validator 1.16.23 (src:85e3058b; feat:4033350765, client:SolanaLabs)

**Comment by DonnieJay11** [comment]
A Ticket has been opened for you.
Talk to a [Solana Live support agent](https://desks.live/) with ID: D17Y84D64X

Click on the [Live Chat](https://desks.live/) at the bottom corner to initiate chat

**Comment by riyue121** [comment]
start command:


#!/bin/bash
set -o errexit
set -o nounset
set -o pipefail
export RUST_LOG=error
export RUST_BACKTRACE=full
/data/solana/solana/target/debug/solana-validator \
        --ledger /data/solana/data/ledger \
        --accounts /data/solana/accounts \
        --identity /data/solana/data/config/validator-keypair.json \
        --known-validator 7Np41oeYqPefeNQEHSv1UDhYrehxin3NStELsSKCT4K2 \
        --known-validator GdnSyH3YtwcxFvQrVVJMm1JhTS4QVX7MFsX56uJLUfiZ \
        --known-validator DE1bawNcRJB9rVm3buyMVfr8mBEoyyu73NBovf2oXJsJ \
        --known-validator CakcnaRDHka2gXyfbEd2d3xsvkJkqsLw2akB3zsN1D2S \
        --expected-genesis-hash 5eykt4UsFv8P8NJdTREpY1vzqKqZKvdpKuc147dw2N9d \
        --entrypoint entrypoint.mainnet-beta.solana.com:8001 \
        --entrypoint entrypoint2.mainnet-beta.solana.com:8001 \
        --entrypoint entrypoint3.mainnet-beta.solana.com:8001 \
        --entrypoint entrypoint4.mainnet-beta.solana.com:8001 \
        --entrypoint entrypoint5.mainnet-beta.solana.com:8001 \
	--minimal-snapshot-download-speed \
	--no-voting \
        --snapshot-interval-slots 500 \
        --maximum-local-snapshot-age 3500 \
        --rpc-bind-address 127.0.0.1 \
        --rpc-port 8799 \
        --gossip-port 8801 \
        --dynamic-port-range 8802-9812 \
        --no-port-check \
        --wal-recovery-mode skip_any_corrupted_record \
        --enable-rpc-transaction-history \
        --enable-cpi-and-log-storage \
        --init-complete-file /data/solana/data/init-completed \
        --require-tower \
        --no-wait-for-vote-to-start-leader \
        --no-poh-speed-test \
        --limit-ledger-size 50000000 \
        --accounts /data/solana/accounts \
        --log /data/solana/logs/sol.log

**Comment by CriesofCarrots** [comment]
It sounds like you need to start with #validator-support on discord: https://solana.com/discord
Once you are more up to speed with running a validator and determine that there is indeed a bug, please return to open an issue.
