### ISSUE TITLE
Why are signatures at the `processed` level not recoverable?

### ISSUE THREAD

**Issue by srvinii** [solana-labs/solana#34663]
I don't know if it's a problem already reported, but currently signatures at the Processed level are not recoverable with most RPC providers, including the clusters themselves found at: https://docs.solana.com/cluster/rpc-endpoints

As specified in this documentation below, it should be possible to receive some getTransaction with the commitment level `Processed`:
https://docs.solana.com/cluster/commitments

But the response most clients return is something like:
```
InvalidParamsMessage {
     message: "Method does not support commitment below `confirmed`",
}
```

If anyone can help with any kind of guidance or correction to the documentation please, because for my project I need to use this method which is available in the documentation itself.

**Comment by buffalojoec** [comment]
Hey there. That's correct, `getTransaction` does not support any commitment level below `confirmed`.

I guess you're right, the documentation on the RPC doesn't say that specifically. It should be updated: #34664.

For your project, perhaps you can leverage the fact that the transaction signature is just the first signature in the list of signatures on the transaction, ie. `transaction.signatures[0]`?

**Comment by hh-h** [comment]
@buffalojoec is there any way to get the recent blockhash of processed transaction?

**Comment by buffalojoec** [comment]
> @buffalojoec is there any way to get the recent blockhash of processed transaction?

You mean the `recent_blockhash` used when the transaction was submitted?

**Comment by hh-h** [comment]
> > @buffalojoec is there any way to get the recent blockhash of processed transaction?
> 
> You mean the `recent_blockhash` used when the transaction was submitted?

exactly

**Comment by buffalojoec** [comment]
> > > @buffalojoec is there any way to get the recent blockhash of processed transaction?
> > 
> > 
> > You mean the `recent_blockhash` used when the transaction was submitted?
> 
> exactly

It's in the response for a [`Transaction` object](https://solana.com/docs/rpc/json-structures#transactions) - ie. `getTransaction` or `getBlock`. But, as the issue states, `processed` is not supported for this method, so you'd have to use a different commitment level.

**Comment by buffalojoec** [comment]
I've linked a correction to the documentation and submitted a PR for the change. Closing in favor of #34664
