### ISSUE TITLE
Publish 1.16.25 and 1.16.26 on crates.io

### ISSUE THREAD

**Issue by fanatid** [solana-labs/solana#34696]
#### Problem

The latest version for 1.16 on crates.io is 1.16.24: https://crates.io/crates/solana-sdk/versions

#### Proposed Solution

Please publish 1.16.25 and 1.16.26

:heavy_check_mark:  1.16.25 is published now: https://crates.io/crates/solana-sdk/1.16.25

**Comment by fanatid** [comment]
discussion in discord: https://discord.com/channels/428295358100013066/560503042458517505/1194030967095046234

**Comment by CriesofCarrots** [comment]
@fanatid , we expect [this PR](https://github.com/solana-labs/solana/pull/34723) to fix the crate-publishing issue. Rather than futz with historical releases, we will cut v1.16.27 shortly, which should see all crates published.

**Comment by fanatid** [comment]
1.16.27 published, thank you!
