### ISSUE TITLE
More portable demo in README

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#347]
The README says to pass `-d` to `solana-fullnode-config` and `solana-client-demo`. On macOS, that IPv6 address causes `UdpSocket::bind` to return `AddrNotAvailable`. Is there a portable solution here for both macOS and Linux?

**Comment by garious** [comment]
Should `-d` be the default now?

**Comment by garious** [comment]
@sakridge, ping

**Comment by sakridge** [comment]
fixed by: https://github.com/solana-labs/solana/pull/354
