### ISSUE TITLE
error: failed to run custom build command for `etcd-client v0.11.1`

### ISSUE THREAD

**Issue by salemalem** [solana-labs/solana#34734]
When trying to install via cargo build
![image](https://github.com/solana-labs/solana/assets/42411937/b6077aad-861f-486b-a39f-588bf60a7d56)

**Comment by steviez** [comment]
Hi, I believe you missed a step in the posted direction (linked below); the error message is pretty clearly telling you that it was unable to find the protobuf compiler.
https://github.com/solana-labs/solana/blob/master/README.md#building

More so, we don't use GH for support and I'm going to close this issue; any further questions for something like this should be directed at the Solana Stack Exchange:
https://solana.stackexchange.com/
