### ISSUE TITLE
The Solana CLI dependency has not been published for version 1.16.27 on crates.io

### ISSUE THREAD

**Issue by Deniskore** [solana-labs/solana#34742]
Please publish the solana-cli dependency for the newly released version 1.16.27
https://crates.io/crates/solana-cli/versions

**Comment by andreisilviudragnea** [comment]
As a side note, there are many missing versions for `solana-cli` on crates.io, apart from `1.16.27`.

**Comment by cecuabin** [comment]
2(d11ts1)/1^-b^^-2/9 + ddx(Ass.V).dmb
R2 = rm^2 + 2/1 (oh^-eipi^n2-2*mf.rsc
n^3x.u'/ r^2, 64pi rnt?d3/4*.int
-L^2 = 0rc . g3/2pi / Am^-pu.u*.lk
z = r^2 v^2 - 2*.zip
3+1/2Nmf = -Aq' . 1/2hco.dnc
Trc . dt^2 = oH
OH = 5Tu' . 3/5q^2
dryHe = Frv^vu^2
10KT = / . 2/1 Api/-pu.ucc
DM = ds^5/4 - pu^-2mû'. -hu!
arcsen^2 = Apu'-mf'/1
5/0- . Mo - ddt^2E = GEo . Q^nk . pEc - Ec2
dt = 3/2j - dc2 . t^h + KPR+-4/27
mu^2 = -t^2 + arcsen r^216pirsc^-2/1
s = -2/1 rsc^2 - TKqu' +DEc
o = -pmiEc't^3/2
a = d-pmu . QPRRct
q = +- -2/1dp (-R)
cos159 = ^8pi^KPR 24/7 + 2/3 pidrt^2ms / r^2arsen3/0
FRmo = Amu + KP445 -r^2h
gcr =dt^3 . -1/2dt

**Comment by CriesofCarrots** [comment]
Thanks, the issue with crate publishing for latest releases on the v1.16 branch is known. Feel free to follow along on [Discord](https://solana.com/discord) #devops, if you'd like to know more about the cause.
