### ISSUE TITLE
compile config

### ISSUE THREAD

**Issue by zxzyy10** [solana-labs/solana#34764]
I attempted to compile the Solana binary locally (v1.16.25) using the ./cargo build command with the added --release option, as mentioned in the documentation. However, the resulting executable does not sync with the latest Solana blocks. Surprisingly, using the executable from the release works correctly and syncs with the latest Solana blocks. Could you provide the compilation options and versions of related software that you use?

**Comment by steviez** [comment]
We don't offer support on GitHub; feel free to head over to our Discord and make sure to provide plenty of details:
https://discord.com/invite/solana

That being said, I'm inclined to think there was a config difference between the run w/ your compiled binary v. the binary you downloaded / you built on one architecture but tried running on another / or something of that nature.
