### ISSUE TITLE
May one of you smarter folk than I although Iam pretty experienced in digital assets.. help or suggest a way to recover over 150 sol tokens for over a year that i sent to a robinhood appsaved  address used many times from a kraken sol account.. Jun 15 i sent over 150 sol to RH and they claim tyo have delisted addresses June 13th :* at the time they were 2900 dollar value now they are 16,000 :( crying ive actually sent a few dollars to the addres delisted ant it hits on chain and increases value. so they are stuck

### ISSUE THREAD

**Issue by agshuman** [solana-labs/solana#34805]
May one of you smarter folk than I although Iam pretty experienced in digital assets.. help or suggest a way to recover over 150 sol tokens saved for over a year that i sent to a robinhood app address used many times from a kraken sol account.. Jun 15 i sent over 150 sol to RH and they claim tyo have delisted addresses June 13th :* at the time they were 2900 dollar value now they are 16,000 :( crying

_Originally posted by @agshuman in https://github.com/solana-labs/solana/issues/34800#issuecomment-1894940246_

![Screenshot 2024-01-07 034935](https://github.com/solana-labs/solana/assets/1637709/58be8108-15fb-4c7e-8a63-bc26fd2eb7f6)

the photo of the block is from a txn 3 weeks prior sent from kraken to same Robinhood address.. and it posted in my RH account June 15 sent over 150 and hit a dead wallet still can send sol to it and its on the chain.

**Comment by agshuman** [comment]
![Screenshot 2024-01-07 034935](https://github.com/solana-labs/solana/assets/1637709/bfb0b13b-0c40-4922-b3e2-3aa7cef4fb94)
![Screenshot 2024-01-07 034935](https://github.com/solana-labs/solana/assets/1637709/5a8afbec-696d-46f6-9819-aa109533c6a8)

**Comment by agshuman** [comment]
you can see 3 weeks prior to june 15 i sent 50 sol to the same Robinhood address in my acccount

**Comment by agshuman** [comment]
![Uploading Screenshot 2024-01-07 034935.png…]()

**Comment by agshuman** [comment]
Iam praying there is a way to recover what is rightfully owned and paid for with proof from kraken and robinhood..

**Comment by t-nelson** [comment]
this isn't a support channel
