### ISSUE TITLE
Testnet participation howto is missing staking setup and monitoring of validator voting

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#3481]
#### Problem

Testnet participation howto is missing staking setup and monitoring of validator voting.

#### Proposed Solution

Fix it.

https://github.com/solana-labs/solana/blob/master/book/src/testnet-participation.md
- [x] Instructions on how to airdop from a drone to the validators stake account (fullnode-x.sh does this)
- [x] Graphana counters for voting #3485 
- [x] where to find the graphana board for the validator
- [x] Wallet rpc call to display staking account state

tag: @rob-solana @mvines

**Comment by mvines** [comment]
Bump to v0.14, although until #3798 is fixed the remaining work here is something of a moot point

**Comment by mvines** [comment]
done
