### ISSUE TITLE
Consider returning the final Upgrade transaction signature on `solana program deploy`

### ISSUE THREAD

**Issue by ellttBen** [solana-labs/solana#34830]
#### Problem
Currently, the `solana program deploy` command only returns the deployed program's programId. In the context of program upgrades it would be very useful to get the transaction signature for the final Upgrade transaction. Having a precise history of deployments is very useful for dealing with potential issues and dealing with several versions of the same program when parsing its transaction history.

#### Proposed Solution
A `transaction_signature` field should be added to the `solana program deploy` output. I am willing to make a quick PR for this if there is any interest.

**Comment by buffalojoec** [comment]
> I am willing to make a quick PR for this if there is any interest.

Sure!
