### ISSUE TITLE
Create solana-bootnode for better node bootstrapping (Validator public testnet configuration)

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#349]
- [ ] validator at boot connects to drone with a TCP connection
- [ ] drone looks at the client's IP address that is in the TCP connection
- [ ] drone checks that all the expected UDP ports are reachable
- [ ] drone sends validator the IP address that is reachable
- [ ] validator advertirzes that IP on the gossip network
- [ ] validator binds to 0.0 locally, so we need a way to distinguish an advertise address and bind address in the configuration of the validator

**Comment by garious** [comment]
Does this need to be on v0.7.0? I have plenty of questions, but don't want to ask them if the testnet will run without this feature. Biggest question, is it possible for the validator to already know everything its asking of the drone? And so if trying to set up a validator from behind a firewall, the advice would be, "yep, don't do that."

**Comment by aeyakovenko** [comment]
For a bear bones mvp, no.

**Comment by garious** [comment]
Cool, stretch goals are good, thanks.

**Comment by garious** [comment]
Bitcoin bootstrapping: https://en.bitcoin.it/wiki/Network#Bootstrapping
Ethereum bootstrapping: https://github.com/ethereum/go-ethereum/wiki/Connecting-to-the-network

I don't think we should extend the drone into this space. Instead, we should create a new executable called `solana-bootnode` (or `solana-beacon`). The drone should stay extremely minimum and possibly never exist outside a testnet. A bootnode, however, which I believe is what's been described by this ticket, should stick around for the long haul.

**Comment by mvines** [comment]
Renamed issue title and booted from 0.7.0 as this is not required for this release.

**Comment by garious** [comment]
@aeyakovenko, this one needs a lot of historical context to guess what should be done. What do you think about opening a new updated ticket and closing this one?

**Comment by aeyakovenko** [comment]
@garious i think @rob-solana knows what to do by now :)
