### ISSUE TITLE
How to require Solana validator to use a proxy?

### ISSUE THREAD

**Issue by GaN601** [solana-labs/solana#34928]
I am in a restricted network and would like to set up a private RPC node But I still can't make Solana validator use the system agent

**Comment by CriesofCarrots** [comment]
We don't provide technical support on github. Try https://solana.com/discord #validator-beginners

**Comment by GaN601** [comment]
> We don't provide technical support on github. Try https://solana.com/discord #validator-beginners

the channel is not public
