### ISSUE TITLE
the trait bound `T: borsh::de::BorshDeserialize` is not satisfied

### ISSUE THREAD

**Issue by BTCLTC** [solana-labs/solana#35013]
#### Problem
![image](https://github.com/solana-labs/solana/assets/13432688/43e499bc-364c-431a-8dae-9b4c13f8462b)

anchor build error

```bash
solana-cargo-build-sbf 1.17.18
platform-tools v1.37
rustc 1.68.0
```

**Comment by buffalojoec** [comment]
Hey there, this isn't the correct repository for reporting Anchor build errors.

Since this looks to be an issue with a dependency mismatch, I would encourage you to search for recent issues/PRs [like this one](https://github.com/coral-xyz/anchor/pull/2798) or take it to the Stack Exchange!
