### ISSUE TITLE
Update Zeroize to new version?

### ISSUE THREAD

**Issue by LUK3ARK** [solana-labs/solana#35042]
#### Problem
Is there anything blocking update to higher version of zeroize? I require at least v1.4.

all possible versions conflict with previously selected packages.

  previously selected package `zeroize v1.4.0`
    ... which satisfies dependency `zeroize = "^1.4"` of package `signatory v0.23.1`

**versions that meet the requirements `>=1, <1.4` are: 1.3.0, 1.2.0, 1.1.1, 1.1.0, 1.0.0**

#### Proposed Solution
update zeroize

**Comment by LUK3ARK** [comment]
update - just found the notes on this issue in the cargo.toml

**Comment by guotie** [comment]
how to solve?
