### ISSUE TITLE
Potential bug in inner_instructions

### ISSUE THREAD

**Issue by fabioberger** [solana-labs/solana#35067]
#### Problem

```
let TransactionSimulationResult {
        result,
        logs,
        post_simulation_accounts,
        units_consumed,
        return_data,
        inner_instructions,
    } = bank.simulate_transaction(transaction, overrides.clone());
```
   
Are the `inner_instructions` returned from `bank.simulate_transaction` guaranteed to have an entry for every top-level instruction of the passed in transaction? I’m finding cases where this isn’t happening — there are fewer entries in `inner_instructions` than in `transaction.message.instructions()`.

Here is an example where `inner_instructions.len() == transaction.message.instructions().len()`  when the transaction doesn’t revert. But, if an instruction error is encountered, the lengths are no longer equal:

### Without revert:

```
err: None
top level instructions length: 7
inner_instructions length: 7 
inner_instructions: [[], [], [CompiledInstruction { program_id_index: 7, accounts: [6], data: [21, 7, 0] }, CompiledInstruction { program_id_index: 3, accounts: [0, 2], data: [0, 0, 0, 0, 240, 29, 31, 0, 0, 0, 0, 0, 165, 0, 0, 0, 0, 0, 0, 0, 6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235, 121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133, 126, 255, 0, 169] }, CompiledInstruction { program_id_index: 7, accounts: [2], data: [22] }, CompiledInstruction { program_id_index: 7, accounts: [2, 6], data: [18, 175, 177, 183, 253, 19, 201, 252, 234, 149, 132, 88, 165, 235, 169, 158, 75, 88, 43, 207, 179, 76, 104, 59, 201, 97, 63, 49, 156, 217, 175, 28, 27] }], [], [], [CompiledInstruction { program_id_index: 23, accounts: [7, 19, 22, 14, 13, 20, 21, 11, 18, 16, 12, 17, 15, 24, 2, 1, 0], data: [9, 64, 66, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }, CompiledInstruction { program_id_index: 7, accounts: [2, 20, 0], data: [3, 64, 66, 15, 0, 0, 0, 0, 0] }, CompiledInstruction { program_id_index: 7, accounts: [13, 1, 22], data: [3, 47, 67, 220, 85, 0, 0, 0, 0] }, CompiledInstruction { program_id_index: 5, accounts: [9], data: [228, 69, 165, 46, 81, 203, 154, 29, 64, 198, 205, 232, 38, 8, 113, 226, 75, 217, 73, 196, 54, 2, 195, 63, 32, 119, 144, 237, 22, 163, 82, 76, 161, 185, 151, 92, 241, 33, 162, 169, 12, 255, 236, 125, 248, 182, 138, 205, 6, 155, 136, 87, 254, 171, 129, 132, 251, 104, 127, 99, 70, 24, 192, 53, 218, 196, 57, 220, 26, 235, 59, 85, 152, 160, 240, 0, 0, 0, 0, 1, 64, 66, 15, 0, 0, 0, 0, 0, 236, 163, 244, 219, 182, 110, 132, 120, 247, 234, 114, 245, 29, 177, 68, 129, 1, 26, 239, 150, 135, 156, 80, 9, 43, 31, 124, 66, 232, 17, 65, 105, 47, 67, 220, 85, 0, 0, 0, 0] }], []]
```

With revert:

```
err: Some(InstructionError(5, Custom(6001)))
top level instructions length: 7
inner_instructions length:  6
inner_instructions: [[], [], [CompiledInstruction { program_id_index: 7, accounts: [6], data: [21, 7, 0] }, CompiledInstruction { program_id_index: 3, accounts: [0, 2], data: [0, 0, 0, 0, 240, 29, 31, 0, 0, 0, 0, 0, 165, 0, 0, 0, 0, 0, 0, 0, 6, 221, 246, 225, 215, 101, 161, 147, 217, 203, 225, 70, 206, 235, 121, 172, 28, 180, 133, 237, 95, 91, 55, 145, 58, 140, 245, 133, 126, 255, 0, 169] }, CompiledInstruction { program_id_index: 7, accounts: [2], data: [22] }, CompiledInstruction { program_id_index: 7, accounts: [2, 6], data: [18, 175, 177, 183, 253, 19, 201, 252, 234, 149, 132, 88, 165, 235, 169, 158, 75, 88, 43, 207, 179, 76, 104, 59, 201, 97, 63, 49, 156, 217, 175, 28, 27] }], [], [], [CompiledInstruction { program_id_index: 23, accounts: [7, 19, 22, 14, 13, 20, 21, 11, 18, 16, 12, 17, 15, 24, 2, 1, 0], data: [9, 64, 66, 15, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }, CompiledInstruction { program_id_index: 7, accounts: [2, 20, 0], data: [3, 64, 66, 15, 0, 0, 0, 0, 0] }, CompiledInstruction { program_id_index: 7, accounts: [13, 1, 22], data: [3, 9, 200, 62, 82, 0, 0, 0, 0] }, CompiledInstruction { program_id_index: 5, accounts: [9], data: [228, 69, 165, 46, 81, 203, 154, 29, 64, 198, 205, 232, 38, 8, 113, 226, 75, 217, 73, 196, 54, 2, 195, 63, 32, 119, 144, 237, 22, 163, 82, 76, 161, 185, 151, 92, 241, 33, 162, 169, 12, 255, 236, 125, 248, 182, 138, 205, 6, 155, 136, 87, 254, 171, 129, 132, 251, 104, 127, 99, 70, 24, 192, 53, 218, 196, 57, 220, 26, 235, 59, 85, 152, 160, 240, 0, 0, 0, 0, 1, 64, 66, 15, 0, 0, 0, 0, 0, 236, 163, 244, 219, 182, 110, 132, 120, 247, 234, 114, 245, 29, 177, 68, 129, 1, 26, 239, 150, 135, 156, 80, 9, 43, 31, 124, 66, 232, 17, 65, 105, 9, 200, 62, 82, 0, 0, 0, 0] }]]
```

It looks like the last top-level instruction doesn’t have a corresponding empty `inner_instruction` entry. This feels like a bug to me, because without the lengths of the two arrays being equal, one cannot assume each entry in inner_instructions maps to a top-level instructions. It is expected behavior?

#### Proposed Solution

Only needs a solution if this behavior is unexpected.

**Comment by CriesofCarrots** [comment]
What did you revert?

**Comment by buffalojoec** [comment]
> This feels like a bug to me, because without the lengths of the two arrays being equal, one cannot assume each entry in inner_instructions maps to a top-level instructions. It is expected behavior?

This is expected behavior, depending on which instructions are being sent in the transaction.

Inner instructions are instructions invoked by each executing program to other programs, specifically Cross-Program-Invocations (CPI).

So you have a list of `instructions` in the transaction's message, which is a list that was created by whoever created the transaction. The runtime will build out the transaction's metadata (`meta`), which contains additional information about the transaction, including all CPIs conducted by each instruction.

This is why inner instructions have `index` and `stack_height` values that correspond to which instruction in the message's instructions list (`index`) the CPI occurred from, and what depth the CPI stack reached during said CPI (`stack_height`).

> It looks like the last top-level instruction doesn’t have a corresponding empty inner_instruction entry.

Then I'll bet it's the _second-last_ instruction where your error occurs. The last one never gets simulated before the transaction rolls back.

In your case it sounds like you just so happen to have a list of instructions, each of which all conduct at least one CPI. If you add one that doesn't CPI, like system instructions, you'll see this is expected.

**Comment by fabioberger** [comment]
Thanks a lot for the detailed response @buffalojoec 🙏  That makes complete sense and I'll write my logic to expect this behavior 🙏  It's good to know that I can expect the missing entries to always be at the end of the `inner_instructions` array (given they stop being generated whenever an instruction reverts).
