### ISSUE TITLE
SVM: `TransactionLoadResult` is causing SVM to depend on `accounts_db`

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#35095]
#### Problem
`TransactionLoadResult` is causing `SVM` to depend on `accounts_db`. This needs to be reworked to break `SVM` dep on `accounts_db`. 

#### Proposed Solution
The `TransactionLoadResult` type uses `NonceFull` which is also part of `accounts_db`. These structs need to be either moved to SDK or SVM. Need more analysis on how to cleanly isolate this.

**Comment by pgarg66** [comment]
Likely fixed by https://github.com/solana-labs/solana/pull/35183

**Comment by dmakarov** [comment]
Yes, accounts-db is no longer in `[dependencies]` of `svm/Cargo.toml`. It seems this issue can be closed.
