### ISSUE TITLE
SVM: `MatchAccountOwnerError` is causing `SVM` to depend on `accounts_db`

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#35096]
#### Problem
`MatchAccountOwnerError` is defined in `accounts_db`. This is causing SVM to depend on `accounts_db`. We need to break this dependency.

#### Proposed Solution
`MatchAccountOwnerError` seems more integral to `accounts_db`. The `SVM` dependency originates from the `TransactionProcessingCallback` trait definition, where `MatchAccountOwnerError` is a return type. The trait could define its custom return type, and trait implementors can map `MatchAccountOwnerError` to trait's return type.

Alternatively, we can move `MatchAccountOwnerError` to SVM once the SVM is split as its own crate. This means `accounts-db` will depend on SVM crate.

**Comment by MOORETOKEN** [comment]
firebase firestore:databases:create newsolrpcdb \
--location=europe-west \
[--delete-protection DELETE_PROTECTION_ENABLEMENT]
