### ISSUE TITLE
SVM: Update `account_loader.rs` unit tests to remove `accounts-db` deps

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#35147]
#### Problem
The unit tests in `account_loader.rs` depend on a few `accounts-db` structs. It'll be nice to have that dependency removed.
```
solana_accounts_db::{accounts::Accounts, accounts_db::AccountsDb, ancestors::Ancestors}
```

#### Proposed Solution
The dependency is mainly needed due to `get_account_shared_data` impl in `TestCallbacks`. Explore if the interface can be mocked, instead of using the actual `accounts-db` structs.

**Comment by MKokeshi** [comment]
Assuming the above questions are addressed, here are some general approaches to consider:

1. Partial Mocking (if applicable):

If only specific data or methods from AccountsDb and Ancestors are required, create mock objects that replicate their behavior for those aspects. Use the mocking library's capabilities to define expected calls and return values. This can keep the dependency to a minimum while maintaining testing coverage.

2. Stubbing (if feasible):

Create simplified implementations of AccountsDb and Ancestors that provide only the essential functionality needed for the tests. If the tests don't need complex interactions with these structures, stubs can be sufficient and eliminate the actual dependency.

3. Test Doubles (generic approach):

Choose a mock or stub approach based on the required level of control and complexity. Consider the trade-offs between ease of creation and flexibility when making this decision.

4. Dependency Injection (for future considerations):

If appropriate for your overall project structure, explore injecting AccountsDb and Ancestors as dependencies into TestCallbacks. This can improve testability and separation of concerns, but might require refactoring existing code.
Example (illustrative, adjust based on your specifics):

```
// Mocking with the `mockall` library:
use mockall::*;

#[automock]
trait MockAccountsDb {
    fn get_account_shared_data(&self, pubkey: &Pubkey) -> Option<SharedData>;
}

// Test implementation:
pub fn test_account_loader() {
    let mock_accounts_db = MockAccountsDb::new();
    let test_callbacks = TestCallbacks::with_accounts_db(mock_accounts_db);

    // Set up mock expectations and behavior
    mock_accounts_db.expect_get_account_shared_data(|pubkey| {
        // Return expected data based on pubkey
    }).once();

    // Run the actual test logic using the test_callbacks
}
```
