### ISSUE TITLE
Failed to start validator: PoH is slower than cluster target tick rate! 

### ISSUE THREAD

**Issue by TehnobitSystems** [solana-labs/solana#35205]
Hello. 
We want to setup a Solana RPC Node, but after snapshot download this error appears:
 ```
INFO  solana_entry::poh] Running 800000 hashes...
 ERROR solana_validator] Failed to start validator: "PoH is slower than cluster target tick rate! mine: 567637293 cluster: 400000000."
```
Please tell me which side is the error? RAM, cores, drive?
We need a simple node only for for the RPC

**Comment by CriesofCarrots** [comment]
We don't provide technical support on github. You can try getting advice on [Discord](https://solana.com/discord), #validator-beginners channel
