### ISSUE TITLE
Possible Incompleteness

### ISSUE THREAD

**Issue by YichiZhang0613** [solana-labs/solana#35368]
In solana/core/src/banking_stage/transaction_scheduler/prio_graph_scheduler.rs, I think the code should check whether thread_set is empty before use thread_set  as comments mentioned.
```rust
    /// Panics if the `thread_set` is empty.
    fn select_thread(
        thread_set: ThreadSet,
        batches_per_thread: &[Vec<SanitizedTransaction>],
        in_flight_per_thread: &[usize],
    ) -> ThreadId {
        thread_set
            .contained_threads_iter()
```

**Comment by steviez** [comment]
CC @apfitzge

**Comment by apfitzge** [comment]
Will double check, but believe it's the case that the interface on TAAL we use to get the thread set will never return an empty set, it either returns Some non-empty set or None.

**Comment by apfitzge** [comment]
I created #35388 to add a couple of clarifying comments. I don't see an issue in the use of this function, we check the thread-set is non-empty before calling it - see below.

Copying relevant code slice:
```rust
    pub(crate) fn try_lock_accounts<'a>(
        &mut self,
        write_account_locks: impl Iterator<Item = &'a Pubkey> + Clone,
        read_account_locks: impl Iterator<Item = &'a Pubkey> + Clone,
        allowed_threads: ThreadSet,
        thread_selector: impl FnOnce(ThreadSet) -> ThreadId,
    ) -> Option<ThreadId> {
        let schedulable_threads = self.accounts_schedulable_threads(
            write_account_locks.clone(),
            read_account_locks.clone(),
        )? & allowed_threads;
        (!schedulable_threads.is_empty()).then(|| {
            let thread_id = thread_selector(schedulable_threads);
            self.lock_accounts(write_account_locks, read_account_locks, thread_id);
            thread_id
        })
    }
```

`thread_selector` is the argument that corresponds to `PrioGraphScheduler::select_thread`. As you can see, we only call it if `schedulable_threads` is non-empty.

I had considered to make `thread_selector` take in a possibly empty set, returning a `Option<ThreadId>`, but felt that fn signature did not communicate the fact we **always** want to choose a thread if at least one is available.

**Comment by apfitzge** [comment]
@tao-stones thoughts on my above comment? If you think it's more straight-forward to just let `thread_selector` take a possibly empty set, it seems like it's any easy change.

**Comment by tao-stones** [comment]
imho, #35388 should be sufficient given `select_thread` is a private to `prio_graph_scheduler`. If it even become public, return a Option<> might be safer.
