### ISSUE TITLE
Large Stack Variables Error in Solana-cli 1.18.1 and Anchor 0.29.0

### ISSUE THREAD

**Issue by julbh** [solana-labs/solana#35387]
This is an error while building Anchor project. `anchor build`
But it was built successfully.
I'm not sure if it's because of version compatibility.

`Error: Function _ZN112_$LT$solana_program..instruction..InstructionError$u20$as$u20$solana_frozen_abi..abi_example..AbiEnumVisitor$GT$13visit_for_abi17h2f3c0d426ad8ac9bE Stack offset of 4584 exceeded max offset of 4096 by 488 bytes, please minimize large stack variables`

solana-cli 1.18.1
anchor 0.29.0
rustc 1.76.0

**Comment by julbh** [comment]
This solution(#35003) did not resolve my problem.

**Comment by joncinque** [comment]
It looks like your question was addressed in the anchor issue, so closing this one. You need to use at least 1.18.2. Please ask a question on the Solana Stack Exchange if you still have issues https://solana.stackexchange.com/
