### ISSUE TITLE
Can we mark this repo as deprecated, so we don't make PRs here instead of anza-xyz/agave?

### ISSUE THREAD

**Issue by mikemaccana** [solana-labs/solana#35497]
#### Problem
 
 I forget things and sent a PR to here rather than to https://github.com/anza-xyz/agave. 

Presumably other will to. 

#### Proposed Solution

[Archive the repo](https://github.blog/2017-11-08-archiving-repositories/) and change README.txt to: 

> # Moved to [anza-xyz/agave](https://github.com/anza-xyz/agave)

**Comment by CriesofCarrots** [comment]
Thanks, @mikemaccana , I get your concerns. However, as per the [transition schedule described here](https://github.com/anza-xyz/agave/wiki/Agave-Transition), we're still making releases from this repository through the v1.18 cycle (releases that are identical to the agave releases in all but name). Therefore, we can't archive the repo yet, and it makes our lives easier to keep as many of the files the same as possible. But I'll explore whether updating the README.md makes sense.

**Comment by mikemaccana** [comment]
No worries, thanks @CriesofCarrots also you have an amazing username!
