### ISSUE TITLE
Stack Size increased with 1.18.x (platform-tools)

### ISSUE THREAD

**Issue by adrena-orex** [solana-labs/solana#35543]
#### Problem

Programs built with solana 1.18.x experience new stack size related issues.

####  Details

We started having issues after migrating from solana `1.16.16` and anchor `0.28.0` to solana `1.18.11` and anchor `0.29.0`.

Started getting messages when building informing us of our ix using too much stack, i.e:
```bash
Error: Function _ZN145_$LT$adrena..instructions..add_custody..AddCustody$u20$as$u20$anchor_lang..Accounts$LT$adrena..instructions..add_custody..AddCustodyBumps$GT$$GT$12try_accounts17h13b564b67762dd31E Stack offset of 4232 exceeded max offset of 4096 by 136 bytes, please minimize large stack variables
```

Then at runtime:
```bash
'Program 76FLzSMB8xPPt2y4ZKWeMiQBnXnqvU2xyJtc4PogsxMa consumed 2523 of 200000 compute units',
'Program 76FLzSMB8xPPt2y4ZKWeMiQBnXnqvU2xyJtc4PogsxMa failed: Access violation in stack frame 5 at address 0x200005ff0 of size 8'
```

Hotfixed the issue by splitting IXs and migrating accounts to use `zero_copy`.

We have noticed that the `init` of accounts takes a lot of stack, 800 bytes+. Can't have more than 3 accounts to `init` within the same instruction atm.

Note: Even when testnet tests works, it may still fail on devnet.

**Setup:**

```
orex> solana --version
solana-cli 1.18.11 (src:c78a9720; feat:3469865029, client:SolanaLabs)
orex> anchor --version
anchor-cli 0.29.0
orex> solana cluster-version                                                                                             
1.18.12
orex> solana config get
Config File: /Users/orex/.config/solana/cli/config.yml
RPC URL: https://api.devnet.solana.com 
WebSocket URL: wss://api.devnet.solana.com/ (computed)
Keypair Path: /Users/orex/.config/solana/id.json 
Commitment: processed
```
Using https://github.com/anza-xyz/platform-tools/releases v1.41 to compile.

#### Related

Found an issue [here](https://github.com/anza-xyz/agave/issues/252) talking about platform tools growing stack usage.

#### Proposed Solution

**Comment by code-brewer** [comment]
I have the same issue with 1.18.10 . Any solution to this?

**Comment by viettriit2110** [comment]
How to fix it?
