### ISSUE TITLE
Validator stops running Poh when it doesn't see itself in the leader scheduler, but set_leader() depends on PoH

### ISSUE THREAD

**Issue by carllin** [solana-labs/solana#3558]
#### Problem
When a validator sees it no longer has a position in the leader scheduler, it stops PoH. However, set_leader() which updates the current leader in ClusterInfo is called in replay_stage and depends on PoH ticking. Thus this potentially breaks anything that depends on knowing the current leader from ClusterInfo. For instance tpu forwarder depends on this leader information.

@sagar-solana, @rob-solana @pgarg66

**Comment by rob-solana** [comment]
sounds like we could just go ahead and leave PoH ticking without caching the ticks

**Comment by pgarg66** [comment]
This issue can also prevent a low staked node from forwarding client transactions to the right leader. The ```next_slot_leader()``` uses poh tick height to calculate the next slot, and looks up the leader schedule cache to identify the leader. If the stake for current node is low enough that it never gets into the leader schedule, its tick will not progress. This will cause ```next_slot_leader()``` to return leader for the incorrect slot.
