### ISSUE TITLE
error: package `solana-program v2.0.0` cannot be built because it 

### ISSUE THREAD

**Issue by MaeThird** [solana-labs/solana#35593]
#### Problem
use `solana-program = "2.0.0"` to compile a very simple custom program failed with `ackage solana-program v2.0.0 cannot be built because it requires rustc 1.75.0 or newer, while the currently active rustc version is 1.72.0-dev` 
the output of `cargo-build-sbf --version`  is `solana-cargo-build-sbf 1.18.5  platform-tools v1.39  rustc 1.72.0`

I mean where i can find the toolchain supporting rustc 1.75.0 or above?

**Comment by mehdimahro** [comment]
Hi friends, I want to start a small project with your help to test my students. Anyone willing to cooperate, reply to this direct email.
