### ISSUE TITLE
 extra entry found: "._genesis.bin" Regular

### ISSUE THREAD

**Issue by hon94csl** [solana-labs/solana#35629]
#### solana-test-validator Error
I am running solana-test-validator on a mac m2 macOs 13.2.1 system with the following error.
`Error: failed to start validator: Failed to create ledger at test-ledger: io error: Error checking to unpack genesis archive: Archive error: extra entry found: "._genesis.bin" Regular`

**Comment by pandaiolo** [comment]
For whoever finds this issue ticket, and have a hard time figuring things out, I found [from that comment](https://github.com/solana-labs/solana/issues/28899#issuecomment-1694152935) that you need to install `gnu-tar` to make this work.

```
brew install gnu-tar
```

Then, check that `tar` is using the brew version
```
which tar
```

If not, update your `~/.zshrc` with `export PATH=...` with value shown in the brew install step above. (and then `source ~/.zshrc`)
