### ISSUE TITLE
AccountsDB is taking a long time to squash

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#3562]
#### Problem

AccountsDB is taking a long time to squash.

#### Proposed Solution

- [x]  AppendVec's should only contain a single Fork, therefore when a thread requests an AppendVec to write to, a new AppendVec will be allocated for that Fork if one isn't available.  AppendVec's should contain a counter of how many accounts are in the vec.

- [x] `AccountsDB::accounts_index: HashMap<Pubkey, Vec<Fork,AccountInfo>>`.  A pubkey for an account will point to a vector of all the forks its in.

- [x] `AccountsDB::roots: HashSet<Fork>`, a set of root forks.

- [x] `AccountDB::add_root(root: Fork)`, just adds the root to roots

- [x]  `AccountsDB::purge_fork(pruned_forks: &Vec<Fork>)`, remove the AppendVecs.  

- [x] `AccountsDB::load(pubkey: Pubkey, ancestors: &HashMap<Fork, usize>) -> Option<Account>`, load the max fork in the vector that is in ancestor set or the root set.

- [x] `AccountdsDB::update_index(pubkey: Pubkey, fork: Fork, account: &AccountInfo)`, store the account, but when appending to the vector, remove any entries for older roots.  We only need to store 1 oldest entry that is in the `AccountsDB:roots` set. For any removed roots, decrement the AppendVec's account counter.  If that counter is 0, free the AppendVec.  When the last AppendVec for the Fork is removed, remove the fork from roots.

AccountsDB::roots HashSet grows by one entry per slot.  4mb in 6 days.  Load should have 1 page fault to get to the vector, then a quick scan against the ancestor set (small), and the root set which might fault as well if it gets large enough.
 
tag: @sakridge @sambley  @carllin

**Comment by sambley** [comment]
@aeyakovenko, the slowness that is being seen with the current squash is with updating the index from the parent forks (1M+ accounts) to make this a root fork. The slowness does not seem to be due to memory or page faults and there are no appendvec operations during the squash operation. The index updates seem to be down to around 200+ms with the latest optimizations, its not clear to me whether the index operations would get eliminated with this new approach?

**Comment by aeyakovenko** [comment]
@sambley, in this design there is no squash or append index when a new root fork is added.  Just the add_root method.

**Comment by sambley** [comment]
@aeyakovenko, think I get an idea of your proposal here that could be faster than the current implementation. Let me know if you would like me to work on this one.

**Comment by aeyakovenko** [comment]
@sambley, thank you!  Please go  ahead

**Comment by aeyakovenko** [comment]
@sambley, @sakridge is working on the `update_index` changes.  it looks like `walk` is really slow in the current implementation.  I think placing forks into the same AppendVec could be a separate pr
