### ISSUE TITLE
solana-test-validator error, expects GNU-tar: proposed solution!

### ISSUE THREAD

**Issue by abhijayrajvansh** [solana-labs/solana#35648]
## Problem

running `solana-test-validator` on macOS (with apple silicon or arm64) fails with the following error:

```bash
Ledger location: test-ledger
Log: test-ledger/validator.log
Error: failed to start validator: Failed to create ledger at test-ledger: io error: Error checking to unpack genesis archive: Archive error: extra entry found: "._genesis.bin" Regular
```

**reason**: the GNU `tar` program is not compatible with the BSD `tar` program that comes pre-installed. 
this is why we're using: [gnu tar installation in .travis.yml](https://github.com/solana-labs/solana/blob/master/.travis.yml#L32)

```yml
- brew install gnu-tar
- PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"
```

and here's the problem: this (`/usr/local/opt/gnu-tar/libexec/gnubin`) executable path is only valid for Intel-based macs (x86_64) and not for macs with apple silicon (arm64) chipset. by default, on apple silicon macs, executables are stored in a different location.

### less ideal solution:
a local fix: Install the gnu tar program using brew and export its executable path in your `.zshrc` file.

#### macOS with apple silicon (arm64):

```bash
brew install gnu-tar
# Put this in ~/.zshrc 
export PATH="/opt/homebrew/opt/gnu-tar/libexec/gnubin:$PATH"
```

#### intel-based macOS (x86_64):

```bash
brew install gnu-tar
# Put this in ~/.zshrc 
export PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"
```

### Ideal Solution:
We can differentiate between Intel-based and Apple Silicon-based macOS directly in the `.travis.yml` file and set the PATH accordingly.

**Comment by Jac0xb** [comment]
> ## Problem
> running `solana-test-validator` on macOS (with apple silicon or arm64) fails with the following error:
> 
> ```shell
> Ledger location: test-ledger
> Log: test-ledger/validator.log
> Error: failed to start validator: Failed to create ledger at test-ledger: io error: Error checking to unpack genesis archive: Archive error: extra entry found: "._genesis.bin" Regular
> ```
> 
> **reason**: the GNU `tar` program is not compatible with the BSD `tar` program that comes pre-installed. this is why we're using: [gnu tar installation in .travis.yml](https://github.com/solana-labs/solana/blob/master/.travis.yml#L32)
> 
> ```yaml
> - brew install gnu-tar
> - PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"
> ```
> 
> and here's the problem: this (`/usr/local/opt/gnu-tar/libexec/gnubin`) executable path is only valid for Intel-based macs (x86_64) and not for macs with apple silicon (arm64) chipset. by default, on apple silicon macs, executables are stored in a different location.
> 
> ## Proposed Solution
> ### less ideal solution:
> a local fix: Install the gnu tar program using brew and export its executable path in your `.zshrc` file.
> 
> #### macOS with apple silicon (arm64):
> ```shell
> brew install gnu-tar
> # Put this in ~/.zshrc 
> export PATH="/opt/homebrew/opt/gnu-tar/libexec/gnubin:$PATH"
> ```
> 
> #### intel-based macOS (x86_64):
> ```shell
> brew install gnu-tar
> # Put this in ~/.zshrc 
> export PATH="/usr/local/opt/gnu-tar/libexec/gnubin:$PATH"
> ```
> 
> ### Ideal Solution:
> We can differentiate between Intel-based and Apple Silicon-based macOS directly in the `.travis.yml` file and set the PATH accordingly.

Thank you for this solution definitely needs to be fixed
