### ISSUE TITLE
Buy tokin

### ISSUE THREAD

**Issue by spaceidco** [solana-labs/solana#35693]
🚀 Next Big Meme Token Alert on Solana! 🐶🔥
Get ready for the hottest new trend!
🔗  Dextools : https://www.dextools.io/app/en/solana/pair-explorer/Ex66A38Zn7wMZQZxHnyQra68UDQFop5ztsuQnpLNZ3K4?t=1731928168082

🌐 Jump in now before it skyrockets! 🚀
#MemeToken #Solana![IMG-20241118-WA0361.jpg](https://github.com/user-attachments/assets/e7d7f227-4a7a-48a2-bf99-8a8c0d16a511)

**Comment by samrat10350** [comment]
I am also going to buy this coin.. I also heard about this. It will pump very soon.

**Comment by mrakib10105** [comment]
Boom
