### ISSUE TITLE
cargo build-sb fails with Failed to install platform-tools: HTTP status client error (404 Not Found)  error

### ISSUE THREAD

**Issue by farawaystar** [solana-labs/solana#35719]
when running cargo build-sbf I get this error
ERROR cargo_build_sbf] Failed to install platform-tools: HTTP status client error (404 Not Found) for url (https://github.com/anza-xyz/platform-tools/releases/download/v1.42/platform-tools-osx-x86_64.tar.bz2)

tried solutions but didn't work:
-> reinstalling latest solana version from Anza: sh -c "$(curl -sSfL https://release.solana.com/stable/install)"
-> clearing cache using cargo clean
-> cargo update
-> rustup update
-> ensuring cargo.toml file has same solana version and my CLI
-> cargo build-bpf also gives the same error

help greatly appreciated

**Comment by mixbe** [comment]
How solve this issue,pls

**Comment by mixbe** [comment]
Ok, I used  **agave-install init 1.18.21**  worked for me.
