### ISSUE TITLE
Fix Local Cluster test start_and_exit_with_config 

### ISSUE THREAD

**Issue by sagar-solana** [solana-labs/solana#3592]
#### Problem

#3591 has added `local_cluster::test::test_local_cluster_start_and_exit_with_config` to ignore.

#### Proposed Solution

Figure out why the test is flaky and re-enable it. Primary suspect is the fact that the test exits immediately and so the replicator isn't able to setup its account by the time teardown has started. 
Make sure LocalCluster returns only once all configured entities are up and running. Might need a restructure of where gossip service is started within replicators

**Comment by sakridge** [comment]
Want to just set 0 replicators in this test for now?

**Comment by sagar-solana** [comment]
Oh it got merged under me, I'll try to take a stab at this when I can.
