### ISSUE TITLE
Testnet participation document is out of sync with V12 branch

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#3603]
#### Problem
The document currently focuses on V12 branch, but some of the commands (e.g. solana-gossip) do not exist on V12 branch. Also, whenever a new tag is released from V12 branch, the document goes out of sync, and needs to be updated.

#### Proposed Solution
Rework the document organization and maintain per branch information.

**Comment by garious** [comment]
@pgarg66, regarding the tag, we use this trick in the Getting Started chapter:

```bash
$ TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
$ git checkout $TAG
```

https://solana-labs.github.io/book-edge/getting-started.html\

**Comment by mvines** [comment]
The root problem is that there's no version of the testnet doc in the v0.12 branch at all.

**Comment by mvines** [comment]
Mostly obsolete now as we can wait for 0.13 to be released early next week.  Updating the doc to include the git tag trick above could still be done before closing this issue though

**Comment by danpaul000** [comment]
The instructions for this document have the user pulling a release via wget, not cloning the repo, which would be needed for getting the latest release tag.  Should I add a step to do:
1) Clone the repo
2) Find the tag using the trick above
3) Use that tag to pull the correct released binaries/tarball

That seems a little circuitous to me, but not a big issue.

**Comment by mvines** [comment]
Yeah that seems a little too hard.  Let's just direct the user to https://github.com/solana-labs/solana/releases and ask them to "use the latest release tag"
