### ISSUE TITLE
Banks can receive votes for "future" slots

### ISSUE THREAD

**Issue by carllin** [solana-labs/solana#3634]
#### Problem
Votes for slots M > N to a bank N should fail.

#### Proposed Solution
possible solutions:

* vote transactions should set their last_blockhash to the last blockhash of the bank they're voting for (needs enforcement, right?)
* vote program should verify that bank state is at least N (syscall #4246), (opens the door to censorship?)

@aeyakovenko @sagar-solana

**Comment by rob-solana** [comment]
fixed in #4381
