### ISSUE TITLE
CI for multinode test

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#364]
We are a bit in the blind with the status of multinode performance.  We need a test that runs on google cloud or aws with a big pile of nodes.  we should have a quota of 20 on google cloud, and it seems easy to increase there. We can base something on these terrible scripts #329

**Comment by aeyakovenko** [comment]
@sakridge @garious I think on every master update?   @sakridge has a script to generate a performance graph. It would be awesome to post it on every pr or master update

**Comment by mvines** [comment]
@sakridge, can you share that script somewhere please

**Comment by sakridge** [comment]
@mvines it's checked in scripts/perf-plot.py

**Comment by mvines** [comment]
Bumping to 0.8.0 as this does not block 0.7.0

**Comment by aeyakovenko** [comment]
Fixed with dynamic test
