### ISSUE TITLE
Refactor array expansion in testnet CI scripts

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#3646]
#### Problem

A few array expansions in ci/testnet-manager.sh and ci/testnet-deploy.sh are failing shellcheck, even though we are getting the desired behavior.  Shellcheck warnings for these lines is suppressed.

#### Proposed Solution

Remove the shellcheck ignore directives from those files and refactor the array expansion to meet its standards, and ensure no quotation marks are printed/displayed as a result of the expansion, as this will break the script being called at those lines.

**Comment by pgarg66** [comment]
https://github.com/solana-labs/solana/pull/3641

**Comment by danpaul000** [comment]
Punting on fixing this issue as it is very low priority.  Shell check bypasses are all over the place, and not worth addressing until we decide we want/need to do a larger refactor of all of our shell scripts.
