### ISSUE TITLE
solana-fullnode: Consider making -l mandatory 

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#367]
Currently if `-l` is not provided on the command-line, a default is supplied:
https://github.com/solana-labs/solana/blob/7fe1fd2f957697b2a3f0b91215b4984a5411d3a1/src/bin/fullnode.rs#L111

Is this really the behaviour we want?

**Comment by garious** [comment]
The default allows you to do single node testing without the extra step of generating a config file first. Just trying to let simple things be simple. Did the default trip you up in the multinode workflow?
