### ISSUE TITLE
solana-web3.js: adapt to Transaction format changes on master branch

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#3681]
solana-web3.js has fallen behind the recent Transaction changes on master, such as the  removal of the fee field but there's probably more churn to adapt to as well.

cc: https://github.com/solana-labs/solana-web3.js/issues/234

**Comment by garious** [comment]
The binary format is now described by this test: https://github.com/solana-labs/solana/blob/master/sdk/src/transaction.rs#L352

214 bytes!

**Comment by mvines** [comment]
Done
