### ISSUE TITLE
New 0.12 releases are not pushing to crates.io

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#3682]
#### Problem

Solana repo releases after v0.12.0 have not been appearing on crates.io.  Investigate why this upload is failing.

**Comment by mvines** [comment]
The failure from the v0.13.0 crates.io publish attempt: https://buildkite.com/solana-labs/solana-secondary/builds/2194#8ea1031e-1cda-4628-afc7-2d04aafcf75d
