### ISSUE TITLE
Change testnet-perf deployment to use a fixed tag

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#3688]
Right now we deploy testnet-perf with the latest tag on the stable release channel.  This is nice an automated, however for the time being we'd like a little more control over the tag used.  

Instead let's encode the tag to use for testnet-perf in `ci/testnet-manager.sh`, so it can be manually bumped as desired by (only) modifying `ci/testnet-manager.sh` in the master branch.   The deployment of other testnets should remain the same though.

**Comment by danpaul000** [comment]
Should we redefine the vars here: https://github.com/solana-labs/solana/blob/master/ci/testnet-manager.sh#L87-L90

Or would it be better to back up one step and hardcode in channel-info, where the stable channel vars are defined (And echoed into the logs), here: https://github.com/solana-labs/solana/blob/master/ci/channel-info.sh#L87-L89

**Comment by mvines** [comment]
That location in testnet-manager.sh looks right to me, but split the case into `testnet` and `testnet-perf` -- we can keep `testnet` using `$STABLE_CHANNEL_LATEST_TAG`

**Comment by danpaul000** [comment]
Ok, will do thanks.
