### ISSUE TITLE
Change testnet-perf to run on-demand

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#3691]
Rather than running testnet-perf 24/7 it'll suit our needs better if there existed an [easy button](https://youtu.be/3YmMNpbFjp0) to turn it on/off on demand.   This _button_ would mostly be used non-devs.

I think two custom buildkite pipelines should be sufficient for this purpose, one pipeline to turn on and one pipeline to turn off where the user can click the "New Build" link.  Under the hood these pipelines should just route into `ci/testnet-manager.sh`.

**Comment by danpaul000** [comment]
Created two new pipelines, one to start, one to stop.  Currently default branch is v0.11, but this could be changed to master or manually set to a desired branch whenever.  Just go to the pipeline and click "New Build" and use default options.

https://buildkite.com/solana-labs/testnet-perf-start-on-demand
https://buildkite.com/solana-labs/testnet-perf-stop-on-demand

Let me know what you think.

**Comment by mvines** [comment]
Cool those buildkite pipelines looks super.

I just realized there's an additional wrinkle here.  We'd want the existing testnet-perf pipelines,
[testnet-perf sanity-or-restart](https://buildkite.com/solana-labs/testnet-management/settings/schedules/28fbffbf-1eb3-4401-bb53-baa65c436d96) and [testnet-perf restart every 3 hours](https://buildkite.com/solana-labs/testnet-management/settings/schedules/935466c2-a9e6-4ec7-b4ea-97bf8f866762), to run during the window that testnet-perf is enabled.   

So seems like we'd need somewhere to stuff a bit to indicate that testnet-perf is expected to be running.  `ci/testnet-manager.sh` always runs on the same machine so I guess we could use the buildkite agent's home directory to store that bit.  This feels a little gross though.  :nauseated_face:

**Comment by danpaul000** [comment]
Might be able to use the artifact feature to pass persistent state between builds  https://buildkite.com/docs/pipelines/artifacts

**Comment by mvines** [comment]
Heh, almost!  Artifacts are convenient to share state between steps in the same job, but I don't think there's any support for sharing artifacts between multiple jobs.

**Comment by danpaul000** [comment]
Added lockfile and some logic to handle it to each of the on-demand pipelines, as well as an option to override the lockfile presence.
