### ISSUE TITLE
Package solana-fullnode as a Linux snap

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#372]
We'd like a way to easily distribute (and automatically update) `solana-fullnode` as widely as possible.  Currently Linux users must have the full rust/cargo toolchain installed which is a barrier to entry, and makes #307 and #364 a little tougher than ideal (there should be no need to build `solana-fullnode`  *again* when deploying it to a testnet or for CI testing.

Snaps seam to fit the bill nicely: https://snapcraft.io/
We can have nightly updates for a testnet setup, multiple release channels, and snaps can be installed explicitly/manually for CI testing.

Before proceeding further, we should confirm that CUDA is workable from within the confined environment of a snap.  https://github.com/anonymouse64/cuda-samples-snap seems to imply this is possible.

* [x] Basic snap infra
* [x] CUDA snap support
* [x] Document snap usage in README

**Comment by garious** [comment]
🥇
