### ISSUE TITLE
Drone is not generic

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#3722]
#### Problem

Drone doesn't implement the generic interface described by the book. Instead, Drone and RemoteVoteSigner has application-specific code in their clients.

#### Proposed Solution

A Drone client should send a serialized Message struct, not an airdrop-specific message. The server should parse that instance and if valid, sign it and return the signature. For instance, the thing currently called a drone should be called a Faucet and should expect `SystemInstruction::Transfer` in its `Message`. Likewise, the RemoteVoteSigner should be a drone server that signs vote messages.

**Comment by mvines** [comment]
@garious - this doesn't seam particularly urgent, any reason you added it to 0.15?

**Comment by garious** [comment]
It's not urgent. It's just that the book is supposed to reflect what's currently implemented. It's a little sloppy to keep pushing this cleanup out, but it's not blocking anything.

**Comment by garious** [comment]
Drone is now just a design pattern.  What was called a drone is now called a faucet.
