### ISSUE TITLE
Scripts in multinode-demo don't work if $PWD is not repo root

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#3730]
#### Problem

setup.sh and client.sh require the shell to be in the repo root.  These scripts should locate themselves and the things they call independent of PWD.

#### Proposed Solution

Refactor common.sh to find neighboring scripts based on repo structure, not from the dir the calling script was launched from.

**Comment by mvines** [comment]
Just FYI, the multinode-demo/ scripts ideally would be reduced in size and eventually deleted so I wouldn't bother investing too much love into them.

**Comment by mvines** [comment]
Fixed by #3831
