### ISSUE TITLE
Influx database size is growing out of bound

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#3777]
#### Problem
Influx Database size grows unless the database is dropped and recreated. Some testnets may require more historical data than others. But, with move towards using Influx Cloud, the larger databases cost more money. Need a solution to configure testnet with maximum depth of history (or database size), and drop data that's older than the depth.

#### Proposed Solution
1. Add configuration parameter to testnet scripts
2. Find a way to tail drop older data than the maximum depth
3. Option to drop database when a dev testnet is torn down (the user can manually drop it by calling init_metrics, but nobody does)
4. Periodically scan database server and kill databases older than a certain time.

**Comment by mvines** [comment]
I thought we setup a reasonable retention policy for each of the Influx databases.   I guess that's not working for some reason.

https://www.influxdata.com/blog/simplifying-influxdb-retention-policy-best-practices/

**Comment by pgarg66** [comment]
Maybe we need to reduce the retention time...
Or, our current plan does not allocated enough disk space

**Comment by danpaul000** [comment]
Rate limiting should have addressed this.  Additional/on-demand db VMs is being tracked in #4114
