### ISSUE TITLE
Merge token-exchange into main repo

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#3787]
token-exchange is too far away and hard to work with.  Let's
* [x] Bring `token-exchange/client-demo` into a subdirectory in the main repo like `bench-exchange/`
* [x] Add support for running `bench-exchange` instead of `bench-tps` in the `net/` scripts 
* [x] Migrate any remaining issues from token-exchange over to the main repo then delete the old repo

**Comment by jackcmay** [comment]
sgtm

**Comment by jackcmay** [comment]
@mvines If we change the swapper to the same mechanism the block explorer uses will we again need a separate repo than Solana?

**Comment by mvines** [comment]
> @mvines If we change the swapper to the same mechanism the block explorer uses will we again need a separate repo than Solana?

We're good.  All the support for the block streamer socket is in the main repo.  Blockexplorer provides a JS program that reads from the socket, which wouldn't be helpful for the swapper, so we'd need to write a Rust version of that program -- but that thing would nicely slide into `sdk/`

**Comment by jackcmay** [comment]
Cool

**Comment by mvines** [comment]
cc: #3826

**Comment by jackcmay** [comment]
cc: #3893
