### ISSUE TITLE
Migrate fullnodes from GCP to Azure

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#3793]
#### Problem

GCP services for fullnodes in our testnets are costing too much money.  We want to move to Azure, where we have credits.

#### Proposed Solution

Create net/scripts/azure-provider.sh API similar to gcp-provider.sh and ec2-provider.sh to configure and deploy VM instances.

**Comment by mvines** [comment]
`azure-provider.sh` now exists, and testnets are not running on GCP anymore
