### ISSUE TITLE
testnet sanity fails ~2 minutes after creation

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#3794]
STR:
1. Create a dev testnet: `./ec2.sh create -n 3 -u -c 0 ; ./net start -t edge`
2. Run `./net.sh sanity -o noValidatorSanity` every 30 seconds.  Within a couple iterations it should fail with and error like:
```
Error: Custom { kind: Other, error: StringError("Transaction \"4W4YGhRD2dBqo2nevUgD8LSm3nbutNhNcv6MdUknpzubkwn7DHxjEJc31AgzuMAKUnPxmvMdFtH5Mgca4nUUT9eh\" failed: None") }
```

This also appears to manifest on testnet-edge

**Comment by mvines** [comment]
Perhaps related, from the fullnode.log of the bootstrap leader I'm seeing an attempt to make the blockstreamer node the leader.  This should never happen as the blockstreamer node is unstaked.

**Comment by sagar-solana** [comment]
@mvines, can you add "--only-bootstrap-stake" to blockstreamer? Or unrevert this https://github.com/solana-labs/solana/pull/3655

**Comment by sagar-solana** [comment]
Looks like blockstreamer is being assigned a staking account but it never votes.

**Comment by mvines** [comment]
Ok blockstreamer nodes no longer get a stake, which is a good fix regardless:
master: 3dc47a46d5ba3ac092d129cbe53284ad97fbdd16
v0.13: e90d97e244189b7d15d32b2d265dfb2012903605

Issue still reproduces for me though :-/
