### ISSUE TITLE
Setup on-demand beta-channel CPU and GPU testnet across as many providers/regions/zones as possible

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#3802]
Let's build two testnets, based on the beta channel that runs CPU/GPU validators across all the GCE, AWS, and Azure regions that we can get quota in.  

The infra for this testnet should be setup like testnet-perf where it starts/stops on demand (cc #3691)

Use the results from #3897 to guide the cluster node count for CPU and GPU.  The cluster should be stable enough to run for at least 60 minutes.

**Comment by danpaul000** [comment]
Is the desire that if our GPU quota increases, or other GPUs free up (such as taking down testnet-perf), that restarting this beta testnet would automatically consume all available resources?  Or perhaps better to specify up-to-N GPUs per provider, to leave a fee aside for perf-testnet or other work.

**Comment by mvines** [comment]
up-to-N would be nice, that feels like a separate issue though.  The intent of this issue is to create a testnet in as many sites across the world as possible

**Comment by mvines** [comment]
(fyi: I've reworded this issue slightly to include a CPU testnet as well, and punted the work of researching the node count to use for both CPU and GPU testnets into a separate issue)

**Comment by mvines** [comment]
testnet-demo is now mostly setup.
