### ISSUE TITLE
Update example tic-tac-toe for >= v0.13.0

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#3815]
https://solana-example-tictactoe.herokuapp.com/ is running on a v0.12-based solana-web3.js.  It needs an update to work with v0.13.

**Comment by mvines** [comment]
I fixed up the heroku deployment, an API key went invalid for some reason (probably something I did in Heroku by accident..)

https://solana-example-tictactoe.herokuapp.com/ is now running against beta/v0.13.0 but it's a little unstable - games seem to get cancelled immediately.  

@CriesofCarrots / @sunnygleason - one or more of you are poking around in tictactoe right?  Mind if I hand off this issue to you?

**Comment by CriesofCarrots** [comment]
@mvines, sure, I'll look at it

**Comment by mvines** [comment]
done
