### ISSUE TITLE
solana-gossip stops working after 20 seconds or so

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#3832]
STR:
1. Run `solana-gossip --network beta.testnet.solana.com:8001` and observe the expected number of nodes
2. Wait for ~20 seconds
3. Observe that no nodes are displayed.  <-- KO
4. ^C and goto 1

**Comment by CriesofCarrots** [comment]
Interesting. Are you seeing this intermittently, or consistently?
Fwiw, I've been running solana-gossip against the beta testnet for ~5min, and seeing 13 nodes the whole time.

**Comment by mvines** [comment]
I've been seeing it pretty consistently from my Azure VM, but that you see different behaviour is super helpful.

**Comment by mvines** [comment]
Neat, the STR don't reproduce under macOS for me either.  🤔

**Comment by mvines** [comment]
@sagar-solana and I discussed a couple improvements that ought to help this issue:
1. We forget the cluster entrypoint once the gossip network is established, which means we have no means of recovering later if all the peers disappear for any reason
2. A spy node can only receive pull responses, and other nodes will not send a pull response if the spy node already likely has the response.   This can cause the spy node to drop a peer because it can't distinguish between "I already have it" and the peer unreachable.  Suggested solution here is for the peer to send an empty response so the spy node can refresh its timeout for that peer.

It's still a mystery why macOS behaves better but ...
