### ISSUE TITLE
Replay stage crashes when bench-tps is run without barrier transactions 

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#3859]
#### Problem
Noticed a crash in replay stage.

![image](https://user-images.githubusercontent.com/40076733/56327809-f6e46b00-6130-11e9-8530-018b8358a5ad.png)

#### Proposed Solution
Triage and fix

**Comment by mvines** [comment]
Obsolete since we removed barrier transactions?

**Comment by pgarg66** [comment]
@sagar-solana is trying to reproduce it. It was noticed after barrier transactions were removed.

**Comment by carllin** [comment]
Here's the trace: 

thread '<unnamed>' panicked at 'index out of bounds: the len is 237 but the index is 238', /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/
libcore/slice/mod.rs:2455:10
thread '<unnamed>' panicked at 'index out of bounds: the len is 237 but the index is 238', /rustc/2aa4c46cfdd726e97360c2734835aa3515e8c858/src/
libcore/slice/mod.rs:2455:10
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}
   5: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:482
   6: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:385
   7: rust_begin_unwind
             at src/libstd/panicking.rs:312
   8: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   9: core::panicking::panic_bounds_check
             at src/libcore/panicking.rs:61
  10: solana_runtime::accounts_db::AccountsDB::store
  11: solana_runtime::accounts::Accounts::store_accounts
  12: solana_runtime::bank::Bank::commit_transactions
  13: solana_runtime::bank::Bank::load_execute_and_commit_transactions
  14: solana::blocktree_processor::par_execute_entries::{{closure}}
  15: rayon::iter::plumbing::bridge_producer_consumer::helper

**Comment by mvines** [comment]
Obsolete.  If this occurs again please create a new issue.
