### ISSUE TITLE
Consider dynamically scaling SigVerify Batch sizes

### ISSUE THREAD

**Issue by sagar-solana** [solana-labs/solana#3873]
#### Problem

SigVerify appears to consume over half the slot duration with the current batch size of 100k. 

![Screenshot from 2019-04-18 10-54-18](https://user-images.githubusercontent.com/44789711/56380960-6d807780-61c8-11e9-9122-6eadb7ef00dc.png)

#### Proposed Solution

Dynamically scale the batch sizes to keep sigverify times below 150ms(or some configurable value)

Tag: @sakridge

**Comment by sagar-solana** [comment]
fyi, this is on perf testnet with big boy gpus :)

**Comment by bw-solana** [comment]
SigVerify batch sizes have been tweaked since this issue was opened. Current design limits batches to 2k and has some load shedding & dedup that takes place before
