### ISSUE TITLE
Add grafana dashboard for bench-exchange

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#3878]
#### Problem
Once bench-exchange is running against a testnet, we have no visual way to view the performance of the exchange. 

#### Proposed Solution
Add pretty graphs and counters for bids, asks, .... 
Iterate the dashboard using feedback from @aeyakovenko until it's looking solid for his needs.

**Comment by mvines** [comment]
@jackcmay - you're probably the best person to take a first swag at defining exchange metrics to add to Grafana.

**Comment by sakridge** [comment]
I added this one: https://github.com/solana-labs/solana/blob/809b051f10d3521f4617928efa26104ddf8298fa/bench-exchange/src/bench.rs#L334

But not sure how to modify the dashboard to include it.

**Comment by aeyakovenko** [comment]
@sakridge we need some for client side requests submitted and in the contract, requests processed. One for bid/ask price updates and matched.

**Comment by mvines** [comment]
All done now
