### ISSUE TITLE
Reading/Writing data to and from `Blob`s is very error-prone

### ISSUE THREAD

**Issue by mark-solana** [solana-labs/solana#3912]
#### Problem
All code that writes to `Blob`s has to essentially re-implement slices by keeping track of and properly updating the blobs size since it is really container of several different logical fixed-sized buffers. Similarly all code the reads from it has to decide which sections it really wants and slice into it appropriately.

Example here: https://github.com/solana-labs/solana/blob/efbb57331613bbb95b830c1bd57a26dddff243a5/core/src/packet.rs#L386-L395

Code updating and keeping track of the size is scattered all over and this kind of thing is very error-prone and slows development velocity.

#### Proposed Solution
The `Bytes` and `BytesMut` traits from the [`bytes` crate](https://docs.rs/bytes/0.4.12/bytes/) abstract over exactly this kind of usage. 

Make `Blob`'s internal storage private and add accessor methods for the logical contents of a `Blob` for client code that return some type implementing the above traits.

**Comment by pgarg66** [comment]
This code has been rewritten as `shreds`. The issue is obsolete now.
