### ISSUE TITLE
testnet-beta is panicking at startup

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#3918]
Since ~Friday evening, testnet-beta has failed to restart every hour.   Most fullnodes are panicking shortly after they start with:
```
thread 'solana-window' panicked at 'assertion failed: self.consumed <= self.last_index + 1', core/src/blocktree/meta.rs:39:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:70
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:58
             at src/libstd/panicking.rs:200
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:215
   4: solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}
   5: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:482
   6: std::panicking::begin_panic
   7: solana::blocktree::Blocktree::handle_chaining
   8: solana::blocktree::Blocktree::insert_data_blobs
   9: solana::window_service::recv_window
```

There's been no commits into v0.13 between the time that it worked to now.   However there's a 3rd party validator attached to testnet-beta, and it shows up in gossip on every testnet restart.   One theory is that this validator is sending repair requests to the rest of the cluster from an old ledger

**Comment by meltaus** [comment]
https://pastebin.com/sCqVkFRJ
version v0.13.1

**Comment by mvines** [comment]
Some progress at #3920 that should prevent the panic.  However to properly recover, replay stage likely needs to remove the blocks from blocktree that fail to verify PoH

**Comment by mvines** [comment]
Here's where in replay stage I think we ought to remove the bad block from blocktree: https://github.com/solana-labs/solana/blob/bec094bb3eeda3e812d08de69649bb8f3e508396/core/src/replay_stage.rs#L295-L297

There's even an existing *TODO* there!
