### ISSUE TITLE
Fix Data Plane fanout 

### ISSUE THREAD

**Issue by sagar-solana** [solana-labs/solana#3922]
#### Problem

It appears that the Dataplane fanout isn't working as expected. Prime suspect being the set of stakes not being the same across all nodes. 
Another possible issue could be that nodes retransmit blobs back to the leader.

#### Proposed Solution

Triage this and figure out why blobs aren't being delivered in time correctly. Temporarily move the Data Plane fanout out of the way of our large(200+) node clusters.

Tag: @aeyakovenko @pgarg66

**Comment by garious** [comment]
Implementing https://github.com/solana-labs/solana/issues/1131 would tell us if your prime suspect is a valid concern.

**Comment by aeyakovenko** [comment]
@garious is it using gossip or epoch leader schedule for the fanout?

**Comment by sagar-solana** [comment]
@aeyakovenko, dataplane fanout uses epoch stakes to figure out how to retransmit to.

**Comment by aeyakovenko** [comment]
@sagar-solana, epoch 100, should only be "active" at slot 200, if the epoch size is 100.  Is it using the epoch right away, or after it becomes active?

**Comment by sagar-solana** [comment]
@aeyakovenko, Only after it becomes active. Effectively it's mirroring what leader schedule uses for stakes.

**Comment by aeyakovenko** [comment]
@sagar-solana how is it inconsistent then?

**Comment by sagar-solana** [comment]
@aeyakovenko, I'm not sure yet. I've been trying to debug this. Seems to work OK without a client. Still early in debugging this.

**Comment by sagar-solana** [comment]
Just a quick update. With a Fanout of 5 with 21 nodes, the data plane appears to function perfectly. 
This translates into the following layout
```
This results in 3 layers. 
1 leader
5 nodes in layer 0(always 1 neighborhood)
10 nodes in layer 1 (2 neighborhoods)
5 node in layer 2 (1 neighborhood). 
```
A test with a much larger network is still pending.
