### ISSUE TITLE
Re-evaluate Influx cloud subscription plan

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#3923]
#### Problem
We have subscribed to Influx Cloud Pro II plan. Our usage of Influx DB could be optimized to change to a lower plan.

#### Proposed Solution
Analyze our usage of Influx DB. See if we can buffer data in fullnode for longer before sending it to Influx Cloud. Goal is reduce peak to average usage of Influx DB (remove spikes). This might be tricky, as there are multiple testnets sending data randomly.

**Comment by mvines** [comment]
Dup of #4116
