### ISSUE TITLE
Replicators don't/can't verify blobs, will retransmit unverified dataplane traffic

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#3924]
#### Problem
 without banks, replicators can't verify that a blob is the correct one for a slot/index, and so are spam gateways for retransmit

#### Proposed Solution
?? 
replicators need a trusted source of leader_id for the chunk of ledger they'll proof, right?

**Comment by rob-solana** [comment]
cc @aeyakovenko @sagar-solana @sakridge

**Comment by sakridge** [comment]
Doesn't seem like #4275 fixes this issue, no?

**Comment by sagar-solana** [comment]
Hm, they actually don't even part take in retransmit. I took this issue to cover the fact that their window service was dropping all blobs.

It comes back to #4220. Current best approach is to somehow verify this against multiple validators?

**Comment by sakridge** [comment]
Couple of ideas:

1. Validators could store the starting/ending PoH value for all segments, and then replicators ask all validators for those values, then they can do PoH verify on the segment.

2. 'Lite' version of the ledger with just the votes is generated, replicator downloads that first and uses it to verify the segment that way. I know @aeyakovenko has talked about having this for other use-cases as well.

**Comment by sagar-solana** [comment]
3. They could also wait to see if their proof is accepted by the cluster? If it fails then they might have to re-download the segment? 

4. If they download a snapshot at the beginning of the segment, they can generate the leader schedule for it and should be able to verify the blobs? 

I'd like to hear @aeyakovenko's thoughts on which way we should take this.

**Comment by aeyakovenko** [comment]
@sagar-solana #4200 is what you want eventually. For now we can just poke multiple validators

**Comment by sakridge** [comment]
@aeyakovenko @sagar-solana Will validators be storing multiple snapshots for every part of the ledger? I was thinking the validator would only hold on to the most recent few.

**Comment by sakridge** [comment]
I suppose replicators themselves could store the snapshots.

**Comment by ryoqun** [comment]
I'm certain this can be closed as well.
