### ISSUE TITLE
testnet gce.sh script gets stuck waiting for /.instance-startup-complete

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#3949]
#### Problem
This is an intermittent problem. @carllin and I have witnessed the issue on multiple occasions.

The testnet gce.sh (ec2.sh) script gets stuck waiting for a node to bootup. It continuously tries to check for /.instance-startup-complete file on the remote node. After some tries it exits with a failure.

```
++ timeout 20s ssh -o ConnectTimeout=20 -o BatchMode=yes -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -o User=solana -o IdentityFile=/home/pankaj_solana_com/workspace/solana/net/config/id_testnet-dev-pankaj -o LogLevel=ERROR 35.204.12.22 'ls -l /.instance-startup-complete'
```

The file actually exists on the remote node, and if the ssh command is run simultaneously from another shell, it does succeed.

If user hits ctrl-C while gce.sh is stuck in a loop, it somehow works and completes the testnet bootup.

#### Proposed Solution
Triage and fix

**Comment by mvines** [comment]
(I've seen this too, it's really weird. 😕)
