### ISSUE TITLE
Bootstrap leader in non CUDA testnet is running OOM

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#3959]
#### Problem
The bootstrap leader node in a non CUDA testnet runs out of memory within 20 minutes. Lowering the tx_count to really low value helps keep the network up. Not sure if the leak slows down, but still happening. 

#### Proposed Solution
Triage and fix.

**Comment by sakridge** [comment]
I've seen them with cuda enabled as well.

**Comment by mvines** [comment]
Seems like this could just be the packet forwarding?   If we barrage one node with more transactions that it can forward and never stop, eventually it'll OOM since we aren't discarding older transactions that are pending forwarding yet.

This might help too: #4112
