### ISSUE TITLE
GCP node stops/dies during testnet startup

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#3970]
#### Problem
This is an intermittent issue. When the issue happens, a subset of the GCP VMs don't bootup (or dies soon after bootup) while testnet is being created (while running gce.sh). The symptoms of this issue are

1. The check for /.instance-startup-complete file keeps failing
2. The corresponding VM in GCP console is stopped and the Public IP of the node has been released.

This is NOT the same issue as https://github.com/solana-labs/solana/issues/3949

#### Proposed Solution
Triage and fix.
This issue can also be detected faster by using gcloud API to find the status of VM instance. If the VM is not running, there's no point looking for /.instance-startup-complete on the VM in a loop. We can declare the error faster and take corrective actions.

**Comment by pgarg66** [comment]
For example, fullnode-19 stopped during testnet startup.

![image](https://user-images.githubusercontent.com/40076733/56688506-ca2ed700-668d-11e9-817e-ea7845a6feeb.png)

**Comment by mvines** [comment]
On v0.14 (and master now too), we've added some extra parameters to the testnet deployment scripts to better handle this issue.  I don't think we need to do much more here
