### ISSUE TITLE
solana-install-init.sh error message observed

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#3971]
#### Problem
observed this error:

`rmdir: failed to remove '/tmp/tmp.VQZuCVvUjU': Directory not empty`

actual contents:
```
[rwalker@ip-172-30-0-124 ~]$ ls -lR /tmp/tmp.VQZuCVvUjU
/tmp/tmp.VQZuCVvUjU:
total 8
-rw-rw-r-- 1 rwalker rwalker 5414 Apr 24 20:16 release
```

#### Proposed Solution
use 'rm -rf '?

**Comment by mvines** [comment]
Yeah just gotta rimraf here prolly:
https://github.com/solana-labs/solana/blob/54b44977e0b2af5a23e97482f967e2f6110a9d48/install/solana-install-init.sh#L116
