### ISSUE TITLE
design for a new repair protocol

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#3974]
#### Problem
validators that find themselves behind the network by an entire epoch struggle/fail to catch up because repair is "backwards facing", i.e. a validator witnesses a blob from a slot far in its future and repairs by asking the network "what came before this?"

This protocol exposes nodes to spam, because blobs outside the node's epoch can't be validated against anything.

#### Proposed Solution
a new repair protocol that works in a "forward" fashion, so validators can verify every blob (as required by #3975)

Broad strokes:
* a node (repairee) advertises its BankForks over gossip, along with its current epoch
* observers of this gossip message **with higher epochs** (repairmen) send blobs to catch the node up

Who sends what?
* repairmen send data.  repairmen are those nodes whose current epochs are higher than that of the repairee
* repairmen send blobs in the repairee's epoch, in slots that chain to the slot of the repairman's latest vote
* each repairman in an N node network (N nodes whose epochs are higher than that of the repairee) sends an Nth of the blobs (simple blob.index iteration by N, seeded with the repairman's node_id)
* data and coding blobs of that index

**Comment by mvines** [comment]
cc: #3954

**Comment by rob-solana** [comment]
@aeyakovenko @carllin @sagar-solana

**Comment by carllin** [comment]
Once a repairman sends the data, we don't send the next batch of data until the repairee updates its message in gossip? Aka, keep an iterator of what we've already sent?

**Comment by aeyakovenko** [comment]
@rob-solana what do you think of repair requests to be responses with more erasure blobs?  
* block is split into blobs, 
I* 64 blobs 32:32 form a set
each request is indexed 0,N sets, with an erasure code index from 0->M > 32.  So the responders start generating additional erasure codes.

**Comment by rob-solana** [comment]
> Once a repairman sends the data, we don't send the next batch of data until the repairee updates its message in gossip? Aka, keep an iterator of what we've already sent?

yes.  repairman does one repair pass per gossip update.  that pass would be considered the repair response, as  the gossip state would be considered a repair request. once a repairman has done the work requested he's done until there's another request.

**Comment by rob-solana** [comment]
> @rob-solana what do you think of repair requests to be responses with more erasure blobs?
> 
> * block is split into blobs
> * 64 blobs 32:32 form a set
> 
> each request is indexed 0 -> N sets, with an erasure code index from 0->M, which can be greater than 32. So the responders start generating additional erasure codes once M is greater than 32.

could be sweet, but how about that being Future! ;)  before such a thing, we need per-slot erasure parameters.  this issue is hopefully a v0.15 thing.

**Comment by carllin** [comment]
When does the repairee decide to update the message in gossip? If validators are only gossiping their bank forks (which only contains consecutive slots from root) it seems like they could be missing some slots that are already completed in their blocktree, either from a previous repair or from retransmit.

**Comment by rob-solana** [comment]
validators update their gossip every time they change the set of frozen banks in their bankforks (i.e. all slots that can be added onto)

**Comment by aeyakovenko** [comment]
How do the repairmen not dos a node?

**Comment by aeyakovenko** [comment]
@rob-solana i was thinking something the other way.  everyone publishes a set of blobs from the current fork and back as a bloom filter in gossip.  A leader can do another fanout message to catch everyone up, or the nodes ask each other by looking at the filters.

**Comment by rob-solana** [comment]
repairmen won't DOS the node because it's less data than is ingested by the TPU

repairmen only send one slot's worth of blobs

leaders may have dropped off radar by the time the repairee joins

@carllin and I discussed bloom filters, and couldn't think of a good way to keep them cheap

**Comment by mvines** [comment]
@carllin did #3402 fix this issue?

**Comment by carllin** [comment]
yeah it did, closing
