### ISSUE TITLE
window_service should not accept blobs for slots for which they can't identify the leader

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#3975]
#### Problem
window_service writes blobs to blocktree even when the leader for the blob's slot can't be verified, as is the case when a new validator joins a network that's far ahead of it

#### Proposed Solution
remove the "unknown leader" clause in window_service::should_retransmit_and_persist()

issue: this will make it so new validators never catch up.  a new, forward-moving, repair protocol is needed see issue #3974

**Comment by mvines** [comment]
Seems like we should just roll this into #3974, as "this will make it so new validators never catch up" is basically a showstopper from us ever wanting to ship a fix to this issue

**Comment by rob-solana** [comment]
#3974 is more of a "don't have a proposal" issue

**Comment by rob-solana** [comment]
@carllin this covered?

**Comment by carllin** [comment]
yup this is done xD
