### ISSUE TITLE
bench-exchange waits too long for transaction send and should retrieve blockhashes more often

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#3979]
#### Problem

bench-exchange has a 100ms poll on the transaction send threads which causes low single-client performance. It also waits too long to get a recent blockhash.

#### Proposed Solution

Remove transaction send thread wait and fetch a new blockhash on every batch.

**Comment by jackcmay** [comment]
@sakridge What do you think about the blockhash, get one every time?  If not, what do you recommend the delay be lowered to?

**Comment by sakridge** [comment]
I think every batch is fine, but if you want to go with the delay I would do around 1 second.
