### ISSUE TITLE
Blobs represent several different types of message but are represented as one type

### ISSUE THREAD

**Issue by mark-solana** [solana-labs/solana#3981]
#### Problem
There are coding blobs, data blobs, and blobs containing serialized packets, used in the data plane. each client of blob has to assume or check whether it's handling  the correct kind of Blob manually and the type system isn't being used to help.

Currently there appear to be three types of blobs in use:

1. Data blobs.
2. Coding blobs.
3. "Buffer" blobs used to forward unprocessed transactions. These blobs pack packets into the whole array, and their header is meaningless. Data and coding blobs have meaningful headers. This shouldn't exist and should be part of a separate protocol. This will be addressed separately.
#### Proposed Solution
* Create an enum `BlobHeader` with `Coding` and `Data` variants that contain structs with the deserialized metadata appropriate for each variant. For example, the `Data` variant could contain a struct that looks something like:
```rust
pub struct DataHeader {
    pub parent: u64,
    pub slot: u64,
    pub index: u64,
    pub id: Pubkey,
    pub forwarded: bool,
    pub genesis: Hash,
    pub data_len: u64,
}
``` 
and the `BlobHeader` enum could be
```rust
pub enum BlobHeader {
    Data(DataHeader),
    Coding(CodingHeader),
}
```
* Implement `Serialize` and `Deserialize` for `BlobHeader` correctly so that it checks the flags, only requires buffers  `>= BLOB_HEADER_SIZE` in length, etc.
* Create structs `DataBlob` and `CodingBlob` that have as fields: 
  * `pub meta: solana::packet::Meta`
  * `pub header: <Data|Coding>Header` as appropriate 
  * `data: BlobData`

  and each have `fn data(&self) -> &[u8]` and `fn data_mut(&mut self) -> &mut [u8]` accessors that slice into the `BlobData` as appropriate. They would also each have a `fn to_blob(self) -> Blob` method that updates the serialized header fields in the `BlobData`  converts them back into `Blob`s
* Add `to_<data|coding>(self, header: <Data|Coding>Header) -> Result<<Data|Coding>Blob, BlobError>` methods to the current `Blob` type
* Migrate clients of `Blob` to first deserialize the header, and then possibly convert the `Blob` into `<Data|Coding>Blob`s if appropriate.
* Migrate code that doesn't need to know about `Blob`s to directly using `<Data|Coding>Blob`s as appropriate.

**Comment by rob-solana** [comment]
ok, we're close

there should be no such thing as a buffer blob

**Comment by mark-solana** [comment]
@rob-solana updated the proposed solution

**Comment by rob-solana** [comment]
let's focus first on data plane stuff, ignore the forwarded stuff for now, tackle in another issue/PR

I'm not sure we need the struct DataBlob/struct CodingBlob stuff, unless they're possible to do in-place

**Comment by mark-solana** [comment]
@rob-solana I think the conversion would be very cheap if it takes `self` by value. from `Blob` -> `DataBlob` would just read the serialized fields, create the header struct, and move the `BlobData` and `Meta` fields. The other direction would use the header struct to update the header part of the `BlobData`, then move it and the `meta` field into the blob. 

Might be useful for declaring intent if we want to have to add methods/functions that only operate on data or coding blobs, but it's true they aren't needed
