### ISSUE TITLE
Storage Stage uses an internal thread to send transactions

### ISSUE THREAD

**Issue by sagar-solana** [solana-labs/solana#3986]
#### Problem

Storage stage uses a second thread internally just to send transactions to the leader. 

#### Proposed Solution

Maybe we can get rid of this thread and send the transactions from the main storage loop.

**Comment by sakridge** [comment]
How is this the top priority for getting replicators working?

**Comment by sagar-solana** [comment]
It's not just clean up while in the middle of other things.

**Comment by ryoqun** [comment]
I'm certain this can be closed as well.
