### ISSUE TITLE
Blocktree is not safe to write to concurrently, but we pretend it is.

### ISSUE THREAD

**Issue by mark-solana** [solana-labs/solana#3987]
#### Problem
As noted [here](https://github.com/solana-labs/solana/pull/3982#pullrequestreview-230468204) blocktree is not safe to write to from multiple threads, because the metadata can get incoherent if batches of writes race to commit. 

The `test_recovery_multi_slot_multi_thread` was the only thing to expose this. This hasn't shown up in production since only `window_service` ever writes to blocktree, but this should be enforced using Rust's type- and borrow-checking system and concurrency primitives.

#### Proposed Solution
Make methods like `write_blobs`, `write_shared_blobs`, `put_data_blob` etc. take `&mut self` and make clients use `Arc<RwLock<Blocktree>>`s as needed.

Could also try a finer-grained locking scheme.

cc @rob-solana @carllin

**Comment by rob-solana** [comment]
replay_stage also writes to blocktree, with set_root()

**Comment by mark-solana** [comment]
@rob-solana Didn't know that. I guess we've just been lucky so far.

**Comment by mvines** [comment]
😱
