### ISSUE TITLE
Nodes stop voting after some time in testnet (with > 100 nodes)

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#3998]
#### Problem
The nodes stop after a while. This is reflected in votes graph and confirmation time graph.
![image](https://user-images.githubusercontent.com/40076733/56763412-36c1d880-6757-11e9-9df9-11345abfd8bf.png)

#### Proposed Solution
Triage and fix

**Comment by mvines** [comment]
@carllin we're probably good here on master now?

**Comment by carllin** [comment]
Yeah the AccountNotFounds should be resolved
