### ISSUE TITLE
Move 3rd party validators from testnet-beta to testnet

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4010]
The testnet-beta cluster automatically picks up any commits that are pushed to the beta channel branch as quickly as possible.  This is great but we've also asked that 3rd party validators who want to learn about running a node also attach to testnet-beta, which while convenient in the immediate term causes problems when a new release is being made.  

eg:
1. The v0.13 branch is currently beta
2. The v0.14 branch is then created and contains changes that are incompatible with v0.13 (hey we're still in the 0.x releases :))
3. The automated testnet-beta nodes pick up v0.14 and boot everybody else off the main testnet-beta cluster.

A reasonable fix would be to ask folks to move to the "testnet" testnet, once that testnet is modified to pick up the latest release tag off the beta branch (or the stable branch if there is no release tag on beta yet).   We used this setup for "testnet-perf" testnet a couple months ago so it's pretty easy to do.   The process for updating validators would then be (1) Tag a new release off beta, (2) Announce it

**Comment by mvines** [comment]
I tagged v0.13.2 as a first step toward fixing this: https://github.com/solana-labs/solana/releases/tag/v0.13.2

**Comment by mvines** [comment]
@danpaul000, I'll work on this since you've got other hipri stuff to work on today already

**Comment by danpaul000** [comment]
> @danpaul000, I'll work on this since you've got other hipri stuff to work on today already

Sounds good.  The testnet-perf channel fixing was just a couple weeks ago and one of my first tasks. :). My how time flies!

**Comment by mvines** [comment]
Oh neat, yeah I can totally use the `TESTNET_TAG` facility you added for testnet-perf

**Comment by danpaul000** [comment]
I think all you need to do is add TESTNET_TAG=<your version of choice> to
all the testnet-beta schedules in the mgmt pipeline and you'll be all set.

**Comment by danpaul000** [comment]
And set the build branch to match.

**Comment by mvines** [comment]
Cool works.  http://testnet.solana.com/ is up running with v0.13.2
So like testnet-perf, updating the software on the testnet testnet (ugh!) requires editing the two buildkite jobs for hourly sanity and daily restart, but we can how fully control the rollout to avoid random bustage on #validator-support.

**Comment by mvines** [comment]
Two remaining issues here:
* [ ] `solana-install` is failing to initialize for http://testnet.solana.com:8899/
* [ ] Using `solana-install-init.sh` to pick up the latest release tag is not desired, need to fix this workflow still

**Comment by mvines** [comment]
All the technical work here is now done.  What remains is tagging the v0.14.0 release and announcing the new release, the normal release flow
