### ISSUE TITLE
Support transactions with multiple instructions

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#402]
We currently only process one instruction per transaction, but the user may want to process many. For example, a contract that requires a signature in one instruction, and then that signature in the second.

Adding too many instructions could cause a pipeline stall, so some thought should be given to how many instructions we should allow under a single transaction.

**Comment by carllin** [comment]
Working on it :)

**Comment by mvines** [comment]
This is done

**Comment by walshe** [comment]
stupid question but if I combine 2 instructions into one transaction, I get one signature right ? bit when I look up this transaction signature in the explorer it only has the fee that relates to one of the instructions. Is there a way I can find both related fees easily ?

The reason I ask is that in my app I keep a record of every signature and later on (asynchronously) I look up the transaction to also make a record of the fee in lamports.

**Comment by t-nelson** [comment]
> stupid question but if I combine 2 instructions into one transaction, I get one signature right ? bit when I look up this transaction signature in the explorer it only has the fee that relates to one of the instructions. Is there a way I can find both related fees easily ?
> 
> The reason I ask is that in my app I keep a record of every signature and later on (asynchronously) I look up the transaction to also make a record of the fee in lamports.

we don't use github for support. join us in #developer-support on https://solana.com/discord instead
