### ISSUE TITLE
Document testnet.solana.com update process in RELEASE.md

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4035]
#### Problem
The process to update testnet.solana.com is manual and undocumented

#### Proposed Solution
Document the process in RELEASE.md.

Roughly:
1. Modify TESTNET_TAG and the Branch settings in https://buildkite.com/solana-labs/testnet-management/settings/schedules/0efd7856-7143-4713-8817-47e6bdb05387 and https://buildkite.com/solana-labs/testnet-management/settings/schedules/2a926646-d972-42b5-aeb9-bb6759592a53 to match the release
2. Trigger a TESTNET_OP=create-and-start to refresh the cluster with the new version
3. Document the new recommended version by updating the `export SOLANA_RELEASE=v0.14.0` text in `book/src/testnet-participation.md` for both edge and beta channel branches (yuck, is there a better way?)
4. Notify discord users that a new release for testnet.solana.com is available.

**Comment by danpaul000** [comment]
Should the same process apply to testnet-perf here as it will for testnet?  Or will perf only ever be changed manually, not necessarily tied to the release cadence like testnet is/should be?

**Comment by mvines** [comment]
testnet-perf is different, as it's just an _internal_ tool for max TPS testing.  For now it'll have its own update cadence.
