### ISSUE TITLE
Synchronize the book version with the testnet.solana.com version 

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4040]
#### Problem
Right now we publish the book based on the contents of the beta release channel, which means that it may contain newer information about booting a validator on the testnet that doesn't match the current testnet deployment.   This has already caused a little confusion 

#### Proposed Solution
Extend #4035 to include publishing the book contents to https://solana-labs.github.io/book, which implies that we'd probably want a book-beta version of the book like [book-edge](https://solana-labs.github.io/book-edge/)

**Comment by danpaul000** [comment]
Not sure I understand your proposed solution.  The book version here:  https://solana-labs.github.io/book/ is based on the beta branch, which is the branch we are putting testnet on.  So when we make a release and the publish-book.sh script runs as part of it, the instructions should align with the testnet software advancement process lined out in #4035.

So I don't think we need another version of the book in that case.

Are you just requesting that whatever changes I make in #4035 onto master also get picked onto the 0.14 branch?

**Comment by mvines** [comment]
"testnet-beta" automatically picks up the beta branch, but "testnet" (cc: #4066) is uses a manually-specified release tag.  

The beta branch could auto publish to https://solana-labs.github.io/book-beta/, like how edge auto publishes to https://solana-labs.github.io/book-edge/, but https://solana-labs.github.io/book/ should be aligned with that manually-specified release tag for "testnet"

**Comment by mvines** [comment]
Ack, let’s try to get this fixed during 0.17.  We’re in the situation again now were the public book url refers to an unreleased version (0.16.0)

**Comment by mvines** [comment]
Somebody got confused again due to this :(

**Comment by danpaul000** [comment]
Sorry this one's gone on for so long.  I'll get it in for tomorrow's 16.4
