### ISSUE TITLE
|solana-gossip spy| is a little flaky when used against a large cluster

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4054]
#### Problem
On testnet-demo, with close to 200 nodes, `cargo run -p solana-gossip -- -n demo.testnet.solana.com:8001 spy` when run from another cloud machine occasionally fails to find any nodes.

This is also a problem with `bench-tps`

#### Proposed Solution
Fix or mitigate it.

**Comment by sagar-solana** [comment]
This happens even if we don't point at the bootstrap leader? I'm wondering if this is because of packet drops on the bootstrap node's kernel.

**Comment by mvines** [comment]
demo.testnet.solana.com points at the blockstreamer node for that network.  I don't recall if I tried to gossip with the bootstrap node when this reproduced for me last night

**Comment by sagar-solana** [comment]
Hm.. Okay. It's possible blockstreamer isn't being favored in gossip since it's got no stake. But it should be running pulls against other nodes. I'll take a look when I get in.

**Comment by mvines** [comment]
Looks like most of this is due to something weird in my Azure VM..
