### ISSUE TITLE
Add custom buildkite agent on metrics.s.c for testnet-demo

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4056]
#### Problem
Testnet operations get bogged down when multiple jobs are competing for the single testnet buildkite agent.  This could be a problem for testnet-demo as it takes quite a while to start and we don't want to wait to start it.

#### Proposed Solution
Migrated the three testnet-demo pipelines to a new agent running on m.s.c

**Comment by danpaul000** [comment]
Started metrics-solana-com-3 agent with queue=demo.  Set all the steps for the 3 demo pipelines to use queue=demo.
