### ISSUE TITLE
testnet-demo-enable fails sanity check

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4059]
See title.  One recent example: https://buildkite.com/solana-labs/testnet-demo-enable/builds/11

**Comment by mvines** [comment]
While debugging #4054, @sagar-solana determined that due to how spy nodes are only partial gossip participants, using a spy node to sanity check the exact number of nodes in a cluster (especially a larger one) is just broken.

Short term fix is to not check for an exact number of nodes during sanity, just that some exist
Longer term @sagar-solana is looking at making a spy node a full gossip participant, which now that we have weighted nodes based on stake should be less of an issue than before

**Comment by mvines** [comment]
All fixed now

**Comment by sagar-solana** [comment]
We can now enforce this with https://github.com/solana-labs/solana/pull/4087
