### ISSUE TITLE
Running bench-tps hard against the demo testnet kills the testnet

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4081]
STR:
1. Bring up testnet-demo
2. ssh into the client VM
3. Run `./bench-tps.sh`, then ^C it after 3-5 minutes
4. From the block explorer, see the node count hit zero and the cluster is now dead

**Comment by mvines** [comment]
Here's a Grafana snapshot of the event: https://metrics.solana.com:3000/dashboard/snapshot/zYwPk0xw1Ves2Vk9CB0kl3KBqiZkw8CL

@sagar-solana / @pgarg66 - could you both please tag team this issue?

**Comment by pgarg66** [comment]
@sagar-solana and I have been looking into this issue. The following is our current hypothesis

1. The block streamer node died (the node count dropped from 204 to 203 around the same time). All the transactions are sent to block streamer. So if it's dead, bench TPS won't work. We tried running a local client against beta testnet. It seems to be running fine, as the block streamer is still up.
2. We see that some nodes are on different forks. That would mean the blockhash in tx won't match the blockhash queue. And TX will keep failing.
3. There are a lot of AccountNotFound errors on validator nodes. That can be causing the network to fork. @carllin has been looking into it.

**Comment by pgarg66** [comment]
We are able to restart bench-tps client from the demo client VM.

1. After the client is killed, the network keeps processing backed up transactions. If the client is restarted while the network is backed up, it'll fail to do initial airdrops (as it's taking longer, and airdrop will timeout)
2. If we leave enough gap between the two runs, it succeeds.

We have done it about 5 times in a row now.

**Comment by pgarg66** [comment]
Updated ```--thread-batch-sleep-ms 50``` in ```bench-tps.sh```
This removes the backlog of transactions from the network, and allows restarting bench-tps.sh.

**Comment by mvines** [comment]
Thanks I think we've gotten to the bottom of this now
