### ISSUE TITLE
 bench-exchange config for the demo testnet is much slower than bench-tps

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4082]
`./bench-tps.sh` on the demo testnet hits north of 30k TPS whereas `./bench-exchange.sh` drives around 5k TPS.

Can we tune anything in `./bench-exchange.sh` to get closer to `./bench-tps.sh`?

**Comment by mvines** [comment]
Here are two Grafana dashboard snapshots that may help too: [bench-tps](https://metrics.solana.com:3000/dashboard/snapshot/fDhTlRu4bLiWNr1gP6aVFU5H5LMj4YN8) vs [bench-exchange](https://metrics.solana.com:3000/dashboard/snapshot/UeRHLt501gX7BIauR5C5vnVGeGPsYqS3?orgId=2)

**Comment by sakridge** [comment]
Seems that bench-tps is too fast, most transactions are bank errors and bench-exchange delay times limit it to 5k, although swaps are not happening even at that rate.

**Comment by mvines** [comment]
We're ok for v0.14, but this issue is also mostly a dup of #3946 so closing
