### ISSUE TITLE
Lots of duplicate code in bench-exchange and bench-tps

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#4120]
#### Problem

Duplicated code in bench-exchange bench-tps, for instance funding many keys, sending transactions with multiple threads, computing stats.

#### Proposed Solution

Move into common library, write more tests.

**Comment by garious** [comment]
@sakridge, I recall you did some work in this space. Is duplicate code still an issue?

**Comment by sakridge** [comment]
I reduced some of it, but I would still say there is more to be done in this area.

**Comment by garious** [comment]
Mind if I remove this from the Performance project, since there's no performance metric that will improve as a result of doing this work?
