### ISSUE TITLE
Dynamically adjust erasure set size and ratio

### ISSUE THREAD

**Issue by mark-solana** [solana-labs/solana#4133]
#### Problem
Currently erasure set size and the ratio of data to parity blobs is a compile-time constant. It should be dynamically adjustable based on pipeline load.

#### Proposed Solution
* [ ] Add an `Index` column to simplify keeping track of blobs and provide an easy presence API: #4724
* [ ] Change the `ErasureMeta`  column to store all encoding parameters so that erasure sets can be configured independently of each other #4826

**Comment by mvines** [comment]
@mark-solana - hey looks like there's some progress on this issue at https://github.com/mark-solana/solana/commits/dyn-erase ?
