### ISSUE TITLE
All metrics all the time is not scalable

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#4147]
#### Problem

The current usage of metrics is coarse and already producing overwhelming amounts of data.  There is a need to add more and finer metrics and doing so is untenable with the current design.  In particular all metrics are always submitted even if they are not needed for a specific analysis use case.

For example:
  - May want all bank messages disabled when not the leader.
  - May want only messages from the leader
  - May want to enable fine grained metrics in a specific area only
  - May want to pick and choose only the metrics that tell a particular story

#### Proposed Solution

Metrics categories (and maybe level too)

- Metric filters by category.
  - Configuratble by environment variable
  - Configuratble programaticllay at runtime
  - Configurable remotely via socket?
- Filter out metrics as close to the caller as possible

Extends itself to category specific rates, batch sizes, and flushes

**Comment by mvines** [comment]
It's likely that the volume of our metrics is also having a negative impact on TPS overall.  cc: @pgarg66

**Comment by jackcmay** [comment]
In addition to filtering by level per module it would also be very helpful to filter by metric group/name.

The logging macros can optionally take a `target` field where the target is by default the module name but could also be a custom name (like a metric group).  If the target name was matched greedily then metrics could be surgically enabled depending on what metrics a certain use case demands.

For example match a group of metrics:
```
RUST_LOG=metric_group=trace
datapoint!("metric_group_metric_name", 5, u64);
if log_enabled!(target: metric_group, Level::trace) {
  ...
}
```
Or match individual metrics
```
RUST_LOG=metric_group_metric_name=trace,metric_group_metric_name2=debug
datapoint!("metric_group_metric_name", 5, u64);
if log_enabled!(target: metric_group, Level::trace) {
  ...
}
```

Any combination of the above would be possible.

**Comment by pgarg66** [comment]
As @aeyakovenko mentioned, we can build a flag server. @rob-solana reminded me today of a similar feature in Chromium, where the metrics can be configured using field trials servers (https://chromium.googlesource.com/chromium/src/+/master/testing/variations/README.md)

**Comment by jackcmay** [comment]
Where does the filtering take place, on the node or on the metrics server?
Ideally, the logging would be filtered as high as possible on the node (at
the call to submit a metric much like how the datapoint! macros are doing
it now for level and module).  I could see the flag server maybe coming
into play as a means to modify the log mask at runtime via a socket

**Comment by mvines** [comment]
Filtering must be on the node.  I don’t want to build a flag server right now, we don’t need this for a mainnet mvp

**Comment by pgarg66** [comment]
yes, it's on the node. The node pulls the config from the flag server and filters out the stats which should/(or not) be uploaded.

**Comment by mvines** [comment]
I think we've now addressed this with the various `datapoint!` macros

**Comment by sakridge** [comment]
I don't think we've fixed this. The datapoint macro is just a nicer way to write the metric submit, how does it help us solve the scaling problem?

**Comment by mvines** [comment]
We have datapoint levels now, eg `datapoint_trace()`, that are controlled by RUST_LOG.

**Comment by pgarg66** [comment]
Also, each level is individually rate limited. So, for example, even though _info level statistics might be dropped, _warn level statistics would be sent to the database..

**Comment by sakridge** [comment]
ok.
I guess I still want metrics that we can stick on a per-tx level and don't slow everything down to a halt and can also plug into profiler tools to make charts. But maybe that's a new issue.
