### ISSUE TITLE
Grinding attack on selecting replication proofs.

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#4157]
#### Problem

Leaders could grind the PoH value to influence which subset of replication proofs they will verify.

#### Proposed Solution

1. Use virtual PoH value instead of the real.

This increases the stake required to run the grinding attack.  The leader would need to be scheduled for consecutive blocks, and have a 2x faster asic.  See also #1558 

2. Someone needs to do some math,

Let's say there are 1m client PoRep proofs.  Leader wants to pick 100 of them, what are the odds of actually generating a random number where the 100 are picked, 1 / 1m choose 100?  10000 choose 100 is e241

tag: @sagar-solana @sakridge

**Comment by ryoqun** [comment]
I think we can close this for now. (let's reduce open issues!)
