### ISSUE TITLE
Rotate leaders on every slot

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4163]
##### Problem

Right now leader rotation occurs every 8 slots:
https://github.com/solana-labs/solana/blob/9b50583641653b6cb34bc5eb6f3ee88364837279/sdk/src/timing.rs#L14

Consecutive leader slots introduce large periods of downtime, and allow for large periods where a single leader is ordering transactions.

##### Solution

Let's bring this back down to 1, which might require further optimizations like:
* Speculative signature verification
* Speculative transaction execution

cc: #4162

**Comment by garious** [comment]
This problem description doesn't describe a problem. What's wrong with consecutive leader slots?
