### ISSUE TITLE
Introduce randomness to Avalanche 

### ISSUE THREAD

**Issue by sagar-solana** [solana-labs/solana#4195]
#### Problem

The current Avalanche design sets up the network based on confirmed stakes and pubkeys. This is very predictable and might allow eclipse attacks on lowly staked nodes in the lowest layers/neighborhoods of avalanche. Use a weighted selection or shuffle the nodes in a layer to pick the nodes in a neighborhood. 

#### Proposed Solution

Use blob signature(when its added) for easiest source of randomness, since we don't need to unpack the blob to get it.

1. Sort the nodes by stake weight and pubkey (as is already implemented)
2. Do a weighted selection/Shuffle the layers with the blob signature as the seed to generate the broadcast tree
3. forward the blob.

Tag: @aeyakovenko

**Comment by sagar-solana** [comment]
Yeah, I think it's blocked on blob sigs primarily.

**Comment by sagar-solana** [comment]
We can also use the blob.slot + blob.slot_index to seed rng and randomize avalanche.

**Comment by aeyakovenko** [comment]
@pgarg66 using bank slots still allows an attacker to carefully stake themselves such that they are scheduled ahead of the target and eclipse those specific blocks.  Per packet based on blob signature would force randomization occur in such a way that an attack is impossible.

**Comment by pgarg66** [comment]
@aeyakovenko , we can easily change it to use per blob shuffle once we have blob signatures. The current solution will allow us some change in the right direction, and a way to benchmark the perf of shuffling.

**Comment by pgarg66** [comment]
Leaving this issue open for per blob randomization (based on blob signature or blob slot + index)
