### ISSUE TITLE
[RFC] Smart Contracts Engine

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#420]
RFC is [here](https://github.com/solana-labs/solana/blob/master/rfcs/rfc-001-smart-contracts-engine.md)

Please comment!

@rob-solana I would love some feedback from you and @bhk.  basically, we have a `call` interface that takes a bunch of PubKeys and for some proofs of ownership.  This translates into memory regions that are loaded into the call.  I think the proofs of ownership can be treated like a privset.  But, any memory that is owned by the contract should be Writable, and in theory, all memory can be Readable.  The call should then be able to make subsequent calls with the subset of the privset.  

I think we should mark the caller, as in the call was initiated by the owner of this public key, and the contract itself should be able to asynchronously schedule other calls either as itself, or as the current caller.

Example is [here](https://github.com/aeyakovenko/solana/blob/tictactoe/src/tictactoe.rs)

Merged PRs (for doc only):
#489 
#439 
#428 
#423 
#419 
#396

**Comment by garious** [comment]
@aeyakovenko, can this be closed?
