### ISSUE TITLE
How do validators pay to vote?

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4212]
In a cluster with non-zero transaction fees, each vote a validator makes will also incur a fee.  How does the validator prevent its account from running out over the long term as a result?  Vote transactions are special and are not charged a fee?  Or are validators just expected to periodically withdraw their reward from the mining pool to replenish themselves?

**Comment by aeyakovenko** [comment]
@mvines they should use some random operational system account for voting fees

**Comment by mvines** [comment]
Ok, but that system account could run out of lamports eventually.  They're expected to periodically withdraw their validator rewards from the mining pool to replenish it?

**Comment by aeyakovenko** [comment]
Yea. They can fund however they want.  The amount of lamports held in that account should probably be small.

**Comment by mvines** [comment]
Ok cool.  So we probably just have a bit of mostly documentation work that describes to potential validators how we recommend they set this up.

**Comment by rob-solana** [comment]
need a vote account withdraw API

**Comment by rob-solana** [comment]
> Ok, but that system account could run out of lamports eventually. They're expected to periodically withdraw their validator rewards from the mining pool to replenish it?

seems that TX fees while a leader should more than cover it...

**Comment by mvines** [comment]
Nothing to do here
