### ISSUE TITLE
Replicators might need to run a replay stage

### ISSUE THREAD

**Issue by sagar-solana** [solana-labs/solana#4220]
#### Problem

Replicators use a window service to download a section of the ledger and store it. 
Currently the repair service they use drops all incoming blobs for the following reasons

- Blobs come from an "unknown leader". Replicators do not have a leader schedule so the window service drops all the incoming blobs. 
- Replicators setup their repair service with a default genesis blockhash. This causes all blobs to mismatch and be dropped.

#### Proposed Solution

There are two problems here. 
- Replicators need to know their genesis blockhash (doable via ledger). 
- Replicators need to run a replay stage 
  - That way they can focus on replicating confirmed blocks only. 
  - They will have a leader schedule to make sure they aren't being fed bad data.

Alternatively, replicators can run a custom window service that disables these checks but will remain unware of forks and can be fed bad data from rogue nodes on the network.

Tag: @sakridge @carllin @aeyakovenko

**Comment by sakridge** [comment]
Maybe we can just disable this unknown leader check or do the download in a different path. How is replay going to work on some subset of the ledger? We can do other things to see that we don't have bad data like ask multiple nodes.

**Comment by sagar-solana** [comment]
@sakridge, yeah I suppose since replicators do shutdown their window service once they figure out what they're going to replicate, it might be better to use a customized window service.
