### ISSUE TITLE
synthesized data accounts (system call)

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#4246]
#### Problem
interaction with runtime, system, bank is limited to tick_height, but needs to include a lot more stuff

among the stuff is recent bank hashes and their height #1131 #4245 

#### Proposed Solution
define and plumb synthesized (read-only) accounts into runtime

 - [x] define syscalls
 - [x] plumb recent bank hashes, height

**Comment by mvines** [comment]
The FeeCalculator associated with a given blockhash would be useful for programs to know too (some programs, like tic-tac-toe, want to pay for future transaction fees)

**Comment by mvines** [comment]
Might be a dependency of #1131
