### ISSUE TITLE
Validators can vote on banks that error

### ISSUE THREAD

**Issue by carllin** [solana-labs/solana#4277]
#### Problem
Certain errors like TransactionErrors should not be propagated to validators. Validators who see these types of errors should not vote on the containing banks. Currently, validators will still freeze/vote on these banks as long as they receive enough ticks.

#### Proposed Solution
Don't freeze banks that throw errors by removing them from BankForks and the replay stage progress map. @aeyakovenko

**Comment by aeyakovenko** [comment]
@carllin i think freezing is ok, we should mark these as dead.

**Comment by mvines** [comment]
Looks like this was fixed already via #4715
