### ISSUE TITLE
Update rust stable 1.34.2

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#4308]
Update to rust stable 1.34.2

The docs at https://github.com/solana-labs/solana/tree/master/ci/docker-rust have rotted a little.   There's no more "automation", it's all manual.  Once you do that, these two lines need an update: https://github.com/solana-labs/solana/blob/master/ci/rust-version.sh#L16-L17

**Comment by garious** [comment]
Why not do this in Silver Strand?

**Comment by mvines** [comment]
@danpaul000's got higher pri stuff to do first.
