### ISSUE TITLE
Remove the local storage_state in storage_stage

### ISSUE THREAD

**Issue by sagar-solana** [solana-labs/solana#4311]
#### Problem

Storage stage uses a local storage_state to service rpc requests about the storage blockhash and slot. This is redundant (and possibly masking issues) since the real storage account might not be in sync with the rpc storage_state. 

#### Proposed Solution

Remove the local redundant storage_state and use the one from the working bank in rpc instead. Problems that arise from doing this are going to need fixing (for example, if the advertise blockhash tx fails often we might have to send it via gossip). 

Tag: @sakridge

**Comment by sagar-solana** [comment]
If https://github.com/solana-labs/solana/issues/4534 is implemented we could leave the local storage state in place.

**Comment by ryoqun** [comment]
I think this issue can be close as this is related to archiver.
