### ISSUE TITLE
Test-drive grcov for coverage reports

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#433]
@marco-c advises `grcov` over `llvm-cov` for coverage reports. Test-drive it. Compare and contrast.

**Comment by garious** [comment]
I've not been able to get grcov or llvm-cov to report coverage from the coverage files output by `cargo-cov`.  Rust doesn't ship with llvm-cov and so I manually installed it via llvm-7, which is what Rust depends on. But still it seems only `cargo-cov report` knows how to read the files `cargo-cov test` generates.

**Comment by marco-c** [comment]
That's strange, cargo-cov should simply use -Zprofile, which should be supported by grcov. We are generating coverage reports for grcov itself using -Zprofile (but without cargo-cov).

Mind sending me the gcno/gcda files that you generate, so I can see if grcov is somehow failing to parse them?

**Comment by garious** [comment]
Got it working now @marco-c, thanks for the push. The run when I used grcov, I mistakenly ran `cargo cov test --lib` instead of `cargo +nightly test --lib`. I'm seeing the same output from your released macOS binary as I do when building it from source (on homebrew's latest llvm package). If I run into any trouble, I'm now in position to send you a PR. :)

**Comment by garious** [comment]
@rob-solana, @mvines, @marco-c, code coverage status:

* `cargo +nightly cov test --lib && cargo +nightly cov report` works well with on MacOS and Linux with minimal installation dependencies. It's just a little odd that it requires clang's libprofile to be installed. Not sure why that wouldn't be distributed with Rust.
* `grcov` and `lcov` works great on MacOS but not on Linux. Their Linux build is using Trusty whereas we run on Stretch, so surprised to see an issue there.
* I upload both the cargo-cov and lcov-via-grcov HTML reports to buildkite and we can see that grcov us unable to generate a report using the same gcno files that cargo-cov is using (and generated).
* codecov.io can consume the lcov.info file that grcov outputs, so as soon as that's working, we should have codecov.io and those nice coverage PR comments back again.

**Comment by rob-solana** [comment]
so good...

test driving it on WSL
