### ISSUE TITLE
Evaluate performance of real PoH

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4331]
With real Poh enabled (cc: #4292, #4117) the leader is now burning 1 core hashing, and validators are burning n+1 cores trying to keep up with the ledger as well as hash for themselves.   Moving PoH verification to the GPU (#4161) intuitively should help, but in parallel it'll be worthwhile analyzing the constraints and bottlenecks with the pure CPU implementation.   

Some ideas for where to look:
* Does a leader flame graph show that recording transactions is bottlenecked by the PohService?  If not can the PohService batch hash (cc: `NUM_HASHES_PER_BATCH`) more?
* Under what conditions do validators having trouble keeping up with PoH verification?  Would increasing the tick frequency to 100 or 1000 per second help?  If so what's the best looking tick rate?
* What does using real PoH do to max TPS currently?

The most visible outcome from this issue should be a recommendation for when we can enable real PoH for all the testnets and a list of perf issues that need to be fixed before that can happen.

**Comment by pgarg66** [comment]
>validators are burning n+1 cores

@mvines, I am wondering why this would be the case? Isn't each node running only one PoH service running continuous hash?

**Comment by mvines** [comment]
Yes one PoH service.  But additionally, as new entries stream in from the leader the PoH on those entries also need to also be verified -- this verification can/does happen in parallel.

**Comment by pgarg66** [comment]
So it would be 1+1 for the validators in a normal scenario. N > 1 when there's a network partition, and the validator can see leaders on all the partitions. Is that right?

**Comment by mvines** [comment]
Even with a single network partition, each entry can mostly be verified in parallel.   So if we get a batch of 10 entries in a tick, those 10 entries could be PoH verified on 10 different cores if available.  But yes in that case it shouldn't be 10 cores all the time, just long enough to hash through those 10 entries

**Comment by pgarg66** [comment]
Thanks @mvines got it now. Makes sense.

**Comment by pgarg66** [comment]
Reduced the hash batch size to 1. With this, the TPS performance is at par with ```sleepy_tick_producer```. The TPS drops by ~8% if we increase the batch size to 4, and drops by total ~15% if we increase the batch to 8.

**Comment by pgarg66** [comment]
Work targeted in this issue for v15 is done. We can move this issue to v16 (or close this and open a new one).
