### ISSUE TITLE
Figure out details of Archiver bootstrapping

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4344]
An Archiver needs a minimal set of lamports before it can start submitting proofs.  Right now this is done via a normal airdrop.  But for a mainnet there needs to be something more restrictive to prevent abuse:
* Rate limit replicator airdrops by IP?
* Make the replicator perform a PoW?
* Something else?

**Comment by mvines** [comment]
@jstarry, when you get to this issue I suggest chatting with @sagar-solana

**Comment by sagar-solana** [comment]
We _could_ make validators bootstrap replicators. 

- They have some incentive to do so; more replicators equals more proofs to verify which leads to higher rewards. Each validator will have some proof verification capacity and it can volunteer to fund the replicator until that validation capacity is reached?

- We could give validators a kickback for setting up replicator accounts.

**Comment by mvines** [comment]
That seems neat!

**Comment by jstarry** [comment]
@sagar-solana would it make sense for the validator to get a portion of the proof reward/rent if it helped the replicator out by eating the cost of the tx fee for the proof?

Seems like the replicator shouldn't be able to get full rent while bootstrapping unless we have some PoW for new replicators like @mvines suggested.

**Comment by sagar-solana** [comment]
Taking a step back, as far as storage program(PoRep) is concerned, nodes have 2 keypairs, 1 for their storage account and one primary one (system account). They use the primary keypair to pay for txs and the storage account is what carries proofs/verifications and rewards.

To bootstrap a Replicator, Validators need to not only cover the tx fee of setting the accounts but they also need to provide some balance in both those accounts (enough such that the replicator can start submitting proofs).

So I was thinking that the validator gets some storage "points" (a reward that can be claimed) for setting up replicator accounts. But the obvious problem with that would be validators just harvesting points by creating a bunch of wasteful replicator accounts. 

The main things we need to defend against are
1. Replicators making Validators waste lamports setting up accounts for them (storage + system accounts) 
2. Validators possibly abusing any points they receive by setting up many of these accounts
3. Someone creating multiple replicator accounts and just draining the bootstrapped balance from them and collecting lamports that way...

When I suggested giving the validators points, I was mainly addressing 1.
@mvines and I just discussed this F2F and came up with a combination of PoW from the Replicator + kickbacks to the validators when the first proof is subitted. 

The bootstrapping process would look something like this 
1. Replicator gets a blockhash from a Validator (via RPC), and spending some time hashing it.
2. Validator quickly verifies that the Replicator did real work on that blockhash
3. Validator sets up the Replicators' storage and primary accounts with sufficient balance to get the Replicator going
4. As part of the account setup, the Replicator's account keeps track of the Validator that sponsored the account. 
5. The first proof the Replicator submits will unlock the credit for that Validator
6. Replicator should be good to start earning rewards.

Mainly, we concluded that we need a proper design that describes the whole bootstrapping process. Do you want to take a shot at it?

**Comment by jstarry** [comment]
@sagar-solana yeah I'd love to.

The bootstrapping process makes sense to me but I have a few questions..

3. What incentive does the Validator have to actually bootstrap the accounts once the Replicator does real work? For example, a Validator could issue a challenge and then ignore the PoW solution, wasting the Replicator's work. Is the idea that the sponsor credit is enticing enough such that the Validator would definitely bootstrap after receiving a solution?

5. How would unlocking work? Would this mechanism be a part of some program on chain?

**Comment by sagar-solana** [comment]
> what incentive does the Validator have to actually bootstrap the accounts once the Replicator does real work? For example, a Validator could issue a challenge and then ignore the PoW solution, wasting the Replicator's work. Is the idea that the sponsor credit is enticing enough such that the Validator would definitely bootstrap after receiving a solution?

So when a replicator wants to join the network, it connects to a validator, gets a blockhash and performs some number of hashes. The validator then verifies that some work was done. Validators don't initiate it, the replicator does. And yeah the hope is that the kickback is lucrative enough. 

> how would unlocking work? Would this mechanism be a part of some program on chain?|

Yeah it would be handled by the storage program, when a replicator submits its first proof, the program will credit the validator's storage account for setting it up.

**Comment by ryoqun** [comment]
close for now because archiver's direction is unclear?
