### ISSUE TITLE
vote accounts are being staked like stake accounts

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#4374]
#### Problem
 since #4213 and associated bridge PRs, vote accounts (which used to be stakes) have unnecessary lamports associated with them.

 #### Proposed Solution 
- [x] drop the stake-level funding of vote accounts in genesis and fullnode.sh
- [x] fund the accounts with some minimum balance that supports the amount of state required CC #4372

**Comment by mvines** [comment]
I think I've done all this now
