### ISSUE TITLE
need RPC for vote account?

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#4383]
#### Problem
Passive stakers who want to bet on a node's work have no way to determine the node's vote account id (necessary to stake).    They could possibly look at current stakes (rpc get_epoch_vote_accounts()), but maybe a more direct mechanism would be more appropriate.

#### Proposed Solution
add an RPC (get_vote_account_id()) that would supply the node's voting target account, the one to which a staker would want to delegate

@aeyakovenko @ericlwilliams @mvines @garious  thoughts?

**Comment by aeyakovenko** [comment]
Can’t they advertise it of chain?  It’s not a bad idea to keep it on chain if that account rotates.   The delegates can then point to a domain.

**Comment by rob-solana** [comment]
I think RPC is off-chain, and this is advertising it separately, which I'd think is something want to help build.

You'd call a specific node and ask it to sign (nonce, vote_account_id) with the voting keypair.

**Comment by mvines** [comment]
IMO need not be a part of MVP, where nodes could buy Facebook ads for their vote pubkeys even.  We could easily build this later when there’s an itch.  I like the idea though.

**Comment by rob-solana** [comment]
closing as unnecessary
