### ISSUE TITLE
Rust BPF: Using customized sysroot requires maintaining a fork

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#4389]
#### Problem

There are multiple customizations to the Rust sysroot (liballoc, libcore, compiler-builtins, etc...) that require we maintain our own fork/repo.  Issues #3101, #3102, multi-thread related features are the most obvious but there are other changes related to interdependencies related to xargo that also require customizing the sysroot `Cargo.toml` files.

**Comment by jackcmay** [comment]
@dmakarov We can close this now that you've combined the custom sysroot into the tree?

**Comment by dmakarov** [comment]
Yes.

**Comment by jackcmay** [comment]
Great work @dmakarov , we are no longer dependent on a bunch of forks for the custom sysroot
