### ISSUE TITLE
No generic way to transfer account ownership

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#4400]
#### Problem

There's no generic instruction to move an account between public keys.  Instead, each program that implements a notion of fungible tokens also implements a way of transferring some tokens. "all" tokens is viewed as a specialization of "some" tokens, but "all" tokens doesn't require any notion of fungibility. Moving "all" equates to treating `Account.data` as opaque data, and doesn't need to be program-specific.

#### Proposed Solution

Make `KeyedAccount::key` mutable and add rules to the runtime dictating what a valid change to that key is.  It would be valid, for example, to swap the keys of two accounts where both keys are signed. It'd also be valid to swap the keys of two accounts where one is signed and the other was initially `Account::default()`.

Concerns:
* Say a program saves some pubkey in an "authorized users" list and then the owner of that pubkey signs a transaction to swap its account data with another account with the same program_id.

tag: @aeyakovenko

**Comment by aeyakovenko** [comment]
The program needs to control the rules, not the runtime.

**Comment by garious** [comment]
It'd be neat if only programs defined ownership rules. I'm not sure that needs to be the case.  The big drawback of program-defined rules is that each action would need to be an `Instruction` instead of a program just writing to a `&mut KeyedAccount::key` and making it the runtime's job to reject only the modifications that'd allow for theft or nondeterminism.

**Comment by aeyakovenko** [comment]
I just have a strong gut reaction against modifying the runtime when it’s possible to do the same thing without it. This only solves token ownership, and not really a general purpose way to compose state.

**Comment by aeyakovenko** [comment]
Like the stuff I want to do is define a contract that represents some unspent external erc20, and have a single interoperable program for tracking scarcity as defined by the amount of the unspent external erc20.  That single program should be reused by every random new asset we add.

**Comment by garious** [comment]
Since the runtime currently doesn't give meaning to `is_signer`, let's keep in that way for now.
