### ISSUE TITLE
Can't transfer Token-defined tokens in response to external state changes

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#4408]
#### Problem

Can't transfer Token-defined tokens in response to external state changes, such as a player X winning a game of tic-tac-toe. And more generally, can't have one program execute in response to a state change, especially if the change drops its lamports to zero.

#### Proposed Solution

Add `Token::transfer_if_eq()` to transfer only when an account has some expected data.

```rust
// Start a game of tic-tac-toe between Alice and Bob
let msg0 = Message::new([
    ttt_instruction::init(&game_id, &alice_id, &bob_id),
]);

// Carol commits: should game_id ever contain a proof that X won, transfer 42 tokens to Dan.
let expected_account_data = ttt_helper::create_winner_data(&game_id, &alice_id, &bob_id, IS_X);
let msg1 = Message::new(vec![
    token_instruction::transfer_if_eq(&token_contract_id, &game_id, &ttt::id(), expected_account_data, 42, &carol_id, &dan_id),
]);

// Cause the account at game_id to show X as the winner, and force the token contract to execute.
let msg2 = Message::new(vec![
    ttt_instruction::move(&game_id, &alice_id, 2, 2),
]);

let msg3 = Message::new(vec![
    token_instruction::execute(&token_contract_id)
]);
```

Concerns:
* The game account is discarded after its lamports drop to zero. How do we keep it around long enough to analyze who won? Perhaps PubSub needs to include a Merkle path?
* What happens if Alice reuses the same public key until she wins?
* We add `transfer_if_eq(expected_data, actual_data)` instead of `transfer_if(actual_bool)` because we need to check the game_id. A slippery slope to needing `transfer_if_ne`, `transfer_if_gt`, etc?
* Must we couple conditionals with actions? if_eq and transfer()

tag: @aeyakovenko

**Comment by aeyakovenko** [comment]
1. Game program can let the winner delete the account
2. the transfer should be tied to a specific game instance

**Comment by garious** [comment]
1. No, let's have Carol/Dan add some lamports to Alice/Bob's game to effectively "pay rent" on the game_id account.
2. That'd mean the TicTacToe dashboard needs to implement a counter, increment it for each game, and add that count to the game_id.
