### ISSUE TITLE
Rename solana-fullnode to solana-validator

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4409]
#### Problem
The name of the executable to start a validator is `solana-fullnode`, which is overly broad.

#### Proposed Solution
Rename solana-fullnode to solana-validator.  Also rename `core/src/fullnode.rs` to `core/src/validator.rs`

**Comment by garious** [comment]
And the struct Fullnode to Validator. And any mention of Fullnode in the book.

**Comment by mvines** [comment]
Done
