### ISSUE TITLE
Validators prune each other when they are not supposed to due to Votes

### ISSUE THREAD

**Issue by carllin** [solana-labs/solana#4413]
#### Problem
Validators are receiving the same vote message on gossip from the same peer, which is causing them to prune each other. This can be seen on a two node testnet with just a leader and a single validator

**Comment by sagar-solana** [comment]
May or may not be related, but the nodes are pruning the owner of the value, not the sender. 

Still need to figure out why the prunes are being generated in the first place.

@aeyakovenko, why prune the node that created the CrdsValue instead of the one that sent it to you? Is this how are prunes supposed to work?

**Comment by aeyakovenko** [comment]
is the logic flipped?  anytime a crds value is updated it should reset the timer.

**Comment by sagar-solana** [comment]
> is the logic flipped?
I don't think so, this seems deliberate. We have the sender's Pubkey but when we prune we use the CrdsValue's Pubkey. That would prune the creator of the CrdsValue and not the sender that caused the duplicate? I'm sure there was a good reason for this, haha

```
    fn handle_push_message(
        me: &Arc<RwLock<Self>>,
        from: &Pubkey,
        data: Vec<CrdsValue>,
    ) -> Vec<SharedBlob> {
```

```
pub fn process_push_message(&mut self, values: Vec<CrdsValue>, now: u64) -> Vec<Pubkey> {
        let labels: Vec<_> = values.iter().map(CrdsValue::label).collect();

        let results: Vec<_> = values
            .into_iter()
            .map(|val| self.push.process_push_message(&mut self.crds, val, now))
            .collect();

        results
            .into_iter()
            .zip(labels)
            .filter_map(|(r, d)| {
                if r == Err(CrdsGossipError::PushMessagePrune) {
----->              Some(d.pubkey())
```

**Comment by aeyakovenko** [comment]
@sagar-solana originally i didn't have the gossip message double wrapped.  Each value is signed, but since messages are signed as well we can use that as a way to reset the TTL for crds.

**Comment by sagar-solana** [comment]
Curious as to why you think this is a TTL issue? If a push contains a duplicate CrdsValue, all we have to do it prune the sender of that Push right ?

**Comment by aeyakovenko** [comment]
@sagar-solana oh, i am confused.  i was thinking purge from the crds, not prune :)

**Comment by sagar-solana** [comment]
haha okay that makes sense. yeah this is about prune :D

**Comment by aeyakovenko** [comment]
@sagar-solana so is this just a validator false positive?  Each one maintains a different set for each origin.

**Comment by sagar-solana** [comment]
>  this just a validator false positive

What exactly? My bad. There are two issues at play here. 
1 - The fact that the prune is even happening (which I'll look into) on a two node network
2 - The prunes are being pointed at the creator of the crdsvalue where as it should be pointed at the sender of the push

**Comment by aeyakovenko** [comment]
@sagar-solana for each creator, we add the sender to the prune set.

**Comment by sagar-solana** [comment]
> Two nodes should prune each other when origin is self.

Yup that makes sense. 

I'll take a second look at the rest of the prune logic.

**Comment by sagar-solana** [comment]
@aeyakovenko, so the active set contains <Pubkey, Bloom> right. The Bloom for every pubkey should be initialized with that pubkey right ? Otherwise CrdsValues might be pushed back to the originator?

**Comment by aeyakovenko** [comment]
@sagar-solana i don't think we include self in the active set

**Comment by aeyakovenko** [comment]
oh i see.  yea, that might be correct.

**Comment by sagar-solana** [comment]
Yeah I'll try that. Because that's what I'm seeing right now. Seems to push the same message back and forth. I don't see it happen with ContactInfo, only with votes and epochstates so I'll take a closer look. It shouldn't be affected by what the crdsvalue is.

**Comment by sagar-solana** [comment]
Actually, the loop should occur only once and then the bloom will look like <Origin, Set {Origin}>. So it's not a huge deal right?

**Comment by sagar-solana** [comment]
@carllin I don't really see an issue here. I can explain when you're in. Two nodes for me are happily pushing to each other even after prunes (prunes are different from what you think). 

@aeyakovenko my last comment make sense?

**Comment by sagar-solana** [comment]
Don't question the Anatoly. ;)

Prunes are working as designed.
