### ISSUE TITLE
Tests failing locally: counter::tests::test_lograte and counter::tests::test_lograte_env

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#4416]
#### Problem
`test_lograte()` and `test_lograte_env()` fail locally (macOS).
This appears to be due to use of `env::set_var()`

#### Proposed Solution
@pgarg66 writes: "We can remove the set_var() and change the log level for metrics to error. That will fix the issue"

**Comment by lazaridiscom** [comment]
=> add label `macOS`
