### ISSUE TITLE
Move get_ip_addr parsing to Rust

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#443]
We don't have a framework for Bash tests and code like this is proving to be either unreliable or too hard to grok for anyone but its author to maintain:

```
ifconfig | awk '/inet(6)? (addr:)?/ {print $2 $3}'
addr:10.138.0.3Bcast:10.138.0.3
addr:fe80::4001:aff:fe8a:3/64
addr:127.0.0.1Mask:255.0.0.0
addr:::1/128
```

@sakridge points out that Rust offers `get_ip_addr`. Can we use it to move that Bash code into Rust?

**Comment by rob-solana** [comment]
is this still relevant?  I think the answer is "no"
