### ISSUE TITLE
Document replicators in book/src/testnet-participation.md

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4433]
When replicators are stable on a large multi-node testnet, document how to use them in the testnet participation document

**Comment by sagar-solana** [comment]
@mvines, is it okay to wait for the standalone executable before documenting this?

**Comment by mvines** [comment]
For this issue I was thinking we’d discuss using solana-replicator.exe (all cli based)
The solminer gui is then essentially a consumer of this doc

**Comment by sagar-solana** [comment]
ah gotcha, okay I'll start on it then. With Linux for the moment but I suspect it'll translate pretty much directly to windows (minus install procedure?)

**Comment by mvines** [comment]
Yep should be about identical on windows with slashes flipped.  We have all the cli tools, including solana-install-init.exe available.  I don’t want to assume bash though, so just individual shell commands

**Comment by sagar-solana** [comment]
yeah no bash just direct binary usage.
