### ISSUE TITLE
[RFC] Consensus

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#445]
RFC is [here](https://github.com/solana-labs/solana/blob/master/rfcs/rfc-002-consensus.md) (afer #439 is merged)

@bhk @rob-solana 

RFC PRs:
#439

**Comment by mvines** [comment]
What's the purpose of this issue?

**Comment by aeyakovenko** [comment]
@mvines to track the consensus thing. i need to update the rfc
