### ISSUE TITLE
Investigate using AVX for poh generation

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4469]
If the AVX instruction set could be used to generate PoH fast enough on the CPU that would keep the GPU free for PoH and signature verification.

**Comment by sakridge** [comment]
https://bench.cr.yp.to/impl-hash/sha256.png

Zen processors with the sha2 instruction seem to be ~4x faster than skylake or kaby lake without it.

openssl has a multi-buffer AVX and AVX2 implementation:
https://github.com/openssl/openssl/blob/master/crypto/sha/asm/sha256-mb-x86_64.pl

Shows about a 3x speedup on Skylake with AVX2. AVX-512 could be faster, but requires Skylake-x (server parts) and newer.
