### ISSUE TITLE
implement cluster economics for validator rewards

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#4470]
#### Problem
cluster economics exist mostly as a proposal in the book (ed_overview.html)

https://solana-labs.github.io/book/ed_overview.html

the book is out of date, implementation now targeted based on inflation-based scheme

https://github.com/solana-labs/solana/issues/4491

this is a tracking issue for implementation of rewards for validators, replicators

#### Proposed Solution
Basics:

There are 2 rewards regimes: validator (staking) and replicator (porep).

1. for each regime, tally the number of "points" earned as of the end of the last epoch (bank can do this, build a synthetic account with the data), update an historical total?
2. "fund" each regime's rewards pools with some an inflation-dictated number of tokens
     * do this in the bank, outside of the runtime, so no runtime special cases
     * roll these funding actions into bank capitalization
3. calculate each regime's "point reward" (unit of reward) which is rewards-tokens/points-earned
4. satisfy rewards redemption requests out of pools (payout is points redeemed * point-reward), pools have all the tokens necessary to pay rewards, but are not infinite

Point reward is expected to vary over time.  More participants in an epoch tends to lower the points reward.  Points reward is a running average over the lifetime of the network or just uses the most recent epoch?

Definition of a point:
PoRep: a verified PoRep?  How do validators of PoReps get paid?
Validator: each max-lockout is a credit, a "point" == credits earned/lamports staked

In order to be able to pay out properly in validators regime, we need to pay according to stake that was actually exposed during the previous epoch.  We can't let stakers open an account with 1 token, build up a bunch of rewards, then push in a bunch of tokens right before redemption.  This implies an "activate stake" instruction that resets credits observed...

Activate Stake:
1. pay rewards according to current points ((credits - credits_observed) * currently activated stake)
2. update credits_observed to credits of the delegate (i.e. zero-out credits)
3. update "activated stake"

TODO:

- [x] tally points at end of epoch (beginning of next epoch) for each regime (implies a bank scan or another cache in the case of porep?)
    - [x] validators
    - [ ] replicators <=== out of scope, see #4776
- [x] "Inflation" that carries rewards config (e.g. current point-reward value, total points?, etc.), placed in genesis_block that the Bank uses to fund rewards and pools
- [x] write rewards redemption code in validator regime
- [x] write the code that keeps track of total lamports in the system
- [x] implement activate stake #4517

Missing from this proposal:
details on redemption to replicators and validators working on porep proofs

**Comment by rob-solana** [comment]
@aeyakovenko @ericlwilliams 
would you guys review and put comments here?  I want to use a github issue instead of a project for this work

**Comment by rob-solana** [comment]
CC @mvines @sagar-solana

**Comment by aeyakovenko** [comment]
@rob-solana woot!  looks good to me
