### ISSUE TITLE
Only one append_vec is created for a given fork

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#4476]
#### Problem

Only a single append_vec is created for a given fork in accounts_db. This serializes the writing and also doesn't allow for multiple SSDs to access append_vecs in multiple threads. Banking performance does not scale with multiple SSDs.

#### Proposed Solution

Create an append_vec per path for each fork and also maybe that many per number of banking_stage threads.

**Comment by sakridge** [comment]
https://github.com/solana-labs/solana/blob/b5324063f1a60076ccc96ff69fd396027729a4b1/runtime/src/accounts_db.rs#L325

If this line is made into something like `while candidates.len() < self.paths.len() {` that would create multiple append_vecs in the fork although not guaranteed to be in each path.

**Comment by rob-solana** [comment]
would #4523 address this?  if an append_vec for a fork is out, busy, another will be created

**Comment by sakridge** [comment]
@rob-solana Seems like it. Just need to double check that the desired behavior is happening with many banking threads.

**Comment by rob-solana** [comment]
any update?

**Comment by sakridge** [comment]
@rob-solana Yea this seems to be fixed. I think we can close it.
