### ISSUE TITLE
Remove tick_height from program entrypoint signature

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4482]
#### Problem
https://github.com/solana-labs/solana/blob/58295b825dc90aac845327e702d81da0ea10c1ff/sdk/src/instruction_processor_utils.rs#L14

#### Proposed Solution
Remove it, it was added for the tic-tac-toe example but no longer really used by that example.  If future programs require the tick height again, a new syscall account can be easily added for it

**Comment by CriesofCarrots** [comment]
I'm in this neighborhood

**Comment by CriesofCarrots** [comment]
Whoops, looks like the storage program uses tick height. I'll take a crack at the syscall account implementation.
