### ISSUE TITLE
expose stake-weighted hash-count per tick to programs

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#4503]
#### Problem
 no wallclock available to programs

 we have tick_height and we have hashes_per_tick, but hashes_per_second, which needs to be a stake-weighted value

 #### Proposed Solution
- [ ] include hashes-per-second in each vote, save the value in the vote account
- [ ] on vote updates and stake updates in the bank, calculate a stake-weighted hashes-per-second and store it in the tick_height synthetic account
- [ ] rename the tick_height syscall?

**Comment by rob-solana** [comment]
CC @aeyakovenko

**Comment by rob-solana** [comment]
maybe only do this on an epoch boundary

**Comment by aeyakovenko** [comment]
Votes should have a wallclock, and gossip should enforce it. At the epoch interpolate and compute the hashes per second value and provide access to that value with a synthetic account.
