### ISSUE TITLE
stake activation

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#4517]
#### Problem
part of  #4470 

In order to be able to pay out properly in validators regime, we need to pay according to stake that was actually exposed during the previous epoch. We can't let stakers open an account with 1 token, build up a bunch of rewards, then push in a bunch of tokens right before redemption. This implies an "activate stake" instruction that resets credits observed...

 #### Proposed Solution
Activate Stake:

pay rewards according to current points ((credits - credits_observed) * currently activated stake)
update credits_observed to credits of the delegate (i.e. zero-out credits)
update "activated stake"

`activate_stake()` instruction to stake_api
* `activate_stake()` must reset rewards on any currently activated stake
    * means it needs the vote_account
    * means it needs a rewards pool account, in order to do any necessary payout
    * activated stake must be <= lamports in account

Questions: 
* does activate stake pay out if the currently activated stake wasn't actually active (i.e. counted) during some epoch?  answer: yes
* stake activation/de-activation needs to be rate-limited per-epoch (at most 1/3 of total may change), can do this per-account?  if rate limits are enforced globally, what happens if a staker misses the boat?

**Comment by rob-solana** [comment]
CC @aeyakovenko

**Comment by rob-solana** [comment]
partially implemented in #4600, but instead of a new API, the DelegateStake API was updated

**Comment by mvines** [comment]
Oops, this:
> Fixes #4470 #4517
only fixes the first PR and not the second (ie, this PR!)
