### ISSUE TITLE
Blobs recovered from erasure don't go through the same integrity checks as those received in WindowService

### ISSUE THREAD

**Issue by carllin** [solana-labs/solana#4584]
#### Problem
WindowService runs a suite of integrity checks on data/coding blobs before putting them in blocktree here: https://github.com/solana-labs/solana/blob/master/core/src/window_service.rs#L78. Blobs recovered via erasure don't go through these checks

#### Proposed Solution
1) Verify blobs recovered from erasure pass the same integrity checks and purge erasure blobs that fail the checks. @rob-solana, @mark-solana 

2) Slots with recovered blobs that fail integrity checks should be marked in the dead slots column family.

3) Replay stage needs to be notified of dead slots (a channel? augmenting `get_slot_entries()` to notify callers that a fork is dead)

**Comment by rob-solana** [comment]
sooo cool!
