### ISSUE TITLE
windows port: solana-install doesn't set PATH correctly

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4609]
When `solana-install.exe init -u http://edge.testnet.solana.com:8899/` is run, the resulting PATH is wrong:
```
Please update your PATH environment variable to include the solana programs:
    PATH="\\?\C:\Users\mvines\.local\share\solana\install\releases\BEGV91SAT1mZMyDL9uiFxxP3QSCfwajsRehT63AoVhiX\solana-release\bin:$PATH"
```

1. `\\?\C:\` prefix is weird
2. The symlink `active_release` is dereferenced to `BEGV91SAT1mZMyDL9uiFxxP3QSCfwajsRehT63AoVhiX`, which is incorrect as a subsequent `solana-install update` will result in a different release hash and the PATH will need to be modified again

**Comment by SquareandCompass** [comment]
Please update your PATH environment variable to include the solana programs:
    PATH="/root/.local/share/solana/install/active_release/bin:$PATH"
