### ISSUE TITLE
Schedule stakes instead of leaders

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#4616]
#### Problem

There are a lot fewer leaders, and liveness of the chain depends on leader availability. 

#### Proposed Solution

Schedule stakes instead, and allow for stakes to switch leaders mid epoch.

This would greatly increase the complexity of blocktree and Tower.

**Comment by rob-solana** [comment]
allowing stakes to change nodes mid-epoch complicates rewards redemption and slashing

**Comment by aeyakovenko** [comment]
@rob-solana what about allowing the stake to propose a concurrent block with the leader it is assigned to?
