### ISSUE TITLE
Windows port: make .exe extension implicit for |solana-install run|

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4618]
Right now `solana-install.exe run -- solana-replicator` will fail here:
https://github.com/solana-labs/solana/blob/6926e89e865ea161a4681268d33dbac56b82ea7e/install/src/command.rs#L752-L757

The user must instead specify `solana-install.exe run -- solana-replicator.exe`, which is weird for Windows users who know the .exe extension is implicit.

Let's fix this by also checking for `full_program_path` with `.exe` appended

**Comment by lazaridiscom** [comment]
@mvines , seems closable:

https://github.com/solana-labs/solana/blame/b997d3eb4e57728dfbd251007a6684db7c49a34c/install/src/command.rs#L899-L902

#4930

**Comment by mvines** [comment]
Oh, yep.  Thanks!
