### ISSUE TITLE
Blobs should WeakRef their respective recyclers

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#462]
If Blobs and Packets are only going to be allocated by recyclers, then they should hold a WeakRef to it and implement the `Drop` trait to pass that memory back to the recycler. If this is implemented, remove any references to `Arc::strong_count` or `Recycler` outside `packet.rs`.

**Comment by garious** [comment]
I don't think this can be done until `alloc` is stabilized, which should let Weak be passed across threads.

**Comment by rob-solana** [comment]
this would be nice....
I see a ton of 
```
WARN 2018-07-12T22:28:50Z: solana::packet: Recycled item still in use. Booting it.
```
when I run the multinode demo

**Comment by garious** [comment]
Those are supposed to be fairly rare and if happen too often will slow things down. If I had to guess, it's because I changed an `Arc` to an `&Arc` and didn't delete the `clone()`.

**Comment by rob-solana** [comment]
validator currently generating that log message to drown out all other log messages

**Comment by garious** [comment]
Recyclers were removed a long time ago
