### ISSUE TITLE
Look into using AVX for PoH verification

### ISSUE THREAD

**Issue by TristanDebrunner** [solana-labs/solana#4623]
PoH verification continuously uses one or more CPU cores on machines that don't have CUDA GPUs. Using SIMD instructions to complete parallel verification could significantly reduce CPU usage for such clients.

**Comment by TristanDebrunner** [comment]
Rust stable now exposes AVX2. AVX512 is still unstable, so getting to that point is likely not worth the effort. There is also the `simdeez` crate, which enables creating SIMD implementations on SSE2, SSE41, AVX2, and sacalar fallback with a single function def.

There are parallel multi-buffer SHA256 implementations as well such as https://github.com/openssl/openssl/blob/master/crypto/sha/asm/sha256-mb-x86_64.pl and https://github.com/kste/sha256_avx. The latter looks abandoned, but it does compile and run.

Using `simdeez`, it looks pretty straightforward to port a parallel SIMD SHA256 hasher to pure rust, and have it be portable to older SIMD paradigms. With `simdeez`, we _should_ also eventually get AVX512 support for free.

**Comment by sakridge** [comment]
Should we combine with #4469 ?

**Comment by sakridge** [comment]
Could look at ISPC as well: https://ispc.github.io/

**Comment by TristanDebrunner** [comment]
#4469 seems somewhat separate from my research. PoH generation can take advantage of SIMD to some extent, though I don't understand exactly how. However, it looks like doing 4-8 (or 16 with AVX512) parallel hashes for verification will still take better advantage of the SIMD capabilities.

**Comment by TristanDebrunner** [comment]
Looking at ISPC, the programming model looks really similar to CUDA, so I like the idea of trying that first.

**Comment by TristanDebrunner** [comment]
Do we want SIMD instruction set selection to happen at compile time or run time?

**Comment by mvines** [comment]
If at all possible runtime.

**Comment by TristanDebrunner** [comment]
It looks like it should be easy to compile the ISPC for all targets, then use rust macros like `is_x86_feature_detected!("avx2")` to do the selection at runtime

**Comment by sakridge** [comment]
I missed that #4469 was for generation because it says' keep the CPU free, but I didn't think we were considering generation on the GPU since it would always be slower unless we need to generate thousands of POH streams in parallel.

**Comment by TristanDebrunner** [comment]
Do we want this code somewhere in solana, or in solana-perf-libs?

**Comment by mvines** [comment]
In solana!  No more growing solana-perf-libs please
