### ISSUE TITLE
Setup TdS testnet

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4629]
For TdS, we'll want the following testnet setup:
1. Cluster endpoint of tds.solana.com (assuming we don't come up with a better name...)
1. Airdrops disabled (depends-on: #4540)
1. Genesis block provisioned with an initial set of accounts for all the participants (depends-on: #4539)
1. A small handful of Solana-run validators (3 including the bootstrap leader?).  CPU only for initial setup and testing but then we'll flip them to GPU when TdS starts.
1. A blockexplorer node
1. A bench-tps client that for initial testing generates some baseline load (say ~1000 TPS)
1. Manual buildkite setup to manage the testnet, like what we did for the "demo testnet".  The ledger should not automatically reset every 24 hours, the cluster just runs until it's dead 💀 
1. Use the "auto" configuration for hashes-per-tick
1. Setup the genesis block to mint 500M SOL to ensure a high-rate of inflation during the stage (`--lamports` set to 500M*2^34)

**Comment by danpaul000** [comment]
PR #4762 should address parts 1 and 4-8.  

Buildkite pipelines are in place.  They currently point at master, will change this to v0.16 once it is branched.

**Comment by danpaul000** [comment]
Some work remains to get the settings correct for 2, 3 and 9.  Should spin up a dedicated influxDB server for this testnet as well.

**Comment by danpaul000** [comment]
@mvines it looks like 2 and 3 can be accomplished by setting: https://github.com/solana-labs/solana/blob/master/net/net.sh#L58 is that correct?  
If so:
1) I'll need to elevate this option to testnet-manager.sh
2) Where/how to maintain this file to be up to date with validator participation and accessible via on-demand builds on build kite.

**Comment by mvines** [comment]
Yep.

> Where/how to maintain this file to be up to date with validator participation and accessible via on-demand builds on build kite.

I just enabled wiki -- https://github.com/solana-labs/solana/wiki
How about creating a page there that lists all the pubkeys we want to provision.
