### ISSUE TITLE
PoH verification should dynamically switch between CPU and GPU based on size

### ISSUE THREAD

**Issue by TristanDebrunner** [solana-labs/solana#4632]
#### Problem

PoH verification can happen on both CPU and GPU now, but where it happens is decided at compile time. A small verification batch will execute faster on the CPU, so when the GPU is enabled, a runtime check should schedule the batch to either the CPU or the GPU.

#### Proposed Solution

Add a runtime check that schedules the verification to either the CPU or the GPU.

**Comment by pgarg66** [comment]
@TristanDebrunner I can take over this issue for v16 (given you are OoO next few days). If we cannot get this in for v16, we can reassign it to you.

Thoughts?

**Comment by TristanDebrunner** [comment]
I have some changes in #4734 that should make this easier, and the new SIMD poh-verify will also need the same runtime check. I can try to get that in today, then hand this off to you?
