### ISSUE TITLE
Build/document validator-specific metrics database/visualizer

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4638]
When running my own validator, I only have logging at my disposal to monitor its activity.

Let's:
* [x] Develop some scripts to enable validators to easily start their own influxdb/grafana instance (highly leveraging #4376)
* [ ] Develop a "Validator Dashboard" for grafana, which probably looks similar to the current testnet dashboard but is specific to one validator
* [ ]  Develop an example Grafana Alert to demonstrate how to be notified when interesting events occur (such as validator not voting, validator lamport balance too low)
* [x]  Document how a validator could use (1), (2) and (3) to monitor their validator

**Comment by chris-remus** [comment]
I feel validators would find starting points for a dashboard and alerting service as very valuable tools.

You can find some Cosmos discussion on this topic, including sample dashboards, [here](https://forum.cosmos.network/t/monitoring-alerting-for-your-validator/446/31).

As you'll see, the discussion was somewhat piecemeal and incomplete. It takes quite a bit of work to piece the information together to build a workable dashboard and alerting system.

For example, when I tried implementing the dashboards, the metrics had changed in later cosmos-sdk versions. This rendered the older dashboards pretty useless.

I'm currently building a Grafana dashboard, have an Icinga monitoring system watching my systems and am working on [an alerting tool based on Certus One's API.](https://github.com/chris-remus/chainflow/tree/master/tools/monitoring-and-alerting/cosmos-sdk-missed-block-monitor) The latter will alert me when my validator misses a block.

Figment's feedback in the forum post is consistent with the alerts you can subscribe to at hubble.figment.network. Relying on a third party service is uncomfortable for most validators.

My experience with the alerts is that they're somewhat inconsistent. They're OK for a delegator keeping track of a validator. They're not reliable enough for a validator operation to rely on.

On the Livepeer side, I find [this Telegram bot](https://forum.livepeer.org/t/transcoder-campaign-0x525-with-telegram-bot/588) to be very useful. You can see it in action in my Transcoder Telegram channel [here](https://t.me/chainflowlivepeertranscoder).

For another take on a Livepeer dashboard, you can see the one Scout is building (and hoping to sell) to transcoders [here](https://scout.cool/livepeer/mainnet/dashboards/5ca0ee4a95e43100170a7226). You can see more transcoder stats [here](https://www.supermax.cool/livepeer/mainnet/activity?filter=%7B%22search%22%3A%220xd0aa1b9d0cd06cafa6af5c1af272be88c38aa831%22%7D).

In my experience, from a high-level, what's most important to validator is -

1 - System health, i.e. is the server running OK?

2 - Validator health, is the validator performing to minimum expectations, e.g. producing and signing blocks?

3 - Validator performance, is the validator performing at optimal levels?

4 - Validator stake activity, does the validator know when people are bonding to and unbonding from it?

So providing templates for a basic dashboard and 1-3 key alerts would be fantastic tools to provide. They'd give validators a running start when building out their Solana validator operation.

**Comment by sakridge** [comment]
Note that the current dashboard setup will show a lot of empty cells for validators since the metrics it looks at is geared toward whatever the current leader is producing. For instance transactions and node count.
