### ISSUE TITLE
Storage verification: Accessing banks from a root slot older than the latest root may not access the correct account

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#4665]
#### Problem

If a new root is generated and one tries to access a bank that is on an older root slot, it will return the highest root that the account exists on, not the highest one from the slot that the bank is at.

Validators who are doing storage verification are using this feature to look at previous rooted bank account state to determine which proofs to start verifying for the upcoming storage mining turn.

#### Proposed Solution

Rework accounts_index::get to use the max root in the ancestors list instead of the absolute max root and purge roots based on dropping banks. Or think of a way around the storage mining issue such that accessing older roots is not required.

**Comment by sakridge** [comment]
cc @sagar-solana @carllin @mvines

**Comment by sagar-solana** [comment]
Alternatively: We need to not make banks useless as long as there are still refs to them.

@rob-solana
