### ISSUE TITLE
Lack of a single trusted reusable program that implements scarcity

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#4672]
#### Problem
 
Every program that represents some scarce resource needs to implement its own version of Token.  

Wallets do not have a single ABI that they can rely on for representing tokens of various things to users.  

Users have no trusted implementation of Token.

#### Bad Solution
* linking a single Token program implementation into different assets

There is no way for users to trust the linked code.  Even with dynamic linking, since the underlying state transitions are allowed by the entire program, the user would need to verify all the linked libraries for every version of a linked Token.

* linking assets with different properties into Token

Token has no easy upgrade mechanism to add additional features.  For example, for tokens representing SPV assets, every new chain and fork represents a new SPV that would need to be supported.  

#### Proposed Solution

A single Token program defines a way for any external program to delegate scarcity to it.  The Token program also defines an ABI to delegate change of ownership to external state transitions.

notes: see #3216

**Comment by garious** [comment]
@aeyakovenko, bumped this back a milestone. Latest plan here is to leave Token as-is, but then allow its instructions to be invoked via the `process_instruction()` proposal.  The hard part here is figuring out a way to trap out of either native or BPF programs. @jackcmay is planning to look into that, but not until after v0.17.0 goes out. We have bigger fish to fry.

**Comment by aeyakovenko** [comment]
@garious we should decide on #4866, blinding calling `process_instruction` will introduce a spaghetti state machine.
