### ISSUE TITLE
Feature Request: validators should support an RPC to poll for metrics

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#4674]
#### Problem

A lot of blockchain monitoring sites may not want to run their own infra, and just want to to consume the data.

#### Proposed Solution

* PubSub interface to validator metrics
* versioning of the metrics names

**Comment by mvines** [comment]
As of 0.16, we'll be publishing a supplemental release that makes it easy for a validator to tap into the same InfluxDB metrics that we've been using for development (cc: #4638).  

We still need to version/publish the list of supported metrics though
