### ISSUE TITLE
Setting SOLANA_CUDA doesn't cause cuda to be used in multinode scripts

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#4693]
#### Problem

`SOLANA_CUDA=1 ./multinode/bootstrap-leader.sh` doesn't cause cuda to be used. Believe this is because the feature is not propagated to the core project since the feature is passed to validator project.

#### Proposed Solution

?

**Comment by mvines** [comment]
Ack,
https://github.com/solana-labs/solana/blob/a2838636940ce17af93f193b5cb512aee8476a3f/validator/Cargo.toml#L26
should look like
https://github.com/solana-labs/solana/blob/a2838636940ce17af93f193b5cb512aee8476a3f/replicator/Cargo.toml#L18

@sakridge could you please check if that fixes it?

**Comment by mvines** [comment]
hmm, it's not that simple it seems.  looking at it now
