### ISSUE TITLE
Running bench-tps on the testnet runs the accounts out of tokens

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#4695]
#### Problem

bench-tps doesn't run successfully on the testnet and gives lots of AccountNotFound errors.

#### Proposed Solution

Debug and fix it.

**Comment by sakridge** [comment]
<img width="794" alt="Screen Shot 2019-06-14 at 10 38 13 AM" src="https://user-images.githubusercontent.com/1024962/59527533-aec39980-8e90-11e9-838d-63335a9c10a3.png">

**Comment by sakridge** [comment]
<img width="899" alt="Screen Shot 2019-06-14 at 10 19 02 AM" src="https://user-images.githubusercontent.com/1024962/59526566-0f9da280-8e8e-11e9-937a-f7ffe1d69200.png">

**Comment by sakridge** [comment]
Using a testnet with 3 nodes using this:
`./net/net.sh restart -o noValidatorSanity -c "bench-tps=2=--tx_count 200000"`

**Comment by pgarg66** [comment]
Turning off signature fee and real PoH seems to help the issue. Not sure if that's a solution for v16 though.

**Comment by pgarg66** [comment]
Here's how it looks with the above changes

![image](https://user-images.githubusercontent.com/40076733/59629936-dddc4400-90f8-11e9-90ee-dd3f028a5b86.png)
