### ISSUE TITLE
Upgrade to CUDA 10.1

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4697]
We're currently building against CUDA 10.0, released Sept 2018.  So old.  

CUDA 10.1 update 1 is out (May 2019).  Much better, let's upgrade:https://developer.nvidia.com/cuda-downloads

**Comment by mvines** [comment]
cc: https://github.com/solana-labs/solana-perf-libs/pull/45

**Comment by mvines** [comment]
CI machines need 10.1 installed as well, @danpaul000

**Comment by danpaul000** [comment]
Will do this today: https://github.com/solana-labs/solana/issues/4703

**Comment by danpaul000** [comment]
> Will do this today: #4703

Done.

**Comment by mvines** [comment]
cc: https://github.com/solana-labs/solana-perf-libs/pull/47

I'm planning to add support for both CUDA 10.0 and 10.1.  Retaining CUDA 10.0 support means we can upgrade our existing net/ VM instances to 10.1 at will instead of blocking on the upgrade
