### ISSUE TITLE
Implement credit-only account optimizations

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#4700]
#### Problem
Continuation of #4432 to implement design: https://github.com/solana-labs/solana/blob/master/book/src/credit-only-credit-debit-accounts.md#credit-only-accounts 

#### Proposed Solution

- [ ] Runtime plumbing: Load CO accounts separately to avoid clone here: https://github.com/solana-labs/solana/blob/0dbe5ee5599fe11cca895daa88eef822b230cd56/runtime/src/accounts_db.rs#L377
- [ ] Runtime plumbing: Pass CO account data to programs by reference 
- [ ]  Rework BPF loader serialization of CD accounts and add handling for CO accounts. Current plan is to split account data by field and account type, and pass read-write and read-only field-types into the VM's RW and RO buffers separately. (Reminder to self: CO accounts will need a RW lamports field)
- [ ] Update BPF handling as needed to accommodate new accounts data organization

**Comment by mvines** [comment]
@CriesofCarrots - is everything in this issue still pending?
