### ISSUE TITLE
max_lamports_per_signature=0 which confuses clients

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#4702]
#### Problem

max_lamports_per_signature=0 which confuses clients

`[2019-06-17T18:31:28.337718090Z INFO  solana_bench_tps::bench] adding more lamports 128 max_fee: FeeCalculator { lamports_per_signature: 21, target_l
amports_per_signature: 42, target_signatures_per_slot: 42, min_lamports_per_signature: 0, max_lamports_per_signature: 0 }`

bench-tps funds with max which=0 and doesnt' give enough tokens for fees.

#### Proposed Solution

Return at least target_lamports_per_signature to the client.

**Comment by mvines** [comment]
Why was this issue re-opened?

**Comment by sakridge** [comment]
Still seems to be a problem. I am seeing as well as @CriesofCarrots and @sunnygleason

**Comment by mvines** [comment]
> max_lamports_per_signature=0 which confuses clients

This is still occurring?  I doubt it.   There's probably a related issue but it would be more helpful to create a new issue with those details rather than overloading this issue, which already has a fix landed for the problem it describes

**Comment by sakridge** [comment]
@mvines with tip code I still see this:

```[2019-06-21T22:41:09.494190807Z INFO  solana_client::rpc_client] signature PfHTnVaPhJZjRqfyAt2AUDMAHZysyBaM6SLEeAS1KxK
NB1jBxQM7QF12TPCcCfwtXrk6iNd9rjL8GyFwkFjB91r confirmed 1 out of 1
current balance 134217728...
Token balance: 134217728
[2019-06-21T22:41:09.494467527Z INFO  solana_bench_tps::bench] adding more lamports 128 fees: 
FeeCalculator { lamports
_per_signature: 21,
target_lamports_per_signature: 42,
target_signatures_per_slot: 42,
min_lamports_per_signature: 0,
max_lamports_per_signature: 0 } <<<<--

funding keys 1048576
```
