### ISSUE TITLE
Bench TPS performance is lacking with real PoH

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#4722]
#### Problem
The bench TPS client does not perform well when real PoH is turned on (hashes per tick is set to auto). The following dashboard snapshot shows the statistics

![image](https://user-images.githubusercontent.com/40076733/59722208-fcfdd300-91d7-11e9-9732-078cea5b6356.png)

Setting hashes per tick to sleep improves the performance (TPS, and overall stability)

#### Proposed Solution
Debug and fix it

**Comment by pgarg66** [comment]
Tag: @mvines @sakridge

**Comment by pgarg66** [comment]
This seems to be related to this PR https://github.com/solana-labs/solana/pull/4524
I tweaked the code to use CPU based verify and it works better with that.

![image](https://user-images.githubusercontent.com/40076733/59732986-27b05180-9201-11e9-8069-6aa1bc446f29.png)

**Comment by pgarg66** [comment]
@TristanDebrunner 

I timed EntrySlice::verify() call for GPU vs Non GPU case. The one with GPU is consistently taking ~1400ms. Whereas CPU is taking around ~200 ms.

![image](https://user-images.githubusercontent.com/40076733/59787743-faa28400-927e-11e9-98b1-ab37ca933204.png)

**Comment by TristanDebrunner** [comment]
What EntrySlice::verify() call were those times from? Do we know any details of the EntrySlices? With small num_hashes and/or short slices, CPU verification is faster, which is a known issue: #4632.

**Comment by pgarg66** [comment]
@TristanDebrunner I created a draft PR with my changes. You can view it here: https://github.com/solana-labs/solana/pull/4732

**Comment by pgarg66** [comment]
To calculate timing for CPU, I just commented out the CUDA version of verify and removed the feature flag check from the CPU version.

**Comment by TristanDebrunner** [comment]
That looks like the problem is small num_hashes/short EntrySlices. It's strange that the GPU case is taking so long. On local benches I'm getting below 600us for small EntrySlices

**Comment by pgarg66** [comment]
Can we do small batches on CPU instead of GPU? Sigverify does something similar..

**Comment by TristanDebrunner** [comment]
That's what #4632 is. I just haven't gotten to it yet.
