### ISSUE TITLE
Fix ignored test_repairman_catchup

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4748]
`test_repairman_catchup` fails too often in CI and is disabled.  Revert #4747 and fix it

**Comment by sagar-solana** [comment]
This test appears to fail with the same flaky error we've seen on other tests too. 

```
test test_two_unbalanced_stakes ... thread 'main' panicked at 'client transfer: Custom { kind: Other, error: StringError("retry_transfer failed in 5 retries") }', src/libcore/result.rs:997:5

test test_repairman_catchup ...  thread 'main' panicked at 'client transfer: Custom { kind: Other, error: StringError("retry_transfer failed in 5 retries") }', src/libcore/result.rs:997:5
```

Looks like we might have a local cluster responsiveness issue. For some reason transactions aren't working once a local cluster is "warmed up".
