### ISSUE TITLE
Expose RPC API for Bank::capitalization()

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4750]
Blockexplorers want to know the total supply.  We can get it from here:
https://github.com/solana-labs/solana/blob/7ea522e8511aa85767e8dbd000cc6dd54167bf07/runtime/src/bank.rs#L1234
and surface through an RPC API

**Comment by t-nelson** [comment]
https://github.com/solana-labs/solana/blob/master/core/src/bank_forks.rs#L118

Does that mean deprecated?

**Comment by mvines** [comment]
Yeah that's prolly a pretty strong sign to stay away.   As a first round I don't think we need to worry about how confirmed the bank is.  Something like this'll do the trick: https://github.com/solana-labs/solana/blob/a38e1a81efbcefc118a0a09c2c6fc9ca4494639f/core/src/rpc.rs#L103-L105

**Comment by t-nelson** [comment]
https://github.com/solana-labs/solana/blob/master/core/src/rpc.rs#L49-L51

I'll just ignore this, then ;)

**Comment by mvines** [comment]
heh, yes.  Or put another way, once that's fixed then everybody wins

**Comment by t-nelson** [comment]
```
running 1 test
{"jsonrpc":"2.0","result":10126,"id":1}
test rpc::tests::test_rpc_get_sol_total_supply ... ok
```

RE that result... I see where the 10000 comes from, but not the 126 (3 * 42?).  I'd like to prevent the test from falling over due to unrelated changes.

**Comment by mvines** [comment]
@rob-solana might know

**Comment by rob-solana** [comment]
depends on genesis and inflation...

**Comment by rob-solana** [comment]
I think a reasonable test might be "ah, I got a number that's non-zero and less than 2^64-1"
