### ISSUE TITLE
Pipeline Runtime is not compatible with Move

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#4759]
#### Problem

The Pipeline Runtime as defined would make it difficult to run a Move interpreter over the runtime state.  

https://developers.libra.org/docs/move-paper

A naive solution with Move running in isolation over a single `Account::data` as its state creates a sandbox that cannot interact across the global state machine.

#### Proposed Solution

#4785 

tag: @rob-solana @mvines @garious @jackcmay

**Comment by rob-solana** [comment]
what are the implications for syscall accounts? rewards pools?  these have well-known pubkey addresses with resources that should not be accessible except to the program (or to the runtime).

**Comment by aeyakovenko** [comment]
@rob-solana the hash of (syscall,owner) is unique and deterministic.  

We need to fix the allocator program.  Basically I think it would be instruction 0

**Comment by rob-solana** [comment]
I meant: today, syscall and rewards pools accounts are completely off limits, even if someone grinds the private key, because the program completely controls the accounts.  with this change, grinding the keys for the rewards pools maybe becomes interesting

**Comment by aeyakovenko** [comment]
@rob-solana but the rewards pool only cares about the accounts at known keys

hash(known key, rewards pool program)

**Comment by garious** [comment]
@aeyakovenko, close this?
