### ISSUE TITLE
implement economics for replicator rewards

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#4776]
#### Problem
replicators are running on a made-up economic model, they should instead be funded by inflation

#### Proposed Solution
- [x] from #4470, rewards points value for replicators  needs to be summed per-epoch
- [x] infinity pools, a la programs/stake_state/src/rewards_pools need to be added to genesis rewards pools
- [x] write rewards redemption code in validator regime, points payouts can use syscall::rewards replicator_point_value against the infinity pools

**Comment by sagar-solana** [comment]
Fixed in #4824
