### ISSUE TITLE
Lack of determinism in programs

### ISSUE THREAD

**Issue by sagar-solana** [solana-labs/solana#4802]
#### Problem

Our BPF loader does not enforce determinism in the programs/instructions they support.

#### Proposed Solution

Find a way to ensure determinism in our programs...

Tag: @aeyakovenko @garious @jackcmay

**Comment by aeyakovenko** [comment]
@sagar-solana bpf enforces it.

**Comment by sagar-solana** [comment]
@jackcmay suggested that it does not yet enforce that entirely.

**Comment by garious** [comment]
The runtime *does* enforce determinism, but under the assumption that the native program implementing a loader implements determinism. In mainnet, the native programs will be defined at genesis (or introduced via hard fork), so that should be a fine assumption to run with. If the BPF loader doesn't enforce determinism, we have a problem.

**Comment by sagar-solana** [comment]
Yeah, sorry I think I should have specifically targeted our BPF loader with this issue. The runtime expects determinism and our native programs are allowed an exception(at least until they are moved to BPF) since they get code reviewed ;).

**Comment by aeyakovenko** [comment]
@sagar-solana we don't have a case where some validators will throw an exception and others won't, and exceptions do not commit state.

**Comment by sagar-solana** [comment]
@aeyakovenko this is really more about programs not being deterministic in their execution. Not just exceptions. For example, a program that stores a random number in its account will cause the block it executed within to fail. 

Jack mentioned that we've got pointers available within the programs and that any state we generate from those values will not match across the network.

**Comment by aeyakovenko** [comment]
@sagar-solana where does it get a random. number?

**Comment by sagar-solana** [comment]
So I just spoke @mvines about this and I'm reasonably convinced that we don't have an issue here. I was mostly worried about the pointers based on my discussion with @jackcmay but you're right, given that these are within a VM and programs should always be loaded identically the pointers should not vary.
