### ISSUE TITLE
Solana Simple Payment Verification

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#4808]
This will be a meta issue to track implementation of, and hold high-level discussions regarding, Solana Simple Payment Verification as described in #4200.  Sub-issues and PRs will be created for lower-level task tracking.

The current plan of attack is as follows:

- [x] **Replace `Entry` mixin hash with a Merkle Root of the included TXs #4644**
- [ ] **Aggregate block votes #4809**
- [ ] Replace block hash with Merkle Root of included `Entry`s
- [ ] Merklize bank state
- [ ] Add transaction filtering for receipt event generation
- [ ] Add RPC methods + pub/sub
- [ ] Implement light client

**Bold** entries are in active development.

Questions, comments, suggestions welcome!

@aeyakovenko @garious @mvines

**Comment by jon-chuang** [comment]
What is the status of this? Is a light client still not able to verify payments quickly as per the above?

**Comment by mvines** [comment]
Yes, lots of work still needed here!

**Comment by jon-chuang** [comment]
There are currently two implementations of merkle root, one in
https://github.com/solana-labs/solana/blob/master/runtime/src/accounts_db.rs#L10
for the account merkle and one used in 
https://github.com/solana-labs/solana/blob/master/ledger/src/entry.rs

Should they be unified to use the crate? And I suppose by Merklising bank state, one is referring to this account merkle computed by the db? What kinds of

Furthermore, could I ask where the blockhash is computed, as that needs to be replaced too. From what I understand, this is currently computed from the PoH and tx hash. However, it seems what we want is a merkle tree made up of Entry-merkles.
