### ISSUE TITLE
Validators that start from a snapshot suffer from vote hash mismatches

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4817]
STR:
1. `export NDEBUG=1; ./multinode-demo/clear-config.sh ; ./multinode-demo/validator.sh beta.testnet.solana.com`

Once the validator starts and catches up to the latest block, observe messages like:
```
[2019-06-25T19:42:22.269520708Z WARN  solana_vote_api::vote_state] dropped vote Vote { slot: 939, hash: 9uFh7iTJ3J9PwavjeTu3prLFA4kptGSjPDEHTfmiazcT } matched slot 939, but not hash 8sc4miN9jEGRkBaVtJn8apA3LbkQrNNnA3aD3DQuW7fg
```
Looks like we aren't fully restoring the bank state.

**Comment by mvines** [comment]
@sambley - when you have time could you please look into this.  This doesn't block the v0.16.0 release though (and thanks for your previous late night efforts though!)

**Comment by sambley** [comment]
@mvines, will look into it.

**Comment by sambley** [comment]
@mvines, uploaded a change to fix this condition. I have not been able to reproduce the issue with this change. Let me know if the issue is this resolves the issue you are seeing as well.
https://github.com/solana-labs/solana/pull/4847
