### ISSUE TITLE
webwallet: derive private key from passphrase

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4857]
The current example-webwallet uses localstorage to hold the private key (yes, 😱...but that's why it's an **example** webwallet).  Beyond this being laughable, functionally it's a problem because now your account is stuck in one browser.

As a babystep towards something more real, we can let the user "unlock" their wallet using a strong passphrase and use exist methods, such as https://github.com/jo/session25519, to derive the private key from it

**Comment by t-nelson** [comment]
Most are comfortable with a BIP39-like [1] mnemonic seed.  Humans are terrible at random, so best not to leave them to their own devices.

[1] https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki

**Comment by mvines** [comment]
cc: #4939
