### ISSUE TITLE
webwallet: add example query url mechanism to allow a user to fund other apps

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4858]
Right now all our example web apps start with an airdrop of tokens, which doesn't really work in the real world. 

Instead the example webwallet could support a query URL whereby the other app can send the user to the webwallet to approve the transfer of funds to start the app.   The query URL could include:
1. Pubkey of the account to receive the funds
2. Amount to send
3. Some kind of justification
4. URL to return the user to once the funds have been transfered

This may end up looking a little like an OAuth2 session.

Also consider a mechanism for the user to reclaim funds that the app didn't spend (and probably create a separate issue for this..)

#4857 needs to be fixed first.

**Comment by mvines** [comment]
So once this issue is fixed, a user of https://github.com/solana-labs/example-messagefeed would first get bounced to the example webwallet to fund their messagefeed session instead of the messagefeed app internally airdropping itself tokens

**Comment by jstarry** [comment]
@mvines it looks like each dApp would need to manage keys for a system account and a program account. From what I can tell, program accounts can't fund system transactions, so the system account would be the "payer account" and would be the account that is funded by this mechanism. Does that all sound right?

**Comment by mvines** [comment]
Yep.  The dApp needs at least a system account keypair, funded from the users's wallet to pay for the first transaction (it could contain just enough lamports to pay for the worst-case transaction fee).

The wallet could also hang on to the keypair it returns to the dApp (meaning it generates the keypair rather than receive a pubkey from the dApp request), so later the wallet has the ability to reclaim any unspent lamports from the dApp's system account.

**Comment by jstarry** [comment]
@mvines great thanks for confirming! Makes sense to send over a keypair, I was also thinking it would be nice to derive keypairs from the wallet account. That way everything is recoverable

So, does it not really make sense to send lamports to a program account? Can they ever transfer or spend those lamports?

**Comment by mvines** [comment]
> I was also thinking it would be nice to derive keypairs from the wallet account. That way everything is recoverable

Yeah nice.   Maybe derive based on the dApp's program id, so each dApp gets just one system account 

> So, does it not really make sense to send lamports to a program account?

Probably not generically from the wallet.  Once the lamports are in a program account, only an instruction run by that program can transfer the lamports elsewhere.   But you still need a system account to pay for the transaction fees to run that instruction.

**Comment by jstarry** [comment]
@mvines thoughts on having a new issue for deriving dApp accounts from the web wallet? The main blocker I found was securely sending the derived account to the dApp. I think we could discuss approaches on a new issue
