### ISSUE TITLE
Figure storage requirements for TdS stage 1

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4859]
Let's get a handle on how much disk space validators will require to participate in TdS stage 1.  Assuming a cluster running at 50k TPS, what's the disk space requirement if it runs for 5 or 7 days?   If too large, let's discuss what a reasonable TPS rate to target would be to ensure validators can run for this long.

**Comment by mvines** [comment]
#4629 needs to be fixed first

**Comment by danpaul000** [comment]
50k TPS will consume roughly 4 TB per day, or 20 TB for a 5 day run.
