### ISSUE TITLE
Setup a STUN server

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#486]
`stun.testnet.solana.com` seems nice.  We'll need this to permit clients to open UDP ports to receive data from the rest of the network

**Comment by mvines** [comment]
The STUN example server from https://github.com/sile/rustun worked on the first try, talking to the example client.  This is all Rust-based.   Maybe we should simply embed a STUN server in fullnode

**Comment by garious** [comment]
👍

**Comment by mvines** [comment]
Turns out we can just use UPnP (on supported NATs) for now -- at least until somebody runs into a NAT that doesn't support this.  When that happens, we should 302 into #496

**Comment by garious** [comment]
👍
