### ISSUE TITLE
Program accounts don't declare program dependencies

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#4860]
#### Problem

A program can't modify account data owned by another program.  For example, say a program implements instruction `foo` and wants to operate on an account with a function `bar`, implemented in another program:

```rust
fn foo(keyed_accounts: &mut [KeyedAccount]) {
    let x = calc(&mut keyed_accounts[0]);
    bar(x, &mut keyed_accounts[1]);
}
```

In current code, the workaround is to have the transaction call two instructions and the first create an ephemeral account to pass the value `x` into `bar()`.  If we change that sample code to include a conditional: 

```rust
fn foo(keyed_accounts: &mut [KeyedAccount]) {
    let x = calc(&mut keyed_accounts[0]);
    if x > 42 {
         bar(x, &mut keyed_accounts[1]);
    }
}
```

Now the workaround gets awkward. That first instruction would need to write `Some(x)` to the account if `x > 42` and otherwise `None`. The semantic coupling gets increasingly obscure as the program gets more complex. Consider:

```rust
fn foo(keyed_accounts: &mut [KeyedAccount]) {
    let x = calc(&mut keyed_accounts[0]);
    if x > 42 {
         bar(x, &mut keyed_accounts[1]);
    } else {
         baz(x + 1,  &mut keyed_accounts[2]);
    }
}
```

Effectively, the ephemeral account is forced to encode the state of `foo()` at the time `bar()` is called. Yuck.

#### Proposed Solution

Offer a way to "trap" into a program from a program. First, we need to tell the runtime that the program that implements `foo` depends on the one that implements `bar`. First-level dependencies should be added to the foo's executable account.  The runtime should recursively crawl the DAG formed by those dependencies to load the full tree of executable accounts. Second, after jumping through the trap door, we need to run something similar to today's `verify_instruction()` to ensure that `foo()` didn't modify `keyed_accounts[2]` before invoking `bar()`.  Finally, do all the other stuff not evident from this 40,000 ft view.

#### Why?

This proposal is an operating systems approach to what Libra's Move does by introducing a new domain-specific programming language. Where Move has compile-time checks, we add runtime checks. In exchange, we give developers the ability to write on-chain programs in general purpose programming languages.

**Comment by garious** [comment]
tag: @aeyakovenko @jackcmay

**Comment by aeyakovenko** [comment]
#4785 proposes scrips that addresses this problem.
