### ISSUE TITLE
Blocktree marks distant slots with no banks as the children of valid slots

### ISSUE THREAD

**Issue by mark-solana** [solana-labs/solana#4863]
#### Problem

While debugging #4827 it became apparent that slot leaders are going missing. @sagar-solana pointed to the assignment of distant slots with no bank as the children of valid slots as the likely issue.

cc: @sagar-solana @rob-solana @carllin @mvines

**Comment by mark-solana** [comment]
Logs supplied by @sagar-solana running `test_leader_failure_4` from the `local_cluster` integration tests:

https://pastebin.com/xxAfzgNE

https://pastebin.com/ZsfLKXza

**Comment by pgarg66** [comment]
@sagar-solana wondering if this is still an issue? Any STR?

**Comment by sagar-solana** [comment]
I think this was something that came up when Mark was debugging his pr. leader_failure_4 would keep failing because some corrupt data was being recovered. STR - run leader_failure_4 with Cuda enabled repeatedly.

**Comment by mvines** [comment]
I'm having a hard time seeing anything actionable here.  Close?

**Comment by sagar-solana** [comment]
Not an issue anymore afaik. Blobs are also being replaced entirely.
