### ISSUE TITLE
metrics.solana.com is in bad shape

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4883]
* https://metrics.solana.com:3000/d/testnet/testnet-monitor?refresh=60s&orgId=2 - not working
* https://metrics.solana.com:3000/d/testnet-beta/testnet-monitor-beta?refresh=60s not working

🤕 

cc: #4757 or perhaps #4114?

**Comment by danpaul000** [comment]
After a restart of the system and upgrading to influx 1.7 m.s.c appears to have been stable for the last few days.  Influx server on-demand is still high-priority WIP but does not appear to be gating the m.s.c stability for current testnet usage.
