### ISSUE TITLE
Storage Program should verify that nodes only work on allowed proofs/segments

### ISSUE THREAD

**Issue by sagar-solana** [solana-labs/solana#4905]
#### Problem

The program doesn't enforce that replicators and validators are working on proofs and segments that were assigned to them.

#### Proposed Solution

The current logic that picks a segment to store/verify using the current "turn" blockhash as a seed (it signs it and uses the signature). This blockhash is then lost completely and cannot be verified by the program. 

- Rework the selection logic to be easily portable/verifiable 
- Allow replicators to pickup where they left off at reboot by using the same selection logic
- Cycling of storage segments can be implemented based on turn count rather than blockhash 

Tag: @sakridge

**Comment by jon-chuang** [comment]
I am interested in this, can start in 6 weeks.
