### ISSUE TITLE
Maybe retransmit blobs recovered from erasure

### ISSUE THREAD

**Issue by sagar-solana** [solana-labs/solana#4914]
#### Problem

Blobs recovered from Erasure are not sent down through Turbine. 

#### Proposed Solution

Evaluate whether or not there is any reasonable benefit to retransmitting blobs recovered from erasure

Tag: @rob-solana @aeyakovenko @carllin @garious

**Comment by rob-solana** [comment]
first blush: no.  but do send erasures with repair responses.  implies we're saving recovered erasure blobs, i.e. running erasure recover even when we have all the data blobs.
