### ISSUE TITLE
LOGS are noisy.  Document all uses of WARN and ERROR

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#4938]
#### Problem

LOGS are noisy. 

#### Proposed Solution

1.  Document all uses of WARN and ERROR.  These must be meaningful to operators.
2. use INFO and DEBUG/TRACE for all other cases

**Comment by mvines** [comment]
We should do the same for metric data points as well

**Comment by pgarg66** [comment]
We may want to decouple logs level from metrics level. Currently we deploy solana fullnode with log level = Info. So all counters/datapoints with level info and above get printed in logs.

**Comment by mvines** [comment]
A new suite of logging macros might be useful here too, E.g.  `info_stable!()`.  The _stable logs/metrics are ones that we publish and maintain.
