### ISSUE TITLE
v0.16: locktower distance frequently too large

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4940]
Too frequently on testnet.solana.com we see a locktower graph that looks like:
![image](https://user-images.githubusercontent.com/1281082/60731881-83672400-9efd-11e9-92e2-5f4c73c96319.png)
which indicates the cluster has diverged.  

Need to debug/fix.  beta.testnet.solana.com performs much better, which consists of homogeneous nodes, so this is likely due to the 3rd party nodes on testnet.solana.com that are all running on different hardware/infra

**Comment by mvines** [comment]
Maybe fixed, by #5111?  Locktower was pretty solid overnight, which is somewhat unusual.

![image](https://user-images.githubusercontent.com/1281082/61317200-5e08ce80-a7b7-11e9-9394-c66be1a693e5.png)

**Comment by carllin** [comment]
@mvines yeah we can keep an eye on it, that fix should have fixed the vote dropping errors which would lead to locktower actually making progress

**Comment by mvines** [comment]
Closing, I don't see anything further actionable here
