### ISSUE TITLE
Verify bitcoin spv proofs on solana

### ISSUE THREAD

**Issue by pathoam** [solana-labs/solana#4941]
#### Problem
Transferring assets between bitcoin and solana or trading one for the other does/will require a trusted third party intermediary in order to settle the transaction.

#### Proposed Solution
Implement a system for validating bitcoin spv proofs on Solana, making it possible to confirm the validity of bitcoin transactions in solana smart contracts. The Bitcoin-IPV program will consist of two principle components: a mechanism for statelessly verifying bitcoin merkle proofs and a public marketplace for participants to request and provide transaction proofs. The program will expose an interface that allows client contracts to request proofs for transactions matching certain criteria and receive verification of them without requiring contract specific infrastructure. This will act as a basic building block for products like swaps, interchain auctions, and representation tokens and will be analogous in some ways to Summa's btc-spv repository, which implements bitcoin transaction verification on ethereum. 
Validating proofs will require as input:
 - transaction hash
 - block digest
 - merkle block proof (partial tree linking the transaction to the block's merkle root)

And will produce a result indicating the validity of the submitted proof which will be saved in the account of the request in question.

Components include:
 * PR #5153 - skeleton for all different components, errors, header parsing
 * PR #5858 - Transaction parsing, including inputs, outputs, errors, utilities for generating test data

**Comment by prestwich** [comment]
Please consider using bitcoin-spv:
https://github.com/summa-tx/bitcoin-spv/tree/master/rust

**Comment by garious** [comment]
Thanks @prestwich, this code looks great!
