### ISSUE TITLE
NAT hardening

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#496]
#494 landed basic support for NATs that honor UPnP to open public UDP ports.   Not all NATs to though.  This issue is meta issue to spend some read time surveying all the different NAT configurations we want/need to support for both thin and full nodes, and then to file more actionable issues to address.

**Comment by garious** [comment]
Not sure if this is helpful, just passing it on. https://medium.com/paritytech/why-libp2p-13085ed0c9c8
