### ISSUE TITLE
Provide TdS genesis block with list of known validator pubkeys

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#4960]
For the TdS dashboard, the blockexplorer API server needs to know the list of known validators.   This probably takes the form of a .json/.yml file from within net/remote/remote-node.sh

**Comment by kwunyeung** [comment]
There should be some ways to let the validators to provide their own information. Can't just rely on the identity pubkey.

**Comment by mvines** [comment]
Yep absolutely. A validator self-registration mechanism is coming in as a part of #4970, whereby validators can optionally associate additional public information with their identity pubkey.  This additional information will be surfaced in the blockexplorer

**Comment by mvines** [comment]
The next step here is probably to create a file like
https://github.com/solana-labs/tour-de-sol/stage1/validators.yml that is pulled in by
* [ ] TdS cluster automation
* [ ] blockexplorer API server at startup
 
Populating that `validators.yml` with the full suite of pubkeys intersects with #5011

**Comment by danpaul000** [comment]
> The next step here is probably to create a file like
> https://github.com/solana-labs/tour-de-sol/stage1/validators.yml that is pulled in by the TdS cluster automation

"A file like" validators.yml?  Why isn't validators.yml THE file?  Current automation pulls validators.yml into the genesis block

**Comment by mvines** [comment]
> Why isn't validators.yml THE file?

My of my classic weasel words.  **THE file** sounds good!

**Comment by danpaul000** [comment]
@mvines the file https://github.com/solana-labs/tour-de-sol/stage1/validators.yml is pulled in by the TdS cluster automation, with the ability to set a custom URL to a different file if needed at the time the cluster software is started.  Is there any other action needed on this issue?

**Comment by mvines** [comment]
`validator.yml` right?  (no s).   But yep that's it.  I just completed the rest of the setup, documented at https://github.com/solana-labs/tour-de-sol/blob/master/README-internal.md#validator-keybase-id-registration
