### ISSUE TITLE
Validators cannot verify mining proofs efficiently 

### ISSUE THREAD

**Issue by sagar-solana** [solana-labs/solana#4963]
#### Problem

Validators cannot verify mining proofs right now since the function that does the verification assumes the offsets are the same for all proofs. This function also does not correctly generate offsets.

#### Proposed Solution

The verification function (`chacha_cbc_encrypt_file_many_keys`) needs to be updated to understand how proofs are generated.
- Per segment that is being verified, this function needs to map encryption keys to offsets per key so that the hashes that are generated are mapped to each key. 
- Offset generation on the validator needs to factor in the segment size correctly and then we know the sample range by `num_bytes/block_size`. 

Tag: @sakridge

**Comment by sagar-solana** [comment]
@sakridge you think you'll be able to look into this at some point?

**Comment by jon-chuang** [comment]
I can look into this in 6 weeks time.
