### ISSUE TITLE
credit-only

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#4966]
#### Problem
some issue exists with the thread-safety of credit-only accounts.

STR: 
`cargo test --manifest-path core/Cargo.toml blocktree_processor::tests::test_process_entries_stress -- --nocapture --ignored`

To convince yourself that credit-only is the culprit, change this line to use a normal credit-debit account for to_pubkey:
https://github.com/solana-labs/solana/blob/c5ba2e08837982fb82adc1a894eba5ef8a53b462/sdk/src/system_instruction.rs#L93

#### Proposed Solution

find and fix, maybe back out credit-only transfers until then?

**Comment by rob-solana** [comment]
STR isn't working for me right now...

**Comment by CriesofCarrots** [comment]
@rob-solana , what were you seeing on the 2 variations of that test?

**Comment by rob-solana** [comment]
seeing that the test is broken ;)

**Comment by rob-solana** [comment]
user error
