### ISSUE TITLE
config_api concerns

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#4973]
#### Problem
from #4970

* deserialize().unwrap() (crashes node)
* keyed_accounts[index] from a deserialized message (crashes node)
* the need to present config keys in the message in the same order as in the account data, which looks brittle
* if the account creator can say who has to sign to change the config, should we require that the account pubkey be forever among that set?

#### Proposed Solution
consider, address above

**Comment by CriesofCarrots** [comment]
@rob-solana , I think your first 3 comments are fair, and I'll fixup today.
I'm torn on the last point, and curious to hear @mvines 's thoughts.

**Comment by mvines** [comment]
> if the account creator can say who has to sign to change the config, should we require that the account pubkey be forever among that set?

I think it's a feature that the config account owner can effectively transfer ownership to another keypair(s)

**Comment by mvines** [comment]
> the need to present config keys in the message in the same order as in the account data, which looks brittle

This seems tolerable to me, as reduces the complexity of the on-chain program where each VM instruction has a cost.  It's easy enough for the client to order appropriately, either programmatically or by convention.

**Comment by rob-solana** [comment]
> > if the account creator can say who has to sign to change the config, should we require that the account pubkey be forever among that set?
> 
> I think it's a feature that the config account owner can effectively transfer ownership to another keypair(s)

I guess I'm missing something.  It looks like the original address of the account *always* needs to sign updates.  I can see how other signers are enabled, but I don't see how the original owner is ever removed from the list of required signers for update.

By the way: how do you get your lamports out of one of these accounts?

**Comment by CriesofCarrots** [comment]
> I think it's a feature that the config account owner can effectively transfer ownership to another keypair(s)

Right now, the config account owner does have to be among the signer set:
https://github.com/solana-labs/solana/blob/fc58b3e8c3ad1fa3118edfc0cff44557b27897a5/programs/config_api/src/config_processor.rs#L15

This is what I was getting at in my comment about the validator having to maintain multiple keypairs in order to update information.

**Comment by mvines** [comment]
> This is what I was getting at in my comment about the validator having to maintain multiple keypairs in order to update information.

Oh got it.  Removing that restriction seems great to me :).   That ought to simplify the validator usage nicely.

> By the way: how do you get your lamports out of one of these accounts?

You don't.  One would just give it just enough lamports to stay alive

**Comment by CriesofCarrots** [comment]
:) Sweet. Yes, it does simplify the validator usage nicely. I was worried that it would complicate your install usage.
