### ISSUE TITLE
Rust BPF: Add Syscall utilities

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#4981]
#### Problem

Users have to read and parse the syscall accounts themselves.

#### Proposed Solution

Provide utilties that will return the data in an easy to use format.

**Comment by rob-solana** [comment]
is syscall::current::from_keyed_account() unfit for purpose?

**Comment by jackcmay** [comment]
Can't pull in current.rs since it relies on std (rust bpf programs are `no_std`).  If we broke the sdk/src stuff into std and no_std pieces we could leverage the no_std pieces.
