### ISSUE TITLE
solana-install-deploy sends airdrops even if they are disabled

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#4983]
#### Problem

https://github.com/solana-labs/solana/blob/master/scripts/solana-install-deploy.sh#L65

If an account balance reached 0 lamports, we automatically call solana-wallet for an airdrop.  With external validators coming online for TdS, we will have airdrops disabled.

#### Proposed Solution

Add some logic to ensure airdrops are enabled on the cluster before calling the wallet.

**Comment by mvines** [comment]
Another option would be to pass a keypair into `solana-install-deploy.sh` that already has some lamports
