### ISSUE TITLE
Manage external accounts stakes file for TdS

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#4986]
#### Problem

Currently, the external accounts primordial staking file for genesis block population is stored in /tmp on the buildkite machine.  We should maintain a copy of this file, easily editable as participants and their stake change, and `wget` the file into the buildkite automation for starting/stopping TdS cluster

**Comment by mvines** [comment]
I think we may want to create a tds github repository for this (I had previously suggested using the solana repo wiki).   I'm expecting well have other assets that will be stage specific as well

**Comment by mvines** [comment]
#4960 is related.

**Comment by mvines** [comment]
#4751 is also related (to a single tds github repo)

**Comment by danpaul000** [comment]
> I think we may want to create a tds github repository for this (I had previously suggested using the solana repo wiki). I'm expecting well have other assets that will be stage specific as well

Agreed.  I looked briefly at the wiki option when you earlier suggested it, but I don't think it's the right place, particularly as the source for pulling down a yml file with the stakes

**Comment by mvines** [comment]
https://github.com/solana-labs/tour-de-sol now exists.   Let's create a `/stage1/validator.yml` file for this.

**Comment by danpaul000** [comment]
@mvines do we have any of the external parties' pubkeys yet, or know how much each will get stakes at the beginning of stage1?

**Comment by mvines** [comment]
N external parties' pubkeys, that will each get the same M stake :)
Just throw some random pubkeys in as a placeholder to get the plumbing in place.

**Comment by danpaul000** [comment]
Okay.  Is the stake represented in lamports or sol?  Trying to figure out what is a reasonable order of magnitude to use for my dummy pubkeys so I can actually use the cluster as a validator

**Comment by mvines** [comment]
lamports. 

> Trying to figure out what is a reasonable order of magnitude
https://github.com/solana-labs/solana/blob/fc58b3e8c3ad1fa3118edfc0cff44557b27897a5/multinode-demo/fullnode.sh#L163
