### ISSUE TITLE
Handle dropped votes in vote transactions

### ISSUE THREAD

**Issue by sagar-solana** [solana-labs/solana#5003]
#### Problem

Votes that fail a Hash or Slot check are silently ignored. Instead this should cause the vote transaction to fail with an error. 

#### Proposed Solution

- Add a Result to `process_vote` and bail if a vote in a transaction fails
- Consider simplifying the vote transactions to be split into individual vote instructions instead of a single vote instruction that carries multiple votes. 

Tag: @rob-solana

**Comment by mvines** [comment]
@sagar-solana - do you know if this is still an issue?

**Comment by sagar-solana** [comment]
No longer an issue.
