### ISSUE TITLE
Testnet monitor does not show 'tds' in database list

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#5014]
#### Problem

Database list in grafana is filtered to only display db's that match "testnet.*"
The new 'tds' db should be included.  You can manually enter this on the URL currently as a workaround.

#### Proposed Solution

Open up the regexes in `metrics/scripts/grafana-provisioning/dashboards/testnet-monitor.json`

**Comment by mvines** [comment]
Meh, not worth tracking/fixing
