### ISSUE TITLE
ci: speed up snap build again

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#506]
We've picked up some new dependencies which seems to be causing the snap build to be close to 100% slower than before.  Can we:
* Use prebuilt bits for our dependent crates that never change?
* Avoid building everything but `fullnode` for the CUDA build.

cc: #442

**Comment by mvines** [comment]
cc: d63493a852e040298aaffda68b99e6d94120a547

**Comment by garious** [comment]
Precedent for CI caching crates: https://docs.travis-ci.com/user/caching/#Rust-Cargo-cache

Regarding the CUDA build, we could split client and server into separate crates (but keeping them in the same git repository). For this public testnet, for instance, it'd be nice to point folks to the client crate.

**Comment by mvines** [comment]
Snap build slowness has been mitigated by:
1. PRs only build the Snap when the `snap/` subdirectory is modified
2. Pushes build the Snap in a separate buildkite pipeline that skips intermediate commits (only 1 Snap build on `master` will run if additional commits arrive when a Snap build is already running)
Also CI caching has been added via #510 and #511.  Closing this issue as mischief managed.
