### ISSUE TITLE
Remove version from blobs

### ISSUE THREAD

**Issue by sagar-solana** [solana-labs/solana#5071]
#### Problem

A version field was added to blobs in #5057 to support rollbacks. 

#### Proposed Solution

Find a way to support rollbacks without a version field, or conclude that this is the only way. 

Tag: @carllin @mvines @aeyakovenko @pgarg66

**Comment by mvines** [comment]
(bump to v0.18, we really gotta do this before mainnet v1!)

**Comment by mvines** [comment]
Fixed by #6937
