### ISSUE TITLE
TdS ledger rollback procedure

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#5082]
#5041 and #5057 move us towards being able to perform a cluster rollback.  What remains is:
1. https://github.com/solana-labs/solana/blob/1c966aac25c88cc3cc876ea011b9dc7e025b5802/ledger-tool/src/main.rs#L194
2. Document the manual rollback procedure as a markdown file in https://github.com/solana-labs/tour-de-sol
3. Test the procedure and make sure the cluster can actually restart after a rollback

**Comment by sagar-solana** [comment]
What's the use of the "slot_list" file? Does the prune need to drop anything that is _not_ in the "slot_list" or just keep the roots until the "target" slot and hash collected in 
https://github.com/solana-labs/solana/blob/1c966aac25c88cc3cc876ea011b9dc7e025b5802/ledger-tool/src/main.rs#L190

**Comment by mvines** [comment]
The slots_list file contains the list of roots that we want a validator to rollback to, any one that's in their local blocktree is fine.   For TdS we'll only use a single slot though, since if we permit multiple slots we run the risk of diverging again until blocktree supports multiple cluster partitions per slot.

**Comment by sagar-solana** [comment]
Understood, so prune will work off of the "target" slot and hash and only keep the rooted path upto that point. Thanks!

**Comment by mvines** [comment]
I've added a place holder for documentation at https://github.com/solana-labs/tour-de-sol/blob/master/README-internal.md#ledger-rollback-procedure

**Comment by sagar-solana** [comment]
@mvines, just remembered that the version field in the blobs is still unused. How should rollbacks deal with that?
