### ISSUE TITLE
Unable to fetch update manifest

### ISSUE THREAD

**Issue by joesixpack** [solana-labs/solana#5088]
#### Problem

![image](https://user-images.githubusercontent.com/23145642/61169064-8faa3d00-a50c-11e9-84ec-4a7b17d3d2bc.png)

#### Proposed Solution

???

**Comment by mvines** [comment]
I suspect the cluster was down when you tried this.  Can you please retry?  You can also use the block explorer at https://explorer.solana.com/ to confirm the cluster is up by looking for transaction activity

**Comment by joesixpack** [comment]
Works now.
