### ISSUE TITLE
Add client options to CI for TdS and Testnet automation

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#5103]
#### Problem

There are flags in net/net.sh for client options that would likely be useful to elevate to CI scripts for cluster automation and benchmarking.

```
-c clientType=numClients=extraArgs - Number of clientTypes to start.  This options can be specified
                                        more than once.  Defaults to bench-tps for all clients if not
                                        specified.
                                        Valid client types are:
                                            bench-tps
                                            bench-exchange
                                        User can optionally provide extraArgs that are transparently
                                        supplied to the client program as command line parameters.
                                        For example,
                                            -c bench-tps=2="--tx_count 25000"
                                        This will start 2 bench-tps clients, and supply "--tx_count 25000"
                                        to the bench-tps client.
```

Proposal:

1. Add support to the `solana-testnet` pipeline to accept the following env vars:  `NUMBER_OF_CLIENT_NODES` and `CLIENT_OPTIONS`. The former var will speciy the number of client VMs to create in `gce.sh` and the latter to specify what settings to pass to `net.sh [re]start` . Bash parsing of the quotation marks from buildkite down to `net.sh` is a bit painful.  Plumbing: `buildkite -> testnet_automation.sh -> net.sh`

2.  Add the same env var support and plumbing to the `tds-create-and-start` pipeline.  Plumbing: `Buildkite -> testnet_manager.sh -> testnet_deploy.sh -> net.sh`

**Comment by danpaul000** [comment]
Currently we can only specify number of clients, which default to bench-tps with default tx-per-batch values.

**Comment by danpaul000** [comment]
@mvines do you think this is needed?  I created this issue before we had https://github.com/solana-labs/tour-de-sol/blob/master/bench-tps.sh

**Comment by mvines** [comment]
Ah, nope.  We don't need this anymore

**Comment by danpaul000** [comment]
This should be implemented now that move transactions are able to be called by setting the right client options.  This should be plumbed up to ci/testnet-deploy, and then ci/testnet-automation for benchmarking.

**Comment by danpaul000** [comment]
Not sure how this didn't get stale-d a while ago.  It's been finished for a long time.
