### ISSUE TITLE
There is no way to verify an old solana transaction in the solana state machine.

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#5113]
#### Problem

A request from Ethereum developers:  A way to verify that a transaction has executed.

#### Proposed Solution

We could allow another TX to submit a Merkle proof to any transaction in the past, and the state machine would only need to verify the path.  Effectively this would be running a solana SPV inside solana.

tag: @t-nelson @garious

**Comment by anoane** [comment]
It would be great if data attached to that transaction could be also accessed by the smartcontract.
Let’s say we have a smartcontract that want to access data sent by a set of specific addresses (trusted data providers chosen by the creator of the contract, they could be Eurosport, Sky, etc.).
Let’s say we have 1XBet/SportsBet that want to query the smart contract for the result of a football match X.
1XBet send a tx with data like “USA/ITA/160719” with some extra “gas” which will be used for the smartcontract to pay for a reply and to pay for Eurosport service.
The smartcontract could parse the inputs from Eurosport/Sky, filter them according to the input, take their data for trusted (true/false or exact match result or average if it’s weather temperature).

Not the most noble use case but I hope it gives the idea on how powerful it could be.
