### ISSUE TITLE
No Next Leader Found

### ISSUE THREAD

**Issue by joesixpack** [solana-labs/solana#5123]
#### Problem

Loops endlessly:

![image](https://user-images.githubusercontent.com/23145642/61293400-731a3900-a788-11e9-829c-3a3af13de21f.png)

#### Proposed Solution

???

**Comment by mvines** [comment]
@joesixpack where is your machine located?  Is it behind a NAT?

> However ensure the machine used is not behind a residential NAT to avoid NAT traversal issues. A cloud-hosted machine works best. Ensure that IP ports 8000 through 10000 are not blocked for Internet inbound and outbound traffic

**Comment by joesixpack** [comment]
Yes, but the router's ports are open and the range is specified on the solana command line.  That's usually sufficient, no?

**Comment by mvines** [comment]
Yes that should be ok.   Is there any way you can provide a full log from the `validator.sh` or other command you used to start your validator.  There may be a clue higher up

**Comment by joesixpack** [comment]
I allowed UDP and that seems to have resolved it, although its consistently several hundred blocks behind the Explorer and never seems to catch up.

![image](https://user-images.githubusercontent.com/23145642/61371875-a32a1080-a84a-11e9-8a0f-867bf1e4b543.png)

**Comment by mvines** [comment]
What kind of machine are you running on?  If you look at the time between the sequential "new fork: xxx: parent: yyyy" messages, it looks to be longer than 800ms (which is the rate that the cluster is producing new blocks at) so you may never catch up.  A couple possibilities are:
1) Your machine is too slow and can't generate PoH hashes fast enough
2) The network connection is too slow and is not receiving new blobs from other nodes fast enough
3) Something else... :)

**Comment by benjamin-lu** [comment]
@joesixpack Same issue here, how to allowed UDP?

**Comment by mvines** [comment]
I think we've fixed various bugs since the first TdS dry run that could have caused this issue.  I'm going to close for now as I don't see anything actionable here anymore.   But if this reproduces, please refile an issue.  Thanks!
