### ISSUE TITLE
Add_snapshots is slow

### ISSUE THREAD

**Issue by carllin** [solana-labs/solana#5130]
#### Problem
The add_snapshots function regularly takes 300ms or more on tested with bench-tips running. 

1) The serialization of the signature cache seems to be the bottleneck.

2) Snapshots should only be taken of the root bank instead of all frozen banks.

**Comment by sakridge** [comment]
@carllin can we just put this in another thread to avoid blocking bank creation?

**Comment by carllin** [comment]
I think the problem is that the statuscache can be purged and AppendVecs can be removed if we allow replay/banking threads to run while serializing a previous bank
