### ISSUE TITLE
TdS state.tgz is getting very large

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#5132]
After running the TdS cluster for ~1 hour, the "snapshot" archive (state.tgz) is now ~5 GB.  Why is it so big?  Is bench-tps not actually reusing the same accounts to transfer in/out of?

**Comment by mvines** [comment]
This also included 1 bench-tps client (with the default net/ config running)

**Comment by CriesofCarrots** [comment]
Tests confirm that bench-tps is reusing accounts appropriately, both when using primordial accounts (airdrops disabled) and when creating accounts on the fly (airdrops enabled)

**Comment by CriesofCarrots** [comment]
While I'm not seeing the size increase as quickly as the original issue description, something isn't quite right. On a healthy testnet with a static number of accounts, the size of state.tgz remains stable for 1-2 hours, but then later doubles or triples.
The source of the size increase is the `accounts` subdirectory (`snapshots` remains relatively small), which retains more and more data subdirectories (thousands after a few hours). I'll dig into accounts_db next to see if there are issues in how accounts are removed.
