### ISSUE TITLE
bench-tps panics at 'attempt to subtract with overflow'

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#5141]
STR:
```
$ solana-bench-tps -n beta.testnet.solana.com:8001  --tx_count 10 -d beta.testnet.solana.com:9900
```
causes a panic at
https://github.com/solana-labs/solana/blob/f88c72c41e134949adb26518f38894cc6caca690/bench-tps/src/bench.rs#L368

**Comment by CriesofCarrots** [comment]
Panic is actually at this line: https://github.com/solana-labs/solana/blob/651f87a937412582ef4e353d447e2a6bf7a3b51e/bench-tps/src/bench.rs#L365
