### ISSUE TITLE
Add facility to verify ledger consistency 

### ISSUE THREAD

**Issue by sagar-solana** [solana-labs/solana#5156]
#### Problem

We need to a way to ensure the ledger is actually consistent within itself. I.e references to indexes within columns must be valid.

#### Proposed Solution

Walk each column and ensure that their ancestry is consistent and that there are not references to non-existent indexes.  

Tag: @mvines @rob-solana

**Comment by rob-solana** [comment]
fsck FTMFW?

**Comment by sagar-solana** [comment]
haha I feel like im missing something, how would I use fsck?

**Comment by rob-solana** [comment]
it's another tool in our toolbox for understanding failures

**Comment by t-nelson** [comment]
`solana-ledger-tool verfy`, right?

**Comment by mvines** [comment]
sorta, it probably doesn't catch *everything* but it's close enough
