### ISSUE TITLE
Get all the libra packages from `e2e_tests` and below building with Rust stable

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#5167]

**Comment by garious** [comment]
@TristanDebrunner Keep an eye on libra master. Looks like there's been some effort going into minimizing nightly dependencies:
https://github.com/libra/libra/commits/master

**Comment by TristanDebrunner** [comment]
It looks like tip of master on the main libra repo does this for us. I can successfully run `cargo +stable build` and `cargo +stable test` in `language/e2e_tests/`. Unless I'm missing something I think this can be closed.

**Comment by garious** [comment]
Don't close this yet. Instead, wait till @jackcmay upgrades to `v0.0.0.1` (same as tip of master of main libra repo). Then switch CI from nightly to stable here: https://github.com/solana-labs/solana/blob/master/ci/buildkite.yml#L18, and update references to nightly in `test-move-demo.sh`.

**Comment by garious** [comment]
@TristanDebrunner, you can do this right now yourself. You should see one test fail, but you can `#[ignore]` to push forward.
