### ISSUE TITLE
consensus uses live stakes, which can change dramatically from epoch-to-epoch

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#5174]
#### Problem
when a large stake comes online (at an epoch boundary), consensus can fail on banks from before the epoch, network falls down

#### Proposed Solution
options:
* use epoch stakes for consensus
* re-visit stake warm-up to have a global view of staking, and ramp stakes by no more than 1/3 of total from previous epoch
* randomization of what stake consensus looks at (i.e. not live, not epoch boundary, but some random distance in the past?)

**Comment by rob-solana** [comment]
CC @aeyakovenko @carllin

**Comment by aeyakovenko** [comment]
@rob-solana ramp up is the right answer.  the validator set shouldn't change by more than 15% or some network configured amount.

**Comment by rob-solana** [comment]
some % of previous epoch's total stake?

**Comment by aeyakovenko** [comment]
@rob-solana yep.  Do we only care about increases?

**Comment by rob-solana** [comment]
what are the concerns with using the bank's epoch stakes for consensus?  or does warmup address other concerns?

**Comment by rob-solana** [comment]
> @rob-solana yep. Do we only care about increases?

I think we only care about increases for this case.

**Comment by aeyakovenko** [comment]
@rob-solana it should be using the bank's epoch stakes.  I thought it was :)

**Comment by rob-solana** [comment]
hopefully that big stake gets a leader slot ;)

**Comment by rob-solana** [comment]
ok, I'm thinking about how to do global stake stuff.  it's already pretty ugly in there...

**Comment by rob-solana** [comment]
one simple way would be to only allow some amount of activation per epoch, first-come-first-serve.  activations that come after the limit is reached would bounce.

**Comment by aeyakovenko** [comment]
but the goal is to prevent an attacker from overwhelming the validator set.  

Something like MIN(N new stakes, X old stakes *0.15) gets activated?

**Comment by rob-solana** [comment]
simple to describe.  sux to implement with a program that can only see one stake account at a time

**Comment by rob-solana** [comment]
I suppose the notion of "activated" is a bank construct...

**Comment by rob-solana** [comment]
CC @carllin

**Comment by aeyakovenko** [comment]
@rob-solana what if we had a client driven TX compute the amount and activate the stake?  All we would need is for the epoch to produce a total available new stake block that people buy

**Comment by rob-solana** [comment]
first-come, first-served?

**Comment by aeyakovenko** [comment]
@rob-solana that seems like an attack vector too :)

**Comment by aeyakovenko** [comment]
@rob-solana can they all register to want the stake, and then at the end of the epoch we give them out?

1. 10 stakers creates a new stake for 100 tokens
2. staking program accumulates the total number of stakes requested to be 1000, only 500 are allowed to "vest"
3. each staker then asks to "vest" their 100, but since 500 is allowed, 500/1000 * 100 actually vest.

**Comment by rob-solana** [comment]
yeah, that's simple to describe, but I only realized how to do it last night after bedtime.

vesting requires global purview.  while `stake_state::stake(epoch: Epoch)` *looks* like a function that only the bank/leader_schedule/fees/etc. needs, the per-epoch value of `stake()` is required for rewards redemption, which means that redeem_vote_credit() needs to see the (bank-calculated) per-epoch stake activations.

my epiphany was that I could put that into a sysvar.
