### ISSUE TITLE
Setup TdS-specific influxdb instance

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#5212]
During the TdS dry runs it'll be invaluable to receive metrics data from all nodes.  But we don't need everybody hammering metrics.solana.com.   

* [ ] Setup a separate VM to run the influxdb used by all TdS participants
* [ ] Provide a write-only account to all validators to use to publish their metrics + instructions on how to use it
* [ ] Add the TdS influxdb datasource to the metrics.solana.com grafana instance (or just run grafana on the new instance too?)

**Comment by danpaul000** [comment]
Should we use a new static hostname?  tds-metrics.solana.com?

**Comment by mvines** [comment]
Sure.  LMK the IP address and I'll setup the domain

**Comment by danpaul000** [comment]
35.233.136.212 for tds-metrics-solana-com

**Comment by mvines** [comment]
Done
