### ISSUE TITLE
accounts_db, accounts, bank serialize tests ignored

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#5231]
#### Problem
when addressing directory ownership problems in accounts_db, I found that the serialize/deserialize tests for accounts, accounts_db, and bank all overwrote an active accounts_db set of append_vecs.  Changing the code to use unique directories (to actually test serialize/deserialize) broke them.

#### Proposed Solution
unignore and fix serialize/deserialize

CC #5230

**Comment by rob-solana** [comment]
CC @sakridge @sambley

**Comment by sakridge** [comment]
I think this is by design. Can we close?

**Comment by rob-solana** [comment]
undone
