### ISSUE TITLE
solana-keygen doesn't generate keys from keys (BIP32 support)

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#5246]
#### Problem

A user may prefer to only hold one private key and want to generate more private keys deterministically from that first one (typically called an HD wallet).

#### Proposed Solution

Add a bip32 implementation to solana-keygen. Consider if it should be in `solana-wallet` as well.

 https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki

Some options:
* https://github.com/rust-bitcoin/rust-bitcoin/blob/master/src/util/bip32.rs
* https://docs.rs/bitcoin/0.18.0/bitcoin/util/bip32/index.html
* (yikes, no repo) https://crates.io/crates/bip32

**Comment by fkbenjamin** [comment]
A fair warning that the combination of bip32 and ed25519 can be vulnerable to certain attacks. Details can be found [here](https://cardanolaunch.com/assets/Ed25519_BIP.pdf) and [here](https://github.com/WebOfTrustInfo/rwot1-sf/issues/13).

I'm not an expert on the topic, but maybe something like this is worth a look: https://github.com/w3f/hd-ed25519

**Comment by garious** [comment]
@fkbenjamin, thank you so much!!

**Comment by CriesofCarrots** [comment]
Un-staling. This would actually be nice to address sometime soon-ish. With more wallet adoption, we're getting a lot of support questions about how to derive keypairs that match those of other wallets.

**Comment by t-nelson** [comment]
I've got an eye on https://github.com/jpopesculian/ed25519-dalek-bip32.  Unfortunately it's not quite flexible enough for our usage in its current form.  I'll try to get some issues up to their repos this week

**Comment by antoineherzog** [comment]
any update on this issue?

**Comment by CriesofCarrots** [comment]
> any update on this issue?

Hi @antoineherzog , just fyi that we're actively working on this now! Keep an eye on this issue for updates.

**Comment by CriesofCarrots** [comment]
I'm going to consider this issue completed by #16942 -- bip32 HD from seed phrase and pass phrase is now supported in solana command-line tools!
There is still additional work needed to support bip32 derivation from Keypair-file inputs; will open a separate issue describing.
