### ISSUE TITLE
Unnecessary protobuf requirement in Libra

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#5251]
#### Problem

The libra codebase uses Google protobuf to send data to its metrics server. We stuffed Golang and protobuf into our Docker containers to move forward, but neither is actually used. Furthermore, those dependencies aren't on our benchmarking servers and not on developer machines. Until we get those dependencies out, we can't integrate Move into our top-level build.

#### Proposed Solution

Add a `metrics` feature to libra that is *on* by default. Then patch libra to only use protobuf when that feature is present. Then when we add dependencies to libra packages, we should use `no-default-features` and add `metrics`.

Also, try to upstream that patch. If lucky, they'll want the feature *off* by default so that `dev_setup.sh` becomes optional for the dev community.

**Comment by TristanDebrunner** [comment]
Libra appears to use `protobuf` for any (de)serialization, so the `metrics` feature won't entirely remove the dependency. I think we also need a feature (such as `proto-serde`?) that enables that.

**Comment by garious** [comment]
Sounds good. `metrics` name just a placeholder for whatever makes the most sense.

**Comment by garious** [comment]
Also consider Rust protobuf implementations: 

https://www.google.com/search?q=rust+protocol+buffers

whatever makes our protobuf woes go away fastest

**Comment by TristanDebrunner** [comment]
So the problem is `protoc`, not `protobuf` itself?

**Comment by garious** [comment]
You tell us. The problem is we don't want Solana CI depending on installing Go and protobuf. How to make those dependencies go away, preferably today, is up to you.

**Comment by garious** [comment]
Two options were experimenting with here:
* Adding the generated Rust files to the libra git repo: https://github.com/solana-labs/libra/pull/2
* Publishing crates that include the generated Rust

**Comment by garious** [comment]
We added the generated code to git
