### ISSUE TITLE
Log level too high for InstructionErrors

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#5263]
#### Problem

`InstructionError` is often complemented by a `error!` log message. That puts the error message in the validator's log, but from the validator's perspective, there was no software error. It did what it was supposed to do. It's only an error from the perspective of the client.

#### Proposed Solution

Downgrade log messages triggered by transactions to `debug!`.

**Comment by garious** [comment]
@jackcmay, looking in the general direction of `move_loader_api` and `ERROR!` noise triggered by unit tests.

**Comment by jackcmay** [comment]
@garious Is this issue asking for a review of all the programs to bring them all to `debug!`, or is it asking for `move_loader_api` specifically?

**Comment by garious** [comment]
`move_loader_api` specifically. CC this issue, but don't close it.

**Comment by jackcmay** [comment]
Fixed in #5265

**Comment by jackcmay** [comment]
Oops, reopening to track other programs
