### ISSUE TITLE
staking key rotation

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#5327]
#### Problem
stakes may be long-lived, which exposes them to grinding

#### Proposed Solution
add a key rotation API, merely transfers state from one key to another

**Comment by rob-solana** [comment]
#5899 would fix this for me

**Comment by rob-solana** [comment]
sorted with authority, but not quite complete...

**Comment by garious** [comment]
@rob-solana, I see this issue is closed. Should it be?

**Comment by rob-solana** [comment]
yes.  #5988 is the replacement
