### ISSUE TITLE
Fork table metrics query is hanging

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#5425]
#### Problem
The new fork table in the metrics dashboard never seems to finish loading on the edge testnet metrics dashboard. https://metrics.solana.com:3000/d/testnet-edge/testnet-monitor-edge?refresh=1m&orgId=2&var-datasource=Solana%20Metrics%20(read-only)&var-testnet=testnet-edge&var-hostid=All&panelId=62&fullscreen&from=now-1h&to=now

#### Proposed Solution
Might need to restructure the query or beef up our metrics instance

**Comment by CriesofCarrots** [comment]
This table was removed from metrics in a code revert.
If it seems like we have a new need for BlockCommitmentCache data represented in metrics, let's open a new issue.
