### ISSUE TITLE
Improve wallet cli errors

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#5437]
Some of the wallet cli errors can be pretty unhelpful if you are unfamiliar with the system.  These instances come to mind:
* [x] create-vote-account from a keypair with insufficient lamports to pay the fee.  We can check the payer account balance before hand and cleanly error.  This should apply to all wallet transactions
* [x] create-vote-account for a vote account that already exists returns an unhelpful program error.  
* [ ]  `solana-wallet create-vote-account  "$IDENTITY_PUBKEY" "$VOTE_PUBKEY" 1` returns an unhelpful error
* [x] Always report the RPC end point the wallet is about to contact (to make it obvious when `--url` is not supplied that the user may be talking to the wrong cluster.  Also cc: #5436)
* [x] Be smart about detecting duplicate keys. `solana-wallet create-vote-account "$IDENTITY_PUBKEY" "$IDENTITY_PUBKEY" 1` should fail locally before sending a transaction

**Comment by CriesofCarrots** [comment]
@mvines , can you point me at the source of bullet 3? I am trying to determine whether it is the same issue as either bullet 2 or "failed transaction due to insufficient funds", or if it's something new...?

**Comment by CriesofCarrots** [comment]
Bullet 1: Done in #5474

**Comment by mvines** [comment]
> @mvines , can you point me at the source of bullet 3? I am trying to determine whether it is the same issue as either bullet 2 or "failed transaction due to insufficient funds", or if it's something different...?

This bullet was about running `solana-wallet create-vote-account` with the vote and identity pubkeys swapped

**Comment by CriesofCarrots** [comment]
Bullet 4: Done #5482

**Comment by CriesofCarrots** [comment]
Bullet 2: Done in #5494

**Comment by CriesofCarrots** [comment]
Bullet 5: Done in #5497
