### ISSUE TITLE
Too much stake too fast

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#5443]
The root cause of the TdS stage 0 dry run 2 cluster failure was due to too much stake coming online from epoch 6 to epoch 7.

#### Epoch 6 Stake
```
2QMWpknvQT9GzQaAS2LZRRbi2kVo5Q1ruAqyoj25jnaq   | stake=8589934592  
5QRvZmVCC6FDsvQw7CxMijrX8NdJCGA49YQo3veE9y4B   | stake=8589934592  
8ohZ3JU9jGJQt9ftBNa2ScPpn5ui7j5F8aSn13hi8uWy   | stake=8589934592  
G3BHHnWZR7bvmfhqhRBF7V5sVmABZEeQaXodfguy2n1q   | stake=8589934592  
```

#### Epoch 7 Stake
```
2QMWpknvQT9GzQaAS2LZRRbi2kVo5Q1ruAqyoj25jnaq   | stake=8589934592  
2X5JSTLN9m2wm3ejCxfWRNMieuC2VMtaMWSoqLPbC4Pq   | stake=5726623060  
33LfdA2yKS6m7E8pSanrKTKYMhpYHEGaSWtNNB5s7xnm   | stake=5726623060  
47UuTGPAQZX2HnVcfxKk8b1BtA4rRTduVaHnvxzQe6AJ   | stake=5726623060  
4Bx5bzjmPrU1g74AHfYpTMXvspBt8GnvZVQW3ba9z4Af   | stake=5726623060  
55nmQ8gdWpNW5tLPoBPsqDkLm1W24cmY5DbMMXZKSP8U   | stake=5726623060  
5NH47Zk9NAzfbtqNpUtn8CQgNZeZE88aa2NRpfe7DyTD   | stake=5726623060  
5QRvZmVCC6FDsvQw7CxMijrX8NdJCGA49YQo3veE9y4B   | stake=8589934592  
6dMH3u76qZ7XG4bVboVRnBHR2FfrxEqTTTyj4xmyDMWo   | stake=5726623060
8FaFEcUFgvJns6RAU4dso3aTm2qfzZMt2xXtSgCh3kn9   | stake=5726623060  
8ohZ3JU9jGJQt9ftBNa2ScPpn5ui7j5F8aSn13hi8uWy   | stake=8589934592  
9J8WcnXxo3ArgEwktfk9tsrf4Rp8h5uPUgnQbQHLvtkd   | stake=5726623060  
G3BHHnWZR7bvmfhqhRBF7V5sVmABZEeQaXodfguy2n1q   | stake=8589934592  
```

![image](https://user-images.githubusercontent.com/1281082/62584634-54303380-b86a-11e9-868a-8b60aa66ca26.png)

cc: https://github.com/solana-labs/solana/blob/f7d3f5556610e02462c32f3db42472c739b847f7/core/src/consensus.rs#L337-L338

**Comment by rob-solana** [comment]
this is ameliorated by using live stakes as in #5426, but making everyone slow their roll would be a good thing TM

this is also potentially hot-patch-able by removing the threshold check

**Comment by mvines** [comment]
@rob-solana - it looks like the stake went from 0 to 66%, not 33%

**Comment by carllin** [comment]
@rob-solana, I can also hotfix it by using the EpochStakes for the threshold bank rather than the new EpochStakes

**Comment by rob-solana** [comment]
@mvines the stake changing from 0-66% is an artifact of epoch stakes, which are a snapshot

Say we take a snapshot halfway through epoch 5 (for epoch 7), if a stake activates in the very next slot, the next time it ends up in epoch stakes will be halfway through 6 (for epoch 8), in which case it's had 2 epochs of ramp (5 and 6)

**Comment by mvines** [comment]
I don't think we need to hack together a super quick fix for this if it moves us away from a more complete solution.  Is that #5426 or do we need more in addition?  I think it's reasonable to continue to expect that in a TdS setup, we'll go from 0 delegated stake to a large N very quickly as participants jump on at the start.

**Comment by rob-solana** [comment]
#5426 will help with this, because the stakes will ramp 0->33->66 correctly

**Comment by mvines** [comment]
But we could still run into the same problem if we go from 4 staked validators in epoch 6 to ~50 staked validators in epoch 7?  Even with just 33% active, the amount of new stake would exceed that threshold check right?

**Comment by rob-solana** [comment]
in #5426 the stakes used are for the bank under voting consideration, which means the stakes come on by slot, not epoch, and so more smoothly

**Comment by rob-solana** [comment]
CC @carllin

**Comment by mvines** [comment]
Cool so #5426 will fix this issue yes? :)

**Comment by rob-solana** [comment]
yes, I think it should

**Comment by carllin** [comment]
@rob-solana, I think it will need to be paired with the warmup limitations as well?

**Comment by rob-solana** [comment]
@carllin I don't think it matters for TdS dry runs

**Comment by rob-solana** [comment]
live stakes are smoother than epoch stakes, even with 33% per epoch warmup

**Comment by carllin** [comment]
@rob-solana is there a guarantee that the live stake won't shift by more than 33% between the threshold bank and the live bank you are considering?

**Comment by rob-solana** [comment]
no guarantees, just a lot less likely than if you're looking at epoch stakes

**Comment by mvines** [comment]
Calling this done based on what I observe on the edge testnet this morning, my node's stake is coming in nice and slow
