### ISSUE TITLE
Snapshot Package: Incorrect usage of hard links

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#5448]
#### Problem
`[2019-08-06T15:08:25.988279757Z INFO  solana::snapshot_package] Error from package_snapshots: IO(Os { code: 18, kind: Other, message: "Invalid cross-device link" })`

I noticed several of these in the bootstrap leader's logs from TdS stage 1 dryrun 2 today.  The snapshot packaging services uses hard links to point snapshot archives from the temp path they were created in, to the output directory they are expected to be served from.  Hard links are limited to a single filesystem (see `EXDEV` error code in `man 2 link`) and there for the temp dir and output dir can't cross filesystem boundaries.

#### Proposed Solution

https://github.com/solana-labs/solana/blob/72e9492ca60726f7f575d0c9ffd38bc642066828/core/src/snapshot_package.rs#L115

Verify that snapshot temp and output directories reside on the same filesystem *or* use symlinks.  We're probably going to run into portability considerations either way

cc: @carllin

**Comment by carllin** [comment]
Ah good catch! I think the fix here is to make a temp file for the archive within the output directory, then rename it. That way we don't cross filesystem boundaries.

**Comment by t-nelson** [comment]
That'd work!  Maybe even easier would be to write to a temp *filename* in the output dir, then just rename it once the snapshot is finalized.
