### ISSUE TITLE
Change default cluster transaction fee from 42 to ~2^28 

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#5467]
The default placeholder transaction fee for a cluster is 42.  A more realistic value is probably in the ballpark of 2^28.

This'll affect the initial starting balance of TdS validators as 1 SOL, so that'll need adjustment as well: https://github.com/solana-labs/tour-de-sol/blob/5d35973084e88541c9bfdc40e0280944838140fb/import-keybase-usernames.sh#L5

**Comment by ericlwilliams** [comment]
Reference (WIP): https://solana.shinyapps.io/initial_network_parameters/

**Comment by mvines** [comment]
For SLP1, a min/max fee of 1 lamport per transaction might be best since the cluster is just idle voting.  The purpose of the transaction fee then is just to avoid spam transactions that do nothing but fill the ledger.
Then when the cluster rolls into SLP2 (cc: #5757), the fees increase.

**Comment by mvines** [comment]
Scratch that last comment.  Instead of messing with fees between SLP1/SLP2, we can just account for the _higher_ fees for SLP1 and avoid adding more code

**Comment by mvines** [comment]
The current target signature rate is 710k, which is way too high
https://github.com/solana-labs/solana/blob/7cf90766a3a991d9ead3016031144b8cd1718779/sdk/src/fee_calculator.rs#L31

Reducing to 50k seems more current

**Comment by mvines** [comment]
Proposal:
```diff
-pub const DEFAULT_TARGET_LAMPORTS_PER_SIGNATURE: u64 = 42;
+pub const DEFAULT_TARGET_LAMPORTS_PER_SIGNATURE: u64 = 171717;
```
and
```diff
 pub const DEFAULT_TARGET_SIGNATURES_PER_SLOT: usize =
-    710_000 * DEFAULT_TICKS_PER_SLOT as usize / DEFAULT_TICKS_PER_SECOND as usize;
+    50_000 * DEFAULT_TICKS_PER_SLOT as usize / DEFAULT_TICKS_PER_SECOND as usize;
```
