### ISSUE TITLE
Document what the network will do if the runtime has non-deterministic execution

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#5481]
#### Problem

1. transaction in a block creates a non-deterministic state
2. everyone voted on the block that caused the non-deterministic state
3. everyone will build blocks on top the last block they voted on
4. everyone else will reject everyone else's block, because the bank hash for the vote is wrong

#### Proposed Solution

Network shouldn't actually fall back, this is a invalid state, and we should halt, pager duty can call @mvines  :smiley:

**Comment by mvines** [comment]
I don't know how one node would be able to detect this condition and halt in a sane way.  Each node just sees bad votes from all other nodes, but that could also be a result of some kind of attack no? 

I think this kind of a bug is just something that must not happen in production.  It's a roll back if does, at the slot prior to the non-determinism with a new software build.

**Comment by aeyakovenko** [comment]
@mvines that’s what I am saying. But it needs to be a human directed hard fork.  

Detection seems easy.  Just observe a supermajority disagree about the bank hash.  Once that happens no fork will reach consensus.

**Comment by mvines** [comment]
Got it.  Yep, fully agree then.  We need a SOP should this happen for pager duty @mvines to follow at 3am!
