### ISSUE TITLE
hash_internal_state can be done on another thread

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#5498]
#### Problem

`hash_internal_state` is pretty expensive, it can be ~100ms per 400ms slot. Since we block on creating the hash before creating the bank for the next slot, it removes about 20% of the time for the TPU to operate between slots.

#### Proposed Solution

Move the hash_internal_state operation to another thread asynchronous of getting the new bank for the next slot. This allows the hashing operation to take place while computing transactions for the next slot simultaneously.

**Comment by mvines** [comment]
@sakridge - looks like you had a WIP fix for this at #5495, do you recall why that PR was closed?

**Comment by sakridge** [comment]
@mvines this is already fixed by https://github.com/solana-labs/solana/pull/5573
