### ISSUE TITLE
testnet cluster

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#550]
#547 has a test that validates we can synchronize 25 nodes on loopback on my mac with randomly killing the nodes.  so its a barebones `live testnet` test.  We should setup a live network to actually run it.

Two kinds of clusters basically, self contained:
- [x] setup a box to run test_multi_node_dynamic_network with a large set of cores

Cloud:
- [x] script to boot a testnet instance on GC with N nodes, and a sha of a commit

The only sane way i've seen debugging multi node networks is via a bunch of live event counters:
- [x] hookup graphana to monitor these counters (can we get a dashboard per cluster instance, dropbox had support for this somehow)
 * leader broadcast counter
 * validator consumed
 * validator received
 * repair requests
 * number of purges to crdt table
 * number of adds to crdt table

Basically, how we can test and debug: 
1. increase N
2. run large number of transactions
3. observe graphana counters.  

The lag from broadcast to consumed/received counters should be due to how well we choose who to talk to about the missing blobs in the window.  The number of purges and adds should be 0, and it should only increase if we are poorly choosing who to ask for gossip requests.  So we should be able to tweak those parameters and observe the stats improve.

We need this for a large N
- [x] have validators send its `ReplicatedData` with the last id set to what it processed as a `vote`.  these broadcasts should shortcut the membership event propagation in the network.  (@aeyakovenko)

Once we are comfortable with N
- [x] setup validator nodes on the actual testnet to talk to the leader

**Comment by rob-solana** [comment]
I'm a little uncomfortable with replication not working well for small N.  How do I get comfortable with that?  Is there an explanation available?

**Comment by aeyakovenko** [comment]
@rob-solana yea. With 3 validator nodes, when we drop 1 we introduce a 33% packet drop.

**Comment by aeyakovenko** [comment]
We can fix it with a faster gossip loop for tiny networks

**Comment by aeyakovenko** [comment]
Or a test that sends N entries.  The problem is that 1/3rd of the time the first node is the bad one and the network won’t realize it needs to repair anything

**Comment by garious** [comment]
@aeyakovenko, this issue has too many parts, too many assignees (more than one) and isn't attached to a milestone. Looks like the consequence is you flying solo on #558 and diverging from `master`.

**Comment by mvines** [comment]
I think this issue is done, or at least close enough.  If there's anything that anybody feels has not been completed here let's please create a new issue for each item
