### ISSUE TITLE
Upgrading rocksdb introduces compiler errors

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#5507]
#### Problem

An upgrade from rocksdb 0.11.x to 0.12.x causes compilation failures.

#### Proposed Solution

Fix 'em so that `core` doesn't sink with that ship

**Comment by garious** [comment]
@mvines, the underlying C code dependency is the concern here. If a security vulnerability is published, the fix is more likely to be published to the latest version. The compilation failures that prevent a quick upgrade is a liability. Can you attach this one to a milestone?

**Comment by garious** [comment]
For reference, the compiler errors: https://github.com/solana-labs/solana/pull/6271

**Comment by TristanDebrunner** [comment]
Updating libra (#6341)  is blocked on this due to dependency conflicts

**Comment by TristanDebrunner** [comment]
I'm having trouble finding a workable solution here. There doesn't seem to be a way to reconcile the API changes with the `Backend` abstraction we created for kvstore. `rocksdb` master reverts the changes that are causing the problem, so it's possible that waiting for 0.13.x could fix the problem without significant effort on our part.

**Comment by garious** [comment]
We no longer have a need for the kvstore abstraction. Want to take a stab at ripping it out?
