### ISSUE TITLE
solana-cli docs out of date

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#5529]
#### Problem
https://github.com/solana-labs/solana/blob/master/book/src/wallet.md
Wallet documentation is from v0.12 😱 
...and it was more of a design doc for budget commands than complete and proper documentation

#### Proposed Solution
Update and expand it to cover current implementation

**Comment by mvines** [comment]
Latest link is https://github.com/solana-labs/solana/blob/master/book/src/api-reference/cli.md, and still references v0.12.

**Comment by CriesofCarrots** [comment]
> Latest link is https://github.com/solana-labs/solana/blob/master/book/src/api-reference/cli.md, and still references v0.12.

? Where are you seeing v0.12?
I see v0.20 here: https://github.com/solana-labs/solana/blob/master/book/src/api-reference/cli.md#solana-cli-1

**Comment by mvines** [comment]
I was looking at 0.19 🤦‍♂ 

but 47e1ea107b99391c60a244380ddd1920f79aaaf2 adds the new `show-validator` command I just landed to the docs, and we're now up to date
