### ISSUE TITLE
solana-genesis support for pre-created vote and stake accounts

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#5555]
`solana-genesis` needs the ability to provision a genesis ledger with a set of vote and stake accounts, so the cluster can boot without the system program available.

A fairly generic  approach would be to enable SystemInstruction::CreateAccount via  `solana-genesis`, perhaps as a yaml input that supplies the CreateAccount parameters.   Once the cluster boots, the vote/stake accounts then still need to be initialized (which will require some `solana-wallet` changes as the wallet wants to CreateAccount too)

Update: this approach seems better than what's in the last paragraph: https://github.com/solana-labs/solana/issues/5555#issuecomment-522713018

**Comment by rob-solana** [comment]
what part of this is not supported?

**Comment by mvines** [comment]
We can create system accounts right now, but not accounts with arbitrary owners and size

**Comment by rob-solana** [comment]
bootstrap leader vote and stake accounts aren't system accounts, do you mean you want to put transactions in the ledger instead of having the array of genesis accounts in genesis block?

**Comment by mvines** [comment]
No, an array of genesis accounts is just perfect.  We just can't supply non-system accounts as an input file to `solana-genesis` (but yes we can certainly construct non-system accounts in code from within `solana-genesis`)

**Comment by rob-solana** [comment]
oh, I see.  yeah, the primordial accounts feature is a little feeb.  I didn't realize it had this limitation.

**Comment by ParthDesai** [comment]
@mvines What's the difference between `SystemInstruction::CreateAccount` and `stake_state::create_account`? 

Aside from that, if I only go by name, and my limited grasp of implementation, I think we should use `stake_state::create_account` and `vote_state::create_account` and take parameter as input file. 
wdyt?

**Comment by rob-solana** [comment]
Parth, I think the best path here is to just rewrite the code that parses the accounts file to use serialized (key+account) instead of serialized (key+amount)
