### ISSUE TITLE
stake account lamport balance can drop below amount staked from rent

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#5564]
#### Problem
rent is automatically deducted from accounts by the runtime as time passes
stake accounts carry `stake` as a number in the account, separate from the balance

this means that a "non-exempt" stake account's lamports balance can drop below the `stake` inner variable on rent collection

#### Proposed Solution(s)
* have delegate_stake() take information about what constitutes an exempt balance and fail activation unless the account's lamport balance is sufficient (implies a new sysvar or config account)
* have the runtime return min(staked, account.lamports) for stake value (defeats to some extent warmup/cooldown)

**Comment by rob-solana** [comment]
CC @aeyakovenko

**Comment by aeyakovenko** [comment]
@rob-solana other programs will want to enforce that account balances are above the rent price.  I think a sysvar is the right approach.

**Comment by mvines** [comment]
Depends-on: #4372

**Comment by mvines** [comment]
Fixed.  Stake accounts must be rent exempt:
https://github.com/solana-labs/solana/blob/41067de5e43699b51c3236d575fc234b79b772d5/programs/stake_api/src/stake_instruction.rs#L280
