### ISSUE TITLE
Fix ignored tests

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#5579]
The following tests were ignored in #5541. Need to isolate the issue and fix the tests

- [x] test_broadcast_ledger
- [ ] window_send_test
- [ ] window_send_leader_test2
- [x] test_storage_stage_process_banks
- [ ] test_replay

**Comment by pgarg66** [comment]
https://github.com/solana-labs/solana/issues/5294

**Comment by mvines** [comment]
All the tests referenced by this issue seem to not exist anymore
