### ISSUE TITLE
`./net.sh sanity` frequently fails ledger-verify step

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#5597]
#### Problem
```
--- 35.197.60.130: verify ledger
+ rm -rf /var/tmp/ledger-verify
+ du -hs config/bootstrap-leader
348M	config/bootstrap-leader
+ cp -r config/bootstrap-leader /var/tmp/ledger-verify
cp: cannot stat 'config/bootstrap-leader/accounts/821.854': No such file or directory
```

It seems like `cp` is losing a race with `snapshot_service` ?  It took three tries for it to succeed 

#### Proposed Solution

--
cc: @carllin

**Comment by mvines** [comment]
I'm not opposed to removing the verify ledger check entirely.   We have it turned off for most testnets already because it's too slow to run on a non-trivial ledger.   I can't think of a single bug we've caught with it either.

**Comment by t-nelson** [comment]
That would certainly reduce time to debug!
