### ISSUE TITLE
Shred deserialization panic on validator startup

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#5618]
#### Problem

I get the following panic when trying to start a validator on a node in our colo.  The build/deploy were performed by `./net.sh start` at aeaa0fe.

https://gist.github.com/t-nelson/94436ee170d4aa7a439b4dc14560d3b1

**Comment by t-nelson** [comment]
cc: @pgarg66

**Comment by pgarg66** [comment]
@t-nelson can you share the steps to reproduce the problem?

**Comment by t-nelson** [comment]
@pgarg66 Yup, updated the OP.

**Comment by pgarg66** [comment]
Are you running the node with an old ledger? Or is it a new node with no old database?

**Comment by t-nelson** [comment]
I'm a little green as to what all `net.sh` does regarding cleanup, but I intended for it to be a fresh start with no old DB.  I'll do a little digging and report back

**Comment by pgarg66** [comment]
Sounds good. Thank you!
Only reason I am asking these questions is that we are able to run TdS and other dev testnets using this code.

**Comment by mvines** [comment]
FWIW, I just rebooted the edge testnet and it came up fine too

**Comment by t-nelson** [comment]
OK, so I wiped `~/solana/` on the colo bootstrap-leader node, reran `./net.sh start --no-deploy` from my laptop and was able to reproduce.

I'll have `net.sh` able to deploy debug builds after lunch.  Hopefully that can reveal something more

**Comment by t-nelson** [comment]
This might be a false alarm.  It seems like I need to extend the cleanup procedures in the colo scripts.  I just realized that the `solana-validator-cuda` binary on this node is stale, likely from a tarball install used to validate the environment...

**Comment by t-nelson** [comment]
Confirmed!  Sorry for the noise
