### ISSUE TITLE
Inconsistent TPS performance and tower consensus

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#5678]
#### Problem
The TPS and consensus performance is quite inconsistent on tip of v0.18.
For a 10 node test, the TPS graph look like this

![image](https://user-images.githubusercontent.com/40076733/63797278-9b837000-c8bc-11e9-9ebf-8d76c07b8e4c.png)

Consensus graphs look like this
![image](https://user-images.githubusercontent.com/40076733/63797312-b229c700-c8bc-11e9-829e-770210817584.png)

#### Proposed Solution
Debug and fix

**Comment by pgarg66** [comment]
The testnet is showing more consistent performance for TPS and consensus now. Closing this issue.

**Comment by mvines** [comment]
🤘
