### ISSUE TITLE
ci: Use Packer to manage CI images

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#570]
Currently we hand build our CI images on GCP (see `ci/README.md`).  Instead let's use [Packer](https://github.com/hashicorp/packer) to build the images from *source* and at the same time ideally make them portable between the different cloud providers

**Comment by mvines** [comment]
Manual steps to move the buildkite-agent home directory that should be done automatically by Packer:
1. Edit /etc/passwd to adjust the buildkite-agent home to `/home/buildkite-agent`
2. `sudo mv /var/lib/buildkite-agent /home/`
3. `sudo ln -s /home/buildkite-agent /var/lib/buildkite-agent`

**Comment by mvines** [comment]
Packer should add these two lines to /etc/security/limits.conf:
```
buildkite-agent  soft nofile 65000
buildkite-agent  hard nofile 65000
```

**Comment by pgarg66** [comment]
Added following lines to /etc/sysctl.conf
net.core.rmem_max=1610612736
net.core.rmem_default=1610612736

And, reload sysctl by
sudo sysctl -p
