### ISSUE TITLE
Clean up solana-validator-cuda workflow

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#5722]
With `validator.sh` well on it's way to the curb, there's nobody to set LD_LIBRARY_PATH for `solana-validator-cuda` so users are having to set it manually.  This is a terrible user experience.

**Comment by garious** [comment]
Is it practical to set the executable's RPATH instead of the user's LD_LIBRARY_PATH?

**Comment by mvines** [comment]
The problem is that we have multiple `libcuda-crypt.so`, one for each CUDA version we support.   source target/perf-libs/env.sh` from the install location does the trick, but finding that file is clunky right now 💭

**Comment by mvines** [comment]
I went for the easy win of turning `solana-validator-cuda` into a bash script that first loads the perf-libs environment and then execs the real `solana-validator-cuda`.
