### ISSUE TITLE
solana-cli --help doesn't always show all arguments

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#5736]
eg:
`solana deactivate-stake --help` doesn’t show that -u/-k args can be applied

Is there a way to show the solana arg help on the subcommands?  Not sure if clap has a mechanism for that...

**Comment by CriesofCarrots** [comment]
The only built-in clap solution appears to be to replace the auto-generated help messages with hand-rolled custom messages: https://docs.rs/clap/2.33.0/clap/struct.App.html#method.help
This seems less than ideal...
