### ISSUE TITLE
Document procedure for deactivating stake

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#5737]
During TdS DR 4, there was some confusion about how to deactivate stake.  Totally understandable as we didn't really document how much.

**Comment by rob-solana** [comment]
I think this is covered?
https://github.com/solana-labs/solana/blob/master/book/src/validator-stake.md

**Comment by mvines** [comment]
We could augment that doc slightly to caution the risks associated with not properly destaking, and how to confirm a validator is fully destaked.  Perhaps right at the top before we show the how to stake!
