### ISSUE TITLE
Local slot is not updating

### ISSUE THREAD

**Issue by wlsaud619** [solana-labs/solana#5767]
#### Problem
**> Testnet**
    - Public Testnet
    - address: 9MUTxbr7dt22a2DD2PcJujEJwyam8bh8gNegofiA5Y3S

**> Version**
    - {"jsonrpc":"2.0","result":{"solana-core":"0.18.0"},"id":1}

**> Problem** 
    - Local slot is not updating

![image](https://user-images.githubusercontent.com/17901095/64091108-9d9c7180-cd89-11e9-877e-9c0ffa7b689e.png)

**Comment by mvines** [comment]
@wlsaud619, is this a reproducible issue for you or did it only occur once?   It looks like your firewall/router/NAT may not be configured to allow port access to the machine your validator is running on.

**Comment by mvines** [comment]
Pretty sure this is resolved, somehow.   If it reproduces once 0.19.0 is released please feel free to re-open
