### ISSUE TITLE
Adjust solana-cli, if needed, to work with zero-initialized vote/stake accounts

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#5769]
`solana-cli` currently assumes it can use a system transfer to create a vote and/or stake account.  But this won't work in SLP1 were the system program is unavailable and all accounts have been provisioned via `solana-genesis` (cc: #5555).   

Either `solana-cli` can take an option to `create-{vote,stake}-account` that specifies the account already exists, or it can dynamically first check to see if it does.

**Comment by rob-solana** [comment]
vote accounts don't properly support being zero-initialized...  zero-initialized vote accounts can be taken over by anybody

**Comment by rob-solana** [comment]
what if we made the system account available for making program_id assignments?

**Comment by mvines** [comment]
I've been hoping to keep the granularity of block-based _features_ to be at the level of program availability, maybe that's a pipe dream.   Another way would be to require the uninitialized vote/stake account provide its signature to perform initialization though right?

**Comment by rob-solana** [comment]
> I've been hoping to keep the granularity of block-based _features_ to be at the level of program availability, maybe that's a pipe dream. Another way would be to require the uninitialized vote/stake account provide its signature to perform initialization though right?

yeah, that'd work, but would require backing out again before SLP2

**Comment by mvines** [comment]
Why would it need to be backed out?

**Comment by rob-solana** [comment]
unless we backed it out, the create_account() TXes will require 2 signatures or will have to be 2 TXes...

**Comment by mvines** [comment]
I don't see a problem with that

**Comment by rob-solana** [comment]
some wallets don't support that...

**Comment by mvines** [comment]
While some wallets only support one private key per user, I don't see why in the process of creating a transaction with that private key, they couldn't create/use an ephemerial private key (eg, the stake account's keypair that's only used to initialize the stake account).   At least in the case of Trust Wallet, we supply a hunk of C++ code to actually create/send transactions -- the restriction was just that Trust Wallet will only hold one private key for us.

**Comment by rob-solana** [comment]
I've just realized that the initialization transaction will _always_ require 2 signatures: one from the payee and one from the stake keypair

**Comment by rob-solana** [comment]
Instead of a zero-initialized vote and stake account, it'd be preferable to have them initialized (authorized_voter, authorized_staker, and (possibly) authorized_withdrawer) to the stake/vote account owner's system-account pubkey.  This approach gets us over all the humps and is fairly straightforward.

**Comment by mvines** [comment]
Looks like we don't need this after all
