### ISSUE TITLE
Rust BPF: target specification uses "linux" as OS, should not be

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#5771]
#### Problem

Pulls in linux stuff in libstd

#### Proposed Solution

Should be something else, maybe "unknown"...

**Comment by garious** [comment]
The triple? Yes, `unknown`, if that's available

**Comment by jackcmay** [comment]
Yup, the triple is already `unknown`, but within the spec we were using `Linux` as the OS due to some libcore restraints.  I'm unwinding those restraints in libcore and libstd and switching the spec to use `unknown`
