### ISSUE TITLE
Warn validators about stake deactivation at process exit

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#5773]
#### Problem

No warning is given to validators that their stake should be deactivated before stopping the process.  This can lead to large amounts of stake going offline, presumably inadvertently, potentially losing our quorum.

#### Proposed Solution

1) Catch `SIGINT`/`Ctrl-C`
2) Warn the user of active stake
3) Automatically begin stake deactivation (? Might not always be what's wanted)
4) Allow process to exit normally upon a second `SIGINT`/`Ctrl-C`

**Comment by cyberbono3** [comment]
Can I start working on it?

**Comment by mvines** [comment]
The latest attempt at this issue can be found at https://github.com/solana-labs/solana/pull/7618
It doesn't seem to work quite right.  When I Ctrl+C the bootstrap leader, when I know it has stake, the validator exits on the first try without a warning.
