### ISSUE TITLE
RPC vulnerable to DoS

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#5778]
#### Problem
RPC is unauthenticated, free, and probably not hardened against DoS attacks, like slow clients, infinite requests, infinite connections, etc.

#### Proposed Solution
audit and fix?  add authentication to RPC?

**Comment by mvines** [comment]
For now we mitigate this by recommending that staked validators not expose an RPC port, and instead provide RPC from an unstaked "api node"
