### ISSUE TITLE
inflation of foundation pool

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#5786]
#### Problem
inflation, as specified, is split among validator rewards, storage rewards and the foundation
foundation pool/pools doesn't/don't exist yet

#### Proposed Solution
possible approaches:
* keep a list of the accounts to be inflated as "the foundation"
* add a new account owner that allows the bank to find these accounts?
* ?

**Comment by rob-solana** [comment]
CC @aeyakovenko @ericlwilliams

**Comment by rob-solana** [comment]
@aeyakovenko @ericlwilliams any updated thinking on this?

**Comment by aeyakovenko** [comment]
@rob-solana i think the plan is to handle it of chain.   Basically only delegate to people who can follow directions and lockup rewards.

**Comment by solana-foundation** [comment]
@aeyakovenko how does that relate to the inflation % specified to the Foundation?

**Comment by ericlwilliams** [comment]
@aeyakovenko how does that relate to the inflation % specified to the Foundation?

**Comment by aeyakovenko** [comment]
@rob-solana @ericlwilliams 

so the % reward fee that is given to the foundation from the total inflation, is basically like a fixed global commission on all inflation rewards.

**Comment by ericlwilliams** [comment]
Yeah, that was my understanding as well

**Comment by rob-solana** [comment]
The question here is how inflation code will identify the Foundation accounts.

Under the current configuration, in the first epoch, the BS leader will earn:
```
500_000_000SOL // capitalization
  * 0.15 // inflation at T=0
  * 0.85  // validator rewards portion of inflation
  * 32   // slots in first epoch, about 13 seconds worth
  / (365*24*3600/0.4) // slots per year
```
Which is approximately 26SOL.  The 2nd epoch is double that, and so on, until other nodes come online and more points are available, which will lead to rewards points dilution.

The Foundation is supposed to see 1.5SOL of that first epoch's inflation.

**Comment by ericlwilliams** [comment]
Does it have to identify the Foundation accounts or can we just specify a
new account where the Foundation inflation rewards land?

**Comment by mvines** [comment]
Not sure if this issue is even relevant anymore actually.

**Comment by mvines** [comment]
My bad, this is relevant still.  The foundation/foundation_term fields in sdk/src/inflation.rs aren't hooked up to anything

**Comment by ericlwilliams** [comment]
Looks like we're lumping Grant and Foundation inflation issuances into the Foundation terms here, which I think is fine, but since we originally scoped 5% grant & 5% foundation, might bump foundation inflation default to 10% for now.  I think 7 years default is also okay to keep for now. Will publish and circulate official numbers before go-live.

**Comment by ryoqun** [comment]
@ericlwilliams @mvines I think we need to address this before enabling inflation on mainnet-beta, which is nearing to realize. :)

**Comment by ryoqun** [comment]
@ericlwilliams I need specific hard-coded accounts to transfer the rewards for foundation and grant to like these: https://github.com/solana-labs/solana/blob/e556f85178af23873a778ddec88a98432b57e3c7/core/src/non_circulating_supply.rs#L58-L80

Maybe the accounts will be one of them, because the accounts should be regarded as non-circulating?

**Comment by ericlwilliams** [comment]
@ryoqun I see!  Let me sync with @danpaul000 on this today and try to get those for you

**Comment by danpaul000** [comment]
@ryoqun will the foundation accounts receiving rewards be system accounts, or stake accounts?  If system, does it matter if the account exists/is already funded or not?

**Comment by mvines** [comment]
It can be any account.   The bank would just deposit the foundation rewards in that account.   Also consider if we just want 1 account or multiple (and if multiple how do the rewards get split up between them)

**Comment by mvines** [comment]
Temporary plan for pico-inflation is to just set the foundation rate to 0% to bypass this entirely
