### ISSUE TITLE
Book-edge install instructions should point at edge, not release

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#5803]
#### Problem
https://solana-labs.github.io/book-edge/validator-testnet.html
and
https://solana-labs.github.io/book-edge/running-replicator.html
instruct the reader to use `solana-install` on 0.18.0.  

#### Proposed Solution
Make sure the edge book points to the edge builds in the docs.  Only when we branch should these instructions get a numbered release associated with them.

**Comment by mvines** [comment]
We could add a template value in the book text itself, then swap it out with the correct release number as a build step in https://github.com/solana-labs/solana/blob/master/book/makefile

**Comment by ryan-shea** [comment]
@mvines @danpaul000 since Github looks directly at the /src files, wouldn't using a template value cause the template value to be displayed on the docs? 

We could have a /build directory that then pushes the book to /src.

**Comment by mvines** [comment]
We can probably teach `scripts/increment-cargo-version.sh` how to do this using the actual version number by blindly replacing the old version in `book/src` with the new version.  That works directly into our existing branching workflow

**Comment by ryan-shea** [comment]
@danpaul000 @mvines Sorry for the delay on this one. Midterms took up a significant chunk of my week.

Here's as far as I've gotten with my additions https://github.com/solana-labs/solana/pull/6177

Any guidance for how to push it across the line?

Thanks.
