### ISSUE TITLE
Installing Validation Software

### ISSUE THREAD

**Issue by Sam31000** [solana-labs/solana#5808]
#### Problem
Hi,

When I try to install the validation software on my mac book pro using the command: 
`curl -sSf https://raw.githubusercontent.com/solana-labs/solana/v0.18.0/install/solana-install-init.sh | sh -s
`
I have the error below : 

```
looking for latest release
downloading v0.18.1 installer
curl: (22) The requested URL returned error: 404 Not Found
solana-install-init: command failed: downloader https://github.com/solana-labs/solana/releases/download//v0.18.1/solana-install-init-x86_64-apple-darwin /var/folders/30/cqgp6r4d71q4tygg6xrl543h0000gr/T/tmp.suU2eRJc/solana-install-init
```

#### Proposed Solution
I noticed that there is 2 "//" on "download//v0.18.1/" and an extra space between "darwin" and "/var" here "x86_64-apple-darwin /var/folders" but even after correcting this the error is still here.

**Comment by mvines** [comment]
You just got lucky!  We are in the process of releasing v0.18.1, and while the github tag exists not all the build artifacts exist (they're still getting built).

For now I've marked the v0.18.1 release as a pre-release, which should solve your issue.  Once the v0.18.1 artifacts finish building we'll remove the pre-release flag from v0.18.1

**Comment by Sam31000** [comment]
I just tried it now and everything went fine :)

Thx.
