### ISSUE TITLE
solana_core::replay_stage] Fatal replay result in slot: X, result: Err(TransactionError(AccountInUse))

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#5895]
Edge testnet is regularly dying because one of the nodes encounters an AccountInUse error in replay_stage, marks that slot as dead, and forks off into the weeds.

**Comment by mvines** [comment]
Reverting #4978 appears to avoid this issue

**Comment by rob-solana** [comment]
CC @ParthDesai are you tracking this?

**Comment by mvines** [comment]
I'm actively debugging this

**Comment by mvines** [comment]
I'm not convinced it's actually #4978 yet.  The account in-use is a validator's identity keypair that's trying to pay for a vote.  But looking at the entries being processed and the accounts that are currently locked, it doesn't seem like there ought to be an account in-use conflict.  But it's a race somewhere because adding more logs can make the error disappear for me.

**Comment by mvines** [comment]
Yep it was #4978 :)
