### ISSUE TITLE
re-keying of accounts

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#5899]
#### Problem
No general facility to rekey or delegate authority of an account in Solana exists.   This manifests as a problem in several ways:

* programs that wish to support re-keying or alternative authority must implement this on their own, leading to replicode and (replicated) bugs
* programs that require authority that don't implement it themselves (i.e. use the account's address as the authority) expose themselves to grinding attacks or require some kind of manual re-keying. 
* programs that: 
   1. require authority of the account and
   2. don't implement alternative authority 

    require that authorized transactions carry multiple signatures (one for issuance of the instruction and one for the program authority), making them inaccessible to wallets that can only handle one keypair.
* programs that carry pubkeys as addresses in state expose their targets to grinding attacks, force those addressed accounts to implement alt-authority, or require big, costly re-keying effort (e.g. multiple stakes pointing at a vote account.  re-key the vote account and you've gotta touch every stake)

#### Proposed Solution
add an `authority` field to Account that defaults to None (or the Account's address), but that can be updated via a system instruction.

**Comment by rob-solana** [comment]
CC @garious @aeyakovenko @mvines @CriesofCarrots

**Comment by CriesofCarrots** [comment]
If we like this direction, I would love to bump it up into v0.19.0, as I've got some downstream stuff chomping at the bit.

**Comment by CriesofCarrots** [comment]
Hi, @rob-solana . I think this might generate more conversation as a [design proposal](https://github.com/solana-labs/solana/blob/master/CONTRIBUTING.md#design-proposals). Are you willing?

**Comment by rob-solana** [comment]
it's a little sad that such a thing would be true, but yes.  I'm willing.  stay tuned ;)

**Comment by rob-solana** [comment]
authority experiment I conducted revealed that rekeying via authority is a problem for programs, not for the runtime
