### ISSUE TITLE
Split repo into multiple crates

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#590]
The dependencies between client and server are substantially different. Splitting them into separate crates would likely improve link times and reduce executable sizes. Here's a first go at how a directory reorg might look:

* solana-services
   * fullnode
   * fullnode-config
   * mint
   * genesis
   * drone
* solana-clients
   * wallet
   * client-demo
* solana-messages
   * request
   * transaction
   * nodeinfo

**Comment by mvines** [comment]
Lots of progress here recently.  `src/` still needs some more work though

**Comment by garious** [comment]
Did the executable sizes end up changing much?

**Comment by mvines** [comment]
Not sure, I didn't pay attention :)

**Comment by garious** [comment]
This is basically done.  @mvines Feel free to create a new ticket with specifics about the remaining work in `src/`
