### ISSUE TITLE
Fix native program loading when `solana-runtime` is a git or crates.io dependency

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#5966]
#### Problem
The native loader runtime looks for dynamic libraries with a specific filename like this: `libsolana_bpf_loader_program.dylib` and has been working fine when the runtime dependency is a relative path but breaks in other scenarios. Cargo seems to add an extra hash suffix to dependency filenames when pulling in dependencies from git and crates.io

#### Proposed Solution
Handle hash suffixed dynamic library file names like this: `libsolana_bpf_loader_program-dad324483fd13565.dylib`

**Comment by mvines** [comment]
> Cargo seems to add an extra hash suffix to dependency filenames when pulling in dependencies from git and crates.io

What's an example of where/when this happens in practice?   This almost feels like a "you're holding it wrong" kind of problem -- eg, stop using a native program, use BPF instead.

**Comment by jstarry** [comment]
@mvines it happens when testing bpf programs with the solana runtime in a different project. For example, this line was breaking because solana-runtime is a git dependency: https://github.com/solana-labs/solana-voib-demo/pull/10/files#diff-b8c3f81279869c0ce939d0328874bca3R218

Seeing the hash in `solana-voib-demo/target/deps`:
![image](https://user-images.githubusercontent.com/1076145/65271172-51a33980-dab8-11e9-9eeb-c9bcbd8bc052.png)

But not in `solana/programs/bpf/target/deps`:
![image (1)](https://user-images.githubusercontent.com/1076145/65271259-82836e80-dab8-11e9-8656-a2fd5a4f8ae3.png)

**Comment by mvines** [comment]
It's not a problem if it's a crates.io dependency though right?

**Comment by jstarry** [comment]
Just double checked and it is still a problem when using crates.io
<img width="996" alt="Screenshot 2019-09-19 09 09 50" src="https://user-images.githubusercontent.com/1076145/65273629-4f8fa980-dabd-11e9-9cca-bffb09117b65.png">

**Comment by mvines** [comment]
Ah, I see.  From cargo’s perspective there could be many versions of that crate in the build.  We’re asking it to do something it’s not equipped for.   We really want to `cargo install` those native program shared objects into a known location, but not sure we can get there without hacks because `cargo installs only works for bins.

**Comment by jstarry** [comment]
@mvines I'm using this hacky workaround for now here: https://github.com/solana-labs/solana-voib-demo/pull/10/files#diff-5e76fee89c5d06973f4f702bc6b21a65R27. We definitely want something better for developers who wish to test their programs using the runtime in the future though.

**Comment by mvines** [comment]
For this kind of local testing we could statically link the native programs into the runtime, there's really no need for the dynamic loading at all

**Comment by jstarry** [comment]
@mvines good point, I was running into issues with that approach but have a fix here: https://github.com/solana-labs/solana/pull/5992

**Comment by mvines** [comment]
@jstarry - think we can call this issue resolved with #5992?

**Comment by jstarry** [comment]
Sounds good to me. Closing because there's a better approach unblocked by #5992

**Comment by jstarry** [comment]
Re-opening to avoid this hacky workaround: https://github.com/solana-labs/solana/pull/6383

**Comment by jackcmay** [comment]
Looks like the consistent messaging from the Rust folks is explicit dynamic linking of direct dependencies is not expected, encouraged, nor supported.  Instead the recommendation is to treat these dependencies like any other FFI dependency and pull them in as separate projects (using build scripts for example).  We can still keep the programs as direct dependencies for cases where we statically link them (treated as libs by runtime) but I didn't find any viable workarounds to address the file name hash while keeping the dynamically linked programs as direct dependencies.

If we treat the dynamically linked programs as external dependencies I see two options:
- Pull the programs in as submodules.  This would mean for example that TDS add a submodule for any programs that exist as stand-alone git repo and/or adding the Solana repo as a submodule for programs that live there
- Use build.rs to clone, build, and install programs into a known location (similar result as the first option)

Not super excited about either of these but they would address this issue.  If we went down this path we might also want to split the programs living in Solana out to their own (or a single) repo.
