### ISSUE TITLE
SDK Instruction constructor implicitly uses bincode serializer

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#5970]
#### Problem
There is an implicit bincode serialization in the Instruction constructor which is not desirable for creating BPF program instructions because they can't use bincode.
```rust
use bincode::serialize;

impl Instruction {
    pub fn new<T: Serialize>(program_id: Pubkey, data: &T, accounts: Vec<AccountMeta>) -> Self {
        let data = serialize(data).unwrap();
        Self {
            program_id,
            data,
            accounts,
        }
    }
}
```

#### Proposed Solution
Probably just rename `Instruction::new` to indicate that only native program instructions should be created with this method.

**Comment by jackcmay** [comment]
bincode is usable by BPF programs but it bloats the binary and is computationally expensive.  BPF programs may use this to create instructions in the future so the real solution is to settle on a suitable serialization solution.  That solution might be some kind of wrapper that hides actual serialization implementation from the user while keeping it in sync with the consumer.
