### ISSUE TITLE
Rust BPF: Use numbered custom error codes instead of GenericError

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#5971]
#### Problem
The BPF loader still returns GenericError when it runs into issues trying to run BPF programs. These errors are opaque and difficult to debug.

#### Proposed Solution
Use numbered custom error codes instead. This may require creating a new error type since the BPF loader needs to avoid conflicts with the BPF program custom errors it bubbles up

**Comment by jackcmay** [comment]
Fixed in https://github.com/solana-labs/solana/pull/8284
