### ISSUE TITLE
Fix BPF program testing when statically linking BPF loader

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#5991]
#### Problem
Native programs can be statically linked in tests by calling `bank.add_instruction_processor(..)` but this approach is not working for testing BPF programs. Even after adding the BPF loader as an instruction processor, BPF program instructions pass through the message processor to the native loader. This is because `MessageProcessor` tries to match the BPF program id instead of the BPF loader id in its `instruction_processors`.

#### Proposed Solution
When the native loader is invoked, it pulls the native library name from the native program account data. We can match that library name against a new "named instruction processor" in order to intercept BPF program instructions before they try to load a native library.

**Comment by garious** [comment]
Did this make it into 0.19? Should it?

**Comment by jstarry** [comment]
@garious just cherry picked it https://github.com/solana-labs/solana/pull/6049

**Comment by garious** [comment]
Ok, cool. I just updated the milestone.
