### ISSUE TITLE
Serializiation of StatusCache in Snapshotting is Slow

### ISSUE THREAD

**Issue by carllin** [solana-labs/solana#6001]
#### Proposed Solution
Offload to SnapshotPackager thread

**Comment by mvines** [comment]
From Discord, while you're in here please change https://github.com/solana-labs/solana/blob/eeda7338ccc65036c2cad71db615910546255fa6/core/src/snapshot_package.rs#L113-L116 to only use a single file (say new_state.tar.bz2).

When the validator is killed and restarted it leaves temp files around: https://pastebin.com/4HAUnsrM

A temp filename here is unnecessary as we tar sequentially
