### ISSUE TITLE
Testnet falls over with Blockhash not updating, TPS goes to 0

### ISSUE THREAD

**Issue by carllin** [solana-labs/solana#6002]
#### Problem
Testnet will occasionally see "Blockhash not updating" errors from the client, implying lack of consensus. No errors pop up in any of our existing dashboards

1) In the good runs, the TPS often goes from 40k to 9, b/c we run out of funding, and getting it up and running again is as simple as killing bench-tps and wait for it to auto-restart. Example:

https://metrics.solana.com:3000/d/testnet-edge/testnet-monitor-edge?orgId=2&from=1569490981688&to=1569491247598&panelId=44&var-datasource=Solana%20Metrics%20(read-only)&var-testnet=testnet-dev-carl&var-hostid=6MFbraZnjwkrEsXX1VDQfokhVX2UaiDxS2dUJX3fsPAd 

2) Bad run: the TPS goes from 40k to 0, vs the 9 we get in a good run. Example: https://metrics.solana.com:3000/d/testnet-edge/testnet-monitor-edge?orgId=2&from=1569485146101&to=1569485832271&var-datasource=Solana%20Metrics%20(read-only)&var-testnet=testnet-dev-carl&var-hostid=6MFbraZnjwkrEsXX1VDQfokhVX2UaiDxS2dUJX3fsPAd

Configuration I was running: 
1) Tip of v0.19 (01c98c5e537e52b693d463a39b21590cd78feb1e)
2) A 4 node testnet with GPUs with a client running 80k tps

I was logging on the different validators the following to correlate for each bank N:
1) When each validator froze bank N
2) When the leader finished broadcasting the last tick for bank N

From what I see in the logs, as soon as the transactions start, the drift grows exponentially. For instance, on some of the validators I was seeing slots being frozen 0-400, and then a sudden jump to slot 480+ being frozen, where all the slots in between were never frozen.

A red flag is that seeing nodes making the same repair requests for like minutes before moving on. The logs look something like 
`INFO  solana_metrics::metrics] datapoint: repair_service repair_request="Blob(405, 405)" to="10.138.0.54:8001" 
from="0.0.0.0:8219"`

#### Proposed Solution
Root cause.

**Comment by mvines** [comment]
Any hints on how I can reproduce?

**Comment by carllin** [comment]
@mvines, I was running the following commands: 

1) `net/gce.sh create -p testnet-dev-carl -c 1 -n 3 -z us-west1-a -d pd-ssd -G "--machine-type n1-standard-16 --accelerator count=2,type=nvidia-tesla-v100`

2) `net/net.sh restart -f "cuda" -o noValidatorSanity -c "bench-tps=1=--tx_count 80000 --thread-batch-sleep-ms 1000`

**Comment by danpaul000** [comment]
@carllin any update here?  This is reliably reproducible on the colo node setup.

Here is a recent reproduction from the colo cluster:
https://metrics.solana.com:3000/d/testnet-edge/testnet-monitor-edge?orgId=2&var-datasource=Solana%20Metrics%20(read-only)&var-testnet=colo-edge-perf-gpu-enabled&var-hostid=All&from=1570717578000&to=1570718045226

Logs for all nodes are here under "Artifacts":
https://buildkite.com/solana-labs/testnet-nightly-performance/builds/66#1fc4fece-5169-4ba5-9ba8-510d9c050ad5

**Comment by mvines** [comment]
Stale
