### ISSUE TITLE
Design proposal process is awkward

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#6019]
#### Problem

Per @rob-solana, the design proposal process is awkward enough that using plain old GitHub Issues is in some ways more appealing.  The biggest problem is the "Implemented" state.  It could mean "Some variation of an accepted proposal was implemented and here's a historical record of what was proposed" or "This is what was implemented and check the git log if you're curious as to how that relates to what was proposed".  Also, once the implemented proposal is integrated into the main part of the book, should the proposal be deleted or stick around as a historical record? Also, we don't document what to do when a proposal is partially implemented at the time of a software release. Do we break the proposal into two or leave it out of the "implemented" state?

#### Proposed Solution

Needs discussion.

**Comment by garious** [comment]
So first change I think we can make, let's drop the requirement for a historical record. Use git history if you really want that.  Instead, if the implemented proposal is integrated into the book, let's just delete the design proposal.  With that change, the process is a nice funnel, that starts with a queue of PRs, then a queue of accepted proposals that need implementing, then a queue of implemented proposals that need integrating into the book. Thoughts? @rob-solana @aeyakovenko

**Comment by aeyakovenko** [comment]
So something like this?
1. Design proposal 
2. Partial implementation 
3. Create an implemented design chapter
4. Delete old design proposal
5. Create a new design for the next phase of the implementation

**Comment by garious** [comment]
@aeyakovenko, I like the iterative nature of what you have there, but no, that's not what I'm suggesting. Currently, design proposals linger in the "implemented" state even though the implementation has changed or its content has already been integrated into the book. We keep them around for historical context.  Instead, I propose we update those documents until they're integrated into the book, and then delete them.  So the whole process would be:

1. PR a design proposal to the "Accepted" section of the book.  Purpose: discussion.
2. Merge the design. Purpose: indicates we grok it and want to implement it.
3. Implement the proposal.
4. Implement to PR updates the design and move to "Implemented". Purpose: for implementor communicate changes to design.
5. Merge the PR. Purpose: to inform the community that the design is implemented.
6. Integrate into book. Purpose: Knowledge Base continuity.
7. Delete the proposal. Purpose: Don't want to maintain 2 copies.
