### ISSUE TITLE
TdS Compensation: Compute rewards earned for each validator

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#6077]
Related to: https://github.com/solana-labs/solana/issues/6076

#### Problem
The TdS Compensation tool needs to find the top rewards earners in the TdS ledger

#### Proposed Solution
Rewards should be calculated as the sum of all vote and stake account balances attributed to a particular validator pubkey minus the initial allotment of tokens at the beginning of stage. In order to calculate this sum, the `ledger-tool` will need to be updated to read ending account balances and state.

Note that validator account balances will **not** be counted, only vote and stake balances will be considered.

In general, stakers are expected to redeem their credits as they are earned so it should be reasonable to rely on that behavior to compute rewards in this way.

**Comment by jstarry** [comment]
@rob-solana could you please review my proposed solution? 

- Is it accurate to say that only rewards earned in the last completed epoch will be counted?
- Is it fair to expect stakers to redeem their own credits in order to have their rewards counted?

**Comment by rob-solana** [comment]
> @rob-solana could you please review my proposed solution?
> 
> * Is it accurate to say that only rewards earned in the last completed epoch will be counted?

it is correct that rewards earned in epoch X cannot be collected/counted until epoch X+1

> * Is it fair to expect stakers to redeem their own credits in order to have their rewards counted?

I think so.  Who else would pay the TX fee?

**Comment by jstarry** [comment]
@mvines It's looking like reward computation will have to be tied a bit closer to the runtime than maybe we'd prefer. Main issue is that validators can debit their accounts and withdraw rewards at will so snapshotting account balances at slot boundaries can be gamed.

Commissions and rewards need to be calculated before and after a `StakeInstruction::RedeemVoteCredits` is processed. This has to be done at the instruction processor level to avoid pulling in account balance updates in the transaction.

Transaction fees are pretty trivial, just need to hook in before and after `bank.freeze()` in `blocktree_processor.rs` to see what the fees were.

The only other tricky part is tracking who owns the staking accounts. My assumption is that validators will earn all the stake rewards from the stake accounts initially funded by their validator account, no matter how the stake account was funded afterwards. This means, I will also have to tie into `SystemInstruction::CreateAccount` to track stake account ownership. Does that sound acceptable? 

By the way, airdrops will be disabled on TdS right?

**Comment by rob-solana** [comment]
@jstarry we dictate the terms of the TdS, so we can set up TdS genesis with zero commission, and set the stakes to have infinite lockup.  in this mode, all earned rewards end up in stakes.  We can also turn on credit re-investment, so earned rewards would be end stake - genesis lamports.

**Comment by jstarry** [comment]
@rob-solana oh interesting, didn't consider changing the rules, that could definitely help for tracking staking rewards.

> so we can set up TdS genesis with zero commission

I didn't see a config for commission, looks like commission is chosen by the user when setting up their vote account. Are you suggesting that we hardcode the commission to a default if it's set in the genesis?

> We can also turn on credit re-investment

Nice, I think we would still need to differentiate rewards from friendly donations from other validators, maybe stake state could be directly updated when earning rewards?

That leaves tracking down ownership of staking accounts as the trickiest part I think.

**Comment by rob-solana** [comment]
> @rob-solana oh interesting, didn't consider changing the rules, that could definitely help for tracking staking rewards.
> 
> > so we can set up TdS genesis with zero commission
> 
> I didn't see a config for commission, looks like commission is chosen by the user when setting up their vote account. Are you suggesting that we hardcode the commission to a default if it's set in the genesis?

yeah, just populate all the vote accounts with commission = 0

> 
> > We can also turn on credit re-investment
> 
> Nice, I think we would still need to differentiate rewards from friendly donations from other validators, maybe stake state could be directly updated when earning rewards?

yes, exactly what I meant my "re-investment", Stake::stake is upped the same amount as Account::lamports when rewards are redeemed

> 
> That leaves tracking down ownership of staking accounts as the trickiest part I think.

I thought we had enough information about TdS participants to do that.  My understanding is that TdS is basically a static set of validators and stakes that are all provisioned at genesis.  If this isn't the case, then there's a bit more work to do.

**Comment by mvines** [comment]
There’s a bit more work to do.  We give everybody a system account at genesis, and they create their vote/staking accounts themselves

**Comment by rob-solana** [comment]
ok, makes good sense to do it that way.

we could just name the top stake and vote accounts and ask participants to prove ownership for the prizes

**Comment by mvines** [comment]
We know all the validator identity pub keys, and from there at any time we can find the associated vote account (if multiple, use the vote account that voted most recently) and all stake accounts associated with the validator's vote account.

At the end of the stage, we could just sum the tokens in the vote+state accounts for each validator no?    Any tokens transferred out of those accounts is not counted, as is the number of tokens remaining in your validator's identity account.

**Comment by jstarry** [comment]
> and all stake accounts associated with the validator's vote account.

What happens if a validator delegates stake to another validator's vote account? Does that other validator get the rewards?

I guess that's fine, we're not preventing validators from pooling their funds into a common stake account

**Comment by mvines** [comment]
> What happens if a validator delegates stake to another validator's vote account? Does that other validator get the rewards?

Yep.  You just gave me some cash, thanks so much.  I'm like 👋 💨

**Comment by jstarry** [comment]
> At the end of the stage, we could just sum the tokens in the vote+state accounts for each validator no?

Doesn't prevent validators from pooling funds into a stake account at the end of the round.

> and all stake accounts associated with the validator's vote account.

Note that stake accounts can be re-delegated to a different vote account at any time. We will only be considering the last set vote account for a stake account when computing the rewards

**Comment by rob-solana** [comment]
> > At the end of the stage, we could just sum the tokens in the vote+state accounts for each validator no?
> 
> Doesn't prevent validators from pooling funds into a stake account at the end of the round.
> 
> > and all stake accounts associated with the validator's vote account.
> 
> Note that stake accounts can be re-delegated to a different vote account at any time. We will only be considering the last set vote account for a stake account when computing the rewards

Do we need to couple the rewards when awarding prizes, could we have winning vote accounts and winning stake accounts, and those could belong to different people...  What's cool about that is we might find some network-preferred commission rate...

**Comment by jstarry** [comment]
> What's cool about that is we might find some network-preferred commission rate...

I thought we were disabling commission 😜 

> Do we need to couple the rewards when awarding prizes? We could have winning vote accounts and winning stake accounts, and those could belong to different people?

I don't think we need to, I think @mvines was suggesting it as a way to simplify the rewards calculation. I think it does go against the incentives a normal testnet to calculate in this way but the main theme of Stage 1 is performance so maybe that's ok?

Also, I think that all accounts should be deterministically tied back to a validator pubkey to avoid any potential issues with claiming ownership

**Comment by rob-solana** [comment]
> Also, I think that all accounts should be deterministically tied back to a validator pubkey to avoid any potential issues with claiming ownership

help me understand this last point.  are you proposing we comb the ledger to show the custody chain of lamports from the initial node pubkey?  how would doing so be better than a proof of ownership of the winning stake and vote pubkeys?

**Comment by jstarry** [comment]
> are you proposing we comb the ledger to show the custody chain of lamports from the initial node pubkey?

I'm proposing tracking which stake accounts are created from our list of TdS validator pubkeys.

> how would doing so be better than a proof of ownership of the winning stake and vote pubkeys?

I'm probably just being paranoid, but I was worried about the case where the private key of the winning stake account was shared between validators. How would we choose who won?

Also, I thought it would be nice to avoid the extra roundtrip of verifying ownership, just have a script that outputs the prizes for each validator

**Comment by mvines** [comment]
> I'm proposing tracking which stake accounts are created from our list of TdS validator pubkeys.

IDK, this seems unnecessary.   What's wrong with using the vote/stake accounts that are associated with each validator identity at the end of the stage?   If one validator transfers all their stake to another validator, the other validator wins (but that's the same for mainnet)

**Comment by rob-solana** [comment]
> > how would doing so be better than a proof of ownership of the winning stake and vote pubkeys?
> 
> I'm probably just being paranoid, but I was worried about the case where the private key of the winning stake account was shared between validators. How would we choose who won?

My thinking was: the winner is the vote account with the highest balance, and the winner presents proof that he owns that vote account (this implies a non-zero VoteState::commission).

> Also, I thought it would be nice to avoid the extra roundtrip of verifying ownership, just have a script that outputs the prizes for each validator

because we have human-readable names for them, I guess?

**Comment by mvines** [comment]
>  the winner is the vote account with the highest balance

vote + stake accounts?

**Comment by jstarry** [comment]
> What's wrong with using the vote/stake accounts that are associated with each validator identity at the end of the stage? If one validator transfers all their stake to another validator, the other validator wins (but that's the same for mainnet)

Sorry, mistakenly backtracked with my suggestion, this approach sounds good!
