### ISSUE TITLE
TdS Compensation: Compute availability for each validator

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#6080]
Related to: #6076

#### Problem
The TdS Compensation tool needs to track the number of missed slots for each validator in the TdS ledger

#### Proposed Solution
For voting availability, retrieve the credit total from validator vote account states and compare with total number of slots in the final ledger. For leader availability, process the blocktree and find skipped banks. Use the epoch's leader schedule to determine which leaders correspond to the skipped banks (missed slots).

**Comment by mvines** [comment]
> For voting availability, retrieve the credit total from validator vote account states and compare with total number of slots in the final ledger

Important: total number of *blocks*, not *slots*.   There will be slots that produce no block when a leader is MIA.

> (missed slots)

missed *blocks*

This approach sounds good to me though!
