### ISSUE TITLE
Testnet manager is broken on v0.19

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#6090]
#### Problem

testnet-manager.sh fails on v0.19 with:
```
++net/net.sh update -t v0.19.0 '--platform linux' '--platform osx' '--platform windows'
Error: Unknown long option: --platform linux
```
#### Proposed Solution
Figure out where those quotes got introduced and clear them out.

**Comment by mvines** [comment]
Looks like it's due to my attempt to be fancy here: https://github.com/solana-labs/solana/blob/03dc4a20a19da565024193f1323f2bb0259ceaa3/ci/testnet-manager.sh#L399
