### ISSUE TITLE
net.sh always runs the CUDA validator implementation if the host has a GPU installed

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#6100]
#### Problem

`net.sh` always runs the CUDA validator implementation if the host has a GPU installed. On the colo nodes, this is always.

#### Proposed Solution

Extend the following logic to respect the `-g/-G` flags to `colo.sh`
https://github.com/solana-labs/solana/blob/093b5b52674f8ef5cb9d725ff3d95ff249c5d59d/net/remote/remote-node.sh#L116-L119

**Comment by danpaul000** [comment]
@t-nelson we're going to need to be able to run some non-CUDA-enabled tests on the colo nodes in short order to flush out some stability issues.

**Comment by t-nelson** [comment]
If you're cool with more hacks, this works...
```
diff --git a/net/remote/remote-node.sh b/net/remote/remote-node.sh
index bf33f6f2..9e25a9ca 100755
--- a/net/remote/remote-node.sh
+++ b/net/remote/remote-node.sh
@@ -113,10 +113,10 @@ cat >> ~/solana/on-reboot <<EOF
   scripts/net-stats.sh  > net-stats.log 2>&1 &
   echo \$! > net-stats.pid
 
-  if [[ -e /dev/nvidia0 ]]; then
-    echo Selecting solana-validator-cuda
-    export SOLANA_CUDA=1
-  fi
+  #if [[ -e /dev/nvidia0 ]]; then
+  #  echo Selecting solana-validator-cuda
+  #  export SOLANA_CUDA=1
+  #fi
 EOF
 
   case $nodeType in
```

I'll up prio here though

**Comment by danpaul000** [comment]
Nah, I don't want to hack this.  I want to ability to set a flag within the automation framework to specify, so we can test the unmodified edge code.

**Comment by t-nelson** [comment]
Sure.  I was just saying that hack works until the fix is ready
