### ISSUE TITLE
Recent book content overwritten

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#6112]
#### Problem

Gitbook changes on v0.19 whacked recent changes to the content: https://github.com/solana-labs/solana/commits/v0.19/book/src/introduction.md.   Specifically, you can see this change to introduction.md was overwritten: https://github.com/solana-labs/solana/commit/b31d334ef4d62a7008b38dbef326754f68953312#diff-8162f2c55d2db62ce1dc7d13d8bef013.

#### Proposed Solution

Diff master to see what all was overwritten and add it to the v0.19 branch.

**Comment by mvines** [comment]
@ryan-shea - could you please take a look at this issue, any idea how the overwrite might have happened?   Thanks!

**Comment by ryan-shea** [comment]
@garious https://github.com/solana-labs/solana/pull/6147 and https://github.com/solana-labs/solana/pull/6148 were merged to fix. let me know if there are any other changes
