### ISSUE TITLE
No Date program

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#6113]
#### Problem

Programs may want to change state in response to a trusted source of wallclock time. We can have a "cluster time" but the program may not trust it. For example, the proposed Vest program aims to implement a paper contract. The company that signed the paper contract may prefer to sign off on monthly updates to wallclock time. 

#### Proposed Solution

Add a program `Date` that only allows owners of the account public key to update the account data, which must include a serialized and valid DateTime object. The default time can be the Unix epoch (`chrono::Utc.timestamp(0, 0)`).

cc: @rob-solana @aeyakovenko

**Comment by rob-solana** [comment]
this is an interesting approach, could we Config instances instead?

**Comment by garious** [comment]
I can try. Hard to tell though - that program has no unit tests.

**Comment by rob-solana** [comment]
config_tests?

**Comment by garious** [comment]
Yep, thanks @rob-solana, looks like Config will work.  Took me a while to reverse engineer that library though.  A similar library without `keys` would be easier to grok.

**Comment by rob-solana** [comment]
did you have a look at how stake_api/src/config.rs uses it?

**Comment by garious** [comment]
yep
