### ISSUE TITLE
Set up nightly testnet performance tests

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#6122]
#### Problem

We have no way to know how a big distributed cluster is going to perform until it's nearly release time and someone (me) is supposed to run the TPS tests and (generally) run into some (really) painful bugs.

#### Proposed Solution

Establish and run an automated nightly testnet cluster.  `ci/testnet-automation.sh` can handle most of this with some tweaks and just add a schedule to the `solana-testnet` pipeline.

Create a source-controlled test configuration file, rather than just editing default environment variables in buildkite.  The *.yml files imported into buildkite from the repo might work.

Append to some database/log structure the timestamped results of all cases as they are run over multiple days, weeks, months, etc.

Test parameters/iterations:
1.  With and without GPUs (or can we just re-run the same GPU cluster with gpus turned off/deallocated.  Will require a little tweak in GCE CLI and remote-node.sh)
2.  Tip of beta branch and tip of edge branch
3.  Number of nodes: 10, 25, 50, 100 (consider a smaller set, 25 & 50?)
4.  Fixed regional deployments.  Currently we use us-west, us-central and europe-west4 because that's where we have V100 quota.
5.  Define what instance type/sizes we are using

Extra credit:
1.  Variable regional deployment
2.  Variable cloud deployment
3.  Non-V100 GPUs (lower end GPUs would enable wider geographic distribution of cloud nodes)

**Comment by danpaul000** [comment]
@mvines what happened to https://github.com/solana-labs/solana/issues/1168 ? Looks like you were after the exact same thing this time last year!

**Comment by mvines** [comment]
It rotted away I think :-/
