### ISSUE TITLE
Test for slashing conditions

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#6125]
#### Problem

We don't have 1) any slashing conditions or 2) a way to test them.

#### Depends on
Design:  #2731 
Implementation:  https://app.asana.com/0/1139331099162253/1139350174790836

#### Proposed Solution

Once implemented, we need some hooks to actually trigger the various offending behaviors, and some monitors to verify that the stake is reduced by the appropriate amount.

**Comment by jon-chuang** [comment]
I'm interested in writing tests for slashing.
