### ISSUE TITLE
Solana CLI - get_epoch

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#6159]
#### Problem
We have solana get-slot but here I am with solana show-stake-account output saying that "stake activates starting from epoch: 10" but I don't know what epoch we're in

#### Proposed Solution
Write a quick `solana get-epoch` command

**Comment by mvines** [comment]
![image](https://user-images.githubusercontent.com/1281082/65803506-9f144c00-e133-11e9-9023-ef92bdb1b88c.png)

**Comment by mvines** [comment]
Done, it's called `solana get-epoch-info`
