### ISSUE TITLE
Running bench-tps against the TdS cluster (all clusters?) is flaky

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#6163]
STR:
1. Run `https://github.com/solana-labs/tour-de-sol/blob/master/bench-tps.sh`

There's a couple issues here:
1. The funding phase often doesn't complete 
2. If it does complete, transactions stop after a minute or so.

**Comment by CriesofCarrots** [comment]
3. If transactions continue beyond a minute, they start triggering InsufficientFunds errors after ~7min

**Comment by CriesofCarrots** [comment]
@mvines , @sagar-solana , I haven't been able to repro the funding stall. Anything you know of to make it more likely to occur?

**Comment by sagar-solana** [comment]
How are you trying to repro it right now?

**Comment by CriesofCarrots** [comment]
> How are you trying to repro it right now?

Running bench-tps on a separate GCE or Azure cloud instance against testnet-dev-tyera, which currently only has 2 nodes. I've mostly been using the args in `https://github.com/solana-labs/tour-de-sol/blob/master/bench-tps.sh`, as per the issue, but with various tx_counts between 10 and 50,000.

**Comment by sagar-solana** [comment]
Okay and you're not using the client accounts yaml right? I was just making sure it was actually funding instead of picking up primordial accounts. It's odd that it's working fast. It basically never does for me. :(
I was running a client from my laptop.

**Comment by mvines** [comment]
Looks much improved for me.   I turned on the TdS cluster to test.  Item 2 is definitely resolved for me.  With large values for `--tx_count`, like `--tx_count=10000`, the later stages of funding will tend to sit there with no console update for many seconds/minutes.   During this time it's unclear if it's still working.   How about adding a log message every couple seconds that updates the funding status?

eg:
```
creating from... 1
transferring 360759016 to 4 in 1 txs
transferred
funded: 4 left: 21840
creating from... 4
transferring 90173160 to 16 in 4 txs
transferred
funded: 16 left: 21824
creating from... 16
transferring 22526696 to 64 in 16 txs
transferred
funded: 64 left: 21760
creating from... 64
transferring 5615080 to 256 in 64 txs
transferred
funded: 256 left: 21504
creating from... 256
transferring 1387176 to 1024 in 256 txs
transferred
funded: 1024 left: 20480
creating from... 1024
transferring 330200 to 4096 in 1024 txs
transferred
funded: 4096 left: 16384
creating from... 4096
transferring 65956 to 16384 in 4096 txs
```
very long pause with no console update or visible transactions in Grafana.  Maybe it's working but ????

**Comment by CriesofCarrots** [comment]
Yeah, I think it's set up to repeat the `transferring 65956 to 16384 in 4096 txs` message after a while, but I find that more confusing than helpful. (Did they all fail, or what?)

> How about adding a log message every couple seconds that updates the funding status?

Sounds good.
I'm also going to put in some optional logging to see how fast the funding batches are being built/confirmed, so that maybe we can get more information about what's going on for @sagar-solana

**Comment by CriesofCarrots** [comment]
Regarding Item 3 I added, setting the `num-lamports-per-account` allows control over how long bench-tps will run for before encountering InsufficientFunds errors. Default is 65536

**Comment by mvines** [comment]
Much less flaky now, if this problem persists we can open a new targetted issue
