### ISSUE TITLE
gce.sh assumes any custom machine size contains a GPU

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#6169]
#### Problem

`net/gce.sh` allows user to override the default machine type with `-G` with whatever you want, but this historically was only used for GPU machines.  We may have desire to run high-CPU instances (or other custom machine types) without the need for a GPU.

`gce.sh` calls `nvidia-smi` on GPU-enabled nodes in the startup script.  This will throw an error at least in the startup log and might cause the instance to not show as completely booted from our status scripts.

#### Proposed Solution

Broaden the ability to specify GPU and non-GPU custom machine types and only call `nvidia-smi` where appropriate.

**Comment by t-nelson** [comment]
Dupe #6100?

**Comment by danpaul000** [comment]
Not a duplicate.  When we specify that we want a GPU-enabled google instance, we can pass all sorts of `machine-type` or `custom-cpu` long args that specify what specs the VM should have.  If we want a non-GPU machine, there is no support so specify any kind of machine type other than the hard coded default.  It would be nice to be able to say "I want a 32 core machine with 64GB mem with no GPU", but this fails due to the nvidia-smi check currently .

**Comment by danpaul000** [comment]
Sorry fixed typo.  This request is about the `gce.sh` instance creator script, not the related `net.sh` instance launcher issue.

**Comment by danpaul000** [comment]
I'd like to get this in sooner than later (I can take it up just as well) so we can explicitly name gce machine type for non-GPU nightly runs.
