### ISSUE TITLE
rent: creating accounts may exhaust SSDs

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#6198]
#### Problem

Creating accounts may exhaust SSDs before those accounts need to pay rent.

#### Proposed Solution

Charge rent early enough that it would be prohibitively expensive. Or consider adding space limits per epoch to the protocol.

**Comment by ParthDesai** [comment]
After  #6947 we are deducting rent, before storing newly created account. 
So, closing this issue in favour of #6413
