### ISSUE TITLE
Unit-test suite is slow

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#6238]
#### Problem

`cargo test --lib` execution time is slowing development. That subset of tests should execute very quickly (ideally just a few seconds), such that one can use `cargo watch -x test`. 

```
test bank_forks::tests::test_slots_to_snapshot ... test bank_forks::tests::test_slots_to_snapshot has been running for over 60 seconds
...
[2019-10-04T16:13:22.411679000Z INFO  solana_metrics::metrics] datapoint: vote-native count=1i
[2019-10-04T16:13:22.413110000Z INFO  solana_metrics::metrics] datapoint: vote-native count=1i
```

#### Proposed Solution

Move all long-running tests to the integration test suite.

**Comment by garious** [comment]
Takes over 3 minutes on my laptop. Am I doing something wrong?

**Comment by garious** [comment]
Looks like all the slowest ones come from just 2 modules, `storage_stage` and `bank_forks` snapshot testing:

```
test storage_stage::tests::test_signature_distribution ... ok
test bank_forks::tests::test_concurrent_snapshot_packaging ... ok
test bank_forks::tests::test_bank_forks_status_cache_snapshot_n ... ok
test storage_stage::tests::test_storage_stage_process_account_proofs ... ok
test bank_forks::tests::test_slots_to_snapshot ... test bank_forks::tests::test_slots_to_snapshot has been running for over 60 seconds
test storage_stage::tests::test_storage_stage_process_banks ... ok
test bank_forks::tests::test_slots_to_snapshot ... ok
```

@carllin, @sakridge, know anything about these? What are they doing in the unit-test suite?

**Comment by sakridge** [comment]
They can be moved. I think we just didn't really have a generic integration test crate. `local_cluster` is close, but it sounds specific to local_cluster tests.

**Comment by garious** [comment]
@sakridge, you guys can put anything into the `tests` directory of any crate. By being in tests, they won't run when using `cargo test --lib`, which is exactly what I'm looking for. When I develop, I use `cargo watch -x 'test --lib'`, so these long-running integration tests inside the unit-test suite is quite painful.

**Comment by sakridge** [comment]
ok; good to know, I can move them there
