### ISSUE TITLE
Tighten github commit process.

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#6289]
We should consider tightening down the commit process in codebase, particularly after the external security audit.
Are we introducing vulnerabilities with loose code additions?
Use signed commits?

**Comment by mvines** [comment]
Generating signed commits from the github API is pretty brutal (cc: @solana-grimes).

**Comment by sakridge** [comment]
How about for external dependencies?

**Comment by danpaul000** [comment]
> How about for external dependencies?

Tracking in https://github.com/solana-labs/solana/issues/6398

**Comment by abebeos** [comment]
@danpaul000 , issue seems closable, similar to https://github.com/solana-labs/solana/issues/6398

Having them open within an unspecified  future milestone makes a negative impression.
