### ISSUE TITLE
Encrypt solana CLI private keys on disk

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#6290]
Private keys are unencrypted.  All keys should be encrypted on disk.  cc: @t-nelson

**Comment by danpaul000** [comment]
https://github.com/solana-labs/solana/pull/6259

**Comment by t-nelson** [comment]
#6259 is in now.  It's really only valuable for offline-ish accounts, though.

Ideally we'll have built-in (en|de)cryption for our tools.  The ergonomics for multi-key use cases will need to be further considered

**Comment by mvines** [comment]
Why are we working on issues with no milestone?

**Comment by danpaul000** [comment]
@t-nelson can this be closed now that #6259 is in?  Should the "further consideration" you are referring to be expounded here, or create new issues as this unfolds?

**Comment by t-nelson** [comment]
@mvines I've got some toy code into and out of the following file formats. Any concerns so far?
```
{
  "version": 0,
  "encryption": {
    "type": "aes256Cbc",
    "kdf": {
      "type": "pbkdf2",
      "salt": "5UX8wRnXweVb2UxhyJS2yk",
      "rounds": 7500
    }
  },
  "keypairs": [
    {
      "type": "aes256Cbc",
      "pubkey": "AeqJWq5d5nRbbMyXHaAL2CYEEK2fNGPUSvsUmnu8SBgj",
      "iv": "PysFD9DTCzTCiCg12B8QPB",
      "ciphertext": "3aRyNk1i8r7ztezxtQnN5DcrArTRHEKJ6VQU4dxYs3FDGDCMvD5NQfn4KrDJoKsFaD4UctxMJ72V1jqTkoWnr1yHybh55ojZ86JDbPFo2KDW91CQ8z5goB7QiJYxFZ5Dteg7TVpsbKMuoSr3RNX9BTQRsq2LmJnFkWE9MjzAgFm4vdQN3HTbXRwZ5y9fdTERqLvwR"
    }
  ]
}
```
```
{
  "version": 0,
  "encryption": {
    "type": "plaintext"
  },
  "keypairs": [
    {
      "type": "plaintext",
      "keypair": "2o85q8TQbrtCzZDHY5kKC1FyaEKKFZA9n12uxsnah6Wzq1uApV3d8JZV4sdB856yByUgMWHKjZmE5wFE3Ni7x2FF"
    }
  ]
}

**Comment by mvines** [comment]
Looks good so far.  For `"type": "plaintext",` seems like the "pubkey" field could still be present for consistency and convenience.

**Comment by t-nelson** [comment]
Sg. I've been waffling on a more generic keypair metadata field anyway.  Thanks for taking a look!
