### ISSUE TITLE
Teach our validators how to protect themselves

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#6291]
- Make sure we tell our highly staked people how to protect their nodes
- Only advise people to open smallest set of ports as needed
- DOS attacks on validator nodes.  Can halt the network by blasting the open ports on a network node.
- Leader can get slammed with RPC queries

**Comment by t-nelson** [comment]
Smallest set of ports seems to be TCP(8001, 8899, 8900), UDP(8000-10000)

**Comment by everstake** [comment]
We found a bunch of similar issues here:

https://github.com/solana-labs/solana/issues/8862 - rate limiting
https://github.com/solana-labs/solana/issues/6862 - load balance
https://github.com/solana-labs/solana/issues/5778 - RPC is unauthenticated
https://github.com/solana-labs/solana/issues/8862 - limit egress traffic for trusted validators

Nginx is a great and versatile tool. We propose using it to solve these issues and gain more control and observability over API connections. Here is simple [Nginx config](https://gist.github.com/everstake/b0621e6e1db778c0efaac0df1291e6e4) that suits our needs:



```
#Nginx config used for api.solana-tds.everstake.one

# Extensive log format used with Nginx Amplify, handy for analysis
log_format  main_ext  '$remote_addr - $remote_user [$time_local] "$request" '
					  '$status $body_bytes_sent "$http_referer" '
					  '"$http_user_agent" "$http_x_forwarded_for" '
					  '"$host" sn="$server_name" '
					  'rt=$request_time '
					  'ua="$upstream_addr" us="$upstream_status" '
					  'ut="$upstream_response_time" ul="$upstream_response_length" '
					  'cs=$upstream_cache_status' ;

# Load balancing, fault tolerance
upstream solana-proxy {
	server 127.0.0.1:8899 weight=3 max_conns=1000 max_fails=1000 fail_timeout=360s;
	# server solana_node1 .....
	# server solana_node2 .....
	# server solana_node3 .....
}

server {
	listen 80;
	server_name api.solana-tds.everstake.one;

	# HTTPS protocol, secure connection from client to server
	#listen 443;
	#ssl_certificate /etc/nginx/certs/solana_api.crt;
	#ssl_certificate_key /etc/nginx/certs/solana_api.key;


	# Enable logging, set log format
	access_log /var/log/nginx/access.log main_ext;
	error_log /var/log/nginx/error.log warn;

	# Disable favicon and robots error messages
	location ~ ^/(favicon.ico|robots.txt) {
		log_not_found off;
	}

	# Simple self-monitoring - connection statistics
	location = /status {
		stub_status;
		access_log off;
		allow 127.0.0.0/24;
		deny all;
	}


	# Allowed requests we want to forward to upstream
	location  ~ ^/ {
		
		# Tune timeouts for proxy
		proxy_buffering off;
		proxy_connect_timeout  360s;
		proxy_send_timeout     360s;
		proxy_read_timeout     700s;

		proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
		proxy_next_upstream_timeout 200s;
		proxy_next_upstream_tries 5;
	
		# Configure basic authentification
		auth_basic "SOLANA RPC API";
		auth_basic_user_file /etc/nginx/.htpasswd;

		# IP's restriction
		#allow x.x.x.x/32;
		#allow y.y.y.y/32;
		#deny all;

		proxy_pass http://solana-proxy;
	}


	# Forbidden requests
	location ~ ^/(errors|network|workers) {
		return 403;
	}

	# Forbiddent IP's
	location ~ ^/forbidden {
		allow 127.0.0.0/24;
		#allow x.x.x.x/32;
		#allow y.y.y.y/32;
		deny all;
	}
}
```

**Comment by mvines** [comment]
@everstake - does Nginx support websockets?   RPC+1 (8900) is a websocket port

**Comment by leoluk** [comment]
That config contains a lot of unnecessary boilerplate. nginx does support websockets, but it needs to be configured properly.

**Comment by mvines** [comment]
I've been using haproxy and liking it

**Comment by brianlong** [comment]
We use HAproxy in high-volume environments and we like it too.

**Comment by everstake** [comment]
> That config contains a lot of unnecessary boilerplate. nginx does support websockets, but it needs to be configured properly.

Websockets:
https://www.nginx.com/blog/websocket-nginx/

It's not "silver bullet" config - just an example of how to solve some issues and we will improve it

**Comment by everstake** [comment]
> We use HAproxy in high-volume environments and we like it too.

Good choice

**Comment by everstake** [comment]
> @everstake - does Nginx support websockets? RPC+1 (8900) is a websocket port

Websockets:
https://www.nginx.com/blog/websocket-nginx/

For config:

location  ~ ^/ {
......
    proxy_pass http://solana-proxy;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
.......

**Comment by AlexandrNesyshi** [comment]
1 удалите антивирус
2 удалите обновления брендмаузера - отключите его ) 
3  защитите соединение wifi на githib  аудит сети - проведите ее.
4 насладитесь жизнью

**Comment by huglester** [comment]
Can sobody here share HAPROXY config then?
