### ISSUE TITLE
Can't pass the same account into multiple `keyed_accounts`.

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#6308]
#### Problem

Can't pass the same account into multiple `keyed_accounts`. As a result, programs' instruction constructors are forced to check for duplicate keys.

#### Proposed Solution

Define `KeyedAccount` with `Rc<Account>` instead of `&mut Account`.

**Comment by garious** [comment]
`Cell`, not `Rc`, might be the right tool for the job.  Maybe `RefCell`, but hoping not to push borrow-checking to the runtime.

**Comment by garious** [comment]
`load_accounts()` creates `Vec<Account>` and would be changed to return `Vec<Cell<Account>>`.  Then the subset created in `MessageProcessor` would be a `Vec<&Cell<Account>>`, and then that's what would be referenced by `KeyedAccount` instead of the `&mut Account`.

**Comment by jackcmay** [comment]
@garious Do you envision these changes also propagating up to the program level where a `RefCell` is passed to the program via KeyedAccount?

**Comment by garious** [comment]
Yes, exactly. It's the only Mutex-free mechanism I'm aware of that would allow multiple references to the same account and doesn't include `unsafe` annotations.
