### ISSUE TITLE
Make sure we are using NVMe accounts drives on Colo nodes

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#6331]
#### Problem

We aren't (afaict) taking advantage of the idle NVMe SSDs on the colo GPU nodes.

#### Proposed Solution

Add to the /net or /multinode-demo scripts the logic to check for NVMe presence, make sure it's formatted and mounted correctly, and use this drive (or drives) for accounts I/O.

**Comment by danpaul000** [comment]
cc: @t-nelson

**Comment by t-nelson** [comment]
Should this be an "always" thing or follow `--fullnode-additional-disk-size-gb` (but warn that the size parameter will be ignored) ?

**Comment by danpaul000** [comment]
Should have similar logic to fullnode-additional-disk-size-gb, except that
param is for config dir, which gets large so we wanted an oversized SSD.
For accounts dir, we need fast I/O, hence NVMe.  I wrote some code to
enable this on GCE a while ago, I'll find it and extend it to colo.  And it
should probably always be done as long as the hardware is sitting in the
machine.
