### ISSUE TITLE
colo.sh create does not clean up after itself if bs leader is not created

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#6334]
#### Problem

Looks like `colo.sh create` still creates the client nodes if the bootstrap leader fails to be allocated, then doesn't deallocate client nodes after the bs leader failure.

To reproduce: Allocate all available colo nodes except a non-GPU node, then do a creation of a different testnet name and only the client will get allocated.

**Comment by t-nelson** [comment]
This is the same behavior as `net/gce.sh` will exhibit.  I was considering adding a `trap` at the top of `create` to run `delete` on failure, but wasn't sure if I should gate it to `net/colo.sh` or leave it global.  Maybe just follow `--allow-boot-failures`?  What do you think?

**Comment by danpaul000** [comment]
Okay, I wasn't sure if GCE had this issue or not, as we rarely if ever have seen a BS leader fail allocation, whereas in colo I think this will happen a lot with our small fixed pool of resources

**Comment by t-nelson** [comment]
Any opinions on the feature gating options?
