### ISSUE TITLE
No runtime check to ensure transaction fee-payer is a debitable account

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#6339]
#### Problem
Currently, all credit-debit checks happen inside message_processor::process_message. However, transaction fees get charged upstream in accounts::load_tx_accounts. This means that if a credit-only account is the first signer, it gets successfully charged the fee if it can afford it, potentially adding non-determinism to the chain. 🙀 

#### Proposed Solution
Update runtime to reject transactions pre-fee if the fee payer is not locked as credit-debit

**Comment by garious** [comment]
Can we reject the transaction before any accounts are loaded? Otherwise you can DoS the leader by having it load a bunch of huge accounts without having to pay anything.  Before SigVerify or any `deserialize()` would be ideal.

**Comment by CriesofCarrots** [comment]
> Can we reject the transaction before any accounts are loaded? Otherwise you can DoS the leader by having it load a bunch of huge accounts without having to pay anything. Before SigVerify or any `deserialize()` would be ideal.

Yes, definitely. I am inclined to build off https://github.com/solana-labs/solana/pull/6236, actually, and put this check in `do_get_packet_offsets`
