### ISSUE TITLE
Rewards sysvar uses float types

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#6347]
#### Problem

Float types are unpredictable across hardware architectures and therefore my be non-deterministic across validators when used within a program (smart contract)

#### Proposed Solution

Two possible solutions:
- Convert the rewards sysvar values to fixed point math
- Add support for a deterministic soft floating-point library

**Comment by jackcmay** [comment]
@rob-solana Any concerns about using fixed point math for rewards?

**Comment by rob-solana** [comment]
the concern I'd have is that we're not operating in an easily defined space (like pixels on a screen), so it's not obvious what precision to choose for the fixed-point numbers...

I'd prefer an FP library to a fixed-point sysvar.

**Comment by jackcmay** [comment]
A FP library in BPF is not something we are going to be able to put in short term.  Maybe we move this issue out?

**Comment by mvines** [comment]
No objections moving out from me if we’re keeping the FP and just adding a library for on-chain support some time later

**Comment by jackcmay** [comment]
When will folks need to use rewards from programs?

**Comment by mvines** [comment]
Add support for a deterministic soft floating-point library seems like the path, moving this issue out for now
