### ISSUE TITLE
Potentially insecure native programs available to SLP1

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#6370]
#### Problem

Potentially insecure native programs available to SLP1

#### Proposed Changes

Chop out anything nonessential, such as Budget, which is part of the CLI, but likely unused.

**Comment by garious** [comment]
@mvines, @rob-solana, do you have the list of required programs?

@CriesofCarrots, fyi

**Comment by mvines** [comment]
This is basically a subset of #5757

**Comment by rob-solana** [comment]
vote and stake are, AFAIK, the only required programs for SLP1
