### ISSUE TITLE
solana-cli insists on a keypair when it's not strictly required

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#6375]
#### Problem
```
$ rm /Users/mvines/.config/solana/id.json
$ solana show-validators
Error: KeypairFileNotFound("Generate a new keypair with `solana-keygen new`")
```
😡 

But the `show-validators` subcommand does not require a keypair, it's just making simple JSON RPC requests.  Numerous other subcommands are like this (`get-slot` and `get-epoch-info` to name a few)

#### Proposed Solution
Refactor the solana-cli implementation to require a keypair only when truly needed.

**Comment by CriesofCarrots** [comment]
As an example (and a place that will need to be made consistent with the solution to this issue), the `address` subcommand already does this: https://github.com/solana-labs/solana/blob/1afc527919200cccdf0487d6077c59202d202044/cli/src/cli.rs#L729
