### ISSUE TITLE
Ensure validator/replicator cannot collude

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#6391]
Build out test cases to try to game the PoRep verification system.

Could a replicator and validator be the same person and submit/verify proofs to one another and gain rewards without actually doing any work?

**Comment by jon-chuang** [comment]
Hi, I am interested in writing a test to see if this can be done. However, it doesn't seem like there is anything wrong with a validator being a replicator too. 

The only problem is ensuring duplication, I think filecoin has a way of handling this.

**Comment by ryoqun** [comment]
I think we can close this for now. (let's reduce open issues!)
