### ISSUE TITLE
SystemInstruction::CreateAccount() could exhaust RAM

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#6413]
#### Problem
The user can request the system create an account of size 0xFFFFFFFFFFFFFFFF, which'll probably OOM the validator:
https://github.com/solana-labs/solana/blob/ba46bc4624e694d3692e1c4b6be3021beef91e9c/sdk/src/system_instruction.rs#L39

#### Proposed Solution
Reduce space to a u32 perhaps and/or add a size check before https://github.com/solana-labs/solana/blob/ba46bc4624e694d3692e1c4b6be3021beef91e9c/runtime/src/system_instruction_processor.rs#L64

**Comment by garious** [comment]
Pay rent upfront?

**Comment by t-nelson** [comment]
Is this the same issue as #6198 ?

**Comment by mvines** [comment]
Potentially, if we can convince ourselves that there's no way for somebody to hit `vec![0; space as usize];` with `space` that's big enough to OOM the process

**Comment by t-nelson** [comment]
It seems like we'll need a bound at any rate.  Paying rent up front still makes the network pay-to-DoS, which may not be economical, but may be an affordable destructive attack
