### ISSUE TITLE
sha2 implementation is slower than could be

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#6463]
#### Problem

sha2 is implementation slower than it could be
Believe we are using this one: https://github.com/RustCrypto/hashes

#### Proposed Solution

Use sha2.rnds2 hardware instruction for processors that support it (ryzen/threadripper) and test openssl or intel performance primitives implementations to see what is best for skylake/cascade lake.

**Comment by aeyakovenko** [comment]
@sakridge difference is 11m vs 2m hashes, so roughly 5x?

**Comment by sakridge** [comment]
> @sakridge difference is 11m vs 2m hashes, so roughly 5x?

@aeyakovenko About 11m vs. 4m. So about 2.8x

**Comment by sakridge** [comment]
Fixed by https://github.com/solana-labs/solana/pull/14746
