### ISSUE TITLE
`blocktree::db::IteratorDirection` is not used meaningfully

### ISSUE THREAD

**Issue by TristanDebrunner** [solana-labs/solana#6489]
#### Problem

Only the `IteratorDirection::Forward` variant is ever used.

#### Proposed Solution

Remove it.

**Comment by garious** [comment]
I changed the code to just use Rocks' `Direction`.  I'm not finding this enum to be very problematic.

**Comment by CriesofCarrots** [comment]
We also use IteratorDirection::Reverse now
