### ISSUE TITLE
Generate PoH as fast as possible

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#6519]
Our current PoH generation is believed to be much slower than what the CPU can actually do, exposing various possible attacks.   We need to ensure we're hashing as fast as possible.

cc: https://github.com/sakridge/asm-hashes
cc: https://github.com/sakridge/hashes

**Comment by garious** [comment]
Any news here?

**Comment by sakridge** [comment]
The sha2 fork will probably not merge my PR, they don't like binary blobs in general https://github.com/RustCrypto/asm-hashes/pull/9

There is a pure Rust PR using rust intrinsics but it's ~30% slower for Poh generation and it probably won't be merged for a while: https://github.com/RustCrypto/hashes/pull/90

@mvines wanted to vendor the relevant code, that's a bit of work though. Need to find time to do it..

**Comment by ryoqun** [comment]
@sakridge They recently merged a PR supporting the AArch64 counterparts of sha256 CPU extension support: https://github.com/RustCrypto/asm-hashes/pull/10. Maybe we could rewrite our PR in asm from intrinsics and use that PR as a precedent to get merged. :)

**Comment by sakridge** [comment]
> @sakridge They recently merged a PR supporting the AArch64 counterparts of sha256 CPU extension support: [RustCrypto/asm-hashes#10](https://github.com/RustCrypto/asm-hashes/pull/10). Maybe we could rewrite our PR in asm from intrinsics and use that PR as a precedent to get merged. :)

Yea. I see. Weird that they don't mind assembly but don't like the intrinsics version.

**Comment by jon-chuang** [comment]
Will validators using multicore CPUs be utilising optimised assembly too?

**Comment by sakridge** [comment]
Fixed by https://github.com/solana-labs/solana/pull/14746
