### ISSUE TITLE
Congestion design docs are not clear.

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#6543]
#### Problem

2.  "the validator doesn't have hardware that can process that many transactions that fast, its confirmation votes will eventually get so long that the cluster will be forced to boot it."

Cluster has no way to "boot" a validator that is behind.  

[edits]
@mvines clarified the rest

#### Proposed Solution

Clarify the docs.

tag: @garious @mvines

**Comment by mvines** [comment]
https://github.com/solana-labs/solana/blob/90461245f9db9b43721cc98058d592c6d2e37ae1/sdk/src/fee_calculator.rs#L65-L71
