### ISSUE TITLE
Replace `daddr` checks with `ip().is_unspecified()`

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#656]
Rust added a function to IpAddr to check if its unspecified.  The code should call that method instead of comparing against `0.0.0.0:0`.

**Comment by martiuslim** [comment]
Would love to give this a shot! Would just like to clarify if the below snippets are heading in the right direction for this issue?

- `else if v.contact_info.tvu == daddr` to `else if v.contact_info.tvu.is_unspecified()`
- `.filter(|r| r.id != self.me && r.contact_info.tvu_window != daddr)` to `.filter(|r| r.id != self.me && !(r.contact_info.tvu_window.is_unspecified()))`

**Comment by aeyakovenko** [comment]
Yes!  

I would define a function ‘is_valid_address’ which checks that the port is nonzero, and address is not unspecified or multicast

**Comment by martiuslim** [comment]
Ah I see. May I kindly check where would be the best place to define this function?

**Comment by aeyakovenko** [comment]
Inside the Crdt class, so it can be called context free ‘Crdt::is_valid_address’

**Comment by martiuslim** [comment]
looks like this can be closed, ref: #721
