### ISSUE TITLE
Retransmit recovered shreds through turbine

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#6594]
#### Problem
A shred that is recovered through erasure codes, is not retransmitted through turbine. If the shred was originally sent to the node from slot leader (and it got dropped), likely the whole cluster is missing it. This can lead to repairs that could be avoided if the node retransmitted the shred thru turbine.

#### Proposed Solution
When a node recovers a data shred, it should check if the shred was sent to it from the leader. If so, it should retransmit the shred thru turbine.

**Comment by jon-chuang** [comment]
I am interested in this. Can start in 6 weeks.

**Comment by behzadnouri** [comment]
Closed by https://github.com/solana-labs/solana/pull/19233
