### ISSUE TITLE
Move Local Cluster Bench Tps test is flaky

### ISSUE THREAD

**Issue by sagar-solana** [solana-labs/solana#6618]
#### Problem

https://github.com/solana-labs/solana/pull/6616 ignored the flaky test

#### Proposed Solution

Figure out why it's flaky. Its likely that the newer Move is too slow. 
Bumping the test's timeout to 60 from 25 seems to help.

**Comment by sakridge** [comment]
> Bumping the test's timeout to 60 from 25 seems to help.

The test looks at overall transactions processed during the time, let's make sure we aren't just waiting longer and counting vote transactions as passing the test.

**Comment by TristanDebrunner** [comment]
> > Bumping the test's timeout to 60 from 25 seems to help.
> 
> The test looks at overall transactions processed during the time, let's make sure we aren't just waiting longer and counting vote transactions as passing the test.

Took a look and dumped the ledger. Slots very consistently contain 1 vote tx, so for the 25s sample time, we see 62-63 vote txs. This means that with the test failing, we are getting <2 tps of move txs. It also means that any sample length under 40s should only pass if at least one move tx gets processed, and bumping the sample length to 30s seems to make this stable in CI. I'm not sure what the speed problem is here, so we could just bump up to 30s, and leave the speed issue for later.

**Comment by TristanDebrunner** [comment]
Fixed by #6993
