### ISSUE TITLE
Replace credit-only account support with read-only account support

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#6655]
Credit-only accounts have proven to be harder to implement correctly than anticipated, and are not strictly required for initial launch.  In the interest of reducing scope, we only need RO (read-only) account for use by sysvar accounts and can add CO back later if demand for this feature exists.  

The AccountMeta bools should be turned into a bitfield (u8 or u16) as RO accounts are added and CO account support removed, so we can restore CO accounts later without breaking the transaction wire format:
https://github.com/solana-labs/solana/blob/b4119c454ae5413e27dbf5f15ba0add3d66828e9/sdk/src/instruction.rs#L118-L120

Depending on when this issue is resolved, we may want to backport the AccountMeta changes to the 0.20 branch for the sake of downstream users like solana-web3.js

**Comment by CriesofCarrots** [comment]
@mvines , my plan is to implement this in 2 steps:
1. First, transition from credit-debit/credit-only accounts to mutable/immutable accounts -- primarily a runtime change -- using the same MessageHeader strategy as currently implemented.
2. Second, transition from MessageHeader to per-account bitfields -- primarily a transaction wire format change.

This will give us a little longer to weigh the transaction wire size implications against the flexibility and backward compatibility benefits, without blocking @jackcmay.

**Comment by mvines** [comment]
Sound great, (2) could be split out to another issue even.  We don't strictly need this right now, just seems nice for the future and it'll only get more painful to do this later
