### ISSUE TITLE
bench-tps slow signature generation causes need for multiple clients

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#6657]
#### Problem

A validator can verify signatures faster than bench-tps can generate them. It uses the GPU for verification, whereas bench-tps uses the CPU to generate signatures. Consequently, one runs bench-tps clients from multiple nodes to flood a single validator for performance testing.

#### Proposed Solution

Use the new GPU-based `sign_many` if available. With that enabled, you should only need one bench-tps client. Depending on the GPUs available, it might even work on the same machine as the validator, allowing the developer to bypass any network bandwidth limitations.

cc: @sakridge

**Comment by ryoqun** [comment]
fyi: @garious [My draft PR](https://github.com/solana-labs/solana/pull/6575) is remotely related to this in that the bottleneck at the bench-tps side.
