### ISSUE TITLE
`cargo-install-all.sh` always builds move 

### ISSUE THREAD

**Issue by TristanDebrunner** [solana-labs/solana#6661]
#### Problem

`cargo-install-all.sh` builds move even when called in situations where it isn't wanted.

#### Proposed Solution

Add a `--use-move` flag that enables the build. Also pipe that option through `net/net.sh`. Have `sdk/docker-solana/build.sh` and `ci/publish-tarball.sh` call that option by default.

**Comment by TristanDebrunner** [comment]
@mvines should `sdk/docker-solana/build.sh` indeed build with move by default?

**Comment by mvines** [comment]
> @mvines should `sdk/docker-solana/build.sh` indeed build with move by default?

Yes please
