### ISSUE TITLE
Add validator log/ledger upload tool

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#6676]
At the end of a TdS dry run/stage, viewing logs and ledgers from different participants can be helpful in debugging the outcome.  Currently there's no easy mechanism to get that information back to us.   There could exist write-only storage somewhere with a tool in the release that validators just need to run once to submit their logs/ledger

**Comment by mvines** [comment]
This is a nice to have but I think we have hobble along without it for a while longer.

**Comment by ryoqun** [comment]
Recently, @sakridge mentioned that there is a cli tool to upload logs: https://github.com/gdrive-org/gdrive

Maybe, could we write a one-liner with that?

**Comment by mvines** [comment]
Sure, this might just be a simple thing we can add to the documentation
