### ISSUE TITLE
RPC calls that operate on a certain bank should return the bank slot to the caller

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#6679]
With #6538, we'll be able to include a confidence for RPC methods like confirmTransaction, getBalance, getAccountInfo so the user can choose their own risk.  Additionally some users want to know the exact block that the response was provided on for their account purposes: 
Q: "What's the current maximum  confirmed account balance of XYZ?"
A: "123, at block N".
The user wants to know what `N` is.

One possibility is to extend the response of the affected RPC methods to include the Bank slot that the response was generated on.

**Comment by sunnygleason** [comment]
see #6716
