### ISSUE TITLE
Emit new root event from blocksteam socket

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#6682]
While the blockstream socket provides information about all entries/blocks that a node is observing/producing there is no confidence data provided.  We have a use-case now where a user wants to ingest the blockstream but only take action on blocks that have achieved max lockout.

Currently such a user would need to continually poll [getBlockConfidence](https://docs.solana.com/book/api-reference/jsonrpc-api#getblockconfidence) for the confidence information about all blocks received over blockstream until they hit max lockout, which will be a performance drag and also very awkward.

Instead the blockstream socket could itself emit a "new root" message upon the creation of each new root.   With this "new root" message, the user would be able to easily discard all blockstream blocks that never become rooted

**Comment by sunnygleason** [comment]
nice! this is an awesome idea -- as block confidence grows, it's much more efficient to update the confidences this way rather than polling/requesting on demand
