### ISSUE TITLE
CrdsValues need to be signed, not just the data they contain

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#6694]
#### Problem

CrdsValue's need to be signed, not just the data they contain.  Attacker could change the enum type of the CrdsValue potentially rerouting or corrupting a nodes ContactInfo.

#### Proposed Solution

Signature should be wrapping CrdsValue.

tag: @sagar-solana

**Comment by sagar-solana** [comment]
@aeyakovenko I'm going to restructure crdsvalue to look like this 
```
/// CrdsValue that is replicated across the cluster
pub struct CrdsValue {
    pub signature: Signature,
    pub data: CrdsData,
}
```
Data will be the enum we use today and we'll just sign the whole enum. sg?
