### ISSUE TITLE
tds cluster running 0.20.2 died with "Unexpected Blocktree Errors"

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#6731]
![image](https://user-images.githubusercontent.com/1281082/68179461-32b81400-ff4d-11e9-92dd-6707d2cb7172.png)

**Comment by mvines** [comment]
Grafana snapshot: https://metrics.solana.com:3000/dashboard/snapshot/eUKLDxD1tYI22zcJMIfJJNgO7Yo4k0P7?orgId=2

**Comment by mvines** [comment]
All nodes on the cluster but the `ChorusM5BVgnAKbg9PF15285LkqeCoZWK2p9s35T7J2A` node reported these errors

**Comment by carllin** [comment]
hehe wonder if the ChorusM5BVgnAKbg9PF15285LkqeCoZWK2p9s35T7J2A was the leader during that slot. It's also strange...that error shouldn't cause the cluster to die. At worst validators should mark that slot as dead and another leader should proposed a new fork...

**Comment by mvines** [comment]
Update: the cluster didn't die due to this afterall.  These messages appear to be a symptom of the Chorus node restarting from a clean snapshot.  ie, not a bug
