### ISSUE TITLE
Figure --hashes-per-tick,--slots-per-epoch value for SLP1

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#6767]
The default `--slots-per-epoch` in `solana-genesis` is too short, we've discussed a epoch duration of 1 week informally.  Let's lock this value down, and potentially make this the default in `solana-genesis` when the `--dev` flag is not provided.

The `--hashes-per-tick` value to use must also be figured

**Comment by sakridge** [comment]
hashes-per-tick

| Hardware | bench_poh_hash |
| -- | -- |
| n1-standard gcp | 2.366m |
| AMD Threadripper 1900x (no sha inst) | 4.24m |
| xeon 2620 v4 | 1.97m |

Easy answer is 2m/s hash rate and 2 week epoch length.
