### ISSUE TITLE
Bank block height is confusingly zero-indexed

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#6779]
#### Problem
Bank block height starts at 0 for the first block after genesis. This is unintuitive.

#### Proposed Solution
Use one based indexing for determining bank block height

**Comment by rob-solana** [comment]
only if you're a lua programmer ? ;)

**Comment by garious** [comment]
I think the confusion here comes from the fact that the blockchain has a height, not its blocks.

**Comment by jstarry** [comment]
Looks like what we currently have implemented is consistent with this definition: https://bitcoin.org/en/glossary/block-height

So maybe it's fine as is, unless @garious do you have another suggestion?

**Comment by garious** [comment]
Discussing on Discord. Let's define the genesis block first.

**Comment by garious** [comment]
I think the only thing wrong was that the word "zero" needed to be "one" in the block height definition. If the genesis block is indeed a block, then the first block after it is height one.  So if we process the GenesisBlock (which really ought to be called GenesisState or GenesisSnapshot) and freeze that bank, the next one would have height one.  If we don't freeze that bank, we'd start processing transactions at height zero.
