### ISSUE TITLE
Clean up naming related to genesis config and genesis block

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#6795]
#### Problem
After https://github.com/solana-labs/solana/pull/6782 our code does not match our stated terminology in the book. 

#### Proposed Solution
GenesisBlock struct should be renamed to GenesisConfig and the first bank/slot/block should be referred to as the genesis bank/slot/block

**Comment by jstarry** [comment]
won't fix - easier to update terminology

**Comment by mvines** [comment]
I think we fixed this, if not please re-open with details
