### ISSUE TITLE
Repair metrics are causing lost datapoints

### ISSUE THREAD

**Issue by sagar-solana** [solana-labs/solana#6830]
#### Problem

The repair datapoints in `repair_service` and `cluster_info::map_repair_request` are far too frequent with the more aggressive repair.

We plot a repair-request's slot and index. I don't think we should rate limit this. The other log in repair_service logs which peer the repair is being sent to but that isn't plotted anywhere. 
Disabling either one isn't enough either.

#### Proposed Solution

@mvines what should we do about this?

**Comment by mvines** [comment]
We can bump the priority of those datapoints and cause other lower priority datapoints to be dropped instead

**Comment by sagar-solana** [comment]
Isn't the ratelimit the same across different priority levels. If these repair metrics are too much by themselves, won't they ratelimit any priority we put them on?
