### ISSUE TITLE
Use reusable identity keypairs for colo nodes

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#6855]
#### Problem

Create some reusable keypairs for the colo nodes so they can be more easily identified in the validator identity pubkey list.  

#### Proposed Solution

https://github.com/solana-labs/solana/pull/6783/files
```
# Fetch reusable testnet keypairs
if [[ ! -d net/keypairs ]]; then
  git clone git@github.com:solana-labs/testnet-keypairs.git net/keypairs
fi
```

**Comment by danpaul000** [comment]
@mvines do you have a script/loop written you used to generate the `val*`, etc prefixes for the pubkeys?

**Comment by mvines** [comment]
```
$ solana-install init edge
$ solana-keygen grind --ignore-case --starts-with danpau1
```
You can give multiple `--starts-with` arguments.  I've not had any luck with grinding out `danpau1` yet myself, or `mvines`

**Comment by danpaul000** [comment]
Sweet, nice feature, thanks!

**Comment by CriesofCarrots** [comment]
>  I've not had any luck with grinding out `danpau1` yet myself, or `mvines`

Amazingly, I've found 2 that start with tyera, but one of them starts with `tyerawefar`, which is weird...
