### ISSUE TITLE
Accounts implicitly created by a Transfer cannot be resized

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#6863]
#### Problem
Once an account is implicitly created by getting tokens from a `Transfer`, it can no longer be "created" in `CreateAccount` because we fail the transaction if the account is already in use (lamports > 0).

#### Proposed Solution
* Remove the conditions that created accounts must have 0 lamports / empty data
* Additional CreateAccount lamports get added to the current account balance, and the account data is simply resized

tag @rob-solana

**Comment by mvines** [comment]
The problem as described here our deliberate design.   What's the actual problem?

**Comment by jstarry** [comment]
Would it be better stated as:

If someone transfers tokens to an account I own the private key for, it shouldn't prevent me from having full control over that account. Full control includes assigning ownership and allocating data. Right now I cannot allocate data in this situation, but I'm still allowed to assign ownership.

Another solution would be to add a "AllocateData" instruction which will allocate data if it is currently empty

**Comment by mvines** [comment]
Ah, I see.   So something is trying to DoS you by sending you money?  The attack looks like:
1) I observe your new public key somehow (maybe I sniff the network for Solana transactions that fly by)
2) Before you CreateAccount transaction can execute, I successfully submit a Transfer transaction that *gives you lamports* and prevents CreateAccount from executing
3) Now I need to generate a new keypair and run CreateAccount again.  But now I have a system account with lamports in it (from you, thanks!) that I can use to finance that second CreateAccount so it doesn't cost me a thing.

**Comment by jstarry** [comment]
Haha, yes, the friendly DoS'er. It still costs you transaction fees

**Comment by mvines** [comment]
No it shouldn't cost you more transaction fees though .  You have full control over the system account that was used to DoS you the first time, so the second time just use the "DoSed account" to fund the transaction.

**Comment by jstarry** [comment]
> No it shouldn't cost you more transaction fees though . You have full control over the system account that was used to DoS you the first time, so the second time just use the "DoSed account" to fund the transaction.

You would pay the transaction fees for the first failed CreateAccount because it would still execute. Unless you're assuming the "DoSed account" would have more lamports than the fees you just lost.

Here's a contrived example:
1. You enter a public key into a poorly designed lottery program
2. You win! Ok create an account for that public key and give it some data so we can mark that you claimed it. Only after you do that can claim your winnings
3. Oops someone transfered lamports to your winning public key
4. Can't claim my winnings

**Comment by ParthDesai** [comment]
@mvines I think overall problem I see is, our system should have systemwide base rules regarding privilege of different actors. For example, if I have private key for the account, I should be able to do whatever I please, unless owner program is preventing this somehow. 

This would make system more consistent in the behaviour, and we can eliminate whole class of this kind of inconsistent behaviour.

**Comment by mvines** [comment]
> Unless you're assuming the "DoSed account" would have more lamports than the fees you just lost.

I was assuming that, but we'd need something like #6864 to ensure this is the case.

There's nothing stopping me from emptying the account.  I can transfer the lamports you DoSed me with to another account so the account is deallocated *and in the same transaction*  run CreateAccount again.  The attacker can't prevent this.

The lottery program from https://github.com/solana-labs/solana/issues/6863#issuecomment-552518656 just sounds broken though.  The lottery program would most likely record the winner's pubkey in an existing lottery program account, and then the winner issues a transaction with the their keypair to transfer.   

What was the actual issue you ran into that spawned this issue though?  Maybe that's something concrete we can discuss

**Comment by jstarry** [comment]
> What was the actual issue you ran into that spawned this issue though? Maybe that's something concrete we can discuss

No specific instance, just occurred to me while fixing up the `to` signer stuff. Not many changes needed made me realize that we were implicitly creating a lot of accounts using airdrops.

> The attacker can't prevent this.

I think they can prevent it by front-running with another transfer.

> There's nothing stopping me from emptying the account. I can transfer the lamports you DoSed me with to another account so the account is deallocated and in the same transaction run CreateAccount again. 

Since this is the case, why don't we bake this into `CreateAccount`? Why give the user the additional burden of draining the account first?

If we take a step back, we do enforce that a balance is empty in `CreateAccount`?

**Comment by ParthDesai** [comment]
@jstarry We are enforcing it, because otherwise a system account with lamports can be assigned to any arbitrary program, and funds can be stolen.

More details here: https://github.com/solana-labs/solana/issues/6449

**Comment by jstarry** [comment]
> @jstarry We are enforcing it, because otherwise a system account with lamports can be assigned to any arbitrary program, and funds can be stolen.
> 
> More details here: #6449

I thought we fixed that by making `to` signed

**Comment by ParthDesai** [comment]
@jstarry hmm. You are right. I do not see any technical reason to keep lamports > 0 check anymore (though other checks introduced in same patch need to stay.)

But on semantic side, I think `to` account referenced by CreateAccount should be blank. It's just weird design, where we are allowing user to overwrite existing account in `CreateAccount` instruction. 

What would be better design, if we have something like `resize` instruction, that allows owner to change data contained in the account (only if owner is system account)

**Comment by mvines** [comment]
Supporting `CreateAccount` into an existing system account regardless of current lamports or data seems fine now that we sign `to`.   In that case the additional `CreateAccount` lamports get added to the current account balance, and the account data is simply resized (no need for clearing back to zero since a system account will always have zero-ed out data).

I think that should solve the potential `Transfer` DoS without introducing another system program instruction.

**Comment by rob-solana** [comment]
current code is a band-aid to prevent CreateAccount being used to steal tokens. CreateAccount should probably go completely away to be separated into its constituent parts (allocate() and assign()), both of which will require the account's signature

**Comment by jstarry** [comment]
This has been resolved by adding the allocate and assign instructions
