### ISSUE TITLE
Accounts with no data to not pay rent

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#6864]
An account with no data still consumes space within the node's account database and yet pays no rent.  Two problems that arise from this are:
1) The system is forced to drag dust accounts around forever (an account with less value in it than the cost of a transaction fee)
2) Somebody can Transfer 1 lamport in a system account that matches your pubkey, effectively preventing you from using CreateAccount to create an account with data at that pubkey.

**Comment by ParthDesai** [comment]
We could implement something like tiered rent: Base rent + Dynamically calculated rent per data byte.
wdyt? @mvines

**Comment by aeyakovenko** [comment]
@rob-solana @ParthDesai it should be just rent per byte, `size_of::<Account>() + account.data.len()`

**Comment by ParthDesai** [comment]
@aeyakovenko hmm. works. `size_of::<Account>()` is constant right? (Due to `repr(c)` attribute)

**Comment by mvines** [comment]
I think we want to detach the literal `size_of::<Account>()` from the base rent upfront.  If we don't then the next time a field is added/removed from Account a hard fork is created.

**Comment by aeyakovenko** [comment]
@ParthDesai good point.  I think your suggestion is the right approach, we should define it in the SDK as the base fee rate.  Account size may change in the future.

**Comment by rob-solana** [comment]
> @ParthDesai good point. I think your suggestion is the right approach, we should define it in the SDK as the base fee rate. Account size may change in the future.

I think it would be fine to just hardcode an ACCOUNT_OVERHEAD that represents a close-enough value for now and forever
