### ISSUE TITLE
The creation of `snapshot.tar.bz2` isn't atomic

### ISSUE THREAD

**Issue by ryoqun** [solana-labs/solana#6881]
#### Problem

`ledger/src/snapshot_utils.rs` creates new `snapshot.tar.bz2` in place. If validator is aborted or another node access to them via RPC when creating, mysterious things could happen from simply failure to malfunction.

This could be more problematic especially as the snapshot size gets bigger and bigger.

#### Proposed Solution

First, write new snapshot into `snapshot.tar.bz2.new` or like, then do atomic syscall `rename`.

**Comment by mvines** [comment]
The rename occurs here:
https://github.com/solana-labs/solana/blob/263641865922d40cae8f8dd338b69cd48f43ccce/core/src/snapshot_packager_service.rs#L118-L120
Do you see a problem with this function?  There is a tiny window where the snapshot may not be present between the remove_file and the rename I guess

**Comment by ryoqun** [comment]
@mvines You're right. I was wrong. It looks that the implementation does (near-)atomic processing correctly.

However, I observed this error and jumped to this conclusion.. I haven't dug in but this can not be caused by the existing short window where the snapshot is missing... Maybe different bug?:

```
[2019-11-11T12:50:39.150796904Z INFO  solana_ledger::bank_forks_utils] Loading snapshot package: "/home/ryoqun/work/solana/solana/for-small-patches/config/ledger/snapshot.tar.bz2"
[2019-11-11T12:50:39.200157953Z INFO  solana_ledger::snapshot_utils] Loading from "/home/ryoqun/work/solana/solana/for-small-patches/config/ledger/snapshot/.tmplU4qyN/snapshots/6400/6400"
thread 'main' panicked at 'Snapshot bank failed to verify', ledger/src/snapshot_utils.rs:226:9
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.37/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1028
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1412
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:189
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:206
  10: solana_metrics::metrics::set_panic_hook::{{closure}}::{{closure}}
  11: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:473
  12: std::panicking::begin_panic
  13: solana_ledger::snapshot_utils::bank_from_archive
  14: solana_ledger::bank_forks_utils::load
  15: solana_core::validator::new_banks_from_blocktree
  16: solana_core::validator::Validator::new
  17: solana_validator::main
...
[2019-11-11T12:50:43.029912207Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="main" one=1i message="panicked at 'Snapshot bank failed to verify', ledger/src/snapshot_utils.rs:226:9" location="ledger/src/snapshot_utils.rs:226:9"
```

**Comment by mvines** [comment]
hmm, not sure.  I've seen validators throw this error before though so digging into it would be great!  You could try adding a sleep between the `remove_file()` and `rename()` to make it easier to trigger the case when there's no snapshot available

**Comment by ryoqun** [comment]
@mvines Hi, I dug in and finally and really found [a real bug](https://github.com/solana-labs/solana/issues/6890), it seems. :smile: 

Also, I think it's prudent to do atomic rename here by just removing `fs::remove_file(&snapshot_package.tar_output_file)`. Is there some concern for doing so, tolerating quasi-atomic rename?

**Comment by mvines** [comment]
> I think it's prudent to do atomic rename ...

Yes, I agree.  Go for it!
