### ISSUE TITLE
Colo - bash5 incompatibilty

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#6963]
#### Problem

Colo uses vertical tabs to separate result fields for SSH scatter/gather.  With `read` on bash5, empty fields are elided.  So something like:
```
read -e A B C <<<$'a\v\vc'
echo "A($A) B($B) C($C)"
```
results in, for bash5
```
A(a) B(c) C()
```
where as on bash <5
```
A(a) B() C($C)
```

#### Proposed Solution

Investigate and fix. Worst case, switch to a less collision-resistant delimiter

h/t: @sagar-solana for riding the bleeding edge!

**Comment by mvines** [comment]
Downgrade to bash4
