### ISSUE TITLE
client-demo: solana::bank: tx error: Err(AccountNotFound(...))

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#697]
STR:
1. Run `./multinode-demo/client.sh master.testnet.solana.com 50`
2. In the leader log, observe a large number of `solana::bank: tx error: Err(AccountNotFound(...))`-like messages.

**Comment by sakridge** [comment]
The client-demo first gets tokens to a single account in the airdrop, then sends those tokens to random accounts. Then it transfers them back to the original account. If any packets are dropped in the first stage, then those accounts will be missing in the second stage.
