### ISSUE TITLE
Validator docs not as clear as they could be

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#6972]
#### Problem

Validator docs not as clear as they could be:
* "Running a Validator" page mentions validator-support Discord, but that's before you've done anything that needs support. I'd expect that link to be at the end, in a "Troubleshooting" section.
* "Running a Validator" page mentions registering public key, but again, that should be at the end, once you've got a validator up and running.
* No mention of "solana-keygen grind" (which is too fun to ignore)
* No Software Requirements page. The mention of Ubuntu 18.04 is on the Hardware Requirements page. Same with installing the GPU software.  If someone is handed validator hardware, they'd likely skip the Hardware Requirements page.
* No ulimit configuration for Ubuntu 18.04.
* All the 0.18.0 versions.
* The "Download Software" section that gives a second, undocumented command, that's meant to be an *alternative*, not a second command to run.
* "Choosing a Testnet" before "Installing Validator Software"
* `solana set --url http://beta.testnet.solana.com:8899` before a bunch of commands that assume the default is `testnet.solana.com:8899` not beta.
* Showing the JSON RPC example, but not its expected output or what that output means.
* The need to run `solana get`. Apparently it has the side-effect of setting the URL?
* No mention of port forwarding 8000-1000 for UDP traffic. Only a mention of how to change those ports.
* Generally, too many alternatives offered - keep it simple.  It's like the document is trying to be both a tutorial and a reference manual. We have "Solana CLI" in the "API Reference" for the details. "define the SOLANA_CUDA flag in your environment before running any of the previously mentioned commands" is particularly obnoxious.
* `--limit-ledger-size` isn't mentioned until after you're already up and running. It could be in the default command.
* In `solana balance --lamports`, why suggest the `--lamports` option?
* "Troubleshooting" page should have links to Discord and the forums

**Comment by mvines** [comment]
We ought to reference this dark magic too: https://github.com/solana-labs/solana/blob/master/scripts/tune-system.sh#L35-L38

**Comment by garious** [comment]
Who's maintaining the validator docs? @CriesofCarrots?

**Comment by CriesofCarrots** [comment]
@ryan-shea and I have been maintaining the TdS docs. Maybe we can jointly pick these up too.

**Comment by ryan-shea** [comment]
@CriesofCarrots let's do it!

**Comment by CriesofCarrots** [comment]
Also addressed by #7187 and #7333
