### ISSUE TITLE
make ledgers rsync-able, readable at arbitrary leader serialization states

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#698]
If a validator reads directly from a leader's ledger file/output or starts from a leader's ledger that was snapshot'd while the leader was appending, the deserialization may fail on the last, partial Entry serialization.

There are choices to be made:
* leaders can advertise snapshots from which validators can safely rsync or read directly
* validators can tolerate failed deserialization, partial tails, and catchup via repair window

It'd be ok if both of the above were employed.

**Comment by sakridge** [comment]
Atomic FS writes maybe something to look at.

**Comment by rob-solana** [comment]
isn't relevant anymore, ledger_recover() covers the case
