### ISSUE TITLE
bank.epoch_stakes grows without bound

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#6991]
#### Problem
the bank never culls epoch stakes

#### Proposed Solution
retain at most N epochs worth of epoch_stakes
```
if leader_schedule_epoch > MAX_LEADER_SCHEDULE_STAKES {
    new.epoch_stakes.remove(leader_schedule_epoch - MAX_LEADER_SCHEDULE_STAKES)
}
```
in bank.new_from_parent()

**Comment by mvines** [comment]
On my TdS test ledger, this reduces the RAM used by `epoch_stakes` hashmap from 30MB to 1.5MB:
```diff
@@ -390,6 +416,9 @@ impl Bank {
             }
         }
 
+        new.epoch_stakes
+            .retain(|&epoch, _| epoch >= leader_schedule_epoch.saturating_sub(5));
+
         // update epoch_stakes cache
         //  if my parent didn't populate for this staker's epoch, we've
         //  crossed a boundary
```
And reduces the total memory used by the unrooted ledger that OOMed TdS nodes previously from 25GB down to 1.5GB.
