### ISSUE TITLE
Add release automation

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#701]
Cargo.toml needs to be updated before tagging. Tags should have a `v` prefix. Post 1.0, tags should follow semantic versioning.

Command-line release automation using [hub](https://hub.github.com/). The wrapper should have `--major`, `--minor`, `--patch` options taking no parameters. The script should read the version in Cargo.toml, and bump the appropriate version number.

**Comment by mvines** [comment]
I'm pretty happy with `RELEASE.md`, a little bit of manual documented steps but nbd.  All the error-prone stuff is now automated
