### ISSUE TITLE
Include genesis hash implicitly in shred signature

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#7012]
While not an issue for mainnet, it's common in testnets for validators to reuse the same keypair across multiple genesis blocks.  Vanity keypairs are one such example, but additionally all TdS participants register just their single validator keypair (for convenience and practicality).

This keypair reuse becomes a problem when
A. A validator is leader for the same slot cross multiple genesis blocks
B. At least one node in gossip is running with the old genesis block

When that "same slot" occurs on the new cain, the node running the old chain can serve up shreds that will be accepted by nodes running the new chain.  This causes a slot verification error and effectively forks off whatever validator received that shred.

A simple (?) fix is to include the genesis hash of the chain implicitly in the signature of all shreds, so that shreds for the "old chain" will fail to verify on the "new chain" in the scenario described above.

**Comment by mvines** [comment]
@sagar-solana - could you take this one?

**Comment by sagar-solana** [comment]
Hm not straightforward to stick extra data in the shred(not transmitted data). Especially with gpu. It'll involve copying shred data into another buffer that carries the genesis hash.

**Comment by mvines** [comment]
Maybe just add the first 8 or 16 bits of the genesis hash into the shred data itself?  A small number of random bits is probably sufficient to keep multiple test chains from stomping on each other

**Comment by sagar-solana** [comment]
Yeah i think that's the way to go. Add the version field back lol.
