### ISSUE TITLE
Add RPC Wallet API

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#702]
RPU UDP-based API should be moved to a REST API so that it'd be straight-forward to add a web-based wallet.

**Comment by garious** [comment]
Here's a potential consumer of that API: https://metamask.io/. Not a requirement to close this ticket, but ideally, we could light up MetaMask with only minor tweaks/extensions after implementing our HTTP API. Please choose an API in the context of at least one popular, potential consumer.

**Comment by CriesofCarrots** [comment]
Based on MetaMask research, plan to use JSON-RPC protocol instead of REST.

**Comment by CriesofCarrots** [comment]
Maybe both...?

**Comment by mvines** [comment]
Yeah JSON-RPC seems to be the norm around these parts.  I don't think we need both

**Comment by mvines** [comment]
I looked into metamask and it only makes sense to interop with metamask, in it's current form, if we choose to implement an eth web3 provider.  Doing this boxes us into an eth world, which I don't think we want to do at this time.
