### ISSUE TITLE
Not enough information of process state during an OOM

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#7031]
#### Problem

Not enough information of process state during an OOM.

#### Proposed Solution

OOMs should dump all the threads.

**Comment by cyberbono3** [comment]
@mvines, could you give more context for this problem? So i can take a closer look at it.

**Comment by aeyakovenko** [comment]
I added some way to trace thread allocations via jemalloc.  it would be cool if we could dump all the threads or heap objects after an OOM.

**Comment by aeyakovenko** [comment]
https://github.com/jemalloc/jemalloc/wiki/Use-Case:-Leak-Checking

**Comment by cyberbono3** [comment]
@aeyakovenko   do you propose to dump [ThreadLocal](https://github.com/solana-labs/solana/blob/0bd41f98ed678388f45fc15978b9764888d595c2/core/src/thread_mem_usage.rs#L16)?  Sorry for beginner questions, i am not so familiar with Solana codebase. i need some direction and context which way I should dig )

**Comment by sakridge** [comment]
@cyberbono3 you could build a hashmap of thread name => u64, serialize as json with serde_json and write to a file.

**Comment by cyberbono3** [comment]
@sakridge do you have a chance to take a look at [it](https://github.com/solana-labs/solana/pull/7331) ?
