### ISSUE TITLE
Experiment with writing a compressed ledger and rsync uncompressed

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#707]
rsync of the ledger with compression requires the leader to compress on-the-fly for each client. In theory writing the ledger compressed to disk may reduce disk IO and also improve rsync speed since it doesn't need to compress on-the-fly.

**Comment by sakridge** [comment]
@aeyakovenko Yea, do we have a binary ledger ticket already? This could be more of experiment with ledger format or I can close and add compression as an idea to try to that one.

**Comment by aeyakovenko** [comment]
i dont think we have one yet.  i've been playing around with a 2 file format, one fixed entry size for PoH, the other one for data

@rob-solana is looking at it as well

**Comment by garious** [comment]
@sakridge, is this still an issue?

**Comment by mvines** [comment]
Obsoleted by #4158
