### ISSUE TITLE
no way to test genesis stakes without putting bogus stakes in genesis_accounts.rs

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#7083]
#### Problem
We want to test stake accounts in the SLP1 configuration using a genesis_accounts.rs containing only real accounts, for which we don't possess private keys. In SLP1, creating accounts is disabled, so we can't write those tests.

#### Proposed Solution
Create a command line tool that can create a file defining one or more staking accountss for which we have the private keys.  This file(s) can be consumed by `solana-genesis` to be included as staking accounts in genesis in a similar manner as we consume `--primordial-accounts-file` for TdS participants

#### Blocks
https://github.com/solana-labs/solana/issues/6194

**Comment by danpaul000** [comment]
cc: @rob-solana I'll take a first crack at this issue

**Comment by garious** [comment]
A problem description might be:
We want to test stake accounts in the SLP1 configuration using a genesis_accounts.rs containing only real accounts, for which we don't possess private keys. In SLP1, creating accounts is disabled, so we can't write those tests.

But that's probably not your problem, because your proposed solution wouldn't work.

**Comment by danpaul000** [comment]
> A problem description might be:
> We want to test stake accounts in the SLP1 configuration using a genesis_accounts.rs containing only real accounts, for which we don't possess private keys. In SLP1, creating accounts is disabled, so we can't write those tests.
> 
> But that's probably not your problem, because your proposed solution wouldn't work.

Sorry I mis-read your label earlier before jumping the gun.  Thanks for the feedback.
