### ISSUE TITLE
Airgapped CLI usage is undocumented

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#7084]
#### Problem

There is no documentation for the airgapped CLI feature being worked on in https://github.com/solana-labs/solana/projects/42.

#### Proposed Solution

Once https://github.com/solana-labs/solana/projects/42 is further along, document it in the book

**Comment by t-nelson** [comment]
Note: Mention potential key leakage via unencrypted swap

**Comment by mvines** [comment]
@t-nelson - think we can close this?

**Comment by t-nelson** [comment]
Probably.  I was considering it last night, but wanted to give the docs a
once over to check for any holes.  I'll do that today

**Comment by t-nelson** [comment]
Closing in favor of #7444
