### ISSUE TITLE
Fork choice rule can be tricked by a minority that overcommits to a fork.

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#7087]
#### Problem

Fork choice rule can be tricked by a minority that overcommits to a fork.

from @carllin:
somebody with 5% of the stake, will roughly in expectatoin be scheduled for 4 consecutve  slots in the schedule oncce every 3 days
so 16 consecutive slots
this 5% then aggressively votes on those slots, then withholds them from the rest of the 95% of the network
the rest of the network skiips those 16 slots, expring the last 4 votes on ther towers
then the 95% will ccontnue, buildng up another 16 votes on top oft hat tower, so net gain of 12 votes
and then the 5% broadcasts the 16 votes they had bult on top of ther tower, wth a net gaini of 16 votes
I think n this ccase . the 95% s now locked out for 2^16 . slots
so 7 hours

#### Proposed Solution

Fork choice rule should ignore forks that have a minority committed beyond the threshold.

tag: @carllin

**Comment by ParthDesai** [comment]
@carllin But nodes with 5% stake will not be scheduled enough to build those 16 slots at the same time the majority fork is building those 16.  By the time, 5% have built 16 slots, majority will be much ahead.

**Comment by aeyakovenko** [comment]
@ParthDesai I think you are right.  

The 5% Is locked out from the alternate fork, and is only expected to be scheduled once in the following 16 slots. So they can’t outrun the network.

But this attack gets easier to pull of the higher the stake.

**Comment by ParthDesai** [comment]
@aeyakovenko @carllin  what I think we could do is this:

1. Find leaf banks (must have entry in ascendants but no entry in descendants) 
2. If there is only one leaf, return
3. Sort leaves from major to minor stake(decreasing), and secondary sort by lockouts(increasing)
4. Start from end, and filter out leaves (which has minority stake committed beyond threshold)
5. If no leaves remains, return last filtered

**Comment by aeyakovenko** [comment]
@ParthDesai need a test that demonstrates the issue first.

If a majority voted on a child, it doesn’t matter if the minority overcommitted on a parent.  We only need to guard against voting on an overcomitted fork.

**Comment by aeyakovenko** [comment]
0.33 minority will be scheduled 9 times in a row 4 times per day.  It can withhold
its fork, let the other network reach 8 slots on a different fork, then transmit.  The main fork is locked out for 2^8 seconds from voting on the heavier fork which has 2^9 lockout with 0.33 minority.

**Comment by aeyakovenko** [comment]
let do some math on impact of this
1. 1/3 minority is scheduled 2x in a row 11% of the time.  Lockout for the 66% is 2 slots.  So total lost is 4 slots.  
95,040 / 216,000 ~= 0.44% loss for the main network.
47,520 / 216,000 ~= 0.22% loss for the 33% network.

(216000 - 47520) / (216000 - 95040) = 1.39
selfish miner makes about 40% more in rewards than the network.

1. 5% minority is scheduled 0.0025 of the time.

2,160 rewards lost for the main network
1,080 rewards lost for the minority

(216000 - 1080)/(216000 - 1080) = 1.0050505051

selfish miner makes about 0.5% more than the network.

**Comment by ParthDesai** [comment]
@aeyakovenko Makes sense. I am write now, writing a test that replicate this behaviour. Then, will work towards finding a solution.

**Comment by aeyakovenko** [comment]
@ParthDesai we don't need to solve selfish mining right now, since the attack vector requires a lot of stake to pull of, is visible to the network, and can be mitigated without a hard fork.  But we need to fix the original issue.  A minority fork shouldn't accidentally create a heavier fork and force the cluster to stall for a long time to switch.

**Comment by ParthDesai** [comment]
@aeyakovenko Yeah, writing test to replicate that scenario only.

**Comment by carllin** [comment]
@ParthDesai, in the 5% attack can happen if the minor fork is scheduled for 16 slots in a row. The probability is low, but in expectation, over 3 days, it should happen at least once.

I introduced capabilities in local cluster in my most recent PR to fix a leader schedule. You can leverage that functionality to write a test which:

1) Sets up a minor fork with multiple consecutive slots. 
2) Creates a custom broadcast stage that withholds those blocks and then broadcasts them at an opportune time to get the major fork to switch and be locked out

**Comment by ParthDesai** [comment]
@carllin cool, will write integration test. At the moment, I am writing unit test for `select_fork` which will illustrates this issue.
