### ISSUE TITLE
BlockhashQueue is non-deterministic when restarting from snapshots

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#7103]
#### Problem

The `BlockhashQueue` is not included in snapshot archives, so has to be rebuilt from the live network when restarting from one

#### Proposed Solution

Include the `BlockhashQueue` in snapshot images.

cc/ @TristanDebrunner for further details

**Comment by mvines** [comment]
@TristanDebrunner - can you please elaborate?

**Comment by mvines** [comment]
Note that the blockhash queue does get serialized as a part of a bank, which is included in a snapshot:
https://github.com/solana-labs/solana/blob/2a42ddbcbf95b87992fed963de37b5460cc305c4/runtime/src/bank.rs#L172

Maybe there's some edge case you're seeing that we are failing to handle?

**Comment by TristanDebrunner** [comment]
This seems to be a false alarm due to me misreading the code. After following the serialized banks through the code, I no longer think there's a problem.

**Comment by mvines** [comment]
\o/
