### ISSUE TITLE
CLI - Support creating a new nonce account for offline tx signing

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#7118]
#### Problem
We currently don't have an easy way to create an initialized nonce account.

Signing a transaction offline is slow and may require passing a `nonce` (valid blockhash) which will be verified by the nonce program. In order to consume the nonce, it must already be initialized in a separate transaction. Then, the nonce account private key must be used to sign the nonced transaction. 

#### Proposed Solution
Add a CLI command for creating and initializing a nonce account

`solana create-nonce-account ~/.config/solana/nonce-keypair.json`

Supported options:
- `--sign-only` for offline signing
- `--signatures` to use offline signature
- `ASK` instead of keypair path for secure key input

**Comment by jackcmay** [comment]
What is `ASK`?

**Comment by jackcmay** [comment]
What's in `~/.config/solana/nonce.json`

**Comment by jstarry** [comment]
> What is `ASK`?

Grep for `ASK_KEYWORD`. It's a magic keyword which triggers a seed phrase prompt

> What's in ~/.config/solana/nonce.json

Just an example path, not important. Just wanted to illustrate that a path could be provided to output the keypair to a file

**Comment by t-nelson** [comment]
I updated the description to clarify that the JSON would be a keypair, if specified.  Though, that file is an _input_ in this case.  The command will be using the keypair to create the nonce account on chain.

**Comment by jackcmay** [comment]
@jstarry Do we have a chicken and egg issue here where creating the nonce account offline itself requires a nonce?

**Comment by jstarry** [comment]
@jackcmay yeah looks like that way. I wasn't thinking about offline nonce creation when I wrote this issue. If you want to create a nonce offline you would probably have to do it with a nonce that was created online or you could just do it under 2min.
