### ISSUE TITLE
CPU-only nightlies are failing to maintain consensus

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#7119]
#### Problem
For the last several days, GCE & Colo CPU 5-node test has been failing consensus after a minute or two of the bench TPS client kicking off.  GPU-enabled testnets are not seeing this failure.

Latest result: https://metrics.solana.com:3000/d/testnet-edge/testnet-monitor-edge?var-testnet=gce-perf-cpu-only&from=1574661679616&to=1574662719109&refresh=60s&orgId=2
https://buildkite.com/solana-labs/system-performance-tests/builds/573

The last good nightly run without this issue was on Nov 21 against: 
https://github.com/solana-labs/solana/commit/d9024db68d6e5b35ebb791e2d82d448677fbe32b
The first time this issue came up was on the nightly on Nov 23 against: 
https://github.com/solana-labs/solana/commit/7f87ac4b650cbb525e982eb25c118f8c8967d429

History:
```
7f87ac4b6 Improve coverage.sh's environment awareness (#7101)
306fbd8bd install: Drop unneeded sha2 dependency (#7108)
3e0b272a2 Remove edge channel hardcode
6c89226cc Purge zero lamport accounts on snapshot ingestion (#7010)
f040987c9 Move date oracle to config program (#7105)
2a42ddbcb Don't panic if pubkeys are missing from Budget transaction (#7102)
8bb68c4e6 Really remove mentions of 'genesis_block' (#7099)
4485b978c Clean up accounts hash internal state api (#7090)
68bad56e7 Streamline multinode-demo/ restart logic (#7094)
ef55c1553 Remove unused --poll-for-new-genesis-config feature (#7093)
ce8d37984 Allow secure keypair input for solana-validator cli (#7080)
c8166aed9 Correctly indicate genesis activation_epoch (#7091)
0bd41f98e Avoid jemalloc in windows build (#7089)
d8ead57fb Use bs58 strings to declare IDs rather then raw bytes (#7082)
d9e7a5fcb Use fork weight instead of individual bank weight for fork selection. (#7079)
c965a110f Use unbounded channel (#7081)
8a879faac add genesis stake placeholders (#6969)
a2a9f1e33 Truncate new keypair files (#7078)
15d756803 Bump cbindgen from 0.9.1 to 0.10.0 (#7044)
8cbc45019 Create genesis.tar.bz2 in solana-genesis (#7039)
79199711b Add gpu resource usage tracking (#7075)
2c1b8fdd3 Add another test for bank state hashes (#7073)
d9024db68 Fix publish of move program (#7072)
```

**Comment by danpaul000** [comment]
cc: @sakridge @carllin @pgarg66 Not sure who is the right person to take this up

**Comment by sagar-solana** [comment]
Pretty sure this is the same "broadcast is slow" issue. 
It looks like we're asking too much tps but that's not a good enough reason to fall over like this. I'll try to dig into it.
