### ISSUE TITLE
master.testnet.solana.com node count is too damn high!

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#712]
After resetting m.t.s.c, the node count should be exactly 50 (unless somebody is running extra validator nodes attached to m.t.s.c -- possible but unlikely at this point).

After adding 17d927ac74ebb24d7fc5ce07c70ed5f9bc1a008c, it shows a node count of 80 or other numbers not 50.

It's possible we have some kind of crdt table issue.

STR: Look at the output from the latest build at https://buildkite.com/solana-labs/testnet-deploy

cc: #693 
cc: #695

**Comment by rob-solana** [comment]
@mvines, still an issue?

**Comment by mvines** [comment]
I suspect it is but we don't have a nice way to detect if/when this happens.  I think we could add a `--strict` flag to `bench-tps` that turns this expression [1] from a `<` to `!=`, then enable `--strict` on the internal testnets.  If it doesn't blow up then this issue can be closed


[1] https://github.com/solana-labs/solana/blob/708add0e6473c757667f73be7c8a2f0931de22b6/src/bin/bench-tps.rs#L506
