### ISSUE TITLE
Document paper wallet usage for key generation

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#7126]
Similar to https://github.com/solana-labs/solana/issues/7084, we need some documentation around using the paper wallet for key generation from an offline system that never touched the internet/etc.

**Comment by jstarry** [comment]
Off the top of my head this includes keypair generation and recovery using `solana-keygen` and inputting keypairs using seed phrases in our CLI tools. Anything else?

**Comment by mvines** [comment]
Yep, that please how to delegate stake with the paper wallet.  I think that'll cover it for 0.21

**Comment by mvines** [comment]
I guess this issue could be folded into #7084...

**Comment by jstarry** [comment]
Yeah lots of overlap but I think it's fine to knock this one out to get the groundwork laid out for #7084. Question though... where do we want the docs to live?

How about a new section in the sidebar of the book called "Paper Wallet Usage" under "Running an Archiver"

<img width="301" alt="Screen Shot 2019-11-26 at 11 53 07 AM" src="https://user-images.githubusercontent.com/1076145/69654755-526dc400-1043-11ea-9cb8-8e00a2e90a1f.png">

**Comment by jstarry** [comment]
And then some links from the other sections to this new section with "Using a paper wallet?" call to actions?

**Comment by mvines** [comment]
sg.  Just "Papet Wallet" as the section title seems sufficient but 🤷‍♂, we can better nit pick once there's some content in place

**Comment by jstarry** [comment]
Need a way to output the pubkey from a seed phrase without writing the keypair file.

Two options:
1. Add --ask-seed-phrase to `solana-keygen pubkey`
2. Add --no-outfile to `solana-keygen recover`
