### ISSUE TITLE
stake lockups run on slots, too granular

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#7128]
#### Problem
stake lockups are specified in slots, which is too granular

#### Proposed Solution
move lockups to epochs

**Comment by jackcmay** [comment]
Something like this?
 https://github.com/solana-labs/solana/blob/1eaf71b5b49baa7aad9b0d8b216dfebaab972b4a/genesis-programs/src/lib.rs#L102

**Comment by rob-solana** [comment]
this issue is closed, stakes moved to epochs when I added genesis placeholders
