### ISSUE TITLE
Drone doesn't give tokens sometimes

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#714]
Running the client after some time the leader/drone is up and client has been previously run.

Client requests an airdrop:

Drone seems to say it's successful:
```
Socket received FIN packet and closed connection
Socket closed with result: Ok(())
Airdrop requested...
 INFO 2018-07-19T21:21:26Z: solana::drone: Requesting airdrop of 500000 to [209, 12, 86, 25, 192, 180, 240, 173, 172, 13, 185, 142, 93, 79, 137, 224, 42, 107, 112, 50, 119, 107, 129, 50, 188, 227, 152, 254, 194, 254, 103, 91]
Airdrop sent!
Socket received FIN packet and closed connection
Socket closed with result: Ok(())
```

But client doesn't see that the balance is updated:
```
 INFO 2018-07-19T21:18:21Z: solana::crdt: 9f7c184d048cd33: run_listen timeout, table size: 2
Your balance is: 0
TPS airdrop limit reached; wait 60sec to retry
```

**Comment by sakridge** [comment]
This may be because I restarted the leader state without restarting the drone, need to test again. Error messages could be better in this case if that is the only case this can happen.

**Comment by garious** [comment]
@sakridge, agreed, but don't bug Tyera this week. Go ahead and handle that error as you see fit. Here's where it's created: https://github.com/solana-labs/solana/blob/master/src/drone.rs#L146

**Comment by sakridge** [comment]
@garious yea wasn't going to but tyera. I was going to look more into it but then got side-tracked/jet lagged. I assigned to myself.

**Comment by mvines** [comment]
I've seen this as well and wrote https://github.com/solana-labs/solana/commit/0206020104743b69ff711f0ef6feefffac103afd as a result.  Closing this issue until it reproduces
