### ISSUE TITLE
`BankClient` has no facilities for time travel

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#7199]
#### Problem

via @garious 

When writing tests, it is often necessary to wait for one or more blocks to elapse between transactions to ensure ordering. `BankClient` currently has no faculties for doing this conveniently.

#### Proposed Solution

Add a helper, ala. https://github.com/solana-labs/solana/blob/master/runtime/src/bank.rs#L1647.

**Comment by garious** [comment]
In hindsight, it shouldn't. User should poke the bank directly.
