### ISSUE TITLE
Fold scripts/tune-system.sh into sys-tuner

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#7203]
The `scripts/tune-system.sh` script is not shipped but is something that validators ought to run to configure their Linux kernel networking stack optimally.   

Now that the sys-tuner daemon exists, folding `scripts/tune-system.sh` into sys-tuner seems like a nice path.

**Comment by CriesofCarrots** [comment]
And update the clunky https://github.com/solana-labs/solana/blob/master/book/src/running-validator/validator-start.md#tune-system I just added :)
