### ISSUE TITLE
sys-tuner does not securely create the unix domain socket

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#7212]
sys-tuner runs as root, and 
1. Creates the unix domain socket at SOLANA_SYS_TUNER_PATH:
https://github.com/solana-labs/solana/blob/b874441a4742fb445a41d6ae344d3fe16d1ba9f2/sys-tuner/src/main.rs#L100
2. Modifies *then* the permissions of said socket:
https://github.com/solana-labs/solana/blob/b874441a4742fb445a41d6ae344d3fe16d1ba9f2/sys-tuner/src/main.rs#L102

This is racy as (1) occurs using the default umask, which could temporarily grant permissions to more than (2).  

To avoid this race, set umask to 077 before executing (1)

**Comment by pgarg66** [comment]
@mvines, the socket is created with 755 permissions, with root/root UID/GID. So until we call `set_socket_permissions()` only root user will be able to connect to the socket. We update the owner of socket to solana in `set_socket_permissions()`. So only process with `solana` UID can connect to it. I don't think there's a race condition where a random UID process can connect to the socket.

**Comment by mvines** [comment]
755 means other can open/read from the socket, which would trigger the daemon no?

**Comment by pgarg66** [comment]
I think to connect they need write permissions. I ran into this problem (while connecting from poh-service) before I added code to change the owner of the socket.

**Comment by mvines** [comment]
Hmm, I don't see why in theory.  But an explicit call to umask, https://docs.rs/libc/0.2.66/libc/fn.umask.html, before creating the socket to ensure it's created with no group/other perms would avoid any risk here entirely

**Comment by pgarg66** [comment]
Sounds good..
