### ISSUE TITLE
Testnet automation nightlies can mismatch scripts and binary version

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#7221]
#### Problem
To save time in automation, we often use pre-built tarballs on the edge or beta channels, rather than re-building them from source for each run.  This occasionally causes test failures due to mismatched argument passing from scripts to binaries.

#### Proposed Solution
Leave the selectable flag in place for on-demand test cases, but ensure that all nightly runs build from source to ensure consistency.

**Comment by mvines** [comment]
An alternative could be to ensure we sync the git commit to the exact commit used by the pre-built tarballs:
```bash
$ curl http://release.solana.com/edge/solana-release-x86_64-unknown-linux-gnu.yml
channel: edge
commit: d5c8b26a458bc469229640b359aa05339ca66c38
target: x86_64-unknown-linux-gnu
```

`PREBUILT_COMMIT=$(curl -s http://release.solana.com/edge/solana-release-x86_64-unknown-linux-gnu.yml | grep commit | cut -d: -f 2)`
