### ISSUE TITLE
Improve `solana uptime` to display multiple validators

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#7276]
`solana uptime <PUBKEY>` allows one to easily view the uptime measurement for a given validator.  But we're missing the ability to easily view the uptime for all nodes.

Two possible solutions that I see are:
1. `solana uptime`, with no pubkey, shows the uptime for all validators
2. Augment the `solana show-validators` command to include the uptime for all validators

**Comment by mvines** [comment]
There should also be a mechanism to report whether a validator is within "99.5% uptime" of the best/reference node.

**Comment by jstarry** [comment]
Going to move forward with "solution 2": adding a new column to the `show-validators` command
