### ISSUE TITLE
solana-validator doesn't use solana-cli's URL

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#7304]
#### Problem

solana-validator requires an `--entrypoint` parameter after having run `solana set --url=...`.

#### Proposed Solution

`--entrypoint` should default to the URL set in `solana-cli`

**Comment by mvines** [comment]
The trick here is that `solana-validator` does not have a strict dependency on RPC.  

RPC, if available, can be used by `solana-validator` to fetch genesis and/or a snapshot from another cluster node but this feature can also be disabled.

**Comment by garious** [comment]
Would be great if `--url` dropped it's port and we added an optional `--rpc-port` that defaulted to 8889.

**Comment by mvines** [comment]
Well —url actually means URL (http/https) so that probably would be pretty clumsy as now we need a —tls flag.  But in principal I totally agree about harmonizing these two “entrypoints” better somehow

**Comment by garious** [comment]
meh, got solana-cli-config nowadays
