### ISSUE TITLE
Add Nonce::Authorize instruction/support

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#7305]
There's a desire by partners to support single-signature Transactions that utilize a Nonce account.   Currently the Nonce account itself must be a signer, which prohibits such a Transaction.   This would be possible if we had a Nonce::Authorize instruction that behaved like the Stake::Authorize instruction, to authorize a system account to act as the authorized *noncer*.

**Comment by t-nelson** [comment]
Are we going to want the Stake implementation's "Authorized Withdrawer" functionality here as well?

**Comment by mvines** [comment]
What would an "Authorized Withdrawer" for a Nonce account be able to do?

**Comment by t-nelson** [comment]
Withdraw balance and consequently, close the nonce account.  It further decouples nonce account usage from the creation keypair.

**Comment by mvines** [comment]
That requirement didn't come up last week.   The only need was for some other system keypair be granted full control over the nonce account.

**Comment by t-nelson** [comment]
For some definition of "full"? 🙂 

I'll just encapsulate the authorization like Stake does so we can easily add it later if need be
