### ISSUE TITLE
CLI tools don't support offline signing for post-SLP1 commands

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#7328]
#### Problem

https://github.com/solana-labs/solana/pull/7104 implements offline signing for the commands that will be live with SLP1 (`pay`, `delegate-stake`, `deactivate-stake`).  The remainder of the commands, should support this as well.

#### Proposed Solution

Extend #7104

**Comment by t-nelson** [comment]
cc/ @garious

**Comment by garious** [comment]
this was done a while back
