### ISSUE TITLE
solana-ping not well documented

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#7351]
#### Problem

After reading:
> https://docs.solana.com/book/v/master/api-reference/cli#solana-ping

It's not obvious to me what it is or what it's for. Most surprisingly, it looks to have no relationship to the popular command-line tool `ping`.

#### Proposed Solution

Add better docs. Consider renaming?

**Comment by garious** [comment]
Who added `solana-ping`?

**Comment by garious** [comment]
Found it! https://github.com/solana-labs/solana/pull/5508 . Indeed related to `ping`.

**Comment by mvines** [comment]
💦
