### ISSUE TITLE
activate.and_then(deactivate) != noop

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#7376]
#### Problem

Deactivating stake before it activates isn't equivalent to not activating at all:

```
stake activates starting from epoch: 10
stake deactivates starting from epoch: 10
```

#### Proposed Solution

Reset the stake account?

**Comment by garious** [comment]
Maybe we can't reset? Credits are earned during warmup?
`credits observed: 54850`

**Comment by rob-solana** [comment]
credits are observed, not earned.  redemption takes warmup into account

**Comment by garious** [comment]
@rob-solana, if deactivate happens in the same epoch is activate, can the account be reset?

**Comment by rob-solana** [comment]
Once de-activated, the only thing one can do with a stake is withdraw().  What use case would you like to cover?

**Comment by rob-solana** [comment]
in an SLP1 world, the lamports in a stake can only be activated once.  Once deactivated, the lamports in the stake are idle until the system program is enabled.

**Comment by garious** [comment]
I'm just trying to figure out what a staking noop is. If I destake in the same epoch as I staked, what's the effect?

**Comment by rob-solana** [comment]
the effect is that you have a stake that's:
1. never earns anything
2. immediately available for withdrawal

**Comment by garious** [comment]
@rob-solana, so can the destaking instruction reset the stake account if it hasn't yet activated?

**Comment by rob-solana** [comment]
I think so, is this an important use case?  If you happen to delegate() close to the end of an epoch, you might be disappointed that an "immediate" deactivate() doesn't work...

**Comment by rob-solana** [comment]
more generally, might be cleaner to just allow re-activation once the stake is fully cooled down

**Comment by garious** [comment]
It's not an important use case. For me, understanding code comes from understanding what variations are equivalent. In this case, I can't restake in the same epoch because of an implementation detail. Not resetting that account makes me, the user, think not my brief bit of staking caused some irreversible side-effect. Less than ideal.

**Comment by rob-solana** [comment]
not being able to restake in the same epoch may be an implementation detail, but:
1. these kinds of limitations are going to exist in almost every program until we support dynamic allocation
2. this limitation **_is_** documented

**Comment by garious** [comment]
Why is dynamic allocation relevant?

**Comment by rob-solana** [comment]
stake could support any number of re-delegations per epoch if there were unlimited space for recording those delegations.  recording previous delegations is necessary to prevent stakers from running away from slashing

**Comment by garious** [comment]
This has taken me a while to absorb. Thanks for the clear explanation. Closing.
