### ISSUE TITLE
Ugly CLI errors

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#7377]
#### Problem

Need a secret decoder ring to grok the CLI errors.

#### Proposed Solution

Render error messages, including custom errors.

**Comment by garious** [comment]
Looks like this was done here: #5494, but not for staking commands.

**Comment by mvines** [comment]
Can you give the specific commands that you think are ugly while it's fresh in your mind

**Comment by CriesofCarrots** [comment]
I can take this.

**Comment by garious** [comment]
I did a reactivate of stake within the same epoch and needed to go dig into the code to see what `CustomError(3)` was. So:

```bash
solana activate-stake ...
solana deactivate-stake ...
solana activate-stake ...
```

**Comment by CriesofCarrots** [comment]
Actually, all the stake commands use `log_instruction_custom_error()`, and so should be rendering the errors nicely.

The issue appears to be that CLI transaction submission is returning TransportError::IoError, instead of TransportError::TransactionError. Haven't yet identified why.

**Comment by CriesofCarrots** [comment]
Ah, got it. This: https://github.com/solana-labs/solana/pull/6219
Will find a clippy-approved way to accomplish the missing `if status.is_some()` case
