### ISSUE TITLE
Ledger Cleanup thread crashes when reading directory size

### ISSUE THREAD

**Issue by sagar-solana** [solana-labs/solana#7389]
#### Problem

STR: 
1- Ran a testnet with 5 validators and 2 clients pushing 10000 tx_count with 250ms sleep with `--limit-ledger-size` enabled and its num_slots set to 1192 slots (also updated `pub const DEFAULT_DEV_SLOTS_PER_EPOCH: u64 = 1192;
`)
2- After about 15 mins some nodes' limit ledger size threads crashed

```
solana-ledger-cleanup | panicked at 'failure while reading ledger directory size: Error { kind: NotFound, message: "entity not found" }', src/libcore/result.rs:1165:5
```

**Comment by sunnygleason** [comment]
@sagar-solana am afk but I can turn around a patch for this in the next hour or 2. I had coded the storage size method as an `Option<u64>` initially, then changed to expect/panic. Does`Option` sound right? (Or is `Result<u64>`) more appropriate for `storage_size()`?)

**Comment by sagar-solana** [comment]
No rush. Only a problem if limit-ledger-size is switched on.
It'd be nice to understand why this error occurs and then we can decide to ignore it with an option if we think that's reasonable.

**Comment by sunnygleason** [comment]
I think it's a race between reading the directory and reading the file metadata:

![image](https://user-images.githubusercontent.com/153621/70490212-d5732d80-1acb-11ea-89b3-694ce2f18d26.png)

**Comment by sagar-solana** [comment]
Yeah maybe that's what is happening. But it seems like a bug on their end? Return an option for now i guess. @carllin said that their repo isn't super active so might not be worth filing an issue.

**Comment by sunnygleason** [comment]
PR available at : https://github.com/solana-labs/solana/pull/7401

(assigning to @sagar-solana pending PR)
