### ISSUE TITLE
thread 'solana-record-stage' panicked at 'assertion failed: serialized_size(&entry).unwrap() <= BLOB_DATA_SIZE as u64', src/entry.rs:67:9

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#740]
This assert is failing on the testnet leader sometimes:
https://github.com/solana-labs/solana/blob/73ae3c3301805/src/entry.rs#L67

```
thread 'solana-record-stage' panicked at 'assertion failed: serialized_size(&entry).unwrap() <= BLOB_DATA_SIZE as u64', src/entry.rs:67:9
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   ...
   7: solana::entry::Entry::new
   8: solana::ledger::next_entries_mut
   9: solana::record_stage::RecordStage::process_signal
```

**Comment by mvines** [comment]
New info from #774:
```
thread 'solana-record-stage' panicked at 'Serialized entry size too large: 66204 (292 transactions):', src/entry.rs:70:13
```

**Comment by rob-solana** [comment]
lots of votes, I guess!

**Comment by mvines** [comment]
The transactions should be getting chunked well before 292 though!  https://github.com/solana-labs/solana/blob/master/src/ledger.rs#L77-L79

**Comment by rob-solana** [comment]
yep, I don't see how 292 gets through unless that vector of transactions is being modified while being passed to recorder

**Comment by mvines** [comment]
My current guess is that `chunk_len = 1` here [1].

[1] https://github.com/solana-labs/solana/blob/master/src/ledger.rs#L82

**Comment by rob-solana** [comment]
I don't get it.  chunk_len = 1 would mean a lot of single-Transaction Entries, right?
