### ISSUE TITLE
`colo.sh create` does not exit with error if a client fails to be allocated

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#7412]
#### Problem
`colo.sh create` does not correctly check for the availability of client nodes, or the success  in allocating one.  It appears only to do this check for validator nodes.  This causes testnet deployment to fail at `net.sh start` instead.

#### Proposed Solution
Improve node status/availability printing and exit if all requested resources are not available.

**Comment by danpaul000** [comment]
cc: @t-nelson

**Comment by t-nelson** [comment]
Analysis is correct.  The checks exist in `gce.sh` and so apply to all providers.  The check should be fairly straightforward to port into the other node roles.  Not sure when I'll have time to take it on though
