### ISSUE TITLE
0.21: rpc threads are panicking on testnet.solana.com and bringing down RPC

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#7418]
As seen on Grafana:
> panicked at 'Rooted parent slot must have blockhash', src/libcore/option.rs:1190:5

This appears to be due to ongoing RPC API testing.  Once all the rpc worker threads panic, the RPC service stops responding.

**Comment by CriesofCarrots** [comment]
The rpc node is panicking when a downstream client tries to getConfirmedBlock on its first root (aside from slot 0).
Blocktree::get_confirmed_block assumes a root always has a valid parent slot, but when a node is booted from a snapshot (as the rpc node is on testnet boot), the snapshot root doesn't contain any entries or have a valid parent root in blocktree.
