### ISSUE TITLE
erasure::recover() may pollute the window if corrupt blobs are received

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#742]
currently a "corrupt" boolean makes a braindead check of erasure recover results by verifying that blob size isn't outrageous, and if it is, raising an assert!()

recover should instead back out the generated blobs from the window and return an error.  the error impugns all blobs in the erasure block...

**Comment by garious** [comment]
@rob-solana, is this still an issue?

**Comment by rob-solana** [comment]
nope
