### ISSUE TITLE
`colo.sh create` motd and lock files are getting mangled

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#7423]
#### Problem
Creating colo resources isn't correctly creating the motd and/or lock files to display the owner of the testnet when you ssh into one of the nodes.  Creating log dumps the following on all nodes:
```
IP(216.24.140.155) Err(1) LINE(/home/solana/.solana.lock: line 3: syntax error in conditional expression)
IP(216.24.140.155) Err(1) LINE(/home/solana/.solana.lock: line 3: syntax error near `-a')
IP(216.24.140.155) Err(1) LINE(/home/solana/.solana.lock: line 3: `[[ -v SSH_TTY -a -f "/home/solana/.solana-motd" ]] && cat "/home/solana/.solana-motd" 1>&2')
```

#### Proposed Solution
Bug smash

**Comment by t-nelson** [comment]
🤔 when did this start?

**Comment by danpaul000** [comment]
Not sure.  I've noticed it for at least a week, but could be longer
