### ISSUE TITLE
StakeInstruction::RedeemCredits is opaque

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#7457]
#### Problem
When a successful RedeemVoteCredits instruction appears on the ledger, a user can surmise that something may have happened to the included stake account's balance, but can't tell what.
This is an obstacle to downstream users who need to follow all credits/debits of Stake accounts and may not be able to query the account state in real time.

#### Proposed Solution
Include the lamports transfer balance in the RedeemVoteCredits instruction.
This requires a client to query for account states to determine the current outstanding credits and epoch validator_point_value.
RedeemVoteCredits transactions should be rejected if the balance passed in the instruction does not match the system's own calculation.

**Comment by mvines** [comment]
Obsoleted by #7492
