### ISSUE TITLE
Transactions are processed when accounts have changed since blockhash

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#7471]
#### Problem

A client transaction contains a blockhash, which indicates the client observed the chain at that particular state. The transaction may or may not want to ensure certain accounts have not changed since that state. If it ensures *all* accounts haven't changed, the transaction output is deterministic. The current implementation processes all valid transactions and does not check to see if accounts have changed since the blockhash.

#### Proposed Solution

Define one of the bits in the `AccountMeta` bitfield as the "unchanged since blockhash" bit, named "unchanged".  When the bit is set, the runtime should check for changes to that account since the transaction's blockhash. If there have been any changes, the transaction should be rejected with the error `TransactionError::AccountChangedSinceBlockhash`.

Open question: should the transaction fee be charged? My gut feeling is "no" and that setting that bit adds a constraint of what is or is not a valid transaction. That'd make the list:
* Valid signatures
* Valid blockhash
* Can pay transaction fee
* Account unchanged since blockhash

Open question: should the bit mean "unchanged since nonce account blockhash, if available, otherwise transaction blockhash"?

cc: @rob-solana @aeyakovenko

**Comment by aeyakovenko** [comment]
A less invasive way to do consistency would be with a 

* `ConsistencyProgram:ConfirmOutputHash`, validates all the modified accounts hash to the expected value.  This should be run at the end of the instruction vector.
* `ConssitencyProgram::ConfirmInputHash`, validate all the input accounts hash to the expected value.  This should be run at the start of the instruction vector.

**Comment by rob-solana** [comment]
how will this work with nonces?

**Comment by garious** [comment]
@rob-solana, your question is the same as the last "Open question" in the issue's description.

**Comment by garious** [comment]
@aeyakovenko, your solution is very elegant and does not require any special cases for nonce accounts. Thanks for your feedback!

**Comment by rob-solana** [comment]
> A less invasive way to do consistency would be with a
> 
> * `ConsistencyProgram::ConfirmOutputHash`, validates that all the modified accounts hash to the expected value.  This should be run at the end of the instruction vector.
> * `ConsitencyProgram::ConfirmInputHash`, validates that all the input accounts hash to the expected value.  This should be run at the start of the instruction vector.
> 
> These can be used together or individually.

I think this issue should be closed and a new issue opened that captures the requirement we've discussed, but not actually written down.

As I understand it, the requirement is: "account balances must be calculable by examining the ledger without knowing how to interpret the smart contract instructions contained therein."

@aeyakovenko's proposal does not cover transactions issued without the guards, and so does not satisfy the requirement above.

**Comment by aeyakovenko** [comment]
@rob-solana I think those are separate issues.  I don't think we need to support the latter, but we should capture the thoughts.  If certain values need to be observable from the transactions, or is it ok if everything depends on the computed state.

**Comment by rob-solana** [comment]
> @rob-solana I think those are separate issues. I don't think we need to support the latter, but we should capture the thoughts. If certain values need to be observable from the transactions, or is it ok if everything depends on the computed state.

@aeyakovenko which is "the latter"?

maybe separately: are you suggesting that we should open another issue to track the requirement I described above?

**Comment by aeyakovenko** [comment]
@rob-solana two issues:
1. transactions have no way to ensure data consistency, that the output is guaranteed to be what the transaction signed.
2. asset transfers are not observable on the ledger without computing the state.

**Comment by rob-solana** [comment]
> @rob-solana two issues:
> 
> 1. transactions have no way to ensure data consistency, that the output is guaranteed to be what the transaction signed.

this sounds like a "nice to have", not something required (maybe I missed a discussion)

> 2. asset transfers are not observable on the ledger without computing the state.

and this seemed like it was a requirement, but has now been dropped apparently

**Comment by aeyakovenko** [comment]
@rob-solana neither is a requirement atm.

**Comment by aeyakovenko** [comment]
I guess, close the issue?  wdyt @garious @rob-solana

**Comment by garious** [comment]
Yeah, I'll close. What we actually need is a library of tips and tricks.
