### ISSUE TITLE
Every rent exempt account creation requires an RPC call

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#7498]
#### Problem
Every time a client wishes to create an account that is rent exempt with a unique data size, an RPC call is needed to fetch `getMinimumBalanceForRentExemption`. This is overkill because the rent config is fixed in genesis.

For example, when creating a new program. A Dapp developer will need a rent exempt program account and may also want to initialize many rent exempt accounts for that program. If each account has a different size, the developer will need to make an RPC call to determine the rent exemption for each account.

#### Proposed Solution
Expose a new RPC endpoint called `getRentCalculator` which will allow clients to compute rent exempt balances on their own. See `FeeCalculator` for prior work

**Comment by jstarry** [comment]
If we add `getRentCalculator` I think `getMinimumBalanceForRentExemption` will not be needed anymore.

**Comment by mvines** [comment]
> This is overkill because the rent config is fixed in genesis.

We'll likely have rent adjustments in the future at Epoch boundaries
