### ISSUE TITLE
Stake program does not support create_account_with_seed()

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#7505]
#### Problem
derived addresses from the system program are not supported by stake_instruction.rs

#### Proposed Solution
- [x] add support (some copy-pasta from stake_instruction::create_account())
- [ ] verify that the instructions work by adding a small test to runtime/test/stake_instruction

**Comment by CriesofCarrots** [comment]
@rob-solana , it looks like past-Rob resolved the bulk of this issue already!
https://github.com/solana-labs/solana/pull/7472
I'll add a small test, though

**Comment by rob-solana** [comment]
oh... heh
