### ISSUE TITLE
Create an 8 hour stability cluster testcase for routine automation

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#7525]
#### Problem
We don't have a repeatable/controlled way to regularly ensure cluster long-term stability until a more public facing cluster has issues.

#### Proposed Solution
Add a .yml file specifying an 8-hour idle (no client) cluster that should just process vote accounts.  Should be able to run this on cron like the nightly perf tests and report the results and links to our results bot.

Test should be considered failed if:
- Any nodes stop voting
- The cluster root slot stops advancing
- Any nodes panic
- Mean confirmation time is above [###] ms/sec

Test is considered a pass if none of the above conditions are hit.  For this issue, pass/fail determination may be a manual check at the end of the test duration.

**Comment by danpaul000** [comment]
@mvines anything to comment re: proposed pass/fail criteria?  Can we quantify an idle cluster conf threshold?

**Comment by mvines** [comment]
I'd just start with the top three for v1 actually. 

For checking "Any nodes stop voting" and "The cluster root slot stops advancing", we've got `solana-watchtower` now that essentially does this.  But where you thinking of using metrics queries directly?

**Comment by danpaul000** [comment]
Yeah ultimately I'd like to have some smarter metics parser or cluster
tooling to determine pass fail or other thresholds but for right now I'm
just thinking a human check that the cluster was alive for the duration
that the automation brought it up to the time it brought it down
