### ISSUE TITLE
Repair request/response can potentially flood the cluster

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#7529]
#### Problem
The cluster can get flooded by repair request/response. This can happen due to 
1. A malicious node, that's generating spurious repair requests targeting one valid node or the whole cluster
2. Network behavior such that alternate paths are not available, routing and/or spanning loops exist, or network partitions exist between responding and requesting nodes

Reference section 6.4.2.1.1

#### Proposed Solution
1. Write tests that simulate such conditions.
2. More intelligence in repair service, that can detect excessive repair requests from a node, and throttle that node's repairs
3. Filter malicious node's IP/ports via kernel filters (e.g. iptables)
4. Validators can deploy firewalls that can be configured dynamically.

More thoughts are needed to find a comprehensive solution for such attacks.

**Comment by sakridge** [comment]
Fixed by https://github.com/solana-labs/solana/pull/9056
