### ISSUE TITLE
Improve handling of missing/crashed nodes in cluster

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#7533]
#### Problem
Nodes can turn off/crash while active in cluster. Such nodes could potentially be in leader schedule. Also, turbine would use these nodes for block propagation. The missing nodes will impact progress of the blockchain, and transaction confirmation times. 

Kudelski reference: Table 4, items 1, 2, 3

#### Proposed Solution
This issue requires more discussions and brainstorming.

**Comment by jon-chuang** [comment]
Is the Kudelski audit available for public consumption?

**Comment by mvines** [comment]
yep! https://solana.com/solana-security-audit-2019.pdf
