### ISSUE TITLE
Slashing needs to verify that slot is an ancestor of the current bank.

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#7553]
#### Problem

Slashing implementation needs to verify that a slot is an ancestor of the current bank.

#### Proposed Solution

Implement a sysvar that holds ancestor slots for at least 1 epoch.

#7522

**Comment by rob-solana** [comment]
@aeyakovenko there's a small difficulty with "at least one epoch": sysvars kinda need to have a fixed size, but the required size for this one is configured at genesis, not a constant.

can we pick a reasonable number of ancestors to record as a fixed number?  e.g. 2M ancestors, and if the slashing offense isn't caught in that timeframe, the validator has got away with it?

**Comment by aeyakovenko** [comment]
@rob-solana why not N sysvars?  One for every 10k slots or something.

**Comment by rob-solana** [comment]
@aeyakovenko same problem, sysvars live in accounts, so aren't really very good at having a configurable size...

**Comment by aeyakovenko** [comment]
@rob-solana no, just sysvar EpochSlots0 is the first 10k slots.  EpochSlots1 is 10k-20k.

**Comment by rob-solana** [comment]
most recent 10k slots?
have a look at the PR?

**Comment by aeyakovenko** [comment]
@rob-solana why not absolute values.  I know which slot the node was slashed in.  I can pick the sysvar programatically

**Comment by rob-solana** [comment]
ok, so you're saying that we'd reserve 44 bits of the address to be able to cover 64-bits of slots 1 million slots at a time?

**Comment by rob-solana** [comment]
slashing conditions should eventually be too old to be punish-able, to cover the case of a leaked key, for example

**Comment by aeyakovenko** [comment]
@rob-solana it only needs to cover at most 2 epochs worth of slots.

**Comment by rob-solana** [comment]
ok, cool.  1M slots is roughly 1/3 of an epoch, 2M slots is like 10 days.
