### ISSUE TITLE
Slashing needs a list of previous authorized signers in the epoch

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#7555]
#### Problem

A validator could violate slashing and change the VoteState authorized signer.

#### Proposed Solution

1. Maintain a list of N previous authorized signers.
2. Only allow N updates per epoch.

**Comment by mvines** [comment]
@aeyakovenko - can you please clarify what "authorized signer" means in the context.  We have multiple authorized signers in various parts of the code so I'm unclear on which one you mean here

**Comment by aeyakovenko** [comment]
The authority that signs Votes.  We need to keep track of all of them for the duration of the slashing epoch.

**Comment by mvines** [comment]
This guy then:
https://github.com/solana-labs/solana/blob/d88d8e2dbb847da394704908357d3a023020df4e/programs/vote/src/vote_state.rs#L107
Thanks!

**Comment by rob-solana** [comment]
fixed in #7643
