### ISSUE TITLE
Support Nonce and Stake program in solana-web3.js

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#7583]
We've have a request to support Nonce and Stake programs in solana-web3.js, specifically the ability to generate Transactions with these programs for offline signing.

 Stake program support can be added anytime, but I suggest waiting until #7443 is resolved before adding Nonce program support to avoid unnecessary churn.

**Comment by CriesofCarrots** [comment]
Initial Nonce implementation:
- [ ] Nonce account creation and withdrawal, stored value query
- [ ] Executing instructions with Nonce: System transfer, Stake delegate and deactivate
