### ISSUE TITLE
A downed node appears to have too large of an impact on the blocks produced by the next leader in line

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#7588]
On an idling cluster running v0.21.5 with one validator offline, `solana show-block-production -v` shows that typically the leader following the offline validator misses two slots while it waits for the offline leader to timeout:
```
  2121738         5BD5PWT7Nn3ZFxZFXKgbrzFZxPi7FxxXHyEdbmVuPEGG
  2121739         5BD5PWT7Nn3ZFxZFXKgbrzFZxPi7FxxXHyEdbmVuPEGG
  2121740         2te46rxywMdCNdkvjumiBBPQoVczJFxhxEaxFavQNqe3 MISSED
  2121741         2te46rxywMdCNdkvjumiBBPQoVczJFxhxEaxFavQNqe3 MISSED
  2121742         2te46rxywMdCNdkvjumiBBPQoVczJFxhxEaxFavQNqe3 MISSED
  2121743         2te46rxywMdCNdkvjumiBBPQoVczJFxhxEaxFavQNqe3 MISSED
  2121744         5BD5PWT7Nn3ZFxZFXKgbrzFZxPi7FxxXHyEdbmVuPEGG MISSED
  2121745         5BD5PWT7Nn3ZFxZFXKgbrzFZxPi7FxxXHyEdbmVuPEGG MISSED
  2121746         5BD5PWT7Nn3ZFxZFXKgbrzFZxPi7FxxXHyEdbmVuPEGG
  2121747         5BD5PWT7Nn3ZFxZFXKgbrzFZxPi7FxxXHyEdbmVuPEGG
```

Consider reducing grace ticks?

**Comment by pgarg66** [comment]
We can also test if the previous leader (`2te46rxywMdCNdkvjumiBBPQoVczJFxhxEaxFavQNqe3 ` in example above) has not transmitted any data in its leader slots. If so, the grace ticks can be ignored by the next leader. This will remove any delays due to missing nodes.
