### ISSUE TITLE
Genesis block and validator software version mismatches are hard to detect.

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#7709]
#### Problem

User reported error:

I have got some test tokens, but stuck at connecting to the TDS cluster:
```
ERROR solana_core::validator] Failed to load genesis from "/root/validator-ledger": Unable to deserialize "/root/validator-ledger/genesis.bin": Io(Custom { kind: Unexp
ectedEof, error: "" })
```

When booting 0.21.5 on 0.22 genesis.

#### Proposed Solution

Track genesis block versions.

**Comment by mvines** [comment]
ABI management, #7738, should help here to detect when the genesis block binary format changes.

**Comment by mvines** [comment]
Fixed by not changing the genesis format anymore :)
