### ISSUE TITLE
No test for archiver and validator storage mining functionality

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#7710]
#### Problem

There doesn't seem to be a test that verifies that an archiver can join a network and start receiving storage rewards for storage mining on the network and also that a validator could also receive rewards.

#### Proposed Solution

Write a local cluster test that starts a network and an archiver and sees that the mining rewards are correctly applied to validators and archivers.

**Comment by jon-chuang** [comment]
I am interested in this, but I can only start in 6 weeks. Can this cluster test be run locally? If not, I would appreciate access to a cloud cluster once some minimal amount of code has been written.

**Comment by sakridge** [comment]
> 
> 
> I am interested in this, but I can only start in 6 weeks. Can this cluster test be run locally? If not, I would appreciate access to a cloud cluster once some minimal amount of code has been written.

It can be run locally, check out these docs: https://docs.solana.com/bench-tps#configuration-setup

**Comment by jon-chuang** [comment]
@sakridge Could you point me in the direction of some other cluster tests not necessarily related to the archiver? I'd like to get a feel for the necessary components and standards.

**Comment by jon-chuang** [comment]
I'm getting the following errors running
```
cargo test test_archiver_startup_1_node -- --ignored
```
```
ERROR solana_local_cluster::local_cluster] leader_pubkey: 6muxfTtyydzu9u6ro2SNJq8ReBsrKWr91mPoSMs9Z1A9
ERROR solana_archiver_lib::archiver] Unable to submit mining proof, no storage account
```
What am I doing wrong?

**Comment by sakridge** [comment]
> 
> 
> I'm getting the following errors running
> 
> ```
> cargo test test_archiver_startup_1_node -- --ignored
> ```
> 
> ```
> ERROR solana_local_cluster::local_cluster] leader_pubkey: 6muxfTtyydzu9u6ro2SNJq8ReBsrKWr91mPoSMs9Z1A9
> ERROR solana_archiver_lib::archiver] Unable to submit mining proof, no storage account
> thread 'test_archiver_startup_1_node' panicked at 'called `Result::unwrap()` on an `Err` value: SegmentDownloadError',
> ```
> 
> What am I doing wrong? Or are these precisely the incomplete tests that this issue is meant to address?

Yep, fixing these would be good first step.

**Comment by ryoqun** [comment]
I'm fairly certain this can be closed.
