### ISSUE TITLE
Archivers don't send fake storage proofs

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#7711]
#### Problem

Archivers don't send fake storage proofs to catch cheating vaildators

#### Proposed Solution

Archivers should hash a message, then send a fake porep to the network to catch validators who are cheating, then send a transaction to the network to prove the cheating after observing it.

**Comment by jon-chuang** [comment]
I am interested in this

**Comment by ryoqun** [comment]
I think we can close this for now. (let's reduce open issues!)
