### ISSUE TITLE
Resolve all security vulnerabilities in dependencies before 1.0

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#772]
Using the audit script added in #769 as a guide, work with upstream crates to eliminate their dependencies that contain security vulnerabilities.  Once done, make `ci/audit.sh` blocking in CI.

**Comment by mvines** [comment]
Fixed by #809

**Comment by garious** [comment]
The commit message in an open PR says that it closes this issue. It'll close automatically when that PR is merged.
