### ISSUE TITLE
testnet stops voting 

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#775]
After a brief time post deployment, a large testnet appears to stop processing votes.  The symptoms:
1. Validators continue to vote once a second
2. Leader doesn't process the validator votes
3. Transacting against the leader still works as expected

It appears that the `last_id` of the validators gets *stuck* and the validators the vote repeatedly for the same `last_id`.  The leader then starts throwing `LastIdNotFound` errors from bank.rs

**Comment by mvines** [comment]
I think I can repo on a local setup by just running `client.sh` with a leader+validator+drone

**Comment by mvines** [comment]
#764 may be a symptom of this issue

**Comment by mvines** [comment]
Windowing!   When `bench-tps` spools up on the testnet, validators continue to receive blobs (`received` increments) but they stop consuming them (`consumed` stalls).
Ref: https://github.com/solana-labs/solana/blob/dd819cec3df249fd434a8c443f32cfde33af89bc/src/streamer.rs#L441-L447

eg, here's a validator that has received 337643 blobs but only consumed 2048 of them.
```
solana::streamer: 9241dfe2d1a06c60: RECV_WINDOW 2048 337643: got packets 1
```

Will try to trace around in streamer.rs to identify the exact failure, stay tuned.

**Comment by mvines** [comment]
Blocked on  ∞ window work (issue TBD)

**Comment by mvines** [comment]
Depends-on: #872

**Comment by aeyakovenko** [comment]
#869 is most likely needed too.  we could get away with #869 and double the window size.  @sakridge one other thing to try is sending votes to a different socket so they can jump the queue.

**Comment by mvines** [comment]
This manifests only when `bench-tps` is flooding the network, bumping to 0.8

**Comment by rob-solana** [comment]
@mvines still an issue?

**Comment by mvines** [comment]
perf-testnet looks pretty solid now.  Let's close this one and open something new if needed down the road
