### ISSUE TITLE
--wait-for-supermajority ignores new validator's snapshot resumption delay

### ISSUE THREAD

**Issue by ryoqun** [solana-labs/solana#7786]
#### Problem

`solana-validator`'s `--wait-for-supermajority` does wait for the supermajority and it's very handy. However, it doesn't account for the newly-joined validator's snapshot resumption delay. In production and stress-testing settings, snapshots are large and takes some time for started validator process to resume from it.

Normally, this is ok thanks to our fork selection rules. Such extra forks should eventually will be abandoned.

#### Proposed Solution

any of?:

- Delay gossip-ing until snapshot resumption is finished
- Include gossip is_complete flag
- Add is_complete RPC endpoint

Also consider `--no-snapshot-fetch`

#### Background

I've tested large ledger hoping something odd for the bank hash mismatch #7736; And I've found this instead as part of the investigation.

**Comment by mvines** [comment]
Are you saying you're seeing the validator jump on gossip before it's done processing the ledger?

https://github.com/solana-labs/solana/blob/e6af4511a8ad22eeba73339ddee54dc05931e5a6/core/src/validator.rs#L282-L288
happens well after:
https://github.com/solana-labs/solana/blob/e6af4511a8ad22eeba73339ddee54dc05931e5a6/core/src/validator.rs#L152-L170
and we wait `--wait-for-supermajority` still later.

**Comment by ryoqun** [comment]
Yeah, it seems so. Actually, this really happens.

Log excerpts (in mixed and strictly chronological order from two validators):

```
# Start validator A: $ validator --wait-for-supermajority
A: [2020-01-16T06:34:16.748758557Z INFO  solana_metrics::metrics] host id: 9EYDJ4HDLYjLMqcZZCgVaE4Bu2LQVLAkBaLe1iHBju3C
A: [2020-01-16T06:34:16.749507632Z INFO  solana_core::validator] creating bank...
...
A: [2020-01-16T06:34:17.381713333Z INFO  solana_ledger::blockstore_processor] ledger processed in ...
A: [2020-01-16T06:34:17.382053707Z INFO  solana_core::rpc_service] rpc bound to V4(0.0.0.0:8899)
A: [2020-01-16T06:34:17.384165673Z INFO  solana_core::validator] Waiting for more than 66% of activated stake at slot 1707 to be in gossip...
A: [2020-01-16T06:34:17.384213360Z INFO  solana_core::validator] 51% of activated stake in gossip
...
A: [2020-01-16T06:34:27.396793484Z INFO  solana_core::cluster_info]
A:    IP Address        |Age(ms)| Node identifier                              |Gossip| TPU  |TPU fwd| TVU  |TVU fwd|Repair|Storage| RPC  |PubSub
A:    ------------------+-------+----------------------------------------------+------+------+-------+------+-------+------+-------+------+------
A:    127.0.0.1       me|  2503 | 9EYDJ4HDLYjLMqcZZCgVaE4Bu2LQVLAkBaLe1iHBju3C | 8001 | 8377 | 8886  | 9696 | 9262  | 8538 | none  | 8899 | 8900
A:    Nodes: 1
# start validator B: $ validator --wait-for-supermajority
B: [2020-01-16T06:34:43.332626585Z INFO  solana_metrics::metrics] host id: 7SgZJnxM7PSSE7PJ7BgPXdG1NH5sqxDDnNyiie5d1Aqg
...
#?!?! Wait wait too early...
A: [2020-01-16T06:34:43.388068550Z INFO  solana_core::validator] 100% of activated stake in gossip
A: [2020-01-16T06:34:43.388537020Z INFO  solana_sys_tuner] Sending tuning request
# Validator A's first vote
A: [2020-01-16T06:34:43.398356443Z INFO  solana_core::replay_stage] vote bank: ...
...
B: [2020-01-16T06:34:44.428502869Z INFO  solana_core::validator] creating bank...
...
A: [2020-01-16T06:34:47.416461319Z INFO  solana_core::cluster_info]
A:     IP Address        |Age(ms)| Node identifier                              |Gossip| TPU  |TPU fwd| TVU  |TVU fwd|Repair|Storage| RPC  |PubSub
A:     ------------------+-------+----------------------------------------------+------+------+-------+------+-------+------+-------+------+------
A:     127.0.0.1       me|  7504 | 9EYDJ4HDLYjLMqcZZCgVaE4Bu2LQVLAkBaLe1iHBju3C | 8001 | 8377 | 8886  | 9696 | 9262  | 8538 | none  | 8899 | 8900
A:     127.0.0.1         |  3080 | 7SgZJnxM7PSSE7PJ7BgPXdG1NH5sqxDDnNyiie5d1Aqg | 9544 | 9573 | 8828  | 8499 | 9453  | 9944 | none  | 8665 | 8666
A:     Nodes: 2
...
B: [2020-01-16T06:36:12.525457941Z INFO  solana_ledger::blockstore_processor] ledger processed in ...
B: [2020-01-16T06:36:12.525655627Z INFO  solana_core::rpc_service] rpc bound to V4(0.0.0.0:8665)
B: [2020-01-16T06:36:12.527238315Z INFO  solana_core::validator] Waiting for more than 66% of activated stake at slot 4962 to be in gossip...
B: [2020-01-16T06:36:12.527274832Z INFO  solana_core::validator] 49% of activated stake in gossip
B: [2020-01-16T06:36:13.527394159Z INFO  solana_core::validator] 100% of activated stake in gossip
B: [2020-01-16T06:36:13.527742150Z INFO  solana_sys_tuner] Sending tuning request
# Validator B's first vote
B: [2020-01-16T06:36:13.538678743Z INFO  solana_core::replay_stage] vote bank: ...
# inevitable forks...
```

Am I missing something? Does this not happen on your environment? I'm glad to explain further if needed! :)

> Delay gossip-ing until snapshot resumption is finished

Also notice that from the above log, validator B starts to advertise to RPC port well before listening, too. So I proposed this quoted one as a solution, too.

**Comment by ryoqun** [comment]
@mvines Wait wait, this could cause a restart failure for the SLP and indeed in the past. I thought this is only problematic for very small number of staked validators (around 2~3). Because not waiting for lastly joined validator isn't significant under the large number of other validators.

This is wrong:

_What if every validators are running with `--wait-for-supermajority`? Even lack of 1 % could cause consensus lost for such an barely staked (around 66%) infant cluster. ;)_

So, we should also add some head room stake (say, wait for 75%), along side this?

**Comment by mvines** [comment]
Oh darn, so this "early gossip" is almost certainly due to https://github.com/solana-labs/solana/blob/787e36a28f2a0d29cd45fb18caabe3a98b5c115e/validator/src/main.rs#L192-L194

Where the validator jumps on gossip to find an RPC port to talk to.  I intentionally re-used the validator's pubkey during this process instead of an ephemeral pubkey to avoid an "extra" node jumping on gossip for a brief time.   However it looks like the bug is that the `get_rpc_addr()` temporary node also includes all the standard validator ports -- instead it could only provide a gossip port (no TPU) so that the other nodes waiting at `--wait-for-supermajority` would filter out the temporary node
