### ISSUE TITLE
Too easy to burn tokens

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#7787]
#### Problem

If a transaction references a system account that doesn't yet exist, the runtime creates one automatically. The "feature" introduces two problems:
1. A transfer to a public key with a typo will succeed, effectively burning all tokens by accident.
2. It's not available to arbitrary programs, which require a `space` parameter. Consequently, we see `CreateAccount` being used with an unused `from` key and zero `lamports`, suggesting `CreateAccount` is doing too much. It's an `Allocate` and a `Transfer`, when only an `Allocate` is needed.

#### Proposed Solution

* Remove the automatic account creation feature.
* Add new instruction `Allocate`, which should be the same as `CreateAccount`, but with no `from` or `lamports` parameters. Consider removing `CreateAccount`.

cc: @rob-solana @aeyakovenko

**Comment by aeyakovenko** [comment]
> Remove the automatic account creation feature.

This isn't super workable though.  You can't automatically create spending addresses without pre-registration.  

To solve 1, Bitcoin and other protocols use a checksum.

**Comment by vpontis** [comment]
@aeyakovenko were checksums introduced into Solana? I Googled "Solana checksum" and this was the first relevant post. 

What's the best way of confirming that an address is a valid Solana address?

**Comment by vstoykovbg** [comment]
> A transfer to a public key with a typo will succeed, effectively burning all tokens by accident.

This is shocking. Solana addresses do not have a checksum (like other cryptocurrencies)?
