### ISSUE TITLE
solana-install init doesn't know when there's know work to do

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#7788]
#### Problem

solana-install init doesn't know when there's know work to do.

Does a bunch of work:
```bash
solana-install init beta
```

Does the same work again:
```bash
solana-install init beta
```

#### Proposed Solution

Detect when there's no work to do and tell the user that they are already up-to-date.

**Comment by mvines** [comment]
This is the case when a named version is used, eg. `solana-install init 0.22.2`.  For a release channel (edge/beta/stable), this issue is the case though.  It doesn't attempt to first check if the latest build for the given release channel is what's currently installed.
