### ISSUE TITLE
Upgrade to CUDA 10.2

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#7815]
#### Problem

Cuda 10.2 is released, so we should support cuda 10.2 and 10.1 in the releases.

#### Proposed Solution

Change to cuda 10.2 and 10.1

**Comment by sakridge** [comment]
cc @danpaul000 @mvines

**Comment by sakridge** [comment]
As a workaround can symlink /usr/local/cuda-10.2 to 10.1 as so: `sudo ln -s /usr/local/cuda-10.2 /usr/local/cuda-10.1` if one has the driver installed from the nvidia runfile. Or use `CUDA_HOME` env variable #7813 is in.

**Comment by mvines** [comment]
It really sucks to have to upgrade all the CI machines to include CUDA 10.2, a docker-based solution would make future CUDA upgrades so much easier

**Comment by sakridge** [comment]
Is it not just updating an image and then rebooting the machines with that image?

**Comment by mvines** [comment]
yes for each machine.
