### ISSUE TITLE
Make cli commands support emitting JSON

### ISSUE THREAD

**Issue by xtrapower** [solana-labs/solana#7827]
#### Problem

We have been working on a [Solana validator dashboard ](https://stakingfacilities.com/solana-validators). To offer more insights we would like to integrate information provided by cli commands like `solana validator-info get` and `solana show-block-production`. It would be extremely helpful if cli commands would support emitting JSON.

#### Proposed Solution

Add a `--json` flag to cli commands that allow programmatic access by outputting JSON.

**Comment by garious** [comment]
How about using curl and the JSON RPC APIs?  https://docs.solana.com/book/api-reference/jsonrpc-api

**Comment by xtrapower** [comment]
@garious We already pull out everything we can via JSON RPC but there are quite a few methods only available via cli such as `solana validator-info get` and `solana show-block-production`

**Comment by garious** [comment]
Okay, I see that those commands do a fair amount of client-side processing that you wouldn't want to duplicate.

@CriesofCarrots, want this one?

**Comment by CriesofCarrots** [comment]
> want this one?

Heck yeah, I do! @garious

**Comment by xtrapower** [comment]
@CriesofCarrots Hi there, is this still upcoming? As mainnet approaches this would help a great deal in extracting information from local nodes programmatically. Thanks!

**Comment by CriesofCarrots** [comment]
@xtrapower , thanks for following up! This got shelved for a bit, but I am going to see if I can squeeze it in sometime in the next week or so.

**Comment by xtrapower** [comment]
@CriesofCarrots Sorry to bother you, I'm just checking in to see when you might find the time to implement this? Thanks!

**Comment by CriesofCarrots** [comment]
@xtrapower , I actually played around with this a little this weekend. If this week isn't too crazy, I should be able to get something landed in the next couple days.

**Comment by CriesofCarrots** [comment]
@xtrapower , this is going in to v1.1 (https://github.com/solana-labs/solana/pull/9495), so it should be available on testnet after our next patch release, and available on mainnet-beta when we move to v1.1 at the end of the month.

New cli options: `--output json` (pretty) and `--output json-compact`
The output option doesn't yet affect all subcommands, but does handle the 2 you were interested in, plus others that have complex return data or are processing-heavy. Please let me know if you have any feedback.
