### ISSUE TITLE
Demo request: leader pays for transaction fee

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#7836]
#### Problem

With Nonce accounts clients can sign a transaction that is executed once and which results in a deposit into the spending account.

This means that clients can propose transactions that can be payed for once and only once by any leader that is willing to include it in a block.  The leader can compute the “tip”, the difference between the deposit and the fee, and sign the transaction if the tip is high enough.

#### Proposed Solution

Implement the demo and documentation for the sdk.

Additional changes to the runtime are necessary for the leader to have a guarantee that the transaction is encoded iff it is  successful.  This could be implemented as an error code for any transaction that fail if they are signed by the leader in the banking stage.  The banking stage would drop transactions with that error code.

Even though this requires the leader to precompute the state before including the transaction, it wont interfere with the bankless leader design.

tag: @garious @t-nelson @jackcmay @jstarry @CriesofCarrots @mvines @rob-solana

**Comment by garious** [comment]
The problem isn't clear to me. Why do you want the leader to pay the fee? Maybe the deposit is not a native token?

**Comment by aeyakovenko** [comment]
@garious Correct, that’s the primary usecase I am thinking of.

Users that hold a Solana DAI can pay for the transaction in DAI to the leader.

**Comment by aeyakovenko** [comment]
Hmm, won’t work yet.  The user needs to sign of on the DAI transfer prior to knowing the leaders pubkey.  So we need signatures that cover parts of the transaction
