### ISSUE TITLE
WouldBlock error are bursted (possibly wasted/worsening retries) under high network load

### ISSUE THREAD

**Issue by ryoqun** [solana-labs/solana#7840]
#### Problem

Under high network load hitting system limits of socket buffers, `WouldBlock` error occurs because `solana-validator` process can't write data anymore into the kernel's socket buffer.

To reproduce, just saturate the local network like starting adhoc non-voting validators with `--no-snapshot-fetch`.

Errors:

- `WARN  solana_core::streamer] gossip responder error: IO(Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" })`
- `INFO  solana_core::repair_service] repair req send_to(XXX.XXX.XXX.XXX:XXX) error Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }`

Note that this actually occurred on some real machines while Rampy hitting the TdS.

#### Proposed Solution

Audit call sites to ensure there is no wasted retry or retransmission, which could exaggerate the network congestion further. Under load, do exponential increasing timeout or similar measure like ordinary tcp congestion.
Then, handle to ignore the specific error, instead of vomiting lots of logs, which could also cause the whole process (not the writing thread only; remember all threads are sharing a log; or each are buffered?) to be blocked due to log file descriptors possibly blocking write (depends on unix socket (systemd), stdout pipe, plain old file, though).

Also, ensure socket buffer size (is this done normally executed as a production environment?)

#### background

Side product of #7736

**Comment by sakridge** [comment]
ok; we update the udp buffer sizes if the user is running sys-tuner in sudo. I wonder if this validator wasn't running that.

**Comment by sakridge** [comment]
https://docs.solana.com/book/v/master/running-validator/validator-start#tune-system

**Comment by mvines** [comment]
@sakridge - that's what I was thinking too.
