### ISSUE TITLE
Avoid special-cased shred_version == 0 to prevent an odd behavior

### ISSUE THREAD

**Issue by ryoqun** [solana-labs/solana#7857]
#### Problem

In a rare occurrences (1 in 2^16 genesis hashes), shred_version can become 0. If shred_version is `0`, it's special cased as _uninitialized_ in code base like [this](https://github.com/solana-labs/solana/commit/e6af4511a8ad22eeba73339ddee54dc05931e5a6#diff-9555ee311227eb057466b72b0222ee8cR89).

This surely will curse us manifested as the mysterious CI mood thing..

Also, in a super unlucky situation, this could happen on the mainnet genesis. ;p

#### Proposed Solution

So, tweak `shred_version` derivation like this a bit like this?:

```patch
diff --git a/ledger/src/shred.rs b/ledger/src/shred.rs
index 59170d2e0..4097d97b1 100644
--- a/ledger/src/shred.rs
+++ b/ledger/src/shred.rs
@@ -394,15 +394,20 @@ impl Shred {
 
     pub fn version_from_hash(hash: &Hash) -> u16 {
         let hash = hash.as_ref();
-        let mut accum = [0u8; 2];
-        hash.chunks(2).for_each(|seed| {
+        let mut accum = [0u8; 4];
+        hash.chunks(4).for_each(|seed| {
             accum
                 .iter_mut()
                 .zip(seed)
                 .for_each(|(accum, seed)| *accum ^= *seed)
         });
-        // convert accum into a u16
-        ((accum[0] as u16) << 8) | accum[1] as u16
+        // convert accum into a u16, while preventing special-cased 0
+        let mut version = 0, i = 0;
+        while (vervion == 0) {
+            version ^= v((accum[i] as u16) << 8) | accum[i + 1] as u16;
+            i += 2
+        }
+        version
     }
 }
```

**Comment by ryoqun** [comment]
@mvines @sagar-solana I'd like to hear your thoughts as relevant authors. :)

**Comment by sagar-solana** [comment]
That's a good point. I see what you're going for. The while loop looks a bit misleading at first but otherwise it's okay. I think it's a valid case that we should be careful about.

**Comment by mvines** [comment]
Nice, I was bothered by the possibility of a 0 shred version

**Comment by mvines** [comment]
I'd probably just go for a more simple:
```rust
if version = 0 {
  1
} else {
  version
}
```
