### ISSUE TITLE
`solana show-validators` is missing information about stake that's warming up

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#7864]
When new stake is delegated to a validator  it's confusing that `solana show-validators` makes no reference to that stake until the next epoch.  And even at the next epoch, `solana show-validators` doesn't show the amount of per-validator stake that is still warming up or cooling down.

Also note that `solana show-stake-history` shows stake warmup/cooldown for the entire cluster, but gives no per-validator breakdown.

Consider improving `solana show-validators` by adding these new columns to display the missing per-validator stake warmup/cooldown information.   This will likely require new RPC APIs.

**Comment by CriesofCarrots** [comment]
@t-nelson , I think this is still an issue, isn't it? #10260 didn't change anything in `solana validators`

**Comment by t-nelson** [comment]
Whoops!  Yep, I misremembered this one being for `solana stakes`. Nice catch!
