### ISSUE TITLE
Recover the good parts of "Generate MAX_DATA_SHREDS_PER_FEC_BLOCK coding shreds for each FEC block"

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#7902]
#7474 was reverted for contributing to a bandwidth usage spike on the idling SLP 1.1 cluster.  Let's re-assess this fix and consider which parts of it we want to keep, if any, while avoiding the bandwidth usage concern.

**Comment by pgarg66** [comment]
We can limit the conditions for generating `MAX_DATA_SHREDS_PER_FEC_BLOCK` coding shreds for FEC blocks with less number of data shreds. For example,

- The shreds generated from a `Vec<Entry>` got split into multiple FEC blocks. The current FEC block contains a part (most likely, tail) of the shred set.

Any thoughts? @carllin, @sagar-solana
