### ISSUE TITLE
Durable nonce transactions have an effectively unpredictable fee schedule

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#7967]
#### Problem

A typical transaction is charged fees based on the value of its `recent_blockhash` field.  The `FeeCalculator` and corresponding blockhash are stored in the working bank's `RecentBlockhashQueue`.  Since a durable nonce transaction's `recent_blockhash` is necessarily no longer in the bank's `RecentBlockhashQueue` the initial implementation simply takes the `FeeCalculator` of the working bank's `last_blockhash`.  This introduces unpredictablity should the fee schedule move significantly between the transaction being created and submitted to the network, which is not ideal.

#### Proposed Solution

1. Store the fee calculator with the account's metadata.  This may incentivize stocking up on low-fee nonce accounts for use in the event of high fees.
1. Leave it as is and accept this inconsistency as a cost of using durable nonces

tag: @garious @rob-solana @mvines

**Comment by garious** [comment]
It's gotta be proposal 1. If that attack is economical, we should rethink our fee structure.

**Comment by rob-solana** [comment]
2. would be my preference

fees shouldn't change that much in the time it takes to turn around offline signature generation

**Comment by t-nelson** [comment]
@mvines 
A few things of note.  Storing `FeeCalculator`s as proposed by 1) will require the network signature rate tracking portion being broken out to a separate data structure such that we're only storing what's necessary to calculate fees for a transaction (`lamports_per_signature` and maybe `burn_percent`).  This will break RPC where we're (unnecessarily) returning the whole shebang now.  The `RecentBlockhashes` sysvar will need the `FeeCalculator` state stored alongside (ABI breakage). And Nonce accounts will also need to store said state (more ABI breakage).

**Comment by mvines** [comment]
Thanks for the heads up.   Breaking RPC is not super concerning.   We really should get these ABI changes into v0.23 in the next couple weeks or it's going to be so much more pain.

@carllin is already working on rewrite of the TdS ledger for some Vote account ABI changes he's making, you should get in on that action to make these changes as well.

Let's turn the Nonce accounts into an enum at the same time, like @carllin is doing with Vote, so we have a way to roll out new ABI changes in a less painful way in the future.

Suggested path:
1. Drop everything, get the ABI changes landed in master ASAP and add the corresponding PRs to https://github.com/solana-labs/solana/projects/45 for tracking the backport to 1.0 and 0.23
2. Jump on @carllin's TdS ledger rewrite

**Comment by mvines** [comment]
I just used `solana-ledger-tool print-accounts` to dump all the current TdS accounts and I don't think I saw any nonce accounts (or maybe I missed one).   But basically the number of real nonce accounts that we current care about is 0 or close to 0, so I think if we're quick we can just sneak this ABI change in without a ledger rewrite

**Comment by t-nelson** [comment]
On it!

**Comment by t-nelson** [comment]
Nice try :robot: ...
