### ISSUE TITLE
CUDA fails to load with v0.22.4 release and CUDA 10.1

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#7975]
#### Problem

From `Pete - LunaNova` on Discord:

Starting a validator with the v0.22.4 release binaries and only CUDA 10.1 libraries installed results in
```
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.                           
[2020-01-25T14:25:38.829843865Z ERROR solana_metrics::metrics] datapoint: panic program="validator" threa
d="solana-receiver" one=1i message="panicked at 'cudaHostRegister error: 35 ptr: 0x7efe93615b80 bytes: 33
3824', perf/src/cuda_runtime.rs:33:17" location="perf/src/cuda_runtime.rs:33:17" 
```

From the CUDA docs
```
cudaErrorInsufficientDriver = 35
    This indicates that the installed NVIDIA CUDA driver is older than the CUDA runtime library. This is not a supported configuration. Users should install an updated NVIDIA display driver to allow the application to run.
```

I tried to start a validator with this release on colo and it chose the CUDA 10.0 installation.

Upgrading to CUDA 10.2 solved the issue for Pete.

#### Proposed Solution

Investigate and fix

tag @sakridge @mvines

**Comment by mvines** [comment]
Nobody seems to be stumbling over this anymore, when it reoccurs we can reopen but for now it's not actionable
