### ISSUE TITLE
SLP 1.1 bootstrap validator forked off from everybody after root 1535564

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#8086]
SLP 1.1 bootstrap validator (bsv) went delinquent last night.

After slot 1535575, everybody else went to 1535576 while bsv went to 1535592 and stayed there.  See [s-1536500.pdf](https://github.com/solana-labs/solana/files/4144821/s-1536500.pdf)

Metric snapshot of the event: https://metrics.solana.com:3000/dashboard/snapshot/W8puFQvCIAswsrtL3KIEDS9LKvtCYOgS

Full ledger and logs in /home/mvines/slp-flatline-1535564 on pacman

**Comment by sakridge** [comment]
@mvines can you add a+r perms on pacman@/home/mvines/slp-flatline

**Comment by mvines** [comment]
Done!

**Comment by aeyakovenko** [comment]
@sakridge i am looking at https://github.com/solana-labs/solana/pull/7972/files as the possible culprit.  

Why don’t we just check if nth vote slot is greater post new vote?  If it’s not, the check should pass.  Otherwise if the nth vote is higher then we should check threshold.

**Comment by sakridge** [comment]
I suppose we can, seemed more thorough to see if anything < lockout was changed in case the lockout modification logic was changed. It would just be an optimization, no?

**Comment by t-nelson** [comment]
Another data point: The rack seems to have lost connectivity around this time (US Mountain).  I'm not sure of the resolution of these metrics since its from a polled cloud appliance.  @danpaul000 is going to follow up with the DC/ISP and see if we can get any more info

![outage](https://user-images.githubusercontent.com/490004/73676308-6a7c4800-4671-11ea-91b4-2d146d5498b6.png)

**Comment by danpaul000** [comment]
> Another data point: The rack seems to have lost connectivity around this time (US Mountain). I'm not sure of the resolution of these metrics since its from a polled cloud appliance. @danpaul000 is going to follow up with the DC/ISP and see if we can get any more info
> 
> ![outage](https://user-images.githubusercontent.com/490004/73676308-6a7c4800-4671-11ea-91b4-2d146d5498b6.png)

For posterity, this outage was confirmed to be an infrastructure issue with one of our ISPs, not related to any of our equipment.
