### ISSUE TITLE
Derived-addresses can cause loss of account control

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#8123]
#### Problem

Assigning a derived-address to a role that requires signing will cause loss of control over that role's faculties since there is no associated private key to sign with.

#### Proposed Solution

Risk analysis
Fix what's deemed dangerous, document what isn't
Probably at least guard against `program_id == system_progrem::id()`

tag: @aeyakovenko @rob-solana @mvines

**Comment by mvines** [comment]
> Probably at least guard program_id == system_progrem::id()

Opposite right?  A derived address cannot be assigned to the system program?

**Comment by t-nelson** [comment]
Yup! Forgot a word... fixed now

**Comment by rob-solana** [comment]
putting this simple guard in `solana_sdk::system_instruction::create_address_with_seed` (which already returns a `Result<>`) is probably a 99% solution.
