### ISSUE TITLE
tds.solana.com OOMs shortly after starting

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#8131]
The solana-validator process on tds.solana.com is in a death loop whereby it starts up, uses all RAM, gets killed, and retries.

Debug, fix.

**Comment by mvines** [comment]
Issue still reproduces after removing `--rpc-port 8899`, so it's not the RPC subsystem

**Comment by mvines** [comment]
This should be resolved by the gossip message ingestion limits added in v0.23.3

**Comment by mvines** [comment]
Fixed

**Comment by hufengvia** [comment]
> Fixed

how to fix ?
