### ISSUE TITLE
Cleanup readme

### ISSUE THREAD

**Issue by ghost** [solana-labs/solana#8177]
> Furthermore nothing in this project constitutes a solicitation for investment.

This, and many other writings, do not belong into the Readme.

Focus on usual stuff, compact.

>Before you jump into the code, review the online book Solana: Blockchain Rebuilt for Scale.

no! provide an archetuctaral overview diagram to llok at, and point to it from the readme.

**Comment by garious** [comment]
Regulations around crypto are fuzzy at best. We'll continue to follow the advice of our legal team and navigate the space conservatively.

Regarding the architectural diagram, we can add that, but it won't get you too far. What's implemented here is complex. Sounds like you came to this project looking for particular information. What is that? The novel tech? Check out Proof of History.

**Comment by lazaridiscom** [comment]
You are the first (or 20? ) projects to have such an "overcrowded" readme, and a legal disclaimer.

Anyways, I just came to get a feeling of the codebase, and possibly to try a build. nothing more.

Your readme needs to be reduced, it's scary. Remove the "Introduction" etc., go straight to the "Build from Source" point. Install from binaries is stuff for the manual (just link to it).

> What's implemented here is complex.

It is not.

> Check out Proof of History.

went already through it, sounds really nice.

**Comment by lazaridiscom** [comment]
(note that the "readme-problem" is a general one, see e.g. 
* https://github.com/kadena-io/chainweb-node/issues/905 and 
* https://gitlab.com/tezos/tezos/issues/674)

**Comment by lazaridiscom** [comment]
some steps: #8735, #8748
