### ISSUE TITLE
Consider grouping directories

### ISSUE THREAD

**Issue by lazaridiscom** [solana-labs/solana#8178]
Around 50 root directories seems a bit much.

Consider moving some into 2nd level grouping directories.

**Comment by garious** [comment]
Thanks for the suggestion, but the flat structure works well for us. Don't attempt to learn the codebase by clicking through directories. Instead use the book and then a good IDE from there

**Comment by lazaridiscom** [comment]
There is something called "System Design Principles", and the team should follow it.

"flat structure" is not a 

> Don't attempt to learn the codebase by clicking through directories. Instead use the book and then a good IDE from there

Why would I do that? I would prefer to restructure your source-code (for me personally), following system-design-principles, and continue a code-base teach-in, simply because this is my prefered way.

No need to discuss, my understanding is that you say:

"Flat Structure is Good"

I say

"Flat Structure violates System-Design-Principles"

and I close this.
