### ISSUE TITLE
Simplify latest Stable checkout

### ISSUE THREAD

**Issue by lazaridiscom** [solana-labs/solana#8179]
#### Problem

https://docs.solana.com/book/apps/tictactoe#build-and-run-tic-tac-toe-locally

```
$ TAG=$(git describe --tags $(git rev-list --tags
--max-count=1))
$ git checkout $TAG
```

#### Proposed Solution

Provide a `Stable` branch

Re "Stable" branch (contains diagram):

* https://gist.github.com/digitaljhelms/4287848

<img src="https://camo.githubusercontent.com/f011896cab0a6e086954a10d3a5132d57ca69468/687474703a2f2f662e636c2e6c792f6974656d732f3369315a336e3154316b3339327231413351306d2f676974666c6f772d6d6f64656c2e3030312e706e67">

**Comment by garious** [comment]
Thanks for the suggestion, but we already have release branches. solana-install also has stable, beta and edge channels, which is inspired by the Chrome release process.  As for the example repos, there's no formal release process because those 2 lines of Bash meet our immediate needs. Solana generally follows Agile-like processes and avoids over-architecture like its a plague. Hence, for example, no sharding.

**Comment by lazaridiscom** [comment]
You don't need to justify the unjustifiable.

**Comment by lazaridiscom** [comment]
Just saw this piece again, in another document:

```sh
$ TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
$ git checkout $TAG
```

really annoying, and does not work on Win, so one needs to lookup manually.

You don't need to change your process very much, its just a tiny additional step when you create the latest release, fully backwards-compatible (e.g. does not break existent ci)

=> copy the master branch to the stable branch

Then, users can simply checkout the stable branch to get the latest stable code.

**Comment by mvines** [comment]
The problem with a stable branch like this is that it requires a history rewrite on every release.  I've used this in past projects and it's not very nice.  A unique branch for each release line (0.23, 0.22, 0.21) and tags for each patch release on that release line works well for us.

`$ git checkout 0.23.2` seems pretty painless to checkout the 0.23.2 release.   The `TAG=` stuff is unnecessary

**Comment by lazaridiscom** [comment]
(it is quite discouraging to see issues closed in that way, e.g. "comment and close", without awaiting any further reply).

> works well for us

No, it does not, because you are forcing (code-repo) users to lookup the latest release manually.

This issue is about **Simplify latest Stable checkout**, and there are other solutions besides a branch, so yo should reopen the issue.

**Comment by lazaridiscom** [comment]
> `$ git checkout 0.23.2` seems pretty painless to checkout the 0.23.2 release.

you cannot permanently update the documentation to latest-release, neither can you ask users to lookup the latest release.

**Comment by garious** [comment]
@lazaridiscom, we're good with the current approach. If you'd like to change that Bash code to something that works on Windows, patches welcome.

**Comment by lazaridiscom** [comment]
Nah, only amateurs bombard users with scripts, so, resting my case here.

**Comment by garious** [comment]
@lazaridiscom, just so we're crystal clear here, you just called us amateurs, right?

**Comment by lazaridiscom** [comment]
(we're moving farther and farther away from the essence, which is DX)

I called myself a "DX-non-amateur", who refuses to use scripts instead of more convenient/cross-platform constructs with "tool quality".

As for you, you're most possibly "Professionals in an Activity Trap" (e.g. busy with core-work, thus neglecting UX/DX details).

Now, me out (though I really think you should reopen this, thus someone looks in the future at this).
