### ISSUE TITLE
Provide "Edge and Beta Channel Overview"

### ISSUE THREAD

**Issue by ghost** [solana-labs/solana#8181]
(related: #8177)

#### Problem

The "Edge and Beta Channel Binaries Overview" is within the README, increasing its size unnecessarily.

Additionally, this information is needed in other places, too, e.g. within documentation like "node-operator-manual".

#### Proposed Solution

* Move this out to a dedicated place (the published documentation which is most relevant for this, like "user-manual" or "node-operator-manual" ...)
* Place a link into the README

**Comment by lazaridiscom** [comment]
#8685, where was this moved to?

**Comment by garious** [comment]
We can revive those docs at any time, but currently don't have a need for that flexibility.
