### ISSUE TITLE
ERROR: Unable to increase the maximum open file descriptor limit to 65000

### ISSUE THREAD

**Issue by ghost** [solana-labs/solana#8183]
## System

Win10 Pro Hyper-V ubuntu 18.04

## Problem

A tiny problem, possibly related to Hyper-V

```sh
Running target/release/deps/solana_chacha-e1ac2c0a7a950f57

running 1 test
[2020-02-09T11:53:20.997346475Z ERROR solana_ledger::blockstore] Unable to increase the maximum open file descriptor limit to 65000
```

the error occurs again and again within several tests.

## Reproduction

on Win10, Hyper-V ubuntu 18.04

```sh
cargo build --release
cargo test --release
```

## Bug

The current code does not verify the `rlim_max` value, see added debug info at end of error-message:

```sh
[2020-02-09T13:15:18.573989543Z ERROR solana_ledger::blockstore] X Unable to increase the maximum open file descriptor limit to 65000, current 1024, max 4096
```

Dummy code for possible fix:

```rust
if nofile.rlim_max < desired_nofile
{
    error!
    (
        "You may need to increase maximum open files on your system to 65536, current maximum {}. See link-xyz for further info", nofile.rlim_max
    );
}
```

## Workaround

```sh
sudo echo 'DefaultLimitNOFILE=65535' >> /etc/systemd/user.conf
sudo echo 'DefaultLimitNOFILE=65535' >> /etc/systemd/system.conf
sudo echo '* soft nofile 65535' >> /etc/security/limits.conf
sudo echo '* hard nofile 65535' >> /etc/security/limits.conf
reboot
```

extracted from: https://superuser.com/a/1200818

.

**Comment by lazaridiscom** [comment]
This issue is actionable (e.g. anyone, including simple contributors) can take immediately some action based on the information provided.

So, parking it simply to "the future" without any labeling... this does not seem like the most efficient process.

**Comment by mvines** [comment]
Hi @lazaridiscom, "the future" is exactly the right milestone, which is for actionable but not immediately blocking issues.

**Comment by lazaridiscom** [comment]
>  is exactly the right milestone

naturally, if you ignore completely ux/dx.

> actionable but not immediately blocking issues.

"actionable", as in "ready for action" like in "already analyzed".

E.g add a 'good first issue' or similar.
