### ISSUE TITLE
ledger error types

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#822]
PR #817 introduces a random access ledger with io::Error return results...

to improve ergonomics, consider giving ledger its own errors, look into error_chain across the board for solana, or make ledger able to return multiple types of errors...

**Comment by garious** [comment]
Update: DbLedger now has its own error type, but that module is still making heavy use of `io::Error` with strings.

**Comment by mvines** [comment]
Seems pretty stale, re-open with more details if not
