### ISSUE TITLE
"Client" keypair file is required to exist for operations that don't use it

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#8253]
#### Problem
A keypair file must exist either in `solana config get keypair` or with `-k/--keypair` for subcommands `transfer`, `pay` and `delegate-stake`, and possibly others, even when all the uses of that file for the given subcommand are explicitly over-ridden with optional flags `--from` and `--fee-payer`

In offline signing environments, there will presumably only be a limited number of keypair files exposed at signing time so the current workaround of adding a dummy no-op file (`solana-keygen new -o dummy.json ; solana config set -k dummy.json`) to get that command to work is most undesirable.  One could also set one of the offline keypair files in `solana config set keypair`, but this leaves a payment/transfer command with some ambiguity.

#### Proposed Solution
Set `requires_keypair` to `false` for these subcommands.  First check if the override flags are set, then look for `--keypair` or config default keypair, then if there is no default/provided client keypair, error out with which functionality/flag is blocked by its absence.

Ideally, we would get rid of a "default client keypair" altogether, as this would allow someone holding multiple online keypairs to quickly and easily send a transfer from the incorrect paying account.

**Comment by t-nelson** [comment]
I think the first part of the proposal is sane.  Would like some more opinions about the second part

tag: @CriesofCarrots for ergonomics, @mvines for sanity

**Comment by CriesofCarrots** [comment]
Most of this issue is resolved by #8398 
The default keypair option is still around (for convenience when using a single signer/fee-payer), but it needn't exist when signers are provided explicitly.

> error out with which functionality/flag is blocked by its absence.
^ This still needs implementation
