### ISSUE TITLE
Units passed as an optional argument instead, adding complexity

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#8279]
#### Problem

Optional argument in CLI introduces unnecessary implementation complexity:

```
$ solana transfer $TO 42 SOL
```

#### Proposed Solution

Require quotes if the user wants to specify units:

```
$ solana transfer $TO "42 SOL"
```

And otherwise, just don't specify units, which continues to imply SOL:

```
$ solana transfer $TO 42
```

**Comment by garious** [comment]
Note: here's an example of where the complexity of `50 lamports` instead of `"50 lamports"` starts to make things brittle. https://github.com/solana-labs/solana/pull/8291/files#diff-6897771877027eaa520b55b24b6dceafR2487

**Comment by lazaridiscom** [comment]
DX has priority over "convenience of implementation".

The `"42 SOL"` should be avoided.

**Comment by garious** [comment]
DX is far worse when the implementation doesn't do what the user thinks it should do because implementation complexity was dismissed.

**Comment by lazaridiscom** [comment]
I don't know what you're talking about.

Main issue is: avoid `" "` within cli, let the folks type freely.

## Personal Preference

(ask 20 users, you'll get ~17 different preferences)

`solana send SOL42 to $TARGET`

**Comment by garious** [comment]
20/20 users will type 42

**Comment by lazaridiscom** [comment]
I meant the whole command, which I understood needs to contain "SOL".

**Comment by garious** [comment]
SOL is currently an optional, extra argument

**Comment by garious** [comment]
Thanks @lazaridiscom, your confusion led me to a better solution: https://github.com/solana-labs/solana/issues/8296
