### ISSUE TITLE
CLI exposes implementation detail "lamports"

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#8296]
#### Problem

The CLI was originally written using all lamports, and then later, we added support for SOL. Now there's this fundamentally unnecessary option disambiguate between lamports and SOL, which is done by adding an argument with the text "lamports" or "SOL". That optional argument adds awkward edge cases, like, what happens if "SOL" is valid input for the next argument?  Also, by retaining support for "lamports", we need to document it. Why brand 2 terms when 1 will suffice?

#### Proposed Solution

Remove support for "lamports" and remove support for specifying units.

cc: @CriesofCarrots

**Comment by mvines** [comment]
👍 Especially with base10 lamports now, this is much easier!
`solana pay 0.000000001` works just as well as `solana pay 1 lamport`

**Comment by CriesofCarrots** [comment]
I did run into some errors with https://github.com/solana-labs/solana/pull/8291 in release build, so I'm going to move forward fixing this since it will resolve that issue as well.
