### ISSUE TITLE
Snapshots are not verified, and validators have no way of knowing if their state is  malicously corrupted.

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#8305]
#### Problem

Our xor bank hash is not secure against manipulation and validators have to trust the snapshot that they download to be correct even if the hash matches.

#### Proposed Solution

1. every 5000 slots validators sign the full snapshot.
   1. copy all the accounts into a separate directory
   2. hash and sign the entire state
2. broadcast the signature in gossip
3. HALT if 1/3+ disagree on the signature

new validator follow this boot procedure: 
1. Download N snapshots from different validators.  Verify they are all the same.  (Hash the full state)
2. boot with a ephemeral key as a vote state with a random snapshot
3. run until the validator generates a snapshot signature and signs it
4.  if the 2/3+ agree on the signature (validator doesn't HALT), reboot with the real key

Question:
1. Can N be 1 for downloads?  Validator just need to check against N signatures in gossip after it catches up to a verified snapshot.  I think all we need is N trusted identities on the network that can bootstrap the state.  Maybe we can pass those in as command line arguments.

tag: @sakridge @mvines

**Comment by garious** [comment]
cc @t-nelson
