### ISSUE TITLE
[PROJECT] Ordering and Completeness of Milestone Overview

### ISSUE THREAD

**Issue by lazaridiscom** [solana-labs/solana#8309]
#### Problem

Newcomers should be able to get an immediate overview of the project, including its milestones.

#### Proposed Solution

As for the milestones:

https://github.com/solana-labs/solana/milestones

* Add a date like 2025-12-31 to "The Future" milestone, so it's ordered correctly
  * https://github.com/solana-labs/solana/milestone/15
* Add the mentioned  "Mainnet MVP" milestone with an estimated date
* Add any other milestones currently known (example: Mainnet 1.0 / Mainnet 2.0 ??? )

**Comment by lazaridiscom** [comment]
@mvines , do you actually read the issues?

At minimum, add a date to "The Future" milestone, so it orders correctly.

**Comment by mvines** [comment]
Yes I do read all the issues.  

Perhaps I will have the pleasure of introducing you to this nifty Github feature:
![image](https://user-images.githubusercontent.com/1281082/75008778-21c8db00-5436-11ea-9919-2cacf7971358.png)

**Comment by lazaridiscom** [comment]
> Perhaps I will have the pleasure of introducing you to this nifty Github feature:

Oh my...

The milestone-sorting feature works now(!), after(!) someone had added the date to the milestone (e.g. reacted to the issue I filed), without(!) mentioning it here.

So, I asked "**Add a date like 2025-12-31 to "The Future" milestone, so it's ordered correctly** ", which was fulfilled.

Assuming that you will not add "Mainnet MVP", so, closing.
