### ISSUE TITLE
Cargo version increment script is over-zealous in text replacement

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#8396]
#### Problem
`scripts/increment_cargo_version.sh` needs a bit more discipline now that we are on branch 1.0.  Running a minor version update from 1.0 to 1.1 found and replaced a lot of non-version related text in the repo.  "Open ports 8000-10000" became something like "ports 8000-1.1.0"

#### Proposed Solution
Tighten up what we look for to replace version strings only, not any numerical match.

**Comment by mvines** [comment]
😆 https://github.com/solana-labs/solana/commit/2d0f4b5c8cbc881967b492a376c9e973dbeee2d0#diff-6a3371457528722a734f3c51d9238c13R48

**Comment by danpaul000** [comment]
Thanks!
