### ISSUE TITLE
Add rollback support to accountant

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#84]
First some background. The accountant currently maintains two hash tables, a map of public keys to balances, and a map of pending transaction IDs (signatures) to spending plans:

```rust
pub struct Accountant {
    balances: HashMap<PublicKey, i64>,
    pending: HashMap<Signature, Plan>,
}
```

When a new transaction enters the system, here's what happens:

1. The `from` balance is updated (`balances[txn.from] -= txn.tokens`)
2. The transaction is placed in the `pending` map and will wait for any witnesses its spending plan requires.

Once the it has the needed witnesses and the spending plan is reduced to a `Payment`, it is removed from the map and `balances` is updated (`balances[payment.to] += payment.tokens`).

The problem here is that we're making updates to both `balances` and `pending` before the transaction has been finalized. Instead, the Accountant state should be broken up into at least two pieces, a *finalized state* and at least one *unverified block state*. Note this is the first time we've used the term *block*. It means, "a set of transactions that are verified together." Also, we say "at least" so that the leader can optimistically start work on a second unverified block while the first has been submitted for verification. In fact, depending on how long verification takes, it's not unreasonable to imagine the Accountant maintaining a long queue of unverified blocks.

Once a block has been verified by at least 2/3 of the verifiers, the block state should be merged into the finalized state. We say the block state is *coalesced*. The reason to coalesce is to save memory and redundant computation, and it can only be done after the block has been finalized.

So what does it mean to support rollback? At a high-level, it means the system state rolls back to an earlier point in time. In this architecture, it means that unverified blocks and associated state are simply discarded and never coalesced.

**Comment by garious** [comment]
![consensus](https://user-images.githubusercontent.com/55449/38102118-88f3e172-333f-11e8-9e1d-59188b141768.png)

**Comment by garious** [comment]
Removed the v0.7.0 milestone because we came up with a simpler, albeit slower, mechanism for rollback described in #310. We can revisit this one a little later.

**Comment by rob-solana** [comment]
wow!  blast from the past.  covered in #1426
