### ISSUE TITLE
Snapshot state is not incorporated into the bank hash

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#8404]
#### Problem

The system would be more robust if the full accounts state as generated when creating a snapshot was incorporated into the voting bank hash. As of now, only the accounts delta state is used along with blockhash/signature count.

#### Proposed Solution

Since calculating the hash value of the full accounts set is very expensive, need to find a value of some number of slots where any validator would be able to calculate the hash.

On a TR 2950x machine with ssd, a full hash of 1m accounts takes around 130ms, 10m about 1.3s.

**Comment by sakridge** [comment]
I think we are delaying this for now in favor of checking trusted validators hash values over gossip to halt the network. @aeyakovenko should we close this? or mark for The Future?

**Comment by aeyakovenko** [comment]
Closed.  Not sure if we should ever do it
