### ISSUE TITLE
Limit extracted data size from genesis.tar.bz2 and snapshot.tar.bz2

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#8427]
As a DoS attack an RPC node could potentially serve up a genesis.tar.bz2 or snapshot.tar.bz2 that fills the disk of the victim validator, by building a file full of 0s or some other content that compresses very well.

**Comment by mvines** [comment]
@ryoqun - can you take this one please?

**Comment by ryoqun** [comment]
> @ryoqun - can you take this one please?

Sure!

I think this attack is one of [those zip bomb attacks](https://github.com/solana-labs/solana/issues/7167#issuecomment-560259723).

**Comment by ryoqun** [comment]
@sakridge I think this fix will be really tiny but it would mildly conflict with split multi-file snapshot download you're working on now?

**Comment by sakridge** [comment]
@ryoqun shouldn't be a problem, I think the conflict will be small.

**Comment by sakridge** [comment]
With the `--trusted-validator` feature limited snapshot fetch to certain nodes, maybe this is lower priority?

**Comment by mvines** [comment]
The tarballs are still downloaded from any rando RPC node, so they can still blow up the disk before the actual contents (genesis/snapshot hash) can be approved or rejected
