### ISSUE TITLE
Quickstart guides in docs

### ISSUE THREAD

**Issue by rajgokal** [solana-labs/solana#8438]
#### Problem
It's hard to know where to start in the documentation, but the website points to the docs everywhere

#### Proposed Solution
Quick start guide in docs (link out to quick starts for each of these)
Run a validator node: https://docs.solana.com/book/running-validator
Develop and app: [don’t really have one]
Integrate your app: [don’t really have one]
Contribute to core: [don’t really have one]
Learn the basics: https://docs.solana.com/book/cluster

**Comment by lazaridiscom** [comment]
@mvines , you should consider starting adding "category" labels to the issues (bug, docs etc.).
