### ISSUE TITLE
Rename book/ to docs/ 

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#8442]
People dislike the term book, the term docs sits better.  So:
1) Rename book/ to docs/
2) Move the TdS docs at https://docs.solana.com/tour-de-sol/ into docs/tour-de-sol
3) Update the gitbook configuration to move the content at https://docs.solana.com/book/ to https://docs.solana.com/

**Comment by jstarry** [comment]
@mvines Why do we want to move the TdS docs? Seems you are suggesting merging the two Gitbooks?

**Comment by mvines** [comment]
Yes, I'm suggesting we merge because otherwise https://docs.solana.com/ redirects to https://docs.solana.com/main/ to make room for the TdS docs at https://docs.solana.com/tour-de-sol/, since the TdS docs come from a separate git repo
