### ISSUE TITLE
solana-watchtower: post relevant watchtower log line to Discord when a validator is identified as failing the sanity test

### ISSUE THREAD

**Issue by Pete-LunaNova** [solana-labs/solana#8443]
The solana-watchtower log often contains some useful info about why a validator has failed the sanity test. It could help speed up responding to alerts if this log line was included when an alert is posted to Discord.

**Comment by HM999** [comment]
The way it works now, it just prints that error if anything fails... what would you expect it to do, if you ran it without the --validator-identity argument? Would you expect a line for each failing validator?

**Comment by mvines** [comment]
test

**Comment by Pete-LunaNova** [comment]
test2

**Comment by HM999** [comment]
testical

**Comment by mvines** [comment]
Fixed by https://github.com/solana-labs/solana/pull/8549
