### ISSUE TITLE
solana-watchtower: add support to post a "CLEARED" message to Discord whenever a validator has returned to a healthy state

### ISSUE THREAD

**Issue by Pete-LunaNova** [solana-labs/solana#8444]
During SLP1.1 I noticed that my validator could often fail a sanity test only for it to be declared healthy again during the next check a minute later. I suspect the likelihood of this occurring will decrease over time as more bugs are ironed out but it may be useful to have solana-watchtower post a "CLEARED" message to Discord whenever a validator has returned to a healthy state (so the on-call sysadmin knows that it is no longer an issue requiring urgent investigation).

**Comment by prographo** [comment]
It would need to store the state of the network and the state of each validator between intervals, to know if a previously delinquent validator because "cleared".

**Comment by HM999** [comment]
It would need to store the state of the network as a whole and the state of each validator between intervals, to know if a previously delinquent validator because "cleared".

**Comment by Pete-LunaNova** [comment]
> It would need to store the state of the network as a whole and the state of each validator between intervals, to know if a previously delinquent validator because "cleared".

If storing the state of the whole network may be too big an overhead, the option to produce "cleared" messages could be restricted to only being available when a single validator is being monitored with the  --validator-identity argument.
