### ISSUE TITLE
refactor validator windowing and write a unit test for windowing functions

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#857]
anatolyToday at 9:16 PM
@rwalker https://github.com/solana-labs/solana/pull/846/files#diff-15a88956858291e240d996faf826809cR377
GitHub
Prevent a node from overrunning it's receive window by pgarg66 · ...
The node drops blobs that will cause it to overrun window
The node does not ask to repair a blob that overruns the window

i am pretty sure i know why things fall over after we run through the window
if pix == *consumed + window
then we insert the blob into the *consumed window slot
but we can't move forward
rwalkerToday at 9:18 PM
I think that's being fixed in pgarg's PR, no?
https://github.com/solana-labs/solana/pull/846/files#diff-15a88956858291e240d996faf826809cR493
GitHub
Prevent a node from overrunning it's receive window by pgarg66 · ...
The node drops blobs that will cause it to overrun window
The node does not ask to repair a blob that overruns the window

anatolyToday at 9:19 PM
not directly, insert should fail and we should test that
rwalkerToday at 9:20 PM
can just move that while() loop at line 487 into its own function
then it's "direct"
anatolyToday at 9:20 PM
i mean, the imiportant part is testing that :smiley:
make sure we dont re-introduce this later
rwalkerToday at 9:21 PM
@pgarg are you down with this?

**Comment by pgarg66** [comment]
https://github.com/solana-labs/solana/pull/882

**Comment by pgarg66** [comment]
https://github.com/solana-labs/solana/pull/882 is merged.
