### ISSUE TITLE
TdS 1.0 restart halted

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#8717]
#### Problem

TdS cluster restart on 1.0.4 halted at slot 2,492,465.

#### Proposed Solution

Debug..

**Comment by sakridge** [comment]
Validator logs:
https://drive.google.com/drive/folders/1OPOM8My7ots-ne9JcINj-SL0dnwNhxpG

**Comment by sakridge** [comment]
Ledger view from bootstrap leader to slot 2,495,000

[ledger-graph.pdf](https://github.com/solana-labs/solana/files/4302615/ledger-graph.pdf)

**Comment by sakridge** [comment]
Ft5fbkqNa76vnsjYNwjDZUXoTWpP7VYm3mtsaQckQADN seemed to stop voting here:

[2020-03-07T13:17:57.855731535Z INFO  solana_core::replay_stage] voting: 2493554 4504466968061038536151040

BSV is voting here:
Mar  7 16:27:35 asteroids bootstrap-validator.sh[38940]: [2020-03-07T16:27:35.482819900Z INFO  solana_core::replay_stage] voting: 2547335 4504425766456483206812160

**Comment by sakridge** [comment]
Nothing in the logs seems fatal, there are a couple worries:

Excess logging of messages like this right around the restart indicate some node is broadcasting a block with too many shreds, not sure why:
`datapoint: blockstore_error error="Slot 2500381: received index 13 >= slot.last_index 8"`

`COUNTER:{"name": "shred_fetch_stage-shred_index_overrun", "counts": 2001, "samples": 2000,  "now": 1583582078549, "events": 1}`

```
[2020-03-07T11:54:39.602393750Z WARN  solana_ledger::blockstore] Received multiple erasure configs for the same erasure set!!!
[2020-03-07T11:54:39.602419288Z WARN  solana_ledger::blockstore] Stored config: ErasureConfig {
        num_data: 1,
        num_coding: 1,
    }, new config: ErasureConfig {
        num_data: 5,
        num_coding: 5,
    }
```

**Comment by sakridge** [comment]
[luna-tds-graph.pdf](https://github.com/solana-labs/solana/files/4304450/luna-tds-graph.pdf)


Graph from Luna, shows some really extreme forking.

**Comment by sakridge** [comment]
@carllin any ideas how those nodes got down these minor forks so far?

**Comment by sakridge** [comment]
> @carllin any ideas how those nodes got down these minor forks so far?

Seems like a lot of cases where nodes kind of got isolated, then they had some leader slots, created their own fork and then got locked out on it, I think because they are voting on their leader slots by default. I think we might need the logic where we detect if the rest of the network is voting on our own fork before voting on it ourselves.

**Comment by carllin** [comment]
@sakridge which minor forks are you looking at specifically? 

I would check the logs to first determine:

1) Are the forks even observing each other? Do some of the validators mark one fork as dead vs/ other validators.
2) Are the two sides of each fork being observed really late? Even If the "heaviest fork" is being observed, if it's observed late, the minor fork could have run ahead.

**Comment by carllin** [comment]
> Ft5fbkqNa76vnsjYNwjDZUXoTWpP7VYm3mtsaQckQADN seemed to stop voting here:
> 
> `[2020-03-07T13:17:57.855731535Z INFO solana_core::replay_stage] voting: 2493554 4504466968061038536151040`
> 
> BSV is voting here:
> `Mar 7 16:27:35 asteroids bootstrap-validator.sh[38940]: [2020-03-07T16:27:35.482819900Z INFO solana_core::replay_stage] voting: 2547335 4504425766456483206812160 `

@sakridge That node 
1) Stopped a minute after its last vote, so I don't know how valuable that information is
2) The last vote was 2493554. Based on the graph from `Luna` the chain is 2493554 -> 2493554 -> 2493600. This node never got 2493600, and took almost 8 seconds to freeze `2493555`. 

```[2020-03-07T13:17:57.871394964Z INFO  solana_core::replay_stage] new fork:2493555 parent:2493554 root:2492468
[2020-03-07T13:18:05.461915798Z INFO  solana_core::replay_stage] bank frozen: 2493555```


I think data propagation definitely looks like an issue on this node, but we need to confirm if the initial forking behavior was caused by the same problem. We do this by looking at logs from the earliest long running fork since the last root, and checking both sides of the fork to see how fast they are observing/freezing each other's banks

**Comment by carllin** [comment]
Of note, I also checked the `Luna` logs, they had:

```
[2020-03-07T12:45:13.301733270Z INFO  solana_core::replay_stage] bank frozen: 2493555
```

almost 30 mins before this other node. And I know both these validators were both initially in sync because both had:

```[2020-03-07T11:54:41.244875431Z INFO  solana_core::replay_stage] bank frozen: 2486177```

and 

```[2020-03-07T11:54:41.014068569Z INFO  solana_core::replay_stage] bank frozen: 2486177```

**Comment by carllin** [comment]
These are all the timestamped votes from both validators:

[Luna_votes.log](https://github.com/solana-labs/solana/files/4305328/Luna_votes.log)
[Ft5fbkqNa76vnsjYNwjDZUXoTWpP7VYm3mtsaQckQADN_votes.log](https://github.com/solana-labs/solana/files/4305330/Ft5fbkqNa76vnsjYNwjDZUXoTWpP7VYm3mtsaQckQADN_votes.log)

These might not be the best example because they both are voting on the same fork, but even then you can see

1) as early as `2492603` and `2492602` they are still within a second of each other
2) by vote `2492860` (right before another minor fork but after a previous minor fork) they are 8 seconds apart, and it gets worse.

**Comment by carllin** [comment]
@sakridge, here's something strange as well. Both validators vote on slot `2492668`, which has parent `2492651`. In order to play a new slot, you must have frozen the parent, which implies `2492651` must be frozen.

However, I don't see a bank frozen log for the parent `2492651` on `Luna`, but I do see on `Ft5fbkqNa76vnsjYNwjDZUXoTWpP7VYm3mtsaQckQADN`:

```[2020-03-07T12:39:28.208597566Z INFO  solana_core::replay_stage] bank frozen: 2492651```

**Comment by carllin** [comment]
@sakridge, @aeyakovenko, this isn't the main cause, but another thing I'm noticing is that the `MAX_ORPHANS = 5` repair requests are being saturated on validators by some seemingly dead slots as they seem to make the same orphan requests over and over.

```
Mar 07 12:39:35 ln-mars-wolv1 solana-validator[2563]: [2020-03-07T12:39:35.130040102Z INFO  solana_metrics::metrics] datapoint: serve_repair-repair_orphan repair-orphan=2494259i
Mar 07 12:39:35 ln-mars-wolv1 solana-validator[2563]: [2020-03-07T12:39:35.130042932Z INFO  solana_metrics::metrics] datapoint: serve_repair-repair_orphan repair-orphan=2495143i
Mar 07 12:39:35 ln-mars-wolv1 solana-validator[2563]: [2020-03-07T12:39:35.130045562Z INFO  solana_metrics::metrics] datapoint: serve_repair-repair_orphan repair-orphan=2495745i
Mar 07 12:39:35 ln-mars-wolv1 solana-validator[2563]: [2020-03-07T12:39:35.130048262Z INFO  solana_metrics::metrics] datapoint: serve_repair-repair_orphan repair-orphan=2496526i
Mar 07 12:39:35 ln-mars-wolv1 solana-validator[2563]: [2020-03-07T12:39:35.130051262Z INFO  solana_metrics::metrics] datapoint: serve_repair-repair_orphan repair-orphan=2497075i
```
@sakridge in line with the `datapoint: blockstore_error error="Slot 2500381: received index 13 >= slot.last_index 8"` logs you were seeing, it seems like there might be somebody who didn't clear their ledger, as I see an orphan request for `2497075` when the cluster was only in the `2492000 - 2493000`

**Comment by sakridge** [comment]
@carllin Take a look at the ledger graph from the BSV node, it doesn't have the other forks blocks at all.

**Comment by mvines** [comment]
>  it seems like there might be somebody who didn't clear their ledger,

This is definitely true.  I saw evidence of this in the metrics before/after the death too.

**Comment by sakridge** [comment]
About 8 nodes ran out of disk space:
```
2020-03-07 09:41:01	URnkWZGiuB7jXbfCSuNSwir1qkn7sXjiSPeLPaXys7b	validator	solana-replay-stage	panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:1188:5
2020-03-07 09:41:00	URnkWZGiuB7jXbfCSuNSwir1qkn7sXjiSPeLPaXys7b	validator	solana-replay-stage	panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 28, kind: Other, message: "No space left on device.
```

If they are at 1.5% stake, that's about 12% stake total.

**Comment by carllin** [comment]
@sakridge, @mvines  there were roots set after that time though, I see both `Luna` and the  `Ft` node set roots at:

```Mar 07 12:38:40 ln-mars-wolv1 solana-validator[2563]: [2020-03-07T12:38:40.860455454Z INFO  solana_ledger::bank_forks] setting snapshot root: 2492456```

**Comment by sakridge** [comment]
@carllin that was just the first one, these are after that root:

```
2020-03-07 18:16:17	Fb5cEcYNgPXKJoEmvPvsU2ENYRVePQtExqgf77AnVX54	validator	solana-replay-stage	panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:1188:5
2020-03-07 18:16:16	Fb5cEcYNgPXKJoEmvPvsU2ENYRVePQtExqgf77AnVX54	validator	solana-replay-stage	panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 28, kind: Other, message: "No space left on device" }', src/libcore/result.rs:1188:5

Disk
2020-03-07 16:25:00	6qJPxxgZHCQKBvbGC9zCsuuPtHMMLszVCoiCvEhVULyJ	validator	solana-replay-stage	panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', src/libcore/result.rs:1188:5
2020-03-07 16:24:59	6qJPxxgZHCQKBvbGC9zCsuuPtHMMLszVCoiCvEhVULyJ	validator	solana-replay-stage	panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 28, kind: Other, message: "No space left on device" }', src/libcore/result.rs:1188:5

Disk
2020-03-07 12:41:23	DzxNmWD99qvkPdDR94ojXhUrpzT8VdqB5ktYX7fZr4gc	validator	solana-broadcaster	panicked at 'Failed to insert shreds in blockstore: RocksDb(Error { message: "IO error: No space left on deviceWhile appending to file: /root/validator-ledger/rocksdb/065581.log: No space left on device" })', src/libcore/result.rs:1188:5

```

**Comment by carllin** [comment]
@sakridge ah ok, those seem to occur a while after we've lost consensus though, I suspect maybe overwhelmed by the number of  forks?

**Comment by sakridge** [comment]
> @sakridge ah ok, those seem to occur a while after we've lost consensus though, I suspect maybe overwhelmed by the number of forks?

The 12:41 one is pretty close assuming the timestamps are comparable. Maybe that is the one to push it over the edge.

**Comment by sakridge** [comment]
> > @sakridge ah ok, those seem to occur a while after we've lost consensus though, I suspect maybe overwhelmed by the number of forks?
> 
> The 12:41 one is pretty close assuming the timestamps are comparable. Maybe that is the one to push it over the edge.

Of course, a few other nodes getting lost on other forks probably didn't help as well. So may have been multiple things going wrong.

**Comment by mvines** [comment]
Root cause has been debugged down to https://github.com/solana-labs/solana/issues/8232
