### ISSUE TITLE
gitbook

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#8746]
#### Problem

gitbook

#### Proposed Solution

mdbook

**Comment by garious** [comment]
gitbook's versioning feature is not something that we need to save. Separate URLs is fine.

**Comment by garious** [comment]
https://docs.gitbook.com/resources/gitbook-legacy/v2-differences#cli-toolchain

**Comment by garious** [comment]
One of these two "Install Solana" links is broken when rendered by gitbook:

https://github.com/solana-labs/solana/blob/v1.0.8/docs/src/paper-wallet/usage.md#before-you-begin
https://github.com/solana-labs/solana/blob/v1.0.8/docs/src/remote-wallet/ledger.md#before-you-begin

Can you figure out why? I can't.

**Comment by rmshea** [comment]
@garious should have something for you to look at early next week. Docusaurus is pretty solid and will work with our translations system as well.

**Comment by rmshea** [comment]
#10806

**Comment by rmshea** [comment]
@garious think we can close this one ;)
