### ISSUE TITLE
Refactor banking stage code

### ISSUE THREAD

**Issue by pgarg66** [solana-labs/solana#877]
Based on @garious and @aeyakovenko feedback on https://github.com/solana-labs/solana/pull/869

garious 5 days ago Member
Yeah, I'm not saying the code is incorrect, just that it'd perform best if the focus was on pipelining flat_map calls (filter_map is a specialization of flat_map), so that you can maximize parallelization of deserialize.

I'd think the optimal code would be structured something like this:

let msgs = mms.iter().flat_map(|x| x.0.read().unwrap());
let vers = mms.iter().flat_map(|x| x.1);
let txs = Self::deserialize_transactions(msgs);
let txs = txs.into_iter().zip(vers).filter_map(...);

**Comment by garious** [comment]
We ended up reverting the code this issue is referring to a while back. Closing.
