### ISSUE TITLE
CLI seems to hang when waiting for transaction confirmation

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#8774]
#### Problem
The CLI currently waits until a transaction appears in a rooted block until it returns the transaction's status. This means that it appears to hang for about 12 seconds with no indication that everything is okay and something useful is happening. 

#### Proposed Solution
Print something reassuring and informative during this wait (most likely only if `--verbose` is set). Possibilities: 
- "Waiting for confirmations [1/32]...", and automatically update in place.
- Or a progress bar.

**Comment by mvines** [comment]
This would be a great enhancement.

**Comment by mvines** [comment]
Although this is a better fix: https://github.com/solana-labs/solana/pull/6327
