### ISSUE TITLE
CLI does not support multi-session signing

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#8845]
#### Problem

One of our partners has a usecase requiring multi-session signing.  This is useful generally

#### Proposed Solution

Create a `NullSigner` which always generates `Signature::default()`
Skip signature verification if a `NullSigner` is passed for `--sign-only`
When listing signers, omit entries with sig = `Signature::default()`

**Comment by mvines** [comment]
We could also add a `--partial-sign` option so that you don't need to explicitly add a null signer for the other party's keys that you don't have.

**Comment by mvines** [comment]
Adding this to `split-stake` command is of primary interest right now

**Comment by t-nelson** [comment]
> We could also add a `--partial-sign` option so that you don't need to explicitly add a null signer for the other party's keys that you don't have.

We'll need all of the pubkeys to construct the TX in either case, so I'm not sure this'll add much

**Comment by mvines** [comment]
> We'll need all of the pubkeys to construct the TX in either case, so I'm not sure this'll add much

I guess I don't want to have to add a `--signer NotMyPubkey=11111111111111111111...` argument for each NotMyPubkey in the transaction, that's my only concern

**Comment by t-nelson** [comment]
Yep, that's what the `NullSigner` will alleviate.  Just need to think through the footguns.  Maybe just something as simple as listing the pubkeys of the missing signers.  I'll noodle it over the weekend
