### ISSUE TITLE
No clear way to get remote-wallet path string

### ISSUE THREAD

**Issue by CriesofCarrots** [solana-labs/solana#8851]
#### Problem
When using more than one remote wallet, it's nice to be able to disambiguate them in commands by their specific usb path. But how do you get those paths? Currently, the only way is to plug them all in, and use something like `solana address --keypair usb://ledger` to generate the selection  (disregarding the address/pubkey response).

#### Proposed Solution
Add a cli command to generate a device's usb path, without requiring multiple devices being plugged in or adding an unnecessary subcommand

**Comment by garious** [comment]
Maybe something like this:

```bash
$ solana resolve-keypair usb://ledger
usb://ledger/nano-s/abcde
```

```bash
$ solana resolve-keypair usb://ledger?key=0
usb://ledger/nano-s/abcde?key=0
```
