### ISSUE TITLE
High rate of tvu ingress traffic causes delinquency

### ISSUE THREAD

**Issue by leoluk** [solana-labs/solana#8861]
A high rate of inbound shreds to the tvu port (~50 kpps) causes validators to fall out of sync with the network and become delinquent.

This how one of the recent TdS networks died (aided the the repair issues at the time that prevented nodes from getting back in sync, so they could be attacked one by one vs. having to target 1/3).

Still works, tested on our TdS node by replaying the same valid shred a lot of times:

![image](https://user-images.githubusercontent.com/859697/76683672-3ac44680-6606-11ea-9b47-9409c0e97b6c.png)

(you can see where it switches to its own fork and goes delinquent until traffic stops)

**Comment by mvines** [comment]
Do you know if the same is true if the payload is an invalid shred?   That would lower the bar for this attack from "anybody who gets enough stake to be in the leader schedule" to "anybody"

**Comment by leoluk** [comment]
Works with invalid shreds, too. Tried by replaying a SLP shred on TDS, still killed the node.

**Comment by leoluk** [comment]
I did not investigate how much of that is due to the TVU stalling vs. overloading the host OS.

**Comment by sakridge** [comment]
@leoluk can you share the hardware setup you used to produce this?

**Comment by leoluk** [comment]
16 vCores @ 2.3 GHz (Skylake Xeon), 64G RAM, NVMe disk

**Comment by leoluk** [comment]
Reproduction instructions: https://gist.github.com/leoluk/bbdcb6173ec3dd3da8b2f6ca9512b2e9
