### ISSUE TITLE
Reduce memory usage in duplicate detection

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#887]
Use something other than Signature for duplicate detection. One `from: PublicKey` per `last_id: Hash` seems promising. Or first map `last_id` to `entry_height` and then require `entry_height` be increasing per `from: PublicKey`. To run multiple TXs in one batch, we can either merge @carllin's multi-instruction patch, or add a `version` field to the TX.

Note: A `last_id`'s `entry_height` will be the ledger's `entry_height` minus its position is the `last_ids` dequeue.

**Comment by aeyakovenko** [comment]
@sakridge @garious 

Sig detection can just check any random 64 bits of the sig. and fail some valid transactions. So we should not need to store 64bits per sig.  odds of a collision over 20 seconds or 20m sigs would be 1:2^40.

**Comment by garious** [comment]
Isn't that how HashSet is implemented? I haven't looked at the code, but the key is Hashable, so sounds like what you're suggesting, except that collisions would be detected and resolved in the usual O(n) way.

**Comment by aeyakovenko** [comment]
@garious, hashset stores the full copy and doesn’t allow for false matches.  I am suggesting we cut the signature to 20 bytes and allow for an unlikely false dup

**Comment by sakridge** [comment]
It's not a bad idea. I worry a bit about potential security, but I cannot think of an attack vector at the moment. We are not really bottlenecked by this today, can we keep as a possible solution for later?

**Comment by aeyakovenko** [comment]
@sakridge sure.  i thought the benchmark showed that this improves the banking stage by 50%

**Comment by sakridge** [comment]
@aeyakovenko first, the banking stage is not the bottleneck to our average TPS right now. Also, removing the check entirely does, but reducing the number of bytes checked will have a smaller effect. You'll have to benchmark it to know how much smaller, but consider you still need to have that table and resize it and do the hash and take locks and whatever else, it's just that it will be a bit smaller.
