### ISSUE TITLE
solana-keygen grind no longer respects case 

### ISSUE THREAD

**Issue by HM999** [solana-labs/solana#8900]
#### Problem

I'm 99% sure it used to search for exactly what you put in, but right now it seems to be searching for everything lower case.

```
solana-keygen grind --starts-with ABC:1
```
Finds pubkey "abc..."

I'm guessing this is also pretty low priority all things considered.

**Comment by garious** [comment]
That's not the intended behavior. It should only happen when `--ignore-case` is added. @mvines, want this one?
