### ISSUE TITLE
CLI: Ambiguous usage help for positional parameters since #8878

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#8962]
#### Problem

Since https://github.com/solana-labs/solana/pull/8878, many CLI commands generate ambiguous usage help for positional parameters.  eg. https://docs.solana.com/v/master/cli/usage#solana-authorize-nonce-account

#### Proposed Solution

`<ROLE TYPE>` for positional parameters, flags self-document optional parameters

cc/ @garious @CriesofCarrots

**Comment by garious** [comment]
Wfm
