### ISSUE TITLE
RPC: Commitment level doesn't make sense for getNumBlocksSinceSignatureConfirmation

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#8964]
#### Problem
Most RPC endpoints allow specifying a commitment level so that an appropriate bank can be used to fulfill the request. Due to the nature of `getNumBlocksSinceSignatureConfirmation`, it only really makes sense to use the "recent" commitment level because one of the main purposes of the endpoint is to track progress towards a slot getting rooted

#### Proposed Solution
- TBD

**Comment by CriesofCarrots** [comment]
This rpc endpoint has been removed.
