### ISSUE TITLE
Can't execute BPF without loading it first

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#8971]
#### Problem

Can't inject simple BPF into transactions. For simple assertions, the compiled code should be well under 1500 bytes.  I'd like to write something like this:

```rust
let ix0 = Instruction {
    program_id: BPF_LOADER,
    accounts: [1],
    data: to_bpf!(|keyed_accounts| assert!(keyed_accounts[0].lamports == 0))
};
let ix1 = SystemInstruction::transfer(...);
let message = Message::new(&[ix0, ix1]);
client.send_message(&message);
```

#### Proposed Solution

Add an instruction to the BPF_LOADER that executes the bytecode in the instruction data.

cc: @jackcmay

**Comment by jackcmay** [comment]
@garious This is possible and will probably come with exceptions, like not being able to call helper functions (traps)
