### ISSUE TITLE
stake commands default --fee-payer to default signer

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#9013]
#### Problem

stake commands default the --fee-payer to the default signer, but the stake authority is already providing a signature. No need for a default that requires a signature when there's one readily available.

#### Proposed Solution

Default to the --stake-authority if --fee-payer is not provided. Exceptions:

* create-stake-account should default to the --from account
* withdraw-stake should default to --withdraw-authority
* stake-authorize should not have a default fee-payer

**Comment by garious** [comment]
cc: @CriesofCarrots, @t-nelson.  Less of a priority, but if implemented drops a lot of dependencies on the default signer, and replaces them with more intuitive defaults.

**Comment by t-nelson** [comment]
A couple things stand out here.
1) There's no reason to assume that authority keypairs have an account on chain. Using them as fee-payer fallback puts a burden on the user to keep track of more balances and the exposure to rent is likely a much higher cost than the extra signature worth of fees on what should be infrequent operations
2) `--fee-payer` and `--from` were really introduced to enable importing offline signatures.  That is, an advanced feature.  While the explicitness they provide is attractive, I'm worried that encouraging their use generally is raising the cognitive load on the user.
3) That's a long list of exceptions. Inconsistencies lead to mistakes lead to losses.

That said, we do have the freedom of specifying signers to enable something like this.  If we're trying to optimize an internal workflow here, I'd be happy to assist with a wrapper script doing so.

**Comment by garious** [comment]
Great points.  How about we remove all defaults for now?  And then we incrementally add them back for specific options? For example: `solana config set --fee-payer=fee-payer.json`, and then use that as the default for any command with a `--fee-payer` option.

**Comment by garious** [comment]
Closing this one.  Will create a new issue with the `--fee-payer` config proposal.
