### ISSUE TITLE
Unnecessary copies of Pubkeys and Signatures

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#9032]
#### Problem

Pubkey and Signature are 32-byte and 64-byte structures, respectively, and implement the `Copy` marker. If you delete that Copy marker on either, it exposes lots and lots of places where the compiler is doing an implicit `clone()` on that data. It's likely degrading system-wide performance.

#### Proposed Solution

Remove the Copy markers. Inspect each `clone()` you have to add to fix the compiler error and evaluate whether it can be refactored to use move semantics. Benchmark before and after.

cc: @sakridge

**Comment by jon-chuang** [comment]
I am interested in investigating this. Can start in 6 weeks.
