### ISSUE TITLE
`solana block-time` is very slow on mainnet-beta, maybe doesn't complete?

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#9034]
STR:
1. Find a recent rooted slot
2. Run `solana block-time <slot>`

I'd expect a response in 1-2 seconds at most.  Mostly (2) doesn't terminate, and we get a `solana-watchtower`  RPC timeout operation fault.

**Comment by CriesofCarrots** [comment]
Confirmed that validators are timestamping votes as expected, and the calculation is working:
- `getBlockTime` works against devnet.solana.com (v1.1.3), although it takes several seconds to return)
- `getBlockTime` also works against a GCP api node that I booted on mainnet-beta (tip of v1.0); returns in <1 sec
