### ISSUE TITLE
solana-watchtower: include a flag that specifies how much of a cluster needs to be delinquent before failing the sanity test

### ISSUE THREAD

**Issue by Pete-LunaNova** [solana-labs/solana#9048]
Currently if solana-watchtower is monitoring a cluster (ie, no validator pubkey is passed to it) it will return a failed sanity test if at least one node is delinquent.
This doesn't allow us to use it as point of reference for the whole cluster still being healthy.

It could be very useful if users could specify how much of a cluster needs to be delinquent before this sanity test is failed, via a command line flag. It may be best if this is done in the format of x% of the cluster needs to be non-delinquent to indicate a healthy cluster.

This change would enable validators to run 2 instances of the watchtower. One monitoring their individual pubkey and the second monitoring the cluster as a whole. If a validator receives an alert regarding their individual validator but none about the cluster they know that the issue is with their system. Conversely, if they are receiving alerts about both their validator and the cluster they will know its a cluster-wide issue and they should head to the Discord for updates.

@HM999

**Comment by mvines** [comment]
Hey Pete, does the existing `solana-watchtower --monitor-active-stake` flag solve this for you?

**Comment by Pete-LunaNova** [comment]
> Hey Pete, does the existing `solana-watchtower --monitor-active-stake` flag solve this for you?

Hi, unfortunately it doesn't. It generated the following messages with only 2 validators delinquent when I ran it with that flag:

`INFO  solana_watchtower] Delinquent validator count: 2`
`INFO  solana_watchtower] Current stake: 99% | Total stake: 2265000.86759296 SOL, current stake: 2255000.87215872 SOL, delinquent: 9999.99543424 SOL`
 `ERROR solana_watchtower] delinquent sanity failure: 2 delinquent validators`
`INFO  solana_metrics::metrics] datapoint: watchtower-sanity ok=false`
`ERROR solana_metrics::metrics] datapoint: watchtower-sanity-failure test="delinquent" err="2 delinquent validators"`

**Comment by mvines** [comment]
Oh but what if you also used the `--validator-identity` to additionally only monitor one or more of your validators?
```
$ solana-watchtower --monitor-active-stake --validator-identity MY_PUBKEY
```

**Comment by Pete-LunaNova** [comment]
> Oh but what if you also used the `--validator-identity` to additionally only monitor one or more of your validators?
> 
> ```
> $ solana-watchtower --monitor-active-stake --validator-identity MY_PUBKEY
> ```

When I do this I can see from its log output that it is tracking the active stake and number of delinquent validators. However, it is not exporting any additional metrics, which is what I am using to trigger my alerts. (They are being pushed to an influxdb-exporter which emulates an influxdb but transforms them in to a format my Prometheus server can ingest. This is then used to trigger alerts and populate my Grafana dashboards)

I had originally thought that, if the "watchtower-sanity-ok" metric could be used to indicate whether the whole cluster was healthy when no individual pubkey is passed, then this would be a good solution. However, if it is possible to get the watchtower to export additional metrics, that would be even better (as I would need to spin up less watchtower instances). 

An additional metric that records whether the cluster is healthy would be sufficient but if we can get additional metrics with the raw numbers around total validators, delinquent validators, total stake, active stake, delinquent stake, transaction count etc. that would be even better, as I can populate my Grafana dashboard with that info and perform calculations as necessary to trigger alerts.
