### ISSUE TITLE
Modifying executable account data is allowed

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#9051]
#### Problem
After an account is marked as executable, its data should not be allowed to be modified. Doing so would be a security issue.

#### Proposed Solution
Add a check, test case, and error type for this situation

**Comment by mvines** [comment]
@jackcmay - want this?

**Comment by jackcmay** [comment]
@jstarry  Is there a case you had in mind not covered by this: https://github.com/solana-labs/solana/blob/b0c83921be011d23299a38c936311336a00737f5/runtime/src/message_processor.rs#L104

**Comment by jackcmay** [comment]
Ah, caught up on discord, will add a check for an executable accounts data
