### ISSUE TITLE
Deleting executable accounts is allowed

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#9052]
#### Problem
Executable accounts can have their balances drained by their owned loader account and it's not clear if this is a feature or a bug.

#### Proposed Solution

TBD

**Comment by garious** [comment]
A JIT should *not* be a reason to allow this. The loader could JIT the bytecode before setting the executable bit.  After that bit, it should not be possible to modify the account data.  We probably shouldn't allow subtracting lamports either - that's not as obvious though.

**Comment by jackcmay** [comment]
@garious @aeyakovenko    Once created should executable accounts ever go away? Thoughts?

Here are a few of mine:
- Preventing the subtracting of lamports will essentially lock up the executable account's lamports forever.  It would be unfortunate if a program marked an account executable that accidentally contained a bunch of lamports.  
- Deleting a program account would render all accounts owned by it frozen.  But, a new program could be loaded using the same program id and then gain access to those accounts even though its a different program.  That sounds very bad...

**Comment by mvines** [comment]
> But, a new program could be loaded using the same program id and then gain access to those accounts even though its a different program. That sounds very bad...

Another option would be to blacklist that program address once the program account goes away so it could never be used again.  Any accounts owned by the program are now read-only for all time.   If we did this then there's no need for a program to be rent-exempt anymore.

**Comment by jackcmay** [comment]
A good way for a malicious entity to lock up lamports not owned by them without requiring the account signer's approval.  For example, a program allows transferring lamports from accounts it own if the signer is present.  Someone deposits lamports in that account to be distributed later, program owner/signer kills program account, lamports locked forever.  Of course, that is one of many risks folks take delegating tokens to accounts owned by programs.

**Comment by mvines** [comment]
Good point, the loader has the ability to kill any program it loaded.  That's a pretty huge gun.

**Comment by aeyakovenko** [comment]
I think it would need to be program defined. But safe default is that they cannot go away.

**Comment by aeyakovenko** [comment]
I think we can solve this later.  With a refcount based on owned accounts or something like that.

**Comment by jackcmay** [comment]
If we want to solve this later maybe we should block lamport subtraction from executable accounts for now?

**Comment by garious** [comment]
Yes, block subtraction. We can discuss relaxing that restriction later down the line.

**Comment by jackcmay** [comment]
@garious I'm thinking we should just block both subtraction AND addition of lamports for executable accounts.  They are already checked for rent exemption when marked executable (this will be cleaned up with #9110) and any additional lamports added at least for now will be locked up forever.

**Comment by garious** [comment]
sgtm
