### ISSUE TITLE
Validator fails to attach to testnet-master

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#910]
STR:
1. Install the latest snap: `sudo snap install solana --edge --devmode`
2. Configure the validator: `sudo snap set solana mode=validator leader-address=$(dig +short master.testnet.solana.com)`
3. Watch the validator log: `tail -f /var/snap/solana/current/validator/current -n200`

There may be a `thread 'main' panicked at 'process_ledger: AccountNotFound` panic.

Two parts to this issue:
* [x] Add the above STR to `ci/testnet-sanity.sh` to validate in automation
* [x] Fix

**Comment by mvines** [comment]
`sudo solana.ledger-tool --ledger /var/snap/solana/current/config/ledger verify` is failing when run on the leader node, we might have a ledger serialization bug

**Comment by mvines** [comment]
I think issue is observable on the master testnet:
![image](https://user-images.githubusercontent.com/1281082/43911059-5072ac3e-9bb3-11e8-8aec-f5f9f1e5af7c.png)

Note that at the top of most hours, when the network resets, the node count drops from 50 to 40, 30, etc.  My theory is that the nodes getting dropped are validators which are hitting this panic

**Comment by rob-solana** [comment]
https://gist.github.com/rob-solana/2acd530f4717c7b66e6afee72f869df5

this is a debug print of the ledger collected this morning from the STR

this ledger is corrupt, as it's 3rd entry id is wrong and it's a vote...

**Comment by rob-solana** [comment]
Ledger issues fixed.  New issue: the abort appears network-related:

@400000005b7198251faf1b5c thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', libcore/result.rs:945:5
@400000005b719825204b150c stack backtrace:
@400000005b719825204b150c    0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
@400000005b719825205438e4              at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
@400000005b719825205438e4    1: std::sys_common::backtrace::print
@400000005b719825205ae004              at libstd/sys_common/backtrace.rs:71
@400000005b719825205ae3ec              at libstd/sys_common/backtrace.rs:59
@400000005b719825205ae3ec    2: std::panicking::default_hook::{{closure}}
@400000005b7198252062bfa4              at libstd/panicking.rs:211
@400000005b7198252062c38c    3: std::panicking::default_hook
@400000005b7198252062c38c              at libstd/panicking.rs:227
@400000005b7198252062c38c    4: solana::metrics::set_panic_hook::{{closure}}::{{closure}}
@400000005b7198252062dee4    5: std::panicking::rust_panic_with_hook
@400000005b719825206311ac              at libstd/panicking.rs:467
@400000005b7198252063197c    6: std::panicking::begin_panic_fmt
@400000005b71982520632534              at libstd/panicking.rs:350
@400000005b719825206330ec    7: rust_begin_unwind
@400000005b71982520633ca4              at libstd/panicking.rs:328
@400000005b71982520636f6c    8: core::panicking::panic_fmt
@400000005b71982520678e1c              at libcore/panicking.rs:71
@400000005b71982520678e1c    9: core::result::unwrap_failed
@400000005b71982520678e1c   10: solana_fullnode::main
@400000005b71982520679204   11: std::rt::lang_start::{{closure}}
@400000005b7198252067a974   12: std::panicking::try::do_call
@400000005b7198252067a974              at libstd/rt.rs:59
@400000005b7198252067dc3c              at libstd/panicking.rs:310
@400000005b7198252067e7f4   13: __rust_maybe_catch_panic
@400000005b719825206839fc              at libpanic_unwind/lib.rs:105
@400000005b7198252068499c   14: std::rt::lang_start_internal
@400000005b71982520730b84              at libstd/panicking.rs:289
@400000005b71982520730f6c              at libstd/panic.rs:374
@400000005b71982520730f6c              at libstd/rt.rs:58
@400000005b71982520730f6c   15: main
@400000005b71982520730f6c   16: __libc_start_main
@400000005b71982520730f6c   17: _start

**Comment by rob-solana** [comment]
instead of using the snap, we're using validator startup directly in testnet-sanity.sh
