### ISSUE TITLE
`/net` testnet scripts are failing to start validators due to failed genesis opening

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#9106]
#### Problem
Kicking off a testnet using the `/net` scripts and `net.sh start` is failing due to all the validators failing to unpack the snapshot from the bootstrap node, and then blacklisting the bootstrapper as a result.

From a non bootstrap validator's log:
```
[2020-03-26T23:36:32.628175836Z INFO  solana_validator] Total 1 RPC nodes found. 0 trusted, 0 blacklisted 
[2020-03-26T23:36:32.628181497Z INFO  solana_validator] Highest available snapshot slot is 100, available from 1 node: [boot1Z6jb15CLqpaMTn2CxktktwZpRAVAgHZEW6SxQ7]
[2020-03-26T23:36:32.628190324Z INFO  solana_validator] Using RPC service from node boot1Z6jb15CLqpaMTn2CxktktwZpRAVAgHZEW6SxQ7: V4(10.1.1.23:8899)
[2020-03-26T23:36:32.650167075Z INFO  solana_validator] RPC node version: 1.1.0 [channel=edge commit=30bed18b777d48065867908ba2a8baf24560676d]
[2020-03-26T23:36:33.090489149Z INFO  solana_download_utils]   Downloaded http://10.1.1.23:8899/genesis.tar.bz2 (46137099 bytes) in 440.264925ms
[2020-03-26T23:36:33.091077098Z INFO  solana_ledger::hardened_unpack] Extracting "/mnt/extra-disk/config/validator/tmp-genesis/genesis.tar.bz2"...
[2020-03-26T23:36:33.128904653Z WARN  solana_validator] Unable to unpack "/mnt/extra-disk/config/validator/tmp-genesis/genesis.tar.bz2": Archive("too large snapshot: 126334094")
[2020-03-26T23:36:33.128918700Z INFO  solana_validator] Excluding boot1Z6jb15CLqpaMTn2CxktktwZpRAVAgHZEW6SxQ7 as a future RPC candidate
```

Example log files can be found under "Artifacts" from this build:  https://buildkite.com/solana-labs/testnet-automation-colocation/builds/111#19f92458-db16-4814-a17d-611da148047f

**Comment by ryoqun** [comment]
Okay, I've dug in a bit.

First, raising the limit of maximum size of genesis would be really easy one-line PR. But I just wanted to verify the justification for the raise as it'd make a bit easier to do a DoS attack.

@danpaul000 I found that `client-accounts.yml` (thus, resultant `genesis.bin`) is really huge (~126 MB) as compared to TdS, SLP, or any local ledgers. I originally thought that [`10MiB` maximum](https://github.com/solana-labs/solana/pull/8959/files#diff-17fc305f5509f475e804ba989bb306caR32) is sensible.
Is that 100MB+ genesis file intended? If that's the case, what would be the sensible upper bound?

Alternatively, if that size of genesis is justifiable only for testing/benchmarking, not ever in production/development, I may be better off introducing some environment variable to skip the newly-introduced check (#8959) with a name like `SOLANA_IGNORE_GENESIS_ARCHIVE_UNPACK_SIZE`.

```
$ tar tvf ryoqun-genesis.tar.bz2 
-rw-rw-r-- solana/solana 126334094 2020-03-27 07:35 genesis.bin
drwxrwxr-x solana/solana         0 2020-03-27 07:35 rocksdb/
-rw-r--r-- solana/solana         0 2020-03-27 07:35 rocksdb/LOCK
-rw-r--r-- solana/solana     36171 2020-03-27 07:35 rocksdb/OPTIONS-000028
-rw-r--r-- solana/solana     36171 2020-03-27 07:35 rocksdb/OPTIONS-000026
-rw-rw-r-- solana/solana    138103 2020-03-27 07:35 rocksdb/LOG
-rw-r--r-- solana/solana        37 2020-03-27 07:35 rocksdb/IDENTITY
-rw-r--r-- solana/solana       666 2020-03-27 07:35 rocksdb/MANIFEST-000004
-rw-r--r-- solana/solana        16 2020-03-27 07:35 rocksdb/CURRENT
-rw-r--r-- solana/solana      3951 2020-03-27 07:35 rocksdb/000003.log

$ less ryoqun-client-accounts.yml| grep balance: | wc -l
1418100
$ stat ryoqun-client-accounts.yml 
  File: ryoqun-client-accounts.yml
  Size: 468578438       Blocks: 915552     IO Block: 4096   regular file
Device: fd01h/64769d    Inode: 11832069    Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1000/  ryoqun)   Gid: ( 1000/  ryoqun)
Access: 2020-03-27 07:46:54.631277048 +0000
Modify: 2020-03-27 07:46:12.668834423 +0000
Change: 2020-03-27 07:46:12.668834423 +0000
 Birth: -

```

**Comment by mvines** [comment]
> Is that 100MB+ genesis file intended? If that's the case, what would be the sensible upper bound?
> 
> Alternatively, if that size of genesis is justifiable only for testing/benchmarking, not ever in production/development, I may be better off introducing some environment variable to skip the newly-introduced check (#8959) with a name like `SOLANA_IGNORE_GENESIS_ARCHIVE_UNPACK_SIZE`.

This is only for testing, so that bench-tps is fully funded immediately from genesis.    How about adding a `--max-genesis-archive-unpack-size` argument to `solana-validator`, `solana-ledger-tool` and `solana-genesis` instead of an env var?   We can add this flag into `net/`.

I say `solana-genesis` because we should have a check in there that ensures it didn't just produce a genesis archive that would not be accepted by `solana-validator`/`solana-ledger-tool`

**Comment by ryoqun** [comment]
> > Is that 100MB+ genesis file intended? If that's the case, what would be the sensible upper bound?
> > Alternatively, if that size of genesis is justifiable only for testing/benchmarking, not ever in production/development, I may be better off introducing some environment variable to skip the newly-introduced check (#8959) with a name like `SOLANA_IGNORE_GENESIS_ARCHIVE_UNPACK_SIZE`.
> 
> This is only for testing, so that bench-tps is fully funded immediately from genesis. How about adding a `--max-genesis-archive-unpack-size` argument to `solana-validator`, `solana-ledger-tool` and `solana-genesis` instead of an env var? We can add this flag into `net/`.
> 
> I say `solana-genesis` because we should have a check in there that ensures it didn't just produce a genesis archive that would not be accepted by `solana-validator`/`solana-ledger-tool`

Okay, I'll do that plumbing including `solana-genesis` quickly!

**Comment by ryoqun** [comment]
![image](https://user-images.githubusercontent.com/117807/80664803-ae48e700-8ad2-11ea-9f47-b090d53a8663.png)

Heh, github doesn't consider adding linked issue after merge, it seems. :) Closing manually!
