### ISSUE TITLE
RPC getBlockCommitment method doesn't return full commitment status

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#9140]
#### Problem
`BlockCommitment` mirrors vote state so it only has information up to 31 confirmations for a particular block. Notably, it doesn't inform the caller whether a node has finalized the block (>= 32 confirmations)

#### Proposed Solution
This method is no longer used, maybe it can be deleted?

**Comment by CriesofCarrots** [comment]
As of #9618 , `BlockCommitment.commitment` now contains 32 items, with the last indicating rooted stake. We can consider endpoint deprecating/removal separately.
