### ISSUE TITLE
Need options for storing snapshots and re-verifying them

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#9160]
#### Problem

Nodes might produce a bad snapshot and no-one is really looking to see if they are bad unless a node reboots and debugging would be much easier if we have the last good snapshot and the first bad snapshot. We would also know when the first good snapshot is so we can use that to reboot nodes as necessary instead of a really old one.

#### Proposed Solution

Add an option to re-load the snapshot and verify it after creation. If it fails, then make sure we keep the previous good snapshot and this bad one. Notify the operator in some way, maybe crash?

**Comment by sakridge** [comment]
cc @ryoqun @mvines

**Comment by mvines** [comment]
I've added support to capture and verify snapshots hourly into https://github.com/solana-labs/cluster/commit/cf03845ee6a487dbff39ccbe5c0e8ed5069ca37c, error notifications go through metrics

**Comment by sakridge** [comment]
> 
> 
> I've added support to capture and verify snapshots hourly into [solana-labs/cluster@cf03845](https://github.com/solana-labs/cluster/commit/cf03845ee6a487dbff39ccbe5c0e8ed5069ca37c), error notifications go through metrics

Ok, that seems good for now. I think it might be nice if this option is built-in so 3rd party validators can have it as well if they want.
