### ISSUE TITLE
Add RPC API to fetch the full transaction from a signature: getConfirmedTransaction?

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#9179]
To enable an explorer view that allows a user to enter a transaction signature and view the full transaction, we'll need an RPC method that looks a little like `getSignatureStatus` ( https://github.com/solana-labs/solana/pull/8823) but returns the full `EncodedTransaction` (similarly to what is returned for a transaction by `getConfirmedBlock`)

In the v0.1 implementation, functionality is more important than performance, so for example if we need to deserialize an entire slot to find the transaction then that's tolerable (with a follow-up issue filed to improve performance later).

**Comment by CriesofCarrots** [comment]
Added in #9381
