### ISSUE TITLE
Solana CLI gives no feedback when cluster unreachable

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#9186]
#### Problem

Solana CLI hangs a long time when it could be telling the user that the cluster cannot be reached (either due to a bad URL or the RPC node being down).

Steps to reproduce:

```bash
solana cluster-version --url http://google.com
```

#### Proposed Solution

Print a message to stderr each time the CLI retries.

cc: @CriesofCarrots

**Comment by CriesofCarrots** [comment]
Fixed
