### ISSUE TITLE
CLI panics if 1.1.0 client transfers to a 1.0.x cluster

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#9193]
#### Problem

CLI panics if 1.1.0 client transfers to a 1.0.x cluster

```
solana transfer -k from.json to.json 1
⠉ [0/32] Waiting for confirmations
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("invalid type: null, expected struct RpcResponseContext", line: 0, column: 0)', client/src/rpc_client.rs:127:13
```

#### Proposed Solution

Preferably, handle the change in data, but if not, handle the error gracefully.

**Comment by garious** [comment]
Seeing the same issue with a 1.0.12 client talking to a 1.0.10 cluster.  I didn't check 1.0.11.  No problem after returning to 1.0.10.

**Comment by garious** [comment]
Yikes, the transfers were sent before it panicked. :(

**Comment by CriesofCarrots** [comment]
The breaking change happened between v1.0.10 and v1.0.11.
As I understand that we no longer need to support v1.0.10, I opted to handle the error instead of special case the old data.
