### ISSUE TITLE
devnet snapshots are too slow to load, due to break accounts?

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#9196]
#### Problem
break.solana.com broke it

STR:
1. `solana-validator --entrypoint devnet.solana.com:8001  -l ledger -o -`

The downloaded snapshot is 1.4G and takes my node about 15 minutes to load.

**Comment by ryoqun** [comment]
I think I've solved this basically: https://github.com/solana-labs/solana/pull/9219#issuecomment-607321692 :)
