### ISSUE TITLE
TVU transaction signature verification on GPU

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#9256]
#### Problem

TVU verifies transaction signatures on the CPU after deserialization in replay stage. This is slow and results in performance degredation.

#### Proposed Solution

Offload the work to GPU.

**Comment by jon-chuang** [comment]
This is CUDA, right?

Is there any interest in offloading with SYCL? This is a single-source heterogeneous compute language embedded in C++ backed by Intel (under DPC++), Xilinx, Codeplay. Performance is better than OpenCL in optimised benchmarks. Advantages include being able to (theoretically) offload to FPGAs and other ASICs with the same infrastructure. I would be interested in writing Rust utils and bindings.

**Comment by sakridge** [comment]
@jon-chuang the GPU code is already implemented for this. This issue is just about hooking up the rust bindings to generate the right offsets into the transaction buffers and calling into the GPU.

Regarding SYCL, we already have an OpenCL implementation of this verify, although it does not work with the AMD compiler and it is not hooked up on the rust side yet. With Intel pushing on OneAPI and AMD pushing on Rocm, I am a bit worried about the support of SYCL long-term. Also, if you want the best performance on nvidia, you can't really mix cuda with sycl or OpenCL because the drivers don't allow those operations to overlap kernel execution like you would get in a single cuda context.

Also, Intel, Xilinx and codeplay don't make hardware that is really suitable for our acceleration purposes. I think if you look at the state of FPGA tools, I think you would be more comfortable with just very basic OpenCL 1.2 code that their toolchain can handle and is also more widely supported.
