### ISSUE TITLE
Remove `confirmTransaction` and `getSignatureStatus` RPC APIs

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#9299]
#### Problem
Various client JSON RPC libraries appear to have problems processing the `status: { "Ok": null } `transaction status returned by methods such as `getSignatureStatuses`. The `null` value causes the removal of `Ok` entirely and the client ends up with a status object of `{}`.

We don't know who is using these two endpoints so we'll have to support them for now and are actively discourage anyone from using them. Deprecation PR: https://github.com/solana-labs/solana/pull/9298

#### Proposed Solution
Low effort: Wait a reasonable amount of time (6 mo?) to be sure no one is using these APIs and then delete them

Ideal: Add monitoring for all RPC endpoints so we can track usage on our API nodes

**Comment by CriesofCarrots** [comment]
Let's open a new issue for the general proposed solution
