### ISSUE TITLE
Remove deprecated `status` field from `getSignatureStatuses`/`getConfirmedBlock` RPC APIs

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#9302]
Various client JSON RPC libraries appear to have problems processing the `status: { "Ok": null } ` transaction status returned by methods such as getSignatureStatuses, and to mitigate this a parallel `err` field was added (see #9296) 

Low effort: Wait a reasonable amount of time (6 mo?) to be sure no one is using these APIs and then delete them

Ideal: Add monitoring for all RPC endpoints so we can track usage on our API nodes

**Comment by acamill** [comment]
Given this one is not to be used, is err is None, means transaction worked?
