### ISSUE TITLE
RPC does not expose `enable_rpc_transaction_history` config setting

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#9316]
#### Problem
There is no way a client can determine whether a node has `enable_rpc_transaction_history` set to false, or if confirmed blocks / statuses have been purged.

#### Proposed Solution
* Return an error from `getConfirmedBlock` when `enable_rpc_transaction_history == false`
* Return an error from  `getSignatureStatuses` when `enable_rpc_transaction_history == false` and `searchTransactionHistory == true`
* Add a `getConfig` endpoint that returns config settings for a node

**Comment by jstarry** [comment]
Resurfacing this since someone just get stuck on this issue today

**Comment by jstarry** [comment]
@CriesofCarrots any objections to returning an error if the transaction history flag is disabled or if bigtable is disabled?

**Comment by mvines** [comment]
> @CriesofCarrots any objections to returning an error if the transaction history flag is disabled or if bigtable is disabled?

This sounds nice to me

**Comment by CriesofCarrots** [comment]
> @CriesofCarrots any objections to returning an error if the transaction history flag is disabled or if bigtable is disabled?

No objections, that sounds great. If it can wait until Monday, I can do this :)

**Comment by jstarry** [comment]
Sounds great, thanks @CriesofCarrots!
