### ISSUE TITLE
solana-keygen grind doesn't support BIP39 mnemonic output

### ISSUE THREAD

**Issue by t-nelson** [solana-labs/solana#9325]
#### Problem

`solana-keygen grind` only outputs to a keypair file, leaving the user no path to recovery should it be lost

#### Proposed Solution

Instead of generating the keypair directly with `Keypair::new()`, use the random BIP39 mnemonic generation as per `solana-keygen new`

https://github.com/solana-labs/solana/blob/ec4745d174fbdf6aaa5fccacb37f7ba30c191cba/keygen/src/keygen.rs#L445-L457

Word count and passphrase should be resolved before spooling up the threads

**Comment by t-nelson** [comment]
Actually, I don't think a passphrase can be used in this scenario due to how it's mixed in as the KDF salt.

This method will be the meat of the operation, https://docs.rs/tiny-bip39/0.8.0/bip39/struct.Mnemonic.html#method.from_entropy

**Comment by t-nelson** [comment]
> Hi I'd like to take a crack at this. Anyone who is already working on or intending to work on this, please let me know so that we do not conflict.

It's all yours!  There are quite a few issues burning hotter than this one in my mind :wink:

**Comment by bji** [comment]
Hm at some level it must be possible, surely a user could script generating keys over and over again until they get a public key that they liked.  I will have to read deeper to understand how the passphrase is mixed in and why it is troublesome to use it in this scenario.

**Comment by bji** [comment]
> > Hi I'd like to take a crack at this. Anyone who is already working on or intending to work on this, please let me know so that we do not conflict.
> 
> It's all yours! There are quite a few issues burning hotter than this one in my mind wink

Well we all gotta start somewhere ... :)

**Comment by t-nelson** [comment]
> Hm at some level it must be possible, surely a user could script generating keys over and over again until they get a public key that they liked. I will have to read deeper to understand how the passphrase is mixed in and why it is troublesome to use it in this scenario.

Oh sorry, I may have confused you.  The _mnemonic_ is totally possible, but the optional BIP39 passphrase I think is not.  See [the spec](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#From_mnemonic_to_seed) for details
