### ISSUE TITLE
Devnet RPC node crashed with repeated unsafe unwraps

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#9373]
#### Problem
Devnet RPC node went down 3 times due to unsafe unwraps then appeared to stop re-starting itself.  Appears to be working now after I manually stopped it, pulled over a newer snapshot, then restarted.

[journalctl_first_crash.txt](https://github.com/solana-labs/solana/files/4452152/journalctl_first_crash.txt)

[syslog_unwrap_logs.txt](https://github.com/solana-labs/solana/files/4452177/syslog_unwrap_logs.txt)

**Comment by mvines** [comment]
It's failing to create threads, which is so weird: https://github.com/solana-labs/solana/blob/01697a9f5c257b9adca32408b998f879fb316de9/ledger/src/sigverify_shreds.rs#L32

Nothing obvious in `dmesg` or `syslog` about this.  I've rebooted the machine 🤞

**Comment by danpaul000** [comment]
Looks like it's still failing in a similar manner, and in a service restart cycle right now

**Comment by mvines** [comment]
Debugged this down to https://github.com/solana-labs/solana/issues/9383, with #9384 as a temporary workaround
