### ISSUE TITLE
No API for largest wallets

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#9395]
#### Problem

Can't query the cluster for its largest wallets.

#### Proposed Solution

Add a JSON RPC API that allows the caller to query for the N largest accounts, where N is no larger than 100.  The return value should include the public key, the balance, and a category such as: marketing/bounties/treasury/private sale investor/team/staking or unknown.  The initial version can populate all descriptions with "unknown".

**Comment by Aimeelu668** [comment]
我们交易所是直接接入优盾钱包的，毕竟真的很不喜欢搭建各个币种节点，因为太耗费硬盘和同步时间了。

**Comment by mvines** [comment]
> 我们交易所是直接接入优盾钱包的，毕竟真的很不喜欢搭建各个币种节点，因为太耗费硬盘和同步时间了。

Google translate says, "Our exchange is directly connected to the Udun wallet. After all, I really don't like to build various currency nodes, because it takes too much hard disk and synchronization time."

**Comment by mvines** [comment]
Duplicate of https://github.com/solana-labs/solana/issues/9811
