### ISSUE TITLE
Hard to transfer full token balance

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#9405]
#### Problem

Transferring the full token balance with only one signer is a pain.  You have to know the transaction fee and then subtract that from `<AMOUNT>`.

#### Proposed Solution

`--subtract-fee-from-amount` flag

Also, a new keyword `MAX` that can be used in any `<AMOUNT>` field.  Using `MAX` should imply `--subtract-fee-from-amount`.

cc: @CriesofCarrots

**Comment by garious** [comment]
cc @t-nelson

**Comment by t-nelson** [comment]
Similarly... https://github.com/solana-labs/solana/issues/9406

**Comment by CriesofCarrots** [comment]
@garious mostly, unless you still want the `--subtract-fee-from-amount` flag. That isn't implemented

**Comment by CriesofCarrots** [comment]
... I haven't thought of a strong use-case for `--subtract-fee-from-amount` outside of ALL, though

**Comment by garious** [comment]
don't need it
