### ISSUE TITLE
Nonces can only be used once per offline transaction

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#9420]
#### Problem
Every time a nonce is used, it stores the latest blockhash which cannot be predicted. In order to reuse a nonce, the nonce must first be advanced and then a client has to fetch the nonce account to inspect the latest stored blockhash. If a user wanted to create a batch of offline transactions, they are forced to use a unique nonce account for each one.

#### Proposed Solution
Use the clock sysvar instead of recent blockhash sysvar for nonce creation

**Nonce initialization:** Init nonce with latest slot
**Nonce Advance:** Increment stored nonce slot and assert it is less than latest slot (same compare and swap mechanism)
**Nonce Withdraw:** Same as current behavior

Why does this fix the problem? Because a client will know what the next nonce value will be after it is advanced. The current blockhash approach doesn't allow this because blockhash is not predictable. So with this slot approach, clients can assume that their offline transactions will all succeed in succession and each sequential offline transaction can use nonce++

#### Other benefits
* If nonces are more easily reused, users will need to create fewer of them.
* Also, nonces can use a `u64` for state instead of a 32 byte hash. So, cheaper rent.

tag @t-nelson

**Comment by jstarry** [comment]
Not sure what to do about the fee calculator.

We could keep the current mechanism of taking from recent blockhashes but that would mean that fees would not be predictable for some of the transactions

Otherwise, we could lock-in the fee calculator for some amount of time after the nonce is first used?

**Comment by t-nelson** [comment]
A couple problems here.

You've noticed the fee determinism, which is a highly valued trait of the platform.  They are especially important for nonce usecases (think pre-signed TX kept offline as a life-insurance policy, etc) 

Consecutive nonces throw a wrench in parallel TX parsing. They have to be processed in order, to prevent dependent TX conflicts. Which means sorting by nonce value and no GPU batching.  Both of which would add non-trivial complexity to the processing pipeline.

I really should have spelled out these design decisions in the proposal, we considered a few variants to your suggestion. Apologies for not laying that out and sparing you the brain cells :slightly_smiling_face:, I'll open an issue to do that now

**Comment by jstarry** [comment]
It was fun to think through, no worries!

I think it would be useful to have more of a nonce usage guide for developers in addition to the CLI guide, could you write an issue for that too?

> Consecutive nonces throw a wrench in parallel TX parsing. They have to be processed in order, to prevent dependent TX conflicts. Which means sorting by nonce value and no GPU batching. Both of which would add non-trivial complexity to the processing pipeline.

Wouldn't the onus of ordering the transactions be on the user rather than the runtime?

**Comment by t-nelson** [comment]
> I think it would be useful to have more of a nonce usage guide for developers in addition to the CLI guide, could you write an issue for that too?

Done! :point_up: 

> Wouldn't the onus of ordering the transactions be on the user rather than the runtime?

That would be quite the uphill battle against the internet routing UDP packets :stuck_out_tongue:. No guarantee of ordering or delivery

**Comment by jstarry** [comment]
> That would be quite the uphill battle against the internet routing UDP packets 😛. No guarantee of ordering or delivery

I don't follow. The nonce proposal I wrote still uses compare and swap...

**Comment by t-nelson** [comment]
Say you send a batch and, for whatever reason, the first TX never arrives to the cluster, but the others do. Keep in mind we don't really have a "mempool" analog. Should we cache them validator-side? How many, for how long? This would be a vector for DoS via resource exhaustion.

**Comment by jstarry** [comment]
> Should we cache them validator-side? How many, for how long? This would be a vector for DoS via resource exhaustion.

No caching, they all fail because they are invalid. But yeah I get your point, if the first transaction fails, the rest of the nonced transactions are useless.

Thanks for chatting through!
