### ISSUE TITLE
High TPS repetitive transactions are hard to nonce

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#9422]
I define **Repetitive Transaction** as a transaction that if you strip away the nonce, has identical instructions.

#### Problem
Since transactions use blockhashes as a nonce, repetitive transactions are limited to one per slot. This is because transactions with duplicate instruction content need to be differentiated by blockhash. Yes, nonce accounts could be used but they are more suited for offline / slow tps use-cases. 

There is a current work around for this problem that is being used by the Break Solana game. It creates repetitive transactions by adding an extra random account key to a BPF instruction which is ignored by its program. This allows it to poll for the blockhash much slower than it otherwise would need to avoid dupe signatures. This is hacky, bloats tx size, and unnecessarily taxes the system to query for accounts that don't exist.

#### Proposed Solution
Add no-op system instruction which can take no accounts (not sure if this is allowed) and ignores all instruction data so that users can define their own nonce.

**Comment by jstarry** [comment]
cc @t-nelson (another nonce related issue)

**Comment by t-nelson** [comment]
I take it the break contract code would be a good example of the issue here?

Aside: You could reduce polling by querying the `RecentBlockhashes` sysvar (probably needs plumbing) instead of `getRecentBlockhash`.  This would get you all (Blockhash, `FeeCalculator`) pairs that are valid for the queried bank.  Nearer the end, closer to expiration.

**Comment by jstarry** [comment]
> I take it the break contract code would be a good example of the issue here?

It's more the client code that has the behaviour, but yeah break is where this came up! I imagine this mostly being an issue for high TPS dapps. Imagine any game where you can a certain action more than once a minute, the actions would have to be nonced or the game would have to be subscribed to a stream of blockhashes to keep up (issue here: https://github.com/solana-labs/solana/issues/9421)

**Comment by t-nelson** [comment]
Gotcha!  I'll try to take a peek when I find a few free minutes.

I'm kinda surprised there's nothing like session/event IDs in the TXs?  Might enable some interesting post-play features.  Replays, race your ghost-players, etc

**Comment by jstarry** [comment]
I realized that devs could just create a no-op bpf program rather than needing a special system instruction for it. So I would say this is just a nice to have, but definitely not necessary
