### ISSUE TITLE
RFC that discusses the file format of programs

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#943]
This is expected to be a simple .elf file relocatable read-only code/data sections.  No relocations or external symbols.  Entrypoint is just offset 0 of the code section. x86 arch first so we bring up LLVM in parallel, but take the time to examine LLVM's eBPF backend as a part of this issue too

**Comment by mvines** [comment]
There's no linker support for BPF so we'll need to load `ET_REL` elfs (.o files) instead of `ET_DYN`/`ET_EXEC`

**Comment by mvines** [comment]
Contenders for ELF processing:
* https://crates.io/crates/goblin
* https://crates.io/crates/xmas-elf

Goblin github seems more active

**Comment by jackcmay** [comment]
Good info on BPF and all things related: https://qmonnet.github.io/whirl-offload/2016/09/01/dive-into-bpf/

Looks like the author already wrote a BPF VM/interpreter/x86 compiler/disassembler in Rust: https://github.com/qmonnet/rbpf

**Comment by jackcmay** [comment]
LLVM 6.0 install info for macos: https://embeddedartistry.com/blog/2017/2/20/installing-clangllvm-on-osx
  Note: You must first install XCode from the App Store then run and accept it's user license

After that I was able to build a .bpf object on macos the same way a mvines:

'/usr/local/opt/llvm/bin/clang -nostdinc -o main.o -c -fno-exceptions -fomit-frame-pointer -fno-exceptions -fno-asynchronous-unwind-tables -fno-jump-tables -fpie -target bpf main.c'

**Comment by jackcmay** [comment]
Added a summary of rust crates dealing with BPF, ELF parsing, and dynamic loading in Rust in #1133

**Comment by jackcmay** [comment]
Tracked by #1255 and #1564
