### ISSUE TITLE
Can't set authorities of locked up stake accounts

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#9432]
#### Problem

On Devnet, I can set the authorities of locked up stake accounts. On Mainnet Beta, it exits with "Error: lockup has not yet expired".

#### Proposed Solution

Figure out what fix landed in master and didn't get backported to v1.0.

**Comment by garious** [comment]
False alarm.  You can't set authorities on locked up accounts in either cluster.  The difference is that devnet is ~400 epochs ahead of mainnet.

**Comment by mvines** [comment]
lol!  devnet is fully locked then.   cool, it works :)
