### ISSUE TITLE
ci: docker-rust-nightly broken

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#947]
https://buildkite.com/solana-labs/solana-ci-docker-rust-nightly/builds/6#6e98b116-5514-4f6c-adab-9bda133a7461

https://buildkite.com/organizations/solana-labs/pipelines/solana-ci-docker-rust-nightly/builds/6/jobs/6e98b116-5514-4f6c-adab-9bda133a7461/download.txt

**Comment by mvines** [comment]
fml https://github.com/solana-labs/solana/blame/master/ci/docker-rust-nightly/Dockerfile#L7

**Comment by rob-solana** [comment]
yeap, got it

**Comment by rob-solana** [comment]
looks like now we have to adapt to whatever the docker image has for clippy
