### ISSUE TITLE
Gossip pull request amplification

### ISSUE THREAD

**Issue by leoluk** [solana-labs/solana#9492]
#### Problem

Some gossip responses are much larger than the request. Sending a single 1175 byte pull request packet results in a 907100 byte response in ~1k individual packets, which represents an impressive amplification factor of 772x.

Example payload: [reflect.bin.txt](https://github.com/solana-labs/solana/files/4476464/reflect.bin.txt)

This allows an attacker to cause excessive egress bandwidth costs for a validator at little cost to herself.

Combined with #9491, it can also be used to repurpose a cluster into a very effective DDoS cannon.

The large UDP send/receive buffers set by sys-tuner likely exacerbate this. After sending a burst of packets to our tds validator, it got stuck sending gossip responses at 1 Gbps until I restarted it:

![image](https://user-images.githubusercontent.com/859697/79246297-78242a00-7e79-11ea-83e6-7fd5cc28f8fc.png)

#### Proposed Solution

Zero-pad request packets to have the same size/be larger than the responses? Not sure.

**Comment by behzadnouri** [comment]
For reference, we do we have an [outbound data budget](https://github.com/solana-labs/solana/blob/87311cce7/core/src/cluster_info.rs#L251) and also some ongoing work https://github.com/solana-labs/solana/pull/11807 to better allocate that budget to pull requests. but, yeah, this definitely needs more work and tuning.
