### ISSUE TITLE
Break program caused several validators to go delinquent around the same time

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#9503]
#### Context
The Break app was switched over to the testnet briefly and loaded a BPF program, created ~100 accounts, and then fired off a dozen bpf instructions to the cluster. Around this time, I noticed that transactions were really flaky and so I checked solana beach and saw 15% of the stake was delinquent. It looked like about 8-10 validators went offline right around when Break was switched over.

Reisen's validator was affected and he shared his logs and ledger for analysis.
Logs: https://drive.google.com/open?id=1Ji85BELba2IZFDrKiMhzd_3ZfPeFykWO
~http://173.231.58.226:11323/starrylogs.tar.xz~
~http://173.231.58.226:11323/ledger2.ext4~

#### Problem
TBD

#### Proposed Solution
Investigate

**Comment by mvines** [comment]
@jstarry - did you save those links anywhere?  I can't get at them

**Comment by jstarry** [comment]
@mvines I updated the issue to have a google drive link with the logs.

I found this in the logs.. unfortunately no backtrace
```text
[2020-04-15T13:42:50.148373696Z INFO  solana_metrics::metrics] datapoint: cluster_info-num_nodes live_count=1i broadcast_count=85i
thread '<unnamed>' panicked at 'slice index starts at 1 but ends at 0', src/libcore/slice/mod.rs:2680:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
/home/solana/scripts/launch.sh: line 71: 238714 Segmentation fault      (core dumped) /home/solana/solana/target/release/solana-validator --wait-for-supermajority 2492465 --expected-shred-version 18216 --trusted-validator 5D1fNXzvv5NjV1ysLjirC4WY92RNsVH18vjmcszZd8on --trusted-validator 9jh8c14x3bfnzoMAYsgr2izfed8d3MgJ71ZpPpMdGeNJ --no-untrusted-rpc --entrypoint 35.203.170.30:8001 --dynamic-port-range 8001-8010 --gossip-port 8001 --rpc-port 8899 --identity $SOLANA_ID_KEY --vote-account $SOLANA_VOTE_KEY --authorized-voter $SOLANA_VOTE_KEY --snapshot-interval-slots 0 --ledger /home/solana/ledger --limit-ledger-size --log -
solana.service: Main process exited, code=exited, status=139/n/a
solana.service: Failed with result 'exit-code'.
solana.service: Scheduled restart job, restart counter is at 1.
Stopped Solana Validator.
Started Solana Validator.
```

I'm confused about the timing of things because nodes went delinquent about 10min before this happened

**Comment by mvines** [comment]
Hmm, Reisen's running old code:
```
solana-validator 1.1.1 [channel=unknown commit=unknown]
```

Don't really want to debug more of his node until it's running https://github.com/solana-labs/solana/releases/tag/v1.1.3

**Comment by mvines** [comment]
enabling `RUST_BACKTRACE=1` would be nice though!

**Comment by jstarry** [comment]
Unable to reproduce so I'd say my hypothesis was definitely wrong. Maybe we can chalk this up to old code / old bug
