### ISSUE TITLE
Unable to connect to wss://devnet.solana.com

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#9526]
#### Problem
```
WebSocket connection to 'wss://devnet.solana.com/' failed: Error during WebSocket handshake: Unexpected response code: 405
```

tag @mvines

**Comment by mvines** [comment]
Fixed, https://github.com/solana-labs/cluster/blob/23c5ed8719f6c8078e678668aa81d9dcaa4a3b8b/bin/machine-setup.sh#L186-L187 was missing from devnet's config

**Comment by jstarry** [comment]
Thanks!
