### ISSUE TITLE
stake-account CLI does not correctly display deactivated stake accounts

### ISSUE THREAD

**Issue by danpaul000** [solana-labs/solana#9538]
#### Problem
`solana stake-account` shows a fully deactivated stake account as still being delegated to a particular vote account, along with a delegated balance.

Example:
```
$ solana stake-account BywQVRJ8ikyBjhHBq8kGLzqSb9LSDYQXJa7Qq4pyphPv
Total Stake: 5000 SOL
Credits Observed: 16717
Delegated Stake: 4999.99771712 SOL
Delegated Vote Account Address: CertusDeBmqN8ZawdkxK5kFGMwBXdudvWHYwtNgNhvLu
Stake activates starting from epoch: 1
Stake deactivates starting from epoch: 5
Stake Authority: so1a4fRBhJojPqeqo3PAymcmzqj1FbBCaRpiSCTimuk
Withdraw Authority: 8CUUMKYNGxdgYio5CLHRHyzMEhhVRMcqefgE6dLqnVRK
Lockup Timestamp: 1970-01-01T00:00:00Z (UnixTimestamp: 0)
Lockup Epoch: 0
Lockup Custodian: Mc5XB47H3DKJHym5RLa9mPzWv5snERsF3KNv5AauXK8
```

I would expect the following lines would show `Stake account is undelegated` like a new account, though I'm not sure what we should do with the Credits earned.
```
Credits Observed: 16717
Delegated Stake: 4999.99771712 SOL
Delegated Vote Account Address: CertusDeBmqN8ZawdkxK5kFGMwBXdudvWHYwtNgNhvLu
```

This deactivated stake does not appear in `solana validators` so I think it is just a CLI bug for `stake-account`

**Comment by danpaul000** [comment]
@t-nelson is this in your domain?

**Comment by t-nelson** [comment]
About to be :wink: 

Added it to the CLI UX project
