### ISSUE TITLE
TdS is dead / Invalid shred header on deserialize

### ISSUE THREAD

**Issue by leoluk** [solana-labs/solana#9586]
#### Problem

Sending out a bad block when we were leader at 9463733 possibly caused the cluster to die.

#### Proposed Solution

:shrug:

**Comment by vkomenda** [comment]
Possibly this assertion failed: https://github.com/solana-labs/solana/blob/d3dd9ec6e23293e2586414a3cc498580d014ec93/core/src/replay_stage.rs#L946.

BTW, why does the validator need to panic here instead of handling the inequality?

**Comment by vkomenda** [comment]
I'm not sure if the nodes did get panic. If they didn't, it might be due to some infinite looping because [`did_complete_bank`](https://github.com/solana-labs/solana/blob/d3dd9ec6e23293e2586414a3cc498580d014ec93/core/src/replay_stage.rs#L424) was `false` in the replay stage loop.

**Comment by mvines** [comment]
Some logs at https://drive.google.com/drive/folders/1c5b2bEibYl88Z4IdAX_tpBlh6SHRBLJc

I also saved the ledger and syslog from Asteroids at /home/sol/issue-9586

**Comment by leoluk** [comment]
```
thread '<unnamed>' panicked at 'attempt to subtract with overflow', ledger/src/shred.rs:301:13
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:77
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:59
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1052
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
```

**Comment by vkomenda** [comment]
@leoluk, only debug binaries will panic on arithmetic over/underflow.

**Comment by leoluk** [comment]
@vkomenda TIL, that makes sense. I've just renamed the ticket to its original name until we know the actual cause :)

**Comment by sakridge** [comment]
Last root on `71bhKKL`:
`[2020-04-19T12:10:53.853547873Z INFO  solana_metrics::metrics] datapoint: tower-vote latest=9495063i root=9463673i `

on
`[2020-04-19T12:10:53.853547873Z INFO  solana_metrics::metrics] datapoint: tower-vote latest=9495063i root=9463673i`

**Comment by sakridge** [comment]
Both nodes marked 9463733 as dead:

```
[2020-04-19T08:59:00.310839882Z WARN  solana_ledger::blockstore_processor] Ledger proof of history failed at slot: 9463733
[2020-04-19T08:59:00.310850111Z WARN  solana_core::replay_stage] Fatal replay error in slot: 9463733, err: InvalidBlock(InvalidEntryHash)
[2020-04-19T08:59:00.310864278Z ERROR solana_metrics::metrics] datapoint: replay-stage-mark_dead_slot error="error: InvalidBlock(InvalidEntryHash)" slot=9463733i
```
and seem to be continuing and voting fine afterwards.

**Comment by leoluk** [comment]
Local devnet validator that crashed (debug mode) running the same attack code: https://github.com/solana-labs/solana/files/4499963/three.log

**Comment by leoluk** [comment]
Can no longer reproduce the issue on my local testnet with #9588 applied.
