### ISSUE TITLE
Suppress Gossip Cross-Talk

### ISSUE THREAD

**Issue by brianlong** [solana-labs/solana#9587]
#### Problem
It is possible for a validator to run multiple nodes for different clusters (e.g. TdS + Mainnet-beta) from the same IP address. If the validators are not configured correctly, there is potential for cross-talk where messages for each cluster are merged into one big mess.

Like they said in Ghost Busters, "Don't cross the streams".
![Ghostbusters](https://user-images.githubusercontent.com/79186/79691612-eb34f400-821d-11ea-8ccc-ed8bb42800bc.jpg)

Here is an example as seen earlier today in my TdS logs. The same IP address is running two different validators (TdS + Mainnet-beta). There is a possible overlap on port 8000/8001.

```
IP Address        |Age(ms)| Node identifier                              |Gossip| TPU  |TPUfwd| TVU  |TVUfwd|Repair|ServeR|Storag| RPC  |PubSub|ShredVer
------------------+-------+----------------------------------------------+------+------+------+------+------+------+------+------+------+------+--------
122.11.202.58     |   987 | 5KZRD6hDCZd1dgM9rJLweFFRkHu3qAgBhHgQ96Wz1VSn | 8000 | 8004 | 8005 | 8002 | 8003 | 8007 | 8008 | none | 9001 | 9002 | 54252
122.11.202.58     |  9507 | BZBKHmW1DhBaAPojxWBQ26vGz42Y7MtNviFZWpc6nGLb | 8001 | 9913 | 9676 | 8882 | 9522 | 9302 | 8750 | none | none | none | 54208
```
Shred 54208 was Mainnet-beta and shred 54252 was TdS.

There were other cases where a validator was running more than one instance from the same IP address. In one case, it looked like the operator was running a validator + a spy:

```
IP Address        |Age(ms)| Node identifier                              |Gossip| TPU  |TPUfwd| TVU  |TVUfwd|Repair|ServeR|Storag| RPC  |PubSub|ShredVer
------------------+-------+----------------------------------------------+------+------+------+------+------+------+------+------+------+------+--------
121.141.1.60      |     2 | SFundNVpuWk89g211WKUZGkuu4BsKSp7PbnmRsPZLos  | 58013| 58015| 58016| 58014| 58012| 58018| 58011| none | none | none | 54208
121.141.1.60      | 8100721 | 123vij84ecQEKUvQ7gYMKxKwKF6PbYSzCzzURYA4xULY | 58021| none | none | none | none | none | none | none | none | none | 0
```

And in another case, it looked like the validator was running two separate TdS nodes:
```
IP Address        |Age(ms)| Node identifier                              |Gossip| TPU  |TPUfwd| TVU  |TVUfwd|Repair|ServeR|Storag| RPC  |PubSub|ShredVer
------------------+-------+----------------------------------------------+------+------+------+------+------+------+------+------+------+------+--------
152.32.185.183    |    15 | 7mmRxJNttYcJVNsJmiLjTHYmNDt32EpzUSgLDoBsTKKK | 8009 | 8012 | 8013 | 8010 | 8011 | 8015 | 8016 | none | 9999 | 10000| 54252
152.32.185.183    |   586 | 836riBS2E6qfxjnrTkQdzD1JkFAoQDyUjTmzi38Gg84w | 8000 | 8003 | 8004 | 8001 | 8002 | 8006 | 8007 | none | 8899 | 8900 | 54252
```

It does not appear to me that the two latter cases would cause a cross-talk problem. The first case seems to be the most problematic.

#### Proposed Solution
- Block ALL messages from an IP address when they are advertising more than one non-0 shred version. This might force the operator to become aware of the problem and fix their server configuration. The cases related to validator + spy or two validators on the same cluster will still be allowed.

**Comment by sakridge** [comment]
I think just more aggressive shred-version filtering might fix this.

**Comment by mvines** [comment]
I think https://github.com/solana-labs/solana/pull/9868 generally fixes this issue by causing nodes to not make gossip pull requests or send gossip pushes to nodes of differing shred version.   This code is deployed in 1.1.10 and will be in 1.0.22
