### ISSUE TITLE
multinode-demo/validator.sh: Remove IP address hard code

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#959]
This has already bite us once: 9688f8fb64c33b3ad34632ce7a4e6eb92915f674

In the short term we can just use `dig` to resolve the DNS name instead.  One small catch, need to confirm `dig` is available from the Snap environment and if not probably ship a copy of it (example: https://github.com/solana-labs/solana/commit/f0446c7e88198ebd2e219824192e20512ea96df1#diff-5fde7a6d86053f0e1d88c0a2a238941f)

**Comment by blackwatertepes** [comment]
This issue has already been addressed: https://github.com/solana-labs/solana/blob/master/multinode-demo/common.sh#L189

**Comment by mvines** [comment]
Almost, we still have this line: https://github.com/solana-labs/solana/blob/e2e569cb43c7a0db9203b7554f369c984f7389de/multinode-demo/common.sh#L177

I'm actually right in this code now so I can quickly do this too
