### ISSUE TITLE
Airdrop failure on isolated validator

### ISSUE THREAD

**Issue by rob-solana** [solana-labs/solana#962]
https://github.com/solana-labs/solana/blob/9688f8fb64c33b3ad34632ce7a4e6eb92915f674/src/bin/fullnode.rs#L93

When a validator starts up, airdrop balance queries are posted to the new validator instead of the leader.  if a validator is off the network or catching up, this check will assert() out...

**Comment by garious** [comment]
@rob-solana was this issue fixed with @pgarg66's timeout fix?

**Comment by rob-solana** [comment]
no, but I fixed this when I added --network last week
