### ISSUE TITLE
Better error message if no ledger data is available

### ISSUE THREAD

**Issue by leoluk** [solana-labs/solana#9631]
#### Problem

```
[2020-04-21T12:57:00.415919557Z ERROR solana_metrics::metrics] datapoint: panic program="validator" thread="blockstore_9" one=1i message="panicked at 'Shred with
                            slot: 0,
                            index: 0,
                            consumed: 3,
                            completed_indexes: [2],
                            index_meta data: Some(ShredIndex { index: {0, 1, 2} }),
                            must exist if shred index was included in a range: 0 2', ledger/src/blockstore.rs:2145:29" location="ledger/src/blockstore.rs:2145:29"
```

when running a validator with `--no-snapshot-fetch`, but no local snapshots or ledger state.

#### Proposed Solution

Intuitive error message

**Comment by migui3230** [comment]
I'll take this issue on! Should I just be adding a .expect() at the end of the unwrap() if that doesn't return a valid value?

**Comment by migui3230** [comment]
#23385

**Comment by kwsohn** [comment]
Hi, what's the status on this? I'd be happy to take this on

**Comment by steviez** [comment]
Thank you for the interest in contributing! The error that issue describes is a bit dated, and we actually just had https://github.com/solana-labs/solana/pull/24839 land that adds some extra color. From now on, if you have no ledger / snapshots (and `--no-snapshot-fetch`), you'll get the following error:
```
[... INFO  solana_ledger::blockstore_processor] processing ledger for slot 0...
thread 'main' panicked at 'Failed to process bank 0 from ledger. Did you forget to provide a snapshot?: InvalidBlock(Incomplete)', ledger/src/blockstore_processor.rs:1117:6
...
```
