### ISSUE TITLE
perf testnet isn't working as hard as it should

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#964]
As of ~1pm PST today, `bench-tps` doesn't seem to be sending as many transactions to the perf testnet has it had previously.   We're seeing a mean TPS of around 30k, whereas it was more around 150k yesterday.  The machine configuration is unchanged and there's nothing in the commit history recently that appears to scream "TPS / 3".

The bench tps barrier transaction confirmation time appears to be more around > 2 seconds now though, whereas it is usually sub one second.  So I'd start looking from there:
![image](https://user-images.githubusercontent.com/1281082/44061517-8f9e8542-9f0d-11e8-8126-c5be1dbc8a4e.png)

**Comment by garious** [comment]
@mvines, current state of affairs on this one?

**Comment by mvines** [comment]
Unclear as the master CD testnets are in a bit of trouble right now.  We can revisit hopefully in a week or so if/once we clear the infra issues and we are back to a stable master dashboard

**Comment by mvines** [comment]
Yeah I think this is still an issue.  This is from a master testnet with 3 clients, the barrier transaction time seems to be really hurting benching with more than 1 client running:
![image](https://user-images.githubusercontent.com/1281082/45186616-f242f600-b1e2-11e8-9b48-28e6b159fe7c.png)

**Comment by garious** [comment]
@rob-solana, can you assign this issue by Monday CoB?

**Comment by garious** [comment]
@sakridge maybe?

**Comment by rob-solana** [comment]
Until the cloud comes back, we don't have a way to reproduce. Big barrier times is a sure sign of client traffic throttling.  I wouldn't want to send anyone in there besides Mike and me, and we're already trying to:

1. make the software startup more sane, reproducible, trace-able
2. re-create with local environments

I'm working something similar that I've noticed with localnet-sanity, looks like airdrop failure, sometimes looks like an unexpected recv_from() return value.

**Comment by mvines** [comment]
Gonna close this as there's nothing actionable here.  If something new pops up, let's file a new issue
