### ISSUE TITLE
move dependencies commented for dalek update

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#9753]
#### Problem

In order to update to dalek 1.0.0-pre3, Move language dependencies were commented since it seems to use a different/incompatible version of dalek.

Specifically bench-tps librapay dependency and test in ci/test-stable.sh were commented.

#### Proposed Solution

Resolve the conflict and re-enable

**Comment by sakridge** [comment]
https://github.com/solana-labs/solana/pull/9733/commits/0d04e4db6fac442e3ac600aa57828f9d782b3d1c

**Comment by mvines** [comment]
Also f5aaf7ff2828cbfa90dd0913d579b447689288d1

**Comment by mvines** [comment]
And 063f616a193f5cd49ce854e61f43a9785563333d

**Comment by jackcmay** [comment]
Resolved by https://github.com/solana-labs/solana/pull/11183
