### ISSUE TITLE
Older Rust BPF is preventing the update of some dependencies in the main tree

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#9760]
#### Problem

Rust BPF is currently at v.1.39.0, needs to be at least v1.41.0 to allow for the upgrade of `generic-array` and the closing of https://github.com/solana-labs/solana/pull/9446#issuecomment-620392308

#### Proposed Solution

Update Rust BPF

**Comment by mvines** [comment]
Fixed
