### ISSUE TITLE
BPF syscall symbols are confusing

### ISSUE THREAD

**Issue by jackcmay** [solana-labs/solana#9769]
#### Problem

BPF syscall symbols service both Rust and C and different symbols are exported for each language which is not necessary and confusing

#### Proposed Solution

Consolidate the exported syscall symbols to a single exported symbol where possible.

For example, instead of exporting `sol_log` and `sol_log_` just export `sol_log_' and point all languages to it.

This is a breaking change for existing programs that require all pre-compiled programs to be rebuilt and should go into the first public release that supports programs.

**Comment by jackcmay** [comment]
@mvines 👀

**Comment by mvines** [comment]
ok if we're going to do this it needs to go into v1.1, and pretty quickly!

**Comment by jackcmay** [comment]
Yup, how quickly?

**Comment by mvines** [comment]
Next week or so doable?   Ideally we have some soak time on testnet before promoting to mainnet-beta at the end of May

**Comment by jackcmay** [comment]
Sounds good, I can get it in asap

**Comment by jackcmay** [comment]
https://github.com/solana-labs/solana/pull/9804
