### ISSUE TITLE
Mystery memory allocation failure triggered by bad CrdsValue

### ISSUE THREAD

**Issue by leoluk** [solana-labs/solana#9786]
#### Problem

The CrdsValue fuzzer crashed all other nodes in my testnet with this exact same error on all nodes:

     memory allocation of 879609302221970 bytes failed

Unfortunately, the log level during this run was INFO and I did not capture the payload that caused it. I ran the same fuzzer for two days straight with more logging and it never happened again. It might be how https://github.com/solana-labs/solana/issues/9700 reproduces on other nodes, but there's plenty of other suspect `Vec::with_capacity` calls in the code base.

Testnet layout:

A = Bootstrap validator (100% stake), bootstrap.log
B = Second validator (0% stake, but voting), two.log
C = Third validator (0% stake, voting, runs the fuzzer), three.log

The stacktrace of the thread that SIGABRT'd on A and B is identical and inconclusive, looks like the stack was clobbered somehow:

```
(gdb) bt
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007f294bd9dcf5 in __GI_abort () at abort.c:79
#2  0x0000559bc819ac57 in std::sys::unix::decode_error_kind () at src/libstd/sys/unix/mod.rs:102
#3  0x00007f25583db803 in ?? ()
#4  0x0000559bc818f68d in core::ptr::drop_in_place () at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/ptr/mod.rs:174
#5  core::ptr::drop_in_place () at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/ptr/mod.rs:174
#6  core::ptr::drop_in_place () at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/ptr/mod.rs:174
#7  core::ptr::drop_in_place () at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/ptr/mod.rs:174
#8  core::ptr::drop_in_place () at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/ptr/mod.rs:174
#9  core::ptr::drop_in_place () at /rustc/b8cedc00407a4c56a3bda1ed605c6fc166655447/src/libcore/ptr/mod.rs:174
#10 std::sys_common::util::dumb_print () at src/libstd/sys_common/util.rs:8
#11 std::alloc::default_alloc_error_hook () at src/libstd/alloc.rs:200
#12 0x0003200000000492 in ?? ()
#13 0x0000000000000001 in ?? ()
#14 0x0003200000000492 in ?? ()
#15 0x0000000000000001 in ?? ()
#16 0x0003200000000492 in ?? ()
#17 0x0000000000000058 in ?? ()
#18 0x0000000000000000 in ?? ()
```

This folder contains the exact binary that was used (with symbols), the coredumps of A and B, and logs: https://drive.google.com/drive/folders/1H9cqCSQcl3dXnW4E3P-rhMba9IJqvXjy?usp=sharing

#### Proposed Solution

TBD

**Comment by mvines** [comment]
@leoluk - did you have #9706 in your local build at the time?

**Comment by leoluk** [comment]
Nope, I did not.

**Comment by mvines** [comment]
If this reproduces on v1.1.8 please re-open.  For now I'll assume the sanitize improvements in v1.1.8 will catch this one
