### ISSUE TITLE
Add "top 20 account list” JSON RPC API

### ISSUE THREAD

**Issue by mvines** [solana-labs/solana#9811]
People want an easy way to find the 🐳 accounts by JSON RPC that return the addresses of the 20 accounts with the most lamports in them, regardless of account owner.

With https://github.com/solana-labs/solana/issues/9433, we could allow the user to filter by current account circulation as well.

**Comment by rajgokal** [comment]
PLEASE inform me early and often if this gets implemented

**Comment by mvines** [comment]
Best way to remain informed is to watch this github issue.   Note that this information is already fully available in other forms

**Comment by CriesofCarrots** [comment]
@mvines , on clusters with the Storage program turned on, this rpc just returns a list of storage `RewardsPool` accounts (those are initialized with lamports = u64::MAX). Thoughts on excluding `RewardsPool` accounts? Or maybe any account owned by the Storage program?

**Comment by mvines** [comment]
Gross.  Excluding `lamports  == u64::MAX` with the Storage program as the owner seems best for now
