### ISSUE TITLE
Can't set --lockup-epoch and --lockup-date in the same transaction

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#9828]
#### Problem

`solana stake-set-lockup` unnecessarily makes `--lockup-epoch`, `--lockup-date`, and `--new-custodian` mutually exclusive.

#### Proposed Solution

Allow any combination of those options in a single invocation.

@CriesofCarrots ?

**Comment by CriesofCarrots** [comment]
Ugh, unfortunate clap default. Let's get that fixed up!
