### ISSUE TITLE
RPC account subscription notifications are unreliable

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#9833]
#### Problem
Account notifications are lossy and inconsistent because subscriptions specify a specific confirmation level and will only be notified when the RPC pubsub service observes a slot at that confirmation level where the account has been modified.

This is lossy for a number of reasons: async races, votes that include more than one block, slow consensus / network partitions. The subscription flow is outlined below and should help with understanding why these reasons cause problems.

#### Proposed Changes
1. Track the latest slot that each subscription was notified on `last_notified_slot`
2. On bank updates, find the latest slot on the current fork that has reached the subscribed level of confirmations
3. Use the latest slot to check when the account was last modified
4. Notify and update `last_notified_slot`

---

##### Replay Stage
1. Decide to vote on a bank
2. Notify RPC subscription service with a reference to bank forks
3. Vote on the bank
4. Notify the block commitment aggregation service of the latest vote

##### RPC subscription service (async)
1. Check block commitment cache to check confirmations for slots on the latest fork
    - There seems to be a bug here: `ancestors` is a `HashMap` and so iteration is done in arbitrary order but we don't have logic to set the conf -> slot mapping to be the latest slot: https://github.com/solana-labs/solana/blob/master/core/src/rpc_subscriptions.rs#L149-L153 (this only affects subscriptions with `confirmations == 0 || confirmations == MAX`)
2. Map slot confirmations to each subscription's subscribed confirmation level (0 to Rooted)
3. Check each subscription to see if the subscribed entity has been modified **strictly** in the mapped slot
    - Note that the signature check is more lenient and returns true if the signature slot is <=  the mapped slot

##### Block commitment aggregation service (async)
1. Compute confirmations for slots on the latest fork
2. Update cache entry

**Comment by CriesofCarrots** [comment]
Nice, thanks for working on this!
One thing I've been pondering that could be included in a refactor in this area: we recently redefined `commitment:max` for RPC to mean the largest cluster-confirmed root (block rooted by supermajority of the cluster). Should this be the default max for pubsub notifications as well? How would we handle this option vis-a-vis the current Confirmations count parameter? (Separate param? Or maybe `max` is only assigned if `confirmations` isn't provided?)

**Comment by jstarry** [comment]
@CriesofCarrots ah yeah, great point!

What's the rationale behind RPC supporting `Max` and `Root`? Assuming it's an important distinction, maybe we should switch subscriptions from having confirmation counts to using `Commitment` as well.

Also, what will `Commitment` look like when optimistic confirmation lands? Right now, subscriptions can be subscribed to `1` confirmation which is basically optimistic confirmation and is pretty convenient and relatively fast (a more important quality for a pubsub api). Should we add `Optimistic` to `Commitment` now or wait for the consensus changes to be finished?

**Comment by mvines** [comment]
> @CriesofCarrots ah yeah, great point!
> 
> What's the rationale behind RPC supporting `Max` and `Root`? Assuming it's an important distinction, maybe we should switch subscriptions from having confirmation counts to using `Commitment` as well.

"root" is when your node makes a root.  "max" is the newest root that 2/3+ of the cluster have rooted on.  "max" will _never_ be rolled back, whereas perhaps your local node made a mistake and rooted a slot that nobody else agrees with -- that slot _might_ be rolled back (although also pretty unlikely).

Supporting commitment in subscriptions would be nice for sure.


> Also, what will `Commitment` look like when optimistic confirmation lands? Right now, subscriptions can be subscribed to `1` confirmation which is basically optimistic confirmation and is pretty convenient and relatively fast (a more important quality for a pubsub api). Should we add `Optimistic` to `Commitment` now or wait for the consensus changes to be finished?

Let's add it later, when it's ready.  We have room in the API to add it so no need to expose a knob that doesn't yet do anything
