### ISSUE TITLE
Can't tell what day the cluster thinks it is

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#9847]
#### Problem

The cluster calculates the date as a function of slots from genesis, and it uses that date to determine if a stake account is locked. If we want to set an unlock for something like "one day from now", there's no RPC endpoint to ask the cluster what it thinks "now" is.

#### Proposed Solution

Add `solana cluster-date` that returns the date and time from `sysvar::Clock.unix_timestamp` in the RFC3339 format.

**Comment by mvines** [comment]
Along the way, I think it would be nice if `solana block-time` (with no provided slot) just returned the block time of the most recently root slot.   That'll then nicely point out how we have two different sources of truth for elapsed wall clock time.
