### ISSUE TITLE
LastIdNotFound: ledger verify panic seen on testnet-sanity

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#985]
This error seen when validating the leader's ledger on testnet deploy:

`verify failed at entry[256], err: LastIdNotFound(3BzTic3PP7urawGXa4n8ATmc5y3ks4SnStJ7FYmz3zep)`

See buildkite build #1115 in testnet-deploy builds.

**Comment by mvines** [comment]
https://buildkite.com/solana-labs/testnet-sanity/builds/957#8ddecb0b-e8cc-4c81-8c51-30f8b5743175
