### ISSUE TITLE
RPC: Get recent blockhash fails on devnet

### ISSUE THREAD

**Issue by jstarry** [solana-labs/solana#9855]
#### Problem
```json
{"method":"getRecentBlockhash","jsonrpc":"2.0","params":[],"id":"c159a4fb-99a0-4c77-b251-edfc93e5d83a"}
```

Received the following error when fetching the recent blockhash from https://devnet.solana.com
```
Failed to update cluster Error: failed to get recent blockhash: Error: failed to get recent blockhash: Cluster largest_confirmed_root 5540360 does not exist on node. Node root: 5540392
```

#### Proposed Solution
TBD

tag @CriesofCarrots

**Comment by mvines** [comment]
devnet.solana.com has been getting stuck and making forward progress, pretty sure that's the root cause here.

**Comment by anoushk1234** [comment]
@mvines im having this issuse now on devnet
`Error: failed to get recent blockhash: TypeError: Network request failed`

**Comment by socr102** [comment]
POST https://api.devnet.solana.com/ net::ERR_FAILED
App.js:109 : error Error: failed to get recent blockhash: TypeError: Failed to fetch
