### ISSUE TITLE
Throttle tx processing to let validators catch up

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#986]
When the ledger height between the leader and average validator gets too far apart, start dropping transactions. To maximize the collection of transaction fees, the leader will want to drop as few transactions as possible.

This should be calculated from the voters that agree with the state of the leader. Any others may be falling behind maliciously. Using their votes would expose the leader to a DoS attack.

**Comment by aeyakovenko** [comment]
I think performance wise we would drop whole batches of packets, and not try to move individual transactions around.  You can sum up the fees in the packets and drop the worst or something simple like that.

**Comment by mvines** [comment]
Obsolete
