### ISSUE TITLE
Accounts hash verifier should verify vote hashes from trusted validators

### ISSUE THREAD

**Issue by sakridge** [solana-labs/solana#9864]
#### Problem

Potential security/correctness problems could be detected if validators in the trusted validator set generate different vote hashes for the same slot.

#### Proposed Solution

Accounts verifier service could look at the vote hashes for trusted validators and see if they match, and halt the validator if they don't.

**Comment by ryoqun** [comment]
@jeffwashington maybe, this could be useful addition in the (distant) future.. I'll let this closed for now, until your 1b work has done. :)
