### ISSUE TITLE
Explore if votes could jump the transaction network queue

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#988]
I think we can improve finality if the validators send their vote transactions to a different socket.  I am not sure it will reduce packet drops, but it will speed up when they are actually registered.

**Comment by garious** [comment]
This feature would also allow all leader/validator communication to happen on a private backplane, which could be used to improve finality time.

**Comment by pgarg66** [comment]
Done in this PR https://github.com/solana-labs/solana/pull/3861
