### ISSUE TITLE
GetConfirmedBlock MAX doesn’t allow the caller or user to select specific nodes that it should wait for along with the supermajority

### ISSUE THREAD

**Issue by aeyakovenko** [solana-labs/solana#9882]
#### Problem

User may not trust the computed supermajority.  GetConfirmedMAX doesn’t have an option to wait for the trusted validator set to confirm a block. 

#### Proposed Solution

Wait for the trusted validator along with 2/3 to confirm.

Tag: @CriesofCarrots

**Comment by abebeos** [comment]
Personally, I would require this in a usage scenario.

## Expected

- GetConfirmedMAX
- GetConfirmedTRUSTED
- GetConfirmedBOTH

**Comment by CriesofCarrots** [comment]
No plans to implement this. We can open a new issue if it seems like a priority in the future.

**Comment by abebeos** [comment]
@CriesofCarrots , just be aware that this issue processing looks very strange.

You need at minimum to explain why its is not relevant in context of security:

> User may not trust the computed supermajority.

Only then you can close this issue casually.

**Comment by t-nelson** [comment]
it's not relevant in the context of security because _none_ of RPC is verifiable from a client's perspective. so a malicious RPC node lying about the block and lying about the having seen any particular validator set commit to the block are no different
