### ISSUE TITLE
TdS died on 2020-05-08 12:09 UTC

### ISSUE THREAD

**Issue by leoluk** [solana-labs/solana#9938]
Tracking ticket for today's TdS Disassembly:

![image](https://user-images.githubusercontent.com/859697/81404934-f2716280-9136-11ea-8199-8bb5881bad59.png)

Upload your logs! You can use our logbin. Example if you run solana as a service:

 `TZ=UTC journalctl -u solana -o cat --utc --since '08:00' --until '14:30' | xz | curl --data-binary @- 'http://logbin.certus.one:8080/solana-github-9938/<your node ID>.log.xz'`

Logs will be available on http://logbin.certus.one:8080/Qui9iehu/solana-github-9938/

**Comment by mvines** [comment]
I'm seeing this unusual warn in a number of validator logs:
https://github.com/solana-labs/solana/blob/3442f36f8ae43890e9afbd0a9cd74a10d821c25c/ledger/src/blockstore.rs#L939-L944

**Comment by mvines** [comment]
All instances of this log look the same:
```
  Stored config: ErasureConfig {
        num_data: 4,
        num_coding: 4,
    }, new config: ErasureConfig {
        num_data: 1,
        num_coding: 1,
    }
```

**Comment by mvines** [comment]
So many shreds: `SELECT mean("num_shreds") AS "mean_num_shreds" FROM "tds"."autogen"."recv-window-insert-shreds" WHERE time > now() - 12h GROUP BY time(:interval:) FILL(null)`
![image](https://user-images.githubusercontent.com/1281082/81432701-43259300-9118-11ea-9ec1-ebdb38bd09ac.png)
cc: https://github.com/solana-labs/solana/blob/bab35022605623ce95ec3f9e9e6301fee48fe34a/core/src/window_service.rs#L383

**Comment by mvines** [comment]
`SELECT mean("count") AS "mean_count" FROM "tds"."autogen"."shred_fetch_stage-shred_count" WHERE time > now() - 12h GROUP BY time(:interval:) FILL(null)`:
![image](https://user-images.githubusercontent.com/1281082/81433400-571dc480-9119-11ea-8a15-ea83c0e9c909.png)
https://github.com/solana-labs/solana/blob/909321928cc070c0f97e421032cce3d41cb632a9/core/src/shred_fetch_stage.rs#L123

**Comment by mvines** [comment]
Traffic breakdown from all the nodes into Leo's: https://gist.github.com/leoluk/b3ebe234c2009d45f9bf88685eca5a63

```
13.114.129.93   - AkVMbJq8pqKEe87uFaxjmt35tX2cNhUJTJwv13iioHu7
95.216.189.140  - CV3F19YAhoW7DpfHQ5W9t2Zomb9h21NRi8k6hCA36Sk6
116.202.224.31  - GbtVg3D6bNFSjem21vrJBJTpUniwwEtmvs8mQkX5XS1V
178.63.94.21    - 2Pik6jn6yLQVi8jmwvZCibTygPWvhh3pXoGJrGT3eVGf
95.217.114.150  - 2ibbdJtxwzzzhK3zc7FR3cfea2ATHwCJ8ybcG7WzKtBd
195.201.160.171 - 9gmnbM2GUVXiTfCg1Pj3ZTJdqyKdS81kjBWwwnZbS4MR
95.217.59.238   - 2GAdxV8QafdRnkTwy9AuX8HvVcNME6JqK2yANaDunhXp
116.202.225.7   - 8oRw7qpj6XgLGXYCDuNoTMCqoJnDd6A8LTpNyqApSfkA
94.130.54.247   - AbF88hkkpZ28VaT3vYn4xu5CeNC8G6Dq9cc8ciRR4fY5
88.99.6.218     - BWiftESMUsve87rkjU7HsaA7fkiJRAbv3xZLQrmKZtnz
95.217.74.231   - H4Dgb3KyCuYWKT8yKtp8qbY49cvaqZcisa2GDnroFsv6
91.90.148.195   - 55nmQ8gdWpNW5tLPoBPsqDkLm1W24cmY5DbMMXZKSP8U
116.202.215.42  - 9oKrJ9iiEnCC7bewcRFbcdo4LKL2PhUEqcu8gH2eDbVM
122.11.202.58   - 5KZRD6hDCZd1dgM9rJLweFFRkHu3qAgBhHgQ96Wz1VSn
```

**Comment by sakridge** [comment]
[tv2.pdf](https://github.com/solana-labs/solana/files/4611192/tv2.pdf)

**Comment by mvines** [comment]
Nothing seems actionable here, closing
