### ISSUE TITLE
Runtime can charge readonly account transaction fee

### ISSUE THREAD

**Issue by garious** [solana-labs/solana#9946]
#### Problem

The runtime charges the first account a fee without checking if the transaction dictates that account is writable.
#### Proposed Solution

Reject transactions with no writable accounts before signature verification.

**Comment by sakridge** [comment]
In transaction sanitize we check for at least 1 writable signed account.

**Comment by garious** [comment]
Awesome, thanks! Then I'll repurpose this ticket for the client-side footgun in the Message library.
